### ISSUE TITLE
Selecting slices in PieCharts with multiple DataSets sometimes changes the color of the slice.

### ISSUE THREAD

**Issue by PhilJay** [PhilJay/MPAndroidChart#1]
Well, the title says it all.

**Comment by esfahanpayamak94** [comment]
اصفهان پیامک به عنوان فعال در زمینه [طراحی سایت در اصفهان](http://www.esfahanpayamak.com/webDesign) اهمیت این موضوع را به خوبی درک کرده و لذا از تکنولوژی های مدرن در طراحی های خود استفاده می نماید.
