### ISSUE TITLE
Y axis max value not displayed?

### ISSUE THREAD

**Issue by alexsullivan114** [PhilJay/MPAndroidChart#1003]
I'm creating a line graph (out of some dynamic data), and I need the y max value to be visible.

Currently, to attempt to achieve this, I'm setting the following values on my chart:

`
chart.getAxisLeft().setAxisMaxValue(200f);
chart.getAxisLeft().setAxisMinValue(0f);
chart.getXAxis().setAvoidFirstLastClipping(true);
chart.setData(lineData);
`

But the graph is displaying 180 instead of 200. Is there any way to force the last y axis label to be that max value?

**Comment by PhilJay** [comment]
Yes. This sould help you:

`setLabelCount(int count, boolean force)`: Sets the number of labels for the y-axis. Be aware that this number is not fixed (if force == false) and can only be approximated. If force is enabled (true), then the exact specified label-count is drawn - this can lead to uneven numbers on the axis.

**Comment by bhavikshah92** [comment]
Hello,

I am facing the same issue may be. I have set min an max value for both Y Axis but there are two problems I am facing.

1. One of the Y-Axix value is cutoff the lineChart, even if I have set the min and max value for it.
2. The Gridlines of Both YAxis are unaligned by their values. I mean LeftAxis Label say 2500 and RightAxis Label is also 2500 but the gridline are not aligned properly.

Below Is My Code:
ArrayList<Entry> eggs_collected_dataset = new ArrayList<Entry>();
ArrayList<Entry> feed_dataset = new ArrayList<Entry>();
String[] xAxis = new String[arr_Date.length];
for (int i = 0; i < arr_Date.length; i++) {
        eggs_collected_dataset.add(new Entry(Float.parseFloat(arr_Eggs[i]), i));
        feed_dataset.add(new Entry(Float.parseFloat(arr_Feed[i]), i));
         xAxis[i] = arr_Age[i]
}

ArrayList<LineDataSet> lines = new ArrayList<LineDataSet>();
LineDataSet dataset3 = new LineDataSet(eggs_collected_dataset, "Eggs Collected");
dataset3.setColor(Color.parseColor("#154eea"));
dataset3.setCircleColor(Color.parseColor("#154eea"));
dataset3.setLineWidth(4f);
lineChart.getAxisLeft().setAxisMaxValue(dataset3.getYMax());
lineChart.getAxisLeft().setAxisMinValue(dataset3.getYMin());
lines.add(dataset3);

LineDataSet dataset4 = new LineDataSet(feed_dataset, "Feed");
dataset4.setColor(Color.parseColor("#00f7ea"));
dataset4.setCircleColor(Color.parseColor("#00f7ea"));
dataset4.setLineWidth(4f);
lineChart.getAxisRight().setAxisMaxValue(dataset4.getYMax());
lineChart.getAxisRight().setAxisMinValue(dataset4.getYMin());
lines.add(dataset4);

 XAxis Axis = lineChart.getXAxis();
Axis.setPosition(XAxis.XAxisPosition.BOTTOM);
Axis.setTextSize(10f);
Axis.setTextColor(getApplicationContext().getResources().getColor(R.color.Black));
Axis.setTypeface(openSansRegular);
Axis.setAvoidFirstLastClipping(false);

lineChart.getAxisLeft().setTextSize(7f);
lineChart.getAxisLeft().setTypeface(openSansRegular);
lineChart.getAxisLeft().setTextColor(getApplicationContext().getResources().getColor(R.color.Black));
lineChart.getAxisLeft().setStartAtZero(true);

lineChart.getAxisRight().setTextSize(7f);
lineChart.getAxisRight().setTypeface(openSansRegular);
lineChart.getAxisRight().setTextColor(getApplicationContext().getResources().getColor(R.color.Black));
lineChart.getAxisRight().setStartAtZero(true);

lineChart.setData(new LineData(xAxis, lines));
lineChart.setDrawGridBackground(false);
lineChart.animateY(2000);
lineChart.postInvalidate();

![problem 1 cutting from top](https://cloud.githubusercontent.com/assets/12729601/19036151/9d388e76-898b-11e6-8342-6d3579837919.png)
![problem 2 unaligned gridlines](https://cloud.githubusercontent.com/assets/12729601/19036152/9d3a92e8-898b-11e6-8288-73d09cc56d42.png)

**Comment by saravananmnm** [comment]
You can check the below code working for the y axis values.

LineData data = new LineData(datas);
            data.setValueTextSize(7f);
            data.setValueTextColor(Color.DKGRAY);
            data.setValueFormatter(new MyvalueFormatter());

            float minValue = data.getYMin();
            float maxValue = data.getYMax();
            //Initial values for Y axis
            int extraSpace = (int) (maxValue / mYAxisNames.size());
            int yMax = (int) maxValue + (extraSpace < 1 ? 1 : extraSpace);
            int yMin = (int) minValue - 1;

            XAxis xAxis = mBinding.lineChart.getXAxis();
            xAxis.setEnabled(true);
            xAxis.setDrawLabels(true);
            xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
            xAxis.setTextSize(7f);
            xAxis.setGranularity(1f);
            xAxis.setGranularityEnabled(true);
            xAxis.setTextColor(Color.BLACK);
            xAxis.setDrawAxisLine(false);
            xAxis.setDrawGridLines(true);
            xAxis.setLabelCount(mXAxisNames.size());
            xAxis.setAxisMinimum(-1f);
            xAxis.setValueFormatter(new MyAxisValueFormatter(mXAxisNames));


            mBinding.lineChart.getAxisRight().setEnabled(false);
            YAxis yAxis = mBinding.lineChart.getAxisLeft();
            yAxis.setLabelCount(mYAxisNames.size(), false);
            yAxis.setTextColor(Color.BLACK);
            yAxis.setTextSize(7f);
            yAxis.setDrawGridLines(true);
            yAxis.setDrawLabels(true);
            yAxis.setGranularity(1f);
            yAxis.setGranularityEnabled(true);
            yAxis.setSpaceTop(5f);
            yAxis.setPosition(YAxis.YAxisLabelPosition.OUTSIDE_CHART);
            yAxis.setDrawZeroLine(false);
            yAxis.setAxisMinimum(-1f);
            yAxis.setDrawZeroLine(true);
            yAxis.setAxisMaximum(yMax);

**Comment by ajaydhadhal1111** [comment]
try this way
chart.getAxisLeft().setAxisMaximum(chart.getYMax()+1f);
