### ISSUE TITLE
Animate individual LineDataSet instances?

### ISSUE THREAD

**Issue by alexsullivan114** [PhilJay/MPAndroidChart#1004]
<img width="419" alt="screen shot 2015-09-03 at 6 12 59 pm" src="https://cloud.githubusercontent.com/assets/3952562/9672319/a1f9952e-5267-11e5-8170-78c6caba927e.png">
Hi again,

I have a graph that combines two line data sets - however, it's not done in a manner to really indicate two separate pieces of data - attached is an image to let you know what I mean.

The animation for the graph works great (just using chart.animateX(millis, easing), but I'd really like to animate the first blue line and then once its finished animate the second green line. Is this possible?

Alternatively, if I could change the style of one combined LineDataSet at some point that would presumably solve the problem. Though I doubt that's doable.

Thanks!

**Comment by PhilJay** [comment]
Currently not possible unfortunately.
