### ISSUE TITLE
Line Chart gradient

### ISSUE THREAD

**Issue by fengx123** [PhilJay/MPAndroidChart#1009]
I want to set gradient color below my line ,how can i do?

**Comment by PhilJay** [comment]
gradients are not yet supported

**Comment by fengx123** [comment]
By the way,thank you very much.I'm try to make it by using Canvas

**Comment by PhilJay** [comment]
Yes, of course it should not be too hard to get this!

**Comment by PhilJay** [comment]
http://www.polyglotprogramminginc.com/adding-gradients-to-android-graphs-with-mpandroidchart-and-decoview/

**Comment by justalearner** [comment]
Hi Phil, can i add a Paint under lineDataSet or array of colors? Please look at this[question?](http://stackoverflow.com/questions/35934743/how-to-fill-linedataset-in-mpandroidchart-with-lineargradiant-or-array-of-colors)

**Comment by ZkHaider** [comment]
Ah I remember Lance, we've met a few times.
