### ISSUE TITLE
MarketView not shown in HorizontalBarchart

### ISSUE THREAD

**Issue by nonla** [PhilJay/MPAndroidChart#1010]
Hello, Im implementing an android app using your amazing chart library. However, I have a small problem with the markerview. The refreshContent method doesnt get called when I click on the horizontal bar chart.

There is a question about this issue on Stackoverflow but have not been answered yet:
http://stackoverflow.com/questions/30319466/markerview-in-mpandroidchart

For the PieChart, I have not tried yet but as you stated in the below question:
http://stackoverflow.com/questions/30319159/mpandroidchart-piechart-is-not-showing-markerview

I think the HorizontalBarChart does support the Markerview.

Ps: The marketview that im using works fine for the LineChart

Thanks

**Comment by PhilJay** [comment]
As of today, `PieChart` and `HorizontalBarChart` do not support `MarkerView`. THis is high on my list and will probably be added soon in the future.
