### ISSUE TITLE
How to draw horizontal stacked bar chart?

### ISSUE THREAD

**Issue by naveen1389** [PhilJay/MPAndroidChart#1011]
Hi PhilJay,

Could you please suggest how to draw horizontal stacked bar chart.

**Comment by PhilJay** [comment]
It's just the same as a normal stacked barchart.

https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/StackedBarActivityNegative.java

**Comment by naveen1389** [comment]
Thank you PhilJay,

I have on more issue -

![values_not_clear](https://cloud.githubusercontent.com/assets/10599591/9713335/66770b08-556e-11e5-8137-e0c3e7a2a425.png)

In above image the women age distribution values are not fully visible. Even after zoom also not visible. So we can't find the second entry's  exact value

mChart.getAxisRight().setStartAtZero(true);

ArrayList<BarEntry> yValues = new ArrayList<BarEntry>();
        yValues.add(new BarEntry(new float[]{ 10, 10 }, 0));
        yValues.add(new BarEntry(new float[]{ 12, 13 }, 1));
        yValues.add(new BarEntry(new float[]{ 15, 15 }, 2));
        yValues.add(new BarEntry(new float[]{ 17, 17 }, 3));
        yValues.add(new BarEntry(new float[]{ 19, 20 }, 4));
        yValues.add(new BarEntry(new float[]{ 19, 19 }, 5));
        yValues.add(new BarEntry(new float[]{ 16, 16 }, 6));
        yValues.add(new BarEntry(new float[]{ 13, 14 }, 7));
        yValues.add(new BarEntry(new float[]{ 10, 11 }, 8));
        yValues.add(new BarEntry(new float[]{ 5, 6 }, 9));
        yValues.add(new BarEntry(new float[]{ 1, 2 }, 10));

**Comment by PhilJay** [comment]
That is because the axis in the example has a fixed limit:

```java
mChart.getAxisRight().setAxisMaxValue(25f);
mChart.getAxisRight().setAxisMinValue(-25f);
```

Remove it and it will work.

**Comment by naveen1389** [comment]
Thank you very much !

**Comment by tribitinfotech** [comment]
![capture](https://cloud.githubusercontent.com/assets/20172434/25268923/33722858-2698-11e7-959c-b38060aabf34.PNG)

I want this kind of bar for working hour in a day. how to get that. and need to display for week

**Comment by Rsl717** [comment]
I have the same issue. I want to have such bar  for working hours. How to get this?  And whether it is possible to put a filter there ? for filtering out monthly/weekly

![](https://cloud.githubusercontent.com/assets/20172434/25268923/33722858-2698-11e7-959c-b38060aabf34.PNG)

**Comment by nagendra25** [comment]
hello beother i want creat bar chart for below my json formate data in below i want Y axis as runtime and X axis as date please help me

{
    "ResponseCode": "200",
    "ResponseMessage": "Success",
    "ResponseData": [
        {
            "date": "2017-07-24",
            "distance": 23.045,
            "run_time": "01:02:50"
        },
        {
            "date": "2017-07-25",
            "distance": 14.561,
            "run_time": "01:36:18"
        },
        {
            "date": "2017-07-27",
            "distance": 19.666,
            "run_time": "02:33:21"
        },
        {
            "date": "2017-07-28",
            "distance": 18.691,
            "run_time": "03:17:02"
        },
        {
            "date": "2017-07-29",
            "distance": 0,
            "run_time": "00:00:00"
        }
    ],
    "DisplayMessage": null
}

**Comment by JKorsten** [comment]
![image](https://user-images.githubusercontent.com/29142585/35669925-0afe5e8e-0737-11e8-8fbc-a49e349de38a.png)

Yes this is what I would like to have as well.

**Comment by alex28lex** [comment]
@Rsl717  @tribitinfotech @JKorsten  Hello,did you find solution of your question?
