### ISSUE TITLE
Linechart: Limitlines behind data issue

### ISSUE THREAD

**Issue by kaiwalyakhasnis** [PhilJay/MPAndroidChart#1012]
I have setup a linechart along with markerview which we can see by pressing on Yvals and everything seems to be working fine. After that i added limitlines so in somecases i have limitline exactly overlapping with the chart, so i used

chart.getAxisLeft().setDrawLimitLinesBehindData(true);

and it did draw the line behind the view ,but it leads to issue that it disturbs the on touch event of Yval (those which are overlapping with chart view) and it leads to non consistent behavior for on touch of those Yvals?

**Comment by PhilJay** [comment]
Which issue exactly are you having? Based on the information you are providing I cannot do anything.
