### ISSUE TITLE
Line not starting from y-axis Combined Chart 

### ISSUE THREAD

**Issue by NilayDani010** [PhilJay/MPAndroidChart#1015]
![screenshot_2015-09-08-14-33-48](https://cloud.githubusercontent.com/assets/14176765/9730947/95e6f06e-5637-11e5-8c4a-5798725766d8.png)
This is the actual result i got when set data from 0 but its not starting from y-axis .

I want the below type graph .
![screenshot from 2015-09-08 14 41 00](https://cloud.githubusercontent.com/assets/14176765/9731008/07db7938-5638-11e5-8257-fbb7e4639445.png)
Can you please tell if it is possible or not .
Thanks for this amazing library (y)

**Comment by NilayDani010** [comment]
Why this Issue is closed without answering it?
Even you didn't specify Is it possible or not ??

**Comment by PhilJay** [comment]
Yes, the below type graph is possible. Use 1 `LineDataSet` and 1 `BarDataSet`.
