### ISSUE TITLE
ProGuard config

### ISSUE THREAD

**Issue by royale1223** [PhilJay/MPAndroidChart#1016]
The recommended proguard config is too generic.

    -keep class com.github.mikephil.charting.** { *; }

This line preserves the entire library. I think something more specific would be better.

**Comment by PhilJay** [comment]
The library is open source anyway. If you want you can just exclude the `animation.*` package that should do as well.

**Comment by royale1223** [comment]
I was thinking of the optimisations and size reduction that proguard
provides. Thanks.
