### ISSUE TITLE
PieChart : Cluttered labels when slices are small

### ISSUE THREAD

**Issue by royale1223** [PhilJay/MPAndroidChart#1017]
If the PieChart slices are small, the labels inside the slices get cluttered. It would be nice if there was ability to draw labels outside the with arrows to the respective slice when the slice is too small to display the label. 

I know this will be a lot of work, but will you consider it?

**Comment by PhilJay** [comment]
Currently I do not have the resources to do that, maybe I will add it in the future.

**Comment by RudolfHladik** [comment]
is there a way to draw labels outside of slice?

I saw some lines in your code like: 
`private PieDataSet.ValuePosition mXValuePosition = PieDataSet.ValuePosition.INSIDE_SLICE;
    private PieDataSet.ValuePosition mYValuePosition = PieDataSet.ValuePosition.INSIDE_SLICE;`

but I cant find the way to set it to OUTSIDE_SLICE

**Comment by Ori1N** [comment]
Not sure if it's still relevant, but using `pieDataSet.setXValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);` did the trick for me!

@RudolfHladik thank for the tip!
