### ISSUE TITLE
Ability to control the margin of the BarChart (Horizontal)

### ISSUE THREAD

**Issue by royale1223** [PhilJay/MPAndroidChart#1018]
In a horizontal bar chart, if the bar label is long and it is drawn outside the bar, the label tends to get clipped in bigger bars. It would be fixable if the distance from longest bar to the chart border could be controlled. Or maybe take the length of the label into consideration while drawing the chart? Either solution would be nice.

**Comment by PhilJay** [comment]
There is a way: https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-(YLabels)
