### ISSUE TITLE
MPAndroidChart multiple line data, with datasets having variable number of input points

### ISSUE THREAD

**Issue by rorlig** [PhilJay/MPAndroidChart#1020]
I am trying to plot baby weight vs CDC weight charts. I have percentile vs week mapping for CDC data (about 24 weeks). The baby data has just 2-3 points (and the number of points are variable).

How can I plot this using MPAndroidChart. I get this error...

java.lang.IllegalArgumentException: One or more of the DataSet Entry arrays are longer than the x-values array of this ChartData object.

I am not sure what the best way to do achieve this use case. I have a stackoverflow question open here 

http://stackoverflow.com/questions/32494735/mpchartandroid-multiple-line-data.

p.s. This is not a bug but a help wanted request. I cannot put label on this

**Comment by PhilJay** [comment]
All possible, but you need to make your x-values array at least as long as many values you have in your biggest dataset.

**Comment by esfahanpayamak94** [comment]
اصفهان پیامک به عنوان فعال در زمینه [طراحی سایت در اصفهان](http://www.esfahanpayamak.com/webDesign) اهمیت این موضوع را به خوبی درک کرده و لذا از تکنولوژی های مدرن در طراحی های خود استفاده می نماید.
