### ISSUE TITLE
LineChart lines get cut off at values of zero

### ISSUE THREAD

**Issue by dakotasanchez** [PhilJay/MPAndroidChart#1021]
![screen shot 2015-09-10 at 2 56 41 pm](https://cloud.githubusercontent.com/assets/6089474/9802053/39ad25ca-57cc-11e5-969d-ba95af65c84d.png)

As you can see it's pretty self explanatory. It looks like the renderer might be using the center of the line as the reference point for drawing, and drawing that on the x-axis for values of zero, cutting off the bottom half of the line.     
Just guessing. I'll step through the library later to see if I can find the reason.    
Is there a library method that could help me out here? setExtraOffsets() didn't do anything. If you're wondering what my formatting is:    

    YAxis leftAxis = chart.getAxisLeft();
    leftAxis.setDrawLabels(false);
    leftAxis.setPosition(YAxis.YAxisLabelPosition.INSIDE_CHART);
    leftAxis.setDrawGridLines(false);
    leftAxis.setDrawAxisLine(false);
    leftAxis.setStartAtZero(true);
    leftAxis.setLabelCount(5, false);
    
    XAxis xAxis = chart.getXAxis();
    xAxis.setDrawLabels(false);
    xAxis.setPosition(XAxis.XAxisPosition.TOP);
    xAxis.setDrawGridLines(false);
    xAxis.setDrawAxisLine(false);
    xAxis.setAvoidFirstLastClipping(true);
    
    chart.setExtraBottomOffset(20);
    chart.getAxisRight().setEnabled(false);
    chart.setDrawBorders(false);
    chart.animateY(500);
    chart.setTouchEnabled(false);
    chart.setPinchZoom(false);
    chart.setDescription("");
    chart.setDrawGridBackground(false);

**Comment by PhilJay** [comment]
You have `startAtZero(true)` in your code, which means that every value below zero will be cut off. In your case, values are not cut off but your line width is simply too high to be fully displayed. I suggest you either reduce your line width or let your axis start below zero.

**Comment by bhavin-chauhan** [comment]
@dakotasanchez  I am facing same issue. Please help me if you have solved it. https://github.com/PhilJay/MPAndroidChart/issues/971

Thanks,
Bhavin

**Comment by mikhailmelnik** [comment]
The reason for the line being clipped is here https://github.com/PhilJay/MPAndroidChart/blob/v3.1.0/MPChartLib/src/main/java/com/github/mikephil/charting/charts/BarLineChartBase.java#L233, the chart implementation clips canvas before rendered starts its job. Extras such as circles are not clipped so are displayed in full.

**Comment by wachidsusilo** [comment]
So, there is no solution for this issue?

**Comment by prabhatsdp** [comment]
> So, there is no solution for this issue?

@wachidsusilo I have downloaded the library and added it as a module in my code. There is a method `lineChart.setClipDataToContent(false)` available and it prevents the canvas from clipping the line at zero.
