### ISSUE TITLE
Showing wrong results

### ISSUE THREAD

**Issue by darkovski88** [PhilJay/MPAndroidChart#1023]
Hello,
I'm trying to use this library in a project but seems that im missing something because its showint me wrong results. 
Here is the values I add:
![4845505988263936](https://cloud.githubusercontent.com/assets/5860687/9811062/40bec43c-5875-11e5-9024-370b017387c8.png)
and here is what I get:
![untitled-1](https://cloud.githubusercontent.com/assets/5860687/9811159/b40f2e2c-5875-11e5-9535-e3d3d59dbc76.png)
Does anyone have an idea why is this happening?
Here is the code that I use:

mChart.setDescription("");
        mChart.setNoDataTextDescription(getString(R.string.chart_empty_text));
        mChart.setDragDecelerationFrictionCoef(0.9f);
        mChart.setDrawGridBackground(false);
        mChart.setHighlightPerDragEnabled(false);
        mChart.setBackgroundColor(Color.WHITE);

        //adding values to the chart
        setData(bills.getBills().size());
        Legend l = mChart.getLegend();
        l.setForm(Legend.LegendForm.CIRCLE);
        l.setTextSize(13f);
        l.setTypeface(gotham);
        l.setTextColor(getResources().getColor(R.color.light_blue));

        ArrayList<String> xVals = new ArrayList<String>();
        for (int i = 0; i < billTotals.size(); i++) {
            Date date = new Date();
            date.setTime(billTotals.get(i).getDate());
            xVals.add(new SimpleDateFormat("MMM").format(date).toLowerCase());
            Log.d(TAG, "xVals = " + i);
        }

        XAxis xAxis = mChart.getXAxis();
        xAxis.setTextSize(12f);
        xAxis.setValues(xVals);
        xAxis.setLabelsToSkip(0);
        xAxis.setTypeface(gotham);
        xAxis.setTextColor(getResources().getColor(R.color.light_blue));

        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setDrawAxisLine(false);

        YAxis leftAxis = mChart.getAxisLeft();
        leftAxis.setAxisMinValue((float) (min));
        leftAxis.setStartAtZero(false);
        leftAxis.setAxisMaxValue((float) (max));
        leftAxis.setTypeface(gotham);
        leftAxis.setValueFormatter(new MyValueFormatter());
        leftAxis.setTextSize(10f);
        leftAxis.setTextColor(getResources().getColor(R.color.light_blue));

        YAxis rightAxis = mChart.getAxisRight();
        rightAxis.setTextColor(Color.WHITE);
        rightAxis.setStartAtZero(false);
        rightAxis.setDrawGridLines(false);

        rightAxis.setAxisMinValue((float) (min));

//and the setData method
private void setData(int count) {
        ArrayList<LineDataSet> dataSets = new ArrayList<LineDataSet>();
        ArrayList<String> xVals = new ArrayList<String>();

        for (int i = 0; i < count; i++) {
            Date date = new Date();
            date.setTime(billTotals.get(i).getDate());
            xVals.add(new SimpleDateFormat("MMM").format(date).toLowerCase());
        }

        ArrayList<Entry> yVals1 = new ArrayList<Entry>();
        for (int i = 0; i < bills.getBills().size(); i++) {
            Bill bill = bills.getBills().get(i);
            Log.d(TAG, "BT1 your bill today " + bill.getTotal() + " " + contractDetails.getMobileOperator().getName());
            if (bill.getTotal() > max) {
                max = bill.getTotal().intValue();
            }
            if (bill.getTotal() < min) {
                min = bill.getTotal().intValue();
            }
            yVals1.add(new Entry(bill.getTotal().floatValue(), i));
            youCanPayVal += bill.getTotal();
        }

        LineDataSet set1 = new LineDataSet(yVals1, getString(R.string.your_bill_today));
        set1.setAxisDependency(YAxis.AxisDependency.LEFT);
        set1.setColor(getResources().getColor(R.color.orange));
        set1.setValueFormatter(new MyValueFormatter());
        set1.setDrawValues(false);
        set1.setCircleColor(getResources().getColor(R.color.orange));
        set1.setDrawCircleHole(true);
        set1.setLineWidth(3f);
        set1.setValueTypeface(gotham);
        set1.setValueTextSize(16f);
        set1.setCircleSize(6f);
        set1.setFillAlpha(65);
        set1.setFillColor(getResources().getColor(R.color.orange));
        set1.setCircleColorHole(Color.WHITE);

        ArrayList<Entry> yVals2 = new ArrayList<Entry>();

        for (int i = 0; i < count; i++) {
            Log.d(TAG, "BT1 your contractFit " + billTotals.get(i).getTotal() + " " + contractDetails.getMobileOperator().getName());
            yVals2.add(new Entry((float) billTotals.get(i).getTotal(), i));
            if (billTotals.get(i).getTotal() > max) {
                max = ((Double) billTotals.get(i).getTotal()).intValue();
            }

            if (billTotals.get(i).getTotal() < min) {
                min = ((Double) billTotals.get(i).getTotal()).intValue();
            }
            nowYouPay += billTotals.get(i).getTotal();
        }

        LineDataSet set2 = new LineDataSet(yVals2, getString(R.string.your_contractfit));
        set2.setValueTextSize(16f);
        set2.setValueTypeface(gotham);
        set2.setAxisDependency(YAxis.AxisDependency.RIGHT);
        set2.setColor(getResources().getColor(R.color.toolbar_text_blue));
        set2.setCircleColor(getResources().getColor(R.color.toolbar_text_blue));
        set2.setDrawCircleHole(true);
        set2.setDrawValues(false);
        set2.setLineWidth(3f);
        set2.setCircleSize(6f);
        set2.setFillAlpha(65);
        set2.setFillColor(getResources().getColor(R.color.toolbar_text_blue));
        set2.setCircleColorHole(Color.WHITE);

        dataSets.add(set2);
        dataSets.add(set1);

        // create a data object with the datasets
        LineData data = new LineData(xVals, dataSets);
        data.setValueTextColor(getResources().getColor(R.color.light_blue));
        data.setValueTextSize(14f);

        // set data
        mChart.setData(data);
        mChart.setGridBackgroundColor(Color.LTGRAY);

        mChart.setDoubleTapToZoomEnabled(false);
    }

Can someone help me fix this?
Thanks

**Comment by PhilJay** [comment]
I suggest you hard code the values and see if the plotted result is still wrong (which I doubt) and then look for an issue in your data model (your `Bill` object).

**Comment by darkovski88** [comment]
@PhilJay Im pretty sure about the results, and I think there is something else that is wrong here, that's why im opening this issue.
Here are the results, and I see they are not according to the graph

Bill today(orange line):

 bill today 49.83 
 bill today 40.29 
 bill today 39.01 
 bill today 42.8 
 bill today 38.46 
 bill today 42.01 
 ==================
your contractFit(blue line):

 contractFit 55.85766666666667 
 contractFit 47.907000000000004 
 contractFit 45.85 
 contractFit 44.99 
 contractFit 44.99 
 contractFit 50.5835
