### ISSUE TITLE
can anyone help me :(

### ISSUE THREAD

**Issue by huydv0109** [PhilJay/MPAndroidChart#1025]
I have to create this graph below, i have two question, can anyone help me:
- I dont know how to make gradient color below th line
- How to custom the last point (color, text size ...)
I used Linechart, thanks!
![graph](https://cloud.githubusercontent.com/assets/8905802/9836202/80f7dfae-5a3a-11e5-8f7f-4954304e1abf.png)

**Comment by PhilJay** [comment]
Gradient below lines is currently not possible, but you can fill the area below a line with a specific color using `setDrawFilled(true)` and `setFillColor(...)`.

Concerning the custom color of your last point: A solution could be to put this point into a separate `LineDataSet` and apply your custom styling.

**Comment by huydv0109** [comment]
thanks @PhilJay , two thing above solved, can you help me one more question?
How to custom values and labels in YAxis like 2000, 4000, 6000, 8000, 15000 ... and limit is 10000 above? Thanks again, have a nice day!
