### ISSUE TITLE
Cubic linechart filling bug

### ISSUE THREAD

**Issue by StefanFaulhaber** [PhilJay/MPAndroidChart#1031]
I created a simple linechart and everything worked perfectly (see bottom half of the attached image). But when I add foo.setDrawCubic(true); the filling isn't working anymore (see top half of the image). I included the circles to show that everything's the same except the cubic property.

Some older issues here suggest that this problem is fixed, but I experience this behavior in version 2.1.3 as well.

A minor issue I also noticed: the setLineWidth function works differently depending on the drawcubic property (see image, both are created with foo.setLineWidth(2f)).

![chart_problem](https://cloud.githubusercontent.com/assets/3966464/9876666/0b0b1796-5bb8-11e5-9ec6-6c4c2530925d.png)

**Comment by Gary111** [comment]
I can confirm it. This bug does really exist in the latest version of the library.

But, @StefanFaulhaber, you can workaround it by generating average values for the missing points. I mean if you have 100 points (List<String> xVals) by XAxis, so you should have 100 points (List<Entry> yVals) by YAxis. Obviously, this is wrong, but the generation of intermediate values the real way to avoid some of the bugs in the library.

**Comment by StefanFaulhaber** [comment]
Thanks for the answer @Gary111!

Interpolating values between "real" datapoints may be a fix for this problem, but as I add these unneeded values the curve gets messy and is not as smooth as it should be with the cubic property.

I will add the cubic property again when this bug gets fixed. Until then my users have to go with harsh edges it seems ¯\_(ツ)_/¯

**Comment by PhilJay** [comment]
Does this issue still persist since the latest commit I made?

**Comment by StefanFaulhaber** [comment]
Yes, it's still the same issue in v2.1.4 as of today (10.10.2015).

**Comment by PhilJay** [comment]
Did you only test the 2.1.4 release or dis you use the code from the latest commit?

**Comment by StefanFaulhaber** [comment]
I now tried it with the latest code (used the release before) and the bug is still there.

**Comment by PhilJay** [comment]
Okay, I'll look into it.

**Comment by octavianmiu** [comment]
I had the same problem, the bug exists. Anyway, the library is awesome, Phil did a tremendous job

**Comment by StefanFaulhaber** [comment]
Any progress on this?

It's the only thing I miss, other than that I have no complains.
Keep up the great work!

**Comment by sathishkumars92** [comment]
y u guys delaying in giving updated

**Comment by StefanFaulhaber** [comment]
This bug is known for over 5 months now.

The new features (like direct realm support) are nice but I'm going to bite the bullet and switch to another library. It'll pay off in the long run to have a well supported lib.

**Comment by PhilJay** [comment]
I have now tested this extensively using the cubic linechart from the example app. Unfortunately I am not able to reproduce the issue with different setup and data provided for the chart.

There have recently been changes to the line-renderer, so it is possible that this issue is resolved.
Can anyone confirm that this issue is still present in the latest release v2.2.4?
