### ISSUE TITLE
How to hide the label

### ISSUE THREAD

**Issue by wuzhenjiang** [PhilJay/MPAndroidChart#1032]
I do not How to hide the label . For example  "LineDataSet set = new LineDataSet(yVals, "label")"

**Comment by wuzhenjiang** [comment]
I don't want to show the label.

**Comment by PhilJay** [comment]
`set.setDrawValues(false)`
`set = new LineDataSet(yVals, "")`
`chart.getLegend().setEnabled(false)`

**Comment by wuzhenjiang** [comment]
Thank you ."chart.getLegend().setEnabled(false)" is right.

**Comment by yizuochengchi** [comment]
thanks!

**Comment by fuzailbyhaqi** [comment]
<img width="292" alt="Screenshot 2020-06-29 at 1 48 22 PM" src="https://user-images.githubusercontent.com/55941677/85990170-3c781580-ba0f-11ea-8e5c-9ce01106b2c1.png">
ABove titles gets cropped any way to fix it or is there any way we can hide
