### ISSUE TITLE
YAxis gridlines appear "squished" on first setData/invalidate

### ISSUE THREAD

**Issue by markljones** [PhilJay/MPAndroidChart#1033]
I have a `LineChart` subclass that takes care of setting a bunch of application default styles and settings, and all of that is working fine. But when I first call `setData` followed by `invalidate` my left YAxis gridlines appear flattened. Sometimes the issue is not so bad, but the chart appears to be missing gridlines for the upper portions of the chart.

If I refresh the data (it is coming from a remote API endpoint) and invalidate the chart again, the issue always goes away.

Granted, it seems like a bug, but there's always a chance I'm doing something that causes this undesirable behavior. I have tried removing the call to `setLabelCount` as it seems the most likely to cause something like this to manifest, but that doesn't help.

As far as settings... here's most of them. Let me know if I should post more. All of these settings occur in a method call from the constructor:
```
setScaleEnabled(false);
setTouchEnabled(false);
setAutoScaleMinMaxEnabled(true);
setViewPortOffsets(0, 0, 0, 0);
getAxisLeft().setPosition(YAxis.YAxisLabelPosition.INSIDE_CHART);
getAxisLeft().setYOffset(10);
getAxisLeft().setDrawGridLines(true);
getAxisLeft().setDrawAxisLine(false);
getAxisLeft().setGridColor(getResources().getColor(R.color.chart_gridline));
getAxisLeft().setTextColor(getResources().getColor(R.color.chart_gridline_label));
getAxisLeft().setStartAtZero(true);
getAxisLeft().setTypeface(Typeface.DEFAULT_BOLD);
getAxisLeft().setTextSize(12);
getAxisLeft().setLabelCount(4, false);
getAxisLeft().setValueFormatter(new SuffixValueFormatter());
getLegend().setEnabled(false);
```

First invalidate (two different but similar instances of the problem):
![weirdgridlines](https://cloud.githubusercontent.com/assets/2000791/9960811/2750a7d8-5e1d-11e5-8e38-d8d151fe28ff.png)

![weirdgridlines2](https://cloud.githubusercontent.com/assets/2000791/9960812/2751cc80-5e1d-11e5-8112-5a03b8c1b5db.png)

Second invalidate (correct):
![correctgridlines](https://cloud.githubusercontent.com/assets/2000791/9960814/2a99dd60-5e1d-11e5-99cc-33a4ad2d529d.png)

**Comment by PhilJay** [comment]
Hmmm, I will try to recreate the issue in my code. 

In the meantime, could you tell me what happens if you don't use this line: `setViewPortOffsets(0, 0, 0, 0);`

**Comment by markljones** [comment]
Removing `setViewPortOffsets(0, 0, 0, 0);` seems to help considerably with the gridlines -- at least at first glance I do not see the same behavior anymore.

**Comment by PhilJay** [comment]
Anything else messed up now?
Or is it all good now?
If so, try calling this method later (e.g. after setting data for the first time)

**Comment by markljones** [comment]
It does not appear that anything in terms of functionality is messed up without `setViewPortOffsets`.

Calling the method after `setData` results in a chart without 0 offsets -- `invalidate` needs to be called once more to have flush edges. (The chart is displayed inside of a CardView)

**Comment by PhilJay** [comment]
I'm not sure I understand. Is it all ok now? :-)

**Comment by markljones** [comment]
What I meant is that without `setViewPortOffsets` the intended visual design is not achieved, but the chart appears to function properly.

But for the purposes of achieving our design:
If I call `setViewPortOffsets(0, 0, 0, 0);` after `setData`, I must do `postInvalidate()` to ensure the correct behavior on small charts. This is OK, despite feeling somewhat awkward.

Larger charts (full screen) *still* have the problem even with `postInvalidate()`

**Comment by markljones** [comment]
I routed all reloads now through a `reloadChart` method and that seems to help with the larger charts, though the lines visibly jump upwards towards their correct places after the redraw.

```@Override
public void setData(LineData data) {
	super.setData(data);
	setViewPortOffsets(0, 0, 0, 0);
}

public void reloadChart() {
	//invalidate();
	postInvalidate();
}
```

**Comment by PhilJay** [comment]
Does this issue still exist in v2.2.5?

**Comment by markljones** [comment]
I will look into it this week. 💪
