### ISSUE TITLE
BarChart XAxisValueFormatter

### ISSUE THREAD

**Issue by vaishalshah** [PhilJay/MPAndroidChart#1037]
I want to modify XAxis value labels in barchart. but I am not seeing any method for setting valueformatter in BarChart.getXAxis(). There is no such method as setValueFormatter() in that. Please tell me how do I achieve that?

**Comment by PhilJay** [comment]
`xAxis.setValueFormatter(...)` is what you should use. It's in the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/XAxis-%28XLabels%29). If you don't see that method, update the library.
