### ISSUE TITLE
How do i set step size and remove texts?

### ISSUE THREAD

**Issue by jofor** [PhilJay/MPAndroidChart#1038]
Hi I have the following questions for ScatterChart.
Is it possible to set the step size for the y-axis values on the left side of the chart?

I have the values 0 - 100 and i want ScatterChart to show an increase of 10 instead of the currently computed 20.

Next thing is. How do I remove the vertical lines from the left/right sides? I wish only to show the horizontal lines that each step value should create out on the left side.

Finally, how do i hide the xVals text, description, and values above the scatter points from appearing on the chart?

Sorry for the many questions, but I could not find it in any of the examples.

**Comment by jofor** [comment]
I think I worked out all the details, except step size for the y-axis. So if possible could anyone point out how to change that for me?

**Comment by PhilJay** [comment]
Step size can not explicitly be set.

But there is a workaround:

First, set the range of your `YAxis` by calling `yAxis.setAxisMinValue(...)` and so on, and then set the label count according to your needs `yAxis.setLabelCount(..., true)`.

All can be found in the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-%28YLabels%29).
