### ISSUE TITLE
LineChart: how to display gradient below line

### ISSUE THREAD

**Issue by ludriv** [PhilJay/MPAndroidChart#104]
Hello Phil,
I want to draw gradient below line: line color with 1 or configurable alpha to line color 0 alpha. How can I do this?

**Comment by woutergoossens** [comment]
I want to do the same. Use a gradient below my line. How would this be possible

**Comment by jcgsxr** [comment]
This I did this by modifying the `drawFilledPath` method in the LineChartRenderer class like so:

```java
        Paint paint = new Paint();
        paint.setShader(new LinearGradient(0, 70, 0, c.getHeight() / 2, 0x80FFFFFF, 0x00FFFFFF, Shader.TileMode.CLAMP));

        c.save();
        c.clipPath(filledPath);

        int color = (fillAlpha << 24) | (fillColor & 0xffffff);
//        c.drawColor(color);
        c.drawPaint(paint);
        c.restore();
```

**Comment by danielvivek2006** [comment]
I did it simply by adding setDrawableFilled which takes drawable as parameter. In that drawable, i've added gradient shape and It worked for me

**Comment by delhmela** [comment]
I wanna draw this chart,so anyone help me how can I draw it? 
![ritm](https://user-images.githubusercontent.com/22794798/30688252-51b98512-9ec6-11e7-8e69-6a0dfdc81e04.jpg)

**Comment by arpitgarg** [comment]
@delhmela Did you got any way to do that.

**Comment by delhmela** [comment]
@arpitgarg yeap I used MPAndroidChart and changed MPAndroidChart's codes )

**Comment by NAT313** [comment]
@PhilJay  animations are laggy in api 19 but without animations the app with the chart is quiet fast by the way thanks man great library.
