### ISSUE TITLE
Problem with Barchart ,how to dragToRefruse

### ISSUE THREAD

**Issue by TimAimee** [PhilJay/MPAndroidChart#1040]
In my project,I have the problem,
I want to load the  data from the Internet and  add to the Barchart,when i srcoll  the chart to the position  one(left),It sounds like the pullToRefresh,but what i want to do is dragToRefresh;.
I have tried to  implements the OnGestureLister,and setOnChartGestureListener,Then  i receive the callback of onChartTranslate,so i can get the motion action and dX,dY,
but i still don't know how to do with the those values,I am not sure when to load the Internet data.
I will appreciate to you ,if you can help me ,

**Comment by PhilJay** [comment]
I dont really understand.
