### ISSUE TITLE
Drag marker view while zooming

### ISSUE THREAD

**Issue by forkch** [PhilJay/MPAndroidChart#1041]
I don't know if this is easily possible. 
But it would be very nice if the marker could be dragged over the graph even if the chart is currently zoomed in.

**Comment by PhilJay** [comment]
Disable dragging / panning the chart.

**Comment by sorter** [comment]
@PhilJay I have tried disabling dragging the chart with

`chart.setDragEnabled(false);`

However when this option is applied the graph no longer supports dragging the marker over the graph. Any advice would be appreciated.
