### ISSUE TITLE
how to draw smooth curves for LineChart?

### ISSUE THREAD

**Issue by byndhorizon** [PhilJay/MPAndroidChart#1043]
what is the setting API for drawing smooth curves?

**Comment by PhilJay** [comment]
`lineDataSet.setDrawCubic(boolean enabled)`

**Comment by byndhorizon** [comment]
good! Thanks.

**Comment by Robhutch616** [comment]
Hi There,

setDrawCubic cannot be resolved - I'm using v3.0.0-beta1 - Have you removed this functionality or renamed it ?

p.s. amazing work, very impressive

**Comment by vutana1** [comment]
Same issue here with v3.0.0-beta1.

**Comment by TR4Android** [comment]
In `3.0.0` you set the mode to your `LineDataSet` instead (you can also use `HORIZONTAL_BEZIER`):
```java
lineDataSet.setMode(LineDataSet.Mode.CUBIC_BEZIER);
```

**Comment by vutana1** [comment]
Thanks. It works!

**Comment by Edonfreiner** [comment]
Hey @TR4Android, @PhilJay for some reason this isn't working fore me, can you check out the issue here? https://stackoverflow.com/questions/45104391/mpandroidchart-making-curved-graphs

Thank you so much.

**Comment by basheerkohli** [comment]
enabling setDrawCubic makes my lines curvy, but start point of line is uneven ,you can see in the picture. Can it be rectified..More over how to skip the 0 values from the line [data.
![screenshot](https://user-images.githubusercontent.com/21100930/33655290-add8162a-da98-11e7-8d10-faac3a0457ba.jpg)
