### ISSUE TITLE
Limit lines labels custom font 

### ISSUE THREAD

**Issue by Szkodniq1** [PhilJay/MPAndroidChart#1044]
In my project I need to set custom font on limit line label. I thought it need to set custom typeface for axis on which limit line would be draw, so axis labels and label for limit line would be the same style. But it didn't work. Axis labels were customized but limit line label didn't change. I followed the source code and found that ie.: labels in YAxisRenderer in renderAxisLabels(Canvas c) method are set by line:

mAxisLabelPaint.setTypeface(mYAxis.getTypeface());

but in renderLimitLines(Canvas c) method few lines later label for limit line is not set with Typeface.

It would be nice if LimitLine class would implement settable parameter of Typeface type, so the labels in Limit lines would be fully customizable.

**Comment by PhilJay** [comment]
Good point, I just pushed the feature. It will be in the next release.
