### ISSUE TITLE
Remove the black Box around the Chart

### ISSUE THREAD

**Issue by sandeep-m** [PhilJay/MPAndroidChart#1047]
Thanks for the cool library. I want remove the black border of the chart how can I removed that??
I am working on that since 2 days but still not able to get rid of that. 

![horizontalchart](https://cloud.githubusercontent.com/assets/13413785/10156037/0ae19cd0-669a-11e5-95b5-d2fd1769676c.png)

**Comment by PhilJay** [comment]
`chart.setDrawBorders(false)`

**Comment by Talha-dev1980** [comment]
mLineChart.getAxisLeft().setDrawAxisLine(false); mLineChart.getAxisRight().setDrawAxisLine(false);

You can also check if this axis draw enabled or not by :

mLineChart.getAxisLeft().isDrawAxisLineEnabled(); mLineChart.getAxisRight().isDrawAxisLineEnabled();
