### ISSUE TITLE
set chart background  

### ISSUE THREAD

**Issue by mohabinventor** [PhilJay/MPAndroidChart#1048]
i cannot set background  color or drawable i tried set LineChart.setBackground but this way set area around chart not chart itself where data displayed 
thanx in advance!

**Comment by PhilJay** [comment]
You are talking about the grid-background
-  `setDrawGridBackground(boolean enabled)`: If enabled, the background rectangle behind the chart drawing-area will be drawn.
- `setGridBackgroundColor(int color)`: Sets the color the grid-background should be drawn with.

**Comment by mohabinventor** [comment]
yes,thanx

**Comment by vikramsphinx** [comment]
Can we set gradient drawable to Grid background?

**Comment by naorcho** [comment]
Did anyone manage to put a gradient on the Grid background?

**Comment by M4riko** [comment]
would need the same thing!

**Comment by libxzr** [comment]
> Can we set gradient drawable to Grid background?

Here's a workaround.

```kotlin
private fun LineChart.setGridBackgroundDrawable(drawable: Drawable) {
        background = object : Drawable() {
            override fun draw(canvas: Canvas) {
                val paint = Paint()
                // In case you want to change the color outside the content.
                // paint.setColor(xxx)
                canvas.drawRect(bounds, paint)
                drawable.bounds = contentRect.toRect()
                drawable.draw(canvas)
            }

            override fun setAlpha(alpha: Int) {
            }

            override fun setColorFilter(colorFilter: ColorFilter?) {
            }

            override fun getOpacity(): Int {
                return PixelFormat.TRANSLUCENT
            }

        }
    }
```

Simply use

```kotlin
lineChart.setGridBackgroundDrawable(getDrawable(R.drawable.gradient)!!)
```

![1](https://github.com/PhilJay/MPAndroidChart/assets/24606814/092f3fe2-d2a9-4566-8202-f43f8a0f2ea2)
