### ISSUE TITLE
PieChart disable click at all

### ISSUE THREAD

**Issue by azizimusa** [PhilJay/MPAndroidChart#1051]
I need to remove all click at all in PieChart. Right now, when I click on it, the slice is zooming, but I dont want that. I want to completely un-clickable at all. How do I achieve that? I look on wiki but cant find it, also I have tried many times but no go.

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart
