### ISSUE TITLE
Ability to style individual entries

### ISSUE THREAD

**Issue by Pitel** [PhilJay/MPAndroidChart#1057]
Imagine you want to show pings on server in bar chart, and you want to show timeouts as small bar with different color.

I didn't found a way to style individual `BarEntry`. Is it somehow possible?

**Comment by PhilJay** [comment]
If it's just the color you want to change, then yes, it's possible: https://github.com/PhilJay/MPAndroidChart/wiki/Setting-Colors

It's not very comfortable tough I admit that :-)

**Comment by Pitel** [comment]
But I don't want to set color for the whole `DataSet`, just for individual `BarEntry`.

**Comment by PhilJay** [comment]
Yes, you can

if you have 3 entries, you want the middle one red and the others green, set colors array [green red green]

**Comment by lidaamber** [comment]
@PhilJay hello, I have a question about styling individual entries in pie chart
I need to have `xValuePosition` and `yValuePosition`  `OUTSIDE_SLICE` for some entries and `INSIDE_SLICE` for others
I thought of having two datasets, but it's not possible to pass list of datasets to PieData constructor
Is there any solution for this? Thank you.
