### ISSUE TITLE
LineChart: hold line points and real-time value

### ISSUE THREAD

**Issue by ludriv** [PhilJay/MPAndroidChart#106]
Hi Phil,
Do you think you may develop this scenarii ?
When the user touches and drags his finger along the graph, it's select the value of the closest point.
It's just a suggestion :)

**Comment by MGaetan89** [comment]
How about this:
* If not zoomed, drag moves the selected value
* If zoomed:
  * Drag moves the chart
  * Long press then drag moves the selected value

**Comment by PhilJay** [comment]
Now available `chart.setHighlightPerDragEnabled(boolean enabled)`
