### ISSUE TITLE
Many Line chart in ScrollView Scrolling issue

### ISSUE THREAD

**Issue by pkb126** [PhilJay/MPAndroidChart#1063]
Hi,
I have four line chart in scroll view, And when i touch any line chart and scroll, Scroll View also Scrolling, So How to disable scroll view scrolling, when i scroll in line chart.

Reply will appreciate.

Thanks for a great library.

**Comment by PhilJay** [comment]
This is more a general Android question than one concerning this library.
Have a look at stackoverflow questions addressing the issue of handling touches in nested views and check out the `onInterceptTouch(...)` method.
