### ISSUE TITLE
PieChart onNothingSelected not firing when clicking outside of the chart

### ISSUE THREAD

**Issue by tudormarze** [PhilJay/MPAndroidChart#1066]
Hi,

Thanks for this awesome library you've made.

I'm trying to create a PieChart that has inside it some textviews that are changing values according to the highlighted slice. However, I've noticed that if a slice is selected and then the user clicks outside of the chart, it goes unselected without firing ```onNothingSelected``` from a ```OnChartValueSelectedListener``` (I want to display back the default texts).

Would it be possible to fire ```onNothingSelected``` also in this case? 

Thanks a lot,
Tudor

**Comment by elenabratanova** [comment]
I've also encountered the same problem.

**Comment by tudormarze** [comment]
I found a workaround for this by setting both an ```OnChartValueSelectedListener``` and an ```OnTouchListener``` that is fired with a minimal delay after the other one. Still, it would be nicer if this would be something default.

```
pieChart.setOnTouchListener(new View.OnTouchListener() {
    @Override
    public boolean onTouch(View v, MotionEvent event) {
        if(event.getAction() == MotionEvent.ACTION_UP) {
            new Handler().postDelayed(new Runnable() {
                @Override
                public void run() {
                    if (pieChart.getHighlighted() == null) {
                        //DO YOUR STUFF
                    }
                }
            }, 20);
        }
        return false;
    }
}); 
```

**Comment by elenabratanova** [comment]
@tudormarze thank you!

**Comment by elenabratanova** [comment]
@PhilJay  thanks!
I was wondering, when are you planning to tag v2.1.5?

**Comment by PhilJay** [comment]
in a couple of days probably!
