### ISSUE TITLE
Maximum values in a line chart graph

### ISSUE THREAD

**Issue by forum6691** [PhilJay/MPAndroidChart#1067]
It seems that the maximum values that a serie can support is 65335 values due to the type INT used to define the X index.

Can you confirm that point ?

**Comment by PhilJay** [comment]
No, I cannot. http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html#MAX_VALUE

**Comment by forum6691** [comment]
OK thank you Philjay. Effectively, I muddle up with langage C++.
So The series can contain a lot of values :)
