### ISSUE TITLE
make LimitLine visible in y-axis range if its value higher than max value in y axis 

### ISSUE THREAD

**Issue by mohabinventor** [PhilJay/MPAndroidChart#1068]
i am using LimitLine lineChart to set goal , i cannot make it visible when its value higher than max value in y-axis  . How achieve that ?
i tried setAutoScaleMinMaxEnabled() it does not work 
thanx for your awesome work .
thanx in advance !

**Comment by PhilJay** [comment]
Change the range of your yaxis: https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-%28YLabels%29

**Comment by mohabinventor** [comment]
thanx
