### ISSUE TITLE
How to dynamic change markerview when scroll chart but not only click markerview show

### ISSUE THREAD

**Issue by hugoGuo** [PhilJay/MPAndroidChart#1069]

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart

`OnChartGestureListener`

**Comment by hugoGuo** [comment]
if i want close the markerview when my finger leave the screen.how should i do this.

**Comment by hugoGuo** [comment]
Thanku,when the markerview in start and end it cant show all.how should i fix this ?
