### ISSUE TITLE
How to know if MarkerView shows/disappears

### ISSUE THREAD

**Issue by dirkam** [PhilJay/MPAndroidChart#1070]
Is there any way to run code when MarkerView shows and disappears? I didn't find any callbacks regarding this.
Do you happen to have any idea for a workaround?

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart

`OnChartValueSelectedListener`

**Comment by dirkam** [comment]
Thanks!
