### ISSUE TITLE
need some suggestions

### ISSUE THREAD

**Issue by codepython** [PhilJay/MPAndroidChart#1073]
hi:
   I want to draw stock market real time data chart ,which is called "K chart" ,it is showed with several small bars,and the start point of y is not 0 normally . I find the 'stacked bar chart' in this lib is similar with my needed chart , but I can not start with it . 
Could my chart be drawn by this library ? if ok, please give some suggestions to me .

thanks

**Comment by PhilJay** [comment]
Yes, take a look at the example: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/StackedBarActivity.java
