### ISSUE TITLE
Awkward Zoom

### ISSUE THREAD

**Issue by bkerensa** [PhilJay/MPAndroidChart#1075]
![photo_2015-10-05_23-40-24](https://cloud.githubusercontent.com/assets/859175/10301782/9602c652-6bba-11e5-81d0-ecd9a76f0089.jpg)

Is there a way to disable zooming or make is more user friendly? Right now to get back to 100% view (normal) user has to pinch vertical then horizontal a few times. This might not be evident to user.

Also some dates get pushed off screen can we lock it to a size?

Our project: http://github.com/Glucosio/android

**Comment by PhilJay** [comment]
To avoid the dates from being pushed off:
 - make them shorter
 - call `xAxis.setAvoidFirstLastClipping(true)`

Concerning the zooming:
 - call `chart.setPinchZoom(true)`

More information in the wiki: https://github.com/PhilJay/MPAndroidChart/wiki

**Comment by PhilJay** [comment]
Of course you can also disable zoom :-)

**Comment by PaoloRotolo** [comment]
Thanks you @PhilJay! Awesome library BTW.
