### ISSUE TITLE
Custom shape for bar chart.

### ISSUE THREAD

**Issue by rahul-padmakumar** [PhilJay/MPAndroidChart#1077]
Need to change the shape of bar chart and add a indicator for the highest bar in y axis.

**Comment by PhilJay** [comment]
Subclass `BarChartRenderer` and then call `chart.setRenderer(new MyCustomBarChartRenderer(...))`

**Comment by rahul-padmakumar** [comment]
Thanks PhilJay.

**Comment by PhilJay** [comment]
You may also have to call `chart.invalidate()` after setting the new renderer.

**Comment by rahulpadmakumar** [comment]
Is it possible to set a custom indicator for highlighted bar graph. I need
to set the indicator on the y axis.

**Comment by PhilJay** [comment]
````java
You can change the alpha (transparency) by calling `barDataSet.setHighLightAlpha(...)`

/**
     * Set the alpha value (transparency) that is used for drawing the highlight
     * indicator bar. min = 0 (fully transparent), max = 255 (fully opaque)
     * 
     * @param alpha
     */
    public void setHighLightAlpha(int alpha) {
        mHighLightAlpha = alpha;
    }
```java

**Comment by montecillodavidacn** [comment]
Hi @PhilJay  Is it possible to create my own renderer that allows rounded rect?

**Comment by syndarin** [comment]
@rahul-padmakumar check my answer here https://stackoverflow.com/questions/53369115/mpandroidchart-change-shape-of-bar-chart/55392212#55392212. Although this solution sacrifices bar shadows.
