### ISSUE TITLE
How to make Bar chart legend look exactly like the Pie chart one

### ISSUE THREAD

**Issue by otamate** [PhilJay/MPAndroidChart#1080]
I see the colored indicators with the associated text in the pie chart and have set it to appear to the left of the chart. I do the same in the bar chart but just get the colored boxes with no text and running always horizontally where I'd like it to look the same, i.e. verticaly.
![device-2015-10-06-215300](https://cloud.githubusercontent.com/assets/658447/10322279/f34327de-6c74-11e5-9234-337a39b02ebd.jpg)

**Comment by PhilJay** [comment]
`legend.setPosition(...)`

https://github.com/PhilJay/MPAndroidChart/wiki/Legend

**Comment by otamate** [comment]
I can set the position to the left but not the orientation - its always horizontal.
