### ISSUE TITLE
setPinchZoom is not working in Combined chart 

### ISSUE THREAD

**Issue by NilayDani010** [PhilJay/MPAndroidChart#1082]
While Using combined chart mchart.setPinchZoom(false); 
is not working , Chart zoom in and out is still accessible through gesture on the graph.

**Comment by PhilJay** [comment]
Read the documentation: https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart

Disabling pinch-zoom does not disable zooming in general. It just disables pinch-zooming.
