### ISSUE TITLE
RadarChart update data

### ISSUE THREAD

**Issue by gnardini** [PhilJay/MPAndroidChart#1087]
Hi! I'm using this library in my app and found an issue. Maybe I'm not taking something into account, so I'm asking.

I have a RadarChart which holds data that can change. So id the data changes i call the method *setData* with the updated data followed by *notifyDataSetChanged*. This works in many phones, but not on my Moto G3 running on Lollipop. Any ideas why? Am I missing something?

Thanks a lot, and great library! It's been super useful! :)

**Comment by PhilJay** [comment]
What does "it doesn't work" mean?
What happens? What does not happen? What is the issue?

**Comment by gnardini** [comment]
Thanks for the quick response! 

I'm sorry I wasn't more descriptive, by "doesn't work" I meant that the data isn't updated with the new one but the old one remains visible.

**Comment by PhilJay** [comment]
Try calling `invalidate()` after setting the data. That should redraw the `View`.

**Comment by gnardini** [comment]
Thanks a lot  for your help, worked like a charm! ;)

**Comment by Vikramsinh** [comment]
superb chart library ..!! Great work by you ..!! Thank you so much
