### ISSUE TITLE
How remove extra spaces beyond Y-axis ?

### ISSUE THREAD

**Issue by mohabinventor** [PhilJay/MPAndroidChart#1089]
i get this bug "extra spaces beyond y-Axis"  when change large data-set values (i.g random input  = 1000000) with small data-set values (i.g input = 10) as shown in screenshots 
i tried re-size chart width to MATCH_PARENT after changing data-sets  but does not work .

large data-set 
![device-2015-10-09-075847](https://cloud.githubusercontent.com/assets/11734125/10386948/e2fc193c-6e5c-11e5-896e-eb020543fd2b.png)

small data-set displayed after large data-set in the same chart make this extra spaces 
![device-2015-10-09-075910](https://cloud.githubusercontent.com/assets/11734125/10386964/08d11004-6e5d-11e5-8995-6241d4aac71c.png)

thanx in advance !

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport

**Comment by mohabinventor** [comment]
i tried fitScreen() but does not work ! 
what is the right answer ?

**Comment by PhilJay** [comment]
`setViewPortOffsets(0,0,0,0)`

**Comment by mohabinventor** [comment]
what does offset mean ?using above line make chart fill screen and y-axis labels does not appear i have to change it to 80 instead of 0 .. but i do not know what this value mean and if   every device or screen should have specific value or not ?
thanx in advance
