### ISSUE TITLE
Recommendation: add Right slide loading the functional data 

### ISSUE THREAD

**Issue by 120660021** [PhilJay/MPAndroidChart#109]
Hello, PhilJay, I hope you're  LineChart, plus the right slide to load data function, namely: Listener right sliding  add data .
Similar to the following:

![qq 20140923141209](https://cloud.githubusercontent.com/assets/8433054/4368225/98ea7320-42e8-11e4-8318-57363934926a.jpg)

**Comment by e-tverdokhleb** [comment]
Hi, so is than issue was resolved? )

**Comment by almic** [comment]
@e-tverdokhleb You should be able to use a combination of the `chart.setOnChartGestureListener(this)` in you activity and checking the currently visible range with `chart.getHighestVisibleX()` in `onChartGestureEnd()` to see if it matches the highest X value in your data. If it does, then load some more points.

**Comment by e-tverdokhleb** [comment]
> @e-tverdokhleb You should be able to use a combination of the `chart.setOnChartGestureListener(this)` in you activity and checking the currently visible range with `chart.getHighestVisibleX()` in `onChartGestureEnd()` to see if it matches the highest X value in your data. If it does, then load some more points.

Thank You for answer, actually i've tried  to implement this feature in onChartTranslate with chart.viewPortHandler ))

**Comment by almic** [comment]
@e-tverdokhleb thanks for pointing that out to me! I don't have the luxury of browsing every single issue, so I just look at them whenever a comment is added or referenced.

Did you figure it out with the information I provided at least?

**Comment by EvanZch** [comment]
Is there a good solution to this problem？

**Comment by e-tverdokhleb** [comment]
Hi) 
I totally dont remember about this topic )))
