### ISSUE TITLE
Linechart tooltips

### ISSUE THREAD

**Issue by Pho3niX90** [PhilJay/MPAndroidChart#1090]
Hi.

I have a basic linechart with 2 datasets that update dynamically/automatically. 

I want to display tooltips to the users when they click on a datapoint, currently it just displays a crosshair through the data point but for the life of me I cannot find 1 tutorial for this.

I have viewed the playstore version as saw 1 chart that has this, but uses a single dataset, the one with 2 datasets do no do this, so was wondering if this is a limitation?

**Comment by PhilJay** [comment]
No, this is not a limitation.
https://github.com/PhilJay/MPAndroidChart/wiki/MarkerView

**Comment by Pho3niX90** [comment]
@PhilJay Thank you, I knew it as tooltips. 
On a side note without opening a separate ticket. Is it possible to add an image to the grid? I tried setting them but they appear  at the back of the grid as a background instead inside the grid? Or setting a image as a grids background?

Thanks in advance, and brilliant work !

**Comment by heyou93** [comment]
Hi where can i find the marker image? I cannot find it on the example source code (drawable folder) the one on the google play app (check screenshot:)

![12970516_1696270683959348_401438395_o](https://cloud.githubusercontent.com/assets/8090574/14425926/9b29e226-001d-11e6-9949-bf5ed1b89bf7.png)

**Comment by heyou93** [comment]
Nevemind, i already found it on drawable-nodpi
