### ISSUE TITLE
PieChart.animateY after doing setRotationAngle give a weird animation

### ISSUE THREAD

**Issue by alexbeville** [PhilJay/MPAndroidChart#1091]
Hi,

Before all, thanks you for this library that's help a lot of Android developers.

I would like to share something interesting that happens with animateY on a PieChart : 

`chart = (PieChart) findViewById(R.id.chart);
chart.setRotationAngle(270);
....
chart.animateY(1500, Easing.EasingOption.EaseInOutQuad);`

The animation's starting point isn't from the angle 270 but it's starting from 0 and reaches the angle 270 during the animation.

Any possibility to fix this ? If we configure a rotation angle, then the angle that must be reached must be equal to this rotation angle.

**Comment by PhilJay** [comment]
I'm not sure if this is a bug. Take a look at this: http://stackoverflow.com/questions/25929820/how-to-calculate-position-on-a-circle-with-a-certain-angle/25929952#25929952

The if you set the rotation-angle to 0°, the chart will start animating from the furthest EAST point. If you set the rotation angle to 270°, the chart will start animating from the top (NORTH).

**Comment by alexbeville** [comment]
Are you sure of this ? I tried, and the animation always begin at East point. Event on your app demo, if you rotate the PieChart with your fingers, and then go to the menu button "Animate Y", you will see that the animation begin at East, and finish on North point.

**Comment by DavidPizarro** [comment]
I have this problem too! Any solution??

**Comment by alexbeville** [comment]
I am still waiting for an answer from the developer ...

**Comment by MrLoveQD** [comment]
me too :-(
Please help me.

**Comment by pickeyboy** [comment]
I referred PieChartRenderer.class for one of my project with similar Donut chart draw and faced the same problem. Regarding animation my requirement was only animateY(),  for which I solved this problem by the following change in protected void drawDataSet(Canvas c, IPieDataSet dataSet) method in PieChartRederer.java


            // draw only if the value is greater than zero
            if ((Math.abs(e.getVal()) > 0.000001)) {

                mRenderPaint.setColor(dataSet.getColor(j));
                mBitmapCanvas.drawArc(mChart.getCircleBox(),
                        (angle + sliceSpace / 2f),
                        (newangle - sliceSpace / 2f) * mAnimator.getPhaseY(),
                        true, mRenderPaint);
            }
            angle += newangle * mAnimator.getPhaseY();


Note: This is case specific changes suits to requirement and may not be generalised.  I hope this will help solving yours.

**Comment by PhilJay** [comment]
Are you using the latest version v2.2.0?

**Comment by pickeyboy** [comment]
Hi Philipp, 

I am not using the library, I referred part of your code to implement a view and yes it is latest one. I faced the same problem mentioned by @alexbeville. i.e. when initial angle of the Pie chart is set to 270 the view is drawn correctly but Animation always starts from angle 0. 

I modified the code as in my previous code and the problem was resolved.

**Comment by PhilJay** [comment]
Okay, I just tested in the latest version with different starting angles, and it all looked fine.
Also see 403b40d573ea2b627f9c9d099883726b0672d011

**Comment by pickeyboy** [comment]
It works like a gem. :)
