### ISSUE TITLE
Force YAxis to use int and not decimal values

### ISSUE THREAD

**Issue by jtz3r0** [PhilJay/MPAndroidChart#1094]
So I've seen this question a few times but I didn't see an answer that works for me.  So the values of the YAxis are chosen for us as best fits (as far as I can tell).  Ways of controlling this seem to be setLabelCount, but it's still not enough control.  The answer always seems to be use value formatter, but that won't fix my issue.

Lets say the plot on my line chart is Y = 3, but the Y-Axis is using labels in floats of 1.2, 2.6, 3.4, etc.  If I were to use a formatter 1.2 becomes 1, 2.6 becomes 3, 3.4 becomes 3.  Now not only am I faced with two 3's on the Y-Axis, but my data plot of Y= 3 is in between these two 3 labels even though its value is actually 3.

How can I fix this?

**Comment by PhilJay** [comment]
Read the documentation: https://github.com/PhilJay/MPAndroidChart/wiki/The-YAxisValueFormatter-interface

**Comment by jtz3r0** [comment]
I'm already using YAxisValueFormatter, but it still doesn't fix the issue not unless you can change the position of where the label and its corresponding line is going to be drawn.  2.2 will be formatted to 2, but the bar which has a value of 2 will not go up to the line because it's value is not 2.2.

**Comment by jtz3r0** [comment]
Nvm, I found my answer here http://stackoverflow.com/questions/28753540/force-barchart-y-axis-labels-to-be-integers I have the exact same problem, and I'm guessing its still not supported.

I'm trying to modify mEntries but it doesn't seem promising.  mEntries seems to get populated after you setData if you modify it afterwards it'll already have been drawn so it's useless.  If you try to set it before setData, it'll just get overwritten.

**Comment by joshfriend** [comment]
I wrote a utility method to compute the Y Axis max and label count for the desired amount of axis labels (6 in my case):

```java
public static void configureChartYAxisLabels(BarLineChartBase chart, YAxis.AxisDependency axisDependency) {
    YAxis yAxis = chart.getAxis(axisDependency);

    // Minimum section is 0.25, could be 1.0f for only integer values
    float labelInterval = 0.25f / 2f;

    int sections;
    do {
        labelInterval *= 2;
        sections = ((int) Math.ceil(chart.getYMax() / labelInterval));
    } while (sections > 6);

    // If the ymax lies on one of the top interval, add another one for some spacing
    if (chart.getYMax() == sections * labelInterval) {
        sections++;
    }

    yAxis.setAxisMaxValue(labelInterval * sections);
    yAxis.setLabelCount(sections + 1, true);
}
```

**Comment by jtz3r0** [comment]
Thanks will give this a shot when I get the chance

**Comment by bilalahmadj110** [comment]
> Thanks will give this a shot when I get the chance
