### ISSUE TITLE
LimitLine not included if height far from graph data

### ISSUE THREAD

**Issue by xorgate** [PhilJay/MPAndroidChart#1095]
Suppose my graph data varies between 80 and 100.

I add a LimitLine with limit 500.
The graph is drawn but the limitline is so far off, it is not drawn.

Can I somehow force the graph to include the limitline in its vertical scale/positioning algo?

Otherwise, it would be nice to have :)

**Comment by PhilJay** [comment]
Just change the range of the YAxis: https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-%28YLabels%29
