### ISSUE TITLE
Changing of color from the default 'Black' color.

### ISSUE THREAD

**Issue by Abhinab01** [PhilJay/MPAndroidChart#1096]
Hi Phil,
This Library is Awesome! It helped me save a lot of time...!
Meanwhile, Im facing some problem in changing the default color of the numbers/ texts in the Axis (L/R/T/B), as it is set to Black by default but I cannot find a way to change it to white or so for a darker background.  I went through the Wiki but couldn't find a way to change that, Am I missing something? It'll be great if you can help me out... Thank You :) :+1:

**Comment by PhilJay** [comment]
`axis.setTextColor(...)`

**Comment by Abhinab01** [comment]
Thanks a lot Phillip,
I hope you don't mind me asking another small little query.... On
zooming-in in the graph, the values in the Y-Axis split up, I mean a
particular value in the Y-Axis remain same for different values of
X-Axis.... Is there a way to dynamically calculate/show the values in the
Y-Axis corresponding to the X-Axis values?
Thank You. :)
