### ISSUE TITLE
PieChart strange behaviour on slice selection

### ISSUE THREAD

**Issue by HOTwheel** [PhilJay/MPAndroidChart#1097]
Hi, I want to use MPAndroidCharts' PieChart for a small project and started implementing a simple test.
I kept it simple with static data etc. and tried to be as close to the official example as possible.

Problem: When a slice is selected, the slice with the next higher value disappears (only the text remains). Additionally, the slice with the highest value does not expand. I have this problem with 2.1.4 and 2.1.5, don't know about previous versions.

My Android version is 5.0.2. I compiled the MPChartExample too, there the PieCharts works fine. But I can't see any difference besides data generation in my code.

In the following screenshot, the 20%-slice has been selected, the 30% disappears.
![ss](https://cloud.githubusercontent.com/assets/1815069/10428890/d2256f9c-70f4-11e5-848e-b67c71b5e9bd.png)

My code:

```java
    private void createPieChart()
    {
        mChart = (PieChart) findViewById(R.id.pieChart);

        mChart.setUsePercentValues(true);
        mChart.setDescription("");
        mChart.setExtraOffsets(5, 10, 5, 5);
        mChart.setDragDecelerationFrictionCoef(0.95f);
        mChart.setDrawHoleEnabled(true);
        mChart.setHoleColorTransparent(true);
        mChart.setTransparentCircleColor(Color.WHITE);
        mChart.setTransparentCircleAlpha(110);
        mChart.setHoleRadius(58f);
        mChart.setTransparentCircleRadius(61f);
        mChart.setDrawCenterText(true);
        mChart.setRotationAngle(0);
        mChart.setRotationEnabled(true);

        ArrayList<Entry> pieces = new ArrayList<Entry>();
        pieces.add(new Entry(40, 1));
        pieces.add(new Entry(30, 2));
        pieces.add(new Entry(20, 3));
        pieces.add(new Entry(10, 4));

        ArrayList<String> piecesDesc = new ArrayList<String>();
        piecesDesc.add("40 prozent");
        piecesDesc.add("30 prozent");
        piecesDesc.add("20 prozent");
        piecesDesc.add("10 prozent");

        PieDataSet dataSet = new PieDataSet(pieces, "Poll results");
        dataSet.setSliceSpace(2f);
        dataSet.setSelectionShift(5f);

        ArrayList<Integer> colors = new ArrayList<Integer>();

        for (int c : ColorTemplate.VORDIPLOM_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.JOYFUL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.COLORFUL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.LIBERTY_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.PASTEL_COLORS)
            colors.add(c);

        colors.add(ColorTemplate.getHoloBlue());

        dataSet.setColors(colors);

        PieData data = new PieData(piecesDesc, dataSet);
        data.setValueFormatter(new PercentFormatter());
        data.setValueTextSize(11f);
        data.setValueTextColor(Color.WHITE);
        mChart.setData(data);

        data.setValueFormatter(new PercentFormatter());
        data.setValueTextSize(11f);
        data.setValueTextColor(Color.WHITE);

        Legend l = mChart.getLegend();
        l.setPosition(Legend.LegendPosition.RIGHT_OF_CHART);
        l.setYEntrySpace(0f);
        l.setYOffset(0f);

        mChart.highlightValues(null);
        mChart.invalidate();
        mChart.animateY(1400, Easing.EasingOption.EaseInOutQuad);
    }
'''

**Comment by PhilJay** [comment]
Does this error always occur? Or just in very specific situations?

I have hade some reports about this issue, but I have not been able to reproduce it so far.
I tested various Android versions and devices.

Which device are you using?

**Comment by HOTwheel** [comment]
This error does always occur for me, I couldn't get the selection to work correctly. I am using an LG G2, I can test it on a Nexus 4 this evening too.

**Comment by PhilJay** [comment]
Thanks!
Yes would be awesome if you could test the nexus 4!
I got one myself on which this bug does not occur.

**Comment by HOTwheel** [comment]
The same on Nexus 4 (5.1.1) and in the Emulator. Must have to do something with the project configuration. Trying to switch Target SDK....

**Comment by PhilJay** [comment]
I'll copy your code and try to reproduce, thanks for testing

**Comment by PhilJay** [comment]
What about hardware acceleration?
Do you have it enabled or disabled? Did you make any changes to hardware acceleration in your project?

**Comment by HOTwheel** [comment]
Happens with android:hardwareAccelerated set to true and false, no difference. I have created a new, minimalistic project which has the same behaviour. You can download it here:

https://dl.dropboxusercontent.com/u/3946758/TestPieChart.zip

**Comment by PhilJay** [comment]
Found the issue. It's in your setup :-)
Your x-index for the entries starts at 1 - but it should start at zero.

I will think of something to prevent this from happening :-)

````java
ArrayList<Entry> pieces = new ArrayList<Entry>();
        pieces.add(new Entry(40, 0));
````

**Comment by HOTwheel** [comment]
OMG, what a stupid mistake... Programmers should always start to count at zero :D

Thank you!

**Comment by Gumarelo** [comment]
@PhilJay thanks!! I had the same mistake that @HOTwheel and with your solution, everything has worked like a charm
