### ISSUE TITLE
Clockwise PieChart

### ISSUE THREAD

**Issue by botondbutuza** [PhilJay/MPAndroidChart#1098]
Is there a setting somewhere to change the direction of the pie charts? Currently it defaults to counter-clockwise, which is peculiar.

My use case is that I show a "completeness" chart, with two values - the actual measured value, and the value that is missing - so one colour is blue for instance, indicating completeness, and the other part of the chart is grey, and I can't seem to find anything that would flip the chart's direction from counter-clockwise to clockwise.

Thanks!

**Comment by PhilJay** [comment]
Can't you just turn around the way ou add items?

**Comment by botondbutuza** [comment]
I am an idiot.

Yes, that worked. Thanks!
