### ISSUE TITLE
Different line styles

### ISSUE THREAD

**Issue by onyame** [PhilJay/MPAndroidChart#11]
It would be great, if you could support different line styles such as dashed or dotted lines for the LineChart.

**Comment by WaliaAditya** [comment]
hey @PhilJay  thanks for the wonderful library its been real help.
I'll be thankful if you can help me through this.
Actually i was using this library and i wanted to make some of the xaxis grid line to be dashed line is their any functionality for that?? i don't want all of the xaxis grid lines to be dashed.
thanks in advance.

**Comment by channae** [comment]
@WaliaAditya Hi, Im looking for the same behaviour. Were you able to achieve this?
