### ISSUE TITLE
LineChart fill rendering not working for API < 18

### ISSUE THREAD

**Issue by MarcSalvat** [PhilJay/MPAndroidChart#1100]
Just checked with the emulator, https://github.com/PhilJay/MPAndroidChart/pull/1064 by @tinsukE works fine for Android API 18 and higher but not for lower versions.

It may be related to canvas clipPath not working for hardware accelerated views in API 11-17. Maybe disable hardware acceleration for those or find another way to also solve the "Path too large to be rendered" problem.

**Comment by PhilJay** [comment]
The chart actually allows to programmatically enable/disable hardware-acceleration:

`chart.setHardwareAccelerationEnabled(boolean enabled)`

**Comment by MarcSalvat** [comment]
Yeah but it's hard to find out that filling is not working only for devices running api < 18. I saw it because I'm always running an older emulator version for testing.

**Comment by JumpMaster** [comment]
Noticed the same issue on JellyBean (18) but not on ICS (14/15).  Best to set it for all devices prior to KitKat just in case though.

    if (android.os.Build.VERSION.SDK_INT < Build.VERSION_CODES.KITKAT)
    {
        chart.setHardwareAccelerationEnabled(false);
    }
