### ISSUE TITLE
Cannot disable LineChart's YAxis (LeftAxis) drawline

### ISSUE THREAD

**Issue by stellarowl12** [PhilJay/MPAndroidChart#1101]
For some weird reason, when I disable the YAxis (both left and right) BUT enable the XAxis (bottom), the left axis is still drawn...

When both YAxis AND XAxis are disabled, then the Left YAxis is NOT drawn (just like I want).

I've even tried enabling the YAxis and changing the color to transparent and the width to 0f, but none of my workarounds have worked.

Please help, has anyone else seen this issue before?

**Comment by PhilJay** [comment]
Try calling `setDrawBorders(boolean enabled)`

**Comment by VijayLakhnotra** [comment]
how to apply 
setDrawBorders(boolean enabled)
