### ISSUE TITLE
X axis grid line differences are not dynamic. Need to add min and max value for x-axis

### ISSUE THREAD

**Issue by CrazyAndroidGuy** [PhilJay/MPAndroidChart#1102]
![screenshot](https://cloud.githubusercontent.com/assets/10461730/10447941/7fc247ea-71a6-11e5-95bb-1c54f348d8c2.jpg)

I have implemented a graph based on two ArrayList (X-Axis: Cop%, Y-Axis- Speed) as mentioned on above image.
I have rounded up minimum and maximum values for Y-axis range. But in X-axis my cop% values are set. And difference between my X-axis values (Cop%) are not uniform. It is like this {0,3,6,9,12,15,18,21,24,26,28,30,32,48,64,80,96,97,98,99,100). But the differences for each vertical grid lines are same. Which should not be. 
See my image where X-axis value 30-32 and 32-48. Space between grid lines are same for both these two different ranges.
I want to set a min and max range of 0..100 for X-axis within that my values will be set like we do in paper graph.

Please check my attached screenshot. How can i achieve this??? Please help. If needed i will post my full source code.

**Comment by PhilJay** [comment]
Add as many empty `""` x-values entries as you need, and adjust your x-index accordingly.

**Comment by CrazyAndroidGuy** [comment]
Can you please elaborate? This is how i am adding X and Y values coming from static Arraylist

if (data != null) {
            set = data.getDataSetByIndex(0);

            if (set == null) {
                set = createSet();
                data.addDataSet(set);
            }
            data.addXValue(MY_X_VALUE);
            data.addEntry(new Entry(Float.parseFloat(MY_Y_VALUE), set.getEntryCount()), 0);

            mChart.notifyDataSetChanged();
            mChart.setVisibleXRange(12, 0);
            mChart.moveViewToX(0);
//            mChart.setVisibleXRangeMaximum(20);
            mChart.animateXY(5000, 500);
        }
