### ISSUE TITLE
NPE from BarLineChartBase#getMarkerPosition

### ISSUE THREAD

**Issue by szhou1234** [PhilJay/MPAndroidChart#1105]
For inline comments of class Highlight.java of v2.1.4, members mStackIndex and mRange will only be valid for stacked bar chart. Thus for normal bar chart (non-stacked), mRange should be null and we shouldn't access any internal variable from it. However, in BarLineChartBase#getMarkerPosition, we try to access Range.to, regardless whether it's stacked bar entry:
                    xPos = highlight.getRange().to;
                    yPos = highlight.getRange().to;

Is this a bug?

**Comment by szhou1234** [comment]
We may need to check whether the entry is stacked, as we do in BarChartRenderer#drawHighlighted.

**Comment by PhilJay** [comment]
Thanks for mentioning, but there actually is a check for that:

````java
if (entry.getVals() != null) {
    xPos = highlight.getRange().to;
}
````

**Comment by pedrofmvcmartins** [comment]
I'm still getting crashes with null on this, my case is when I have a Stacked bar but only one stack there. So entry.getVals() != null is true but highlight.getRange() is null
