### ISSUE TITLE
Showing of precise values of the divisions in the Y-Axis...

### ISSUE THREAD

**Issue by Abhinab01** [PhilJay/MPAndroidChart#1107]
In my Activity I have set leftAxis.setAxisMaxValue(10.00f); && leftAxis.setAxisMinValue(0.00f); But on Zooming in, The Values get split up rather than showing the Decimal values... e.g on zooming in, near the number 4 on the Y-Axis, it splits up in multiple numbers of 4. What I want is, it should show the decimal points i.e 4.25, 4.50 etc rather than showing the number 4 multiple times!
Is there a method/way to do that? Any kind of Help is highly appreciated. Thank You :)

**Comment by PhilJay** [comment]
It looks like you are not drawing decimals. Use `YAxisValueFormatter` and set the number of decimals you want to draw.
