### ISSUE TITLE
Line Graph

### ISSUE THREAD

**Issue by pkb126** [PhilJay/MPAndroidChart#1111]
Hi, Can we draw Line graph like below image, Yaxis with only two value 0 and 1, 0 have bottom space as per image

![linechartdemo](https://cloud.githubusercontent.com/assets/10512037/10514577/321595a2-736c-11e5-8ddf-5bde99d7eca3.png)

**Comment by PhilJay** [comment]
Yes, you can.
https://github.com/PhilJay/MPAndroidChart/wiki/The-YAxisValueFormatter-interface

```java
if(value == 1 || value == 0) return value;
else return "";
```
