### ISSUE TITLE
Wrong Percentage calculation on PIE chart

### ISSUE THREAD

**Issue by khushwaqt** [PhilJay/MPAndroidChart#1112]
Hi, 
Thank for such a library. 
I am facing an issue with PIE chart. 
I get wrongly calculated pie chart. 
I have two values Data Remaining and Total Data 
I have 6144 MB of total data and 3365 MB of remaining data, so the percentage should be 54% Used and 46 % remaining. But the PIE chart shows as 35% used and 64% remaining. 
Here is my code. 
public void generateChartDataUsage(String totalVolume, String userVolume) {    

mPieChartData.setUsePercentValues(true);
		mPieChartData.setHoleColor(Color.rgb(235, 235, 235));
		mPieChartData.setHoleColorTransparent(true);
		mPieChartData.setCenterTextTypeface(mFont);
		mPieChartData.setHoleRadius(0f);
		mPieChartData.setDescription("");
		mPieChartData.setDrawCenterText(true);
		mPieChartData.setDrawHoleEnabled(false);
		mPieChartData.setRotationAngle(0);
		mPieChartData.setRotationEnabled(true);
		mPieChartData.setCenterText(totalVolume+" MB");
		mPieChartData.setCenterTextSize(20);
		mPieChartData.setCenterTextColor(Color.parseColor("#02438b"));
		mPieChartData.setCenterTextTypeface(mFont);
		mPieChartData.animateXY(1500, 1500);
		setChartDataUsage(Integer.parseInt(totalVolume),Integer.parseInt(userVolume));
		Legend l = mPieChartData.getLegend();
		l.setEnabled(false);
}
private void setChartDataUsage(int totalVolume, int usedVolume) {

		ArrayList<Entry> yVals1 = new ArrayList<Entry>();
		yVals1.add(new Entry(totalVolume,1));
		yVals1.add(new Entry(usedVolume,2));

		ArrayList<String> xVals = new ArrayList<String>();
		xVals.add("% Remaining");
		xVals.add("% Used");
		PieDataSet dataSet = new PieDataSet(yVals1, "");
		dataSet.setSliceSpace(3f);

		ArrayList<Integer> colors = new ArrayList<Integer>();
		colors.add(Color.parseColor("#63d957"));//green 72e866 52c447
		colors.add(Color.parseColor("#ed5653"));//red f46d6d
		dataSet.setColors(colors);

		PieData data = new PieData(xVals, dataSet);
		data.setValueFormatter(new PercentFormatter());
		data.setValueTextSize(11f);
		data.setValueTextColor(Color.parseColor("#FFFFFF"));
		data.setValueTypeface(mFont);
		mPieChartData.setData(data);

		// undo all highlights
		mPieChartData.highlightValues(null);
		mPieChartData.invalidate();
	}

**Comment by PhilJay** [comment]
Start your Entries at index 0, not 1:
`yVals1.add(new Entry(totalVolume,0));`

**Comment by khushwaqt** [comment]
Its still the same. No effect on graph

**Comment by PhilJay** [comment]
Are you sure your calculated values are correct?
Could you try without variables and just "6144"

**Comment by khushwaqt** [comment]
Yes, I am sure. I have checked at every point by debugging the app. And I just hard coded the values as 
yVals1.add(new Entry(6144,0));
yVals1.add(new Entry(3365,1));
but chart is still the same.

**Comment by PhilJay** [comment]
Okay, I did the math:
````java
6144 + 3365 = 9509 = 100%
6144 / 9509 = 0,646 = ~64,6 %
3365 / 9509 = 0,353 = ~35,3 %
````

Meaning the chart is correct.

**Comment by khushwaqt** [comment]
Yeah !!! 
I am so dumb. 
Thanks for time and  help.  
Really appreciate it.
