### ISSUE TITLE
Fragment on Linechart problem

### ISSUE THREAD

**Issue by sanghan4029** [PhilJay/MPAndroidChart#1115]
![image](https://cloud.githubusercontent.com/assets/15139896/10534967/5758e01e-7419-11e5-8422-43698df52f60.png)
 
I'm not good at English.

The graph is drawn only to that part.

**Comment by PhilJay** [comment]
post your xml

**Comment by sanghan4029** [comment]
xml 

   <LinearLayout
        android:id="@+id/background"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="horizontal"
        android:gravity="center">

        <com.github.mikephil.charting.charts.LineChart
            android:layout_width="match_parent"
            android:layout_height="400dp"
            android:id="@+id/graph"
            android:layout_weight="1"
            />

        <Button
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="clicked"
            android:onClick="clicked"
            android:layout_gravity="bottom"
            android:layout_weight="1"/>

    </LinearLayout>

and chart setup.

        mChart = (LineChart) linearLayout.findViewById(R.id.graph);
        //mChart = new LineChart(null);

        mChart.setDrawGridBackground(false);

        // set an alternative background color
        mChart.setBackgroundColor(Color.GRAY);

        // no description text
        mChart.setDescription("");
        mChart.setNoDataTextDescription("You need to provide data for the chart.");

        // enable value highlighting
        mChart.setHighlightEnabled(true);

        // enable touch gestures
        mChart.setTouchEnabled(true);

        // enable scaling and dragging
        mChart.setDragEnabled(true);
        mChart.setScaleEnabled(true);

        // if disabled, scaling can be done on x- and y-axis separately
        mChart.setPinchZoom(true);

        mChart.getAxisRight().setEnabled(true);
        mChart.getAxisRight().setAxisMaxValue(100f);
        mChart.getAxisRight().setAxisMinValue(0f);
        mChart.getAxisLeft().setEnabled(false);
        mChart.getXAxis().setDrawGridLines(true);
        mChart.getXAxis().setDrawAxisLine(true);
        mChart.getXAxis().setSpaceBetweenLabels(30);
        mChart.getXAxis().setAvoidFirstLastClipping(true);
        mChart.setVisibleXRange(50, 50);
        mChart.getTransformer(YAxis.AxisDependency.RIGHT);
        mChart.getXAxis().setAxisLineWidth(10f);


        // get the legend (only possible after setting data)
        Legend l = mChart.getLegend();

        // modify the legend ...
        // l.setPosition(LegendPosition.LEFT_OF_CHART);
        l.setForm(Legend.LegendForm.CIRCLE);

        mChart.invalidate();

**Comment by sanghan4029** [comment]
setVisibleXRange(); <- problem.

I want to implement a real-time graph using the Fragment.
