### ISSUE TITLE
Plotting a large number of points per minute realtime.

### ISSUE THREAD

**Issue by trrahul** [PhilJay/MPAndroidChart#1119]
Hello, I need to plot 192500 points each in 3 line graphs  a minute, the data is read from a file. I'm using the realtime example for plotting the points. To test,  I used the following code to test how m any points I can draw.

        new Thread(new Runnable() {

            @Override
            public void run() {
                for(int i = 0; i < 200000; i++) {
                	k=i;
                    runOnUiThread(new Runnable() {

                        @Override
                        public void run() {
                        	if(!paused)
                            graph.addEntry(k,k%50);

                    try {
                    		Thread.sleep(0);
                    	}
						
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
                }
            }
        }).start();

The most  I could get was 92000 on HP 7 Voicetab. The number is very low ( about 20000 ) when reading from file to plot in all 3 graphs. I also modified the source following this post. https://github.com/PhilJay/MPAndroidChart/issues/838

Is there any way that I can plot such a big number of points?

**Comment by AkhilGoel** [comment]
Did you find a solution to plot such a large number of points.
