### ISSUE TITLE
Rotate line chart to landscape mode

### ISSUE THREAD

**Issue by PrashantMangale** [PhilJay/MPAndroidChart#1120]
Hello Sir,
I have problem with line chart. I want to show line chart in landscape mode. I have chart in view pager. When user comes on that screen the graph should be in landscape mode. I dont know how to do this.
I tried one solution is that put FrameLayout and set animation for it. This is works fine but if you do any operation on it graph get reset to original portrait mode.
I got reference for this on stackoverflow " http://stackoverflow.com/questions/3444764/rotate-view-hierarchy-90-degrees "
Please give me answer. And one more question can we rotate clockwise or anticlockwise any graph of your library ?
If not so can you implement that feature.
![screenshot_2015-10-19-12-34-35 1](https://cloud.githubusercontent.com/assets/7066962/10571615/89e25d52-765e-11e5-98b6-5ad853b122ff.png)

**Comment by PrashantMangale** [comment]
I want chart like this. But after do any operation it looks like this
![screenshot_2015-10-19-12-42-47_1445238826967 1](https://cloud.githubusercontent.com/assets/7066962/10571697/1a41a038-765f-11e5-9a4c-568db1b06b76.jpg)

**Comment by PhilJay** [comment]
Try `android:rotation="90"` in xml.

**Comment by cagriyalcinn** [comment]
in my case, i used lineChart.setRotation(90); but it's not working.

**Comment by vladturcuman** [comment]
I managed to fit it to it's parent by using RotateAnimation.
`
public class RotatedLineChart extends LineChart {

    public RotatedLineChart(Context context, AttributeSet attrs) {
        super(context, attrs);

        RotateAnimation rotate = new RotateAnimation(0, 90, Animation.RELATIVE_TO_SELF, 0.5f, Animation.RELATIVE_TO_SELF, 0.5f);
        rotate.setFillAfter(true);
        rotate.setFillEnabled(true);
        rotate.setDuration(0);
        rotate.setInterpolator(new LinearInterpolator());

        rotate.setAnimationListener(new Animation.AnimationListener() {
            @Override
            public void onAnimationStart(Animation animation) {

            }

            @Override
            public void onAnimationEnd(Animation animation) {

                int w = getWidth();
                int h = getHeight();

                setTranslationX((w - h) / 2);
                setTranslationY((h - w) / 2);

                ViewGroup.LayoutParams lp = getLayoutParams();
                lp.height = w;
                lp.width = h;


                requestLayout();



            }

            @Override
            public void onAnimationRepeat(Animation animation) {

            }
        });

        startAnimation(rotate);
    }

}
`

**Comment by HarryMMR** [comment]
@vladturcuman The line chart still rotates correctly but doesn't stretch horizontally. Any solution?

**Comment by vladturcuman** [comment]
Try this:

```

public class RotatedLineChart extends LineChart {

    RotateAnimation rotate;
    boolean changedSize;

    public RotatedLineChart(Context context, AttributeSet attrs) {
        super(context, attrs);

        rotate = new RotateAnimation(0, 90, Animation.RELATIVE_TO_SELF, 0.5f, Animation.RELATIVE_TO_SELF, 0.5f);
        rotate.setFillAfter(true);
        rotate.setFillEnabled(true);
        rotate.setDuration(0);
        rotate.setInterpolator(new LinearInterpolator());

        rotate.setAnimationListener(new Animation.AnimationListener() {
            @Override
            public void onAnimationStart(Animation animation) {

            }

            @Override
            public void onAnimationEnd(Animation animation) {

                if(changedSize){

                    int w = getWidth();
                    int h = getHeight();

                    setTranslationX( (w-h) / 2);

                    requestLayout();
                    return;
                }

                int w = getWidth();
                int h = getHeight();

                setTranslationX((w - h) / 2);
                setTranslationY((h - w) / 2);

                changedSize = true;

                ViewGroup.LayoutParams lp = getLayoutParams();
                lp.height = w;
                lp.width = h;

                requestLayout();

            }

            @Override
            public void onAnimationRepeat(Animation animation) {

            }
        });

    }

    @Override
    protected void onAttachedToWindow() {
        super.onAttachedToWindow();
        startAnimation(rotate);
    }
}

```

**Comment by think-twice-code-once** [comment]
is this something what you want? if it's right I'll show my code.
![screenshot_20180727-165543](https://user-images.githubusercontent.com/25735122/43314857-6ce8413e-91be-11e8-8b5e-f26e8ce68b1e.png)
