### ISSUE TITLE
The red line is missing, why?

### ISSUE THREAD

**Issue by zhengdejie** [PhilJay/MPAndroidChart#1121]
![issue](https://cloud.githubusercontent.com/assets/5269738/10572899/ac0d38e6-767e-11e5-9cad-ac66fe827ce7.png)

**Comment by PhilJay** [comment]
Without any further information, I have no idea why.

**Comment by zhengdejie** [comment]
I ran the demo codes, turns out some lines is missing. This is all information I know. It is my first time to use this library
![Uploading issue.png…]()

**Comment by zhengdejie** [comment]
I ran the demo codes, turns out some line is missing.This is my first time to use this library,so this is all information I know.
![issue](https://cloud.githubusercontent.com/assets/5269738/10573786/940226de-7684-11e5-8b47-68cfb5b60af6.png)

**Comment by PhilJay** [comment]
You only have 1 dataset.

**Comment by zhengdejie** [comment]
The lines are missing, I mean, the line from center to Party B, the line from center to Party D,the line from center to Party F,the line from center to Party H

**Comment by PhilJay** [comment]
Fix: 'chart.setSkipWebLineCount(0)`
