### ISSUE TITLE
How to take screenshot of whole chart? 

### ISSUE THREAD

**Issue by himanshu1706** [PhilJay/MPAndroidChart#1122]
Hi, @PhilJay. MpChart is an awesome library. many thanks for this.

I using cubic line chart to draw real time recording waveform. Every thing is working fine but I have a requirement now that I need to take screenshot of complete waveform not only viewport. I know that I can get bitmap of viewport from this method 'getChartBitmap()'. Please guide me to make modification in library to get complete screenshot.

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Miscellaneous

You can save the chart to your gallery or to another specific path.

**Comment by himanshu1706** [comment]
I am aware about those methods and they perfect to create image from bitmap. But that only captures some part of waveform. I require to capture complete waveform. As my waveform is drawing in real time and bigger then device width.

**Comment by vusaar** [comment]
hello i also have a similar issue, i  need to get the bitmap of a chart which extends beyond the viewport.  Is there a way of doing that

**Comment by chiddudixit** [comment]
Hi @PhilJay ,
Sir, I also have exact problem.. Please give some solution to it...

**Comment by chiddudixit** [comment]
And I have total 3 chart in single page(vertically), I want to take all chart's image in Single File, all chart are has line data more then device's width... Please Help me.. if you know any Solution..

**Comment by mateohervas** [comment]
@chiddudixit did you find any solution?

**Comment by jagadishnallappa** [comment]
Did anyone find a solution to this?

**Comment by jagadishnallappa** [comment]
Hi, 

I don't know if this answer will be bashed. But it worked for me. I just figured it out.

```
<HorizontalScrollView
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:fillViewport="true"
                android:scrollbars="horizontal">

                <LinearLayout
                    android:layout_height="wrap_content"
                    android:layout_width="wrap_content"
                    android:orientation="vertical" >

                    <com.github.mikephil.charting.charts.CombinedChart
                        android:id="@+id/combinedChartBroodingGrowing"
                        android:layout_width="3000dp"
                        android:layout_height="1000dp"
                        />
                </LinearLayout>
            </HorizontalScrollView>
```

Unfortunately you'll need to specify the layout_width and layout_height explicitly in order for this to work(You'll need to play around and decide what's best for you. Also, please note: I haven't checked for any side effects. Use with discretion. I'm so sorry!). Also make sure setVisibleXRangeMaximum is not set. And then call saveToGallery() as usual. You'll see the entire chart saved to gallery. :)
