### ISSUE TITLE
Grid row & Grid line coloured chart.

### ISSUE THREAD

**Issue by andymalai** [PhilJay/MPAndroidChart#1127]
Hi ,
      As following the MPAndroidChart for a long time , I ended up with a request. The need is , 

     Can I able to set the grid background for each and every grid?
     Can I able to set the grid line colour for each and every grid line? 

     Please look in to the below line chart.

![screen shot 2015-10-20 at 5 53 18 pm](https://cloud.githubusercontent.com/assets/3078275/10606873/606c165c-7753-11e5-9b48-607694b228c4.png)

 Thank you in advance.

**Comment by PhilJay** [comment]
Such a feature is currently not available. However it should not be too hard to do this on your own by modifying the library. I'll consider the feature in the future.

**Comment by andymalai** [comment]
Thank you phil for considering this request. I will try my best at my side.
