### ISSUE TITLE
Setting proportions of sectors in pieChart

### ISSUE THREAD

**Issue by Chilcone** [PhilJay/MPAndroidChart#1129]
Hi,

I'm using this library for my project in which I use pieCharts to show nutrition values of specific meals. However, sometimes the value for specific nutrition is 0. For example carbs = 20, protein = 10, fats = 0. In this case the pieChart doesn't show a sector with fats, because the value is 0. What can I do to somehow adjust the proportions of slices, so that the 0-value would have its own slice in the graph?

Thanks for help.
![graph](https://cloud.githubusercontent.com/assets/15217072/10614136/de8f95c2-7758-11e5-8121-d674d0ed34f0.png)

**Comment by PhilJay** [comment]
Whats the purpose of using a PieChart if you change the slices away from the numbers they actually represent?

**Comment by Chilcone** [comment]
I actually don't want to change them, just need to have all the slices, even with value 0 visible. Is that possible?
Appreciate your help.

**Comment by PhilJay** [comment]
Assign a value of like 0.0001 and remove the slice space. Then it should show.
