### ISSUE TITLE
Pie-chart not drawing if entries are less than 3

### ISSUE THREAD

**Issue by NayanSrivastav** [PhilJay/MPAndroidChart#1130]
I am using your exapmle to draw pie-chart but it is not drawing if entries are less than three.

**Comment by PhilJay** [comment]
When I use the example app it draws everything below 3 entries just fine. Without any code I cannot help you.

**Comment by NayanSrivastav** [comment]
Please find the code below

List<Entry> yValues = new ArrayList<Entry>();
		for (int i = 0; i < categories.size(); i++) {
			yValues.add(new Entry(
					((amountCategoryWise.get(i)) / totalTransaction) * 100, i));
		}
		PieDataSet dataSet = new PieDataSet(yValues, "");

		dataSet.setSliceSpace(3.4f);
		dataSet.setSelectionShift(8f);
		PieData data = new PieData(categories, dataSet);
		if (type == Transaction.EXPENSE)
			dataSet.setColors(EXPENSE_COLORS);
		else {
			dataSet.setColors(INCOME_COLORS);
		}

		data.setValueFormatter(new PercentFormatter());
		data.setValueTextSize(11f);
		data.setDrawValues(true);
		String noDataText;
		if (type == Transaction.EXPENSE)
			noDataText = "NO EXPENSES FOUND";
		else {
			noDataText = "NO INCOME FOUND";
		}
		pieChart.setDrawHoleEnabled(true);
		pieChart.setNoDataText(noDataText);
		pieChart.setDrawSliceText(false);
		data.setValueTypeface(tf);
		data.setValueTextColor(Color.BLACK);
		pieChart.setData(data);
		pieChart.setOnChartValueSelectedListener(new OnChartValueSelectedListener() {
			@Override
			public void onNothingSelected() {
			}

			@Override
			public void onValueSelected(Entry e, int dataSetIndex, Highlight h) {
				pieChart.highlightValue(e.getXIndex(), dataSetIndex);
				pieChart.setCenterText(new SpannableString(amountCategoryWise
						.get(e.getXIndex()) + ""));
			}
		});
		//pieChart.setHovered(true);
		
		//pieChart.getChartBitmap().setWidth(280);
		
		Legend l = pieChart.getLegend();
		l.setFormToTextSpace(2);
		l.setWordWrapEnabled(true);
		l.setPosition(LegendPosition.BELOW_CHART_CENTER);
		l.setForm(LegendForm.CIRCLE);
		l.setDirection(LegendDirection.LEFT_TO_RIGHT);
		l.setXEntrySpace(2f);
		l.setYEntrySpace(0);
		l.setYOffset(2f);
		pieChart.highlightValues(null);
		pieChart.invalidate();
