### ISSUE TITLE
Show values only when tapped [Line Data]

### ISSUE THREAD

**Issue by poldz123** [PhilJay/MPAndroidChart#1133]
I`ve been looking for a way to enable the MPAndroidChart to only display the value(label) of data point when clicked. But It seems that I could not find it online even in the documentation.

I used the line chart and what I want is to only display the label of the certain point when tapped.

Is there a functionality for it?

if not, what are the other alternative to it?

**Comment by NasaGeek** [comment]
Have you tried setting setOnChartValueSelectedListener on your LineChart and then calling highlightValues with the Highlight object that gets passed to the OnValueSelected method?

https://jitpack.io/com/github/PhilJay/MPAndroidChart/v2.1.5/javadoc/com/github/mikephil/charting/charts/Chart.html#highlightValues(com.github.mikephil.charting.highlight.Highlight[])
https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart
