### ISSUE TITLE
stacked bar chart with single bar segment in stack

### ISSUE THREAD

**Issue by ECrosland** [PhilJay/MPAndroidChart#1134]
I am using a stacked bar chart in my app. In most cases, there will indeed be more than one "stack segment" per entry; in some cases, however, there will not be, and in these cases I expect the chart to look like an ordinary "unstacked" bar chart.

The business logic that sets up the chart depends on user-supplied data, and it is the latter that determine whether or not more than one segment will be present. I would rather not introduce special-case logic to handle the case where only a single segment exists.

The problem is that, when in a given case only one segment is needed, certain things break down. For one, no labels are printed in the legend--I suppose this is because I set the labels with BarDataSet#setStackLabels, and these are not consulted when the chart doesn't look like a stacked bar chart. The second problem I notice is that any Highlight object I retrieve by calling Chart#getHighlighted will not, where only a single stack segment is present, include a valid stack index.

I notice that the implementation of BarDataSet#isStacked returns true if and only if the stack size is greater than one. If I override this method on my data sets to always return true, the problems I mentioned seem to go away. 

Would it be possible to modify the default implementation to more robustly handle the "degenerate" case of a stacked bar chart having only a single segment? I construct each of my BarEntry instances using the constructor that accepts an array of float for its first argument, and the docs identify this as a constructor for stacked entries, so it seems that, semantically, the intent to create a stacked bar chart is being communicated.

**Comment by PhilJay** [comment]
If your stack has only one segment, it's technically not a stack. Therefore, simply use the normal `BarEntry` constructor and not the one that takes a float array as parameter.

**Comment by ECrosland** [comment]
Thank you for your reply. Perhaps I could take a moment to clarify something, however.

I understand I can simply use the constructor that accepts a single float as a parameter, but this doesn't address the problems I mentioned, which is that the stack labels aren't drawn when a single segment is given (I'd still like a label for the single segment that is present) and the Highlight object doesn't have a stack index (it would make sense to me to give the single segment index zero).

Analogously, one could argue that an array with a single element isn't much of an array, but nonetheless the Java runtime does not throw a `PoorExcuseForAnArrayException` when you try to subscript a single-element array! Thus code written against arrays does not have to treat single-element arrays in a special manner.

That said, if you don't see anything here to be addressed, then I totally get it. As I mentioned previously, I do have a workaround that addresses my peculiar use case.
