### ISSUE TITLE
MarkView at the edges of the screen will be out of range

### ISSUE THREAD

**Issue by tombcato** [PhilJay/MPAndroidChart#1136]
How to control the complete show at the edge
I hope someone can help me with this problem
thanks!
![screenshot_2015-10-22-14-18-26_cn suncloud kopak](https://cloud.githubusercontent.com/assets/10005665/10658307/27d24660-78c8-11e5-91a1-9466f5d0766f.png)
![screenshot_2015-10-22-14-18-51_cn suncloud kopak](https://cloud.githubusercontent.com/assets/10005665/10658308/27d2df6c-78c8-11e5-850b-4dd2d65f9d60.png)

**Comment by marcosmbbrito** [comment]
Hello I resolve this overriding the draw method like this:

@Override
	public void draw(Canvas canvas, float posx, float posy) {

                //Log.e("MyMarkerView", "draw (line 59): pox " + posx + " poy " + posy);
		// take offsets into consideration
		if (posx > (LineFragment.mChart.getWidth() +getXOffset()))
			posx += (LineFragment.mChart.getWidth() +getXOffset()) - posx + getXOffset();
		else if (posx < (getWidth() / 2)) posx += (getWidth() / 2) - posx + getXOffset();
		else posx += getXOffset();
		posy += getYOffset();

		// translate to the correct position and draw
		canvas.translate(posx, posy);
		draw(canvas);
		canvas.translate(-posx, -posy);

	}

Regards
------------- Complete code ---------------------------------

public class MyMarkerView extends MarkerView {


	private TextView tvContent;
	private TextView tvDatasetName;

	public MyMarkerView(Context context, int layoutResource) {
		super(context, layoutResource);

		tvContent = (TextView) findViewById(R.id.tvContent);
		tvDatasetName = (TextView) findViewById(R.id.tv_marker_dataset_name);
//		mChart = (LineChart) context.findViewById(R.id.lineChart1);
	}


	// callbacks everytime the MarkerView is redrawn, can be used to update the
	// nome
	@Override
	public void refreshContent(Entry e, Highlight h) {

		if (e instanceof CandleEntry) {

			CandleEntry ce = (CandleEntry) e;

			tvContent.setText(String.format(" %s", Utils.formatNumber(ce.getHigh(), 0, true).trim()));
		} else {
//			Log.e("MyMarkerView", "refreshContent (line 43): ");


			try {
				tvDatasetName.setText(LineFragment.mChart.getLegend().getLabel(h.getDataSetIndex()));
				tvDatasetName.setBackgroundColor(LineFragment.mChart.getLegend().getColors()[h.getDataSetIndex()]);
				tvContent.setBackgroundColor(LineFragment.mChart.getLegend().getColors()[h.getDataSetIndex()]);
				NumberFormat nf = new DecimalFormat("###,###,###,###,###,###,###,###,###,###.#");
				tvContent.setText(String.format("%s / {faw-calendar} %s", nf.format(e.getData() == null ? (double) e.getVal() : (BigDecimal) e.getData()), LineFragment.mChart.getXValue(e.getXIndex())));
			} catch (Exception e1) {
				e1.printStackTrace();
			}


		}
	}

	@Override
	public int getXOffset() {
		return -(getWidth() / 2);
	}

	@Override
	public int getYOffset() {
		return -getHeight();
	}

	@Override
	public void draw(Canvas canvas, float posx, float posy) {

//			Log.e("MyMarkerView", "draw (line 59): pox " + posx + " poy " + posy);
		// take offsets into consideration
		if (posx > (LineFragment.mChart.getWidth() +getXOffset()))
			posx += (LineFragment.mChart.getWidth() +getXOffset()) - posx + getXOffset();
		else if (posx < (getWidth() / 2)) posx += (getWidth() / 2) - posx + getXOffset();
		else posx += getXOffset();
		posy += getYOffset();

		// translate to the correct position and draw
		canvas.translate(posx, posy);
		draw(canvas);
		canvas.translate(-posx, -posy);

	}


}

**Comment by tombcato** [comment]
Nice of you, the perfect solution to my problem,thank you

**Comment by PhilJay** [comment]
I'll provide a fix for this by handing over the xpos in the `getXOffset()` method. So you can then do this:

```java
@Override
public int getXOffset(float xpos) {

    if(xpos == whatever) // do this
    
    else // do that...
}
```
