### ISSUE TITLE
Can I clear middle circle and retain circle on the edge

### ISSUE THREAD

**Issue by wanglg** [PhilJay/MPAndroidChart#1139]
About LineChart,Can I clear middle circle and retain circle on the edge

**Comment by PhilJay** [comment]
What do you mean by "clear"?

**Comment by wanglg** [comment]
Sorry,My English is not good,I want to disable middle circle ,the method setDrawCircles(false) is not draw all circles ,but I want retain two circle on the edge.

**Comment by PhilJay** [comment]
Just set the hole color to transparent for your dataset.
