### ISSUE TITLE
Adjacent slice disappears in Pie Chart on click

### ISSUE THREAD

**Issue by CROSP** [PhilJay/MPAndroidChart#1146]
Hi, I have tried to create PieChart, it seems to look good ,but it works a little bit weird.   
When I click on slice nearby slice disappears.
http://imgur.com/NjLZMuq

Also I  cannot click on smile slice at all.     

Here is my code     
```java
 List<ChartItem> chartItems = new ArrayList<>();
        Random rnd = new Random();
        for (int i = 1; i < 6; i++) {
            DeliveryChartItem deliveryChartItem = new DeliveryChartItem();
            int color = Color.argb(255, rnd.nextInt(256), rnd.nextInt(256), rnd.nextInt(256));
            Entry entry = new Entry(i * 100, i);
            deliveryChartItem.chartColor = color;
            deliveryChartItem.chartData = entry;
            deliveryChartItem.legendDescription = "CHART #" + i;
            chartItems.add(deliveryChartItem);
        }

```

And setting up pie chart with data  

```java
  private void setChartData() {
        yValues = new ArrayList<>();
        xValues = new ArrayList<>();
        colorsList = new ArrayList<>();
        for (int i = 0; i < chartItems.size(); i++) {
            ChartItem item = chartItems.get(i);
            yValues.add(item.getCharData());
            colorsList.add(item.getChartColor());
            xValues.add(item.getLegendDescription());
        }
        PieDataSet dataSet = new PieDataSet(yValues, chartTitle);
        dataSet.setSliceSpace(SLICE_SPACE);
        dataSet.setSelectionShift(SELECTION_SHIFT);
        dataSet.setColors(colorsList);
        PieData data = new PieData(xValues, dataSet);
        data.setValueFormatter(new PercentFormatter());
        data.setValueTextSize(DEFAULT_CHART_TEXT_SIZE);
        data.setValueTextColor(Color.WHITE);
        pcDeliveries.setData(data);
        pcDeliveries.invalidate();
    }
```
    
And initalization of PieChart   

```java
    void initChart() {
        pcDeliveries.setUsePercentValues(true);
        pcDeliveries.setDescription("");
        pcDeliveries.setExtraOffsets(5, 12, 5, 5);
        pcDeliveries.setDragDecelerationFrictionCoef(DRAG_DECELERATION_FRICTION_COEF);
        // Change this to false to disable internal color
        pcDeliveries.setDrawHoleEnabled(true);
        pcDeliveries.setHoleColorTransparent(true);
        pcDeliveries.setTransparentCircleColor(Color.WHITE);
        pcDeliveries.setTransparentCircleAlpha(CIRCLE_ALPHA);
        pcDeliveries.setHoleRadius(HOLE_RADIUS);
        pcDeliveries.setTransparentCircleRadius(TRANSPARENT_CIRCLE_RADIUS);
        pcDeliveries.setRotationAngle(ROTATION_ANGLE);
        // enable rotation of the chart by touch
        pcDeliveries.setRotationEnabled(true);
        pcDeliveries.setOnChartValueSelectedListener(this);
        pcDeliveries.animateY(DURATION_MILLIS, Easing.EasingOption.EaseInOutQuad);
        // pcDeliveries.spin(2000, 0, 360);
        Legend legend = pcDeliveries.getLegend();
        legend.setPosition(Legend.LegendPosition.RIGHT_OF_CHART);
        legend.setXEntrySpace(X_ENTRY_SPACE);
        legend.setTextColor(defaultTextColor);
        legend.setTextSize(defaultTextSize);
        legend.setYEntrySpace(Y_ENTRY_SPACE);
        legend.setYOffset(Y_OFFSET);
        CustomMarkerView mv = new CustomMarkerView (getContext(), R.layout.custom_marker_view_layout);

// set the marker to the chart
        pcDeliveries.setMarkerView(mv);

    }

```

I have used most values as in the example.    

Is it my fault or it is bug in the library.    

Thank you.

**Comment by PhilJay** [comment]
`for (int i = 1; i < 6; i++) `

start your loop at 0 like a normal developer :-)

**Comment by zelin** [comment]
I am having the same problem. Here is my code 

               ArrayList<Entry> yVals1 = new ArrayList<Entry>();
        ArrayList<String> xVals = new ArrayList<String>();
        ArrayList<Integer> colors = new ArrayList<Integer>();
        ArrayList<BarEntry> yValsBar = new ArrayList<BarEntry>();

        totalUserMoodsCount = 0;
        for (int i = 0; i < userMoodsList.size(); i++)
        {
            MoodModel mood = userMoodsList.get(i);
            totalUserMoodsCount = mood.totalCount + totalUserMoodsCount;
        }

        for (int i = 0; i < userMoodsList.size(); i++)
        {
            MoodModel mood = userMoodsList.get(i);

            int percentage = (int) (((double) mood.totalCount / totalUserMoodsCount) * 100);
            if(percentage >= 1)
            {
                yVals1.add(new Entry(percentage, i));
                xVals.add(getResources().getString(Utilities.getMoodStringFromType(Integer.valueOf(mood.mood))).replace("Feeling","").toUpperCase());
                colors.add(getResources().getColor(Utilities.getMoodColorFromType(Integer.valueOf(mood.mood))));

                yValsBar.add(new BarEntry(percentage, i));
            }
        }

        addChartValues(userChart, new PieChartItem(generateDataPie(xVals,yVals1, colors), mContext));


Now for settings

    private PieData generateDataPie(ArrayList<String> moodNames, ArrayList<Entry> entries,  ArrayList<Integer> colors)
    {
        PieDataSet d = new PieDataSet(entries, "");
        d.setSliceSpace(1f);
        d.setColors(colors);
        d.setSelectionShift(0f);
        d.setHighlightEnabled(false);
        PieData cd = new PieData(moodNames, d);
        return cd;
    }

private void addChartValues(PieChart mChart, PieChartItem mItem)
    {
        ChartData<?> mChartData = mItem.mChartData;
        mChartData.setValueFormatter(new PercentFormatter());
        mChartData.setValueTextSize(9f);
        mChartData.setValueTextColor(Color.WHITE);
        // set data
        mChart.setData((PieData) mChartData);

        Legend l = mChart.getLegend();
        l.setPosition(Legend.LegendPosition.RIGHT_OF_CHART);
        l.setYEntrySpace(0f);
        l.setWordWrapEnabled(true);
        l.setYOffset(0f);


        // do not forget to refresh the chart
        // userChart.invalidate();
        mChart.animateXY(900, 900);
    }


  // apply styling
        userChart.setDescription("");
        userChart.setHoleRadius(52f);
        userChart.setTransparentCircleRadius(57f);
        userChart.setCenterText("");
        userChart.setCenterTextSize(9f);
        userChart.setHoleColorTransparent(true);
        userChart.setUsePercentValues(true);
        userChart.setExtraOffsets(5, 10, 100, 10);
