### ISSUE TITLE
class not found exception issue

### ISSUE THREAD

**Issue by coder4567** [PhilJay/MPAndroidChart#1148]
Hy, I would like to thank you for the great solution you have posted, it's really amazing.
I downloaded the example and it worked fine on eclipse. But as I tried to integrate the solution in my application, it compiled correctly but every time the PineChartActivity or any other chart Activity gets called I get the following error:
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/xxmassdeveloper/mpchartexample/PieChartActivity;
Kindly note that I have included the activities in the manifest file, and I have included the mpchartlib.jar, the build.graddle file I also included the mpandroidchartlibrary-2-1-3-jar-with-dependencies.jad and android-support-v4.jar. I also changed the project.properties file to include the following:
target=Google Inc.:Google APIs:18
proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
android.library.reference.1=../MPChartLib
And in the library configuration I chose google APIs for android ands added the MPChartLib

kindly if I am missing anything would you please point it out for me.
Thank you for your help.

**Comment by PhilJay** [comment]
`PieChartActivity` is a demo class from the example project. It has nothing to do with the library itself.

**Comment by coder4567** [comment]
Thank you for your reply, I do understand that PieChartActivity is from the example but as I was trying to use the library in my project on a different activity I got the same error, so I moved the demo to my project with all the classes in order to test the source of the problem, the same problem has occurred. I would truly appreciate if you could guide me through using it, I have read all the instructions that comes with the example project and still I don't know what I'm missing.
