### ISSUE TITLE
Custom Legend for a Bar chart

### ISSUE THREAD

**Issue by ramvdixit** [PhilJay/MPAndroidChart#1149]
Hello there!

I really dont understand how to override the auto compute feature of the legend and set a custom legend with custom colors and labels. Can you please elaborate? I gather from the docs that we need to use a -2 and a null label. Can you please highlight how it is done? I have a bar chart with one yVals arrayList with 8 values with 8 different colors. I need to set a custom legend with differet lables for all these 8 items. Help please.

Best,
Ram

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Legend

Try the `legend.setCustom(...)` method.
