### ISSUE TITLE
X Label Multiline

### ISSUE THREAD

**Issue by sharma24** [PhilJay/MPAndroidChart#1150]
Hi,
Is there any way we can display Xlabel entry into two line like attached image?
I have source code setup in my Studio project. Do i need to make any changes in Lib project. Please suggest.

Thanks.
<img width="340" alt="screen shot 2015-10-26 at 2 30 12 pm" src="https://cloud.githubusercontent.com/assets/4346822/10724966/668b9f5e-7bee-11e5-987d-44283992d4df.png">

**Comment by Rohfosho** [comment]
Hey, any update on this?
