### ISSUE TITLE
"No Chart Data Available." appears although the chart is being set with data.

### ISSUE THREAD

**Issue by rubennunes** [PhilJay/MPAndroidChart#1151]
Hello there, first off all i want to say thank you for giving us this wonderful library.

I have being stuck with this problem in a BarChart. I use the *setData* and the *invalidate* as the image below suggests:

![setdata](https://cloud.githubusercontent.com/assets/3810826/10728429/9d04dc68-7bd9-11e5-9b23-50a8bd3679f4.PNG)

The chart is being created in this block of code:

![createview](https://cloud.githubusercontent.com/assets/3810826/10728448/bbedba6e-7bd9-11e5-9544-b85a8792a784.PNG)

and this is my XML:

![layout](https://cloud.githubusercontent.com/assets/3810826/10728451/c65c9d4e-7bd9-11e5-8368-8efc2e6f482a.PNG)

And the result is this(No Chart Data Available.):

![data not available](https://cloud.githubusercontent.com/assets/3810826/10728466/eeac68b0-7bd9-11e5-99b8-dcf3c4dfc76c.png)

Can you give me some help on this one?
Ps: Sorry for my English

**Comment by PhilJay** [comment]
Have you tried calling `chart.invalidate()` after adding it to the layout?

**Comment by rubennunes** [comment]
I added the line and still the message "No chart data available".
I even added to the actual frame and still no results.

![invalidate](https://cloud.githubusercontent.com/assets/3810826/10738170/f117860a-7c0d-11e5-9bcd-5535256b3685.PNG)

**Comment by ramden** [comment]
Same problem here, why is this closed?

**Comment by PhilJay** [comment]
Why did you define your graph in .xml and then add it programmatically as well?

**Comment by rubennunes** [comment]
I don't know why Phil close this thread but i managed to show the values. Not with "good" code but it worked.
Because i wanted the number of bars need to be added dynamically.

**Comment by crescent7272** [comment]
I have same problem may I ask how did you solve that? invalidate() does not work for me ?

**Comment by crescent7272** [comment]
Sorry solved the issue, there was actually no data. thanks

**Comment by rubennunes** [comment]
Glad to know that :)
Any question you can ask.
