### ISSUE TITLE
Not able to hide background grid in Barchart

### ISSUE THREAD

**Issue by harshgaba** [PhilJay/MPAndroidChart#1152]
i want to hide the background grid and values from bargraph, but unable to hide it.
right now i'm doing-

 barChart.setDrawGridBackground(false);
        barChart.setGridBackgroundColor(Color.TRANSPARENT);

but these are not working

**Comment by PhilJay** [comment]
The grid lines can be disabled via x- and y-axis, the values can be disabled via dataset. Its all in the wiki: https://github.com/PhilJay/MPAndroidChart/wiki
