### ISSUE TITLE
detailed information about data on touch to points

### ISSUE THREAD

**Issue by umuplus** [PhilJay/MPAndroidChart#1157]
Hello,

When I touch one of the points a thin orange lines shows up. Is it possible to show something like in this picture? Design doesn't matter. I just want to show the actual value. Otherwise it's not possible to say the actual value.
![detailed information example](https://cloud.githubusercontent.com/assets/681115/10787449/afe520da-7d79-11e5-803f-f26106f8f797.png)

**Comment by PhilJay** [comment]
I think this is what you are looking for: https://github.com/PhilJay/MPAndroidChart/wiki/MarkerView

Concerning the lines that show up when touching values, you can enable/disable them like this: 
`dataSet.setDrawHighlightIndicators(boolean enabled)`

 - <code>setDrawHighlightIndicators(boolean enabled)</code>: Enables / disables both vertical and horizontal highlight indicator lines. Call `setDrawVerticalHighlightIndicator(...)` and `setDrawHorizontalHighlightIndicator(...)` for individual configuration.
