### ISSUE TITLE
No data text

### ISSUE THREAD

**Issue by botondbutuza** [PhilJay/MPAndroidChart#1158]
Hey there!

I'm having trouble with the no data text on PieCharts - I can't get rid of it! I've tried 

`chart.setNoDataText("");
chart.setNoDataTextDescription("");
chart.invalidate();
`

after data has been set, and tried it before data's set as well, but the text is still there. I've also tried grabbing the info paint object, and setting the colour to transparent, but that didn't work either:

`Paint paint = chart.getPaint(Chart.PAINT_INFO);
        paint.setColor(Color.TRANSPARENT);
        chart.setPaint(paint, Chart.PAINT_INFO);
`

Any suggestions?

Thanks!

**Comment by coolscott** [comment]
please try:
...
 chart.setNoDataText("");
 chart.invalidate();
...
