### ISSUE TITLE
LineChart draw cubic problem

### ISSUE THREAD

**Issue by octavianmiu** [PhilJay/MPAndroidChart#1161]
I try to make a linechart with drawcubic activated but does not render right. If i do not activate the option, it looks fine. where is the problem?
![untitled](https://cloud.githubusercontent.com/assets/11173639/10844163/432eb0b2-7f06-11e5-8e65-5e8c3c89e412.png)
![untitled2](https://cloud.githubusercontent.com/assets/11173639/10844164/4334a530-7f06-11e5-8db9-53b7ba877300.png)

**Comment by PhilJay** [comment]
Have you tried reducing the cubic-intensity?

````java
 /**
     * Sets the intensity for cubic lines (if enabled). Max = 1f = very cubic,
     * Min = 0.05f = low cubic effect, Default: 0.2f
     * 
     * @param intensity
     */
    public void setCubicIntensity(float intensity);
```
e.g.:

`lineDataSet.setCubicIntensity(0.1f)`

**Comment by octavianmiu** [comment]
last, 2.1.5

**Comment by PhilJay** [comment]
And what did changing the intensity do?

**Comment by octavianmiu** [comment]
what u cand see in the screenshot, makes a distorsioned line

**Comment by octavianmiu** [comment]
and area

**Comment by octavianmiu** [comment]
the idea is next: i have 25 values on xAxis, and in yVales i have only 3 random values, others are null.
can be this the problem?
