### ISSUE TITLE
how to hide or make user friendly bar color description.

### ISSUE THREAD

**Issue by himanshumoriglobus** [PhilJay/MPAndroidChart#1162]
I am working on MPAndroid BarChart  activity. there successfully i am able to draw bars with multiple colors by method  barDataSet.setColors(..........); 
But in the bottom of xaxis i am getting each bar color description. if suppose i have 30 bars then it will give me 30 bars description at bottom. And that is not user friendly i dont want that.

is there any way or function to hide these color descriptions or making it user freindly .????

![screenshot_76](https://cloud.githubusercontent.com/assets/8234317/10845439/e813320c-7f2d-11e5-9fe6-831e1a03bc22.png)

i hope this screenshot shows the problem which i am facing.

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Legend

Try the `legend.setCustom(...)` method.

It allows you to set custom colors and labels.
So you could add just two colors (green & red) and then add two adequate description labels.
