### ISSUE TITLE
Can it be done in BarChart?

### ISSUE THREAD

**Issue by fmeneuhe** [PhilJay/MPAndroidChart#1164]
Hi,
- Is possible in BarChart to draw an horizontal line showing the average value when maximum Y is set?
- Is possible in BarChart show on the top of the bar the value and the percentage when the maximum Y value is set?
- Is possible a CombinedChart with multiple Line DataSets (multiple bars)?

Thanks

**Comment by PhilJay** [comment]
- yes
 - yes
 - multiple linedatasets is possible, multiple bardatasets is not possible
