### ISSUE TITLE
Bug coloring XAxis in CombinedChart?

### ISSUE THREAD

**Issue by fmeneuhe** [PhilJay/MPAndroidChart#1165]
Hi,
I have this issue with CombinedCharts:
I set the value bar color:
BarDataSet.setValueTextColor(Color.BLACK) and it works fine.

But, if after that, I set the axis color:
CombinedChart.getXAxis().setTextColor(Color.WHITE),

It overrides the value bar color to white and I loose the black color. 

Is this a bug or normal behavior?

**Comment by PhilJay** [comment]
Show me your code and a screenshot of the result please.

**Comment by fmeneuhe** [comment]
Since I wrote this issue so far, I have changed the code and now is working, I cannot reproduce the issue again. So you can close it, sorry about the inconvenience.
