### ISSUE TITLE
Y axis minimum not working

### ISSUE THREAD

**Issue by rodrigoturnes** [PhilJay/MPAndroidChart#1170]
Hi,

I have been trying to set the chart Y axis minimum and it won't work. The strange thing is that maximum is working fine! Help please.

YAxis y = cell.graphView.getAxisLeft();
y.setAxisMaxValue(max);
y.setAxisMinValue(min);

Thanks!

**Comment by PhilJay** [comment]
axis.setStartAtZero(false)

**Comment by rodrigoturnes** [comment]
Great!

Thanks

**Comment by Sushinn** [comment]
This method is marked as Deprecated, what should I use then?
