### ISSUE TITLE
PieChart : transparent color

### ISSUE THREAD

**Issue by alexbeville** [PhilJay/MPAndroidChart#1172]
Hi,
I need to have a piece of PieChart (the circle doesn't have to be full, mean 100%).

I tried to put a 80f grey part, and a 20f transparent part and I was expected to work well, but instead, my PieChart won't display.

Is there a way to do this ?

valsComp1.add(new Entry(80f, 0));
xVals.add("0");
colors.add(R.color.grey);
valsComp1.add(new Entry(20f, 1));
xVals.add("1");
colors.add(R.color.transparent);

**Comment by PhilJay** [comment]
You need to resolve the colors: `getResources().getColor(R.color.transparent)`

**Comment by alexbeville** [comment]
Thanks for your reply. But I'm using `setColors(int [] colors, Context c)`

int[] ret = new int[colors.size()];
for (int x = 0; x < ret.length; x++) {
      ret[x] = colors.get(x).intValue();
}
setComp1.setColors(ret, getActivity());

**Comment by PhilJay** [comment]
Okay, and whats your output? Can you show a screenshot?

**Comment by alexbeville** [comment]
I can send you a screenshot, but all I have is ... nothing, the pie chart isn't drawn

**Comment by alexbeville** [comment]
Did you reproduced the issue ?

**Comment by alexbeville** [comment]
Can you please reopen this issue ?
