### ISSUE TITLE
Grid lines color

### ISSUE THREAD

**Issue by rodrigoturnes** [PhilJay/MPAndroidChart#1173]
Hi,

I was trying to set grid lines color (both x-axis and y-axis) and found that worked with standard colors such as Color.RED (0xFFFF0000) but no with custom colors such as R.color.blue (<color name="blue">#23b1f7</color>). Any help?

Thanks!

**Comment by PhilJay** [comment]
For colors like `R.color.blue` you need to use this: `getResources().getColor(R.color.blue)` - it's all in the method documentation.

https://github.com/PhilJay/MPAndroidChart/wiki/Setting-Colors

**Comment by rodrigoturnes** [comment]
Excellent!

Thanks
