### ISSUE TITLE
Adjacent slice or same slice becomes transparent in Pie Chart on click

### ISSUE THREAD

**Issue by zelin** [PhilJay/MPAndroidChart#1176]
Referring to same issue mentioned in https://github.com/PhilJay/MPAndroidChart/issues/1146
i am having same problem.

               ArrayList<Entry> yVals1 = new ArrayList<Entry>();
        ArrayList<String> xVals = new ArrayList<String>();
        ArrayList<Integer> colors = new ArrayList<Integer>();
        ArrayList<BarEntry> yValsBar = new ArrayList<BarEntry>();

        totalUserMoodsCount = 0;
        for (int i = 0; i < userMoodsList.size(); i++)
        {
            MoodModel mood = userMoodsList.get(i);
            totalUserMoodsCount = mood.totalCount + totalUserMoodsCount;
        }

        for (int i = 0; i < userMoodsList.size(); i++)
        {
            MoodModel mood = userMoodsList.get(i);

            int percentage = (int) (((double) mood.totalCount / totalUserMoodsCount) * 100);
            if(percentage >= 1)
            {
                yVals1.add(new Entry(percentage, i));
                xVals.add(getResources().getString(Utilities.getMoodStringFromType(Integer.valueOf(mood.mood))).replace("Feeling","").toUpperCase());
                colors.add(getResources().getColor(Utilities.getMoodColorFromType(Integer.valueOf(mood.mood))));

                yValsBar.add(new BarEntry(percentage, i));
            }
        }

        addChartValues(userChart, new PieChartItem(generateDataPie(xVals,yVals1, colors), mContext));

Now for settings

    private PieData generateDataPie(ArrayList<String> moodNames, ArrayList<Entry> entries,  ArrayList<Integer> colors)
    {
        PieDataSet d = new PieDataSet(entries, "");
        d.setSliceSpace(1f);
        d.setColors(colors);
        d.setSelectionShift(0f);
        d.setHighlightEnabled(false);
        PieData cd = new PieData(moodNames, d);
        return cd;
    }

private void addChartValues(PieChart mChart, PieChartItem mItem)
    {
        ChartData<?> mChartData = mItem.mChartData;
        mChartData.setValueFormatter(new PercentFormatter());
        mChartData.setValueTextSize(9f);
        mChartData.setValueTextColor(Color.WHITE);
        // set data
        mChart.setData((PieData) mChartData);

        Legend l = mChart.getLegend();
        l.setPosition(Legend.LegendPosition.RIGHT_OF_CHART);
        l.setYEntrySpace(0f);
        l.setWordWrapEnabled(true);
        l.setYOffset(0f);

        // do not forget to refresh the chart
        // userChart.invalidate();
        mChart.animateXY(900, 900);
    }

  // apply styling
        userChart.setDescription("");
        userChart.setHoleRadius(52f);
        userChart.setTransparentCircleRadius(57f);
        userChart.setCenterText("");
        userChart.setCenterTextSize(9f);
        userChart.setHoleColorTransparent(true);
        userChart.setUsePercentValues(true);
        userChart.setExtraOffsets(5, 10, 100, 10);

**Comment by PhilJay** [comment]
Which version are you using?

**Comment by PhilJay** [comment]
I might have a solution for your problem.

You are only adding entries if a certain condition `if(percentage >1)` is met. In general, this is fine, but it causes you to leave out x-indices. And that is not good.

So I suggest you use a separate index value in your loop and only increment it inside the if condition:

```java
int xIndex = 0;

for (int i = 0; i < userMoodsList.size(); i++)  {
        MoodModel mood = userMoodsList.get(i);

        int percentage = (int) (((double) mood.totalCount / totalUserMoodsCount) * 100);
        if(percentage >= 1) {
            yVals1.add(new Entry(percentage, xIndex)); // use xIndex, NOT i
            xIndex++;
            // other code ...
        }
    }
```

**Comment by zelin** [comment]
@PhilJay  Ok xindex does solve the problem of selection of other values. However the slice is still disappearing when i click on it. It becomes sort of transparent. How can i fix this?
