### ISSUE TITLE
How to draw straight line between two points

### ISSUE THREAD

**Issue by sarathnk** [PhilJay/MPAndroidChart#1177]
![graph](https://cloud.githubusercontent.com/assets/5154084/10929882/e98b399a-82de-11e5-8624-c22be6dbb2ae.jpg)
![device-2015-11-04-100502](https://cloud.githubusercontent.com/assets/5154084/10929846/984cbdce-82de-11e5-9b58-e4694b4da4a2.png)
How can i connect the points with straight lines like in the picture1 instead of curved lines in the picture 2.

**Comment by sarathnk** [comment]
solved issue

  LineDataSet set = new LineDataSet(entries, "");
  set.setDrawCubic(false);

**Comment by mitchtabian** [comment]
Is it possible to draw lines between only a select few points? 
For example, if we are talking about the above graphs - how can I draw a line only between pt=108 and pt=130?

I made a simple diagram in the attached image. 

Thanks in advance.

![diagram](https://cloud.githubusercontent.com/assets/17446480/20235016/ecad428e-a83b-11e6-919f-cbb99c38b2ad.PNG)
