### ISSUE TITLE
Draw fill above line chart

### ISSUE THREAD

**Issue by tijee** [PhilJay/MPAndroidChart#1178]
Hi, is there a way to fill _above_ the line chart (i.e. from the top of the viewport to the line)? If not, have you planned to add this feature?

Thanks in advance!

**Edit**: just thought of a way to do that: change the background color of the viewport and fill below the line with white color. Anyway, a `setFillPosition()` would be a nice addition :)

**Comment by PhilJay** [comment]
Check out [FillFormatter](https://github.com/PhilJay/MPAndroidChart/wiki/FillFormatter) - you should be able to do this

**Comment by tijee** [comment]
Awesome, thanks! :+1:

**Comment by andrearinaldispotsoftware** [comment]
It's enough for you to change this two lines:

`float chartMaxY = dataProvider.getYChartMax();`
`float chartMinY = dataProvider.getYChartMin();`

with the following:

`float chartMaxY = dataProvider.getYChartMin();`
`float chartMinY = dataProvider.getYChartMax();`

and everything will be taken upside-down :)
