### ISSUE TITLE
Hi i have question regarding writing text vertically in Y Axis.

### ISSUE THREAD

**Issue by hukumsingh87** [PhilJay/MPAndroidChart#1181]
![screenshot from 2015-11-05 19 56 53](https://cloud.githubusercontent.com/assets/12544602/10970943/a5ee1de6-83f7-11e5-8bcd-5bd77408ab36.png)
Hi i found your lib super awesome .. :) but i have a doubt regarding... how we would draw text vertically on Y Axis, as highlighted in screenshot attached here. It is very much required in  many cases.

**Comment by PhilJay** [comment]
Just use a TextView and rotate it 90 degrees :-)

**Comment by hukumsingh87** [comment]
Thanks :+1:  
I was anticipating for solution within your legendary Lib :-) Thanks Once again  :-)
