### ISSUE TITLE
dataset.setLabel() not working on BarDataSet

### ISSUE THREAD

**Issue by PatrikOO** [PhilJay/MPAndroidChart#1182]
When I click on value in chart I want to update dataset label with value of selected entry. It is working on LineDataset, but not on BarDataset. Value mLabel in dataset is updated, but it is not seen on display.

@Override
    public void onValueSelected(Entry entry, int i, Highlight highlight) {
        for (String label : barGraphData.keySet()){
            if (getBarData().getDataSetByIndex(i).getLabel().contains(barGraphData.get(label).label)){
                barGraphData.get(label).dataset.setLabel(barGraphData.get(label).label+ " " + entry.getVal() + " " + mCurrentUnitType.toString());
                invalidate();
                return;
            }
        }
    }

**Comment by PhilJay** [comment]
What exactly are you invalidating?

Are you setting the label to the same data that is also displayed in the chart?

**Comment by PatrikOO** [comment]
Yes, When I select a value in graph, I want to update label in legend for corresponding DataSet with the selected value. On LineChart it works, on BarChart it works not.

**Comment by PhilJay** [comment]
This code works for me:

````java
@Override
public void onValueSelected(Entry e, int dataSetIndex, Highlight h) {

     mChart.getBarData().getDataSetByIndex(dataSetIndex).setLabel("test");
     mChart.getLegendRenderer().computeLegend(mChart.getBarData());
     mChart.invalidate();
}
````
