### ISSUE TITLE
How can I stop scrolling on y axis?

### ISSUE THREAD

**Issue by himanshu1706** [PhilJay/MPAndroidChart#1184]
I am using cubic line chart to show real time audio recording data. Graph's minimum and maximum depends on sound intensity. I am using graph in landscape mode.The problem is that I only want to show a specific range of values on graph for that I am using 

mChart.setVisibleYRangeMaximum(2500, AxisDependency.LEFT);

method. It fixes the visible range but when a more lower values comes in to picture the graph will automatically shifts the top side of the device height(in landscape mode). 

After that I have to manually scroll the graph on y axis to see the main part of graph.

![19679](https://cloud.githubusercontent.com/assets/13013382/10990811/3c1f9b70-847d-11e5-8106-59a423f703d4.png)

Above image is perfect view of my graph but after using the above method and a lower value comes it will shift towards top edge of device. It should automatically adjust the center point of graph.

Please guide me to resolve this issue.

Thanks

**Comment by sayoojvalsan-demandmedia** [comment]
I have the same issue. Looking for a solution. Let me know if you did find any

**Comment by himanshu1706** [comment]
I have used 

YAxis y = mChart.getAxisLeft();
y.setAxisMaxValue(600);
y.setAxisMinValue(-600);

to stop the y axis scrolling.

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart

setDragEnabled(false)
