### ISSUE TITLE
Line chart filling bug

### ISSUE THREAD

**Issue by aint** [PhilJay/MPAndroidChart#1186]
2.1.6 
![2015-11-06 20 44 34](https://cloud.githubusercontent.com/assets/3179252/11006123/aba71566-84ca-11e5-80bf-4330d2402c10.png)

2.1.3
![2015-11-06 21 05 34](https://cloud.githubusercontent.com/assets/3179252/11006114/a446c028-84ca-11e5-8123-8458a1d92139.png)

**Comment by NasaGeek** [comment]
Possibly related to #1064  
Also see #1100 for a workaround (disabling HW acceleration for the chart)

**Comment by PhilJay** [comment]
Should be fixed now.
