### ISSUE TITLE
Chart Scrolling the data from right to left

### ISSUE THREAD

**Issue by ranjithnaidu** [PhilJay/MPAndroidChart#1188]
I'm Building a barchart using MpAndroid chart library, i've around 50 - 60 bars and wanted to display the 60th initially i.e. display the last element in the ArrayList and the scroll should be from right to Left.

Main motive is to display the end of the chart during the initial load of the chart barchart.

Thanks in Advance.
@PhilJay please help me with this..

**Comment by PhilJay** [comment]
Take a look at the `moveViewToX(...)` and `setVisibleXRangeMaximum(...)` methods of the chart: https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport

**Comment by shadygoneinsane** [comment]
Hey I am trying to fix the VisibleXRangeMaximum to a value 'x' and that works very well but how do I get the view to scroll on x axis to see the other points on line chart along x axis that are hidden now ?

**Comment by Karthick-Ramanathan** [comment]
hey how to scroll the view in x direction , cannot scroll and items goes off the screen

**Comment by raghunandankavi2010** [comment]
@Karthick-Ramanathan  found any answers?
