### ISSUE TITLE
Problem with setDrawFilled(true) when drawing atmosferic pressure

### ISSUE THREAD

**Issue by ogromis** [PhilJay/MPAndroidChart#1189]
Hello Mr. Phill,

I have one problem with “setDrawFilled(true);” method. I work with version mpandroidchartlibrary-2-1-1. When I draw chart for temperature, humidity or battery voltage all is OK (bottom example for temperature):

leftAxis.setStartAtZero(true);
leftAxis.setAxisMaxValue(t_max_day + 7);
leftAxis.setAxisMinValue(0);

![temperature_lib_v_2_1_1](https://cloud.githubusercontent.com/assets/15679998/11032777/65b5cbf4-86de-11e5-8ee0-74e03b7eda50.jpg)

Unortunately chart for atmosferic pressure draw without filled under line chart:
leftAxis.setStartAtZero(false);
leftAxis.setAxisMaxValue(p_max_day + 7);
leftAxis.setAxisMinValue(p_min_day - 7);

![pressure_lib_v_2_1_1_shortrange](https://cloud.githubusercontent.com/assets/15679998/11032800/a891f7c2-86de-11e5-93c9-7bc6300007cf.jpg)

When I set a wider range for Yaxis pressure chart is drawing correctly:
leftAxis.setStartAtZero(false);
leftAxis.setAxisMaxValue(960);
leftAxis.setAxisMinValue(1030);

![pressure_lib_v_2_1_1_widerange](https://cloud.githubusercontent.com/assets/15679998/11032819/d1aff082-86de-11e5-9320-94d104ef36d6.jpg)

In the latest version of mpandroidchartlibrary (2-1-7) is there another problem. Filled is drawing from maximum value in chart.  Bellow are examples for temperature and pressure:
![temperature_library_v_2_1_7](https://cloud.githubusercontent.com/assets/15679998/11032833/f25b7df6-86de-11e5-8089-55357514c188.jpg)

![pressure_library_v_2_1_7](https://cloud.githubusercontent.com/assets/15679998/11032835/fb4748f0-86de-11e5-8788-9cbbf5c6e72e.jpg)

I tried also drawing plot with library version created by tinsukE (https://github.com/tinsukE/MPAndroidChart) but results are the same as in mpandroidchartlibrary version 2-1-7.
Can you advise something? Thank you.

**Comment by ogromis** [comment]
Hello,

I read now issue  "LineChart fill rendering not working for API < 18 #1100" - https://github.com/PhilJay/MPAndroidChart/issues/1100 and I read about programmatically enable/disable hardware-acceleration: chart.setHardwareAccelerationEnabled(boolean enabled). In my case it helped :) I tested this for API 16 and 17 (for mpandroidchartlibrary-2-1-1 and mpandroidchartlibrary-2-1-6). Thank you.

**Comment by PhilJay** [comment]
How did disabling HW-acceleration affect performance?
I might have to think of a different solution for this.

**Comment by ogromis** [comment]
Disabling hardware acceleration in my opinion did not affect the performance. I made also a little test. Before and after chart.invalidate I got time (in milisec). Then I compared these two results and difference was 0ms.

**Comment by PhilJay** [comment]
Okay, thats good. How many values are you plotting and how long did it take?

**Comment by ogromis** [comment]
I have 288 samples (one sample per 5 min). After downloading data from the server to array I set:
1. the range for the Y-axis
2. line style, color, etc
3. set the line dataset
4. then I plot the draw

Time for this 4 steps is about 3-4ms also when hardware acceleration is disabled.

**Comment by PhilJay** [comment]
Okay, thats good. Thank you
