### ISSUE TITLE
Remove unnecessary margins when axis are disable

### ISSUE THREAD

**Issue by eSoares** [PhilJay/MPAndroidChart#1190]
I don't know if is a bug or not, but I'm trying to build a chart that will have zero margin on the left (left and right axis disable).

I'm unable to remove the left and right padding, is there any option that i'm missing?

My current work looks like this:
![margin_bugs](https://cloud.githubusercontent.com/assets/1862296/11037460/b8218894-86f5-11e5-9bc5-5d6b4cf7f086.png)

My view looks like this:
```
    <com.github.mikephil.charting.charts.LineChart
        android:id="@+id/chart"
        android:layout_width="fill_parent"
        android:layout_height="220dp"
        android:layout_margin="0dp"
        android:padding="0dp"
        />
```
And the code:
```
chart = (LineChart) getView().findViewById(R.id.chart);

chart.setData(data);

chart.getXAxis().setEnabled(false);
chart.getAxisLeft().setEnabled(false);
chart.getAxisRight().setEnabled(false);

chart.getAxisRight().setDrawGridLines(false);
chart.getAxisLeft().setDrawGridLines(false);
chart.getAxisRight().setStartAtZero(false);
chart.getAxisLeft().setStartAtZero(false);
chart.setDrawGridBackground(false);

chart.getXAxis().setAvoidFirstLastClipping(true);
chart.getXAxis().setDrawGridLines(false);

chart.getLegend().setEnabled(false);

chart.setVisibleXRangeMaximum(5); // allow 5 values to be displayed at once on the x-axis, not more
chart.setVisibleXRangeMinimum(2); // allow 5 values to be displayed at once on the x-axis, not less
chart.setDragOffsetX(10);


chart.setBackgroundColor(Color.TRANSPARENT);

chart.setTouchEnabled(true);

chart.setDragEnabled(true);
chart.setScaleYEnabled(false);
chart.setScaleXEnabled(true);



chart.setDescription(null);
chart.setExtraTopOffset(10f);

chart.setDrawBorders(false);

chart.animateY(2000);

chart.invalidate();
chart.moveViewToX(chart.getLineData().getXValCount() - 5);
```

Thanks in advance.

**Comment by PhilJay** [comment]
Check this out: https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport

`setViewPortOffsets(...)` might be what you are looking for.
You can also see it in action in the example project here: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/LineChartActivityColored.java

**Comment by DasCody** [comment]
Hey @PhilJay that worked for me, calling `.setViewPortOffsets(4f, 4f, 4f, 4f);` removed the margins entirely. Thanks for creating such a robust library :)

**Comment by jaredsburrows** [comment]
@PhilJay @DasCody Thanks for that!

**Comment by SaurabhSawarkar** [comment]
I am using LineChart and my x-axis starts from 0 count of y-axis. Zero of y-axis and x-axis labels are too close to each other. How can i add some space in the beginning of x-axis?

**Comment by Connerium** [comment]
Hey, it works with the viewport, but not with the xAxis label.

**Comment by Werder630** [comment]
setMinOffset(0f)
