### ISSUE TITLE
OnChartGestureListener for multiple charts

### ISSUE THREAD

**Issue by urospodkriznik** [PhilJay/MPAndroidChart#1191]
Hi,
I generate multiple charts dynamically in one activity. I would like to have a GestureListener which would trigger a Dialog in which I could change that chart (ex.) from pieChart to barChart (similar like in SurveyMonkey).

Is it possible to have 1 OnChartGestureListener for all charts? From the example I see "mChart" is a global variable which is then called in (for example) onChartSingleTapped function. But how can I get a dynamically created chart from which a guesture was triggered?

Is this possible to achive? How?

Thanks in andvance!

**Comment by PhilJay** [comment]
I'm not sure I understand :-)

**Comment by urospodkriznik** [comment]
Ok. Sorry for my bad english.

I have an activity with multiple charts and all charts have diferent dataset. I am makeing those charts programmatically - in java, not xml. I want to have setOnChartGestureListener on all those charts and when onChartSingleTapped is triggered, I want to change Chart (lets say from PieChart to BarChart) but with old dataset. How can I get chart (and its dataset), on wich user taped it once?
Should I provide some code and example?

Thanks for quick replay!

**Comment by CoryCharlton** [comment]
You could supply the chart you are attaching the `OnChartGestureListener` to in the constructor.

    private class ChartGestureListener implements OnChartGestureListener {
        private final Chart mChart;

        public ChartGestureListener(Chart chart) {
            mChart = chart;
        }
        ...
        @Override
        public void onChartSingleTapped(MotionEvent me) {
            final ChartData dataSet = mChart.getData();
            // Do something with the data...
        }
    }

**Comment by urospodkriznik** [comment]
Of course, you are right.
Thank you!
