### ISSUE TITLE
How to add vertical dashed gridlines?

### ISSUE THREAD

**Issue by alexandrastockman88** [PhilJay/MPAndroidChart#1196]
Hi, first of all, thank you for a great library!:)
I just have one problem, I want the vertical gridlines to be dashed. At the moment the vertical lines are not dashed, they are just "regular" lines.
This is what I've tried:

       XAxis xAxis = mBarChart.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setDrawAxisLine(false);
        xAxis.setDrawGridLines(true);
        xAxis.enableGridDashedLine(10f, 10f, 10f);
        ....
        YAxis leftAxis = mBarChart.getAxisLeft();
        leftAxis.setDrawAxisLine(false);
        leftAxis.setDrawGridLines(true);
        leftAxis.enableGridDashedLine(10f, 10f, 10f);
        leftAxis.setEnabled(false);

    
        YAxis rightAxis = mBarChart.getAxisRight();
        rightAxis.setDrawGridLines(true);
        rightAxis.setDrawAxisLine(false);
        rightAxis.enableGridDashedLine(10f, 10f, 10f);
        rightAxis.setEnabled(false);

What am I missing?
Thank you in advance!

**Comment by PhilJay** [comment]
Actually you did not miss anything :-)
It should work just like that. 

 - Which library version are you using?
 - Wich android version are you running?

**Comment by alexandrastockman88** [comment]
Ok :)

I thought that I had the latest version of your project, but when I now looked in the gradle build file I saw that I'm using version 1. Maybe that's the problem?:)
(I've actually downloaded the project from github, and I'm using it as a module dependency because I needed to change the design of the stacks in the graph. I've just made the corners of the stacks in the graph rounded.)

The android version I use currently is 19. But I need to support versions 8-22.
Thanks in advance!

**Comment by PhilJay** [comment]
Yes, that could be the problem. Please try the latest version!

**Comment by alexandrastockman88** [comment]
I now have the latest version (v2.1.6) but the problem remains. Any ideas?

**Comment by iChon** [comment]
How do you resolve it?
