### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by faizandedia** [PhilJay/MPAndroidChart#1197]
Getting out of memory exception after drawing chart more than 30 times

threadid=1: thread exiting with uncaught exception (group=0x41738c08)
D/Crash Analytics(12499): java.lang.OutOfMemoryError
D/Crash Analytics(12499): 	at android.graphics.Bitmap.nativeCreate(Native Method)
D/Crash Analytics(12499): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:903)
D/Crash Analytics(12499): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:880)
D/Crash Analytics(12499): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:847)
D/Crash Analytics(12499): 	at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:85)
D/Crash Analytics(12499): 	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:230)
D/Crash Analytics(12499): 	at android.view.View.draw(View.java:15312)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14206)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14248)
D/Crash Analytics(12499): 	at android.view.View.draw(View.java:15026)
D/Crash Analytics(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
D/Crash Analytics(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
D/Crash Analytics(12499): 	at android.view.View.draw(View.java:15315)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14206)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14248)
D/Crash Analytics(12499): 	at android.view.View.draw(View.java:15026)
D/Crash Analytics(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
D/Crash Analytics(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14201)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14248)
D/Crash Analytics(12499): 	at android.view.View.draw(View.java:15026)
D/Crash Analytics(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
D/Crash Analytics(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14201)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14248)
D/Crash Analytics(12499): 	at android.view.View.draw(View.java:15026)
D/Crash Analytics(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
D/Crash Analytics(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14201)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14248)
D/Crash Analytics(12499): 	at android.view.View.draw(View.java:15026)
D/Crash Analytics(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
D/Crash Analytics(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
D/Crash Analytics(12499): 	at android.view.View.draw(View.java:15315)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14206)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14248)
D/Crash Analytics(12499): 	at android.view.View.draw(View.java:15026)
D/Crash Analytics(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
D/Crash Analytics(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14201)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14248)
D/Crash Analytics(12499): 	at android.view.View.draw(View.java:15026)
D/Crash Analytics(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
D/Crash Analytics(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
D/Crash Analytics(12499): 	at android.view.View.draw(View.java:15315)
D/Crash Analytics(12499): 	at android.widget.FrameLayout.draw(FrameLayout.java:472)
D/Crash Analytics(12499): 	at android.widget.ScrollView.draw(ScrollView.java:2156)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14206)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14248)
D/Crash Analytics(12499): 	at android.view.View.draw(View.java:15026)
D/Crash Analytics(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
D/Crash Analytics(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
D/Crash Analytics(12499): 	at android.view.View.draw(View.java:15315)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14206)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14248)
D/Crash Analytics(12499): 	at android.view.View.draw(View.java:15026)
D/Crash Analytics(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
D/Crash Analytics(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14201)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14248)
D/Crash Analytics(12499): 	at android.view.View.draw(View.java:15026)
D/Crash Analytics(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
D/Crash Analytics(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14201)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14248)
D/Crash Analytics(12499): 	at android.view.View.draw(View.java:15026)
D/Crash Analytics(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
D/Crash Analytics(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14201)
D/Crash Analytics(12499): 	at android.view.View.getDisplayList(View.java:14248)
D/Crash Analytics(12499): 	at android.view.View.draw(View.java:15026)
D/Crash Analytics(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
D/Crash Analytics(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
D/Crash Analytics(12499): 	at android.view.View.getDi
E/AndroidRuntime(12499): FATAL EXCEPTION: main
E/AndroidRuntime(12499): Process: com.deg.mdubai, PID: 12499
E/AndroidRuntime(12499): java.lang.OutOfMemoryError
E/AndroidRuntime(12499): 	at android.graphics.Bitmap.nativeCreate(Native Method)
E/AndroidRuntime(12499): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:903)
E/AndroidRuntime(12499): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:880)
E/AndroidRuntime(12499): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:847)
E/AndroidRuntime(12499): 	at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:85)
E/AndroidRuntime(12499): 	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:230)
E/AndroidRuntime(12499): 	at android.view.View.draw(View.java:15312)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14206)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14248)
E/AndroidRuntime(12499): 	at android.view.View.draw(View.java:15026)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
E/AndroidRuntime(12499): 	at android.view.View.draw(View.java:15315)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14206)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14248)
E/AndroidRuntime(12499): 	at android.view.View.draw(View.java:15026)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14201)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14248)
E/AndroidRuntime(12499): 	at android.view.View.draw(View.java:15026)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14201)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14248)
E/AndroidRuntime(12499): 	at android.view.View.draw(View.java:15026)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14201)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14248)
E/AndroidRuntime(12499): 	at android.view.View.draw(View.java:15026)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
E/AndroidRuntime(12499): 	at android.view.View.draw(View.java:15315)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14206)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14248)
E/AndroidRuntime(12499): 	at android.view.View.draw(View.java:15026)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14201)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14248)
E/AndroidRuntime(12499): 	at android.view.View.draw(View.java:15026)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
E/AndroidRuntime(12499): 	at android.view.View.draw(View.java:15315)
E/AndroidRuntime(12499): 	at android.widget.FrameLayout.draw(FrameLayout.java:472)
E/AndroidRuntime(12499): 	at android.widget.ScrollView.draw(ScrollView.java:2156)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14206)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14248)
E/AndroidRuntime(12499): 	at android.view.View.draw(View.java:15026)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
E/AndroidRuntime(12499): 	at android.view.View.draw(View.java:15315)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14206)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14248)
E/AndroidRuntime(12499): 	at android.view.View.draw(View.java:15026)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14201)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14248)
E/AndroidRuntime(12499): 	at android.view.View.draw(View.java:15026)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14201)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14248)
E/AndroidRuntime(12499): 	at android.view.View.draw(View.java:15026)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3144)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14201)
E/AndroidRuntime(12499): 	at android.view.View.getDisplayList(View.java:14248)
E/AndroidRuntime(12499): 	at android.view.View.draw(View.java:15026)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3307)
E/AndroidRuntime(12499): 	at android.view.ViewGroup.disp

**Comment by PhilJay** [comment]
What do you mean by "drawing the chart 30 times"? Do you have 30 chart views?

**Comment by faizandedia** [comment]
No, just refreshing graph view with different data

**Comment by brcinho** [comment]
I am also experimenting the same issue. On my dashboard fragment, I have two pie charts and one bar chart. User is often navigated back to dashboard and in memory profiler in Android studio I see that each time additional three MB get allocated, when I navigate to some other Fragment from it, those MB don't get garbage collected.

I even put 

 @Override
    public void onStop()
    {
        if (totalCountChart != null)
        {
            pieChartLocations.clearAllJobs();
            totalCountChart.clearAnimation();
            totalCountChart.clear();
            totalCountChart = null;
        }
        if (pieChartLocations != null)
        {
            pieChartLocations.clearAllJobs();
            pieChartLocations.clearAnimation();
            pieChartLocations.clear();
            pieChartLocations = null;
        }
        if (pieChartItems != null)
        {
            pieChartLocations.clearAllJobs();
            pieChartItems.clearAnimation();
            pieChartItems.clear();
            pieChartItems = null;
        }

        super.onStop();
        System.gc();
    }

in my dashboard fragment, but it doesn't help.

Later I traced that in your DataRenderers you have bitmap fields and somewhere in between version 2.1.4 and version 2.1.6 the method  the new method

public void releaseBitmap() {
        if (mDrawBitmap != null) {
            mDrawBitmap.recycle();
            mDrawBitmap = null;
        }
    }

was introduced in but I don't think it gets called anywhere, maybe I am wrong.

The problem is that I see that Bitmap.createBitmap in memory tracer takes those around three MB, and I think that the releaseBitmap should be called somewhere in chart.clear() method

**Comment by jaredsburrows** [comment]
@faizandedia What version?

**Comment by brcinho** [comment]
In my case 2.1.6
