### ISSUE TITLE
Need show markerview automatically  when point is in the middle of screen

### ISSUE THREAD

**Issue by razester** [PhilJay/MPAndroidChart#1198]
Is it possible to show data of point when its in the center of device screen? The graph will be scrolling and automatically showing data of points. Thanks

**Comment by CoryCharlton** [comment]
You can highlight values programmatically with the `highlightValue` or `highlightValues` methods: https://jitpack.io/com/github/PhilJay/MPAndroidChart/v2.1.5/javadoc/com/github/mikephil/charting/charts/Chart.html#highlightValue(int,%20int)

To clear existing highlights pass null to `highlightValues`.
