### ISSUE TITLE
Support for x values (instead of x indices)

### ISSUE THREAD

**Issue by onyame** [PhilJay/MPAndroidChart#12]
Thanks for your great library!

We just found one major drawback. We like to draw a time series chart where the values are not equidistant. The x values where points are drawn must be at any position not just distributed equally by index. For example, the x axis represents the date and time (as in this blood pressure chart http://www.andreas-schreiber.net/activities/quantified-self/blood-pressure/).

This applies to line chart and scatter chart.

**Comment by nekdenis** [comment]
Thanks for cool library! 
Maybe anyone already make this feature possible? 
@PhilJay Are you working on this feature ? I've got some ideas how to make it real.

**Comment by dowi** [comment]
+1, I am looking for the same feature as well

**Comment by rajatdeshpande** [comment]
Hi Guys, 

@nekdenis - Could you please discuss the ideas here, I would be glad to contribute using your ideas :)

Thanks,

**Comment by Ploppy3** [comment]
+1 same here

**Comment by medy75** [comment]
+1

**Comment by rajatdeshpande** [comment]
+1

**Comment by bhspencer** [comment]
+1

**Comment by bhspencer** [comment]
I am looking for an android equivalent to to vis.js graph2d http://visjs.org/graph2d_examples.html

**Comment by TR4Android** [comment]
+1

**Comment by nekdenis** [comment]
https://github.com/nekdenis/MPAndroidChart/tree/decart
I've implemented this feature. But here are one bad thing: I'm not using existed data model. 
If someone need example usage of this graph I could add it.

**Comment by jurrik** [comment]
+1

**Comment by Robyer** [comment]
+1

**Comment by webventil** [comment]
+1

**Comment by johannes82** [comment]
+1

**Comment by dhofmann404** [comment]
+1

**Comment by idellwig** [comment]
+1

**Comment by burix** [comment]
+1 man come on it is awesome!!!

**Comment by enffichris** [comment]
Indeed this would make this library the best! Otherwise it already excels

**Comment by mathieudebrito** [comment]
+1

**Comment by rajatdeshpande** [comment]
+1

On Tue, Apr 21, 2015 at 3:23 PM, Mathieu De Brito <notifications@github.com>
wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PhilJay/MPAndroidChart/issues/12#issuecomment-94724753>
> .
>



-- 
Rajat Deshpande
Mechanical Engineering
IIT BOMBAY

**Comment by FranzBusch** [comment]
+1

**Comment by SoftwareRancher** [comment]
+1

I was really impressed with the capabilities of MPAndroidChart but since it's not possible to enter data as (x,y) pairs I can't use it.  My application has real-time time-series data with irregular/unpredictable time coordinates for each measurement.

**Comment by enffichris** [comment]
@SoftwareRancher You should be able to do this. You can use e.g. a unix-timestamp type of datasystem.

**Comment by SoftwareRancher** [comment]
It looked to me (from the API) that the "x values" were basically labels 
and would not affect the position of the data on the graph.  I need a 
set of data points such as

(0, 1), (45,1), (50, 2), (55, 1), (100, 1)

to appear like:





On 04/27/2015 02:52 PM, enffichris wrote:
>
> @SoftwareRancher <https://github.com/SoftwareRancher> You should be 
> able to do this. You can use e.g. a unix-timestamp type of datasystem.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PhilJay/MPAndroidChart/issues/12#issuecomment-96816398>.
>


-- 
Jim

**Comment by SrMouraSilva** [comment]
+1

**Comment by matejcikm** [comment]
+1

**Comment by wangningdy** [comment]
+1

**Comment by marcfrost** [comment]
+ 1

**Comment by rascheC** [comment]
+1
any news?

**Comment by arkanus** [comment]
+1

**Comment by fountaingeyser** [comment]
:+1: @PhilJay @danielgindi Thanks for the great library! Yet this feature would make it perfect. So I (and I thank many others too) would really appreciate it if this feature would come any time soon... 
Please keep us posted. Thanks a lot!

**Comment by enffichris** [comment]
Considering the considerable amount of people requiring this feature. Would it make sense to crowdfund it? How much would be required - if that's an option at all for you @PhilJay

**Comment by puuro** [comment]
+1
@nekdenis 
Can you add an example usage of your graph. I didn't find it anywhere.

**Comment by LucasMoody** [comment]
+1

**Comment by biftekman** [comment]
+1

**Comment by mathieudebrito** [comment]
YES WAY ?

--
Mathieu de Brito
www.mathieudebrito.fr <http://mathieudebrito.fr>
Fr : +33 6 87 36 74 78

**Comment by SergioEscuder** [comment]
+1

**Comment by aorbegozo005** [comment]
The library is great. I am using it on my final degree project and I would love to use this feature.
 
Currently I found a way to use it with not equidistant values even with large values (I tested up to 30000 and there is no problem as the strings are created dynamically) but when you zoom in, the lines on the edges sometimes get invisible https://github.com/PhilJay/MPAndroidChart/issues/801.

In case someone is interested this is the class I use to replace the strings array: 

The other methods that needs to be implemented from List<String> are left with the default implementation:
```java
public class MaxList implements List<String> {

    private int max;

    public MaxList(){
        max = 0;
    }

    @Override
    public void clear() {
        max = 0;
    }

    @Override
    public String get(int i) {
        if (i<1000){
            return String.valueOf(i) + "m";
        }else{
            return String.valueOf(i/1000)+","+String.valueOf(i%1000)+"km";
        }
    }

    @Override
    public int size() {
        return max+1;
    }

    public void addMax(int new_max){
        if (new_max > max){
            max = new_max;
        }
    }

    @Override
    public boolean isEmpty() {
        return false;
    }
}
```

Remember to set the max value of your data.

Hope it helps someone and thanks for the great library!

**Comment by sowrabh** [comment]
+1, this is a much needed feature. Would be happy to contribute.

**Comment by subhanshuja** [comment]
+1

**Comment by forkch** [comment]
+1

**Comment by micnguyen** [comment]
+1 Huge missing use case. Has anyone bolted on this functionality in a nice way?

**Comment by bomiyr** [comment]
+1

**Comment by Mashnin** [comment]
+1

**Comment by knseir** [comment]
+1

**Comment by prabel** [comment]
+1

**Comment by Brian0122** [comment]
＋1

**Comment by doom369** [comment]
+1

**Comment by prateekdwv** [comment]
+1 for this feature
That's exactly what I was looking for.

**Comment by forum6691** [comment]
+1 for this feature which will have multiple applications to display various scientific data.

**Comment by amandeepgautam** [comment]
+1 for the feature

**Comment by knseir** [comment]
@PhilJay Hi Philipp, any news on this ?

**Comment by alexpell00** [comment]
+1

**Comment by ranj27** [comment]
Is this feature available yet?I am looking for such time series as well. Wonderful library

**Comment by zdesiree** [comment]
+1

**Comment by zjuhasz** [comment]
Yep +1! Please save us @PhilJay

**Comment by JohanCosemans** [comment]
+1 for this feature

**Comment by funkvps** [comment]
Hello, could you please add examples for this? @nekdenis

**Comment by mehdi-shiba** [comment]
Using the great port of this already great library on iOS. Would love to have support for XY charts!

**Comment by mohitagrawal** [comment]
+1 This would be a great improvement to the library. XY coordinate is kind of basic of graphing system and its sad that this library doesn't support that.

**Comment by adek** [comment]
Yes. I hope you'll  be able to add timeseries in future. 
I've switched to your library and this is something that is missing. Previously I've been using aChartEngine.

At the moment I'm using simple indexing method. I've got only days so it's pretty simple. But probably there is a better way of doing that.

**Comment by cerebrahm** [comment]
+1 for this feature. It is indeed a great library. Would love to see support for float values in x axis.

**Comment by ff0o0** [comment]
I have the same question. So i change my x values to be equidistant and set to x Axis. Although it looks 
work, the callback OnChartValueSelectedListener.onValueSelected can't be called exactly. I'm still finding solution.

**Comment by binujayaram** [comment]
+1

**Comment by Overholt94** [comment]
+1

**Comment by tripplemac** [comment]
+1

**Comment by mat90c** [comment]
+1

**Comment by ildar2244** [comment]
which chart to use for this?
![how_draw_this_chart](https://cloud.githubusercontent.com/assets/12645841/13180243/ae2617e0-d738-11e5-8453-c4785f24fe38.png)

**Comment by refaelsh** [comment]
+1

**Comment by apatrone** [comment]
+1

**Comment by rlimberger** [comment]
We are also just starting to integrate iOS Charts, great library, thank you. We are running into this limitation as well. We have xValues like 0, 0.2, 3, 5.75, 6.5, 10, 40, 66.7. Using the workaround described, we would have to have xValues every 0.1 steps, which would be a lot, to cover a range of 0-600 for example. 

Any news on this feature or some other work around that performs well at larger numbers of values? 

Thanks.

**Comment by plusCubed** [comment]
@PhilJay I think, as a first step, the graph should respect the x-indices put into `Entry`. It could do this by automatically splitting the graph into [highest x-index] number of increments, then plotting the sparse array of x-indices. 

That would allow for relative x-value positioning without instantiating large arrays, which I think is adequate for the majority of use cases here. The drawback is the labels are still attached to the x-indices, as opposed to an actual xy Cartesian graph, but this solution would still be much better than what is available currently.

**Comment by MGasztold** [comment]
+1 this feature is extra needed

**Comment by binujayaram** [comment]
HI friends, I prepared a simple solution for this. Please refer https://github.com/binujayaram/LogarithmicGraphForAndroid.

**Comment by RyGuyM** [comment]
+1

**Comment by cgathergood** [comment]
+1

**Comment by mazzonem** [comment]
+1

**Comment by stevekelly20** [comment]
+1

**Comment by sschale** [comment]
+1

**Comment by johnfrey99** [comment]
+1

**Comment by dalewking** [comment]
+1

**Comment by MarioGravel** [comment]
+1 I'm logging data from events so the xAxis is variable and time based.

**Comment by Philipp2405** [comment]
+1
Great library!
I would really appreciate this feature too.

**Comment by Datalization** [comment]
+1

**Comment by MonStar1** [comment]
+1

**Comment by TeunKooijman** [comment]
+1

**Comment by marcio-granzotto-ckl** [comment]
+1 @PhilJay

**Comment by shohiebsense** [comment]
in the name of mankind sir, +1

**Comment by biovolt** [comment]
+1

**Comment by PhilJay** [comment]
Within the next few weeks v3.0.0 of this library with major changes will be released which is finally going to close this issue, stay tuned :-)

**Comment by forum6691** [comment]
Information very interesting :)
Cyril

Le 10/06/2016 à 16:05, Philipp Jahoda a écrit :
>
> Within the next few weeks v3.0.0 of this library with major changes 
> will be released which is finally going to close this issue, stay 
> tuned :-)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/PhilJay/MPAndroidChart/issues/12#issuecomment-225190713>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ALlmhbwUpwdiXXW4GqTb0JW68yoycplIks5qKW8WgaJpZM4CN54o>.
>


-- 
Des logiciels Android à découvrir:

Pour la sécurité de votre bateau
MarineSecurity et MarineSecurityMap : http://marinesecurity.free.fr

Pour la mesure de votre vitesse et l'optimisation de vos performances à moto/ski, voiture ou en bateau
SpeedMeter : http://androidapp.free.fr

**Comment by FabianTerhorst** [comment]
@PhilJay this branch https://github.com/PhilJay/MPAndroidChart/tree/remove_xindices ?

**Comment by rlimberger** [comment]
This issue being closed, does this mean that the master branch has this implemented now?

**Comment by PhilJay** [comment]
Yes, & the latest release.

**Comment by FabianTerhorst** [comment]
@androidhopeful check out the updated samples

**Comment by androidhopeful** [comment]
@FabianTerhorst  I had tried that (using `data.add(new Entry(timestamp, (float)value));` but it doesn't seem to be parsing the times correctly. Maybe because the timestamp is being processed as a float rather than as a long?

**Comment by androidhopeful** [comment]
Is there a way to allow newlines in the x-axis labels? As a result of switching to the new date format, there's now a great deal of text crowding unless I manually set xAxis.setLabelCount() to something very small (like 3).

**Comment by PhilJay** [comment]
It does not work for you because the `Entry` constructor changed as mentioned in the release notes.

Its now `Entry(float x, float y)`
instead of `Entry(float y, int xIndex)`

**Comment by Praveen2106** [comment]
TimeStamp to Date format conversion can be done using AxisValueFormatter. (@Phil, correct if am wrong)

 But does getFormattedValue() supports new line character?.

This issue https://github.com/PhilJay/MPAndroidChart/issues/73 is still open.Allowing new line character reduces the label length and allows more labels in XAxis.

**Comment by androidhopeful** [comment]
@PhilJay I got that to work, yes, but using float for timestamp means you lose precision and get incorrect times

**Comment by FabianTerhorst** [comment]
@androidhopeful we aren´t as far with the timestamp to loose data there when converting the timestamp long to a float.

**Comment by androidhopeful** [comment]
@FabianTerhorst The minute level is where it begins to lose precision from what I can tell

**Comment by FabianTerhorst** [comment]
@androidhopeful with a timestamp thats in seconds that shouldn´t be the case.

**Comment by PhilJay** [comment]
Exactly, you can simply use "second" timestamps and then multiply them by 1000 when using them with a java `Date` object.

**Comment by Robyer** [comment]
Why not allow using double instead of float?

**Comment by androidhopeful** [comment]
@PhilJay I don't doubt that there are good reasons for using float, but forgive me if I say that it is not obvious (nor do I see it listed anywhere) how to use a second timestamp for formatting, let alone one that will still allow proper ordering and spacing in the actual data itself. Are you saying to include two timestamps per Entry-- one with seconds removed (divide by 60000, multiply by 60000), and one that is seconds only (x000), and then somehow later combine the two into a long to get the "correct" time?

**Comment by androidhopeful** [comment]
@PhilJay Is there a workaround to allow newlines in the X-axis labels?

**Comment by androidhopeful** [comment]
BTW: The multiply by 1000 trick does not work because everything else in the graph (i.e. non-points) is still being compressed at /1000, so every point gets forced onto a single x-value.

**Comment by srinivasan-cgvak** [comment]
Please share your sample to set the date and time value in X-Axis. Now it's not working fine when i tried to convert date object to float (For Entry)and vice versa(AxisValueFormatter). I required this option for most dynamic moving chart based on limited interval like 30sec,60sec. I have spent lots of time on it but till now no success.

**Comment by rlimberger** [comment]
Thank you for adding this feature. Is there an example on how to use this new feature?

**Comment by lkkjohnny** [comment]
how to set YAxis accuracy 0.01 in mpandroidchart -LineChart ?

**Comment by gokulbalakrishnan** [comment]
![screenshot_1517308668](https://user-images.githubusercontent.com/33621243/35561930-d998c150-05d7-11e8-81ba-f9ce0bba00b0.png)
Facing the same issue

**Comment by Hetal2011** [comment]
+1, I am looking for the same feature as well
