### ISSUE TITLE
How to focus/scale to a specific range of x-values?

### ISSUE THREAD

**Issue by ludriv** [PhilJay/MPAndroidChart#120]
Hi Phil,

How can I adjust zoom to display specific range of x-values with animation if possible?
Here an example: 
I have a line chart with data on x-axis from 0 to 1000 and I want to adjust zoom to see 10 to 100 on the whole width.

Regards,

**Comment by AmberKCopper** [comment]
one question what condition to be checked if user pinches zoom in or out so that i can do all the above methods to refresh chart

**Comment by AmberKCopper** [comment]
and also limit zoom till particular values.

**Comment by AmberKCopper** [comment]
okay i have doubt how to limit zoom to particular scale so till daily values cant refresh chart or zoom further

**Comment by chiragintersoft** [comment]
How I can set max zoom limit along xAxis?

**Comment by saravananmnm** [comment]
### **X and Y axis values are not set properly. i am using version  'com.github.PhilJay:MPAndroidChart:v3.0.3 in android'**
` if (!UIUtils.isEmpty(mModel.getChartData())) {
            for (String lists : mModel.getChartData().split(",")) {
                if (lists != null) {
                    String[] str = lists.split(":");
                    mXAxisNames.add(str[0]);
                    mYAxisNames.add(str[1]);
                }
            }
            float count = mYAxisNames.size();
            ArrayList<BarEntry> yvalues = new ArrayList<>();
            for (int i = 0; i < mYAxisNames.size(); i++) {
                yvalues.add(new BarEntry(i, Float.parseFloat(mYAxisNames.get(i))));
            }
            BarDataSet dataSet = new BarDataSet(yvalues, "");
            dataSet.setColors(Utils.getBarChartColors());
            dataSet.setValueFormatter(new MyvalueFormatter());

            BarData data = new BarData(dataSet);
            data.setValueTextSize(10f);
            data.setBarWidth(0.9f);
            data.setValueTextColor(Color.DKGRAY);

            float minValue = data.getYMin();
            float maxValue = data.getYMax();
            //Initial values for Y axis
            int yMax = (int) maxValue + 1;
            int yMin = (int) minValue - 1;

            XAxis xAxis = mBinding.barChart.getXAxis();
            xAxis.setGranularity(1f);
            xAxis.setDrawGridLines(false);
            xAxis.setDrawAxisLine(true);
            xAxis.setDrawLabels(true);
            xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
            xAxis.setValueFormatter(new MyAxisValueFormatter(mXAxisNames));
//Y-axis
            mBinding.barChart.getAxisRight().setEnabled(false);
            mBinding.barChart.getAxisLeft().setEnabled(true);
            YAxis leftAxis = mBinding.barChart.getAxisLeft();
            leftAxis.setValueFormatter(new MyYAxisValueFormatter());
            leftAxis.setDrawGridLines(true);
            leftAxis.setDrawLabels(true);
            leftAxis.setSpaceTop(10f);
            leftAxis.setAxisMinimum(0f);
            leftAxis.setAxisMaximum(yMax);
            leftAxis.setLabelCount((int) count,true);

            // Default value
            mBinding.barChart.setDrawBarShadow(false);
            mBinding.barChart.setTouchEnabled(false);
            mBinding.barChart.setDrawValueAboveBar(true);
            mBinding.barChart.setPinchZoom(false);
            mBinding.barChart.setScaleEnabled(false);
            mBinding.barChart.setDescription(null);
            mBinding.barChart.setVerticalScrollBarEnabled(false);
            mBinding.barChart.setHorizontalScrollBarEnabled(false);
            mBinding.barChart.setDrawGridBackground(false);
            mBinding.barChart.setDoubleTapToZoomEnabled(false);
            mBinding.barChart.setData(data);
            mBinding.barChart.setFitBars(true);
            mBinding.barChart.setAutoScaleMinMaxEnabled(true);
            mBinding.barChart.animateXY(1000, 1000);
            mBinding.barChart.invalidate();
        }
![screenshot_20181212-175338](https://user-images.githubusercontent.com/23417457/49871693-e9df0480-fe3c-11e8-90bf-5459233f8aaf.png)
`
