### ISSUE TITLE
Is it possible to fill a ```LineDataSet``` with negative indices?

### ISSUE THREAD

**Issue by ahasbini** [PhilJay/MPAndroidChart#1203]
I'm filling the ```LineDataSet``` with negative indices crossing over 0 index and continuing to a positive index such that the index 0 is the midpoint of the line. Unfortunately ```LineChart``` is only drawing from index 0 and forward. Is there a reason why it is set like that?

I've tracked down the rendering algorithm and found these two lines inside ```LineChartRenderer.java``` (287 - 288) :
```Java
Entry entryFrom = dataSet.getEntryForXIndex(mMinX);
Entry entryTo = dataSet.getEntryForXIndex(mMaxX);
```

Looked where the ```mMinX``` and ```mMinY``` are being set and found that ```Renderer.java``` has the method ```calcXBounds()``` which is setting them, but didn't really understand how. This method is being called whenever the ```onDraw``` of the ```LineChart``` is being called.

So is there a way to perhaps override that by extending the ```LineChartRenderer``` and overriding the ```calcXBounds()``` to take into account the negative indices as well? What's the downside of doing that?

Best regards,

ahasbini

# Update 1
With more digging around I found these 2 line in ```Render.java``` (55-56):
```Java
int low = dataProvider.getLowestVisibleXIndex();
int high = dataProvider.getHighestVisibleXIndex();
```
```getLowestVisibleXIndex()``` is implemented in ```BarLineChartBase.java``` with return statement: 
```return (pts[0] <= 0) ? 0 : (int) (pts[0] + 1);```

By any chance could this be the reason to a always zero starting index?

Best regards,
ahasbini

# Update 2
Did some experiments and have created my own ```CustomRenderer```, here's the code:
```Java
private class CustomRenderer extends LineChartRenderer{

        public CustomRenderer(LineDataProvider chart, ChartAnimator animator, ViewPortHandler viewPortHandler) {
            super(chart, animator, viewPortHandler);
        }

        @Override
        public void calcXBounds(BarLineScatterCandleBubbleDataProvider dataProvider, int xAxisModulus) {
            mMinX = Utils.getRangeMin(nbrOfPoints);
            mMaxX = Utils.getRangeMax(nbrOfPoints);
        }
    }
```

Fortunately the ```mMinX``` and ```mMaxX``` are being set correctly, but unfortunately the graph is still drawing from the 0 index instead of the negative index.

With digging some more and bit of debugging, found that the final statement choosing how to draw them is ```trans.pointValuesToPixel(buffer.buffer);``` on line 303 in ```LineChartRenderer.java```.
The statement is transforming the buffer lines between each point to actual locations on screen and resulting with negative x-indexed pixel location, hence the negative x-indexed pixel locations are drawn outside the canvas area and are not visible.

I hope I gave good insight into this problem and wish it could be fixed in order to allow negative indexed points to be drawn in order to keep calculations the same without the need of transforming, especially when there is real-time updates and zooming about the midpoint of the graph.

Best regards,
ahasbini

**Comment by PhilJay** [comment]
The question is - why do you need negative indices? Why not start at 0?
All the x-indices do is map to x-values in your Strings array. There is no need for negative ones.

**Comment by ahasbini** [comment]
The reason why I need negative indices is due to an algorithm I'm trying to implement that requires some of the indices to be negative. However your right, I ended up doing a mapping layer on top of the graph that will change my algorithms output indices into indices applicable for the graph and does start at 0. Hence my problem has problem has been solved! :)

Thanks for the help,
ahasbini
