### ISSUE TITLE
How to make 360 degree piechart to 180 degree pie chart

### ISSUE THREAD

**Issue by sathishkumars92** [PhilJay/MPAndroidChart#1204]
Hi  guys I want a pie chart of 180 degree that means semi circle , whether there is any way to make that in mpchart?

**Comment by kyogs** [comment]
Yes,you can change angle in PieChart class with 180 degree.

 private float calcAngle(float value) {
            return value / mData.getYValueSum() * 180f;
    }

**Comment by sathishkumars92** [comment]
Thanks dude its working now
