### ISSUE TITLE
Unable to add HorizontalBarChart inside a CombinedChart.

### ISSUE THREAD

**Issue by puneetakhouri** [PhilJay/MPAndroidChart#1205]
I tried adding a Bar and a Line inside a CombinedChart using its DrawOrder and it seemed to be working fine. But for one of my cases I have to add a HorizontalBarChart and a Line within the CombinedChart but the DrawOrder does not seem to be having any option for the same.

Is their any property in BarChart to achieve it?

**Comment by PhilJay** [comment]
Horizontal bars in combinedchart are not yet supported.
