### ISSUE TITLE
onValueSelected issue with CombinedChart  for version above 2.1.3

### ISSUE THREAD

**Issue by TSG9876** [PhilJay/MPAndroidChart#1207]
I noticed that the combinedchart implements OnChartValueSelectedListener (having Line and Bar ) onValueSelected  fail to work for those library version above 2.1.3 ,

I have tested  with the modified combinedChartActivity for  both version 2.1.3 and latest 2.1.6,
and noticed that vesion 2.1.3. can somehow identify two different entry ie line and bar whereas version 2.1.6 fail to identify the expected correct entry when touched using the following procedure 

public void onValueSelected(Entry e, int dataSetIndex, Highlight h) {

     

        Log.d("XHIGHLIGHT", String.valueOf(h.toString()));
       Log.d("h datesetindex", String.valueOf(dataSetIndex));

        Log.d("Barentry ",String.valueOf(mChart.getBarData().getDataSetForEntry(e)));
        Log.d("LINE Entry ",String.valueOf(  mChart.getLineData().getDataSetForEntry(e)));

    } 

[CombinedChartActivity.txt](https://github.com/PhilJay/MPAndroidChart/files/36235/CombinedChartActivity.txt)

![onvalue](https://cloud.githubusercontent.com/assets/14348325/11202165/48749ed8-8d20-11e5-9bda-b348066fe3fe.jpg)

**Comment by Aeonia** [comment]
I can confirm I've been having this issue too...

**Comment by gavabri** [comment]
I am having this issue with (Line + Scattered) CombinedChart. When tap on scattered chart value it does not always recognize value selected. Sometimes zooming in and then trying to select fires onSelectedValue, sometime it does not

**Comment by PhilJay** [comment]
This will be fixed in new release.
