### ISSUE TITLE
Change font color and size for PieChart labels

### ISSUE THREAD

**Issue by mohoff** [PhilJay/MPAndroidChart#1209]
Hi, I can't find a way to change font color and font size for slice labels in pie charts. By default it is black and printed in a very small size for me.

![selection_002](https://cloud.githubusercontent.com/assets/6060612/11233193/66bfcb92-8dbb-11e5-8eaa-c4baa875b842.png) (sorry for bad contrast there)

Feels bad to ask basic questions like this but neither the Issues-pages nor Stackoverflow could help me so far. Thanks!

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/The-ChartData-class

https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/PieChartActivity.java

**Comment by anismarzouk** [comment]
https://github.com/PhilJay/MPAndroidChart/issues/496

**Comment by ispam** [comment]
How can i accomplish the styling of the ChartData Class using a fragment?

**Comment by HamzehSoboh** [comment]
What about "Bars" and "Home" text at the top right of the screen? How can it be customized?

**Comment by smw7156** [comment]
Hi, I am creating  Pie Chart using MPAndroidCharts Library. Everything went well, just one problem i m facing regarding ValueTextColor

![chart_whole](https://user-images.githubusercontent.com/16005377/29202980-c2f2dfd2-7e8a-11e7-9904-3bb181cfdf9d.png)

![chate_part](https://user-images.githubusercontent.com/16005377/29202988-d21be27e-7e8a-11e7-9755-963129f2a4bf.png)

XValuesLabel are coming in White font Color, and YValueLabel in Black fontColor.
I want both of it in black color, but somehow setValueTextColor() is not making any impact in XValuesLabel 

`       Log.d("PIECHART dataset", "addDataSet started");
        ArrayList<PieEntry> yEntrys = new ArrayList<>();
        ArrayList<String> xEntrys = new ArrayList<>();

        for(int i = 0; i < yData.length; i++){
          //for(int d1 : yData)  {

            if(yData[i]>0) {

               // yEntrys.add(new PieEntry(yData[i], shot_type.values().toString()));
                switch(i){
                    case 0://if(!xEntrys.contains("Straight"))xEntrys.add("Straight");
                        yEntrys.add(new PieEntry(yData[i], "banana"));
                        break;
                    case 1://if(!xEntrys.contains("Cover"))xEntrys.add("Cover");
                        yEntrys.add(new PieEntry(yData[i], "guava"));
                        break;
                    case 2://if(!xEntrys.contains("On"))xEntrys.add("On");
                        yEntrys.add(new PieEntry(yData[i], "apple"));
                        break;
                    case 3://if(!xEntrys.contains("Cut"))xEntrys.add("Cut");
                        yEntrys.add(new PieEntry(yData[i], "pineapple"));
                        break;
                    case 4://if(!xEntrys.contains("Hook"))xEntrys.add("Hook");
                        yEntrys.add(new PieEntry(yData[i], "mango"));
                        break;
                    case 5://if(!xEntrys.contains("Pull"))xEntrys.add("Pull");
                        yEntrys.add(new PieEntry(yData[i], "papaya"));
                        break;
                    case 6://if(!xEntrys.contains("Sweep"))xEntrys.add("Sweep");
                        yEntrys.add(new PieEntry(yData[i], "dates"));
                        break;
                    default : ;
                }

            }
        }

       /* for(int i = 0; i < xData.length; i++){
            xEntrys.add(xData[i]);
        }*/

        //create the data set

        pieDataSet = new PieDataSet(yEntrys, "");
        pieDataSet.setSliceSpace(2f);
        pieDataSet.setValueTextSize(15f);
        pieDataSet.setValueTextColor(Color.RED);/* this line not working */
        pieDataSet.setSelectionShift(10f);
        pieDataSet.setValueLinePart1OffsetPercentage(80.f);
        pieDataSet.setValueLinePart1Length(1f);
        pieDataSet.setValueLinePart2Length(0.9f);
        pieDataSet.setXValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);
        //pieDataSet.setYValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);
        
        //add colors to dataset
        ArrayList<Integer> colors = new ArrayList<>();
        colors.add(Color.rgb(156,254,230));
        colors.add(Color.rgb(159,185,235));
        colors.add(Color.rgb(143,231,161));
        colors.add(Color.rgb(160,239,136));
        colors.add(Color.rgb(200,246,139));
        colors.add(Color.rgb(176,219,233));
        colors.add(Color.rgb(183,176,253));
        
        pieDataSet.setColors(colors);

        ///// disabling chart legend
        pieChart.getLegend().setEnabled(false);

        Log.d("PIECHART dataset2", xEntrys.size()+" ");

        //create pie data object
        PieData pieData = new PieData(pieDataSet);
        pieData.setValueTextColor(Color.RED);/* only YValue color changes, Xvalues remains white*/
        pieData.setValueFormatter(new valueFormat());
        pieChart.setData(pieData);
        //pieDataSet.notifyDataSetChanged();
        //pieChart.invalidate();`
 
please help. Thanks

**Comment by MZellhofer** [comment]
@smw7156 did find a way to solve the problem?

**Comment by smw7156** [comment]
@MZellhofer yeah, i did a way out..

**Comment by SWAVIS** [comment]
@HamzehSobo did you find the solution?

**Comment by VuHongHiep** [comment]
@HamzehSoboh @Swavis try:

Legend legend = pieChart.getLegend();
legend.setTextColor(yourColor);

**Comment by AnilKumarBG** [comment]
i used like below line.its working 

data.setValueTextColor(getResources().getColor(R.color.bc_light_blue));

**Comment by shakiz** [comment]
> @HamzehSoboh @Swavis try:
> 
> Legend legend = pieChart.getLegend();
> legend.setTextColor(yourColor);

Thanks to you.I was trying to find a solution for this one.
