### ISSUE TITLE
Get values from stacked bars chart

### ISSUE THREAD

**Issue by urospodkriznik** [PhilJay/MPAndroidChart#1210]
Hi,

I use stacked bar chart to show some data. I am setting Entries like in example app.

        ArrayList<BarEntry> yVals1 = new ArrayList<BarEntry>();
        for (int i = 0; i < osy.length; i++) {
            int val1 = osy[i];
            int val2 = sum - osy[i];
            yVals1.add(new BarEntry(new float[]{val1, val2}, i));
        }

Data in chart is shown as it should. Then I have Gesture Listener in which I am getting data in chart like this:
mChart.getData().getDataSetByIndex(0).getYVals();
In this list there are only sums of every YVals. This is sufficiently for normal BarChart, PieChart ect. but in my case, I need to get val1 and not sum of val1 and val2. 

Is this possible or are there only sums available?

Thanks a lot!

**Comment by PhilJay** [comment]
The `BarEntry` class has a method for that.

`float[] stackVals = barEntry.getVals();`
