### ISSUE TITLE
PieChart : x-values hide on low y-values

### ISSUE THREAD

**Issue by paolo8417** [PhilJay/MPAndroidChart#1211]
Hi,
I want to hide x-values and y-values in piechart for low y values, to avoid cluttered labels.

This is my example:
![1](https://cloud.githubusercontent.com/assets/5022754/11238980/9b27e684-8de9-11e5-84fc-79efc7f55908.png)

I want to show only "64,2% Others" and "30,4% Label_1", and hide all the others (before 5%).

I've read the issue #535, and I think that the problem is hide the x-values labels.

Refering issue #535, I've solved with this:

    private ArrayList<String> xVals;

    public class MyPercentageFormatter implements ValueFormatter {

        private DecimalFormat mFormat;

        public MyPercentageFormatter() {
            mFormat = new DecimalFormat("###,###,###,##0.0");
        }

        @Override
        public String getFormattedValue(float value, Entry entry, int dataSetIndex, ViewPortHandler viewPortHandler ) {
            if(value < 5) return "";
            else return String.format("%s\n%s",xVals.get(entry.getXIndex()),mFormat.format(value) + " %");
        }
    };

using chart.setUsePercentValues(true) and chart.setDrawSliceText(false).

but the '\n' on the string format doesn't work and the label is a single line.

![2](https://cloud.githubusercontent.com/assets/5022754/11239916/20fe3b5a-8def-11e5-886d-00b6d4388a7d.png)

Is this the correct way to hide x-labels on low y values or there are others way?

**Comment by PhilJay** [comment]
Yes, indeed it is.

**Comment by seanyc4** [comment]
I implemented this and it doesnt remove the labels only the percentages
