### ISSUE TITLE
Xlabel at a given position in Bar Chart

### ISSUE THREAD

**Issue by vipinagrahari** [PhilJay/MPAndroidChart#1215]
How can I access label at a given position in Bar Chart. I want to underline the label of bar which is currently clicked by user. 
Thank you for the awesome library

**Comment by sentilab** [comment]
In my case, I got the information of Bar's Rect from "getBarBounds(BarEntry e)" method at HorizontalBarChart class.
And I finally got the each Rect's information of Bar.
If you want to use label, I think you can use label position below each Bar position.

**Comment by PhilJay** [comment]
Use `OnChartValueSelectedListener`:

````java
public void onValueSelected(Entry e, int dataSetIndex, Highlight h) {
    String label = mChart.getXVals().get(e.getXIndex());
}
````
