### ISSUE TITLE
Dotted Limit Line

### ISSUE THREAD

**Issue by gray419** [PhilJay/MPAndroidChart#1218]
I am looking for a way to style the limit line as a dotted limit line. Is this possible?

<img width="185" alt="screen shot 2015-11-21 at 2 09 02 pm" src="https://cloud.githubusercontent.com/assets/3689237/11319992/8eb3b050-9059-11e5-8977-f4bf9fa73292.png">

**Comment by PhilJay** [comment]
`limitLine.enableDashedLine(...)`
