### ISSUE TITLE
leftAxis.setAxisMinValue(X) / mCustomAxisMin not working

### ISSUE THREAD

**Issue by BrunoCarrier** [PhilJay/MPAndroidChart#1220]
Hi, as far as I can tell setAxisMinValue is not working.  T

he left axis starts at the value 0 even if the value for leftAxis.getAxisMinValue() / mCustomAxisMin returns non-zero.  I've tried many ways to make the left Y axis start at a value other than zero, to no avail.  

I used only positive values and disabled the right axis with         chart.getAxisRight().setEnabled(false);

The max value does behave as expected though.

Would it be possible to look into this?

Thanks!

**Comment by PhilJay** [comment]
`leftAxis.setStartAtZero(false)`

**Comment by BrunoCarrier** [comment]
Thanks!
