### ISSUE TITLE
indexoutofboundsexception

### ISSUE THREAD

**Issue by jaycho19** [PhilJay/MPAndroidChart#1223]
pls help me , many thanks

   private void initCardView() {

        yVals1 = new ArrayList<>();
        yVals2 = new ArrayList<>();

        mChart.setOnChartValueSelectedListener(this);
        // no description text
        mChart.setDescription("");
        mChart.setNoDataTextDescription("You need to provide data for the chart.");

        // enable value highlighting
        mChart.setHighlightEnabled(true);

        // enable touch gestures
        mChart.setTouchEnabled(true);

        mChart.setDragDecelerationFrictionCoef(0.9f);

        // enable scaling and dragging
        mChart.setDragEnabled(true);
        mChart.setScaleEnabled(true);
//        mChart.notifyDataSetChanged();
//        mChart.invalidate();
        mChart.setDrawGridBackground(false);
        mChart.setHighlightPerDragEnabled(false);

        // if disabled, scaling can be done on x- and y-axis separately
        mChart.setPinchZoom(true);

        // set an alternative background color
        mChart.setBackgroundColor(Color.LTGRAY);

        // set chart Animation
        mChart.animateX(2500);

        // set chart style
        Typeface tf = Typeface.createFromAsset(getAssets(),"OpenSans-Light.ttf");

        // get the legend (only possible after setting data)
        Legend l = mChart.getLegend();

        // modify the legend ...
        // l.setPosition(LegendPosition.LEFT_OF_CHART);
        l.setForm(Legend.LegendForm.LINE);
        l.setTypeface(tf);
        l.setTextSize(11f);
        l.setTextColor(Color.BLACK); //show type text color
        l.setPosition(Legend.LegendPosition.BELOW_CHART_LEFT);
//        l.setYOffset(11f);

        XAxis xAxis = mChart.getXAxis();
        xAxis.setTypeface(tf);
        xAxis.setTextSize(12f);
        xAxis.setTextColor(Color.WHITE); // xline text colot
        xAxis.setDrawGridLines(false);
        xAxis.setDrawAxisLine(false);
        xAxis.setSpaceBetweenLabels(1);

        YAxis leftAxis = mChart.getAxisLeft();
        leftAxis.setTypeface(tf);
        leftAxis.setTextColor(ColorTemplate.getHoloBlue());
        leftAxis.setAxisMaxValue(400);
        leftAxis.setAxisMinValue(-10);
        leftAxis.setDrawGridLines(true);

        YAxis rightAxis = mChart.getAxisRight();
        rightAxis.setTypeface(tf);
        rightAxis.setTextColor(Color.RED);
        rightAxis.setAxisMaxValue(300);
        rightAxis.setStartAtZero(false);
        rightAxis.setAxisMinValue(-10);
        rightAxis.setDrawGridLines(true);

    }

private class AsyncCallWS extends AsyncTask<String, Void, String> {

        @Override
        protected String doInBackground(String... params) {
            // Call Web Method

            EnvironmentToJson setdata = new EnvironmentToJson(mID, mQueryType, mStartDate, mEndDate);
            EnvironmentToJson setrequestdata = new EnvironmentToJson(WebServiceName.WebService_getEnvironmentInfo, setdata);
            EnvironmentToJson sendata = new EnvironmentToJson(setrequestdata);

            String jsondata = mGson.toJson(sendata);
            Log.d(UserSessionManager.TAG, "jsondata " + jsondata);

            mGetHistorialStatus = WebServicePortal.invokePortalNormalWS(jsondata,
                    WebServiceName.WebService_EntryPoint);
            Log.d(UserSessionManager.TAG, "mGetHistorialStatus " + mGetHistorialStatus);
            return mGetHistorialStatus;
        }

        @Override
        // Once WebService returns response
        protected void onPostExecute(String result) {
            // Error status is false
            try {
                if (!WebServicePortal.errored) {
                    // start parse response by json type
                    jsonToEnvironmentInfo(result);

                    // value should be clear and start set chart x-value
                    if (mQueryType.equals("Hour")) {
                        xVals.clear();
                        for(int v = 0; v < 3; v++) {
                            for (int j = 0; j < 24; j++) {
                                xVals.add((j) + "");
                            }
                        }
                    } else if (mQueryType.equals("Day")) {
                        xVals.clear();
                        for (int i = 1; i < 31; i++) {
                            xVals.add((i) + "");
                        }
                    } else if (mQueryType.equals("Month")) {
                        xVals.clear();
                        for (int h = 1; h < 13; h++) {
                            xVals.add((h) + "");
                        }
                    }

                    // create a dataset and give it a type
                    LineDataSet set1 = new LineDataSet(yVals1, getResources().getString(R.string.temperature));
                    set1.setAxisDependency(YAxis.AxisDependency.LEFT);
                    set1.setColor(ColorTemplate.getHoloBlue());
                    set1.setCircleColor(Color.WHITE);
                    set1.setLineWidth(2f);
                    set1.setCircleSize(3f);
                    set1.setFillAlpha(65);
                    set1.setFillColor(ColorTemplate.getHoloBlue());
                    set1.setHighLightColor(Color.rgb(244, 117, 117));
                    set1.setDrawCircleHole(false);

                    // create a dataset and give it a type
                    LineDataSet set2 = new LineDataSet(yVals2, getResources().getString(R.string.humidity));
                    set2.setAxisDependency(YAxis.AxisDependency.RIGHT);
                    set2.setColor(Color.RED);
                    set2.setCircleColor(Color.WHITE);
                    set2.setLineWidth(2f);
                    set2.setCircleSize(3f);
                    set2.setFillAlpha(65);
                    set2.setFillColor(Color.RED);
                    set2.setDrawCircleHole(false);
                    set2.setHighLightColor(Color.rgb(244, 117, 117));

                    // add the datasets
                    ArrayList<LineDataSet> dataSets = new ArrayList<LineDataSet>();
                    dataSets.add(set1);
                    dataSets.add(set2);

                    // create a data object with the datasets
                    LineData data = new LineData(xVals, dataSets);
                    data.setValueTextColor(Color.BLACK); // show value color(point)
                    data.setValueTextSize(11f);

                    // set data
                    mChart.setData(data);
                    mChart.setVisibleXRangeMaximum(20);
                    mChart.notifyDataSetChanged();
                    mChart.invalidate();
                    // Error status is true
                } else {
                    ToastUtility.showToast(getApplication(),
                            "Error occured in invoking webservice",
                            Toast.LENGTH_SHORT);

                }
            } catch (Exception e) {
                Log.e(UserSessionManager.TAG, e.getMessage());
            }
            // Re-initialize Error Status to False
            WebServicePortal.errored = false;
        }
    }

**Comment by PhilJay** [comment]
Is your chart empty on purpose?

    yVals1 = new ArrayList<>();
    yVals2 = new ArrayList<>();

**Comment by jaycho19** [comment]
add yVals is here.

                JSONObject obj = new JSONObject(DataTable);
                JSONArray array = obj.getJSONArray("DataRow");
                for (int i = 0; i < array.length(); i++) {

                    JSONObject jsonObject = array.getJSONObject(i);
                    float tem = Float.parseFloat(jsonObject.optString("Temperature").toString());
                    float hum = Float.parseFloat(jsonObject.optString("Humidity").toString());

                    if (mQueryType.equals("Hour")) {
                        int time = Integer.parseInt(jsonObject.optString("Time").toString());
                        yVals1.add(new Entry(tem, time));
                        yVals2.add(new Entry(hum, time));
                    } else if (mQueryType.equals("Day")) {
                        int day = Integer.parseInt(jsonObject.optString("Day").toString());
                        yVals1.add(new Entry(tem, day));
                        yVals2.add(new Entry(hum, day));
                    } else if (mQueryType.equals("Month")) {
                        int month = Integer.parseInt(jsonObject.optString("Month").toString());
                        yVals1.add(new Entry(tem, month));
                        yVals2.add(new Entry(hum, month));
                    } else if (mQueryType.equals("Year")) {
                        int year = Integer.parseInt(jsonObject.optString("Year").toString());
                        yVals1.add(new Entry(tem, year));
                        yVals2.add(new Entry(hum, year));
                    }

**Comment by PhilJay** [comment]
I suggest that you dont make your x-values and y-values arrays member variables.

**Comment by jaycho19** [comment]
pls tell me what should i do , many thanks.

**Comment by PhilJay** [comment]
Your ArrayLists called yVals1, yVals2 and xVals seem to be member variables. Change them to local valriables.
