### ISSUE TITLE
add a static dash line in the chart

### ISSUE THREAD

**Issue by poldz123** [PhilJay/MPAndroidChart#1226]
Is there a function that will add multiple static line on the grid from either side x or y axis?

example image:

![sample](https://cloud.githubusercontent.com/assets/4010507/11378936/be50acdc-92bb-11e5-9dde-318edf21c2a7.png)

The Brown dash line is what I want to show in the graph and what I want to implement.

Thank you.

**Comment by PhilJay** [comment]
Yes, it's called [`LimitLine`](https://github.com/PhilJay/MPAndroidChart/wiki/The-Axis).
