### ISSUE TITLE
faint color before vertical line LimitLine

### ISSUE THREAD

**Issue by poldz123** [PhilJay/MPAndroidChart#1227]
Sorry for asking again and thank you for the answer for the last question I had.

Currently I have a vertical line, Now What I want is to have a faint color such as grey before the static line.

Example image:

![sample](https://cloud.githubusercontent.com/assets/4010507/11380569/dd309a8c-92c4-11e5-8292-a3a0f73ca474.png)

Is there a way to render a color before the vertical line?

**Comment by PhilJay** [comment]
Not by default, you will have to do that by yourself by modifying the library.
