### ISSUE TITLE
Shadow effect in Line chart

### ISSUE THREAD

**Issue by sathishkumars92** [PhilJay/MPAndroidChart#1229]
![screenshot from 2015-11-25 14 21 43](https://cloud.githubusercontent.com/assets/3184062/11392475/0b7bbafa-9380-11e5-8f9f-b5a73a2b4a59.png)

How to have this kind of shadow effect in linechart...

**Comment by PhilJay** [comment]
Where is the shadow?

**Comment by sathishkumars92** [comment]
look at the dots there will be a fading line color below line

**Comment by PhilJay** [comment]
Wow my monitor is so bad I really cannot see the shadow effect :-D
However I just viewed it on my phone and there I can see it.

To your question:
Well it is possible to add a color below the line, that is absolutely no problem. What you have in your image is some kind of gradient, which is currently not supported and would require a custom implementation.
