### ISSUE TITLE
PieChart Fullscreen

### ISSUE THREAD

**Issue by nokosi** [PhilJay/MPAndroidChart#1233]
I'm currently developping a small app in which i want to display one graph per tab (there is 3 tabs).
When I launch my app, the Chart is always fullscreen. 
I tried without the tabs and it's the same result. I declare the Chart in a Relative Layout:

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:id="@+id/mainLayout"
    tools:context=".MainActivity">

    <com.github.mikephil.charting.charts.PieChart
        android:id="@+id/mChart"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        />
</RelativeLayout>

How can i set a specific width and height for the Chart?

Thank you!!

**Comment by PhilJay** [comment]
<com.github.mikephil.charting.charts.PieChart
    android:id="@+id/chart"
    android:layout_width="100dp"
    android:layout_height="100dp"
    />

**Comment by nokosi** [comment]
Thank you for your useful help !!
