### ISSUE TITLE
Problem with coloring multiple line when used with cubic-lines

### ISSUE THREAD

**Issue by gizone** [PhilJay/MPAndroidChart#1236]
I build an app that using the multiple line chart. For coloring lines I used this code:
```
int[] colors = new int[89];
for (int i = 0; i<62; i++){
    colors[i]=Color.parseColor("#A0A0A0");
}
for (int i = 62; i<89; i++) {
    if (z == 0) {
        colors[i] = Color.parseColor("#0000FF");
    } else if (z == 1) {
        colors[i] = Color.parseColor("#FF0000");
    } else {
        colors[i] = Color.parseColor("#008000");
    }
}

LineDataSet d = new LineDataSet(entriesLine, title);
d.setColors(colors);
d.setCircleColors(colors);
dataset.add(d);
```
the problem is when I switch to "toggle cubic" (setDrawCubic(true)) the line color just show color #A0A0A0 (gray) but the circle color working well.
Could someone solve my problem?
Thanks ...

**Comment by PhilJay** [comment]
Yep, that's not in the documentation. Cubic-lines currently do not support multiple colors.
