### ISSUE TITLE
Lines between data nodes can disappear in some situations

### ISSUE THREAD

**Issue by bright-nll** [PhilJay/MPAndroidChart#1237]
Hi 
When I set datas not continuely (like the first value for x1, second value for x4, etc), and zoom in , then dragging the line may disappear , dragging little the line is show, have you met this? Thank you!

**Comment by GRouslan** [comment]
I'm facing this issue too

![issue](https://cloud.githubusercontent.com/assets/12217692/11764037/ebdb38d2-a131-11e5-98f0-20ae52d80be5.png)

**Comment by matejcikm** [comment]
I have the same problem

**Comment by hugey010** [comment]
Having this same issue. On ios-charts as well. Its pretty trivial to show an example for if needed.

**Comment by jakub-martyna-comarch** [comment]
I have the same problem.

**Comment by PhilJay** [comment]
Should be fixed in new v3.0.0
