### ISSUE TITLE
How to show all the range of x axis without zoomimg in Bar Chart?

### ISSUE THREAD

**Issue by sahilgarg1993** [PhilJay/MPAndroidChart#1238]
Hi Phil,

How can I show all the x axis values at a time without zooimg?
Here an example: 
I have a bar chart with data on x-axis from 0 to 50 and I want to show all the numbers from 0 to 50 at same time.

I hope you understand what I'm asking.

Regards,
Sahil Garg

**Comment by PhilJay** [comment]
`chart.fitScreen()`

**Comment by sahilgarg1993** [comment]
I'm Sorry it didn't work for me it still displaying random numbers between 0 to 50
