### ISSUE TITLE
I want to make this type of graph, Can you please help me out?

### ISSUE THREAD

**Issue by sahilgarg1993** [PhilJay/MPAndroidChart#1239]
![image4](https://cloud.githubusercontent.com/assets/16078970/11467268/ed1c789c-976c-11e5-9132-089340605253.JPG)

**Comment by sahilgarg1993** [comment]
I hope you understand the need..

**Comment by PhilJay** [comment]
You should find everything you need int the example app: https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample
