### ISSUE TITLE
replace data for chart

### ISSUE THREAD

**Issue by lanitahedgehog** [PhilJay/MPAndroidChart#1246]
First of all, thank you for your library - I find it very helpful and easy customizable! 
What I need: 
I have several time intervals user can choose for CandleStick chart. Each time when user choose an interval I load data from server, invoke fitScreen(), clear(), create new CandleDataSet, CandleData and set that new data to chart. Then I scale the chart to the specific scale factor.
It works great, but I can not figure out how I can move the chart to the latest data after the used moved it to somewhere in the middle (for example). I used you code form dynamicActivity 
moveViewToX(candleDataSet.getEntryCount());
and it works when I add data dynamically. 
But it doesn't when I add new data to chart (kind of replace it) after user moved the chart somehow. Seems like the chart stays on the same scroll position even after I add new data and invoke moveViewToX.
P.S. I also tried moveViewTo, centerViewTo. The result was the same.
Help me please to find a solution

**Comment by PhilJay** [comment]
show the code that should work but doesnt

**Comment by lanitahedgehog** [comment]
if (resetChartZoom) {
                            fitScreen();
                            clear();
                        }

                        CandleDataSet candleDataSet = createCandleDataSet((ArrayList<CandleEntry>) ret[0]);  //create absolutely new dataset
                        CandleData candleData = new CandleData((ArrayList<String>) ret[1], candleDataSet);

                        setData(candleData);
                        setVisibleXRangeMinimum(1f);

                        if(resetChartZoom) {
//zoom the chart so the candles would have needed width
                            float candleWidth = candleDataSet.getShadowWidth();
                            if(candleWidth < CANDLE_STICK_WIDTH)
                            {
                                int scaleFactor = (int) (9/candleWidth);
                                CustomLog.print(CustomLog.UI, CLASSNAME, "need initial scale. candleWidth = " + candleWidth + " scaleFactor = " + scaleFactor);
                                RectF rect = getViewPortHandler().getContentRect();
                                zoom(scaleFactor, 1, rect.left, getHeight() / 2);

                                moveViewToX(candleDataSet.getEntryCount()-1); // works only when the chart data is set for the 1st time
                            }
                            resetChartZoom = false;
                        }

**Comment by PhilJay** [comment]
have you tried calling `chart.invalidate()` after all this?

**Comment by lanitahedgehog** [comment]
just tried - didn't help. By the way I noticed that if after scrolling the chart user "fitScreen" the chart - the new interval opens fine being scrolled to the latest data. But in code, as you can see I call fitScreen() when timeInterval chages but the result is not the same

**Comment by lanitahedgehog** [comment]
By the way, just noticed that method moveViewToX(candleDataSet.getEntryCount()-1) in my case provokes a bug in yAxis's labels rendering. Like this (see a screenshot). Most of yLabels are missing. They appear after a single touch on a chart. 
Meanwhile, I don't use method moveViewToX, as it provokes the bug and doesn't scroll a chart.. it would be great if you could tell me if there is an alternative way to scroll the chart, that has been zoomed programmatically. 
Thank you! 
![screenshot_2015-12-07-14-46-47](https://cloud.githubusercontent.com/assets/15926835/11632232/c89657ac-9d0e-11e5-824b-04240319f637.png)

**Comment by rhavran** [comment]
Hello, @lanitahedgehog I had the similar issue, it can be related to deceleration mode, try to call ((BarLineChartTouchListener)mChart.getOnTouchListener()).stopDeceleration() before moveViewToX.
