### ISSUE TITLE
PieChart Animation Not Working in case of Fragment

### ISSUE THREAD

**Issue by mihaltianistvan** [PhilJay/MPAndroidChart#1247]
Hi, I am using Android Studio, I have a fragment which contains my pieChart. I add this fragment to another fragments layout in a LinearLayout. Everithing is wokring fine also the seted animation is working fine, but when I change the orientation of the screen and I have seted animation for the chart, the aplication crashed with the following error java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Canvas.drawCircle(float, float, float, android.graphics.Paint)' on a null object reference. This is happening if I use fragmenttransaction.add, because if I use replace than is working fine. Also if I'm using FrameLayout as placeholder the add is working. My problem is that I create a same fragment for LineChart and for this everithing is working well. Somebody have any idea ?

**Comment by PhilJay** [comment]
Looks like an issue related to your code setup and the way you initialize UI components in the Fragment. Without any code this will be impossible to solve.

**Comment by Shivam077770** [comment]
Without any code this will be impossible to solve.
