### ISSUE TITLE
How could i tell the state of the rendered finished?

### ISSUE THREAD

**Issue by lvwenbo0107** [PhilJay/MPAndroidChart#1249]
I added some lines in another thread like
" while(result){ addSingleLine()}"
and i updated it in MainThread .Now there is a thing.  I have another analysisMethod after its addSingleLine() finished,my analysisMethod always get the wrong size of thel ines becaulse of
Rendering is not finised yet. How could I know the state of the rendered finished?thx!

**Comment by lvwenbo0107** [comment]
I add the data in MainThread because added in other thread makes error.I need to know the state of Finish ,then I could use my ananlysis method

**Comment by PhilJay** [comment]
I suggest you extend the chart and add a listener that fires when the drawing is finished.

**Comment by lvwenbo0107** [comment]
Hi friend,
Could u show me a demo?I don't not know where to set my listener...Thx!
