### ISSUE TITLE
Chart empty until touch event

### ISSUE THREAD

**Issue by tijee** [PhilJay/MPAndroidChart#1250]
Hi there. My LineChart gets empty when its size changes, after another view is added to my layout. The data reappears only when I touch the chart.

It seems the problem has occurred before: https://github.com/PhilJay/MPAndroidChart/issues/14.

You can try to reproduce it with an horizontal LinearLayout, in which you have a LineChart and another View, which is hidden. Somewhere in your code, set the visibility of the second view to Visible, the LineChart should then clear itself.

**Comment by PhilJay** [comment]
Call invalidate() to refresh the chart.
