### ISSUE TITLE
DataSet values not appearing in multiple horizontal bar charts

### ISSUE THREAD

**Issue by pranayairan** [PhilJay/MPAndroidChart#1251]
I am trying to create Horizontal Bar charts with multiple data. The chart is coming correct but i can not see values in yAxis. If i use only single data set it is working and i can see the values but for multi data set it does't show anything. 

Here is how i am doing it:

                            BarDataSet dataset1 = new BarDataSet(entries1, "");
                            BarDataSet dataset2 = new BarDataSet(entries2, "");

                            dataset1.setColors(new int[]{Color.rgb(56, 142, 60)});
                            dataset2.setColors(new int[]{Color.rgb(211, 47, 47)});
                            ArrayList<BarDataSet> dataSets = new ArrayList<>();
                            dataSets.add(dataset2);
                            dataSets.add(dataset1);

                            BarData data = new BarData(labels, dataSets);
                            data.setValueTextSize(10f);
                            horizontalBarChart.setData(data);

<img width="422" alt="screen shot 2015-12-04 at 8 51 03 pm" src="https://cloud.githubusercontent.com/assets/430940/11593436/64e601b2-9aca-11e5-812d-02fca1a0c7e0.png">

**Comment by PhilJay** [comment]
Have you checked your `ValueFormatter` in case you are using one?
Did you call `data.setDrawValues(true)`?

**Comment by pranayairan** [comment]
Yes i tried setting valueformatter, but it never gets called, i added a debug point inside value formatter but it never reaches that point. Also setting setDrawvalue has no effect. 

In the same code, instead of adding Arralylist of datasets in new BarData constructor, if i just add single dataset in the list or only dataset it works and i can see the values on graph. 

<img width="416" alt="screen shot 2015-12-05 at 1 43 04 pm" src="https://cloud.githubusercontent.com/assets/430940/11606854/2695db30-9b56-11e5-8184-90dc81f28ac9.png">

**Comment by PhilJay** [comment]
Ok. I will look into it.
Which version of the library are you using?

**Comment by pranayairan** [comment]
I was using v2.1.5 but i upgraded to 2.1.6 but still same thing. Just to give some more info, i have disabled left and right axis since i wanted this kind of interface. 

        horizontalBarChart.getAxisLeft().setEnabled(false);
        horizontalBarChart.getAxisRight().setEnabled(false);
        horizontalBarChart.getXAxis().setPosition(XAxis.XAxisPosition.BOTTOM);

**Comment by PhilJay** [comment]
And just to be clear: You are talking about the values that are drawn to the right of each bar? They are not visible for you?

**Comment by pranayairan** [comment]
yes if you see the second image attached it is the same data but without 2 data sets.

**Comment by PhilJay** [comment]
Can you post the full code of your chart setup?

**Comment by pranayairan** [comment]
Sure, here you go 

        HorizontalBarChart creditDebitMonthlyBarChart (injected reference)

        creditDebitMonthlyBarChart.setDescription("desc");

        // if more than 60 entries are displayed in the chart, no values will be
        // drawn
        creditDebitMonthlyBarChart.setMaxVisibleValueCount(8);

        // scaling can now only be done on x- and y-axis separately
        creditDebitMonthlyBarChart.setPinchZoom(false);

        creditDebitMonthlyBarChart.setDrawBarShadow(false);
        creditDebitMonthlyBarChart.setDrawGridBackground(false);

        creditDebitMonthlyBarChart.getAxisLeft().setEnabled(false);
        creditDebitMonthlyBarChart.getAxisRight().setEnabled(false);

        creditDebitMonthlyBarChart.getXAxis().setPosition(XAxis.XAxisPosition.BOTTOM);

        // add a nice and smooth animation
        creditDebitMonthlyBarChart.animateY(2000);
        creditDebitMonthlyBarChart.getLegend().setEnabled(false);

        ArrayList<BarEntry> barChartentriesCredit = new ArrayList<>();
        ArrayList<BarEntry> barChartentriesDebit = new ArrayList<>();

        //add some data into arraly list 
        for (int i = 0; i < 10; i++) {
            barChartentriesDebit.add(new BarEntry(i+1, i));
            barChartentriesCredit.add(new BarEntry(i+2, i));
        }

        BarDataSet dataset1 = new BarDataSet(barChartentriesDebit, "data1");
        BarDataSet dataset2 = new BarDataSet(barChartentriesCredit, "data2");

        dataset1.setColors(new int[]{Color.rgb(56, 142, 60)});
        dataset2.setColors(new int[]{Color.rgb(211, 47, 47)});


        ArrayList<BarDataSet> dataSets = new ArrayList<>();
        dataSets.add(dataset2);
        dataSets.add(dataset1);

        creditDebitMonthlyBarChart.setVisibility(View.VISIBLE);

        BarData data = new BarData(merchantLabels, dataSets);
        data.setDrawValues(true);
        data.setValueTextSize(11f);
        data.setValueTextColor(Color.BLACK);

        creditDebitMonthlyBarChart.setData(data);

**Comment by pranayairan** [comment]
i uninstalled and installed app again and it is working now. Closing the issue. Sorry for the confusion.

**Comment by PhilJay** [comment]
Weird error I guess, thanks for letting me know!

**Comment by Anfet** [comment]
Can I up this topic.

I have a piece of code, that at one point draws values and at other don't.

```
chart.getLegend().setEnabled(false);

		chart.getAxisLeft().setEnabled(false);
		chart.getAxisRight().setEnabled(false);

		chart.getXAxis().setPosition(XAxis.XAxisPosition.BOTTOM);
		chart.getXAxis().setDrawLabels(true);
		chart.getXAxis().setDrawGridLines(false);

		chart.setDrawGridBackground(false);
		chart.setNoDataText("");
		chart.setDescription("");
```
```
final BarDataSet barDataSet = new BarDataSet(entries, "");
		BarData barData = new BarData(barDataSet);
		barData.setBarWidth(0.8f);

		barDataSet.setDrawValues(true);
		barDataSet.setColor(getResources().getColor(R.color.accent));
		barDataSet.setValueTypeface(Fonts.getFont(this, Fonts.OPEN_SANS));
		barDataSet.setValueTextSize(Fonts.getFontSizeFromDimension(this, R.dimen.minitext_size));
		barDataSet.setValueTextColor(Color.BLACK);
		barDataSet.setBarBorderWidth(12f);
		barDataSet.setBarShadowColor(Color.argb(255, 255, 255, 255));
		barDataSet.setBarBorderColor(getResources().getColor(android.R.color.transparent));

		barDataSet.setValueFormatter(new ValueFormatter() {
			@Override
			public String getFormattedValue(float value, Entry entry, int dataSetIndex, ViewPortHandler viewPortHandler) {
				return Formatters.getInstance().getVolumeFormat().format(value) + getString(R.string.litr);
			}
		});

		chart.getXAxis().setValueFormatter(new AxisValueFormatter() {
			@Override
			public String getFormattedValue(float value, AxisBase axis) {
				if (value < 0 || value > (entries.size() - 1f))
					return "";


				Brand brand = (Brand) barDataSet.getValues().get((int) value).getData();
				return brand.getName();
			}

			@Override
			public int getDecimalDigits() {
				return 0;
			}
		});


		chart.getXAxis().setAxisMinValue(-0.5f);
		chart.getXAxis().setAxisMaxValue(entries.size() - 0.5f);
		chart.getXAxis().setLabelCount(entries.size(), false);


		int actualMin = chart.getMinimumHeight();
		int min = entries.size() * getResources().getDimensionPixelSize(R.dimen.padding_16dp) * 2;
		chart.setMinimumHeight(min);

		chart.setData(barData);
		chart.postInvalidate();
```
The problem is that it either calls barDataSet.setValueFormatter or don't.
I cannot figure out what is the problem.

Code feeding values.
A.
```
List<BarEntry> entries = new LinkedList<>();
for (Brand brand : brands) {
				BarEntry entry = new BarEntry(0, 0f);
				entry.setData(brand);

				for (ISaleElement sale : sales) {
					if (sale.getBrand().getId() == brand.getId()) {
						entry.setY(entry.getY() + sale.getSold());
					}
				}

				entries.add(entry);
			}
			return entries;
```

B.
```
List<BarEntry> entries = new LinkedList<>();
			for (Product product : salepoint.getProducts()) {
				BarEntry entry = new BarEntry(0, 0f);

				for (ISaleElement sale : sales) {
					if (sale.getBrand() == product.getBrand()) {
						entry.setY(sale.getSold());
						entry.setData(product.getBrand());
						break;
					}
				}

				entries.add(entry);
			}

			return entries;
```

What can be the problem?
