### ISSUE TITLE
Displaying Timing

### ISSUE THREAD

**Issue by GauravCreed** [PhilJay/MPAndroidChart#1252]
Hi Philipp Jahoda.

you have done a great work for the commercial work,
i download and check the your example it's work very well,
i have a question in that, can i have display the Timing like that (HH:MM:SS) in the column value.

plaese help me.
thanks.

**Comment by PhilJay** [comment]
yes thats possible!

**Comment by GauravCreed** [comment]
thanks for the response Philipp Jahoda.

so how can it possible can u tell me please.
i current pass the float value in the code like

yVals1.add(new BarEntry(Floatvalue, key));  but in that how can i pass the value as a string yVals1.add(new BarEntry(Stringvalue, key));

thanks.
