### ISSUE TITLE
pie chart

### ISSUE THREAD

**Issue by 381174610** [PhilJay/MPAndroidChart#1253]
If the right of the description is too long, the text will directly cover the pie chart, is there any way to solve and pie charts can be centered in the layout to ask how to adjust its position

**Comment by PhilJay** [comment]
No, you will have to keep your description shorter or decrease it's text size.

**Comment by 381174610** [comment]
Pie chart width set width of the screen, only the center circle graph, how do I adjust the position of the circular chart? Could you answer, thank you
