### ISSUE TITLE
Displaying Color Under the Graph with multiple colors(Rainbow Color)

### ISSUE THREAD

**Issue by justalearner** [PhilJay/MPAndroidChart#1254]
I am getting a data from a spectrometer. The data is in the visual range. from 400nm to 700nm. Ranges from light blue, to yellow, to pink, to green, to red. Right now, For pink color it is showing only Pink color as a function of RGB, can i display this as a mixture of red and blue. There is one library for QT, discussed here http://www.fourmilab.ch/documents/specrend/. I want to do the same.

Right now with MPAndroidChar library, I am getting this output
![image](https://cloud.githubusercontent.com/assets/5591087/11620985/0557ef98-9cfb-11e5-8545-5a1555513f22.png)

But i want to do something like this

![image](https://cloud.githubusercontent.com/assets/5591087/11620992/19a5643a-9cfb-11e5-9317-88873b091d1c.png)

**Comment by PhilJay** [comment]
Unfortunately a feature like that is not supported.
