### ISSUE TITLE
Pie chart

### ISSUE THREAD

**Issue by 381174610** [PhilJay/MPAndroidChart#1261]
Pie chart width is set to the mobile phone screen width and height set to a fixed height, regardless of the setting, the pie chart will appear in the middle of the screen is fixed. How to set the position of the circular chart? Very much looking forward to your answer, thank you

**Comment by PhilJay** [comment]
This is an android layout issue and not an issue related to the library. I suggest you take a look at how to properly style your layout here: http://developer.android.com/guide/topics/ui/declaring-layout.html
