### ISSUE TITLE
Scatter Chart - Set Custom Shape

### ISSUE THREAD

**Issue by betteit** [PhilJay/MPAndroidChart#1266]
I'm trying to customize the Scatter Chart with my custom shape:

ScatterDataSet set = new ScatterDataSet(entries, "Scatter DataSet");
set.setCustomScatterShape(path);

but nothing appears, only the SQUARE shape.

From the wiki:
     /**
     * Custom path object the user can provide that is drawn where the values
     * are at. This is used when ScatterShape.CUSTOM is set for a DataSet.
     */

but there is no CUSTOM option in ScatterScape, only CIRCLE, CROSS, TRIANGLE and SQUARE.

**Comment by PhilJay** [comment]
Sorry, that must be an error in the documentation. Custom scattershapes have caused issues in the past and are currently not available.
