### ISSUE TITLE
Porting MPAndroidChart and ios-charts to Xamarin.Forms

### ISSUE THREAD

**Issue by Bogidon** [PhilJay/MPAndroidChart#1269]
I'm exploring the possibility of building a Xamarin.Forms component out of MPAndroidChart and ios-charts. 

If you're interested, see [this issue](https://github.com/danielgindi/ios-charts/issues/606) from the ios-charts repository.

**Comment by PhilJay** [comment]
I think it's a great idea. Is there any progress yet?

I will close this for "overview" reasons.

**Comment by Bogidon** [comment]
No progress yet. When I looked into this I hit a roadblock with ios-charts. I wasn't able to import a Swift framework into a Xamarin project. IIRC the Xamarin team was working on fixing this, though I'm not sure what progress they've made.

Maybe the open sourcing will help. I'd still be interested in working on this, if there's interest.
