### ISSUE TITLE
Pie chart problem，After data refresh pie chart shape changes, how can I do to make a pie chart does not change, thank you for your answer

### ISSUE THREAD

**Issue by 381174610** [PhilJay/MPAndroidChart#1271]
Just the time of entry
![h sgc qkb 5 k9p6 uhq x](https://cloud.githubusercontent.com/assets/11782657/11759855/efa54920-a0bf-11e5-8de6-e545686ed9ae.png)
After refresh the data
![o d 8wsvgzago43lh x_ l](https://cloud.githubusercontent.com/assets/11782657/11759872/2acea9b0-a0c0-11e5-8673-32f3be7e7681.png)

**Comment by PhilJay** [comment]
Show some code of how you setup the chart
