### ISSUE TITLE
WordWrap not wrapping

### ISSUE THREAD

**Issue by jetav8r** [PhilJay/MPAndroidChart#1272]
I have some code with a legend that has several items...7 or more sometimes.  I have word wrap enabled and the code is at the bottom, but the strings just expand out past the borders of the chart anyway.   Any suggestions?  

Here is the code that I am using...

     Legend l = mChart.getLegend();
             l.setPosition(Legend.LegendPosition.BELOW_CHART_CENTER);
             l.setWordWrapEnabled(true);
             l.setXEntrySpace(7f);
             l.setYEntrySpace(0f);
             l.setYOffset(8f);

The legend string data is passed in as an ArrayList as such `ArrayList<String> categories`

**Comment by jetav8r** [comment]
I actually fixed this somehow...I went back and initialized everything and then called setData at the very end of my query to supply the data.  For whatever reason, this worked

**Comment by qualife** [comment]
> 
> 
> I actually fixed this somehow...I went back and initialized everything and then called setData at the very end of my query to supply the data. For whatever reason, this worked

This saved my life, thanks man. They should really document it or fix it as a tricky bug.

**Comment by italomp** [comment]
It's worked here. Thank you.
