### ISSUE TITLE
How do I force the labels on X Axis to start after some padding from the left of the screen?

### ISSUE THREAD

**Issue by ladia12** [PhilJay/MPAndroidChart#1273]
Currently when I enable both the labels on X axis and Y axis it looks like this:
![screenshot_2015-12-12-20-03-00](https://cloud.githubusercontent.com/assets/3083995/11762432/bf7570b2-a10b-11e5-9391-9122a774ca3c.png)

But I want the X axis labels to start after a certain gap, maybe skip a first few labels, so that it looks clean. Will be helpful from keeping it from Y axis labels. I wish to achieve something like this. Would appreciate any help possible

![material_blood_sugar copy](https://cloud.githubusercontent.com/assets/3083995/11762449/b075f860-a10c-11e5-9643-b73f26ee0db0.png)

**Comment by PhilJay** [comment]
Maybe `yAxis.setXOffset(...)` can help you with that. You will probably have to play around a bit with the numbers to get the right distance.

Concerning the label count, you can use `yAxis.setLabelCount(3, true)` to set it to a fixed size of "3" for example.
