### ISSUE TITLE
Customization xAxis on my ArrayData BarChart

### ISSUE THREAD

**Issue by Viniciuscarvalho** [PhilJay/MPAndroidChart#1276]
Hello, I am trying to customize my graphic texts and I'm not getting.
I am wanting to put the white color in the graphic texts.

My methods are as follows,

private ArrayList<BarDataSet> getDataSet() {
        ArrayList<BarDataSet> dataSets = null;

        ArrayList<BarEntry> valueSet = new ArrayList<>();
        valueSet.add(new BarEntry(100f, 0));
        valueSet.add(new BarEntry(80f, 1));
        valueSet.add(new BarEntry(70f, 2));
        valueSet.add(new BarEntry(120f, 3));
        valueSet.add(new BarEntry(30f, 4));
        valueSet.add(new BarEntry(35f, 5));

        BarDataSet barDataSet = new BarDataSet(valueSet, "Medições");
        barDataSet.setColor(Color.rgb(22, 134, 100));
        barDataSet.setBarSpacePercent(3);

        dataSets = new ArrayList<>();
        dataSets.add(barDataSet);
        return dataSets;
    }

    private ArrayList<String> getXAxisValues() {
        ArrayList<String> xAxis = new ArrayList<>();
        xAxis.add("Jan");
        xAxis.add("Fev");
        xAxis.add("Mar");
        xAxis.add("Abr");
        xAxis.add("Mai");
        xAxis.add("Jun");

        return xAxis;
    }

**Comment by PhilJay** [comment]
duplicate #1275

**Comment by PhilJay** [comment]
Axis styling:

https://github.com/PhilJay/MPAndroidChart/wiki/The-Axis

X-Axis specific:

https://github.com/PhilJay/MPAndroidChart/wiki/XAxis-%28XLabels%29
