### ISSUE TITLE
New Feature request: Color background between limit lines

### ISSUE THREAD

**Issue by leijdekkers** [PhilJay/MPAndroidChart#1277]
Hi

I would like to color the background between limit lines. So for example i have 3 limit lines in my graph and the color between the first and second limit line should be light green and between the second and third limit line the background should be red. 

This would be a nice enhancement of the library and used a lot in graphs to show whether values are in the good /bad zone...

thanks Peter

**Comment by PhilJay** [comment]
I am currently working on other features, maybe this is something for the future.
