### ISSUE TITLE
How to reduce the space between the bar without increasing the bar width

### ISSUE THREAD

**Issue by sathishkumars92** [PhilJay/MPAndroidChart#1282]
Hi I need to put three bar which is static not more than three , so I want to put the bars in centre and dont want much space between the bars and bar size also be same and small

**Comment by valentin-sobolev** [comment]
In your BarDataSet you should call .setBarSpacePercent(0). It will set spaces between bars to 0.

**Comment by econBabar** [comment]
With latest version setBarSpacePercent doesn't exists.
