### ISSUE TITLE
How to make the chart and the other chart with the same action 

### ISSUE THREAD

**Issue by Han0224** [PhilJay/MPAndroidChart#1286]
Hi,PhilJay.
I have a CandleStickChart and a BarChart below it. When I make CandleStickChart zoom in or out or translate, I want BarChart do the same action.
Do you have a solution about this?

**Comment by bingofly** [comment]
in stackoverflow . You can search.

**Comment by Han0224** [comment]
@bingofly http://stackoverflow.com/questions/28521004/mpandroidchart-have-one-graph-mirror-the-zoom-swipes-on-a-sister-graph
It's working ! Thanks
