### ISSUE TITLE
Text Wrap in Legend

### ISSUE THREAD

**Issue by jvcsizilio** [PhilJay/MPAndroidChart#1288]
How to wrap text in chart?

**Comment by PhilJay** [comment]
`legend.setWordWrapEnabled(boolean enabled)`

**Comment by jvcsizilio** [comment]
Hi,
i refer to the sidebar legend, like [here] (https://camo.githubusercontent.com/2ec281e0ac3013076bff1c3ac00d8d6de372d7a4/68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d5043686172742f6d61737465722f73637265656e73686f74732f686f72697a6f6e74616c5f62617263686172742e706e67)

I need wrap text in "jun", "May" and "Apr". This is possible?

Thanks.
