### ISSUE TITLE
Zooming in perticular direction

### ISSUE THREAD

**Issue by sandeeptengale** [PhilJay/MPAndroidChart#1291]
Is it possible to zoom in particular direction? I mean only in X direction or Y direction

Like horizontal pinch should make zoom in X axis and vertical pinch will make zoom in y axis

**Comment by PhilJay** [comment]
Yes.

`chart.setPinchZoom(false)`

https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart
