### ISSUE TITLE
Yvalues=0

### ISSUE THREAD

**Issue by SlandKiss** [PhilJay/MPAndroidChart#1295]
PieChart View,if the Yvalues include 0,how to hide the 0 value or set the 0's textcolor

**Comment by PhilJay** [comment]
Use the [ValueFormatter](https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface)

**Comment by SlandKiss** [comment]
I mean not that,man. Look,i just suggest  the api provide the method as that Piedata.getYVals().get(index).setValueTextColor(int). As this way,we can set each YValue's textColor
