### ISSUE TITLE
Wrong order of draw calls when using LineDataSet.setDrawFilled

### ISSUE THREAD

**Issue by roughboy** [PhilJay/MPAndroidChart#1298]
When drawing chart with option setDrawFilled(true) the first draw call is drawing chart solid line and then drawing fill area below the line. The result of thhis is that part of the chart sold line is being overdrawn with the fill area color.
The correct order should be first drawing fill area and then drawing chart solid line - that will guarantee no overdrawn of the chart solid line.

**Comment by PhilJay** [comment]
That just depends on the order you add your `DataSets`

**Comment by roughboy** [comment]
I think you misunderstood me. I did mean single DataSet like this:

<pre><code>LineDataSet dataSet = new LineDataSet(data, "title");
dataSet.setDrawFilled(drawFilled);
dataSet.setLineWidth(getResources().getDimension(R.dimen.chart_line_size));</code></pre>

in which the fill part of the chart is drawn over line, and should be opposite.
![chart](https://cloud.githubusercontent.com/assets/6866304/11938186/47a04fc0-a819-11e5-8264-6533e55aecb1.png)
