### ISSUE TITLE
Graph Area Color

### ISSUE THREAD

**Issue by hfarinha** [PhilJay/MPAndroidChart#1299]
Hi, 

How can i set , the graph area color, to a diffent color than white.

I use "chart.setBackgroundColor(Color.TRANSPARENT);", but the graph background stays white.

I pretende something like https://camo.githubusercontent.com/7a2dab07378f11cc33a3009d495f9f5eacbabc7e/687474703a2f2f7777772e616368617274656e67696e652e6f72672f64696d616765732f74656d70657261747572655f72616e67655f63686172742e706e67 and not like https://lh4.ggpht.com/6cnsvYUeE1ZFVSjeBsjWQme2lEVq2HBB-m1actPKEMXisQAz_-sDZy1U4y3tIBy5JA=h900

Thanks.

**Comment by PhilJay** [comment]
`chart.setDrawGridBackground(false)`
`chart.setBackgroundColor(colorOfYourChoice)`

**Comment by hfarinha** [comment]
Thanks for your help
