### ISSUE TITLE
setDrawBorders cannot resolve

### ISSUE THREAD

**Issue by vanjavanjavanja** [PhilJay/MPAndroidChart#1300]
Hi
I saw there is an option to set borders to the chart (Pie Chart) but the Android Studio says it cannot resolve such method:
`setDrawBorders`
in
`PieChart piechart;`
`piechart.setDrawBorders(true);`

**Comment by PhilJay** [comment]
this method is not available for piechart

**Comment by esfahanpayamak94** [comment]
هنگامی که جهت کسب و کار خود سایتی را طراحی می کنید احتمال دارد از طراح سایت خود در مورد [بهینه سازی سایت اصفهان](http://www.esfahanpayamak.com/seo) (سئو سایت) اطلاعاتی دریافت نمایید و به اهمیت آن پی ببرید. در اینجا قصد داریم به زبان ساده در مورد بهینه سازی وب سایت توضیحاتی دهیم .
