### ISSUE TITLE
HorizontalBarChart - need to disable automatic compression (ZoomIn)

### ISSUE THREAD

**Issue by AngelOfMors** [PhilJay/MPAndroidChart#1301]
The Y-axis is very much values. Chart is automatically fit in a window, causing a lot of data is not visible, to a very small height of the element, we have zoomed to the full display.
How to disable this behavior?
It is necessary that the height of one element is equal to the font size.

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport
