### ISSUE TITLE
problem  saveToPath() or saveToGallery() method

### ISSUE THREAD

**Issue by xbandx68** [PhilJay/MPAndroidChart#1303]
Hi, I'm using your library in my app. I test saveToPath() or saveToGallery() method, but it makes "java.lang.IllegalArgumentException: width and height must be > 0".

As I see vars of 'mChart' by debugger, I think the problem lies on position vals are 0, such as mLeft = 0 and mRight = 0.. but I can't understand why and how to handle it.
The chard are draw correctly inside a Listview (listGraph):
...
...

listGraph.add(new BarChartItem(generateDataBar(NameIng, QtaProductMese), GappContext));
...
...
..
but when I select the otion menu 'SavetoGallery' the app crash
"java.lang.IllegalArgumentException: width and height must be > 0".

@Override
	public boolean onOptionsItemSelected(MenuItem item) {

		switch (item.getItemId()) {

			case R.id.actionSave: {

				if (mChart.saveToPath("produzione" + System.currentTimeMillis(), "")) {
					Toast.makeText(GappContext, "Saving SUCCESSFUL!",Toast.LENGTH_SHORT).show();
				} else
					Toast.makeText(GappContext, "Saving FAILED!", Toast.LENGTH_SHORT).show();

				if (mChart1.saveToGallery("ore_permanenza" + System.currentTimeMillis(), 50)) {
					Toast.makeText(GappContext, "Saving SUCCESSFUL!",Toast.LENGTH_SHORT).show();
				} else
					Toast.makeText(GappContext, "Saving FAILED!", Toast.LENGTH_SHORT).show();
				break;
			}
		}
		return true;
	}

**Comment by PhilJay** [comment]
looks like the chart you are trying to save has a height or width of 0 - that is not possible

**Comment by xbandx68** [comment]
Sorry, but the all the chart (mChart and mChart1) are added on the ListView and show on screen correctly, but when I try to use actionSave, the app crash, and I have used the debug and the width and the height are 0!!
