### ISSUE TITLE
Cant seem to use package: import com.github.mikephil.charting.interfaces.datasets.ILineDataSet;

### ISSUE THREAD

**Issue by Junaid-Sakib** [PhilJay/MPAndroidChart#1306]
If I import the lib manually it works, however the above package is unknown if the dependency is added to Gradle using: 

compile 'com.github.PhilJay:MPAndroidChart:v2.1.6

**Comment by PhilJay** [comment]
this is not released yet

**Comment by Junaid-Sakib** [comment]
Thanks for the lib mate :)

**Comment by komal3003** [comment]
I am not able to import 
 com.github.mikephil.charting.interfaces.datasets.ILineDataSet;

Is the lib released now?
