### ISSUE TITLE
Pie Chart data refresh

### ISSUE THREAD

**Issue by Betthub** [PhilJay/MPAndroidChart#1307]
Hello there, I've been trying to construct my own PieChart. 

Currently I have a ViewPager with 3 Fragments displaying, and data in the first two Fragments supply the information for the PieChart which is positioned in the third one. 
It happens that I change some things in the data fragments, and my PIeChart needs to be updated with the new values that have changed as such:

```java
 public void insertPie(Data data)
    {
        PieDataSet pieDataSet = this.pie.getData().getDataSet();
        Entry e = pieDataSet.getEntryForXIndex(0);
        float val = e.getVal();

        if(data.getX().toLowerCase().equals("z")) 
        {
            ++al;
            boys.setVal(boysVal);
        }
        pie.invalidate();
}
```

This piece of code updates the values inside the pie chart, but the slices of the Pie itself are not updated. What am I doing wrong?

**Comment by PhilJay** [comment]
call notifyDataChanged() before invalidate()

**Comment by Betthub** [comment]
This is indeed redrawing part of the PieChart, the problem now is that the PieChart is adding or removing one of its pieces. So for example, if instead of adding the values in the example above I do 
````java
if(data.getX() == myVal)
{
    --val;
    entry.setVal(val);
}
pie.notifyDataChanged();
pie.invalidate();
````

part of the pie is now missing. :\
