### ISSUE TITLE
LineChart :Different point colors in same line

### ISSUE THREAD

**Issue by Don2012** [PhilJay/MPAndroidChart#1308]
Hi,

In my case, I need to show different colors in the same line. 
If the yValue is higher than "30", the point should be in red. 
If the yValue is lower than "20", the point should be in blue.
If the yValue is between 20-30 , the point should be in green.

I tried to use 3 LineDataSets. However, it made three lines in the chart, not one line.

Is it possible to make a chart like the below ?
![3521xdu](https://cloud.githubusercontent.com/assets/16362027/11999918/a510b058-ab04-11e5-8127-e6aa3d77e194.png)
![images](https://cloud.githubusercontent.com/assets/16362027/11999916/9d16826a-ab04-11e5-89d1-e9f0ef483ee3.png)

Thanks a lot.

**Comment by Don2012** [comment]
setCircleColors work for me.
However, it is possible in setCircleColorHole?

**Comment by rohan31710** [comment]
Can you please give me example of setCircleColors  with dynamic values and depends upon range i can change color f circle.

**Comment by lmdiloveu** [comment]
@rohan31710 你解决这个一条线不同圆圈颜色的问题了吗？可以解决吗？
你解决了吗
Have you solved it？

**Comment by krunalp1993** [comment]
@Don2012 Could you please let us know how you fixed it?

@rohan31710 @lmdiloveu Did you fix it?
