### ISSUE TITLE
Extending the horizontal gridlines

### ISSUE THREAD

**Issue by mike-esokia** [PhilJay/MPAndroidChart#1314]
<img width="327" alt="screen shot 2015-12-28 at 1 39 06 pm" src="https://cloud.githubusercontent.com/assets/16316721/12016756/68cbed86-ad68-11e5-8a3d-dbe987ecaf7f.png">

Hi. Is there a method for extending the gridlines as shown on the screenshot?

**Comment by PhilJay** [comment]
Not by default. But it should not be hard to modify the library in a way to achieve this.
