### ISSUE TITLE
Change color while raising and add horizontal line

### ISSUE THREAD

**Issue by androideveloper** [PhilJay/MPAndroidChart#132]
I have debts and debt limit. I want to have debt limit as a fixed horizontal line and debts as bars in barchart. Is there a way to add horizontal line in barchart? And if debt bar is greater than limit, change color of bar while raising (when line is crossed)?

**Comment by jayramhari** [comment]
Why is'nt the addLimitLine() not showing in your library version 2.1.3 or am I making any mistakes. The limitline is created but the method is not showing up

**Comment by tuanlamsts** [comment]
Hi @PhilJay ,
I am getting some problem with barchart when adding multi limit lines.
It show wrong line color
