### ISSUE TITLE
setAxisMaxValue and setAxisMinValue

### ISSUE THREAD

**Issue by nikolaz111** [PhilJay/MPAndroidChart#1320]
In the case where the values shown are all positive, and we call `setAxisMinValue()` with a negative value as a parameter, the chart only displays the axis in starting from 0. This is not desirable in many cases, specially if you want to play with overlapped charts. the `setAxisMinValue()` should be absolute, even if there are no values below zero.

**Comment by PhilJay** [comment]
try `yAxis.setStartAtZero(false)`

**Comment by nikolaz111** [comment]
I did that but no luck :(
