### ISSUE TITLE
interfaces datasets not being imported

### ISSUE THREAD

**Issue by soundfx37** [PhilJay/MPAndroidChart#1321]
I've tried using the library as a jar and from the maven repository, but when I try to import ...interfaces.dataset nothing is available.  The only available options are for the provider class set. 
![untitled-1](https://cloud.githubusercontent.com/assets/16358824/12056759/f424376c-aeee-11e5-8d9a-2c41d5fe54ae.jpg)

**Comment by PhilJay** [comment]
Those classes are not released yet.

**Comment by soundfx37** [comment]
Hi Mike PhilJay,
So, does that mean the real time data isn't released either seeing as you use the dataset interface class there?


Sent from my T-Mobile 4G LTE Device


-------- Original message --------
