### ISSUE TITLE
LargeValueFormatter

### ISSUE THREAD

**Issue by AngelOfMors** [PhilJay/MPAndroidChart#1323]
Debug from: String makePretty(double number)
1) Lenovo A319 (Android 4.4.2)
Generate value (etc number) for Legend X-Axis: 99999, 199998, 299997
2) Android emulator (4.0.3) & Samsung Tablet (5.0.2): 100000, 200000, 300000

I will be testing continue.

**Comment by AngelOfMors** [comment]
![bugs1](https://cloud.githubusercontent.com/assets/13793037/12073432/5ba57456-b14b-11e5-9a87-e9bc90a4e033.JPG)

**Comment by AngelOfMors** [comment]
Change:
double intervalMagnitude = Utils.roundToNextSignificant(Math.pow(10, (int) Math.log10(interval)));

**Comment by AngelOfMors** [comment]
Change:
double intervalMagnitude = Utils.roundToNextSignificant(Math.pow(10, (int) Math.log10(interval)));

**Comment by dexterbg** [comment]
Confirmed: default formatter shows "4.000", LargeValueFormatter shows "3,9k" (german locale).

Added sub-issue, may be locale related: 15000 is shown as "15,k" instead of "15k" or "15,0k"
