### ISSUE TITLE
I manually set DefaultValueFormatter(0) to a ChartData but still show 1 digital in DecimalFormat.

### ISSUE THREAD

**Issue by coolscott** [PhilJay/MPAndroidChart#1327]
My solution as below for your reference:

step-1. in public void setData(T data) of MPChartLib\src\com\github\mikephil\charting\charts\Chart.java
add a Disable flag to skip calling calculateFormatter(data.getYMin(), data.getYMax());

step-2. in MPChartLib\src\com\github\mikephil\charting\data\DataSet.java
<br>public boolean needsDefaultFormatter() {
<br> if (mValueFormatter == null)
<br>    return true; 
<br>//if (mValueFormatter instanceof DefaultValueFormatter)  //ignore it for an unreasonable case
<br> //    return true;
<br>return false;
<br>}

**Comment by PhilJay** [comment]
Just use the formatter like it's supposed to be used: https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface

**Comment by coolscott** [comment]
thank you so much.
