### ISSUE TITLE
Could not see the Performance result

### ISSUE THREAD

**Issue by licongqi** [PhilJay/MPAndroidChart#1329]
Hi, I can't see the result for performance test from here.
https://github.com/PhilJay/MPAndroidChart/wiki/Performance
![image](https://cloud.githubusercontent.com/assets/12727554/12091197/3d82b754-b330-11e5-9a54-f8be9a30f5b2.png)
That's what I get, maybe there is something wrong with my network, would you show me the result please?
I merely found this info. https://github.com/PhilJay/MPAndroidChart/issues/1245
Thank you very much!

**Comment by PhilJay** [comment]
This wiki entry is not complete yet. I did not have the time so far to do all the tests.

**Comment by hzlicongqi** [comment]
ok, thanks any way!
