### ISSUE TITLE
Time chart support

### ISSUE THREAD

**Issue by kenaiX** [PhilJay/MPAndroidChart#133]
i used AChartEngine and your jar , if you can support time chart like AChartEngine , i think may be very useful !!

**Comment by danielgindi** [comment]
@tsengvn well of course you can! Just make your formatter query for the current scale, so you can decide what to show.

**Comment by danielgindi** [comment]
That's actually how it's always done in charts. You do not create a "time specific chart". You format the X labels based on visibility.

**Comment by klassm** [comment]
Hi @danielgindi 

Of course you can format x labels, but this is not always the only usecase. Having graph entries stemming from different time intervals (i.e. one entry after an hour, the next one 5 minutes later and the next one 20 minutes later) will result in three datapoints shown in the graph. This is correct. However, this looks ugly, because MPAndroidChart will position all three datapoints with the same distance between each other - which is wrong. Of course, MPAndroidChart cannot decided whether we got strings or dates as x labels.

Still, in my opinion, this is exactly what this issue is about.

Matthias

**Comment by mynavy** [comment]
+1 for time chart support

**Comment by rascheC** [comment]
+1

**Comment by Jambetito** [comment]
+1

**Comment by klassm** [comment]
Well, home many votes do you need :-)

**Comment by Zainulabdeen** [comment]
Looking to make this. If anyone have sample code then help :) Thanks

**Comment by mohitagrawal** [comment]
+1

**Comment by davidstosik** [comment]
+1

**Comment by firebear** [comment]
+1

**Comment by klassm** [comment]
Hi @PhilJay 
Does "closed" mean that time chart support is now available or does it mean you won't add support for time charts any time soon?
Thanks,
Matthias

**Comment by PhilJay** [comment]
Now supported!

**Comment by klassm** [comment]
Wow cool :-). Can you add some hint on how to achieve time axis? Thanks, Matthias

**Comment by literakl** [comment]
Hi, I am eager for this feature as well .. and some tutorial. 

I am googling around a while how to represent a date. I tried to pass a unix timestamp but it was not good idea. It seems that I need to integer indexes since the first date and then somehow map it to real dates. Real date support would be great. Is it 3.0 feature?

**Comment by Yasir-Ghunaim** [comment]
@klassm and @literakl,
Check my comment to know how to use timestamps with MPAndroidChart: https://github.com/PhilJay/MPAndroidChart/issues/789#issuecomment-241507904

**Comment by tasosno1** [comment]
@Yasir-Ghunaim  -- Hi, I saw your solution and guide, looks exactly what i need but i just started to nice Chart library and i appreciate if you could do a proper demo. Am trying to get stock data at the moment and although i get the graph Ok im strugling the time in (HH:MM) 

If you are familiar with Volley you could do the following as i do

```
private void makeChart() {

        url = "http://chartapi.finance.yahoo.com/instrument/1.0/AAPL/chartdata;type=quote;range=1d/json";

        StringRequest strReq = new StringRequest(Request.Method.GET,
                url, new Response.Listener<String>() {

            @Override
            public void onResponse(String response) {

              String data =  response.toString().substring(response.toString().lastIndexOf("\"series\" : [") + 1);

              String  newdata = data.replace("series\" : ", "");
                String  result = newdata.replace("\n" +
                        "} )", "");

                try {
                    JSONArray json = new JSONArray(result);

                    for (int i = 0; i <= json.length(); i++) {

                        JSONObject objv = json.getJSONObject(i);
                        
                        time = objv.getString("Timestamp");
                        open = objv.getString("open");

                        float open = Float.parseFloat(time);
                        float val  = Float.parseFloat(open);

                        ///// Insert to Chart Array
                        
                    }

                } catch (JSONException e) {
                    e.printStackTrace();
                }

                    }


        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                VolleyLog.d(TAG, "Error: " + error.getMessage());


            }
        });

        AppController.getInstance().addToRequestQueue(strReq);

         handlerb = new Handler();
        handlerb.postDelayed(new Runnable() {
            public void run() {


            //// Setup Chart and Display

                     }
        }, 1000);
    }

```

The Above fetches Json from Yahoo charts, as a string and cleans it up a bit with the final data looking like this

```
[
 { "Timestamp" :1473341400,"close" :107.1600,"high" :107.2500,"low" :107.1000,"open" :107.2500,"volume" :1354400 } 
, { "Timestamp" :1473341519,"close" :106.7900,"high" :107.1800,"low" :106.6300,"open" :107.1600,"volume" :819100 } 
, { "Timestamp" :1473341520,"close" :106.9200,"high" :106.9600,"low" :106.7400,"open" :106.7900,"volume" :460600 } 
, { "Timestamp" :1473341639,"close" :106.9700,"high" :106.9900,"low" :106.8100,"open" :106.9000,"volume" :302000 } 
, { "Timestamp" :1473341699,"close" :106.9050,"high" :107.0800,"low" :106.9000,"open" :106.9865,"volume" :386300 }
.
.
. ]

```

So at the moment the chart Displays fine inserting data like this ``yVals1.add(new Entry(i, val));`` following the Linechart Demo. But As i menttioned above im stuck with the time to show below the chart following your instructions.


![untitled-1](https://cloud.githubusercontent.com/assets/9547308/18406284/c386f9b8-7703-11e6-9a9a-95df367df524.jpg)

**Comment by tasosno1** [comment]
@Yasir-Ghunaim -- I manged to add the time by doing the following but i would still like know how to implement your method.

Thanks

```
//set up array
 ArrayList<String> xValues = new ArrayList<String>();  

                        //convert unix time to date time and add to array
                        long unixSeconds = Long.parseLong(time);
                        Date date = new Date(unixSeconds*1000L); 
                        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm"); 
                        sdf.setTimeZone(TimeZone.getTimeZone("America/New_York")); 
                        String formattedDate = sdf.format(date);
                        
                        xValues.add(formattedDate);



         / /add the Times to the Xaxis
   xAxis.setValueFormatter(new AxisValueFormatter() {
                    @Override
                    public String getFormattedValue(float value, AxisBase axis) {
                        return xValues.get((int) value % xValues.size());
                    }

                    @Override
                    public int getDecimalDigits() {
                        return 0;
                    }
                });
```

**Comment by timusus** [comment]
Heads up, If you're using a unix timestamp, when it gets converted to Float, it loses precision, so lots of timestamps that actually represent different times end up being rounded and represented as the same x value. See #2891
