### ISSUE TITLE
PieChart.setCenterText() overloads

### ISSUE THREAD

**Issue by matiash** [PhilJay/MPAndroidChart#1332]
Is there a reason there are two distinct overloads:
 * `void setCenterText(SpannableString text)`
 * `void setCenterText(String text)`

instead of a single `setCenterText(CharSequence text)`, as is common usage in the rest of the Android framework, e.g. [`TextView.setText()`](http://developer.android.com/reference/android/widget/TextView.html#setText%28java.lang.CharSequence%29)?

As far as I can see by browsing the code, the text is only used to instantiate a `StaticLayout` in `PieChartRenderer.drawCenterText()`, and `StaticLayout` can handle `CharSequence`. It does not need to be specifically passed a `SpannableString` instance.

I think that having a single method receiving `CharSequence` would make the API slightly cleaner and bring it more in-line with the standard Android conventions.

**Comment by matiash** [comment]
See https://github.com/PhilJay/MPAndroidChart/pull/1333
I have tested it and seems to work just as before.

**Comment by matiash** [comment]
It might also be worthwhile to replace other Strings by CharSequence (e.g. for setDescription(), names in datasets and x-values, &c).

**Comment by PhilJay** [comment]
merged
