### ISSUE TITLE
MarkerView: diffrerent xVals and yVals lag

### ISSUE THREAD

**Issue by adek** [PhilJay/MPAndroidChart#1335]
I've got problem with LineChart.

At the moment I'm using it to shome values in time. There is no time series in MPAndroidChart that's why I'm using simple indexing to do it (after suggersion in other thread from @PhilJay #12 )

So:
_It is not necessary that each possible index on the x-axis (ranged from 0 to 365) is bound to a value._
That's right. I've got for example XAxis with 365 values and YAxis with 20 values. 

I'm using MarkerView - if the number of values if diferent it's hard to use them. We have something we can call "lag". Trying to drag over values generates some "lag". But it's not connected with the size of data. I'm calling it lag because it looks like a lag. 

I've  been trying to fix it - no luck.

For example chart is super smooth if you'll add dummy YAxis with the same number of values. I've been trying to do that but then there are problem with showing markers. Maybe there is a better way or this is a bug.

Just try to fill XVals with the range 0 - 365
And then try to set only selected indexes for YVals. 

Turn on MarkerView and try to navigate between points.

**Comment by PhilJay** [comment]
So what you mean is that the marker does not appear between data points, but just hops from one point to the next? If there is significant space between the points, there is lag. Is that what you mean?

**Comment by PhilJay** [comment]
I have identified the issue. The new version 3.0.0 will contain the fix.
