### ISSUE TITLE
Can I set the min and max for X values and let the API auto calculate the X values, like the way we have for Y axis?

### ISSUE THREAD

**Issue by 176873548** [PhilJay/MPAndroidChart#1336]
thank for your project!
my project collect user's gps points,because distance is float and random. X valuesDesign is not friendly to the user,I hope set min and max and step.Design will be good!
please help me,thank you

**Comment by altairmizuchi** [comment]
yup. Ability to construct lines via x-y-tuple way (for example, HelloChart) for auto x spacing would be great.

**Comment by PhilJay** [comment]
This will work in v3.0.0
