### ISSUE TITLE
YAxis setAxisMaxValue not working

### ISSUE THREAD

**Issue by Mbt925** [PhilJay/MPAndroidChart#1338]
After updating data, i am resetting yAxis max via "yAxis.setAxisMaxValue", but YAxis doesn't update at all. Why?

    private void updateData() {
        BarData data = mChart.getData();
        if (data != null) {
            BarDataSet barDataSet= data.getDataSetByIndex(0);
            float maxY=4;
            for (int i = entries.size()-1, j=0; i>=0; i--, j++) {
                barDataSet.getEntryForXIndex(j).setVal(entries.get(i));
                maxY= Math.max(maxY, entries.get(i));
            }

            YAxis yAxis= mChart.getAxisLeft();
            yAxis.setAxisMaxValue(maxY + 1);
            mChart.invalidate();
        }
    }

**Comment by coolscott** [comment]
try mChart.notifyDataSetChanged();

**Comment by Mbt925** [comment]
It's not working either:

    private void updateData() {
        BarData data = mChart.getData();
        if (data != null) {
            BarDataSet barDataSet= data.getDataSetByIndex(0);
            float maxY=4;
            for (int i = entries.size()-1, j=0; i>=0; i--, j++) {
                barDataSet.getEntryForXIndex(j).setVal(entries.get(i));
                maxY= Math.max(maxY, entries.get(i));
            }
            mChart.notifyDataSetChanged();

            YAxis yAxis= mChart.getAxisLeft();
            yAxis.setAxisMaxValue(maxY + 1);
            mChart.setVisibleYRangeMaximum(maxY + 1, YAxis.AxisDependency.LEFT);
            mChart.invalidate();
        }
    }

**Comment by coolscott** [comment]
"YAxis doesn't update at all. " 
beg pardon
Did you need  yAxis.setAutoScaleMinMaxEnabled() instead?

**Comment by Mbt925** [comment]
setAutoScaleMinMaxEnabled() is one of Chart's methods and has other applications!

**Comment by Mbt925** [comment]
Thanks. Your last suggestion worked.
"and mChart.notifyDataSetChanged(); right before mChart.invalidate(); please
