### ISSUE TITLE
Dynamic Loading Data While Dragging

### ISSUE THREAD

**Issue by Mbt925** [PhilJay/MPAndroidChart#1339]
I want to dynamically load new data into chart while user is dragging to the left. (For example when getLowestVisibleXIndex()<10)
But OnChartGestureListener gives me only start and end of drag events. Does anyone have any suggestions?

**Comment by PhilJay** [comment]
`onChartTranslate(...)` & `onChartFling(...)` might be methods of the `OnChartGestureListener` that you should check out. 

https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart
