### ISSUE TITLE
CandleDataset Entry Horizontal line always white

### ISSUE THREAD

**Issue by hetdev** [PhilJay/MPAndroidChart#1341]
When I change the value for the entries in the CandleDataset, there is a horizontal line always in white, anyone can help to turn it in another color. 
Here it is some of the code:

        CandleDataSet candleDataSet = new CandleDataSet(candleEntries, "Min/Max");
        candleDataSet.setBodySpace(0f);
        candleDataSet.setShadowWidth(1f);
        candleDataSet.setDrawValues(false);
        candleDataSet.setDecreasingColor(ContextCompat.getColor(this, R.color.colorTransparent));
        candleDataSet.setIncreasingColor(ContextCompat.getColor(this, R.color.colorTransparent));
        candleDataSet.setDrawVerticalHighlightIndicator(false);
        candleDataSet.setDrawHorizontalHighlightIndicator(false);
        candleDataSet.setColor(ContextCompat.getColor(this, R.color.colorGreenAnalytics));
        candleDataSet.setAxisDependency(YAxis.AxisDependency.LEFT);
        mCandleData = new CandleData(xValsReturns);
        mCandleData.addDataSet(candleDataSet);

![image](https://cloud.githubusercontent.com/assets/12351362/12155677/8d9b8170-b494-11e5-84f8-534a37850f2d.png)

**Comment by hetAuxo** [comment]
I tried the method setShadowColor, but the color change affected both horizontal and vertical line.

    candleDataSet.setShadowColor(ContextCompat.getColor(this, R.color.colorTransparent));

**Comment by PhilJay** [comment]
Take a look at this:

https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/CandleStickChartActivity.java#L195-L201
