### ISSUE TITLE
'Datasets' directory missing in interfaces

### ISSUE THREAD

**Issue by BalalakshmiSadhasivam** [PhilJay/MPAndroidChart#1342]
I've added the following url to my gradle.
compile 'com.github.PhilJay:MPAndroidChart:v2.1.6'

I can't import IBarDataSet file to my activity.It shows 'cannot resolve symbol 'datasets' while importing. How can I import IBarDataSet file?

**Comment by smw7156** [comment]
same problem, I need to plat line graph but having problem in importing Datasets.

import com.github.mikephil.charting.interfaces.**datasets**.ILineDataSet;
"Cannot resolve symbol datasets"

And so,
List<**ILineDataSet**> dataSets = new ArrayList<**ILineDataSet**>();
        dataSets.**add**(set1);

android studio showing error in these words(All the libraries and dependencies added)
