### ISSUE TITLE
Bug in drawCubic?

### ISSUE THREAD

**Issue by maksim88** [PhilJay/MPAndroidChart#1345]
Hey, first of all thanks for this cool library!

i think I found a bug inside the drawing mechanism of the lines, i suppose.

The first image shows a a line connecting the points in the linear style. There everything is fine.
![screen shot 2016-01-07 at 15 15 58](https://cloud.githubusercontent.com/assets/5750253/12172525/b562e884-b551-11e5-989a-29a109a2d9c3.png)

The next image below shows the same graph, but with `drawCubic` set to `true`.
![screen shot 2016-01-07 at 15 14 42](https://cloud.githubusercontent.com/assets/5750253/12172548/e1dd03fe-b551-11e5-8586-9fbc5019bb64.png)

As you can see, there is a small line before the first point which is too long.
Maybe the starting point of the cubicLine inside the LineChartRenderer is wrong?

Thanks a lot!

**Comment by michaelmuenzer** [comment]
Did you came up with a solution?, because I have the same problem and need a fix/workaround for it.

**Comment by m-glebova** [comment]
Maybe,you have solution for this bug in cubic draw
https://github.com/PhilJay/MPAndroidChart/issues/1031?
I've found a workaround,but it appeared that there is still some kind of approximation error

**Comment by PhilJay** [comment]
Should be fixed now.
