### ISSUE TITLE
Port to ContextCompat

### ISSUE THREAD

**Issue by NilayKulkarni** [PhilJay/MPAndroidChart#1346]
If the app's support libraries are latest, the DataSet.setColors() method parses the wrong colors or doesn't parse anything because the getResources.getColor() method is deprecated.

Port to ContextCompat.getColor()

**Comment by danielgindi** [comment]
Do you want to make a PR for that? :-)

**Comment by jaredsburrows** [comment]
:+1:

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
