### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by linlei1990527** [PhilJay/MPAndroidChart#1348]
java.lang.OutOfMemoryError
Failed to allocate a 1152012 byte allocation with 435442 free bytes and 425KB until OOM
dalvik.system.VMRuntime.newNonMovableArray(Native Method)
android.graphics.Bitmap.nativeCreate(Native Method)
android.graphics.Bitmap.createBitmap(Bitmap.java:817)
android.graphics.Bitmap.createBitmap(Bitmap.java:794)
android.graphics.Bitmap.createBitmap(Bitmap.java:761)
com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:88)
com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:247)
android.view.View.draw(View.java:15122)
android.view.View.updateDisplayListIfDirty(View.java:14056)
android.view.View.getDisplayList(View.java:14079)
android.view.View.draw(View.java:14846)
android.view.ViewGroup.drawChild(ViewGroup.java:3405)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
android.view.View.draw(View.java:15125)
android.view.View.updateDisplayListIfDirty(View.java:14056)
android.view.View.getDisplayList(View.java:14079)
android.view.View.draw(View.java:14846)
android.view.ViewGroup.drawChild(ViewGroup.java:3405)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
android.view.View.updateDisplayListIfDirty(View.java:14051)
android.view.View.getDisplayList(View.java:14079)
android.view.View.draw(View.java:14846)
android.view.ViewGroup.drawChild(ViewGroup.java:3405)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
android.view.View.updateDisplayListIfDirty(View.java:14051)
android.view.View.getDisplayList(View.java:14079)
android.view.View.draw(View.java:14846)
android.view.ViewGroup.drawChild(ViewGroup.java:3405)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
android.view.View.draw(View.java:15125)
android.widget.FrameLayout.draw(FrameLayout.java:592)
android.widget.ScrollView.draw(ScrollView.java:1689)
android.view.View.updateDisplayListIfDirty(View.java:14056)
android.view.View.getDisplayList(View.java:14079)
android.view.View.draw(View.java:14846)
android.view.ViewGroup.drawChild(ViewGroup.java:3405)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
android.view.View.updateDisplayListIfDirty(View.java:14051)
android.view.View.getDisplayList(View.java:14079)
android.view.View.draw(View.java:14846)
android.view.ViewGroup.drawChild(ViewGroup.java:3405)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
android.view.View.updateDisplayListIfDirty(View.java:14051)
android.view.View.getDisplayList(View.java:14079)
android.view.View.draw(View.java:14846)
android.view.ViewGroup.drawChild(ViewGroup.java:3405)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
android.view.View.draw(View.java:15125)
android.view.View.updateDisplayListIfDirty(View.java:14056)
android.view.View.getDisplayList(View.java:14079)
android.view.View.draw(View.java:14846)
android.view.ViewGroup.drawChild(ViewGroup.java:3405)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
android.view.View.draw(View.java:15125)
android.view.View.updateDisplayListIfDirty(View.java:14056)
android.view.View.getDisplayList(View.java:14079)
android.view.View.draw(View.java:14846)
android.view.ViewGroup.drawChild(ViewGroup.java:3405)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
android.view.View.updateDisplayListIfDirty(View.java:14051)
android.view.View.getDisplayList(View.java:14079)
android.view.View.draw(View.java:14846)
android.view.ViewGroup.drawChild(ViewGroup.java:3405)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
android.view.View.updateDisplayListIfDirty(View.java:14051)
android.view.View.getDisplayList(View.java:14079)
android.view.View.draw(View.java:14846)
android.view.ViewGroup.drawChild(ViewGroup.java:3405)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
android.view.View.updateDisplayListIfDirty(View.java:14051)
android.view.View.getDisplayList(View.java:14079)
android.view.View.draw(View.java:14846)
android.view.ViewGroup.drawChild(ViewGroup.java:3405)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
android.view.View.draw(View.java:15125)
android.widget.FrameLayout.draw(FrameLayout.java:592)
com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2646)
android.view.View.updateDisplayListIfDirty(View.java:14056)
android.view.View.getDisplayList(View.java:14079)
android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:266)
android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:272)
android.view.ThreadedRenderer.draw(ThreadedRenderer.java:311)
android.view.ViewRootImpl.draw(ViewRootImpl.java:2523)
android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2361)
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1992)
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1078)
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5810)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:818)
android.view.Choreographer.doCallbacks(Choreographer.java:617)
android.view.Choreographer.doFrame(Choreographer.java:583)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:804)
android.os.Handler.handleCallback(Handler.java:739)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:135)
android.app.ActivityThread.main(ActivityThread.java:5249)
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke(Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)

**Comment by jaredsburrows** [comment]
@linlei1990527 What version?
