### ISSUE TITLE
BarChart Dataset Border Problem

### ISSUE THREAD

**Issue by WrathChaos** [PhilJay/MPAndroidChart#1352]
Hello, 
First of all, thank you ! Your project is awesome. 

I have a problem about BarChart. I want to add a highlighted border on my BarChart's datasets. Unfortunately, i could not find any solution. Therefore, is there any chance to add a border on my datasets ? 

<img width="483" alt="border" src="https://cloud.githubusercontent.com/assets/6813862/12218104/e2ebe490-b71d-11e5-991a-cc01e0e9aa42.png">

I want kinda like this spreading border. 

Also, is there any way to show these dataset's value integer not double? I mean i do not want the 20.0 after dot part.

Thank you so much :)

**Comment by PhilJay** [comment]
- Take a look at the `setDrawBorder(...)` method and the method `setDrawAxisLine(..)` of the `Axis` classes.
- Take a look at the `ValueFormatter` class.

**Comment by WrathChaos** [comment]
I've already checked that methods and i have no idea about ValueFormatter class, can you help me a bit more detail please ?
