### ISSUE TITLE
Issue with large chart height in ScrollView

### ISSUE THREAD

**Issue by bbraig** [PhilJay/MPAndroidChart#1357]
For a chart inside a ScrollView, the chart's dimensions don't get set when its height is 10,000px or greater. So you end up with a chart of no height and no width (i.e., nothing). Obviously you wouldn't use PX for your chart height, but even if your DP height value is equivalent to 10,000px or greater, you get the same result.

This is easy to duplicate using the sample app. Just open activity_scrollview.xml and change the layout_height value of the chart to 10,000px. This results in no chart for the ScrollView sample. Simply setting layout_height to 9,999px results in the chart displaying fine.

You can also use setLogEnabled(true) to view the logcat output.... "Setting chart dimens" never occurs after OnSizeChanged() when the chart height is 10,000px or greater, but it does when the chart is less than 10,000px.

**Comment by PhilJay** [comment]
So your chart has a height of 10.000 pixels?
Do you think that is a good idea?
Why not just restrict the viewport?
https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport

**Comment by bbraig** [comment]
Well why is there a hard limit of 10,000px in Chart.java's onSizeChanged() method? That seems arbitrary. If anything, shouldn't the limit be documented somewhere?

I'll give you some context so hopefully you can understand my situation better. I'm using a HorizontalBarChart to display values for user-created projects during a preset time period (e.g., the current month). A user could have 0 projects or 1,000,000,000 projects, or any number in between. If I set the chart height to be constant, an increase in the number of projects (i.e., data values) causes the bars to become too thin, resulting in the labels on the vertical axis and the data values on each bar to become illegible.

Therefore the thickness of each bar needs to remain constant, in which case I need to set the height of the chart dynamically based on the number of projects (i.e., data values). More projects results in a taller chart.

**Comment by mkruglikov** [comment]
I have exactly the same case. This limit is awful
