### ISSUE TITLE
LineChart & XAxis & YOffset

### ISSUE THREAD

**Issue by AngelOfMors** [PhilJay/MPAndroidChart#1359]
Default value YOffset != 0
Crop values from below
![chartlib1](https://cloud.githubusercontent.com/assets/13793037/12256073/a0f5c2dc-b924-11e5-81a9-4e2d4228b77d.png)

**Comment by sathishkumars92** [comment]
I'm too getting the same problem .If anyone know say it quick

**Comment by PhilJay** [comment]
Yeah we have some problems with the offsets. Something is not quite right.
I'm working on it.

**Comment by PhilJay** [comment]
Is this the head version or just the latest release?

**Comment by AngelOfMors** [comment]
Last

**Comment by PhilJay** [comment]
d01f03105d171608aaf43a87ed63f4716bda39a6
