### ISSUE TITLE
Add as library android studio

### ISSUE THREAD

**Issue by caioketo** [PhilJay/MPAndroidChart#136]
Probably something Im doing wrong.
I added the .jar file to my project and added as library.
At the graddle is:
"compile files('libs/mpandroidchartlibrary-1-6-5.jar')"
and it says:
"Error:Execution failed for task ':app:dexDebug'.

> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
>     C:\Users\Caio\AppData\Local\Android\android-studio\sdk\build-tools\android-4.4W\dx.bat --dex --num-threads=4 --output C:\Users\Caio\AndroidStudioProjects\GerenciadordeEstudos\app\build\intermediates\dex\debug C:\Users\Caio\AndroidStudioProjects\GerenciadordeEstudos\app\build\intermediates\classes\debug C:\Users\Caio\AndroidStudioProjects\GerenciadordeEstudos\app\build\intermediates\dependency-cache\debug C:\Users\Caio\AndroidStudioProjects\GerenciadordeEstudos\app\build\intermediates\pre-dexed\debug\classes-2ad2e634f377109edb5f3f3003eab88b7132dd73.jar C:\Users\Caio\AndroidStudioProjects\GerenciadordeEstudos\app\build\intermediates\pre-dexed\debug\classes-42689e144852c5837065927493f4d98df98a454e.jar C:\Users\Caio\AndroidStudioProjects\GerenciadordeEstudos\app\build\intermediates\pre-dexed\debug\classes-728caae4c14f690c5f97c747461e3ebb47d5601f.jar C:\Users\Caio\AndroidStudioProjects\GerenciadordeEstudos\app\build\intermediates\pre-dexed\debug\classes-7fcb08e62e6c84b89aae3a89771bb11c50bb6168.jar C:\Users\Caio\AndroidStudioProjects\GerenciadordeEstudos\app\build\intermediates\pre-dexed\debug\classes-dfd09680352444a4de430cd1b7d0145706bd448f.jar C:\Users\Caio\AndroidStudioProjects\GerenciadordeEstudos\app\build\intermediates\pre-dexed\debug\internal_impl-20.0.0-672bad7969c057121ff0b2b1a8979fa8736fe8ba.jar C:\Users\Caio\AndroidStudioProjects\GerenciadordeEstudos\app\build\intermediates\pre-dexed\debug\mpandroidchartlibrary-1-6-5-605cd8bcffd08837c73f78d8273ef96c7c3bd37e.jar C:\Users\Caio\AndroidStudioProjects\GerenciadordeEstudos\app\build\intermediates\pre-dexed\debug\nineoldandroids-2.4.0-3b31f597c9c803eb84b00afef37b2c781071add2.jar C:\Users\Caio\AndroidStudioProjects\GerenciadordeEstudos\app\build\intermediates\pre-dexed\debug\support-annotations-20.0.0-eab61fa45cef4448a67cc22398579eaa95bd4a19.jar
> Error Code:
>     2
> Output:
>     UNEXPECTED TOP-LEVEL EXCEPTION:
>     com.android.dex.DexException: Multiple dex files define Lcom/nineoldandroids/animation/Animator$AnimatorListener;
>         at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
>         at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
>         at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
>         at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
>         at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
>         at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
>         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
>         at com.android.dx.command.dexer.Main.run(Main.java:230)
>         at com.android.dx.command.dexer.Main.main(Main.java:199)
>         at com.android.dx.command.Main.main(Main.java:103)"

when I changed the compile to provided it executes all normal but when I call some class of the .jar it throws exception "Could not find class com.github.mikephil.charting.charts.BarChart".

Any Idea on how to solve this?

**Comment by paracha3** [comment]
Thanks @caioketo , your solution helped me.

**Comment by glassweichao** [comment]
Thanks @caioketo ,your solution helped me too,
and in the latest version(here is 1.7.4), download master.zip from github,I imported it as module in my project,and use as library in my module,didn't change the build.gradle. and then it work~
thanks again

**Comment by tn00373427** [comment]
Thanks @caioketo ,your solution helped me too.
