### ISSUE TITLE
How to pass a LineData in a bundle?

### ISSUE THREAD

**Issue by aharshac** [PhilJay/MPAndroidChart#1360]
I'm using an AsyncTaskLoader in a fragment that returns a Bundle of multiple strings and a Parcelable POJO. I'm trying to put a LineData that is generated in the doInBackground of the AsyncTaskLoader but am unable to do so. Please help.

**Comment by PhilJay** [comment]
Just extend LineData and make it `Parcelable`. Android Studio can do that for you.
