### ISSUE TITLE
Highlighting value draws marker in wrong Y position

### ISSUE THREAD

**Issue by usmaanz** [PhilJay/MPAndroidChart#1363]
I have a line chart with a single value in it (right now). I'm trying to highlight the maximum value in the chart, so I'm using:

```
chart.highlightValue(barEntryIndex, 0);
```

where I only have one dataset and barEntryIndex is the index of the highest value. I expect to see the marker drawn above the plotted circle (I am drawing circles). Instead of the marker drawing above the circle, it gets drawn right on the limit line. The X position of the marker is correct but the Y position is not.

Here's a pic:
<img width="337" alt="screen shot 2016-01-12 at 17 18 06" src="https://cloud.githubusercontent.com/assets/8617849/12270928/82ffa262-b950-11e5-9dd8-3fdba1bebf30.png">

**Comment by PhilJay** [comment]
Show your implementation of the markerview

**Comment by usmaanz** [comment]
Hi @PhilJay, thanks for the reply. 

The ````layout```` of the marker:

````
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content">

    <TextView
        android:id="@+id/tvContent"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@drawable/white_rectangle"
        android:gravity="center"
        android:paddingLeft="@dimen/default_spacing_25"
        android:paddingRight="@dimen/default_spacing_25"
        android:text="20"
        android:textColor="?colorPrimary"
        android:textSize="9sp"/>

    <com.threesquared.axamobilehealth.view.UpsideDownArrow
        android:layout_width="6dp"
        android:layout_height="4dp"
        android:layout_below="@+id/tvContent"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="-1dp"/>

</RelativeLayout>
````

```chart``` object setting the marker:

```chart.setMarkerView(new CustomMarkerView(getActivity(), R.layout.marker_layout, tool, user, getResources()));```

```Highlighting``` the index:

            chart.setData(data);

            data.setHighlightEnabled(false);

            int barEntryIndex = -1;
            double highestBarValue = -1;
            if (data.getDataSets() == null || data.getDataSets().size() == 0)
            {
                return;
            }

            LineDataSet dataSet = data.getDataSets().get(0);

            List<Entry> yVals = dataSet.getYVals();
            for (int i = 0; i < yVals.size(); i++)
            {
                Entry barEntry = yVals.get(i);
                float barValue = barEntry.getVal();

                if (highestBarValue <= barValue && barValue > 0)
                {
                    highestBarValue = barValue;
                    barEntryIndex = barEntry.getXIndex();
                }
            }

            chart.highlightValue(barEntryIndex, 0);

**Comment by usmaanz** [comment]
Hi @PhilJay. This has been resolved. I was calling the ```drawMarkers();``` function in the wrong place in the ```onDraw``` function within the ```BarLineChartBase``` method.
