### ISSUE TITLE
Draw x axis labels without grid lines

### ISSUE THREAD

**Issue by inneke-dc** [PhilJay/MPAndroidChart#1364]
I want to show a line chart with data per day, during 1 week, as shown in the image.
![line chart](https://cloud.githubusercontent.com/assets/11866704/12293005/f41cfb16-b9f0-11e5-8412-065ccdaa2328.PNG)
First I created a list containing 7 values for the x axis labels:

    List<String> xVals = new ArrayList<>();
    xVals.add("Di 13");
    xVals.add("Wo 14");
    //And so on
    return new LineData(xVals, dataSets);

But then the labels would be on top of the vertical lines, and I want them between the lines. So I changed my code to add more labels:

    List<String> xVals = new ArrayList<>();
    xVals.add("");
    xVals.add("Di 13");
    xVals.add("");
    xVals.add("Wo 14");
    xVals.add("");
    //And so on
    return new LineData(xVals, dataSets);

Now there are more grid lines: between the original labels and below the originial labels. I need the ones below the original labels to go away. If I use:
    xAxis.setLabelsToSkip(1);
I see the right amount of vertical grid lines, in the correct places, but I can't see my labels anymore: only the "" labels are visible. 
![line chart 2](https://cloud.githubusercontent.com/assets/11866704/12293313/ff50607a-b9f2-11e5-92e2-bfebd4095ed5.PNG)

So the question: is there a possibility where I can draw the labels at index 1, 3, 5, ... but not show the grid lines for those labels. The only grid lines should be at index 0, 2, 4, 6, ...

**Comment by PhilJay** [comment]
Yes, everything you mentioned can be customized.

https://github.com/PhilJay/MPAndroidChart/wiki/The-Axis

**Comment by inneke-dc** [comment]
@PhilJay Could you point me to the correct method please? I can only find methods to completely enable/disable the grid lines and lables:
    - setDrawGridLines(boolean enabled)
    - setDrawLabels(boolean enabled)
What I am looking for is a method to draw some of the labels and <i>some</i> of the grid lines, which won't affect the corresponding labels.
