### ISSUE TITLE
How to stop scaling and dragging of MPAndroidchart barchart  along yaxis

### ISSUE THREAD

**Issue by miantech786** [PhilJay/MPAndroidChart#1366]
I am working on barchart example.it keep scaling and dragging on both axis.i want to stop the scaling and dragging of barchart along yaxis.is there any method for this?Kindly guide me.?

**Comment by PhilJay** [comment]
`chart.setScaleYEnabled(false)`

https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart
