### ISSUE TITLE
yaxis doesn't calculate new vlaue

### ISSUE THREAD

**Issue by lrz-hal** [PhilJay/MPAndroidChart#1367]
If i add new Values to dataset, yaxis doesn't calculate automatically. It looks like this

![image](https://cloud.githubusercontent.com/assets/2706572/12299389/cd1d2de4-ba16-11e5-8a4f-eb6ac49603ff.png)

Here's my code:

```Java
data = getChartData();
LineDataSet setSystole = data.getDataSetByLabel("Systole", true);
LineDataSet setDiastole = data.getDataSetByLabel("Diastole", true);
LineDataSet setPuls = data.getDataSetByLabel("Puls", true);
Entry valDiastole = new Entry(entity.getDiastole(), setDiastole.getEntryCount());
Entry valSystole = new Entry(entity.getSystole(), setSystole.getEntryCount());
Entry valPuls = new Entry(entity.getPuls(), setPuls.getEntryCount());
SimpleDateFormat dateformat = new SimpleDateFormat("dd.MM.yy");
data.addXValue(dateformat.format(entity.getDate()));
setDiastole.addEntry(valDiastole);
setSystole.addEntry(valSystole);
setPuls.addEntry(valPuls);
chart.notifyDataSetChanged(); // let the chart know it's data changed
chart.invalidate();
```
Is there something i missed?

Thanks,

Martin

**Comment by coolscott** [comment]
try chart.getAxisLeft().setAutoScaleMinMaxEnabled(true)
or chart.getAxisRight().setAutoScaleMinMaxEnabled(true).

**Comment by PhilJay** [comment]
Show the code of your `YAxis`!

**Comment by lrz-hal** [comment]
I use default values. No special settings.

**Comment by PhilJay** [comment]
Okay, try calling 

`data.notifyDataChanged()`
before `chart.notifyDataSetChanged()`

**Comment by lrz-hal** [comment]
That did the trick. Can you update this in DynamicalAddingActivity.java.

Many thanks!!
