### ISSUE TITLE
PieChart: extra padding at top

### ISSUE THREAD

**Issue by romangromov** [PhilJay/MPAndroidChart#137]
Hi @PhilJay,

just wanna to say you many thanks for your great library.

I'm playing with PieChart and I found some extra padding above it when using Legend.
Could you please help me to figure out how to fix it? 
![screenshot_2014-10-07-20-53-14](https://cloud.githubusercontent.com/assets/1655573/4546504/28baf2f2-4e44-11e4-915b-1021ee5ab891.png)

**Comment by LeoYe168** [comment]
@PhilJay  i want to set some extra padding in barchart bottom..which method ?

**Comment by coolscott** [comment]
give a try via Chart.setExtraBottomOffset(n); //n > default 15

**Comment by liuzheng9110** [comment]
@coolscott  3ks
