### ISSUE TITLE
YAxis.setMaxValue() not working properly

### ISSUE THREAD

**Issue by usmaanz** [PhilJay/MPAndroidChart#1372]
When I update the chart, I want to change the maximum value of the YAxis so that the LimitLine appears as per your answer in my previous post. The answer you provided worked, however, I'm experiencing an issue where it won't set the max value at certain times:

```
float quotaValue = (float) getQuota();
float maxValue;

if (quotaValue > highestBarValue)
{
    maxValue = quotaValue;
}
else
{
    maxValue = (float) highestBarValue;
}

yAxisLeft.setAxisMaxValue(maxValue);
```

I've noticed that the time it won't set the max value is when the number is quite big in relation to the highest data point. The example which didn't work was when the `maxValue` was 900 and the `highestBarValue` was 30.

When it doesn't work, it WILL work but only when I update the chart again...which at that point, I will have a completely different maxValue. So it works but it won't work for that update, it'll work for the next update. Even though I am calling the above code every time, and the maxValue will be like 27, the chart will still have scaled to 900. So it will scale to 900 but on not at the turn I want it to. I am calling `chart.clear()` and `chart.invalidate()` to ensure everything is cleared and rendered. Any ideas?

**Comment by usmaanz** [comment]
I fixed this by calling `setData` AFTER I have set the `setAxisMaxValue`.

**Comment by Svantulden** [comment]
@usmaanz Thanks a lot! I was stuck on this same issue for a long time.
