### ISSUE TITLE
BarChart Dataset Border Problem + HorizontalBarChart IBarDataSetI interface Problem

### ISSUE THREAD

**Issue by WrathChaos** [PhilJay/MPAndroidChart#1373]
Hello again,

Unfortunately, you closed my issue too early.. I still could not find the solution to add a glowing border on my specific dataset. I'm gonna copy paste my problem again. 

"I have a problem about BarChart. I want to add a highlighted border on my BarChart's datasets. Unfortunately, i could not find any solution. Therefore, is there any chance to add a border on my datasets ?"

<img width="483" alt="border" src="https://cloud.githubusercontent.com/assets/6813862/12332601/0ac0fafe-baf8-11e5-84e1-cd22a04825e8.png">

I want kinda like this spreading border.

I cannot find any solution on your answer, please give me a good example for like that spesific border. 

---

Another problem is about the HorizontalBarChart. I want to add a dataset from your sample but i cannot find any import for IBarDataSetI interface so i cannot use horizontal one. Please help me about it.

Thank you :)

**Comment by PhilJay** [comment]
- Concerning IBarDataSet -> update to the latest version
- Concerning border -> thats not possible by default, you will have to modify the renderer classes to achieve that
