### ISSUE TITLE
removeEntry(index) not updating indexes for values above

### ISSUE THREAD

**Issue by lrz-hal** [PhilJay/MPAndroidChart#1375]
If you remove an entry with remove.Entry(index), xIndex values for values before and after not updating

befor
![mpcahrt1](https://cloud.githubusercontent.com/assets/2706572/12351198/313c80de-bb7c-11e5-991b-2b1fe94be493.PNG)

after remove
![mpcahrt2](https://cloud.githubusercontent.com/assets/2706572/12351244/82f8b744-bb7c-11e5-85d1-1d040f2964c0.PNG)

So result is, after refresh the chart values are not on there right places. Is this a bug, or is there anything else you have to do after remove entries?

Thanks,

Martin

**Comment by PhilJay** [comment]
of course not, it just removes
