### ISSUE TITLE
Multi dataset BarData displayed incorrectly on CombinedChart

### ISSUE THREAD

**Issue by chmykh** [PhilJay/MPAndroidChart#1378]
Possible bug I have just observed with slightly modified version of BarChartActivityMultiDataset.java. By default, this example displays N groups of 3 bar each (so N*3 bars are actually visible). Replace BarChart with CombinedChart (in both java and layout files), then replace line 234 with the following:
        `CombinedData cd = new CombinedData(xVals);
        cd.setData(data);
        chart.setData(cd);`

With this, only N first bars are visible. It looks like bars don't get resized horizontally according to number of datasets. Last two-thirds of bars are not displayed. Visible bars don't match x axis labels.

If this it not a bug, would you please help me with workaround.

**Comment by PhilJay** [comment]
#449
