### ISSUE TITLE
Feature request: Data Binding

### ISSUE THREAD

**Issue by TheNetStriker** [PhilJay/MPAndroidChart#1382]
Are there any plans to implement support for data bindings? (http://developer.android.com/tools/data-binding/guide.html)

**Comment by PhilJay** [comment]
Not in near future, sorry.

**Comment by quiKsilverItaly** [comment]
Hello, is it supported now?

**Comment by quiKsilverItaly** [comment]
It works!!! Thanks to Custom Setters: https://medium.com/androiddevelopers/android-data-binding-custom-setters-55a25a7aea47

**Comment by prabhusns33** [comment]
can u give samples
