### ISSUE TITLE
Any plans to add custom labels to LineData?

### ISSUE THREAD

**Issue by fraklo** [PhilJay/MPAndroidChart#1384]
Something like:
Entry c1e2 = new Entry(50.000f, 1, "Custom Label"); 

Also, great job on an awesome library!

**Comment by PhilJay** [comment]
Why not use the `ValueFormatter`?
https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface

**Comment by fraklo** [comment]
Am I correct in thinking that the ValueFormatter applies to an entire set of values?

What I want to do is create a custom label for only a few values. This is for a charting activity. That is, the user is entering data and when a particular data point is chosen I need a custom label for that. Imagine the following:
// Labeled "4"
0,4
// Labeled "33"
19, 33
// Labeled: "Start"
20, 35
// Labeled: "49"
25, 49
// Labeled: "Marker 1"
26, 50
// Labeled: "End"
40, 51
