### ISSUE TITLE
about HorizontalBarChart YAxis value

### ISSUE THREAD

**Issue by helenaccount** [PhilJay/MPAndroidChart#1387]
When  Y axis values are all  negative ,the value display error.
Error
![abnormal](https://cloud.githubusercontent.com/assets/8554618/12447883/73d2fdbc-bfad-11e5-909b-a3b911fe469c.jpg)

normal
![normal](https://cloud.githubusercontent.com/assets/8554618/12447886/7975ea18-bfad-11e5-97f0-a1b91af7ea3e.jpg)

**Comment by PhilJay** [comment]
Where is the error?

**Comment by helenaccount** [comment]
thanks for you reply
Now I want to make value is opposite of the bar  ,like this
![normal](https://cloud.githubusercontent.com/assets/8554618/12469008/50a2bc12-c023-11e5-9c2f-0f39ce3d6cd2.jpg)

**Comment by PhilJay** [comment]
You mean that the bars should not cover up the grey line?

**Comment by helenaccount** [comment]
No. in your case the valueLabel only above the bar or in the bar .
Now i want when the value is less than 0 the valueLabel is on the zero line right
if the value greater than 0 ,the valueLabel is on the left

**Comment by PhilJay** [comment]
That's what is the case in the screenshots. I'm confused.

**Comment by vicmns** [comment]
I think @helenaccount tries to say is that, on a horizontal bar chart, when te values are negative, the rendering of the bar must be to the right of the Y-Axis and the label rendering must be on the right. And the oposite way on a positive value?

**Comment by PhilJay** [comment]
Yes I understand that, but the screenshots show exactly the "wanted" case.

**Comment by helenaccount** [comment]
yeah, i achieve that by change your code,but it lead to another problem,the picture one
when the values  all negative ,the value label is out of the chart,for example, the picture one first value is -3.8%, and the chart only show -3,and this code is so deep ,can not change it easily，thanks again

**Comment by PhilJay** [comment]
Then increase the value-range of your axis. This will prevent the numbers from being cut off.

`yAxis.setAxisMaxValue(...)`

https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-(YLabels)

**Comment by qingchen1016** [comment]
Thank you
