### ISSUE TITLE
Incomplete MarkerView For First and Last Entry

### ISSUE THREAD

**Issue by ctorresthrash** [PhilJay/MPAndroidChart#1388]
Hello Phil and thanks for this nice work

I'm facing a problem with the MarkerView, basically with first and last ones, here are some screenshots of my problem

![captura de pantalla 2016-01-20 a las 11 07 05 a m](https://cloud.githubusercontent.com/assets/4590204/12454545/fe2096ca-bf65-11e5-89c3-ab9f138c28f0.png)

![captura de pantalla 2016-01-20 a las 11 08 03 a m](https://cloud.githubusercontent.com/assets/4590204/12454578/1c256ba0-bf66-11e5-91d9-ee01161bc964.png)

I wonder if there is a way to drag the view beyond the first and last points to display the MarkerView's properly

**Comment by PhilJay** [comment]
This question on stackoverflow provides different clean solutions for this problem: 

http://stackoverflow.com/questions/30169327/markerview-goes-out-of-the-chart-for-the-last-point-on-the-chart
