### ISSUE TITLE
RealmBaseDataSet java.lang.NoSuchMethodError Exception

### ISSUE THREAD

**Issue by AbdulRehmanSO5** [PhilJay/MPAndroidChart#1396]
In the constructors,

this.results.sort(mIndexField, true); // Exception occurs here
please change this to
this.results.sort(mIndexField, Sort.ASCENDING);

**Comment by vieck** [comment]
How did you fix this? It's making me have to convert the realm results over manually into LineBarData

**Comment by AbdulRehmanSO5** [comment]
I manually build that library, see issue #1397 commits
