### ISSUE TITLE
Realm Multiple DataSets in a single lineData

### ISSUE THREAD

**Issue by AbdulRehmanSO5** [PhilJay/MPAndroidChart#1398]
RealmResults<SensorRealmObject> results = realm.where(SensorRealmObject.class).equalTo("id", 1).findAll();
         RealmLineDataSet<SensorRealmObject> set1 = new RealmLineDataSet<SensorRealmObject>(results, "yaxis", "xIndex");
        results = realm.where(SensorRealmObject.class).equalTo("id", 2).findAll();
        RealmLineDataSet<SensorRealmObject> set2 = new RealmLineDataSet<SensorRealmObject>(results, "yaxis", "xIndex");
        results = realm.where(SensorRealmObject.class).equalTo("id", 3).findAll();
        RealmLineDataSet<SensorRealmObject> set3 = new RealmLineDataSet<SensorRealmObject>(results, "yaxis", "xIndex");

        ArrayList<ILineDataSet> dataSets = new ArrayList<>();
        dataSets.add(set1);
        dataSets.add(set2);
        dataSets.add(set3);

        RealmLineData lineData = new RealmLineData(results, "timestamp", dataSets);
        mChart.setData(lineData);
       The problem is in RealmLineData, how do I use different results for different datasets in a singe lineData object.

**Comment by PhilJay** [comment]
You can't. But thats a general limitation of the library. All the lineData object does with the results is extract the x-values.

**Comment by AbdulRehmanSO5** [comment]
I got it :-). Thanks for the help.
