### ISSUE TITLE
Viewport implementation

### ISSUE THREAD

**Issue by Praveen2106** [PhilJay/MPAndroidChart#14]
Hi Phil,
Thanks for the library. I have a chart with more than 100 values on X-Axis. So i tried using setScalaMinima to a particular value to zoom in. But is it possible to move the end of the chart ? Since its a timeline chart, i would like to show the user the latest entries first and the user can scroll left for more entries. Basically my requirement to show only particular no. of entries(like a viewport) and rest can be viewed by dragging the chart left.

**Comment by wenli135** [comment]
Still met this problem with the latest release, the chart show correctly only after touch it
