### ISSUE TITLE
'The import io cannot be resolved'.Why

### ISSUE THREAD

**Issue by sharockguan** [PhilJay/MPAndroidChart#1400]
Hello!After I import MPChartLib,it ocurred.
wrong place:import io.realm.RealmObject;
                    import io.realm.RealmResults;
                   and other places.whats wrong?  Please help me...please....

**Comment by PhilJay** [comment]
You need to resolve the librarys dependencies via gradle

**Comment by staplesj** [comment]
@PhilJay - ' resolve the librarys dependencies via gradle' - please translate into English!!
