### ISSUE TITLE
can not compile example

### ISSUE THREAD

**Issue by luoqii** [PhilJay/MPAndroidChart#1401]
in master==>
/mnt/workbench/MPAndroidChart/MPChartExample/build/intermediates/classes/debug/io/realm/RealmFloatRealmProxy.java:62: error: method does not override or implement a method from a supertype
    @Override
    ^

my java version:
bysong@bysong-OptiPlex-790:~/w/MPAndroidChart$ java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
bysong@bysong-OptiPlex-790:~/w/MPAndroidChart$ 

i try with this java, but result is same:
bysong@bysong-OptiPlex-790:/mnt/workbench/android$ java -version
java version "1.7.0_55"
Java(TM) SE Runtime Environment (build 1.7.0_55-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.55-b03, mixed mode)
bysong@bysong-OptiPlex-790:/mnt/workbench/android$ 

but in tag v2.2.0
all are ok for me.

**Comment by PhilJay** [comment]
Yep that's an issue in the latest commit, should be fixed tomorrow.

**Comment by luoqii** [comment]
thx.

are we need a CI system to build, verify, test code? maybe we can use travis!!!
