### ISSUE TITLE
no jar for  v2.2.0?

### ISSUE THREAD

**Issue by ste71m** [PhilJay/MPAndroidChart#1403]
i was wondering why in release section there's not a jar for  v2.2.0
Since i sometimes use Eclipse to compile, a jar is very useful for me
thanks

**Comment by PhilJay** [comment]
The jar generation is always quite tricky, especially now that I have external dependencies involved. 
In case you really need to use Eclipse I suggest you just use the gradle plugin.

**Comment by PhilJay** [comment]
https://marketplace.eclipse.org/search/site/gradle

**Comment by ste71m** [comment]
Thanks
I guessed it was because of new dependencies due to realm.

**Comment by Shne** [comment]
Are you planning on making a .jar file for the v2.2.0 release?

I'm using MPAndroidChart in a Xamarin.Android project where I can bind to the .jar file.
I have not found a way to use gradle or maven to import the library in Xamarin.Android.

**Comment by karolys** [comment]
@Shne Have you been able to create a binding library for your Xamarin project with the newest build? I've attempted to using the last available jar and I even generated my own .aar of the latest build but neither built and threw lots of errors.

**Comment by Shne** [comment]
@karolys In a way, yes, but only with the newest released .jar: By using the binding library Flash3001 has created: https://github.com/Flash3001/MPAndroidChart.Xamarin

It's available as a NuGet package as well, though only with version 2.1.4.
But you can just clone his project and replace the .jar file with the latest available (2.1.6 at this time) and it works very well.

In the end, I had too many problems trying to create a binding library for the iOS version of MPAndroid Chart (https://github.com/danielgindi/ios-charts), and I want the same or similar chart library on both platforms.
So I've decided to either go with ShinobiCharts (very good, but very expensive) or SyncFusion Charts (a lot cheaper, but still looks pretty good) depending on how much money my client wants to throw at it.
Both of those offer ready-made .dll's for Xamarin.Android, Xamarin.iOS and Xamarin.Forms.

The documentation for SyncFusion Charts can be a little confusing but you should read the Android docs for Xamarin.Android and iOS docs for Xamarin.iOS and Xamarin docs for Xamarin.Forms

**Comment by Flash3001** [comment]
@Shne @karolys Just updated it to 2.2.3. Soon it will be available on NuGet.

**Comment by Flash3001** [comment]
@Shne @karolys https://www.nuget.org/packages/iOSCharts/
