### ISSUE TITLE
 PieChart mChart.setUsePercentValues(true) not working

### ISSUE THREAD

**Issue by HaMob** [PhilJay/MPAndroidChart#1408]
Thank you for this great library but i am facing this issue:
mChart.setUsePercentValues(true); is not working at all on piechart , i even tried  mChart.setUsePercentValues(false); and no changes. 

Please help, i really need to show percentages next to values :)

**Comment by PhilJay** [comment]
All this method does is transform values to percent values in relation to the total chart value. It does not append a % sign.

To that, use the `ValueFormatter` or predefined `PercentFormatter`: 
https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface

**Comment by HaMob** [comment]
Ahh i missed that. thanks alot
