### ISSUE TITLE
ScatterChart dont show all  Entry point on charts

### ISSUE THREAD

**Issue by sidstudio** [PhilJay/MPAndroidChart#1409]
Hello! I have some question about ScatterChart. 
I create list with points and label for charts (~2500) but on app i dont see some point on charts. 
if i setup 2500 point i was see max 2200 pooint and other a i cant see.

what i missing or why i cant see other points?
ScatterChart chart = (ScatterChart) findViewById(R.id.chart1);
        ArrayList<Entry> entries = new ArrayList<>();
        ArrayList<String> labels = new ArrayList<String>();
        XAxis xAxis = chart.getXAxis();
        xAxis.setDrawGridLines(true);
        for (int i=0; i<2500;i=i+50) {
            LimitLine line = new LimitLine(i,""+i);
            xAxis.addLimitLine(line);
        }
        for (int i=0;i<2500;i++) {
            if ((i>100 && i< 250)  || (i>600 && i< 750)) {
                continue;
            }
            entries.add(new Entry((float) Math.sqrt(i), i));
            if (i==0) {
                labels.add("23:12:12");
            } else {
                labels.add("");
            }
        }
        ScatterDataSet dataset = new ScatterDataSet(entries, "");
        dataset.setScatterShapeSize(5f);
        dataset.setScatterShape(ScatterChart.ScatterShape.CIRCLE);
        dataset.setColor(Color.BLACK);
        ScatterData data = new ScatterData(labels,dataset);
        chart.setDescription("");
        chart.setData(data);

![screenshot_2016-01-26-14-32-07](https://cloud.githubusercontent.com/assets/13994907/12580576/54a9e294-c439-11e5-8957-5838ce9c4755.png)
![screenshot_2016-01-26-14-22-59](https://cloud.githubusercontent.com/assets/13994907/12580431/51ee34e8-c438-11e5-9df7-fed27bbfaaf3.png)

**Comment by PhilJay** [comment]
Thats because your chart does not contain more than 2200 values.

Your `continue` statement in the loop also prevents new labels from being added.

I suggest you add your labels before the `continue`
