### ISSUE TITLE
setSpaceBetweenLabels not working for rotated xValues

### ISSUE THREAD

**Issue by Mbt925** [PhilJay/MPAndroidChart#1410]
Thanks for the great library.
setSpaceBetweenLabels should apply horizontal margin between labels whether labels are rotated or not!

**Comment by Mbt925** [comment]
Can you explain why you closed this issue?

![setspacebetweenlabels](https://cloud.githubusercontent.com/assets/10066112/12614626/5e3ba490-c516-11e5-99b2-3570da271f93.png)

**Comment by Mbt925** [comment]
Dear Philipp, closing an issue reporting a problem without any explanation is not right, specially if it does exist!!!

**Comment by PhilJay** [comment]
Besides the fact that I decide what is right or not in my repository, I just pushed a fix for the problem 20 minutes ago as you can see.

**Comment by Mbt925** [comment]
Another fact is that all the users want to help to improve this library. When a user like me takes the time to report a problem, you can honor it at least be looking at it or type a couple of words before closing it.
I know you fixed it and it bothered me more.

**Comment by PhilJay** [comment]
So I am the one who is supposed to "honor" your input, while you did not even took one second of your time and "honored" my work buy starring this project that definitely saved you hours if not days of development time? Okay then. And yes, I am sorry that it took me 8 hours to respond to your issue and fix it and I am also sorry that I did not write you a "thank you" note for reporting it.

**Comment by Mbt925** [comment]
You're right. Unlike you i accept my wrongs! I should have starring it and i would have definitely. I also thanked you in all my issue reports. And also i thanked you in my program. And i wanted to donate some money too and i will.
You know i want to help, right? it's not my issue, it's the library's.
