### ISSUE TITLE
Different xValues for each zoom level

### ISSUE THREAD

**Issue by Mbt925** [PhilJay/MPAndroidChart#1411]
Consider a Chart with years as xValues. I want to change the xValues to months when the user zoom in  or double tap. And change the xValues to days for the next zooming level.
Is it possible with great MPAndroidChart?

**Comment by PhilJay** [comment]
yes

**Comment by Mbt925** [comment]
Can you explain a little more :D please?

**Comment by coolscott** [comment]
use CustomXAxisValueFormatter like something in my composed example below:
<br>

public class CustomXAxisValueFormatter implements XAxisValueFormatter {
    protected SimpleDateFormat mFormat;
    private float mMidScale = 2f;
    private float mMaxScale = 4f;

    public CustomXAxisValueFormatter(SimpleDateFormat sdf) {
        // maybe do something here or provide parameters in constructor
        mFormat = sdf;
    }

    @Override
    public String getXValue(String original, int index, ViewPortHandler viewPortHandler) {
        String strRet = ""; 

        try { 
			Calendar cal = Calendar.getInstance();
			Date date = mFormat.parse(original);
			cal.setTime(date);
			final int yyyy = cal.get(Calendar.YEAR);
			final int MM = 1 + cal.get(Calendar.MONTH);
			final int dd = cal.get(Calendar.DAY_OF_MONTH);
			final int HH = cal.get(Calendar.HOUR_OF_DAY);
			final int mm = cal.get(Calendar.MINUTE);
	   
			if (viewPortHandler.getScaleX()>=mMaxScale) { //the 1st kind
				strRet = String.format(Locale.ENGLISH, "%02d %02d %4d", dd, MM, yyyy);
			} else if (viewPortHandler.getScaleX()>=mMidScale) { //the 2nd kind
				strRet = String.format(Locale.ENGLISH, "%02d %4d", MM, yyyy);
			} else { //the 3rd kind
				strRet = String.format(Locale.ENGLISH, "%4d", yyyy);
			} 
        }catch (ParseException pe){
            Log.e("LOG_TAG", pe.getMessage());
        }
        return strRet;
    }
}

**Comment by PhilJay** [comment]
Use the onChartGestureListener: 
https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart

And change the data on the callback of your choice.

**Comment by Mbt925** [comment]
DOUBLE_TAP zoom is not working when i set onChartGestureListener. Is there a problem or i am doing something wrong?

**Comment by PhilJay** [comment]
There was a little issue, the double tap was not recognized if a listener was set, I just fixed it in the latest commit.

**Comment by Mbt925** [comment]
Thanks @coolscott. Your code put me in the right direction. Here is my solution:

    xl.setValueFormatter(new XAxisValueFormatter() {
        @Override
        public String getXValue(String original, int index, ViewPortHandler viewPortHandler) {
            int months= index/30, days= index%30;
            if (days==0) return String.format(Locale.ENGLISH, "%d months", months);
            return String.format(Locale.ENGLISH, "%s%s",
            months == 0 ? "" : String.format(Locale.ENGLISH, "%d months and ", months),
            String.format(Locale.ENGLISH, "%d days", days));
        }
    });

    @Override
    public void onChartScale(MotionEvent me, float scaleX, float scaleY) {
        int nLabelsToSkip= Math.min(30, Math.max((int) (120 / mChart.getViewPortHandler().getScaleX()), 0));
        nLabelsToSkip = (nLabelsToSkip/5) * 5 -1; // (n+1) should be dividable by 5        mChart.getXAxis().setLabelsToSkip(nLabelsToSkip);
    }

Fully Zoom Out: 0 months, 1 months, 2 months, ...
Zoom Level 1: 0 months, 0 months and 15 days, 1 months, 1 months and 15 days, ...
Zoom Level 2: 0 months, 0 months and 10 days, 0 months and 20 days, 1 months, 1 months and 10 days, ...
Zoom Level 3: 0 months, 0 months and 5 days, 0 months and 10 days, 0 months and 15 days, 0 months and 20 days, 0 months and 25 days, 1 months, ...
Zoom Level n: 0 months, 0 months and 1 days, 0 months and 2 days, ...
