### ISSUE TITLE
LineChart: AxisY is not drawed in RecyclerView inside ViewPager

### ISSUE THREAD

**Issue by mtrakal** [PhilJay/MPAndroidChart#1412]
We have ViewPager > Fragment with RecyclerView with Adapter. Adapter contains widgets with MPA-Charts.

When we start app / scroll view pager (min 2 pages by cached pages) axis Y is not drawn on LineChart, when scroll down and up to widget Axis is now redraw and visible.

https://www.dropbox.com/s/697oagr66rjq8b1/device-2016-01-27-120334.mp4?dl=0

**Comment by PhilJay** [comment]
Can I see the corresponding code of recyclerview item and chart setup?

**Comment by mtrakal** [comment]
```java
    // classes for drawing graph...
    public void prepareView(View view, final boolean dummyWidget) {
        mChart = (LineChart) view.findViewById(R.id.chart_layout);
        mChart.setDrawGridBackground(false);
        mChart.setScaleEnabled(false);
        mChart.setAutoScaleMinMaxEnabled(true);
        mChart.setGridBackgroundColor(Color.TRANSPARENT);
        mChart.setDrawBorders(false);
        mChart.setTouchEnabled(false);
        mChart.setNoDataText(mContext.getString(R.string.no_chart_data_available));
        mChart.getPaint(LineChart.PAINT_INFO).setColor(...);
        Paint paint = mChart.getPaint(Chart.PAINT_INFO);
        paint.setColor(ContextCompat.getColor(mContext, R.color.black_87));
        mChart.invalidate();
        setOnViewClick(view, !dummyWidget);
    }

    private LineData prepareDataForChart(...)
        ArrayList<String> xVals = new ArrayList<>();
        ArrayList<Entry> yVals = new ArrayList<>();
        ...
        LineDataSet set1 = new LineDataSet(yVals, null);
        set1.setDrawCircles(drawCircles);
        set1.setCircleRadius(2f);
        set1.setCircleColor(...);
        set1.setDrawCircleHole(false);
        set1.setDrawCubic(false);
        set1.setLineWidth(2f);
        set1.setColor(...);
        set1.setDrawValues(false);

        ArrayList<ILineDataSet> dataSets = new ArrayList<>();
        dataSets.add(set1); // add the datasets

        // create a data object with the datasets
        LineData lineData = new LineData(xVals, dataSets);
        lineData.setDrawValues(false);
        return lineData;
    }

    private void showChart(LineChart chart, LineData data) {
        if (chart == null || data == null ) {
            return;
        }

        Legend legend = mChart.getLegend();
        legend.setEnabled(false);

        XAxis xAxis = chart.getXAxis();
        xAxis.setTextSize(8f);
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        int color = ContextCompat.getColor(mContext, R.color.black_87);
        xAxis.setTextColor(color);
        xAxis.setDrawGridLines(true);
        xAxis.setGridColor(ContextCompat.getColor(mContext, R.color.black_12));
        xAxis.setDrawAxisLine(true);
        xAxis.setAxisLineColor(color);
        xAxis.setAxisLineWidth(0.5f);
        xAxis.setSpaceBetweenLabels(1);

        YAxis axisRight = chart.getAxisRight();
        axisRight.setTextColor(color);
        axisRight.setTextSize(8f);
        axisRight.setGridColor(ContextCompat.getColor(mContext, R.color.black_12));
        axisRight.setDrawGridLines(true);
        axisRight.setDrawLabels(true);
        axisRight.setDrawAxisLine(true);
        axisRight.setStartAtZero(false);
        axisRight.setAxisLineColor(color);
        axisRight.setAxisLineWidth(0.5f);

        YAxis axisLeft = chart.getAxisLeft();
        axisLeft.setTextColor(color);
        axisLeft.setTextSize(8f);
        axisLeft.setDrawGridLines(false);
        axisLeft.setDrawAxisLine(false);
        axisLeft.setAxisLineColor(color);
        axisLeft.setAxisLineWidth(0.5f);
        axisLeft.setStartAtZero(false);
        axisLeft.setDrawLabels(false);

        chart.setDescription(null);
        chart.setAutoScaleMinMaxEnabled(true);
        chart.setExtraLeftOffset(16);
        chart.setData(data);
        chart.invalidate();
    }
```

```java
    // ViewPagerFragment
    private RecyclerView mRecyclerView;
    private WidgetContainerAdapter mAdapter;

    private void initRecyclerView(@Nullable View view) {
        mAdapter = new WidgetContainerAdapter(getContext());
        mAdapter.setHasStableIds(true);
        mRecyclerView = (RecyclerView) view.findViewById(R.id.recycler_view);
        mRecyclerView.setHasFixedSize(false);
        mRecyclerView.setAdapter(mAdapter);
        mAdapter.setRecyclerView(mRecyclerView);

        final RecyclerView.LayoutManager layoutManager;
        // simple LinearLayoutManager with extra space on bottom to precache more items to recyclerview
        layoutManager = new PreCachingLayoutManager(getActivity());

        mRecyclerView.setLayoutManager(layoutManager);
        mRecyclerView.setItemViewCacheSize(10);
```

```java
// WidgetContainerAdapter
public class WidgetContainerAdapter extends RecyclerView.Adapter<WidgetHolder> {
    private Context mContext;
    private LayoutInflater mLayoutInflater;
    private ArrayList<AbstractWidget> mObjects = new ArrayList<>(); // in any widget is some MPAGraph

    private void init() {
        // dynamically load data to mObjects from DB and call notifyDataSetChaged
    }

    @Override
    public WidgetHolder onCreateViewHolder(ViewGroup parent, int viewType) {
            View view = mLayoutInflater.inflate(R.layout.widget_dashboard_container, parent, false);
            return new WidgetHolder(view);
    }

    @Override
    public void onBindViewHolder(WidgetHolder holder, int position) {
           // bind data from mObjects to holder
    }
```

I can't support complete code due to NDA. But this is important parts I hope. When you will need more, I'll try to support what I will want.

**Comment by PhilJay** [comment]
Hmmm, code looks good to me.
I will have to implement a quick example with `RecyclerView` to see if I can reproduce.

Could you try calling `chart.notifyDataChanged()` before every `invalidate()` and see if this helps?

**Comment by mtrakal** [comment]
The axis is not drawn, becaouse layout when is added to recyclerView has zero size.
We make a workaround called in `prepareView` and it works now, but on another charts it's not necessary (as is seen on video, next chart axis has OK):

        mLineChart.addOnLayoutChangeListener(new View.OnLayoutChangeListener() {
            @Override
            public void onLayoutChange(View v, int left, int top, int right, int bottom, int oldLeft, int oldTop, int oldRight, int oldBottom) {
                showChart(mChart, mLineData);
            }
        });


I'll try to call your suggestion and leave feedback after. Thanks

**Comment by mtrakal** [comment]
Calling `chart.notifyDataSetChanged();` before invalidate really helps :+1: 

Thanks you very much

**Comment by PhilJay** [comment]
Awesome! Please let me know if it affects performance, (it shouldn't but just test it)

**Comment by limormek** [comment]
Hi! I'm having the same problem in my app - I'm using a view pager with fragments, and in each fragment I have a recyclerView with one item that contains an MPAndroidChart BarChart.

The problem is that I can't see the XAxis at all under my chart.

This is the code in my ViewHolder (after editing it according to your two suggestions - but it still doesn't work and I can't see the x axis labels if I set its position to BOTTOM):

```
public ActivityViewHolder(View itemView) {
        super(itemView);
        graphColor = ContextCompat.getColor(itemView.getContext(), R.color.barchart_graph);
        emptyView = (LinearLayout) itemView.findViewById(R.id.empty_text);
        barChart = (BarChart) itemView.findViewById(R.id.chart);
        barChart.setViewPortOffsets(0, 20, 0, 0);
        this.context = itemView.getContext();
        barChart.setDescription("");
        barChart.setDescriptionColor(graphColor);
        barChart.setTouchEnabled(false);
        barChart.setDragEnabled(false);
        barChart.setScaleEnabled(false);
        barChart.setPinchZoom(false);
        barChart.setDoubleTapToZoomEnabled(false);

        barChart.notifyDataSetChanged();
        barChart.invalidate();

        barChart.addOnLayoutChangeListener(new View.OnLayoutChangeListener() {
            @Override
            public void onLayoutChange(View v, int left, int top, int right, int bottom, int oldLeft, int oldTop, int oldRight, int oldBottom) {
                showChart(barData);
            }
        });

    }

@Override
    public void setData(ProcessedData processedData) {

        if (processedData != null) {
            barChart.setVisibility(View.VISIBLE);
            emptyView.setVisibility(View.GONE);

            barData = getBarData(processedData);

            showChart(barData);

        } else {
            barChart.setVisibility(View.GONE);
            emptyView.setVisibility(View.VISIBLE);
        }

    }

```
Any suggestions?

**Comment by hansraj123** [comment]
Please Watch this Video :https://youtu.be/AvSOh_RYxnY
  This Is my Code ..

`package com.h8.h8wifiad.login.adapter;


import android.content.Context;
import android.graphics.Color;
import android.support.v7.widget.CardView;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;

import com.github.mikephil.charting.charts.PieChart;
import com.github.mikephil.charting.components.Legend;
import com.github.mikephil.charting.data.PieData;
import com.github.mikephil.charting.data.PieDataSet;
import com.github.mikephil.charting.data.PieEntry;
import com.github.mikephil.charting.formatter.PercentFormatter;
import com.github.mikephil.charting.utils.ColorTemplate;
import com.h8.h8wifiad.R;
import com.h8.h8wifiad.login.customfonts.CustomTextViewUbuntuRegular;
import com.h8.h8wifiad.login.dto.QuestionSummery_Dto;

import java.util.ArrayList;
import java.util.Random;


/**
 * Created by Jeffrey Liu on 3/21/16.
 */
public class SummaryList_Child_Adapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {

    LayoutInflater layoutInflater;
    Context mContext;
    ArrayList<QuestionSummery_Dto> alQuestionSummery;
    ArrayList<QuestionSummery_Dto> uniqueQuestionName;
    ArrayList<PieEntry> entries;
    PieDataSet dataSet;
    String subQuestionsName;
    PieData data;
    boolean isEnteryDataAdded = false;


    public SummaryList_Child_Adapter(ArrayList<QuestionSummery_Dto> uniqueQuestionName, ArrayList<QuestionSummery_Dto> alQuestionSummery, Context mContext) {
        this.alQuestionSummery = alQuestionSummery;
        this.mContext = mContext;
        this.uniqueQuestionName = uniqueQuestionName;
        entries = new ArrayList<PieEntry>();


    }

    private class CellViewHolder extends RecyclerView.ViewHolder {
        private PieChart summaryPieChart;
        CustomTextViewUbuntuRegular tvsubQuestion;
        CardView summary_child_mRoot;

        public CellViewHolder(View itemView) {
            super(itemView);
            summaryPieChart = (PieChart) itemView.findViewById(R.id.summaryPieChart);
            tvsubQuestion = (CustomTextViewUbuntuRegular) itemView.findViewById(R.id.tvsubQuestion);
            summary_child_mRoot=itemView.findViewById(R.id.summary_child_mRoot);

        }


    }

    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(final ViewGroup viewGroup, int viewType) {

        switch (viewType) {
            default: {
                View v1 = LayoutInflater.from(viewGroup.getContext()).inflate(R.layout.summary_child_raw, viewGroup, false);
                return new CellViewHolder(v1);
            }
        }
    }

    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder viewHolder, int position) {


        entries.clear();
        switch (viewHolder.getItemViewType()) {
            default: {
                CellViewHolder cellViewHolder = (CellViewHolder) viewHolder;
                try {
                    if (!uniqueQuestionName.get(position).getSubquestion().equalsIgnoreCase("") && !uniqueQuestionName.get(position).getSubquestion().equalsIgnoreCase(" ")) {
                        cellViewHolder.tvsubQuestion.setVisibility(View.VISIBLE);
                        cellViewHolder.tvsubQuestion.setText(uniqueQuestionName.get(position).getSubquestion());
                        subQuestionsName = uniqueQuestionName.get(position).getSubquestion();
                        LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(
                                LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT);

                        cellViewHolder.summary_child_mRoot.setLayoutParams(layoutParams);

                    } else {
                        cellViewHolder.tvsubQuestion.setVisibility(View.GONE);

                    }

                    for (QuestionSummery_Dto dto : alQuestionSummery) {
                        if (uniqueQuestionName.size() <= 1) {
                            entries.add(new PieEntry(Float.parseFloat(dto.getAnswerratio()), dto.getAnswer()));
                        } else {
                            try {
                                if (dto.getSubquestion().contains(subQuestionsName)) {

                                    entries.add(new PieEntry(Float.parseFloat(dto.getAnswerratio()), dto.getAnswer()));

                                }
                            } catch (ArrayIndexOutOfBoundsException e) {
                                e.printStackTrace();
                            }
                        }
                    }

                    cellViewHolder.summaryPieChart.setUsePercentValues(true);
                    cellViewHolder.summaryPieChart.getDescription().setEnabled(false);

                    cellViewHolder.summaryPieChart.setDragDecelerationFrictionCoef(0.95f);

//
//            holder.summaryPieChart.setExtraOffsets(20.f, 0.f, 20.f, 0.f);

                    cellViewHolder.summaryPieChart.setDrawHoleEnabled(true);
                    cellViewHolder.summaryPieChart.setHoleColor(Color.WHITE);

                    cellViewHolder.summaryPieChart.setTransparentCircleColor(Color.GRAY);
                    cellViewHolder.summaryPieChart.setTransparentCircleAlpha(110);

                    cellViewHolder.summaryPieChart.setHoleRadius(2f);
                    cellViewHolder.summaryPieChart.setTransparentCircleRadius(5f);
                    cellViewHolder.summaryPieChart.setDrawCenterText(true);
                    cellViewHolder.summaryPieChart.setRotationAngle(0);
                    cellViewHolder.summaryPieChart.setRotationEnabled(true);
                    cellViewHolder.summaryPieChart.setHighlightPerTapEnabled(true);

                    dataSet = new PieDataSet(entries, "Survey  Data");
                    dataSet.setDrawValues(false);
                    data = new PieData(dataSet);
                    dataSet.setSliceSpace(3f);
                    dataSet.setSelectionShift(5f);
                    dataSet.setColor(Color.BLACK);

                    showChart(cellViewHolder.summaryPieChart,data);


                } catch (Exception e) {
                    e.printStackTrace();
                }

                break;

            }


        }


//
    }

    private void showChart(PieChart chart, PieData data) {
        if (chart == null || data == null) {
            return;
        }
        ArrayList<Integer> colors = new ArrayList<Integer>();
//
        for (int c : ColorTemplate.MATERIAL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.JOYFUL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.COLORFUL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.MATERIAL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.COLORFUL_COLORS)
            colors.add(c);
//                    Random rnd = new Random();
//                    int color = Color.argb(255, rnd.nextInt(220), rnd.nextInt(250), rnd.nextInt(220));
//                view.setBackgroundColor(color);
//                    colors.add(colors);

        dataSet.setColors(colors);
        dataSet.setSelectionShift(0f);

        dataSet.setValueLinePart1OffsetPercentage(80.f);
        dataSet.setValueLinePart1Length(0.2f);
        dataSet.setValueLinePart2Length(0.4f);
        dataSet.setXValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);
        dataSet.setYValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);


        data.setValueFormatter(new PercentFormatter());
        data.setValueTextSize(9f);
        data.setValueTextColor(Color.BLACK);

        chart.setData(data);


        // undo all highlights
        chart.highlightValues(null);


//                        cellViewHolder.summaryPieChart.animateY(1400, Easing.EasingOption.EaseInOutQuad);

        Legend l = chart.getLegend();
        l.setVerticalAlignment(Legend.LegendVerticalAlignment.TOP);
        l.setHorizontalAlignment(Legend.LegendHorizontalAlignment.RIGHT);
        l.setOrientation(Legend.LegendOrientation.VERTICAL);
        l.setTextColor(Color.BLACK);
        l.setDrawInside(false);
        l.setEnabled(false);
        chart.notifyDataSetChanged();
        chart.invalidate();

    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public int getItemViewType(int position) {
        return position;
    }


    @Override
    public int getItemCount() {
        if (uniqueQuestionName == null)
            return 0;
        return uniqueQuestionName.size();
    }

}`

**Comment by almic** [comment]
@hansraj123 please do not necropost on such old issues. Especially if you are only going to spam poorly formatted code (for the future, please use triple backticks `` ` `` for code blocks).

This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/), it probably has what you're looking for.

**Comment by Javohir6949** [comment]
Does anyone can help me?

**Comment by almic** [comment]
@Javohir6949 did you not see my previous comment?
