### ISSUE TITLE
Pie chart just percentage

### ISSUE THREAD

**Issue by tartacutza** [PhilJay/MPAndroidChart#1414]
Hi, how do I display only the percentage in the slices? Now I get the Legend value as well and I don't want (44% Correct Values), I want 44% and Correct values to be just in the legend.

Thanks

**Comment by PhilJay** [comment]
`chart.setDrawSliceText(false)`
https://github.com/PhilJay/MPAndroidChart/wiki/Specific-chart-settings

**Comment by tartacutza** [comment]
Uber, Cheers! thought that was gonna hide all the text inside. My bad
