### ISSUE TITLE
BarChart: setDrawValuesForWholeStack() is not available

### ISSUE THREAD

**Issue by miglrodri** [PhilJay/MPAndroidChart#1415]
setDrawValuesForWholeStack(boolean enabled): If set to true, all values of stacked bars are drawn individually, and not just their sum on top of all.

Hello, i'm using version 2.1.6 and i'm using some stacked bars graphic and i wanted to put the total at the top of the stack bar. I assume this could be the method to enable that. But when i try to use this method it's not available. It's included in newer version? and if so could you please build a jar file to import to the project.

Thanks in advance, Miguel.

**Comment by PhilJay** [comment]
You can use the `ValueFormatter` to do that. It's not as easy but overall allows much more flexibility.
I just created a default formatter specifically for stacked values.

https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface

**Comment by PhilJay** [comment]
In order to draw the values above instead of inside the bar, use `chart.setDrawValuesAboveBar(true)`

**Comment by miglrodri** [comment]
Yep, in a single bar i have stacked the number of calls, and then the number of sms. the visual i wanted to reproduce was:

bar 1 with total inside bar, calls = 40;
bar 2, stacked, with total inside bar, sms = 30;
and above the stacked bars, i wanted the total = 70.

one stacked bar for each month.

**Comment by miglrodri** [comment]
Sorry to keep bugging you. :smile: 

I will try to get the sum of all values above the stacked bars.
