### ISSUE TITLE
Show different XLabels when using BOTH_SIDED xAxis

### ISSUE THREAD

**Issue by davidbin** [PhilJay/MPAndroidChart#1417]
Hi, I'm using LineChart, version 2.1.6, I can show xAxis in top and bottom by using
 xAxis.setPosition(XAxis.XAxisPosition.BOTH_SIDED);

But they're now showing the same labels, how can I assign different set of lables for top and bottom xAxis ? Thanks.

**Comment by PhilJay** [comment]
Currently not possible
