### ISSUE TITLE
how to change the field width 

### ISSUE THREAD

**Issue by dancingalone** [PhilJay/MPAndroidChart#1419]
hi all  I am new guy for android. In my project I am using the MPAndroidChart it is amazing lib.
now I have a question how to change the field width for linechart . what i means  i want to draw the android chart like this photo, but i don't know how to set the little padding for the first value circle
![default](https://cloud.githubusercontent.com/assets/2200697/12646092/fd4e6926-c608-11e5-99cb-c9151fc1ce9b.png)

**Comment by PhilJay** [comment]
Just add one more x-value at the beginning or check out this: https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport
