### ISSUE TITLE
LineChart: how to change the circle color according to the yVals??

### ISSUE THREAD

**Issue by enginebai** [PhilJay/MPAndroidChart#142]
Hello Phil, 
I have to display a line chart, the following is my app design diagram:
![1](https://cloud.githubusercontent.com/assets/3387462/4580736/50414114-4fd9-11e4-9944-39c84a759142.png)

Some features are required in my app:
1. I have to change the circle color according to yVals, for example, if the yVal is between 0 and 50, then the circle has to be green.
2. I have to change the background color according to the yVal value range, i.e. 0-50 is green, 50-100 is yellow...etc.

I've cloned your repo. and included it to my app project, I would like to modify the source code of this project directly to achieve my requirement.
Could you help me out?? Thank a lot.

Regrads, 
Engine Bai.

**Comment by danishkaleem095** [comment]
Hi PhilJay,
   I have to change the circle color according to value but I have a problem. I am using line graph and adding values dynamically so how can I change the color of specific circles. 
 Here is the 
`public void addEntry(float yValue) {

        LineData data = lineChart.getData();

        ILineDataSet set = data.getDataSetByIndex(0);

        if (set == null) {
            set = createSet();
            data.addDataSet(set);
        }

        // choose a random dataSet
        int randomDataSetIndex = (int) (Math.random() * data.getDataSetCount());
        data.addXValue(" ");
        Entry entry=new Entry( yValue,data.getDataSetByIndex(randomDataSetIndex).getEntryCount());
        data.addEntry(entry, 0);
        data.notifyDataChanged();

        // let the chart know it's data has changed
        lineChart.notifyDataSetChanged();

        lineChart.setVisibleXRangeMaximum(6);
        //mChart.setVisibleYRangeMaximum(15, AxisDependency.LEFT);
//
//            // this automatically refreshes the chart (calls invalidate())
        lineChart.moveViewTo(data.getXValCount() - 7, 50f, YAxis.AxisDependency.LEFT);

    }



    private LineDataSet createSet() {

        LineDataSet set = new LineDataSet(null, "DataSet 1");
        set.setLineWidth(2.5f);
        set.setCircleRadius(6.5f);
        set.setCircleHoleRadius(3.5f);
        set.setColor(Color.parseColor("#ffffff"));
        set.setCircleColor(Color.parseColor("#ffffff"));
        set.setCircleColorHole(Color.parseColor("#039BE5"));
        set.setHighLightColor(Color.rgb(190, 190, 190));
        set.setAxisDependency(YAxis.AxisDependency.LEFT);
        set.setValueTextColor(Color.parseColor("#ffffff"));
        set.setValueTextSize(10f);

        return set;
    }`

**Comment by venilla** [comment]
Hi Phil,

How to set the circle hole colors.

Is it possible to use drawable for circle.

**Comment by roeiros** [comment]
Hey Phil.
Thanks for this library.
Is this feature supported yet?
> I have to change the background color according to the yVal value range, i.e. 0-50 is green, 50-100 is yellow...etc.

**Comment by lonewolf9277** [comment]
Hi Phil, how can we do this for realtime data?

**Comment by binaykumarrana** [comment]
Hi Phil, Instead of setCircleColors I am trying to pass setColors() //List of colors but default color is being drawn. I wan red, yellow, green to be drawn based on values. But my graph is like heatmap not a circle.  Any help?

**Comment by ManikandanBalakrishnan** [comment]
Hi Phil, is there a way to display image, in place of circle, that too not in all points, in some points I need to show?

**Comment by AtifAbbAsi19** [comment]
Hey there..
I want to increase size of circle how I'll be able to achieve that.?

**Comment by LaxmanDroid** [comment]
set1.setCircleSize(10f); // by using this you can increase the size of circle
