### ISSUE TITLE
Why this problem produce?Through the browser is able to access

### ISSUE THREAD

**Issue by SunPointed** [PhilJay/MPAndroidChart#1420]
Error:A problem occurred configuring project ':MPChartExample'.
        > A problem occurred configuring project ':MPChartLib'.
> Could not resolve all dependencies for configuration ':MPChartLib:_debugCompile'.
        > Could not resolve io.realm:realm-android:0.84.1-SNAPSHOT.
        Required by:
MPAndroidChart:MPChartLib:unspecified
> Could not resolve io.realm:realm-android:0.84.1-SNAPSHOT.
        > Unable to load Maven meta-data from http://oss.jfrog.org/artifactory/oss-snapshot-local/io/realm/realm-android/0.84.1-SNAPSHOT/maven-metadata.xml.
> Could not GET 'http://oss.jfrog.org/artifactory/oss-snapshot-local/io/realm/realm-android/0.84.1-SNAPSHOT/maven-metadata.xml'.
        > The target server failed to respond

**Comment by PhilJay** [comment]
Don't know, check your gradle setup I guess.
