### ISSUE TITLE
How do I make the x axis below my bar chart?

### ISSUE THREAD

**Issue by anshulg12** [PhilJay/MPAndroidChart#1421]
Currently if I have a bar chart and show X axis it overlays them on top of my graph and I would like it to be below it. 

How would I do that?

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/XAxis-%28XLabels%29

**Comment by anshulg12** [comment]
I dont understand. In this there is no function to draw the chart on top of the x axis rather than the x axis being drawn on top of the chart. 
![ahm9bifyoe1en8x70trhdaplcmz4mtawv0urxz1k7hf9](https://cloud.githubusercontent.com/assets/10050470/12660982/f9ba4268-c5e4-11e5-8b12-bc379e376c85.jpg)

**Comment by anshulg12** [comment]
setPosition(XAxisPosition pos): Sets the position where the XAxis should appear. Choose between TOP, BOTTOM, BOTH_SIDED, TOP_INSIDE or BOTTOM_INSIDE.

Is this what I am supposed to use?
