### ISSUE TITLE
The Linechart lines are jagged

### ISSUE THREAD

**Issue by anshulg12** [PhilJay/MPAndroidChart#1422]
When using this library the line chart lines are jagged as compared to being smooth. In the examples that you have on git show lines being smooth along the curve but while using it mine seems to be jagged. Any ideas on why?
![aqz6bzm5h8ieb5n5qaddrnqfbasudwkiztzzvsteb0c8](https://cloud.githubusercontent.com/assets/10050470/12661057/74118c1a-c5e5-11e5-86e9-3ef376b34e1d.jpg)

**Comment by PhilJay** [comment]
Well thats because of your line-thickness which is too thick. You can either reduce it or use cubic lines.
