### ISSUE TITLE
judge  x MinValue  or x MaxValue  isvisible

### ISSUE THREAD

**Issue by liuhui313364809** [PhilJay/MPAndroidChart#1423]
hello,I have a question
I used  this  methods   `mLineChart.zoom(6.5f, 0f, 0f, 0f);`
I want to getParent to control  when x minValue is visible or x maxValue is visible 
It's have this method to get x min value  is visible?? thank you  very much!

**Comment by liuhui313364809** [comment]
how  judge Sliding to the border, this method is have?

**Comment by PhilJay** [comment]
Sorry, I don't understand
