### ISSUE TITLE
Multiple BarChart

### ISSUE THREAD

**Issue by qzaqza1818** [PhilJay/MPAndroidChart#1424]
![capture](https://cloud.githubusercontent.com/assets/15046075/12672903/6eee30e2-c6b4-11e5-875f-d2cc753f2b98.PNG)

Why is there 4003, 8003 values appear? Any way to remove it?

**Comment by PhilJay** [comment]
Are you using `LargeValueFormatter`?

**Comment by qzaqza1818** [comment]
ya, thank you, I already solved the problem. Thank you for your library.
