### ISSUE TITLE
Unable to import library via Gradle

### ISSUE THREAD

**Issue by Shadie6** [PhilJay/MPAndroidChart#1426]
I'm trying to import library like said in [Usage](https://github.com/PhilJay/MPAndroidChart#usage) section in my Android project.
I'm currently using Gradle, ofc.

This is a piece of my build.gradle

```
[...]
repositories {
        maven { url 'http://repo1.maven.org/maven2' }
        maven { url 'https://jitpack.io' }
    }
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.github.PhilJay:MPAndroidChart:v2.2.0'
}
```

and this is the error I got:
<img width="571" alt="schermata 2016-01-29 alle 15 29 15" src="https://cloud.githubusercontent.com/assets/7540739/12678103/6ee171c0-c69d-11e5-97b3-c9f305c090af.png">

I'm not new to importing new dependencies to my project and I really need to say that this is the first time I can't include a new dependency in this way....

On the other side, including JAR library in `lib` folder does the trick.

**Comment by gang018** [comment]
try an older version, for example I'm using 2.1.6

**Comment by PhilJay** [comment]
Weird. I just tired it with v2.2.0 - works just fine for me, maybe it was just a temporary issue with jitpack?

**Comment by sachams** [comment]
Hmm, I'm getting the same error. Also tried 2.1.6, that didn't work either. Any ideas - jitpack flakiness?

**Comment by ianjuma** [comment]
same issue on 2.2.2

**Comment by PhilJay** [comment]
Just tested it again with a completely new project.

Had no issues resolving v2.2.2

**Comment by sachams** [comment]
If it's of any help I had the dependency declaration in the wrong part of the gradle file - my bad.

**Comment by derSascha** [comment]
@sachams where do you place the dependency declaration and what version are using?

I am unable to resolve v2.2.4 via jitpack..

**Comment by derSascha** [comment]
Strange. Running "sync now" in android studio 1.5 results in resolving errors. After running gradle from command line (e.g. `./gradlew tasks`), everything works fine in android studio too...

**Comment by surfer190** [comment]
@derSascha champion answer.

Steps I took:

1. Change `distributionUrl` in `gradle-wrapper.properties` to the [latest gradle](https://services.gradle.org/distributions/)

2. Run gradle wrapper task from command line

```
cd ~/AndroidStudioProject/myproject/ myapp
./gradlew tasks
```

Profit

**Comment by ashutosh5889** [comment]
Hi phil,

I lost at least two days to compile MPAndroidChart in my Android studio it says that failed to resolve 'com.github.PhilJay:MPAndroidChart:v2.2.3' i am using Android studio 1.4 please respond me as soon as possible how i syn it in android studio ..

Thanks

**Comment by PhilJay** [comment]
Add the jitpack repository:

repositories {
        //...
        maven { url 'https://jitpack.io' }
    }
}

**Comment by ashutosh5889** [comment]
I already added it but not compile till

**Comment by ashutosh5889** [comment]
Thanks a lot phil it works for me ... and one more thing i want to customize the graph putting integer value on x axis and y axis plese help me

**Comment by surfer190** [comment]
@ashutosh5889 A good skill to learn is reading documentation, you should try it.

**Comment by ashutosh5889** [comment]
if you have any link regarding this documentation then send me

**Comment by surfer190** [comment]
It seems you want everything just handed to you on a silver platter. But life doesn't work that way.

**Comment by milaptank** [comment]
This  SO answer may helps us all http://stackoverflow.com/a/37892027/1293313

**Comment by 10121991** [comment]
allprojects {
  
to repositories under allprojects not under buildscript see screenshot:

  repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by ps06756** [comment]
I was getting the same error, despite my build files being correct. After I updated android studio, and rebuilt the project, this error was removed.

**Comment by hayeseyboy** [comment]
I got the exact same error. I couldn't figure out why i was getting the error,  but a guy in my office hit 
'Build' > 'Make Project'    (even when the error was showing)  and it synced like magic . . . .. . weird

**Comment by ashishtyagi056** [comment]
Phill can you provide the latest .jar file because i am facing some problems to resolve the dependencies

Error:(27, 24) Failed to resolve: com.github.PhilJay:MPAndroidChart:v3.0.0

**Comment by amanshuraikwar** [comment]
I am getting the same problem again with this library.
![screenshot from 2017-02-06 18-38-48](https://cloud.githubusercontent.com/assets/16191316/22648210/91b6fd80-ec9b-11e6-8150-941f546d17e6.png)

**Comment by ashishtyagi056** [comment]
[MPAndroidChart-v3.0.1.zip](https://github.com/PhilJay/MPAndroidChart/files/754677/MPAndroidChart-v3.0.1.zip)
try with the JAR

**Comment by amanshuraikwar** [comment]
I can try with the JAR but do you know why is this problem coming in the first place? Its working for my colleague sitting next to me but not for me.

**Comment by ashishtyagi056** [comment]
I was facing this problem because of some site restrictions in my office
might be the same issue with you..else i don't know

**Comment by amanshuraikwar** [comment]
I don't think that's it. The guy sitting next to me was using the same wifi but it worked for him. Thanks anyway.

**Comment by tejasuplenchwar** [comment]
not able to add dependency in compile sdk version 25
is there any problem withsdkversion

**Comment by ParveenSharma01** [comment]
The graph does not show in android 26 version, there looking blank screen

**Comment by FAS16** [comment]
![skaermbillede 2018-01-05 kl 03 23 45](https://user-images.githubusercontent.com/22447499/34592939-e4b2ce92-f1c7-11e7-9692-5ba5e7172f9a.png)

Guys, remember to add the maven { url "https://jitpack.io" } inside of allprojects/repositories !

**Comment by anilthummar** [comment]
Please add below code in gradle file:

repositories {
jcenter()
maven { url "https://jitpack.io" }
}
dependencies {
  
    implementation 'com.github.PhilJay:MPAndroidChart:v2.2.4'

}

**Comment by banoth-ravinder** [comment]
This worked for me. If your under proxy add this lines in gradle properties(project properties)

[systemProp.http.proxyHost= "Your proxy"
systemProp.http.proxyPort= "Proxy port"
systemProp.https.proxyHost= "Your proxy"
systemProp.https.proxyPort= "Proxy port"]()
