### ISSUE TITLE
Stacked Bar chart (Help)

### ISSUE THREAD

**Issue by Sutirth** [PhilJay/MPAndroidChart#1427]
I have two linkedHashMap iterator which I want to set in Stacked bar chart but unable to do so any help or guidance???

**Comment by PhilJay** [comment]
simply create a float array (`float[]`) and set it for the `BarEntry`

**Comment by Sutirth** [comment]
I am trying the following,

ArrayList<BarEntry> yVals3 = new ArrayList<BarEntry>();
        Iterator iterator2 = sweatPointCountHashMap.entrySet().iterator();
        Iterator iterator3 = goalSweatpointHashMap.entrySet().iterator();
        while(iterator2.hasNext()){
            Map.Entry entrySweatPoints = (Map.Entry) iterator2.next();
            double valueSweatPoints;
            float actualSweatPoints = 0;
            Log.i(TAG,"Key:  "+entrySweatPoints.getKey().toString()+"Value: "+entrySweatPoints.getValue().toString());
            if(entrySweatPoints.getValue() !=0) {
                 valueSweatPoints = Double.valueOf(entrySweatPoints.getValue().toString());
                 actualSweatPoints = (float) valueSweatPoints;

            }
            yVals3.add(new BarEntry(actualSweatPoints, Integer.valueOf(entrySweatPoints.getKey().toString())));

            float actualGoalSweatPoints= 0;
            String goalSweatPointsKey = null;
            while(iterator3.hasNext()){
                Map.Entry entryGoalSweatPoints = (Map.Entry) iterator3.next();
                double valueGoalsSweatPoints;

                if(entryGoalSweatPoints.getValue()!= 0 ){
                    goalSweatPointsKey = entryGoalSweatPoints.getKey().toString();

                    valueGoalsSweatPoints = Double.valueOf(entryGoalSweatPoints.getValue().toString());
                    actualGoalSweatPoints = (float) valueGoalsSweatPoints;
                  //  yVals3.add(new BarEntry(new float[] {actualSweatPoints,actualGoalSweatPoints}  , Integer.valueOf(goalSweatPointsKey)));
                }
            }

        }

And I have hit a roadblock could you help me ??

**Comment by PhilJay** [comment]
This line:
```java
yVals.add(new BarEntry(new float[] {actualSweatPoints,actualGoalSweatPoints}  , Integer.valueOf(goalSweatPointsKey)));
```

is exactly how you create stacked entries. You can see another example here:
https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/StackedBarActivity.java

**Comment by Sutirth** [comment]
I tried using the same thing as you suggested but the graph isn't implemented
