### ISSUE TITLE
Rounded edges issue

### ISSUE THREAD

**Issue by k0ber** [PhilJay/MPAndroidChart#1428]
Hi. I want to make a colorized HorizontalBarChart  with rounded edges. I'm trying to change HorizontalBarChartRenderer for my chart for it. Here is my code:

HorizontalBarChart initialization:
```
List<Float> values = new ArrayList<>();
List<Integer> colors = new ArrayList<>();
// initializing

float[] valuesArray = new float[values.size()];
for (int i = 0; i < values.size(); i++) {
    valuesArray[i] = values.get(i);
}
List<BarEntry> yValues = valuesArray.length <= 0
    ? Collections.<BarEntry>emptyList()
    : Collections.singletonList(new BarEntry(valuesArray, 0));
BarDataSet barDataSet = new BarDataSet(yValues, "");
barDataSet.setColors(colors);
barDataSet.setValueFormatter(new ValueFormatter() {
    @Override
    public String getFormattedValue(float value, Entry entry, 
        int dataSetIndex, ViewPortHandler viewPortHandler) {
            return "";
        }
});
chartView.setData(new BarData(new String[]{"sleep"}, barDataSet));
```

And extended HorizontalBarChartRenderer:
```
@Override
protected void drawDataSet(Canvas c, IBarDataSet dataSet, int index) {
// ...
c.drawRoundRect(new RectF(buffer.buffer[j], buffer.buffer[j + 1] + 10, buffer.buffer[j + 2],
    buffer.buffer[j + 3] - 10), 20, 20, mRenderPaint);
}
```

The result is:
![1](https://cloud.githubusercontent.com/assets/9946776/12698638/3c5aa9bc-c7cc-11e5-9bff-95df63cdaa07.png)

How can I make rounded edges only for outer sides? Something like this:
![2](https://cloud.githubusercontent.com/assets/9946776/12698674/43427fb0-c7cd-11e5-845d-c243ff0a0ae4.png)

**Comment by PhilJay** [comment]
I suggest you only round the edges of the last bar?
This is not really a library issue, I suggest you take this to [stackoverflow.com](www.stackoverflow.com)
