### ISSUE TITLE
remove space on horizontal bar chart

### ISSUE THREAD

**Issue by babonski** [PhilJay/MPAndroidChart#1430]
hi again, one more question

do you have any idea how to remove this unwanted spacing , so i can make the bar fill the available width space(full)? i'm making a horizontal bar chart as a percentage chart so the total value for each chart is 100.

![screenshot_20160202-043128 copy](https://cloud.githubusercontent.com/assets/8475841/12732557/b8a8b9da-c968-11e5-95a0-78d33531aea8.png)

and also why this method is not working? u can see from the image that the offsets are still exist.
`chart.setViewPortOffsets(0f, 0f, 0f, 0f);`

thanks before

**Comment by PhilJay** [comment]
Yes, you can control this space via `YAxis`: https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-%28YLabels%29

By setting the minima and maxima accordingly.

Also `chart.setExtraOffsets(...)` can help.
