### ISSUE TITLE
Bar chart Is appearing inverted while added data

### ISSUE THREAD

**Issue by Sutirth** [PhilJay/MPAndroidChart#1432]
@Bind(R.id.previousStepCountChart)
    BarChart mPreviousStepCountChart;

  mPreviousStepCountChart.setDrawGridBackground(false);

 mPreviousStepCountChart.getAxisLeft().setEnabled(false);
        mPreviousStepCountChart.getLegend().setEnabled(false);
        mPreviousStepCountChart.getAxisRight().setEnabled(false);

  ArrayList<BarEntry> yVals1  = new ArrayList<BarEntry>();
        Iterator iterator = stepCountHashMap.entrySet().iterator();
        while(iterator.hasNext()){
            Map.Entry entry = (Map.Entry)iterator.next();
            if(entry.getValue()!=null){
                double value = Double.valueOf(entry.getValue().toString());
                float actualValue = (float) value;

                yVals1.add(new BarEntry(actualValue,Integer.valueOf(entry.getKey().toString())));
            }
        }
        BarDataSet set1 = new BarDataSet(yVals1, "StepCount");
        set1.setColor(ContextCompat.getColor(getContext(), R.color.step_count_text));
        set1.setBarSpacePercent(35f);

        ArrayList<IBarDataSet> dataSets = new ArrayList<IBarDataSet>();
        dataSets.add(set1);

        BarData data =new BarData(getXAxisValues(), dataSets);
        data.setValueTextSize(10f);
        data.setDrawValues(false);
        data.setHighlightEnabled(false);
        mPreviousStepCountChart.setData(data);

**Comment by PhilJay** [comment]
What do you mean by "inverted"?
Can you show me a screenshot or describe that in more detail?

**Comment by Sutirth** [comment]
![screenshot_2016-02-02-17-01-00](https://cloud.githubusercontent.com/assets/3212997/12748215/d95c1e68-c9ce-11e5-8eb4-c3b440ea62b4.png)

**Comment by Sutirth** [comment]
the X-axis is drawn inverted

**Comment by Sutirth** [comment]
What should I do rectify it??
