### ISSUE TITLE
setDrawGridLines lines color

### ISSUE THREAD

**Issue by qzaqza1818** [PhilJay/MPAndroidChart#1434]
![capture](https://cloud.githubusercontent.com/assets/15046075/12743866/bf2ac808-c9cb-11e5-97fe-911129382171.PNG)

As you can see, I had set setDrawGridLines(true) for both left and x axis, yet the line color start from shallow to deep black and then random. Do you have any idea why?

**Comment by PhilJay** [comment]
Well that's not a library issue but more a general Android issue.
If your grid lines are too thin in comparison to the screen resolution, this effect can occur.
