### ISSUE TITLE
Showing gaps in linechart

### ISSUE THREAD

**Issue by cuddle-puneet** [PhilJay/MPAndroidChart#1435]
Is it possible to show gaps in line chart with null values. The current implementation does not consider null values and connects the previous and the next values directly. Is their any way to do this or creating a separate LineDataSet after the null value the only approach for that.

**Comment by PhilJay** [comment]
You can achieve that by using multiple `LineDataSets` and one per gap.

**Comment by cuddle-puneet** [comment]
Showing it as a separate dataset leads to a new entry in Legend at the bottom and a new label gets added.

**Comment by PhilJay** [comment]
You can also customize your `Legend` to change that.

Use `legend.setCustom(...)` method.
