### ISSUE TITLE
setFillDrawable not in gradle build

### ISSUE THREAD

**Issue by jeffreyliu8** [PhilJay/MPAndroidChart#1436]
Hi, I tried both the zip file and the gradle version, but in gradle version 2.2.0, there is no setFillDrawable call in LineRadarDataSet.java, can someone please sync it please? Thanks.

**Comment by PhilJay** [comment]
It's going to be in the next release. You will have to be patient for another couple of days.

**Comment by jeffreyliu8** [comment]
Awesome, thank you!
