### ISSUE TITLE
saveToGallery method 

### ISSUE THREAD

**Issue by qzaqza1818** [PhilJay/MPAndroidChart#1438]
I had searched through the documentation you provided and those issues but I do not find any way to applied saveToGallery method to multiple charts. 

Means I have a horizontal bar chart and a pie chart below it, after click a generate button, both chart will be save to gallery as one image, is it possible?

**Comment by PhilJay** [comment]
Yes it is. But don't use the `saveToGallery(...)` method.

You need to extract the bitmap of both views and combine them. If you do some research on stackoverflow you can find out how this works.

**Comment by qzaqza1818** [comment]
ok thank you very much

**Comment by ajaybarvey** [comment]
I am using CombinedChart and I am saving single chart to path but it is not saving the image even though permission is given in manifest. What could be the issue?
--Code- 
  if (combinedChart.saveToPath("title" + System.currentTimeMillis(), "100")) {
                    Toast.makeText(getApplicationContext(), "Saving SUCCESSFUL!",
                            Toast.LENGTH_SHORT).show();
                Log.i("Logger", "Image saved to Gallery");
                } else {
                Toast.makeText(getApplicationContext(), "Saving FAILED!", Toast.LENGTH_SHORT)
                        .show();
            }
