### ISSUE TITLE
How to change the particular Tab text color in PieChart?

### ISSUE THREAD

**Issue by Mayank1904** [PhilJay/MPAndroidChart#1439]
![screenshot_2016-01-11-08-22-31](https://cloud.githubusercontent.com/assets/16149915/12774950/f96dfbc6-ca6f-11e5-9f1f-cece6098f914.png)

How to change the particular Tab text color? e.g Skipped text color which is white in color

**Comment by PhilJay** [comment]
Currently the color of invidual slices in the `PieChart` cannot be changed.

**Comment by Mayank1904** [comment]
ohk thanks for the reply.. can you please tell how to use this piechat in fragment?
