### ISSUE TITLE
Make MarkerView clickable

### ISSUE THREAD

**Issue by linKnowEasy** [PhilJay/MPAndroidChart#144]
I want add a Listener to the MarkerView,but it don't work

mv.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Log.v("LineChartActivity","click");
                Toast.makeText(getBaseContext(),"click",Toast.LENGTH_LONG).show();
            }
        });

the logcat didn't show the log, also the toast not show

**Comment by Smartertime** [comment]
I actually managed in a hacky way : you can set an "onClick" on the chart without interfering with the touch functions. You know when a marker is shown as refreshContent is called, then when you click the chart, the marker has been shown, and not valuesToHighlight(), then the marker has just been closed.

My test code with static status and text : 
barChart.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if(MyMarkerView.showing && !barChart.valuesToHighlight()) {
                    Log.i("barChart","closed "+MyMarkerView.barString);
                    MyMarkerView.showing = false;
                }
            }
        });

**Comment by jkwiecien** [comment]
still not possible?

**Comment by romatroskin** [comment]
Hey!
You can do something like place Chart and your View in RelativeLayout, look at , set ChartValueSelectedListener, fill your View and translate it's position like in getMarkerViewPosition() from Chart. Handle scroll events etc.

Sincerely,
Roman

**Comment by juliusspencer** [comment]
I made a solution of sorts:
http://stackoverflow.com/questions/37959156/mpandroidchart-button-click-in-markerview/37984995#37984995

**Comment by zhengxuming** [comment]
has this question bean soluted now?

**Comment by thanhzusu** [comment]
I have finished my app with clickable marker view. My solution is that we'll create a subclass of LineChart (or other chart), then let override onTouchEvent and detect the touch location.

```
public class MyChart extends LineChart {
    
    @Override
    public boolean onTouchEvent(MotionEvent event) {
        boolean handled = true;
        // if there is no marker view or drawing marker is disabled
        if (isShowingMarker() && this.getMarker() instanceof ChartInfoMarkerView){
            ChartInfoMarkerView markerView = (ChartInfoMarkerView) this.getMarker();
            Rect rect = new Rect((int)markerView.drawingPosX,(int)markerView.drawingPosY,(int)markerView.drawingPosX + markerView.getWidth(), (int)markerView.drawingPosY + markerView.getHeight());
            if (rect.contains((int) event.getX(),(int) event.getY())) {
                // touch on marker -> dispatch touch event in to marker
                markerView.dispatchTouchEvent(event);
            }else{
                handled = super.onTouchEvent(event);
            }
        }else{
            handled = super.onTouchEvent(event);
        }
        return handled;
    }

    private boolean isShowingMarker(){
        return mMarker != null && isDrawMarkersEnabled() && valuesToHighlight();
    }
}

public class ChartInfoMarkerView extends MarkerView {
    @BindView(R.id.markerContainerView)
    LinearLayout markerContainerView;
    
    protected float drawingPosX;
    protected float drawingPosY;
    private static final int MAX_CLICK_DURATION = 500;
    private long startClickTime;

    /**
     * The constructor
     *
     * @param context
     * @param layoutResource
     */
    public ChartInfoMarkerView(Context context, int layoutResource) {
        super(context, layoutResource);
        ButterKnife.bind(this);
        markerContainerView.setClickable(true);
        markerContainerView.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                Log.d("MARKER","click");
            }
        });
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        switch (event.getAction()) {
            case MotionEvent.ACTION_DOWN: {
                startClickTime = Calendar.getInstance().getTimeInMillis();
                break;
            }
            case MotionEvent.ACTION_UP: {
                long clickDuration = Calendar.getInstance().getTimeInMillis() - startClickTime;
                if(clickDuration < MAX_CLICK_DURATION) {
                    markerContainerView.performClick();
                }
            }
        }
        return super.onTouchEvent(event);
    }

    @Override
    public void draw(Canvas canvas, float posX, float posY) {
        super.draw(canvas, posX, posY);
        MPPointF offset = getOffsetForDrawingAtPoint(posX, posY);
        this.drawingPosX = posX + offset.x;
        this.drawingPosY = posY + offset.y;
    }
}
```

**Comment by JainamJhaveri** [comment]
Thanks, @thanhzusu your answer helped. If there was a button inside the markerview, I was wondering if there was any way to handle its onclick event.

**Comment by thanhzusu** [comment]
hi @JainamJhaveri 
You can get the coordinates from MotionEvent and determine whether it's inside viewDetailsButton's frame or not.
```
case MotionEvent.ACTION_UP: {
                    long clickDuration = Calendar.getInstance().getTimeInMillis() - startClickTime;
                    if (clickDuration < MAX_CLICK_DURATION) {
// TODO: check the coordinates from event inside viewDetailsButton's frame.
                        viewDetailsButton.performClick();
                    }
                }
```

**Comment by JainamJhaveri** [comment]
I am unable to figure out how to check the coordinates from inside viewDetailsButton, keeping in mind the orientation change as well

**Comment by RiverYYH** [comment]
how does ios?

**Comment by CavalcanteLeo** [comment]
@RiverYYH 

> how does ios?

i came here to try to find a solution too.

have you figured out how does it work on iOS?
