### ISSUE TITLE
Title for bar chart (include horizontal bar chart)

### ISSUE THREAD

**Issue by qzaqza1818** [PhilJay/MPAndroidChart#1440]
The bar chart only have setDescription method to set something as title for the chart. After that still had to use setDescriptionPosition method to adjust it. Do you plan on adding a setTitle function for bar chart? 

Besides that, we are able to adjust its position just like legend setPosition with defined constants. That would be great and thank you very much for your library.

**Comment by PhilJay** [comment]
I am not planning on adding a title feature any time soon. You can simply do that with an overlaying textview. As for the constants, that's something I might consider.

**Comment by May-nerd** [comment]
Maybe the title feature is nice to add especially if you want to export the chart as images?
