### ISSUE TITLE
withEnabled on drawer item

### ISSUE THREAD

**Issue by qzaqza1818** [PhilJay/MPAndroidChart#1441]
After I set withEnabled(false) on a secondary drawer item, it becomes disabled. Afterwards, I don't know how to enable a drawer item back. 

For example, result.getDrawerItems().get(3).withSelectable(true). I didn't found any method to enable the drawer item back.

**Comment by PhilJay** [comment]
This issue has nothing to do with this library (when looking at the information you provided). Maybe you are talking about the [MaterialDrawer](https://github.com/mikepenz/MaterialDrawer)?

**Comment by qzaqza1818** [comment]
ya, sorry for my mistake
