### ISSUE TITLE
LineChart Y autoscale with restrictions.

### ISSUE THREAD

**Issue by lboryczka** [PhilJay/MPAndroidChart#1442]
Hello,
is it possible to set some restrictions for autoscaling on Y axis, e.g. minimum visible values (e.g. -5;5). When the drawing of chart is dynamic and there are different values, like "big" - 20 and "small" - 1, like in this picture:
![chart](https://cloud.githubusercontent.com/assets/7459293/12780633/4739767e-ca6f-11e5-8707-f6775c8063fe.png)
It is possible to set the span e.g. 5? For values greater than 5 chart will be scaled, but for smaller max value will be set to 5.

Regards.

**Comment by PhilJay** [comment]
I'm not sure I understand everything, but yes you can restrict the `YAxis`: https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-(YLabels)

And you can react on scaling / zooming the chart with the `OnChartGestureListener` and e.g. change restrictions in the callbacks: https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart
