### ISSUE TITLE
CustomMarkerView

### ISSUE THREAD

**Issue by trehin** [PhilJay/MPAndroidChart#1443]
Hello Philip,

A markerview is set for a chart. Is it possible to set it for an Entry ?
I use different markerviews with pictures that I would like to display on the same chart.

Thanks for your help.

**Comment by PhilJay** [comment]
Well yes, with a few "hacks" I'd say you can simply change the layout of the `MarkerView` in the `refreshContent(...)` method.

Take a look at the `setupLayoutResource(...)` method: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/com/github/mikephil/charting/components/MarkerView.java
