### ISSUE TITLE
Exception: Attempt to invoke virtual method LineBuffer.setPhases(float, float) on a null object reference

### ISSUE THREAD

**Issue by mic3ael** [PhilJay/MPAndroidChart#1445]
Hi, found a NullpointerException when add real time data to LineChart.
The app crashed after few second ...

> E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                                Process: com.gmedinnovation.gmeditests, PID: 30113
>                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.mikephil.charting.buffer.LineBuffer.setPhases(float, float)' on a null object reference
>                                                                                    at com.github.mikephil.charting.renderer.LineChartRenderer.drawLinear(LineChartRenderer.java:295)
>                                                                                    at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:122)
>                                                                                    at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:101)
>                                                                                    at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:247)
>                                                                                    at android.view.View.draw(View.java:15040)
>                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:13961)
>                                                                                    at android.view.View.getDisplayList(View.java:13984)
>                                                                                    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3286)
>                                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3265)
>                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:13921)
>                                                                                    at android.view.View.getDisplayList(View.java:13984)
>                                                                                    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3286)
>                                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3265)
>                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:13921)
>                                                                                    at android.view.View.getDisplayList(View.java:13984)
>                                                                                    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3286)
>                                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3265)
>                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:13921)
>                                                                                    at android.view.View.getDisplayList(View.java:13984)
>                                                                                    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3286)
>                                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3265)
>                                                                                    at android.view.View.updateDisplayListIfDirty(View.java:13921)
>                                                                                    at android.view.View.getDisplayList(View.java:13984)
>                                                                                    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:284)
>                                                                                    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:290)
>                                                                                    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:342)
>                                                                                    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2581)
>                                                                                    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2406)
>                                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2030)
>                                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1094)
>                                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6054)
>                                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:793)
>                                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:606)
>                                                                                    at android.view.Choreographer.doFrame(Choreographer.java:575)
>                                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:779)
>                                                                                    at android.os.Handler.handleCallback(Handler.java:739)
>                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                                    at android.os.Looper.loop(Looper.java:135)
>                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5538)
>                                                                                    at java.lang.reflect.Method.invoke(Native Method)
>                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
>                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958)
>                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:753)

There is my LineChart class:

```
public class ChartECG extends LineChart {

    public ChartECG(Context context) {
        super(context);
    }

    public ChartECG(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public ChartECG(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
    }

    public void addNewResult(int[] values) {

        ILineDataSet set = getData().getDataSetByIndex(0);

        for (int i = 0; i < values.length; i++) {

            getData().addXValue("");
            setAutoScaleMinMaxEnabled(true);
            getAxisLeft().resetAxisMaxValue();
            getAxisLeft().resetAxisMinValue();

            getData().addEntry(new Entry((float) values[i], set.getEntryCount()), 0);
        }

        // let the chart know it's data has changed
        notifyDataSetChanged();

        // limit the number of visible entries
        setVisibleXRangeMaximum(TemporaryConsts.CHART_VISIBLE_X_RANGE_MAX);

        // scroll to the last entry
        moveViewToX(getXValCount() - (TemporaryConsts.CHART_VISIBLE_X_RANGE_MAX + 1));
    }

    public void init() {

        super.init();
        // no description text
        setDescription("");
        // no data text
        setNoDataText("");
        // no data description text
        setNoDataTextDescription("");
        // enable touch gestures
        setTouchEnabled(true);

        //setDoubleTapToZoomEnabled(false);

        // enable dragging
        setDragEnabled(true);

        //disable all zooming:
        setScaleEnabled(false);

        //disable highlight / selection:
        setHighlightPerTapEnabled(false);

        setDrawGridBackground(true);
        // if disabled, scaling can be done on x- and y-axis separately
        setPinchZoom(false);

        // set an alternative background color
        setBackgroundColor(Color.WHITE);

        XAxis xAxis = getXAxis();
        xAxis.setDrawGridLines(true);
        xAxis.setTextColor(Color.RED);
        xAxis.setDrawAxisLine(true);
        xAxis.setAxisLineColor(Color.RED);
        xAxis.setGridColor(Color.RED);
        xAxis.setLabelsToSkip(TemporaryConsts.SAMPLES_DRAW_LINE - 1);

        YAxis rightAxis = this.getAxisRight();
        rightAxis.setEnabled(false);

        YAxis leftAxis = this.getAxisLeft();
        leftAxis.setStartAtZero(false);
        leftAxis.setTextColor(Color.BLACK);
        leftAxis.setShowOnlyMinMax(false);
        leftAxis.setDrawGridLines(true);
        leftAxis.setAxisLineColor(Color.RED);
        leftAxis.setGridColor(Color.RED);
        leftAxis.setSpaceBottom(10f);
        leftAxis.setSpaceTop(10f);

        Legend legend = getLegend();
        legend.setEnabled(false);
        LineData data = new LineData();

        // add empty data
        setData(data);
        LineDataSet set = new LineDataSet(null, "Ecg");
        set.setAxisDependency(YAxis.AxisDependency.LEFT);
        set.setColor(ColorTemplate.getHoloBlue());
        set.setLineWidth(3f);
        set.setDrawCircles(false);
        set.setFillColor(ColorTemplate.getHoloBlue());
        set.setDrawValues(false);
        data.addDataSet(set);
    }
}
```

Thanks, Michael.

**Comment by PhilJay** [comment]
Try removing this from the for loop:

            setAutoScaleMinMaxEnabled(true);
            getAxisLeft().resetAxisMaxValue();
            getAxisLeft().resetAxisMinValue();

And call

data.notifyDataChanged() after calling data.addDataSet(...)

**Comment by PhilJay** [comment]
Documentation here: https://github.com/PhilJay/MPAndroidChart/wiki/Dynamic-&-Realtime-Data

**Comment by esfahanpayamak94** [comment]
اصفهان پیامک به عنوان فعال در زمینه [طراحی سایت در اصفهان](http://www.esfahanpayamak.com/webDesign) اهمیت این موضوع را به خوبی درک کرده و لذا از تکنولوژی های مدرن در طراحی های خود استفاده می نماید.
