### ISSUE TITLE
customization - radar chart -rounded

### ISSUE THREAD

**Issue by devpandda** [PhilJay/MPAndroidChart#1446]
hi ,

I wonder whether we can make the radar chart round ?
no way to do this for some property or only through the code of editing ?

**Comment by PhilJay** [comment]
Currently that is not possible by default, you will have to implement that yourself

**Comment by devpandda** [comment]
Thanks for the answer.
I will work on it and be able to make available here.
congratulations for the project

**Comment by sridharsaminathan** [comment]
Can you please update the things to make it round.
