### ISSUE TITLE
setScale in a line chart

### ISSUE THREAD

**Issue by Renaudyes** [PhilJay/MPAndroidChart#1449]
Hi,

I would like to know if it's possible to have the _same scale between data_ ( so, not the same space between them) in a line chart. 
After searching during hours the only function that could be what I want was "setSpaceBetweenLabels()". But unfortunately, that's not exactly what I want.

For example, it this picture : 
http://hpics.li/0dd38ed
As we can see the scale on the x axis is not respected. Indeed, they are the same space between data.

What I want is that : 
http://hpics.li/055b65a
Here we can see that the scale on the x axis is respected. But in order to do that, I must create a lot of different data. With what I want to do, it's not possible ...

Is there a trick to modified the code to achieve that ? 

Sorry for my english, hope you understand what i want to do.

Thanks in advance,

**Comment by PhilJay** [comment]
Just add empty x-values.
