### ISSUE TITLE
Set specific color for specific slice of a PieChart

### ISSUE THREAD

**Issue by ChristianAE** [PhilJay/MPAndroidChart#1450]
I am trying to find a way to set a specific color to a slice of a _PieChart_. In a _LineChart_ what I would do would be to create multiple _LineDataSet_'s and set the color for each individual. This  _LineDataSet_'s I would throw into an _ArrayList<ILineDataSet>_ and add this list as the second parameter of the _LineData_ constructor.
Sadly this does not work for _PieChart_'s. The JavaDoc of the _PieData_ class confirms that it can only hold one _PieDataSet_.
Is there a different way to define a particular color to a particular slice of a _PieChart_

**Comment by PhilJay** [comment]
Just use the `setColors(...)` method.

**Comment by ChristianAE** [comment]
That's would I thought. My problem is that I can't define which color is used for which slice.

From the Wiki:

> setColors(ArrayList<Integer>colors): Sets the colors that should be used fore this DataSet. Colors are reused as soon as the >number of Entries the DataSet represents is higher than the size of the colors array. Make sure that the >colors are already prepared (by calling getResources().getColor(...)) before adding them to the DataSet

I want to be able to define which Slice gets which color.

**Comment by PhilJay** [comment]
Sure you can.

If you have 5 slices, and you want them to be green, red, green, yellow, blue - then add green, red, green, yellow, blue to your colors array.

**Comment by ChristianAE** [comment]
Great. That could solve it.

This just leaves one problem: Deepening on the color of the slice I need to change the color of the text (for better readability). Is there a way to do that like with the colors for the slices?

**Comment by PhilJay** [comment]
Yes, I just added that feature: https://github.com/PhilJay/MPAndroidChart/commit/31de4f2a2905ba4f9a211095799e3fa65376778d

But its not in release v2.2.0, it will be in the next release which I will publish in the next couple of days.

**Comment by ChristianAE** [comment]
Danke! I appreciate it.

**Comment by fatema62a** [comment]
Hey #PhilJay , how to change the text color of each slice? Upper text is changing but the lower text is not changing

**Comment by IJDesign** [comment]
Hi #PhilJay, thanks for your creativity and innovation. The MPAndroidChart is a great library for developing cool applications. Currently, I'm using it to visualize the users' steps with the Piechart. In our design, we want to draw a slice of the chart with an image instead of filling it with a specific color. Is it possible to do that in the current version of MPAndroidChart? If it's yes, could you give some hints or references to try on? Thanks. The design of our UI is as follows. Thank you very much.
<img src="http://reach.bitnamiapp.com/Asking_Helps/HT_dailyview_piechart.jpg" />

**Comment by mujeebrahaman** [comment]
how to i need to set specific color for specific text in slice of a PieChart

**Comment by PratishParijaRaj** [comment]
> how i need to set specific color for specific text in slice of a PieChart

Did you get any solution ? Rehaman.
