### ISSUE TITLE
How to add two different Scatter Data in Combined Chart

### ISSUE THREAD

**Issue by swathimithran** [PhilJay/MPAndroidChart#1451]
Hi PhilJay,

Thanks for your previous reply, Currently we are using three dataset in Combined Chart namely  
1. Line Data
2. Scatter Data
3. Scatter Data 2

But when we plot the graph, it only shows the scatter Data which is added latest, hence we are getting only the "Scatter Data 2" on the graph. Can you please let us know how to resolve this issue.

We have many zero values in the Scatter Data, and we do not want to show them on the graph, We have the index value of non-zero values. Can you please explain how to proceed for that.

Thanks & Regards,
M Swathi Mithran.

**Comment by PhilJay** [comment]
Use one `LineData` object and one `ScatterData` object. Use 1 `LineDataSet`, use 2 `ScatterDataSets`.

**Comment by swathimithran** [comment]
Hi PhilJay,

Thank you for your instant reply, and the solution worked, we are able to plot different dataSet.
Can you please let us know how to hide non zero values from the Graph

Thanks & Regards,
M Swathi Mithran

**Comment by new-soul** [comment]
> Hi PhilJay,
> 
> Thank you for your instant reply, and the solution worked, we are able to plot different dataSet.
> Can you please let us know how to hide zero values from the Graph
> 
> Thanks & Regards,
> M Swathi Mithran

Hi,
I set 'ScatterData scatterData = new ScatterData(dataSets)' which dataSets is 'ArrayList<IScatterDataSet>' but it show only one what is last set ScatterData also.How did you solve？
Thanks.
