### ISSUE TITLE
Placing draw values inside circle in line chart (MPAndroid Used API) ?

### ISSUE THREAD

**Issue by VinuSuruli123** [PhilJay/MPAndroidChart#1453]
How to place the draw values inside the circle on line chart(i attached sample image ) like that i want to integrate
,I used MPAndroidChart for this,
Any suggestions regards placing the values or need to use some other API's for solving the issues.
![text3906](https://cloud.githubusercontent.com/assets/15013556/12915591/51513d9e-cf52-11e5-926f-3fcdd522a336.png)

**Comment by PhilJay** [comment]
That is something that is not possible by default. You will have to modify the library yourself to get that behaviour.
