### ISSUE TITLE
Realtime Line Chart Laggy after 10 mins of Graphing

### ISSUE THREAD

**Issue by KE7JLM** [PhilJay/MPAndroidChart#1457]
Hey guys, I am using a Realtime line chart to graph csv data coming in from an Arduino with a Bluetooth adapter. Everything works great but I am getting some lag in the data and overall poor system performance when graphing the data. The data is coming in at about 90Hz. Over time it because complete unusable and will freeze my Note4. I pretty much followed the MPChart example code. I set DragEnable to false, I also set TouchEnable to false. I don't care about the old data and I am only graphing so we can get a visual representation of the data. I suspect the chart is storing all of that old data and its running out of memory. 

My question for you guys is, how do I make it not lag up over time? I can't seem to find another options relevant to this issue. 

Thanks in advance.

**Comment by PhilJay** [comment]
Well, 90Hz is a pretty fast rate, and over a time of 10 minutes this means there are 54.000 values in the chart. That amount of data obviously takes it's toll on the library and on the operating system.

I suggest you find a way to either reduce the data rate, or to reduce the total amount of values (e.g. by deleting old ones or doing some filtering...).
