### ISSUE TITLE
Showing BarData set in combine chart

### ISSUE THREAD

**Issue by jatindersi** [PhilJay/MPAndroidChart#1458]
I am trying to combine multiple charts together. Its working fine in case of linedataset. But as i try to add bardata in combinechart  the chart is cutting  from edges its not displaying all bardataset values in chart please let me know where i need modification so that it will work in bardataset in combinechart

**Comment by PhilJay** [comment]
Are you using multiple `BarDataSets`?

Show a screenshot and some code how you setup the chart & data.

**Comment by jatindersi** [comment]
Hello 

i am using below code and i am adding some screenshot for your reference
![device-2016-02-10-142155](https://cloud.githubusercontent.com/assets/17155287/12942546/06138566-d002-11e5-9a96-424173be1661.png)
![device-2016-02-10-142111](https://cloud.githubusercontent.com/assets/17155287/12942547/06401162-d002-11e5-97dc-b3c75bfe29d7.png)
When there are more then one bardata set below Xvals getting  smaller its not taking whole device space as you see in case of line and bar its working fine

**Comment by jatindersi** [comment]
private void setUpCombineBarChart()
    {
        Chart = new CombinedChart(getActivity());
        Chart.setDescription("");
        Chart.setNoDataTextDescription("No Chart Data Available.");
        Chart.setBackgroundColor(Color.WHITE);
        Chart.setDrawGridBackground(false);
        Chart.setDrawBarShadow(false);
        Chart.getLegend().setEnabled(false);


        // draw bars behind lines
        Chart.setDrawOrder(new CombinedChart.DrawOrder[]{
                CombinedChart.DrawOrder.BAR, CombinedChart.DrawOrder.BUBBLE, CombinedChart.DrawOrder.CANDLE, CombinedChart.DrawOrder.LINE, CombinedChart.DrawOrder.SCATTER
        });
        MyMarkerView mv = new MyMarkerView(getActivity(), R.layout.custom_marker_view);
        Chart.setMarkerView(mv);
        YAxis rightAxis = Chart.getAxisRight();
        rightAxis.setDrawGridLines(false);
        rightAxis.setDrawLabels(false);
        rightAxis.setEnabled(false);

        YAxis leftAxis = Chart.getAxisLeft();
        leftAxis.setValueFormatter(new LargeValueFormatter());
        leftAxis.setDrawGridLines(false);
        leftAxis.setSpaceTop(30f);

        XAxis xAxis = Chart.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setEnabled(true);
        xAxis.setLabelRotationAngle(45);
        xAxis.setSpaceBetweenLabels(0);
        xAxis.setTextSize(9);

        ArrayList<String> xVals = null;
        ArrayList<Entry> yVals = null;
        ArrayList<BarEntry> yValsBar = null;
        ArrayList<ILineDataSet> dataSets = new ArrayList<ILineDataSet>();
        ArrayList<IBarDataSet> dataSetsBar = new ArrayList<IBarDataSet>();
        String setvalue = "";
        if (Util.isEngLocale())
        {
            CombinedData data = null;
            for (int j = 0; j < ChartGlobal.chartList.size(); j++)
            {

                if (ChartGlobal.chartList.get(j).isSelected())
                {

                    xVals = new ArrayList<>();
                    yVals = new ArrayList<>();
                    yValsBar = new ArrayList<>();

                    for (int i = 0; i < ChartGlobal.chartList.get(j).valuesEn.size(); i++)
                    {
                        xVals.add(ChartGlobal.chartList.get(j).valuesEn.get(i).valueX);
                        float val = Float.parseFloat(ChartGlobal.chartList.get(j).valuesEn.get(i).valueY);
                        yVals.add(new Entry(val, i));
                        yValsBar.add(new BarEntry(val, i));
                        setvalue = ChartGlobal.chartList.get(j).nameEn;
                        if (data == null)
                            data = new CombinedData(xVals);
//                        if (ChartGlobal.chartList.get(j).display.equalsIgnoreCase("line"))
//                        {
//                            data.setData(generateLineData(yVals, setvalue, j));
//                        }
//                        else if (ChartGlobal.chartList.get(j).display.equalsIgnoreCase("column"))
//                        {
//                            data.setData(generateBarData(yValsBar, setvalue, j));
//                        }
//                        Chart.setData(data);
                    }
                    if(ChartGlobal.chartList.get(j).valuesEn.size()>0)
                    {
                        if (ChartGlobal.chartList.get(j).display.equalsIgnoreCase("line"))
                        {
                            LineDataSet d = new LineDataSet(yVals, "");
                            d.setLineWidth(2.5f);
                            d.setCircleSize(4f);
                            int totalYAxis = 0;
                            String title = "";
                            for (int i = 0; i < ChartGlobal.chartList.get(j).valuesEn.size(); i++)
                            {
                                if (ChartViewActivity.isInteger(ChartGlobal.chartList.get(j).valuesEn.get(i).valueY))
                                {
                                    totalYAxis = totalYAxis + Integer.parseInt(ChartGlobal.chartList.get(j).valuesEn.get(i).valueY);
                                }
                            }
                            title = totalYAxis + "\n" + ChartGlobal.chartList.get(j).nameEn;
                            d.setLabel(title);
                            d.setValueTextSize(15f);
                            d.setColor((ColorTemplate.rgb(ChartGlobal.chartList.get(j).rgbColor)));
                            d.setCircleColor((ColorTemplate.rgb(ChartGlobal.chartList.get(j).rgbColor)));
                            dataSets.add(d);
                            LineData datavalue = new LineData(xVals, dataSets);
                            data.setData(datavalue);
                            Chart.setData(data);
                            //Chart.invalidate();
                        }
                        else if (ChartGlobal.chartList.get(j).display.equalsIgnoreCase("column"))
                        {
                             BarDataSet barset = new BarDataSet(yValsBar,"");
                             //barset.setBarSpacePercent(30f);

                            barset.setColor((ColorTemplate.rgb(ChartGlobal.chartList.get(j).rgbColor)));
                            int totalYAxis = 0;
                            String title = "";
                            for (int i = 0; i < ChartGlobal.chartList.get(j).valuesEn.size(); i++)
                            {
                                if (ChartViewActivity.isInteger(ChartGlobal.chartList.get(j).valuesEn.get(i).valueY))
                                {
                                    totalYAxis = totalYAxis + Integer.parseInt(ChartGlobal.chartList.get(j).valuesEn.get(i).valueY);
                                }
                            }
                            title = totalYAxis + "\n" + ChartGlobal.chartList.get(j).nameEn;
                            barset.setLabel(title);
                            barset.setValueTextSize(15.0f);
                            dataSetsBar.add(barset);
                            BarData dataBar = new BarData(xVals, dataSetsBar);
                            dataBar.setValueFormatter(new LargeValueFormatter());
                            // add space between the dataset groups in percent of bar-width
                            // dataBar.setGroupSpace(100f);
                            //  data.setValueTypeface(tf);

                            data.setData(dataBar);
                            Chart.setData(data);
                            //  Chart.invalidate();
                        }
                    }
                    if (xVals.size() > 3)
                    {
                        Chart.setDragEnabled(true); // on by default
                       // Chart.setVisibleXRange(5f, 15f);
                    }
                }
            }

        } else
        {
            CombinedData data = null;
            for (int j = 0; j < ChartGlobal.chartList.size(); j++)
            {

                if (ChartGlobal.chartList.get(j).isSelected())
                {

                    xVals = new ArrayList<>();
                    yVals = new ArrayList<>();
                    yValsBar = new ArrayList<>();

                    for (int i = 0; i < ChartGlobal.chartList.get(j).valuesAr.size(); i++)
                    {
                        xVals.add(ChartGlobal.chartList.get(j).valuesAr.get(i).valueX);
                        float val = Float.parseFloat(ChartGlobal.chartList.get(j).valuesAr.get(i).valueY);
                        yVals.add(new Entry(val, i));
                        yValsBar.add(new BarEntry(val, i));
                        setvalue = ChartGlobal.chartList.get(j).nameAr;
                        if (data == null)
                            data = new CombinedData(xVals);
//                        if (ChartGlobal.chartList.get(j).display.equalsIgnoreCase("line"))
//                        {
//                            data.setData(generateLineData(yVals, setvalue, j));
//                        } else if (ChartGlobal.chartList.get(j).display.equalsIgnoreCase("column"))
//                        {
//                            data.setData(generateBarData(yValsBar, setvalue, j));
//                        }
//                        Chart.setData(data);
                    }
                    if(ChartGlobal.chartList.get(j).valuesAr.size()>0)
                    {
                        if (ChartGlobal.chartList.get(j).display.equalsIgnoreCase("line"))
                        {
                            LineDataSet d = new LineDataSet(yVals, "");
                            d.setLineWidth(2.5f);
                            d.setCircleSize(4f);
                            int totalYAxis = 0;
                            String title = "";
                            for (int i = 0; i < ChartGlobal.chartList.get(j).valuesAr.size(); i++)
                            {
                                if (ChartViewActivity.isInteger(ChartGlobal.chartList.get(j).valuesAr.get(i).valueY))
                                {
                                    totalYAxis = totalYAxis + Integer.parseInt(ChartGlobal.chartList.get(j).valuesAr.get(i).valueY);
                                }
                            }
                            title = totalYAxis + "\n" + ChartGlobal.chartList.get(j).nameAr;
                            d.setLabel(title);
                            d.setValueTextSize(15.0f);
                            d.setColor((ColorTemplate.rgb(ChartGlobal.chartList.get(j).rgbColor)));
                            d.setCircleColor((ColorTemplate.rgb(ChartGlobal.chartList.get(j).rgbColor)));
                            dataSets.add(d);
                            LineData datavalue = new LineData(xVals, dataSets);
                            data.setData(datavalue);
                            Chart.setData(data);
                           // Chart.invalidate();
                        } else if (ChartGlobal.chartList.get(j).display.equalsIgnoreCase("column"))

                        {
                            BarDataSet barset = new BarDataSet(yValsBar, "");
                          //  barset.setBarSpacePercent(60f);
                            int totalYAxis = 0;
                            String title = "";
                            for (int i = 0; i < ChartGlobal.chartList.get(j).valuesAr.size(); i++)
                            {
                                if (ChartViewActivity.isInteger(ChartGlobal.chartList.get(j).valuesAr.get(i).valueY))
                                {
                                    totalYAxis = totalYAxis + Integer.parseInt(ChartGlobal.chartList.get(j).valuesAr.get(i).valueY);
                                }
                            }
                            title = totalYAxis + "\n" + ChartGlobal.chartList.get(j).nameAr;
                            barset.setLabel(title);
                            barset.setValueTextSize(15.0f);
                            barset.setColor((ColorTemplate.rgb(ChartGlobal.chartList.get(j).rgbColor)));
                            dataSetsBar.add(barset);
                            BarData dataBar = new BarData(xVals, dataSetsBar);

//        data.setValueFormatter(new LargeValueFormatter());

                            // add space between the dataset groups in percent of bar-width
                            dataBar.setGroupSpace(80f);
                            //  data.setValueTypeface(tf);
                            data.setData(dataBar);
                            Chart.setData(data);
                            // Chart.invalidate();
                        }
                    }
                if(xVals.size()>3)
                {
                    Chart.setDragEnabled(true); // on by default
                    //Chart.setVisibleXRange(5f,15f);
                }
                }
            }

        }


        Chart.invalidate();
        mparentchartcontainer.addView(Chart);


    }

****This is the code that i am using  its working fine in case of LIneDataset but in case of bardataset i am not getting proper display of result i modified Combinechart calcminmax() Method and it show all bar values but below labels are still not ok**

**Comment by jatindersi** [comment]
My only issue now is Xvals are not taking whole device width in case of Bardataset as you can check in screens

**Comment by jatindersi** [comment]
package com.github.mikephil.charting.charts;

import android.content.Context;
import android.util.AttributeSet;
import android.util.Log;

import com.github.mikephil.charting.data.BarData;
import com.github.mikephil.charting.data.BubbleData;
import com.github.mikephil.charting.data.CandleData;
import com.github.mikephil.charting.data.CombinedData;
import com.github.mikephil.charting.data.LineData;
import com.github.mikephil.charting.data.ScatterData;
import com.github.mikephil.charting.highlight.CombinedHighlighter;
import com.github.mikephil.charting.interfaces.datasets.IBubbleDataSet;
import com.github.mikephil.charting.interfaces.dataprovider.BarDataProvider;
import com.github.mikephil.charting.interfaces.dataprovider.BubbleDataProvider;
import com.github.mikephil.charting.interfaces.dataprovider.CandleDataProvider;
import com.github.mikephil.charting.interfaces.dataprovider.LineDataProvider;
import com.github.mikephil.charting.interfaces.dataprovider.ScatterDataProvider;
import com.github.mikephil.charting.renderer.CombinedChartRenderer;

/**
 * This chart class allows the combination of lines, bars, scatter and candle
 * data all displayed in one chart area.
 *
 * @author Philipp Jahoda
 */
public class CombinedChart extends BarLineChartBase<CombinedData> implements LineDataProvider,
        BarDataProvider, ScatterDataProvider, CandleDataProvider, BubbleDataProvider {

    /**
     * flag that enables or disables the highlighting arrow
     */
    private boolean mDrawHighlightArrow = false;

    /**
     * if set to true, all values are drawn above their bars, instead of below
     * their top
     */
    private boolean mDrawValueAboveBar = true;

    /**
     * if set to true, a grey area is drawn behind each bar that indicates the
     * maximum value
     */
    private boolean mDrawBarShadow = false;

    protected DrawOrder[] mDrawOrder = new DrawOrder[]{
            DrawOrder.BAR, DrawOrder.BUBBLE, DrawOrder.LINE, DrawOrder.CANDLE, DrawOrder.SCATTER
    };

    /**
     * enum that allows to specify the order in which the different data objects
     * for the combined-chart are drawn
     */
    public enum DrawOrder {
        BAR, BUBBLE, LINE, CANDLE, SCATTER
    }

    public CombinedChart(Context context) {
        super(context);
    }

    public CombinedChart(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public CombinedChart(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
    }

    @Override
    protected void init() {
        super.init();

        mHighlighter = new CombinedHighlighter(this);

        // mRenderer = new CombinedChartRenderer(this, mAnimator,
        // mViewPortHandler);
    }

    @Override
    protected void calcMinMax() {
        super.calcMinMax();

        if (getBarData() != null || getCandleData() != null || getBubbleData() != null) {
            mXChartMin = -0.5f;
            mXChartMax = mData.getXVals().size() - 0.5f;

            if (getBubbleData() != null)
            {

                for (IBubbleDataSet set : getBubbleData().getDataSets()) {

                    final float xmin = set.getXMin();
                    final float xmax = set.getXMax();

                    if (xmin < mXChartMin)
                        mXChartMin = xmin;

                    if (xmax > mXChartMax)
                        mXChartMax = xmax;
                }
            }
        }

        mDeltaX = Math.abs(mXChartMax - mXChartMin);

        if (mDeltaX == 0.f && getLineData() != null && getLineData().getYValCount() > 0) {
            mDeltaX = 1.f;
        }
        if (getBarData()!= null && getBarData().getYValCount() > 0)
        {
            // increase deltax by 1 because the bars have a width of 1
            mDeltaX += 0.5f;

            // extend xDelta to make space for multiple datasets (if ther are one)
            mDeltaX *= mData.getBarData().getDataSetCount();

            float groupSpace =mData.getBarData().getGroupSpace();
            mDeltaX += mData.getBarData().getXValCount() * groupSpace;
            mXChartMax = mData.getBarData().getXVals().size() - 0.5f;
            Log.e("values",mXChartMax +"" +mDeltaX);
        }
        Log.e("Without",mXChartMax +"" +mDeltaX);
    }

    @Override
    public void setData(CombinedData data) {
        mData = null;
        mRenderer = null;
        super.setData(data);
        mRenderer = new CombinedChartRenderer(this, mAnimator, mViewPortHandler);
        mRenderer.initBuffers();
    }

    @Override
    public LineData getLineData() {
        if (mData == null)
            return null;
        return mData.getLineData();
    }

    @Override
    public BarData getBarData() {
        if (mData == null)
            return null;
        return mData.getBarData();
    }

    @Override
    public ScatterData getScatterData() {
        if (mData == null)
            return null;
        return mData.getScatterData();
    }

    @Override
    public CandleData getCandleData() {
        if (mData == null)
            return null;
        return mData.getCandleData();
    }

    @Override
    public BubbleData getBubbleData() {
        if (mData == null)
            return null;
        return mData.getBubbleData();
    }

    @Override
    public boolean isDrawBarShadowEnabled() {
        return mDrawBarShadow;
    }

    @Override
    public boolean isDrawValueAboveBarEnabled() {
        return mDrawValueAboveBar;
    }

    @Override
    public boolean isDrawHighlightArrowEnabled() {
        return mDrawHighlightArrow;
    }

    /**
     * set this to true to draw the highlightning arrow
     *
     * @param enabled
     */
    public void setDrawHighlightArrow(boolean enabled) {
        mDrawHighlightArrow = enabled;
    }

    /**
     * If set to true, all values are drawn above their bars, instead of below
     * their top.
     *
     * @param enabled
     */
    public void setDrawValueAboveBar(boolean enabled) {
        mDrawValueAboveBar = enabled;
    }


    /**
     * If set to true, a grey area is drawn behind each bar that indicates the
     * maximum value. Enabling his will reduce performance by about 50%.
     *
     * @param enabled
     */
    public void setDrawBarShadow(boolean enabled) {
        mDrawBarShadow = enabled;
    }

    /**
     * Returns the currently set draw order.
     *
     * @return
     */
    public DrawOrder[] getDrawOrder() {
        return mDrawOrder;
    }

    /**
     * Sets the order in which the provided data objects should be drawn. The
     * earlier you place them in the provided array, the further they will be in
     * the background. e.g. if you provide new DrawOrer[] { DrawOrder.BAR,
     * DrawOrder.LINE }, the bars will be drawn behind the lines.
     *
     * @param order
     */
    public void setDrawOrder(DrawOrder[] order) {
        if (order == null || order.length <= 0)
            return;
        mDrawOrder = order;
    }
}
calcMinMax() i had chnaged to something like this in case of BarData so its showing all Yvals but xvals i think i need some modification there.please suggest

**Comment by PhilJay** [comment]
Okay, I see the issue.
Multiple `BarDataSets` in a `CombinedChart` are unfortunately not yet supported.

See here: #449
