### ISSUE TITLE
pie chart issue 

### ISSUE THREAD

**Issue by kshrikant** [PhilJay/MPAndroidChart#1459]
@PhilJay 
![device-2016-02-10-143725](https://cloud.githubusercontent.com/assets/9281639/12943009/757dbafa-d004-11e5-8098-06a90c205592.png)

In fragment i have implemented pie chart. The issue is whenever i'm clicking any section all other sections get vanished. As mentioned in above image. Please let me know how to fix this, it will be really grateful.

**Comment by PhilJay** [comment]
Show the code you use to add data to the chart.

Start your x-index at 0.

**Comment by kshrikant** [comment]
Please check below code. Thank you.
     
       pieChart = (PieChart)view.findViewById(R.id.chart);

        pieChart.setUsePercentValues(true);
        pieChart.setDescription("");
        pieChart.setExtraOffsets(5, 10, 5, 5);
        pieChart.setDragDecelerationFrictionCoef(0.95f);
        pieChart.setDrawHoleEnabled(true);
        pieChart.setHoleColorTransparent(true);
        pieChart.setTransparentCircleColor(Color.WHITE);
        pieChart.setTransparentCircleAlpha(110);
        pieChart.setHoleRadius(58f);
		//      pieChart.setTouchEnabled(true);
        pieChart.setTransparentCircleRadius(61f);
        pieChart.setDrawCenterText(true);
        pieChart.setRotationAngle(0);
		//        pieChart.setRotationEnabled(true);
        pieChart.setHighlightPerTapEnabled(true);
        //pieChart.animateY(1400, Easing.EasingOption.EaseInOutQuad);
        pieChart.setOnChartValueSelectedListener(this);



        // customize legends
        Legend l = pieChart.getLegend();
        l.setPosition(Legend.LegendPosition.RIGHT_OF_CHART);
        l.setXEntrySpace(7);
        l.setYEntrySpace(5);
        l.setYOffset(0f);
  
 		 private void loadPieChart()
   		 {
   	     noOfferTextView.setVisibility(View.GONE);

        OfferModel offer = offers.get(currentPosition);

        ArrayList<OfferAnalyticModel> analyticModels = vendorDB.selectOfferAnalyticWhere(offer.offerId);
        ArrayList<String> xValues = new ArrayList<>();
        ArrayList<Entry> yValues = new ArrayList<Entry>();

        float total = 0.0f;

        for(int i =0;i<analyticModels.size();i++)
        {
            String name = vendorDB.selectStatusNameforID(analyticModels.get(i).offerStatusId);
            xValues.add(name);//(analyticModels.get(i).name);
            total += analyticModels.get(i).count;
        }


        for(int i =0;i<analyticModels.size();i++)
        {
            float count = analyticModels.get(i).count;
            yValues.add(new Entry((count/100)*total,0));
        }


        // create pie data set
        PieDataSet dataSet = new PieDataSet(yValues,"Offer Statistics");
        dataSet.setSliceSpace(3);
        dataSet.setSelectionShift(5);

        // add many colors
        ArrayList<Integer> colors = new ArrayList<Integer>();

        for (int c : ColorTemplate.VORDIPLOM_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.JOYFUL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.COLORFUL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.LIBERTY_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.PASTEL_COLORS)
            colors.add(c);

        colors.add(ColorTemplate.getHoloBlue());
        dataSet.setColors(colors);

        // instantiate pie data object now
        PieData data = new PieData(xValues, dataSet);
        data.setValueFormatter(new PercentFormatter());
        data.setValueTextSize(11f);
        data.setValueTextColor(Color.GRAY);

        pieChart.setData(data);

        // undo all highlights
        pieChart.highlightValues(null);

        pieChart.setVisibility(View.VISIBLE);

        // update pie chart
        pieChart.invalidate();
   		 }

**Comment by kshrikant** [comment]
@PhilJay please check above code & let me know.

**Comment by PhilJay** [comment]
yValues.add(new Entry((count/100)*total,0));

should be:

yValues.add(new Entry((count/100)*total,i));

**Comment by kshrikant** [comment]
Thanks a lot man !! you saved my time :) :+1:

**Comment by softwarelim** [comment]
Wow.. Thank you for your kind explain.
