### ISSUE TITLE
Wrong display for negative values in BarChart

### ISSUE THREAD

**Issue by SilkSama** [PhilJay/MPAndroidChart#146]
Negative values displayed inside a BarChart (maybe the same for other charts) have a wrong position.
See linked screenshot.
There is a mistake of my side ?
(setDrawValueAboveBar is set to true)
![capture](https://cloud.githubusercontent.com/assets/9135797/4593572/f836a3f2-5086-11e4-8191-7aed89fef57b.JPG)

**Comment by rashmitank** [comment]
I am facing same issue in v3.1.0. In which version, i can get this issue fixed ?
