### ISSUE TITLE
How to change color of  value's which I painted red ?  

### ISSUE THREAD

**Issue by yusufonderd** [PhilJay/MPAndroidChart#1461]
I used setValueTextColor but it didn't  work. . 

```
LineDataSet d1 = new LineDataSet(e1, entityList.get(i).getName());
d1.setValueTextColor(Color.rgb(255, 255, 83));
sets.add(d1);
LineData cd = new LineData(dateList, sets);
cd.setValueTextColor(Color.rgb(223, 83, 83));

```
![mpandroid](https://cloud.githubusercontent.com/assets/13941871/12949797/81fc89c4-d012-11e5-9104-617f716e0768.png)

**Comment by PhilJay** [comment]
Individual colors for individual axis or legend entries are not supported atm.
