### ISSUE TITLE
90 degree rotated XAxis labels gets out of view.

### ISSUE THREAD

**Issue by michaelfranz89** [PhilJay/MPAndroidChart#1462]
This is my setup of my chart:
chart.setDescription("");
chart.getAxisRight().setEnabled(false);
chart.getXAxis().setPosition(XAxis.XAxisPosition.BOTTOM);
chart.setTouchEnabled(false);
chart.setDrawGridBackground(false);
chart.getAxisLeft().setAxisMaxValue(100);
// Fix when labels are rotated and gets out of bounds.
chart.getXAxis().setSpaceBetweenLabels(4);
chart.getXAxis().setLabelRotationAngle(90);
chart.getAxisLeft().setDrawGridLines(false);
chart.setData(getHistogramData(title, keys, values));
chart.getLegend().setEnabled(false);
chart.invalidate();

Here i have to use setSpaceBetweenLabels for the entire labels to be shown. Otherwise the label gets cut and not shown.

**Comment by PhilJay** [comment]
Which library version?

**Comment by michaelfranz89** [comment]
Sorry I have not answered earlier.
I use the version: com.github.PhilJay:MPAndroidChart:v2.1.6

**Comment by troy21688** [comment]
I am having the same issue as well:

<img width="373" alt="screen shot 2016-02-17 at 9 21 09 pm" src="https://cloud.githubusercontent.com/assets/16483832/13132896/689598d6-d5bc-11e5-93c8-5e006c37278b.png">
