### ISSUE TITLE
I want to show Both values on Top Xvals and yvals

### ISSUE THREAD

**Issue by jatindersi** [PhilJay/MPAndroidChart#1463]
AS there is method name ** setdrawvalues()** which show Yvals on top . i want to show Both xvals and Yvals on Top of chart is it possibel .Please let me know if thi possibe

**Comment by PhilJay** [comment]
You can shot the x-values on top, you cannot show the values on top of the chart.

**Comment by jatindersi** [comment]
OK can i show Multiple Marker View on a single click means marker view show on top of each chart point

**Comment by PhilJay** [comment]
Are you talking about on top of the points? You can show anything you want in the markerview, including xaxis value.

**Comment by jatindersi** [comment]
yes i want to show markerview for each top points in a single click of a button
