### ISSUE TITLE
Realtime line chart stops scrolling at the time of the GC.

### ISSUE THREAD

**Issue by mrksy** [PhilJay/MPAndroidChart#1464]
I am using a Reltime line chart with "setDrawFilled(true)" option.
But it sometimes stops scrolling for a moment at the time of the garbage collection.

I changed the following two lines of the Realtime line chart sample (v2.2.2). And I checked the time of the GC in the memory monitor of Android Studio.

```Java

    private LineDataSet createSet() {

        LineDataSet set = new LineDataSet(null, "Dynamic Data");
        set.setAxisDependency(AxisDependency.LEFT);
        set.setColor(ColorTemplate.getHoloBlue());
        set.setCircleColor(Color.WHITE);
        set.setLineWidth(2f);
        set.setCircleRadius(4f);
        set.setFillAlpha(65);
        set.setFillColor(ColorTemplate.getHoloBlue());
        set.setHighLightColor(Color.rgb(244, 117, 117));
        set.setValueTextColor(Color.WHITE);
        set.setValueTextSize(9f);
        set.setDrawValues(false);
        set.setDrawFilled(true);    //Here
        return set;
    }

    private void feedMultiple() {

        new Thread(new Runnable() {

            @Override
            public void run() {
                for(int i = 0; i < 10000; i++) {    //Here

                    runOnUiThread(new Runnable() {

                        @Override
                        public void run() {
                            addEntry();
                        }
                    });

                    try {
                        Thread.sleep(35);
                    } catch (InterruptedException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                }
            }
        }).start();
    }
```

The problem occurred on the following devices.

- Nexus 6P (Android 6.0.1)

- Nexus 5X (Android 6.0.1)

- Nexus 9 (Android 6.0)

However, the problem did not occur on the following devices.

- Nexus 6 (Android 6.0.1)

- Nexus 5 (Android 5.1.1)

- Xperia Z5 (Android 5.1.1)

Can you advise something? 
Thank you.

**Comment by PhilJay** [comment]
Are you sure the realtime feed stops because of gc?
Or are the 10 seconds (10000 milliseconds) the thread is supposed to run simply over and then the system garbage collects?

**Comment by mrksy** [comment]
I am using memory monitor tool in Android Studio. When the allocated memory amount has dropped, the realtime feed stops. Even if I click the "Initiate GC" button, the problem will occur in the same way.

There is no special meaning to the number of 10000 in above code. It's just repeating "addEntry" for monitoring long times.

**Comment by PhilJay** [comment]
Okay, well I'm not sure what do do about this :-)
