### ISSUE TITLE
Interrupt functionality for LineChart

### ISSUE THREAD

**Issue by arkde8** [PhilJay/MPAndroidChart#1466]
First of all I would like to thank you for this awesome library.
I'm currently using it in my application and it performs outstanding.
I have to implement a line chart that uses a gradient drawn on it. I've figured that out by drawing a gradient on the `paintRenderer`.
Now I'm in need to add interrupted parts to the line graph, just like in this image
http://imgur.com/0y8jouQ

Is it possible to do that somehow with the current implementation? Or do I need to create another renderer that is able to draw the values like that

**Comment by PhilJay** [comment]
It is now possible to set a gradient: `lineDataSet.setFillDrawable(...)`

What you mentioned with the "interrupts" can be achieved by using multiple datasets.

**Comment by arkde8** [comment]
Hey Phil,
I've been testing around with the Line data and I accidentally found that if I add a value to the line data set equal to Long.MIN_VALUE, those values are not drawn and the graph is completely ignoring those values, leaving it interrupted.

I was digging deep into the library to find out why, and it seems that those values are out of bounds for the graph and there are some checks in place for outside of bounds drawing. 

What do you think about this?
