### ISSUE TITLE
Pull Bar from Bar Chart

### ISSUE THREAD

**Issue by troy21688** [PhilJay/MPAndroidChart#1468]
I am interested in pulling the bar graphic from the bar chart. Would it be possible to pull this information without all of the other axis and data?  Please see post here: http://stackoverflow.com/questions/35346511/how-to-programatically-create-a-bar-displaying-poll-results-under-answer-option

**Comment by PhilJay** [comment]
Well a quite simple solution could be to simple disable all legends, axis, etc... and then use the build in functions to save the graph.
