### ISSUE TITLE
Increase line chart width to screen width

### ISSUE THREAD

**Issue by jz-plume** [PhilJay/MPAndroidChart#1469]
Is there a way to increase the chart width to the full screen width? I would like to achieve the effect of having only top/bottom borders and hide the left/right borders into the edges

**Comment by PhilJay** [comment]
I guess `chart.setViewPortOffsets(...)` is what you are looking for.

https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport

**Comment by Sheshank-Srivastava** [comment]
how can i increase the thickness of line in line Chart??
