### ISSUE TITLE
Horizontal Bar Graph Not Generating Data

### ISSUE THREAD

**Issue by troy21688** [PhilJay/MPAndroidChart#1470]
I am trying to generate a horizontal bar graph and am having issues. Ultimately, I will be adding dynamic data, but for now I am just trying to get a feel for how the library works. With my current code, I am not able to generate a Bar Graph:

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // TODO: Add Fragment Code to check if savedInstanceState == null; add at Activity Level?

        // Inflate the layout for this fragment
        final ViewGroup rootView = (ViewGroup) inflater.inflate(R.layout.fragment_poll, container, false);
        getActivity().setTitle(R.string.todays_polls_title);

        //Initialize Poll Results Bar Chart and set to Invisible
        mPollResults = (HorizontalBarChart) rootView.findViewById(R.id.poll_results_chart);
        mPollResults.setBackgroundColor(getResources().getColor(R.color.white));
        mPollResults.setNoDataTextDescription(getResources().getString(R.string.no_results_description));
        mPollResults.setVisibility(View.INVISIBLE);

        mPollQuestion = (TextView) rootView.findViewById(R.id.poll_question);
        mPollQuestionRadioGroup = (RadioGroup) rootView.findViewById(R.id.poll_question_group);
        mPollQuestionRadioGroup.setOnCheckedChangeListener(new RadioGroup.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(RadioGroup group, int checkedId) {
                group.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        mPollQuestionRadioGroup.setVisibility(View.INVISIBLE);
                    }
                }, 1000);
                mPollResults.setVisibility(View.VISIBLE);
                ArrayList<Entry> valuesToCompare = new ArrayList<Entry>();
                valuesToCompare.add(new Entry(100.000f, 0));
                valuesToCompare.add(new Entry(500.000f, 1));
                CustomBarDataSet data = new CustomBarDataSet(valuesToCompare, "Vote Results");
                data.setAxisDependency(YAxis.AxisDependency.RIGHT);
                ArrayList<IBarDataSet> dataSets = new ArrayList<IBarDataSet>();
                dataSets.add(data);
                ArrayList<String> xvals = new ArrayList<String>();
                xvals.add(0, "Test 1");
                xvals.add(1, "Test 2");
                BarData testBarData = new BarData(xvals, dataSets);
                mPollResults.setData(testBarData);
                mPollResults.invalidate();

![image](https://cloud.githubusercontent.com/assets/16483832/12998042/ae0adabe-d104-11e5-9a73-d698050df0d8.png)

**Comment by PhilJay** [comment]
Is there any reason you are using a "customized" version of `BarDataSet`: `CustomBarDataSet `

I guess your issue lies in your own implementation of that class. Other than that, your code is correct.

**Comment by troy21688** [comment]
I created the CustomBarDataset as the regular BarDataSet's constructor did not allow me to pass in the Array<List> entry. Is there a way to change the constructor? I could see how I am doing it wrong. At the end of the day, I am looking for a simple horizontal bar graph. It will also be dynamic, as I will continue to read poll data from Firebase.

Thanks for your help.

**Comment by PhilJay** [comment]
You need to use `BarEntry` class for `BarDataSet`, not the normal `Entry` class.

**Comment by troy21688** [comment]
Thanks for the prompt response, I will let you know if I have further
questions. Your library is extremely helpful!

On Fri, Feb 12, 2016 at 9:02 AM, Philipp Jahoda <notifications@github.com>
wrote:

> You need to use BarEntry class for BarDataSet, not the normal Entry class.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PhilJay/MPAndroidChart/issues/1470#issuecomment-183363832>
> .
>



-- 
Troy Chuinard, CPA
