### ISSUE TITLE
Data loss in pie chart when using big value

### ISSUE THREAD

**Issue by pramodkrjsr** [PhilJay/MPAndroidChart#1472]
I wanted to show the actual value on pie chart and found that there is a loss/change of data if using big values.
Example:
91751082.35  shown as 91751080
95102983.03 shown as 95102984

It looks that due to using "float" values in the class "Entry".

Any suggestion to solve this issue.

**Comment by PhilJay** [comment]
Yes, that is a floating point issue.
Atm there is not much you can do about it except rounding the value.

I am planning to switch to double values in the future.

**Comment by skh1993** [comment]
@PhilJay I want to know whether 3.01 has solved this problem？I also encountered such a problem
