### ISSUE TITLE
Setting visibility of a linedataset doesn't remove the values drawn on top of the data entrys

### ISSUE THREAD

**Issue by stefanb22** [PhilJay/MPAndroidChart#1475]
Hi,

I'm using a **LineChart** and I'm having an option to toggle visiblity of lines in the chart by using the `lineDataSet.setVisible()` method. However when I set a line to not visible then the values for each entry is still shown (I'm using `lineData.setDrawValues(true)`. 

So there is no line visible but the values are still visible. Is there anyway to also toggle the visibilty of the values for each specific line? I don't want use `lineData.setDrawValues(false)` because that affects the whole chart. And I don't want to remove the dataset either, just make it not visible.

Thanks

**Comment by PhilJay** [comment]
Which library version are you using?

**Comment by stefanb22** [comment]
I'm using v2.2.0.

**Comment by stefanb22** [comment]
Now I feel embarrassed!!!

Don't know how I missed that there is a `setDrawValues()` also in LineDataSet. Just what I needed. I've read the javadoc over and over and still I managed to miss that.

Closing this non-issue.

Thanks for a great work!!!
