### ISSUE TITLE
Adding Module Dependency to Library causes Gradle Error

### ISSUE THREAD

**Issue by JRSoftware92** [PhilJay/MPAndroidChart#1477]
I'm attempting to incorporate this Library into my application and I'm running into some issues trying to build my project. I'm using Android Studios to develop my application, and I have no issues importing the Library as a module. However, once I add a module dependency to my mobile module depending on the Library module, I'm immediately presented a Gradle Sync error stating _Gradle DSL method not found: 'compile()'_

I'm unsure of how to resolve this issue. Is there another way I can reference these module classes, or preferably fix this dependency?

**Comment by PhilJay** [comment]
I am also not sure, this is something for stackoverflow.
