### ISSUE TITLE
Horizontal Bar Chart - Value Color

### ISSUE THREAD

**Issue by jrustonapps** [PhilJay/MPAndroidChart#1478]
Hi,

There appears to be a bug in the horizontal bar chart, relating to the text color of values drawn "above the bar".

I'm using the following lines:

`barChart.setDrawValueAboveBar(true);
barChart.getAxisLeft().setTextColor(Color.RED);
dataSet.setValueTextColor(Color.RED);
barData.setValueTextColor(Color.RED);`

Most of what this does works - it does draw the values to the right of the bars and does set most of the text red, but the values drawn to the right of the bars is a dark grey color. Since it's being drawn on a black background, they're basically unreadable in my application. I've been unable to find out how to change the color of this text.

Note that this does work in line charts and vertical bar charts. It's only horizontal bar charts I've noticed this problem for. I haven't been able to look into it too far yet, but the color of it seems to match the one defined in DataRenderer.java:

`mValuePaint.setColor(Color.rgb(63, 63, 63));`

**Comment by PhilJay** [comment]
Show a screenshot.

Have you set `xAxis.setTextColor(Color.RED)`?

**Comment by AngelOfMors** [comment]
Bug! in HorizontalBarChartRenderer:
public void drawValues(Canvas c)
don't use dataSet.getValueTextColor
