### ISSUE TITLE
BarChart inside Listview

### ISSUE THREAD

**Issue by przelew** [PhilJay/MPAndroidChart#1480]
I have a big problem, 
Im using MPAndroidChart library to draw charts. One chart is inside first record of my Listview - it is initialy empty. After I add more record, chart should redraw with new data but it even dont wont to appear. I have white space.... All references are proper

On the other side, whene I initialize my chart once with data at the begining it appears .... So it seems like not refreshing the Canvas ... Anybody any sugestions ???

**Comment by PhilJay** [comment]
call `notifyDataChanged()` and `invalidate()` on the chart
