### ISSUE TITLE
Touch on pie chart small slices

### ISSUE THREAD

**Issue by lucacastenetto** [PhilJay/MPAndroidChart#1481]
Hi,

thank you for your awesome library. I have a problem with the pie chart when I try to select a slice that is too small to be tapped easily (I always end up selecting the near bigger slice). 

I was thinking about letting the legend items to be selected so that touching on a legend item highlights the corresponding slice on the chart. 

What do you think? Is this possible/doable?

Thanks is advance

**Comment by PhilJay** [comment]
At the moment such a feature is not planned.
