### ISSUE TITLE
BarEntry index and the Array index have to correspond

### ISSUE THREAD

**Issue by Pythonix** [PhilJay/MPAndroidChart#1482]
I use a special DataSet for setting colors.
But if the BarEntry index 

> new BarEntry(val,index)

is not the same as the index that the BarEntry has in the ArrayList<BarEntry>, the last bar decides which color ALL bars should have.
So the BarEntry index and the Array index have to correspond. Otherwise there is a problem.

Hope this is understandable...

**Comment by PhilJay** [comment]
Ok, then make them correspond. You have a custom DataSet after all.

**Comment by Pythonix** [comment]
Yeah I know how to do that of course..
But in my opinion this is not really logical. If the array index is used why use an extra BarEntry index?  And I didn't found it in the docs so I thought it's a bug.
