### ISSUE TITLE
X Axis labels with letters that go below baseline not aligned

### ISSUE THREAD

**Issue by bmcd87** [PhilJay/MPAndroidChart#1484]
![device-2016-02-18-151807](https://cloud.githubusercontent.com/assets/4515769/13156949/256f9c0e-d653-11e5-9664-f544cca4bef8.png)

In the above chart, you can see that labels with the letter "p" or "g" (letters that go below the baseline) are not lined up with the rest of the labels. Maybe they have a different line height and it's throwing off the drawing calculations.

**Comment by JeppeLeth** [comment]
Commit 19a98c2c8a0d1a0e84d89e700ab808995b157c1e seems to have fixed the problem for my project also. Should a pull request be made to merge it into the source?

**Comment by BalalakshmiSadhasivam** [comment]
I too face the same issue

**Comment by tijee** [comment]
Same here!! :)

**Comment by senthilmgs** [comment]
Hi Phil, 
    I need to show all the labels in x-axis on load itself without zooming.  I have upgraded my exisitng chart api to V3.0.0beta1. What's is the equivalent method for **setSpaceBetweenLabels(0)** in the recent updated version. 
![line_charts](https://cloud.githubusercontent.com/assets/1173989/17029720/f5bec6be-4f89-11e6-866b-4854b81f2551.png)

**Comment by nihp** [comment]
I am facing issue with .setSpaceBetweenLabels(0). Any update @senthilmgs 

xAxis.setSpaceBetweenLabels(0);
             ^
  symbol:   method setSpaceBetweenLabels(int)
  location: variable xAxis of type XAxis
