### ISSUE TITLE
Text Size of Values on Chart

### ISSUE THREAD

**Issue by troy21688** [PhilJay/MPAndroidChart#1485]
I am looking to change the size of the value displayed at the end of the bar on the chart. Was not able to find it in the documentation.

![image](https://cloud.githubusercontent.com/assets/16483832/13160826/9c7cf7d6-d65f-11e5-9693-9a0b23c7ad78.png)

Also, is there a way to show percentage as well?

**Comment by PhilJay** [comment]
`xAxis.setTextSize(...)`

**Comment by troy21688** [comment]
Any way to add percentages?

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki

take a look at formatting chapters

**Comment by troy21688** [comment]
I noticed that for larger values, the text gets cut off of the screen. In other words, a value of 4,321 may only display 4,32. What are my options to resolve this issue?

**Comment by troy21688** [comment]
I think I resolved the issue:
yAxisLeft.setAxisMaxValue(10000);
        yAxisRight.setAxisMaxValue(10000);

**Comment by mrleisen** [comment]
> 
> 
> `xAxis.setTextSize(...)` for `XAxis`
> 
> `dataSet.setValueTextSize(...)` for data values

SetValueTextSize not working on PieChart. It does not change value text size. What can i do? Thanks
