### ISSUE TITLE
Riibon chart (strip hart)

### ISSUE THREAD

**Issue by ildar2244** [PhilJay/MPAndroidChart#1486]
Hi, guys. Tell me on the my question. I want to know, how I can to draw this diagramm (show pichture) with our Bar chart? Or any charts. In my diagramm every color as unique type and every part have start data and finish data. Thank you so match.
[https://drive.google.com/file/d/0B4LXSJ-3xMF2RUxubGFsODI4dTg/view?usp=sharing](url)

**Comment by PhilJay** [comment]
Your link does not work.
