### ISSUE TITLE
Wrong dataSetIndex value in ValueFormatter

### ISSUE THREAD

**Issue by Kikju** [PhilJay/MPAndroidChart#1487]
Hello,
I think I discover a bug. 
I'm using multi bar chart. When I implement `setOnChartValueSelectedListener` I got right value of `dataSetIndex`. But when I have custom ValueFormatter, `dataSetIndex ` is incorrect (it is barData index like in Entry and not dataSetIndex). 
Can you help me?

**Comment by PhilJay** [comment]
Are you using a BarChart or horizontal Barchart? I cannot reproduce the issue.

**Comment by Kikju** [comment]
BarChart with multiple dataSets

Kikju

2016-02-19 10:34 GMT+01:00 Philipp Jahoda <notifications@github.com>:

**Comment by PhilJay** [comment]
The Highlight object has the dataset index
