### ISSUE TITLE
No main manifest attribute when using mpandroidchartlibrary-2-1-6.jar

### ISSUE THREAD

**Issue by straesso** [PhilJay/MPAndroidChart#1488]
Hi,

i try to use the MPAndroidChart-Library with Android Studio 1.5.1. I copied the jar-File in the libs-Folder of my project. In dependency - section of build.gradle i have 'compile fileTree(include: ['*.jar'], dir: 'libs')'.

When i want to test my project, i allways get the error message 'no main manifest attribute in c:\....\mpandroidchartlibrary-2-1-6.jar' It seems to be, that i missed one stepp or did something wrong. Please help me.

Regards, Olaf

**Comment by aktaraydin** [comment]
Same problem...
