### ISSUE TITLE
Values Disappear when pinch zoom

### ISSUE THREAD

**Issue by joaopedronardari** [PhilJay/MPAndroidChart#1489]
I implemented a Scatter Chart, with 90 data values. At a first moment the values appear ok, but when user do Zoom (pinch) in Y or X-axis some data disappear.

**Comment by PhilJay** [comment]
What disappears? The scatter shapes? The value labels?
Which version are you using?

**Comment by joaopedronardari** [comment]
The points in chart

**Comment by PhilJay** [comment]
Can you show the code you use to setup your chart and add data?

**Comment by grndvl1** [comment]
I'm actually having the same issue on a combined chart.  No pattern as to why it loses some values.

**Comment by jiangchengzhi** [comment]
@PhilJay Scatter chart start and end data set circles are clipped at the axis,how to solve this problem
