### ISSUE TITLE
piechart item clicked event

### ISSUE THREAD

**Issue by MohammadRezaRahmatzadeh** [PhilJay/MPAndroidChart#1490]
hi
i want an event listener to handle item clicked when user touched one of piechart item
i try this :
pieChart.setClickable(true);
        pieChart.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
             int i = v.getId();
            }
        });
but is does not work 
please help , how can handle item click in piechart and get id or label text of that item to use?
thanks ...

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart

**Comment by MohammadRezaRahmatzadeh** [comment]
very nice , thanks a lot
