### ISSUE TITLE
Artificially Extend X-Axis - Infinite Zoom Out

### ISSUE THREAD

**Issue by Mike278** [PhilJay/MPAndroidChart#1491]
Currently my chart looks like this. The right-most edge of the viewport has the most recent data. Users cannot zoom out further than what the existing data is.
![current](https://cloud.githubusercontent.com/assets/17344144/13187603/1d157dae-d71a-11e5-9c8c-6a98ce12b9e1.png)

I want users to be able to infinitely zoom out of the x-axis. For example, the result of x-pinching the above screenshot would look something like this: (edited in photoshop..)
![desired](https://cloud.githubusercontent.com/assets/17344144/13187604/1d222d24-d71a-11e5-8424-55bb5061ec7d.png)

I've looked through the documentation and haven't been able to find anything. Is this supported at the moment?

**Comment by PhilJay** [comment]
`chart.setDragOffsetX(float offset)`

**Comment by Mike278** [comment]
Thanks for the reply! 

While this is useful, its not what I was looking for. I need a way to be able to zoom out further than the maximum allowable zoom (aka zoom out beyond the available datapoints).

**Comment by PhilJay** [comment]
Okay, in that case, go for the dummy points. There is not really an official way.
