### ISSUE TITLE
Remove Decimals from BarChart Values

### ISSUE THREAD

**Issue by troy21688** [PhilJay/MPAndroidChart#1492]
I have read the documentation on ValueFormatters and am trying to remove the decimals displayed for the BarChart values, but having difficulty:

    public class MyYAxisValueFormatter implements YAxisValueFormatter{

    private DecimalFormat mFormat;

    public MyYAxisValueFormatter(){
        mFormat = new DecimalFormat("###,###,##0");
    }

    @Override
    public String getFormattedValue(float value, YAxis yAxis) {
        return mFormat.format(value);
     }
    }

And then where I initialize the chart:

        MyYAxisValueFormatter f = new MyYAxisValueFormatter();
        yAxisLeft.setValueFormatter(f);
        yAxisRight.setValueFormatter(f);

**Comment by PhilJay** [comment]
This sets a new formatter for the `YAxis`.

You need to use the `ValueFormatter` interface and set it to your data object:

`barData.setValueFormatter(...)`

**Comment by troy21688** [comment]
Worked perfectly! Thanks.
