### ISSUE TITLE
the label of XAxis is clipped

### ISSUE THREAD

**Issue by zhangranran** [PhilJay/MPAndroidChart#1493]
![device-2016-02-20-181447](https://cloud.githubusercontent.com/assets/4494763/13196034/e4e3ad68-d7fd-11e5-949f-3fb29afe47a6.png)
        mChart = (BarChart) findViewById(R.id.chart1);

        mChart.setDescription("");

        mChart.setPinchZoom(true);

        mChart.setDrawBarShadow(false);
        mChart.setDrawGridBackground(true);
        mChart.setGridBackgroundColor(Color.parseColor("#E9E9E9"));

        XAxis xAxis = mChart.getXAxis();
        xAxis.setPosition(XAxisPosition.BOTTOM);
        xAxis.setSpaceBetweenLabels(0);
        xAxis.setDrawGridLines(false);
        xAxis.setLabelRotationAngle(45);
        xAxis.setTextSize(12);
//        xAxis.setYOffset(0);
        xAxis.setTextColor(0x76000000);

        YAxis axisLeft = mChart.getAxisLeft();
        axisLeft.setDrawGridLines(true);
        axisLeft.setTextSize(12);
        axisLeft.setTextColor(0x76000000);
        axisLeft.setAxisMinValue(0);

        YAxis axisRight = mChart.getAxisRight();
        axisRight.setDrawGridLines(false);
        axisRight.setDrawLabels(false);

        mChart.animateY(2500);

        mChart.getLegend().setEnabled(false);

        ArrayList<BarEntry> yVals1 = new ArrayList<BarEntry>();

        for (int i = 0; i < 5; i++) {
            float mult = 10;
            float val1 = (float) (Math.random() * mult) + mult / 3;
            yVals1.add(new BarEntry((int) val1, i));
        }

        ArrayList<String> xVals = new ArrayList<String>();
        for (int i = 1; i < 6; i++) {
            xVals.add(i + "颗星");
        }

        BarDataSet set1 = new BarDataSet(yVals1, "Data Set");
        ArrayList<Integer> colors = new ArrayList<>();
        colors.add(0xFFD84928);
        colors.add(0xFFE29A12);
        colors.add(0xFF3098D8);
        colors.add(0xFF2B9977);
        colors.add(0xFF6B3BA7);
        set1.setColors(colors);
        set1.setValueTextColors(colors);
        set1.setDrawValues(true);
        set1.setBarSpacePercent(70);
        set1.setValueTextSize(12);
        set1.setValueFormatter(new ValueFormatter());

        ArrayList<IBarDataSet> dataSets = new ArrayList<IBarDataSet>();
        dataSets.add(set1);

        BarData data = new BarData(xVals, dataSets);

        mChart.setData(data);
        mChart.getData().setHighlightEnabled(false);

**Comment by PhilJay** [comment]
You can fix that by adding some extra offset `chart.setExtraOffset(...)`

**Comment by zhangranran** [comment]
Perfect!Thank you very much!
