### ISSUE TITLE
Unable to set custom max value for Y axis

### ISSUE THREAD

**Issue by marco-ni** [PhilJay/MPAndroidChart#1494]
Hi, I'm working on an Xcode project and trying to set a custom max value for Y axis. This is the piece of code I'm using:

```
yAxis = lineChart.rightAxis;

// yMax is the value I would like to use as maximum for Y axis
[yAxis setAxisMaximum:yMax];

// these are the dataset of the chart    
LineChartData *data = [[LineChartData alloc] initWithXVals:xVals dataSets:dataSets];
  
// assigning data to chart 
lineChart.data = data;
```
but it does not work. Using _setCustomAxisMax_ instead of _setAxisMaximum_ did not solve the problem. What I'm doing wrong ?

**Comment by PhilJay** [comment]
What do you mean by "it does not work"?

**Comment by marco-ni** [comment]
That the maximum value of Y axis is not set to the value I want ("yMax" in my code). For example, I had a line chart where the highest Y value is 2.1, I try to set the max value of Y axis to 2.5, but when I run the app the Y axis reaches 5.0

**Comment by PhilJay** [comment]
@danielgindi since this is ios, any idea?

**Comment by danielgindi** [comment]
There's a slight api naming difference there - in iOS it was called "custom..." for historical reasons with other similar property names there to confuse - but it will be changed soon as clutter in the library reduces (i.e no more `startAtZero` etc.).

Anyway, `lineChart.rightAxis.customAxisMax = yMax` should work. You can actually see this working in the demos.
If it's not working - you may want to check what is actually the max that you are setting, and that the other axis is synchronized (or disabled).

**Comment by danielgindi** [comment]
Also - please specify the version of Charts that you are working with :-)
