### ISSUE TITLE
Realm - ColumnType invalid

### ISSUE THREAD

**Issue by DropArtDev** [PhilJay/MPAndroidChart#1495]
I want to use a BarChart with my Realm database, but I am getting  _java.lang.IllegalArgumentException: Illegal Argument: ColumnType invalid_ at the fourth line of my code:
```
mBchart = (BarChart) rootView.findViewById(R.id.chart);
mRealm = Realm.getDefaultInstance();
mRealmResults = mRealm.where(Data.class).findAllSorted("dati");
RealmBarDataSet<Data> dataSet = new RealmBarDataSet<>(mRealmResults, "weight", "id");
ArrayList<IBarDataSet> dataSetList = new ArrayList<>();
dataSetList.add(dataSet);
RealmBarData data = new RealmBarData(mRealmResults, "dati", dataSetList);
mBchart.setData(data);
mBchart.invalidate();
```
What am I doing wrong? Thanks for helpful answers.

**Comment by PhilJay** [comment]
Which data types do your weight and id fields have?
Could I see the Data.java file?

**Comment by DropArtDev** [comment]
```
public class Data extends RealmObject{
    @PrimaryKey
    private int id;
    private double weight;
    private long dati;

    public long getDati() {
        return dati;
    }

    public void setDati(long dati) {
        this.dati = dati;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public double getWeight() {
        return weight;
    }

    public void setWeight(double weight) {
        this.weight = weight;
    }
}
```

**Comment by PhilJay** [comment]
Ok, your weight needs to be a float

**Comment by DropArtDev** [comment]
Now I am getting the same exception at the seventh line of my code.

**Comment by PhilJay** [comment]
Is your "dati" a string? If not, thats the reason for the crash

**Comment by DropArtDev** [comment]
If you look at my Data.java you can see that it is a long value.

**Comment by DropArtDev** [comment]
Please help me??

**Comment by AndreiD** [comment]
I'm having the same issue: I have my Model like this:

`
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

public class TheDBModel extends RealmObject {

  @PrimaryKey private long id;
  private int the_value;
  private double lat;
  private double lng;
  private long time;
  private boolean synced = false;

  public TheDBModel() {

  }

  public TheDBModel(int the_value, double lat, double lng, long time, boolean synced) {
    this.the_value = the_value;
    this.lat = lat;
    this.lng = lng;
    this.time = time;
    this.synced = synced;
  }

  public long getId() {
    return id;
  }

  public int getThe_value() {
    return the_value;
  }

  public void setThe_value(int the_value) {
    this.the_value = the_value;
  }

  public double getLat() {
    return lat;
  }`

In the docs it's said: Field types
Realm supports the following field types: boolean, byte, short, int, long, float, double, String, Date and byte[]. The integer types byte, short, int, and long are all mapped to the same type (long actually) within Realm. Moreover, subclasses of RealmObject and RealmList<? extends RealmObject> are supported to model relationships.
