### ISSUE TITLE
Barchart cannot display float numbers but int.

### ISSUE THREAD

**Issue by PanWangJ** [PhilJay/MPAndroidChart#1497]
I'm trying to work with MPAndroidChart to draw a very simple BarChart, and this is my code:

    private void createSaleGraph() {
		ArrayList<BarEntry> entries = new ArrayList<>();
		entries.add(new BarEntry(200f, 0));
		entries.add(new BarEntry(301f, 1));
		entries.add(new BarEntry(112f, 2));
		entries.add(new BarEntry(98f, 3));
		entries.add(new BarEntry(523.5f, 4));
		BarDataSet dataset = new BarDataSet(entries, "Sale Data");

		ArrayList<String> labels = new ArrayList<>();
		labels.add("02.01");
		labels.add("02.02");
		labels.add("02.11");
		labels.add("02.12");
		labels.add("02.17");

		BarData data = new BarData(labels, dataset);
		mBarChart.setDoubleTapToZoomEnabled(false);
		mBarChart.setDescription("");
		mBarChart.setNoDataText("No Data");
		mBarChart.setTouchEnabled(false);
		mBarChart.setClickable(false);
		mBarChart.setData(data);
	}

The fifth date in the DataSet should be 523.5, but the graph always displays 524, don't know how to make it display 523.5 as it should be.

Please help! Thanks!

**Comment by hijamoya** [comment]
face the same issue

**Comment by keith30xi** [comment]
Did you try a custom ValueFormatter that knows how to display floating point numbers? 
See [The-ValueFormatter-interface](https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface)
