### ISSUE TITLE
Where to format long to String, to assign dates to the x-Axis??

### ISSUE THREAD

**Issue by DropArtDev** [PhilJay/MPAndroidChart#1500]
I am opening a new issue now because you aren't answering and closing issues way too fast.
If I have a Realm database with a long value for dates, **how can I then format them in my Activity/Fragment to Strings so that I can assign them to the x-Axis**?
My Code at the moment is this:
```
mBchart = (BarChart) rootView.findViewById(R.id.chart);
mRealm = Realm.getDefaultInstance();
mRealmResults = mRealm.where(Data.class).findAllSorted("dati");
RealmBarDataSet<Data> dataSet = new RealmBarDataSet<>(mRealmResults, "weight", "id");
ArrayList<IBarDataSet> dataSetList = new ArrayList<>();
dataSetList.add(dataSet);
//RealmBarData data = new RealmBarData(mRealmResults, "dati", dataSetList);
mBchart.setData(data);
mBchart.invalidate();
```
But I am obviously getting an error at the line which I commented, because "dati" is a long value and it needs to be a String. Can you provide an example of how to do this please? And please don't close always so fast.

**Comment by PhilJay** [comment]
Worst case scenario, if you are unable to use the `Realm` related classes of this library because of your setup, you need to use the normal classes instead and build them up from your database. The only difference should be a couple more lines of code.

In that way you can transform your long values to dates before adding them to the data classes.

**Comment by esfahanpayamak94** [comment]
هنگامی که جهت کسب و کار خود سایتی را طراحی می کنید احتمال دارد از طراح سایت خود در مورد[ بهینه سازی سایت ](http://www.esfahanpayamak.com/seo)(سئو سایت) اطلاعاتی دریافت نمایید و به اهمیت آن پی ببرید. در اینجا قصد داریم به زبان ساده در مورد بهینه سازی وب سایت توضیحاتی دهیم .
