### ISSUE TITLE
Pie Chart gap

### ISSUE THREAD

**Issue by Raykud** [PhilJay/MPAndroidChart#1501]
I have tried to find a way to remove the gap between values when a pie chart is drawn. Like having pie data without gaps. here is an example of a single data value in the graph and does show the gap.
![graph](https://cloud.githubusercontent.com/assets/4366666/13236732/e2cb1f72-d98b-11e5-91ef-c8060ff4208e.png)
Multiple data with gaps
![screen shot 2016-02-22 at 5 47 04 pm]
(https://cloud.githubusercontent.com/assets/4366666/13236824/92fad11c-d98c-11e5-89eb-44c68c216043.png)

**Comment by PhilJay** [comment]
`pieDataSet.setSliceSpace(...)`
