### ISSUE TITLE
Chart does not draw automatically unless onClick on it

### ISSUE THREAD

**Issue by Sutirth** [PhilJay/MPAndroidChart#1503]
![screenshot_20160223-134827](https://cloud.githubusercontent.com/assets/3212997/13245614/684bd3f0-da34-11e5-89e5-b88125076882.png)

As seen data is loaded but chart is not drawn automatically unless and until someone taps on it

**Comment by PhilJay** [comment]
call `chart.invalidate()` after setting the data.
