### ISSUE TITLE
Dynamic Text Size

### ISSUE THREAD

**Issue by troy21688** [PhilJay/MPAndroidChart#1505]
In android, I use the method below to dynamically set a text size based on the specific device:

                mPollAnswerArrayList.get(i).setTextSize(TypedValue.COMPLEX_UNIT_PX, getResources().getDimension(R.dimen.radio_button_answer_text_size));

However, the xAxis only allows for 1 parameter, a float, to be passed into the setTextSize() method. In other words, this approach is not accepted:

        xAxis.setTextSize(TypedValue.COMPLEX_UNIT_PX, getResources().getDimension(R.dimen.answer_label_text_size));

How can I dynamically set the text size?

**Comment by PhilJay** [comment]
Text size can be set in dp (density pixels), these pixels are already dynamic and will adopt to different screen sizes and resolutions.

**Comment by troy21688** [comment]
I am noticing that on a 10" tablet, I am not able to see the text size. I have the text size set to 12, and it appears fine on handheld devices. However, with a 10" tablet the size does not scale accordingly:

        xAxis.setTextSize(12);

![image](https://cloud.githubusercontent.com/assets/16483832/13299461/e548a032-db00-11e5-8ee9-5e3f60cccb33.png)

**Comment by troy21688** [comment]
Note that the screenshot was from a Google Nexus 10 running Android 4.2.2
