### ISSUE TITLE
Bubble and Scatter dataset are not displayed correctly

### ISSUE THREAD

**Issue by vicmns** [PhilJay/MPAndroidChart#1506]
This is my current issue, I have some data points that are far away from each other (Y-Axis) so the chart only shows the nearest one, ignoring the rest of the data points. It's easy to replicate, just use the following data for the chart:
```java
ArrayList<String> xVals = new ArrayList<String>();
for (int i = 0; i < count; i++) {
   xVals.add((i) + "");
}
ArrayList<BubbleEntry> yVals1 = new ArrayList<BubbleEntry>();
int[] valArray = {1000, 50000, 500000};
int[] valSize = {50000, 25000, 150000};
for (int i = 0; i < 3; i++) {
  yVals1.add(new BubbleEntry(i, valArray[i], valSize[i]));
}
BubbleDataSet set1 = new BubbleDataSet(yVals1, "DS 1");
set1.setColor(ColorTemplate.COLORFUL_COLORS[0], 130);
set1.setDrawValues(true);
ArrayList<IBubbleDataSet> dataSets = new ArrayList<IBubbleDataSet>();
dataSets.add(set1);
BubbleData data = new BubbleData(xVals, dataSets);
```

Using this data set the chart show like this:
![device-2016-02-24-104457](https://cloud.githubusercontent.com/assets/1101060/13293080/dbc4cbe8-dae3-11e5-808a-aa39e02b9193.png)

And when performing the chart animation we can see that the actual scale of the chart is not the best.
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/1101060/13293366/0416fd86-dae5-11e5-9d27-74d07ed2e87b.gif)

Do I have to modify the chart view port to make a better scale or there's an option for that.

Thanks.

**Comment by PhilJay** [comment]
Thank you for your report. It should be fixed, please let me know if it works now.

**Comment by vicmns** [comment]
Perfect! Now is working, thanks @PhilJay
