### ISSUE TITLE
LimitLine Labels can't render multi lines using backslash n ("\n")

### ISSUE THREAD

**Issue by silva96** [PhilJay/MPAndroidChart#1507]
When you do `limitline.setLabel("FOO\nBAR")` it gets rendered as a single line as the picture shows (red one RIGHT_BOTTOM of first red limitline)

![screenshot_20160224-135259](https://cloud.githubusercontent.com/assets/4019924/13293509/b6134684-dafe-11e5-8ca1-1c2a12d66710.png)

**Comment by PhilJay** [comment]
Yes, this is related to the fact that the canvas drawText(...) method ignores linebreaks. I might consider adding such a feature in the future.
