### ISSUE TITLE
Offset Yaxis values when displayed above line chart

### ISSUE THREAD

**Issue by CameronBanga** [PhilJay/MPAndroidChart#1509]
Currently have the following graph.

![screen shot 2016-02-24 at 4 44 11 pm](https://cloud.githubusercontent.com/assets/611354/13303650/21c7f75a-db16-11e5-9a91-489b7498c493.png)

Don't believe from what I've found in the docs, that there is a way to set the margin between the point on a line chart, and where it's associated Value Text appears. Ideally, would want more of a gap between the point on the graph and it's bar, so the values don't intersect the graph when drawing as a bezier curve.

If I'm missing this, any help would be appreciated, other would be an awesome feature to see added in future.

**Comment by PhilJay** [comment]
Unfortunately there is currently no way to change this by default.
You will have to modify the library to achieve that.

**Comment by razon30** [comment]
How to change the library to achieve that?

**Comment by cpienovi** [comment]
There is no need for you to modify the library.
I think you can achieve this by implementing your own LineChartRenderer, override drawValue method and simply add offset.

`public class MyLineChartRenderer extends LineChartRenderer {

    @Px
    private int yOffset;

    public MyLineChartRenderer(int yOffset, LineDataProvider chart, ChartAnimator animator, ViewPortHandler viewPortHandler) {
        super(chart, animator, viewPortHandler);
        this.yOffset = yOffset;
    }

    @Override
    public void drawValue(Canvas c, ValueFormatter formatter, float value, Entry entry, int dataSetIndex, float x, float y, int color) {
        super.drawValue(c, formatter, value, entry, dataSetIndex, x, y + this.yOffset, color);
    }

}`

Then you would set it like this:
`int yValueOffset = getResources().getDimensionPixelSize(R.dimen.chart_y_offset);
lineChart.setRenderer(new MyLineChartRenderer(yValueOffset, lineChart, lineChart.getAnimator(), lineChart.getViewPortHandler()));`

**Comment by odahcam** [comment]
@cpienovi do you have an updated version for 2020?

**Comment by 15574946385** [comment]
> There is no need for you to modify the library. I think you can achieve this by implementing your own LineChartRenderer, override drawValue method and simply add offset.
> 
> ```
> public class MyLineChartRenderer extends LineChartRenderer {
> 
>     @Px
>     private int yOffset;
> 
>     public MyLineChartRenderer(int yOffset, LineDataProvider chart, ChartAnimator animator, ViewPortHandler viewPortHandler) {
>         super(chart, animator, viewPortHandler);
>         this.yOffset = yOffset;
>     }
> 
>     @Override
>     public void drawValue(Canvas c, ValueFormatter formatter, float value, Entry entry, int dataSetIndex, float x, float y, int color) {
>         super.drawValue(c, formatter, value, entry, dataSetIndex, x, y + this.yOffset, color);
>     }
> 
> }
> ```
> 
> Then you would set it like this:
> 
> ```
> int yValueOffset = getResources().getDimensionPixelSize(R.dimen.chart_y_offset);
> lineChart.setRenderer(new MyLineChartRenderer(yValueOffset, lineChart, lineChart.getAnimator(), lineChart.getViewPortHandler()));
> ```my linechart has two datasets，use LineChartRenderer can make them change offects, how can i just change one of them，the second don't need change position
