### ISSUE TITLE
stacked bar chart

### ISSUE THREAD

**Issue by lqzdota** [PhilJay/MPAndroidChart#1513]
when i  set the val1 = 10000f(or bigger) in the example code, the data will be misplaced.

**Comment by PhilJay** [comment]
can you provide a screenshot?

**Comment by lqzdota** [comment]
![example](https://cloud.githubusercontent.com/assets/13333897/13383680/12f7bb24-dec8-11e5-9aec-25a63cbc4ce7.png)
I did not find way to solve this.is there a method to set the area of the column hidden when it is not high  enough. and show it when pull it higher.

**Comment by JayTaoNg** [comment]
Have you solved the problem?

**Comment by lqzdota** [comment]
find the sourcecode that cause of the problem。change it by your own logic。 



At 2018-03-08 17:01:20, "JayTaoNg" <notifications@github.com> wrote:


Have you solved the problem?
