### ISSUE TITLE
How To Change Background in LineChart

### ISSUE THREAD

**Issue by Bekakk** [PhilJay/MPAndroidChart#1518]
hello
i set successfully some values in LineChart.I have one problem.i read your documentations but did not wind solutions
please see my pictures

> http://s16.postimg.org/7orgifj6d/Capture_chart.jpg
how i can colorize this area?i mean the body of the chart
thanks
dear beka

**Comment by PhilJay** [comment]
`lineDataSet.setFillColor(...)` or `lineDataSet.setFillDrawable(...)`

**Comment by Bekakk** [comment]
thank you your attention
I tryed it but not working..i can show you my code. and please,tell what is
a wrong in my code
i hope you can help me
thanks
dear beka

On Sat, Feb 27, 2016 at 3:18 AM, Philipp Jahoda <notifications@github.com>
wrote:

> Closed #1518 <https://github.com/PhilJay/MPAndroidChart/issues/1518>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PhilJay/MPAndroidChart/issues/1518#event-568860363>.
>

 LineChart chart = (LineChart)mView.findViewById(R.id.chart);
        ArrayList<String> xVals = new ArrayList<String>();
        ArrayList<Entry> valsComp1 = new ArrayList<Entry>();
        Entry c1e1;
        for (int i = 0; i < statistic.size(); i++) {
            Float value = Float.parseFloat(statistic.get(i).getVALUE());
            c1e1=new Entry(value,i);
            xVals.add("");
            valsComp1.add(c1e1);
        }
        LineDataSet setComp1 = new LineDataSet(valsComp1, "");
        setComp1.setFillColor(Color.parseColor("#ff0000"));
        setComp1.setCircleColorHole(Color.YELLOW);
        setComp1.setDrawCircles(false);

        setComp1.setAxisDependency(YAxis.AxisDependency.LEFT);
        ArrayList<ILineDataSet> dataSets = new ArrayList<ILineDataSet>();
        dataSets.add(setComp1);
        LineData data = new LineData(xVals, dataSets);
        YAxis left = chart.getAxisLeft();
        left.setDrawLabels(false); // no axis labels
        left.setStartAtZero(false);
        left.setDrawAxisLine(false); // no axis line
        left.setDrawGridLines(false); // no grid lines
        left.setDrawZeroLine(true); // draw a zero line
        chart.getAxisRight().setEnabled(false); // no right axis
        data.setValueTextColor(Color.TRANSPARENT);
        data.setValueFormatter(new MyValueFormatter());

        XAxis xAxis = chart.getXAxis();

        xAxis.setTextSize(0f);
        xAxis.setTextColor(Color.TRANSPARENT);
        xAxis.setDrawAxisLine(true);
        xAxis.setDrawGridLines(false);



        YAxis leftAxis = chart.getAxisLeft();
        YAxis rightAxis = chart.getAxisRight();


        leftAxis.setTextSize(0f);
        leftAxis.setTextColor(Color.TRANSPARENT);
        leftAxis.setDrawAxisLine(true);
        leftAxis.setDrawGridLines(false);


        rightAxis.setTextSize(0f);
        rightAxis.setTextColor(Color.TRANSPARENT);
        rightAxis.setDrawAxisLine(true);
        rightAxis.setDrawGridLines(false);

        chart.setData(data);
        chart.invalidate(); // refresh
