### ISSUE TITLE
Axis Labels and Chart labels do not change when font size increased from System Settings.

### ISSUE THREAD

**Issue by cuddle-puneet** [PhilJay/MPAndroidChart#1519]
Checking the AxisBase and ComponentBase classes, the label size is set to default of 10f which we can override to provide our own font sizes. However, on changing the font size of the entire system from Settings->Display->Font Size -> Huge. All the other labels within the app scale perfectly except for the chart labels. I think it has got something to do with using dp for text sizes instead of sp. Please advice.

**Comment by PhilJay** [comment]
The reason is that the chart is live rendered to a drawing canvas, it does not check system settings for changed font sizes like textfields do.
