### ISSUE TITLE
[Question] How to draw x, y axises, not draw all grid

### ISSUE THREAD

**Issue by NtcWai** [PhilJay/MPAndroidChart#152]
I want to create a chart like this:
<img src="http://www.upsieutoc.com/images/2014/10/13/ScreenShot2014-10-13at1.28.48PM.png" border="0">
But now :
<img src="http://www.upsieutoc.com/images/2014/10/13/ScreenShot2014-10-13at1.58.03PM.png" border="0">
I have some question: 
1. How to hide DataSetLabel at
LineDataSet set1 = new LineDataSet(yVals, "DataSetLabel");
--> I have just found: mLineChart.setDrawLegend(false);
2. How to draw and set color only 2 coordinate axises, not draw all grid ?
3. How to display apart of xValues, assume displaying from 25 to 40, and then can scroll to left to showing the remaining from 25 to 0 ?
i'm appreciated for your help.

**Comment by vineetjain495** [comment]
how this black color came as background...?
