### ISSUE TITLE
SetColor() - Wrong color

### ISSUE THREAD

**Issue by DropArtDev** [PhilJay/MPAndroidChart#1522]
I am setting my color like this:
``barDataSet.setColor(R.color.colorPrimaryDark);``
But I am getting the wrong color:
![colors](https://cloud.githubusercontent.com/assets/17216196/13362086/b5271f3c-dcc2-11e5-9cad-ce23e7fd838e.png)
If I am doing something like this:
``barDataSet.setColor(Color.RED);``
it's working correctly.

**Comment by PhilJay** [comment]
Use getResources().getColor(...)

**Comment by MarkOSullivan94** [comment]
@PhilJay's answer is deprecated, use this instead:

`ContextCompat.getColor(getContext(), R.color.<color>)`
