### ISSUE TITLE
is there a way to create a date scale for the x axis?

### ISSUE THREAD

**Issue by skrite** [PhilJay/MPAndroidChart#1523]
Greetings. I was wondering if this feature has been added yet? I have seen a couple of requests for it here. I need the XAxis of my chart to represent time of events instead of all of the data points being spaced equally across the chart.

thanks

**Comment by PhilJay** [comment]
Not yet available, but one of the next things on my todo list.

**Comment by HeinrichReimer** [comment]
I need this feature too :+1:

**Comment by HeinrichReimer** [comment]
Shouldn't you keep this issue open until it is implemented, @PhilJay?

**Comment by niteshgoel** [comment]
+1
