### ISSUE TITLE
Can we do this?

### ISSUE THREAD

**Issue by DropArtDev** [PhilJay/MPAndroidChart#1525]
How can we achieve different background colors like in the picture?
![e6f4c67c-d58e-11e4-9a94-f909afc19e36](https://cloud.githubusercontent.com/assets/17216196/13378760/05dab4bc-de11-11e5-95f8-56470089aeaf.png)

**Comment by PhilJay** [comment]
Yes, partly.

You cannot define a range that should be green and a range of values that should be red, but you can add a drawable background like the one shown above to your chart.

**Comment by DropArtDev** [comment]
@PhilJay Can you add an easy method like the LimitLines to the library which does this? Would be much easier. Thanks

**Comment by saiidabs** [comment]
@DropArtDev  , im having the same problem , have you found a solution to it?
