### ISSUE TITLE
leftAxis.setDrawLimitLinesBehindData(false); doesn't affect chart circles

### ISSUE THREAD

**Issue by IRuth** [PhilJay/MPAndroidChart#1529]
First of all, thanks for an awesome chart library. It has saved me a lot of development time.

`leftAxis.setDrawLimitLinesBehindData(false);` doesn't seem to affect the chart's circles. I am wondering if there's anything I need to set for the limit line to be drawn in front of the chart's circles.

Also, is there a way to decrease the thickness of the chart circle's circumference line when increasing the circle's radius?

Thanks.

![screenshot_20160301-102142](https://cloud.githubusercontent.com/assets/5240961/13433342/6af06664-df9f-11e5-8f1a-a4ee43ecc8fb.png)

**Comment by coolscott** [comment]
Ans to Q1: please take a look for Z-Order issue @ BarLineChartBase::onDraw(Canvas canvas)
Ans to Q2: please take a look for circle style @ LineChartRenderer::drawCircles(Canvas c)
and you may see LineDataSet.getCircleRadius() mapping to LineDataSet.setCircleRadius(float size).

**Comment by IRuth** [comment]
Thanks for the pointer @coolscott. I was able to resolve my second question [here](https://github.com/WW-Digital/MPAndroidChart/commit/54737b2b6855ac761595b72c0ff5e7dac4e6aecc).

**Comment by IRuth** [comment]
I resolved my first question [here](https://github.com/WW-Digital/MPAndroidChart/commit/dd5c635b59bdca536c942dfa259dfb5da83cfc0f).

**Comment by coolscott** [comment]
+1:
