### ISSUE TITLE
setValueTextColors() not working as expected when viewport scrolled

### ISSUE THREAD

**Issue by rnithya77** [PhilJay/MPAndroidChart#1531]
I first of all want to thank you for this incredible piece of software! In the linechart am setting valueTextColors while setting the corresponding circleColors as well, so for positive y values I choose to display green and negative I choose red. I set my visibleXRangeMaximum to 10f to scroll through the stuff on xAxis. While am on the first 10, the circles and the labels shows up in the right colors. But when I do a right scroll, the circle colors have caught up to their correct values, but not the labels - they are all mixed up. Appreciate your time!

**Comment by rituapplocum** [comment]
Is It resolved?
Facing the same issue 
Label colors change on horizontal scroll
