### ISSUE TITLE
App crashes while setting color to chart

### ISSUE THREAD

**Issue by Sutirth** [PhilJay/MPAndroidChart#1533]
BarDataSet set1 = new BarDataSet(yVals1, "StepCount");
        set1.setColor(getResources().getColor(R.color.step_count_text));
        set1.setBarSpacePercent(35f);

Crashlytics and android error log shows error at setColor

**Comment by PhilJay** [comment]
Whats the exception?

**Comment by Sutirth** [comment]
It occurs intermediate I will post  a crash log once I encounter it again till then keep it open

**Comment by Sutirth** [comment]
03-08 14:15:28.060 21227-21227/com.workoutguru.workoutcash E/AndroidRuntime: FATAL EXCEPTION: main
03-08 14:15:28.060 21227-21227/com.workoutguru.workoutcash E/AndroidRuntime: Process: com.workoutguru.workoutcash, PID: 21227
03-08 14:15:28.060 21227-21227/com.workoutguru.workoutcash E/AndroidRuntime: java.lang.IllegalStateException: Fragment SweatPoints_Previous_Fragment{424ba110} not attached to Activity
03-08 14:15:28.060 21227-21227/com.workoutguru.workoutcash E/AndroidRuntime:     at android.support.v4.app.Fragment.getResources(Fragment.java:639)
03-08 14:15:28.060 21227-21227/com.workoutguru.workoutcash E/AndroidRuntime:     at com.workoutguru.workoutcash.SweatPoints_Previous_Fragment.fetchFitnessDataFromDatabase(SweatPoints_Previous_Fragment.java:460)
03-08 14:15:28.060 21227-21227/com.workoutguru.workoutcash E/AndroidRuntime:     at com.workoutguru.workoutcash.SweatPoints_Previous_Fragment.access$200(SweatPoints_Previous_Fragment.java:65)
03-08 14:15:28.060 21227-21227/com.workoutguru.workoutcash E/AndroidRuntime:     at com.workoutguru.workoutcash.SweatPoints_Previous_Fragment$2$2.onSuccess(SweatPoints_Previous_Fragment.java:340)
03-08 14:15:28.060 21227-21227/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.Realm$1$1.run(Realm.java:1112)
03-08 14:15:28.060 21227-21227/com.workoutguru.workoutcash E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733)
03-08 14:15:28.060 21227-21227/com.workoutguru.workoutcash E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-08 14:15:28.060 21227-21227/com.workoutguru.workoutcash E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:146)
03-08 14:15:28.060 21227-21227/com.workoutguru.workoutcash E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5602)
03-08 14:15:28.060 21227-21227/com.workoutguru.workoutcash E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
03-08 14:15:28.060 21227-21227/com.workoutguru.workoutcash E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
03-08 14:15:28.060 21227-21227/com.workoutguru.workoutcash E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
03-08 14:15:28.060 21227-21227/com.workoutguru.workoutcash E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
03-08 14:15:28.060 21227-21227/com.workoutguru.workoutcash E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

**Comment by Sutirth** [comment]
BarDataSet set1 = new BarDataSet(yVals1, "StepCount");
        set1.setColor(getResources().getColor(R.color.step_count_text));
        set1.setBarSpacePercent(35f);

logcat shows at setColor cc @PhilJay

**Comment by PhilJay** [comment]
Which android version are you running?

**Comment by Sutirth** [comment]
@PhilJay  This one specifically crashed on 4.4 kitkat
