### ISSUE TITLE
Issue with two bar data sets

### ISSUE THREAD

**Issue by igorbljahhin** [PhilJay/MPAndroidChart#1537]
Hello,

I am trying to display two bars, one above the other, but negative bar is shifted to the right, although it is related to same x index. See screenshot (https://www.dropbox.com/s/o4ep7yewe7h28jw/2016-03-02%2023_59_15-.png?dl=0).

The simplified source is following:

`        final CombinedChart chart = (CombinedChart) findViewById(R.id.chart);
        chart.setAutoScaleMinMaxEnabled(false);
        chart.animateY(1500);
        chart.getLegend().setEnabled(false);
        chart.getAxisRight().setDrawLabels(false);
        chart.setDescription("");
        chart.setDrawOrder(new CombinedChart.DrawOrder[]{CombinedChart.DrawOrder.BAR, CombinedChart.DrawOrder.LINE});

        final YAxis leftYAxis = chart.getAxisLeft();
        leftYAxis.setAxisMaxValue(Constants.MAX_RATE_VALUE);
        leftYAxis.setAxisMinValue(Constants.MIN_RATE_VALUE);
        leftYAxis.setValueFormatter(new YAxisValueFormatter() {

            @Override
            public String getFormattedValue(float value, YAxis yAxis) {
                return "" + (int) value;
            }
        });

        leftYAxis.setDrawTopYLabelEntry(true);
        leftYAxis.setLabelCount(7, true);

        final YAxis rightYAxis = chart.getAxisRight();
        rightYAxis.setDrawGridLines(false);

        final XAxis xAxis = chart.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setSpaceBetweenLabels(0);
        xAxis.setDrawGridLines(true);

            final List<String> labels = new ArrayList<>();
            labels.add("2/29/16");
            labels.add("3/1/16");
            labels.add("3/2/16");
            
            final List<Entry> ratesEntries = new ArrayList<>();
            ratesEntries.add(new Entry(0, 0));
            ratesEntries.add(new Entry(0, 1));
            ratesEntries.add(new Entry(0, 2));
            
            final List<ILineDataSet> ratesDatasets = new ArrayList<>();
            ratesDatasets.add(createLibidoDataset(ratesEntries));

            final List<BarEntry> periodEntriesAbove = new ArrayList<>();
            periodEntriesAbove.add(new BarEntry(3, 0));
            
            final List<BarEntry> periodEntriesBelow = new ArrayList<>();
            periodEntriesBelow.add(new BarEntry(-3, 0));
            
            final BarData periodBarData = new BarData(labels);

            BarDataSet periodDataset;

            periodDataset = new BarDataSet(periodEntriesAbove, null);
            periodDataset.setDrawValues(false);
            periodDataset.setBarSpacePercent(0);
            periodBarData.addDataSet(periodDataset);

            periodDataset = new BarDataSet(periodEntriesBelow, null);
            periodDataset.setDrawValues(false);
            periodDataset.setBarSpacePercent(0);
            periodBarData.addDataSet(periodDataset);

            final CombinedData data = new CombinedData(labels);
            data.setData(periodBarData);
            data.setData(new LineData(labels, ratesDatasets));

            chart.setData(data);`

What I am doing wrong?

**Comment by PhilJay** [comment]
Use stacked bars.

`new BarEntry(new float[] { -5, 5 }, xIndex)`

In that way they will be on top of each other.

**Comment by igorbljahhin** [comment]
Thanks a lot!
