### ISSUE TITLE
IndexOutOfBound Exception by DataSet.getEntryForIndex

### ISSUE THREAD

**Issue by ixig** [PhilJay/MPAndroidChart#1541]
100% reproducible in your example app, by 

1. adding the following two lines to 
RealTimeChartActivity.java:creatSet():
set.setDrawCubic(true);
set.setDrawFilled(true);

2. Select the Realtime Chart, then select Fast Feed, and while feeding is ongoing, pinch out (zoom in) 

---

[RealTimeChartCrash.txt](https://github.com/PhilJay/MPAndroidChart/files/156658/RealTimeChartCrash.txt)

at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:250)
at com.github.mikephil.charting.renderer.LineChartRenderer.drawCubicFill(LineChartRenderer.java:260)
at com.github.mikephil.charting.renderer.LineChartRenderer.drawCubic(LineChartRenderer.java:232)
at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:125)
at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:108)

**Comment by vit001** [comment]
See issue 1539 for bugfix.

**Comment by ixig** [comment]
@vit001 - Thanks but that didn't fix it for me. My exception stack-trace shows it being the fault of drawCubicFill (not CombinedHighlighter). I confimed by disabling cubic fill (.setDrawCubic(false)) -- problem did not occur.

**Comment by DropArtDev** [comment]
Same for me. @PhilJay please fix this.

**Comment by despDev** [comment]
Exact same thing. @ixig Thanks for the setDrawCubic(false)

**Comment by PhilJay** [comment]
I cannot reproduce the issue with the steps described above.
Some fixes have already been performed regarding this issue, please be aware that they might not be released yet since the current master branch is around 45 commits ahead of the last release.

**Comment by PaoloRotolo** [comment]
I can reproduce this. My app crashes when trying to zoom in if setDrawCubic is true. Can you please release a fix ASAP?
