### ISSUE TITLE
changing the starting position of line chart 

### ISSUE THREAD

**Issue by shweta1bhandari** [PhilJay/MPAndroidChart#1542]
![line_chart](https://cloud.githubusercontent.com/assets/14952151/13495107/b6581ef0-e16e-11e5-95c0-5dfa19a68372.png)

In this Line Chart  their is only one zero position, from where this chart starts drawing, but i want another zero position at x axis(at some distance of original zero position), so that new Line chart starts from this position ,after taking some distance from y axis.

**Comment by PhilJay** [comment]
Choose a different x-index

**Comment by ttdat89** [comment]
Hi PhilJay, I changed different x-index (a) for my starting points, but x-axis also changed its starting position to that point.x (a)

**Comment by sharmaDaemon** [comment]
I too have this problem (Distance between two points in the x axis is inconsistent)
When there are 3 entries, graph will cover all the screen space and one entry is at the first position, one is at last and one is at center

when there are 10 entries, the graph will cover all the screen space and will print the x axis with some distance between two entries

If anybody can help us, please help...
