### ISSUE TITLE
PieChart disappear if only has one x value

### ISSUE THREAD

**Issue by maniacs-engineerica** [PhilJay/MPAndroidChart#1543]
![empty chart](https://cloud.githubusercontent.com/assets/15658731/13501661/4d53155e-e146-11e5-9cac-ca53b58c5cfe.jpg)

**Comment by seba123neo** [comment]
same ploblem for me, I want to show the graphic with just one value of 100% and the graphic disappears.

**Comment by PhilJay** [comment]
Yep, this is a known issue and already fixed.

**Comment by seba123neo** [comment]
I have version 2.2.3 and it is not fixed

**Comment by maniacs-engineerica** [comment]
Hey Phil, we have the last version and it still happens.
When was it fixed?
Thanks for your job, you've developed a great library.

**Comment by seba123neo** [comment]
I need to work with a single value, I have to show a single value when the graph reaches 100% (full)

Thanks.
