### ISSUE TITLE
Change Horizontal Bar Chart Bars Value Label

### ISSUE THREAD

**Issue by JavierCruz** [PhilJay/MPAndroidChart#1547]
Hello, I need to change the values of the Bars in my Horizontal Bar Chart adding a "%" at the end, as shows the picture:
<a href='http://postimg.org/image/eaqovggez/full/' target='_blank'><img src='http://s17.postimg.org/89szydtsv/grafica_question.png' border='0' alt="grafica question" /></a><br />

I'd read all answers here and the wiki documentation, but I couldn´t find a solution.
There's any way to do it?

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface

**Comment by vigneshdharma** [comment]
Hi PhilJay,
Is it possible to set the bar value in two lines usig ValueFormatter?
