### ISSUE TITLE
LineDataSet set/getCircleRadius() Bug!

### ISSUE THREAD

**Issue by XxGoliathusxX** [PhilJay/MPAndroidChart#1548]
Hello,
I wanted to change the circleRadius of my LineDataSets so I sat it via lds.setCircleRadius(12f);.
The default value lds.getCircleRadius() is 8.0f. Setting it to 12f it got huge so I have investigated a bit:
```
 System.out.println("Radius " + lds.getCircleRadius());  //8.0
 lds.setCircleRadius(8.0f); //Setting to default just for test
 System.out.println("Radius " + lds.getCircleRadius());  //24.0
```

So there must be something wrong...

So I sat the value to 4.0f to get the 12.0f i wanted.

**Comment by PhilJay** [comment]
Thats because the library internally converts to density pixels at runtime.

**Comment by tutysathish** [comment]
Hello,
I'm also facing the same problem, for example.
I have loaded the chart in recycler view.
When I populate the chart for the first time it looks good,
I mean circleRadius is 15f.
But, If I navigate to another fragment and comes back to this fragment at the second time it doesn't look good.
I mean now the circleRadius is 45f. (Even I was creating new object for the LineDataSet every time)

LineDataSet setComp1 = new LineDataSet(valuesComp1, mChartName);
setComp1.setCircleRadius(15f); //Outer circle radius
setComp1.setCircleHoleRadius(10f); //Inner circle radius
setComp1.setValueTextSize(30f);
setComp1.setLineWidth(5f);

ArrayList<ILineDataSet> dataSets = new ArrayList<>();
dataSets.add(setComp1);

LineData mLineData = new LineData(listOfDates, dataSets);
mLineData.notifyDataChanged();

Please help me to solve this out

**Comment by uburoiubu** [comment]
@tutysathish, did you find the solution?
