### ISSUE TITLE
Translation is corrupted while applying zoom limit.

### ISSUE THREAD

**Issue by vit001** [PhilJay/MPAndroidChart#1551]
Translation is corrupted while applying zoom limit. I set viewport limits using
`mChart.getViewPortHandler().setMinimumScaleX( 20 );        mChart.getViewPortHandler().setMaximumScaleX( 500 );
`
when zooming
`mChart.zoom( mChart.isScaleXEnabled() ? 1.4f : 1f, mChart.isScaleYEnabled() ? 1.4f : 1f, trans.x, trans.y );`
new matrix is computed, which includes new zoom and new translation.
Subsequently. zoom limits are applied in ViewPortHandler.limitTransAndScale. However, if the scale is clipped here to the zoom limit, the translation is not adjusted for the clip. The result is extreme translation jitter when pinch-zooming in beyond a limit.

The fix is to either clip the scale before computing new matrix, or to adjust translation after clipping scale.

**Comment by vit001** [comment]
Thank you for the fix. It is an improvement but it does not fully resolve the problem. The remaining issue happens when the X zoom limit is hit before the Y zoom limit (or vice versa). In that case pinch-zoom will still happen, scale clipping of X will happen, and translation will get corrupted.

**Comment by vit001** [comment]
Also, this issue still persists when calling BarLineChartBase.zoom( float scaleX, float scaleY, float x, float y ), or BarLineChartBase.zoomAndCenterAnimated( float scaleX, float scaleY, float xValue, float yValue, AxisDependency axis, long duration ). Maybe the best way to handle this is to adjust the translation properly in ViewPortHandler.limitTransAndScale( Matrix matrix, RectF content )?

**Comment by dpeters1** [comment]
I believe I'm having the same issue when using LineChart.zoomAndCenterAnimated(...) Strangely, the animation works sometimes, but other times it zooms without any animation.
