### ISSUE TITLE
RadarChart - web doesn't appear right on a samsung tablet

### ISSUE THREAD

**Issue by 4bernard** [PhilJay/MPAndroidChart#1552]
I'm running android 4.4.2 and mpandroidchart 2-1-6. I see some lines missing:

![rad2](https://cloud.githubusercontent.com/assets/17674971/13548492/0cdcc8aa-e2f2-11e5-958b-0bbfe9c2b631.jpg)

it's running fine on an STC phone or when I rotate the web.
Any ideas what could be the issue?

`public class Radar_Chart extends Fragment {

    public Radar_Chart() {
        // Required empty public constructor
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.radar_chart, container, false);
    }

    private RadarChart mChart;
    private Typeface tf;

    @Override
    public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        getActivity().getApplicationContext();

        RadarChart chart = (RadarChart) getActivity().findViewById(R.id.radar_chart);

        ArrayList<Entry> entries = new ArrayList<>();
        entries.add(new Entry(4f, 0));
        entries.add(new Entry(5f, 1));
        entries.add(new Entry(2f, 2));
        entries.add(new Entry(7f, 3));
        entries.add(new Entry(6f, 4));
        entries.add(new Entry(5f, 5));

        ArrayList<Entry> entries2 = new ArrayList<>();
        entries2.add(new Entry(1f, 0));
        entries2.add(new Entry(5f, 1));
        entries2.add(new Entry(6f, 2));
        entries2.add(new Entry(3f, 3));
        entries2.add(new Entry(4f, 4));
        entries2.add(new Entry(8f, 5));

        RadarDataSet dataset_comp1 = new RadarDataSet(entries, "Company1");

        RadarDataSet dataset_comp2 = new RadarDataSet(entries2, "Company2");

        dataset_comp1.setColor(Color.CYAN);
        dataset_comp1.setDrawFilled(true);

        dataset_comp2.setColor(Color.RED);
        dataset_comp2.setDrawFilled(true);

        ArrayList<RadarDataSet> dataSets = new ArrayList<RadarDataSet>();
        dataSets.add(dataset_comp1);
        dataSets.add(dataset_comp2);

        ArrayList<String> labels = new ArrayList<String>();
        labels.add("Communication");
        labels.add("Technical Knowledge");
        labels.add("Team Player");
        labels.add("Meeting Deadlines");
        labels.add("Problem Solving");
        labels.add("Punctuality");

        RadarData data = new RadarData(labels, dataSets);
        chart.setData(data);
        String description = "Employee-Skill Analysis (scale of 1-10), 10 being the highest";
        chart.setDescription(description);
        chart.setWebLineWidthInner(0.5f);
        chart.setDescriptionColor(Color.RED);

        //chart.setSkipWebLineCount(10);
        chart.invalidate();
        chart.animate();
     //   Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
     //   setSupportActionBar(toolbar);

    }

}
`

**Comment by PhilJay** [comment]
That's because you set the line width too thin so that it does not always render correctly. Increase it a bit to fix this.

**Comment by 4bernard** [comment]
:) thanks!
