### ISSUE TITLE
PieChart disappear if only has one x value (#1543)

### ISSUE THREAD

**Issue by maniacs-engineerica** [PhilJay/MPAndroidChart#1554]
Hey Phill, sorry but I am seeing this bug in v2.3.3 (last version).
Are you sure you fixed it?

**Comment by Brianvdb** [comment]
I am also having this issue.

**Comment by Lianghonglu** [comment]
I am also having this issue: not only one x value will cause this , if there is three Y but only one Y is not  0 , the chart will also disappear

**Comment by WangMingJue** [comment]
I am also having this issue.

**Comment by PhilJay** [comment]
This will be fixed in next release.
