### ISSUE TITLE
Ensuring Optimal Realtime Performance

### ISSUE THREAD

**Issue by troy21688** [PhilJay/MPAndroidChart#1555]
I am creating a voting application, and I am expecting users to vote on topics almost every minute.

I have 2 methods: 1 to initially create the chart .assignInitialBarGraphResults() and another to update the chart .updatePollResultsAnswersDynamically().

While I have been able to get my Android application to work exactly as desired, I wanted to make sure that I had my code correct. 

2 primary concerns:

1. I am creating a new image that is being stored on the client's device every time new data in the chart is updated (when updatePollResultsAnswersDynamically() is called).

2. I am not using cache correctly and am also using a significant amount of a client's data. In other words, my method will eat up a client's data and they will not be able to use my app unless they are on a WiFi connection.

Here is my code:

     private void assignInitialBarGraphResults(DataSnapshot dataSnapshot) {

        mPollResults.setDescription("");
        //Pollvalues get added here
        pollResultChartValues = new ArrayList<BarEntry>();
        int pollAnswerCount = (int) dataSnapshot.child(POLL_ANSWERS_LABEL).getChildrenCount();

        for (int i = 0; i < pollAnswerCount; i++) {
            Long chartLongResultvalue = (Long)         dataSnapshot.child(POLL_ANSWERS_LABEL).child(String.valueOf(i +       1)).child(VOTE_COUNT_LABEL).getValue();
            float chartFloatResultvalue = chartLongResultvalue.floatValue();
            pollResultChartValues.add(new BarEntry(chartFloatResultvalue, i));
        }

        data = new BarDataSet(pollResultChartValues, "Vote Results");

        ArrayList<Integer> barColors = new ArrayList<>();
        barColors.add(ContextCompat.getColor(getActivity().getApplicationContext(), R.color.bar_one));
        barColors.add(ContextCompat.getColor(getActivity().getApplicationContext(), R.color.bar_two));
        barColors.add(ContextCompat.getColor(getActivity().getApplicationContext(), R.color.bar_three));
        barColors.add(ContextCompat.getColor(getActivity().getApplicationContext(), R.color.bar_four));
        barColors.add(ContextCompat.getColor(getActivity().getApplicationContext(), R.color.bar_five));
        data.setColors(barColors);

        data.setAxisDependency(YAxis.AxisDependency.LEFT);
        MyDataValueFormatter f = new MyDataValueFormatter();
        data.setValueFormatter(f);

        XAxis xAxis = mPollResults.getXAxis();
        xAxis.setDrawGridLines(false);
        xAxis.setDrawAxisLine(false);
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        if ((getResources().getConfiguration().screenLayout &       Configuration.SCREENLAYOUT_SIZE_MASK) == Configuration.SCREENLAYOUT_SIZE_XLARGE) {
            xAxis.setTextSize(20);
        } else if ((getResources().getConfiguration().screenLayout &      Configuration.SCREENLAYOUT_SIZE_MASK) == Configuration.SCREENLAYOUT_SIZE_LARGE) {
            xAxis.setTextSize(16);
        }

        YAxis yAxisLeft = mPollResults.getAxisLeft();
        yAxisLeft.setDrawGridLines(false);
        yAxisLeft.setEnabled(false);
        YAxis yAxisRight = mPollResults.getAxisRight();
        yAxisRight.setDrawGridLines(false);
        yAxisRight.setEnabled(false);

        Legend legend = mPollResults.getLegend();
        legend.setEnabled(false);

        dataSets = new ArrayList<IBarDataSet>();
        dataSets.add(data);

        //Poll Answer Options get added here
        ArrayList<String> yVals = new ArrayList<String>();
        for (int x = 0; x < pollAnswerCount; x++) {
            String pollResult = dataSnapshot.child(POLL_ANSWERS_LABEL).child(String.valueOf(x + 1)).child("Answer").getValue().toString();
            yVals.add(x, pollResult);
        }

        BarData testBarData = new BarData(yVals, dataSets);
                     testBarData.setValueTextSize(getResources().getDimension(R.dimen.answer_value_label_text_size));
        if ((getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == Configuration.SCREENLAYOUT_SIZE_XLARGE) {
            testBarData.setValueTextSize(22);
        } else if ((getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == Configuration.SCREENLAYOUT_SIZE_LARGE) {
            testBarData.setValueTextSize(14);
        } else if ((getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == Configuration.SCREENLAYOUT_SIZE_NORMAL) {
            testBarData.setValueTextSize(12);
        } else if ((getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == Configuration.SCREENLAYOUT_SIZE_SMALL) {
            testBarData.setValueTextSize(12);
        }

        mPollResults.getXAxis().setLabelRotationAngle(-15);
        mPollResults.getXAxis().setSpaceBetweenLabels(5);
        mPollResults.setTouchEnabled(false);
        mPollResults.setPinchZoom(false);
        mPollResults.setData(testBarData);
        mPollResults.invalidate();

    }

Update Poll Results Dynamically

     private void updatePollResultAnswersDynamically(int numberOfAnswers, DataSnapshot dataSnapshot) {

        mPollResults.clearValues();

        pollResultChartValues = new ArrayList<BarEntry>();

        for (int i = 0; i < numberOfAnswers; i++) {
            Long chartLongResultvalue = (Long) dataSnapshot.child(POLL_ANSWERS_LABEL).child(String.valueOf(i + 1)).child(VOTE_COUNT_LABEL).getValue();
            float chartFloatResultvalue = chartLongResultvalue.floatValue();
            pollResultChartValues.add(new BarEntry(chartFloatResultvalue, i));
        }

        data = new BarDataSet(pollResultChartValues, "Poll Results");

        ArrayList<Integer> barColors = new ArrayList<>();
        barColors.add(ContextCompat.getColor(getActivity().getApplicationContext(), R.color.bar_one));
        barColors.add(ContextCompat.getColor(getActivity().getApplicationContext(), R.color.bar_two));
        barColors.add(ContextCompat.getColor(getActivity().getApplicationContext(), R.color.bar_three));
        barColors.add(ContextCompat.getColor(getActivity().getApplicationContext(), R.color.bar_four));
        barColors.add(ContextCompat.getColor(getActivity().getApplicationContext(), R.color.bar_five));
        data.setColors(barColors);

        data.setAxisDependency(YAxis.AxisDependency.LEFT);
        MyDataValueFormatter f = new MyDataValueFormatter();
        data.setValueFormatter(f);

        //xAxis is a inverted yAxis since the graph is horizontal
        XAxis xAxis = mPollResults.getXAxis();
        xAxis.setDrawGridLines(false);
        xAxis.setDrawAxisLine(false);
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        if ((getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == Configuration.SCREENLAYOUT_SIZE_XLARGE) {
            xAxis.setTextSize(20);
        } else if ((getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == Configuration.SCREENLAYOUT_SIZE_LARGE) {
            xAxis.setTextSize(16);
        }

        //yAxis is an inverted xAxis since the graph is horizontal
        YAxis yAxisLeft = mPollResults.getAxisLeft();
        yAxisLeft.setDrawGridLines(false);
        yAxisLeft.setEnabled(false);
        YAxis yAxisRight = mPollResults.getAxisRight();
        yAxisRight.setDrawGridLines(false);
        yAxisRight.setEnabled(false);

        Legend legend = mPollResults.getLegend();
        legend.setEnabled(false);

        //TODO: This figure needs to be dynamic and needs to adjust based on the number of users in the application
        //TODO: Or does it? Right now, it scales without it

        dataSets = new ArrayList<IBarDataSet>();

        dataSets.add(data);

        //Poll Answer Options get added here
        ArrayList<String> yVals = new ArrayList<String>();
        for (int x = 0; x < numberOfAnswers; x++) {
            String pollResult = dataSnapshot.child(POLL_ANSWERS_LABEL).child(String.valueOf(x + 1)).child("Answer").getValue().toString();
            yVals.add(x, pollResult);
        }

        BarData testBarData = new BarData(yVals, dataSets);
        //TODO: Fix all text sizes using this method
        if ((getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == Configuration.SCREENLAYOUT_SIZE_XLARGE) {
            testBarData.setValueTextSize(22);
        } else if ((getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == Configuration.SCREENLAYOUT_SIZE_LARGE) {
            testBarData.setValueTextSize(14);
        } else if ((getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == Configuration.SCREENLAYOUT_SIZE_NORMAL) {
            testBarData.setValueTextSize(12);
        } else if ((getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == Configuration.SCREENLAYOUT_SIZE_SMALL) {
            testBarData.setValueTextSize(12);
        }

        mPollResults.getXAxis().setLabelRotationAngle(-15);
        mPollResults.getXAxis().setSpaceBetweenLabels(5);
        mPollResults.setTouchEnabled(false);
        mPollResults.setPinchZoom(false);
        mPollResults.setData(testBarData);
        data.notifyDataSetChanged();
        mPollResults.notifyDataSetChanged();
        mPollResults.invalidate();
    }

**Comment by vit001** [comment]
It is not clear to me what bug in MPAndroidLib you are reporting here.

**Comment by troy21688** [comment]
I am essentially trying to figure out where the images are saved on the device so that I can delete them accordingly when a chart becomes outdated. My chart updates every 5 seconds, thus deeming the chart from 5 seconds ago meaningless.

**Comment by vit001** [comment]
Why would you be saving images of the chart every 5 seconds? What's the point? Or what images are you refering to ??

**Comment by troy21688** [comment]
I am assuming that the chart is an actual image on the client's device.
Every time a user votes, a new chart is generated since the bars update,
thus a new image is generated. That is my logic and what I am referring to
when I mention images.

On Tue, Mar 15, 2016 at 10:38 PM, Vit Hradecky <notifications@github.com>
wrote:

> Why would you be saving images of the chart every 5 seconds? What's the
> point? Or what images are you refering to ??
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/PhilJay/MPAndroidChart/issues/1555#issuecomment-197138325>
>



-- 
Troy Chuinard, CPA

**Comment by vit001** [comment]
> I am assuming that the chart is an actual image on the client's device.

You are incorrect on this point.
