### ISSUE TITLE
piechart x,y Values overlapping 

### ISSUE THREAD

**Issue by kprathap23** [PhilJay/MPAndroidChart#1556]
piechart values are overlapping

I have data like this
Present Days =4
Absents =0
Leaves =0

I don't to want show data if the values are zero. 

is there any way to fix this.

![ScreenShot](https://dl.dropboxusercontent.com/u/83669745/images/Screenshot_2016-03-08-11-38-58.png)

**Comment by PhilJay** [comment]
Thats because your slices are very small.
There is not much to be done about that.

**Comment by kprathap23** [comment]
Even though i sent 

dataSet.setSliceSpace(100);

still overlapping 

![sc](https://dl.dropboxusercontent.com/u/83669745/images/Screenshot_2016-03-08-15-15-17.png)
