### ISSUE TITLE
c.clipPath(filledPath) do not work on android 4.2.2

### ISSUE THREAD

**Issue by hexi** [PhilJay/MPAndroidChart#1558]
![2016-03-09 9 31 22](https://cloud.githubusercontent.com/assets/2355115/13622486/f19933d6-e5d9-11e5-933d-84277060cb4e.png)

**Comment by hexi** [comment]
clipPath() first supported on api 18

**Comment by PhilJay** [comment]
Correct.

Simplest solution to the problem is turning of hardware acceleration. The `Chart` class actually provides a method for that: `chart.setHardwareAccelerationEnabled(...)`.

http://stackoverflow.com/a/30354461/1590502
