### ISSUE TITLE
Labels in X axis are not aligned

### ISSUE THREAD

**Issue by adarsh-tm** [PhilJay/MPAndroidChart#1560]
![screenshot_2016-03-09-16-24-01](https://cloud.githubusercontent.com/assets/17596472/13641261/18d06e86-e618-11e5-91e6-5b2659f9aabe.png)

In the above graph the x axis is not aligned. Kindly, let me know how should I align them.  And also I want to manually enter the coordinates after removing the sliders. It would be really helpful if you could guide me

**Comment by PhilJay** [comment]
post your xml

**Comment by adarsh-tm** [comment]
this is the activity_lineChart.xml

`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.github.mikephil.charting.charts.LineChart
        android:id="@+id/chart1"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/tvYMax"
        android:layout_alignLeft="@+id/seekBar2"
        android:layout_alignStart="@+id/seekBar2" />
    
    <SeekBar
        android:id="@+id/seekBar2"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentLeft="true"
        android:layout_margin="8dp"
        android:layout_toLeftOf="@+id/tvYMax"
        android:layout_marginRight="5dp"
        android:max="200"
        android:paddingBottom="12dp" />

    <SeekBar
        android:id="@+id/seekBar1"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_above="@+id/seekBar2"
        android:layout_margin="8dp"
        android:layout_marginBottom="35dp"
        android:layout_toLeftOf="@+id/tvXMax"
        android:layout_marginRight="5dp"
        android:max="500"
        android:paddingBottom="12dp" />

    <TextView
        android:id="@+id/tvXMax"
        android:layout_width="50dp"
        android:layout_height="wrap_content"
        android:layout_alignBottom="@+id/seekBar1"
        android:layout_alignParentRight="true"
        android:text="500"
        android:layout_marginBottom="15dp"
        android:layout_marginRight="10dp"
        android:gravity="right"
        android:textAppearance="?android:attr/textAppearanceMedium" />

    <TextView
        android:id="@+id/tvYMax"
        android:layout_width="50dp"
        android:layout_height="wrap_content"
        android:layout_alignBottom="@+id/seekBar2"
        android:layout_alignParentRight="true"
        android:text="500"
        android:layout_marginBottom="15dp"
        android:layout_marginRight="10dp"
        android:gravity="right"
        android:textAppearance="?android:attr/textAppearanceMedium" />

</RelativeLayout>`


Let me know what is the issue
