### ISSUE TITLE
It's seems that MPAndroidChart doesn't support multi marker.

### ISSUE THREAD

**Issue by Hysting** [PhilJay/MPAndroidChart#1564]
I have two LineDataSet in the LineChart, but I can add only one marker,
![image](https://cloud.githubusercontent.com/assets/8590421/13662041/83daaff6-e6d2-11e5-8414-968713de22ff.png)

**Comment by PhilJay** [comment]
You can simply highlight multiple values: https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart
