### ISSUE TITLE
Realm x,y,z, plots verses t 

### ISSUE THREAD

**Issue by tdunbar12** [PhilJay/MPAndroidChart#1567]
I have a Realm database of RealmObjects called DataEntry

`import io.realm.RealmObject;
import io.realm.annotations.RealmClass;

@RealmClass
public class DataEntry extends RealmObject {

    private int xIndex;
    private String androidDevice;
    private long timestamp;
    private float x;
    private float y;
    private float z;
    private int accuracy;

    //  no arguments constructor for Realm database
    public DataEntry() {
    }
    public DataEntry(float x, float y, float z, long timestamp,int xIndex) {
        this.x = x;
        this.y = y;
        this.z = z;
        this.xIndex = xIndex;
        this.timestamp = timestamp;
    }
    public int getxIndex() {
        return xIndex;
    }

    public void setxIndex(int xIndex) {
        this.xIndex = xIndex;`

I then initialize the database with 1000 dummy datapoints to test it out 

` public void initializeRealm(){
        //   Log.i(TAG, "Begin Transaction ");
        mRealm.beginTransaction();
        //   Log.i(TAG, "Start loop for database fill ");
        for (int i=0; i<1000; i++) {
        //    Log.i(TAG, "define DataEntry object ");
            DataEntry entry = mRealm.createObject(DataEntry.class);
        //    Log.i(TAG, "define device ");
            entry.setAndroidDevice(mAndroidId);
        //    Log.i(TAG, "set time ");
            long currtime = SystemClock.elapsedRealtime();
            entry.setTimestamp(currtime);
        //    Log.i(TAG, "set x ");
            float x = (float) (-10 +.02 * i );
            entry.setX(x);
            float y = (float) (-10 + .02 * i);
            entry.setY(y);
            float z = (float) (-10 + .02 * i);
            entry.setZ(z);
            int accu = 1;
            entry.setAccuracy(accu);
            entry.setxIndex(i);
        }
    //    Log.i(TAG, "Finished loop ");
        mRealm.commitTransaction();
    //    Log.i(TAG, "Commit ");
    }`

In onCreate I setup the Realm Configuration and add a listener so the chart can be updated each time the database gets updated.

`  RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                .name("myrealm.realm")
                .inMemory()
                .build();
        Log.i(TAG, "delete previous");

        Realm.deleteRealm(realmConfiguration); // Clean slate
        Log.i(TAG, "set default configuration");
        Realm.setDefaultConfiguration(realmConfiguration); // Make this Realm the default
        Log.i(TAG, "define an instance for this");
        mRealm = Realm.getDefaultInstance();
        Log.i(TAG, "setup dummy data filling the database");
        initializeRealm();

        Log.i(TAG, "build a Listener for database changes");
        realmListener = new RealmChangeListener() {
            @Override
            public void onChange() {
                // Update UI new data in the database
                setData();
                mChart.invalidate();
            }
        };
        Log.i(TAG, "add Listener  ");

        mRealm.addChangeListener(realmListener);`

Further in onCreate I setup the rough characteristics of the chart

`   mChart = (LineChart) findViewById(R.id.lineChart2);
        Log.i(TAG, "Setup graphing view1");
        // set onchartValue
        // mChart.setOnChartValueSelectedListener(getApplication());
        // obtain legend object
        Legend legend = mChart.getLegend();
        // turn off legend
        legend.setEnabled(true);
        // set chart to display 100 values in x axis (Time)
        mChart.setVisibleXRangeMaximum((float) 1000);
        // enable touch gestures
        mChart.setTouchEnabled(true);
        // enable scaling and dragging
        mChart.setDragEnabled(true);
        mChart.setScaleEnabled(true);
        // mChart.setScaleXEnabled(true);
        // mChart.setScaleYEnabled(true);

        // if disabled, scaling can be done on x- and y-axis separately
        mChart.setPinchZoom(true);
        Log.i(TAG, "Setup graphing view  x");
        // set up the x axis
        XAxis xAxis = mChart.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setTextSize(15f);
        xAxis.setTextColor(Color.BLACK);
        xAxis.setDrawAxisLine(true);
        xAxis.setDrawGridLines(true);
        // set a custom value formatter
        //        xAxis.setXValueFormatter(new MyCustomFormatter());

        YAxis yAxisR = mChart.getAxisRight();
        // yAxis.setPosition(YAxis.YAxisLabelPosition.BOTTOM);
        yAxisR.setTextSize(15f);
        yAxisR.setTextColor(Color.BLACK);
        yAxisR.setDrawAxisLine(true);
        yAxisR.setDrawGridLines(true);
        // set a number of decimal places on axis
        yAxisR.setValueFormatter(new DefaultYAxisValueFormatter(2));

        YAxis yAxis = mChart.getAxisLeft();
        // yAxis.setPosition(YAxis.YAxisLabelPosition.BOTTOM);
        yAxis.setTextSize(15f);
        yAxis.setTextColor(Color.BLACK);
        yAxis.setDrawAxisLine(true);
        yAxis.setDrawGridLines(true);
        // set a number of decimal places on axis
        yAxis.setValueFormatter(new DefaultYAxisValueFormatter(2));
        //       yAxis.setYValueFormatter(new MyCustomFormatter());

        Log.i(TAG, "Setup data querry and graphing");
        setData();`

Lastly try to setData for what I was hoping would be the initial conditions of the chart.  Gently sloped line from -10 to 10 over the range of timestamps in the x-axis.  My code quits at the displaying the TAG "Create Line Data for Graphing"

` private void setData() {

        Log.i(TAG, "In setData perform querry ");
        RealmResults<DataEntry> results = mRealm.allObjects(DataEntry.class);

        Log.i(TAG, "Extract x data ");
        RealmLineDataSet<DataEntry> set1 = new RealmLineDataSet<>(results, "x","timestamp");
        set1.setDrawCubic(false);
        set1.setLabel("Realm LineDataSet");
        set1.setDrawCircleHole(false);
        set1.setColor(ColorTemplate.rgb("#FF5722"));
        set1.setCircleColor(ColorTemplate.rgb("#FF5722"));
        set1.setLineWidth(1.8f);
        set1.setCircleSize(3.6f);
  //
  //      Log.i(TAG, "Extract y data ");
  //      RealmLineDataSet<DataEntry> set2 = new RealmLineDataSet<DataEntry>(results, "y");
  //      Log.i(TAG, "Extract z data ");
  //      RealmLineDataSet<DataEntry> set3 = new RealmLineDataSet<DataEntry>(results, "z")
  //

        ArrayList<ILineDataSet> dataSets = new ArrayList<>();
        Log.i(TAG, "add datasets ");
        dataSets.add(set1);
  //      dataSets.add(set2);
  //      dataSets.add(set3);

        Log.i(TAG, "Create Line Data for graphing ");

        RealmLineData lineData = new RealmLineData(results, "timestamp", dataSets);

        Log.i(TAG, "Set Data on Chart ");
        mChart.setData(lineData);
        Log.i(TAG, "Animate ");
        mChart.invalidate();
    }`

I've tried various different iterations of calling RealmLineDataSet  and RealmLineData and haven't found the trick.  Any suggestions?   Also as you can see I want to get y and z datasets and plot them as different colors.

Sorry for the messy cut and paste,  I hope you can follow what I was up to .

Thanks

**Comment by tdunbar12** [comment]
`package com.tomphyx.android.plotrealmtest;

import android.graphics.Color;
import android.graphics.Typeface;
import android.os.SystemClock;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;

import com.github.mikephil.charting.charts.LineChart;
import com.github.mikephil.charting.components.Legend;
import com.github.mikephil.charting.components.XAxis;
import com.github.mikephil.charting.components.YAxis;
import com.github.mikephil.charting.data.ChartData;
import com.github.mikephil.charting.data.realm.implementation.RealmLineData;
import com.github.mikephil.charting.data.realm.implementation.RealmLineDataSet;
import com.github.mikephil.charting.formatter.DefaultYAxisValueFormatter;
import com.github.mikephil.charting.formatter.PercentFormatter;
import com.github.mikephil.charting.interfaces.datasets.ILineDataSet;
import com.github.mikephil.charting.utils.ColorTemplate;

import java.util.ArrayList;

import io.realm.RealmResults;
import io.realm.Realm;
import io.realm.RealmChangeListener;
import io.realm.RealmConfiguration;



public class MainActivity extends AppCompatActivity {

    private Realm mRealm;
    private RealmChangeListener realmListener;
    private String mAndroidId =  "toms";
    private LineChart mChart;
    protected Typeface mTf;

    private static String TAG = "Realm_plot_test";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        Log.i(TAG, "establish instance of realm database");

        // The RealmConfiguration is created using the builder pattern.
// The realm file will be located in Context.getFilesDir() with name "myrealm.realm"

        //     RealmConfiguration config = new RealmConfiguration.Builder(this).build();
        //      Realm.setDefaultConfiguration(config);
        //     RealmConfiguration config = new RealmConfiguration.Builder(context)
        //             .name("myrealm.realm")
        //             .encryptionKey(getKey())
        //             .schemaVersion(42)
        //             .setModules(new MySchemaModule())
        //             .migration(new MyMigration())
        //             .build();
// Use the config
        //    Realm realm = Realm.getInstance(config);

        // Building a Realm instance un-persisted in memory (ie not on disk)
        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                .name("myrealm.realm")
                .inMemory()
                .build();
        Log.i(TAG, "delete previous");
        Realm.deleteRealm(realmConfiguration); // Clean slate

        Log.i(TAG, "set default configuration");
        Realm.setDefaultConfiguration(realmConfiguration); // Make this Realm the default

        Log.i(TAG, "define an instance for this");
        mRealm = Realm.getDefaultInstance();

        Log.i(TAG, "setup dummy data filling the database");
        initializeRealm();

        Log.i(TAG, "build a Listener for database changes");
        realmListener = new RealmChangeListener() {
            @Override
            public void onChange() {
                // Update UI new data in the database
                setData();
                mChart.invalidate();
            }
        };
        Log.i(TAG, "add Listener  ");
        mRealm.addChangeListener(realmListener);

        Log.i(TAG, "Setup graphing view1");
        mChart = (LineChart) findViewById(R.id.lineChart2);

        // set onchartValue
        // mChart.setOnChartValueSelectedListener(getApplication());
        // obtain legend object
        Legend legend = mChart.getLegend();
        // turn off legend
        legend.setEnabled(true);
        // set chart to display 100 values in x axis (Time)
        mChart.setVisibleXRangeMaximum((float) 1000);
        // enable touch gestures
        mChart.setTouchEnabled(true);
        // enable scaling and dragging
        mChart.setDragEnabled(true);
        mChart.setScaleEnabled(true);
        // mChart.setScaleXEnabled(true);
        // mChart.setScaleYEnabled(true);

        // if disabled, scaling can be done on x- and y-axis separately
        mChart.setPinchZoom(true);
        Log.i(TAG, "Setup graphing view  x");
        // set up the x axis
        XAxis xAxis = mChart.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setTextSize(15f);
        xAxis.setTextColor(Color.BLACK);
        xAxis.setDrawAxisLine(true);
        xAxis.setDrawGridLines(true);
        // set a custom value formatter
        //        xAxis.setXValueFormatter(new MyCustomFormatter());

        YAxis yAxisR = mChart.getAxisRight();
        // yAxis.setPosition(YAxis.YAxisLabelPosition.BOTTOM);
        yAxisR.setTextSize(15f);
        yAxisR.setTextColor(Color.BLACK);
        yAxisR.setDrawAxisLine(true);
        yAxisR.setDrawGridLines(true);
        // set a number of decimal places on axis
        yAxisR.setValueFormatter(new DefaultYAxisValueFormatter(2));

        YAxis yAxis = mChart.getAxisLeft();
        // yAxis.setPosition(YAxis.YAxisLabelPosition.BOTTOM);
        yAxis.setTextSize(15f);
        yAxis.setTextColor(Color.BLACK);
        yAxis.setDrawAxisLine(true);
        yAxis.setDrawGridLines(true);
        // set a number of decimal places on axis
        yAxis.setValueFormatter(new DefaultYAxisValueFormatter(2));
        //       yAxis.setYValueFormatter(new MyCustomFormatter());

        Log.i(TAG, "Setup data querry and graphing");
        setData();
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }
    private void setData() {

        Log.i(TAG, "In setData perform querry ");
        RealmResults<DataEntry> results = mRealm.allObjects(DataEntry.class);


        Log.i(TAG, "Extract x data ");
        RealmLineDataSet<DataEntry> set1 = new RealmLineDataSet<>(results, "x");
        set1.setDrawCubic(false);
        set1.setLabel("Realm LineDataSet");
        set1.setDrawCircleHole(false);
        set1.setColor(ColorTemplate.rgb("#FF5722"));
        set1.setCircleColor(ColorTemplate.rgb("#FF5722"));
        set1.setLineWidth(1.8f);
        set1.setCircleSize(3.6f);
        //
        //      Log.i(TAG, "Extract y data ");
        //      RealmLineDataSet<DataEntry> set2 = new RealmLineDataSet<DataEntry>(results, "y");
        //      Log.i(TAG, "Extract z data ");
        //      RealmLineDataSet<DataEntry> set3 = new RealmLineDataSet<DataEntry>(results, "z")
        //

        ArrayList<ILineDataSet> dataSets = new ArrayList<>();
        Log.i(TAG, "add datasets ");
        dataSets.add(set1);
        //      dataSets.add(set2);
        //      dataSets.add(set3);

        Log.i(TAG, "Create Line Data for graphing ");

        RealmLineData lineData = new RealmLineData(results, "xIndex", dataSets);

        Log.i(TAG, "Set Data on Chart ");
        mChart.setData(lineData);
        Log.i(TAG, "Animate ");
        mChart.invalidate();
    }
    protected void styleData(ChartData data) {
        data.setValueTypeface(mTf);
        data.setValueTextSize(8f);
        data.setValueTextColor(Color.DKGRAY);
        data.setValueFormatter(new PercentFormatter());
    }
    public void initializeRealm(){
        //   Log.i(TAG, "Begin Transaction ");
        mRealm.beginTransaction();
        //   Log.i(TAG, "Start loop for database fill ");
        for (int i=0; i<1000; i++) {
            //    Log.i(TAG, "define DataEntry object ");
            DataEntry entry = mRealm.createObject(DataEntry.class);
            //    Log.i(TAG, "define device ");
            entry.setAndroidDevice(mAndroidId);
            //    Log.i(TAG, "set time ");
            long currtime = SystemClock.elapsedRealtime();
            entry.setTimestamp(currtime);
            //    Log.i(TAG, "set x ");
            float x = (float) (-10 +.02 * i );
            entry.setX(x);
            float y = (float) (-10 + .02 * i);
            entry.setY(y);
            float z = (float) (-10 + .02 * i);
            entry.setZ(z);
            int accu = 1;
            entry.setAccuracy(accu);
            entry.setxIndex(i);
        }
        //    Log.i(TAG, "Finished loop ");
        mRealm.commitTransaction();
        //    Log.i(TAG, "Commit ");
    }
}`

**Comment by PhilJay** [comment]
I am not sure where the problem is.

Take a look at this tutorial and the example code: https://github.com/PhilJay/MPAndroidChart/wiki/Realm.io-database-integration
