### ISSUE TITLE
Piechart with vertical legend

### ISSUE THREAD

**Issue by evixar** [PhilJay/MPAndroidChart#1572]
Hi,

I'm trying to display the legend of a pie chart vertically but I can't find any option to do it.

It looks like Google Analytics app uses MPAndroidChart (it looks very familiar) and their legend below a pie chart is shown vertically.

Is there anyway to do this ?

Regards

**Comment by PhilJay** [comment]
`legend.setPosition(...)`

**Comment by evixar** [comment]
Hi,

I Know i van change legend position and set to BelowLeft but when I choose this position, the legend is displayed horizontally on one line but i want it change its orientation to vertical with one line for each value 
Regards

**Comment by PhilJay** [comment]
RIGHT_OF_CHART_CENTER will make it vertical

**Comment by evixar** [comment]
Ok thanks i'll try that and let you know 

Regards

**Comment by evixar** [comment]
Is there anyway to have the legend below the chart and vertical ?

Thanks

**Comment by unmays** [comment]
Hi, I was facing the same issue.
Got the Legend below the PieChart by using setPosition(BELOW_CHART_LEFT), setTextSize(14) and setWordWrapEnabled(true).
Increasing the text size will do make the individual legend items wrap around and appear on the next line.

**Comment by omidraha** [comment]
Now, the `legend.setPosition` is deprecated, 
How to use new direction for that?

**Comment by martinock** [comment]
@omidraha Try to use `legend.setOrientation()`. It's not what I expect though, because it become on the left side of the chart instead of below of it. But for some of us I think it's okay.
