### ISSUE TITLE
Can I get a smaller package if I don't need all of the chart?

### ISSUE THREAD

**Issue by tinybright** [PhilJay/MPAndroidChart#1573]
I only need linechart  or barchart.It's there a way to compile a package only contains what I need?

**Comment by vit001** [comment]
Why don't you use proguard to take care of that?

**Comment by tinybright** [comment]
I want to use instant run.If I use proguard,I can't use instant run.

**Comment by vit001** [comment]
You were asking about compiling a small size package, presumably for distribution. If you use instant run for debugging, why does the method count matter to you?

**Comment by tinybright** [comment]
Method counts doesn't change after I use proguard.

**Comment by vit001** [comment]
OK, I suggest you review your proguard configuration. In particular, if you added this:

-keep public class com.github.mikephil.** {
     public protected *;
}

then of course, your method count won't change. I am not sure what you are trying to accomplish, but I am pretty sure it doesn't belong under MPAndroidChart issues.

**Comment by PhilJay** [comment]
I suggest you carry this to [stackoverflow.com](http://stackoverflow.com).

**Comment by tinybright** [comment]
http://facebook.github.io/stetho/
https://github.com/FrantisekGazo/Blade
