### ISSUE TITLE
代码不匹配

### ISSUE THREAD

**Issue by zhaoxiuyu** [PhilJay/MPAndroidChart#1575]
新的compile 'com.github.PhilJay:MPAndroidChart:v2.2.3'依赖包
和我下载下来的代码不匹配
                List<ILineDataSet> sets = mChart.getData()
                        .getDataSets();
                for (ILineDataSet iSet : sets) {
                    LineDataSet set = (LineDataSet) iSet;
                    if (set.isDrawSteppedEnabled()) {
                        set.setDrawStepped(false);
                    } else {
                        set.setDrawStepped(true);
                    }
                }

没有这些方法

**Comment by zhaoxiuyu** [comment]
没有线程，看附件图片，代码是直接从github里面下载的。





在 2016-03-15 15:08:29，"Philipp Jahoda" <notifications@github.com> 写道：


Closed #1575.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/PhilJay/MPAndroidChart/issues/1575#event-589853917

**Comment by MarcellaGu** [comment]
Hi, there are no isDrawSteppedEnabled and setDrawStepped methods in LineDataSet when this project is referenced in build.gradle dependencies
(compile 'com.github.PhilJay:MPAndroidChart:v2.2.3')

Can you check it again, please?
