### ISSUE TITLE
All bars not displaying:Barchart generation from Realm.io Database

### ISSUE THREAD

**Issue by yashthakerlearns** [PhilJay/MPAndroidChart#1577]
![img-20160315-wa0001](https://cloud.githubusercontent.com/assets/17721892/13772817/19237f06-eabc-11e5-8dc7-57b250ee6acc.jpg)

Hey @PhilJay check dis image with problem and here's the code.plz help mostly first two bars are not displaying in the result.
 
private void setData(){

        RealmResults<Transactions> results = realm.where(Transactions.class).between("mydate", StartDate,EndDate).findAll();

        RealmBarDataSet<Transactions> barDataSet = new RealmBarDataSet<Transactions>(results, "Purchase_order", "id");
        barDataSet.setColor(ColorTemplate.rgb("#27ae60"));
        barDataSet.setLabel("Purchase Order");
        ArrayList<IBarDataSet> barDataSets = new ArrayList<IBarDataSet>();
        barDataSets.add(barDataSet);
        RealmBarData barData = new RealmBarData(results, "date", barDataSets);
        barChart.setData(barData);
        barChart.invalidate();
        Legend legend=barChart.getLegend();
        legend.setForm(Legend.LegendForm.CIRCLE);
        legend.setFormSize(10f);
        legend.setTextSize(12f);
        legend.setTextColor(Color.rgb(52, 73, 94));
        legend.setXEntrySpace(5f);
        legend.setYEntrySpace(5f);
        XAxis xAxis=barChart.getXAxis();
        xAxis.setDrawGridLines(false);
        xAxis.setDrawAxisLine(true);
        xAxis.setTextColor(R.color.colorAccent);
        YAxis left=barChart.getAxisLeft();
        left.setDrawAxisLine(true);
        left.setDrawGridLines(true);
        barChart.getAxisRight().setEnabled(false);

        barChart.setMaxVisibleValueCount(7);
  
        barChart.setDescriptionPosition(720f, 410f);
        barChart.setDescriptionTextSize(12f);
        barChart.setDescriptionColor(Color.rgb(52, 73, 94));
        barChart.setDescriptionTypeface(typeface);

        barChart.setNoDataTextDescription("No chart data available to display.");
        barChart.animateY(1400, Easing.EasingOption.EaseInOutQuart);
        barChart.notifyDataSetChanged();
        barChart.invalidate();
    }

**Comment by PhilJay** [comment]
Have you checked that your database actually has values for the first two bars?

**Comment by yashthakerlearns** [comment]
Yes @PhilJay it shows values when I start from 01-03-2016 as Start Date (which is my first entry of database) but if I select 02-03-2016 as Start Date then and only then it skips value. Here take a look,my start date in this image is 01-03-2016.everything working fine then
![img-20160316-wa0001 1](https://cloud.githubusercontent.com/assets/17721892/13805371/2849c332-eb7a-11e5-9906-ad9a0eb663e3.jpg)

**Comment by yashthakerlearns** [comment]
@PhilJay if you require my database entries file for help,then plz tell me.

**Comment by yashthakerlearns** [comment]
plz reply @PhilJay

**Comment by donnfelker** [comment]
Do you have a sample project that you can provide to demonstrate the problem?

**Comment by PhilJay** [comment]
Yes, a sample project could be helpful. Any progress?

**Comment by yashthakerlearns** [comment]
[main.zip](https://github.com/PhilJay/MPAndroidChart/files/201789/main.zip)
Find all project related files here that I am working on. @PhilJay @donnfelker

**Comment by yashthakerlearns** [comment]
Hey @PhilJay from my experience working with this library, I've found that this issue is due to **xValuesField "id"**  in my case. 
RealmBarDataSet<Transactions> barDataSet = new RealmBarDataSet<Transactions>(results, "Purchase_order", "id");
If suppose I select 01-03-2016 date then it's id is 0 so it will show all bars. But if I select 03-03-2016 date then it skips two bars as id of this record is 2. Hence it skips records which have ids 0 and 1. So it skips two bars. So xValuesField has problem here.

**Comment by yashthakerlearns** [comment]
hey @PhilJay if you have any suggestions please reply me immediately because I am using this library in my project which I have to finish soon. So little help would be great.

**Comment by yashthakerlearns** [comment]
Hey I've figured out solution. I just injected a for loop with int i which will be id of bars. So even if I select 03-03-2016 as Start so it will take its id 0 and hence problem is solved. So closing this issue @PhilJay
