### ISSUE TITLE
Pie chart breaks down after 100 entries

### ISSUE THREAD

**Issue by vicmns** [PhilJay/MPAndroidChart#1582]
Regretfully, I have some data sets with 100+ data entries that I need to plot on this specific chart. I know, it sounds stupid but those are the specifications...

Pretty much what it happens is this:
![device-2016-03-15-165614](https://cloud.githubusercontent.com/assets/1101060/13796871/078536d2-eacf-11e5-8c77-6ffa82f9b125.png)

And of course I'm setting a list of colors with the same size as my entries:
``` 
for (int i = 0; i < colEdge.getEx(); i++) {
  chartEntryExtraModel = createEntryExtraModelForChart(data, 0, i);
  entries.add(new BarEntry(data.getBody().get(0).get(i).getRAsDouble().floatValue(), i));
  colors.add(ALTA_DVT_PALETTE_COLOR[i % ALTA_DVT_PALETTE_COLOR.length]);
}
```

Is this a limitation of the library, so I can stop poking on the source code in the meantime and concentrate in other stuff?

**Comment by PhilJay** [comment]
The code you posted above cannot be the code corresponding to your `PieChart`, since you are creating entries of type `BarEntry` which cannot be used in the `PieChart`.

Are you sure you set everything up correctly?

Color count is not a limitation.

**Comment by vicmns** [comment]
Yikes, my bad, just changed to Entry, but I still have the same problem. I'm not able to reproduce it outside my dataset... But using the following count and range when creating the PieChartActivity `setData(150, 5000000);` I found out another bug, which makes the chart to render like this:
![device-2016-03-16-104914](https://cloud.githubusercontent.com/assets/1101060/13820872/d2cac2e0-eb64-11e5-8f0c-22772dd9717d.png)

**Comment by vicmns** [comment]
Ok I found out why the pie chart was plotting like that. After I do an upstream merge on my fork (which includes the last commits on the pie chart) the chart is now rendering like the demo application that I mentioned previously.

**Comment by PhilJay** [comment]
So everything works now? :-)

**Comment by vicmns** [comment]
Well not exactly, the chart renders like this:
![device-2016-03-16-115012](https://cloud.githubusercontent.com/assets/1101060/13822984/6613d764-eb6d-11e5-80db-a1db304d78da.png)

For a strange reasons the background paints itself, the background of the chart is set to be white...

This can be reproduce on the PieChartActivity changing the `setData(3, 100)` line on `onCreate()`  to `setData(150, 5000000)`

**Comment by PhilJay** [comment]
You are right, the issue is related to the `sliceSpace` of the pie-slices. I think that as soon as the slice space exceeds the size of the slices, this issue occurs. Since the slices are very small when adding 150 values, this can easily happen.

If the space is set to 0f, the issue does not occur.

@danielgindi what do you think of this?

**Comment by danielgindi** [comment]
Spacing should be reduced if there's not enough space...
But maybe we can determine that and reduce it automatically
