### ISSUE TITLE
Gaps for x axis

### ISSUE THREAD

**Issue by southerton81** [PhilJay/MPAndroidChart#1583]
Thank you for a great library. 
Is there a way to chart unequally distanced elements? For example 3, 7, 8 in such a way that the graph would have longer distance between 3 and 7, and shorter between 7 and 8?

**Comment by MGasztold** [comment]
+1

**Comment by PhilJay** [comment]
Yes, add values like that:
"1" "2" "3" "" "" "" "" "8" "" "10"

**Comment by MGasztold** [comment]
This is not working in a scalable way when somebody wants to plot double X values like:

{1.2030952380952384,1.2876666666666667,1.1901428571428572,1.2245238095238096,1.3009285714285714,1.330785714285714,1.3865952380952382,1.343904761904762,1.3996190476190478,1.56,1.4201190476190477,1.4839285714285713,1.4721666666666666, ... }

It would be great if the x axis handles Number objects , not String only.

**Comment by PhilJay** [comment]
Yes, you are right. That's a feature on top of my list for the future :-)

**Comment by jitccgcg** [comment]
Is this possible to do now with the newest version?
