### ISSUE TITLE
Dynamically change valueFormatter 

### ISSUE THREAD

**Issue by BalalakshmiSadhasivam** [PhilJay/MPAndroidChart#1585]
How to dynamically change y-axis valueFormatter while zooming so that the precision of values can be changed based on zoom level ? 

**After Zooming:**
![zoomed_chart](https://cloud.githubusercontent.com/assets/14068048/13811412/a10f6f9e-eb9b-11e5-8899-4874e2c1fc87.png)

**Comment by vit001** [comment]
Why do you want to change the valueFormatter dynamically? Why not just make the valueFormatter return the correct string based on the visible range / zoom ?

**Comment by BalalakshmiSadhasivam** [comment]
@vit001 That is what I was trying to do. But I was not able to relate zoom level with precision. How to make get current zoom level or how to check for repetitive values in y-axis  ?

**Comment by PhilJay** [comment]
You can get direct access to the current zoom / scale level of the chart by using the `ViewPortHandler`.

```java
ViewPortHandler h = chart.getViewPortHandler();
```

Concerning the `YAxisValueFormatter`, all you need to do is hand an instance of the `ViewPortHandler` to your formatter (e.g. via constructor).

```java

private ViewPortHandler handler;

public MyCustomFormatter(ViewPortHandler h) {
    this.handler = h;
}

public void getFormattedValue(...) {
    
    float yScale = handler.getScaleY();
}

```

**Comment by BalalakshmiSadhasivam** [comment]
How to check for repetitive values in the axis ?
