### ISSUE TITLE
No isDrawSteppedEnabled and setDrawStepped methods in LineDataSet

### ISSUE THREAD

**Issue by MarcellaGu** [PhilJay/MPAndroidChart#1586]
Hi, there are no #isDrawSteppedEnabled and setDrawStepped methods in LineDataSet when this project is referenced in build.gradle dependencies
(compile 'com.github.PhilJay:MPAndroidChart:v2.2.3')

Can you check it again, please?
#1575 (closed but not fixed)

**Comment by PhilJay** [comment]
I do not speak chinese or japanese or whatever language was used to create the referenced issue. If an issue is not worded in english, which is the official language for this repository, I will not review it.

Furthermore, those methods already exist in the library, but are not yet in a release.

**Comment by MarcellaGu** [comment]
OK. Forget the previous issue that the other user informed.
I wrote this issue  (#1586) in English.

This issue occurs when only the dependence is informed in build.grandle 
(first usage of this tutorial: [https://github.com/PhilJay/MPAndroidChart#usage](url)   ).

Like that:

> repositories {
    maven { url "https://jitpack.io" }
}

> dependencies {
    compile 'com.github.PhilJay:MPAndroidChart:v2.2.3'
}


There are no **isDrawSteppedEnabled** and **setDrawStepped** methods in **LineDataSet** when this library (version **v2.2.3**) is used like that.

Can you check it?
