### ISSUE TITLE
bug in RadarChart

### ISSUE THREAD

**Issue by yankai-victor** [PhilJay/MPAndroidChart#1588]
use  mpandroidchartlibrary-2-1-6.jar

> java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.mikephil.charting.data.RadarData.getXValCount()' on a null object reference
> 	at com.github.mikephil.charting.charts.RadarChart.getSliceAngle(RadarChart.java:229)
> 	at com.github.mikephil.charting.charts.RadarChart.getIndexForAngle(RadarChart.java:238)
> 	at com.github.mikephil.charting.listener.PieRadarChartTouchListener.onSingleTapUp(PieRadarChartTouchListener.java:176)
> 	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:595)
> 	at com.github.mikephil.charting.listener.PieRadarChartTouchListener.onTouch(PieRadarChartTouchListener.java:47)
> 	at com.github.mikephil.charting.charts.PieRadarChartBase.onTouchEvent(PieRadarChartBase.java:76)
> 	at android.view.View.dispatchTouchEvent(View.java:8293)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2318)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2324)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2324)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2324)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2324)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2324)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2324)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2324)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2324)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
> 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2345)
> 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1708)
> 	at android.app.Activity.dispatchTouchEvent(Activity.java:2797)
> 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2306)
> 	at android.view.View.dispatchPointerEvent(View.java:8483)
> 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4291)
> 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4157)
> 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3662)
> 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3715)
> 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3681)
> 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3791)
> 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3689)
> 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3848)
> 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3662)
> 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3715)
> 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3681)
> 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3689)
> 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3662)
> 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5978)
> 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5952)
> 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5923)
> 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6081)
> 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
> 	at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
> 	at android.os.MessageQueue.next(MessageQueue.java:143)
> 	at android.os.Looper.loop(Looper.java:122)
> 	at android.app.ActivityThread.main(ActivityThread.java:5539)
> 	at java.lang.reflect.Method.invoke(Method.java)
> 	at java.lang.reflect.Method.invoke(Method.java:372)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart#questions--issues

**Comment by yankai-victor** [comment]
I update it to latest version. But this bug is still here.
