### ISSUE TITLE
peer not authenticated

### ISSUE THREAD

**Issue by luoqii** [PhilJay/MPAndroidChart#1590]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not resolve com.github.PhilJay:MPAndroidChart:v2.2.0.
     Required by:
         android-bmob-pm25:app:unspecified
      > Could not resolve com.github.PhilJay:MPAndroidChart:v2.2.0.
         > Could not get resource 'https://jitpack.io/com/github/PhilJay/MPAndroidChart/v2.2.0/MPAndroidChart-v2.2.0.pom'.
            > Could not GET 'https://jitpack.io/com/github/PhilJay/MPAndroidChart/v2.2.0/MPAndroidChart-v2.2.0.pom'.
               > peer not authenticated

but i can wget this by 

bysong@bysong-OptiPlex-790:/tmp$ wget https://jitpack.io/com/github/PhilJay/MPAndroidChart/v2.2.0/MPAndroidChart-v2.2.0.pom
--2016-03-17 16:39:38--  https://jitpack.io/com/github/PhilJay/MPAndroidChart/v2.2.0/MPAndroidChart-v2.2.0.pom
Resolving jitpack.io (jitpack.io)... 104.24.23.62, 104.24.22.62
Connecting to jitpack.io (jitpack.io)|104.24.23.62|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 406
Saving to: ‘MPAndroidChart-v2.2.0.pom.1’

100%[==========================================================================================================================================================================>] 406         --.-K/s   in 0s      

2016-03-17 16:39:39 (80.3 MB/s) - ‘MPAndroidChart-v2.2.0.pom.1’ saved [406/406]

bysong@bysong-OptiPlex-790:/tmp$

**Comment by luoqii** [comment]
my build.gralde (partly):

repositories {
    //https://github.com/luoqii/MPAndroidChart
    maven { url "https://jitpack.io" }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'

    //以下SDK开发者请根据需要自行选择
    //bmob-sdk ：Bmob的android sdk包
    compile 'cn.bmob.android:bmob-sdk:3.4.5'

    //okhttp（选填）：为解决弱网情况下SDK请求失败及响应慢的问题，自`V3.4.3版本`开始使用`okhttp`优化SDK的网络框架。
    compile 'com.squareup.okhttp:okhttp:2.4.0'
    compile 'com.squareup.okio:okio:1.4.0'

    //bmob-sms ：Bmob单独为短信服务提供的包
    compile 'cn.bmob.android:bmob-sms:1.0.1'

    //https://github.com/luoqii/MPAndroidChart
    compile 'com.github.PhilJay:MPAndroidChart:v2.2.0'
}

**Comment by PhilJay** [comment]
Try getting the latest version. 2.2.3

**Comment by luoqii** [comment]
bysong@bysong-OptiPlex-790:/tmp$ wget https://jitpack.io/com/github/PhilJay/MPAndroidChart/v2.2.0/MPAndroidChart-v2.2.3.pom
--2016-03-17 17:57:44--  https://jitpack.io/com/github/PhilJay/MPAndroidChart/v2.2.0/MPAndroidChart-v2.2.3.pom
Resolving jitpack.io (jitpack.io)... 104.24.22.62, 104.24.23.62
Connecting to jitpack.io (jitpack.io)|104.24.22.62|:443... connected.
HTTP request sent, awaiting response... 404 ok
2016-03-17 17:57:49 ERROR 404: ok.

bysong@bysong-OptiPlex-790:/tmp$ 


why ....   ???

**Comment by Handison** [comment]
@luoqii it seems the url is wrong, I think it must be https://jitpack.io/com/github/PhilJay/MPAndroidChart/v2.2.3/MPAndroidChart-v2.2.3.pom, not v2.2.0/MPAndroidChart-v2.2.3.pom

But after I use the latest version, still got the same issue, "peer not authenticated"

Any help?
