### ISSUE TITLE
Stacked Bar Chart not stacking up

### ISSUE THREAD

**Issue by Sutirth** [PhilJay/MPAndroidChart#1596]
@PhilJay Hey I am trying to used stack bar chart example but its not working . It is infact showing multiple chart data.

 ArrayList<String> xVals = new ArrayList<String>();
            for (int i = 0; i < 500 + 1; i++) {
                xVals.add(String.valueOf(i));
            }

            ArrayList<BarEntry> yValsT = new ArrayList<BarEntry>();

            for (int i = 0; i < 500 + 1; i++) {
                float mult = (500 + 1);
                float val1 = (float) (Math.random() * mult) + mult / 3;
                float val2 = (float) (Math.random() * mult) + mult / 3;
                float val3 = (float) (Math.random() * mult) + mult / 3;

                yValsT.add(new BarEntry(new float[] { val1, val2, val3 }, i));
            }

                BarDataSet setPoints = new BarDataSet(yVals1, "Statistics Vienna 2014");
                setPoints.setColors(getColors());
                setPoints.setStackLabels(new String[]{"Births", "Divorces", "Marriages"});
                ArrayList<IBarDataSet> dataSetPoints = new ArrayList<IBarDataSet>();
                dataSetPoints.add(setPoints);
                BarData dataBarPoints = new BarData(getXAxisValues(), dataSetPoints);
                mPointChart.setData(dataBarPoints);
                mPointChart.invalidate();

<img width="400" alt="screenshot 2016-03-18 16 13 27" src="https://cloud.githubusercontent.com/assets/3212997/13875587/cd820afc-ed24-11e5-8a8e-5059d905c108.png">

**Comment by Sutirth** [comment]
Even the legends are not displayed

**Comment by PhilJay** [comment]
When you create the entries, you use `yValsT`, for the dataset, you are using `yVals1`

**Comment by Sutirth** [comment]
It was a copy paste issue sorry for that but still doesn't solve the issue

**Comment by Sutirth** [comment]
cc @PhilJay
