### ISSUE TITLE
To increse the circle radious of Highlighted point in line Chart 

### ISSUE THREAD

**Issue by aAalane** [PhilJay/MPAndroidChart#1597]
My requirement is to increase the circle radius of highlighted point in Line Chart. Can anyone please resolve this issue..??

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/DataSet-classes-in-detail

**Comment by aAalane** [comment]
I wanted to increase the radius of point which I have selected ( I.e. Highlighted point) , instead of whole dataset setting the radius of dataset.

**Comment by PhilJay** [comment]
Circle size cannot be changed individually.
What you can do is have a second dataset with different circle sizes which you can show on selection.

**Comment by aAalane** [comment]
I know that we cannot change the radius of particular value of dataset. That is why I have opened new issue. My requirement is not a second dataset, I want to change the radius of particular value of dataset. Will you please fix this issue.?

**Comment by anschauhanex** [comment]
Was this fixed? I need the circle radius to be bigger where highlight line intersects on touch.

**Comment by illiaNaumov** [comment]
I'd like to make circle radius to be bigger on touch. Isn't solved yet?

**Comment by iRuth** [comment]
I had a similar requirement and I solved it by [adding circular highlighting](https://github.com/WW-Digital/MPAndroidChart/pull/9/commits/0e30e21aac868399628160eb689ede11a02ae9da). This is [how it looks](https://github.com/WW-Digital/MPAndroidChart/pull/9#issuecomment-264565712).

**Comment by tjiang11** [comment]
@iRuth Can you make a PR into the original repo?

**Comment by Edonfreiner** [comment]
@iRuth how do I get that to happen?
