### ISSUE TITLE
Pie chart dataset problem

### ISSUE THREAD

**Issue by MSehati** [PhilJay/MPAndroidChart#1600]
hello
if Pie DataSet contain one entry, the chart dont show anything.(this bug is happened for version upper than 2.1.6)
thanks for your useful library.

**Comment by lefevrG** [comment]
Hi,

Same problem here, i'm using v2.2.3.

**Comment by PhilJay** [comment]
This issue is already fixed, there will he a new release in a couple of days.

**Comment by esfahanpayamak94** [comment]
هنگامی که جهت کسب و کار خود سایتی را طراحی می کنید احتمال دارد از طراح سایت خود در مورد [بهینه سازی سایت](http://www.esfahanpayamak.com/seo) (سئو سایت) اطلاعاتی دریافت نمایید و به اهمیت آن پی ببرید. در اینجا قصد داریم به زبان ساده در مورد بهینه سازی وب سایت توضیحاتی دهیم .
