### ISSUE TITLE
RadarChart: color filled outside bounderies in Old Android

### ISSUE THREAD

**Issue by sorrento** [PhilJay/MPAndroidChart#1601]
Hi,
 
In Android 5.0, just fine. Instead in  **Android 4.1.2**  this happens:

![2016-03-19 13 07 10](https://cloud.githubusercontent.com/assets/11578646/13898511/eb26f644-edd3-11e5-98f3-195dcba7d584.png)

Very nice library. Good job!

Thanks

**Comment by minha-neofect** [comment]
I can figure out the reason of this error.
Radar chart uses clipPath function which can be used from API18+.
http://developer.android.com/intl/ko/guide/topics/graphics/hardware-accel.html#drawing-support
