### ISSUE TITLE
Pie Chart color is not visible for a single item

### ISSUE THREAD

**Issue by pradeepsagayam** [PhilJay/MPAndroidChart#1606]
Hi All,

When pie chart is drawn with only one item (100%), then color of the pie is not visible.

I request you to help me with the same.

Thanks in advance.
![mp_piechart](https://cloud.githubusercontent.com/assets/5426616/13916657/f389f660-ef81-11e5-8f44-c3f4d10a334e.png)

**Comment by CoryCharlton** [comment]
Was just coming to report the same thing. In my case I have three `Entry`s, two of which have zero values. As you can see from my video the single `Entry` that has a value is colored during the animation but then goes blank. I'll start digging into the code to see if I can find out why.

https://youtu.be/GE28PmOruPM

**Comment by CoryCharlton** [comment]
It looks like this changeset might have already resolved the issue: https://github.com/PhilJay/MPAndroidChart/commit/06e63af1e1927a99c424b0da4957bdef7849cd3b

**Comment by masztalski** [comment]
My solution is to set sliceSpace to 0f for only one non-zero value. Before new version release is the best solution

**Comment by taynanb** [comment]
@masztalski your solution works like a charm!!

Thank you!
