### ISSUE TITLE
Bug in Y axis interval calculation

### ISSUE THREAD

**Issue by vit001** [PhilJay/MPAndroidChart#1607]
In YAxisRenderer.computeAxisValues, there is code which calculates the label interval. Reading the comment, it is supposed to: "Use one order of magnitude higher, to avoid intervals like 0.9 or 90". The code works for intervals > 1, but breaks for interval < 1. I suggest replacing the following code:
```
double intervalMagnitude = Math.pow( 10, (int) Math.log10( interval ) );
int intervalSigDigit = (int) (interval / intervalMagnitude);
if ( intervalSigDigit > 5 ) {
    // Use one order of magnitude higher, to avoid intervals like 0.9 or 90
    interval = Math.floor( 10 * intervalMagnitude );
}
```
 with
```
double intervalMagnitude = Math.pow( 10, Math.floor( Math.log10( interval ) ) );
int intervalSigDigit = (int)Math.round (interval / intervalMagnitude);
if ( intervalSigDigit > 5 ) {
    // Use one order of magnitude higher, to avoid intervals like 0.9 or 90
    interval = 10 * intervalMagnitude;
}
```

**Comment by PhilJay** [comment]
Could you evaluate what you mean by "the code breaks" and what difference your suggested change would make?
Thank you.

**Comment by vit001** [comment]
The suggested change produces the correct result. The existing code does not, for intervals less than 1. Take, for example an interval of 0.06. The correctly adjusted interval should be 0.1. 

Going through the existing code, interval magnitude is 0.1, instead of 0.01. The problem here is that for negative values, (int) always rounds towards negative infinity, while floor rounds towards zero. 

Next, intervalSigDigit is zero, instead of 6. (Note my Math.round correctly handles floating point numbers like 5.99999999, where the (int) does not (it would produce intervalSigDigit=5 instead of the correct 6)

Last, you just want interval = 10 * intervalMagnitude;, taking the floor will always result in an interval of zero for intervalMagnitude <0.01.

**Comment by vit001** [comment]
If my comment is not clear, I suggest just feeding an interval of 0.06 to your code and see for yourself.

**Comment by PhilJay** [comment]
#1323

**Comment by vit001** [comment]
Looking at your commit, it only fixes one out of the 3 bugs. Please fix the other two as well. Thank you.

**Comment by macjay** [comment]
I have download the code and replace the code like you said,but didn't  work .

**Comment by vit001** [comment]
Sorry, nothing I can do for you without any more information.
