### ISSUE TITLE
How to rotate data value in line chart?

### ISSUE THREAD

**Issue by kizer93** [PhilJay/MPAndroidChart#1611]
Hello. I use your good graph library but i have a question.
I used value of second and I changed Data format.
Now, my Y data format is time data like 10:52:01.
but x interval is too small and string is too long so the fonts  were overlapped.
If the values were rotated, I could show all of values.
I can't find the function. Isn't it included?

**Comment by PhilJay** [comment]
`xaxis.setRotationAngleDegrees(...)`

**Comment by kizer93** [comment]
![aa](https://cloud.githubusercontent.com/assets/16444585/14014555/9bbde37a-f1f6-11e5-85f6-b5ca18de7cf9.JPG)
this is my problem. In the graph, you can see my problem.
you recommend serRotationAngleDegrees() but I can't find it.
There isn't existing in the javadoc.
