### ISSUE TITLE
Horizontal bar chart animation issue

### ISSUE THREAD

**Issue by eirini91** [PhilJay/MPAndroidChart#1613]
Hi,

This is not actually an issue but a question so i'm sorry for posting this here. 

So the Horizontal bar chart X animation starts from the bottom value and goes all the way to the top. I would like it to start from the top I have tried changing the library code a lot with no luck. I spent almost 2 days on this and still i cannot even identify which of all those classes I will need to work on. 

Can you suggest anything or guide me to the code that I should be looking at? 

Great library by the way. Thanks a lot.

**Comment by PhilJay** [comment]
Have a look at the chartanimator: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/com/github/mikephil/charting/animation/ChartAnimator.java
