### ISSUE TITLE
MPAndroidChart : Fix x Axis width or Break X axis text in two lines

### ISSUE THREAD

**Issue by bhaveshkaila** [PhilJay/MPAndroidChart#1617]
I am working and android chart library using MPAndroidChart .

I am using HorizontalBarChart to display chart.

Please see the attached image and I want do decrease x axis width or want to display x axis text in two lines is there any way to this ?

http://i.stack.imgur.com/sMawA.png

http://stackoverflow.com/questions/36215817/mpandroidchart-fix-x-axis-width-or-break-x-axis-text-in-two-lines

**Comment by PhilJay** [comment]
There is currently no way to draw the x-axis labels in multiple lines.

What you can do to decrease the space the labels consume is to simply provide shorter labels. A axis label of the length you are showing above is too long for a chart to be easily readable anyway.

**Comment by audoindechanterac** [comment]
A pull request has been opened for this feature, will it be added to the lib soon ?  @PhilJay

**Comment by felislynx-silae** [comment]
@PhilJay any ETA? I believe this is quite important feature if X axis is DATE axis :)

**Comment by Ahmad19860** [comment]
I am also facing the same issue. Hope new version will be released soon.

**Comment by rolyanos** [comment]
I did it in IOS charts by adding "\n" to xAxis labels, but here it is not working :(
