### ISSUE TITLE
Customizing the line graph

### ISSUE THREAD

**Issue by murthyanitaa** [PhilJay/MPAndroidChart#1618]
Hi, 

First off, thanks for this awesome library. You made my day!
I just have a couple of clarifications on how to achieve the following UI:
![ex](https://cloud.githubusercontent.com/assets/6929302/14040555/524827da-f28e-11e5-86e9-b13cbcf43bd9.png)

So far, I have achieved the following:
![screenshot_2016-03-25-13-37-35](https://cloud.githubusercontent.com/assets/6929302/14040628/f7bbc82a-f28e-11e5-8c44-ab81ae36526a.png)

I'm not sure how to:
1) remove the description that seems to be added to the graph
2) remove the padding that is surrounding the graph (I checked my code and I do not have any padding around the graph)
3) Add padding between the graph and the text above it
4) I am not able to horizontally scroll the graph once it is drawn.

Thanks a lot for your help.

**Comment by PhilJay** [comment]
The description can be removed by setting `chart.setDescription("")`. Concerning the other stuff, take a look at this example it pretty much does what you need:

https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/LineChartActivityColored.java

The only thing that cannot be changed is the position of the value labels.

**Comment by murthyanitaa** [comment]
Hi Phil,

Thanks for the help!
I'm still not able to set the graph to start from the center of the screen and scroll horizontally. Not sure if I'm doing anything wrong.

Secondly is there any way I can change the position of the value labels? Maybe I could customize the LineDataSet class? Could you just point me in the right direction with this one?

Thanks
