### ISSUE TITLE
Line Chart data set values are Overlapped when multiple values are in chart(like 100 value), need to be skip values as like in Xaxis Labels

### ISSUE THREAD

**Issue by abhaydatta** [PhilJay/MPAndroidChart#1621]
I had implemented line chart and it works like awesome. But i need some help where when i entered large data set values like 100 then the values are get overlapped and chart is not looking nice.So i need implement it like done in XAxis label in which if the labels are too large then it will get spaced between the label and fit in chart accordingly.
Please find below screenshot where chart data values get overlapped but XAxis values are get arranged properly by skipping some values.
![device-2016-03-28-144626](https://cloud.githubusercontent.com/assets/2194338/14075096/edf71f30-f4f3-11e5-8f7f-50ee3f25b9fc.png)

**Comment by PhilJay** [comment]
`chart.setMaxVisibleCount(...)` lets you set the maximum amout of entries in view for which value labels should be drawn.

Alternatively, you can write your own logic to do this.
