### ISSUE TITLE
Attempting to set member of null object in PieChart.calcMinMax()

### ISSUE THREAD

**Issue by KonstantinSchubert** [PhilJay/MPAndroidChart#1622]
In the PieChart, the method:

```
 protected void calcMinMax() {
       super.calcMinMax();

        calcAngles();
    }
```

Calls the parent's method, which is in PieRadarChartBase:

```
    protected void calcMinMax() {
        mXAxis.mAxisRange = mData.getXVals().size() - 1;
    }

```

This gives an error, because in the init section of the PieChart, `mAxis` is set to `null`.
My  proposed fix would be to remove the call to the parent's calcMinMax method, but I am not deep enough into the framework to decide if that's a good idea.

**Comment by PhilJay** [comment]
Good spot

**Comment by danielgindi** [comment]
Oh no, this is not the correct thing to do...

**Comment by PhilJay** [comment]
super does not do anything in that case, so it's okay
