### ISSUE TITLE
How to skip x-axis labels inverse?

### ISSUE THREAD

**Issue by cdytoby** [PhilJay/MPAndroidChart#1626]
For example:
I have 10 labels, from 1 to 10, if I set the skip label to 1, it would be 1 3 5 7 9, and the 10 won't be showed, but 1 will always be showed
I want to do it in another way, 10 is always be showed, and display 2, 4, 6, 8, 10, it doesn't matter the first label shows or not.

Is there any way to do this?

**Comment by PhilJay** [comment]
Yes [XAxisValueFormatter](https://github.com/PhilJay/MPAndroidChart/wiki/The-XAxisValueFormatter-interface). You can do whatever you want with it.
