### ISSUE TITLE
Move Realm support to separate artifact?

### ISSUE THREAD

**Issue by paulblessing** [PhilJay/MPAndroidChart#1628]
Not all users of this library need the Realm support. It would be beneficial in terms of library size / method count to have the Realm support be an optional add-on. Would likely remove the need for ProGuard workarounds as well.

**Comment by PhilJay** [comment]
Well, the realm dependency has the `provided` dependency scope. This means that the dependency can only be used for compilation, not in an actual application.

If you want to use the library with realm, you will have to add the realm dependency to your android project, otherwise it will not work. However, you can still use all other library features without adding the realm dependency.

**Comment by PhilJay** [comment]
To show you what I mean I created a small test project with no code in it, and added various dependencies and then created an apk file from it.

 1. This .apk file is from a project without any dependencies (except android support lib)
 2. This .apk file is the same as the first but also has dependency to `MPAndroidChart`
 3. This .apk file has both `MPAndroidChart` and `Realm` dependency

<img width="679" alt="screen shot 2016-03-29 at 18 10 54" src="https://cloud.githubusercontent.com/assets/6759734/14115013/a0bd5626-f5d9-11e5-83d3-203c809288b6.png">

As you can clearly see adding only `MPAndroidChart` only adds 100kb to your apk and allows you to use all features of the library, except realm related.

Only when you add the realm.io dependency, your apk size will increase significantly. But again, this is only required if you need to use the realm specific features of MPAndroidChart.

**Comment by paulblessing** [comment]
I understand that Realm being optional means that I don't need Realm itself as a dependency, but there are several classes in this library now (bringing along additional methods in the overall method count) that anyone who doesn't need Realm is now forced to bundle. No, they don't add thousands of methods or megabytes of size to the app, but to me it's more of a future-proofing suggestion. Keep the core charting library storage-agnostic, and provide add-on modules for Realm and potentially other back-ends in the future. I see it as analogous to Retrofit which has add-on modules for converters (http://square.github.io/retrofit/#restadapter-configuration).
