### ISSUE TITLE
Default View

### ISSUE THREAD

**Issue by amandrews** [PhilJay/MPAndroidChart#1630]
Right now my chart has an x-axis (days) and a y-axis (gallons).

For simplicity, I have created an array of strings "Day1" to "Day30" that I use as my X values. Y values are a random number (just to see varying bar sizes).

Currently: My graph displays all 30 days with random Y values and I am able to zoom in and out, as well as scroll left or right when zoomed in. I am able to zoom out to a max of 30 days and zoom in to a min of 3 days.

What I would like: When my graph is built, I would like for the default view of the graph to only show 7 Days (ex. "Day5" through "Day11") but still be able to scroll left or right on the graph to view the other days 1-30. Is there functionality to do this with MPAndroidChart. Thanks for the help, PhilJay!

**Comment by PhilJay** [comment]
This is what you need: https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport

Have a look at the methods for setting the x-range and moving the view.
