### ISSUE TITLE
PieChart with only 1 data value doesnt show in 2.2.3

### ISSUE THREAD

**Issue by StephenMilone** [PhilJay/MPAndroidChart#1632]
If i have a piechart with only 1 data value, it doesnt show in 2.2.3, just a blank space is shown with the center text.

If I add more values to it, it works just fine.

If i revert to 2.2.2, it works just fine.

Also if i do an animate, the animation works fine, but when it completes, it disappears

**Comment by PhilJay** [comment]
This issue is already fixed, but it' not in the latest release.
There will be a new release the fix in a few days

**Comment by StephenMilone** [comment]
awesome thank you
