### ISSUE TITLE
How to move view to particular index in barchart?

### ISSUE THREAD

**Issue by kamal250** [PhilJay/MPAndroidChart#1634]
Can you please give details to move view to particular index in barchart?
Say for, I have total 10 value in ArrayList and that is assigned to barchart and I want to move my view to 7th position, and my Index=7.
I have tried with `mChart.moveViewToX(index);`, but it is not working as expected.

**Comment by PhilJay** [comment]
What do you expect to happen? What happens?

**Comment by kamal250** [comment]
If I have index=7, then the view should jump to x index 7.

**Comment by PhilJay** [comment]
And what happens?

**Comment by kamal250** [comment]
Not able to change the view with `mChart.moveViewToX(index);`. Nothing changed with this. If I do not use this method, then also it is at the same view.

**Comment by PhilJay** [comment]
The method "Moves the left side of the current viewport to the specified x-index." However, this can only be done of the current x-range allows the view to move any further to the right. If your axis range restricts that, nothing will move.

**Comment by kamal250** [comment]
Yes, that is true. I have changed scaleMinima as `mChart.setScaleMinima(1.60f, 1f);` and it allows to scroll as there are more data.

**Comment by AdityaAnand1** [comment]
Any updates? I simply cannot get the chart to move to the end (to show the most recent data) by any means. @PhilJay please enlighten us 😄
