### ISSUE TITLE
ANR with large datasets on BarChart (Rendering taking about 2 minutes)

### ISSUE THREAD

**Issue by vicmns** [PhilJay/MPAndroidChart#1638]
I'm getting ANR when rendering a BarChart that uses 220 datasets, each one of 36 entries.
Looking at the traces text I'm seeing the following behaviour on the Main Thread
```
"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 obj=0x747d42a0 self=0xb4db6500
  | sysTid=924 nice=0 cgrp=default sched=0/0 handle=0xb6f8bb34
  | state=S schedstat=( 19656044769 24873583239 58675 ) utm=1462 stm=503 core=1 HZ=100
  | stack=0xbe076000-0xbe078000 stackSize=8MB
  | held mutexes=
  kernel: (couldn't read /proc/self/task/924/stack)
  native: #00 pc 00040894  /system/lib/libc.so (__epoll_pwait+20)
  native: #01 pc 00019e6f  /system/lib/libc.so (epoll_pwait+26)
  native: #02 pc 00019e7d  /system/lib/libc.so (epoll_wait+6)
  native: #03 pc 00012c57  /system/lib/libutils.so (android::Looper::pollInner(int)+102)
  native: #04 pc 00012ed3  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+130)
  native: #05 pc 00081ce1  /system/lib/libandroid_runtime.so (android::NativeMessageQueue::pollOnce(_JNIEnv*, _jobject*, int)+22)
  native: #06 pc 0000056d  /data/dalvik-cache/arm/system@framework@boot.oat (Java_android_os_MessageQueue_nativePollOnce__JI+96)
  at android.os.MessageQueue.nativePollOnce(Native method)
  at android.os.MessageQueue.next(MessageQueue.java:323)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
Doing some research (aka Google it) I found out this [post](http://stackoverflow.com/questions/13482883/why-android-treats-an-app-in-anr-when-it-is-in-the-looper-waiting) on StackOverflow. In summary what they said is that the NDK wrapper has a bug when dealing with events from multiple sources, causing ANR's.

My theory is, because our app uses shared element transitions animations, and the library is hardware accelerated by default, the NDK wrapper that handles the rendering thread it's getting multiple rendering events. So in order to corroborate this assumption, I went ahead and turn off the hardware acceleration on the chart, improving the rendering from 2 minutes to 5 seconds...

The funny thing, is that I tried to reproduce this bug using the demo application of the library, but without any luck...
I have a couple of thread traces files, in case that the problem can be pin pointed, but I'm really sure that this is out of the scope of the library.

**Comment by vicmns** [comment]
Finally I was able to reproduce the problem... I created a demo application using the large data set that I mentioned. From time to time the application hangs, sometimes at activity start, other times at activity stop.

I also was able to pinpoint the problem. It's something related to the toolbar... Inside the demo application can be found two layouts for the DetailActivity, the only difference is that in one the Toolbar is Wrapped on a AppBarLayout while in the other not, using the second one will make the application hangs.

Heres the link to the demo project: [Github Repo](https://github.com/vicmns/ChartTest)

**Comment by PhilJay** [comment]
Okay, so the issue is purely related to the toolbar? That's interesting and weird at the same time :-)

**Comment by vicmns** [comment]
Yeah I know! I'm pretty sure there's a bottleneck somewhere on the View Layer implementation that arise particularly on this case... Which is Kind of hard to think, since it should be the opposite case given that we have another extra ViewGroup to render...

Anyhow I'll try to open a bug report on the Android Source project, hoping that real problem can be found.
