### ISSUE TITLE
BarLineChartBase should renderAxisLine after renderGridLines

### ISSUE THREAD

**Issue by vit001** [PhilJay/MPAndroidChart#1639]
Currently the axis line is rendered first, followed by the grid lines. The problem is - if the colors of grid lines and axis lines are different (for example, grid lines are lighter gray), then if a grid line happens to coincide with an axis as a user scrolls the chart, the color of the axis line will flicker from the axis color to the grid line color and back to the axis color.

**Comment by vit001** [comment]
A possible solution is to adjust the clip rectangle when rendering the grid lines, to not allow the grid lines to be drawn over an axis:

```
        int clipRestoreCount = canvas.save();
        RectF contentRect = mViewPortHandler.getContentRect();
        // Adjust the contentrect so the grid lines won't draw over an axis line
        contentRect.left   += 1;
        contentRect.bottom -= 2;
        canvas.clipRect( contentRect );

        mXAxisRenderer.renderGridLines( canvas );
        mAxisRendererLeft.renderGridLines( canvas );
        mAxisRendererRight.renderGridLines( canvas );

        // if highlighting is enabled
        if ( valuesToHighlight() )
            mRenderer.drawHighlighted( canvas, mWhatToHighlight );

        // Restore the content rect
        contentRect.left   -= 1;
        contentRect.bottom += 2;

        // Removes clipping rectangle
        canvas.restoreToCount( clipRestoreCount );
```

**Comment by ardmn** [comment]
I think it is personal case. What about custom renderer or custom viewport and so on ?  at best it should be methods  that return contentRectLeftOffset and  contentRectBottomOffse ...

**Comment by vit001** [comment]
There is no scenario I can think of where the current behavior is preferable.
