### ISSUE TITLE
MarkerView: offset auto-adjustment

### ISSUE THREAD

**Issue by enginebai** [PhilJay/MPAndroidChart#164]
Hi, Phil
I display a `MarkerView` on the line chart, but it's cut when clicking the rightest point. 
![markerview](https://cloud.githubusercontent.com/assets/3387462/4691929/a7fe08fe-573d-11e4-8ec4-d9feba13de3d.png)

I know that there is `setOffsets(x, y)` API which can change the marker offset position, but in this way, I have to detect whether the rightest point is clicked so that I can change the offset.

Is it possible to auto-adjust the marker position so that the marker can display correctly?? Thanks.

**Comment by warptrosse** [comment]
This is a particular workaround:

```
/**
 * Screen width in pixels.
 */
private int uiScreenWidth;

public MyMarker(Context context, int layoutResource)
{
    super(context, layoutResource);
    uiScreenWidth = getResources().getDisplayMetrics().widthPixels;
}

@Override
public void draw(Canvas canvas, float posx, float posy)
{
    // Check marker position and update offsets.
    int w = getWidth();
    if((uiScreenWidth-posx-w) < w) {
        posx -= w;
    }

    // translate to the correct position and draw
    canvas.translate(posx, posy);
    draw(canvas);
    canvas.translate(-posx, -posy);
}
```

NOTES:
1) I get the width of the screen just one time and never update it because my application will run only in portrait mode. (Update the value of the variable "uiScreenWidth" when drawing if the screen width changes dynamically or by other reason).
2) I just want to adjust the X position of the marker... again, if you want, you can change the position of both axis dynamically of based in other parameters you want.

**Comment by ohpoloha** [comment]
Hi Phil,
Where to adjust x-values array? I can't find it. 

Thanks,
Bruce

**Comment by ohpoloha** [comment]
I see what you mean now. please disregard my previous question

**Comment by PhilJay** [comment]
http://stackoverflow.com/questions/30169327/markerview-goes-out-of-the-chart-for-the-last-point-on-the-chart

**Comment by YangQiRen** [comment]
The following URL can give you a reference：
https://www.jianshu.com/p/ca0246f5f1fb

**Comment by mak1nt0sh** [comment]
@warptrosse 

This switched my marker too soon. If you want your marker switched to other side of highlighted entry when marker view doesn't fit, use: 

`if (resources.displayMetrics.widthPixels - posx < w) {
                posx -= w.toFloat()
            }`

**Comment by Bunty-petiwala** [comment]
@warptrosse thank's 

public class CustomMarkerView extends MarkerView {

    private TextView tvContent;
    private Context mContext;

    public CustomMarkerView(Context context, int layoutResource) {
        super(context, layoutResource);
        this.mContext = context;
        tvContent = findViewById(R.id.txt_value);
    }

    @SuppressLint("SetTextI18n")
    @Override
    public void refreshContent(Entry e, Highlight highlight) {
        Log.e("Text", " : " + Math.round(e.getY()));
        tvContent.setText("" + Math.round(e.getY()));
    }


    @Override
    public void draw(Canvas canvas, float posx, float posy) {

        WindowManager windowManager = (WindowManager) mContext.getSystemService(Context.WINDOW_SERVICE);
        Display display = windowManager.getDefaultDisplay();
        Point size = new Point();
        display.getSize(size);
        int width = size.x;

        int w = getWidth();
        if ((width - posx - w) < w) {
            posx -= w;
        }
        canvas.translate(posx, posy);
        draw(canvas);
        canvas.translate(-posx, -posy);
    }

}

**Comment by mostafaimran** [comment]
```
override fun getOffsetForDrawingAtPoint(posX: Float, posY: Float): MPPointF {
        if (posX > chartView.width - width) {
            offset.x = (-width).toFloat()
        } else {
            offset.x = (-(width / 2)).toFloat()
        }

        offset.y = -(height / 2).toFloat()

        return offset
    }
```

You need to set chart view to `MarkerView.chartView` before calculation.
