### ISSUE TITLE
"Description" in right bottom bar chart

### ISSUE THREAD

**Issue by CW29** [PhilJay/MPAndroidChart#1640]
Hello, I have an issue with a barchart. I have a "Description" label in the right bottom of the bar chart but I don't no why. I try to disable all kind of things but it is still there.

![barchart](https://cloud.githubusercontent.com/assets/15063633/14203021/c50c2aba-f7fb-11e5-9c91-df8a513a1932.png)

**Comment by PhilJay** [comment]
`chart.setDescription("")`

**Comment by Nfear** [comment]
`setDescription(String)` was not available to me, but `setDescription(Description)` was.

So I had to use:

    Description description = new Description();
    description.setText("");
    binding.chart.setDescription(description);

**Comment by prathibhaprabs** [comment]
`         mChart.getDescription().setText("abcd");
`

**Comment by myatmon** [comment]
description.setPosition(1f,0f); won't work in bar chart

**Comment by Pygmalion69** [comment]
You can disable the description:
```
mChart.getDescription().setEnabled(false);
```
