### ISSUE TITLE
Bug: Line chart fill color on pre API 21 devices.

### ISSUE THREAD

**Issue by Blodgard** [PhilJay/MPAndroidChart#1642]
I have found this problem:
![screenshot_2016-04-02-01-00-55 1](https://cloud.githubusercontent.com/assets/11709402/14222243/9cdef8ba-f86e-11e5-94c5-e167d60b2d7e.png)
The fill color does not follow the data.

This is the method that causes problem in my pre lollipop device.
`dataSet.setDrawFilled(true);`

In a device with api 21+ all works.

If there is a workaround until the fix please let me know it because it's really ugly to see the chart without a Fill color.

**Comment by PhilJay** [comment]
Library version?

**Comment by Blodgard** [comment]
You are right, I'm using an old version of the library.
thanks

**Comment by Blodgard** [comment]
Why you have closed it? 
This is a relevant problem I think.

I've executed more try and it work also in emulator with API 15. 
The problem happen in my Samsung mini GT-I9195 with android 4.4.2
