### ISSUE TITLE
Dot placement in multilinechart  

### ISSUE THREAD

**Issue by danzhu10** [PhilJay/MPAndroidChart#1643]
I have multilinechart which display data from json. But dot placement is not match with the value. This the result. Dot 199 set in yValue 220
![line](https://cloud.githubusercontent.com/assets/10788806/14231141/e683ce5c-f9a2-11e5-809f-9d2e05031abb.PNG)
Please help me

**Comment by PhilJay** [comment]
The blue line dots are correct. My wild guess is (since you did not provide any code), that you are plotting the red line against the right (invisible) axis.

So call `redLineDataSet.setAxisDependency(AxisDependency.LEFT)`
