### ISSUE TITLE
No YAxisLabels when no integers

### ISSUE THREAD

**Issue by warmax** [PhilJay/MPAndroidChart#1645]
First screenshot is from master branch and second from an older release:

![labels](https://cloud.githubusercontent.com/assets/9325874/14232250/d2e7d798-f9a3-11e5-893f-e6671703f8b5.png)

Tried with setLabelCount but id didn't make any difference.

Regards

**Comment by PhilJay** [comment]
This could be related to the new granularity feature that allows to control the minimum interval of the y-axis.

Please try `leftYAxis.setGranularity(0.01f)` and let me know if that resolves your issue.

**Comment by MarcSalvat** [comment]
Yes, it fixed it.

Thanks

**Comment by MarcSalvat** [comment]
Yes, it fixed it.

Thanks

**Comment by warmax** [comment]
Yes, it fixed it.
Thaks

(Sorry for spam used my other account :D)

**Comment by PhilJay** [comment]
@danielgindi as the default value of 1 sometimes can lead to confusion, what do you think about auto-calculating this (just like axis min max)?

**Comment by danielgindi** [comment]
Well this value should depend on the output of the formatter, and maybe other user choices.
So I think it should just be defaulted to `false`

**Comment by PhilJay** [comment]
You mean granularityenabled = false?

Yes, we could do that. I have written a simple "logic" which now auto calculates the granularity. It' basically just the axis interval divided by 10. 
This can be improved but also should be sufficient for most cases (and definitely more sufficient than just setting it to 1 per default).

However I think that we still should set granularityenabled to false per default.

What do you say?

**Comment by danielgindi** [comment]
I think that granularity should stay completely manual, people can do a simple calculation based on their formatters... Otherwise the would start opening many issues about this like this one :-)

**Comment by PhilJay** [comment]
You are right. I will remove it again :-)
This was stupid.

**Comment by danielgindi** [comment]
Not stupid, it's just that we don't have the money to hire enough people to answer those issues ;-)

**Comment by PhilJay** [comment]
Yeah. :-)
It's tough to answer all as it is. The hardest part actually is to figure out wether the issue is real or just caused by incompetence.
