### ISSUE TITLE
Y Axis Labels overlap with BarChart values

### ISSUE THREAD

**Issue by puneetakhouri** [PhilJay/MPAndroidChart#1646]
No changes done to the library and using the horizontal barchart, the labels of the bar tend to overlap the Y axis labels.
PFA the attached screenshot
<img width="426" alt="screen shot 2016-04-04 at 12 38 47 pm" src="https://cloud.githubusercontent.com/assets/10497275/14240453/b573fdbc-fa62-11e5-981b-bf189fdda7cd.png">

In the screenshot, the topmost Y axis label "Ester" and the bar value -2.2 tend to overlap.

**Comment by PhilJay** [comment]
`yAxis.setSpaceTop(...)`
