### ISSUE TITLE
piechart items border

### ISSUE THREAD

**Issue by MohammadRezaRahmatzadeh** [PhilJay/MPAndroidChart#1649]
hi
when i use custom color for piechart items for example i use green for all of them , the border of items is not clear and they seen as one item with multi labels
how can i enable items border to solve this issue
thanks a lot ,

**Comment by PhilJay** [comment]
`pieDataSet.setSliceSpace(...)`

**Comment by MohammadRezaRahmatzadeh** [comment]
Thank You Man ...
