### ISSUE TITLE
MPAndroidChart X Axis Label not wrapping

### ISSUE THREAD

**Issue by SutharRohit** [PhilJay/MPAndroidChart#1654]
I am using BarChart by MPAndroidChart in my project.

I have some long labels in X Axis. as shown in a following screen shot.

I want to do wrap X axis label in multi-line.

![screenshot_2016-04-06-11-35-13](https://cloud.githubusercontent.com/assets/5028584/14307810/4c650166-fbef-11e5-84f2-85ffe3912aec.png)

**Comment by thadeubatista** [comment]
hi, can you put the name of Chart and the configuration that you are using?

**Comment by PhilJay** [comment]
Multiple line labels are not supported yet.

**Comment by FranPrin** [comment]
Are they still not supported?

**Comment by mecoFarid** [comment]
@FranPrin Quite sure the project is already dead. I don't think there will be major changes, anyway
