### ISSUE TITLE
No labels on zero line

### ISSUE THREAD

**Issue by ditzdragos** [PhilJay/MPAndroidChart#1655]
Hi, I need to show the labels only on the zero line. I tried using two separate charts, one for positive and one for negative, but is device dependant, and I cannot assure a match on all devices, as I support both phones and tablets.

**Comment by PhilJay** [comment]
Use [YAxisValueFormatter](https://github.com/PhilJay/MPAndroidChart/wiki/The-YAxisValueFormatter-interface).

```java
    @Override
    public String getFormattedValue(float value, YAxis yAxis) {
        
        if(value == 0) return "0";
        else return "";
    }

````

**Comment by ditzdragos** [comment]
Not like this, On the X Axis. Now you can put the labels in: TOP,TOP INSIDE,BOTTOM,BOTTOM-INSIDE and BOTH. I need it only on the 0 X axis

**Comment by takaoandrew** [comment]
Same issue for me!
@ditzdragos Did you ever figure out how to do this?
https://stackoverflow.com/questions/55661121/setting-the-x-axis-position-to-y-0-in-mpandroid-bar-chart

**Comment by ditzdragos** [comment]
@takaoandrew Unfortunately, it was a long time ago and I don't remember how we managed to get past this impediment. I hope you find a way to solve it!

**Comment by takaoandrew** [comment]
@ditzdragos No worries, thanks for letting me know!

**Comment by takaoandrew** [comment]
If anyone else is struggling with this, I used the following
MPPointD pos = mTrans.getPixelForValues(0f, 0f);
c.drawLine(mViewPortHandler.contentLeft(),
                (float)pos.y, mViewPortHandler.contentRight(),
                (float)pos.y, mAxisLinePaint);
