### ISSUE TITLE
Stacked Bar chart Unable to set legends and colors to separate bars

### ISSUE THREAD

**Issue by Sutirth** [PhilJay/MPAndroidChart#1659]
mSweatPointChart.getAxisRight().setEnabled(true);

        Legend l = mSweatPointChart.getLegend();
        l.setPosition(Legend.LegendPosition.BELOW_CHART_LEFT);
        l.setFormSize(8f);
        l.setFormToTextSpace(4f);
        l.setXEntrySpace(6f);

  ArrayList<BarEntry> yVals3 = new ArrayList<BarEntry>();
  for(int i = 0; i <sweatPointFitnessResults.size() ; i++){

                    String forday_split[] = sweatPointFitnessResults.get(i).getForday().toString().split("-");
                    String eachDay = forday_split[2];

                        double valueSweatPoints;
                        float actualSweatPoints = 0;
                        double valueGoalsSweatPoints;
                        float actualGoalSweatPoints = 0;

                        double valueBadgeSweatPoints;
                        float actualBadgeSweatPoints = 0;
                        valueSweatPoints = Double.valueOf(sweatPointFitnessResults.get(i).getSweatpoints());
                        actualSweatPoints = (float) valueSweatPoints;
                        valueGoalsSweatPoints = Double.valueOf(sweatPointFitnessResults.get(i).getGoalSweatPoints());
                        actualGoalSweatPoints = (float) valueGoalsSweatPoints;

 valueBadgeSweatPoints = Double.valueOf(sweatPointFitnessResults.get(i).getBadgeSweatPoints());
                            actualBadgeSweatPoints = (float) valueBadgeSweatPoints;

                        yVals3.add(new BarEntry(new float[]{actualSweatPoints, actualGoalSweatPoints, actualBadgeSweatPoints}, Integer.valueOf(eachDay) - 1));

            }

 BarDataSet setSweatPoints = new BarDataSet(yVals3, " ");
          //  setSweatPoints.setColor();
            setSweatPoints.setColor(getResources().getColor(R.color.graph_calories_count),getResources().getColor(R.color.step_count_text));
            setSweatPoints.setStackLabels(new String[]{"Sweatpoints", "GoalsSweatPoints"});
            setSweatPoints.setBarSpacePercent(35f);
            ArrayList<IBarDataSet> dataSetSweatPoints = new ArrayList<IBarDataSet>();
            dataSetSweatPoints.add(setSweatPoints);
            BarData dataSweatPoints = new BarData(getXAxisValues(), dataSetSweatPoints);
            dataSweatPoints.setValueTextSize(10f);
            dataSweatPoints.setHighlightEnabled(false);
            dataSweatPoints.setDrawValues(false);
            mSweatPointChart.setData(dataSweatPoints);
            mSweatPointChart.invalidate();

The above is my following code. Using this legend name is not displayed nor stacked bar chart with different colors are displayed. Though addition 3 values are done properly and shown in chart.

**Comment by PhilJay** [comment]
You did not provide a name for your dataset, so you have no legend label:

`BarDataSet setSweatPoints = new BarDataSet(yVals3, " ");`

**Comment by Sutirth** [comment]
Hi @PhilJay I tried entering text but still I am unable to get legends and I tried setting color like this as well
 setSweatPoints.setColor(getResources().getColor(R.color.graph_calories_count),getResources().getColor(R.color.step_count_text),getResources().getColor(R.color.well_done_color));

still unable to do so

**Comment by issacchern** [comment]
Same here. They are there before and for some reasons, it's not there anymore. Still looking for answer now...

**Comment by Sutirth** [comment]
Hi @PhilJay  Any help ???
