### ISSUE TITLE
Bug in background Color because error in PieChart when percent equal 0,0%

### ISSUE THREAD

**Issue by TheLGameS** [PhilJay/MPAndroidChart#1660]

**Comment by PhilJay** [comment]
The issue is related to the `slicespace` --> `pieDataSet.setSliceSpace(...)`

If the "size" of the slice-space exceeds the size of a pie slice, this issue occurs. I suggest you remove the slice space if you have extremely small slices.

**Comment by TheLGameS** [comment]
done and worked.. thank you

**Comment by cuizaixi** [comment]
thanks , did work

**Comment by IvanSimovic** [comment]
What if not setting SliceSpace is not a option?
I was thinking of adding extra entries to simulate these spaces, but those spaces get their X value written out 2, which is a problem. is it possible to write out every second x value,
dataSet.setXValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE); //For everyone other?

Or can you recommand a different solution?

**Comment by rkrsgithub** [comment]
When i add 3 pie entries with whole 3 have value 1. the graph is completely empty. when we click on a slice its get highlighting . It will be very helpful to me if can give me a solution for this. Thanks
