### ISSUE TITLE
Bar Entry minimum Y axis value

### ISSUE THREAD

**Issue by danponce** [PhilJay/MPAndroidChart#1661]
Hi!

Is there any chance to make a bar chart like the picture? I think that if the Bar Entry had a minimum Y axis value I could do this.

![captura de pantalla 2016-04-06 a las 2 57 58 p m](https://cloud.githubusercontent.com/assets/5649731/14327288/016e778c-fc08-11e5-9fd8-24260f672cea.png)

**Comment by PhilJay** [comment]
This is not directly possible.

However there is a hack that will allow you to get there:

You could use stacked bars and simply draw the bar that occupys the space that you want to leave out in the color of the background.
