### ISSUE TITLE
How to set one particular bar's color

### ISSUE THREAD

**Issue by kamal250** [PhilJay/MPAndroidChart#1662]
Hello Philipp,

I have added data to barchart as: 

`for(int i=0;i<10;i++){
        xVals.add(i);
        yVals1.add(new BarEntry(i*10, i));
}

BarDataSet set1 = new BarDataSet(yVals1, "Number");
ArrayList<IBarDataSet> dataSets1 = new ArrayList<IBarDataSet>();
dataSets1.add(set1);
BarData data = new BarData(xVals, dataSets1);
mChart.setData(data);`

**Now my question is that: if I want to change the bar color of 2nd and last bar, then how can I change it?**

**Comment by PhilJay** [comment]
```java
if(index == specificIndex) colors.add(Color);
else colors.add(NormalColor);
```

**Comment by kamal250** [comment]
Can you please elaborate more?

**Comment by PhilJay** [comment]
Inside your for loop that adds the entries, place this code.

**Comment by kamal250** [comment]
Like this? set1.addColor(Color.parseColor("#878686"));

**Comment by kamal250** [comment]
Thanks, it is working.

**Comment by hi-manshu** [comment]
the above code didn't work for me.
i Tried 
if (j == 6) {
                    Bardataset.setColors(new int[]{Color.parseColor("#2DC9D7")});
                    Bardataset.setHighLightColor(Color.parseColor("#2DC9D7"));
                } else {
                    Bardataset.setColor(Color.parseColor("#000000"));
                    Bardataset.setHighLightColor(Color.parseColor("#000000"));
                }

**Comment by nimish17** [comment]
@PhilJay can you please help me for reduce space between bars? i need remove space between all bars

**Comment by almic** [comment]
@hi-manshu and @nimish17 please do not necropost of such old issues, especially not with useless comments like code spam and off-topic questions.
