### ISSUE TITLE
Animation in PieChart using old data

### ISSUE THREAD

**Issue by Sheradil** [PhilJay/MPAndroidChart#1663]
Hey,

maybe it is already implemented and I just didn't see it:

It would be a nice feature if there would be an option to upgrade an existing data set.
I will give you an example:

There is a set with X=1 and Y=2 in the PieChart.
Then there is an update incoming, changing the value of X to 3.

As far as I can see the only possible way to achieve this is to generate a new data set and apply it to the chart (Or remove the old X-entry and insert a new one). The chart then completely redraws and the drawing starts at X=0,Y=0 until it reaches X=3/Y=2..

A nice feature would be to change the existing data set to X=3 and the chart automaticly animates from the old view to the new one instead of erasing the old one and generating a new one. The animation should smoothly animate from X=1/Y=2 to X=3/Y=2 instead of creating a new chart where the chart animates to X=3/Y=2 from X=0/Y=0.

Greetings
Shera

**Comment by hendrep** [comment]
Is this possible?
