### ISSUE TITLE
PieChart filling bug for small-value part.

### ISSUE THREAD

**Issue by kaftanati** [PhilJay/MPAndroidChart#1665]
2.2.2 - all ok
![2016-04-08 09 23 54](https://cloud.githubusercontent.com/assets/11496817/14379871/226706ba-fd85-11e5-9b1a-56e2964fa3f1.jpg)

2.2.3 bug exist
![2016-04-08 09 28 16](https://cloud.githubusercontent.com/assets/11496817/14379909/64ddd834-fd85-11e5-9937-7a488e389d6e.jpg)

2.2.4 another bug exist
![2016-04-08 09 15 57](https://cloud.githubusercontent.com/assets/11496817/14379875/254b5a16-fd85-11e5-8b1f-56d74e221ac7.jpg)

P.S. Total amount is about 75000, value with error - 200.

**Comment by PhilJay** [comment]
This issue is related to slice space. I evaluated how to fix it here: #1660
