### ISSUE TITLE
y-axis grid spacing

### ISSUE THREAD

**Issue by marcio-granzotto-ckl** [PhilJay/MPAndroidChart#1666]
I've a chart that shows values between 1.023 and 1.027, I wanted to set the horizontal grid lines spacing to 0.001, but YAxisRenderer.computeAxisValues calls roundToNextSignificant(rawInterval), so it only supports integer intervals.

There's any workaround this?

**Comment by vit001** [comment]
I submitted this bug earlier, with a detailed bugfix, in Issue #1607. Unfortunately, the issue was closed and the fix not applied.

**Comment by PhilJay** [comment]
This code:

```java
        YAxis leftAxis = mChart.getAxisLeft();
        leftAxis.setLabelCount(6, true);
        leftAxis.setAxisMinValue(1.023f);
        leftAxis.setAxisMaxValue(1.027f);
        leftAxis.setGranularityEnabled(true);
        leftAxis.setGranularity(0.001f);
```

Leads to the following result for me:
![screen shot 2016-04-09 at 14 41 14](https://cloud.githubusercontent.com/assets/6759734/14403669/260e8234-fe61-11e5-8e6e-76cda35a213a.png)


Do you expect something different?

**Comment by vit001** [comment]
The problem appears if you don't setGranurality. You cannot setGranurality if you allow y zoom.

**Comment by PhilJay** [comment]
Sure you can set granularity if you allow y-zoom. That's the whole purpose of the feature.

**Comment by vit001** [comment]
Sorry, maybe I don't understand the feature. Why do I have to set the
granularity at all? Why can't it be calculated automatically?

**Comment by PhilJay** [comment]
The granularity allows you to define the point at which the labels are no longer re-calculated. As an example, if you defined your axis to have zero decimal digits, you want to set your granularity to 1, which means the minimum allowed interval on the axis is 1, and no labels are duplicated.

**Comment by vit001** [comment]
OK. The default behavior when not setting any granularity, should still produce a correct chart though. As is, it does not. If you apply the fix I suggested in #1607.this bug will go away.

**Comment by marcio-granzotto-ckl** [comment]
This doesn't make sense. I'm giving an example of values here, but the user's data could be within any range. The chart should find out the granularity by itself.

**Comment by marcio-granzotto-ckl** [comment]
Also, why the granularity doesn't work if I set `.setLabelCount(2, true)` or `.setShowOnlyMinMax(true)`? I need to have the horizontal grid lines but only the min and max labels. The grid lines only show for intervals of 1, even when I set the granularity to 0.001f

**Comment by rabiyawaseem94** [comment]
i want to set the scaling of x axis as well. is it possible ?

**Comment by donnahmarizh** [comment]
Hi,
![screenshot_20170526-145309](https://cloud.githubusercontent.com/assets/3504610/26486995/13c88142-4230-11e7-9bd3-6aaba371ae5e.png)

![screenshot_20170526-145251](https://cloud.githubusercontent.com/assets/3504610/26487120/b16a55f6-4230-11e7-834e-5067a52b8754.png)

I have set the chart with setAxisMinimum(0f) so that there wont be spacing below 0 but most data aren't aligned to the y-axis lines. How do you set the data into non-negative and to be started with 0?

**Comment by aldiandika** [comment]
How do I set intervals for x-axis, my data is real time data which is x-axis is "time" data, and I want to show x axis with current interval, is there the way to do that ?

tahnk you very much
