### ISSUE TITLE
How to wrap around plotting once it reaches the maximum window in a Line Chart?

### ISSUE THREAD

**Issue by gdsomia** [PhilJay/MPAndroidChart#1672]
Could you please help me to wrap around plotting once it reaches the full window. Instead of appending data to right I need to start back from the left and continue plotting when it reaches the full window.

 private void addEntryGraph4(int ch0[], int ch1[]) {
        data = graph4.getLineData();
        if (data != null) {
            ILineDataSet set = data.getDataSetByIndex(0);
            if (set == null) {
                set = createSet();
                data.addDataSet(set);
            }
            data.addXValue("");
            for (int i = 0; i < ch0.length; i++)
                data.addEntry(new Entry((float) (ch0[i]), set.getEntryCount()), 0);
            graph4.notifyDataSetChanged();
            graph4.setVisibleXRange(ch0.length * 3, ch0.length * 3);
            graph4.moveViewToX(data.getXValCount() - 10);
        }
    }

**Comment by PhilJay** [comment]
I guess those two wiki entries will help you:

 - [Dynamic and realtime data](https://github.com/PhilJay/MPAndroidChart/wiki/Dynamic-&-Realtime-Data)
 - [Modifying the viewport](https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport)

**Comment by gdsomia** [comment]
Phil, I am able to move to a specific X value but unable to plot the data. What I wanted is to plot the data like an ecg wave..
