### ISSUE TITLE
how to show markerview in mpandroidchart

### ISSUE THREAD

**Issue by eycrckag** [PhilJay/MPAndroidChart#1674]
I got a question . For example in the demo of LineChartActivity1 MyMarkerView, default is not show, only after clicking, to show, but I think, to make this MyMarkerView default show

**Comment by PhilJay** [comment]
You can just call `chart.highlightValue(...)` at startup and the provided entry will be highlighted.

https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart

**Comment by eycrckag** [comment]
I'm sorry , I didn't speak clearly, I want to get into this LineChartActivity1, can see MyMarkerView directly
