### ISSUE TITLE
Delay in plotting real time data

### ISSUE THREAD

**Issue by gdsomia** [PhilJay/MPAndroidChart#1676]
I need to plot real time data using line graph. I have 240 values in a second to be plotted. But the plotting is too slow and it takes more than 5 seconds to plot the data of a second. How is it possible to do the plotting of 1 second data in one second itself?

    private void addEntryGraph1() {
        LineData data = graph1.getLineData();
        if (data != null) {
            ILineDataSet set = data.getDataSetByIndex(0);
            if (set == null) {
                set = createSet();
                data.addDataSet(set);
            }
            data.addXValue(new SimpleDateFormat("HH:mm:ss")
                    .format(new Date(System.currentTimeMillis())));
            for (int i = 0; i < sampleRatio; i++)
                data.addEntry(new Entry((float) (ch1Buffer.get(i)), set.getEntryCount()), 0);
            graph1.notifyDataSetChanged();
            graph1.setVisibleXRange(240, 240);
            graph1.moveViewToX(0);
            synchronized (ch1Buffer) {
                ch1Buffer.subList(0, sampleRatio).clear();
            }
        }
    }

**Comment by PhilJay** [comment]
The answer is quite simple: Plotting 240 values per second is not gonna work (or at least not for very long), even on a high end device. The library is not feasible for that amount of data plotted at realtime.

You can improve performance by removing any unnecessary styling from your chart and reducing the number of values plotted per second.

**Comment by gdsomia** [comment]
Thanks Phil.. I will choose another plotting library.

**Comment by balamurugannatarajan** [comment]
"The answer is quite simple: Plotting 240 values per second is not gonna work (or at least not for very long), even on a high end device. The library is not feasible for that amount of data plotted at realtime.

You can improve performance by removing any unnecessary styling from your chart and reducing the number of values plotted per second."

still, the limitation persists in the latest library. I need to show 1000 values per second. shall I proceed to implement your library?

**Comment by balamurugannatarajan** [comment]
@PhilJay Did you have any chance to review my last post?

**Comment by hamid44** [comment]
Hello @gdsomia .
Do you find any other library to solve your problem? I have similar problem.

**Comment by Tufan21** [comment]
hello @gdsomia @hamid44 do you find any other library, i am plotting 360 data in a second , it is slow for some device

**Comment by hamid44** [comment]
@Tufan21 , hi , i was using that long time ago , but i did my work by this library v2.2.4 . unfortunately I forgot how my problem was solved.
