### ISSUE TITLE
How do I hide labels in X asix when I have too many values

### ISSUE THREAD

**Issue by hongsonitptit** [PhilJay/MPAndroidChart#1677]
Hi,
My problem is I have too many values to display in X axis, so these labels is very close as picture (a).
![a](https://cloud.githubusercontent.com/assets/5134089/14463799/b2ce388a-00f6-11e6-994c-4101c4ff6ba1.png)
(a)
I wanna hide all labels as picture (b) or some of them to make more space between these labels.
![b](https://cloud.githubusercontent.com/assets/5134089/14463800/b2dc523a-00f6-11e6-8081-8396cba563a7.png)
(b)
And If all of labels is hide, I also wanna display labels again when user zoom the chart as picture (c)
![c](https://cloud.githubusercontent.com/assets/5134089/14463801/b2de2e0c-00f6-11e6-9d4d-4c400948debb.png)
(c)
How can I do that?
Thanks

**Comment by hongsonitptit** [comment]
![a](https://cloud.githubusercontent.com/assets/5134089/14463789/9e8bb3ca-00f6-11e6-939e-7ec70ee1c050.png)
![b](https://cloud.githubusercontent.com/assets/5134089/14463791/9e94efe4-00f6-11e6-892a-1882ca20c8e9.png)
![c](https://cloud.githubusercontent.com/assets/5134089/14463790/9e92093c-00f6-11e6-8b3d-751208c8ca4c.png)

**Comment by TimAimee** [comment]
use  xAxis.setLabelsToSkip(4);

**Comment by hongsonitptit** [comment]
@TimAimee 
Thanks for your comment, but my data is dynamic (i could not know size of it), so the solution of hard code is not the best.
I want to find other better solution

**Comment by TimAimee** [comment]
@hongsonitptit 
 also can use it .when you change the datasize ,you also change the value at xAxis.setLabelsToSkip(value);
just like this;
private void changeChartView(Arraylist<Integer> data){
     int dataLength=data.size();
     int value=data/10,//or another,you just try!
     mChart.getxAxis.setLabelsToSkip(value);
}

**Comment by hongsonitptit** [comment]
@TimAimee 
Oh I have found the best and simple solution by do not use setLabelsToSkip() function and the library create labels automatically in X axis depend on my data size (these labels will not stacked together)

**Comment by PhilJay** [comment]
Exactly, so setting this to e.g. "4" takes your data size into account.
