### ISSUE TITLE
the textValue  is cover  in RadarChart

### ISSUE THREAD

**Issue by TimAimee** [PhilJay/MPAndroidChart#1679]
http://7pn5vy.com1.z0.glb.clouddn.com/device-2016-04-13-114804.png

the textvalue is cover ,what should i do.

**Comment by PhilJay** [comment]
Which values do you mean?

**Comment by TimAimee** [comment]
you can see the friday[67,62] ,the two textvalue  is overlap,the same thing at saturday[67,61].

**Comment by PhilJay** [comment]
Well the only thing you can do is decrease the range of your chart, which will put the values further apart.
Other than that, you can decrease the text size.
