### ISSUE TITLE
Support for lines drawn to pie values 

### ISSUE THREAD

**Issue by Scrounger** [PhilJay/MPAndroidChart#1681]
@danielgindi:

Trying to use:

        dataSet.setValueLinePart1OffsetPercentage(80.f);
        dataSet.setValueLinePart1Length(0.4f);
        dataSet.setValueLinePart2Length(0.5f);
        // dataSet.setXValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);
        dataSet.setYValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);

but it says that "_.setValueXXX_" cannot be resolved.

**Comment by PhilJay** [comment]
This feature can just be found in the latest commits on the master branch, it is not in a release version (v2.2.4) yet!
Next release will be out soon!

**Comment by Scrounger** [comment]
@PhilJay 
Ahh, ok thanks for the hint!
