### ISSUE TITLE
DataSet setYVals alternative?

### ISSUE THREAD

**Issue by peswanibros** [PhilJay/MPAndroidChart#1683]
setYVals method has been removed from DataSet class in the library. is there any alternative to it?

**Comment by jorgecasariego** [comment]
+1

**Comment by AzerTyQsdF** [comment]
File ==> New == > Import Module ==> PathToMPAndroidChart/MPChartLib 
compile project in gradle:
compile project(':MPChartLib')

Dont know why setYVals was removed.

**Comment by manoj2791** [comment]
For me the below code worked
   mChart.notifyDataSetChanged();
        mChart.invalidate();

**Comment by viraj-tank-sociomantic** [comment]
+1

**Comment by PhilJay** [comment]
It has not been removed. But you are working with the interface that does not expose setters.

Cast your `ILineDataSet` to `LineDataSet` and you will have access to all setter methods.
