### ISSUE TITLE
setDescription(String desc) does not work

### ISSUE THREAD

**Issue by JPMJPM** [PhilJay/MPAndroidChart#1685]
Hi,

I'm starting to develop a LineChart but I have a problem:

The XML is (inside a FrameLayout) :

<com.github.mikephil.charting.charts.LineChart
        android:id="@+id/chart"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

The JAVA code is (inside onCreate) :

LineChart mychart = (LineChart) findViewById(R.id.chart);
mychart.setBackgroundColor(Color.CYAN);  ----> OK, the whole screen is cyan with "No chart data available." in the center.
mychart.setDescription("HELLO WORLD");  ----> This string does not appear in the bottom right corner of the screen.

Any help ?

Best regards and thanks in advance.

**Comment by JPMJPM** [comment]
Sorry, the copy&paste failed, XML is :

<com.github.mikephil.charting.charts.LineChart
        android:id="@+id/chart"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

**Comment by vit001** [comment]
Unrelated but a request to the devs: please make the argument to setDescription and similar methods a CharSequence not String. I have Spans I need to use in texts.
