### ISSUE TITLE
Multiple Data Point Vertical Graphs

### ISSUE THREAD

**Issue by bkerensa** [PhilJay/MPAndroidChart#1688]
Any chance you can add support for this style of graphing? It is easier to track multiple data points in say a single day with this style of chart.

![screen shot 2016-04-17 at 11 15 42 pm](https://cloud.githubusercontent.com/assets/859175/14595216/6fe178e8-04f2-11e6-97e7-cfcb526b3dd2.png)

**Comment by PhilJay** [comment]
Looks quite cool tbh. Does that kind of chart have a name?
I guess it shouldn't take too long to make this, I'll keep it in mind.

**Comment by bkerensa** [comment]
@PhilJay I do not know if it has a name but for Glucosio which uses MPAndroidChart one issue we run into is displaying multiple glucose entries per day in a single chart. This chart style solves that issue by having dots for each data point plotted vertically and with dates below and values to the right.

Thanks for considering this!
