### ISSUE TITLE
Ensure the last axis label is displayed.

### ISSUE THREAD

**Issue by tomasKa** [PhilJay/MPAndroidChart#1689]
Hi I am using bar chat and the last Xaxis label is never displayed. Is there the way to ensure that the first and the last labels are displayed? ( **setLabelsToSkip** and **setAvoidFirstLastClippingEnabled**) does not really solve my problem.

**Comment by PhilJay** [comment]
Not really unfortunately. However, the new v3.0.0 which will be out in a few weeks will allow to treat the x-axis like y-axis, and then you can ensure to draw all values you need.

**Comment by shashank090789** [comment]
@tomasKa did you able to do it?

**Comment by CodeDakait** [comment]
hi philjay 

i am using mpandroidchart and i want to try show the last point of the line graph on a textview. How can i do this.
