### ISSUE TITLE
New features not being downloaded 

### ISSUE THREAD

**Issue by joaovq** [PhilJay/MPAndroidChart#1690]
Hi, I started using MPAndroidChart and I'm downloading it from grandle. However, I saw some features in the sample which I'm not able to use with the current version I have. For example the new feature of placing the percent values outside the pie chart. Is it already available?

**Comment by PhilJay** [comment]
This is because the current master branch is ahead of the latest release. A new release will be out soon.

**Comment by joaovq** [comment]
Ok. Thank you
