### ISSUE TITLE
After the Legend set not centered

### ISSUE THREAD

**Issue by lvtanxi** [PhilJay/MPAndroidChart#1696]
Hello, in the use of MP, reference library version for 2.2.4, when using the PieChart Legend is set to the legend. LegendPosition. BELOW_CHART_CENTER, always can't center, is this why?You are not using this in the demo version of the

**Comment by BalalakshmiSadhasivam** [comment]
+1

**Comment by PhilJay** [comment]
This issue is already fixed in the latest commits. A new release will be out soon.

**Comment by lvtanxi** [comment]
不好意思，我还还有一个问题。Legend在item很多的时候能不能自动换行显示呢？Legend能不能设置显示或者隐藏呢？

**Comment by lvtanxi** [comment]
I'm sorry, but I still have one more question.Legend in the item a lot of time can automatically display a new line?Legend can set show or hide?
