### ISSUE TITLE
Combined Chart with Bar Chart with group Data set after adding line chart the x-axis showing improperly. 

### ISSUE THREAD

**Issue by Deepak1202** [PhilJay/MPAndroidChart#1697]
When i try adding line chart to combined chart ,the x axis are getting closer according to line chart but the bar chart has grouped dataset and that becomes improper.

**Comment by ardmn** [comment]
Hello. Can you show source code ?

**Comment by PhilJay** [comment]
Grouped barcharts are not yet supported in a combinedchart. This feature will be available when v3.0.0 is out in a few weeks.
