### ISSUE TITLE
How to draw 3 YAxis in one LineChart

### ISSUE THREAD

**Issue by luffy3** [PhilJay/MPAndroidChart#1705]
I want to draw LineChart like below picture, but I find the library can only draw 2 YAxis. Is there anyone who can help me?
![problem](https://cloud.githubusercontent.com/assets/8219682/14736149/b810b3f0-08a7-11e6-9bba-881a6cae3bb4.png)

**Comment by PhilJay** [comment]
You just need to create 3 `LineDataSet`

**Comment by luffy3** [comment]
Ok, thank you. I'll have a try.
