### ISSUE TITLE
A problem about "Legent.setPosition()" on version 2.2.4

### ISSUE THREAD

**Issue by yangnan221** [PhilJay/MPAndroidChart#1707]
Hi,

I met a problem when using pie chart.
When I use "myLegent.setPosition(Legend.LegendPosition.BELOW_CHART_CENTER);" the legend didn't not go center, but went to a strange position on the left below the chart. 

I tried other legend position like ABOVE_CHART_CENTER, BELOW_CHART_LEFT, BELOW_CHART_RIGHT... they all work well.

Then I tried to use old version v2.0.9, and the problem gone.  I think it could be a problem in the new version.

**Comment by BalalakshmiSadhasivam** [comment]
#1696
