### ISSUE TITLE
break line in xVals not working

### ISSUE THREAD

**Issue by RonEskinder** [PhilJay/MPAndroidChart#1709]
I need to place the percentage in a new line below the name of the venue. But its not working

this are my chart options

    `private void setDataBySubAccount() {

        sum = 0;
        
        ArrayList<Entry> yVals1 = new ArrayList<Entry>();
        ArrayList<Float> percents = new ArrayList<Float>();

        // Chart By Sub Account
        for (int i = 0; i < bySubAccount.length(); i++) {
            try {
                JSONObject x = bySubAccount.getJSONObject(i);
                yVals1.add(new Entry((float) Float.parseFloat(x.getString("amount")), i));
                sum = sum + Float.parseFloat(x.getString("amount"));
            } catch (JSONException e) {
                e.printStackTrace();
            }

        }

        for (int i = 0; i < bySubAccount.length(); i++) {
            try {
                JSONObject x = bySubAccount.getJSONObject(i);
                percents.add(Float.parseFloat(x.getString("amount"))/sum*100);
            } catch (JSONException e) {
                e.printStackTrace();
            }
        }

        ArrayList<String> xVals = new ArrayList<String>();
        for (int i = 0; i < bySubAccount.length(); i++){
            try {
                JSONObject x = bySubAccount.getJSONObject(i);
                xVals.add(x.getString("name") + "\n" + String.format("%.2f", percents.get(i)) + "%"); << THIS "\n" IS NOT WORKING
            } catch (JSONException e) {
                e.printStackTrace();
            }
        }

        PieDataSet dataSet = new PieDataSet(yVals1, "Por Sub-cuentas");

        // add color palette
        dataSet.setColors(ColorTemplate.LIBERTY_COLORS);

        PieData data = new PieData(xVals, dataSet);
        data.setValueTextSize(12f);
        data.setValueFormatter(new MyValueFormatter());
        data.setValueTextColor(Color.BLACK);

        mChartBySubAccount.setData(data);
        mChartBySubAccount.setDescription("");
        mChartBySubAccount.setHoleRadius(40f);
        mChartBySubAccount.setTransparentCircleRadius(50f);
        mChartBySubAccount.isHighlightPerTapEnabled();
        mChartBySubAccount.setCenterTextColor(Color.BLACK);
        mChartBySubAccount.setCenterText("Total\n" + currencySymbol + String.valueOf(sum)); << THIS WORKS

        Legend l = mChartBySubAccount.getLegend();
        l.setEnabled(false);

        // undo all highlights
        mChartBySubAccount.highlightValues(null);
        mChartBySubAccount.invalidate();
        mChartBySubAccount.animate();
    }`

Any ideas why?

![screenshot_20160423-122329](https://cloud.githubusercontent.com/assets/2273945/14763289/9d747d2c-094e-11e6-81bd-26d9fdd8d699.png)

**Comment by PhilJay** [comment]
Yes, x-axis values currently dont support multiple lines.
