### ISSUE TITLE
Impossible to hide the top, right and separator lines in HorizontalBarChart?

### ISSUE THREAD

**Issue by Sh4rPEYE** [PhilJay/MPAndroidChart#1710]
Hey! I'm trying to make my HorizontalBarChart look as simple as possible, thus removing all the unneeded lines and labels from the chart. The problem is, though I can't remove the top and rightside lines, as well as the separator lines between individual bars. Is there an option for it, that I haven't yet found, or is it just impossible? 

![The chart](https://cloud.githubusercontent.com/assets/8573043/14765830/027a7cda-09f4-11e6-9144-92d692b48794.png)

In my code, I set "enabled", "drawLabelsEnabled", "drawAxisEnabled" and "drawGridLinesEnabled" of both axises to false,

**Comment by BalalakshmiSadhasivam** [comment]
**To hide separators between bars,**

> YAxis yAxis = barChart.getAxisLeft(); // Show left y-axis line
>  yAxis.setDrawGridLines(false); // Hide y-axis (horizontal) grid lines

**To hide right side line,**

>  barChart.getAxisRight().setEnabled(false);// Hide right y-axis line

**To hide top x-axis line,**
       
>  XAxis xAxis = barChart.getXAxis();
>         xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);

**Comment by Sh4rPEYE** [comment]
Thanks for the answer. The top line of xAxis is away now, but the setDrawGridLines doesn't work unfortunately.

**Comment by PhilJay** [comment]
`yAxis.setDrawAxisLine(false)`
