### ISSUE TITLE
drawMarkers() in PieChart's onDraw() is looking for X-Axis, giving NullPointer

### ISSUE THREAD

**Issue by swarajsaaj** [PhilJay/MPAndroidChart#1713]
While setting a MarkerView for PieChart , I get a runtime exception, 

```
 java.lang.NullPointerException: Attempt to read from field 'float com.github.mikephil.charting.components.AxisBase.mAxisRange' on a null object reference
                                                                                   at com.github.mikephil.charting.charts.Chart.drawMarkers(Chart.java:673)
                                                                                   at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:136)
```

After some analysis, I found the Chart class is calculating deltaX from XAxis mXAxis object.
But for a pie chart there is no X-Axis?

Is there something wrong in this?

**Comment by PhilJay** [comment]
I think you are using an older version of the library. Could you post the code snippet where this issue occurs in the library?

For me, the code looks like this, which would prevent nullpointer:

```java
            float deltaX = mXAxis != null 
                ? mXAxis.mAxisRange
                : ((mData == null ? 0.f : mData.getXValCount()) - 1.f);
```

**Comment by swarajsaaj** [comment]
Hi Phil,
          I am using 2.2.4 (released 24 days ago)
but I see this was fixed 12 days ago
[in this commit](https://github.com/PhilJay/MPAndroidChart/commit/bef8db1af1f2c888ddeff9bf31301233c5c5e10e)

**Comment by PhilJay** [comment]
Awesome, I will close it then. New release will be out soon.
