### ISSUE TITLE
Cannot add Entry because dataSetIndex too high or too low.

### ISSUE THREAD

**Issue by waqary705** [PhilJay/MPAndroidChart#1719]

**Comment by zshn25** [comment]
Same problem here. Cannot find any threads relating this. Please help

**Comment by PhilJay** [comment]
Do you have `weight.size()` `BarDataSet` objects in your `BarData` object?
If not, your code is wrong.

Try:

`data.addEntry(entry, 0)` -> INDEX OF THE DATASET TO ADD TO, NOT INDEX OF THE ENTRY

**Comment by Chakib-Temal** [comment]
here , you can find an exemple for the future developpers :

https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/main/java/com/xxmassdeveloper/mpchartexample/RealtimeLineChartActivity.java
