### ISSUE TITLE
Legend position

### ISSUE THREAD

**Issue by AndroFlo** [PhilJay/MPAndroidChart#172]
Hi,
I have found i think a bug but it is useful.

My graph havne't legend because i use a legend with button to hide/show values in line series.
But when a want save the chart i show the legend like this :

``` Java
chart.setDrawLegend(true);
chart.getLegend().setPosition(LegendPosition.RIGHT_OF_CHART);
chart.invalidate();
}
```

![sans titr2](https://cloud.githubusercontent.com/assets/5589240/4736059/953fcbfa-59e8-11e4-924f-2a1af53d4343.png)

So when i want display the legend always in this position i put the same code at the first build of the graph but the result is :
![sans titre](https://cloud.githubusercontent.com/assets/5589240/4736045/68b2cc9a-59e8-11e4-8efc-a4608fe819c6.png)

It's possible to always have the position like the first screenshot ?
Thank you

**Comment by shawncalda** [comment]
is there no option to set legend on top of chart?

**Comment by wajdichamakhi** [comment]
yes there is `Legend.LegendPosition.ABOVE_CHART_CENTER`
