### ISSUE TITLE
The version in maven is not newest

### ISSUE THREAD

**Issue by heshiweij** [PhilJay/MPAndroidChart#1720]
The version of maven is not newest.

**Comment by Zengminjie** [comment]
I use MPAndroidChart:v2.2.4 and try to run the newest example ,but it didn't work ... in lack of some newest method ... like getMode \ setMode

**Comment by danielgindi** [comment]
The code on `master` is not released yet. When there will be a release it will get to Maven.
I know that it's much easier to compile the project through Maven than to compile directly - but we can't simply push releases for any new feature. Those need time to sink in, to find bugs, and to improve.
