### ISSUE TITLE
[QUESTION] How to hide the value of data inside the chart??

### ISSUE THREAD

**Issue by neomacedo** [PhilJay/MPAndroidChart#1728]
I have a chart (Line Chart) with too many data points, so i cant find on examples or documentation, how to hide the values from the chart.. i want to show just the chart line without text inside it..

How to??

**Comment by AxingG** [comment]
LineDataSet.setValueTextSize(0f);

**Comment by Noires** [comment]
LineDataSet.SetDrawValues(false); should be more appropriated, i guess.
But both should work~

**Comment by neomacedo** [comment]
`lineDataSet.setDrawValues(false);`

It Works!!


Thanks!!
