### ISSUE TITLE
What happened to FillFormatter?

### ISSUE THREAD

**Issue by smedic** [PhilJay/MPAndroidChart#1729]
Hi. 

As I can see, if you want to color specific region, you should use FillFormatter.
Ok, but how to add it to LineChart? 
There is no method setFillFormatter on LineDataSet anymore.
So, how to do that?

Regards,
Stevan

**Comment by PhilJay** [comment]
Actually, there is:
https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/com/github/mikephil/charting/data/LineDataSet.java#L365-371

You are probably working with the interface `ILineDataSet` which doesn't expose setters.
