### ISSUE TITLE
lineDataSet.setYVals(yVals) is not available at V2.2.4

### ISSUE THREAD

**Issue by unthinkfull** [PhilJay/MPAndroidChart#1731]
Because class DateSet has't setYVals, class ChartData has't setXVals. Do they have deleted? why?
Please add!

**Comment by yasaman93** [comment]
I have the same issue!

**Comment by manoj2791** [comment]
I have the same issue. Please add it back..

**Comment by willu2** [comment]
I have the same issue!

**Comment by Ydcool** [comment]
Please update the example project with the latest version! thanks

**Comment by Drakot** [comment]
Use v2.2.5

**Comment by PhilJay** [comment]
You are working on the interface `ILineDataSet`. This interface does not expose setter methods.
Access the setter like this:

```java

ILineDataSet set = ...;
((LineDataSet) set).setYVals(...)
```
