### ISSUE TITLE
Setting Data only works in OnViewCreated

### ISSUE THREAD

**Issue by Strandberg95** [PhilJay/MPAndroidChart#1732]
Hello! I'm trying to use the HorizontalBarChart in creating a chart to show income/expense in a fragment. And the graph works for the most. I can set and change the data but only while the OnCreate-method is active. 
What i want to do is to be able to change the data for the chart while another fragment is active. I have tried to use a variable that contains the data and then using the OnResume-method to update the graph to the current data. The applications does not crash, but nothing at alla happens. 

`public class BudgetFragment extends Fragment{

    private HorizontalBarChart mainChart;
    private BarData data;
    private BarDataSet dataset1;
    private BarDataSet dataset2;

    private int expenseSum = 0;
    private int incomeSum = 0;

    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        return inflater.inflate(R.layout.activity_main_progress_budget_fragment, container, false);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        mainChart = (HorizontalBarChart) view.findViewById(R.id.mainBudgetChart);

        //create data points
        ArrayList<BarEntry> entries1 = new ArrayList<>();
        ArrayList<BarEntry> entries2 = new ArrayList<>();

        entries1.add(new BarEntry(10000, 5));
        entries2.add(new BarEntry(10000, 5));

        dataset1 = new BarDataSet(entries1, "income");
        dataset2 = new BarDataSet(entries2, "expense");

        //X-axis labels
        ArrayList<String> xVals = new ArrayList<String>();
        xVals.add("income"); xVals.add("expense");;

        ArrayList<BarDataSet> dataSets = new ArrayList<BarDataSet>();
        dataSets.add(dataset1);
        dataSets.add(dataset2);

        //Add to chart
        data = new BarData(xVals, dataSets);
        mainChart.setData(data);

        //Description and animation
        mainChart.setDescription("");  // set the description
        mainChart.setScaleYEnabled(false);
        mainChart.setTouchEnabled(false);
        mainChart.animateY(2000);
    }

    @Override
    public void onResume() {
        super.onResume();
        updateDataExpense();
        updateDataIncome();
    }

    public void updateDataExpense() {
        dataset2.removeEntry(1);
        data.addEntry(new BarEntry(expenseSum, 1), 1);
        dataset2.setColor(getResources().getColor(R.color.orange));
        mainChart.notifyDataSetChanged(); // let the chart know it's data changed
        mainChart.invalidate(); // refresh
    }

    public void updateDataIncome(){
        dataset1.removeEntry(0);
        data.addEntry(new BarEntry(incomeSum,0), 0);
        dataset1.setColor(getResources().getColor(R.color.green));
        mainChart.notifyDataSetChanged(); // let the chart know it's data changed
        mainChart.invalidate(); // refresh
    }

    public void setDataExpense(int sum){
        expenseSum = (expenseSum + sum);
        Log.d("ResumeTag", "expense set at " + expenseSum);
    }

    public void setDataIncome(int sum){
        incomeSum = (incomeSum + sum);
        Log.d("ResumeTag", "income set at " + incomeSum);
    }
}
`

Let me know if I missed something important. 
Thank you for your help! 
    /Chris

**Comment by Baxtex** [comment]
I got the exact same problem, how do we actually set the data?

**Comment by vit001** [comment]
It's not clear what you mean by "fragment that is not active". A fragment can be hidden or destroyed. if it is hidden, and subsequently shown, onResume won't get called. If it is destroyed and then re-created, both onCreate and onResume will be called. Either way, you would not be updating/setting data in onResume.

**Comment by Strandberg95** [comment]
Well the thing is that i can use the setExpense/income and updateExpense/income but only in OnViewCreated. If i try changing the data from somewhere else the application crashes. That is why i suspected that the fragment has to be "active" in order to change the data. Im really new to Android Studio, so I'm not really sure yet how things work. 

Do you perhaps have any tip of what i can do fix my problem?

**Comment by vit001** [comment]
What do you mean by 'crashes'? Pls post the stacktrace

**Comment by Strandberg95** [comment]
http://imgur.com/xAqRfq4 
The fragment was not attached to the activity. though it is fixed now. 
So now I am getting no errors at all, and the chart does not change....

**Comment by vit001** [comment]
You need to read the Android documentation for Fragment lifecycle, FragmentManager and FragmentTransitions. It seems you are destroying your fragment when it goes off screen. Then you of course can't change anything in it. Your question has nothing to do with this library. I suggest you get your app working first by updating a simple textview when your fragment is hidden and take the chart out of the picture.

**Comment by PhilJay** [comment]
Dynamic data needs a call to `chartData.notifyDataSetChanged()`
