### ISSUE TITLE
Pie chart Values are overlapping

### ISSUE THREAD

**Issue by saileshpatne** [PhilJay/MPAndroidChart#1733]
When pie chart data is less compared to other data, the values on the pie chart gets overlapped.
Is it possible show values outside of pie chart with an arrow.

**Comment by PhilJay** [comment]
Yes, this feature is available since v2.2.5 - have a look at the example: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/PiePolylineChartActivity.java

**Comment by TravelerLq** [comment]
When pie chart data like one is 100% and the other is all =0, the text on the pie chart gets overlapped.
Is it possible show all the pie lable text(value =0) in a rectangular text boxoutside of pie chart with an arrow ?

**Comment by sakshi5724** [comment]
i have the same question as @TravelerLq

**Comment by AlbertoFabbri93** [comment]
Same problem here and the GitHub link is no longer active.
