### ISSUE TITLE
Adding more colours to PieChart

### ISSUE THREAD

**Issue by Vidxyz** [PhilJay/MPAndroidChart#1736]
I'm trying to create a pie chart with 7 different axis labels, however since there are only 5 colours the labels are cut off and the colours repeat

How do I add additional colours to facilitate further entries?

**Comment by cizkey** [comment]
I find the MPChartExample's Pie Chart sample has so many colors. ... more than 7 kinds ... It may be that you made a mistake......

![charts](https://cloud.githubusercontent.com/assets/14026236/15548323/6a23bc9e-22da-11e6-8769-aea5be964a15.jpg)
