### ISSUE TITLE
MPAndroid chart circular graph has errors when values too small...

### ISSUE THREAD

**Issue by jjupin** [PhilJay/MPAndroidChart#1737]
This is sorta complicated so I'll explain as best as I can.

I'm using MPAndroid chart to create a circular pie chart (well, more of a torus) with sections colored based on the integer values.  Now, when I have four values with the following values:

1380, 880, 12 and 1 each with a corresponding color.

When those are plotted in the circular graph, the background color of the graph assumes the color of the values that are the smallest.  Even when explicitly setting the background color of the graph to white, it will still be overwritten by the color of the smallest value.

Additionally, with further testing, I found that if the smallest value is less than 2.5% of the total, the graph will exhibit this problem.  (In order to get my graph to work correctly, I add in the 2.5% amount to all values less than that value and it draw correctly.)

What I don't understand is how this is bleeding into the background of the graph - and for the record, the color is only around the graph, the middle area remains white as directed in the code.

Send me a message and I'll send an image.

**Comment by tiagoluzpoa** [comment]
I had the same issue here.

**Comment by PhilJay** [comment]
#1699
