### ISSUE TITLE
spider web chart background

### ISSUE THREAD

**Issue by d0938687689** [PhilJay/MPAndroidChart#1738]
![2016-05-04 11 48 29](https://cloud.githubusercontent.com/assets/18639372/15004849/b3095a10-11ee-11e6-8aa5-901b85569648.png)
I would love to know that if I can change the right one chart to the left one chart by using the different color? and how to do that? Thanks <3

**Comment by PhilJay** [comment]
Theoretically, you could "fake" that effect by adding dummy data objects to the chart.
Other than that, there is no option.
