### ISSUE TITLE
Near and large values overlaps each others in line chart

### ISSUE THREAD

**Issue by nahr-elgannah** [PhilJay/MPAndroidChart#1739]
Hi,
Thank you for this powerful library.
I have a problem when the values are near to each other and every value has several amount of digits, the value would overlap each others like in the below snapshot.
I tried to make some values upper and some lower the line, or to make values written in vertical way (like x labels in the snapshot), but I didn't find way to do that.

If there is any advice or other workaround, it will be appreciated.

![overlapping near values](https://cloud.githubusercontent.com/assets/7861475/15014000/78728fc4-1203-11e6-942b-fe09f889afa4.PNG)

**Comment by nahr-elgannah** [comment]
Any help ?

**Comment by nahr-elgannah** [comment]
Reminder

**Comment by nahr-elgannah** [comment]
My issue is not solved yet !

**Comment by PhilJay** [comment]
There is not much you can do. Just make the values smaller, or don't display them. Also, you can try setting a low chart.setMaxVisibleCount(...)
