### ISSUE TITLE
LineChart Not Rendering New RealmLineData

### ISSUE THREAD

**Issue by rgr-myrg** [PhilJay/MPAndroidChart#1741]
### Set Up:

Thread A invokes YahooFinance API on a background thread.

When data is loaded Thread A finishes and the ChartActivity runs on the UI Thread to:

1. Save the data in Realm
2. Create an instance of RealmLineData with the new result set
3. Create a LineChart using findViewById and setting chart options
4. Invoke LineChart.setData with the instance of RealmLineData created in step 2

### Result:

LineChart data is rendered and graphed with new RealmLineData **only the first time** ChartActivity launches. On subsequent launches, the resulting new data set created in step 2 is not graphed. 

The sequence (steps 1-4) was verified to ensure new data is being retrieved and created.

**LineChart.setLogEnabled(true)** was enabled to capture the log. [Gist][LogLink] 

### Steps to Reproduce

1. Download and install StockHawk sample APK from [Repo][ApkLink]
2. Launch StockHawk app
3. Click on first ticker (YAHOO). Observe LineChart renders data. 
4. Touch home arrow to return to main activity
5. Click on second ticket (AAPL). Observe LineChart does not render data. Empty LineChart.
6. Touch home arrow to return to main activity.
7. Click on other tickers. Observe LineChart does not render data. Empty LineChart.

LineChart and RealmLineData implementation can be seen here:

* [ChartActivity][ChartActivityLink]

[LogLink]: <https://gist.github.com/rgr-myrg/c933b38df125733b0a3f84d2c5587869>
[ApkLink]: <https://github.com/rgr-myrg/www/tree/master/apk>
[ChartActivityLink]: <https://github.com/rgr-myrg/www/blob/master/java/ChartActivity-MpAndroidChart-Issue-1741.java>

**Comment by rgr-myrg** [comment]
A workaround for this issue is to bypass MPAndroidChart's RealmLineData implementation and manually feed the chart instance.

**Comment by PhilJay** [comment]
There are currently some issues with the new realm version. I am working on resolving them to allow using the realm implementation provided by this library again.
