### ISSUE TITLE
LineChart only show points on graph that have an x-axis value

### ISSUE THREAD

**Issue by mikemike396** [PhilJay/MPAndroidChart#1742]
How can I remove any of the bubbles and text value on the line that do not have a x-axis value?

![screen shot 2016-05-04 at 4 16 14 pm 3](https://cloud.githubusercontent.com/assets/14999806/15027852/c9ed6238-1213-11e6-92b8-1cfb16554e95.png)

**Comment by jessb417** [comment]
For me what has worked is to skip adding an entry for such values but still increment the index.
