### ISSUE TITLE
Reduce the top space between the chart (PieChart) and the Legend

### ISSUE THREAD

**Issue by ropherpanama** [PhilJay/MPAndroidChart#1743]
How can I remove the blank space between the chart and the legend. I'm using PieChart. In this [stackoverflow](http://stackoverflow.com/questions/27945624/mpandroidchart-remove-top-and-bottom-spaces) question say that should use the `setOffset` method, but in the last version this method doesn't exists, and the `setMinOffset` doesn't work.

**Comment by PhilJay** [comment]
Cou can achieve that by simply making the chart view smaller or mor proportional in terms of width and height.

**Comment by dwivedi** [comment]
Try this... work for me
`pieChart.setExtraOffsets(-10,-10,-10,-10);`
