### ISSUE TITLE
How to get group index for highlighted value in GroupedBarChart ?

### ISSUE THREAD

**Issue by BalalakshmiSadhasivam** [PhilJay/MPAndroidChart#1748]
Hi Phil, I am currently working with GroupedBarChart. I am using MarkerView to display values when a chart is highlighted. I can fetch x-index by using highlight.getXIndex() method.

The problem is highlight.getStackIndex() always returns -1 for this chart since there is no stacked data. 

How to show value using markerView for GroupedBarChart? Is there any method to get groupIndex (for getting the index of the element in the group) similar to getStackIndex()?

**Comment by PhilJay** [comment]
Have you tried highlight.getDataSetIndex() - it basically represents the group index.
