### ISSUE TITLE
The Chart is not redrawn when the data is null after initiating the chart

### ISSUE THREAD

**Issue by alexwbaule** [PhilJay/MPAndroidChart#1749]
Hi Guys,

i'm using this amazing library, its easy and beautiful, tks.
I will try to explain what happens, and below the explanation put the source code.

When I start any of the charts, and use the setData the first time with a null data, the message "The chart data available." is displayed.
But if I start the chart, and use the setData chart with data, the char is displayed OK. Then, i call the setData again to "update" the chart with another period, and this period has a  null data, like the first explanation,  the message is not displayed.
I call invalidate() after setData, call notifyDataSetChanged() too, but the chart is not redrawn with the correct message, that is no data available.
Doing some test, if you setData with some numbers, after that call chart.clear() (internally this set mData to null) and call invalidate(), the chart is not redrawn to.

Explained my code below:

When I create the fragment, my onCreateView is called, and call the createGraph passing invalid as false. When my fragment is showing (and the User clicks on the button to update the date) the update event is called, passing invalid as true.
Here is the Code:

public class TravelDistanceLineChart extends BaseFragment {
    private LineChart chart;

    public TravelDistanceLineChart() {
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.fragment_line_chart, container, false);
        ReportLabelFormatter labelformat = new ReportLabelFormatter(ReportLabelFormatter.types.DISTANCE);
        chart = (LineChart) rootView.findViewById(R.id.linechart);
        chart.setDescription(null);
        chart.setLogEnabled(true);
        chart.setNoDataText(getString(R.string.nao_ha_graficos));
        chart.getAxisRight().setValueFormatter(labelformat);
        chart.getAxisLeft().setValueFormatter(labelformat);
        createGraph(rootView, false);
        Log.d(getClass().getSimpleName(), "Calling onCreateView");
        return rootView;
    }
    public void update() {
        Log.d(getClass().getSimpleName(), "Calling Update");
        createGraph(getView(), true);
    }

    protected void createGraph(View view, boolean invalid){
        TextInputEditText report_ini_date = (TextInputEditText) getActivity().findViewById(R.id.report_ini_date);
        TextInputEditText report_end_date = (TextInputEditText) getActivity().findViewById(R.id.report_end_date);

        if(report_ini_date != null && report_end_date != null) {
            chart.setData(MeuCarroApplication.getInstance().reportTravelDistance(report_ini_date.getText().toString(), report_end_date.getText().toString()));
        }
        if (invalid) {
            chart.notifyDataSetChanged();
            chart.invalidate();
        }
        //chart.animateX(1500);
    }

**Comment by lisardo** [comment]
@alexwbaule Did you find any solution for this problem? I'm facing exactly the same issue.

**Comment by PhilJay** [comment]
This is under investigation, thanks for the detailed report.

**Comment by alexwbaule** [comment]
Tks for The Answer , and for the fix !!!
