### ISSUE TITLE
Posibility to include library using gradle dependencies

### ISSUE THREAD

**Issue by claucookie** [PhilJay/MPAndroidChart#175]
It would be great if your library could be included using gradle dependencies instead of downloading .jar file.
I just added it to one of my projects and really love it. The cons is every time it gets updated i have to re-download the jar file, so if it would be managed with gradle, you could provide updates for everyone much more easy =) 

What do you thing?

**Comment by romaloma** [comment]
+1 for gradle :)

**Comment by erickChavez** [comment]
+1 for Gradle dependency in Maven central!

**Comment by nekdenis** [comment]
+1

**Comment by mathieudebrito** [comment]
up

**Comment by vincentbrison** [comment]
Up. This should be publish on a maven repository, since distributing this library in a .jar with its own dependencies already compiled in it (as nine old android) is a real problem if you use another library in your project distributed the same way.

**Comment by manujosephv** [comment]
+1 .. exactly what vincentbrison said...  nine old android is included in one of my other libraries and its clashing with MPAndroidChart ..

**Comment by PhilJay** [comment]
This is now possible:

https://github.com/PhilJay/MPAndroidChart/blob/master/README.md#usage

**Gradle dependency**

 - 	Add the following to your `build.gradle`:
 ```gradle
repositories {
	    maven { url "https://jitpack.io" }
}

dependencies {
	    compile 'com.github.PhilJay:MPAndroidChart:v2.0.0'
}
```

**Comment by romangromov** [comment]
Sounds great, thank you!

**Comment by mathieudebrito** [comment]
Thank you so much @PhilJay !

**Comment by romaloma** [comment]
Just in time! Im finishing the project with MPAndroidChart in two weeks :)
Many thanks!
