### ISSUE TITLE
The pie chart  background  will change when the one value of PieDataSet is 0.01

### ISSUE THREAD

**Issue by zhangshuliang** [PhilJay/MPAndroidChart#1752]
Hi,PhilJay, I use mpandroidchart for my project ,and  I find the  question that if your one values of PieDataSet is lessthen 0.21, then the pie chart background will change.This is my code 
`mPieChart.setBackgroundColor(Color.WHITE);`
`ArrayList<Float> values = new ArrayList<Float>();`
`values.add(40.12f);`
`values.add(4.88f);`
`values.add(6f);`
`values.add(0.05f);`
`values.add(52f);`
`for (int i = 0; i < values.size(); i++) {`
`	yValues.add(new Entry(values.get(i), i));`
`}`
`PieDataSet mPieDataSet = new PieDataSet(yValues, "");`
can you help me ?

**Comment by PhilJay** [comment]
#1699 
#1737
