### ISSUE TITLE
How to remove extra whitespace when using PieChart and maxAngle?

### ISSUE THREAD

**Issue by chubbard** [PhilJay/MPAndroidChart#1755]
I have a StackOverflow question on this with code and pictures that should help:

http://stackoverflow.com/questions/37080602/how-to-remove-extra-whitespace-on-pie-charts-from-mpandroidcharts

But how do you eliminate the extra whitespace created when using maxAngle with PieCharts?

**Comment by PhilJay** [comment]
Temporary workaround is setting a negative bottom margin:

```java
        Display display = getWindowManager().getDefaultDisplay();
        int height = display.getHeight();  // deprecated

        int offset = (int)(height * 0.65); /* percent to move */

        RelativeLayout.LayoutParams rlParams =
                (RelativeLayout.LayoutParams)mChart.getLayoutParams();
        rlParams.setMargins(0, 0, 0, -offset);
        mChart.setLayoutParams(rlParams);

```

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
