### ISSUE TITLE
MPAndroidChart RadarChart collapses itself

### ISSUE THREAD

**Issue by Sleeper9** [PhilJay/MPAndroidChart#1760]
I have some problems with RadarChart labels. Specifically, if I use long texts (e.g. 15-20 chars), and the available space is not too big, the chart gets collapsed and the labels are positioned inside the collapsed chart (but there is clearly more space available).

I tried to use ValueFormatter for the label axis that truncates labels if they are longer than 5 chars, but as I see, the chart size calculaction is based on the full label text, as the chart got collapsed the same way I described before.

[See more information and pictures here](http://stackoverflow.com/questions/37112855/mpandroidchart-radarchart-collapses-itself)

**Comment by Sleeper9** [comment]
OK, so what's the solution? Please do provide some information why did you close this issue,

**Comment by GuilhermeCouto** [comment]
I am facing the same problem. That was also found here: http://stackoverflow.com/questions/35966673/cant-reduce-extra-space-in-mpandroidchart-radarchart
