### ISSUE TITLE
Real-time line data library

### ISSUE THREAD

**Issue by duanemalcolm** [PhilJay/MPAndroidChart#1762]
Apologies if this isn't the proper way to let people know about this library.
[RealTimeLineData](https://github.com/duanemalcolm/RealTimeLineData)
Others may find it useful.

I've written a class to manage lots of real time data, essentially it's a sliding buffer. I wanted to try a rolling double buffer with a sliding viewport which may computationally cheaper but ran out of time.

It's based on [issue 1036](https://github.com/PhilJay/MPAndroidChart/issues/1036) and one other one I cannot find.

Feel free to send feedback.

**Comment by PhilJay** [comment]
Thank's, I think you should carry this to stackoverflow and let people who have trouble implementing realtime data know about it.
