### ISSUE TITLE
major and minor gridline in x-axis and y-axis

### ISSUE THREAD

**Issue by loftyet** [PhilJay/MPAndroidChart#1770]
any way we can draw major and minor grid lines in x-axis and y-axis? like in this image
http://highered.mheducation.com/sites/dl/free/0073520713/356819/chap03_001.jpg
![grid_sample](https://cloud.githubusercontent.com/assets/356347/15234678/f3e23e1e-1868-11e6-9084-3b397b61dd13.jpg)

**Comment by PhilJay** [comment]
Currently not possible

**Comment by Shrikant-B** [comment]
@liangjun-jiang Are you able to figure out solution for this?
