### ISSUE TITLE
 java null pointer exception com.github.mikephil.charting.renderer.LineChartRenderer.drawCircles

### ISSUE THREAD

**Issue by pandiarajanKC** [PhilJay/MPAndroidChart#1771]
private void addEntry(float _pitch) {

		try {
			if (mChart == null) {
				return;
			}
			data = mChart.getData();
			if (data != null) {
				set = data.getDataSetByIndex(0);
				if (set == null) {
					// creation if null
					set = CreateSet();
					data.addDataSet(set);
				}
				data.addXValue(NAME[note]);
				data.addEntry(new Entry(_pitch, set.getEntryCount()), 0);
				mChart.notifyDataSetChanged();
				mChart.setVisibleXRangeMaximum(4);
				// mChart.moveViewToX(data.getXValCount() - 4);
				seekBar.setProgress(data.getXValCount());
				// mChart.animateX(20000);
			}
		} catch (Exception e) {
			Log.e("Oncreate Error", e.toString());
		}
	}

	private void addEntry1(float _pitch) {
		try {
			if (mChart == null) {
				return;
			}

			data1 = mChart.getData();
			if (data1 != null) {
				set1 = data1.getDataSetByIndex(1);
				if (set1 == null) {
					// creation if null
					set1 = CreateSet1();
					data1.addDataSet(set1);
				}
				data1.addEntry(new Entry(_pitch, set1.getEntryCount()), 1);
				mChart.notifyDataSetChanged();
				mChart.setVisibleXRangeMaximum(4);
				if (set1.getEntryCount() > 4) {
					mChart.moveViewToX(set1.getEntryCount() - 4);
				}
				//seekBar.setProgress(data1.getXValCount());
				set1.setValueTextColor(Color.RED);

			}
		} catch (Exception e) {
			Log.e("Oncreate Error", e.toString());
		}
	}

**Comment by Noires** [comment]
Where do you call these methods? Is it in a seperate thread or the main thread?
A little more background information to your problem would be nice.
