### ISSUE TITLE
how to drag the markerview ?

### ISSUE THREAD

**Issue by zhangshuliang** [PhilJay/MPAndroidChart#1772]
Hi,@PhilJay
I use mpandroidchart line chart , and I set the markerview , but the markerview only click . I want to drag the markerview with my finger moving at the phone screen. how can I do?
`markerView = new MyMarkerView(this,R.layout.custom_markerview);`
`mLineChart.setMarkerView(markerView);`
`mLineChart.invalidate();`

**Comment by TeunKooijman** [comment]
You can use the following calls to determine whether or not a marker view is rendered upon a specific gesture:

```
        mLineChart.setHighlightPerDragEnabled(true);
        mLineChart.setHighlightPerTapEnabled(true);
```

Hope this helps.
