### ISSUE TITLE
PieChart color "bleeds" on the background when on Entry of the dataset is small compared to others

### ISSUE THREAD

**Issue by vguillou** [PhilJay/MPAndroidChart#1774]
When a PieChart has wildly different entries in it's dataset (say for example 23 and 7142), the color that is suppose to represent the smaller entry (23) is "bleeding" into the background of the chart.

Example (from v2.2.4) :
![wrong-2 2 4](https://cloud.githubusercontent.com/assets/9221460/15250718/561f3b5a-1926-11e6-8278-143564a392e0.png)

Expected outcome (v2.2.0) :
![correct-2 2 0](https://cloud.githubusercontent.com/assets/9221460/15250716/529fd480-1926-11e6-9a38-52f71dae1fed.png)

I'm not sure when exactly was this issue introduced (probably v2.2.3), I can only vouched that it is present in v2.2.4 and not in v2.2.0.

**Comment by hovo888s** [comment]
Same for me

**Comment by AndZp** [comment]
+1 
Same problem. v2.2.5
