### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0

### ISSUE THREAD

**Issue by jenhani-ameni** [PhilJay/MPAndroidChart#1778]
i changed the code of the fragment SimpleFragment.java to adapt it in my app:
`protected BarData generateBarData(int dataSets, float range, int count,ArrayList<BarEntry> entries) {
        
        ArrayList<IBarDataSet> sets = new ArrayList<IBarDataSet>();

        for(int i = 0; i < dataSets; i++) {
            BarDataSet ds = new BarDataSet(entries, getLabel(i));
            ds.setColors(BarChartFrag.COLORS);
            sets.add(ds);
        }

        BarData d = new BarData(ChartData.generateXVals(0, count), sets);
        d.setValueTypeface(tf);
        return d;
    }`

### But i get this problem
`java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
05-16 17:57:53.112 19205-19205/? E/AndroidRuntime:     at com.github.mikephil.charting.buffer.BarBuffer.addBar(BarBuffer.java:37)
05-16 17:57:53.112 19205-19205/? E/AndroidRuntime:     at com.github.mikephil.charting.buffer.BarBuffer.feed(BarBuffer.java:82)
05-16 17:57:53.112 19205-19205/? E/AndroidRuntime:     at com.github.mikephil.charting.renderer.BarChartRenderer.drawDataSet(BarChartRenderer.java:95)
05-16 17:57:53.112 19205-19205/? E/AndroidRuntime:     at com.github.mikephil.charting.renderer.BarChartRenderer.drawData(BarChartRenderer.java:74)
05-16 17:57:53.112 19205-19205/? E/AndroidRuntime:     at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:247)
05-16 17:57:53.112 19205-19205/? E/AndroidRuntime:     at android.view.View.draw(View.java:15635)`

can you help me

**Comment by Noires** [comment]
Just a rough guess here, but maybe because your entries for your BarDataSet are empty? Or atleast it seems so, when i just look at that code snippet.

**Comment by zorroblue** [comment]
@jenhani-ameni  I too got a similar error before. I think what @Noires says is right. Your dataset might be empty because the for loop never ran.

**Comment by jenhani-ameni** [comment]
Thanks @Noires and @zorroblue problem is solved
