### ISSUE TITLE
Line chart, missing axis (2.2.2 -> 2.2.4)

### ISSUE THREAD

**Issue by adek** [PhilJay/MPAndroidChart#1779]
After updating library to 2.2.4 in my app some of my charts are messed.
I can't find differences in the usage between these version so I think this could be a bug.

![mpchartengine-difference-222vs224](https://cloud.githubusercontent.com/assets/963361/15333315/7245b516-1c69-11e6-9863-ebbbff3ad3c6.jpg)

Here's my styling for the chart

       ```
                mChartView = (LineChart) findViewById(R.id.linechart);
                mChartView.setVisibility(View.VISIBLE);
                mChartView.setBorderWidth(0f);
                mChartView.setData(mDataChart);
                mChartView.setDrawBorders(false);
                mChartView.setDrawGridBackground(false);
                mChartView.setDescription(null);

                mChartView.setGridBackgroundColor(Color.parseColor("#000000"));
                mChartView.getXAxis().setDrawAxisLine(false);
                mChartView.getXAxis().setPosition(XAxis.XAxisPosition.BOTTOM);
                mChartView.getAxis(YAxis.AxisDependency.LEFT).setDrawAxisLine(false);
                mChartView.getAxis(YAxis.AxisDependency.RIGHT).setEnabled(false);
                mChartView.getLegend().setForm(Legend.LegendForm.CIRCLE);
                mChartView.getAxis(YAxis.AxisDependency.LEFT).setStartAtZero(false);
                mChartView.getAxis(YAxis.AxisDependency.LEFT).setValueFormatter(new           YAxisValueFormatter() {
                    @Override
                    public String getFormattedValue(float value, YAxis yAxis) {
                        DecimalFormat mFormat = new DecimalFormat("###,###,##0.00");
                        return mFormat.format(value);
                    }
                });

                MyMarkerView mv = new MyMarkerView(getBaseContext(), R.layout.marker_view);
                mChartView.setMarkerView(mv);
                mChartView.invalidate();
```

**Comment by cizkey** [comment]
also +1.  when i use version 2.2.4, sometimes line chart displays  missed axis lines... or, lines confusion

![chartbugs](https://cloud.githubusercontent.com/assets/14026236/15529403/9d3b94ea-227f-11e6-9b96-fce5b5a602eb.jpg)

**Comment by PhilJay** [comment]
Unfortunately I cannot reproduce the issue. For me everything works fine. Could you post your whole setup (all the code from the activity or fragment)?

**Comment by adek** [comment]
So maybe this is related with data. I'm abroad right now but later I'll try to get more info for you.
This could be related also with the number format

#,## 

I've got a lots of values where the third place is important

0.051
0,053

I think this related with creating the axis.

Please try this on a list with numbers like:

0,21 - 0,29
0,031 - 0,050

The in 2.2.4 Axis is not showing (as you can see on the image). Everything works fine when you have bigger numbers.

I didn't change anything else to create the screenshots - just the 2.2.1 -> 2.2.4 update.
I'm back on 2.2.1

**Comment by PhilJay** [comment]
Alright thanks, I'll investigate this.

**Comment by cizkey** [comment]
i agree with adek. 
I used the random integer as data, and I generate new data when the fragment was show.
sometimes it  will display like that. 

```java
        ArrayList<Entry> entries = new ArrayList<>();
        for (int i = 0; i < 31; i++) {
            entries.add(new Entry((int) (Math.random() * 100 + 30), i));
        }
        LineDataSet dataSet = new LineDataSet(entries, "");
```

sorry my poor English.

**Comment by PhilJay** [comment]
I still cannot reproduce the issue even with small values like 0,031 - 0,050
For me everything displays correctly.

Could you show me the code of your fragment?
