### ISSUE TITLE
How to draw a Line on Chart ios-chart

### ISSUE THREAD

**Issue by anhltse03448** [PhilJay/MPAndroidChart#1781]
I want to draw this blue line on Chart but I don't know how to draw. 
- I only get Value of chart when click where have Bar or Candle....., but I want to click other more 
- How to draw this Line on chart :) 
<img width="768" alt="screen shot 2016-05-18 at 08 44 06" src="https://cloud.githubusercontent.com/assets/7755118/15344972/46dec22a-1cd5-11e6-8606-fef0fd3fd76c.png">

**Comment by PhilJay** [comment]
Take a look at the example project.
