### ISSUE TITLE
White space on line chart when draw circle is disabled

### ISSUE THREAD

**Issue by amaniago** [PhilJay/MPAndroidChart#1782]
I have an issue with linechart. I have some white space in the line.

![device-2016-05-18-092615](https://cloud.githubusercontent.com/assets/1519313/15350612/a18786c6-1cda-11e6-8dc3-a891a297ae48.png)

I tried to change all parameters but I can not get the expected result.

**Comment by sinnott-balin** [comment]
Were you able to figure out a solution to this problem?  I am running into something very similar.
