### ISSUE TITLE
Problem with setData

### ISSUE THREAD

**Issue by NuMetalSour** [PhilJay/MPAndroidChart#1783]
Hi there

i'm develop an aplication on xamarin for android , this works almost everything, but when I make a call to setData() method does not recognize me, What could be the problem??

Best regards
![screenshot_1](https://cloud.githubusercontent.com/assets/5225945/15382688/791c1cc6-1d5a-11e6-88b7-1c71935c01e5.png)

**Comment by Noires** [comment]
Most of the Set and Get Methods got replaced with Properties. So you just have to use lineChart.Data and it should work without a problem.
