### ISSUE TITLE
How implement zoom only Asix X

### ISSUE THREAD

**Issue by service-user-spot-software** [PhilJay/MPAndroidChart#1787]
I have a "CombinedChart" with 100 x values (chartXVals) and VisibleXRangeMaximum is 30. When I draw entries force to scroll to the last X:

```
int indexXVal = chartXVals.size() - 1
this.mChart.setVisibleXRangeMaximum(30);
this.mChart.moveViewToX(indexXVal);
this.mChart.setScaleYEnabled(false);
this.mChart.setScaleXEnabled(true);
```

I have two buttons to zoom in / zoom out the Asix X of chart. 
Unfortunately the methods of `this.mChart.zoomIn()` and t`his.mChart.zoomOut()`  make zoom from the charts center of viewport of Asix X and Asix Y, then `setScaleYEnabled(false`) is ignored. I tried so:

```
float factorScaleX = 1.4 —>  zoom in
float factorScaleX = 0.7 —>  zoom out

PointF center = this.getChart().getViewPortHandler().getContentCenter();
this.getChart().zoom(factorScaleX, 1f, center.x, 0f);
```

Have you another solution?

Thanks in advanced.

Please refer link below for detailed problem.

http://stackoverflow.com/questions/36651455/mpandroidchart-how-implement-zoom-asix-x-and-zoom-does-not-work-when-scrolling

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
