### ISSUE TITLE
LineChart Label only half visible

### ISSUE THREAD

**Issue by Dabendorf** [PhilJay/MPAndroidChart#1788]
Hello,
if I'm using Integers from 0 to 100 on y-Axis, all very big numbers like 99 or 100 have a non-good-visible label, as you can see in the following screenshot:
![img_0044](https://cloud.githubusercontent.com/assets/9696353/15393228/7fa258fe-1dcc-11e6-903e-e877be9b8c4d.PNG)

My (swift)-Code is the following:
`barChartView.noDataText = "Das Diagramm kann nicht dargestellt werden."
        barChartView.noDataTextDescription = "Dies liegt daran, dass noch\nkeine Messdaten vorliegen."
        barChartView.descriptionText = ""
        barChartView.leftAxis.axisMinValue = 0
        barChartView.leftAxis.axisMaxValue = 100
        barChartView.xAxis.labelPosition = ChartXAxis.LabelPosition.Bottom
        barChartView.xAxis.drawLabelsEnabled = true
        barChartView.autoScaleMinMaxEnabled = false
        barChartView.maxVisibleValueCount = 90`

Is that a bug or do I have overlooked one essentiell code-line?

Note: it is a linechart, don't know why I have named it barChart ;)

**Comment by PhilJay** [comment]
leftAxis.spaceTop = 30
