### ISSUE TITLE
How to change size of values inside chart?

### ISSUE THREAD

**Issue by kitek111** [PhilJay/MPAndroidChart#1791]
How can i change size of y values inside of chart? I've found this question: https://github.com/PhilJay/MPAndroidChart/issues/24, but this methos still isnt there.

**Comment by Noires** [comment]
Maybe iam understanding you wrong, but shouldnt be stuff like ...

```
            BarData barData = new BarData();
            barData.SetValueTextSize(9f);
```
or
```
            LineDataSet lineDataSet = new LineDataSet(null, "");
            lineDataSet.SetValueTextSize(9f);
```
...doing the trick?

**Comment by kitek111** [comment]
Not at all, i had to use .setValueTextSize(10f) on LineDataSet object which i use to create LineData and then set it to graph. So, at end it seems like that:

`LineDataSet dataset = new LineDataSet(values, "legend");
dataset.setValueTextSize(10f);
LineData data = new LineData(labels, dataset);
graph.setData(data);`
