### ISSUE TITLE
XAxis.XAxisPosition.BOTTOM Problem

### ISSUE THREAD

**Issue by jamesbang** [PhilJay/MPAndroidChart#1792]
Hi, MPAndroidChart Developer

when i use XAxis.XAxisPosition.BOTTOM, the label position is misplaced.
chart result link：https://db.tt/0ZhmT3jC

**Comment by zorroblue** [comment]
Hi @jamesbang ! Could you share your code snippet so that your problem could be better understood?

**Comment by jamesbang** [comment]
Hi MPAndroidChart Developer

Attached is the code I used to test。

2016-05-24 16:12 GMT+08:00 Rameshwar Bhaskaran <notifications@github.com>:

> Hi @jamesbang <https://github.com/jamesbang> ! Could you share your code
> snippet so that your problem could be better understood?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/PhilJay/MPAndroidChart/issues/1792#issuecomment-221196910>
>



-- 
James

**Comment by zorroblue** [comment]
Not able to see it. Am I making a mistake?

**Comment by jamesbang** [comment]
========== Test Code ============
        final int maxCalorie = 2800;
        final int overCalorie = 1600;
        holder.calorieChart.setMaxVisibleValueCount(maxCalorie);
        holder.calorieChart.setDescription("");
        holder.calorieChart.setPinchZoom(false);

        XAxis xAxis = holder.calorieChart.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setDrawGridLines(false);

        final String[] weekDate =
getContext().getResources().getStringArray(R.array.week_date);
        /**
         *  R.array.week_date data
         *  <array name="week_date">
         <item>日</item>
         <item>一</item>
         <item>二</item>
         <item>三</item>
         <item>四</item>
         <item>五</item>
         <item>六</item>
         </array>
         */
        List<String> xVals = Arrays.asList(weekDate);
        List<BarEntry> yVals = new ArrayList<>();

        Random random = new Random();
        List<Integer> colors = new ArrayList<>();
        for (int i = 0; i < xVals.size(); i++) {
            float val = random.nextInt((maxCalorie - 1000) + 1) + 1000;
            final BarEntry barEntry = new BarEntry(val, i);
            yVals.add(barEntry);

            if (val > overCalorie) {
                colors.add(ContextCompat.getColor(getContext(),
R.color.chart_bar_over));
            } else {
                colors.add(ContextCompat.getColor(getContext(),
R.color.chart_bar_normal));
            }
        }

        BarDataSet dataSet = new BarDataSet(yVals, "每日攝取熱量");
        dataSet.setColors(colors);
        dataSet.setValueTextSize(10f);
        dataSet.setBarSpacePercent(60f);

        List<IBarDataSet> dataSets = new ArrayList<>();
        dataSets.add(dataSet);
        BarData data = new BarData(xVals, dataSets);
        holder.calorieChart.setData(data);
        holder.calorieChart.getData().setHighlightEnabled(false);
        holder.calorieChart.getLegend().setEnabled(false);
        holder.calorieChart.setDrawGridBackground(true);
        holder.calorieChart.setGridBackgroundColor(0xF7FFB986);
        holder.calorieChart.invalidate();


========== Layout ============
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:background="#F7FFE674"
    android:layout_height="@dimen/wall_content_image_height">

    <com.github.mikephil.charting.charts.BarChart
        android:id="@+id/chart_calorie"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/seekBar1" />
</LinearLayout>


2016-05-30 13:07 GMT+08:00 Rameshwar Bhaskaran <notifications@github.com>:

> Not able to see it. Am I making a mistake?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/PhilJay/MPAndroidChart/issues/1792#issuecomment-222412319>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGK3B2Ky1WDyLYyNW21BhhhVI68-YzwCks5qGnCsgaJpZM4Ii2IT>
> .
>



-- 
James
