### ISSUE TITLE
BarChart only drawing itself on touching the graph

### ISSUE THREAD

**Issue by richeekdey** [PhilJay/MPAndroidChart#1796]
I've used a viewpager in which I've embedded the graph, now I've got three buttons: Day, Week and Month to show the respective views. In my code, on the onClick of each of these buttons, I'm fetching data from database and feeding it to the graph. The problem is, after I click the buttons, nothing happens, I have to click on the graph for the values to appear.

**Comment by TR4Android** [comment]
@richeekdey Have you tried calling `invalidate( )` on your chart? This forces the chart to redraw its contents.

**Comment by richeekdey** [comment]
Thanks, this helped.

**Comment by TR4Android** [comment]
@richeekdey If this solved your issue, closing it would be helpful so @PhilJay can concentrate on the unresolved issues. Thanks!
