### ISSUE TITLE
LineChart - Display MarkerView in fixed location (upper left corner)

### ISSUE THREAD

**Issue by TeunKooijman** [PhilJay/MPAndroidChart#1799]
Hi Phil,

I was wondering if it were possible to draw the `MarkerViews` of a `LineChart` in a static/fixed location, such as the upper left corner. I've looked through existing GitHub issues and the Wiki articles, but sadly I was unable to find something like this.

Any help is greatly appreciated, so thank you in advance.

Kind regards,

Teun Kooijman

**Comment by spaultownsend** [comment]
Subclass the MarkerView class and override the draw() method. The draw() method is passed a reference to the Canvas, on which you can draw your marker at any location you like.

**Comment by TeunKooijman** [comment]
Worked like a charm. I ended up ignoring the posx and posy arguments of the draw() method entirely and hardcoded these to 20 density pixels:

```
    @Override
    public void draw(Canvas canvas, float posx, float posy)
    {
        posx = PixelUtility.convertDpToPixel(20, getContext());
        posy = PixelUtility.convertDpToPixel(20, getContext());

        canvas.translate(posx, posy);
        draw(canvas);
        canvas.translate(-posx, -posy);
    }
```

Thanks for the help @spaultownsend!
