### ISSUE TITLE
PieChart labels

### ISSUE THREAD

**Issue by Edwhis** [PhilJay/MPAndroidChart#180]
Hello,
I have one problem with piechart labels - if one value if really big and others are small, labels overlaps eachother and it is imposible to read something. I tried to do some labels styling, but I found out that piechart doesn't has functions getXLables() and getYlabels(). Is it bug? If not, how can I solve this problem? 

He is screenshot with overlaping lables:
![ss 2014-10-28 at 05 01 42](https://cloud.githubusercontent.com/assets/8588171/4810652/d3d00008-5eb4-11e4-9052-6863c723b69a.png)

**Comment by digimatrix** [comment]
How to display the chart labels outside of the chart?
