### ISSUE TITLE
Set Bar minimum height so text is visible

### ISSUE THREAD

**Issue by JumpMaster** [PhilJay/MPAndroidChart#1802]
After setting labels and values to be shown within the bar it is not always big enough to accommodate the text.

Ideally something along the lines of:
setBarMinimumHeight(int px)

![screenshot_20160522-115254](https://cloud.githubusercontent.com/assets/3468825/15453621/c1ce530a-2014-11e6-8378-545f0cf6a1fa.png)

**Comment by PhilJay** [comment]
`yAxis.setSpaceBottom(50f)` - for example
