### ISSUE TITLE
Image for labels

### ISSUE THREAD

**Issue by Aksi0m** [PhilJay/MPAndroidChart#1803]
Quick question. Is it possible to replace the text labels on an axis with an image?

**Comment by Noires** [comment]
You could overwrite the ChartClass(LineChart as a Example), overwrite the AxisRenderer you want to change(XAxisRenderer as a Example) and exchange it in your ChartClass with the normal one. Then adjust it to your needs, which is a little bit work. But should work by roughly looking over the classes.

But to my knowledge it is not directly implemented yet.

**Comment by Aksi0m** [comment]
Thanks for the response, I hacked my way around it already. Its not the best solution but it was easy to implement and suites my needs perfectly.
