### ISSUE TITLE
Sometimes line chart circles do not show up 

### ISSUE THREAD

**Issue by vineetak** [PhilJay/MPAndroidChart#1806]
Circles on line chart sometimes disappear after refreshing the chart (as in the screenshots. )

`     LineData data = new LineData(xAxis, lineDataSet1);`
  `      lineDataSet1.setColor(getActivity().getResources().getColor(R.color.color_grey));`
  `      lineDataSet1.setDrawCircles(true);`
   `     lineDataSet1.setCircleRadius(2f);`
   `     chart.setData(data);`
 `       chart.setDescription("");`
   `     chart.animateXY(2000, 2000);`
     `   chart.setMaxVisibleValueCount(10);`
      ` chart.setDrawGridBackground(false);`
`        chart.getLegend().setEnabled(false);`
`        chart.setRenderer(new ColoredLineChartRenderer(chart, chart.getAnimator(), chart.getViewPortHandler()));`
 `      chart.setPinchZoom(false);`
   `    chart.setOnClickListener(null);`
   `    chart.setDoubleTapToZoomEnabled(false);`
   `    chart.setHighlightPerTapEnabled(true);`
   `    chart.setHighlightPerDragEnabled(false);`
   `    chart.setScaleEnabled(false);`
`       chart.invalidate();`
![screenshot_2016-05-24-01-40-04](https://cloud.githubusercontent.com/assets/3579381/15483193/103f49d0-2151-11e6-9bbc-8ff95bc0d028.png)
![screenshot_2016-05-24-01-40-17](https://cloud.githubusercontent.com/assets/3579381/15483194/1088146c-2151-11e6-9e3b-ea205244761f.png)

**Comment by PhilJay** [comment]
I am quite sure this has something to do with your custom implementation of the renderer: 

chart.setRenderer(new ColoredLineChartRenderer(chart, chart.getAnimator(), chart.getViewPortHandler()));

I suggest you check your code and see if there is anything wrong.
