### ISSUE TITLE
BUG! when data too small

### ISSUE THREAD

**Issue by gojuukaze** [PhilJay/MPAndroidChart#1807]
my datas:
add(new Entry(833.83f, 0));
add(new Entry(167.11f, 1));
add(new Entry(70.0f, 2));
add(new Entry(49.83f, 3));
add(new Entry(18.75f, 4));
add(new Entry(13.0f, 5));
add(new Entry(3.0f, 6));

Then setSliceSpace
setSliceSpace(3f);

Show like this (it is wrong):
![1](https://cloud.githubusercontent.com/assets/15613304/15500632/31e896fe-216f-11e6-8b72-4a73f6f1429b.jpg)

But setSliceSpace(0f);
Show : 
![2](https://cloud.githubusercontent.com/assets/15613304/15500652/4d1091d4-216f-11e6-9230-437b592cd3d5.png)

**Comment by vguillou** [comment]
Same as #1774
