### ISSUE TITLE
I'm Using PieChart, Can I Do Zero Percent item Invisible?

### ISSUE THREAD

**Issue by wlgnsdi** [PhilJay/MPAndroidChart#1810]
I Always Thank you to Creater of MPAndroidChart!! ^^

now, I'm using PieChart and i want to make invisible Text of Zero percent Item. Is it possible with PieChart Function?!

Like that :
[Issue Picture](https://pbs.twimg.com/media/CjSOPhSWEAUfCrP.jpg:large)

**Comment by PhilJay** [comment]
No, but you can give it a value of > 0 and format the value to 0.
