### ISSUE TITLE
How do I draw a line between different data sets? I want to use 3 different datasets all corresponding to the same x-axis. And I've plotted them using both line chart and scatter chart. I want to show a way in which they connect with each other, with a line. 

### ISSUE THREAD

**Issue by richeekdey** [PhilJay/MPAndroidChart#1811]
![whatsapp-image-20160525](https://cloud.githubusercontent.com/assets/16813242/15537728/a5d7e78c-2295-11e6-853a-7a1a495d18b5.jpg)

**Comment by richeekdey** [comment]
That's how I want it to look

**Comment by richeekdey** [comment]
![screenshot_20160525-164450](https://cloud.githubusercontent.com/assets/16813242/15538184/39ef9008-2298-11e6-9523-061f980cdfdc.png)

**Comment by joaosardinha** [comment]
How did you worked around it?
