### ISSUE TITLE
Barchart display error

### ISSUE THREAD

**Issue by ricky40403** [PhilJay/MPAndroidChart#1815]
after add bar data 

private void addEntry(ArrayList<String>  xval,ArrayList<Float> yval) {
        //***************** bar chart ***********************//
            ArrayList<BarEntry> yVals1 = new ArrayList<BarEntry>();
            for (int i = 0; i < yval.size(); i++) {
                yVals1.add(new BarEntry(yval.get(i), i));
            }
            BarDataSet set = new BarDataSet(yVals1, "BarDataset");
            //cancel label
            set.setBarSpacePercent(50f);
            set.setDrawValues(!set.isDrawValuesEnabled());
            ArrayList<IBarDataSet> dataSets = new ArrayList<IBarDataSet>();
            dataSets.add(set);
            BarData data = new BarData(xval, dataSets);
            mBarchart.setData(data);
            mBarchart.invalidate();
        }

but when the  dataset is all the same value(94623320) , my Barchart display like this :

![default](https://cloud.githubusercontent.com/assets/5608280/15567041/af2f8972-2356-11e6-8a52-8767a4109b2d.png)

but other same dataset value would not cause this problem

Thanks,
RIcky

**Comment by PhilJay** [comment]
`yAxis.setAxisMinValue(0f)`
