### ISSUE TITLE
Building issues

### ISSUE THREAD

**Issue by zorroblue** [PhilJay/MPAndroidChart#1818]
I am not able to build the Example project correctly. I looked up a lot of StackOverflow questions without any progress and that's why I am posting it here([this](http://stackoverflow.com/questions/34605667/android-studio-gradle-version-gradle-version-2-8-is-required/34606234) and [this](http://stackoverflow.com/questions/35153112/gradle-version-2-10-is-required-current-version-is-2-8-error/35153305) and [this](classpath 'com.android.tools.build:gradle:2.0.0-alpha3').) The exact error I am getting is <br>
`Error:(1, 1) A problem occurred evaluating project ':MPChartExample'.> Failed to apply plugin [id 'com.android.application']> Gradle version 2.10 is required. Current version is 2.8. If using the gradle wrapper, try editing the distributionUrl in /home/rameshwar/MPAndroidChart/MPChartExample/gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip` <br>

Can somebody tell me what I need to do?

**Comment by EduardDenisjonoks** [comment]
http://stackoverflow.com/questions/34814368/gradle-version-2-10-is-required-error

**Comment by zorroblue** [comment]
No, that didn't help. I tried upgrading to Android 2.1.1 . Now it gives me an option to upgrade to Gradle 2.10 , which I click and still pops the same message after 2 minutes of build time. :(

**Comment by joshuar500** [comment]
I'm having the same problem...

**Comment by EduardDenisjonoks** [comment]
do u have following line in gradle-wrapper.properties
distributionUrl=https://services.gradle.org/distributions/gradle-2.10-all.zip

**Comment by zorroblue** [comment]
Yes
