### ISSUE TITLE
how can I change the mark view

### ISSUE THREAD

**Issue by kyo313** [PhilJay/MPAndroidChart#1819]
as follow, the mark view is close to the side, how can I change the mark view
![dcf24423-1410-4e46-b6ec-88c124e8f174](https://cloud.githubusercontent.com/assets/3380876/15608639/be31c384-244d-11e6-8b47-650e3c396b2d.jpg)

**Comment by SmallDrogan** [comment]
override draw

**Comment by PhilJay** [comment]
Create a new class and let it extend `MarkerView`.
