### ISSUE TITLE
LineChart LineWidth attribute

### ISSUE THREAD

**Issue by anileger** [PhilJay/MPAndroidChart#182]
Great library dude! Congrats..

My question is how can I set width of lines? (on LineChart)

**Comment by qiaolw** [comment]
Hi, PhilJay:
https://jawbone.com/support/articles/000008210/tracking-sleep-up24 can set BarChart barWidth different?

**Comment by mallikarjun095** [comment]
Hi,
I tried this method (set.setLineWidth(...);) but it's not working
