### ISSUE TITLE
Horizontal Bar Chart, bar is very low

### ISSUE THREAD

**Issue by snyappy** [PhilJay/MPAndroidChart#1820]
![screenshot_2016-05-27-23-01-59_com example snyap graphdemo_1464382943670](https://cloud.githubusercontent.com/assets/19289697/15621462/6a7ae0fe-2461-11e6-8d1f-39e7265690e1.png)
For some reason my bar is really low and I have no idea how to change or influence its height.

xml file: (tried changing min height, layout height, doesn't change it at all)
`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="com.example.snyap.graphdemo.BMI">

    <com.github.mikephil.charting.charts.HorizontalBarChart
        android:id="@+id/chart1"
        android:layout_width="match_parent"
        android:layout_height="100dp"
        android:background="@android:color/white"
        android:layout_alignParentTop="true"
        android:layout_alignParentStart="true"
        android:minHeight="50dp"/>

</RelativeLayout>`

`public class BMI extends AppCompatActivity {

    protected HorizontalBarChart mChart;
    private int [] colors ={R.color.bmiOver , R.color.bmiOkay, R.color.bmiUnder};

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
                WindowManager.LayoutParams.FLAG_FULLSCREEN);
        setContentView(R.layout.activity_bmi);

        mChart = (HorizontalBarChart) findViewById(R.id.chart1);

        mChart.setDrawBarShadow(false);
        mChart.setDescription("");
        mChart.getLegend().setEnabled(false);
        mChart.setPinchZoom(false);
        mChart.setDrawValueAboveBar(false);

        //disables left, top axis
        XAxis xl = mChart.getXAxis();
        xl.setEnabled(false);
        YAxis yl = mChart.getAxisLeft();
        yl.setEnabled(false);

        YAxis yr = mChart.getAxisRight();
        yr.setDrawAxisLine(true);

        yr.calcMinMax(0f,40f);

        setData();
        mChart.animateY(2000);
    }

    private void setData() {

        ArrayList<String> bmiValues = new ArrayList<>();
        for (int i = 0; i <= 40; i++) {
            bmiValues.add(i,String.valueOf(i).toString());
        }

        ArrayList<BarEntry> entries = new ArrayList<>();
        entries.add(new BarEntry(40f, 0));
        entries.add(new BarEntry(25f, 0));
        entries.add(new BarEntry(18.5f, 0));

        //BarDataSet contains yAxis, yAxis legend
        BarDataSet bmi = new BarDataSet(entries, "BMI");
        bmi.setColors(colors, getApplicationContext());
        bmi.setDrawValues(true);
        //BarData contains xAxis, yAxis
        BarData data = new BarData(bmiValues, bmi);

        mChart.setData(data);
        mChart.invalidate();
    }
}`

**Comment by PhilJay** [comment]
entries.add(new BarEntry(40f, 0));
    entries.add(new BarEntry(25f, 0));
    entries.add(new BarEntry(18.5f, 0));

change to

entries.add(new BarEntry(40f, 0));
    entries.add(new BarEntry(25f, 1));
    entries.add(new BarEntry(18.5f, 2));

**Comment by snyappy** [comment]
Thanks for the fast reply but it while it does change the position of the bar, the height still doesn't change.
![screenshot_2016-05-27-23-57-29_com example snyap graphdemo](https://cloud.githubusercontent.com/assets/19289697/15622259/549138f0-2467-11e6-99c4-c794656cb15c.png)

Tried changing them to a stacked BarEntry but that didn't work either.
