### ISSUE TITLE
PieChart: Using percent and absolute values

### ISSUE THREAD

**Issue by malte1989** [PhilJay/MPAndroidChart#1822]
Hi,

First: Really awesome library!

I am trying to get the percent and the absolute value into an piechart. I tried to create a custom Formatter but this doen't work because the chart object is either providing percent values OR absolute values (triggered with setUsePercentValues).

Is there any possiblity to get both values into the formatter?

2
1
or
66%
33%

Goal: 
66% (2)
33% (1)

Best regards

**Comment by PhilJay** [comment]
`pieChart.setUsePercentValues(true)` will turn anything into percent.

But you cannot get both values from the formatter.

If you have access to your data object, you can calculate the percentages yourself by using the `data.getYValueSum()` method.
