### ISSUE TITLE
Y value text is drawn in front of limit line

### ISSUE THREAD

**Issue by Chozzle** [PhilJay/MPAndroidChart#1824]
![2016-05-29 14 35 59](https://cloud.githubusercontent.com/assets/11524191/15633338/b4f5daf4-25aa-11e6-8136-ca979d279da4.png)
It looks ugly and it should be drawn behind limit line

**Comment by PhilJay** [comment]
`yAxis.setDrawLimitLinesBehindData(true)`

**Comment by Chozzle** [comment]
I don't want the line behind the data. I want it in front of the bars and the values. I've fixed it for my app by just moving drawValues before drawLimitlines in BarLineChartBase. I believe the line should be in front of values by default. The default behaviour above looks ugly. Cheers
