### ISSUE TITLE
The value of YAxis is wrong 

### ISSUE THREAD

**Issue by wtwt91** [PhilJay/MPAndroidChart#1825]
When the values are small and closed，the values will show the same numbers, like this:
![11](https://cloud.githubusercontent.com/assets/3053007/15638501/d3e924e4-2653-11e6-9651-7a1d90cb0725.png)
Maybe it should be show as the 0.441, 0.442, 0.443...

**Comment by vit001** [comment]
This is a bug which has been around for a long time and for some reason and devs refuse to fix it. See #1607.

**Comment by wtwt91** [comment]
So maybe I should download the code, and fix it in my project, Actually. I don't want to do it like this... Because I want to reduce the libraries in my project.

**Comment by vit001** [comment]
Yes, download the source and fix it. That's what I did.

**Comment by wtwt91** [comment]
Ok~ thanks

**Comment by macjay** [comment]
I have the some problem.I do as #1607 ,but still have the problem.do you know how to fix it?

**Comment by vit001** [comment]
Without any more information from you, I have absolutely no clue.

**Comment by wtwt91** [comment]
Maybe you should set it like this.

```
YAxisValueFormatter valueFormatter = new DefaultYAxisValueFormatter(3);
            leftAxis.setValueFormatter(valueFormatter);

```

**Comment by TR4Android** [comment]
@wtwt91 Did you try the granularity property? Something like `mChart.getAxisLeft().setGranularity(0.1f)`. Or if you want to use three decimal places use `0.001f`. Check the [docs](https://jitpack.io/com/github/PhilJay/MPAndroidChart/v2.2.5/javadoc/com/github/mikephil/charting/components/YAxis.html#setGranularity(float)) for more info. You'll also have to enable this using `mChart.getAxisLeft().setGranularityEnabled(true) `.

**Comment by wtwt91** [comment]
@TR4Android OK, thanks, It works well too.

**Comment by TR4Android** [comment]
@wtwt91 Sure, no problem :wink: 
If this issue has been resolved and you want to do @PhilJay a favor you could close this issue. That'd be really helpful, since he already has enough work maintaining this library as it is. Thanks!

**Comment by rathymathy** [comment]
but for me
mChart.getAxisLeft().setGranularityEnabled(true).. is not workin.why it is??
what can i do? i am using mpandroidchart2.0.9 .any one please help me

**Comment by TR4Android** [comment]
@rathymathy Make sure you are also setting a granularity using `mChart.getAxisLeft().setGranularity(0.1f)` (which restricts the axis to one decimal point). If that doesn't work, I'd highly suggest you update to the latest version (3.1.0 at the time of writing).

**Comment by rathymathy** [comment]
> @rathymathy Make sure you are also setting a granularity using `mChart.getAxisLeft().setGranularity(0.1f)` (which restricts the axis to one decimal point). If that doesn't work, I'd highly suggest you update to the latest version (3.1.0 at the time of writing).

> @TR4Android ...Thank you.

> are there any other ways to change the size between two gridlines??? beacuse

> i am building an ecg app .so i want set 1mm space between two small grid lines and highlight the gridlines between 5mm. how can do that ???..
