### ISSUE TITLE
MPAndroidChart: setting last line as transparent hides other lines

### ISSUE THREAD

**Issue by aalih** [PhilJay/MPAndroidChart#1826]
I have a LineChart with several datasets that the user can show/hide. The algorithm to show/hide each dataset is something like this:

```
LineDataSet set = chart.getData().getDataSetByIndex(item.getIndex());
int color = item.isEnabled() ? Color.TRANSPARENT : item.getColor();
set.setColor(color);
set.setCircleColorHole(color);
set.setCircleColor(color);
set.setDrawValues(!item.isEnabled());
chart.invalidate();
```
It works perfect for the n-1 first datasets, but when applied to the last dataset the lines of the other datasets disappear too (circles and text values remain, but the lines joining each circle are transparent). The weird thing is that if i change TRANSPARENT for any other color (Ex: RED) it works as expected.

**Comment by PhilJay** [comment]
Please use the built in feature for hiding and showing datasets, it's much easier:

`dataSet.setVisible(false)` - for hiding

**Comment by HannahCarney** [comment]
Oh god I was stuck on this bug for ages! Transparent does not work when your last dataset is set to transparent - thanks!

**Comment by micHar** [comment]
It appears that the alpha value of the color set to the line overrides the one for other data sets. E.g. when I set the line color to Color.parse("#5FFF") all of the data in all sets become semi-transparent.
