### ISSUE TITLE
Offset from zero

### ISSUE THREAD

**Issue by richeekdey** [PhilJay/MPAndroidChart#1827]
Hi, 
I recently updated to the newest version of the APi and since then there has been an offset from the zero in all my graphs. I don't want an offset. How do I set the offset to null? I tried chart.setDragOffsetX(0) and chart.setDragOffsetY(0), they are not giving me the correct response. Any way to fix this? This was not an issue in the older versions. 
![screenshot_20160531-123628](https://cloud.githubusercontent.com/assets/16813242/15666151/c14f7a7a-272c-11e6-8044-8562cc36ebfe.png)

**Comment by PhilJay** [comment]
`chart.setViewPortOffsets(0, 0, 0, 0)` 

Does this help?

**Comment by richeekdey** [comment]
Unfortunately, no.

**Comment by richeekdey** [comment]
If i do that, my x-axis disappears completely. I just want the spacing between the axis and the '0' point to not be there. It was fine before, can you suggest the which older version should I downgrade to?

**Comment by TR4Android** [comment]
@richeekdey Have you tried setting the minimum value of the y axis to zero? Something like `chart.getAxis().setAxisMinValue(0)`.

**Comment by richeekdey** [comment]
Yeah, still no luck :(

**Comment by richeekdey** [comment]
Oh and the candlestick chart is incorrect now. Even though I specify the max and min values, it always starts from zero. =/

**Comment by richeekdey** [comment]
I can't even downgrade to 2.1.6 now. it gives no direct method error. =/

**Comment by BosAtWork** [comment]
One of your axis has not aligned it's zero to the bottom. In your screenshot it looks like the left axis. So get the left axis and set axisMinValue to zero. I had the same project in the iOS port so not sure what the exact java syntax is.

**Comment by PhilJay** [comment]
Now I get it :-)
Just set the y-axis minimum value to zero. This was set to default 0 in previous versions and is now dependant on the values.

So `yAxis.setAxisMinValue(0f)` should fix your problem.
