### ISSUE TITLE
PieChart: values outside of chart

### ISSUE THREAD

**Issue by Scrounger** [PhilJay/MPAndroidChart#1828]
@danielgindi 
First thanks for this amazing feauture!

Please take a look at the screenshot.
1. Is there a way to wrap the outsidelabels or to auto adjust the whole size of the piechart depending of the outside labels?
2. Is it possible to add more space between the outsidelabels to prevent overlapping?

![chart](https://cloud.githubusercontent.com/assets/6370451/15687128/68901aec-2773-11e6-91b1-0ee02cc1b0e6.jpg)

**Comment by danielgindi** [comment]
In addition to playing with the various line properties - you may want to add "extra offset" to the pie chart View, to add space for those label. Have fun :-)

**Comment by danielkummer** [comment]
A more in-detail explanation would be very helpful :) 👍

**Comment by danielgindi** [comment]
It is well demonstrated in the demo

**Comment by MyGitUserAcc** [comment]
@Scrounger  How do you made this text outside the piechart??Please reply..

**Comment by BongJaeChoi** [comment]
@danielgindi you save my life. Thank you so much.

**Comment by mecoFarid** [comment]
@danielgindi What? When text gets bigger add more padding? :)
