### ISSUE TITLE
Scrolling when Y-Axis is Inverted without any Datapoint

### ISSUE THREAD

**Issue by laurinmueller** [PhilJay/MPAndroidChart#1829]
The Scrolling missbehaves(wrong direction) with an empty chart whithout any datapoint:
Code for Reproduction:

`
        LineChart chart = (LineChart) getActivity().findViewById(R.id.chart);

        LineData data = new LineData();
        List<String> values=new ArrayList<>();
        for(int x=0;x<=240;x++){
            values.add(""+x);
        }
        data.setXVals(values);
        chart.setData(data);
        chart.setVisibleXRange(0,30);
        chart.setDescription(getResources().getString(R.string.dive_profile));
        chart.getAxisRight().setEnabled(false);

        YAxis depthAxis = chart.getAxisLeft();
        depthAxis.setInverted(true);
        depthAxis.setAxisMaxValue(300);
        depthAxis.setAxisMinValue(0);

        XAxis timeAxis = chart.getXAxis();
        timeAxis.setAxisMinValue(0);
        timeAxis.setAxisMaxValue(240);
        timeAxis.setEnabled(true);
        timeAxis.setDrawGridLines(true);

        timeAxis.setValues(values);

        chart.invalidate();`

The following Fix worked for me:

![bugfix](https://cloud.githubusercontent.com/assets/1231069/15693114/055131d0-2793-11e6-94e4-0f73108ba86e.PNG)

Thank you anyway for your good work!

Cheers Laurin

**Comment by PhilJay** [comment]
I have
