### ISSUE TITLE
set.setCircleColorHole(Color.WHITE)  does not work.

### ISSUE THREAD

**Issue by JackLeeMing** [PhilJay/MPAndroidChart#1834]
LineDataSet set1 = new LineDataSet(yVals, s);           
            set1.setDrawCircleHole(true);
            set1.setCircleColorHole(Color.WHITE);

this method set.setCircleColorHole(Color.WHITE) does not work.

**Comment by PhilJay** [comment]
What does "does not work" mean?
What happens?
