### ISSUE TITLE
how to Keep three decimal places in yAxis?

### ISSUE THREAD

**Issue by macjay** [PhilJay/MPAndroidChart#1835]
I want to the result as bellow,how can i do?
![wxid_ygt4l3ie6f2i22_1464864311347_54](https://cloud.githubusercontent.com/assets/3992332/15742594/86e59776-28f2-11e6-9016-f568a60b60fc.png)

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/The-YAxisValueFormatter-interface

**Comment by PhilJay** [comment]
Use a DecimalFormat with 3 decimals.
