### ISSUE TITLE
How to show 2 lines with different number of dataset entries on LineChart

### ISSUE THREAD

**Issue by t7ank** [PhilJay/MPAndroidChart#1836]
I have 2 arrays of avg.values per month. But it is not necessary that both arrays have same number of entries. I can not bind values to their X label. If second line has less values in array it starts at the beginning of chart (first image) but should leave out some "X values".
Second image shows what i want to achieve. Please link me to the similar issue if it already exists.

Current situation:
![chartproblem](https://cloud.githubusercontent.com/assets/19713784/15753121/b5928486-28f1-11e6-8d90-d27ef6ed79e0.png)

Wanted result:
![chartproblemwantedresult](https://cloud.githubusercontent.com/assets/19713784/15753135/c1f57f44-28f1-11e6-8264-8f3d6e44b00d.jpg)
*values should be 2.5@Mar, 3.5@May, 4.0@Jun

**Comment by anshul90** [comment]
Great work is done by you @t7ank 

Can you please tell me how to change range of y-Axis dynamically as you're showing -2 to 10 according of values ?

**Comment by jessb417** [comment]
I am facing this issue as well.  Have you had any luck with it?  Thanks!

**Comment by PhilJay** [comment]
You used x-index 0 - 1 - 2 for your entries. However, you need to use the following entries:

new Entry(2.5f, 1)
new Entry(3.5f, 3)
new Entry(4.5f, 4)
