### ISSUE TITLE
PieChart different color for x and y labels

### ISSUE THREAD

**Issue by Maradox** [PhilJay/MPAndroidChart#1837]
I'm using a PieChart with `dataSet.setYValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);` I would like to color the y-labels outside black, while the x-labels inside should be white. I did not find a way to do that, is it possible?

**Comment by PhilJay** [comment]
Not yet possible, but good input, I will add this feature in the new release.

**Comment by PhilJay** [comment]
possible now 82d5fde6f2e8fc7ef1f90257de3671bac6d2d544

release v3.0.0 will contain the new feature
