### ISSUE TITLE
Line sliders in MPAndroidChart

### ISSUE THREAD

**Issue by zorroblue** [PhilJay/MPAndroidChart#1839]
Also posted at : http://stackoverflow.com/questions/37607317/custom-line-slider-in-mpandroidchart

Hi, I have been trying to include a line slider at the bottom of my real-time plotting data graph. I searched around in StackOverflow and googled a lot regarding this. I tried manually adding a seekbar and trying to highlight the thumb's x index, but it wasn't working and moreover I need something like scroll bar. 
The closest on SO I could find was [http://stackoverflow.com/questions/29743092/creating-a-line-slider-on-a-graph-in-android] . I basically need an additional  vertical line slider that on sliding would highlight the point it intersects in the graph. Something like this.

![chart](https://cloud.githubusercontent.com/assets/8344320/15770451/8367e1fa-2981-11e6-91df-9e7065b359ab.jpg)  

Can someone tell me how I can implement this?

**Comment by PhilJay** [comment]
I'm not sure I fully understand. This looks like a very basic thing to do.

Could you further evaluate?

**Comment by zorroblue** [comment]
At present , we have HighlightLines which can highlight the x-value when we touch the chart at that x point. I want to extend it further by using a line slider underneath, which is not yet implemented in the library( according to my knowledge, I would be glad if you corrected me here). I tried using a seekbar and measuring the x-coordinate of  the thumb. But I don't find a way to put a highlight line at an "absolute coordinate" rather than an x-value

**Comment by PhilJay** [comment]
So what you want is a feature to drag your finger across the chart and highlight the value underneath, instead of "clicking" the chart?

**Comment by zorroblue** [comment]
Yes. I want the line to be at the closest x value to the slider's thumb which is movable.

**Comment by PhilJay** [comment]
Okay, that should already be possible, which issues are you experiencing? Did you set `chart.setHighlightPerDragEnabled(true)`?

**Comment by zorroblue** [comment]
I did that. But that isn't exactly what I need because I need a line slider under the graph. I made a seekbar and got its thumb's coordinate. But I don't see a way to highlight at a coordinate.

**Comment by PhilJay** [comment]
All you have to do is create a highlight object that corresponds to the position you touched, and then set it for the chart:

`chart.highlightValue(...)`

You can easily create that object yourself or use this method:

`chart.getHighlightByTouchPoint(x, y)` where x and y are screen pixels.

**Comment by zorroblue** [comment]
Hi @PhilJay , I tried what you suggested. It was matching my requirement but the problem is that the Highlight line isn't moving as expected at times. I built upon your `PerformanceLineChart.java` . I modified the onProgressChanged() mainly

`  @Override
    public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {

        int count = mSeekBarValues.getProgress() + 1000;
        mTvCount.setText("" + count);

       // mChart.resetTracking();
        Rect pos=mSeekBarValues.getThumb().getBounds();
        float position= ((float)pos.left+pos.right)/2;
        float positionY=(float)(pos.top+pos.bottom)/2;
        Highlight highlight=mChart.getHighlightByTouchPoint(position,0);

        mChart.highlightValue(highlight);
        mChart.setHighlightPerDragEnabled(true);
        Log.d("DEBUG123",new Float(pos.left).toString()+" "+new Float(pos.right).toString());
        setData(count, 500f);
        line.setEnabled(true);
        line.setBackgroundColor(Color.GREEN);
        line.setMinimumWidth(10);
        // redraw
        mChart.invalidate();
    }
`

Here is the screenshot: 

![scr1](https://cloud.githubusercontent.com/assets/8344320/16278759/b2051286-38d5-11e6-8a31-ff67fc47c90f.png)

Can you tell me where I am going wrong?

**Comment by kksingla** [comment]
Hey, I want similar functionality. Please suggest. I tried a lot but unable to do this.
I had also set : setHighlightPerDragEnabled(true);

![negbb](https://user-images.githubusercontent.com/18482328/34378810-ee2389ea-eb1d-11e7-9f0b-05924537ef3a.png)

**Comment by kksingla** [comment]
mChart.setHighlightPerDragEnabled(true);
        mChart.setHighlightPerTapEnabled(false);
        // set data
        mChart.setData(data);
        Highlight highlight = mChart.getHighlightByTouchPoint(70, 3);
        Highlight highlight1 = mChart.getHighlightByTouchPoint(90, 3);
        mChart.highlightValue(highlight);
        mChart.highlightValues(new Highlight[]{highlight, highlight1});
