### ISSUE TITLE
custom XAxis grid line

### ISSUE THREAD

**Issue by tankjj** [PhilJay/MPAndroidChart#1840]
Hi guys,
I'm try to custom X-Axis grid line in my project, for every 5 X-Axis values, draw one thin grid line, for every 10 X-Axis values, draw one thick grid line.

Can anyone tell me how to implement it?

Thanks a lot in advance.

**Comment by PhilJay** [comment]
You will have to modify the library to achieve that. You can start by looking at the XAxisRenderer class.

**Comment by PankajDandriyal** [comment]
@PhilJay  i want grid lines for all the labels e.g. if i have labels in X-Axis like 0 4 8 16....  and  so on  i want grid line for 1,2,3 same goes for Y-Axis also also,which is not visible , how should i do this?

Can u please help, have been stuck at it for days..

Thanks  a lot in advance !!..
