### ISSUE TITLE
Bar chart issue

### ISSUE THREAD

**Issue by Arunkarthicknallasami** [PhilJay/MPAndroidChart#1846]
I am trying to load data dynamically from a web response. I did manage to load couple of reports and It seemed satisfying.When examining it closely i came to know that in some case labels in xAxis are missing i.e data is present in array but only odd positions (0,1,3..etc) gets loaded. Is it an issue with library or with my code?

**Comment by keith30xi** [comment]
It will be difficult to diagnose the issue without code.  Can you provide a basic running example that demonstrates the issue?

**Comment by talhahasanzia** [comment]
I think this is not issue, when you zoom in, it will display all data. Like this weekdays example, where only Monday, Wednesday, Friday, Sunday are shown unless you zoom in to see all labels.
![zoom](https://cloud.githubusercontent.com/assets/7442631/15882842/28875d72-2d5c-11e6-848f-6b0cd83c1bd4.png)

**Comment by Arunkarthicknallasami** [comment]
Thank you all for your support. I got it resolved by setting xAxis.setLabelsToSkip(0)
