### ISSUE TITLE
Horizontal BarChart in ViewPager

### ISSUE THREAD

**Issue by JamesLeit** [PhilJay/MPAndroidChart#1848]
Hi,

i tried your BarChart out and I'm not able to find what's wrong with my code.
My BarChart is placed in a Fragment. The Fragment is placed in ViewPager.
The first Fragment (incl. the BarChart) looks correct, but after swiping to the other, the BarChart properties are reseted.

**Properties like:**
barchart.setViewPortOffsets(0f, 0f, 0f, 0f);
barchart.getAxisRight().setSpaceTop(0f);
barchart.getAxisRight().setSpaceBottom(0f);

**My BarChart Setup:**
https://www.dropbox.com/s/4p1i74hsls7bf0o/pic1.jpg?dl=0

**Step by Step walk through:**
https://www.dropbox.com/s/4p1i74hsls7bf0o/pic1.jpg?dl=0

My PagerAdapter's getItem(int position) returns a new instance of BarChart Fragment.

It only happens if the ViewPagers recreate the fragment after swiping. If i set the offscreenlimit higher.. no problems.

If I place the fragment (incl. BarChart) three times in my ViewPager (different instances). the 2. and 3. are never correct. Why?

Greetings,
James

**Comment by PhilJay** [comment]
Sorry, links no longer work. Can you post the code here?
