### ISSUE TITLE
Bug for use DefaultValueFormatter

### ISSUE THREAD

**Issue by AngelOfMors** [PhilJay/MPAndroidChart#1849]
I'am use in my App:
DefaultValueFormatter dvf = new DefaultValueFormatter(0);
barSet[i].setValueFormatter(dvf);

in Chart.java / public void setData(T data)
...
        for (IDataSet set : mData.getDataSets()) {
            if (Utils.needsDefaultFormatter(set.getValueFormatter()))
                set.setValueFormatter(mDefaultFormatter);
        }
Change my DefaultValueFormatter(0) to DefaultValueFormatter(1)

**Comment by PhilJay** [comment]
The DefaultFormatter is for library internal use only. If you want to format your values with 1 decimal digit, please write your own class and let it implement the ValueFormatter interface.

I might change this in the future, but for now this should be a sufficient solution.
