### ISSUE TITLE
Grid Lines are always shown regardless of setDrawGridLines() call.

### ISSUE THREAD

**Issue by talhahasanzia** [PhilJay/MPAndroidChart#1850]
Using BarChart, when the method call `BarChart.setDrawGridLines(false)` is made it still shows grid background. By my understanding calling this method is enough to disable gridlines. Other things work fine on updating the chart. Using following code.

        barChart.setData(barData);
        barChart.setDrawGridBackground(false);
        barChart.notifyDataSetChanged();   
        barChart.invalidate();

**_EDIT:_** I have managed to remove vertical grid lines by calling
`barChart.getXAxis().setDrawGridLines(false)`,
however, horizontal lines are there and there is no method for getYAxis(), is this possible?

**Comment by TR4Android** [comment]
@talhahasanzia Maybe `chart.getAxisLeft( )` and `chart.getAxisRight( )` might be of help?

**Comment by PhilJay** [comment]
@TR4Android has the solution.

**Comment by Nfear** [comment]
So what does `setDrawGridBackground(false)` exactly do if it doesn't disable the grid?

**Comment by TR4Android** [comment]
@Nfear Some code would be helpful. Do you call `invalidate()` on your chart after disabling the grid?

**Comment by Nfear** [comment]
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:weightSum="2">

        <com.github.mikephil.charting.charts.BarChart
            android:id="@+id/chart"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1" />

    </LinearLayout>

I use [Data Binding Library](https://developer.android.com/topic/libraries/data-binding/index.html) to access the cart and the chart is shown on a `support.v4.app.Fragment`.

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        binding.chart.setDrawGridBackground(false);
        binding.chart.invalidate();
    }

The chart shows, but the grid is still drawn.

**Comment by iRuth** [comment]
@Nfear, depending on which axis is enabled and has the grid lines, you can disable it with the code below. `binding.chart.setDrawGridBackground(false);` disables the grid background and not the grid lines.

```
binding.chart.getXAxis().setDrawGridLines(false); // disable grid lines for the XAxis
binding.chart.getAxisLeft().setDrawGridLines(false); // disable grid lines for the left YAxis
binding.chart.getAxisRight().setDrawGridLines(false); // disable grid lines for the right YAxis
```

**Comment by Oprea-Bogdan95** [comment]
Hello I'm trying to disable the grid lines on a radar chart on the x and y axis like this:
_fragmentBinding?.radarChart?.xAxis?.setDrawGridLines(false)
_fragmentBinding?.radarChart?.yAxis?.setDrawGridLines(false)
but the lines are still there. 
Does anyone know what the problem could be?
Thank you in advance.
