### ISSUE TITLE
Anyway to change sort(from asc to desc) in HorizontalBarChart?

### ISSUE THREAD

**Issue by dyguests** [PhilJay/MPAndroidChart#1851]
In HorizontalBarChart.The chart is like this:
4:-------------
3:--
2:------
1:--------

I want to change to this:

1:--------
2:------
3:--
4:-------------

is there any way to do this **without reverse Data**?

**Comment by PhilJay** [comment]
Not at the moment, but you can simply give values that you want to be displayed on top a higher x-index than others? Or is there any problem with that?

**Comment by dyguests** [comment]
Got it,thanks.
