### ISSUE TITLE
PieChart not displayed in a tab(Fragment)

### ISSUE THREAD

**Issue by nihalm95** [PhilJay/MPAndroidChart#1852]
I am creating an android app with 3 horizontal tabs(fragments). The first tab displays a pie chart. Since, this was my first time using this MPAndroidChart library, I decided to implement the demo pie-chart fragment code given in github. After I did everything and ran the app, the first tab is empty, it does not display anything, nor does it give any error. Kindly help me. Thanks in advance..

Here is my code:

PieChartFrag.java--

import android.graphics.Color;
import android.graphics.Typeface;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.text.SpannableString;
import android.text.style.ForegroundColorSpan;
import android.text.style.RelativeSizeSpan;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.github.mikephil.charting.charts.PieChart;
import com.github.mikephil.charting.components.Legend;
import com.github.mikephil.charting.components.Legend.LegendPosition;
//import com.xxmassdeveloper.mpchartexample.R;

public class PieChartFrag extends TabFragment1 {

    public static Fragment newInstance() {
        return new PieChartFrag();
    }

    private PieChart mChart;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.frag_simple_pie, container, false);

        mChart = (PieChart) v.findViewById(R.id.pieChart1);
        mChart.setDescription("");

        Typeface tf = Typeface.createFromAsset(getActivity().getAssets(), "OpenSans-Light.ttf");

        mChart.setCenterTextTypeface(tf);
        mChart.setCenterText(generateCenterText());
        mChart.setCenterTextSize(10f);
        mChart.setCenterTextTypeface(tf);

        // radius of the center hole in percent of maximum radius
        mChart.setHoleRadius(45f);
        mChart.setTransparentCircleRadius(50f);

        Legend l = mChart.getLegend();
        l.setPosition(LegendPosition.RIGHT_OF_CHART);

        mChart.setData(generatePieData());

        return v;
    }

    private SpannableString generateCenterText() {
        SpannableString s = new SpannableString("Revenues\nQuarters 2015");
        s.setSpan(new RelativeSizeSpan(2f), 0, 8, 0);
        s.setSpan(new ForegroundColorSpan(Color.GRAY), 8, s.length(), 0);
        return s;
    }
}

TabFragment1--

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.graphics.Color;
import android.graphics.Typeface;
import com.github.mikephil.charting.data.Entry;
import com.github.mikephil.charting.data.PieData;
import com.github.mikephil.charting.data.PieDataSet;
import com.github.mikephil.charting.utils.ColorTemplate;
import com.github.mikephil.charting.utils.FileUtils;
import java.util.ArrayList;

public class TabFragment1 extends Fragment {

    private Typeface tf;

    public TabFragment1(){}

    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        tf = Typeface.createFromAsset(getActivity().getAssets(), "OpenSans-Light.ttf");
        return super.onCreateView(inflater, container, savedInstanceState);
        //return inflater.inflate(R.layout.tab_fragment_1, container, false);
    }

    protected PieData generatePieData() {

        int count = 4;

        ArrayList<Entry> entries1 = new ArrayList<Entry>();
        ArrayList<String> xVals = new ArrayList<String>();

        xVals.add("Quarter 1");
        xVals.add("Quarter 2");
        xVals.add("Quarter 3");
        xVals.add("Quarter 4");

        for(int i = 0; i < count; i++) {
            xVals.add("entry" + (i+1));

            entries1.add(new Entry((float) (Math.random() * 60) + 40, i));
        }

        PieDataSet ds1 = new PieDataSet(entries1, "Quarterly Revenues 2015");
        ds1.setColors(ColorTemplate.VORDIPLOM_COLORS);
        ds1.setSliceSpace(2f);
        ds1.setValueTextColor(Color.WHITE);
        ds1.setValueTextSize(12f);

        PieData d = new PieData(xVals, ds1);
        d.setValueTypeface(tf);

        return d;
    }

    private String[] mLabels = new String[] { "Company A", "Company B", "Company C", "Company D", "Company E", "Company F" };
//    private String[] mXVals = new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dec" };

    private String getLabel(int i) {
        return mLabels[i];
    }
}

frag_simple_pie.xml--
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="100dp"
    android:layout_height="100dp"
    android:orientation="vertical" >

    <com.github.mikephil.charting.charts.PieChart
        android:id="@+id/pieChart1"
        android:layout_width="20dp"
        android:layout_height="20dp" />

</LinearLayout>

tab_fragment_1.xml--
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context="com.nic.nihal.nicapp.TabFragment1">

    /* <TextView
        android:id="@+id/textView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:text="CITIZEN"
        android:textAppearance="?android:attr/textAppearanceLarge"/> */

    <ImageView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:src="@drawable/pie"
        />

</RelativeLayout>

---------------------------
As you can see most of the code is as written by Phil Jay, with little or no modifications. My aim was to implement this demo pie-chart, see if it works, and then modify the code to display my intended pie-chart. But, unfortunately i ran into this problem. Any help is appreciated. Thanks.

**Comment by PhilJay** [comment]
The reason why your chart is not displayed is because it's extremely small (only 20dp according to your xml). Even more space is covered by the side offsets of the chart, that is why you cannot see it.

You should either increase the size of the chart or remove it's offsets via calling `chart.setViewPortOffsets(0,0,0,0)`.

**Comment by nihalm95** [comment]
where do i call chart.setViewPortOffsets(0,0,0,0);??
i called it in PieChartFrag.java after setData(), but it displays an error saying that setViewPortOffsets(0,0,0,0) in not resolved.
