### ISSUE TITLE
X-axis values are not wrapped

### ISSUE THREAD

**Issue by BalalakshmiSadhasivam** [PhilJay/MPAndroidChart#1855]
I am currently using BarChart and  I am facing some few issues in them.

**#Issue 1:**

In BarChart, x-axis values are not getting wrapped which results in overlapping of values. For example, if some x-axis labels are larger in length, then those values overlap the nearby labels.

**In the below image, the x-value at the 0th index is 'Test:ThisIsToTestALongMessageInX-AxisValue'. This is how the screen looks for this scenario.**

![issue_in_wrapping](https://cloud.githubusercontent.com/assets/14068048/15964589/ec7f311a-2f36-11e6-9288-686ac81f37f3.png)

**whereas the expected output should be like the following**
![expected](https://cloud.githubusercontent.com/assets/14068048/15963852/b7cbdf76-2f32-11e6-8440-c49d60222385.png)

**Issue 2:**

 In the case of HorizontalBarChart, plenty (sometimes all values) of y-values are being shown in the y-axis.

**In the following chart, all the values are shown in y-axis.**
![y-axis](https://cloud.githubusercontent.com/assets/14068048/15933743/80965fea-2e7e-11e6-88de-db9e1f0f3cb2.png)

**Issue 3:**

As mentioned in the previous case, all the x-values are being displayed in the HorizontalBarChart.

**In the following chart, it can skip some labels. But all the values are shown here which can't be done if there are a large number of values(say 20).**
![barchart](https://cloud.githubusercontent.com/assets/14068048/15933761/9601dddc-2e7e-11e6-95f9-22e9e978cf33.png)

**Note:**
**`xAxis.setLabelsToSkip();`** is not set to zero. So all the values need not be shown in the chart.

Even though **Issue 1**  can be handled with a **CustomValueFormatter** by wrapping the values, I can't  calculate the number of labels to be shown in the axis at that moment . 

**1. Is there any way to calculate the number of values to be shown in x-axis and y-axis (based on zoom level if zooming is allowed)?
2. Is it possible to dynamically wrap the x-axis value based on the number of values shown at that moment to get rid of overlapping of values?**  For example, at some instance the chart might get zoomed, we should be able to  calculate number of x-values to be shown and alter the length of the  label (value at the x-axis at a particular index) accordingly and if the zoom gets changed (which can be found be getScaleY() ), then the number of values to be shown should be calculated again and based on that x-axis label should be altered.

**Comment by shubhapp** [comment]
I am also facing the same issue. Did you find any workaround ?

**Comment by sau05** [comment]
Will you please elaborate how you have fixed **issue 1** ?

**Comment by randikawann** [comment]
there is no any solution for this issue.. @PhilJay is thereany solutions for that
