### ISSUE TITLE
setVisibleXRangeMaximum and setVisibleYRangeMaximum not working

### ISSUE THREAD

**Issue by BalalakshmiSadhasivam** [PhilJay/MPAndroidChart#1858]
Hi,

setVisibleXRangeMaximum(int) and  setVisibleYRangeMaximum(int ,AxisDependency) functions are not working in this chart.

I've set `setVisibleXRangeMaximum(3)` and `setVisibleYRangeMaximum(3,YAxis.AxisDependency.LEFT)`. The expected chart should contain a maximum of 3 values on x-axis and 3 values on y-axis.
But the chart is currently showing all the values. Kindly let me know the reason for this issue.

**Screenshots:**

The above-mentioned functions are not working on the chart. I've added the screenshots for LineChart and BarChart.

![linechart](https://cloud.githubusercontent.com/assets/14068048/15957272/a1d84622-2f0b-11e6-908e-a2eff1dcd815.png)

**Comment by Oleksandr32** [comment]
I had the same problem and I fixed that.
First add your data and then set max visible range
    `chart.data = BarData(BarDataSet(entries, "title"))`
    `chart.setVisibleXRangeMaximum(7f)`
    ` chart.invalidate()`
