### ISSUE TITLE
Unable to setGranularityEnabled to false

### ISSUE THREAD

**Issue by pramadae** [PhilJay/MPAndroidChart#1862]
Yaxis.java

public void setGranularityEnabled(boolean enabled) {
        mGranularityEnabled = true;
    }

Since above method always uses true instead of "enabled" parameter which does not allow me to setGranularity to false

**Comment by pramadae** [comment]
Philip, I see that you have changed it in Axisbase.java, but the source code has the above code in YAxis.java file

**Comment by PhilJay** [comment]
Yes, that is a new branch, a lot of code from YAxis has been moved to AxisBase.

**Comment by pramadae** [comment]
When can we expect the new branch release? Thanks in advance!!

**Comment by PhilJay** [comment]
Probably a couple of more weeks. I plan to release at 10k stars. There will probably be a beta release before that.

**Comment by pramadae** [comment]
In my understanding, it was one line change to yaxis.java. If possible, Could you please commit the change, so that we can use it as we need that immediately.  Thanks in advance.
