### ISSUE TITLE
setHoleColorTransparent not available in 2.2.5

### ISSUE THREAD

**Issue by RamPattikonda** [PhilJay/MPAndroidChart#1863]
Was able to use setHoleColorTransparent for pie chart in 2.2.0. It is not there in 2.2.5. Is there a replacement function. 

Thank you,
Ram

**Comment by PhilJay** [comment]
mChart.setHoleColor(Color.TRANSPARENT);

**Comment by RamPattikonda** [comment]
Thank you Phil. 

Your library is the best. Great features, Great support. It is Awesome!
