### ISSUE TITLE
Icons in legend

### ISSUE THREAD

**Issue by mtrakal** [PhilJay/MPAndroidChart#1864]
Hi,

could be possible add icons to graphs legend? I think that currently no, right?

It would be nice, when you can add icons/drawable to data items which could be drawn in legend as on screen.
After click on Item maximize icon and show them near a graph.

![asdsa](https://cloud.githubusercontent.com/assets/1458891/16001858/dc1f57f8-3154-11e6-8ce0-c44ffe9caf80.png)

**Comment by PhilJay** [comment]
Currently not possible, maybe a feature I will consider for future updates.
