### ISSUE TITLE
Fill color between two line charts

### ISSUE THREAD

**Issue by vishal16babu** [PhilJay/MPAndroidChart#1865]
It would be great if LineDataSet have methods which would allow to fill color the region between two lines.
Thank you

**Comment by john1jan** [comment]
Yes..It would be a great feature .using this we can make jazzy graphs..

**Comment by TR4Android** [comment]
@vishal16babu @john1jan Please check out the [FillFormater](https://jitpack.io/com/github/PhilJay/MPAndroidChart/v2.2.5/javadoc/com/github/mikephil/charting/formatter/FillFormatter.html) interface. You can apply it to a dataset using `mLineDataSet.[setFillFormatter](https://jitpack.io/com/github/PhilJay/MPAndroidChart/v2.2.5/javadoc/com/github/mikephil/charting/data/LineDataSet.html#setFillFormatter(com.github.mikephil.charting.formatter.FillFormatter))(mFillFormatter)`

**Comment by vishal16babu** [comment]
@TR4Android I want to fill color between two lines, but I am not able to understand how to do it using FillFormatter. I have two LineDataSets. Any help is appreciated :)

**Comment by kvs-hcl** [comment]
There is a work around. Fill the first dataset with desired fill color and fill the second dataset with same color as the chart background. Also, set fill alpha with 255 for both datasets so that they are not transparent.

**Comment by ardmn** [comment]
@kvs-hcl , @TR4Android if lines are crossed how it shall look?

**Comment by PhilJay** [comment]
It does not work when lines are crossed. In all other cases it will work. I have coded an example.
https://github.com/PhilJay/MPAndroidChart/blob/remove_xindices/MPChartExample/src/com/xxmassdeveloper/mpchartexample/FilledLineActivity.java

**Comment by amitks2015** [comment]
Check for this solution.
https://github.com/PhilJay/MPAndroidChart/issues/3016

**Comment by nickyk2407** [comment]
Hi,

I want to join both the datasets with a line. Any suggestions?
