### ISSUE TITLE
Problem when use drawPath yAxis

### ISSUE THREAD

**Issue by vankhoa01** [PhilJay/MPAndroidChart#1870]
Hi,

I have issue when draw grid lines in YAxisRenderer bellow: 
https://www.dropbox.com/s/ulrpdz0hhgkz026/Image.png?dl=0

On some devices, grid line was draw with wrong position.
If you have any idea to fix issue, please share for me.

Thanks a lot

**Comment by ardmn** [comment]
Hi , can show YAxisRenderer source code ?

**Comment by PhilJay** [comment]
#1033
