### ISSUE TITLE
CombinedCharts issue on rendering grouped bardata

### ISSUE THREAD

**Issue by senthilmgs** [PhilJay/MPAndroidChart#1871]
I'm very much impressed with your charting API. I am good with integrating my data stuff with your API.  However am struck to generate grouped Bar Data set with combined charts. It's not rendering has expected way. When I try to execute has an Bar Chart view things are working fine. My requirement is to the show grouped bar data with Line Charts has an combined chart view . In this case the Bar Data set is not grouping properly, the bar data is positioned over the entire view on my  layout.

**Comment by PhilJay** [comment]
This issue is known. The new branch "remove_xindices" which will be released with v3.0.0 within the next few weeks already contains this feature.

**Comment by senthilmgs** [comment]
Hi PhilJay, Is there any updates on this version(v3.0.0). If not, please provide me the approximate time for this release.Because of this, I was troubled with my work schedule.

**Comment by senthilmgs** [comment]
Hi Phil,
     Please respond to the below link to get fixed this issue.

https://github.com/PhilJay/MPAndroidChart/issues/2040


On Wed, Jun 15, 2016 at 4:57 PM, Philipp Jahoda <notifications@github.com>
wrote:

> This issue is known. The new branch "remove_xindices" which will be
> released with v3.0.0 within the next few weeks already contains this
> feature.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PhilJay/MPAndroidChart/issues/1871#issuecomment-226160325>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABHp5eCaVx0zxegNeF78z5xDGRBhj4rAks5qL-GdgaJpZM4I2Brg>
> .
>



-- 
*Thanks & Regards*
*  Senthil MG,*
  +91-7736377987
