### ISSUE TITLE
background color change if ratio is less than 1% in PieChart

### ISSUE THREAD

**Issue by AmazingKevin** [PhilJay/MPAndroidChart#1877]
if the ratio is less 1% in PieChart,background color will change.but if we dont set exact num such code as `dataSet.setSliceSpace(0f);`.than this problem will not happen

**Comment by PhilJay** [comment]
This has been reported over 10 times already, and the issue has been resolved weeks ago.
A new release will be out soon.

**Comment by gwl026596** [comment]
don't resolve this problem，i have the same problem  when  valve is 0.1%
