### ISSUE TITLE
draw multiple line charts with different set of lebels

### ISSUE THREAD

**Issue by vishal16babu** [PhilJay/MPAndroidChart#1880]
It would be great if there are methods which allow users to draw two line charts together even if they have different set of xlabels.
(or)
If the combinedChart class allowed different set of xvalues for different dataSets
(or)
If more than one chart is allowed to be drawn on a sigle layout

The whole point is if I have two data sets like {(1,2) , (2,4) , (3,6)} ,{(1.5,2) , (2.5, 3) , (4.5 , 5)} which have different set of xvalues ({1,2,3} and {1.5,2.5,4.5}) how can I plot then together

**Comment by ardmn** [comment]
Hello. See, please, [com.xxmassdeveloper.mpchartexample.MultiLineChartActivity.java](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/MultiLineChartActivity.java) from samples. 
Main idea :
```java
ArrayList<String> xVals = new ArrayList<String>();
...
ArrayList<ILineDataSet> dataSets = new ArrayList<ILineDataSet>();
....
 dataSets.add(new LineDataSet(....));
 dataSets.add(new LineDataSet(....));
 dataSets.add(new LineDataSet(....));
...
```

 Important point.
`xVals.size() - must be equals or more than: MaxValueOf( dataSets.get(0).getEntryCount(), ... , dataSets.get(dataSets.size()-1).getEntryCount())`

```java
LineData data = new LineData(xVals, dataSets);
 mChart.setData(data);
```
