### ISSUE TITLE
Draw on each grid cell

### ISSUE THREAD

**Issue by luizmello** [PhilJay/MPAndroidChart#1881]
Hi, I'm starting with this lib and I didn't  find a way to draw a pattern in each grid cell, 
like this:
![driverlog](https://cloud.githubusercontent.com/assets/3990453/16116466/819b07f4-33a3-11e6-8c0a-075c6e24507e.png)

Could you please tell me if this is possible with this lib?
Thank you for this great lib

**Comment by PhilJay** [comment]
Thats a stepped linechart.

`lineDataSet.setMode(STEPPED)`

**Comment by luizmello** [comment]
Hi @PhilJay, thank you for your help.
I'm really need the float values on the xAxis, so I use your branch with this feature to make the chart,  this works well! 
![screenshot_20160618-213620](https://cloud.githubusercontent.com/assets/3990453/16174566/4620d856-359d-11e6-8fdb-87f8086e1125.png)

Thank you!
