### ISSUE TITLE
rendering order of filled line datasets

### ISSUE THREAD

**Issue by kvs-hcl** [PhilJay/MPAndroidChart#1882]
Hi,
I need to draw a chart with multiple filled line charts.
1. How do I fill area between two line chart/ series?
2. Can I control which dataset to be drawn first as this will affect the filling
3. How do I draw the limit line above the filled line charts?

Please clarify

**Comment by PhilJay** [comment]
1. Currently not possible
2. This is determined by the order you add the datasets
3. `axis. setDrawLimitLinesBehindData(false)`
