### ISSUE TITLE
In Barchart,how to show the MarkView in  some Bar when chart Create?

### ISSUE THREAD

**Issue by rehan91** [PhilJay/MPAndroidChart#1883]
Same as the title.....thanks!

**Comment by PhilJay** [comment]
`chart.highlightValues(...)`

https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart

**Comment by rehan91** [comment]
i use this method,but the markView did not show when barchart oncreate,how to fit it?
Highlight highlight1 = new Highlight(0,1);
chart.highlightValue(highlight1);
actually,i don''t understand the differencies between several constructor about ''highlight''?
