### ISSUE TITLE
BarChart with horizontal scrolling into ViewPager (bad scrolling)

### ISSUE THREAD

**Issue by ardmn** [PhilJay/MPAndroidChart#1885]
Hello. I have problem with BarChart horizontal scrolling. Scroling work so bad and I don understanf how fix it. Hello. I have problem with BarChart horizontal scrolling. Scrolling is work so bad and I do not understand how fix it. Can you give me some advice ? I need change my charts with viewpager effects.In my case: user scrolls to end of first chart, next when he scroll again I start showing next chart (like viewpager change page). I change first chart from PageAdapter of   com.xxmassdeveloper.mpchartexample.fragments.SimpleChartDemo class:

 ```java
private class PageAdapter extends FragmentPagerAdapter {

        public PageAdapter(FragmentManager fm) {
            super(fm); 
        }

        @Override
        public Fragment getItem(int pos) {  
            Fragment f = null;
            
            switch(pos) {
            case 0:
                 f =  TestMyBarChart.newInstance();
                break;

...

            case 5:
            ...
            break;
            }

            return f;
        }

        @Override
        public int getCount() {
            return 5;
        }       
    }
```

```java
package com.xxmassdeveloper.mpchartexample.fragments;

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import com.github.mikephil.charting.charts.BarChart;
import com.github.mikephil.charting.data.BarData;
import com.github.mikephil.charting.data.BarDataSet;
import com.github.mikephil.charting.data.BarEntry;
import com.github.mikephil.charting.interfaces.datasets.IBarDataSet;
import com.github.mikephil.charting.interfaces.datasets.IDataSet;
import com.github.mikephil.charting.utils.ColorTemplate;
import com.xxmassdeveloper.mpchartexample.R;
import java.util.ArrayList;

public class TestMyBarChart extends Fragment {

    public static TestMyBarChart newInstance() {
        return new TestMyBarChart ();
    }

    protected BarChart mChart;


    protected String[] mMonths = new String[] {
            "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"
    };

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.activity_barchart, container, false);

        mChart = (BarChart) v.findViewById(R.id.chart1);
        mChart.setDrawBarShadow(false);
        mChart.setDrawValueAboveBar(true);
        mChart.setDescription("");
        mChart.setMaxVisibleValueCount(60);
        mChart.setPinchZoom(false);
        mChart.setDrawGridBackground(true);
        mChart.setHighlightFullBarEnabled(false);
        mChart.setDoubleTapToZoomEnabled(false);

        XAxis xAxis = mChart.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setDrawGridLines(false);
        xAxis.setSpaceBetweenLabels(0);

        YAxis leftAxis = mChart.getAxisLeft();
        leftAxis.setDrawGridLines(false);
        leftAxis.setLabelCount(2, false);
        leftAxis.setPosition(YAxis.YAxisLabelPosition.OUTSIDE_CHART);
        leftAxis.setSpaceTop(15f);
        leftAxis.setAxisMinValue(0f);
        leftAxis.setDrawZeroLine(true);

        YAxis rightAxis = mChart.getAxisRight();
        rightAxis.setEnabled(false);
        rightAxis.setDrawGridLines(false);
        rightAxis.setLabelCount(8, false);
        rightAxis.setSpaceTop(15f);
        rightAxis.setAxisMinValue(0f); 

        Legend l = mChart.getLegend();
        l.setEnabled(false);
        l.setPosition(Legend.LegendPosition.BELOW_CHART_LEFT);
        l.setForm(Legend.LegendForm.SQUARE);
        l.setFormSize(9f);
        l.setTextSize(11f);
        l.setXEntrySpace(4f);

        setData(12, 30);

        mChart.setVisibleXRangeMaximum(6);

        for (IDataSet set : mChart.getData().getDataSets()) {
            set.setDrawValues(false);
        }

        return v;
    }

    private void setData(int count, float range) {

        ArrayList<String> xVals = new ArrayList<String>();
        for (int i = 0; i < count; i++) {
            xVals.add(mMonths[i % 12]);
        }

        ArrayList<BarEntry> yVals1 = new ArrayList<BarEntry>();

        for (int i = 0; i < count; i++) {
            float mult = (range + 1);
            float val = (float) (Math.random() * mult);
            yVals1.add(new BarEntry(val, i));
        }

        BarDataSet set1;

        if (mChart.getData() != null &&
                mChart.getData().getDataSetCount() > 0) {
            set1 = (BarDataSet)mChart.getData().getDataSetByIndex(0);

            set1.setYVals(yVals1);
            set1.getLabel();
            set1.setHighLightAlpha(204);
            mChart.getData().setXVals(xVals);
            mChart.getData().notifyDataChanged();
            mChart.notifyDataSetChanged();
        } else {
            set1 = new BarDataSet(yVals1, "DataSet");
            set1.setBarSpacePercent(35f);
            set1.setColors(ColorTemplate.MATERIAL_COLORS);
            set1.setHighLightAlpha(204);

            ArrayList<IBarDataSet> dataSets = new ArrayList<IBarDataSet>();
            dataSets.add(set1);

            BarData data = new BarData(xVals, dataSets);
            data.setValueTextSize(10f);

            mChart.setData(data);
        }
    }

}

```

activity_barchart.xml:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent" >

    <com.github.mikephil.charting.charts.BarChart
        android:id="@+id/chart1"
        android:layout_width="match_parent"
        android:layout_height="194dp"
        android:layout_above="@+id/seekBar1" />
    
  
</RelativeLayout>
```

**Comment by ardmn** [comment]
I override onInterceptTouchEvent(MotionEvent ev) method of ViewPager.  briefly : if I can scroll chart return false else return true

**Comment by interblitz** [comment]
I have the same issue. Could you please write some code, how one can check is chart able to scroll or not.

Thank you in advance

**Comment by rcrepaldi** [comment]
I have the same problem and it is not resolved by overwriting the onInterceptTouchEvent method. Would he have another way to solve it?

**Comment by interblitz** [comment]
Well, to resolve the problem follow this and look for new code and modified code comments (//-- is end of modification):

1. Modify chart.java
public abstract class Chart<T extends ChartData<? extends IDataSet<? extends Entry>>> extends
        ViewGroup
        implements ChartInterface {
//**new code**
public interface ChartScrollListener {
		public void disableScroll(ViewParent view);
		public void enableScroll(ViewParent view);
	}
private ChartScrollListener mChartScrollListener;
//--
...
//**new code**
public void setChartScrollListener(ChartScrollListener chartScrollListener){
    	mChartScrollListener = chartScrollListener;
}
//--
public void disableScroll() {
        ViewParent parent = getParent();
        //**modified code**
//        if (parent != null)
//            parent.requestDisallowInterceptTouchEvent(true);
        while(parent != null){
        	parent.requestDisallowInterceptTouchEvent(true);
        	if(mChartScrollListener != null){
        		mChartScrollListener.disableScroll(parent);
        	}
        	parent = parent.getParent();
        }
//--        
    }
public void enableScroll() {
        ViewParent parent = getParent();
        //**modified code**
//        if (parent != null)
//            parent.requestDisallowInterceptTouchEvent(false);
        while(parent != null){
        	parent.requestDisallowInterceptTouchEvent(false);
        	if(mChartScrollListener != null){
        		mChartScrollListener.enableScroll(parent);
        	}
        	parent = parent.getParent();
        }
//--        
    }

2. Modify BarLineChartTouchListener.java
    @SuppressLint("ClickableViewAccessibility")
    @Override
    public boolean onTouch(View v, MotionEvent event) {
        if (mVelocityTracker == null) {
            mVelocityTracker = VelocityTracker.obtain();
        }
        mVelocityTracker.addMovement(event);
        if (event.getActionMasked() == MotionEvent.ACTION_CANCEL) {
            if (mVelocityTracker != null) {
                mVelocityTracker.recycle();
                mVelocityTracker = null;
            }
        }
        if (mTouchMode == NONE) {
            mGestureDetector.onTouchEvent(event);
        }
        if (!mChart.isDragEnabled() && (!mChart.isScaleXEnabled() && !mChart.isScaleYEnabled()))
            return true;
        // Handle touch events here...
        switch (event.getAction() & MotionEvent.ACTION_MASK) {
            case MotionEvent.ACTION_DOWN:
                startAction(event);
                stopDeceleration();
                saveTouchStart(event);
                break;
            case MotionEvent.ACTION_POINTER_DOWN:
                if (event.getPointerCount() >= 2) {
                    mChart.disableScroll();
                    saveTouchStart(event);
                    // get the distance between the pointers on the x-axis
                    mSavedXDist = getXDist(event);
                    // get the distance between the pointers on the y-axis
                    mSavedYDist = getYDist(event);
                    // get the total distance between the pointers
                    mSavedDist = spacing(event);
                    if (mSavedDist > 10f) {
                        if (mChart.isPinchZoomEnabled()) {
                            mTouchMode = PINCH_ZOOM;
                        } else {
                            if (mChart.isScaleXEnabled() != mChart.isScaleYEnabled()) {
                                mTouchMode = mChart.isScaleXEnabled() ? X_ZOOM : Y_ZOOM;
                            } else {
                                mTouchMode = mSavedXDist > mSavedYDist ? X_ZOOM : Y_ZOOM;
                            }
                        }
                    }
                    // determine the touch-pointer center
                    midPoint(mTouchPointCenter, event);
                }
                break;
            case MotionEvent.ACTION_MOVE:
            	//**new code**
            	mChart.disableScroll();
            	//--       	
                if (mTouchMode == DRAG) {
                	//**modified code**
                	//mChart.disableScroll();
                	//--
                    performDrag(event);
                } else if (mTouchMode == X_ZOOM || mTouchMode == Y_ZOOM || mTouchMode == PINCH_ZOOM) {
                	//**modified code**
                	//mChart.disableScroll();
                	//--
                    if (mChart.isScaleXEnabled() || mChart.isScaleYEnabled())
                        performZoom(event);
                } else if (mTouchMode == NONE
                        && Math.abs(distance(event.getX(), mTouchStartPoint.x, event.getY(),
                        mTouchStartPoint.y)) > mDragTriggerDist) {
                    if (mChart.hasNoDragOffset()) {
                        if (!mChart.isFullyZoomedOut() && mChart.isDragEnabled()) {
                            mTouchMode = DRAG;
                        } else {
                            mLastGesture = ChartGesture.DRAG;
                            if (mChart.isHighlightPerDragEnabled())
                                performHighlightDrag(event);
                        }
                    } else if (mChart.isDragEnabled()) {
                        mLastGesture = ChartGesture.DRAG;
                        mTouchMode = DRAG;
                    }
                }
                break;
            case MotionEvent.ACTION_UP:
                final VelocityTracker velocityTracker = mVelocityTracker;
                final int pointerId = event.getPointerId(0);
                velocityTracker.computeCurrentVelocity(1000, Utils.getMaximumFlingVelocity());
                final float velocityY = velocityTracker.getYVelocity(pointerId);
                final float velocityX = velocityTracker.getXVelocity(pointerId);
                if (Math.abs(velocityX) > Utils.getMinimumFlingVelocity() ||
                        Math.abs(velocityY) > Utils.getMinimumFlingVelocity()) {
                    if (mTouchMode == DRAG && mChart.isDragDecelerationEnabled()) {
                        stopDeceleration();
                        mDecelerationLastTime = AnimationUtils.currentAnimationTimeMillis();
                        mDecelerationCurrentPoint.x = event.getX();
                        mDecelerationCurrentPoint.y = event.getY();
                        mDecelerationVelocity.x = velocityX;
                        mDecelerationVelocity.y = velocityY;
                        Utils.postInvalidateOnAnimation(mChart); // This causes computeScroll to fire, recommended for this by
                        // Google
                    }
                }
                if (mTouchMode == X_ZOOM ||
                        mTouchMode == Y_ZOOM ||
                        mTouchMode == PINCH_ZOOM ||
                        mTouchMode == POST_ZOOM) {
                    // Range might have changed, which means that Y-axis labels
                    // could have changed in size, affecting Y-axis size.
                    // So we need to recalculate offsets.
                    mChart.calculateOffsets();
                    mChart.postInvalidate();
                }
                mTouchMode = NONE;
                mChart.enableScroll();
                if (mVelocityTracker != null) {
                    mVelocityTracker.recycle();
                    mVelocityTracker = null;
                }
                endAction(event);
                break;
            case MotionEvent.ACTION_POINTER_UP:
                Utils.velocityTrackerPointerUpCleanUpIfNecessary(event, mVelocityTracker);
                mTouchMode = POST_ZOOM;
                break;
            case MotionEvent.ACTION_CANCEL:
                mTouchMode = NONE;
                endAction(event);
                break;
        }
        // perform the transformation, update the chart
        mMatrix = mChart.getViewPortHandler().refresh(mMatrix, mChart, true);
        return true; // indicate event was handled
    }
3. Use setChartScrollListener method to manual disable and enable scroll, for example:
		final BarChart chart = (BarChart) super.createChartView(contentView);
		chart.setChartScrollListener(new ChartScrollListener() {
			@Override
			public void disableScroll(ViewParent view) {
				if(SwipeRefreshLayout.class.isAssignableFrom(view.getClass())){
					((SwipeRefreshLayout)view).setEnabled(false);
				}
			}
			@Override
			public void enableScroll(ViewParent view) {
				if(SwipeRefreshLayout.class.isAssignableFrom(view.getClass())){
					((SwipeRefreshLayout)view).setEnabled(true);
				}
			}
		});

Hope this helps

**Comment by iad24** [comment]
@ardmn Hey man. were u able to solve this issue? Or anyone? aside from @interblitz 's answer?
Thanks

**Comment by Danil4ever** [comment]
parent.requestDisallowInterceptTouchEvent(false);
and 
parent.requestDisallowInterceptTouchEvent(true);

solved problem.

![image](https://user-images.githubusercontent.com/37780817/146878009-8586f98d-9d96-4f59-a0a2-4302c62ae8bb.png)
