### ISSUE TITLE
Large number 

### ISSUE THREAD

**Issue by fadaeian** [PhilJay/MPAndroidChart#1888]
Hello 

Very Large number like 998989989898 in barEntry have bug because of using float instead of double 

Is there an update for this bug ?

Thanks

**Comment by PhilJay** [comment]
That's not a bug, that's normal behaviour of floating point numbers. Unfortunately canvas drawing and matrix multiplications are optimized for float numbers in Android, so I will not change to double.

I suggest you take a look at the [LargeValueFormatter](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/com/github/mikephil/charting/formatter/LargeValueFormatter.java)

**Comment by skh1993** [comment]
So can only show 7 digits is not？
