### ISSUE TITLE
To disable data in axis-base

### ISSUE THREAD

**Issue by sunilpk** [PhilJay/MPAndroidChart#1889]
How to disable data in axis-base,

var avgData={
xValues:[],
yValues:[
{
data:[],
label:"K",
config:{
drawCircles:false,
drawLabels: false,
color:'#FF0080'
}
}]
}
I tired 'drawLabels: false' but it is not working.
I also tired 'AxisBase={{ drawLabels: false }}' but not working.
Thanks

**Comment by PhilJay** [comment]
I dont know what you mean by "disable data"

**Comment by PhilJay** [comment]
`dataSet.setDrawValues(false)`
