### ISSUE TITLE
How to disable data in axis-base

### ISSUE THREAD

**Issue by jainkjohnson** [PhilJay/MPAndroidChart#1890]
How to disable data in axis-base,

var avgData={
xValues:[],
yValues:[
{
data:[],
label:"K",
config:{
drawCircles:false,
drawLabels: false,
color:'#FF0080'
}
}]
}
I tired 'drawLabels: false' but it is not working.
I also tired 'AxisBase={{ drawLabels: false }}' but not working.
Thanks

**Comment by PhilJay** [comment]
#1889

**Comment by jainkjohnson** [comment]
![send](https://cloud.githubusercontent.com/assets/10278715/16186486/69987716-36e8-11e6-9014-7c9ef8d45d31.png)

Data means the black circled portion in the image.
