### ISSUE TITLE
To hide the label in graph.

### ISSUE THREAD

**Issue by jainkjohnson** [PhilJay/MPAndroidChart#1891]
![send](https://cloud.githubusercontent.com/assets/10278715/16188841/2a0badae-36f5-11e6-915a-c986c6403d51.png)

To hide the label that is marked in black circle.

I tried this but not working,
var avgData={
xValues:[],
yValues:[
{
data:[],
label:"K",
config:{
drawCircles:false,
drawLabels: false,
color:'#FF0080'
}
}]
}

**Comment by PhilJay** [comment]
STOP CREATING DUPLICATE ISSUES

#1889

**Comment by jainkjohnson** [comment]
Is there any way to hide label.

**Comment by PhilJay** [comment]
Yes, I already answered here: #1889
