### ISSUE TITLE
Horizontal Bar Chart, draw X-Axis labels above each bar?

### ISSUE THREAD

**Issue by ZkHaider** [PhilJay/MPAndroidChart#1893]
Is it possible to draw the x-axis labels above each bar and have a greater amount of spacing between each bar?

**Comment by PhilJay** [comment]
Spacing between bars can be controlled via `barDataSet.setBarSpace(...)`. It's currently not possible to display the x-axis labels above the bars, but you can draw them inside the chart via the `xAxis.setPosition(...)` method and set an y-offset via `xAxis.setYOffset(...)`.

**Comment by ZkHaider** [comment]
Your solution does not work. I tried the following:

    // Configure x axis - will draw name values to the right
        xAxis.setEnabled(true);
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM_INSIDE);
        xAxis.setYOffset(30.0f);
        xAxis.setDrawLabels(true);
        xAxis.setDrawAxisLine(false);
        xAxis.setDrawGridLines(false);
        xAxis.setDrawLimitLinesBehindData(false);
        xAxis.setTextSize(10.0f);
        xAxis.setTextColor(Color.WHITE);

And the X-Values still show up inside the chart without a Y-offset

**Comment by ZkHaider** [comment]
Should I make a PR to allow x-axis labels to be displayed above the horizontal bar chart?

**Comment by ynagarjuna1995** [comment]
barDataSet.setBarSpace(...) is not working in current version.

**Comment by vetkolisanket** [comment]
@ZkHaider  instead of xAxis.setYOffset(30.0f); try xAxis.setXOffset(30.0f); should work

**Comment by oduysmara** [comment]
xAxis.setYOffset is not working , please help me  in this point !! xAxis.setXOffset is  wotking without  any problem

**Comment by slavaantonenko** [comment]
@PhilJay Hi, are you planning to add such feature in the near future?

**Comment by jollyjoker992** [comment]
@PhilJay It's super common use case. Could you help to support? 
Thank you!
