### ISSUE TITLE
How to use this method in StackedBarChart to show markView once chart created?

### ISSUE THREAD

**Issue by rehan91** [PhilJay/MPAndroidChart#1894]
/**
     * Constructor, only used for stacked-barchart.
     *
     * @param x the index of the highlighted value on the x-axis
     * @param dataSetIndex the index of the DataSet the highlighted value belongs to
     */
    public Highlight(int x, int dataSetIndex) {
        this(x, Float.NaN, 0, dataSetIndex, -1);
    }

However,I don't really understand how to use this method,and the pramas meaning.Especially,dataSetIndex,but i hold onlyone dataset,it's mean that the index of that will be 0?

**Comment by PhilJay** [comment]
x -> the index on your x-axis that should be highlighted. If you have three bars in a barchart for example, and you want to highlight the first one, you will provide 0 here. If you want to highlight the middle one, provide 1, and so on...

dataSetIndex -> this tells the chart which dataSet the highlighted entry belongs to. As In a linechart for example multiple entries can be at the same x-index, it is important to know which dataset you want to highlight. If you have only one dataset, provide 0.

**Comment by rehan91** [comment]
thanks for your answer!but i use this method →_→: barDataSet.setStackLabels(new String[]{"base", "plus"}),so in this case,how to calculate the index of the datasetindex?when i use this method ☞:  Highlight highlight1 = new Highlight(0,0);
chart.highlightValue(highlight1);
it will encounter a runtime exception:java.lang.NullPointerException
here is the details about exception:
 at com.github.mikephil.charting.charts.BarLineChartBase.getMarkerPosition(BarLineChartBase.java:593)
                                                                                   at com.github.mikephil.charting.charts.Chart.drawMarkers(Chart.java:698)
                                                                                   at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:286)

**Comment by PhilJay** [comment]
To be honest I think the way highlighting is handled right now is not very good. v3.0.0 will be released in a couple of weeks which will allow much easier and clearer highlighting values (programmatically).
