### ISSUE TITLE
Canvas.clipPath(...) crash when too many filled Entries

### ISSUE THREAD

**Issue by chintandesai49** [PhilJay/MPAndroidChart#1895]
In Line chart when i increase first seekBar and when it reaches to approx value 350 app restarts it self.
I have attached zip file containing video of problem.
I tested this thing on Nexus 6. But not able to reproduc on nexus 4.
[MPAndroidChart Problem.zip](https://github.com/PhilJay/MPAndroidChart/files/324989/MPAndroidChart.Problem.zip)

**Comment by PhilJay** [comment]
Thank you for the report. What kind of device are you using?

Could you tell me if the crash still occurs if you disable "filled" (the red gradient) option in the example you have shown me.

**Comment by chintandesai49** [comment]
No crash at all just simple restart of app as you can see in device. I'm using nexus 6 and Nexus 4. 
problem occur in only Nexus 6 but not reproducible on Nexus 4.

**Comment by PhilJay** [comment]
Can you please test again and see if the issue also occurs if "filled" is disabled?
The restart of the app is an indicator for a crash.

**Comment by chintandesai49** [comment]
No, when toggle filled marked disable app does not restart and worked as expected on Nexus 6 and Nexus 4.

**Comment by PhilJay** [comment]
Alright, this looks very much like a memory issue, most likely related to `canvas.clipPath(...)` method which is used for filling. If you disable hardware acceleration, the crash will stop.

**Comment by tonypatino-monoclesociety** [comment]
@PhilJay I have a proposed fix for this bug currently in my local remove_xindeces branch.  It involves generating smaller paths iteratively until all paths are drawn.  Would you like to incorporate this after v3.0.0 is out?

**Comment by tonypatino-monoclesociety** [comment]
**Results - Stress testing Activity 1 with 1500 items, full color fill.**
![device-2016-06-30-174125](https://cloud.githubusercontent.com/assets/13628883/16508655/f009a960-3ee9-11e6-887e-2aa835893d92.png)



**Results - Stress testing Activity 2 with 1500 items and full color fill.**
![device-2016-06-30-174419](https://cloud.githubusercontent.com/assets/13628883/16508674/332bbfa8-3eea-11e6-8270-9ba52684e0b5.png)

**Comment by PhilJay** [comment]
Yes, I would incorporate it!

**Comment by tonypatino-monoclesociety** [comment]
Cool, I'll incorporate this into the performance-related pull request.
