### ISSUE TITLE
In StackedBarchart,how to show the MarkView once the chart Create without touch?

### ISSUE THREAD

**Issue by rehan91** [PhilJay/MPAndroidChart#1896]
thanks for your answer! i use this method →_→: barDataSet.setStackLabels(new String[]{"base", "plus"}),so in this case,in one bar,it hold two parts,so,how to calculate the index of the datasetindex?
when i use this method ☞:
Highlight highlight1 = new Highlight(0,0);//i have onlyone dataset
chart.highlightValue(highlight1);
it will encounter a runtime exception:java.lang.NullPointerException
here is the details about exception:
at com.github.mikephil.charting.charts.BarLineChartBase.getMarkerPosition(BarLineChartBase.java:593)
at com.github.mikephil.charting.charts.Chart.drawMarkers(Chart.java:698)
at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:286)

**Comment by PhilJay** [comment]
To be honest I think the way highlighting is handled right now is not very good. v3.0.0 will be released in a couple of weeks which will allow much easier and clearer highlighting values (programmatically).

Please stay tuned until it is out!

**Comment by rehan91** [comment]
e....,no wonder i cannot find responding method to realized this function.But,in LineChart case,we can show MarkView when LineChart oncreated without touch....Why in BarChart cannot work?
