### ISSUE TITLE
Pinch gesture to highlight an interval on LineChart

### ISSUE THREAD

**Issue by monxalo** [PhilJay/MPAndroidChart#1898]
First of all, awesome library!

I've been working on a feature that mimics the Google Now Stocks interaction with the chart.
It basically it uses two touch pointers to highlight an interval of a LineChart

Here's the current progress:

![linechart-doubletap](https://dl.dropboxusercontent.com/u/5473207/eco-graphic.gif)

It works okay but it's not very well implemented due to lack of understanding the architecture of this library's framework.

Can anyone give me some guidance of how can this be properly implemented?
You can check my implementation [here](https://github.com/PhilJay/MPAndroidChart/compare/master...monxalo:monxalo/double-highlight).

If more people want this feature, i can later create a PR.

**Comment by zorroblue** [comment]
@monxalo It is a really good feature. Thanks for sharing it! :)
