### ISSUE TITLE
Draw whole numbers only on Y-axis and draw 0 value

### ISSUE THREAD

**Issue by rsarker** [PhilJay/MPAndroidChart#1900]
First of all thanks a lot for this wonderful library.

So when we create Y-axis and let's say set it's label count to be 3 or so, Y-axis draws some random numbers (like 4.38, 7,79, 10.29). Is there any way I can make it draw  evenly (like 4.5, 7.5, 10.5).
Even if the interval is not even (in this case 3), how can I draw only values like 1 or 1.25 or 1.5 or 1.75 and so on.

Other thing is, I can draw the zero line by making the drawZeroLineEnabled to be true, but how can I insert that into the Y values so that renderer draws it by itself and I don't have to draw 0 label on the y-axis manually. Suggest if there are any possible ways.

Thanks in advance.

**Comment by PhilJay** [comment]
The YAxis will always draw evenly unless you specify a label count and a custom axis range that do not allow even numbers.

If you set the range to be 0-100 and a label count of 4, even numbers are not possible since this would result in labels 0; 0.33; 0.66; 1
