### ISSUE TITLE
How can i cancel to show markview when i touch the bar?

### ISSUE THREAD

**Issue by rehan91** [PhilJay/MPAndroidChart#1902]
Yeah,my situation is a bit of thorny...i want to show my markview when the Barchart created,but i dont't want to show  it when i touch the bar later,because i want to show it 's value in a textView...maybe there are some method can be used in method"onValueSelected()",when i touch the bar,i can cancel to show the markView in this listener method,On the contrary,i will show it's value in a textView ,so,how can i solve this problem?thx very much!

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart

chart.setHighlightPerTapEnabled(false)

chart.highlightValue(...)
