### ISSUE TITLE
For two entries Bar chart is Showing huge difference in height.

### ISSUE THREAD

**Issue by ujjainturvo** [PhilJay/MPAndroidChart#1904]
ArrayList<BarEntry> entries = new ArrayList<>();

        float i = 39f;
        float j = 47f;
        float k = 6f;

        entries.add(new BarEntry(i, 0));
        entries.add(new BarEntry(j, 1));

        BarDataSet dataset = new BarDataSet(entries, "# of Calls");
        dataset.setDrawValues(false);
     //   dataset.setBarSpacePercent(-10);
        dataset.setValueTextColor(Color.WHITE);
      //  dataset.setColors(new int[]{mContext.getResources().getColor(R.color.red), mContext.getResources().getColor(R.color.green)});
        // creating labels
        ArrayList<String> labels = new ArrayList<>();

        labels.add("a/r");
        labels.add("a/p");

        BarData data = new BarData(labels, dataset);
        barChart.setData(data); // set the data and list of lables into chart[
![device-2016-06-23-162013](https://cloud.githubusercontent.com/assets/18459968/16304285/5336ecaa-3972-11e6-9eca-fdf98ca262ef.png)
](url)

**Comment by PhilJay** [comment]
thats because your axis does not start at zero

**Comment by ujjainturvo** [comment]
So how should i handle it?  Because with more that 3 or more data bar chart is drawn uniformly.

**Comment by PhilJay** [comment]
No it is not, it just appears that way because the scale is larger.
`yAxis.setAxisMinValue(0f)`
