### ISSUE TITLE
Why can't i get the y-value when i touch the bar in this method in BarChart?

### ISSUE THREAD

**Issue by rehan91** [PhilJay/MPAndroidChart#1905]
@Override
    public void onValueSelected(Entry e, int dataSetIndex, Highlight h) {
        float val = e.getVal();
        Log.v("1","bar was touched:"+Float.toString(val));
    }

and i cannot see log in my logcat ,how can i get the bar value when i touch it?

**Comment by PhilJay** [comment]
float val = e.getVal(); returns the bar value.
