### ISSUE TITLE
The chart labels do not align with bar in Combinedchart

### ISSUE THREAD

**Issue by ajaybarvey** [PhilJay/MPAndroidChart#1906]
The chart labels do not align with bars when you change the space between bar chart in 
The landscape view alignment is better than portrait view but I want them to be perfectly aligned in both views
These are my setting for Bar Space -
   [    BarDataSet barDataSet = new BarDataSet(group1, "X");
        barDataSet.setColors(ColorTemplate.COLORFUL_COLORS);
        barDataSet.setBarSpacePercent(75f);
] Could you please guide me?
Many thanks
Ajay

(url)
![mpchart](https://cloud.githubusercontent.com/assets/16981946/16334713/2f248d82-3a20-11e6-912c-10c9265f46ca.png) 

![mpchart2](https://cloud.githubusercontent.com/assets/16981946/16335520/bfe5b7c0-3a24-11e6-81f1-f47613d9f920.png)

**Comment by BalalakshmiSadhasivam** [comment]
I think the labels are center aligned with the corresponding bars. If the label length is large, it seems like a misalignment ( say 7th  and 8th label in portrait view).

**Comment by PhilJay** [comment]
`chart. getRendererXAxis().getPaintAxisLabels().setTextAlign(Align.LEFT)`
