### ISSUE TITLE
Pie chart : display percent in legend

### ISSUE THREAD

**Issue by csbenz** [PhilJay/MPAndroidChart#1907]
I've searched through the Wiki and can't find how to do this; don't know if it's possible.
In my Pie Chart I would like to show the percent of each color, instead of the xValue for that color.

Thanks in advance!

**Comment by PhilJay** [comment]
I am not sure what you mean. Could you post a screenshot of what you want?

**Comment by csbenz** [comment]
HI, this issue isn't resolved at all, please keep it open while the problem hasn't found a solution.
The legend of a pie chart displays the xValues. I would like to know if it's possible to show the percentage of the corresponding yValue instead.
Otherwise I'll calculate the yValue percent value and add them as the xValues, which seems redundant.
Thanks in advance.

**Comment by PhilJay** [comment]
Currently that's not possible, so the best approach would indeed be to calculate the value and add them as x-value.
