### ISSUE TITLE
how to resolve this porblem

### ISSUE THREAD

**Issue by maoaixianyu** [PhilJay/MPAndroidChart#1909]
how to resolve this problem,I am very warry!
![qq20160625-0](https://cloud.githubusercontent.com/assets/17868022/16355323/ee3cb97c-3ae5-11e6-95fe-548f073c0929.png)

**Comment by PhilJay** [comment]
Decrease the text size and / or increase the chart size.
Use ValueFormatter to prevent too small values from being drawn.

**Comment by maoaixianyu** [comment]
Decrease the text size for PieData?
