### ISSUE TITLE
how to use ValueFormatter to prevent too small values from being drawn to resolve this porblem

### ISSUE THREAD

**Issue by maoaixianyu** [PhilJay/MPAndroidChart#1910]
how to  use ValueFormatter to prevent too small values from being drawn.
![qq20160625-0](https://cloud.githubusercontent.com/assets/17868022/16355529/bd15c360-3aeb-11e6-85de-b887a0d22672.png)

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface

if(value < smallestValueToDraw) {
   return "";
}
