### ISSUE TITLE
How can we limit grid lines upto the line drawn?

### ISSUE THREAD

**Issue by anshchauhan** [PhilJay/MPAndroidChart#1914]
I've couple of queries which I've been trying since many days now. I tried asking on stackoverflow but no luck. Please guide me how to achieve the following. 
![achieve](https://cloud.githubusercontent.com/assets/14310139/16361056/f838c5c4-3b9e-11e6-9d38-d0654d8d9ce4.jpg)

I've reached here:
![capture](https://cloud.githubusercontent.com/assets/14310139/16361058/0c7e2678-3b9f-11e6-9074-88e58371904c.PNG)

But now I can't figure out how to:
1. Drop line shadow.
2. Limit grid lines up to the line drawn.
3. Add dot at the end of grid line.

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
