### ISSUE TITLE
Chart errors - the error depends on the version of OS

### ISSUE THREAD

**Issue by liouria** [PhilJay/MPAndroidChart#1915]
There is a bug when plotting. The error depends on the version of OS. Two smartphones are used when testing the software (Lenovo Z2 and Philips V387). Lenovo Z2 - **Android 5.0.2**. Philips V387 - OS **Android 4.4.2**. Error occurs when using a smartphone Philips. The errors shown in the screenshots.  I really need help!

![chart errors 201-06-26](https://cloud.githubusercontent.com/assets/10761512/16361496/06da9408-3b9b-11e6-89ff-d5558d22b378.png)

**Comment by PhilJay** [comment]
I suggest you check the data the is fed to the chart. It looks like the chart is drawing correctly, but the data you are providing for the chart is simply corrupted. Have you checked (debugged) the actual values you provided for the chart?

**Comment by liouria** [comment]
You are right. It's my fault. Graphics library is working correctly!
My data are computed with an error. But! 
1) !!! Calculation errors do **not exist** when **using** the **debug** mode (Android Studio 2.1.2) !!!
2) The calculation errors are available in **non-debug** mode !!!
3) I'm using ViewPager to show graphics. There is an interesting feature.Error does not exist if the plot is shown for the first time. But when the graph is redrawn again (after you change pages in ViewPager), an error occurs.
4) There is an error in my calculations if I use a Philips smartphone (Android **4.4.2**), but there is no error if I use the Lenovo smartphone (Android **5.0.2**).

SOLUTION (**VERY STRANGE**).

I added the code line:
                                          **String ss = "appYValue =" + appYValue;** 
**Attention!!!** 
The variable "**ss**" **not used** anywhere else!!! It turned out that this unnecessary line helps getting the correct data. Most likely, this error is related to a compiler.
**Thanks for the quick answer to my question!**
