### ISSUE TITLE
Gantt Chart Creation

### ISSUE THREAD

**Issue by mishra-m** [PhilJay/MPAndroidChart#1917]
How can i create gantt chart with this library

**Comment by PhilJay** [comment]
gantt charts are not supported

**Comment by tjiang11** [comment]
+1 for gantt chart

**Comment by sebastianMof** [comment]
+2 for gantt charts

**Comment by protectedMan** [comment]
+10086 for gantt charts

**Comment by liujia95** [comment]
+9999999 for gantt charts
