### ISSUE TITLE
Dynamic chart not working correctly

### ISSUE THREAD

**Issue by elpeppe** [PhilJay/MPAndroidChart#1919]
Hi, I'm facing an issue in your library adapted for Xamarin. More precisely, I'm developing an app which uses dynamic graphs, but, strangely enough, sometimes the leftmost value disappears(meaning that its label and its circle are not shown). Also, every now and then the label gets shifted a little bit(4, 7, 11, 12 in this case). Would you happen to know how to solve these problems? Thanks in advance.
![graph issue](https://cloud.githubusercontent.com/assets/20165272/16377810/7a7b5f0a-3c68-11e6-92c8-eaf825eb7b79.png)

**Comment by PhilJay** [comment]
Not really, I have nothing to do with the Xamarin port so I can't really say anything.

**Comment by elpeppe** [comment]
Actually, the person who ported it redirected me here saying that the issue is related to the library itself.

**Comment by elpeppe** [comment]
It's not a port, it is a binding, meaning that it uses your native Java code, by calling it.
