### ISSUE TITLE
Stacked area chart with filling of colors between line charts

### ISSUE THREAD

**Issue by naman14** [PhilJay/MPAndroidChart#1922]
Hi, I wanted to ask if there is any way to fill the chart with a particular color between different line data sets. 
I want to achieve chart like this
![68747470733a2f2f7261772e6769746875622e636f6d2f6e756d65747269636c61627a2f6e756d416e64726f69644368617274732f6d61737465722f73637265656e73686f74732f737461636b65642d617265612e706e67](https://cloud.githubusercontent.com/assets/8599099/16413299/cc0ac4e6-3d4e-11e6-9455-955a2dcf43d6.png)

Using FillFormatter doesn't seem to work in this case as FillFormatter expects a definite Y value. I want to fill different colors between each line data set. 
What I am getting is that all line data set fills color to Y=0 resulting in overlapping of colors at the bottom.

**Comment by PhilJay** [comment]
Just set the fill-alpha value to maximum (255) than the overlapping will not be noticed. Also make sure the order of your data is correct.

`lineDataSet.setFillAlpha(255)`

**Comment by FrantisekGazo** [comment]
@PhilJay Would it be hard to implement support for StackedArea chart? 
I'm asking because I need some transparency, so I cannot set alpha to 255. I would be willing to implement it. I'm just curious if there are some obstacles.

**Comment by FrantisekGazo** [comment]
@PhilJay Or another way: would it be possible to draw line grid above the lines/areas?

**Comment by joaosardinha** [comment]
+1
