### ISSUE TITLE
Hint for UnbindDrawables in Chart

### ISSUE THREAD

**Issue by Noires** [PhilJay/MPAndroidChart#1923]
Iam not sure if this issue is just related to Xamarin, but i had to adjust the Chart-Class to let me manually call the UnbindDrawables-Method, else it would create a huge memory leak for me.

So basically each time if i would rotate my fragment or just close and reopen it, it would allocate around 5MB for the drawables, which wouldnt get freed by the garbage collector. 

So maybe this is just related to Xamarin, but it could be that onDetachedFromWindow() doesnt get called? Ofc i setUnbindEnabled(true).

Maybe worth to take a closer look at it.

Greetings Noires

**Comment by almic** [comment]
Sorry about this issue collecting dust for so long. I'm closing due to it being so old, but if this issue still exists, please **open a new issue** about it. Thanks 👍
