### ISSUE TITLE
Dynamic chart not working correctly

### ISSUE THREAD

**Issue by elpeppe** [PhilJay/MPAndroidChart#1926]
Hi, I'm facing an issue in your library in Xamarin(**it is used through binding, meaning that it uses your java code!**). More precisely, I'm developing an app which uses dynamic graphs, but, strangely enough, sometimes the leftmost value disappears(meaning that its label and its circle are not shown). Also, every now and then the label gets shifted a little bit(4, 7, 11, 12 in this case). Would you happen to know how to solve these problems? Thanks in advance.
![graph issue](https://cloud.githubusercontent.com/assets/20165272/16377810/7a7b5f0a-3c68-11e6-92c8-eaf825eb7b79.png)

**Comment by PhilJay** [comment]
#1919 

https://github.com/PhilJay/MPAndroidChart#questions--issues
https://github.com/PhilJay/MPAndroidChart/wiki/How-not-to-contribute
