### ISSUE TITLE
In Barchart,how to highlight the bar,but not show the markView?

### ISSUE THREAD

**Issue by rehan91** [PhilJay/MPAndroidChart#1927]
when i touch the bar,the bar's color will be sharpen(yeah,highlight...),but i don't want to show the markView at the same time...however,i use this method but i cannot touch the bar anymore:
`mChart.setHighlightPerTapEnabled(false);`

**Comment by PhilJay** [comment]
If you dont want the markerview to show, then don't set a markerview for your chart.

**Comment by rehan91** [comment]
However,i just want  to show the markView once the BarChart onCreat ,as a default value to show with user,but i don't want it show anymore when i touch the bar again...because i put it's value in a textview...
