### ISSUE TITLE
LineChart.calcMinMax() not including LimitLines'value.

### ISSUE THREAD

**Issue by colin-phang** [PhilJay/MPAndroidChart#1929]
Line Chart calcMinMax() is not including LimitLines'value.  In such a situation, which **LimitLine Value** is larger/smaller than the **mLeftAxisMax/mLeftAxisMin** ,can cause the **LimitLine** out of **Chart's content Rect**。 As shown below：
![image](https://cloud.githubusercontent.com/assets/13748497/16440274/de932f64-3df2-11e6-912f-bf2077c89ea0.png)

**Comment by PhilJay** [comment]
That's intended behaviour as the value of the limit line should not influence the calculation of minimum and maximum value of the data.

If you want to prevent the limitline from being cut off, set a custom axis range.
