### ISSUE TITLE
Pie chart radius change

### ISSUE THREAD

**Issue by mishra-m** [PhilJay/MPAndroidChart#1931]
I am not able to reduce pie chart radius. Only hole radius and transparent circle radius can be altered.

**Comment by PhilJay** [comment]
That's because the radius of the chart is determined by the size of the chart-view. So of you want to change the radius, change the size of the view.

**Comment by Shanmugapriyan22** [comment]
@PhilJay Hi i want same size of the chart view but i want to reduce chart radius thickness.

**Comment by pjain168** [comment]
@Shanmugapriyan22 You can use `pieChart.setHoleRadius(35);`, So the more you set hole radius the chart will become thinner.

**Comment by sivakumarswaminthan** [comment]
@PhilJay  Can the entries inside the pie chart be swapped?

**Comment by hotstu** [comment]
the right solution is   `dataSet.setSelectionShift(10);`, that reduce the radius by 10

**Comment by AbhilashGuptaOM** [comment]
> @Shanmugapriyan22 You can use `pieChart.setHoleRadius(35);`, So the more you set hole radius the chart will become thinner.

but if we decrease the hole radius then the color becomes uneven, I want to achieve a thicker slice pie.
![WhatsApp Image 2020-12-07 at 6 11 47 PM](https://user-images.githubusercontent.com/75599626/101352192-c4fcbb00-38b7-11eb-93c4-ee40da9815af.jpeg)
