### ISSUE TITLE
adding MPAndroidChart as a Library in Android in offline mode

### ISSUE THREAD

**Issue by Aelafseged** [PhilJay/MPAndroidChart#1932]
your work is simply superb, due to horrible connection in my place,Eritrea Horn of Africa  i work my android studio  in offline mode. and i found it hard debug or find jar file of your project for offline build.
Thank you for your time

**Comment by PhilJay** [comment]
What you can do is add the library as a dependency module.

v3.0.0 which will be released soon will probably also have a .jar file that you can then use.

**Comment by kusan-thana** [comment]
Is it possible to upgrade to AAR file? Not sure if it'd actually improve something but better do it now since it'll probably be the standard for librairies.
