### ISSUE TITLE
In Barchart,how to change the color  of the bar?

### ISSUE THREAD

**Issue by rehan91** [PhilJay/MPAndroidChart#1936]
same as the title,and i want to do this:
1.set the color of the bar;
2.set the highlight color of the bar;
thx very much!!

**Comment by PhilJay** [comment]
You cannot change the highlight color, but you can change the alpha value: `barDataSet.setHighlightAlpha(...)`

`barDataSet.setColors(...)`

**Comment by rehan91** [comment]
thanks very much!
