### ISSUE TITLE
In Barchart,can i set the stroke to make bar more obvious?

### ISSUE THREAD

**Issue by rehan91** [PhilJay/MPAndroidChart#1939]
i make the space between bar zero,so the bar will stucke together,this made the barChart like a whole mountain,so i want to make then distinct,and i want to know if there are some method to make stroke to make it clear...
any help appreciate..

**Comment by PhilJay** [comment]
`barDataSet.setBarBorderWidth(2f)`
`barDataSet.setBarBorderColor(...)`

**Comment by rehan91** [comment]
but i didn't have this two method ,my MPAndroidChart version too old?

**Comment by rehan91** [comment]
thanks,i have found the resolution,this method not set with dataset,but with chart ,so the method should be used for this:
mChart.setBarBorderWidth(2f)
mChart.setBarBorderColor(...)
