### ISSUE TITLE
Remove Y values and label

### ISSUE THREAD

**Issue by moonandroid** [PhilJay/MPAndroidChart#1940]
![device-2016-06-30-165528](https://cloud.githubusercontent.com/assets/9553836/16486580/5390a684-3ee3-11e6-81fa-0ae43f137d7b.png)

How i can remove these lables?
There are any property for these ?

**Comment by PhilJay** [comment]
1. `chart.getAxisLeft().setEnabled(false)`
2. `chart.getLegend().setEnabled(false)`

**Comment by moonandroid** [comment]
thanks man
