### ISSUE TITLE
Vertical Highlight height of the selected value

### ISSUE THREAD

**Issue by Drakot** [PhilJay/MPAndroidChart#1941]
Hello, 

I dont know if this is already working but I cant.

What I need is the big light green rectangle to be as high as the curve. That way we can see the selected 
value.

Here is how it is right now.

![captura de pantalla 2016-06-30 a las 13 08 05](https://cloud.githubusercontent.com/assets/10567874/16487075/dfe110f8-3ec8-11e6-9f46-11fe488b52cc.png)

**Comment by PhilJay** [comment]
You will have to modify the library to achieve this. This is not possible by default.
