### ISSUE TITLE
Jar file for 2.2.5

### ISSUE THREAD

**Issue by thaleslessa** [PhilJay/MPAndroidChart#1942]
Unfortunately I can't download the library from jetpack, so I need to get the jar file directly. Since v2.2.5 has some important bug fixes for us, I'd ask you to post the jar in the releases page.

Thanks!

**Comment by matejsnoha** [comment]
Hi, you can get any .jar from jitpack using maven [(download)](https://maven.apache.org/download.html) with a 1-liner like this:

`mvn dependency:get -DremoteRepositories=https://jitpack.io -Dartifact=com.github.PhilJay:MPAndroidChart:v2.2.5 -Ddest=mpandroidchart-2.2.5.jar`

The list of available versions is at https://jitpack.io/#PhilJay/MPAndroidChart
Hope it helps.

**Comment by thaleslessa** [comment]
Unfortunately I'm blocked by proxy, so that doesn't really work for me. That's why I've been relying on the jar to use the library
