### ISSUE TITLE
Enhancement : XML attribute configuration for charts

### ISSUE THREAD

**Issue by tonypatino-monoclesociety** [PhilJay/MPAndroidChart#1946]
It would be nice to configure XML embedded chart views in the same way that we can configure native Android views.  After the new version, do you think the lib would be in a stable enough position to add this feature?

**Comment by recoverrelax** [comment]
make a wrapper class and do it yourself. there are more priority bugs to fix i think

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
