### ISSUE TITLE
Realtime Chart Issue

### ISSUE THREAD

**Issue by Sher101** [PhilJay/MPAndroidChart#1949]
Hello,
I'm developping an android application (using the library version 2.2.4) that is aimed to plot a realtime graph. The code works fine but when it's time to move the graph with the moveViewToX method something goes wrong and the first visible value disappears.
`
   LineData ld = linechart.getLineData();
    	if (ld != null) {
    		LineDataSet dataset = (LineDataSet)ld.getDataSetByIndex(0);
    		if (dataset == null) {
    			dataset = createSet();
    			ld.addDataSet(dataset);
    		}
    		ld.addXValue(Integer.toString(i));
    		ld.addEntry(new Entry(rssi, dataset.getEntryCount()), 0);
    		linechart.notifyDataSetChanged();
    		linechart.setVisibleXRangeMaximum(10);
    		linechart.setVisibleXRangeMinimum(10);
    		linechart.moveViewToX(ld.getXValCount());
    	}
`
I don't understand where is the error. Could You please help me?
Thank You in advance
![screenshot_2016-07-03-12-02-32 1](https://cloud.githubusercontent.com/assets/20265327/16544922/ba390fb2-4117-11e6-9d09-ea9aff6c2bd2.png)

**Comment by PhilJay** [comment]
Upgrade to the latest version and call `data.notifyDataSetChanged()` after adding something.

**Comment by Sher101** [comment]
Hello @PhilJay, thank You for your answer. I need to have the .jar file but the latest version available is 2.2.4. Is there a method to create it from source code?
