### ISSUE TITLE
OnChartGestureListener not working with setRotationEnabled(false) in PieChart

### ISSUE THREAD

**Issue by ghost** [PhilJay/MPAndroidChart#1950]
Hi,

I'm trying to change the rotating behaviour of the PieChart for a dragging gesture with no luck.

If I setRotationEnabled(true), the OnChartGestureListener.onChartGestureStart and onChartGestureEnd is called, but the pie rotates (unwanted).
If I setRotationEnabled(false) the OnChartGestureListener.onChartGestureStart and onChartGestureEnd is not called at all, it doesn't work.

It seems that the behaviour is reversed, since we don't need to listen to gestures when enabling the rotation.
Is there any other way to acomplish a drag event listener?

Regards,
Roberto

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
