### ISSUE TITLE
How can we draw a line in the Y axis has a variety of labels

### ISSUE THREAD

**Issue by chsmy** [PhilJay/MPAndroidChart#1951]
How can we draw a line in the Y axis has a variety of labels like ![](https://github.com/chsmy/MyRecycleView/blob/master/123.png)  I try to change YAxisRenderer and  LineChartRenderer. But I failed.

**Comment by PhilJay** [comment]
I dont understand.

**Comment by chsmy** [comment]
Can I use MPAndroidChart to achieve this effect 
![](https://github.com/chsmy/MyRecycleView/blob/master/159.png)

There are three to the right of the Y axis labels .  Three lines depend on the right of the Y axis

**Comment by PhilJay** [comment]
Different axis on one side is not possible.
