### ISSUE TITLE
BarChart rendering problem in 3.0.0-beta1

### ISSUE THREAD

**Issue by Pitel** [PhilJay/MPAndroidChart#1953]
v2.5.0
![before](https://cloud.githubusercontent.com/assets/113248/16553873/8ee13bc8-41cb-11e6-8f18-fba328d98f3b.png)

v3.0.0-beta1
![after](https://cloud.githubusercontent.com/assets/113248/16553874/8efceefe-41cb-11e6-987a-c5ee10b8efba.png)

Tested on Android 4.4 and 6.

**Comment by PhilJay** [comment]
Thats not an issue, that's just how the new version works. There is no longer such a thing as "barSpace".

You specified the bars to be at x-position 0, 1, 2, 3, ... and the default bar width is 1f -> result, the bars touch each other.

You can either increase the x-position of the bars to 0, 1.1, 2.2, 3.3, etc or set the width of the bar to e.g. 0.9

`barData.setBarWidth(float barWidth)`
