### ISSUE TITLE
some ideas for improvement

### ISSUE THREAD

**Issue by rehan91** [PhilJay/MPAndroidChart#1954]
1.can show the markView but can chose to change or not change the bar's color when touch or highlight,this should also be a configuration;
2.can set the highlight color,not only the bar's color;
3.when i touch the bar,markView can show or hide,this can be a configuration;

i do hope these matters can be update later!!!thank you very much!

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
