### ISSUE TITLE
LineData constructor doesn't have string value entry anymore??

### ISSUE THREAD

**Issue by masoud2v** [PhilJay/MPAndroidChart#1956]
I want to add string values as my x axis values but i cannot add string arraylist in LineData constructor

                  ` LineDataSet setComp1 = new LineDataSet(valsComp1, "Company 1");
                    setComp1.setAxisDependency(YAxis.AxisDependency.LEFT);
                    setComp1.setColors(new int[]{Color.BLUE});
                    setComp1.setCircleColor(Color.BLUE);
                    setComp1.setCircleColorHole(Color.BLUE);

                    belowAxis.setValueFormatter(new MyCustomXAxisValueFormatter());

                    ArrayList<ILineDataSet> dataSets = new ArrayList<ILineDataSet>();
                    dataSets.add(setComp1);

                    ArrayList<String> xVals = new ArrayList<String>();
                    xVals.add("a");
                    xVals.add("b");
                    xVals.add("c");
                    xVals.add("d");

                    LineData data = new LineData(dataSets);
                    chart.setData(data);
                    chart.invalidate();`

**Comment by PhilJay** [comment]
No, this is now done via `AxisValueFormatter`.

Example:

```java

final String[] xValues = new String[] { "a", "b", "c" };

xAxis.setValueFormatter(new AxisValueFormatter() {
            @Override
            public String getFormattedValue(float value, AxisBase axis) {
                return xValues[(int) value % xValues.length];
            }

            @Override
            public int getDecimalDigits() {
                return 0;
            }
        });
```

**Comment by Pr0duktiv** [comment]
Please update the wiki, others might run into the same issue.

**Comment by gao746700783** [comment]
it helped me，please update the wiki
