### ISSUE TITLE
Move Chart Rendering Off the UI Thread

### ISSUE THREAD

**Issue by tonypatino-monoclesociety** [PhilJay/MPAndroidChart#1958]
Given that rendering charts is inherently expensive, performing the operation inside of onDraw places a hard limit on the smoothest frames per second we can hope to achieve.  

Drawing onto a bitmap buffer inside of a worker thread could offer a smoother animation experience.  onDraw then, would only re-draw the chart once the worker has completed its task and copied its bits to the bitmap that the UI thread will render.

**Comment by amiguels** [comment]
Any updates on this?

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
