### ISSUE TITLE
Pie Chart: Invisible slices are still activating events in the center hole

### ISSUE THREAD

**Issue by daveatwork123** [PhilJay/MPAndroidChart#1959]
My Requirements are a bit more sophisticated I need to be able to add up to 6 more icons to the center hole in the pie chart. I have managed to do this by Overlaying a layout atop the piechart center hole.

i have since detected that the pie chart does not allow us to

1.pick up events from the phone screen around the center of a piechart with the centerhole removed/unused
2. Invisible slices are still activating events in the center hole even when disabled using currentChart.setDrawSlicesUnderHole(false); in PieChart
3. There is no way of associating an event with the text in the center hole in the PieChart

Is there anay way we could resolve this issues?

regards
David

**Comment by azri92** [comment]
I guess one way is to put a circular Button on top of the hole in a RelativeLayout - put the Button after PieChart in code.

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
