### ISSUE TITLE
y axis unit

### ISSUE THREAD

**Issue by changjieyy** [PhilJay/MPAndroidChart#1960]
Could not add the Y axis data unit？

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/The-YAxisValueFormatter-interface

**Comment by changjieyy** [comment]
I'm saying this, like a picture.  Marked out of in picture.
![20160709122722](https://cloud.githubusercontent.com/assets/6008507/16706138/117cc51a-45d3-11e6-8adb-f1cbb18ed422.png)

**Comment by 603530013** [comment]
`private class YourValueFormatter implements IAxisValueFormatter {
        @Override
        public String getFormattedValue(float value, AxisBase axis) {
            float[] axisEntries = axis.mEntries;
            String result = (int) value + "";
            if (value == yAxis[yAxis.length - 1]) {
                result = yourUnit;
            }
            return result;
        }
    }`

**Comment by acenodie** [comment]
so , how can i do like the picture??

**Comment by plain-dev** [comment]
You can do it with the help of `Description`, the specific method is as follows

```kt
chart.apply {
    // Reserve space at the top of the chart
    extraTopOffset = 30f

    post {
        description.apply {
            isEnabled = true

            text = unit
            textSize = 10f
            textColor = color

            val offsetLeft = viewPortHandler.offsetLeft()
            val offsetTop = viewPortHandler.offsetTop()
            val offsetRight = viewPortHandler.offsetRight()

            when (position) {
                LeftTop -> {
                    textAlign = Paint.Align.LEFT
                    offsetLeft / 2 to offsetTop - 10f.px
                }
                RightTop -> {
                    textAlign = Paint.Align.RIGHT
                    width - offsetRight / 2 to offsetTop - 10f.px
                }
            }.apply {
                setPosition(first, second)
            }
        }
    }
}
```
