### ISSUE TITLE
In Barchart,how to set can scroll the bar?

### ISSUE THREAD

**Issue by rehan91** [PhilJay/MPAndroidChart#1961]
there are too many bar in the phone screen,so,i want to scroll the screen to see the other bar,
in addition,i have two barchart in a viewpager,so ,can i scroll the screen to see another page,
and also ,i can scroll the barchart to see more bar?
any help appreciate!

**Comment by castrojr913** [comment]
@PhilJay. Sir, I don't understand why do you close the issue without explaining anything? Is it fixed, isn't?
