### ISSUE TITLE
Missing addXValue() in the example of Dynamic & Realtime Data tutorial

### ISSUE THREAD

**Issue by hankes-garden** [PhilJay/MPAndroidChart#1962]
In the webpage of [Dynamic & Realtime Data](https://github.com/PhilJay/MPAndroidChart/wiki/Dynamic-&-Realtime-Data), two examples are given at the end of tutorial: [DynamicalAddingActivity] (https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/DynamicalAddingActivity.java) and [RealtimeDataActivity](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/RealtimeLineChartActivity.java).

Both of these two examples use ChartData.addEntry() function to add a point. However, calling this function without corresponding invoke of ChartData.addXValue() can cause a fail on the ChartData.checkLegal() and raise an IllegalArgumentException saying "One or more of the DataSet Entry arrays are longer than the x-values array of this ChartData object".

Since this tutorial targets at newbies, this can be very confusing.

**Comment by PhilJay** [comment]
This can only happen if your code is based on an outdated version of this library.
As the new release states the current documentation is not up to date so developers should refer to the example project only for the time being.

https://github.com/PhilJay/MPAndroidChart/releases
