### ISSUE TITLE
part of the markerview is out of screen

### ISSUE THREAD

**Issue by wtwt91** [PhilJay/MPAndroidChart#1963]
when the markerview's width is big, it will show out of the screen, like as
![qq20160706-0](https://cloud.githubusercontent.com/assets/3053007/16620019/5e17e7ea-43c3-11e6-9eb3-3329b3a14567.png)

**Comment by wtwt91** [comment]
I have create a new one which extends MarkerView, and overwrite draw.

**Comment by 603530013** [comment]
@wtwt91 
do u have code example?
