### ISSUE TITLE
Dynamically add data

### ISSUE THREAD

**Issue by smith1994** [PhilJay/MPAndroidChart#1964]
Hello PhilJay,
When I dynamically add data from a sensor, 10 seconds it is ok. However, when i measure about 1 minute it starts to slow the Chart and then hang the phone. I think because of my internal storage. So, I want to see about 200 samples and then the Chart will overwrite the old samples. But I don't know how to do it. Can you show me some functions that can deal with my problem ?
Thank you in advance.

**Comment by fantingdong** [comment]
hello, what is the IDE you are working with? Eclipse+ADT or Android Studio?

**Comment by TeunKooijman** [comment]
What I do to create a kind of round robin realtime chart is to check everytime I add an entry whether or not the set has more than the desired amount of entries. A piece of sample code would be:

```
private void addEntry(float x, float y)
{
     //Grab a reference to the LineData and DataSet objects. Initialize them if they're null.
     LineData data = chart.getData();

     if(data == null)
     {
          data = new LineData();
          this.chart.setData(data);
     }

     ILineDataSet set = data.getDataSetByIndex(0);

     if(set == null)
     {
          set = new LineDataSet(null, "Values");
          data.addDataSet(set);
     }

     //Add the measurement to the chart.
     set.addEntry(new Entry(x, y));

     //Round robin the set.
     while(set.getEntryCount() > MAXIMUM_ENTRY_COUNT)
     {
          data.removeEntry(0, 0);
     } 

     //Let the chart know it's data has changed.
     this.chart.notifyDataSetChanged();
     this.chart.invalidate();
}
```

Hope this helps.

**Comment by fantingdong** [comment]
Thank you for your  kind help! 

When I was trying to add new entry into the realtime charts, I got an error with the following statement:  "One or more of the DataSet Entry arrays are longer than the x-values array of this ChartData object". 

What would be the solution to the problem? Could anyone provide any tips?

The code I was using is shown below:

`	protected void onCreate(Bundle savedInstanceState){
		super.onCreate(savedInstanceState);		
		setContentView(R.layout.activity_realtime_linechart);
		
		mChart=(LineChart) findViewById(R.id.chart6);
	
		mChart.setDescription("");
		mChart.setNoDataTextDescription("You need to provide data for the chart.");
		mChart.setTouchEnabled(true);
		
		mChart.setDragEnabled(true);
		mChart.setScaleEnabled(true);
		mChart.setDrawGridBackground(true);
		
		mChart.setPinchZoom(true);
		mChart.setBackgroundColor(Color.LTGRAY);
		
		LineData data=new LineData();
		data.setValueTextColor(Color.BLUE);
		
		mChart.setData(data);
		
		Legend l=mChart.getLegend();
		l.setForm(LegendForm.LINE);
	
		l.setTextColor(Color.WHITE);
		
		XAxis xl=mChart.getXAxis();
		xl.setPosition(XAxisPosition.BOTTOM);
		xl.setTextColor(Color.WHITE);
		xl.setDrawGridLines(false);
		xl.setAvoidFirstLastClipping(true);
		xl.setEnabled(true);
		YAxis leftAxis=mChart.getAxisLeft();
		leftAxis.setTextColor(Color.WHITE);
		leftAxis.setAxisMaxValue(100f);
		leftAxis.setAxisMinValue(0f);
		leftAxis.setDrawGridLines(true);
		
		YAxis rightAxis=mChart.getAxisRight();
		rightAxis.setEnabled(false);
		
		addEntry();
		
	}
	
	
	private void addEntry() {

        LineData data = mChart.getData();

        if (data != null) {

            ILineDataSet set = data.getDataSetByIndex(0);
            
            if (set == null) {
                set = createSet();
                data.addDataSet(set);
            }
            data.addEntry(new Entry((float)(Math.random()*40)+30f,0), 0);
            data.addEntry(new Entry((float)(Math.random()*40)+30f,1), 0);
            data.addEntry(new Entry((float)(Math.random()*40)+30f,2), 0);
           
           data.notifyDataChanged();

            // let the chart know it's data has changed
           mChart.notifyDataSetChanged();

            // limit the number of visible entries
           mChart.setVisibleXRangeMaximum(120);
            // mChart.setVisibleYRange(30, AxisDependency.LEFT);
           mChart.setVisibleXRangeMinimum(5);

            // this automatically refreshes the chart (calls invalidate())
            // mChart.moveViewTo(data.getXValCount()-7, 55f,
            // AxisDependency.LEFT);
           mChart.invalidate();
        }
    }

    private LineDataSet createSet() {

        LineDataSet set = new LineDataSet(null, "Dynamic Data");
        set.setAxisDependency(AxisDependency.LEFT);
        set.setColor(ColorTemplate.getHoloBlue());
        set.setCircleColor(Color.WHITE);
        set.setLineWidth(2f);
        set.setCircleRadius(4f);
        set.setFillAlpha(65);
        set.setFillColor(ColorTemplate.getHoloBlue());
        set.setHighLightColor(Color.rgb(244, 117, 117));
        set.setValueTextColor(Color.WHITE);
        set.setValueTextSize(9f);
        set.setDrawValues(false);
        return set;
    }`

**Comment by PhilJay** [comment]
You are using an older version of this library, and you are not adding enough x-values to display all entries you added.

`data.addXValue(...)`
