### ISSUE TITLE
fill rendering not working for API < 18

### ISSUE THREAD

**Issue by mohamedpsx** [PhilJay/MPAndroidChart#1966]
@PhilJay && @danielgindi  I know that this was mentioned in multiple issues before (like #1100), but after some investigation the implemented solution is not doing the job, yes we can control HardwareAcceleration by using `chart.setHardwareAccelerationEnabled` but the filling methods are using `clipPathSupported ` [LineRadarRenderer:92](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/main/java/com/github/mikephil/charting/renderer/LineRadarRenderer.java#L92) which only checks for the API LEVEL resulting in `Fatal Exception: java.lang.RuntimeException: Fill-drawables not (yet) supported below API level 18, this code was run on API level 17.` no matter if HWA enabled or not.

**Comment by mohamedpsx** [comment]
this hsould fix it , at least for v2.2.5 https://github.com/mohamedpsx/MPAndroidChart/blob/master/MPChartLib/src/com/github/mikephil/charting/renderer/LineRadarRenderer.java

**Comment by hram** [comment]
Hi!
How can I get this fix?
In version 3.0.2 bug is still present

**Comment by hram** [comment]
https://github.com/mohamedpsx/MPAndroidChart/blob/master/MPChartLib/src/com/github/mikephil/charting/renderer/LineRadarRenderer.java

solved bug, but how can I get fixed version from official repo?
