### ISSUE TITLE
Set custom x-value spacing in graph

### ISSUE THREAD

**Issue by KodiKraig** [PhilJay/MPAndroidChart#1968]
I am trying to achieve custom x spacing such as the way the y axis acts. The reason is I want to graph a best fit line on a line graph but it really doesn't work properly without the actual x values corresponding to the distance between them displayed on the graph. If this not an option by default could you please point me in the direction as to which classes I might need to modify in the library. Thank you!

**Comment by TeunKooijman** [comment]
The newest version ([v3.0.0-beta1](https://github.com/PhilJay/MPAndroidChart/releases/tag/v3.0.0-beta1)) has added suport for x indices. Change your gradle compile statement to `compile 'com.github.PhilJay:MPAndroidChart:v3.0.0-beta1'` and your `Entry` constructors should now support x and y coordinates.
