### ISSUE TITLE
How to set BarChart bar width and spacing?

### ISSUE THREAD

**Issue by Bishalsingh** [PhilJay/MPAndroidChart#197]
How can i increase barchart width and Spacing between them?

**Comment by 15mgm15** [comment]
@PhilJay Is there a way to know the width of the full X column in pixels/dp? and with full column I mean this:

![screenshot-2017-03-09_11 21 42 426](https://cloud.githubusercontent.com/assets/3074404/23762159/cf53e77a-04ba-11e7-8af7-655ebb42a5be.png)

**Comment by CurtesMalteser** [comment]
> @PhilJay Is there a way to know the width of the full X column in pixels/dp? and with full column I mean this:
> 
> ![screenshot-2017-03-09_11 21 42 426](https://cloud.githubusercontent.com/assets/3074404/23762159/cf53e77a-04ba-11e7-8af7-655ebb42a5be.png)

is there any answer to this question? It would be quite useful to get the this data in one clear way so it would make easier to make a lot of stuff. In special manage the number of labels dynamically.

**Comment by CurtesMalteser** [comment]
Could this be the right width?
` val barWidth = transformer.getPixelForValues(dataSet.barWidth, 0F).x - transformer.getPixelForValues(0.15f, 0F).x`

This is my thought:
-  0.85f is the default value and when apply this to `transformer.getPixelForValues(dataSet.barWidth, 0F).x` I get a super large column width
- So I suppose that the return measured width is 100%
- Then I tried subtracting 0.15f, which seems to work

@PhilJay can you confirm if this is correct please?

**Comment by nnyerges** [comment]
@CurtesMalteser this may help:

            float barWidth = bChart.getBarData().getBarWidth();
            Transformer transformer = bChart.getTransformer(YAxis.AxisDependency.LEFT);
            MPPointD barDimensPoint = transformer.getPixelForValues(barWidth, 0);
            float barWidthInPixels = (float) barDimensPoint.x;

**Comment by nnyerges** [comment]
@CurtesMalteser may this help:

        float bWidth = bChart.getBarData().getBarWidth();
        Transformer transformer = bChart.getTransformer(YAxis.AxisDependency.LEFT);
        MPPointD barDimensPoint = transformer.getPixelForValues(barWidth, 0);
        float barWidth = (float) barDimensPoint.x;
