### ISSUE TITLE
can i set the value of Y-Axis?

### ISSUE THREAD

**Issue by rehan91** [PhilJay/MPAndroidChart#1970]

**Comment by PhilJay** [comment]
Yes, you can set label count + min/max value and granularity. This means that you can set any values you want. 

https://github.com/PhilJay/MPAndroidChart/wiki/YAxis

**Comment by rehan91** [comment]
mChart.getAxisLeft().setGranularity(2.0f);
why can't i use this method?setGranularity() in my project said"cannot resolve method"

**Comment by PhilJay** [comment]
Because you are probably not using the latest version...
