### ISSUE TITLE
Can't disable circles in a values range

### ISSUE THREAD

**Issue by ferPrieto** [PhilJay/MPAndroidChart#1971]
Hello, I am using LineChart and I would like to show only circles in the first (0) value and the last. So I wanted to hide some circles inside a range from one value to another value. Would it be possible?

**Comment by PhilJay** [comment]
You can only enable or disable circles for a whole data set. But you can use two datasets and disable values for one and enable it for the other.

**Comment by ferPrieto** [comment]
Many thanks for answering so fast! Will try your two datasets option :)   Cheers

**Comment by emersonwdesigner** [comment]
Hello friend, I'm using pieChart, how do I get the center circle?

**Comment by nrana982** [comment]
My requirement is that i need to show the circle when user tap on graph for that particular point, an idea how to implement that @PhilJay
