### ISSUE TITLE
how to set a part of barchart's background color?

### ISSUE THREAD

**Issue by rehan91** [PhilJay/MPAndroidChart#1977]
i want to set the background color of the barchart,but not whole barchart,just a part of bar's background,i mean can i set the area,just like this :`mChart.setBackgroundColor(Color.BLUE,int from,int to);`
"from" means:start of one bar,and "to" means:end of one bar.

any help appreciate!

**Comment by PhilJay** [comment]
Currently not possible

**Comment by rehan91** [comment]
look forward to update...
