### ISSUE TITLE
Why BarData constructor not work ?

### ISSUE THREAD

**Issue by WithGJR** [PhilJay/MPAndroidChart#1980]
My code:

``` java
 public BarData getBarData(String fieldName) {
        ArrayList<BarEntry> entries = new ArrayList<>();
        entries.add(new BarEntry(this.house.Population, 0));
        entries.add(new BarEntry(this.currentStore.Population, 1));

        ArrayList<String> labels = new ArrayList<String>();
        labels.add("house");
        labels.add("store" + this.currentStore.StoreName);

        List<BarDataSet> dataSets = new ArrayList<>();
        dataSets.add(new BarDataSet(entries, fieldName));
        
        return new BarData(labels, dataSets);
    }
```

According to the document, the BarData constructor is like the code above. But why Android Studio always tell me there is something wrong? 

Please give me some information. Thanks.

**Comment by PhilJay** [comment]
Because you are using the latest version which includes major changes. I suggest you read the compiler error.

**Comment by taranbirvirk** [comment]
if you are using latest version of Barchat then replace dependency version to this :
   implementation 'com.github.PhilJay:MPAndroidChart:v2.2.4'
