### ISSUE TITLE
Extra lines appearing in Y axis

### ISSUE THREAD

**Issue by saurabh190** [PhilJay/MPAndroidChart#1981]
Hey there. I have been using MP android chart's Bar chart in my android application. I am using the following code -
`       barChart.setData(data);

        //For pinch zoom
        barChart.setPinchZoom(false);

        //To enable/disable barChart scaling upon 2 fingers expansion on the chart
        barChart.setScaleXEnabled(false);
        barChart.setScaleYEnabled(false);

        //To disable double tap zoom
        barChart.setDoubleTapToZoomEnabled(false);

        barChart.animateY(3000);

        YAxis yAxis = barChart.getAxisLeft();
        yAxis.setAxisMinValue(0);`

All is looking good with the exception that I am getting extra Horizontal lines along side the intended lines which are aligned to the lables in the y axis. Those extra horizontal lines are not aligned to the Y axis labels.
How can these extra horizontal lines be removed ?

**Comment by jerofad** [comment]
If the lines are in form of a grid, then you can try this piece of code;
`    XAxis xAxis = barChart.getXAxis();
    xAxis.setDrawGridLines(false);
    xAxis.setDrawAxisLine(false);`

**Comment by saurabh190** [comment]
Solved it. For the solution and please go the StackOverflow link here :
http://stackoverflow.com/questions/38055343/unable-to-display-pivot-point-in-bar-graph-in-mp-android-chart/38239901#38239901
