### ISSUE TITLE
customer bar chart color

### ISSUE THREAD

**Issue by yanjf90** [PhilJay/MPAndroidChart#1982]
can I set different colors for one dataset?
for example, depending on different y value levels show different color.

**Comment by jerofad** [comment]
Yes you can. You can decide to create an array of colors and then call the `setColors()` method. 
Below is a sample:
`int[] colorArray= { Color.rgb(220, 20, 60), Color.rgb(210, 105, 30), Color.rgb(65, 105, 225),
                Color.rgb(34, 139, 34),};
        dataset.setColors(ColorTemplate.createColors(colorArray));`
