### ISSUE TITLE
why i cannot use two barChart in a layout?

### ISSUE THREAD

**Issue by rehan91** [PhilJay/MPAndroidChart#1984]
i use two barchart in a lineLayout,the first barchart can show,but the second barchart cannot show the bar,and it said"no chart data avaiable",but i actually set the data to the second barchart.and another funny question,the two barchart has a margin,but i never set the margin,i want to merge two barchart 
together...

**Comment by MGaetan89** [comment]
Is this still relevant?
Did you find a source of your issue?

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
