### ISSUE TITLE
XAxis vertical limit line should be linked to data XValue

### ISSUE THREAD

**Issue by pwireless** [PhilJay/MPAndroidChart#1985]
XAxis vertical limit line should be linked to data XValue, needed especially for real-time charting, since the line moves constantly to the left, as opposed to the yaxis limit lines that do not move.

So maybe adding another constructor, to be used for XAxis limit line would be great:

LimitLine ll1 = new LimitLine(data_xvalue, label);

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
