### ISSUE TITLE
Discontinuous line in the line chart

### ISSUE THREAD

**Issue by pwireless** [PhilJay/MPAndroidChart#1986]
Is there a way to add line points that are not all connected with a line?

A discontinuous line option in the line chart would be nice feature.

A float value could be set by the user, so when the Entry has that value the line to the previous point would be discontinued.

Thanks for the great work you have done.

**Comment by vygiszs** [comment]
I'm also intrested in this feature. Was able to do it in v2, but have big time problems with v3

**Comment by pa1pal** [comment]
Any solution for this yet?

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
