### ISSUE TITLE
3.0.0-beta1 - Highlighting of measurements not working correctly.

### ISSUE THREAD

**Issue by TeunKooijman** [PhilJay/MPAndroidChart#1988]
In the V3.0.0-beta1 release of the library, my linecharts no longer seem to handle touch events (highlighting of a measurement) correctly. Please refer to the following video to see what I mean:

https://lookback.io/watch/oFC99bLEpuWneJ4N5

**Comment by PhilJay** [comment]
That's related to the newly introduced "highlight-distance". It's not a bug, it's a feature :-)
You can now specify a maximum distance to which highlighting will trigger in dp. If you set it to 100dp, highlight gestures further away than 100dp from an entry will not trigger a highlight.

To change this, simply increase the highlight distance: 

`chart.setMaxHighlightDistance(500f)`

Default value is 100dp.

**Comment by TeunKooijman** [comment]
Dear PhilJay, 

Thanks for the swift reply. I have tried the fix you have suggested and set the maxHighlightDistance to Float.MAX_VALUE. This did indeed fix some of the performance issue, but did not fix it entirely. I have made another video displaying what I mean:

https://lookback.io/watch/gdxSGi4jH2mEP6J42

Do you have any idea what might be causing this?
