### ISSUE TITLE
HorizontalBarChart dataset values not showing when zoomed

### ISSUE THREAD

**Issue by CyberMew** [PhilJay/MPAndroidChart#1989]
I'm looking at the latest example from HorizontalBarChartActivity. When zoomed, the dataset value sometimes does not appear in/above the bar. This is easily replicable if you fired up the example app and zoom it. However, this is not an issue in the example for BarChartActivity.

Is this a bug or are some settings made that causes this inconsistency inside HorizontalBarChartActivity?

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
