### ISSUE TITLE
HorizontalBarChart bars disappears when zoomed vertically

### ISSUE THREAD

**Issue by CyberMew** [PhilJay/MPAndroidChart#1990]
I didn't have time to try this with other examples yet, but I found out that if I did the countdown insertion, the bars disappears when zooming along the x axis.

Replace line 221 with this:
`for (int i = count; i > 0; i--) {`

I encountered this issue when I was trying to reverse the x-axis, but it seems like this cannot be done? Smaller values should be at the top, and go downwards, instead of the current big values on top, and smaller values at the bottom.

**Comment by PhilJay** [comment]
Library version?

**Comment by CyberMew** [comment]
3 beta 1 iirc

**Comment by CyberMew** [comment]
The bar values are still disappearing in your example on the latest 3.0.0 release.

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
