### ISSUE TITLE
Possible to have a x-value for each bar?

### ISSUE THREAD

**Issue by CyberMew** [PhilJay/MPAndroidChart#1991]
This is on Horizontal Bar Chart. I'm trying to get each bar to have their own x-value, but it isn't working. But I'm pretty sure it appears to other types of charts as well. I'm referring to the zoom out version, since when zoomed in everything shows up ok.

edit: looks like there was a `setLabelsToSkip` for XAxis in the past, but current versions don't have them anymore?

**Comment by hzw1199** [comment]
I want to know too, please help

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
