### ISSUE TITLE
How to set vertical orientation to the legend for LineChart

### ISSUE THREAD

**Issue by anto2b** [PhilJay/MPAndroidChart#1992]
Hi, 

Here is my actually rendering of the chart : [http://img15.hostingpics.net/pics/265445chart1.jpg](http://img15.hostingpics.net/pics/265445chart1.jpg)

But i would like achieve this rendering (legend in vertical) : [http://img15.hostingpics.net/pics/141149chart2.jpg](http://img15.hostingpics.net/pics/141149chart2.jpg)

Here is my code :

```
LineChart chart = (LineChart )findViewById(...);
chart .getLegend().setHorizontalAlignment(Legend.LegendHorizontalAlignment.LEFT);
chart .getLegend().setVerticalAlignment(Legend.LegendVerticalAlignment.CENTER);
chart .getLegend().setOrientation(Legend.LegendOrientation.VERTICAL);
chart .getLegend().setFormSize(0f);
```

Thanks you for your helps !

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
