### ISSUE TITLE
MPAndroidChart insert Y axis listArray variable or dinamic params

### ISSUE THREAD

**Issue by oscarcuenca** [PhilJay/MPAndroidChart#1993]
Hi
This is the first time I am using MPAndroidChart.
I would like to make a Lineal Chart but not sure how to do it. I would like  to introduce variable or dinamic parameter into Y axis(MPAndroidChart). The params comes from remote server, and they are not fix params since they are "temperature and Humidity" catched from a sensor in real time, then It is allocated in Mysql and from my APP make a chart after geting this data, every time I open the Actitity for the chart the parameters are different.

I would like to have any help on how to make it. I have my code like this:

For params (humidity and temperature) in method "CapatarParametros()" using loopj to connect to server and geting the data:

`List<String> allNames = new ArrayList<String>();

 JSONArray cast = jsonobject.getJSONArray("result");
                for (int i=0; i<cast.length(); i++) {
                    JSONObject parametrosdht11 = cast.getJSONObject(i);
                    String temperatura = parametrosdht11.getString("temperatura");
                    String humedad = parametrosdht11.getString("humedad");
                    allNames.add(temperatura);
                    allNames.add(humedad);`

This code give me temperature and humedity from remote BBDD. Now I need to take these parameters and add to the y axis (per exemple "temperature" ) in Oncreate :

`LineChart lineChart = (LineChart) findViewById(R.id.chart);

```
ArrayList<Entry> entries = new ArrayList<>();`
```

_**(.... here I do not know how to focus it....)**_

Thanks in advance for your help-
Óscar

**Comment by oscarcuenca** [comment]
Solution

`ArrayList<Entry> temperature = new ArrayList<>();
ArrayList<Entry> yVals2 = new ArrayList<>();
LineChart mChart; `

    then:
` protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.actividad_datos_sensor);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
        mChart = (LineChart) findViewById(R.id.chart);`

then;

`  mChart.setDescription("");
        mChart.setNoDataTextDescription("You need to provide data for the chart.");

        // enable touch gestures
        mChart.setTouchEnabled(true);

        mChart.setDragDecelerationFrictionCoef(0.9f);

        // enable scaling and dragging
        mChart.setDragEnabled(true);
        mChart.setScaleEnabled(true);
        mChart.setDrawGridBackground(false);
        mChart.setHighlightPerDragEnabled(true);

        // if disabled, scaling can be done on x- and y-axis separately
        mChart.setPinchZoom(true);

        // set an alternative background color
        mChart.setBackgroundColor(Color.LTGRAY);
        mChart.animateX(2500);

        XAxis xAxis = mChart.getXAxis();
        xAxis.setTextSize(11f);
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setAxisMaxValue(125f);
        xAxis.setAxisMinValue(0f);
        xAxis.setTextColor(Color.WHITE);
        xAxis.setDrawGridLines(false);
        xAxis.setDrawAxisLine(false);

        //modify leftYaxis range similarly others
        YAxis leftAxis = mChart.getAxisLeft();
        leftAxis.setTextColor(ColorTemplate.getHoloBlue());
        leftAxis.setAxisMaxValue(50f);
        leftAxis.setAxisMinValue(10f);
        leftAxis.setDrawGridLines(false);
        leftAxis.setGranularityEnabled(true);

        YAxis rightAxis = mChart.getAxisRight();
        rightAxis.setTextColor(Color.RED);
        rightAxis.setAxisMaxValue(50f);
        rightAxis.setAxisMinValue(10f);
        rightAxis.setDrawGridLines(false);
        rightAxis.setDrawZeroLine(false);
        rightAxis.setGranularityEnabled(false);

        // add data
        setData();
    }
`
then:

` public void onSuccess(int statusCode, Header[] headers, JSONObject response) {
                // called when response HTTP status is "200 OK"
                JSONObject jsonobject = null;
                JSONObject dht11JSONbject = null;
                JSONArray dht11JSONarray = null;

                try {

                    jsonobject = new JSONObject(String.valueOf(response));
                    //dht11JSONbject = jsonobject.getJSONObject("result");

                    List<String> allNames = new ArrayList<String>();
                    JSONArray cast = jsonobject.getJSONArray("result");
                    for (int i=0; i<cast.length(); i++) {
                        JSONObject parametrosdht11 = cast.getJSONObject(i);
                        String temperatura = parametrosdht11.getString("temperatura");
                        String humedad = parametrosdht11.getString("humedad");
                        String fecha = parametrosdht11.getString("Insertado");
                        temperature.add(new Entry(Float.valueOf(i),Float.valueOf(temperatura)));
                        yVals2.add(new Entry(Float.valueOf(i), Float.valueOf(humedad)));
                        //labels.add(new Entry(toString(fecha)));

                        //rrefresh
                        mChart.notifyDataSetChanged();
                        // limit the number of visible entries
                        mChart.setVisibleXRangeMaximum(12);`

then:

` private void setData() {
//data set represents a lin
        LineDataSet set1, set2;

        // create a dataset and give it a type
        //modifications with colour and stuf
        set1 = new LineDataSet(temperature, "temperature");
        set1.setAxisDependency(YAxis.AxisDependency.LEFT);
        set1.setColor(ColorTemplate.getHoloBlue());
        set1.setCircleColor(Color.WHITE);
        set1.setLineWidth(2f);
        set1.setCircleRadius(3f);
        set1.setFillAlpha(65);
        set1.setFillColor(ColorTemplate.getHoloBlue());
        set1.setHighLightColor(Color.rgb(244, 117, 117));
        set1.setDrawCircleHole(false);

        //set1.setFillFormatter(new MyFillFormatter(0f));
        //set1.setDrawHorizontalHighlightIndicator(false);
        //set1.setVisible(false);
        //set1.setCircleHoleColor(Color.WHITE);

        // create a dataset and give it a type
        // similar above
        set2 = new LineDataSet(yVals2, "humidity");
        set2.setAxisDependency(YAxis.AxisDependency.RIGHT);
        set2.setColor(Color.RED);
        set2.setCircleColor(Color.WHITE);
        set2.setLineWidth(2f);
        set2.setCircleRadius(1f);
        set2.setFillAlpha(65);
        set2.setFillColor(Color.RED);
        set2.setDrawCircleHole(false);
        set2.setHighLightColor(Color.rgb(244, 117, 117));
        //set2.setFillFormatter(new MyFillFormatter(900f));

        ArrayList<ILineDataSet> dataSets = new ArrayList<ILineDataSet>();
        dataSets.add(set1); // add the datasets
        dataSets.add(set2);

        // create a data object with the datasets
        LineData data = new LineData(dataSets);
        data.setValueTextColor(Color.WHITE);
        data.setValueTextSize(9f);

        // set data
        Log.i("Lists Sizedata",temperature.size() + " and " + yVals2.size());
        mChart.setData(data);
        // move to the latest entry
       mChart.moveViewToX(data.getEntryCount());
`

But I would like to plot in X Axis also dinamic data, like TimeStamp from server. I know how to bring data, but not know how to plot it , I would like to make it in same activity but not creating a new one with "XAxisValueFormatter". Any help will be wellcome.

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
