### ISSUE TITLE
Combined Chart (Grouped bar chart and line chart)

### ISSUE THREAD

**Issue by van-cuong-nguyen** [PhilJay/MPAndroidChart#1994]
I see a combined chart example with a bar chart and a line chart. However, I want to create a line chart with a group bar chart. Please help me, i have spent a lot of time but fail.

**Comment by PhilJay** [comment]
- versions prior to v3.0.0 do not support grouped barcharts in combinedchart
- if you are on v3.0.0, take a look at this example: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/CombinedChartActivity.java
