### ISSUE TITLE
In Barchart,can i set the size of background?

### ISSUE THREAD

**Issue by rehan91** [PhilJay/MPAndroidChart#1996]
i don't want all barchart filled with a color,i want the color can follow the value of the Y-axis,and only fill with the color inside the area the bar reach...the blank that top of the bar should not be filled...can i do this?
any help appreciate!!!

**Comment by jerofad** [comment]
Yes you can. You can decide to create an array of colors and then call the `setColors()`  method. 
Below is a sample:
`int[] colorArray= { Color.rgb(220, 20, 60), Color.rgb(210, 105, 30), Color.rgb(65, 105, 225), Color.rgb(34, 139, 34),}; dataset.setColors(ColorTemplate.createColors(colorArray));`

**Comment by rehan91** [comment]
this seems to set the color of the bar?but i want to set the background color......thanks
