### ISSUE TITLE
HorizontalBarChart unable to scroll to top when zoomed

### ISSUE THREAD

**Issue by CyberMew** [PhilJay/MPAndroidChart#1998]
I'm using `setVisibleXRangeMaximum` and `setVisibleXRangeMinimum`, so my graph does not fit to screen as I want the individual bar labels to appear.

However, since HorizontalBarChart is very fixated on the bottom (i.e. everything is orientated with respect to bottom-most), even the default viewport starts at the bottom. I am unable to use `chart.moveViewToX(0);` to scroll it back up to the top. I am calling the function after `setData()` and before `invalidate()`.

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
