### ISSUE TITLE
MPAndroid Chart:  chart colors.

### ISSUE THREAD

**Issue by jerofad** [PhilJay/MPAndroidChart#1999]
Hello, I need help on how to remove the color boxes beneath the BarChart.
![image](https://cloud.githubusercontent.com/assets/13038413/16726413/3d383ab8-4786-11e6-9d8f-8f88ac8f0282.png)

I don't want those tiny little boxes there. Any help?

**Comment by rehan91** [comment]
this very simple,use this method:
` Legend legend = mChart.getLegend();`
` legend.setEnabled(false);`

**Comment by jerofad** [comment]
OMG! it worked! you're a life saver. thanks so much.

**Comment by rehan91** [comment]
My pleasure. ^_^

**Comment by ozanurkn** [comment]
thanks, it work for me like Jerofad.
