### ISSUE TITLE
MarkerView not working

### ISSUE THREAD

**Issue by PhilJay** [PhilJay/MPAndroidChart#2]
Due to the latest code changes / improvements, the marker-view that can be displayed when selecting values is currently not working.

**Comment by esfahanpayamak94** [comment]
اصفهان پیامک به عنوان فعال در زمینه [طراحی سایت در اصفهان](http://www.esfahanpayamak.com/webDesign) اهمیت این موضوع را به خوبی درک کرده و لذا از تکنولوژی های مدرن در طراحی های خود استفاده می نماید.
