### ISSUE TITLE
Use double instead of float for Entry objects

### ISSUE THREAD

**Issue by matheusjardimb** [PhilJay/MPAndroidChart#2002]
I just started dealing with bigger values and float just can't represent them.

**Comment by rehan91** [comment]
you can format your values to float...use BigDecimal to parse then!

**Comment by CyberMew** [comment]
It would actually be great if it took in objects instead and then we had a function to output, based on the object, the value and also the value to be shown on screen.  That would solve a lot of problems I'm having.

**Comment by MarkOSullivan94** [comment]
@rehan91 could you post an example of this?
