### ISSUE TITLE
[bug...]In Barchart,i use two DataSet,but can't set the barSpace and bar's size too small...

### ISSUE THREAD

**Issue by rehan91** [PhilJay/MPAndroidChart#2004]
in this situation,i want to set two different bar color and two different barSpace,so i use two set to try to realized that,but the space between bar too large and the size of bar are too small,in this situation,how can i adjust these?
any help appreciate!!!

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
