### ISSUE TITLE
How to customize the label for x axis?

### ISSUE THREAD

**Issue by KiBa1215** [PhilJay/MPAndroidChart#2006]
I'm finding all around, and still have no idea how to change the values of x-axis, using **CubicLineChart**.
Could anyone tell me how to do it ?

**Comment by plthatfunkymusic** [comment]
Hi Phil

I was also trying to set custom labels along the X-Axis (using a String for the date) as per the example given in the wiki (https://github.com/PhilJay/MPAndroidChart/wiki/Setting-Data)  

(my code...)
ArrayList<String> xStrings = new ArrayList<>();
...
BarData data = new BarData(xStrings, dataSets);


but it appears this has changed with version 3.0.   How do I achieve the same result with rel. 3.0 ? 

Thanks,
Simon

**Comment by PhilJay** [comment]
Use the `AxisValueFormatter` interface.

**Comment by plthatfunkymusic** [comment]
Thanks, I'll check it out.  Thanks for speedy response, appreciated.
