### ISSUE TITLE
how to use only 2 colors in stackedBarChart

### ISSUE THREAD

**Issue by Swapnil-Garg16** [PhilJay/MPAndroidChart#2007]
I have 2 Y-axis values for one X-axis value , ie , one bar should have only 2 colours.I want  2 fixed colours (say green and orange-green for lower bar and orange for upper bar) in StackedBarChart for all bars.I don't want all bars having different colors. But when I set 2 colours in getColor( ) , it mixes both the colours by default and gives a purple color to both the stacks of a single bar.

private int[] getColors() {

        int stacksize = 2;

        // have as many colors as stack-values per entry
        int[] colors = new int[stacksize];
        int MATERIAL_COLORS[]=new int[2];
        MATERIAL_COLORS[0]=R.color.spec5;   //orange
        MATERIAL_COLORS[1]=R.color.spec1;  //green

        // MATERIAL_COLORS[2]=R.color.spec5;

        for (int i = 0; i < 2; i++) {
            colors[i] = MATERIAL_COLORS[i];
        }

        return colors;
    }

**Comment by PhilJay** [comment]
Not sure what you mean but I guess you could solve this using two datasets.
