### ISSUE TITLE
extra space between the columns and signatures in BarChart

### ISSUE THREAD

**Issue by IvanSyabro** [PhilJay/MPAndroidChart#2010]
![image](https://cloud.githubusercontent.com/assets/20424848/16776930/4020e5aa-4870-11e6-8540-4049d99e76e6.png)

**Comment by IvanSyabro** [comment]
How remove this space?

**Comment by shubhapp** [comment]
set minimum value for axis 
`YAxis leftAxis = chart.getAxisLeft();
  leftAxis.setAxisMinValue(0);`

**Comment by IvanSyabro** [comment]
M
13 июля 2016 г. 8:10 пользователь "Subham Tyagi" <notifications@github.com>
написаNotepad
