### ISSUE TITLE
BaseEntry.mData is not available in AxisBase.getFormattedLabel()

### ISSUE THREAD

**Issue by literakl** [PhilJay/MPAndroidChart#2011]
I want to format a date in an X axis. I found DayAxisValueFormatter that passes simple day index. Originally I thought I will pass miliseconds for X, parse it to a date and format it - big fail. Then I realized that Entry has another free form argument. So I used the index concept and passed the date in it:

values.add(new Entry(days, value, date));

but AxisValueFormatter has following method where a float is passed:

public String getFormattedValue(float value, AxisBase axis)

I went through the library and even AxisBase does not hold Entries but float values.

Ok, I know a workaround - pass starting date to DayAxisValueFormatter as argument. But would you consider passing mValue down the stack to axis formatter?This would allow generic purpose formatters. How is this mValue used?

**Comment by PhilJay** [comment]
The axis has nothing to do with entires of type `Entry`. The "mEntries" field just refers to the labels of the axis.

**Comment by literakl** [comment]
Ok. I have successfully created flexible DayAxisValueFormatter. It takes startingDate as an constructor argument and it expects dataSet containig number of days since startingDate. Pseudocode

fetch data
startingDate = find oldest date
formatter = new  DayAxisValueFormatter(startingDate)
iterate data
x = compute difference between current date and startingDate
store new Entry(x, value);

Would you be interested in pull request?
