### ISSUE TITLE
Line legends go out of screen when many

### ISSUE THREAD

**Issue by pwireless** [PhilJay/MPAndroidChart#2012]
In a 5 in. screen I have 4 lines with 4 legends each of about 14 letters. The 4th legend goes out of screen.

A suggestion would be to wrap the "whole" legends and use an additional line if necessary.

Thanks

**Comment by PhilJay** [comment]
`legend.setWordWrapEnabled(true)` will cause the `Legend` to start a new line if too long.

**Comment by joaosardinha** [comment]
This didn't work for me, is this still the solution?
