### ISSUE TITLE
Set custom x-axis values for LineDataChart

### ISSUE THREAD

**Issue by korest** [PhilJay/MPAndroidChart#2013]
http://stackoverflow.com/questions/38337877/is-it-possible-to-set-custom-x-axis-values-in-mpandroidchart

As I understood it's not possible to achieve right now.  We can use value formatter but for me it looks like workaround.
Maybe you could add such functionality?

**Comment by PhilJay** [comment]
In the new version x-axis value formatting is possible. You did not specify your library version so I cannot say any more

https://github.com/PhilJay/MPAndroidChart/wiki/How-not-to-contribute
