### ISSUE TITLE
HorizontalBarChart draw custom Value

### ISSUE THREAD

**Issue by xixsuse** [PhilJay/MPAndroidChart#2014]
Is it possible to replace Value with custom Value? So it looks something like this:
![value](https://cloud.githubusercontent.com/assets/8171661/16799438/1ebc432e-48f1-11e6-8f65-6225cb677bdb.PNG)
![myvalue](https://cloud.githubusercontent.com/assets/8171661/16799483/53d4f3e4-48f1-11e6-950f-24fa4690ac8c.PNG)

**Comment by PhilJay** [comment]
This can be done with `MarkerView`. But in that case you need every bar to be highlighted.
