### ISSUE TITLE
Initial visible range different from setVisibleXRangeMaximum

### ISSUE THREAD

**Issue by plthatfunkymusic** [PhilJay/MPAndroidChart#2016]
Hi Phil

I'd like to set the visible X range to something large, but when the graph is first viewed to show a smaller range (as if the graph had been zoomed manually).  Is this possible?  For example - my data set has 187 values, and I'd like to show up to 50 maximum, but begin with only 8 on screen and allow the user to zoom from there.

Apologies if this is covered elsewhere.  

Thanks,
Simon

**Comment by evasyuk** [comment]
@plthatfunkymusic did you find solution?

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
