### ISSUE TITLE
Change LineChart circle colour based on value. 

### ISSUE THREAD

**Issue by daesu** [PhilJay/MPAndroidChart#2018]
Hi all, 

I'm trying to change the colour of a linechart circle datapoint based on a value. e.g. if the YValue is 1, color is blue, if the YValue is 2 color is green, 3 color is red etc. 

Whats the best way to go about doing this ?

**Comment by PhilJay** [comment]
I guess the best way to do this would be to check the value upon entry creation, and then add the desired color.
