### ISSUE TITLE
Highlight define height

### ISSUE THREAD

**Issue by rmoreira0** [PhilJay/MPAndroidChart#2019]
Hi!

Is possible to define the height of Highlight? Or making the height be the same as the curve?

I want to create something like this:

<img src="https://cloud.githubusercontent.com/assets/1692772/16843788/9e289d80-49da-11e6-97ee-67648902bf8b.jpg" width="250">

But the best i can is this:

<img src="https://cloud.githubusercontent.com/assets/1692772/16843791/a04d551a-49da-11e6-9793-bd82a2401724.jpg" width="250">

Thanks!

**Comment by PhilJay** [comment]
That's not possible by default, you will have to modify the library to achieve this.
