### ISSUE TITLE
issues when zooming and then graph jumping

### ISSUE THREAD

**Issue by aslamy** [PhilJay/MPAndroidChart#2020]
Hi !
When I zoom in on the graph then it pops up. This problem exists even in MPAndroidChart realtime chart demo.  I have recorded the problem and attach it like a zip file.

[vid_0657.mp4.zip](https://github.com/PhilJay/MPAndroidChart/files/364784/vid_0657.mp4.zip)

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
