### ISSUE TITLE
mpandroid draws an incomplete chart

### ISSUE THREAD

**Issue by farshidcivil** [PhilJay/MPAndroidChart#2023]
hi
I implemented a line chart. I wanna draw these data
`double[] y2={4151.07,	3375.21,	3354.56,	3333.87,		123.67,	84.89,	43.9,	0.34,	0.0};
            double[] x2={ 0.0,	1606.64,	1643.04,	1679.05,		1377.66,	1291.13,	1260.91, 1200.2, 547.3};`

but just the first five elements are drawn (I mean from y2[0] to y2[5] and x2[0] to x2[5])
this is my code : 

` double[] y2={4151.07,	3375.21,	3354.56,	3333.87,		123.67,	84.89,	43.9,	0.34,	0.0};
            double[] x2={ 0.0,	1606.64,	1643.04,	1679.05,		1377.66,	1291.13,	1260.91,  1200.2,      547.3};`

             ` for(int i=0;i<5;i++){
                float y=(float)y2[i] ;
                float x=(float)x2[i] ;
                yVals.add(new Entry( x, y));
            }
            LineDataSet sety=new LineDataSet(yVals,"yData");
            LineData data = new LineData(sety);
            lineChart.setData(data);
               XAxis xAxis = lineChart.getXAxis();
               lineChart.getAxisRight().setAxisMaxValue(4500);
               lineChart.getAxisLeft().setAxisMaxValue(4500);
               lineChart.getAxisRight().setAxisMinValue(-20);
               lineChart.getAxisLeft().setAxisMinValue(-20);
               xAxis.setAxisMaxValue(3500);
               xAxis.setAxisMinValue(-20);
               lineChart.animateX(3000);
               lineChart.setDragEnabled(true);
               lineChart.setScaleEnabled(true);`

I changed the data... and, amazing!... the app is crashed!!

` double[] y2={123.67,	84.89,	43.9,	0.34,	0.0}; //reduce the length of data
            double[] x2={1377.66,	1291.13,	1260.91, 1200.2, 547.3};

            for(int i=0;i<5;i++){
                float y=(float)y2[i] ;
                float x=(float)x2[i] ;
                yVals.add(new Entry( x, y));
                tv.setText(Double.toString(Pn_points.size()));
            }
            LineDataSet sety=new LineDataSet(yVals,"yData");
            LineData data = new LineData(sety);
            lineChart.setData(data);
             XAxis xAxis = lineChart.getXAxis();
               lineChart.animateX(3000);
               lineChart.setDragEnabled(true);
               lineChart.setScaleEnabled(true);`

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/How-not-to-contribute
