### ISSUE TITLE
v3.0.0

### ISSUE THREAD

**Issue by chenzhao4940** [PhilJay/MPAndroidChart#2025]
i want to know v3.0.0 how to show this 

 List<String> xValues = new ArrayList<>();
        for(int i = 0; i< 4; i++) {
            xValues.add("project"+ ArabicToChineseUtils.Arabic2Chinese(i));
        }

2..2.5 we can use this method
  PieData pieData = new PieData(xValues, pieDataSet);

but 3.0.0 no this method.

**Comment by PhilJay** [comment]
```java
xAxis.setValueFormatter(new AxisValueFormatter() {
            @Override
            public String getFormattedValue(float value, AxisBase axis) {
                return "anystringyouwant"; // "value" can be use as index
            }

            @Override
            public int getDecimalDigits() {
                return 0;
            }
        });
```
