### ISSUE TITLE
BarChartView y-values from Double to Int

### ISSUE THREAD

**Issue by nhantrivinh** [PhilJay/MPAndroidChart#2026]
I want to display my y values as Int instead of double. At the moment I use BarChartDataEntry and the only option is Double values. So I read something about NSFormatter, but I do not know how to implement it. Perhaps, it is the answer to my question.

**Comment by PhilJay** [comment]
Use the `ValueFormatter` interface in combination with `NSFormatter`. There are plenty of examples in the demo project.

Here is how to use `NSFormatter`: http://supereasyapps.com/blog/2016/2/8/how-to-use-nsnumberformatter-in-swift-to-make-currency-numbers-easy-to-read
