### ISSUE TITLE
Half pie chart draws on half view.

### ISSUE THREAD

**Issue by WimSchuiteman** [PhilJay/MPAndroidChart#2027]
Hi
I my app, I display a half Pie chart. No is the problem that the chart not resize to the view height.
![screenshot_20160715-132301](https://cloud.githubusercontent.com/assets/19692689/16872808/a1f59020-4a8f-11e6-9fa8-09193d21e150.png)

**Comment by PhilJay** [comment]
That is an issue that is not really resolved yet, see 

However, there is a workaround. See: #1755 

 - https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/HalfPieChartActivity.java#L122-L133
