### ISSUE TITLE
XAxis Label rendering issues when there are exactly 2 entries.

### ISSUE THREAD

**Issue by Praveen2106** [PhilJay/MPAndroidChart#2030]
Hi PhilJay,
When there are exactly 2 entries, XAxis rendering is not proper. Corresponding xAxis.mEntries[] is {0.0, 0.2, 0.4, 0.6, 0.8}. If the count is greater than 2, it is rendered properly. Please help.  

![image](https://cloud.githubusercontent.com/assets/8241455/16901488/47c58e86-4c63-11e6-8882-6eb0e79955bc.png)

PS: Using AxisValueFormatter over XAxis. I've never set X values as any one of them in the array. 
Further debugging, i found mAxis.mEntries.length is Zero in computeAxisValues() of AxisRenderer.

**Comment by PhilJay** [comment]
Library version?

**Comment by Praveen2106** [comment]
3.0.0 Beta

**Comment by Praveen2106** [comment]
3.0.0 Beta

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
