### ISSUE TITLE
How to remove the Description-"No chart data available"??

### ISSUE THREAD

**Issue by samarth220194** [PhilJay/MPAndroidChart#2039]
![device-2016-07-19-162922](https://cloud.githubusercontent.com/assets/17960987/16947666/fddd5ac6-4dcd-11e6-97c9-4fe62e84f00a.png)

Whenever i load my page on my phone then initially this line is shown on the page then the chart data is loaded.How to remove this line-"No chart data available".
I have tried using setNoDataTextDescription(""),but it is not working.

**Comment by PhilJay** [comment]
`char. setNoDataText("")`

**Comment by samarth220194** [comment]
[I have used this command .But it is not working.
This is my code  for the chart-
` private void plotchart(String s[],float[] f1){
        chart.setTouchEnabled(true);
        chart.setDragEnabled(true);
        chart.setScaleEnabled(true);
        chart.setPinchZoom(true);
//        chart.setGridBackgroundColor(Color.rgb(30, 46, 141));
        chart.setDrawGridBackground(false);
        chart.getAxisRight().setEnabled(false);
        chart.setDrawMarkerViews(true);
        chart.setViewPortOffsets(0f, 0f, 0f, 0f);


       // chart.setVisibleXRangeMaximum(4);

        ArrayList<String> xVals=new ArrayList<String>();
        for(int i=0;i<s.length;i++){
            xVals.add(s[i]);
        }
        chart.getLegend().setEnabled(false);

        XAxis x = chart.getXAxis();
        x.setEnabled(true);
        x.setDrawGridLines(false);
        x.setPosition(XAxis.XAxisPosition.BOTTOM_INSIDE);
        x.setTextColor(Color.argb(255, 128, 128, 255));
        x.isDrawLabelsEnabled();
        x.setAxisLineColor(Color.BLACK);
        x.setSpaceBetweenLabels(9);
        x.setAvoidFirstLastClipping(true);
        x.setXOffset(4f);


        YAxis y = chart.getAxisLeft();
        y.setValueFormatter(new MyYAxisFormatter());
        y.setAxisLineColor(Color.BLACK);
        y.setTextColor(Color.BLACK);
        y.setEnabled(true);
        y.setAxisLineColor(Color.argb(255, 128, 128, 255));
        y.setPosition(YAxis.YAxisLabelPosition.INSIDE_CHART);
        y.setDrawGridLines(false);
        y.setLabelCount(5, true);
        y.setGridColor(Color.argb(255, 128, 128, 255));
        y.setDrawZeroLine(false);
        y.setDrawLimitLinesBehindData(true);
        y.setDrawGridLines(true);
        y.setDrawLimitLinesBehindData(true);
        y.setTextColor(Color.argb(255, 128, 128, 255));
        y.setYOffset(6f);
        ArrayList<com.github.mikephil.charting.data.Entry> entries= new ArrayList<>();
        for (int i = 0; i < f1.length; i++) {
             entries.add(new com.github.mikephil.charting.data.Entry(f1[i], i));
        }




        LineDataSet dataset = new LineDataSet(entries, "");
        dataset.isDrawCirclesEnabled();
        dataset.setCircleRadius(0f);
        dataset.setDrawFilled(true);
        dataset.setFillColor(Color.rgb(0, 0, 0));
        dataset.setLineWidth(0.2f);
        dataset.setValueTextSize(0f);

        dataset.setColor(Color.rgb(0, 0, 0));
       
    
        LineData data = new LineData(xVals, dataset);
        MymarkerView mv =new MymarkerView(this,R.layout.custom_marker_view,xVals);

        chart.setMarkerView(mv);

        chart.setData(data);
        chart.setDescription("");
        chart.setNoDataText("");
        chart.setNoDataTextDescription("");
        chart.notifyDataSetChanged();
        chart.invalidate();
    }`

**Comment by miladheydari** [comment]
@PhilJay  how change text color for no data text???

**Comment by jolabti** [comment]
I have this same issue, in my real device the chart cannot be shown and the output is "No chart data avaliabe", can someone give me the advices for this issue , please...?

Thanks before...

**Comment by davpardom** [comment]
@jolabti maybe you're not in the UI thread. I had the same issue but it works when I call setNoDataText in UI thread.

Regards.

**Comment by anilthummar** [comment]
Hiii  **PhilJay**

char. setNoDataText("")

Its working for me Thanks for that.

**Comment by Winghin2517** [comment]
You can set the textcolor for the noDataText by using the following code:

            lineChart.setNoDataTextColor(color);

**Comment by anilthummar** [comment]
Hii 

can we set text in rounded way like clockwise (curve text set  as per slice )

**Comment by patzu** [comment]
Why setting `char. setNoDataText("")`  is not working for me?
