### ISSUE TITLE
barDataSet.setBarSpacePercent(...) not compiling

### ISSUE THREAD

**Issue by Pointy-Hat** [PhilJay/MPAndroidChart#2046]
I have the following code
```
  BarDataSet dataSet= new BarDataSet(data,label);
        dataSet.setBarSpacePercent(40f);
```
and it does not want to compile the setBarSpacePercent (shows red in Android Studio).
Does the new version support some other way to set spacing between the bars?

**Comment by WesleyHunt** [comment]
Same problem here, setBarSpacePercent is unavailable.

**Comment by Pointy-Hat** [comment]
Apparently there is some other way to do it in the new version. I couldn't find it in the documentation yet, though.

**Comment by WesleyHunt** [comment]
I actually found it last evening, it is not documented and I haven't really figured out how the spacing ratio works for the numbers but if you look in the HorizontalBarChartActivity (download the project and run it, I wish I did sooner) there is:

  float spaceForBar = 10f;
        for (int i = 0; i < count; i++) {
            float val = (float) (Math.random() * range);
            yVals1.add(new BarEntry(i * spaceForBar, val));
        }


The key part being that the BarEntry is where space is made. If you simply add the int's in order in that first variable from 0 to Count there will be no spaces. I'll add more concrete info as I find it.

**Comment by WesleyHunt** [comment]
setting spaceForBar to 19f seems(by visual inspection) to produce spacing that is the same width of the bar for any given number of bars

**Comment by antohama** [comment]
Hi Wesley,
I assume you are using v.3+ of the lib. 
Then please use
```
BarData barData = new BarData(dataSet);
barData.setBarWidth(0.7f);
```
instead of 
`dataSet.setBarSpacePercent(40f);`

**Comment by PhilJay** [comment]
That is correct, can also be found [here](https://github.com/PhilJay/MPAndroidChart/wiki/Setting-Data#barchart) as part of the documentation.
