### ISSUE TITLE
'com.github.PhilJay:MPAndroidChart:v3.0.0-beta1' have a problem

### ISSUE THREAD

**Issue by newbigman** [PhilJay/MPAndroidChart#2049]
the Legend can't show . 
use example:
  maven { url "https://jitpack.io" }
 compile 'com.github.PhilJay:MPAndroidChart:v3.0.0-beta1'

**Comment by newbigman** [comment]
compile 'com.github.PhilJay:MPAndroidChart:v3.0.0-beta' 
it is can show

**Comment by PhilJay** [comment]
already fixed
