### ISSUE TITLE
How can i set fixed values on y-axis ????

### ISSUE THREAD

**Issue by jzafrilla** [PhilJay/MPAndroidChart#205]
Hi all!
I would like to set fixed values (labels) on y-axis. For example, from 0 to 30 and display always this range. Can i do that? I'm looking into library code, but i have no idea how to do this.

Thanks in advance!

**Comment by ranj27** [comment]
I do not see this method public void setYRange(float minY, float maxY, boolean invalidate) in chart class

I am using library version mpandroidchartlibrary-2-1-4

**Comment by Utsav2** [comment]
I don't see it either

**Comment by tejkoorapati** [comment]
I too cannot see this function on an object of type LineChart.

**Comment by alaurila** [comment]
For linechart you set it to axises, like this (left and/or right):
```
lineChart.getAxisLeft().setAxisMaxValue(100f);
lineChart.getAxisLeft().setAxisMinValue(0f);
```

**Comment by carlosughini** [comment]
I used this:

YAxis y = mChart.getAxisLeft();
        y.setLabelCount(5);
        y.setAxisMaxValue(100);
        y.setAxisMinValue(20);

So, will make this:

20 - 40 - 60 - 80 - 100

**Comment by johnandersonUJ** [comment]
i am currently using seek bars to change the values on the radar chart but the axis keeps resizing, how do i make it that it just has a standard range of 0 - 100 in intervals of 10.
