### ISSUE TITLE
LineChart HORIZONTAL_BEZIER DrawFilled() Problem

### ISSUE THREAD

**Issue by ITServicesAM** [PhilJay/MPAndroidChart#2051]
Hello Phil,

at first nice library, good job :)!

I Have a LineChart with data that is a date on the x-axis and a weight on the y-axis. If I set the mode to LINEAR all is fine and the fill looks good, but if I turn to HORIZONTAL_BEZIER or CUBIC_BEZIER the fill gets broken.

Here two Screenshots to demonstrate this:
**Mode: LINEAR:**
![linear](https://cloud.githubusercontent.com/assets/4500322/17029388/5543632a-4f6b-11e6-9178-42962c2cad7c.png)

**Mode: HORIZONTAL_BEZIER:**
![horizontal_bezier](https://cloud.githubusercontent.com/assets/4500322/17029408/63e57d82-4f6b-11e6-9b1c-1f3807fe3f98.png)

**Code:**

`List<BodyData> allData = bodyDataDao.loadAll();
        ArrayList<Entry> valsGewichtData = new ArrayList<>(allData.size());
        for (BodyData bodyData : allData) {
            valsGewichtData.add(new Entry((float) bodyData.getDate().getTime(), (float) bodyData.getGewicht()));
        }

        LineDataSet lineDataSet = new LineDataSet(valsGewichtData, "lineDataSet");
        lineDataSet.setColor(getResources().getColor(R.color.colorAccent));
        lineDataSet.setFillColor(getResources().getColor(R.color.colorAccent));
        lineDataSet.setFillAlpha(255);
        lineDataSet.setFillFormatter(new MyFillFormatter());
        lineDataSet.setDrawFilled(true);
        lineDataSet.setDrawValues(false);
        lineDataSet.setDrawCircles(false);
        lineDataSet.setCircleRadius(4f);
        lineDataSet.setMode(LineDataSet.Mode.LINEAR);

        LineData lineData = new LineData(lineDataSet);

        lineChart.setData(lineData);
        lineChart.setMarkerView(new MyMarkerView(this, R.layout.my_marker_view));
        lineChart.setDrawGridBackground(false);
        lineChart.setDescription("");
        lineChart.setDragEnabled(true);
        lineChart.setScaleEnabled(true);
        lineChart.setPinchZoom(true);

        XAxis xAxis = lineChart.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.TOP);
        xAxis.setDrawAxisLine(false);
        xAxis.setDrawGridLines(false);
        xAxis.setGranularity(TimeUnit.MILLISECONDS.convert(1, TimeUnit.DAYS)); // one day in millis
        xAxis.setValueFormatter(new AxisValueFormatter() {

            private FormattedStringCache.Generic<Long, Date> mFormattedStringCache = new FormattedStringCache.Generic<>(new SimpleDateFormat("dd.MM.yy"));

            @Override
            public String getFormattedValue(float value, AxisBase axis) {
                Long v = (long) value;
                return mFormattedStringCache.getFormattedValue(new Date(v), v);
            }

            @Override
            public int getDecimalDigits() {
                return 0;
            }
        });

        lineChart.getAxisRight().setEnabled(false);
        YAxis yAxis = lineChart.getAxisLeft();
        yAxis.setDrawGridLines(false);
        lineChart.invalidate();

public class MyFillFormatter implements FillFormatter {

    @Override
    public float getFillLinePosition(ILineDataSet dataSet, LineDataProvider dataProvider) {
        float fillMin = 0f;
        float chartMaxY = dataProvider.getYChartMax();
        float chartMinY = dataProvider.getYChartMin();

        LineData data = dataProvider.getLineData();

        if (dataSet.getYMax() > 0 && dataSet.getYMin() < 0) {
            fillMin = 0f;
        } else {

            float max, min;

            if (data.getYMax() > 0)
                max = 0f;
            else
                max = chartMaxY;
            if (data.getYMin() < 0)
                min = 0f;
            else
                min = chartMinY;

            fillMin = dataSet.getYMin() >= 0 ? min : max;
        }

        return fillMin;
    }
}`

I hope someone can help me here :) Thx

**Comment by ITServicesAM** [comment]
No one on this issue here?

**Comment by ITServicesAM** [comment]
I Think I made it. The x-Values as dates in theire long presentation are not good. I switched to x-Values as 0f, 1f,...5f and so on. Then with a Valueformatter I printed my dates. So this issue could be closed ;)

**Comment by Edonfreiner** [comment]
Hey @ITServicesAM how exactly did you solve this issue, I am having the same problem, thanks
