### ISSUE TITLE
i can not find v3.0.0-beta1

### ISSUE THREAD

**Issue by SeongyongChang** [PhilJay/MPAndroidChart#2057]
i added on app gradle file the library and when i sync, android studio can not find file.
other library such as gson, or other library from github works fine.
is there any problem in mpandroidchar library?
thank you

**Comment by lschuetze** [comment]
Did you added `jitpack.io` to your repositories as stated in the readme?

```
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}
```
