### ISSUE TITLE
Setting Data Wiki , wrong code

### ISSUE THREAD

**Issue by seppemarotta** [PhilJay/MPAndroidChart#2061]
https://github.com/PhilJay/MPAndroidChart/wiki/Setting-Data

The constructor has changed , this line is not working anymore.

    ArrayList<String> xVals = new ArrayList<String>();
    xVals.add("1.Q"); xVals.add("2.Q"); xVals.add("3.Q"); xVals.add("4.Q"); 

    LineData data = new LineData(xVals, dataSets);
    mLineChart.setData(data);
    mLineChart.invalidate(); // refresh`

**Comment by PhilJay** [comment]
The [setting data wiki](https://github.com/PhilJay/MPAndroidChart/wiki/Setting-Data) has now been updated to fit the v3.0.0 release.
