### ISSUE TITLE
Legend not displaying first time graph is created

### ISSUE THREAD

**Issue by xainbutt** [PhilJay/MPAndroidChart#2065]
The legend is not displayed properly the first time the graph is created, but when i rotate the screen its shows up.. i am using latest version and cant seem to solve it...
@PhilJay

**Comment by Praveen2106** [comment]
@PhilJay, When used Legend.setPosition(Legend.LegendPosition.RIGHT_OF_CHART) for PieChart, it doesn't work for the first draw. It is drawn over the slices.

**Comment by leveme** [comment]
I also met with this problem.

**Comment by Sevenupboy** [comment]
@leveme but the legend still no display ...

**Comment by Sevenupboy** [comment]
i met this when i use LineChart 
` legendCo2.setForm(Legend.LegendForm.SQUARE);
        legendCo2.setTextSize(11f);
        legendCo2.setTextColor(Color.GRAY);`

**Comment by Sevenupboy** [comment]
u can see #2064 , maybe can solve the problem u met

**Comment by PhilJay** [comment]
Related to #1969, stable release containing the fix will be out soon.
