### ISSUE TITLE
MarkerView Beyond the screen

### ISSUE THREAD

**Issue by imyyq-star** [PhilJay/MPAndroidChart#2068]
Hello, I use the MP, I found MarkerView line graph edges disappear off the screen, as shown in

![image](https://cloud.githubusercontent.com/assets/11580876/17090082/735c50a0-525f-11e6-8555-61ebaba38066.png)

Forgive my English is not good

**Comment by imyyq-star** [comment]
No one has this problem？？

**Comment by PhilJay** [comment]
In the new release that will be out soon, this problem will no longer be present when extending the `MarkerView` class. In addition to that, marker positions can be adjusted by overriding the `getOffsetForDrawingAtPos(...)` method of the `IMarker` interface.

[IMarker documentation](https://github.com/PhilJay/MPAndroidChart/wiki/IMarker-Interface).

**Comment by alexkrolinfinum** [comment]
@PhilJay still not work for the right edge of the LineChart 😕

**Comment by alexkrolinfinum** [comment]
Ok, I've figured it out. It wasn't working because I didn't set the chart instance into my marker view. I think this should be mentioned in [MarkerView documentation](https://github.com/PhilJay/MPAndroidChart/wiki/MarkerView)

**Comment by YangQiRen** [comment]
The following URL can give you a reference：
https://www.jianshu.com/p/ca0246f5f1fb

**Comment by david-alejandro-reyes-milian** [comment]
as @alexkrolinfinum mentioned it's required to do [kotlin]:
`val marker = YourMarkerView(chart.context, R.layout.chart_hint).apply { chartView = chart }`

the relevant part: `.apply { chartView = chart }`. When doing this, the lib will actually protect the visibility of your hint MarkerView.

Guys please add to docs, 2h behind this here :(
