### ISSUE TITLE
First Dataset Using Second's Alpha Value in Line Chart

### ISSUE THREAD

**Issue by jngr** [PhilJay/MPAndroidChart#2071]
I noticed some odd behavior when using dual line charts. I wanted to have one data series shown as a line and another data series of discrete values with only the data points plotted. Idea was to make the second graph line invisible setting its alpha value to 0. 
- start off e.g. with the dual line chart sample
- use ARGB values for the colors of both graphs
- first graph's mode set to LINEAR
- make the second graph disappear by setting its alpha value to 0
- change first graph's mode to HORIZONTAL_BEZIER or CUBIC_BEZIER
- the first graph and its fill disappear

Playing with different alpha values, it turns out that the first graph's color and fill both use the second graph's alpha value if HORIZONTAL_BEZIER or CUBIC_BEZIER mode are selected. ´
(This is using MPAndrroidChart version 3.0.0 beta.)

**Modified Code from the LineChartActivity2 sample:**

```
            set1 = new LineDataSet(yVals1, "DataSet 1");
            set1.setAxisDependency(AxisDependency.LEFT);
            //set1.setColor(ColorTemplate.getHoloBlue());
            set1.setColor(0xffff0000);
            set1.setCircleColor(Color.WHITE);
            set1.setLineWidth(2f);
            set1.setCircleRadius(3f);
            set1.setFillAlpha(65);
            set1.setDrawFilled(true);
            set1.setMode(LineDataSet.Mode.HORIZONTAL_BEZIER);
            set1.setFillColor(ColorTemplate.getHoloBlue());
            set1.setHighLightColor(Color.rgb(244, 117, 117));
            set1.setDrawCircleHole(false);

            // create a dataset and give it a type
            set2 = new LineDataSet(yVals2, "DataSet 2");
            set2.setAxisDependency(AxisDependency.RIGHT);
            //set2.setColor(Color.RED);
            set2.setColor(0x0000ff00);
            set2.setCircleColor(Color.WHITE);
            set2.setLineWidth(2f);
            set2.setMode(LineDataSet.Mode.HORIZONTAL_BEZIER);
            set2.setCircleRadius(3f);
            set2.setFillAlpha(65);
            set2.setFillColor(Color.RED);
            set2.setDrawCircleHole(false);
            set2.setHighLightColor(Color.rgb(244, 117, 117));
```

**Comment by RobertZagorski** [comment]
Probably does not happen anymore. I can't reproduce it.

**Comment by almic** [comment]
Hey there! This issue is fairly old, and may no longer apply to the current library version. I'm closing this in order to clean up the issue tracker. The repository has been inactive for a long time and old issues may have existing answers or are no longer valid.

I've been working diligently to get to as many issues as I can, but I can no longer spend time writing a unique answer to each issue. This is especially true if that issue may no longer be applicable. If you think this was done by mistake, please search through all `open` and `closed` issues first, and then create a new one using the templates.

This is a copied and pasted response, and has been put on many other issues. So please, don't take this personally.

**Comment by jngr** [comment]
Agreed. Checked it and confirm that the issue no longer exists.

**Comment by calulelalu** [comment]
You have to explicitly specify the FillFormatter and the fillAlpha for both the datasets! This was my solution to the issue.

**Comment by rvenk** [comment]
This still seems like an issue in v3.1.0. I think the problem is that `LineChartRenderer` calls `c.drawBitmap` with the `mRenderPaint` , which still contains the alpha from the last drawn dataset.

**Comment by qinidea** [comment]
> This still seems like an issue in v3.1.0. I think the problem is that `LineChartRenderer` calls `c.drawBitmap` with the `mRenderPaint` , which still contains the alpha from the last drawn dataset.

Agree.
I fixed and made a pull request.
