### ISSUE TITLE
I want to set custom values on x axis

### ISSUE THREAD

**Issue by Siddhant-Dawaibox** [PhilJay/MPAndroidChart#2072]
I am using this library and I want to plot different values of different days on x axis, but the problem is the setAxisMaxValue and setAxisMinValue takes float and calculate the range of values on x axis. Here, how can I add custom range with custom values like if I want to add weeks as a value and the range should be one week means if i start from this week than next value on x axis will be next to next week value. Can you help me out on this and is there any way to do that

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/The-AxisValueFormatter-interface

**Comment by Siddhant-Dawaibox** [comment]
Thanks for your answer but I have got into a unique problem. I have two different arraylist one for x axis values and one arraylist of entry so data can be drawn in chart. Now here comes the problem suppose there are 10 values in x axis arraylist and I want that the value format should be the starting value in x axis arraylist till the last. But what is happening is if i have less data in entry arraylist and 10 data in x axis arraylist the x axis formatter skips that x axis value that should be print in x axis and shows the next value on which the value of entry its getting . I will share you the code you can check.

final ArrayList<Entry> valueSet1 = new ArrayList<>();
final ArrayList<String> xVals = new ArrayList<String>();
                        valueSet1.clear();
                        xVals.clear();
                        getActivity().runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                SimpleDateFormat date = new SimpleDateFormat("dd-MMM");
                                Date d = new Date();
                                Calendar cal = Calendar.getInstance();
                                cal.setTime(d); // convert your date to Calendar object
                                cal.add(Calendar.DATE, -29);
                                int k = 0;
                                for (int i = 0; i < 30; i++) {
                                    d = cal.getTime(); // again get back your date object
                                    String newDate = String.valueOf(date.format(d));
                                    xVals.add(newDate);
                                    k++;
                                    Double temp = 0.0;
                                    int count = 0;
                                    for (int j = 0; j < value.size(); j++) {
                                        SimpleDateFormat date1 = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                                        Date d1 = new Date();
                                        try {
                                            d1 = date1.parse(value.get(j).getDate());
                                        } catch (ParseException e) {
                                            e.printStackTrace();
                                        }
                                        if (newDate.equalsIgnoreCase(date.format(d1))) {
                                            if (value.get(j).getValue() != null && !value.get(j).getValue().isEmpty() &&
                                                    !value.get(j).getValue().matches("null")) {
                                                temp += Double.parseDouble(value.get(j).getValue());
                                                count++;
                                            }

                                        }
                                    }
                                    float answer = (float) (temp / count);
                                    if (count > 0) {
                                    valueSet1.add(new Entry(answer, i));
                                    }
                                    cal.add(Calendar.DATE, 1);
                                }
                                Log.d("xvals data ", String.valueOf(xVals.size()));
                                Log.d("xvals data ", String.valueOf(valueSet1.size()));
                            }
                        });

and I am setting the formatter like this

xAxis.setValueFormatter(new AxisValueFormatter() {
                            @Override
                            public String getFormattedValue(float value, AxisBase axis) {
                                return String.valueOf(xVals.get((int) value));
                            }

                            @Override
                            public int getDecimalDigits() {
                                return 0;
                            }
                        });

Please help me out in this. 
Thanks
