### ISSUE TITLE
I get a negative NegativeArraySizeException at generateTransformedValuesScatter

### ISSUE THREAD

**Issue by KIC** [PhilJay/MPAndroidChart#2074]
This is the data I pass along:

```
DataSet, label: Equities, entries: 22
Entry, x: 2.4622053E-4 y (sum): -2.5103273E-4 Entry, x: 1.4264166E-4 y (sum): 1.06562635E-4 Entry, x: 1.0069651E-4 y (sum): 2.2954303E-4 Entry, x: 3.3205854E-6 y (sum): 6.520928E-5 Entry, x: 2.1512537E-4 y (sum): -1.926993E-4 Entry, x: 1.4847405E-4 y (sum): -1.5883509E-4 Entry, x: 2.8459038E-4 y (sum): 1.1068245E-4 Entry, x: 1.3150444E-4 y (sum): 1.4332784E-4 Entry, x: 7.719888E-5 y (sum): 1.6962597E-4 Entry, x: 1.3707434E-4 y (sum): 1.7498349E-4 Entry, x: 2.5035875E-4 y (sum): 3.8239497E-4 Entry, x: 1.0254524E-4 y (sum): 1.468406E-4 Entry, x: 1.5425305E-4 y (sum): 4.278698E-5 Entry, x: 1.2035284E-4 y (sum): 3.2309844E-4 Entry, x: 8.58292E-5 y (sum): 4.6827746E-4 Entry, x: 8.473067E-5 y (sum): 4.3495893E-4 Entry, x: 3.0464705E-4 y (sum): -2.1406553E-4 Entry, x: 2.2885398E-4 y (sum): -1.1195301E-4 Entry, x: 1.5392534E-4 y (sum): 4.011409E-5 Entry, x: 2.240534E-4 y (sum): 1.1159029E-5 Entry, x: 2.7432045E-4 y (sum): -1.8261799E-5 Entry, x: 4.9744867E-5 y (sum): -1.1376083E-4 
```

And I get a NegativeArraySizeException:

```
java.lang.NegativeArraySizeException: -10
                                                                                        at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesScatter(Transformer.java:110)
                                                                                        at com.github.mikephil.charting.renderer.ScatterChartRenderer.drawValues(ScatterChartRenderer.java:106)
                                                                                        at com.github.mikephil.charting.renderer.CombinedChartRenderer.drawValues(CombinedChartRenderer.java:95)
                                                                                        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:272)
                                                                                        at android.view.View.draw(View.java:15231)
                                                                                    
```
```
    public float[] generateTransformedValuesScatter(IScatterDataSet data, float phaseX,
                                                    float phaseY, int from, int to) {

        /// ------- interestingly i get a 17 for the from and an 11 for the to which is n fact negative.
        final int count = (int) ((to - from) * phaseX + 1) * 2;

        if(valuePointsForGenerateTransformedValuesScatter.length != count){
            valuePointsForGenerateTransformedValuesScatter = new float[count];
        }
        float[] valuePoints = valuePointsForGenerateTransformedValuesScatter;

        for (int j = 0; j < count; j += 2) {

            Entry e = data.getEntryForIndex(j / 2 + from);

            if (e != null) {
                valuePoints[j] = e.getX();
                valuePoints[j + 1] = e.getY() * phaseY;
            }else{
                valuePoints[j] = 0;
                valuePoints[j + 1] = 0;
            }
        }

        getValueToPixelMatrix().mapPoints(valuePoints);

        return valuePoints;
    }

```

I use the current/newest version from maven.

**Comment by ErfanThinker** [comment]
same here, I get this error

**Comment by KIC** [comment]
As a workaround try to sort the Entrties by x value like so: Collections.sort(entries, new EntryXComparator());

**Comment by ErfanThinker** [comment]
Thanks @KIC , I was really stuck and frozen, I didn't know what to do.

**Comment by PhilJay** [comment]
The answer of @KIC is correct. Entries need to be added sorted by their x-position. Otherwise unexpected behaviour might occur. I am aware this is not clearly stated in the documentation and will do some updating in that matter.

**Comment by PhilJay** [comment]
Documentation is now [updated](https://github.com/PhilJay/MPAndroidChart/wiki/Setting-Data#the-order-of-entries).

**Comment by AndroidBirdBoom** [comment]
thanks so much @KIC  your answer resolved my problem!

**Comment by f839903061** [comment]
thanks so much @KIC your answer resolved my problem !!!!!

**Comment by aguskoll** [comment]
. In version 2 I didn't have that problem. 
If all the entries need to be <float, float> maybe you can improve the library in the next version  and do the sort automatically ?

**Comment by pflammertsma** [comment]
This appears to be a much more complex issue than simply the order of entries. Implementing even the most basic line chart throws a NegativeArraySizeException in generateTransformedValuesLine().

In Kotlin:

        val tempVals = LinkedList<Entry>()
        val tempDataSet = LineDataSet(tempVals, "Temperature")

        tempVals.add(Entry(0f, 100000f))
        tempVals.add(Entry(1f, 140000f))
        tempVals.add(Entry(2f, 130000f))
        tempVals.add(Entry(3f, 100000f))

        val dataSets = ArrayList<ILineDataSet>()
        dataSets.add(tempDataSet)
        chart.data = LineData(dataSets)

Doing some basic debugging reveals that the actual problem lies in BarLineScatterCandleBubbleRenderer. Here, getLowestVisibleX() and getHighestVisibleX() are returning swapped values, such that locating the from and to entries through dataset.getEntryForXValue() is returning a range going from right to left.

As a result, LineChartRenderer invokes the transformer with the this right-to-left range, and ultimately Transformer.generateTransformedValuesLine() attempts to initialize an array of negative size.

**Comment by KennyGoers** [comment]
Same problem even though ordered, is there a work around?

**Comment by paamand** [comment]
I guess this issue should be reopened?

**Comment by noloman** [comment]
For me, it still crashes even if I'm using the `Collections.sort(entries, new EntryXComparator());`
Is there any workaround, or explanation?

**Comment by Krishnakant-android** [comment]
Thank you @KIC 
Its working for me code like below

Collections.sort(entries, new EntryXComparator());
LineDataSet thisSet = new LineDataSet(entries, "");

**Comment by FirstSpectr** [comment]
Hi, I'm init chart:
`        ScatterDataSet dataSet = new ScatterDataSet(dotSet, "dots");
        dataSet.setColor(Color.RED);
        dataSet.setScatterShape(ScatterChart.ScatterShape.CIRCLE);

        CombinedData data = new CombinedData();
        data.setData(new ScatterData(dataSet));
        data.setData(new LineData(gammaDataSet));
        chart.setData(data);`
and add new Entry dynamicly: 
`chart.getData().getScatterData().addEntry(new Entry(x, gamma),0);` 
How I can sort Entries after add?

**Comment by Krishnakant-android** [comment]
I think You should add all data into list  dynamically than short the data and pass to the addEntry().

**Comment by FirstSpectr** [comment]
> I think You should add all data into list dynamically than short the data and pass to the addEntry().

The data come from the user dot by dot

**Comment by SayyedHashimAkhtar** [comment]
In my case it turns out the reason was that in the previous version of the graph, we were creating a new entry with the followin: new Entry(value, index);

**Comment by SayyedHashimAkhtar** [comment]
In my case it turns out the reason was that in the previous version of the graph, we were creating a new entry with the following:

new Entry(value, index);

However, in the latest version of the library, you have to create an entry in reverse:

new Entry(index, value);

**Comment by KennyGoers** [comment]
I was having the same problem. If you set the X axis limits on a line graph the graph crashes with that error.

**Comment by mohammadJaliliTorkamani** [comment]
just call dataset.notifyDataSetChanged  right after you changed the values of your entry-list

**Comment by developerfromjokela** [comment]
`Collections.sort(entries, new EntryXComparator());` worked for me, thumbs up for that :+1:

**Comment by AdrianxSh** [comment]
> Collections.sort(entries, new EntryXComparator());

 also worked for me. Thanks, KIC.

**Comment by ajaygalagali** [comment]
I was facing issue, i found out that arrayList was empty before declaring dataset.

Before fix : 
`lineChart = findViewById(R.id.lineChart)
        lineChart.isDragEnabled = true
        lineChart.setScaleEnabled(false)
        arrayList = ArrayList()
        
        dataSetOne = LineDataSet(arrayList,"Data Set One")
        arrayList.add(Entry(1f,10f))
        arrayList.add(Entry(2f,60f))
        arrayList.add(Entry(3f,20f))
        arrayList.add(Entry(4f,50f))`

After fix:
`lineChart = findViewById(R.id.lineChart)
        lineChart.isDragEnabled = true
        lineChart.setScaleEnabled(false)
        arrayList = ArrayList()
        arrayList.add(Entry(1f,10f))
        arrayList.add(Entry(2f,60f))
        arrayList.add(Entry(3f,20f))
        arrayList.add(Entry(4f,50f))
        dataSetOne = LineDataSet(arrayList,"Data Set One")`

**Comment by ajaygalagali** [comment]
I was facing issue, i found out that arrayList was empty before declaring dataset.

Before fix:
```
lineChart = findViewById(R.id.lineChart)
        lineChart.isDragEnabled = true
        lineChart.setScaleEnabled(false)
        arrayList = ArrayList()

        dataSetOne = LineDataSet(arrayList,"Data Set One")

        arrayList.add(Entry(1f,10f))
        arrayList.add(Entry(2f,60f))
        arrayList.add(Entry(3f,20f))
        arrayList.add(Entry(4f,50f))
        
```

After fix:
```

lineChart = findViewById(R.id.lineChart)
        lineChart.isDragEnabled = true
        lineChart.setScaleEnabled(false)
        arrayList = ArrayList()
        arrayList.add(Entry(1f,10f))
        arrayList.add(Entry(2f,60f))
        arrayList.add(Entry(3f,20f))
        arrayList.add(Entry(4f,50f))
        dataSetOne = LineDataSet(arrayList,"Data Set One")

```

**Comment by PankajDandriyal** [comment]
> 
> 
> For me, it still crashes even if I'm using the `Collections.sort(entries, new EntryXComparator());`
> Is there any workaround, or explanation?

Did you find any solution @noloman

**Comment by ArcherEmiya05** [comment]
> 
> 
> As a workaround try to sort the Entries by x value like so: Collections.sort(entries, new EntryXComparator());

I tried this but no luck, may you please check my bug report [here](https://github.com/PhilJay/MPAndroidChart/issues/5103#issue-821359256)? It seems this still exist somewhat.

**Comment by kaskikas** [comment]
I figured out that LineData.addEntry(Entry e, int index) works fine while LineDataSet.addEntry() does not.

**Comment by Verkop** [comment]
This is a very unfortunate limitation as for some cases sorting the data by x coordinate is not possible (e.g. having x and y coordinates for a moving car and wanting it to be connected in the same order they were recorded so they are sorted by time).

At least the documentation should be updated to state that this limitation also applies to **ScatterPlot**. Currently it just states that data for **LineChart** must be sorted.

**Comment by rookielord** [comment]
> I figured out that LineData.addEntry(Entry e, int index) works fine while LineDataSet.addEntry() does not.

sometimes works sometimes doesn't.T_T|||

**Comment by natvar97** [comment]
Thanks @KIC your answer helped me

> As a workaround try to sort the Entries by x value like so: Collections.sort(entries, new EntryXComparator());

Thank you very much @KIC your answer helped me.

**Comment by simon-2022-22** [comment]
The first thing I want to say is that I'm not a pro in java, i only try to fix the problem when use MPAndroidChart.
My problem is descripted below.

I have several variants of exceptions. I have described the matches code variants below.

Exception error match the **Generate array 1**

> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.example.androidclient, PID: 8679
>     **java.lang.NegativeArraySizeException: -2**
>         at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:178)
>         at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:549)
>         at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:278)
>         at android.view.View.draw(View.java:14465)
>         at android.view.View.getDisplayList(View.java:13362)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1569)
>         at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1448)
>         at android.view.ViewRootImpl.draw(ViewRootImpl.java:2381)
>         at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2253)
>         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1883)
>         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
>         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
>         at android.view.Choreographer.doCallbacks(Choreographer.java:574)
>         at android.view.Choreographer.doFrame(Choreographer.java:544)
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
>         at android.os.Handler.handleCallback(Handler.java:733)
>         at android.os.Handler.dispatchMessage(Handler.java:95)
>         at android.os.Looper.loop(Looper.java:136)
>         at android.app.ActivityThread.main(ActivityThread.java:5017)
>         at java.lang.reflect.Method.invokeNative(Native Method)
>         at java.lang.reflect.Method.invoke(Method.java:515)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
>         at dalvik.system.NativeStart.main(Native Method)


Exception error match the **Generate Array 1**

> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.example.androidclient, PID: 9740
>     **java.lang.NegativeArraySizeException: -4**
>         at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:178)
>         at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:549)
>         at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:278)
>         at android.view.View.draw(View.java:14465)
>         at android.view.View.getDisplayList(View.java:13362)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1569)
>         at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1448)
>         at android.view.ViewRootImpl.draw(ViewRootImpl.java:2381)
>         at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2253)
>         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1883)
>         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
>         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
>         at android.view.Choreographer.doCallbacks(Choreographer.java:574)
>         at android.view.Choreographer.doFrame(Choreographer.java:544)
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
>         at android.os.Handler.handleCallback(Handler.java:733)
>         at android.os.Handler.dispatchMessage(Handler.java:95)
>         at android.os.Looper.loop(Looper.java:136)
>         at android.app.ActivityThread.main(ActivityThread.java:5017)
>         at java.lang.reflect.Method.invokeNative(Native Method)
>         at java.lang.reflect.Method.invoke(Method.java:515)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
>         at dalvik.system.NativeStart.main(Native Method)

Exception error match the **Generate array 2**

> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.example.androidclient, PID: 8130
>     **java.lang.NegativeArraySizeException: -4**
>         at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:178)
>         at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:549)
>         at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:278)
>         at android.view.View.draw(View.java:14465)
>         at android.view.View.getDisplayList(View.java:13362)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1569)
>         at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1448)
>         at android.view.ViewRootImpl.draw(ViewRootImpl.java:2381)
>         at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2253)
>         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1883)
>         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
>         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
>         at android.view.Choreographer.doCallbacks(Choreographer.java:574)
>         at android.view.Choreographer.doFrame(Choreographer.java:544)
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
>         at android.os.Handler.handleCallback(Handler.java:733)
>         at android.os.Handler.dispatchMessage(Handler.java:95)
>         at android.os.Looper.loop(Looper.java:136)
>         at android.app.ActivityThread.main(ActivityThread.java:5017)
>         at java.lang.reflect.Method.invokeNative(Native Method)
>         at java.lang.reflect.Method.invoke(Method.java:515)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
>         at dalvik.system.NativeStart.main(Native Method)


Exception error match the **Generate array 2**

> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.example.androidclient, PID: 8460
>     **java.lang.NegativeArraySizeException: -2**
>         at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:178)
>         at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:549)
>         at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:278)
>         at android.view.View.draw(View.java:14465)
>         at android.view.View.getDisplayList(View.java:13362)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>         at android.view.View.getDisplayList(View.java:13300)
>         at android.view.View.getDisplayList(View.java:13404)
>         at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1569)
>         at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1448)
>         at android.view.ViewRootImpl.draw(ViewRootImpl.java:2381)
>         at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2253)
>         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1883)
>         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
>         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
>         at android.view.Choreographer.doCallbacks(Choreographer.java:574)
>         at android.view.Choreographer.doFrame(Choreographer.java:544)
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
>         at android.os.Handler.handleCallback(Handler.java:733)
>         at android.os.Handler.dispatchMessage(Handler.java:95)
>         at android.os.Looper.loop(Looper.java:136)
>         at android.app.ActivityThread.main(ActivityThread.java:5017)
>         at java.lang.reflect.Method.invokeNative(Native Method)
>         at java.lang.reflect.Method.invoke(Method.java:515)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
>         at dalvik.system.NativeStart.main(Native Method)

My code fragments below.

I use two variants of generate data. 
**Generate array 1:** (array)
```
public static float[][] generateRandomGraph() {
            float min=-5.0f, max=10.0f;
            int colCount=2,rowCount=5;
            float[][] randomNumbers = new float[rowCount][colCount];

            Random random = new Random();
    for (int i = 0; i < rowCount; i++) {
        for (int j = 0; j < colCount; j++) {
            float randomNumber;
            try {
                do {
                    double gaussianValue = random.nextGaussian();
                    randomNumber = (float) (min + (gaussianValue + 1) * 0.1f * (max - min));
                } while (randomNumber < min && randomNumber < max);
                randomNumbers[i][j] = randomNumber;
            } catch (NegativeArraySizeException e) {
                logger.severe("Error: " + e.getMessage());
                logger.severe("Stack:");
                for (StackTraceElement element : e.getStackTrace()) {
                    logger.severe(element.toString());
                }
                System.out.printf("rowCount is: %d \n", i);
                System.out.printf("colCount is: %d \n", j);
                System.out.println("Array size is: "+randomNumbers.length );
            }
        }
    }
    return randomNumbers;
        }
```

**Generate array 2:** (this is not array, only one float number)
```
 public static float randomGraph() {
            float min = 1.0f;
            float max = 10.0f;
            Random random = new Random();
            float randomNumber;

            do {
                double gaussianValue = random.nextGaussian();
                randomNumber = (float) (min + (gaussianValue + 1) * 0.5f * (max - min));
            } while (randomNumber > min && randomNumber < max);
            return randomNumber;
        }
```

**Code to update chart & paste data for chart with Generate array 1:**
```
upDateChart.setOnClickListener(new View.OnClickListener(){
            @Override
        public void onClick(View v){

                try {
                    float randomnumbers[][] = YourData.generateRandomGraph();
                    System.out.println(Arrays.deepToString(randomnumbers));
                    System.out.println("RED length: "+randomnumbers.length);
                    System.out.println("\n");
                    System.out.println("RED \n");
                    YourData[] DataObjects = new YourData[]{
                            new YourData(randomnumbers[0][0], randomnumbers[0][1]),
                            new YourData(randomnumbers[1][0], randomnumbers[1][1]),
                            new YourData(randomnumbers[2][0], randomnumbers[2][1]),
                            new YourData(randomnumbers[3][0], randomnumbers[3][1]),
                            new YourData(randomnumbers[4][0], randomnumbers[4][1])
                    };


                    float randomnumbers1[][] = YourData.generateRandomGraph();
/*println code*/
                    YourData[] DataObjects1 = new YourData[]{
                            new YourData(randomnumbers1[0][0], randomnumbers1[0][1]),
                            new YourData(randomnumbers1[1][0], randomnumbers1[1][1]),
                            new YourData(randomnumbers1[2][0], randomnumbers1[2][1]),
                            new YourData(randomnumbers1[3][0], randomnumbers1[3][1]),
                            new YourData(randomnumbers1[4][0], randomnumbers1[4][1])
                    };

                    float randomnumbers2[][] = YourData.generateRandomGraph();
/*println code*/
                    YourData[] DataObjects2 = new YourData[]{
                            new YourData(randomnumbers2[0][0], randomnumbers2[0][1]),
                            new YourData(randomnumbers2[1][0], randomnumbers2[1][1]),
                            new YourData(randomnumbers2[2][0], randomnumbers2[2][1]),
                            new YourData(randomnumbers2[3][0], randomnumbers2[3][1]),
                            new YourData(randomnumbers2[4][0], randomnumbers2[4][1])
                    };

                    List<Entry> points = new ArrayList<Entry>();
                    for (int i = 0; i < DataObjects.length; i++) {
                        float xValue = DataObjects[i].getXValue(); 
                        float yValue = DataObjects[i].getYValue(); 
                        points.add(new Entry(xValue, yValue));
                    }
                    DataObjects=null;
                    randomnumbers=null;

                    List<Entry> points1 = new ArrayList<Entry>();
                    for (int i = 0; i < DataObjects1.length; i++) {
                        float xValue = DataObjects1[i].getXValue(); 
                        float yValue = DataObjects1[i].getYValue(); 
                        points1.add(new Entry(xValue, yValue));
                    }
                    DataObjects1=null;
                    randomnumbers1=null;

                    List<Entry> points2 = new ArrayList<Entry>();
                    for (int i = 0; i < DataObjects2.length; i++) {
                        float xValue = DataObjects2[i].getXValue(); 
                        float yValue = DataObjects2[i].getYValue(); 
                        points2.add(new Entry(xValue, yValue));
                    }
                    DataObjects2=null;
                    randomnumbers2=null;

                        LineDataSet dataSet = new LineDataSet(points, "line_0");
                        dataSet.setColor(Color.RED);

                        LineDataSet dataSet1 = new LineDataSet(points1, "line_1");
                        dataSet1.setColor(Color.GREEN);

                        LineDataSet dataSet2 = new LineDataSet(points2, "line_2");
                        dataSet1.setColor(Color.YELLOW);

                        List<ILineDataSet> dataSets = new ArrayList<>();
                        dataSets.add(dataSet);
                        dataSets.add(dataSet1);
                        dataSets.add(dataSet2);

                        LineData lineData = new LineData(dataSets);

                        //LineData lineData1 = new LineData(dataSet1);

                        chart.setData(lineData);
                        //chart.setData(lineData1);

                        chart.invalidate();

                   // }

                }catch (Exception e) {System.out.printf("Exception: \n");e.printStackTrace();}
            }
        });
```

**Code to update chart & paste data for chart with Generate array 2:**
```
        upDateChart.setOnClickListener(new View.OnClickListener(){
            @Override
        public void onClick(View v){

                try {
                    YourData[] DataObjects = new YourData[]{
                            new YourData(YourData.randomGraph(), YourData.randomGraph()),
                            new YourData(YourData.randomGraph(), YourData.randomGraph()),
                            new YourData(YourData.randomGraph(), YourData.randomGraph()),
                            new YourData(YourData.randomGraph(), YourData.randomGraph()),
                            new YourData(YourData.randomGraph(), YourData.randomGraph())
                    };

                    YourData[] DataObjects1 = new YourData[]{
                            new YourData(YourData.randomGraph(), YourData.randomGraph()),
                            new YourData(YourData.randomGraph(), YourData.randomGraph()),
                            new YourData(YourData.randomGraph(), YourData.randomGraph()),
                            new YourData(YourData.randomGraph(), YourData.randomGraph()),
                            new YourData(YourData.randomGraph(), YourData.randomGraph())
                    };

                    YourData[] DataObjects2 = new YourData[]{
                            new YourData(YourData.randomGraph(), YourData.randomGraph()),
                            new YourData(YourData.randomGraph(), YourData.randomGraph()),
                            new YourData(YourData.randomGraph(), YourData.randomGraph()),
                            new YourData(YourData.randomGraph(), YourData.randomGraph()),
                            new YourData(YourData.randomGraph(), YourData.randomGraph())
                    };

                    List<Entry> points = new ArrayList<Entry>();
                    for (int i = 0; i < DataObjects.length; i++) {
                        float xValue = DataObjects[i].getXValue(); 
                        float yValue = DataObjects[i].getYValue(); 
                        points.add(new Entry(xValue, yValue));
                    }
                    DataObjects=null;
                    //randomnumbers=null;

                    List<Entry> points1 = new ArrayList<Entry>();
                    for (int i = 0; i < DataObjects1.length; i++) {
                        float xValue = DataObjects1[i].getXValue(); 
                        float yValue = DataObjects1[i].getYValue(); 
                        points1.add(new Entry(xValue, yValue));
                    }
                    DataObjects1=null;
                    //randomnumbers1=null;

                    List<Entry> points2 = new ArrayList<Entry>();
                    for (int i = 0; i < DataObjects2.length; i++) {
                        float xValue = DataObjects2[i].getXValue();
                        float yValue = DataObjects2[i].getYValue();
                        points2.add(new Entry(xValue, yValue));
                    }
                    DataObjects2=null;
                    //randomnumbers2=null;

                        LineDataSet dataSet = new LineDataSet(points, "line_0");
                        dataSet.setColor(Color.RED);

                        LineDataSet dataSet1 = new LineDataSet(points1, "line_1");
                        dataSet1.setColor(Color.GREEN);

                        LineDataSet dataSet2 = new LineDataSet(points2, "line_2");
                        dataSet1.setColor(Color.YELLOW);

                        List<ILineDataSet> dataSets = new ArrayList<>();
                        dataSets.add(dataSet);
                        dataSets.add(dataSet1);
                        dataSets.add(dataSet2);

                        LineData lineData = new LineData(dataSets);

                        //LineData lineData1 = new LineData(dataSet1);

                        chart.setData(lineData);
                        //chart.setData(lineData1);

                        chart.invalidate();

                   // }

                }catch (Exception e) {System.out.printf("Exception: \n");e.printStackTrace();}

            }
        });
```

These two errors (**java.lang.NegativeArraySizeException: -2** and **java.lang.NegativeArraySizeException: -4**) appear 
without changes in the source code, i think this because i use randomly generated array or number to test linechart functionality. I try both code version: Generate array 1 and Generate array 2. In both cases with different periods i get  **java.lang.NegativeArraySizeException: -2** and **java.lang.NegativeArraySizeException: -4**. But most often i get **java.lang.NegativeArraySizeException: -2** in both code version. Errors appear with different numbers of button clicks, sometimes after 1 or 2 clicks, sometimes after about 10-15... But they always appear.
The try-catch blocks in my code has no effects, they are show NOTHING.

I tried to localize the source of the problem to fix the error, but i was unable to get more information.
Can someone tell me in which library or file of MPAndroidChart the problem locate? @PhilJay, or any othe guys, any ideas? I can't understand it from the debugger message trace. I want to try to put debug mechanism into that files.

I tried to made replace with address and value, but this threw an OutOfBund Exception.
Sorting it is bad idea in my case

Thanks in advance!
