### ISSUE TITLE
Problem filling the color inside the Line Chart.

### ISSUE THREAD

**Issue by samarth220194** [PhilJay/MPAndroidChart#2078]
I wanted to fill color inside my Line Chart .I have used .setDrawFilled() and .setFillColor() but it is not working for me properly.There are four Different Charts drawn when I Press The buttons (Day,Month,3Months,1 Year),1 chart for each button.But On adding the Above commands my chart color gets distorted .Here is My code and screenshot after adding the Above commands.

` 
          private void plotchart(String s[],float[] f1)
{

        ArrayList<String> xVals=new ArrayList<String>();

        for(int i=0;i<s.length;i++){
            xVals.add(s[i]);
        }

        ArrayList<com.github.mikephil.charting.data.Entry> entries= new ArrayList<>();
        for (int i = 0; i < f1.length; i++) {
             entries.add(new Entry(f1[i], i));
        }
        LineDataSet dataset;

        if (chart.getData() != null &&
                chart.getData().getDataSetCount() > 0) {
             dataset= (LineDataSet)chart.getData().getDataSetByIndex(0);
            dataset.setYVals(entries);

            //dataset.setFillColor(Color.BLACK);
            chart.getData().setXVals(xVals);
            MymarkerView mv = new MymarkerView(this, R.layout.custom_marker_view, xVals);
            chart.setMarkerView(mv);
           // dataset.setDrawFilled(true);
            chart.getData().notifyDataChanged();
            chart.notifyDataSetChanged();
            chart.invalidate();
        }
        else {
            dataset = new LineDataSet(entries, "");
            // dataset.isDrawCirclesEnabled();
            dataset.setColor(Color.BLACK);
            dataset.setCircleRadius(0f);
            dataset.setLineWidth(0.2f);
            dataset.setValueTextSize(0f);
            dataset.setDrawFilled(true);
             dataset.setFillColor(Color.BLACK);

            ArrayList<ILineDataSet> dataSets = new ArrayList<ILineDataSet>();
            dataSets.add(dataset); // add the datasets

            // create a data object with the datasets
            LineData data = new LineData(xVals, dataSets);

          //  LineData data = new LineData(xVals, dataset);

            MymarkerView mv = new MymarkerView(this, R.layout.custom_marker_view, xVals);

            chart.setMarkerView(mv);
            chart.setData(data);

             chart.notifyDataSetChanged();
            chart.invalidate();

        }
    }`

![device-2016-07-28-234152](https://cloud.githubusercontent.com/assets/17960987/17224087/10767eaa-551d-11e6-90db-dffd0b292aec.png)

![device-2016-07-28-234206](https://cloud.githubusercontent.com/assets/17960987/17224100/1b26984e-551d-11e6-8387-4d04560c006a.png)

![device-2016-07-28-234227](https://cloud.githubusercontent.com/assets/17960987/17224114/23673b94-551d-11e6-8826-92bd01bcc880.png)

![device-2016-07-28-234246](https://cloud.githubusercontent.com/assets/17960987/17224120/2ff1a232-551d-11e6-8a57-583e28fb9efd.png)

**I want a Display Like the one below**

![device-2016-07-28-234555](https://cloud.githubusercontent.com/assets/17960987/17224184/8ba706da-551d-11e6-82a5-5f594fd94df5.png)

**Comment by jngr** [comment]
Have you checked #1644 ?

**Comment by samarth220194** [comment]
My problem is occuring only on API level 19 ..evrything works fine for all other devices.

**Comment by jngr** [comment]
Sounds very familiar. Check that link and the solution on the bottom of the thread.

**Comment by samarth220194** [comment]
THe Command which you have posted.Should i try that?

**Comment by samarth220194** [comment]
Ohhh Bro..Thanks a Lot !!! :) :) .I was facing this problem from the past 1 week..It is solved ..

**Comment by jngr** [comment]
That's good to hear.  :)
