### ISSUE TITLE
Different line widths, though set to the same width. 

### ISSUE THREAD

**Issue by MaximilianKeppeler** [PhilJay/MPAndroidChart#2081]
I just started to implement your library and I have the issue at the bar and line chart, that the horizontal lines to the labels have different width. When I force to make 4 labels, it draws the 2 inside in 2.0f as I need it, but the highest and lowest line in another width, which I haven't specified . They should all have the same width. I checked for days the Wiki and tried around, but there wasn't really regarding this. Also interesting is, that if I don't specify a grid line width at all, it draws them in their default width - but even there are the highest and lowest line thinner than the lines between.

**Comment by PhilJay** [comment]
Show some code.
