### ISSUE TITLE
an IndexOutOfBoundsException occasionally occur  in my app linechart

### ISSUE THREAD

**Issue by Sevenupboy** [PhilJay/MPAndroidChart#2083]
when i finish coding of my app ,    an IndexOutOfBoundsException occasionally  occur  as below ( open 20 times & occur once ) ,and when i make yAxis enable(false) the problem never occur....

> 08-01 16:08:53.360 20364-21189/com.qixi.m303chartdemo D/MainActivity: hum arrayHum.size():64
08-01 16:08:53.360 20364-20364/com.qixi.m303chartdemo D/AndroidRuntime: Shutting down VM
08-01 16:08:53.360 20364-21189/com.qixi.m303chartdemo D/MainActivity: init co2
08-01 16:08:53.360 20364-21189/com.qixi.m303chartdemo D/MainActivity: co2 setting
08-01 16:08:53.360 20364-21189/com.qixi.m303chartdemo D/MainActivity: co2 data3
08-01 16:08:53.360 20364-21189/com.qixi.m303chartdemo I/MPAndroidChart: Preparing...
08-01 16:08:53.361 20364-21189/com.qixi.m303chartdemo I/MPAndroidChart: offsetLeft: 122.0, offsetTop: 0.0, offsetRight: 0.0, offsetBottom: 146.0
08-01 16:08:53.361 20364-21189/com.qixi.m303chartdemo I/MPAndroidChart: Content: RectF(122.0, 52.5, -52.5, -146.0)
08-01 16:08:53.361 20364-21189/com.qixi.m303chartdemo I/MPAndroidChart: Preparing Value-Px Matrix, xmin: 1.4699814E12, xmax: 1.4700376E12, xdelta: 5.6229888E7
08-01 16:08:53.361 20364-21189/com.qixi.m303chartdemo I/MPAndroidChart: Data is set.
08-01 16:08:53.361 20364-21189/com.qixi.m303chartdemo D/MainActivity: co2 arrayCo2.size():64
08-01 16:08:53.361 20364-21189/com.qixi.m303chartdemo D/HttpUtil: disconnect
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime: FATAL EXCEPTION: main
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime: Process: com.qixi.m303chartdemo, PID: 20364
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime: java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at java.util.ArrayList.get(ArrayList.java:308)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at com.github.mikephil.charting.formatter.FormattedStringCache$PrimFloat.getFormattedValue(FormattedStringCache.java:151)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at com.github.mikephil.charting.formatter.DefaultAxisValueFormatter.getFormattedValue(DefaultAxisValueFormatter.java:45)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at com.github.mikephil.charting.components.AxisBase.getFormattedLabel(AxisBase.java:451)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at com.github.mikephil.charting.components.AxisBase.getLongestLabel(AxisBase.java:437)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at com.github.mikephil.charting.components.YAxis.getRequiredWidthSpace(YAxis.java:302)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at com.github.mikephil.charting.charts.BarLineChartBase.calculateOffsets(BarLineChartBase.java:461)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at com.github.mikephil.charting.charts.BarLineChartBase.notifyDataSetChanged(BarLineChartBase.java:344)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at com.github.mikephil.charting.charts.Chart.onSizeChanged(Chart.java:1727)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at com.github.mikephil.charting.charts.BarLineChartBase.onSizeChanged(BarLineChartBase.java:1563)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.View.sizeChange(View.java:15786)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.View.setFrame(View.java:15751)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.View.layout(View.java:15667)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:122)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1170)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:814)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1187)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
08-01 16:08:53.361 20364-20364/com.qixi.m303chartdemo E/AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRo
08-01 16:08:54.486 20364-20364/com.qixi.m303chartdemo I/Process: Sending signal. PID: 20364 SIG: 9

my app has 3 linecharts of 3 type of data : temperature、humidity 、co2 , and use timestamp as yAxis(has fommat ->"02:34" fommat and show successsfully) , the normal data as below:
      `humidity:53.2;co2:907.0;temperature:25.9;date:1470037583000`

i has enable the MP's log so i found the problem maybe occur near when i setData to the linechart (maybe onSizeChange() is neaer),  and occur with the IndexOutOfBoundsException,but i found it's difficult to debug step by step. Some people met this problem?

**Comment by lschuetze** [comment]
I get the same error when writing lots of data into the chart.

**Comment by Sevenupboy** [comment]
@lschuetze thx ur reply. But my app  parse json and get all data when it start , then  use 'for' to add Entrys to ArrayList<Entry> ,  use ArrayList as param for LineDataSet init , finally invalidate() in runOnUiThread. So i make sure that the data not update after 'for' , and the threadId  always the same one unless in 'runOnUiThread' . So i feel puzzled now :-(

**Comment by lschuetze** [comment]
Then the problem could be how the data is stored and retrieved within MPAndroid. When you see particulary [this part of the code](https://github.com/PhilJay/MPAndroidChart/blob/43fa1e6cecf9b194be7dc56e4a01df9f6ea3f22b/MPChartLib/src/main/java/com/github/mikephil/charting/formatter/FormattedStringCache.java#L146-L148) then you see that float values and their String representation is stored in two different `ArrayList`. Maybe these lists diverge and do not have both the same length anymore.

A fix would be to use a `HashMap`.

```java
private HashMap<Float, String> cachedValues = new HashMap<>();
public String getFormattedValue(float value) {
  Float boxedValue = new Float(value);
  String result = cachedValues.get(boxedValue);
  if(result == null) {
    result = mFormat.format(boxedValue);
    cachedValues.put(boxedValue , result);
  }
  return result;
}
```

Not an offense but it seems that the whole `FormattedStringCache` class could be improved. I could write a pull request. Question is if @PhilJay would accept source- and binary incompatible changes (since it is already 3.0.0-beta1) so that all could be refactored into generic classes, or if it would be enough just to change the data structures for all `PrimXXX` classes.
