### ISSUE TITLE
Interacting with Chart

### ISSUE THREAD

**Issue by chaudhary-v** [PhilJay/MPAndroidChart#2084]
I created a Bar Chart and a Pie Chart. Now what I want both chart to be interactive.
Means if I click on bar, pie should show the distribution of Bar and vice versa.
Can we do that? If yes then how?

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart

https://github.com/PhilJay/MPAndroidChart/wiki/Highlighting
