### ISSUE TITLE
setMaxVisibleValueCount(int count):   doesn't work in Combined Chart

### ISSUE THREAD

**Issue by nimran** [PhilJay/MPAndroidChart#2086]
I have 12 bars and I need to display only 5 bar. Yes in BarGraph I can achieve. But in Combine chart that method is not working. Is that intended. 

Thanks in Advance. 
btw awesome library :) 👍

**Comment by PhilJay** [comment]
The way I see it is that you are confusing "maxVisibleCount" with "visibleXRange".

- `maxVisibleCount`: Controls the number of labels that are drawn until drawing of labels (only) stops. 
- `visibleXRange`: Controls the maximum number of visible entries on the chart area. Zooming out further than the visibleXRange is not possible.

Have a look at the [modifying the viewport](https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport) documentation chapter.

**Comment by nimran** [comment]
Thanks, got it
