### ISSUE TITLE
How to show MarkerView by default 

### ISSUE THREAD

**Issue by john1jan** [PhilJay/MPAndroidChart#2088]
I want the markerview to be visible by default at some x,y point , when the data is loaded in graph.

How can it be achieved ?

**Comment by john1jan** [comment]
I have fixed this, using 
`mChart.highlightValue(30, dataSetIndex);`

You should highlight the value after mChart.notifyDataSetChanged();

**Comment by nickyk2407** [comment]
@john1jan 
https://github.com/PhilJay/MPAndroidChart/issues/3375

How are you updating markerview?
