### ISSUE TITLE
setAutoScaleMinMaxEnabled() has no effect with CombinedChart in v3.0.0 beta1

### ISSUE THREAD

**Issue by 402169950** [PhilJay/MPAndroidChart#2092]
Hi,dear developer,MPAndroidChart has saved me a lot of time and i'm so appreciate. Buy there's a issue with me in V3.0.0 beta1 .After i filled the data in chart and invoked setAutoScaleMinMaxEnabled(). But nothing happened,my chart was just like a photo,it cannot autoscale its Y Axis when i drag the chart,i can move the chart in four directions and it never fixed the Y Axis.And here's the code snippets.
 chart.setScaleYEnabled(true);
        chart.setScaleXEnabled(false);
        chart.setAutoScaleMinMaxEnabled(true);
        chart.getAxisRight().setEnabled(false);
        Log.i("chartScaleY", chart.getScaleY() + "");
        chart.fitScreen();
        MovingPointMarkView mpmv = new MovingPointMarkView(chart.getContext(), null, xVals,  MovingPointMarkView.Mode.CANDLE);
        chart.setMarkerView(mpmv);
        chart.zoom(2f, 1f, chart.getXAxis().getAxisMaximum(), chart.getCandleData().getDataSetByIndex(chart.getCandleData().getDataSetCount() - 1).getYMax());

       Hope for your reply.

**Comment by PhilJay** [comment]
Issue fixed as of 1bbf4be1eed520a1da075d2e5a5d4cfb686ff4bd.

Thanks for the report.
