### ISSUE TITLE
How to draw a dot when user tap inside on chart?

### ISSUE THREAD

**Issue by aldajo92** [PhilJay/MPAndroidChart#2093]
I want to do an app that let me to add entries when user tap inside on chart. The problem is to get the X and Y position respect to chart axis. I did a review on OnChartGestureListener event but the problem is that MotionEvent only give me the tap location respect to screen and not respect to chart axis. The same problem is when I want to do a zoom, because the the idea is to draw dot when this happens, but MotionEvent only give me the position respect to screen.

**Comment by PhilJay** [comment]
So what you need is the corresponding "chart values" for screen pixels, am I right?

You can get them by using this method:

```java
MPPointD values = chart.getValuesByTouchPoint(touchX, touchY, AxisDependency.LEFT);
```

The `AxisDependency` specifies which axis scale should be chosen to transform the screen pixels.
