### ISSUE TITLE
Draw chart to PDF (itext)

### ISSUE THREAD

**Issue by yfsx** [PhilJay/MPAndroidChart#2095]
Hi, thanks for share this amazing lib!

if i create some charts, can we export it to pdf creator on android like itext?

thanks

**Comment by PhilJay** [comment]
Currently not possible!

**Comment by piotrek1543** [comment]
Hi guys, any update with this issue? I mean do you know how I can generate PDF view with charts?

**Comment by Damian1335** [comment]
Hello everyone, PhilJay could reply please ? I have same issue and want to know if an update have been made for this.
I'm developping an app for medical process and need absolutely this final touch ==> charts inside my pdf results. Thank you and waiting for your reply !!!!
