### ISSUE TITLE
Multiple Y-Axis for LineData to provide different Scaling

### ISSUE THREAD

**Issue by Noires** [PhilJay/MPAndroidChart#2096]
As said in the topic, it is a requirement for me kinda to have multiple Y-Axis.
Basically this should ensure that every graph gets drawn by the full height of the chart.

If i have have graph with really high values and one with lows, you basically cant check course 
of the lower graph. Is there any good way to implement this with MPAndroidChart?

**Comment by lschuetze** [comment]
The `CombinedChart` allows to draw multiple Y-axis. See [this example](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/CombinedChartActivity.java) and the [this](https://github.com/PhilJay/MPAndroidChart/wiki/Data-classes-in-detail) and [that](https://jitpack.io/com/github/PhilJay/MPAndroidChart/v3.0.0-beta1/javadoc/) documentation.

**Comment by Noires** [comment]
It seemed to me that the `Combined Chart` allowed multiple Y-Axis for different chart data, but not multiple Y-Axis only for LineData? Or am i wrong there?

**Comment by lschuetze** [comment]
The `CombinedChart` is to combine different types of charts. If you just want to show lines you can draw a `LineChart` and add different `LineDataSet`s containing the values for each line to draw.

The charts have a left and a right Y axis. For a given `(Line-)DataSet` you can add the respective Y axis.

```java
firstLineDataSet.setAxisDependency(lineChart.getAxisLeft());
secondLineDataSet.setAxisDependency(lineChart.getAxisRight());
```

**Comment by Noires** [comment]
The problem is that in the LineChart the Left-Axis gets scaled to the highest value of the graphs. But i kinda hoped to have multiple Left-Axis for each graph, so that everything gets scaled how it is required.

But i think i will just scale the values manually now to one unified range before adding them to the chart and exchange the value formatter depending on which graph is focused.

**Comment by OksanaKryvenko** [comment]
> The problem is that in the LineChart the Left-Axis gets scaled to the highest value of the graphs. But i kinda hoped to have multiple Left-Axis for each graph, so that everything gets scaled how it is required.
> 
> But i think i will just scale the values manually now to one unified range before adding them to the chart and exchange the value formatter depending on which graph is focused.
> 
> Still thanks though!

Could you (or anyone who knows) please kindly show an example of your code for this issue? Or maybe someone knows better solution to achieve this?

**Comment by trix0** [comment]
What about 3 and more Y Axis ? I have found support only for Left and right. What If I want 2 Y axis on left and 1 on right or 20 on the left and 69 on the right?

It would be nice to have Multi Y Combined Chart. Where you just add array of Y Axis.

Is it possible to do this with currect library or Do I need to go custom ?

If anybody has solution for this Id be very happy if you share it.

Thanks,
Trixo

**Comment by humleflue** [comment]
I guess a hacky solution is required to achieve 3 or more y-axis values as the library only supports 2. Did anyone come up with a solution to this?

**Comment by ngotiendat** [comment]
hi, I facing the same issue someone help me tsk
