### ISSUE TITLE
StackedBar legend dataset name

### ISSUE THREAD

**Issue by SchadtJ** [PhilJay/MPAndroidChart#2097]
Hello, thank you for the great library! I am making a stacked bar graph, and I have a question about the legend displaying the dataset name. When I use a regular bar graph, the legend displays the name of the dataset to the right of the form; however, when I use a stacked bar graph, there are two forms and the name is displayed to the right of both. I want the legend to have different values for the two forms as they represent two different price ranges. Is there a way to assign String values to these forms? My Java code is below, and a picture of the graph is attached as-well. Thank You!

![capture](https://cloud.githubusercontent.com/assets/12833400/17377486/e9cb6b16-5987-11e6-96b5-3e1766bd69be.PNG)

public class MpAndroidChartExample extends Activity {

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.androidchart_mp);
        BarChart chart = (BarChart) findViewById(R.id.chart_bar_mp);
        BarEntry entry3 = new BarEntry(1f, new float[] {2,3});
        BarEntry entry2 = new BarEntry(3f, new float[] {3,8});
        BarEntry entry = new BarEntry(5f, new float[] {4,4});
        ArrayList<BarEntry> entries = new ArrayList<>();
        entries.add(entry);
        entries.add(entry2);
        entries.add(entry3);

        BarDataSet dataset = new BarDataSet(entries, "   Summary");
        dataset.setColors(new int[] {R.color.portal_dark_blue, R.color.portal_light_blue}, this);

        YAxis left = chart.getAxisLeft();
        left.setAxisMaxValue(10);
        left.setAxisMinValue(0);
        chart.getAxisRight().setEnabled(false);
        XAxis bottomAxis = chart.getXAxis();
        bottomAxis.setValueFormatter(new AxisValueFormatter() {
            @Override
            public String getFormattedValue(float value, AxisBase axis) {
                return "entry"; // eventually need to update
            }

            @Override
            public int getDecimalDigits() {
                return 0;
            }
        });

        bottomAxis.setAxisMinValue(-1);
        bottomAxis.setAxisMaxValue(15);
        bottomAxis.setDrawGridLines(false);
        chart.setDrawValueAboveBar(true);
        chart.setDescription("");

        BarData data = new BarData(dataset);
        chart.setData(data);

                    // legend

        Legend legend = chart.getLegend();
        legend.setYOffset(40);
        legend.setPosition(Legend.LegendPosition.BELOW_CHART_CENTER);
        legend.setTextSize(200);
    }
}

**Comment by SchadtJ** [comment]
Hello! I figured out how to fix this. You can set your labels for your BarDataSet via the setStackLabels method.

**Comment by PhilJay** [comment]
Yes, exactly!
