### ISSUE TITLE
Combined-Chart (bar- and linechart in this case) 

### ISSUE THREAD

**Issue by sarathi1989** [PhilJay/MPAndroidChart#2098]
Hi I integrated Combined-Chart (bar- and linechart in this case)  code. but the problem is I want the exact output one bar and line in center similer like you mention the screen shots

https://camo.githubusercontent.com/e29d8d3316203700965cc6cc56e67b779f2845bb/68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d5043686172742f6d61737465722f73637265656e73686f74732f636f6d62696e65645f63686172742e706e67

I dont want Bubble, ScatterData and Candle Data and group bar.

Please help me.

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/CombinedChartActivity.java
