### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by NaveenJayaram1994** [PhilJay/MPAndroidChart#2100]
Compilation error while designing pie chart in android Studio

Error:(41, 51) error: incompatible types: List<PieEntry> cannot be converted to List<Entry>
Error:(53, 24) error: no suitable constructor found for PieData(PieDataSet)
constructor PieData.PieData(List<String>) is not applicable
(argument mismatch; PieDataSet cannot be converted to List<String>)
constructor PieData.PieData(String[]) is not applicable
(argument mismatch; PieDataSet cannot be converted to String[])

too many errors while doing for pie chart.
sir plz send me example for piechart.
the one which is Apk didnt work for me

solution needed plz help me

**Comment by lschuetze** [comment]
Take a look into [this example](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/PieChartActivity.java).

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki
