### ISSUE TITLE
setValueTypeFace makes values turn invisible, HorizontalBarGraph

### ISSUE THREAD

**Issue by WesleyHunt** [PhilJay/MPAndroidChart#2101]
<img width="1080" alt="default typeface is null" src="https://cloud.githubusercontent.com/assets/6569040/17418329/fae74c4c-5a65-11e6-9b66-c780a5ea1dc0.png">
<img width="915" alt="typeface set" src="https://cloud.githubusercontent.com/assets/6569040/17418330/fae8499e-5a65-11e6-92e6-4c447e38c531.png">

Use .setValueTypeFace on BarDataSet or BarData and the values in the horizontal Bar Graph will disappear. Functions fine when not using setValueTypeFace. Without setting a typeface the default behaviour is setValueTypeFace = null, and the text will draw fine when that is the case.

**Comment by PhilJay** [comment]
Have you tested your typeface on other UI components (e.g. `TextView`) and checked if it draws successfully there?

Unfortunately I cannot reproduce the issue, for me custom typefaces work fine.

**Comment by WesleyHunt** [comment]
The typeface works everywhere else, but for some reason it won't work in this instance with the barchart values or axis labels. Every other typeface I have tried works fine though, so it may just be something weird with this typeface

**Comment by PhilJay** [comment]
Okay, thanks for letting me know. If you could just tell me the name of the font, I might be able to get it myself.

**Comment by WesleyHunt** [comment]
Hey it's a google font actually, Fira Sans https://fonts.google.com/specimen/Fira+Sans , any of the Fira Sans do not seem to work; regular, bold, italic, light.
