### ISSUE TITLE
Pie Chart label text outside slice overlaps with value line.

### ISSUE THREAD

**Issue by anshchauhan** [PhilJay/MPAndroidChart#2102]
Hi,

While working with a pie charts I found out that if you are drawing labels(only) outside the slices the text of labels overlaps with the value line. I just commented this 
`dataSet.setYValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);`
in https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/PiePolylineChartActivity.java:

![screenshot_20160805-040515](https://cloud.githubusercontent.com/assets/14310139/17420740/3fc1ae00-5ac2-11e6-8a32-76e1069d9bcc.png)

Please let me know if there is a setting for setting label text offset. As a workaround I've set offset in drawValues to labelRadius/2 instead of 5.f but I guess that will might mess other things up.

**Comment by dylan33p** [comment]
This still appears to be broke on 3.0.0-beta1

Also once moving to outside slice value text color only shows white.

<img width="407" alt="screen shot 2016-10-17 at 11 24 46 am" src="https://cloud.githubusercontent.com/assets/22891428/19443907/55bb1790-945c-11e6-8202-92c49a67a6cf.png">

`data.setValueTextColor(Color.BLACK);
        dataSet.setValueLinePart1OffsetPercentage(90.f);
        dataSet.setValueLinePart1Length(1f);
        dataSet.setValueLinePart2Length(.2f);
        dataSet.setValueTextColor(Color.BLACK);
        dataSet.setXValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);`

**Comment by MyGitUserAcc** [comment]
@anshchauhan How do you made to draw the text outside the slices.
I sit using the line dataSet.setYValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE) ??
I didn't see setYValuePosition() method in mpandroidchart library.Is this because am using an older library?? Currently i am using mpandroidchartlibrary-2-2-4.jar for building piechart.

**Comment by gokulrajkc** [comment]
How to show the data with a line outside piechart using MPchart
 com.github.PhilJay:MPAndroidChart:v2.0.9 , can anyone help me with this
![sample](https://cloud.githubusercontent.com/assets/11208646/22503877/b86a3a10-e899-11e6-887a-55b0db87e007.png)

I need the values to be outside the pie chart with a line .

**Comment by MyGitUserAcc** [comment]
@gokulrajkc Use the below code
`pieEntryList = new ArrayList<PieEntry>();
            for (int i = 0; i < yList.size(); i++){
                PieEntry newPEntry = new PieEntry(yList.get(i).getAmount(), yList.get(i).getName() + " " + Math.round(yList.get(i).getAmount()));
                pieEntryList.add(newPEntry);
            }
            // create pieDataSet
            dataSet = new PieDataSet(pieEntryList, chart);
            //    dataSet.setSliceSpace(3f);
            dataSet.setSelectionShift(5f);
            dataSet.setXValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);
            dataSet.setValueLinePart1OffsetPercentage(80.f);
            dataSet.setValueLinePart1Length(0.2f);
            dataSet.setValueLinePart2Length(0.4f);

            PieData data = new PieData(dataSet);
            data.setDrawValues(false);
            pchart.setData(data);
            pchart.setEntryLabelColor(Color.BLACK);
            pchart.setEntryLabelTextSize(7f);
            pchart.setEntryLabelTypeface(tf);

            // undo all highlights
            pchart.highlightValues(null);
            // refresh/update pie chart
            pchartRepOne.invalidate();`

Where 
`dataSet.setXValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);
            dataSet.setValueLinePart1OffsetPercentage(80.f);
            dataSet.setValueLinePart1Length(0.2f);
            dataSet.setValueLinePart2Length(0.4f);`
solves your problem.You can change the line size by using the above codes.

**Comment by shubhamtunwal97** [comment]
How to remove the bright whiter translucent circle in the pie chart?

**Comment by Rishabhsaxena2011** [comment]
I am just trying to set text near line but unable to add.
Please tell any one how to set label near line in Pie Chart.

  mChart.setOnChartValueSelectedListener(this);
        //   mChart.setTouchEnabled(false);
        mChart.setUsePercentValues(true);
        mChart.getDescription().setEnabled(false);
        mChart.setExtraOffsets(5, 10, 5, 5);

        mChart.setDragDecelerationFrictionCoef(0.95f);
        mChart.setDrawHoleEnabled(true);
        mChart.setHoleColor(Color.WHITE);

        mChart.setTransparentCircleColor(Color.WHITE);
        mChart.setTransparentCircleAlpha(110);

        mChart.setHoleRadius(80f);
        mChart.setTransparentCircleRadius(61f);
        mChart.setRotationAngle(0);
        // enable rotation of the chart by touch
        mChart.setRotationEnabled(true);
        mChart.setHighlightPerTapEnabled(true);


float mult = range;
        ArrayList<PieEntry> entries = new ArrayList<PieEntry>();
        for (int i = 0; i < count; i++) {
                 entries.add(new PieEntry(40f, globalViewDetailsDataArrayList.get(i).getItemDisplayName(), globalViewDetailsDataArrayList.get(i)));   // divide from the num. of count
        }

        PieDataSet dataSet = new PieDataSet(entries, "");

        dataSet.setDrawIcons(false);
      
        dataSet.setIconsOffset(new MPPointF(0, 40));
        dataSet.setSelectionShift(5f);



        


        dataSet.setXValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);
        dataSet.setValueLinePart1OffsetPercentage(80.f);
        dataSet.setValueLinePart1Length(0.4f);
        dataSet.setValueLinePart2Length(0.5f);

     

        ArrayList<Integer> colors = new ArrayList<Integer>();
        for (int i = 0; i < globalViewDetailsDataArrayList.size(); i++) {
            colors.add(Color.parseColor(globalViewDetailsDataArrayList.get(i).getColor()));//red
        }
        dataSet.setColors(colors);

        PieData data = new PieData(dataSet);
        data.setValueFormatter(new PercentFormatter());
        data.setValueTextSize(11f);
        data.setValueTextColor(Color.BLACK);
        dataSet.setDrawValues(false);

        mChart.setData(data);


        mChart.setEntryLabelColor(Color.BLACK);
        mChart.setEntryLabelTextSize(7f);
      
        mChart.highlightValues(null);
    

        mChart.invalidate();



 mChart.spin(20000, 0, 360, Easing.EasingOption.EaseInOutBounce);
        // mChart.animateY(14000, Easing.EasingOption.EaseInOutQuad);
        Legend l = mChart.getLegend();
        l.setEnabled(true);
        l.setVerticalAlignment(Legend.LegendVerticalAlignment.TOP);
        l.setHorizontalAlignment(Legend.LegendHorizontalAlignment.RIGHT);
        l.setOrientation(Legend.LegendOrientation.VERTICAL);
        l.setDrawInside(true);
        // l.setExtra(getLabel());
        l.setXEntrySpace(7f);
        l.setYEntrySpace(0f);
        l.setYOffset(0f);
        // l.setEnabled(false);

        // l.setEntries(getLabel());           //Give Side Menu of Label with Color
        //  l.setCustom(getLabel());  //Give Side Menu of Label
        // entry label styling
        mChart.setEntryLabelColor(Color.WHITE);
        // mChart.setEntryLabelTypeface(mTfRegular);
        mChart.setEntryLabelTextSize(12f);

**Comment by ALI-SAMPSON** [comment]
> This still appears to be broke on 3.0.0-beta1
> 
> Also once moving to outside slice value text color only shows white.
> 
> <img alt="screen shot 2016-10-17 at 11 24 46 am" width="407" src="https://cloud.githubusercontent.com/assets/22891428/19443907/55bb1790-945c-11e6-8202-92c49a67a6cf.png">
> 
> `data.setValueTextColor(Color.BLACK); dataSet.setValueLinePart1OffsetPercentage(90.f); dataSet.setValueLinePart1Length(1f); dataSet.setValueLinePart2Length(.2f); dataSet.setValueTextColor(Color.BLACK); dataSet.setXValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);`

I faced the same issue and this line of code fixed it for me

pieChart.setEntryLabelColor(Color.YELLOW);

**Comment by nitish-gloify** [comment]
use match parent in pie chart that's all
