### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by JakeWang123** [PhilJay/MPAndroidChart#2103]
An exception has occurred in the compiler (1.8.0_11). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.

Pls help me solve it !

**Comment by qujc** [comment]
@PhilJay ,i got the same issue, help me ~

**Comment by qujc** [comment]
@JakeWang123 , have you solved it ?
