### ISSUE TITLE
Linechart not showing

### ISSUE THREAD

**Issue by LISPos** [PhilJay/MPAndroidChart#2111]
public class MainActivity extends AppCompatActivity {

    //private String data ="  0.1163  0.0311  0.1187  0.0294  0.1170  0.0401  0.1183  0.0497  0.1168  0.0578  0.1177  0.0684  0.1166  0.0784  0.1163  0.0851  0.1172  0.0979  0.1172  0.1076  0.1147  0.1142  0.1151  0.1269  0.1161  0.1352  0.1159  0.1461  0.1149  0.1569  0.1149  0.1648  0.1147  0.1751  0.1133  0.1862  0.1144  0.1950  0.1149  0.2040  0.1159  0.2147  0.1112  0.2244  0.1121  0.2331  0.1138  0.2430  0.1119  0.2524  0.1131  0.2604  0.1127  0.2721  0.1131  0.2837  0.1112  0.2927  0.1123  0.3007  0.1108  0.3099  0.1117  0.3208  0.1093  0.3300  0.1121  0.3390  0.1095  0.3508  0.1110  0.3574  0.1116  0.3673  0.1116  0.3797  0.1099  0.3838  0.1106  0.3988  0.1084  0.4069  0.1101  0.4132  0.1088  0.4273  0.1086  0.4380  0.1078  0.4476  0.1072  0.4566  0.1067  0.4665  0.1071  0.4776  0.1046  0.4881  0.1058  0.4937  0.1054  0.5046  0.1033  0.5177  0.1039  0.5276  0.0969  0.5353  0.0917  0.5434  0.0741  0.5539  0.0516  0.5640  0.0315  0.5736  0.0011  0.5784  0.0002  0.5792  0.0000  0.5805  0.0030  0.5798  0.0019  0.5786  0.0006  0.5790  0.0015  0.5771  0.0000  0.5779  0.0008  0.5796  0.0022  0.5794  0.0002  0.5788  0.0015  0.5786  0.0015  0.5790  0.0017  0.5796  0.0021  0.5788  0.0000  0.5788  0.0006  0.5784  0.0021  0.5809  0.0008  0.5798  0.0006  0.5784  0.0000  0.5779  0.0026  0.5769  0.0006  0.5784  0.0002  0.5779  0.0000  0.5788  0.0002  0.5781  0.0021  0.5784  0.0011  0.5799  0.0013  0.5779  0.0015  0.5813  0.0004  0.5782  0.0000  0.5766  0.0017  0.5811  0.0006  0.5794  0.0011  0.5790  0.0011  0.5796  0.0009  0.5811  0.0002  0.5794  0.0006  0.5794  0.0011  0.5820  0.0008  0.5798  0.0002  0.5803";

    private String data ="  0.2139  2.7345  0.2137  3.4806  0.2132  4.3003  0.2124  5.1515  0.2122  6.0237  0.2119  6.8433  0.2119  7.6525  0.2112  8.5142  0.2104  9.3654  0.2061 10.1850  0.2036 11.0257  0.2031 11.9084  0.2023 12.7281  0.2023 13.5372  0.2018 14.4094  0.2011 15.2711  0.2003 16.0803  0.1993 16.9105  0.1983 17.7932  0.1978 18.6233  0.1971 19.4220  0.1961 20.3047  0.1953 21.1559  0.1948 21.9756  0.1940 22.8162  0.1935 23.6674  0.1928 24.5081  0.1923 25.3172  0.1913 26.1789  0.1903 27.0406  0.1900 27.8603  0.1887 28.6905  0.1852 29.5627  0.1691 30.4034  0.1258 31.2020  0.0482 32.0742 -0.0004 32.4945 -0.0007 32.5366 -0.0007 32.5471 -0.0012 32.4945 -0.0010 32.5050 -0.0007 32.5681 -0.0007 32.5261 -0.0007 32.4945 -0.0010 32.5366 -0.0007 32.5471 -0.0010 32.5050 -0.0010 32.5050 -0.0010 32.5681 -0.0010 32.5366 -0.0010 32.4840 -0.0010 32.5261 -0.0010 32.5576 -0.0010 32.5156 -0.0010 32.5050 -0.0007 32.5681 -0.0010 32.5261 -0.0010 32.4735 -0.0007 32.5156 -0.0010 32.5576 -0.0010 32.5156 -0.0010 32.5050 -0.0010 32.5576 -0.0010 32.5366 -0.0010 32.4840 -0.0010 32.5156 -0.0010 32.5576 -0.0010 32.5261 -0.0010 32.5050 -0.0010 32.5471 -0.0010 32.5366 -0.0010 32.4840 -0.0010 32.5050 -0.0010 32.5576 -0.0010 32.5156 -0.0010 32.4945 -0.0010 32.5366 -0.0007 32.5471 -0.0010 32.4840 -0.0010 32.5261 -0.0010 32.5576 -0.0010 32.5366 -0.0010 32.5050 -0.0010 32.5471 -0.0010 32.5471 -0.0010 32.4945 -0.0010 32.5050 -0.0010 32.5471 -0.0010 32.5261 -0.0010 32.5050 -0.0010 32.5366 -0.0010 32.5366 -0.0010 32.4945 -0.0010 32.5050 -0.0007 32.5576 -0.0010 32.5261 -0.0010 32.5050 -0.0010 32.5261 -0.0010 32.5576 -0.0010 32.4945";
    private String dac_V, dac_A;
    public static float[] arr_A = new float[100];
    public static float[] arr_V = new float[100];
    public static float[] arr_P = new float[100];

    LineChart chart;
    LineDataSet lineDataSet1, lineDataSet2;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        chart = (LineChart) findViewById(R.id.chart);

        int x = 0, y = 8;
        for (int i = 0; i <= 99; i++) {
            for (int j = 1; j <= 2; j++) {
                if (j % 2 == 0) {
                    dac_V = data.substring(x, y);
                    arr_V[i] = Float.parseFloat(dac_V);
                    x += 8;
                    y += 8;
                } else {
                    dac_A = data.substring(x, y);
                    arr_A[i] = Float.parseFloat(dac_A);
                    x += 8;
                    y += 8;
                }
            }
        }

        chart.getLegend().setPosition(Legend.LegendPosition.ABOVE_CHART_RIGHT);
        chart.setDrawGridBackground(false);
        chart.setDescription("");
        chart.setTouchEnabled(true);
        chart.setDragEnabled(true);

        chart.getXAxis().setAxisLineColor(0xFF898989);
        chart.getXAxis().setAxisLineWidth(1f);

        chart.getXAxis().setPosition(XAxis.XAxisPosition.BOTTOM);
        chart.getAxisRight().setEnabled(false);
        chart.getAxisLeft().setAxisLineColor(0xFF898989);
        chart.getAxisLeft().setAxisLineWidth(1f);

        chart.getAxisLeft().setValueFormatter(new DefaultAxisValueFormatter(5));
        chart.getXAxis().setValueFormatter(new DefaultAxisValueFormatter(5));

        ArrayList<Entry> entries1 = new ArrayList<Entry>();
        ArrayList<Entry> entries2 = new ArrayList<Entry>();

        for(int i=0; i<100; i++) {
            entries1.add(new Entry(arr_V[i],arr_A[i]));
            entries2.add(new Entry(arr_A[i],arr_P[i]));
        }

        lineDataSet1 = new LineDataSet(entries1, "IV Curve");
        lineDataSet1.setDrawFilled(true);
        lineDataSet1.setFillColor(0xFFFAFFE5);
        lineDataSet1.setDrawCircles(false);
        lineDataSet1.setLineWidth(1.7f);
        lineDataSet1.setDrawHighlightIndicators(false);
        lineDataSet1.setColor(0xFF96AA39);
        lineDataSet1.setDrawValues(false);

        lineDataSet2 = new LineDataSet(entries2, "PW Curve");
        lineDataSet2.setDrawFilled(true);
        lineDataSet2.setFillColor(0xFFFFCFCF);
        lineDataSet2.setDrawCircles(true);
        lineDataSet2.setLineWidth(1.7f);
        lineDataSet2.setDrawHighlightIndicators(true);
        lineDataSet2.setColor(0xFFFF0000);
        lineDataSet2.setDrawValues(true);

        ArrayList<ILineDataSet> dataSets = new ArrayList<ILineDataSet>();
        dataSets.add(lineDataSet1);
        dataSets.add(lineDataSet2);

        LineData data = new LineData(dataSets);

        chart.setData(data);

        chart.animateX(700, Easing.EasingOption.EaseInOutSine);
        chart.notifyDataSetChanged();
        chart.invalidate();
    }
}

**Comment by PhilJay** [comment]
What is the result? No chart at all? A chart displaying the no data message?

You need to be more specific otherwise no-one can help you.

**Comment by LISPos** [comment]
this data is not showing

private String data ="  0.2139  2.7345  0.2137  3.4806  0.2132  4.3003  0.2124  5.1515  0.2122  6.0237  0.2119  6.8433  0.2119  7.6525  0.2112  8.5142  0.2104  9.3654  0.2061 10.1850  0.2036 11.0257  0.2031 11.9084  0.2023 12.7281  0.2023 13.5372  0.2018 14.4094  0.2011 15.2711  0.2003 16.0803  0.1993 16.9105  0.1983 17.7932  0.1978 18.6233  0.1971 19.4220  0.1961 20.3047  0.1953 21.1559  0.1948 21.9756  0.1940 22.8162  0.1935 23.6674  0.1928 24.5081  0.1923 25.3172  0.1913 26.1789  0.1903 27.0406  0.1900 27.8603  0.1887 28.6905  0.1852 29.5627  0.1691 30.4034  0.1258 31.2020  0.0482 32.0742 -0.0004 32.4945 -0.0007 32.5366 -0.0007 32.5471 -0.0012 32.4945 -0.0010 32.5050 -0.0007 32.5681 -0.0007 32.5261 -0.0007 32.4945 -0.0010 32.5366 -0.0007 32.5471 -0.0010 32.5050 -0.0010 32.5050 -0.0010 32.5681 -0.0010 32.5366 -0.0010 32.4840 -0.0010 32.5261 -0.0010 32.5576 -0.0010 32.5156 -0.0010 32.5050 -0.0007 32.5681 -0.0010 32.5261 -0.0010 32.4735 -0.0007 32.5156 -0.0010 32.5576 -0.0010 32.5156 -0.0010 32.5050 -0.0010 32.5576 -0.0010 32.5366 -0.0010 32.4840 -0.0010 32.5156 -0.0010 32.5576 -0.0010 32.5261 -0.0010 32.5050 -0.0010 32.5471 -0.0010 32.5366 -0.0010 32.4840 -0.0010 32.5050 -0.0010 32.5576 -0.0010 32.5156 -0.0010 32.4945 -0.0010 32.5366 -0.0007 32.5471 -0.0010 32.4840 -0.0010 32.5261 -0.0010 32.5576 -0.0010 32.5366 -0.0010 32.5050 -0.0010 32.5471 -0.0010 32.5471 -0.0010 32.4945 -0.0010 32.5050 -0.0010 32.5471 -0.0010 32.5261 -0.0010 32.5050 -0.0010 32.5366 -0.0010 32.5366 -0.0010 32.4945 -0.0010 32.5050 -0.0007 32.5576 -0.0010 32.5261 -0.0010 32.5050 -0.0010 32.5261 -0.0010 32.5576 -0.0010 32.4945";

---------------------------------------------------------------------------------------------------

this data is showing

private String data ="  0.1163  0.0311  0.1187  0.0294  0.1170  0.0401  0.1183  0.0497  0.1168  0.0578  0.1177  0.0684  0.1166  0.0784  0.1163  0.0851  0.1172  0.0979  0.1172  0.1076  0.1147  0.1142  0.1151  0.1269  0.1161  0.1352  0.1159  0.1461  0.1149  0.1569  0.1149  0.1648  0.1147  0.1751  0.1133  0.1862  0.1144  0.1950  0.1149  0.2040  0.1159  0.2147  0.1112  0.2244  0.1121  0.2331  0.1138  0.2430  0.1119  0.2524  0.1131  0.2604  0.1127  0.2721  0.1131  0.2837  0.1112  0.2927  0.1123  0.3007  0.1108  0.3099  0.1117  0.3208  0.1093  0.3300  0.1121  0.3390  0.1095  0.3508  0.1110  0.3574  0.1116  0.3673  0.1116  0.3797  0.1099  0.3838  0.1106  0.3988  0.1084  0.4069  0.1101  0.4132  0.1088  0.4273  0.1086  0.4380  0.1078  0.4476  0.1072  0.4566  0.1067  0.4665  0.1071  0.4776  0.1046  0.4881  0.1058  0.4937  0.1054  0.5046  0.1033  0.5177  0.1039  0.5276  0.0969  0.5353  0.0917  0.5434  0.0741  0.5539  0.0516  0.5640  0.0315  0.5736  0.0011  0.5784  0.0002  0.5792  0.0000  0.5805  0.0030  0.5798  0.0019  0.5786  0.0006  0.5790  0.0015  0.5771  0.0000  0.5779  0.0008  0.5796  0.0022  0.5794  0.0002  0.5788  0.0015  0.5786  0.0015  0.5790  0.0017  0.5796  0.0021  0.5788  0.0000  0.5788  0.0006  0.5784  0.0021  0.5809  0.0008  0.5798  0.0006  0.5784  0.0000  0.5779  0.0026  0.5769  0.0006  0.5784  0.0002  0.5779  0.0000  0.5788  0.0002  0.5781  0.0021  0.5784  0.0011  0.5799  0.0013  0.5779  0.0015  0.5813  0.0004  0.5782  0.0000  0.5766  0.0017  0.5811  0.0006  0.5794  0.0011  0.5790  0.0011  0.5796  0.0009  0.5811  0.0002  0.5794  0.0006  0.5794  0.0011  0.5820  0.0008  0.5798  0.0002  0.5803";

---------------------------------------------------------------------------------------------------


y axis data (0.2139, 0.2137, 0.2132 or 0.1163, 0.1187, 0.1170)
x axis data (2.7345, 3.4806, 4.3003 or 0.0311, 0.0294, 0.0401)



first data is not showing ... Can not draw a line. 
second data is showing ... draw a line.


I think
This problem is by a negative number  .. a lot of

sorry,
I don't speak english very well.

Thank you, Sir!

**Comment by PhilJay** [comment]
You are parsing a String with data into float values. That is very bad practice to say the least.

Also, to me it looks like your parsing is faulty since you always call `string.substring(...)` in steps of 8 characters, but your data sometimes contains negative values with a "-" character in front of them causing your parser to fail.

Summed up I am quite certain that the issue of "the chart is not showing" is related to your data and the way you process it.
