### ISSUE TITLE
Use PieChart: When a slice is smaller than 0.1% , the chart background changed it`s color to this slice

### ISSUE THREAD

**Issue by xukunn** [PhilJay/MPAndroidChart#2119]
PieChartRenderer.drawDataSet():

if (sweepAngleOuter % 360f == 0.f) {
                            // Android is doing "mod 360"
                            mPathBuffer.addCircle(center.x, center.y, innerRadius, Path.Direction.CCW);
                        }

in this case sweepAngleOuter ==0

**Comment by lschuetze** [comment]
The comparison of floats against 0 is [not a good idea](http://stackoverflow.com/questions/1088216/whats-wrong-with-using-to-compare-floats-in-java). There is always some epsilon which should be taken into account.

**Comment by AmmarMhd** [comment]
I'm having the same issue and just came check if someone opened it

**Comment by lukas1** [comment]
I'm still affected by this bug even with latest master (7b3355)

**Comment by AmmarMhd** [comment]
This is not fixed actually
