### ISSUE TITLE
BUG - About CombinedChart cannot show markerview

### ISSUE THREAD

**Issue by HelloLollipop** [PhilJay/MPAndroidChart#2123]
I make a combinedchart in an actvity,and set bardata and linedata,but I have to hide the line in the combinedchart and I find that if you hide line you cannot click bar,and the markerview cannot be show in that case,so is any solutions here?

**Comment by PhilJay** [comment]
I don't understand, what do you mean by "hiding the line"?

**Comment by HelloLollipop** [comment]
I have solved this bug,and also thank u very much,and love your libs~it`s can be used in many different flexible ways!
