### ISSUE TITLE
percentage without the "%" in pie chart 

### ISSUE THREAD

**Issue by aviTwito** [PhilJay/MPAndroidChart#2124]
i`m seeing the percentage without the "%"  symbol in the chart.
how do i fix it? this is code im creating xVals and yVals:

  for (int i = 0; i < parentArray.length(); i++) {
                    JSONObject finalObject = parentArray.getJSONObject(i);//get the current json object which is representaion of roomate object
                    yVals1.add(new Entry(((float) finalObject.getDouble("amountPayed")), pos));
                    xVals.add(finalObject.getString("firstName"));
}

here i`m setting the prefrences:

  public void setPieChartPrefrences() {
        mPieChartData.setUsePercentValues(true);
        mPieChartData.setHoleColor(Color.rgb(235, 235, 235));

        mPieChartData.setDescription("");
        mPieChartData.setDrawCenterText(true);

        mPieChartData.setRotationAngle(0);
        mPieChartData.setRotationEnabled(true);
        mPieChartData.setCenterText("כמה שילמנו");
        mPieChartData.setCenterTextSize(25);
        mPieChartData.setCenterTextColor(Color.parseColor("#02438b"));

        mPieChartData.animateXY(1000, 1000);

        mPieChartData.setCenterTextSize(10f);

    }

**Comment by PhilJay** [comment]
You need to add a formatter to draw the % sign. 

https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface

**Comment by mebr1416** [comment]
pieData.setValueFormatter(new PercentFormatter());

**Comment by nagasureshkalla** [comment]
still not displaying %

**Comment by MGaetan89** [comment]
With the latest version (`3.1.0`), you should also set `pieChart.setUsePercentValues(true)`.

**Comment by nagasureshkalla** [comment]
data.setValueFormatter(new PercentFormatter());
       

        pieChart.setUsePercentValues(true);

**Comment by bkoruznjak** [comment]
If you do not initialise your `PercentFormatter` with the pie chart it will not render the %

The correct way to do this (if you want percentage sign displayed) is:

```
pieData.setValueFormatter(new PercentFormatter(pieChart))
pieChart.setUsePercentValues(true)
```

The comment in the `PercentageFormatter` is really missleading on the constructor that takes the `PieChart`

> // Can be used to remove percent signs if the chart isn't in percent mode
seeing as you need it set to have the %

**Comment by vkumar644** [comment]
```
public class MyValueFormatter extends PercentFormatter {
    DecimalFormat mFormat;
    PieChart mPieChart;

    public MyValueFormatter(DecimalFormat format, PieChart pieChart){
        mFormat = format;
        mPieChart = pieChart;
    }


    @Override
    public String getFormattedValue(float value) {
        return mFormat.format(value) + "%";
    }

    @Override
    public String getPieLabel(float value, PieEntry pieEntry) {
        if (mPieChart != null && mPieChart.isUsePercentValuesEnabled()) {
            // Converted to percent
            return getFormattedValue(value);
        } else {
            // raw value, skip percent sign
            return mFormat.format(value);
        }
    }
}
```
Use above class in  your code.

```
pieData.setValueFormatter(new MyValueFormatter(mFormat, pieChart));

pieChart.setUsePercentValues(true);
```
User Above line to for formated percent value. pass percent format and piechart.

**Comment by mohmdlabeeb** [comment]
For Kotlin use,

pieDataSet.valueFormatter = PercentFormatter(PieChart)
PieChart.setUsePercentValues(true)

**Comment by ardhanmz** [comment]
all solution above working well. passing argument piechart to formatter and set piechart to use percentvalues. dont forget add piedataset a valueformatter
