### ISSUE TITLE
Pie chart show image in hole 

### ISSUE THREAD

**Issue by talhahasanzia** [PhilJay/MPAndroidChart#2125]
I know how to draw images on canvas I cant find place to write code, in android the files are locked, when I download them it fails. The logic I perceive is not tested, but I need to try atleast. For that I need help where I should tweak the code (In which class pie chart or pie chart renderer or data renderer)?

I downloaded as jar and placed in libs. Other things are working fine. But I cant edit.

Thanks.

**EDIT**

*Temporary fix*

I set hole color as transparent, using this line:

`mChart.setHoleColor( Color.argb(0,0,0,0));`

Then set an image view at same location with padding and other positional adjustments, it works but only when legends are disabled. Otherwise the image position is not the same as before.

**Comment by PhilJay** [comment]
Thats currently not possible by default.

You can have a look at the `PieChartRenderer` and modify the rendering of the chart there. Simply clone the repository for that.
