### ISSUE TITLE
"maxVisibleValueCount" didn't work 

### ISSUE THREAD

**Issue by Misilence** [PhilJay/MPAndroidChart#2129]
I saw that "the number of maximum visible drawn values on the chart only active when setDrawValues() is enabled",and I did it ;but nothing have changed.I want to display part of dataset on screen ,scrolling can get more data .I am waiting for help...

**Comment by PhilJay** [comment]
Show some code.

**Comment by Misilence** [comment]
@PhilJay  Thanks for your reply.I need to add a lineChartView in the contentView of tableViewCell. The following is all about lineChartView code

- (LineChartView *)lineChartView {
    if(_lineChartView == nil) {
        _lineChartView                               = [[LineChartView alloc] init];
        _lineChartView.noDataTextDescription         = @"请先导入数据";
        _lineChartView.drawGridBackgroundEnabled     = NO;
        _lineChartView.dragEnabled                   = YES;
        _lineChartView.pinchZoomEnabled              = NO;
        ChartXAxis *xAxis                            = _lineChartView.xAxis;
        xAxis.labelPosition                          = XAxisLabelPositionBottom;
        xAxis.labelFont                              = [UIFont fontWithName:@"HelveticaNeue-Light" size:6.f];
        _lineChartView.rightAxis.enabled             = NO;
        ChartYAxis *leftAxis                         = _lineChartView.leftAxis;
        leftAxis.labelFont                           = [UIFont fontWithName:@"HelveticaNeue-Light" size:6.f];
        leftAxis.labelTextColor                      = UIColor.darkGrayColor;
        _lineChartView.leftAxis.drawGridLinesEnabled = NO;
        _lineChartView.xAxis.drawGridLinesEnabled    = NO;
        _lineChartView.legend.enabled = NO;
        _lineChartView.scaleYEnabled = NO;
        
    }
    return _lineChartView;
}

///add data
- (void)setChannelIndex:(NSInteger)channelIndex{
    _channelIndex = channelIndex;
    NSArray *eegContinuousData = self.eegData.continuousData[_channelIndex];
    NSMutableArray *xVals = [[NSMutableArray alloc] init];
    NSMutableArray *yVals = [[NSMutableArray alloc] init];

   // "count" is big very much,so that the line of the chart all crowded together  
    NSInteger count = eegContinuousData.count ;
    for (int xIndex = 0;  xIndex < count; xIndex ++) {
        NSString *st =[NSString stringWithFormat:@"%.4g",xIndex * 0.002];
        [xVals addObject:st];
        [yVals addObject:[[ChartDataEntry alloc] initWithValue:[eegContinuousData[xIndex] floatValue] xIndex:xIndex]];
    }
    LineChartDataSet *lineChartDataSet = [[LineChartDataSet alloc] initWithYVals:yVals label:nil];
    lineChartDataSet.drawValuesEnabled = YES;
    [lineChartDataSet setColor:[UIColor blackColor]];
    lineChartDataSet.lineWidth = 1.0;
    lineChartDataSet.drawCircleHoleEnabled = NO;
    lineChartDataSet.drawCirclesEnabled  = NO;
    lineChartDataSet.valueFont = [UIFont systemFontOfSize:9.f];
    NSMutableArray *dataSets = [NSMutableArray array];
    [dataSets addObject:lineChartDataSet];
    LineChartData *data = [[LineChartData alloc] initWithXVals:xVals dataSets:dataSets];
    self.lineChartView.data = data;
    [self.lineChartView.data setDrawValues:YES];
    self.lineChartView.maxVisibleValueCount = 1000;
}
It look like this(I don't know whether you can see this picture, it doesn't matter if you don't can):
![1644bc0f-cdae-494c-b618-bb82d6329604](https://cloud.githubusercontent.com/assets/16147900/17642255/09b1559e-6171-11e6-8a15-cfa75fe525cf.png)

**Comment by PhilJay** [comment]
The way I see it is that you are confusing "maxVisibleCount" with "visibleXRange".

- `maxVisibleCount`: Controls the number of labels that are drawn until drawing of labels (only) stops. 
- `visibleXRange`: Controls the maximum number of visible entries on the chart area. Zooming out further than the visibleXRange is not possible.

Have a look at the [modifying the viewport](https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport) documentation chapter.

**Comment by Misilence** [comment]
@PhilJay  Thanks very much,I understand it.wish you a nice day
