### ISSUE TITLE
Labels for X axis cut off

### ISSUE THREAD

**Issue by edbond** [PhilJay/MPAndroidChart#2137]
Please see the screenshot
![2016-08-11_15-49-02](https://cloud.githubusercontent.com/assets/1044/17589094/6922920a-5fdb-11e6-85c9-03c53c42ce7f.png)

Month names are cut off.
Library version is
    compile 'com.github.PhilJay:MPAndroidChart:v2.2.5'

Let me know if you need more information.

**Comment by PhilJay** [comment]
does this still occur in v3?

**Comment by edbond** [comment]
Sorry, I didn't test yet. I tried to update the version of the library and there is so much changes.
Let me try to create a minimal project and then test using version 3.

**Comment by PhilJay** [comment]
Yep, the changes are huge :-D, let me know when you have tested it, thanks.

**Comment by edbond** [comment]
It seems that offset a slightly bigger for custom fonts. I use
    compile 'uk.co.chrisjenx:calligraphy:2.2.0'
and OpenSans fonts

Here is a default font (actually the 'y' in 'May' is very close to the bottom):
![2016-08-11_20-14-26](https://cloud.githubusercontent.com/assets/1044/17597887/8a20b746-6000-11e6-9af1-fa12db7b1f3a.png)

and here is a result of:
```
        Typeface light = TypefaceUtils.load(this.getAssets(), "fonts/OpenSans-Light.ttf");
        xAxis.setTypeface(light);
```
![2016-08-11_20-14-56](https://cloud.githubusercontent.com/assets/1044/17597906/9f6e250c-6000-11e6-96a1-861e480a818a.png)


Should I try the 3.0 beta version?

**Comment by edbond** [comment]
I got it working by adding extra offsets:
```
            chart.setExtraOffsets(10, 10, 10, 10);
```

Works fine with v2 and v3 and a custom font.

![2016-08-11_21-07-34](https://cloud.githubusercontent.com/assets/1044/17599469/e62ed39a-6007-11e6-98c4-eadb89d23d61.png)

Thanks!

**Comment by PhilJay** [comment]
Okay, that's sort of a workaround. This still should not happen even with custom fonts, thanks for the report!
