### ISSUE TITLE
how to set the values in x axis to second？

### ISSUE THREAD

**Issue by feixiangsmile** [PhilJay/MPAndroidChart#2139]
I have a project ， I need to show dates - for each second  I have a single value on X axis. I want to be sure that the vertical grid axis on X matches the x position of the value and thus display a label on the X axis with the date. I read the code in  LineChartTime.java . But I find there is a single value per hour  on X axis . When I change the time to second ( in other words, there is a value per second), the code `new Entry(x, y)` will make the x to a same value( maybe the interval between two values is small, the float type take them as a same value ).
      so, how I can use or set something to satisfy my need?

**Comment by PhilJay** [comment]
You cannot "set" the x-axis to seconds. That would not make any sense.

You yourself decide how the x-axis looks like by the data you provide and the way you place it in the chart.

An x-axis range from 0 to 100 can represent seconds, but it can also represent years, depending on the data you provide and the way you set it.

If you have 100 data values representing seconds and you set their x-position to 0, 1, 2, 3, ... then your x-axis is "in seconds". If you have 100 data values representing years and you set their x-position to 0, 1, 2, 3, ... then your x-axis is "in years".

**Comment by feixiangsmile** [comment]
Yes. I have resolved the problem. 

And , when I set false about  drawing the grid lines for this x-axis,   are  there sth to set to indicate the position of the labels of x-axis? e.g. there is a very short gridline on the x-axis line @PhilJay

**Comment by PhilJay** [comment]
Alright. There is currently no way to show very short lines, you will have to modify the library to achieve this.
