### ISSUE TITLE
 maybe a bug when use xAxis.setGranularity(1) and  xAxis.setLabelCount(4,true)  ?

### ISSUE THREAD

**Issue by feixiangsmile** [PhilJay/MPAndroidChart#2147]
In the demo project , for example in  LineChartActivity1.java , after I add code " xAxis.setGranularity(1);" and " xAxis.setLabelCount(4,true); ",  when I zoom in , I find there are many same values for each xaxis label ( in the visible regin there are 4 same values).  Maybe is it a bug?

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
