### ISSUE TITLE
class BarData does not have a constructor looks like public BarData(List<IBarDataSet> dataSets) { ... }

### ISSUE THREAD

**Issue by yunair** [PhilJay/MPAndroidChart#2148]
I want to  plot data coming directly from the realm. So I read this wiki. `https://github.com/PhilJay/MPAndroidChart-Realm/wiki/Realm.io-database-integration`
In this wiki, it says
> 
After creating the DataSet, we need to add it to a BarData object. The class BarData a constructor that looks like this:
~~~ java
public BarData(List<IBarDataSet> dataSets) { ... }
~~~

But I can't find this constructor in version 2.2.5.

**Comment by PhilJay** [comment]
This is because you are not using the latest version of the library.

**Comment by yunair** [comment]
But This tutorial mentions ` since v2.2.0` ,  and  it does not say only for `v3.0.0 or later` , so this will confuse user. I think this wiki need to update
