### ISSUE TITLE
Bar Chart:Issue when I tried to integrate it on my code

### ISSUE THREAD

**Issue by BAristide** [PhilJay/MPAndroidChart#2149]
Hello dear all,

I hvave tried to add Bar Chart in my Code, nothing appaer whan I launch my app.

The target of my code is that: When the user enter the start date (StartDate),  end date (EndDate) and the product name. The graph should show the show price evolution during that period.

I have tried the code below, but nothing appear on the graph.

Please help to find the issue, or propose to me another code.

public class ResultProductStatisticsActivity extends AppCompatActivity {

    private String mCategory;
    private String mName;
    private long mStartDate;
    private long mEndDate;
    private int mNumber = 0;
    private ProgressBar mProgressBar;
    private ArrayList<ShopDetail> mDetail = new ArrayList<ShopDetail>();

    private ArrayList<Float> mPriceList = new ArrayList<Float>();
    protected Typeface mTfLight;
    private  Typeface mTypeFaceLight;

    private TextView mMontextViewtest;

    private BarChart mChart;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
                WindowManager.LayoutParams.FLAG_FULLSCREEN);
        setContentView(R.layout.result_product_statistics_activity);

        mChart = (BarChart) findViewById(R.id.m_barchart);
       // mChart.setOnChartValueSelectedListener(this);

        mChart.setDrawBarShadow(false);
        mChart.setDrawValueAboveBar(true);

        mChart.setDescription("");

        // if more than 60 entries are displayed in the chart, no values will be
        // drawn
        mChart.setMaxVisibleValueCount(60);

        // scaling can now only be done on x- and y-axis separately
        mChart.setPinchZoom(false);

        mChart.setDrawGridBackground(false);
        // mChart.setDrawYLabels(false);

        AxisValueFormatter xAxisFormatter = new DayAxisValueFormatter(mChart);

        XAxis xAxis = mChart.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setTypeface(mTfLight);
        xAxis.setDrawGridLines(false);
        xAxis.setGranularity(1f); // only intervals of 1 day
        xAxis.setLabelCount(7);
        xAxis.setValueFormatter(xAxisFormatter);

        AxisValueFormatter custom = new MyAxisValueFormatter();

        YAxis leftAxis = mChart.getAxisLeft();
        leftAxis.setTypeface(mTfLight);
        leftAxis.setLabelCount(8, false);
        leftAxis.setValueFormatter(custom);
        leftAxis.setPosition(YAxis.YAxisLabelPosition.OUTSIDE_CHART);
        leftAxis.setSpaceTop(15f);
        leftAxis.setAxisMinValue(0f); // this replaces setStartAtZero(true)

        YAxis rightAxis = mChart.getAxisRight();
        rightAxis.setDrawGridLines(false);
        rightAxis.setTypeface(mTfLight);
        rightAxis.setLabelCount(8, false);
        rightAxis.setValueFormatter(custom);
        rightAxis.setSpaceTop(15f);
        rightAxis.setAxisMinValue(0f); // this replaces setStartAtZero(true)

        Legend l = mChart.getLegend();
        l.setPosition(Legend.LegendPosition.BELOW_CHART_LEFT);
        l.setForm(Legend.LegendForm.SQUARE);
        l.setFormSize(9f);
        l.setTextSize(11f);
        l.setXEntrySpace(4f);
        // l.setExtra(ColorTemplate.VORDIPLOM_COLORS, new String[] { "abc",
        // "def", "ghj", "ikl", "mno" });
        // l.setCustom(ColorTemplate.VORDIPLOM_COLORS, new String[] { "abc",
        // "def", "ghj", "ikl", "mno" });
        init();

        mChart.setMarkerView(new XYMarkerView(this, xAxisFormatter));
    }

    private void init(){
        mCategory = Myrecord.getSearchShopCategory(this);
        mName = Myrecord.getSearchShopName(this);
        mStartDate = Myrecord.getSearchStartTime(this);
        mEndDate = Myrecord.getSearchEndTime(this);

        if(mStartDate == -1){
            mStartDate = Long.MIN_VALUE;
        }
        if(mEndDate == -1){
            mEndDate = Long.MAX_VALUE;
        }

        Thread thread = new Thread(){
            @Override
            public void run() {

                MyDB db = new MyDB(ResultProductStatisticsActivity.this);
                ArrayList<MyDetail> detailList = db.getMyDetailByAll(mCategory, mName, -1, 0, -1);

                for(int i = 0; i < detailList.size(); i ++){
                    MyDetail detail = detailList.get(i);
                    long date = detail.date;

                    if(date >= mStartDate && date <= mEndDate){
                
                        mPriceList.add(db.getPriceGoodsByOwnName("ALEVONS")+0f);
                    }
                }

                ResultProductStatisticsActivity.this.runOnUiThread(new Runnable() {

                    @Override
                    public void run() {
                         setData(mPriceList);
                    }
                });
            }

        };
        thread.start();
    }

    private void setData(ArrayList<Float> mPriceList) {
	
        mChart.getXAxis().setAxisMinValue(mStartDate);
        mChart.getXAxis().setAxisMaxValue(mEndDate);

        ArrayList<BarEntry> yVals1 = new ArrayList<BarEntry>();

        for (int i = 0; i < mPriceList.size(); i++) {
            yVals1.add(new BarEntry(i , mPriceList.get(i)));
        }

        BarDataSet set1;

        if (mChart.getData() != null &&
                mChart.getData().getDataSetCount() > 0) {
            set1 = (BarDataSet) mChart.getData().getDataSetByIndex(0);
            set1.setValues(yVals1);
            mChart.getData().notifyDataChanged();
            mChart.notifyDataSetChanged();
        } else {
            set1 = new BarDataSet(yVals1, "Evolution du prix produit");
            set1.setColors(ColorTemplate.MATERIAL_COLORS);

            ArrayList<IBarDataSet> dataSets = new ArrayList<IBarDataSet>();
            dataSets.add(set1);

            BarData data = new BarData(dataSets);
            data.setValueTextSize(10f);
            data.setValueTypeface(mTfLight);
            data.setBarWidth(0.9f);

            mChart.setData(data);
        }
    }

}

**Comment by PhilJay** [comment]
I suggest you check the data you feed to the chart and see if it is correct. Especially `mStartDate` and `mEndDate`.
