### ISSUE TITLE
Just download the demo, the piechart activity inside setdata seekbar according to the code data set piechat commented, adding only a very simple array inside the data, but the chart just did not go in the color, click on what part of that part there is color, but do not the block is still no color, really do not understand, please enlighten

### ISSUE THREAD

**Issue by imgod1** [PhilJay/MPAndroidChart#2151]
Just download the demo, the piechart activity inside setdata seekbar according to the code data set piechat commented, adding only a very simple array inside the data, but the chart just did not go in the color, click on what part of that part there is color, but do not the block is still no color, really do not understand, please enlighten

private double[] data = {1, 1, 1, 1};
//        for (int i = 0; i < count; i++) {
//            entries.add(new PieEntry((float) ((Math.random() * mult) + mult / 5), mParties[i % mParties.length]));
//        }

        for (int i = 0; i < data.length; i++) {
            PieEntry pieEntry = new PieEntry((float) data[i], "T:" + i);
            entries.add(pieEntry);
        }

**Comment by PhilJay** [comment]
Sorry man, I just don't understand.

**Comment by imgod1** [comment]
oh,im so sorry for my poor english,
the problem is:
in the piechart activity
Method setData(int ,int)
// for (int i = 0; i < count; i++) {
// entries.add(new PieEntry((float) ((Math.random() * mult) + mult / 5), mParties[i % mParties.length]));
// }

replace to 
private double[] data = {1, 1, 1, 1};
for (int i = 0; i < data.length; i++) {
        PieEntry pieEntry = new PieEntry((float) data[i], "T:" + i);
        entries.add(pieEntry);
    }
the chart is crazy...
