### ISSUE TITLE
BarDataSet Label Color(v2.2.5)

### ISSUE THREAD

**Issue by sekomod** [PhilJay/MPAndroidChart#2152]
I didn't find BarDateSet label color property. Actually there is a property which name is "setValueTextColor" but that's not what I'm looking for. Is there a way for change label's color?
BarDataSet dataset = new BarDataSet(yVals1, "Base Stats");
![20160815_102603](https://cloud.githubusercontent.com/assets/1280839/17658261/1eb74a08-62d3-11e6-9080-e42af2b43583.png)

**Comment by PhilJay** [comment]
`chart.getLegend().setTextColor(...)`

**Comment by FirstSpectr** [comment]
That set color for legend labels too, how to set color only for dataset label?
