### ISSUE TITLE
how to set dual y-axis in combinedchart

### ISSUE THREAD

**Issue by dancingalone** [PhilJay/MPAndroidChart#2154]
I am using the combinedchart to display a linechart and a barchart. as the requirement, i need to set the different scale y-axis , so what is the solution?

**Comment by Stevemaster92** [comment]
I am facing the same or a similar problem where I want to have two y-axes belonging to different data and scale, like this [example](https://help.salesforce.com/resource/HTHelpDocImages_202_16_en_US_3/reports_combination_charts_line-on-column.png).
The left axis belongs to the barchart whereas the right one belongs to the linechart.

**Comment by PhilJay** [comment]
`lineDataSet.setAxisDependency(AxisDependency.LEFT)`
`barDataSet.setAxisDependency(AxisDependency.RIGHT)`

Then scale your left and right axis the way you want.
