### ISSUE TITLE
Formatters are not available when importing library using gradle in android studio

### ISSUE THREAD

**Issue by tenzinsamten** [PhilJay/MPAndroidChart#2155]
i imported the library as instructed 

dependences {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.github.PhilJay:MPAndroidChart:v3.0.0-beta1'
}
 and 

allprojects {

    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
so when i try to any formatter , it is not available 

but if i add the library project as 

dependencies {
    compile project(':MPChartLib')
    compile 'com.android.support:appcompat-v7:23.1.1'
}
it works fine.

**Comment by PhilJay** [comment]
Are you talking about `IValueFormatter` and `IAxisValueFormatter`?

Those are not in a release yet, this is why they are not available via jitpack. A new release will be out soon and then you can get them via jitpack.

**Comment by tenzinsamten** [comment]
yes, i was trying IAxisValueFormatter and ColorFormatter. So to use XAxisValueFormatter , i have to use the previous version of the library?

**Comment by tenzinsamten** [comment]
Thank u .. i revert back to v2.2.5 and using XAxisValueFormatter for while. Thank you for your prompt reply. Have a nice day. cheers..
