### ISSUE TITLE
reduce size of piechart 

### ISSUE THREAD

**Issue by NaveenJayaram1994** [PhilJay/MPAndroidChart#2156]
how to reduce the grid size which shows the % in the piechart . please help me 
![issue](https://cloud.githubusercontent.com/assets/20768701/17695267/6c05938a-63c5-11e6-84cf-673366b04bc8.jpg)

**Comment by PhilJay** [comment]
What do you mean by "grid"?

**Comment by NaveenJayaram1994** [comment]
sorry i dont know what its called. that bar in piechart with blue color which shows the percentage.
i want to reduce that bar size . please help

**Comment by PhilJay** [comment]
`pieChart.setHoleRadius(...)` might be what you are looking for.

**Comment by NaveenJayaram1994** [comment]
it dint work

**Comment by azri92** [comment]
@NaveenJayaram1994 If you're talking about the actual "pie" section or in other words, the outer circle, I think that one follows the layout_width & layout_height of the pie that you set in XML. If you set them to "match_parent", then it depends on the parent view.

**Comment by TobiasJoergensen** [comment]
If this is still a relevant thread, I might suggest the following:
        float x = 0;
        pieChart.setDrawHoleEnabled(true);
        pieChart.setHoleRadius(x);

The hole radius sets the size of the hole in the middle, and will just make the size of the pie smaller.
If you want to get rid of the transparent cirlcle, don't set the transparent cirlce or set it to 0f.

Hope it helps.

**Comment by wseng92** [comment]
> If this is still a relevant thread, I might suggest the following:
> float x = 0;
> pieChart.setDrawHoleEnabled(true);
> pieChart.setHoleRadius(x);
> 
> The hole radius sets the size of the hole in the middle, and will just make the size of the pie smaller.
> If you want to get rid of the transparent cirlcle, don't set the transparent cirlce or set it to 0f.
> 
> Hope it helps.

It will just make the hole smaller, but the outer circle width become bigger.

**Comment by waqasdevel** [comment]
val x = 80f
        binding!!.ivPie.isDrawHoleEnabled = true

        binding!!.ivPie.setHoleColor(Color.TRANSPARENT)
        binding!!.ivPie.holeRadius = x
        
        it will work for me
