### ISSUE TITLE
RE: References

### ISSUE THREAD

**Issue by Enteleform** [PhilJay/MPAndroidChart#2157]
Not really an issue, but figured I'd send this your way since some of the listed apps aren't mentioned on your [**References**](https://github.com/PhilJay/MPAndroidChart/wiki/References) page.

# [AppBrain > MPAndroidChart](http://www.appbrain.com/stats/libraries/details/mpandroidchart/mpandroidchart)

![capture](https://cloud.githubusercontent.com/assets/10906415/17698537/ce2d5b10-6389-11e6-9fd0-6594e707746c.PNG)

Not sure how how they verify libraries, but if it's accurate then I'm sure Instagram & Uber would make for nice additions to your Reference page : )

**Comment by PhilJay** [comment]
Thank's man, I wasn't aware tbh :-)
I only knew about Periscope for Android.

I will definitely add those.
