### ISSUE TITLE
iOS computeAxis for YAxisRenderer doesn't work.

### ISSUE THREAD

**Issue by afloury** [PhilJay/MPAndroidChart#2159]
When I make my graph with all the values, the YAxis take a very very large marge above the highest point, 
![screen shot 2016-08-16 at 15 40 18](https://cloud.githubusercontent.com/assets/18677074/17700884/d9ae52da-63c7-11e6-8481-3cbb2a1c1e48.png)
it's not the same result than Android version, it seems that the computeAxis doesn't work fine, I try to get the minimum and maximum value and call `computeAxis` myself :
`graph.leftYAxisRenderer.computeAxis(yMin: minimumValue, yMax: maximumValue)`
It's the same. I also try to call calculate `graph.leftAxis.calculate(min: minimumValue, max: maximumValue)`, always the same result.
The best result I got is when I set `axisMaxValue` like that :
`lineChartView.leftAxis.axisMaxValue = maxValueWithMargin
lineChartView.data?.notifyDataChanged()
lineChartView.notifyDataSetChanged()`
but I have to calculate the margin myself.

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
