### ISSUE TITLE
Bar Chart: Same value one X entries

### ISSUE THREAD

**Issue by BAristide** [PhilJay/MPAndroidChart#2162]
I have tried to add dynamically date one X entries.
but I got at eech time the same date one X entries.

I have modify the public class DayAxisValueFormatter like below:
private BarLineChartBase<?> chart;
private String[] mValues;
private ArrayList<Long> mDateList = new ArrayList<Long>();
private int mSize;

public DayAxisValueFormatter(BarLineChartBase<?> chart, ArrayList<Long> DateList, int size) {
    this.chart = chart;
    this.mDateList = DateList;
    this.mSize = size;
}
@Override
public String getFormattedValue(float value, AxisBase axis) {
    return longToStringForTimeReal(mDateList.get( mSize));
}
public static String longToStringForTimeReal(long time) {
    Date date = new Date(time);
    SimpleDateFormat simpleDate = new SimpleDateFormat("yyyy/MM/dd");
    return simpleDate.format(date);
}
.......

And I call it like this:

AxisValueFormatter xAxisFormatter = new DayAxisValueFormatter(mChart,mDateList, mDateList.size());
xAxis.setValueFormatter(xAxisFormatter);

I have attached one image for the result.

![screeshot2](https://cloud.githubusercontent.com/assets/20907053/17709104/5e6e6848-63d7-11e6-88ec-1f489dd9c5b7.png)

Please help me to find the issue.

**Comment by PhilJay** [comment]
Thats because you are always using the same date object:

```java
@Override
public String getFormattedValue(float value, AxisBase axis) {
    return longToStringForTimeReal(mDateList.get(mSize));
}
```

The field `mSize` is initially set and never changes. Please review your code before opening issues.

**Comment by BAristide** [comment]
Even when I use a variable i like mDateList.get(i), this one always initialized to zero
