### ISSUE TITLE
varargs mismatch; ArrayList<String> cannot be converted to IBarDataSet

### ISSUE THREAD

**Issue by androidlool** [PhilJay/MPAndroidChart#2163]
i have a prob using BatData here is my code it shows an error at : 
BarData Data = new BarData(Date,depenses);

`package gdf.gestiondesfrais.statistics;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

import com.github.mikephil.charting.charts.BarChart;
import com.github.mikephil.charting.data.BarData;
import com.github.mikephil.charting.data.BarDataSet;
import com.github.mikephil.charting.data.BarEntry;
import com.github.mikephil.charting.utils.ColorTemplate;

import java.util.ArrayList;

import gdf.gestiondesfrais.R;

public class statistique extends AppCompatActivity {

    BarChart barChart;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_statistique);

        barChart = (BarChart)findViewById(R.id.stats_chart);

        ArrayList<BarEntry> entries = new ArrayList<>();
        entries.add(new BarEntry(4f, 0));
        entries.add(new BarEntry(8f, 1));
        entries.add(new BarEntry(6f, 2));
        entries.add(new BarEntry(12f, 3));
        entries.add(new BarEntry(18f, 4));
        entries.add(new BarEntry(9f, 5));

        BarDataSet depenses = new BarDataSet(entries, "depenses");

        ArrayList<String> Date = new ArrayList<>();
        Date.add("2/7/2016");
        Date.add("3/7/2016");
        Date.add("5/7/2016");
        Date.add("6/7/2016");
        Date.add("23/7/2016");
        Date.add("30/7/2016");

        BarData Data = new BarData(Date,depenses);
        barChart.setData(Data);

        barChart.setTouchEnabled(true);
        barChart.setDragEnabled(true);
        barChart.setScaleEnabled(true);
        barChart.animateXY(3000, 3000);
        barChart.setHorizontalScrollBarEnabled(true);
        barChart.setDoubleTapToZoomEnabled(true);
        barChart.setDescription("Dépenses");
        depenses.setColors(ColorTemplate.COLORFUL_COLORS);

    }
}
`

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Setting-Data

The constructor for `BarData` has changed in v3.0.0
