### ISSUE TITLE
Value text overlap on vertical StackedBarChart

### ISSUE THREAD

**Issue by 222xiaohuan** [PhilJay/MPAndroidChart#2164]
![chart](https://cloud.githubusercontent.com/assets/38194/17729398/961ff3be-6496-11e6-9f2d-224bbbf68799.png)

As showing in the image on the first bar, the value 0.5 should be in the red box, the value overlaps on the second value, anyone knows how to resolve this problem?

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
