### ISSUE TITLE
BarChart 3.0.0beta1,The last label does not show complete

### ISSUE THREAD

**Issue by tombcato** [PhilJay/MPAndroidChart#2165]
I don't wanna lable rotation，just show complete in chart，how can do it，please help me！

my code :
  XAxis x = mChart.getXAxis();
 BarDataSet set = new BarDataSet(values, "Values");
if (values != null && values.size() > 0) {
    if (values.size() > 1) {
        x = mChart.getXAxis();
        x.setLabelCount(2, true);
    }
}

![screenshot_2016-08-17-17-01-50-037_cn suncloud ko](https://cloud.githubusercontent.com/assets/10005665/17730721/b01ac068-649c-11e6-9f66-e795d925ad7b.png)

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
