### ISSUE TITLE
BaseDataSet.setValueTextSize problem

### ISSUE THREAD

**Issue by ymsf** [PhilJay/MPAndroidChart#2166]
`BaseDataSet.setValueTextSize(float)` expects values in dp but `BaseDataSet.getValueTextSize()` gives values in pixels.
Imo it should stick to either pixels or dp.
I had to look into source code to find why `LimitLine.setTextSize(LineDataSet.getValueTextSize());` wont work.
PS: This is how I'm making it work atm `LimitLine.setTextSize(convertPixelsToDp(LineDataSet.getValueTextSize()))`

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
