### ISSUE TITLE
Y-Max orientation on limitline

### ISSUE THREAD

**Issue by XxGoliathusxX** [PhilJay/MPAndroidChart#2169]
How to increase the y-axis range, so that the limitline shows up? For example, when the limitline yValue is set to 100 and the heighest value from my data is 99, I can't see or scroll so that the limitline shows up.

**Comment by PhilJay** [comment]
You can increase the range of your axis by calling `axis.setAxisMaximum(120f)`.

**Comment by XxGoliathusxX** [comment]
When I do this, I get a bug. The horizontal lines do not have a regular spacing between each other anymore
