### ISSUE TITLE
Add image on the middle of the pie chart

### ISSUE THREAD

**Issue by achercasky** [PhilJay/MPAndroidChart#2173]
Hi everybody, is it possible to add an image on the middle of the middle of the pie chart? I'm already showing a text but i will also want to show an image.

Is it possible?

**Comment by cauli** [comment]
@achercasky One way to do it is to extend the renderer of your corresponding chart (PieChartRenderer), then override one of the drawing methods of the original renderer:

```java
public class CustomPieChartRenderer extends PieChartRenderer {
    private Context context;

    public CustomPieChartRenderer(PieChart chart, ChartAnimator animator,
                            ViewPortHandler viewPortHandler) {
        super(chart, animator, viewPortHandler);
        context = chart.getContext();
    }

    @Override
    public void drawExtras(Canvas c) {
        super.drawExtras(c);
        drawImage(c);
    }

    private void drawImage(Canvas c) {
        MPPointF center = mChart.getCenterCircleBox();

        Drawable d =  ResourcesCompat.getDrawable(context.getResources(), R.drawable.ic_your_drawable, null);

        if(d != null) {
            float halfWidth = d.getIntrinsicWidth() / 2;
            float halfHeight = d.getIntrinsicHeight() / 2;

            d.setBounds((int) (center.x - halfWidth), (int) (center.y - halfHeight), (int) (center.x + halfWidth), (int) (center.y + halfHeight) );
            d.draw(c);
        }
    }
}
```

Then, in your activity or fragment, when you instantiate your chart you need to use your renderer and invalidate the standard one:

```java
mChart.setRenderer(new CustomPieChartRenderer(
        mChart,
        mChart.getAnimator(),
        mChart.getViewPortHandler()
));

// When seeing a new renderer, we need to invalidate the old one
mChart.invalidate();
```

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.

**Comment by yadavved** [comment]
Hi All,
this what I have done for set Image instead of text.

` private SpannableString generateCenterSpannableText() {
        ImageSpan imageSpan = new ImageSpan(context, R.drawable.ic_logo_new_over_round_drawable); //Find your drawable.

        SpannableString spannableString = new SpannableString(" "); //Set text of SpannableString from TextView
        spannableString.setSpan(imageSpan, " ".length() - 1, " ".length(), 0); //Add image at end of str

        return spannableString;
    }`

and then set into 

`mPieChart.setCenterText(generateCenterSpannableText());`

**Comment by edo26** [comment]
I found a tricky way i got it from my teacher/senior of android developer. You can use RelativeLayout like this :

<RelativeLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content">
                <com.github.mikephil.charting.charts.PieChart
                    android:id="@+id/piechart"
                    android:layout_width="match_parent"
                    android:layout_height="255dp"/>
                <ImageView
                    android:layout_width="35dp"
                    android:layout_height="35dp"
                    android:src="@drawable/ic_directions_car_24px"
                    android:layout_centerInParent="true"
                    />
            </RelativeLayout>
I hope it helpful

**Comment by Priyanka-Mohanty** [comment]
> @achercasky One way to do it is to extend the renderer of your corresponding chart (PieChartRenderer), then override one of the drawing methods of the original renderer:
> 
> ```java
> public class CustomPieChartRenderer extends PieChartRenderer {
>     private Context context;
> 
>     public CustomPieChartRenderer(PieChart chart, ChartAnimator animator,
>                             ViewPortHandler viewPortHandler) {
>         super(chart, animator, viewPortHandler);
>         context = chart.getContext();
>     }
> 
>     @Override
>     public void drawExtras(Canvas c) {
>         super.drawExtras(c);
>         drawImage(c);
>     }
> 
>     private void drawImage(Canvas c) {
>         MPPointF center = mChart.getCenterCircleBox();
> 
>         Drawable d =  ResourcesCompat.getDrawable(context.getResources(), R.drawable.ic_your_drawable, null);
> 
>         if(d != null) {
>             float halfWidth = d.getIntrinsicWidth() / 2;
>             float halfHeight = d.getIntrinsicHeight() / 2;
> 
>             d.setBounds((int) (center.x - halfWidth), (int) (center.y - halfHeight), (int) (center.x + halfWidth), (int) (center.y + halfHeight) );
>             d.draw(c);
>         }
>     }
> }
> ```
> 
> Then, in your activity or fragment, when you instantiate your chart you need to use your renderer and invalidate the standard one:
> 
> ```java
> mChart.setRenderer(new CustomPieChartRenderer(
>         mChart,
>         mChart.getAnimator(),
>         mChart.getViewPortHandler()
> ));
> 
> // When setting a new renderer, we need to invalidate the old one
> mChart.invalidate(); 
> ```

how to change the background color of holo in DrawExtra. I want to change the background color of holo, with iclude the image. In your logic. image is coming center. but background color is still remating white. How to change it ?
