### ISSUE TITLE
Issue in Adding Library

### ISSUE THREAD

**Issue by bhavikshah92** [PhilJay/MPAndroidChart#2174]
I'm getting issue in adding your project to my project. On below line I'm getting error as **"cannot resolve symbol LineChart"**
LineChart lineChart = (LineChart)rootView.findViewById(R.id.chart);

So can you tell me how can I add the library into my project

**Comment by PhilJay** [comment]
It's all in the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/Getting-Started).
