### ISSUE TITLE
setVisibleXRangeMaximum

### ISSUE THREAD

**Issue by BafanaM** [PhilJay/MPAndroidChart#2175]
Hi Phil,

I am using this library to draw a bar graph using data from the android call log. The X values represent all 30 days of the month. I have set the viewport to only display 5 days and then scroll to see the other days as follows:

mChart.setData(data)
mChart.setVisibleXRangeMaximum(5f)
mChart.invalidate()

The problem is that when the graph is initially created, it displays the 5 xValues data sets, then when i scroll to the left to view days 6 to 10 and so fourth, the bar data sets disappear and are not redrawn or refreshed. This shows an impression that there is no data for those days. However, if i don't set the visible x range, the data for the 30 days does get displayed. The problem comes when i set max values to be displayed. Please assist.

**Comment by BafanaM** [comment]
I have managed to fix the issue. It was the way i was retrieving data from the call log.

**Comment by NirLevanon** [comment]
@BafanaM , mind elaborating? I'm a tad bit stuck on this kind of issue lately.

**Comment by NirLevanon** [comment]
Found my issue. Some of these posts should give you a hint on how to get a rolling chart (after updating, you must call the sequence `chartView.notifyDataSetChanged()`, `chartView.moveViewToX(data.getEntryCount())` and `chartView.setVisibleXRangeMaximum(range)`:
https://github.com/PhilJay/MPAndroidChart/issues/562#issuecomment-94039698
https://github.com/PhilJay/MPAndroidChart/issues/983#issuecomment-152299035

The plugin is awesome, yet the Wiki is outdated.
