### ISSUE TITLE
CombinedChart Question

### ISSUE THREAD

**Issue by XxGoliathusxX** [PhilJay/MPAndroidChart#2177]
Is it possible for the CombinedChart that each graph has its own y-axis numbering? Take a look at my example^^. Or would you recommend another charttype?

![unbenannt](https://cloud.githubusercontent.com/assets/14278233/17826311/b7d3d824-666f-11e6-86ae-68557ee3bfd4.png)

**Comment by PhilJay** [comment]
Yes, that is possible. You can have your bars plot to the left axis of the chart, and your lines to the right axis.

All you need to do is set the `AxisDependency` for your `DataSet`.

e.g.:

```java

barDataSet.setAxisDependency(AxisDependency.LEFT);
lineDataSet.setAxisDependency(AxisDependency.RIGHT);
```

You can then format your axes as you wish. Detailed information about the `YAxis` can be found [here](https://github.com/PhilJay/MPAndroidChart/wiki/YAxis).

**Comment by XxGoliathusxX** [comment]
Thx a lot!
