### ISSUE TITLE
after using version 3.0.0beta1 nothing works properly 

### ISSUE THREAD

**Issue by pouyadanesh** [PhilJay/MPAndroidChart#2178]
So I was using last stable version 2.5.4 with jar file and it would create some charts but since the wiki was for last version and I needed some guidance I decided to update this lib to version 3.0.0 using gradle.
but after that compiler gives error to previous constructors but gradle build fails saying these constructors are wrong???!!!!
what am I doing wrong please help.
I updated my gradle and android studio to last version for this awesome library.
I have 10 errors like following : 
`    Error:(81, 21) error: no suitable constructor found for BarEntry(float,float)
     constructor BarEntry.BarEntry(float[],int) is not applicable
     (argument mismatch; float cannot be converted to float[])
     constructor BarEntry.BarEntry(float,int) is not applicable
     (argument mismatch; possible lossy conversion from float to int)`

and here is my code in activity: 
`     private void fillBarChart(BarChart chart) {
            List<BarEntry> entries = new ArrayList<BarEntry>();
       

        entries.add(new BarEntry(0f, 30f));
          entries.add(new BarEntry(1f, 80f));
        entries.add(new BarEntry(2f, 60f));
        entries.add(new BarEntry(3f, 50f));
        // gap of 2f
        entries.add(new BarEntry(5f, 70f));
        entries.add(new BarEntry(6f, 60f));

            BarDataSet dataSet = new BarDataSet(entries, "Test Label"); // add entries to dataset
        //             dataSet.setBarSpacePercent(50f);
                 dataSet.setColor(ColorTemplate.getHoloBlue());
            BarData barData = new BarData(dataSet);
           barData.setBarWidth(0.9f);
            chart.setData(barData);
           chart.setFitBars(true);
               chart.invalidate(); // refresh
       }`

and this is build.gradle dependencies : 
`     dependencies {
          compile fileTree(dir: 'libs', include: ['*.jar'])
          compile 'com.android.support:design:24.0.0'
          compile 'com.android.support:appcompat-v7:24.0.0'
          compile 'com.github.jakob-grabner:Circle-Progress-View:v1.2.9'
             compile 'com.android.support:cardview-v7:24.0.0'
          compile 'com.github.PhilJay:MPAndroidChart:v3.0.0-beta1'
     }`

by the way I think there is a problem somewhere in dependencies but I already tried syncing and cleaning and rebuilding the project.

**Comment by PhilJay** [comment]
Why dont you just look at the error messages and let your compiler propose a constructor?
As the messages clearly indicate, the constructors of e.g. BarEntry have changed.

For example:

```java
public BarEntry(float value, int xIndex)
```

changed to:

```java
public BarEntry(float x, float y)
```

This can also be seen in the [example project](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/Setting-Data#barchart) and in the [source code](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/main/java/com/github/mikephil/charting/data/BarEntry.java#L41-L83) itself.
