### ISSUE TITLE
Some functions do not exist

### ISSUE THREAD

**Issue by sakitA** [PhilJay/MPAndroidChart#2179]
with 3.0.0-beta1 LineData(dataSet, labels) constructor could not find. Also  lineChart.getAxisLeft().setShowOnlyMinMax() and lineChart.getXAxis().setLabelsToSkip() methods could not find

**Comment by PhilJay** [comment]
Yes, the x-values are no longer associated with the data object, instead the x-axis is treated like the y-axis, and now allows custom formatting of all values.

You can find an example in the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/Setting-Data).

**Comment by sakitA** [comment]
Thank you very much
