### ISSUE TITLE
HorizontalBarChart

### ISSUE THREAD

**Issue by Jefferson-Tavares** [PhilJay/MPAndroidChart#2180]
Hi! I'm using the latest version of the library and I can't get the HorizontalBarChart to draw the value above the bar, even after setting mChart.setDrawValueAboveBar(true) and invalidating the chart. Any is this a bug or is there a way to make his work?

**Comment by PhilJay** [comment]
What happens?
Can you provide a screenshot?

**Comment by tomoss1994** [comment]
Same problem here.
Code:
       `BarDataSet set = new BarDataSet(barEntries, "BarDataSet");`
       ` BarData data2 = new BarData(set);`
     `   set.setColors(new int[] { R.color.colorAccent,R.color.colorPrimary, R.color.colorPrimaryDark, R.color.colorPrimaryDark, R.color.colorAccent }, getActivity());`
     `   set.setDrawValues(true);`
      `  barChart.setDrawValueAboveBar(true);`
       ` data2.setBarWidth(0.4f);`
       ` barChart.setDescription("");`
        `barChart.setData(data2);`
       ` barChart.setDoubleTapToZoomEnabled(false);`
       ` barChart.setPinchZoom(false);`
      `  barChart.setClickable(false);`
`        barChart.setFitBars(true);`
      `  barChart.getXAxis().setEnabled(false);`
        `YAxis leftAxis = barChart.getAxisLeft();`
        `barChart.getAxisRight().setEnabled(false);`
       ` leftAxis.setEnabled(false);`
      `  barChart.setDrawGridBackground(false);`
        `barChart.animateXY(750, 750);`
      `  barChart.invalidate();`

Screenshot:
![screenshot_2016-09-01-14-03-43](https://cloud.githubusercontent.com/assets/9782734/18166800/71dc1b46-704d-11e6-9eaa-3d356ebd5868.png)

**Comment by Jefferson-Tavares** [comment]
My code was Basically the same. I decided to move to another chart because I had finish the app for a College presentation. It would be good to have this ficed though

**Comment by kwosu87** [comment]
+1 I have same issue too.

**Comment by Jefferson-Tavares** [comment]
Did you guys manage to solve this? I wanna use this chart but not sure if I should

**Comment by alecrespo** [comment]
Same here since v3

**Comment by MarkOSullivan94** [comment]
Seems to be an issue atm where the values wont be displayed unless there's at least one 0.0 value within your barEntries: https://github.com/PhilJay/MPAndroidChart/issues/2452

**Comment by GameChanger001** [comment]
I too Have the same issue and it is still not fixed in the Latest version Mp android 3.0.1

**Comment by MarkOSullivan94** [comment]
Spent a bit of time looking into this, I've now got it working where the labels are being drawn using the settings shown below. It shouldn't matter if you draw the labels inside or outside of the bars.

`        barData.setValueFormatter(new MyValueFormatter());
        barChart.getAxisRight().setEnabled(false);
        barChart.getAxisLeft().setEnabled(false);
        **barChart.getAxisLeft().setDrawAxisLine(true);
        barChart.getAxisLeft().setDrawGridLines(true);
        barChart.getAxisLeft().setAxisMinimum(0f);**
        barChart.setDrawGridBackground(false);
        barChart.setDrawBorders(false);
        barChart.setDrawValueAboveBar(false);
        barChart.getLegend().setEnabled(false);
        barChart.getDescription().setEnabled(false);
        barChart.getXAxis().setEnabled(true);
        barChart.getXAxis().setPosition(XAxis.XAxisPosition.BOTTOM);
        barChart.getXAxis().setDrawGridLines(false);
        barChart.getXAxis().setTextSize(12f);
        barChart.getXAxis().setDrawAxisLine(false);
        barChart.getXAxis().setTextColor(Color.WHITE);
        barChart.getXAxis().setLabelCount(numberOfEntries);
        barChart.setScaleEnabled(false);
        barChart.setDoubleTapToZoomEnabled(false);
        barChart.setPinchZoom(false);
        barChart.setData(barData);
        barChart.invalidate();`

I am not sure if these settings will work for everyone, hopefully it will but I haven't tested it out much. The code I added to get it to work for my app is in bold.

I did take a look into the library example app and got it to stop plotting the value labels using similar settings to what I had in my own application. Found that it would commonly have issues when dealing with a smaller amount of bars (9 or below) although if I set a break point and debugged the app, it'd add the label values fine.

`public void drawValues(Canvas c) {` on line 144 of HorizontalBarChartRenderer.java was being called, however there was something within that method going wrong because `protected void drawValue(Canvas c, String valueText, float x, float y, int color) {` wasn't being called.

Hopefully this information will help the people who work on this library identify a solution to this problem.

**Comment by GameChanger001** [comment]
Does it really Works With The latest Version v3.0.0 MpAndroidChart @MarkOSullivan94

**Comment by MarkOSullivan94** [comment]
I'm using it with v3.0.0 @GameChanger001

**Comment by TuanBC** [comment]
I also have this problem in version 3.0.1. Anyone have a solution for this?


        YAxis rightAxis = mChart.getAxisRight();
        rightAxis.setEnabled(false);
        Legend legend = mChart.getLegend();
        legend.setEnabled(false);

        YAxis leftAxis = mChart.getAxisLeft();
        leftAxis.setAxisMinimum(0);

        leftAxis.setAxisMaximum(50);
        leftAxis.setGranularity(1);
        leftAxis.setDrawGridLines(false);
        leftAxis.setTextSize(R.dimen.text_size_15sp);
        leftAxis.setDrawAxisLine(false);
        leftAxis.setDrawLabels(false);

        XAxis xAxis = mChart.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setDrawAxisLine(false);
        xAxis.setDrawGridLines(false);
        xAxis.setDrawLabels(false);

        mChart.setFitBars(true);
        mChart.setDescription(null);
        mChart.setNoDataText("Không có bình luận nào");
        mChart.setDrawValueAboveBar(true);
        mChart.setDoubleTapToZoomEnabled(false);
        mChart.setPinchZoom(false);
        mChart.setTouchEnabled(false);
        mChart.animateY(2000);
        mChart.setViewPortOffsets(30, -5, 0, -15);
        mChart.invalidate();

**Comment by lucadln** [comment]
Any solutions yet? I have the same problem.

https://github.com/PhilJay/MPAndroidChart/issues/3380

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
