### ISSUE TITLE
Is it possible to pause a real time graph (Line Graph) ?

### ISSUE THREAD

**Issue by srikanthNIS** [PhilJay/MPAndroidChart#2183]
I am working on graphs(Line Graph) in android by using MP Chart library. I don't know how to pause the real-time or running graph (Line Graph). Can anyone help me to sort out this problem.

Thanks in advance...

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.

**Comment by kartikay-mahajan** [comment]
Please tell how to start and pause real time graph using mp chart library
