### ISSUE TITLE
Horizontal BarChart Reversing Bar Order

### ISSUE THREAD

**Issue by AndreiAta** [PhilJay/MPAndroidChart#2184]
Hi Phil!
 Right now I am using your library to display some data obtained from two API calls in a Horizontal BarChart. I am saving the values in two ArrayLists of BarEntries and then drawing the chart.
My issue is that I would like to reverse the order of the bars, so its descending from highest to lowest.
Is it possible to change the order, after the entries have been added to the ArrayList of BarEntries?

![screenshot_2016-08-22-15-33-16 1](https://cloud.githubusercontent.com/assets/16190278/17856669/e8d83b84-687e-11e6-8123-103310592fb2.png)

That way, LinkedIn would be on top, and Twitter at the bottom.

Thank you for your time and awesome library!

**Comment by MarkOSullivan94** [comment]
@AndreiAta did you find a way to do this?

**Comment by Sunsiha** [comment]
Have you got any solution for this?

**Comment by AndreiAta** [comment]
Hi guys sorry for responding so late I don't remember exactly but I think I just reversed my array going into the chart. Sorry I don't remember too well I might have given up on it.

**Comment by Sunsiha** [comment]
Oh am really stuck with it.When am trying to reverse it the bar entry is
properly reversing but bar entry labels not reversing properly.If possible
help me.

*Regards,*

*Sunisha.K.R*

**Comment by Sunsiha** [comment]
some other way i have done.

**Comment by MarkOSullivan94** [comment]
@Sunsiha I posted on SO seeking help and was lucky to receive an answer which helped me: http://stackoverflow.com/questions/41655150/mpandroidchart-how-to-reverse-the-order-of-a-horizontalbarchart

**Comment by alexnuts** [comment]
I had the same issue with range of grouped bars

`
            val set1 = BarDataSet(listOf(
                    BarEntry(1F, floatArrayOf(7F, 7F, 7F)),
                    BarEntry(2F, floatArrayOf(5F, 5F, 5F)),
                    BarEntry(3F, floatArrayOf(3F, 3F, 3F))

            ).reversed(), "Label 1")
            bars.add(set1)

            val set2 = BarDataSet(listOf(
                    BarEntry(1F, floatArrayOf(5F, 6F, 6F)),
                    BarEntry(2F, floatArrayOf(4F, 4F, 4F)),
                    BarEntry(3F, floatArrayOf(2F, 2F, 2F))
            ).reversed(), "Label 2")
            bars.add(set2)

            val data = BarData(bars.map { it }.reversed())
            barChart.data = data

// handle grouping of items
`
