### ISSUE TITLE
BubbleChart, BubbleEntry, the size variable doesn't change the actually size. 

### ISSUE THREAD

**Issue by wiccy46** [PhilJay/MPAndroidChart#2185]
Following the example:

```
    for (int i = 0; i < count; i++) {
        float val = (float) (Math.random() * range);
        float size = (float) (Math.random() * range );
        yVals1.add(new BubbleEntry(i, val, size));
    }
```

When I tried to increase the size: float size = (float) (Math.random() \* range \* 10 );

The result of the bubble size remains the same. 

For my bubble plot, my data set range from (0 ~ 1000), however, each bubble size is still less than 1.0. This makes the data points invisible. 

Is there anyway way to set the absolute bubble radius?

**Comment by yusufnacir** [comment]
You have to set normalizesize of dataset:
 jBubbleDataSet.setNormalizeSizeEnabled(false);

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
