### ISSUE TITLE
How can I implement a bar chart window to slide with finger and view large amount of bars

### ISSUE THREAD

**Issue by ZekunWang** [PhilJay/MPAndroidChart#2186]
How can I implement a bar chart like a sliding window that I can only view 5 out of 20 bars and move bars left or right to view different bars? 

I also wish to be able to specify the position of the chart window

**Comment by imp8468** [comment]
@ZekunWang 试试BarChart.animateXY()和BarChart.zoomAndCenterAnimated()方法吧:)

**Comment by ZekunWang** [comment]
@imp8468  谢谢! Thanks for the method names and I solve the view port problem with setVisibleXRangeMaximum(). 

This is original chart with all bars:
![image](https://cloud.githubusercontent.com/assets/14100634/17952469/64ac6f16-6a30-11e6-926e-035a5a01f5d9.png)

This is chart with  mChart.setVisibleXRangeMaximum(5f);
![image](https://cloud.githubusercontent.com/assets/14100634/17952516/c7240366-6a30-11e6-8088-349c112c2ea8.png)


However, the x axis labels are in a mess. Do you know how to fix it?

**Comment by NeoLSN** [comment]
Same issue.

**Comment by ZekunWang** [comment]
@NeoLSN  I think the problem is that the view port is too small, so the x axis can only display 0, 1.5, 3, 4.5..... However, the bars are located at 0, 1, 2, 3, 4... And you probably set labels at x axis as label[(int) value], where label is the array of labels. So in the view port, the labels are : 0 -> label[0], 1.5 -> label[1], 3 -> label[3], 4.5 -> labe[4],  and 1, 2, 4 do not even show. That's why the labels are in a mess.

My dump solution is to make the view port include more bars so that x axis can show all integers. When showing the labels, if  value % 1 != 0, make it return "", otherwise return label[(int) value]. This solution works for me.

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
