### ISSUE TITLE
Horizontal Bar Chart no margins

### ISSUE THREAD

**Issue by thekekc** [PhilJay/MPAndroidChart#2188]
I was trying to implement stacked horizontal bar chart without any labels, margins and so forth. I was able to remove everything from chart, exept colored bars. Thank you for nice documentation and stackoverflow help. 
The only thing that I could not remove were margins that chart had. According to stackoverflow i used .setViewPortOffsets() method to get rid of margins, but it did not work. The only thing that maked this happen was setting protected property mMinOffset to 0 in  BarLineChartBase class. So I spent some time debugging, and found out that calculateOffsets() method in HorizontalBarChart always resets mHandlerViewport.mViewPortHandler.restrainViewPort(), setted by .setViewPortOffsets() of base class.  So I think calculateOffsets() method in HorizontalBarChart should know about if we using customViewPort or not. But this property is private in Base class. So if it is ok to make it protected I can make a pull request for this issue. Thank you.

**Comment by adeperio** [comment]
+1 for this

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
