### ISSUE TITLE
Piecharts on low-DPI screens gain considerable padding

### ISSUE THREAD

**Issue by jesopo** [PhilJay/MPAndroidChart#2189]
![piechart](http://i.imgur.com/auETE7n.png)

The blue lines on either side are android showing layout bounds; there's a considerable amount of space between the piechart and the FrameLayout it's in, causing unpredictable behavior between devices. There seems, from documentation and source code, to not be a way to change this.

Perhaps this has something to do with hardcoded pixels, rather than DIP?

**Comment by jesopo** [comment]
bump?

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
