### ISSUE TITLE
Draw image in pie chart center

### ISSUE THREAD

**Issue by ghost** [PhilJay/MPAndroidChart#219]
Hi, i have used this library and this works great.
now i want image in center of pie chart instead of text, is it possible? can anyone help me?

**Comment by rabertol** [comment]
Great Lib! 
Maybe someday you can implemented ;) 
Gr8!

**Comment by NickDelfino** [comment]
Did anyone ever have any luck in implementing this?

**Comment by KathiSick** [comment]
@NickDelfino I just wrote a little hack to acchive this:

I put my Piechart in a [PercentFrameLayout](https://developer.android.com/reference/android/support/percent/PercentFrameLayout.html) and added a View on top of it. 
As I set a hole radius of 75% for chart (`chart.setHoleRadius(75f);`), I gave the view on top of the chart a width and height of 65% (I know that's not clean and you should calculate the correct percentage, but for me this is enough) and centered it. Then you can do whatever you want with this view...

It's just a simple hack but doesn't take much time and for my requirements it's enough
