### ISSUE TITLE
I couldn't change text color of specific x-axis label

### ISSUE THREAD

**Issue by anik123** [PhilJay/MPAndroidChart#2191]
I wanna to change specific x-axis label's color like 8 which mentioned in the image below. 
 
![screenshot-trello com 2016-08-24 14-42-00](https://cloud.githubusercontent.com/assets/6007117/17924117/1de6bf0e-6a09-11e6-9d65-7f2c082c549c.png)

But i hardly found any source or option to do that. 

How to do that ? Is it possible ?

**Comment by lschuetze** [comment]
Provide your own [XAxisRenderer](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/main/java/com/github/mikephil/charting/renderer/XAxisRenderer.java) using `setXAxisRenderer()`.

**Comment by foxsent** [comment]
How to set the X axis s' hilight label

**Comment by foxsent** [comment]
Thx @lschuetze
