### ISSUE TITLE
grouping of Dynamic charts 

### ISSUE THREAD

**Issue by sarathraj-coder** [PhilJay/MPAndroidChart#2192]
i am using the bar charts with grouping function . i can able to group 2 or 3  data set using below

``` sh
        float groupSpace = 0.04f;
        float barSpace = 0.02f; // x3 dataset
        float barWidth = 0.3f; // x3 dataset
```

But my charts are dynamically creating and i cant predict the number of bars. in that case i set the groupspace like below . Then i can see blank chart with out the bar . also i can the 0 values for non bars..

``` sh
   groupSpace=(barWidth + barSpace) * graphRenderItem.getOptions().size()+1 + groupSpace;
```

can u give me some suggestion to solve this

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
