### ISSUE TITLE
getLineData().addXValue(formattedDate);

### ISSUE THREAD

**Issue by ghost** [PhilJay/MPAndroidChart#2194]
Hello! Earlier there was the ability to add xValues separately from the entries. Now I can not find it. This is obsolete and no longer available or I badly searched? 
Sincerely, Dmitri.

**Comment by be1ski** [comment]
Just for my purposes I need to display the graph xValues more than yValues. It's impossible now? So for me the actual version is v2.2.5?

Thank you.

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
