### ISSUE TITLE
Managing timestamps in LineTimeChart

### ISSUE THREAD

**Issue by utkarshns** [PhilJay/MPAndroidChart#2195]
I want to add the following sort of data to the newly introduced timeseries chart.

```
Value :  50.0   at   1472112259
Value :  49.0   at   1472112294
Value :  50.0   at   1472112329
Value :  50.0   at   1472112360
Value :  50.0   at   1472112392

```

The following data will be fetched from the array. 
Right now, I guess there is some mess up with the timestamps.
Here is the complete code: https://gist.github.com/utkarshns/e1723dcc57022fcd392bc3b127b6c898

**Comment by utkarshns** [comment]
The issue is primarily because of the `float` datatype unable to store unix timestamps.
The solution to work with unix timestamps seems only to support a higher range data type like `long`

Closing this issue and opening a feature request to support `long` for timestamps.

**Comment by timusus** [comment]
If you're using a unix timestamp, the problem is when it gets converted to Float, it loses precision, so lots of timestamps that actually represent different times end up being rounded and represented as the same x value. See #2891
