### ISSUE TITLE
Linechart how to set the coordinate values of the X axis

### ISSUE THREAD

**Issue by foxsent** [PhilJay/MPAndroidChart#2196]
Linechart how to set the coordinate values of the X axis

**Comment by foxsent** [comment]
for example： LineData data = new LineData(xVals, set1);

**Comment by Liveinadream** [comment]
Maybe it would help you.
https://github.com/PhilJay/MPAndroidChart/issues/2105

**Comment by foxsent** [comment]
Thx

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
