### ISSUE TITLE
Do we have floating bar graph in this library?

### ISSUE THREAD

**Issue by vigneshdharma** [PhilJay/MPAndroidChart#2198]
Hi,
    Thanks for you great chart Library. I need a floating bar chart like below. Do we have that functionality available in the existing library?

![image](https://cloud.githubusercontent.com/assets/21219605/17968922/2169f1a2-6aed-11e6-80d5-ab013c7c6295.png)

Thanks,
Dharma

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
