### ISSUE TITLE
Bar color and limit issue

### ISSUE THREAD

**Issue by vijaykarora** [PhilJay/MPAndroidChart#22]
Thank you for providing a very good library. I need your help to complete my requirement. I tried to findout solution on stackoverflow but didn't found any conversation about this topic. Actually i am working on Bar chart and i want to set particular bar color with every bar like if my value is less than 10 then i need to show different color otherwise different.

My another issue is to draw horizontal line at 10 values in a bar chart like it will look like a limit.

Thanks in advance
 Regards
Vijay Kumar

**Comment by SantoshDawanse** [comment]
@amagine @PhilJay I have the same issue as @amagine but I cannot understand what you guys are saying. Can you show me a simple example.
