### ISSUE TITLE
how to set markview in the center of the linechart

### ISSUE THREAD

**Issue by Liveinadream** [PhilJay/MPAndroidChart#2205]
![two](https://cloud.githubusercontent.com/assets/20057805/18047603/50c1f7ee-6e10-11e6-9fe4-4c815d10e10c.gif)
I want set the markview and display all Y data in the center of the lingchart.

**Comment by Liveinadream** [comment]
I write a textview in the center of linechart and replace the markview 
`mChart.setOnChartValueSelectedListener(new OnChartValueSelectedListener() {
            @Override
            public void onValueSelected(Entry e, Highlight h) {
                graphHolder.markview.setVisibility(View.VISIBLE);
                graphHolder.markview.setText("日期："+e.getData()+"\n"+e.getY()+areaResponse.trend.get(0).list.get(0).number_count_unit);
            }

            @Override
            public void onNothingSelected() {
                graphHolder.markview.setVisibility(View.GONE);
            }
        });`

but I still don't know how to get all Y data .

**Comment by Liveinadream** [comment]
I had slove this problem .
I try to get the same String Date at the list of json and display all of them.
My code:
` mChart.setOnChartValueSelectedListener(new OnChartValueSelectedListener() {
            @Override
            public void onValueSelected(Entry e, Highlight h) {


                clearChooseValueData();
                Logger.d("日期" + e.getData());
                Date AllYDate = new Date();
                String AllYDAte;
                graphHolder.markview.setVisibility(View.VISIBLE);
                try {
                    AllYDate = sdfsh.parse(e.getData().toString());
                } catch (ParseException e1) {
                    e1.printStackTrace();
                }
                AllYDAte = sdf.format(AllYDate);
                Logger.d("AllYDAte:" + AllYDAte);

                for (int i = 0; i < areaResponse.trend.size(); i++) {
                    for (int k = 0; k < select.size(); k++) {
                        if (i == select.get(k)) {
                            for (int j = 0; j < areaResponse.trend.get(i).list.size(); j++) {
                                Logger.d("日期：" + areaResponse.trend.get(i).list.get(j).day_date.toString());
                                if (TextUtils.equals(areaResponse.trend.get(i).list.get(j).day_date.toString(), AllYDAte)) {
                                    AllDispalyYDate.add(areaResponse.trend.get(i).list.get(j).number_count);
                                    AllDispalyYDateName.add(areaResponse.trend.get(i).list.get(j).city_name);
                                }
                            }
                        }
                    }
                }
                Logger.d("show size" + AllDispalyYDate.size());
                String display = "";

                for (int i = 0; i < AllDispalyYDate.size(); i++) {
                    final SpannableStringBuilder sps = new SpannableStringBuilder();

                    if (i < AllDispalyYDate.size() - 1) {

                        display = display + AllDispalyYDateName.get(i) + ":" + AllDispalyYDate.get(i)
                                + areaResponse.trend.get(0).list.get(0).number_count_unit + "\n";
                        Logger.d("length"+display.length());
                    } else {
                        display = display + AllDispalyYDateName.get(i) + ":" + AllDispalyYDate.get(i)
                                + areaResponse.trend.get(0).list.get(0).number_count_unit;
                    }
                }
                Logger.d("show:" + display);
                String MarkviewDate = "日期：" + e.getData() + "\n";
                String all = MarkviewDate + display;
                graphHolder.markview.setText(all);
            }

            @Override
            public void onNothingSelected() {
                graphHolder.markview.setVisibility(View.GONE);
            }
        });`

**Comment by kushanshah11** [comment]
Hi @Liveinadream ,

i wondered how can you enable and  disable to draw a line on click particular legend.

can you please share your code it will be more helpful to me.

here i posted my issues what i faced. https://github.com/PhilJay/MPAndroidChart/issues/2790

Thanks in advance.

**Comment by ikkong** [comment]
Hi @Liveinadream 
The GIF picture on this page, click the legend to show / hide the effect of the corresponding data, how to achieve it?
