### ISSUE TITLE
How to get the value of the current X axis through hightlight

### ISSUE THREAD

**Issue by foxsent** [PhilJay/MPAndroidChart#2212]
How to get the value of the current X axis through hightlight

**Comment by Liveinadream** [comment]
mChart.setOnChartValueSelectedListener(new OnChartValueSelectedListener() {
            @Override
            public void onValueSelected(Entry e, Highlight h) {
           ...}
            @Override
            public void onNothingSelected() {
                graphHolder.markview.setVisibility(View.GONE);
            }
        });
you can get x axis by e.get....;

**Comment by foxsent** [comment]
Thx
