### ISSUE TITLE
set value of step on xaxis in line chart 

### ISSUE THREAD

**Issue by folol** [PhilJay/MPAndroidChart#2218]
I am creating Line chart and my entries includes data points like (0,11) , (1,22) , etc but the problem is that when graph is rendered it is displaying value like this on xaxis - 0.8 , 1.6 , 2.4 ....

How can i resolve this ?

![screenshot_2016-09-01-16-29-16](https://cloud.githubusercontent.com/assets/8148617/18165294/04a81f9c-7062-11e6-9739-162644fe7c58.png)

**Comment by Liveinadream** [comment]
axis.setGranularityEnabled(true);
                axis.resetAxisMaxValue();
                axis.isAxisMaxCustom();
set it in   `xAxis.setValueFormatter(new AxisValueFormatter() {
            @Override
            public String getFormattedValue(float value, AxisBase axis) {
.....
}
 @Override
            public int getDecimalDigits() {
                return 0;
            }
        });`
May be helpful

**Comment by folol** [comment]
Thanks  , it worked !
