### ISSUE TITLE
Left decreasing chart part not drawn at all or correctly BUG

### ISSUE THREAD

**Issue by gGololicic** [PhilJay/MPAndroidChart#2226]
I love MPCharts and I really appreciate the work, however I found a bug in the android version of the library.
The problem is that values in the left data set are not drawn at all in version 3.0.0-beta1 or they are drawn wrong in 3.0.0-beta. 

As seen in the picture left side is just drawn as a straight line even though the data is different. 
![1](https://cloud.githubusercontent.com/assets/2612591/18229900/7989342a-728a-11e6-8dd4-832f36ed8acc.png)

The data feed to line chart for the left data set is:
```
DataSet, label: , entries: 461
Entry, x: 593.62 y (sum): 0.633634 Entry, x: 593.6 y (sum): 3.7147155 Entry, x: 593.55 y (sum): 4.534798 Entry, x: 593.4 y (sum): 15.777748 Entry, x: 593.12 y (sum): 15.79894 Entry, x: 593.0 y (sum): 24.80894 Entry, x: 592.32 y (sum): 25.80894 Entry, x: 592.01 y (sum): 26.406086 Entry, x: 591.79 y (sum): 26.940962 Entry, x: 591.42 y (sum): 27.381863 Entry, x: 591.3 y (sum): 27.397562 Entry, x: 591.17 y (sum): 39.54756 Entry, x: 591.16 y (sum): 59.54756 Entry, x: 591.12 y (sum): 60.04756 Entry, x: 591.11 y (sum): 65.41229 Entry, x: 591.01 y (sum): 68.86229 Entry, x: 590.9 y (sum): 69.34229 Entry, x: 590.76 y (sum): 69.3626 Entry, x: 590.66 y (sum): 94.32941 Entry, x: 590.64 y (sum): 95.2794 Entry, x: 590.51 y (sum): 99.547485 Entry, x: 590.32 y (sum): 100.44815 Entry, x: 590.11 y (sum): 102.36245 Entry, x: 590.0 y (sum): 102.41262 Entry, x: 589.91 y (sum): 103.21262 Entry, x: 589.62 y (sum): 104.04653 Entry, x: 589.29 y (sum): 106.911896 Entry, x: 589.28 y (sum): 107.816925 Entry, x: 588.95 y (sum): 108.39577 Entry, x: 588.8 y (sum): 109.295425 Entry, x: 588.57 y (sum): 109.87543 Entry, x: 588.25 y (sum): ......
```

Is the fix available or should I found the issue?

**Comment by PhilJay** [comment]
Thats because your entries are not ordered: https://github.com/PhilJay/MPAndroidChart/wiki/Setting-Data#the-order-of-entries

You need to sort your entries ascending by x-position. The reason therefore is that the library uses binary search algorithms for better performance that only work on sorted lists.

**Comment by gGololicic** [comment]
I understand. Thank you.
