### ISSUE TITLE
Android Studio Failed to resolve:com.github.PhilJay:MPAndroidChart:v2.1.3

### ISSUE THREAD

**Issue by HassanShahbaz** [PhilJay/MPAndroidChart#2229]
Hi all i am using charts library in my project a month ago it was working fine but now i have reinstalled android studio and when i build my project it gives gradle sync error.

Failed to resolve:com.github.PhilJay:MPAndroidChart:v2.1.3
I am stuck on this any suggestions how to solve this.My android studio version is 2.1.3

Here is project dependencies

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 22
    buildToolsVersion '23.0.2'

    defaultConfig {
        applicationId "com.app.comismv"
        minSdkVersion 14
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    maven {
        jcenter()
        url "https://jitpack.io"
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.github.PhilJay:MPAndroidChart:v2.1.3'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.3'
    //compile 'com.cardiomood.android:android-widgets:0.1.1'
}
```

**Comment by MGaetan89** [comment]
I guess this can be closed now? As the latest version is 3.0.3.

**Comment by Thebarda** [comment]
I've the same issue with version 3.0.3

**Comment by vasiledoe** [comment]
**SOLVED**

Just change 
`maven { url 'https://www.jitpack.io' }`

to

`maven { url 'https://jitpack.io' }`

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.

**Comment by mayank1513** [comment]
I face the same issue. I have tried both maven { url 'https://www.jitpack.io' } and maven { url 'https://jitpack.io' }. I am putting it as right place under all projects. Using the latest graddle

**Comment by engr-erum** [comment]
> I face the same issue. I have tried both maven { url 'https://www.jitpack.io' } and maven { url 'https://jitpack.io' }. I am putting it as right place under all projects. Using the latest graddle

Hi did u find any solution ?

**Comment by mayank1513** [comment]
Yes.

Actually I needed to release my project on github by going to release tab. I did that and it started working.

**Comment by RuchiraSheyan** [comment]
Put this "maven { url 'https://jitpack.io' }" to the project level build.gradle and **make sure**  to put it to repositories in **allprojects{  }**.
Put this "implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'" to the app level buil.gradle dependencies.

**Comment by hunnihundert** [comment]
> Put this "maven { url 'https://jitpack.io' }" to the project level build.gradle and **make sure** to put it to repositories in **allprojects{ }**.
> Put this "implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'" to the app level buil.gradle dependencies.

putting it into allprojects { } did it for me! thank you
