### ISSUE TITLE
Plotting issue with LineData with Fill and Bezier mode 

### ISSUE THREAD

**Issue by nielsz** [PhilJay/MPAndroidChart#2235]
I'm drawing 2 LineDataSets on top of each other.
When using HORIZONTAL_BEZIER or CUBIC_BEZIER, the fill pattern is skewed towards zero.
mode LINEAR is filling it as expected.

Mode STEPPED is also doing some other filling I wouldn't expect.

Library version: v3.0.0-beta1. Tested on Emulator (23) and Nexus 5X (24).

![horizontal_bezier](https://cloud.githubusercontent.com/assets/105541/18276424/23403d8a-744b-11e6-9f72-26000fa84379.png)
![cubic_bezier](https://cloud.githubusercontent.com/assets/105541/18276423/232eb54c-744b-11e6-8681-ade075697729.png)
![linear](https://cloud.githubusercontent.com/assets/105541/18276440/3ec6ad82-744b-11e6-83db-032b87f90159.png)

![stepped](https://cloud.githubusercontent.com/assets/105541/18276421/232b9484-744b-11e6-97e5-a8359969737e.png)

**Comment by jhutarek** [comment]
![img_0627](https://cloud.githubusercontent.com/assets/22645578/19128276/f521ddd2-8b42-11e6-8808-2663d50bb2bd.JPG)
The same issue here

**Comment by nielsz** [comment]
Those problems don't appear in the 3.0.0 release.

**Comment by andriistakhov** [comment]
I use 3.0.0 version and problem @jhutarek stay.

**Comment by JacobJust** [comment]
I created a PR to fix this, lets hope it gets merged and released soon ;-)
