### ISSUE TITLE
Calculate min max Y on combined data set does not work for me

### ISSUE THREAD

**Issue by gGololicic** [PhilJay/MPAndroidChart#2250]
I am struggling for hours to make auto scale of min and max Y values work. On iOS version it worked just by enabling `chartView.setAutoScaleMinMaxEnabled(true);` however this is not the case for android version. I have tried to fiddle with the example code and it works and its getting me really frustrated.
Here is my setup: 
I use `CombinedChart` with `setAutoScaleMinMaxEnabled` set to true. I created `CombinedData` to which I set `BarDataSet` and `CandleDataSet`. I have set `setVisibleXRange` to 40 and 50 on the `CombinedChart` and I call `notifyDataSetChanged` and `invalidate` on each update of the data.
My chart is not scaled on moving or on initial fill of the data. Y axis is scaled taking in to account whole data and not just data currently drawn between visible x range. 
I tried to output getYMax and getYMin on the combined data set and it is wrong (taking into account whole data). I also output getLowestVisibleX and getHighestVisibleX which is correct value as shown in current view. 

Here is the picture of the graph (candles should have much bigger y range):
![device-2016-09-11-132007](https://cloud.githubusercontent.com/assets/2612591/18416962/db6d9962-7823-11e6-84c1-3b4b5fad12be.png)

**Comment by Ornolfr** [comment]
@gGololicic have you solved the problem? I have the same...

**Comment by shushper** [comment]
And i have the same too

**Comment by shushper** [comment]
I solved it! Per default, all data that is added to the chart plots against the left YAxis of the chart. So if left YAxis disabled and only right YAxis enabled, we need to manually set for our dataset to plot against right YAxis. 

```
dataSet.setAxisDependency(AxisDependency.RIGHT); 
```
