### ISSUE TITLE
linechart horizontal scroll

### ISSUE THREAD

**Issue by viniciusjns** [PhilJay/MPAndroidChart#2258]
Hey guys, I'm starting with MpAndroidChart and I need to implement a line chart that have a horizontal scroll and move it to the last point of the chart (the end of the scroll). Are there some method to help me in this issue? Can someone help me to solve this? Thanks.

**Comment by 1690251766** [comment]
I want to implement horizontal scroll but not scale,is there some solution?Thanks.

**Comment by castrojr913** [comment]
@1690251766 yeah, I don't understand the PhilJay's attitude, closing issues without explaining anything. It would be better to create a fork and fix these bugs.

**Comment by surhidamatya** [comment]
@PhilJay 
I want to set horizontal scroll in linechart but I am not able to set horizontal scroll. Any workaround.

**Comment by Hariharan27** [comment]
> @PhilJay
> I want to set horizontal scroll in linechart but I am not able to set horizontal scroll. Any workaround.

Hi surhi 
  Just set a default zoom if your entries has more than 6 data.
  if (month > 6) {
            lineChart?.zoom(1.2f, 0f, 1f, 0f, lineChart.axisLeft.axisDependency)
            lineChart?.invalidate()
        } else {
            lineChart?.fitScreen()
        }
     It's work around. hope it will be helpfull
