### ISSUE TITLE
How to remove the small cube which appears at the bottom of the chart showing what the line represents?

### ISSUE THREAD

**Issue by alsaa** [PhilJay/MPAndroidChart#2264]
![screenshot](https://cloud.githubusercontent.com/assets/21615890/18541709/97a894ce-7b44-11e6-957c-f8a50ccfaf0e.png)

You can find a small square box at the bottom the line graph (Cyan colored Box - below Jan). I do not require this representation. How to hide this box? Is it possible ?

**Comment by joanna-zolopa** [comment]
I think it's a legend showing. Try:
chart.getLegend().setEnabled(false);

**Comment by alsaa** [comment]
Yes its working Thanks :+1:

**Comment by joanna-zolopa** [comment]
No problem :)

**Comment by alsaa** [comment]
@joanna-zolopa i want to know from which version setFillDrawable(Drawable d) is available ? current;y i am using v2.1.6 in which this api is not available

**Comment by alsaa** [comment]
@joanna-zolopa How to set Yaxis Labels for Line chart in version-3.0. beta?
Previously when i was using version 2.3.3 MPChartLibrary the Yaxis Labels were set using following syntax:
ArrayList labels = new ArrayList<>();
LineData data = new LineData(labels, dataSet); -- > this api is not supported in version 3.0 beta.

So how to set yaxis labels?

**Comment by karan0008** [comment]
Works like a charm. Thanks.
