### ISSUE TITLE
Cannot resolve method getDescription()

### ISSUE THREAD

**Issue by AkshayGangurde** [PhilJay/MPAndroidChart#2272]
I have just started to learn how to use MPAndroidChart and the git example working great, 
But when I tried to implement it in my app

Getting error like 
Cannot resolve method 'getDescription()'

Can anyone help me?

**Comment by PhilJay** [comment]
These are features not yet in a release.
In release v3.0.0-beta1, description can be changed via the `Chart` instance.

`chart.setDescription("...")`
`chart.setDescriptionTextSize(...)`

**Comment by AkshayGangurde** [comment]
Thanks :)

**Comment by jithishpn** [comment]
Error:(37, 11) error: cannot find symbol method setChartView(ScatterChart)
Error:(44, 17) error: cannot find symbol method setAxisMaximum(float)
Error:(96, 15) error: cannot find symbol method setMarker(MyMarkerView)

so many unresolved methods.

so which is correct working version ?
