### ISSUE TITLE
How to set Yaxis Labels for Line chart in version-3.0. beta?

### ISSUE THREAD

**Issue by alsaa** [PhilJay/MPAndroidChart#2282]
Previously when i was using version 2.3.3 MPChartLibrary the Yaxis Labels were set using following syntax:
ArrayList<String> labels = new ArrayList<>();
 LineData data = new LineData(labels, dataSet);  -- > this api is not supported in version 3.0 beta.

So how to set yaxis labels?

**Comment by alsaa** [comment]
@PhilJay

**Comment by chenshuiluke** [comment]
@alsaa Did you find a way to do what you wanted. I can't figure it out either.

**Comment by alsaa** [comment]
@chenshuiluke Sorry no i did not find a way to do it in 3.0 beta version.

**Comment by qwerty2121212** [comment]
I couldn't find a way pl.let me know if there is an alternative way in the new version
