### ISSUE TITLE
The BarChart draw over the leftYAxis

### ISSUE THREAD

**Issue by xiaolongonly** [PhilJay/MPAndroidChart#2284]
Like this !

How can I make a space this version?
![screenshot_2016-09-22-18-59-16_com cncn gdctourmo](https://cloud.githubusercontent.com/assets/12853050/18745969/3792439c-80f7-11e6-9a6f-ed376752dc48.png)

**Comment by xiaolongonly** [comment]
The versionName is '3.0.0'

**Comment by saiidabs** [comment]
same problem, did you figure out a way to fix it?

**Comment by xiaolongonly** [comment]
hey guy !   I have forget that I don't close this problem. 

now the BarEntry with a Constructor BarEntry(float x, float y)  the x is the position of x in the chart

I think you can try to new a BarEntry() with x value start from 0

**Comment by xiaolongonly** [comment]
hey guy ! I have forget that I don't close this problem.

now the BarEntry with a Constructor BarEntry(float x, float y) the x is the position of x in the chart

I think you can try to new a BarEntry() with x value start from a value bigger than zero.

**Comment by xiaolongonly** [comment]
hey guy ! I have forget that I don't close this problem.

now the BarEntry with a Constructor BarEntry(float x, float y) the x is the position of x in the chart

I think you can try to new a BarEntry() with x value start from a value bigger than zero.

I hope it will helpful to you!! @saiidabs
