### ISSUE TITLE
xAxis.setTextSize() text gets clipped

### ISSUE THREAD

**Issue by Aiden01** [PhilJay/MPAndroidChart#2290]
I have a LinearLayout with the graph and a spacer below.
I have this code to style the x axis

```
XAxis xAxis = chart.getXAxis();
xAxis.setDrawGridLines(false);
xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
xAxis.setTextSize(15);
```

the problem is that the text gets clipped on the bottom as you can see in the photo
No problem with the default  text size
![screenshot_1474635847](https://cloud.githubusercontent.com/assets/22396529/18789022/959cb9ec-81a9-11e6-956e-441bdb5795af.png)

I tried to add margins and padding but nothing changed.
I'm using 3.0.0-beta1 version

**Comment by hkusb** [comment]
I also meet this problem, have you solved it?

**Comment by Aiden01** [comment]
No, I've tried few things, but nothing.
Maybe it's something related to the core.

**Comment by hkusb** [comment]
Thanks for your feedback.

**Comment by jhanay** [comment]
try call this  method:
mChart.setExtraBottomOffset(5);

**Comment by Aiden01** [comment]
Thanks, problema solved!
