### ISSUE TITLE
Add maven central support

### ISSUE THREAD

**Issue by liampeters** [PhilJay/MPAndroidChart#23]
Would love for this library to be mavenised in some way! Thanks!

**Comment by mathieudebrito** [comment]
Up

**Comment by ripern** [comment]
Deploying to jCenter seems easier. Here's a guide describing it: http://androiddeving.blogspot.se/2014/08/deploying-on-jcenter-bintray-how-to.html

Like someone said in October, if you just create the account there are plenty of people here that would do the rest. From guide: "First of all you need to register for a new account at https://bintray.com/".
So if you could spare 5min of your time, someone else might spare the hour or two the rest takes.

Just my 2 cents
Thanks for a great library!

**Comment by mathieudebrito** [comment]
up

**Comment by FriesischScott** [comment]
I second this motion  :)

**Comment by aint** [comment]
Someone published this lib on maven central. :+1:http://mvnrepository.com/artifact/org.quanqi/mpandroidchart
```
<dependency>
	<groupId>org.quanqi</groupId>
	<artifactId>mpandroidchart</artifactId>
	<version>1.7.5</version>
</dependency>
```

**Comment by TealOcean** [comment]
Finally! :+1: :+1: :+1:

**Comment by marunjar** [comment]
Hmm, the library on maven central is a fork that seems to be a little behind this codebase.

I'd like to see this library published directly by @PhilJay , i would prefer that.

btw: thanks for this awesome library

**Comment by mathieudebrito** [comment]
@marunjar +1

**Comment by aint** [comment]
Yep, the situation with the library versions is really confusing. But this is a good alternative, because today almost half a year since the original request was posted and still no progress. :confused:

**Comment by ripern** [comment]
@PhilJay (the author) has probably stopped reading this thread.

**Comment by PhilJay** [comment]
I absolutemy have not 😉
But I am extremely busy atm working on my masters thesis. Hoping to get to this (and other issues) soon!

**Comment by jitpack** [comment]
Btw, you could also get MPAndroidChart library as a maven dependency using https://jitpack.io. Submitted PR #345 to make it possible

**Comment by Maragues** [comment]
@jitpack your solution isn't working. "Failed to resolve: com.github.PhilJay:MPAndroidChart:v1.7.4". I've tried 1.7.5 as well. 

The maven repository is added to the build.gradle, as described in the instructions

Thanks for the library @PhilJay , and good luck with yout master thesis

**Comment by jitpack** [comment]
@Maragues Thanks for brinnging up the issue! The thing is that our PR #345 was merged but there hasn't been a new release that includes that PR. So 1.7.4 doesn't have it therefore it doesn't build. Maybe @PhilJay can create v1.7.5 that include this.
  
In the mean time you can download from our fork: https://jitpack.io/#jitpack/MPAndroidChart/v1.7.5 
Tested and it works!:)

**Comment by Maragues** [comment]
@jitpack that worked like a charm :+1:

**Comment by jitpack** [comment]
@Maragues The new 2.0.0 version of MPAndroidChart includes PR #345 so works nicely with JitPack: https://jitpack.io/#PhilJay/MPAndroidChart/v2.0.0/aar

**Comment by PhilJay** [comment]
Finally, this is possible :-)

- Add the following to your `pom.xml`:
 ```xml
<repository>
       	<id>jitpack.io</id>
	    <url>https://jitpack.io</url>
</repository>

<dependency>
	    <groupId>com.github.PhilJay</groupId>
	    <artifactId>MPAndroidChart</artifactId>
	    <version>v2.0.0</version>
</dependency>
```

Be aware that v2.0.0 is still beta.

**Comment by jaredsburrows** [comment]
+1

**Comment by WalterNyeko** [comment]
This library no longer works??? I have tried to use the official one at com.github.PhilJay. But it is not available.
