### ISSUE TITLE
Legend issue

### ISSUE THREAD

**Issue by yx19861211** [PhilJay/MPAndroidChart#2313]
Legend l = mChart.getLegend();
        l.setVerticalAlignment(Legend.LegendVerticalAlignment.BOTTOM);
        l.setHorizontalAlignment(Legend.LegendHorizontalAlignment.LEFT);
      #   l.setOrientation(Legend.LegendOrientation.VERTICAL);
        l.setDrawInside(true);
        l.setYOffset(0f);
        l.setYEntrySpace(0f);
        l.setTextSize(8f);

![s60929-183438](https://cloud.githubusercontent.com/assets/8265300/18950738/ef381e28-8673-11e6-96a7-a25c54a5d189.jpg)

 Legend l = mChart.getLegend();
        l.setVerticalAlignment(Legend.LegendVerticalAlignment.BOTTOM);
        l.setHorizontalAlignment(Legend.LegendHorizontalAlignment.LEFT);
        # l.setOrientation(Legend.LegendOrientation.HORIZONTAL);
        l.setDrawInside(true);
        l.setYOffset(0f);
        l.setYEntrySpace(0f);
        l.setTextSize(8f);

![s60929-183934](https://cloud.githubusercontent.com/assets/8265300/18950866/b88c896c-8674-11e6-92a3-ffa861a8c054.jpg)

HORIZONTAL :  Legend  is not show

android versions : 5.0.1

**Comment by yx19861211** [comment]
Status at the bottom of the issue.

l.setPosition(Legend.LegendPosition.BELOW_CHART_LEFT); 
 Legend is not show

**Comment by yx19861211** [comment]
MPAndroidChart versions :
compile 'com.github.PhilJay:MPAndroidChart:v3.0.0-beta1'

**Comment by JanosSarkezi** [comment]
same here ... when i initially initialize the chart, no legend is shown. after the dataset changes, i reset the data and only then the chart gets redrawn with the legend on the bottom.

**Comment by xcqwan** [comment]
@PhilJay how to fix it?

**Comment by ugurcany** [comment]
Same here. Any solution?

**Comment by yx19861211** [comment]
use this versions  com.github.PhilJay:MPAndroidChart:v3.0.0-beta
not  issue

**Comment by xcqwan** [comment]
upgrade version fix it
