### ISSUE TITLE
some problem with HorizontalScrollView

### ISSUE THREAD

**Issue by taerran** [PhilJay/MPAndroidChart#2316]
I'm using MPAndroidChart(v3.0.0-beta1) inside HorizontalScrollView.
Everything is ok before scrolling chart. But, when I scroll the chart, some number is missing in the chart! (see below screen capture)

![screenshot_2016-09-30-00-41-33](https://cloud.githubusercontent.com/assets/18208332/18961359/c630ffca-86a7-11e6-841e-40ae3af0f260.png)

My code is as below.

xml file:

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <HorizontalScrollView
        android:layout_width="wrap_content" android:layout_height="wrap_content"
        android:layout_marginLeft="5dp"
        android:layout_marginRight="5dp"
        android:background="#66000000">

        <LinearLayout
            android:orientation="vertical"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content">

            <TextView
                android:layout_width="500dp"
                android:layout_height="match_parent" />

            <com.github.mikephil.charting.charts.LineChart
                android:id="@+id/chart"
                android:layout_width="match_parent"
                android:layout_height="240dp" />
        </LinearLayout>

    </HorizontalScrollView>

</LinearLayout>`

MainActivity:

`protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Step 1
        LineChart chart = (LineChart)findViewById(R.id.chart);

        // Step 2 : prepare raw data
        float[] temperature = new float[]{33.0f, 29.5f, 28.0f, 30.0f, 26.4f, 27.3f};
        float[] axis        = new float[]{0f, 1f, 2f, 3f, 4f, 5f};

        // Step 3 : convert to ArrayList<Entry>
        ArrayList<Entry> tempEntryList = new ArrayList<Entry>();
        for(int i=0; i<temperature.length; i++){
            tempEntryList.add(new Entry(axis[i],temperature[i]));
        }

        // Step 4 : create LineDataSet + Style
        LineDataSet lineDataSet = new LineDataSet(tempEntryList,"Temperature");
        lineDataSet.setValueTextColor(Color.WHITE);
        lineDataSet.setColor(Color.WHITE);        // line color
        lineDataSet.setCircleColor(Color.WHITE);  // dot(circle) color
        lineDataSet.setValueTextSize(12f);      // value textSize
        lineDataSet.setValueFormatter(new TemperatureValueFormatter()); // degree 

        // Step 5 : create LineData
        LineData lineData = new LineData(lineDataSet);
        chart.setData(lineData);

        // Axis
        chart.getXAxis().setEnabled(false);
        chart.getAxisLeft().setEnabled(false);
        chart.getAxisRight().setEnabled(false);
        chart.setTouchEnabled(false);
        chart.setDescription("");

        //chart.setBackground
        chart.setAlpha(0.7f);

        chart.invalidate();
    }`

**Comment by GUINN355** [comment]
This is just a guess of mine. Maybe you have to refresh the Graph when scrolled.

Try to set up an onTouchEvent() where you invalidate your chart.

I`m not sure about this, but maybe it helps.

**Comment by taerran** [comment]
- I have solved this problem by setting the chart's width explicitly. (I don't know why it works ... )
(<com.github.mikephil.charting.charts.LineChart android:layout_width="match_parent" ==> android:layout_width="500dp")

- (GUINN355) I tried your suggestion, but it doesn't work. But, thanks for your suggestion.
