### ISSUE TITLE
XAxis Date labels - LineChartTime.java

### ISSUE THREAD

**Issue by oxoocoffee** [PhilJay/MPAndroidChart#2323]
Hello,

While working on my project I did try to modify my source to do something similar like you do in one of your MPChartExample/ LineChartTime.java. In your case you storing time in X axis (hour resolution) setData() and formation it in getFormattedValue(). I am trying to do something very similar but display time in second resolution.

So here is what I do

long t = TimeUnit.MILLISECONDS.toSeconds( System.currentTimeMillis() );
lineData.addEntry(new Entry(t, val), 0);

// SimpleDateFormat _Format = new SimpleDateFormat("HH:mm:ss");
// String ss = _Format.format(new Date(TimeUnit.SECONDS.toMillis(t)));
// Log.i(TAG, " S: " + ss);

So when adding data above commented out code prints the time. And that looks fine.

Now I see data added to chart (on display) but they are all on same X axis "point" (imagine vertical line and new points are appearing on it based on Y value). Also the strange thing is that getFormattedValue() is sometimes called sometimes it is not. But when it is called value passed looks correct and converting it to String looks correct.

private SimpleDateFormat _format = new SimpleDateFormat("HH:mm::ss");

public String getFormattedValue(float value, AxisBase axis) {
      return _format(new Date(TimeUnit.SECONDS.toMillis((long)value)));
}

Now if I update above code to just insert int counter ++ each time new value is inserted and updating 
getFormattedValue() to just convert value to string chart looksOK!!!...
I do not see any value overflow at first glance unless there is something internally that it has problem dealing with large X values somewhere.

Also I see possible work around with stuffing my time into 3rd parameter to Entry( , , Object) and then retrieve? in getFormattedValue() Possible?

Also sample code has this line
xAxis.setGranularity(1f); // one hour

In my case where I deal with second resolution this should be the same?

Also my data is coming at un even intervals but 1s is the smallest. There could be times where there is no data for 15 sec or next data point would be 4sec or 6 sec apart. 

I would be ok if all values on screen are equally spaced on X Axis even if time duration between is them is different.

**Comment by oxoocoffee** [comment]
I noticed today that there is overflow with float. Workaround to use Entry( , , Object) and externally store times if you deal with values larger them float

**Comment by csbenz** [comment]
Could you tell me more about how you solved this problem with `Entry(float, float, Object) ` please?

**Comment by frog1014** [comment]
I want to know the solution... thanks much!
