### ISSUE TITLE
Overlapping labels on X-axis when used with Formatter

### ISSUE THREAD

**Issue by JainamJhaveri** [PhilJay/MPAndroidChart#2324]
![screenshot_2016-10-02-16-25-43](https://cloud.githubusercontent.com/assets/8875913/19020163/d0ddf7a8-88bd-11e6-9a38-16389938bdd4.png)

On X-axis, the leftmost value overlaps with the 2nd value. I have used a custom formatter for displaying values on X-axis as directed in https://github.com/PhilJay/MPAndroidChart/issues/789
If I scroll left horizontally then those 2 values are separated but another values that become leftmost start overlapping.

Now if I do not use the formatter, then the values appear separate but still they do not appear equidistant from each other.
![screenshot_2016-10-02-16-46-48](https://cloud.githubusercontent.com/assets/8875913/19020218/24e83e42-88c0-11e6-9a5e-d8cfd4081337.png)

My code for CustomFormatter is here:
https://github.com/JainamJhaveri/rasppi_android/blob/master/app/src/main/java/com/jainamjhaveri/rasppiclient/HourAxisValueFormatter.java
and the fragment from which I am using CustomFormatter is here:
https://github.com/JainamJhaveri/rasppi_android/blob/master/app/src/main/java/com/jainamjhaveri/rasppiclient/GraphFragment.java

@PhilJay

**Comment by iRuth** [comment]
@JainamJhaveri if you remove [x.setAvoidFirstLastClipping(true)](https://github.com/JainamJhaveri/rasppi_android/blob/master/app/src/main/java/com/jainamjhaveri/rasppiclient/GraphFragment.java#L197), it should work. However, if you remove it, your x-labels would [be clipped off sometimes](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/main/java/com/github/mikephil/charting/components/XAxis.java#L100-L108).

**Comment by JainamJhaveri** [comment]
Yes it worked..
