### ISSUE TITLE
Draw circles with a given interval

### ISSUE THREAD

**Issue by dyshen** [PhilJay/MPAndroidChart#2335]
Is it possible to draw circles on a given interval? Or any workaround approach?

e.g. draw a circle for every 12 data points
<img width="258" alt="screen shot 2016-10-06 at 5 17 28 pm" src="https://cloud.githubusercontent.com/assets/1556057/19175108/ee3d3682-8be8-11e6-97d0-c35dbecf5fbe.png">

**Comment by PhilJay** [comment]
Workaround is to create a second dataset for the cirles!
