### ISSUE TITLE
How to add Date on Xaxis.

### ISSUE THREAD

**Issue by JImmyBhavsar** [PhilJay/MPAndroidChart#2338]
I have used xAxisFormatter, but it is not using the Entry array values. 
Is there a better way I can plot date on X -Axis? 
Please help.

**Comment by sanmish16** [comment]
first store all date in array
here mDate is an array which stores all dates of current month
value is index of xAxis

String stringValue;
                if (mDate.size() >= 0 && value >= 0) {
                    if (value < mDate.size()) {
                        stringValue = mDate.get((int) value);
                    } else {
                        stringValue = "";
                    }
                }else {
                    stringValue = "";
                }
                return stringValue;

**Comment by JImmyBhavsar** [comment]
Hi,
Thank you so much for your feedback. 
It worked smoothly :) You saved my day.

But it is not printing first x-axis value while  the y-axis is well.  Can you please help ?
Please review below mentioned code

  xAxis.setValueFormatter(new IAxisValueFormatter() {
            SimpleDateFormat mFormat = new SimpleDateFormat("dd.MM");
            @Override
            public String getFormattedValue(float value, AxisBase axis)
            {
                if (xAxisArrayList.size() >= 0 && value >= 0) {
                    if (value < xAxisArrayList.size()) {
                        stringValue = mFormat.format((new Date((long) xAxisArrayList.get((int) value))));
                    } else {
                        stringValue = "";
                    }
                }else {
                    stringValue = "";
                }
                return stringValue;
            }
            @Override
            public int getDecimalDigits() {
                return 0;
            }
        });



Thanks.

**Comment by sanmish16** [comment]
xAxis.setAxisMinValue(0f);
or if its not working then put xAxis.setAxisMinValue(-1f);
else xAxis.setCenterAxisLabels(true); this one will work

**Comment by JImmyBhavsar** [comment]
Hi, 

Thank you so much for your feedback.

Can you please review this? 
I have almost achieved it but it is not starting from first x-position and if it starts from a first x - position it skipped first one ( ex. first 18.08 skipped ).
![image](https://cloud.githubusercontent.com/assets/4188706/19190189/c10b145a-8cb9-11e6-97c8-f5074aac4999.png)

**Comment by sanmish16** [comment]
xAxis.setCenterAxisLabels(true);  make it false

**Comment by JImmyBhavsar** [comment]
Hi,

I have used    xAxis.setCenterAxisLabels(true); also but it is not exactly same to point  y-axis  values. 
You can check on above image also where 22.08 date is pointing to nowhere.  

I have coded as below. 

 set1 = new LineDataSet(values, "Metric Value");

                                // set the line to be drawn like this "- - - - - -"
                                set1.enableDashedLine(10f, 5f, 0f);
                                set1.enableDashedHighlightLine(10f, 5f, 0f);
                                set1.setColor(Color.BLACK);
                                set1.setHighLightColor(Color.RED);
                                set1.setValueTextColor(Color.BLUE);

                                set1.setCircleColor(Color.BLUE);
//                                set1.setColors(colors);
                                set1.setLineWidth(1f);
                                set1.setCircleRadius(3f);
                                set1.setDrawCircleHole(true);
                                set1.setValueTextSize(9f);
                                set1.setDrawFilled(true);
                                set1.setHighlightEnabled(true);

**Comment by vmosconecds** [comment]
facing the same issue. X axis labels values are not aligned with the value of Y axis. I want one x axis label per y axis value. How do you manage to fix this? Thanks!
