### ISSUE TITLE
How to add String label to x and y axes?

### ISSUE THREAD

**Issue by antedesk** [PhilJay/MPAndroidChart#234]
I am developing a simple Android app which shows a dataset of flot numbers on a linechart through your library MPAndroidChart and thanks to it I am able to manage my custom linechart and its style.

However, I am trying to add a String Label in order to label both the domain (x-axes) and the range (y-axes) of my linechart, as shown in the picture below. 
![example](https://cloud.githubusercontent.com/assets/4306797/5159166/1792cb3a-735b-11e4-9904-fe015a2588d0.jpg)

Any suggestions to do it using MPAndroidChart?
Thank you for your time

**Comment by tejprakashtiwary** [comment]
is it possible to draw custom axes. i like to create it as coordinate system means origin should be in middle of the graph. thanks in advance.

**Comment by itzhangyang** [comment]
Hi,Could you please tell me how did you add the feature into this libs? I am meeting the same problem...

**Comment by AmitP8745** [comment]
Hey, I used this lib for a project last year. In the end I came to the conclusion that the library didn't support this, so we had to have a textview representation of the chart below it, if that makes sense

Date: Mon, 23 Nov 2015 18:36:51 -0800

**Comment by vnd-ranga** [comment]
how to set in v3.0.1

**Comment by ghizoulo** [comment]
@antedesk Plz can u post ur solution here ?

**Comment by cmy113** [comment]
Is the feature added in the new version?

**Comment by vnd-ranga** [comment]
if you want to show value over dot this is method


        mLineChart.setDescription(null);
        mLineChart.getAxisRight().setEnabled(false);
        mLineChart.setClickable(false);
        mLineChart.setTouchEnabled(true);
        mLineChart.setPinchZoom(false);
        mLineChart.setDoubleTapToZoomEnabled(false);
        mLineChart.animateY(2000, Easing.EasingOption.EaseInOutCirc);
        mLineChart.setExtraOffsets(10, 20, 20, 10);


        mLineChart.getAxisRight().setAxisMinimum(0);
        YAxis leftAxis = mLineChart.getAxisLeft();
        leftAxis.setDrawGridLines(false);
        mLineChart.setBorderWidth(20f);
        leftAxis.setEnabled(true);
        leftAxis.setGranularity(1f);
        leftAxis.setTextColor(DeprecatedMethodCaller.getResourceColor(getActivity(), R.color.white));
        Legend legend = mLineChart.getLegend();
        legend.setEnabled(false);
        leftAxis.setDrawLabels(true);

  XAxis xAxis = mLineChart.getXAxis();
            xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
            xAxis.setDrawGridLines(false);
            xAxis.setGranularity(1f);
            xAxis.setLabelCount(3);
            xAxis.setTextColor(DeprecatedMethodCaller.getResourceColor(getActivity(), R.color.white));
            YearXAxisFormatter xAxisFormatter = new YearXAxisFormatter();
            xAxisFormatter.setMonths(xData.toArray(new String[xData.size()]));
            xAxisFormatter.setChart(mLineChart);
            xAxis.setValueFormatter(xAxisFormatter);

ArrayList<String> xData = new ArrayList<>();
ArrayList valueSet = new ArrayList<>();

 for(int i =0 ; i < listData.size();i++){
                Data data = listData.get(i);
                String monthName  = "";
                try {
                     cal.setTime(f.parse(data.getLastUpdated()));
                     monthName  = new SimpleDateFormat("MMM ''yy", 
                                               Locale.getDefault()).format(cal.getTime());
                } catch (ParseException e) {
                    e.printStackTrace();
                }
                xData.add(monthName);
                int value = Integer.valueOf((int) data.getScore());
                valueSet.add(new  Entry(i, value));
            }

            //set color
            LineDataSet barDataSet1 = new LineDataSet(valueSet, ".");
            barDataSet1.setDrawCircles(true);
            barDataSet1.setCircleRadius(4);
            LineData data = new LineData(barDataSet1);
            barDataSet1.setDrawFilled(true);
            data.setHighlightEnabled(true);
            data.setDrawValues(true);
            data.setValueTextSize(10);
            data.setValueTextColor(Color.rgb(255, 255, 255));
            xAxis.setAxisMinimum(data.getXMin() - 0.25f);
            xAxis.setAxisMaximum(data.getXMax() + 0.25f);
            YAxis leftAxis = mLineChart.getAxisLeft();
            if(data.getYMax() < 850) {
                leftAxis.setAxisMaximum(data.getYMax() + 50f);
            }else{
                leftAxis.setAxisMaximum(900f);
            }
            if(data.getYMin() > 600){
                leftAxis.setAxisMinimum(600f);
            }else{
                leftAxis.setAxisMinimum(data.getYMin() - 50f);
            }
               leftAxis.setSpaceTop(50f);
            mLineChart.setData(data);

**Comment by hkchakladar** [comment]
Is it fixed in current version?

**Comment by pj210493** [comment]
@antedesk @AmitP8745 @PhilJay @tejprakashtiwary @itzhangyang 
How can i add Unit?

**Comment by Snehalsixthsense** [comment]
For the com.github.PhilJay:MPAndroidChart:v3.0.3

I am using a label list:

final List list_x_axis_name = new ArrayList<>();
list_x_axis_name.add("label1");
list_x_axis_name.add("label2");
list_x_axis_name.add("label3");
list_x_axis_name.add("label4");
list_x_axis_name.add("label5");

and setting the label like this:

BarChart chartBar = (BarChart) findViewById(R.id.chartBar);
XAxis xAxis = chartBar.getXAxis();
xAxis.setGranularity(1f);
xAxis.setCenterAxisLabels(true);
xAxis.setLabelRotationAngle(-90);
xAxis.setValueFormatter(new IAxisValueFormatter() {
 @override
 public String getFormattedValue(float value, AxisBase axis) {
  if (value >= 0) {
   if (value <= list_x_axis_name.size() - 1) {
    return list_x_axis_name.get((int) value);
   }
   return "";
  }
  return "";
 }
});

**Comment by AbbasTuri** [comment]
You can easily do using this method...

import android.annotation.SuppressLint;
import android.content.Context;
import android.content.res.TypedArray;
import android.graphics.Canvas;
import android.graphics.Path;
import android.graphics.Rect;
import android.util.AttributeSet;
import android.widget.TextView;

@SuppressLint("AppCompatCustomView")
public class VerticalTextView extends TextView {

	public final static int ORIENTATION_UP_TO_DOWN = 0;
	public final static int ORIENTATION_DOWN_TO_UP = 1;
	public final static int ORIENTATION_LEFT_TO_RIGHT = 2;
	public final static int ORIENTATION_RIGHT_TO_LEFT = 3;

	Rect text_bounds = new Rect();
	private int direction;

	public VerticalTextView(Context context) {
		super(context);
	}

	public VerticalTextView(Context context, AttributeSet attrs) {
		super(context, attrs);

		TypedArray a = context.obtainStyledAttributes(attrs,
				R.styleable.verticaltextview);
		direction = a.getInt(R.styleable.verticaltextview_direction, 0);
		a.recycle();

		requestLayout();
		invalidate();

	}
	
	public void setDirection(int direction) {
		this.direction = direction;
		
		requestLayout();
		invalidate();
	}

	@Override
	protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
		getPaint().getTextBounds(getText().toString(), 0, getText().length(),
				text_bounds);
		if (direction == ORIENTATION_LEFT_TO_RIGHT
				|| direction == ORIENTATION_RIGHT_TO_LEFT) {
			setMeasuredDimension(measureHeight(widthMeasureSpec),
					measureWidth(heightMeasureSpec));
		} else if (direction == ORIENTATION_UP_TO_DOWN
				|| direction == ORIENTATION_DOWN_TO_UP) {
			setMeasuredDimension(measureWidth(widthMeasureSpec),
					measureHeight(heightMeasureSpec));
		}

	}

	private int measureWidth(int measureSpec) {
		int result = 0;
		int specMode = MeasureSpec.getMode(measureSpec);
		int specSize = MeasureSpec.getSize(measureSpec);

		if (specMode == MeasureSpec.EXACTLY) {
			result = specSize;
		} else {
			result = text_bounds.height() + getPaddingTop()
					+ getPaddingBottom();
			// result = text_bounds.height();
			if (specMode == MeasureSpec.AT_MOST) {
				result = Math.min(result, specSize);
			}
		}
		return result;
	}

	private int measureHeight(int measureSpec) {
		int result = 0;
		int specMode = MeasureSpec.getMode(measureSpec);
		int specSize = MeasureSpec.getSize(measureSpec);

		if (specMode == MeasureSpec.EXACTLY) {
			result = specSize;
		} else {
			result = text_bounds.width() + getPaddingLeft() + getPaddingRight();
			// result = text_bounds.width();
			if (specMode == MeasureSpec.AT_MOST) {
				result = Math.min(result, specSize);
			}
		}
		return result;
	}

	@Override
	protected void onDraw(Canvas canvas) {
//		 super.onDraw(canvas);
		
		canvas.save();
		
		int startX = 0;
		int startY = 0;
		int stopX = 0;
		int stopY = 0;
		Path path = new Path();
		if (direction == ORIENTATION_UP_TO_DOWN) {
			startX = (getWidth() - text_bounds.height() >> 1);
			startY = (getHeight() - text_bounds.width() >> 1);
			stopX = (getWidth() - text_bounds.height() >> 1);
			stopY = (getHeight() + text_bounds.width() >> 1);
			path.moveTo(startX, startY);
			path.lineTo(stopX, stopY);
		} else if (direction == ORIENTATION_DOWN_TO_UP) {
			startX = (getWidth() + text_bounds.height() >> 1);
			startY = (getHeight() + text_bounds.width() >> 1);
			stopX = (getWidth() + text_bounds.height() >> 1);
			stopY = (getHeight() - text_bounds.width() >> 1);
			path.moveTo(startX, startY);
			path.lineTo(stopX, stopY);
		} else if (direction == ORIENTATION_LEFT_TO_RIGHT) {
			startX = (getWidth() - text_bounds.width() >> 1);
			startY = (getHeight() + text_bounds.height() >> 1);
			stopX = (getWidth() + text_bounds.width() >> 1);
			stopY = (getHeight() + text_bounds.height() >> 1);
			path.moveTo(startX, startY);
			path.lineTo(stopX, stopY);
		} else if (direction == ORIENTATION_RIGHT_TO_LEFT) {
			startX = (getWidth() + text_bounds.width() >> 1);
			startY = (getHeight() - text_bounds.height() >> 1);
			stopX = (getWidth() - text_bounds.width() >> 1);
			stopY = (getHeight() - text_bounds.height() >> 1);
			path.moveTo(startX, startY);
			path.lineTo(stopX, stopY);
		}
		
		this.getPaint().setColor(this.getCurrentTextColor());
//		canvas.drawLine(startX, startY, stopX, stopY, this.getPaint());
		canvas.drawTextOnPath(getText().toString(), path, 0, 0, this.getPaint());
		
		canvas.restore();
	}
}


////////////////// Then go to XML File and call this class, where you want to modify the textview like below

 <LinearLayout
        android:id="@+id/txt_and_chart"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        android:layout_below="@id/title_layout"

        >
        <LinearLayout

            android:layout_below="@+id/toolbar_layout"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            >
            <com.example.smarthome.VerticalTextView
                android:layout_width="wrap_content"
                android:layout_height="180dp"
                android:layout_alignParentLeft="true"
                android:layout_below="@+id/title_layout"
                android:background="#455a64"
                android:padding="10dp"
                android:layout_marginTop="60dp"
                android:text="Lux Value (Y)"
                android:textStyle="bold"
                android:textColor="@android:color/white"
                android:textSize="20sp"
                app:direction="downtoup" />



        </LinearLayout>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:id="@+id/graph_layout"
        >

        <com.github.mikephil.charting.charts.LineChart
            android:layout_width="match_parent"
            android:layout_height="500dp"
            android:id="@+id/sensor_linechart"
            android:layout_below="@id/title_layout"
            android:layout_marginLeft="0dp"
            >
        </com.github.mikephil.charting.charts.LineChart>
    </LinearLayout>
    </LinearLayout>

**Comment by mariusgrams** [comment]
Hey @antedesk, I have a question to your chart. 
How do you add the titles (Range and Domain) on the side? I need a text like this.

**Comment by pallaviMN** [comment]
@mariusgrams , did u get any solution?

**Comment by arinmodi** [comment]
@mariusgrams @pallaviMN I also have same problem, can anyone post their solution if found ?
