### ISSUE TITLE
how to show dashes in xaxis 

### ISSUE THREAD

**Issue by sunitdeswal** [PhilJay/MPAndroidChart#2343]
![mdchart](https://cloud.githubusercontent.com/assets/22705584/19212536/ce9e02a0-8d70-11e6-9382-8885dc2577e3.png)

**Comment by sunitdeswal** [comment]
@PhilJay 
do you know the method for this

**Comment by PhilJay** [comment]
`yAxis.enableDashedLine(...)`

**Comment by sunitdeswal** [comment]
@PhilJay I am using  v2.1.6  and dont find any such function for xaxis .Do you know the method for this in v2.1.6
