### ISSUE TITLE
unable to set value on Xaxis by using the lastest version v3.0.0

### ISSUE THREAD

**Issue by taeyeat** [PhilJay/MPAndroidChart#2350]
such as LineData data  = new LineData(new ArrayList<String>(),new ArrayList<LineDataSet>()),android studio points out the error.
and now how to set value on Xaxis in version v3.0.0

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/The-AxisValueFormatter-interface
