### ISSUE TITLE
how to zoom in or out to the original standard?

### ISSUE THREAD

**Issue by lvwenbo0107** [PhilJay/MPAndroidChart#2354]
After I zoom in or out,which method could recovery it to the original state.I mean zoom...

**Comment by lvwenbo0107** [comment]
I mean back to 100%View. waiting for help God.

**Comment by AbdulSalamAli0018** [comment]
Yes this is a issue , should be resolved at quickly as possible.

**Comment by lvwenbo0107** [comment]
while (!negChart.isFullyZoomedOut())
                negChart.zoomOut();
            while (!posChart.isFullyZoomedOut())
                posChart.zoomOut();

**Comment by illiaNaumov** [comment]
Doesn't work for me.  I've got infinity loop `while(!mChart.isFullyZoomedOut()){
            mChart.zoomOut();
        }`

**Comment by lvwenbo0107** [comment]
Check ur lib version.My lib version is 2.2.4.
