### ISSUE TITLE
2 lines on line chart.

### ISSUE THREAD

**Issue by JImmyBhavsar** [PhilJay/MPAndroidChart#2361]
Hello,

I have added  two lines on line chart view.  The data is plotted on a chart but x-axis values are not mapping properly.  ( ex. the red line should draw until the end of screen . the 12.2 point belongs to date 29-08-16)
Please review this screenshot and share thoughts on the same.

![device-2016-10-15-151053](https://cloud.githubusercontent.com/assets/4188706/19409069/faa4273e-92e9-11e6-8f6a-b94d4dd8ef35.png)

**Comment by iRuth** [comment]
@JImmyBhavsar, please include your code.

**Comment by JImmyBhavsar** [comment]
@iRuth  Thanks for your feedback.
Please review this code.


		
	xAxis = mChart.getXAxis();
	xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setTextSize(7f);
        xAxis.setTextColor(Color.BLACK);
        xAxis.setDrawAxisLine(true);
        xAxis.setDrawGridLines(false);
        xAxis.setGranularity(0f); // only intervals of 1 day
        xAxis.setCenterAxisLabels(true);
		
		
		
		// Array 1
				String sql = " Exec sp_GSMGraphMinMaxAvg_AfKwAmVaEf @TableType ='gsmAgpAmps', @ObjKey =125, @ObjType ='Cabinet', @ValueType ='live',@StartDate ='10/13/2014', @EndDate ='10/13/2016'"
				rs = statement.executeQuery();	
					if (!rs.next()) {
                        isSuccess = false;
                    } else {
                        isSuccess = true;
                                            
						while (rs.next())
                        {
                            cnt++;
                            metricValue = rs.getFloat("MetricValue");
                            float x = Float.parseFloat(da.substring(0,da.lastIndexOf(".")));
							
                            xAxisArrayList.add(milliseconds);
                            yVals2.add(new Entry(cnt, metricValue));

                        }
		}
					
					
		// Array 2
					cnt=0;
					String sql = " Exec sp_GSMGraphMinMaxAvg_AfKwAmVaEf @TableType ='gsmAgpAmps', @ObjKey =125, @ObjType ='Cabinet', @ValueType ='live',@StartDate ='10/13/2014', @EndDate ='10/13/2016'"
					rs = statement.executeQuery();	
					if (!rs.next()) {
                        isSuccess = false;
                    } else {
                        isSuccess = true;
                      
                      while (rs.next())
                        {
                            cnt++;
                            metricValue = rs.getFloat("MetricValue");
                       
							
                            xAxisArrayList.add(milliseconds);
                            yVals1.add(new Entry(cnt, metricValue));

                        }
		}
					
					
									
					
	                LineDataSet set1, set2;

					//Dataset 1
 				    set1 = new LineDataSet(yVals1, "DataSet 1");
                    set1.setAxisDependency(YAxis.AxisDependency.LEFT);
                    set1.setColor(Color.BLACK);
                    set1.setCircleColor(Color.WHITE);
                    set1.setLineWidth(2f);
                    set1.setCircleRadius(3f);
                    set1.setFillAlpha(65);
                    set1.setFillColor(ColorTemplate.getHoloBlue());
                    set1.setHighLightColor(Color.rgb(244, 117, 117));
                    set1.setDrawCircleHole(false);
					
					
					//Dataset 2
                   set2 = new LineDataSet(yVals2, "DataSet 2");
                   set2.setAxisDependency(YAxis.AxisDependency.RIGHT);
                   set2.setColor(Color.RED);
                   set2.setCircleColor(Color.WHITE);
                   set2.setLineWidth(2f);
                   set2.setCircleRadius(3f);
                   set2.setFillAlpha(65);
                   set2.setFillColor(Color.RED);
                   set2.setDrawCircleHole(false);
                   set2.setHighLightColor(Color.rgb(244, 117, 117));
				   
				   
				   
				    ArrayList<ILineDataSet> dataSets = new ArrayList<ILineDataSet>();
                    dataSets.add(set1); // add the datasets
                    dataSets.add(set2);

                    // create a data object with the datasets
                    LineData data = new LineData(dataSets);
                    data.setValueTextColor(Color.BLUE);
                    data.setValueTextSize(9f);

                    // set data
                    mChart.setData(data);

**Comment by JImmyBhavsar** [comment]
@iRuth  can you please help me out .?
@mikemonteith can you please help me out .?

**Comment by iRuth** [comment]
Hi @JImmyBhavsar,

The `while` loops that populates the chart's y values for both data sets look the same to me, apart from `float x = Float.parseFloat(da.substring(0,da.lastIndexOf(".")));`, which is only in the first `while` loop. I don't see where you use `x` after computing a value for it. Also, what's the initial value of `cnt`?

Also, both datasets have 2 different `YAxis` dependencies, can you try setting both of them to the same `YAxis` dependency to see if you notice any change?

**Comment by JImmyBhavsar** [comment]
Hi @iRuth ,

The float x = Float.parseFloat(da.substring(0,da.lastIndexOf("."))); is storing date values but it is not used.
The cnt default value is 0.  I want dates on X-Axis so I have stored cnt and parsed it later.
We can not store string value to entry list thus I have added cnt to entry list and applied formatting on x-axis which parses cnt to date. like this.


        xAxis.setValueFormatter(new IAxisValueFormatter() {
            SimpleDateFormat mFormat = new SimpleDateFormat("dd-MM-yy");

            @Override
            public String getFormattedValue(float value, AxisBase axis) {
                if (xAxisArrayList.size() >= 0 && value >= 0) {
                    if (value < xAxisArrayList.size()) {
                        stringValue = mFormat.format((new Date((long) xAxisArrayList.get((int) value))));
                    } else {
                        stringValue = "";
                    }
                } else {
                    stringValue = "";
                }
                return stringValue;
            }

            @Override
            public int getDecimalDigits() {
                return 0;
            }
        });


Both sets have different YAxis array because I require two different line on a chart.  
The issues are X-Axis values of data set 2 is not mapping properly.

**Comment by pawan4one** [comment]
LineData data = new LineData(xVals, dataSets);
i am facing error in this line

**Comment by neerajpandey1512** [comment]
@JImmyBhavsar Hi sir, M facing the same issue with my line chart.. Wanted to know if u found any solution for this.. thanks in advance

**Comment by pawan4one** [comment]
Give me your mail or mail me at 
Pawan7408@gmail.com
I will share working code of dataset line chart

**Comment by the-maux** [comment]
I'm in the same situation of @neerajpandey1512
Any public solution available ?

**Comment by almic** [comment]
@JImmyBhavsar You reset `cnt` to `0`, that is the X axis value. By doing that, the next set starts back at `0`. You'll need to manually map the dates to `cnt`, so that the date/ MetricValue pairs actually match up, or just don't reset `cnt` after populating the first array.

@pawan4one, @neerajpandey1512, @the-maux, make sure you are all doing the same. The `Entry` uses the X value you give it, so make sure you pass the right value.
