### ISSUE TITLE
I want to set PieChart and the Legend 

### ISSUE THREAD

**Issue by wtwt91** [PhilJay/MPAndroidChart#2363]
when the length of the Legend is too long , it can not start in new line. I have already setWordWrapEnabled(true). and the piechart's position can not to set,  I want to set it in the left of the view. and the legend in the right of the view. 
how to do it? pls

**Comment by Otsoko** [comment]
I have the same issue with `CombinedChart`. When legend is too long and `setWordWrapEnabled()` is setted to `true`, only the first line is shown. See attached image as example:

![combined-chart-word-wrap](https://cloud.githubusercontent.com/assets/2643640/19418307/9676a628-93c1-11e6-8c94-12e034008b7a.png)

My legend code is as follows:

`Legend legend = combinedChart.getLegend();
legend.setPosition(Legend.LegendPosition.BELOW_CHART_CENTER);
legend.setVerticalAlignment(Legend.LegendVerticalAlignment.BOTTOM);
legend.setHorizontalAlignment(Legend.LegendHorizontalAlignment.CENTER);
legend.setOrientation(Legend.LegendOrientation.HORIZONTAL);
legend.setForm(Legend.LegendForm.CIRCLE);
legend.setWordWrapEnabled(true);
legend.setDrawInside(false);
legend.getCalculatedLineSizes();`

Method `legend.getCalculatedLineSizes();` is called just for making the lagend appear, as suggested in #2281

**Comment by Otsoko** [comment]
This is fixed in `com.github.PhilJay:MPAndroidChart:v3.0.0`
Thanks

**Comment by kishanverma26** [comment]
any suggestions how i can move legends on left side and circular piechart on right side 
currently legends is show on left side that is right but circular piechart is showing in center i just want to shift my circular pie-chart on right

**Comment by kishanverma26** [comment]
> when the length of the Legend is too long , it can not start in new line. I have already setWordWrapEnabled(true). and the piechart's position can not to set, I want to set it in the left of the view. and the legend in the right of the view.
> how to do it? pls

anything you got 

any suggestions how i can move legends on left side and circular piechart on right side 
currently legends is show on left side that is right but circular piechart is showing in center i just want to shift my circular pie-chart on right
