### ISSUE TITLE
how to Set value inside bar vertical

### ISSUE THREAD

**Issue by vivekkujur** [PhilJay/MPAndroidChart#2364]
![barchart172](https://cloud.githubusercontent.com/assets/22867625/19416961/6d8ec082-93bd-11e6-8459-f51cf26476c3.png)

**Comment by AbdulSalamAli0018** [comment]
can you please show the source code ?

**Comment by vivekkujur** [comment]
this image is for example.
i want to bar value vertical in the bar like this image..

chart.setValueAboveBar(false);
by this  method value is display in bar but its horizontal..

how can i set vertical .

**Comment by PhilJay** [comment]
Unfortunately this is not supported by default - you will have to modify the library to achieve this.
