### ISSUE TITLE
Some dataset cannot show on PieChart

### ISSUE THREAD

**Issue by sincerelamb** [PhilJay/MPAndroidChart#2365]
if a dataset contains 1 in array, like "5"1""2""3""4", the color in the piechart of the number "1"  cannot be shown.

**Comment by sincerelamb** [comment]
[https://twitter.com/sincerelambyy/status/786869281837330436](url)

**Comment by nleveque** [comment]
I have the same problem, I have found no solution

**Comment by sincerelamb** [comment]
I have a way : just double every number in the chart and set the legend original number. But this is not the best way...

**Comment by PhilJay** [comment]
#2385
