### ISSUE TITLE
LineChart fill the data is only one point or two points, why the X axis Label with the data is not a one-to-one correspondence

### ISSUE THREAD

**Issue by foxsent** [PhilJay/MPAndroidChart#2366]
LineChart fill the data is only one point or two points, why the X axis Label with the data is not a one-to-one correspondence
![f61f5cce-cc21-4911-95a7-faac11229b14](https://cloud.githubusercontent.com/assets/8345066/19428886/40dda162-947f-11e6-9e05-2af7d7350d64.png)

**Comment by PhilJay** [comment]
Looks like there are integers rounded in the axis. If you use decimals or set axis granularity to 1f, this should disappear.
