### ISSUE TITLE
Feature request: Limit line label position outside the graph area

### ISSUE THREAD

**Issue by kaciula** [PhilJay/MPAndroidChart#237]
It would be really nice if there were a way to position the labels for the limit lines a little bit outside the actual drawing area for the graph. Right now, depending on the graph data, the graph lines and graph fill colors can go over the labels and make them hard/impossible to see.

**Comment by aalap-shah** [comment]
Hey Phil,

Its a great library , thanks .. I wanted to know if this enhancement is implemented ? Is there a way I can achieve this ? Thanks in advance.
