### ISSUE TITLE
how to put legend label on the left hand side of the legend form

### ISSUE THREAD

**Issue by farshidcivil** [PhilJay/MPAndroidChart#2378]
I have a graph in my app that is drawn using MPAndroid .
The problem is : how to put legend label on the left hand side of the legend form ? The below picture shows my problem
[![enter image description here][1]][1] 

  [1]: https://i.stack.imgur.com/zlJGD.png

I want to put legend forms (circles)  on the right hand side of the legend label

**Comment by zhangruize** [comment]
Get `Legend` from your `Chart` firstly.Then 
`legend.setDirection(Legend.LegendDirection.RIGHT_TO_LEFT);`
