### ISSUE TITLE
First and last data points are being cut in bubble chart

### ISSUE THREAD

**Issue by vicmns** [PhilJay/MPAndroidChart#2379]
Hey Guys, just notice that you release version 3.0 of the library, but I've been seeing the same problem since the earliest versions of 3.0.

Just as the title says, all the bubble contained on the first and last indexes are being cut regardless the bubble size as you can see in the attached image, (and it makes sense since the rendering is being made by the data set)
![screenshot_20161020-105557](https://cloud.githubusercontent.com/assets/1101060/19567820/d818c962-96b4-11e6-8b50-b973fa2b3dba.png)

Is there any way to prevent this? Maybe adding dummy data at start and end, but it sounds kind of cumbersome and I'm not sure how to handle it with the Axis Value Formatter...

**Comment by PhilJay** [comment]
You can avoid this by setting the x-axis range from -0.5 to maximum-x-value + 0.5.

So if your bubbles range from x = 0 to x = 10, call:

`xAxis.setAxisMinimum(0.5f)`
`xAxis.setAxisMaximum(10.5f)`
