### ISSUE TITLE
Barchart spacing and new data

### ISSUE THREAD

**Issue by saiidabs** [PhilJay/MPAndroidChart#2380]
I have two problems:
1. the spacing of the bars , they are not the same, and how to pad it away from the y-axis
![barchart](https://cloud.githubusercontent.com/assets/10105522/19586508/3f3a510a-97a1-11e6-89d2-2e1a35cf75ca.png)

2. Once i click on the button on the bottom , i realload the data, to the chart, but i have a problem with the x-axis, always getting a java.lang.IndexOutOfBoundsException:  
 return  (waterRecs.get((int)value).getDate());
from the AxisValueFormatter
![prob](https://cloud.githubusercontent.com/assets/10105522/19586530/71f11584-97a1-11e6-82f9-3da413c1f0fe.png)

**Comment by saiidabs** [comment]
here is the whole class

public class WaterChart extends Fragment
{
    protected BarChart barchart;
    public ArrayList<WaterRec> waterRecs;
    private   String[] TEXTS = { "Image #1", "Image #2", "Image #3" };
    private Button monthly, daily, yearly;
    private static final Integer DAY =1;
    private static final Integer MONTH =2;
    private static final Integer YEAR = 3;

    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        String myTag = getTag();
        ((WaterInfoTabs)getActivity()).setGraphTag(myTag);


    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
    {
        // Inflate the layout for this fragment
        View rootView = inflater.inflate(R.layout.fragment_water_chart, container, false);
        barchart = (BarChart)rootView.findViewById(R.id.water_bar);
        monthly = (Button)rootView.findViewById(R.id.monthlyChart);
        daily = (Button)rootView.findViewById(R.id.dailyChart);
        yearly  = (Button)rootView.findViewById(R.id.Yearlychart);

        monthly.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
               setchart(MONTH);
            }
        });

        daily.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                setchart(DAY);
            }
        });

        yearly.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                setchart(YEAR);
            }
        });


        return rootView;
    }

    @Override
    public void onActivityCreated(Bundle savedInstanceState)
    {
        super.onActivityCreated(savedInstanceState);

        //Default, start with daily
        waterRecs =  ((WaterInfoTabs)getActivity()).db.getDailyWaterSumRecord();
        if(waterRecs !=null)
        {
            displayChart();
        }
    }

    private void displayChart()
    {
        barchart.setDrawBarShadow(false);
        barchart.setDrawValueAboveBar(true);


        barchart.setDescription("");

        // if more than 60 entries are displayed in the chart, no values will be
        // drawn
        barchart.setMaxVisibleValueCount(60);

        // scaling can now only be done on x- and y-axis separately
        barchart.setPinchZoom(false);

        barchart.setDrawGridBackground(false);
        // barchart.setDrawYLabels(false);



        System.out.println("Size of water recs" + waterRecs.size());
        AxisValueFormatter formatter = new AxisValueFormatter()
        {

            @Override
            public String getFormattedValue(float value, AxisBase axis)
            {

                System.out.println(value);
                return  (waterRecs.get((int)value).getDate());
            }

            // we don't draw numbers, so no decimal digits needed
            @Override
            public int getDecimalDigits() {  return 0; }
        };

        XAxis xAxis = barchart.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setTypeface(((WaterInfoTabs)getActivity()).opens);
        xAxis.setLabelCount(4);
        xAxis.setDrawGridLines(false);
        xAxis.setGranularity(1f); // only intervals of 1 day
        xAxis.setValueFormatter(formatter);
        xAxis.setAvoidFirstLastClipping(true);


        YAxis leftAxis = barchart.getAxisLeft();
        leftAxis.setTypeface(((WaterInfoTabs)getActivity()).opens);
        leftAxis.setLabelCount(8, false);
        leftAxis.setDrawGridLines(true); // no grid lines
        leftAxis.setPosition(YAxis.YAxisLabelPosition.OUTSIDE_CHART);
        leftAxis.setSpaceTop(15f);
        leftAxis.setAxisMinValue(1f); // this replaces setStartAtZero(true)



        barchart.getAxisRight().setEnabled(false);




        Legend l = barchart.getLegend();
        l.setVerticalAlignment(Legend.LegendVerticalAlignment.BOTTOM);
        l.setHorizontalAlignment(Legend.LegendHorizontalAlignment.CENTER);
        l.setOrientation(Legend.LegendOrientation.HORIZONTAL);
        l.setDrawInside(false);
        l.setForm(Legend.LegendForm.SQUARE);
        l.setFormSize(9f);
        l.setTextSize(11f);
        l.setXEntrySpace(4f);


        barchart.animateY(2000);
        barchart.invalidate();
        barchart.setFitBars(true);

        setData();


    }

    private void setData()
    {
        float start = 0f;

        barchart.getXAxis().setAxisMinValue(start);

        ArrayList<BarEntry> yVals1 = new ArrayList<BarEntry>();


        double d = 0.0;
        float f = 0;
        for (int i = 0; i < waterRecs.size(); i++) {
            d = waterRecs.get(i).getAmount();
            f = (float) d;
            yVals1.add(new BarEntry(i, f));
        }

        BarDataSet set1;

        if (barchart.getData() != null && barchart.getData().getDataSetCount() > 0)
        {
            set1 = (BarDataSet) barchart.getData().getDataSetByIndex(0);
            set1.setValues(yVals1);
            barchart.getData().notifyDataChanged();
            barchart.notifyDataSetChanged();
        }
        else
        {
            set1 = new BarDataSet(yVals1, "Amount consumed");
            set1.setColors(ColorTemplate.COLORFUL_COLORS);

            ArrayList<IBarDataSet> dataSets = new ArrayList<IBarDataSet>();
            dataSets.add(set1);

            BarData data = new BarData(dataSets);
            data.setValueTextSize(10f);
            data.setValueTypeface(((WaterInfoTabs) getActivity()).opens);
            data.setBarWidth(0.9f);

            barchart.notifyDataSetChanged();
            barchart.setFitBars(true);
            barchart.setData(data);
        }

    }



    public void setchart(int time)
    {

        if(time == DAY)
        {
            waterRecs =  ((WaterInfoTabs)getActivity()).db.getDailyWaterSumRecord();
        }
        else if(time == MONTH)
        {
            waterRecs =  ((WaterInfoTabs)getActivity()).db.getMonthlyWaterSumRecord();
        }
       else if(time == YEAR)
        {
            waterRecs =  ((WaterInfoTabs)getActivity()).db.getYearlySumRecord();
        }


        if(waterRecs !=null)
        {
            System.out.println(waterRecs.size());
            setData();
            barchart.invalidate();
        }

    }

}

**Comment by PhilJay** [comment]
Your horizontal chart content extends from 0 - 3. The center of your bars is set to 0 - 2, this is why the chart looks the way it does. You can change that by either calling `chart.fitBars()` to automatically adjust the size of the chart area to the content, or manually set the range of the x-axis from -0.5 to +2.5
`xAxis.setAxisMinimum(...)`
`xAxis.setAxisMaximum(...)`

**Comment by saiidabs** [comment]
@PhilJay how do i deal with the out of bounds problem with the  x- axis  setvalueformater, doesn't refresh , once a new data set is given to the chart
