### ISSUE TITLE
Add lables to xAxis

### ISSUE THREAD

**Issue by qwerty2121212** [PhilJay/MPAndroidChart#2382]
In the previous version adding labels to x-Axis was

BarData barData=new BarData(labels,dataset);

but in a recent version, the same line shows error.
and I could not find an alternative.

Can I get a complete code which shows String in the x-axis

**Comment by Bigscaltest** [comment]
I want to render x-Axis values using IAxisValueFormatter extension.but it does't work for me in swift 3.

Can you please provide guidance on it?

**Comment by qwerty2121212** [comment]
U can refer this it might help @Bigscaltest 

https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/custom/DayAxisValueFormatter.java

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/The-AxisValueFormatter-interface
