### ISSUE TITLE
Define chart size relative to an other one

### ISSUE THREAD

**Issue by MGaetan89** [PhilJay/MPAndroidChart#2384]
Hi,

I am looking into replacing my home-made charts in my application with your library, using the latest 3.0 release.
It looks great and seems to be doing everything I need, except for one point.

I would like to display two charts (let's say one line chart and one bar chart):
- The first chart has a left and a right axis, but no visible bottom axis
- The second chart has a bottom axis, but no visible left or right axis

What I want to achieve, is having the second chart taking the same horizontal space as the first chart (the line part only, without the axis). The result is similar to the following screenshot:
![screenshot_20161021-145605](https://cloud.githubusercontent.com/assets/1009664/19599142/74ed95de-979f-11e6-9669-533b985b9707.png)

As you can see, the second chart as some free space on the left and on the right, to align itself with the first chart. Is there a way to do that? If not, do you have any idea how I could implement it myself?

I also need to sync events (zoom & drag) between those two charts. But I've seen that we can provide listener to those events, so this should be easy to handle myself.

Thanks for your help

**Comment by PhilJay** [comment]
I'm not exactly sure I fully understand what you want to achieve, but have you looked into the `chart.serViewPortOffsets(...)` method? This method allows you to manually set the space between the actual chart content and the borders of the chart view.

**Comment by MGaetan89** [comment]
The two charts are backed by the same data, but the representation is different. I try to keep them in sync, so the placement, zoom, ... are the same on both charts.
`chart.serViewPortOffsets(...)` is what I needed. Thanks for your help!
