### ISSUE TITLE
if PieEntry(1f, "STRINGKEY") is set then NO COLOR (BUG)

### ISSUE THREAD

**Issue by azaabudeen** [PhilJay/MPAndroidChart#2385]
i have found a bug, 
when ever we enter 1f or less then 1f in the entries....it doesnt add color in the piechart,this issue is not only for my app..but the sample app is also having same issue,

```
    entries.add(new PieEntry(1f, "Monday"));
    entries.add(new PieEntry(1f,"Tuesday"));
    entries.add(new PieEntry(1f,"Wednesday"));
    setPieChart(entries);
```

I will get 3 entities but with no color,
Please fix this issue

**Comment by anuragphadke19** [comment]
#2393 . Looks like I a running into the same issue. Didn't realise this was already logged as bug. I will close mine as duplicate.

**Comment by joker-fu** [comment]
How to solve? I also encountered the same problem.

**Comment by anuragphadke19** [comment]
@PhilJay , any pointers on where I should be looking at to fix this? I would be happy to give it a try and see if I can.

**Comment by azaabudeen** [comment]
@PhilJay  please solve this issue as soon as possible

**Comment by vincent-paing** [comment]
+1

**Comment by 1758376079** [comment]
The problem (bug) on some models
