### ISSUE TITLE
Help！Help！Fill color between two line charts

### ISSUE THREAD

**Issue by 120660021** [PhilJay/MPAndroidChart#2386]
I used it setFillFormatter，Failed to achieve，
![05d9680e-0068-40c6-8605-7c2d8a554882](https://cloud.githubusercontent.com/assets/8433054/19617700/a942a0e8-9869-11e6-9c53-465e0ee17537.png)

**Comment by PhilJay** [comment]
This example shows how to get a fill color between lines by using the chart background as the color and filling the space above and below with white:
https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/FilledLineActivity.java

**Comment by 120660021** [comment]
![1f4565dc-f011-49a3-b833-b37b1ecdcdd9](https://cloud.githubusercontent.com/assets/8433054/19620172/aba9a026-98a9-11e6-8943-99132b9dfb34.png)

help！！！This effect can not be achieved？

**Comment by 120660021** [comment]
@PhilJay

**Comment by amitks2015** [comment]
@120660021 
Please take a look at https://github.com/PhilJay/MPAndroidChart/issues/3016
