### ISSUE TITLE
How to change Circle color in line chart if values are dynamically inserted? 

### ISSUE THREAD

**Issue by danishkaleem095** [PhilJay/MPAndroidChart#2387]
Hi,
 I am using line chart and adding values in it dynamically I want to change circle color for specific values how to do it? 
 `public void addEntry(float yValue) {

        LineData data = lineChart.getData();

        ILineDataSet set = data.getDataSetByIndex(0);

        if (set == null) {
            set = createSet();
            data.addDataSet(set);
        }

        // choose a random dataSet
        int randomDataSetIndex = (int) (Math.random() * data.getDataSetCount());
        data.addXValue(" ");
        Entry entry=new Entry( yValue,data.getDataSetByIndex(randomDataSetIndex).getEntryCount());
        data.addEntry(entry, 0);
        data.notifyDataChanged();

        // let the chart know it's data has changed
        lineChart.notifyDataSetChanged();

        lineChart.setVisibleXRangeMaximum(6);
        //mChart.setVisibleYRangeMaximum(15, AxisDependency.LEFT);
//
//            // this automatically refreshes the chart (calls invalidate())
        lineChart.moveViewTo(data.getXValCount() - 7, 50f, YAxis.AxisDependency.LEFT);

    }

    private LineDataSet createSet() {

        LineDataSet set = new LineDataSet(null, "DataSet 1");
        set.setLineWidth(2.5f);
        set.setCircleRadius(6.5f);
        set.setCircleHoleRadius(3.5f);
        set.setColor(Color.parseColor("#ffffff"));
        set.setCircleColor(Color.parseColor("#ffffff"));
        set.setCircleColorHole(Color.parseColor("#039BE5"));
        set.setHighLightColor(Color.rgb(190, 190, 190));
        set.setAxisDependency(YAxis.AxisDependency.LEFT);
        set.setValueTextColor(Color.parseColor("#ffffff"));
        set.setValueTextSize(10f);

        return set;
    }`

**Comment by PhilJay** [comment]
You can just dynamically insert new colors as well. That way your newly inserted circles will have the newly inserted color.

**Comment by danishkaleem095** [comment]
When i do this all circle color changed no for the new one

**Comment by danishkaleem095** [comment]
new version

**Comment by danishkaleem095** [comment]
sorry wrong
