### ISSUE TITLE
Cannot set string as value in xaxis in new version

### ISSUE THREAD

**Issue by john1jan** [PhilJay/MPAndroidChart#2389]
I cannot set any string values in Xaxis . Which was there in earlier version

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/The-AxisValueFormatter-interface

**Comment by john1jan** [comment]
I read the doc . But getFormattedValue(float value, AxisBase axis)  gives me float value , which i have to map to string. But i dont have that mapping. I have a list of string which comes form server. I was adding in xvals and plotting it before. After i updated there is no way to do that. I dont know the mapping of xvalues

**Comment by john1jan** [comment]
OK Got it... i can use the list returned form the server and use float value as index

**Comment by john1jan** [comment]
Am i right @PhilJay  ?

**Comment by PhilJay** [comment]
Yes!
