### ISSUE TITLE
help me ,bar chart  problem.

### ISSUE THREAD

**Issue by Oterman1314** [PhilJay/MPAndroidChart#2391]
## the result is like below,no bars display,i don't what's wrong,plesse help me,thanks a lot!
![363669528834759935](https://cloud.githubusercontent.com/assets/11433660/19626043/c2f20b72-995a-11e6-96f9-ccd49dcf812a.png)

this is my code:

`List<BarEntry> entries=new ArrayList<BarEntry>();
                    for(SportRecord record:list){
                        float x=Float.parseFloat(record.getDateStr());
                        float y=record.getRecord();
                         BarEntry barEntry=new BarEntry(x,y);
                        entries.add(barEntry);
                    }
                    
                    BarDataSet dataSet=new BarDataSet(entries,"记录");
                    dataSet.setColors(ColorTemplate.MATERIAL_COLORS);

                    BarData data=new BarData(dataSet);
                    data.setValueTextSize(10f);
                    data.setBarWidth(0.9f);

                    XAxis xAxis = barChart.getXAxis();
                    xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
                    xAxis.setDrawGridLines(false);

                    YAxis yAxis=barChart.getAxisRight();
                    yAxis.setEnabled(false);
                    yAxis.setDrawGridLines(false);

                    YAxis leftAxis=barChart.getAxisLeft();
                    leftAxis.setEnabled(false);
                    leftAxis.setDrawGridLines(false);

                    xAxis.setValueFormatter(new MyXFormater());
                    barChart.setData(data);

                    barChart.invalidate();`

MyXFormater.java:

public class MyXFormater implements IAxisValueFormatter {

    SimpleDateFormat sourceFormat;
    SimpleDateFormat resultFormat;

    public  MyXFormater(){
        sourceFormat=new SimpleDateFormat("yyyyMMdd");
        resultFormat=new SimpleDateFormat("MM.dd");
    }

    @Override
    public String getFormattedValue(float value, AxisBase axis) {
        String result=null;
        try {
            int i= (int) value;
            Date date = sourceFormat.parse(i + "");
             result = resultFormat.format(date);

        } catch (ParseException e) {
            e.printStackTrace();
        }
        return result;

    }

    @Override
    public int getDecimalDigits() {
        return -1;
    }
}
`

**Comment by Oterman1314** [comment]
# please help me,this issue puzzled me whole day! i nearly crashed!
Thanks a lot

**Comment by PhilJay** [comment]
You are using date long's on the x-axis, meaning that your x-axis range is most likely > 1.000.000, yet you set the width of the bars to be 0.9f 

My point: **Your bar width is so small that bars are not visible.**

**Comment by Oterman1314** [comment]
problem solved.Thanks a lot.

**Comment by zhengxuming** [comment]
你咋解决的，说说
