### ISSUE TITLE
The PieChart sector color 2 bugs

### ISSUE THREAD

**Issue by joker-fu** [PhilJay/MPAndroidChart#2394]
1 .    ArrayList<PieEntry> list = new ArrayList<>();
        list.add(new PieEntry(0, "sector1"));
        list.add(new PieEntry(0, "sector2"));
        list.add(new PieEntry(2, "sector3"));
        list.add(new PieEntry(0, "sector4"));
        list.add(new PieEntry(1, "sector5"));
        setData(list);

bug1: Sector 5 without color, after touching can be displayed.
1.     ArrayList<PieEntry> list = new ArrayList<>();
       list.add(new PieEntry(0, "sector1"));
       list.add(new PieEntry(0, "sector2"));
       list.add(new PieEntry(53565, "sector3"));
       list.add(new PieEntry(0, "sector4"));
       list.add(new PieEntry(66, "sector5"));
       setData(list);

bug2: Sector 5 color filled the pie chart.

**Comment by norcdeveloper** [comment]
I ran into the same bug1( didn't test bug2). For my test, if the value is 1, then the color is not drawn. For my use case, since I am just displaying integer numbers, I use a workaround to test if the value==1, then set value=1.001f. This is not desired workaround.

**Comment by joker-fu** [comment]
#Bug2 not implemented? This is what I encountered in the work, I chose to use v2.2.5.
