### ISSUE TITLE
How to programmatically select values in PieChart?

### ISSUE THREAD

**Issue by fatemeh2sh** [PhilJay/MPAndroidChart#240]
hi ,
i have a listview. i want click on item of listview then selected section of piechart.
how can i do?

Regards fatemeh

**Comment by Manhazito** [comment]
@PhilJay 
Hi!
I click a value on the graph and it gets selected. When I then call  `highlightValues(...)` or `highlightTouch(...)` it gets deselected, but the next click on the graphic is ignored. It looks like it's waiting for that click to deselect the value...

Is there a way around this behavior?

Thanks!

**Comment by jeanbaptisteODE** [comment]
@Manhazito Hi ! 

Did you find the solution ? 
I have the same problem ... I still need to click twice on the slice to re-select it ...

thx

**Comment by Manhazito** [comment]
@jeanbaptisteODE 
I did not! :-/

**Comment by IvanSimovic** [comment]
@jeanbaptisteODE
@Manhazito 
mChart.highlightValue(null); worked for me

**Comment by anilthummar** [comment]
Hello Everyone,

How to set text format in Reverse like in circle wise,Please check attached image i want to set text like this in app using MPchart Lib in android.
![capture](https://user-images.githubusercontent.com/7361686/38038816-7d5d5ff8-32c9-11e8-9840-d565e15c5ccc.PNG)

**Comment by mazend** [comment]
I leave a comment for you guys.
I could call onValueSelected() in my RecyclerView Adapter.

**pieChart.highlightValue(highlight, true);**


```
 @Override
    public void onBindViewHolder(ViewHolder holder, int position) {

        holder.rl_root.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Highlight highlight = new Highlight((float)position, 0.0f, 0);
                //pieChart.highlightValue(highlight); //doesn't call onValueSelected()
                pieChart.highlightValue(highlight, true); //call onValueSelected()
            }
        });

    }
```

**Comment by alierdogan7** [comment]
```
PieEntry entry = new PieEntry(value, label);        
pieChart.highlightValue(0, entry.getY(), dataSetIndex);
```

```highlightValue``` first parameter should always be 0, and the second is the Y value of that entry, and last one is dataSetIndex which will be 0 if you use only one dataset in your plot.

**Comment by Andjdd** [comment]
你好，如何设置pieChart 默认高亮和突出一部分

**Comment by kushal96k** [comment]
hi guys,
we are looking for a pie chart with selected slice  data to be get displayed 
 Thank you
