### ISSUE TITLE
How is LineData less constructed? Did not add X-axis data?

### ISSUE THREAD

**Issue by BigSea001** [PhilJay/MPAndroidChart#2411]
Today, when doing version iteration MPAndroidChart updated version, but found a lot of methods are less, for example:
public LineData (List <String> xVals, ILineDataSet dataSet) {
         Super (xVals, toList (dataSet));
     }
I would like to ask what alternative?

**Comment by Zarwan** [comment]
I am also in this situation. Is it still possible to setup string labels for the x-axis?

**Comment by Zarwan** [comment]
Try #2105 or #2283.
