### ISSUE TITLE
Pie Chart can't show one part background color

### ISSUE THREAD

**Issue by lodaDuan** [PhilJay/MPAndroidChart#2424]
Pie Chart can't show one part background color in PieChartActivity.
Add data such as
entries.add(new PieEntry((float) 2, "Part A"));
entries.add(new PieEntry((float) 6, "Part B"));
entries.add(new PieEntry((float) 1, "Part C"));
"Part C" can't show background color,but click it can show color

**Comment by BusyCount** [comment]
I have the same problem too.I did a number of tests, found that the value of pie chart can not be set to 1

**Comment by iammrj** [comment]
Me too got the same issue.
Don't know how to fix it

**Comment by dphillipsprosper** [comment]
Same thing is happening to me. Values <= 1 will not draw the background color, unless highlighted.
