### ISSUE TITLE
Duplicate XAxis Labels

### ISSUE THREAD

**Issue by AdamMak** [PhilJay/MPAndroidChart#2437]
I am trying to create a basic bar chart but am really struggling to get the XAxis labels display properly. The XAxis labels are duplicating for some reason. Here is my cide

` final String[] quarters = new String[] { "Jan", "Feb", "March", "April" };`

   ```
IAxisValueFormatter formatter = new IAxisValueFormatter() {

            @Override
            public String getFormattedValue(float value, AxisBase axis) {
                return quarters[(int) value];
            }

            @Override
            public int getDecimalDigits() {  return 0; }
        };

        XAxis xAxis = chart.getXAxis();
        xAxis.setValueFormatter(formatter);

        List<BarEntry> entries = new ArrayList<>();
        entries.add(new BarEntry(0f, 30f));
        entries.add(new BarEntry(1f, 80f));
        entries.add(new BarEntry(2f, 60f));
        entries.add(new BarEntry(3f, 50f));

        BarDataSet set = new BarDataSet(entries, "BarDataSet");
        BarData data = new BarData(set);
        chart.setData(data);
        chart.setFitBars(true);
        chart.invalidate(); // refresh
```

And the chart that is created looks like this

![screen shot 2016-11-03 at 14 31 11](https://cloud.githubusercontent.com/assets/17201601/19969972/6e24edf0-a1d2-11e6-8ce5-b71ccba279ce.png)

Any idea why this is happening? I just want one label per value. Any help would be much appreciated

**Comment by sachinrana135** [comment]
Same here. Moreover, I am also facing an overlapping issue. See below. 
![screenshot_2016-11-04-11-43-46](https://cloud.githubusercontent.com/assets/23253712/19996281/6ff09b36-a284-11e6-80d8-b4ff79b67113.png)

**Comment by sachinrana135** [comment]
I resolved this. just added one line.

`xAxis.setGranularity(1f);`

**Comment by AdamMak** [comment]
Cheers, that seems to do the trick!

**Comment by rajeesh7** [comment]
I did the same but not working. The X axis labels are repeating. 
For y axis I have disabled the zooming already.
ANy solution ?

**Comment by StevenTB** [comment]
> I did the same but not working. The X axis labels are repeating.
> For y axis I have disabled the zooming already.
> ANy solution ?

Might be late, but you can try to activate the granularity before setting it at 1f. Moreover, you can set the label count following these lines :

`XAxis xAxis = barChart.getXAxis();
barChart.getXAxis().setGranularityEnabled(true);
 barChart.getAxisLeft().setGranularity(1f);
 xAxis.setLabelCount(labelCount, false);

`
