### ISSUE TITLE
About MarkerView

### ISSUE THREAD

**Issue by xf222zt** [PhilJay/MPAndroidChart#246]
Hi Phil
        I had overwirte the MarkerView to make it fit my app。But when the content in the view be little more，its posionton on chart will be moved some pixels from the exact place。
     How can i deal with it？

**Comment by Bishalsingh** [comment]
https://github.com/PhilJay/MPAndroidChart/issues/285#event-217315895

**Comment by PhilJay** [comment]
As of the latest commit, any **issues concerning the position** of the `MarkerView` should be fixed.

The `MarkerView` now provides **2 abstract methods from which the desired offsets have to be returned**: [AbstractMarkerView class](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/com/github/mikephil/charting/utils/MarkerView.java)

The implementation looks like the following: [Custom MarkerView implementation](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/MyMarkerView.java)

By returning `-(getWidth() / 2);` from the `getXOffset()` method, the `MarkerView` will be centered horizontally.

By returning `-getHeight()` from the `getYOffset()` method, the `MarkerView` position will be above the selected value.
