### ISSUE TITLE
X-Axis Textpositions wrong

### ISSUE THREAD

**Issue by darksider110** [PhilJay/MPAndroidChart#2489]
I have a chart with x values, which all have different textheights for example the month of the year:

Jan, Feb, Mar, Apr, May, Juni, July, Aug

Some of the word are different high because of letters like 'p' or 'g'

Because of these letters the text of the x-axis is displayed on different y-values

**Comment by GoneUp** [comment]
Could you add a screenshot?

**Comment by darksider110** [comment]
![device-2016-11-22-104755](https://cloud.githubusercontent.com/assets/22616554/20518992/7bf047d0-b0a1-11e6-9706-0355eddb7ccf.png)

**Comment by jonathankofahl** [comment]
You need to give the legend more space. You can do that with an offset to the chartView, for example like this:

_barChartView.extraBottomOffset = 20;

**Comment by darksider110** [comment]
Sorry for the late answer, but your comment helped alot :) thanks :)
