### ISSUE TITLE
Multiple line charts working in real time simultaneously

### ISSUE THREAD

**Issue by mroavi** [PhilJay/MPAndroidChart#2490]
Is it feasible to have the **RealTimeLineChartActivity** and **MultiLineChartActivity** examples merged in one? I.e. to have **multiple line charts** working in **real time** simultaneously.

I suspect that the `ChartDataAdapter` and its `getView` method might not support this scenario. I would really appreciate if you give me your thoughts on this. Regards.

**Comment by mroavi** [comment]
The answer is yes it is feasible.

**Comment by wonjsohn** [comment]
Would you mind sharing how you did it? I am thinking something similar, having multiple real time charts displayed simultaneously and would benefit from what you did if it is available. ..

**Comment by mroavi** [comment]
I'm not allowed to. Sorry.
