### ISSUE TITLE
Legend margin

### ISSUE THREAD

**Issue by skadyrov** [PhilJay/MPAndroidChart#252]
Hi,

I could not find a way to set margin or padding around the legend. Seems this is not possible at all. I tried setOffsetTop and setOffsetBottom (and other setOffsets), but none of them had any effect on spacing around the legend. See picture below
![device-2014-12-04-162604](https://cloud.githubusercontent.com/assets/2365058/5301142/8947a8d0-7bd6-11e4-97ef-d923d62fa844.png)

**Comment by PramodGarg** [comment]
Any update on this?

**Comment by JagadishaIncture** [comment]
piechart and legend is overlaping same issue

**Comment by nscRodolfo** [comment]
ANY UPDATE!!!!????

**Comment by dinhletrieuduong** [comment]
I use chart.setExtraOffsets(0, 0, 0, 10) and it works for me
![120904082_743862709804083_4273892011875972252_n](https://user-images.githubusercontent.com/39703705/95414867-1096f500-0959-11eb-9879-0263a6de5393.jpg)
