### ISSUE TITLE
Labels for HorizontalBarChart

### ISSUE THREAD

**Issue by jsmontteiro** [PhilJay/MPAndroidChart#2529]
Hi, I'm using horizontal bar chart in version 2.2.5 and set labels for each bar, like image below 

Version 2.2.5

![horizontalbarchart](https://cloud.githubusercontent.com/assets/2491217/20710796/41f69b88-b623-11e6-8113-fd5fc162c4ad.png)

When I upgraded version to 3.0.1, I don't find method setXVals()

can you help me?

**Comment by GameChanger001** [comment]
Could u paste your code it will be easy to help

**Comment by jsmontteiro** [comment]
I used to set values in constructor of BarData, but now is not allowed

Version 2.2.5
BarData data = new BarData(xVals, dataSets);

Version 3.0.1
BarData data = new BarData(dataSets);

**Comment by iRuth** [comment]
@jsmontteiro you would need to use an `AxisValueFormatter` to display the labels. Take a look at the [doc here](https://github.com/PhilJay/MPAndroidChart/wiki/The-AxisValueFormatter-interface) and [this example formatter](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/custom/DayAxisValueFormatter.java) used [here](https://github.com/PhilJay/MPAndroidChart/blob/d65ffb88712e682e4ecdbee5cb0d706a327a91b6/MPChartExample/src/com/xxmassdeveloper/mpchartexample/BarChartActivity.java#L81-L107).

**Comment by GameChanger001** [comment]
It won't be easier for adding few labels. It will be useful only for large data sets.

**Comment by GameChanger001** [comment]
hey how did u get values on top of each bar @jsmontteiro 
could u paste the code i have the same requirement.

**Comment by zhangyanru** [comment]
you can set x values like this:
`IAxisValueFormatter formatter = new IAxisValueFormatter() {
            @Override
            public String getFormattedValue(float value, AxisBase axis) {
                if (value < 0 || value >= xVals.size()) {
                    return "";
                }
                return xVals.get((int) value);
            }

            @Override
            public int getDecimalDigits() {
                return 0;
            }
        };
        barChart.getXAxis().setValueFormatter(formatter);`
