### ISSUE TITLE
set space between labels in x-Axis

### ISSUE THREAD

**Issue by GameChanger001** [PhilJay/MPAndroidChart#2531]
I have a long string as a label so my labels overlap. It would look good if I reduce the no of labels or set the spacing between labels. I couldn't find any related to that issue. pl reply Asap

**Comment by sebastiande** [comment]
+1

In my case 30 data points with dates (2016-12-12) on a Nexus 5X.

**Comment by GameChanger001** [comment]
Hi.. 
I solved it with this
XAxis xAxis=chart.getXAxis();
xAxis.setLabelCount(4,true);

Just reduce the label count
Let me know whether it helped

**Comment by dxshindeo** [comment]
The above mentioned works, but only if the data are numbers/dates. If your data is series (for example, strings such as "Apple", "Orange", "Banana"), then only 4 of those string values would be seen. The rest would only show up if user zooms in the graph. But, when a user looks at this graph, he has no idea that there are more values there, he just sees 4 fruits and nothing else.

**Comment by almic** [comment]
@dxshindeo then make the graph extend off the screen by [restricting the view port](https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport)
