### ISSUE TITLE
HorizontalBarChart moveViewToX don't work

### ISSUE THREAD

**Issue by zhangyanru** [PhilJay/MPAndroidChart#2546]
I used methods moveViewToX() in horizontalBarChart ,and it doesn't work. What should I do?

**Comment by zhangyanru** [comment]
@nielsz @Pitel @dseider @mikemonteith @matiash

**Comment by zhangyanru** [comment]
I solved this issue by set right yValue.
this is not work code:
`horizontalBarChart.moveViewTo(xVals.size() - 1, 0 , YAxis.AxisDependency.LEFT);`
And I change yValue like this:
`horizontalBarChart.moveViewTo(xVals.size() - 1, phoneModelBarChart.getAxisLeft().getAxisMaximum(), YAxis.AxisDependency.LEFT); `
It works good.

**Comment by adil-hussain-84** [comment]
This is an open issue in my opinion. The `moveViewToX(...)` method should work as expected. The `moveViewTo(...)` call as above just happens to be a fortunate workaround.
