### ISSUE TITLE
I am trying to plot two different integer values for y axis and and dates for xaxis 

### ISSUE THREAD

**Issue by Adeyiwunmi** [PhilJay/MPAndroidChart#2549]
please i need to know how to input integer values for y axis parameters, (two different parameters ) and plot them against dates on x axis

**Comment by iRuth** [comment]
@Adeyiwunmi do you have an example image of what you want to achieve?

**Comment by Adeyiwunmi** [comment]
the type of thing i am expeccting is attached to this mail .

I only want to plot for two different  integers on the y axis, and show an
array of dates on the x axis .

**Comment by Adeyiwunmi** [comment]
![branddddd](https://cloud.githubusercontent.com/assets/22346734/20920477/61b087d6-bba0-11e6-9151-37c10f943584.PNG)

Some thing like what i attached is what i want to do.
