### ISSUE TITLE
I can't get the Legend labels to show on a Bar Chart.

### ISSUE THREAD

**Issue by Smith454** [PhilJay/MPAndroidChart#2589]
I'm using literally the same code in the sample app. The one titled "Bar Chart" with subtitle "A simple demonstration of the bar chart" in the sample app is the one I'm talking about. I've tried all things to get the Legend to show with labels but it only shows the coloured shapes just like in the sample. Can someone please tell me what to do to get it to work? I feel like maybe I'm missing a method or something but whatever I try, it just doesn't work and I feel it's for this same reason that the Legend labels don't show in the sample app either. I'm using version 3.0.1 of the library. Please see the screenshot below, it's from the sample app as I'm using exactly the same code that is in the sample. How do I make the Legend to show with labels?

![screenshot_20161216-052429](https://cloud.githubusercontent.com/assets/24600136/21251890/45a8e1a0-c352-11e6-86be-41cc97814cee.png)

**Comment by GoneUp** [comment]
Do you mean the 'The year 2017' text? That legend entries are set over the DataSet object, in this case `set1 = new BarDataSet(yVals1, "The year 2017");`

**Comment by karthikrpandian** [comment]
I faced similar issue. I extended the Chart(BarChart in this case) to specify my own LegendRenderer. In my own LegendRenderer, I override computeLegend method, copied code from super method as is and modified line that fetches Label.
