### ISSUE TITLE
Crash when zoom

### ISSUE THREAD

**Issue by xiezhigang** [PhilJay/MPAndroidChart#2590]
hello,

the problem is with a linechart.

when i zoom the app crash with error(there's three linecharts in my layout):

thank you

`
12-16 14:16:02.009: I/View(4206): Touch up dispatch to com.github.mikephil.charting.charts.LineChart{42201ac8 V.ED.... ......ID 0,0-1496,524 #7f09004d app:id/swf_chart_pi}, event = MotionEvent { action=ACTION_UP, id[0]=0, x[0]=1194.2095, y[0]=499.0835, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=19322940, downTime=19322380, deviceId=2, source=0x1002 }

12-16 14:16:02.009: E/MotionEvent-JNI(4206): validatePointerIndex pointerIndex:-1, pointerCount:1

12-16 14:16:02.010: E/InputEventReceiver(4206): Exception dispatching input event.

12-16 14:16:02.010: D/AndroidRuntime(4206): Shutting down VM

12-16 14:16:02.010: W/dalvikvm(4206): threadid=1: thread exiting with uncaught exception (group=0x41d61c98)

12-16 14:16:02.010: W/dalvikvm(4206): threadid=1: uncaught exception occurred

12-16 14:16:02.010: W/System.err(4206): java.lang.IllegalArgumentException: pointerIndex out of range

12-16 14:16:02.013: W/System.err(4206): 	at android.view.MotionEvent.nativeGetAxisValue(Native Method)

12-16 14:16:02.014: W/System.err(4206): 	at android.view.MotionEvent.getX(MotionEvent.java:1979)

12-16 14:16:02.014: W/System.err(4206): 	at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)

12-16 14:16:02.014: W/System.err(4206): 	at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:91)
12-16 14:16:02.014: W/System.err(4206): 	at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:219)
12-16 14:16:02.014: W/System.err(4206): 	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1834)
12-16 14:16:02.014: W/System.err(4206): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1902)
12-16 14:16:02.014: W/System.err(4206): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
12-16 14:16:02.014: W/System.err(4206): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
12-16 14:16:02.014: W/System.err(4206): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
12-16 14:16:02.014: W/System.err(4206): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
12-16 14:16:02.015: W/System.err(4206): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
12-16 14:16:02.015: W/System.err(4206): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
12-16 14:16:02.015: W/System.err(4206): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
12-16 14:16:02.015: W/System.err(4206): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
12-16 14:16:02.015: W/System.err(4206): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2109)
12-16 14:16:02.015: W/System.err(4206): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1541)
12-16 14:16:02.015: W/System.err(4206): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2491)
12-16 14:16:02.015: W/System.err(4206): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2057)
12-16 14:16:02.015: W/System.err(4206): 	at android.view.View.dispatchPointerEvent(View.java:7973)
12-16 14:16:02.015: W/System.err(4206): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4392)
12-16 14:16:02.016: W/System.err(4206): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4263)
12-16 14:16:02.016: W/System.err(4206): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3809)
12-16 14:16:02.016: W/System.err(4206): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3859)
12-16 14:16:02.017: W/System.err(4206): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3828)
12-16 14:16:02.017: W/System.err(4206): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3935)
12-16 14:16:02.017: W/System.err(4206): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3836)
12-16 14:16:02.017: W/System.err(4206): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3992)
12-16 14:16:02.017: W/System.err(4206): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3809)
12-16 14:16:02.017: W/System.err(4206): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3859)
12-16 14:16:02.018: W/System.err(4206): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3828)
12-16 14:16:02.018: W/System.err(4206): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3836)
12-16 14:16:02.018: W/System.err(4206): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3809)
12-16 14:16:02.018: W/System.err(4206): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6124)
12-16 14:16:02.018: W/System.err(4206): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6104)
12-16 14:16:02.019: W/System.err(4206): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6058)
12-16 14:16:02.019: W/System.err(4206): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6254)
12-16 14:16:02.019: W/System.err(4206): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
12-16 14:16:02.019: W/System.err(4206): 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
12-16 14:16:02.019: W/System.err(4206): 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
12-16 14:16:02.019: W/System.err(4206): 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6216)
12-16 14:16:02.019: W/System.err(4206): 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6276)
12-16 14:16:02.019: W/System.err(4206): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
12-16 14:16:02.019: W/System.err(4206): 	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
12-16 14:16:02.019: W/System.err(4206): 	at android.view.Choreographer.doFrame(Choreographer.java:558)
12-16 14:16:02.019: W/System.err(4206): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
12-16 14:16:02.019: W/System.err(4206): 	at android.os.Handler.handleCallback(Handler.java:808)
12-16 14:16:02.019: W/System.err(4206): 	at android.os.Handler.dispatchMessage(Handler.java:103)
12-16 14:16:02.020: W/System.err(4206): 	at android.os.Looper.loop(Looper.java:193)
12-16 14:16:02.020: W/System.err(4206): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
12-16 14:16:02.020: W/System.err(4206): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-16 14:16:02.020: W/System.err(4206): 	at java.lang.reflect.Method.invoke(Method.java:515)
12-16 14:16:02.020: W/System.err(4206): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
12-16 14:16:02.020: W/System.err(4206): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
12-16 14:16:02.020: W/System.err(4206): 	at dalvik.system.NativeStart.main(Native Method)`

**Comment by vasiledoe** [comment]
@xiezhigang any solutions?
