### ISSUE TITLE
How to hide the top right of Label in PieChartActivity 

### ISSUE THREAD

**Issue by diaosidenixi** [PhilJay/MPAndroidChart#2595]
I want to hide the top right of Label in PieChartActivity , but I use this code useless。

mChart.setEntryLabelColor(Color.TRANSPARENT);
    mChart.setEntryLabelTypeface(mTfRegular);
    mChart.setEntryLabelTextSize(0f);
    mChart.setDrawEntryLabels(false);

**Comment by GoneUp** [comment]
Top right? Do you mean the description or the legend? To disable that try this:
`      chart.getDescription().setEnabled(false);
        chart.getLegend().setEnabled(false);`
