### ISSUE TITLE
How to add this library to my project?

### ISSUE THREAD

**Issue by sparrowjack** [PhilJay/MPAndroidChart#26]
Hey ,PhilJay. I want to develop an application with a chart functionality. So I found MPAndroidChart on github, I really like this project. But because I'm just starting out with github, so I do not know how to apply some of the features of this project to my application. I would be very appreciate if you could tell me the the way to apply it to my application！

**Comment by saadbutt67** [comment]
Hey Phil. i followed the steps exactly as mentioned above and i couldn't see any errors being ponted out.
but when i run the project i get this error in the logcat saying "Native typeface cannot be made

///////////////////////////////////////////////Main Activity//////////////////////////////////////////////////////////////////////////////

package com.example.night;

import java.util.ArrayList;

import android.app.Activity;
import android.graphics.Typeface;
import android.os.Bundle;

import com.github.mikephil.charting.charts.LineChart;
import com.github.mikephil.charting.charts.BarChart;
import com.github.mikephil.charting.data.BarData;
import com.github.mikephil.charting.data.BarDataSet;
import com.github.mikephil.charting.data.BarEntry;
import com.github.mikephil.charting.data.Entry;
import com.github.mikephil.charting.data.filter.Approximator;
import com.github.mikephil.charting.data.filter.Approximator.ApproximatorType;
import com.github.mikephil.charting.interfaces.OnChartValueSelectedListener;
import com.github.mikephil.charting.utils.Legend;
import com.github.mikephil.charting.utils.Legend.LegendPosition;
import com.github.mikephil.charting.utils.XLabels;
import com.github.mikephil.charting.utils.XLabels.XLabelPosition;
import com.github.mikephil.charting.utils.YLabels;
import com.github.mikephil.charting.utils.YLabels.YLabelPosition;



public class MainActivity extends Activity {
	
	private BarChart mChart;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);
		
		mChart = (BarChart) findViewById(R.id.chart);
		
		// enable the drawing of values
        mChart.setDrawYValues(true);
        
        mChart.setDrawValueAboveBar(true);

        mChart.setDescription("");

        // if more than 60 entries are displayed in the chart, no values will be
        // drawn
        mChart.setMaxVisibleValueCount(60);

        // disable 3D
        mChart.set3DEnabled(false);

        // scaling can now only be done on x- and y-axis separately
        mChart.setPinchZoom(false);

        // draw shadows for each bar that show the maximum value
        // mChart.setDrawBarShadow(true);

        mChart.setUnit(" â‚¬");
        
        // mChart.setDrawXLabels(false);

        mChart.setDrawGridBackground(false);
        mChart.setDrawHorizontalGrid(true);
        mChart.setDrawVerticalGrid(false);
        // mChart.setDrawYLabels(false);

        // sets the text size of the values inside the chart
        mChart.setValueTextSize(10f);

        mChart.setDrawBorder(false);
        // mChart.setBorderPositions(new BorderPosition[] {BorderPosition.LEFT,
        // BorderPosition.RIGHT});

        Typeface tf = Typeface.createFromAsset(getAssets(), "OpenSans-Regular.ttf");

        XLabels xl = mChart.getXLabels();
        xl.setPosition(XLabelPosition.BOTTOM);
        xl.setCenterXLabelText(true);
        xl.setTypeface(tf);

        YLabels yl = mChart.getYLabels();
        yl.setTypeface(tf);
        yl.setLabelCount(8);
        yl.setPosition(YLabelPosition.BOTH_SIDED);

        mChart.setValueTypeface(tf);

        
        setData(12, 50);
        
        Legend l = mChart.getLegend();
        l.setPosition(LegendPosition.BELOW_CHART_LEFT);
        l.setFormSize(8f);
        l.setXEntrySpace(4f);

        
	}

	
	private void setData(int count, float range) {

        ArrayList<String> xVals = new ArrayList<String>();
        for (int i = 0; i < count; i++) {
            
        }

        ArrayList<BarEntry> yVals1 = new ArrayList<BarEntry>();

        for (int i = 0; i < count; i++) {
            float mult = (range + 1);
            float val = (float) (Math.random() * mult);
            yVals1.add(new BarEntry(val, i));
        }

        BarDataSet set1 = new BarDataSet(yVals1, "DataSet");
        set1.setBarSpacePercent(35f);

        ArrayList<BarDataSet> dataSets = new ArrayList<BarDataSet>();
        dataSets.add(set1);

        BarData data = new BarData(xVals, dataSets);

        mChart.setData(data);
    }

	
}


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
![logcat of project not working](https://cloud.githubusercontent.com/assets/11037943/6222304/0d8337d2-b673-11e4-9080-b0a2126d5a5b.PNG)
![xml of project not working](https://cloud.githubusercontent.com/assets/11037943/6222305/0d88dcfa-b673-11e4-934e-d4159c646260.PNG)

"

**Comment by saadbutt67** [comment]
one more problem whenever i try to clean the project it shows this
![clean](https://cloud.githubusercontent.com/assets/11037943/6222333/91e73eba-b673-11e4-9e49-5412cc863b5e.PNG)

**Comment by saadbutt67** [comment]
awesome library Buddy!! finally was able to make it work :D

**Comment by yogitabang** [comment]
I used the library to draw piechart ... but it is showing "rt data av" on screen and pie chart is not being drawn...what could be the issue... I used a video tutorial for reference

**Comment by sharockguan** [comment]
Hello,PhilJay!I just met some difficulties same as  what Uncle-Leo have met.I don't  really understand  the answear --'different versions of the support library'.Could you help me?(Sorry,I'm a newbie 囧)Thanks！

**Comment by sanchana123** [comment]
i have got an error like mpchartlib.jar missing in bin when i added the mpchartlib folder to my project in eclipse and i am also geeting error in the library files as the package io.realm missing
please help......

**Comment by thriveni** [comment]
will this library works in offline mode?

**Comment by capuzzi** [comment]
I used the library in Xamarin Android and it shows "rt data av"..

any idea?

**Comment by peacex1** [comment]
After importing the library folder , the "main" project shows up in project explorer, but while adding the library to my project, after clicking add button the project selection window pops up empty, I
am unable to choose the imported project, please help. 
![capture](https://cloud.githubusercontent.com/assets/27757435/25164065/3b11bdf6-24ec-11e7-9f28-ae46d0fa2fe5.JPG)
![capture1](https://cloud.githubusercontent.com/assets/27757435/25164066/3b181b6a-24ec-11e7-8282-e922f3b0bf71.JPG)
