### ISSUE TITLE
Barchart add tooltip

### ISSUE THREAD

**Issue by sanjay-kakadiya** [PhilJay/MPAndroidChart#2627]
I wanted to show star and value tooltip in Bar graph of CombinedChart MPAndroidChart like in below image.
![0yule](https://cloud.githubusercontent.com/assets/5549171/21494142/79cc6ef2-cc35-11e6-8f36-e12aa0ebf1bb.png)

If bar value is >= to goal value then add star in bar.
And if user click on particluar bar then show tooltip as per image.
Can any one help me for customize same.

**Comment by JStav** [comment]
For the tooltip, use a [Marker](https://github.com/PhilJay/MPAndroidChart/wiki/IMarker-Interface).

For the star, probably some sort of custom [Renderer](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartLib/src/main/java/com/github/mikephil/charting/renderer) though there may be an easier way.

**Comment by sanjay-kakadiya** [comment]
@JStav Thanks for your response. For star i used custom Renderer and it working fine.

**Comment by JStav** [comment]
Great! Glad I could help
