### ISSUE TITLE
Any way do disable the ascending ordering on X Axis?

### ISSUE THREAD

**Issue by AlNistor** [PhilJay/MPAndroidChart#2628]
Hei people,

I have on the x Axis values from 0 to 34. But I want to sort the data to display data ordered by values. So if I have the following arrays:
let xAxisIDs = [0,1,2,3,4,5,6,7,8,9]
let xAxisValues = [1, 3, 30, 15, 20, 99, 56, 22, 18, 43]

I have these arrays in a dictionary so the sorting part is not the problem.
The problem is that even if I sort the array in the correct order that I want, when I give the data to the BarChartView it automatically puts the data sorted back by the xAxisIDs ascending from 0 to 34.
Any thoughts on this?

Cheers!

**Comment by patrick-iv** [comment]
You need to re-map the values to reflect the sorted order, I would probably do something like this:

    final int[] ids = new int[]{0, 1, 2};
    final int[] values = new int[]{10, 30, 20};

    // do fancy sorting...

    final int[] sortedIds = new int[]{0, 2, 1};
    final int[] sortedValues = new int[]{10, 20, 30};

    final String[] labels = new String[sortedIds.length];
    final List<BarEntry> entries = new ArrayList<>();
    for (int i = 0; i < sortedValues.length; i++) {
        entries.add(new BarEntry(i, sortedValues[i]));
        labels[i] = String.valueOf(sortedIds[i]);
    }

and then use `labels` inside a `ValueFormatter` to show the correct values. By using `i` as the x value you will reflect the new order.

**Comment by AlNistor** [comment]
Thanks a lot! That logic worked like a charm. I've been trying to use the Value formatter as a bridge, but I was getting it wrong. 👍 

Now everything is right. Thanks again

**Comment by AndroPlus** [comment]
Good  job.. i able to do like this.. thanks ...
