### ISSUE TITLE
X-Axis values are not properly displayed

### ISSUE THREAD

**Issue by meet2011** [PhilJay/MPAndroidChart#2637]
I tried to display x-axis values from 0 to 23 using ValueFormatter but its not working
`

        List<Entry> offDutyEntry = new ArrayList<>();
        offDutyEntry.add(new Entry(1, 1));
        offDutyEntry.add(new Entry(3, 1));
        offDutyEntry.add(new Entry(3, 4));
        offDutyEntry.add(new Entry(6, 4));
        offDutyEntry.add(new Entry(6, 2));

        LineDataSet dailyHourSet = new LineDataSet(offDutyEntry, "Daily Hours of Service");
        dailyHourSet.setColor(Color.BLUE);
        dailyHourSet.setLineWidth(2.0f);
        dailyHourSet.setDrawValues(false);
        dailyHourSet.setDrawCircles(true);
        dailyHourSet.setCircleColor(Color.BLUE);

        List<String> xAxisValues = new ArrayList<>();

        for (int i = 0; i < 24; i++)
            xAxisValues.add(String.valueOf(i));

        List<String> yAxisValues = new ArrayList<>();

        for (int i = 0; i < 7; i++) {

            if (i > 0 && i < 5)
                yAxisValues.add(modeList[i-1]);
            else
                yAxisValues.add(String.valueOf(""));

        }

        LineData lineData = new LineData(dailyHourSet);
        lineChart.setData(lineData);
        lineChart.setPinchZoom(false);
        lineChart.setDoubleTapToZoomEnabled(false);
        lineChart.animateXY(1000, 1000);
        lineChart.setDrawBorders(true);
        lineChart.setBorderWidth(1f);
        lineChart.setScaleMinima(1f,1f);
        lineChart.setVisibleXRangeMaximum(24f);

        Description desc = new Description();
        desc.setText("Daily eLog");

        lineChart.setDescription(desc);

        // Disable Right X-Axis
        lineChart.getAxisRight().setEnabled(false);

        // Disable Legend
        lineChart.getLegend().setEnabled(true);

        XAxis xAxis = lineChart.getXAxis();
        xAxis.setAxisMinimum(0);
        xAxis.setAxisMaximum(23);
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setValueFormatter(new MyAxisValueFormatter(xAxisValues));
        xAxis.setTextSize(10f);
        xAxis.setGranularity(1f);

        xAxis.setGranularityEnabled(true);

        xAxis.setTextColor(Color.BLACK);
        xAxis.setDrawAxisLine(true);
        xAxis.setDrawGridLines(true);

        YAxis yAxis = lineChart.getAxisLeft();
        yAxis.setTextColor(Color.BLACK);
        yAxis.setTextSize(10f);
        yAxis.setValueFormatter(new MyAxisValueFormatter(yAxisValues));
        yAxis.setDrawAxisLine(true);
        yAxis.setDrawGridLines(true);
        yAxis.setGranularity(1f);
        yAxis.setGranularityEnabled(true);

        lineChart.invalidate();

    public class MyAxisValueFormatter implements IAxisValueFormatter {

        private List<String> mValues;

        public MyAxisValueFormatter(List<String> values) {
            this.mValues = values;
        }

        @Override
        public String getFormattedValue(float value, AxisBase axis) {
            // "value" represents the position of the label on the axis (x or y)
            return mValues.get((int) value);
        }

    }
`

 I must say this library is awesome. I tried other library but this stands out from the list. Thank you for the great library

**Comment by meet2011** [comment]
I've yAxis value length of 6 but it only displays 5 axis values.

**Comment by klingon2413** [comment]
I’m also facing similar problem. I want to format x and Y axis. For example, I want to format the X and Y axes so that they go from input minimum to input maximum values with a grid increment by an input value. As an example in the Y axis, I cannot get the chart to display from 0 to 5 with grid increments of 1.
