### ISSUE TITLE
Hide/ Remove/ Theme Thread Cross in Combined Chart (Bar + Line)

### ISSUE THREAD

**Issue by MaximilianKeppeler** [PhilJay/MPAndroidChart#2648]
Hey, I just switched from a Bar Chart to a Combined Chart including a Bar and Line chart. I want to remove or hide the thread cross selector, which appears when you click on a point on the chart. (It displays x, y axis to the the current point. It's red and orange)

If that's not possible, I at least want to theme it differently. I haven't found something useful in the wiki page

**Comment by MaximilianKeppeler** [comment]
Oh, found it. I wish the wiki would be better.

**Comment by dpeters1** [comment]
I wish people would post the solution before closing the issue. -_-
