### ISSUE TITLE
How to find current zoom center ?

### ISSUE THREAD

**Issue by igorvlassov** [PhilJay/MPAndroidChart#2652]
Hi,
I want to zoom and move one chart according to zooming of another chart (made by gesture). How can I find zoom center?

Thanks in advance,
Igor

**Comment by drawers** [comment]
Within the library, you can call `getTransformer(AxisDependency which)` and translate between points on the screen and xIndices and yValues on your chart.

**Comment by igorvlassov** [comment]
Dear @drawers Thanks a lot you point me to transformer. I'll try to use it for custom drawings on the chart. I managed with zoom center getting fingers' coords in onChartScale method of gesture listener, thanks.
