### ISSUE TITLE
Draw custom shape on the chart

### ISSUE THREAD

**Issue by igorvlassov** [PhilJay/MPAndroidChart#2653]
Hi,
Is it possible to draw custom shape on the chart? I'd like to draw circle around finger when long press.

Thanks in advance,
Igor

**Comment by patrick-iv** [comment]
I think you would have to extend the whatever chart class you're using and override onTouch to get the position and onDraw to draw the circle. Just remember to call `super.onDraw(canvas);` in onDraw before doing custom drawing.

**Comment by igorvlassov** [comment]
@patrick-iv Thanks a lot! I'll try
