### ISSUE TITLE
How to draw marks/annotations on the chart?

### ISSUE THREAD

**Issue by igorvlassov** [PhilJay/MPAndroidChart#2654]
Hi,
Could you point me the best way to draw some marks on significant points/events on the chart? Like on following image: 
![image](https://cloud.githubusercontent.com/assets/1935274/21592414/05f627f8-d116-11e6-849b-7c600d12050e.png)

**Comment by GoneUp** [comment]
Limitlines could help you at this task. https://github.com/PhilJay/MPAndroidChart/wiki/The-Axis

**Comment by igorvlassov** [comment]
@GoneUp Thanks a lot! I'll check this.

**Comment by igorvlassov** [comment]
@GoneUp LimitLines are useful staff but not for that task. I need marks exactly like on image. There are could be more local extremums on curve I need to mark

**Comment by GoneUp** [comment]
I think there is nothing like that implemted in the libary. They are Markers that are pretty close to that what you want (mark a specific point with a custom view), but they are limited to the values the user highlightes.
You could extend the implementation of the markers, but that would be a bigger task,

**Comment by drawers** [comment]
There are a few examples of custom highlights, custom limit lines, and custom images inside bars on StackOveflow. As a professional programmer, or a aspiring one, rather than merely stating your requirements ("I need this") you should be able to attempt a solution yourself using the extensibility provided by the library .

**Comment by igorvlassov** [comment]
@GoneUp Thanks a lot. To the moment I simply added 2 separated scatter plots for red and green marks as a background for points of interest. However I should say annotations/events are very common charts feature and should be provided out of the box. There is example:
https://www.amcharts.com/demos/stock-events/
