### ISSUE TITLE
RealtimeLineChart Error..

### ISSUE THREAD

**Issue by JungYongWook** [PhilJay/MPAndroidChart#2659]
I'm using an Android studio, and I get some errors, but I do not know what to do.
Follow RealtimeLineChartActivity,

MChart.setVisibleXRange (6); 6 error,

 @Override
    public boolean onCreateOptionMenu (Menu menu) {
        getMenuInflater().inflate(R.menu.main, menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {

        int id = item.getItemId();
        if (id == R.id.action_settings) {
            return true;
        }
        return super.onOptionsItemSelected(item);
    }

getMenuInflater().inflate(R.menu.main, menu); ==> menu error,
R.id.action_settings ==> action_settings error

But I have not added them anywhere.

in build.gradle file,

Compile 'com.github.PhilJay: MPAndroidChart: v2.2.5', repositories {
    Maven {url "https://jitpack.io"}
} 
And did nothing else.

What should I do to complete the RealtimeLineChartActivity without errors?
What do I need to add to my activity_main.xml file?

Please help..

**Comment by GoneUp** [comment]
You are using the method wrong. It takes a min and a max parameter.
`public void setVisibleXRange(float minXRange, float maxXRange)`
You should also update to 3.0.1.
