### ISSUE TITLE
how should i make X limit Line..

### ISSUE THREAD

**Issue by asker517** [PhilJay/MPAndroidChart#266]
how should i make X limit line in the line chart ? for help thanks...

**Comment by SvartaHajen** [comment]
Hi,
I know this thread is closed but I would like to make sure that, by now, this feature remains unimplemented.
The documentation makes me believe this is not the case:
"limit - - the position (the value) on the y-axis (y-value) or x-axis (xIndex) where this line should appear"
Still, I am having trouble creating those limit lines, they are created but not on the correct x position therefore I wonder if the feature is fully working now.
Thanks in advance!
Enric

**Comment by johnnyzen** [comment]
Please if there is an update to vertical limit lines on the x-axis?
