### ISSUE TITLE
2 charts linking/zoom sync

### ISSUE THREAD

**Issue by igorvlassov** [PhilJay/MPAndroidChart#2660]
Is there some method to synchronize gesture zoom of 2 charts with same x length?  Say user zooms first chart and the second is zoomed on the same manner?

**Comment by drawers** [comment]
Hi Igor,
Please see my answer to your question on StackOverflow:

http://stackoverflow.com/a/41460255/5241933

**Comment by igorvlassov** [comment]
Dear @drawers 
Yes, I thought about  gesture listener. Something like
`           public void onChartScale(MotionEvent me, float scaleX, float scaleY){
                oscChart.zoom(scaleX,scaleY, x, y);
            }
`
The cuestión is how to find x, y which are coordinates of the center of translation. Will see.

**Comment by igorvlassov** [comment]
I managed with zoom center getting fingers' coords in onChartScale method of gesture listener.
`            @Override
            public void onChartScale(MotionEvent me, float scaleX, float scaleY) {
                float xPos = (me.getX(0)+me.getX(1))/2f, yPos = (me.getY(0)+me.getY(1))/2f;
                chart2.fitScreen();
                chart2.zoom(scaleX,scaleY, xPos, yPos);
            }
`
