### ISSUE TITLE
CombinedChart  with group value

### ISSUE THREAD

**Issue by xiaolongonly** [PhilJay/MPAndroidChart#2666]
How can I move the axis value in the center of their data area ？

**Comment by xiaolongonly** [comment]
![qq 20170105173921](https://cloud.githubusercontent.com/assets/12853050/21676007/00c4c414-d36f-11e6-9038-be4ca513e5a0.png) 
now it is in left of their data area , and I want move it to the linechart data X axis position, have anyone
met this problem?

**Comment by cypis** [comment]
.setCenterAxisLabels(true)

**Comment by xiaolongonly** [comment]
@cypis ok! thank you!
