### ISSUE TITLE
How to set Color??

### ISSUE THREAD

**Issue by JungYongWook** [PhilJay/MPAndroidChart#2669]
Look this my code.

chart = (BarChart) findViewById(R.id.chart1);

        BARENTRY = new ArrayList<>();
        BarEntryLabels = new ArrayList<String>();

        AddValuesToBARENTRY();
        AddValuesToBarEntryLabels();

        Bardataset = new BarDataSet(BARENTRY, "");
        BARDATA = new BarData(BarEntryLabels, Bardataset);
        Bardataset.setColors(ColorTemplate.PASTEL_COLORS);

        chart.setData(BARDATA);

.....

 public void AddValuesToBARENTRY(){

        BARENTRY.add(new BarEntry(62f, 0));
        BARENTRY.add(new BarEntry(23f, 1));
        BARENTRY.add(new BarEntry(99f, 2));
    }

    public void AddValuesToBarEntryLabels(){

        BarEntryLabels.add("ex1");
        BarEntryLabels.add("ex2");
        BarEntryLabels.add("ex3");
    }

For example, 
I would represent 20 data bars, and half would be red, and half would be green.

What should I do?

**Comment by Sunsiha** [comment]
Bardataset.setColors(new int[]{Color.parseColor("#701112")}); 
You can set like this.Then there will be only one color.Accroding to your color you can change it.

**Comment by rwsiam** [comment]
or Bardataset.setColors(Color.parseColor("#701112"));
