### ISSUE TITLE
How make Linechart xAxis value always increase by 1?

### ISSUE THREAD

**Issue by minhnguyen31093** [PhilJay/MPAndroidChart#2671]
For example I have max value of xAxis is 15 and I display 5 labels on xAxis: 11 12 13 14 15
And after change max value from 15 to 300 I want it display: 296 297 298 299 300
but it display 180 210 240 270 300

I have research and try this but it not work
xAxis.setGranularity(1f);
xAxis.setLabelCount(5);
mChart.setVisibleXRange(5, 5);

I think it can be done if change zoom but I have no ideal to calculate the right scale value to make it zoom in and show xAxis increase 1 value with 5 labels.

Is there any way to make it always increase only 1 value?

**Comment by thangins** [comment]
xAxis.setGranularity(1f);
xAxis.setLabelCount(6);
mChart.setVisibleXRangeMaximum(5)

**Comment by minhnguyen31093** [comment]
Thank you for reply, I have tried but it not work. When change value but keep zoom if the value is small it only display 1 to 2 label and if large it can be display 8 label also not increase by 1 value but 10 or 100.

**Comment by 603530013** [comment]
```java
xAxis.setAxisMinimum(chart.getXChartMax()-4);
xAxis.setLabelCount(5);
```

**Comment by minhnguyen31093** [comment]
After set new data I reset the view so the problem solved :)
lineChart.setData(monData);
lineChart.invalidate();
xAxis.setGranularity(1);
xAxis.setLabelCount(5);
lineChart.setVisibleXRange(1, 24);
lineChart.centerViewTo(lineChart.getXRange(), lineChart.getYChartMax(), YAxis.AxisDependency.RIGHT);
