### ISSUE TITLE
A problem occur in the HorizontalBarChart

### ISSUE THREAD

**Issue by xiaolongonly** [PhilJay/MPAndroidChart#2675]
how to put this text（place name） into the HorizontalBarChart's inside，The version of 1.0 can do it ,but when I update the version to 3.0.1,it's sad to see that the text was showed in the left of the HorizontalBarChart。Please do me a favor。

version 3.0.1
![qq 20170106142646](https://cloud.githubusercontent.com/assets/12853050/21709562/d3524872-d41c-11e6-894b-c710517491e0.png)

version 1.0
![qq 20170106142641](https://cloud.githubusercontent.com/assets/12853050/21709486/3a599986-d41c-11e6-8f33-1b0ac7525ece.png)

here is my chart config code on 3.0.1 version

        mHorizontalBarChart.getDescription().setEnabled(false);

        mHorizontalBarChart.setNoDataText("无数据");

        mHorizontalBarChart.setGridBackgroundColor(mContext.getResources().getColor(R.color.white));

        XAxis xAxis = mHorizontalBarChart.getXAxis();

        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM_INSIDE); 

        xAxis.setDrawGridLines(false);

        xAxis.setLabelCount(20);

        xAxis.setValueFormatter(mIAxisValueFormatter);

        xAxis.setGranularity(1f);

        YAxis yAxisRight = mHorizontalBarChart.getAxisRight();

        yAxisRight.setAxisMinimum(0);

        mHorizontalBarChart.getAxisLeft().setEnabled(false);

        mHorizontalBarChart.setData((BarData) mChartData);

        mHorizontalBarChart.getLegend().setEnabled(false);

        mHorizontalBarChart.animateY(1400, Easing.EasingOption.EaseInOutQuad);//动画

**Comment by xiaolongonly** [comment]
I solved this problem~ Thanks !

**Comment by FredericoNoce** [comment]
How ?
