### ISSUE TITLE
There is a bug in horizontalbarChart

### ISSUE THREAD

**Issue by xiaolongonly** [PhilJay/MPAndroidChart#2695]
I change the XAixs position to BOTTOM_INSIDE  then  it show that 

![qq 20170110110520](https://cloud.githubusercontent.com/assets/12853050/21792436/bf61b73e-d724-11e6-9e89-3f73d4d2aa42.png)
![qq 20170110110525](https://cloud.githubusercontent.com/assets/12853050/21792437/c06d5a34-d724-11e6-9824-a2966bef2ada.png)

The xAxis label dosen't show inside..

How can I fix it???

**Comment by xiaolongonly** [comment]
The xAxis label  dosen't show inside..

**Comment by xiaolongonly** [comment]
I changed some code and solved this problem..

thanks for your great library!

**Comment by fanyuzhing** [comment]
Can you show me your code ?

I have the same problem, thank you .

**Comment by vitorhansen** [comment]
Hey, i had the same problem, can anyone share the fix?
tks

**Comment by vitorhansen** [comment]
@xiaolongonly can you share the solution?
