### ISSUE TITLE
Legend doesn't display correctly on stacked bar charts for small sample size

### ISSUE THREAD

**Issue by sixteh** [PhilJay/MPAndroidChart#271]
In a stacked bar chart, if there are more groups than there are entries, the legend gets seriously messed up and displays everything incorrectly. This can be verified on the sample app by dragging the slider all the way to the left so that there's only 1 sample and seeing that only 1 group appears on the legend.

**Comment by PhilJay** [comment]
This is now fixed and will be released in the next update.
