### ISSUE TITLE
How to set chart position?

### ISSUE THREAD

**Issue by hram** [PhilJay/MPAndroidChart#2724]
How can I add for example 100 items in chart but display only last 10.
I new about visible range.
In my case visible range might be between 10 and 100
I need scroll chart and zoom it.

If I load 100 items then all of them displayed on chart.
Can you help me?

**Comment by JStav** [comment]
chart.moveViewToX(chart.getXChartMax())?

**Comment by hram** [comment]
this is not right for me
setVisibleXRange() method call setMinMaxScaleX()
and after this I cant zoom/pinch chart

I need make it scrollable and zoomable

**Comment by hysheng** [comment]
Hi,I have the same problem,were you able to solve this issue?

**Comment by almic** [comment]
@hysheng this is absolutely possible, please look at the existing documentation and examples. I'm working on some new documentation as well, hopefully that will be available soon. But for now, you should be able to figure it out by checking the examples.
