### ISSUE TITLE
Can't disable pinch to zoom for BarChart

### ISSUE THREAD

**Issue by andreyfel** [PhilJay/MPAndroidChart#2733]
I have a BarChart and I'm trying to disable scaling.
Seems that these methods doesn't work:
setScaleEnabled(false);
setPinchZoom(false);
setDoubleTapToZoomEnabled(false);
I still can double tap or pinch to zoom. If I set setTouchEnabled(false), it works but in this case I'm losing drag to highlight functionality.

Probably a regression?

**Comment by andreyfel** [comment]
I used v3.0.1 of MPAndroidChart

**Comment by andreyfel** [comment]
It appears that the issue is caused by the fact that I called setScaleEnabled inside overridden init() method, which is called before the mScaleXEnabled field is initialized. I moved this logic to onFinishInflate and now it works.

**Comment by scsfwgy** [comment]
Hey，I have the same issues "It appears that the issue is caused by the fact that I called setScaleEnabled inside overridden init() method",but I can't find where "the mScaleXEnabled field is initialized"?
