### ISSUE TITLE
First and Last values are being cut in BUBBLE CHART ! HELP !

### ISSUE THREAD

**Issue by sans07** [PhilJay/MPAndroidChart#2747]
**I tried setting XAxisMin and XAxisMax values aswell but still doesn't work 
![screenshot_1485167937](https://cloud.githubusercontent.com/assets/23051788/22200865/1112031a-e187-11e6-90a7-7560b1ac2281.png)
**
`mChart = (BubbleChart) view.findViewById(R.id.chart);

        mChart.getDescription().setEnabled(false);

        mChart.setMaxVisibleValueCount(10);
        mChart.setPinchZoom(false);
        mChart.setDrawGridBackground(false);

        XAxis xAxis = mChart.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setDrawGridLines(false);
        xAxis.setDrawLabels(false);
        xAxis.setTextSize(12.0f);
        xAxis.setTextColor(Color.BLACK);

        YAxis yAxis = mChart.getAxisLeft();
        yAxis.setDrawGridLines(false);
        yAxis.setDrawLabels(false);
        yAxis.setSpaceMax(10);

        mChart.getAxisLeft().setDrawAxisLine(false);
        mChart.getAxisRight().setDrawAxisLine(false);
        mChart.getAxisLeft().setDrawGridLines(false);
        mChart.getAxisRight().setDrawGridLines(false);
        mChart.getAxisRight().setDrawLabels(false);
        mChart.getXAxis().setDrawGridLines(false);
        mChart.getXAxis().setDrawAxisLine(false);
        mChart.animateY(2500);

        mChart.getLegend().setEnabled(false);

        List<BubbleEntry> yVals = new ArrayList<BubbleEntry>();
        yVals.add(new BubbleEntry(1,120f,5f));
        yVals.add(new BubbleEntry(2, 170f,3f));
        yVals.add(new BubbleEntry(3, 150f,2f));
        yVals.add(new BubbleEntry(4, 180f,4f));

        BubbleDataSet set1;

        set1 = new BubbleDataSet(yVals, "DataSet 1");
        set1.setColor(Color.parseColor("#F06393"));

        set1.setValueTextColor(Color.parseColor("#FFFFFF"));
        set1.setValueTextSize(14f);

        ArrayList<IBubbleDataSet> dataSets = new ArrayList<IBubbleDataSet>();
        dataSets.add(set1);

        BubbleData data = new BubbleData(dataSets);
        data.setValueFormatter(new AccValueFormatter());
        data.setHighlightCircleWidth(1.5f);

        mChart.setTouchEnabled(false);
        mChart.setData(data);`

**Comment by bkraszewski** [comment]
Hi @sans07 have you found solution?
