### ISSUE TITLE
Support of Bubble Chart

### ISSUE THREAD

**Issue by mobeela** [PhilJay/MPAndroidChart#276]
Please add new type of chart - Bubble Chart.

http://en.wikipedia.org/wiki/Bubble_chart

**Comment by danielgindi** [comment]
@PhilJay we can close this now :-)

**Comment by alex-dokienko** [comment]
hello guys, thank you for awesome library.
Wanted to check if current bubble chart implementation supports the following chart ?
![image](https://user-images.githubusercontent.com/7915796/95346922-03302b00-08c5-11eb-9f3d-3592ca30e437.png)

Basically without xAxis, don't know actually how such type properly called, but I hope you got the idea based on screenshot.
