### ISSUE TITLE
how to set xaxis String data for BarChart

### ISSUE THREAD

**Issue by vj12354** [PhilJay/MPAndroidChart#2767]
Hi @PhilJay 

Looks like you have removed BarData.setXVals(List<String> xAxisValues) method, which was available in version 2.2.5

How can I pass this values now in version 3.0.1 ?

Thanks,
vj

**Comment by vj12354** [comment]
@tobyerbailey @Malikkhoja 
Do you have any idea this? thanks.

**Comment by tobyerbailey** [comment]
I followed and modified the code from the example application:

In the initialise function for the chart:
`IAxisValueFormatter xAxisFormatter = new DayAxisValueFormatter(mChart);`

In a separate class:
```
**
 * Created by philipp on 02/06/16.
 */
public class DayAxisValueFormatter implements IAxisValueFormatter
{

    protected String[] mMonths = new String[]{
            "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dec"
    };

    private BarLineChartBase<?> chart;

    public DayAxisValueFormatter(BarLineChartBase<?> chart) {
        this.chart = chart;
    }

    @Override
    public String getFormattedValue(float value, AxisBase axis) {
    
          //Insert code here to return value from your custom array or based on some processing

  }

```

**Comment by vj12354** [comment]
Thanks @tobyerbailey for the quick reply. Agreed that IAxisValueFormatter can be used for formatting values, given xaxis values are of time float.

But what is the values are of type String or Long. In my case my data looks like this:

`
public class ReportChartData {
    public List<Integer> colors;    
    public List<String> xAxis ;   //Category Names
    public List<BarEntry> yAxis ;  //Category Totals
}

`

And I was passing it to the barChart as below:


`
private void drawBarChart(ReportChartData data) {
        BarDataSet set1 = new BarDataSet(data.yAxis, "");
        set1.setColors(data.colors);
        set1.setDrawValues(true);
       //set1.setValueFormatter(new ReportChartValueFormatter());

        BarData _data = new BarData();
        _data.setXVals(data.xAxis);
        _data.addDataSet(set1);
        // data.setValueFormatter(new MyValueFormatter());
        _data.setValueTextSize(10f);

        // barChart.getXAxis().setValueFormatter(new MyXAxisValueFormator());

        barChart.setData(_data);
    }`

Sorry about not getting it into my head. I'm not able to figure out how do I pass the xAxis values, at all?

Thanks,
Vijay

**Comment by tobyerbailey** [comment]
I initially set my data as follows:

`ArrayList<BarEntry> yVals1 = new ArrayList<>();

        for (int i = (int) start; i < dataArray.size(); i++) {
            yVals1.add(new BarEntry(i, dataArray.get(i).floatValue()));
        }`

So the x values in each BarEntry are basically set as integer values mirroring array indexes. Those are then used in the axis formatter to pull a value from a string/long/anything else array.

So I am not explicitly storing my x-axis data as strings, I am using integer values to pull a string from an array in the formatter.

Hope that makes sense and might work for you. Probably best if Phil answers any further questions. I'm pretty new to this myself.

**Comment by vj12354** [comment]
Thanks @tobyerbailey I finally figured the same thing.

Also I did:
`
        xAxis.setValueFormatter(new ReportChartXAxisValueFormatter(plotChart.xAxis));
        xAxis.setGranularity(1.0f);
`

And my value formatter looks like this:

`
public class ReportChartXAxisValueFormatter implements IAxisValueFormatter { 
    private List<String> labels;

    public ReportChartXAxisValueFormatter(List<String> labels) {
        this.labels = labels;
    }

    @Override
    public String getFormattedValue(float value, AxisBase axis) {
        try {
            int index = (int) value;
            return labels.get(index);
        } catch (Exception e) {
            return "";
        }
    }
}`

Appreciate you help. [somehow this github Insert code formatter is aweful...]

Cheers.
