### ISSUE TITLE
there is no jar file in downloads.

### ISSUE THREAD

**Issue by leguang** [PhilJay/MPAndroidChart#2778]
Latest release
 v3.0.1
 08f295e
Stability Improvements
@PhilJay PhilJay released this on 18 Nov 2016 · 7 commits to master since this release

This release improves stability and fixes bugs.
Downloads
Source code (zip)
Source code (tar.gz)

Can update on the jar file?Thank you.^_^

**Comment by GoneUp** [comment]
https://jitpack.io/com/github/PhilJay/MPAndroidChart/v3.0.1/MPAndroidChart-v3.0.1.jar

**Comment by MGaetan89** [comment]
@leguang can you close this issue as @GoneUp provided you the answer?

**Comment by allsetformove** [comment]
thanks a ton!
