### ISSUE TITLE
Legend is in single line and overflow Canvas when set after setData

### ISSUE THREAD

**Issue by mtrakal** [PhilJay/MPAndroidChart#2784]
Using PieChart and latest version: 3.0.1.

When you set legend AFTER call `setData(...)` on PieChart, legend is everytime single-line and text overflow view (screen)!

Have a lot of items (10) with long names (5-10 characters).

```
 private void showLegend(PieChart chart) {
        Legend l = chart.getLegend();
        l.setDrawInside(false);
        l.setOrientation(Legend.LegendOrientation.HORIZONTAL);
        l.setHorizontalAlignment(Legend.LegendHorizontalAlignment.CENTER);
        l.setVerticalAlignment(Legend.LegendVerticalAlignment.BOTTOM);
        l.setWordWrapEnabled(true);
        l.setXEntrySpace(8f);
        l.setYEntrySpace(3f);
        l.setYOffset(3f);
    }

  private void show() {
        showLegend(chart); // !!! MUST BE BEFORE SET DATA !!!
        chart.setData(pieData);
        chart.invalidate(); // refresh
  }
```

when you use
```
  private void show() {
        chart.setData(pieData);
        showLegend(chart); // !!! MUST BE BEFORE SET DATA !!!
        chart.invalidate(); // refresh
  }
```
result is one line, without wrap to more lines.

I spent two hours for resolve this issue 👎

**Comment by Neil1484** [comment]
there any solution for this.

**Comment by almic** [comment]
@Neil1484 this issue is fairly old, could you please open a new issue and describe the problem in detail and maybe I can help you?

**Comment by mtrakal** [comment]
old, but still valid I think :).

But the solution is shown in my example, you must set BEFORE setting data...

```
        showLegend(chart); // !!! MUST BE BEFORE SET DATA !!!
chart.setData(pieData);
        chart.invalidate(); // refresh
```

**Comment by SachinTanpure** [comment]
I was also stuck in this issue. Thanks for solution. set legend BEFORE setting data really works.
