### ISSUE TITLE
Legend Click and Multiple Line data set value in One MarkerView

### ISSUE THREAD

**Issue by kushanshah11** [PhilJay/MPAndroidChart#2790]
Hi @PhilJay ,

1 ) it is possible to get Legend click ?
 -On particular legend Click I have enable or disable draw of live chart.

![device-2017-02-09-185027](https://cloud.githubusercontent.com/assets/18567763/22785173/3a87b29c-eef9-11e6-8079-f34a6b45ac8f.png)

2) I have multiple Line chart on click of any value selected of chart how can i get all value of that vertical point in one marker View?

I have currently getting only value of that particular point.

![device-2017-02-09-185101](https://cloud.githubusercontent.com/assets/18567763/22785267/9ffc50e2-eef9-11e6-8639-1d42ab650157.png)

I need something like this on selecting particular value,

![chart](https://cloud.githubusercontent.com/assets/18567763/22785362/fd4fb9be-eef9-11e6-8e24-a2c0d2b0e860.png)

Thanks in Advance!!!!!!

**Comment by Liveinadream** [comment]
you can write a textview On the chart,and set data on it 

`
<RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="220dp">
                <com.github.mikephil.charting.charts.LineChart
                    android:id="@+id/chart1"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:clipChildren="false"
                    android:visibility="gone">
                </com.github.mikephil.charting.charts.LineChart>

                <TextView
                    android:id="@+id/center_tv_Content"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerInParent="true"
                    android:background="@drawable/bg_marker"
                    android:padding="4dp"
                    android:textAppearance="?android:attr/textAppearanceSmall"
                    android:textColor="@android:color/white"
                    android:textSize="@dimen/textSize_14"
                    android:visibility="gone" />

                <ImageView
                    android:id="@+id/b_graph_no_data"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerInParent="true"
                    android:src="@drawable/x_common_nodata_bg"
                    android:visibility="gone"
                    android:contentDescription="@string/no_data" />
            </RelativeLayout>
`

use   this code Control its display
  `mChart.setOnChartValueSelectedListener(new OnChartValueSelectedListener() {
            @Override
            public void onValueSelected(Entry e, Highlight h) {
                graphHolder.markview.setText(null);
//TODO
               graphHolder.markview.setVisibility(View.VISABLE);
            }

            @Override
            public void onNothingSelected() {
                graphHolder.markview.setText(null);
                graphHolder.markview.setVisibility(View.GONE);
            }
        });`

**Comment by kushanshah11** [comment]
Hi @Liveinadream ,

thanks for quick response.......

i did't get you @Liveinadream are you taking about Markerview or Legend Click ?

Legend click is important for me now(On particular legend click i have to enable/disable draw real time line chart as in your issue gif).

and yes how to get All Y values in marker in above answer?

Thanks!!!!!

**Comment by Liveinadream** [comment]
The "graphHolder.markview" just a Textview's name,not a Markview or Legend ,you can use Entry e ,get the Y data ,and find the same data in Json.

**Comment by Malikkhoja** [comment]
@kushanshah11 Can you please help me in producing the same line chart in the first picture shared by you. Even i have multi line chart and have to plot Time on Xaxis and Values on Y. But i am not able to achieve the same. The values on XAxis seems to repetitive and not in the correct order.

I have already raised the question #2775

Request you to please help me achieve the same.

Thanks

**Comment by kushanshah11** [comment]
private void addEntry(ArrayList<ChartBean> values, Float base) {

        LineData data = mChart.getData();

        if (data == null) {
            for (int i = 0; i < values.size(); i++) {
                Entry newEntry = new Entry(base, values.get(i).getValue(), values.get(i).getLabel());

                ArrayList<Entry> newEntryList = new ArrayList<Entry>();
                newEntryList.add(newEntry);

                int color;

                if(i == 1){
                    color = R.color.chart_line3;
                }else if ((i == 2)){
                    color = R.color.chart_line2;
                } else if ((i == 3)) {
                    color = R.color.blue;
                } else if ((i == 4)) {
                    color = R.color.bg_purple;
                }else {
                    color = R.color.chart_line1;
                }

                LineDataSet newSet = createSet(newEntryList, R.color.bg_green,color);
                if (data == null) {
                    data = new LineData(newSet);
                }else {

                    data.addDataSet(newSet);
                }
            }
            data.setValueTextColor(Color.GREEN);
            data.setValueTextSize(9f);
        }else {
            for (int i = 0; i < values.size(); i++) {
                Entry newEntry = new Entry(base, values.get(i).getValue(), values.get(i).getLabel());

                LineDataSet newSet = (LineDataSet) mChart.getData().getDataSetByIndex(i);

                List<Entry> newEntryList = newSet.getValues();
                newEntryList.add(newEntry);
                newSet.setValues(newEntryList);
            }

        }

        // set data
        mChart.setData(data);
        mChart.getData().notifyDataChanged();
        mChart.notifyDataSetChanged();
        mChart.invalidate();

        // limit the number of visible entries
        mChart.setVisibleXRangeMaximum(10);
        // mChart.setVisibleYRange(30, AxisDependency.LEFT);

        // move to the latest entry
        mChart.moveViewToX(base);

        // this automatically refreshes the chart (calls invalidate())
        // mChart.moveViewTo(data.getXValCount()-7, 55f,
        // AxisDependency.LEFT)
    }




 private LineDataSet createSet(ArrayList<Entry> entryList , int circleColor , int lineColor) {

        LineDataSet set = new LineDataSet(entryList, ((entryList.get(0).getData()!= null) ? entryList.get(0).getData().toString() : ""));
        set.setAxisDependency(YAxis.AxisDependency.LEFT);
        set.setColor(ContextCompat.getColor(mActivity,lineColor));
        set.setCircleColor(ContextCompat.getColor(mActivity,circleColor));
        set.setLineWidth(1f);
        set.setCircleRadius(3f);
        set.setFillAlpha(65);
        set.setFillColor(ContextCompat.getColor(mActivity,R.color.chart_axis));
        set.setHighLightColor(Color.rgb(244, 117, 117));
        set.setValueTextColor(Color.GREEN);
        set.setValueTextSize(9f);
        set.setDrawValues(false);
        return set;
    }



 else if(item.get(liveDataTitle) instanceof  JSONObject){
                                                    JSONObject newEntry = (JSONObject) item.get(liveDataTitle);

                                                    ArrayList<ChartBean> values = new ArrayList<ChartBean>();
                                                    Iterator iterator = newEntry.keys();

                                                    while (iterator.hasNext()) {
                                                        String key = (String) iterator.next();
                                                        float x = (float) newEntry.getDouble(key);
                                                        values.add(new ChartBean(key,x));
                                                    }

                                                    altimeStamp.add(item.getLong("date"));

                                                    addEntry(values, count);
                                                }

**Comment by Malikkhoja** [comment]
Hi kushanshah11,

Thanks for the quick response and sending the code snippet. Really appreciated.

I had a question that in the last code snippet, you are adding a timestampp in an array but not using it anywhere. I m still facing issues with the date on x axis.

Can you please look at my data as given here #2775 and help me to solve the issue.

**Comment by kushanshah11** [comment]
Hi @Malikkhoja ,

// Two Property 
   xl.setGranularity(3);
  xl.setAvoidFirstLastClipping(true);


// Format what you want to see on X Axis , mine is show date and time to particular timezone

        xl.setValueFormatter(new IAxisValueFormatter() {
            @Override public String getFormattedValue(float value, AxisBase axis) {

                Date time = new java.util.Date(altimeStamp.get((int) value));
                SimpleDateFormat simpleDateFormatArrivals = new SimpleDateFormat("HH:mm:ss");

                TimeZone destinationTimezone = TimeZone.getTimeZone(
                    Utils.getAppPrefString(mActivity, AppConstants.DEFAULT_TIMEZONE));
                simpleDateFormatArrivals.setTimeZone(destinationTimezone);
                return simpleDateFormatArrivals.format(time);

            }
        });

**Comment by Malikkhoja** [comment]
Hi @kushanshah11 ,

Thanks a lot. Can you please help with the base value that u setting?

**Comment by kushanshah11** [comment]
Hi @Malikkhoja i cant understand what are you talking about.

**Comment by Malikkhoja** [comment]
Hi @kushanshah11 ,

The code which you provided, has the 'base' value of type float that you are passing during the time of addEntry function.

I have updated my data values to this. Please look at the issue #2775 . Kindly help me solve the issue.

Many thanks.

**Comment by Edge-Developer** [comment]
@kushanshah11  can you please share how you were able to add label to your multiple line chart.

Thanks

**Comment by kushanshah11** [comment]
@Edge-Developer are you still looking for solution?

Sorry for late response.

**Comment by Edge-Developer** [comment]
@kushanshah11 Yes.

Just share the code of how you finally acheived what is available in that picture ( https://cloud.githubusercontent.com/assets/18567763/22785362/fd4fb9be-eef9-11e6-8e24-a2c0d2b0e860.png );

**Comment by kushanshah11** [comment]
Hi @Edge-Developer i m not able to develop what you are pointing, that was my requirement what i want to achieve but unfortunately i m not able to do that. i have lots of R&D on this but there is no way to achieve what i and you want to develop.

I have achieved particular point shown in marker , if you want to do that i can share. 

Thanks.

**Comment by TijiJoy** [comment]
I wanted to use mysql database table values to plot using mpandroidcharts. How to do it. Please help

**Comment by dinosunny** [comment]
@kushanshah11  Could you please share code snippet for the last image which u posted?

https://cloud.githubusercontent.com/assets/18567763/22785362/fd4fb9be-eef9-11e6-8e24-a2c0d2b0e860.png


Thanks in Advance.

**Comment by shashikant180493** [comment]
can you please share code for given question with me.
i want to try out but can not be able to get multilinechart for selected value at a same time for multiple dataset.

Exactly i want like this.(as shown in attached image)

 it is possible to get Legend click On particular legend Click I have enable or disable draw of live chart.

Thanks in advance...!!

**Comment by indrajitcol** [comment]
@kushanshah11 can you share code about Multi line chart for real time data?? thanks before

**Comment by shuwnyuantee** [comment]
Is anyone able to do this already?
https://cloud.githubusercontent.com/assets/18567763/22785362/fd4fb9be-eef9-11e6-8e24-a2c0d2b0e860.png

I am drawing price history chart with volume for stocks:
<img width="273" alt="screen shot 2018-02-03 at 2 02 17 pm" src="https://user-images.githubusercontent.com/614382/35763610-f20e2f70-08ea-11e8-97a6-e193d8f44f5a.png">

The `line chart is history price, bar chart is volume, x-axis is date`. Upon highlight on either line or bar chart, I want to show `single marker with price + volume + date`.

Anyone has any pointer? Thanks.

**Comment by shuwnyuantee** [comment]
Btw I am able to achieve what I want with below code:

```
public class YMarkerView extends MarkerView {
    private TextView tvContent;
    private final String xLabels[];
    private final double[] prices;
    private final long[] vols;

    // xLabels is for x-axis label
    // prices is array for line chart
    // vols is array for bar chart
    public YMarkerView(Context context, String[] xLabels, double[] prices, long[] vols) {
        super(context, R.layout.custom_marker_view);
        tvContent = (TextView) findViewById(R.id.tvContent);

        this.xLabels = xLabels;
        this.prices = prices;
        this.vols = vols;
    }

    @Override
    public void refreshContent(Entry e, Highlight highlight) {
        int xIndex = (int) e.getX();

        // use x value to lookup for price & vol value from arrays passed in constructor
        String vol = shortenBigNumber(vols[xIndex]);
        String price = toStockPrice(prices[xIndex]);
        String xVal = xLabels[xIndex];

        tvContent.setText(xVal + " " + price + " Vol: " + vol);

        super.refreshContent(e, highlight);
    }
```

Hope this help!

**Comment by soorajnb** [comment]
@Edge-Developer @kushanshah11

**Comment by vmvilas9** [comment]
how can i implement the view shown in third picture?
