### ISSUE TITLE
Issue about function"isDrawingValuesAllowed"

### ISSUE THREAD

**Issue by xiezhigang** [PhilJay/MPAndroidChart#2796]
Hi, 
  Please ignore my poorly English.

  I think it is better that replace the function "**isDrawingValuesAllowed**"  in "**DataRenderer.java**" with my code below in situation which like the picture below.

`
 protected boolean isDrawingValuesAllowed(ChartInterface chart) {
    	return chart.getXRange() < chart.getMaxVisibleCount()
                * mViewPortHandler.getScaleX();
    	/*return chart.getData().getEntryCount() < chart.getMaxVisibleCount()
                * mViewPortHandler.getScaleX();*/
    }
`
[picture](https://github.com/xiezhigang/Android/blob/master/issue.png)

**Comment by GoneUp** [comment]
You should open a pull request to introduce new code, a issue is not the right way to do that.

**Comment by xiezhigang** [comment]
@GoneUp  Thank you.
