### ISSUE TITLE
LineChart : different colors

### ISSUE THREAD

**Issue by HappyDr0id** [PhilJay/MPAndroidChart#28]
Hello,

First of all, thanks a lot for this awesome chart library : it is very complete and customizable + the API seems to be very clear.

I just have one question about colors template. For the LineChart, it is possible to show different colors : one for each line, but is it possible to show different colors for the same line ? I would like to draw different colors for circles, lines and also for the background under the line when the 'filled' option is enabled. I see that I can redefine the Paint object for the circles and change their color, but I can't do the same for lines and filled background, am I wrong ?

Thanks in advance for your answer :)

**Comment by woutergoossens** [comment]
Hi,

Thanks for the great library!
Is it already possible in the release branch to choose different colours for 1 line?

Thanks

Wouter

**Comment by avlemos** [comment]
same question as @woutergoossens.

**Comment by afreakyelf** [comment]
I have on doubt. I want two different colours when Mt data increase and decrease. Suppose when my line chart is moving upward, I want green colour of that line . And when it is moving downward, I want red colour. Any help please

**Comment by Zephyer7673** [comment]
@avlemos , I have same question , Did you find any solution ? I want to have two colors for one dataset based on Y - axis values, but dataset.setColors method not working.

**Comment by Govi02** [comment]
@PhilJay How can I highlight the alternative lines...? For example ,In X axis ,0 should be darken and 1 should be lighten..and again 2 should be darken...How to attain this ??
