### ISSUE TITLE
Real Time Graph for two sets

### ISSUE THREAD

**Issue by preranagawale** [PhilJay/MPAndroidChart#280]
Hello,
I'm trying to plot 2 data sets with 2 different colors on single line graph dynamically. I've created 2 different methods for adding entries for each data set as shown below [addEntry1() & addEntry2()]. But when I call both of them it plots only first called data set and not both.

void addEntry1() {

    LineData data1 = chart.getData();

    if (data1 != null) {

        LineDataSet set1 = data1.getDataSetByIndex(0);
        // set.addEntry(...);

        if (set1 == null) {
            set1 = createSet1();
            data1.addDataSet(set1);
        }

        data1.addEntry(
                new Entry((float) sensorvalue1, set1.getEntryCount()), 0);

    }

    chart.notifyDataSetChanged();

    chart.invalidate();
}

Thanks in advance.

**Comment by PhilJay** [comment]
Thats gonna be in the next update.

**Comment by Faaranta** [comment]
Hi Phil,
Is two sets in real time line chart available now ?
