### ISSUE TITLE
Multiple y values for a given x value not displaying if last x

### ISSUE THREAD

**Issue by MarcusStuhr** [PhilJay/MPAndroidChart#2823]
If there are multiple y values for a fixed x, they appear correctly as long as they do not belong to the last x value of the dataset. But if it's the final x value (for which the data is defined), it does not show all the points associated with that x (and instead appears to show the first entry added). 

Example:

        //firstTimestamp is earlier than secondTimestamp

        data.add(new Entry(firstTimestamp, 10));
        data.add(new Entry(firstTimestamp, 20)); //won't show unless you uncomment below
        data.add(new Entry(firstTimestamp, 30)); //won't show unless you uncomment below

        //data.add(new Entry(secondTimestamp, 40));

Graph when second timestamp commented out: http://i.imgur.com/XpgunQu.png

Graph with second timestamp uncommented (note that the 20 and 30 are now included, whereas they weren't before): http://i.imgur.com/F5WGmfs.png

**Comment by rayano24** [comment]
I'm having the same issue as well, did you find a solution?
