### ISSUE TITLE
Draw line chart with different colors

### ISSUE THREAD

**Issue by wuzesheng** [PhilJay/MPAndroidChart#283]
Hi, 
I want to draw a line chart with your awesome chart library,the chart is like this:
The total length of the line is L, I want to draw the first L/3 line using color A, the next L/3 using color B and the last L/3 using color C. And I want to show 3 legends for each of the part.
Is it possible to draw such a chart, and how to do it with your library?
Thanks very much.

**Comment by PhilJay** [comment]
Yes it is.

Simply create a new `LineDataSet` for each line and set your desired color for the line.

**Comment by jayramhari** [comment]
I want to draw a line chart with nodes in one color and line in a different color is it possible to ??
