### ISSUE TITLE
Display Custom Text on the Chart

### ISSUE THREAD

**Issue by heyou93** [PhilJay/MPAndroidChart#2834]
Hi guys,

How can i add custom text in this charting library?? Custom text in the center of the chart and values of the candlestick on top as well as on the other chart.

Something like this:

EDIT:

Issue fixed. CLOSED

**Comment by enginebai** [comment]
I think that you can take a look at `MarkerView`.

**Comment by heyou93** [comment]
How about the custom text "ALCO" that is on the center of the first chart?? How to do it?

**Comment by heyou93** [comment]
I've already fixed it. Closed
