### ISSUE TITLE
Multiple charts in ListView overlapping

### ISSUE THREAD

**Issue by LeeonTM** [PhilJay/MPAndroidChart#2835]
I am filling a ListView with multiple charts (much like in the example app). This works fine when the charts are drawn for the first time. But when i scroll down in my list to the next chart, and then scroll back up to the top one, the animation for the chart triggers again and overlaps the chart that was already there. Resulting in 2 of the same charts being drawn over each other. This happens to all chart types aswell. Am i forgetting something / doing something wrong?

**Comment by LeeonTM** [comment]
The issue lies in the way I inflate my View in the GetView method in my custom adapter for the listview, and not in the library.

**Comment by collinpreston** [comment]
@LeeonTM What was the way you were inflating?  I'm facing a similar issue.

**Comment by almic** [comment]
@collinpreston This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.
