### ISSUE TITLE
Issue with setFillAlpha when used with cubic-lines

### ISSUE THREAD

**Issue by boardy** [PhilJay/MPAndroidChart#284]
I am developing an app that is utilising the line chart. I am adding data to my chart and to the LineDataSet I have the following code snippet. 

```Java
LineDataSet set1 = new LineDataSet(yVals, "Total crashes during the week");
set1.disableDashedLine();
set1.setColor(Color.BLUE);
set1.setDrawFilled(true);
set1.setLineWidth(2f);
set1.setDrawCubic(true);
set1.setFillColor(Color.BLUE);
set1.setFillAlpha(65);
```

I am setting the fill alpha to be 65 so the fill of the line chart is slightly transparent, this does work until I then also use `setDrawCubic(true)`, the fill alpha then seems to get ignored and instead the fill colour is completely opaque. 

I get the same result when togging the cubic mode from the MPAndroidChart example app as well.

**Comment by Rajagopaul** [comment]
It is a bug on the Library, It seems... When going through the library, I didn't find any code for setting Alpha Color on the place where the fill color is drawn. The alpha color what we set is not at all used inside the library for CubicFill.... I changed the LineChart Code and it is working.
Replace the drawCubic() and drawCubicFill() method of LineChart.java file in com.github.mikephil.charting.charts as follows:

    protected void drawCubic(LineDataSet dataSet, ArrayList<Entry> entries) {
        // get the color that is specified for this position from the
        // DataSet
        mRenderPaint.setColor(dataSet.getColor());

        float intensity = dataSet.getCubicIntensity();

        // the path for the cubic-spline
        Path spline = new Path();

        Path spline2 = new Path();
        float x1, y1, x2, y2, x3, y3;

        ArrayList<CPoint> points = new ArrayList<CPoint>();
        for (Entry e : entries)
            points.add(new CPoint(e.getXIndex(), e.getVal()));

        if (points.size() > 1) {
            for (int j = 0; j < points.size() * mPhaseX; j++) {

                CPoint point = points.get(j);

                if (j == 0) {
                    CPoint next = points.get(j + 1);
                    point.dx = ((next.x - point.x) * intensity);
                    point.dy = ((next.y - point.y) * intensity);
                } else if (j == points.size() - 1) {
                    CPoint prev = points.get(j - 1);
                    point.dx = ((point.x - prev.x) * intensity);
                    point.dy = ((point.y - prev.y) * intensity);
                } else {
                    CPoint next = points.get(j + 1);
                    CPoint prev = points.get(j - 1);
                    point.dx = ((next.x - prev.x) * intensity);
                    point.dy = ((next.y - prev.y) * intensity);
                }

                // create the cubic-spline path
                if (j == 0) {
                    y1 = point.y * mPhaseY;
                    spline.moveTo(point.x, y1);
                    spline2.moveTo(point.x, y1);
                } else {
                    CPoint prev = points.get(j - 1);
                    x1 = prev.x + prev.dx;
                    y1 = (prev.y + prev.dy) * mPhaseY;
                    x2 = point.x - point.dx;
                    y2 = (point.y - point.dy) * mPhaseY;
                    y3 = point.y * mPhaseY;
                    spline.cubicTo(x1, y1, x2, y2, point.x, y3);
                    spline2.cubicTo(x1, y1, x2, y2, point.x, y3);
                }
            }
        }

        mRenderPaint.setStyle(Paint.Style.STROKE);
        mTrans.pathValueToPixel(spline);
        mDrawCanvas.drawPath(spline, mRenderPaint);
        if (dataSet.isDrawFilledEnabled())
            drawCubicFill(dataSet, entries, spline2);
        // if filled is enabled, close the path
        // if (dataSet.isDrawFilledEnabled()) {
        // drawCubicFill(dataSet, entries, spline);
        // } else {
        // mRenderPaint.setStyle(Paint.Style.STROKE);
        // }
        //
        // mTrans.pathValueToPixel(spline);
        // mDrawCanvas.drawPath(spline, mRenderPaint);

    }

    protected void drawCubicFill(LineDataSet dataSet, ArrayList<Entry> entries,
            Path spline) {
        // float fillMin = mFillFormatter
        // .getFillLinePosition(dataSet, mData, mYChartMax, mYChartMin);

        // spline.lineTo((entries.size() - 1) * mPhaseX, fillMin);
        // spline.lineTo(0, fillMin);
        spline.close();
        mRenderPaint.setStyle(Paint.Style.FILL);
        mRenderPaint.setColor(dataSet.getFillColor());
        mRenderPaint.setAlpha(dataSet.getFillAlpha());
        mTrans.pathValueToPixel(spline);
        mDrawCanvas.drawPath(spline, mRenderPaint);
        mRenderPaint.setAlpha(255);
    }

**Comment by PhilJay** [comment]
It seems like this is a library bug. I will see to fix it in the next update.

Best regards,
Phil
