### ISSUE TITLE
Start linechart plotting from the left with dyanmic values

### ISSUE THREAD

**Issue by rohan31710** [PhilJay/MPAndroidChart#2844]
First of all thanks for great library.
Now can we start plotting the points from the left with dynamic values. Actually the liner mode will work only if we have values at beginning, but I have dynamic values on per sec basis. This is causing first point at center then next two at left and right. then center of all.. till it reach my label count. can we override this behavior.

**Comment by rohan31710** [comment]
Sorry Guy.. I got the Solution with min and max values we can do this. Thanks..

**Comment by lokesh1210** [comment]
hi rohan , can you please share how exactly you set the min and max so that there is a default gridlines with the range before populating the first data
