### ISSUE TITLE
markerView problem

### ISSUE THREAD

**Issue by mxylayout** [PhilJay/MPAndroidChart#285]
Sorry to trouble you，but this problem  bothering me for quite.
Watch this：
![image](https://cloud.githubusercontent.com/assets/10346229/5576210/8dcf37fc-902f-11e4-9db4-529a6cde90ff.png)
and the result like this:
![image](https://cloud.githubusercontent.com/assets/10346229/5576857/20fd1f8e-9040-11e4-95b9-0797ba42e902.png)
linechart also:
![image](https://cloud.githubusercontent.com/assets/10346229/5576910/307bbf78-9041-11e4-8c0c-51246a42b814.png)
it is not enough space to draw the markerView on the top，"setOffsets(float x, float y)"   is contral all the markerview  ,so how can i control one of markerview draw in the meddle  if there there is not enough space on the top?
Help me.

**Comment by fateme2sh** [comment]
hi @mxylayout 
i use this method and work it
/////////////////////////////////////////////////////////////////////////
 protected void drawMarkers() {
   // if there is no marker view or drawing marker is disabled
      if (mMarkerView == null || !mDrawMarkerViews || !valuesToHighlight())
            return;
        for (int i = 0; i < mIndicesToHightlight.length; i++) {
            int xIndex = mIndicesToHightlight[i].getXIndex();
            int dataSetIndex = mIndicesToHightlight[i].getDataSetIndex();

            if (xIndex <= mDeltaX && xIndex <= mDeltaX * mPhaseX) {
                Entry e = getEntryByDataSetIndex(xIndex, dataSetIndex);
                // make sure entry not null
                if (e == null)
                    continue;
                float[] pos = getMarkerPosition(e, dataSetIndex);

                // check bounds
                if (pos[0] < mOffsetLeft || pos[0] > getWidth() - mOffsetRight
                        || pos[1] < mOffsetTop || pos[1] > getHeight() - mOffsetBottom)
                    continue;

                // callbacks to update the content
                mMarkerView.refreshContent(e, dataSetIndex, pos);

                mMarkerView.measure(MeasureSpec.makeMeasureSpec(0,                 MeasureSpec.UNSPECIFIED), MeasureSpec.makeMeasureSpec(0, MeasureSpec.UNSPECIFIED));
                mMarkerView.layout(0, 0, mMarkerView.getMeasuredWidth(), mMarkerView.getMeasuredHeight());
                if(pos[1] - mMarkerView.getHeight() <= 0){
                	float y = mMarkerView.getHeight() - pos[1];
                	mMarkerView.draw(mDrawCanvas, pos[0], pos[1]+ y);
                }
            else{
                	mMarkerView.draw(mDrawCanvas, pos[0], pos[1]);
                }
            }
        }
    }

**Comment by mxylayout** [comment]
@fateme2sh 

wonderful way！

here is the result：
![image](https://cloud.githubusercontent.com/assets/10346229/5702016/d992f980-9a8e-11e4-83c4-92afdd6cae60.png)

![image](https://cloud.githubusercontent.com/assets/10346229/5702050/42a67fb4-9a8f-11e4-81e2-2c25e0af8ae2.png)

Thank You!
Thank You!
Thank You!

**Comment by PhilJay** [comment]
As of the latest commit, any **issues concerning the position** of the `MarkerView` should be fixed.

The `MarkerView` now provides **2 abstract methods from which the desired offsets have to be returned**: [AbstractMarkerView class](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/com/github/mikephil/charting/utils/MarkerView.java)

The implementation looks like the following: [Custom MarkerView implementation](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/MyMarkerView.java)

By returning `-(getWidth() / 2);` from the `getXOffset()` method, the `MarkerView` will be centered horizontally.

By returning `-getHeight()` from the `getYOffset()` method, the `MarkerView` position will be above the selected value.
