### ISSUE TITLE
markerView get Entry data is null?

### ISSUE THREAD

**Issue by fukemy** [PhilJay/MPAndroidChart#2852]
![marker data null](https://cloud.githubusercontent.com/assets/8202437/23351057/5827390c-fcf1-11e6-8d70-113e36412715.png)](url)

Here is my code:
`public class FrReportSummary extends Fragment {
    private View rootView;
    private LineChart mChart;
    private ArrayList<Entry> entry0, entry1;
    LineDataSet lDataSet2;

    public static FrReportSummary newInstance() {
        FrReportSummary f = new FrReportSummary();
        return f;
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        rootView = inflater.inflate(R.layout.fr_report_summary, container, false);

        initLayout();
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                runDataSample();
            }
        }, 500);

        return rootView;
    }

    private void runDataSample() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < 20; i++) {
                    final int z = i;
                    mChart.post(new Runnable() {
                        @Override
                        public void run() {
                            if (z == 19)
                                lDataSet2.setDrawCircles(true);
                            addEntry();
                        }
                    });

                    try {
                        Thread.sleep(10);
                    } catch (InterruptedException e) {
                        Logger.error(e.getMessage());
                    }
                }
            }
        }).start();
    }

    private void initLayout() {
        mChart = (LineChart) rootView.findViewById(R.id.graphView);
        // enable description text
        mChart.getDescription().setEnabled(false);
        // enable touch gestures
        mChart.setTouchEnabled(true);
        // enable scaling and dragging
        mChart.setDragEnabled(true);
        mChart.setScaleEnabled(true);
        mChart.setDrawGridBackground(false);
        // if disabled, scaling can be done on x- and y-axis separately
        mChart.setPinchZoom(true);
        // get the legend (only possible after setting data)
        Legend l = mChart.getLegend();
        // modify the legend ...
        l.setForm(Legend.LegendForm.CIRCLE); // set what type of form/shape should be used
        l.setTextColor(Color.WHITE);

        XAxis xl = mChart.getXAxis();
        xl.setTextColor(Color.WHITE);
        xl.setDrawGridLines(true);
        xl.setAxisMaximum(20);
        xl.setAxisMinimum(-20);
        xl.setPosition(XAxis.XAxisPosition.BOTTOM);
        xl.setAvoidFirstLastClipping(true);
        xl.setEnabled(true);

        YAxis leftAxis = mChart.getAxisLeft();
        leftAxis.setTextColor(Color.WHITE);
        leftAxis.setAxisMaximum(21);
        leftAxis.setAxisMinimum(0);
        leftAxis.setDrawGridLines(true);

        YAxis rightAxis = mChart.getAxisRight();
        rightAxis.setTextColor(Color.WHITE);
        rightAxis.setAxisLineColor(leftAxis.getAxisLineColor());
        rightAxis.setDrawLabels(false);
        rightAxis.setEnabled(true);
        rightAxis.setDrawGridLines(true);

        createDataSet();
    }

    private void createDataSet() {
        entry0 = new ArrayList<>();
        entry1 = new ArrayList<>();
        entry0.add(new Entry(0, 0));
        entry1.add(new Entry(0, 0));

        ArrayList<ILineDataSet> lines = new ArrayList<>();

        LineDataSet vLineDataSet = createLineDataSet(true);
        lDataSet2 = createLineDataSet(false);
        lines.add(vLineDataSet);
        lines.add(lDataSet2);

        LineData data = new LineData(lines);
        data.setValueTextColor(Color.WHITE);
        // add empty data
        mChart.setData(data);
        mChart.setMarker(new CustomMarkerView(RappyBerryApplication.getInstance(), R.layout.custom_marker_view_layout));
    }

    private void addEntry() {
        LineData data = mChart.getData();
        if (data != null) {
            ILineDataSet set = data.getDataSetByIndex(0);
            if (set != null) {
                entry0.add(new Entry(0, set.getEntryCount()));
                entry1.add(new Entry(set.getEntryCount() - 1, set.getEntryCount() - 1));
                data.notifyDataChanged();
            }
            // let the chart know it's data has changed
            mChart.notifyDataSetChanged();
            mChart.invalidate();
        }
    }

    private LineDataSet createLineDataSet(boolean isVerticalSet) {
        LineDataSet set = new LineDataSet(isVerticalSet ? entry0 : entry1, isVerticalSet ? "X-Axis Data" : "D-out Data");
        set.setMode(LineDataSet.Mode.CUBIC_BEZIER);
        set.setAxisDependency(YAxis.AxisDependency.LEFT);
        set.setColor(isVerticalSet ? Color.WHITE : ColorTemplate.getHoloBlue());
        set.setCircleColor(ColorTemplate.getHoloBlue());
        set.setDrawCircles(false);
        set.setLineWidth(1f);
        set.setHighlightEnabled(true);
        set.setCircleRadius(5f);
        set.setFillAlpha(65);
        set.setFillColor(ColorTemplate.getHoloBlue());
        set.setHighLightColor(Color.rgb(244, 117, 117));
        set.setValueTextColor(Color.WHITE);
        set.setValueTextSize(9f);
        set.setDrawValues(false);
        return set;
    }

}`

The Log say:
`02-27 13:40:48.229 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 9.0 y: 9.0

02-27 13:40:48.569 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 9.0 y: 9.0

02-27 13:40:48.609 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 6.0 y: 6.0
02-27 13:40:49.594 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 6.0 y: 6.0
02-27 13:40:49.647 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 10.0 y: 10.0

02-27 13:40:49.981 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 10.0 y: 10.0

02-27 13:40:50.066 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 13.0 y: 13.0

02-27 13:40:50.349 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 13.0 y: 13.0

02-27 13:40:50.392 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 8.0 y: 8.0

02-27 13:40:50.717 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 8.0 y: 8.0

02-27 13:40:50.781 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 5.0 y: 5.0

02-27 13:40:51.089 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 5.0 y: 5.0

02-27 13:40:51.138 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 12.0 y: 12.0

02-27 13:40:51.504 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 8.0 y: 8.0

02-27 13:40:51.847 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 8.0 y: 8.0

02-27 13:40:51.899 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 5.0 y: 5.0

02-27 13:40:52.381 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 5.0 y: 5.0

02-27 13:40:52.435 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 7.0 y: 7.0

02-27 13:40:52.682 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 7.0 y: 7.0

02-27 13:40:52.706 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 7.0 y: 7.0

02-27 13:40:52.736 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 9.0 y: 9.0

02-27 13:40:52.921 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 9.0 y: 9.0

02-27 13:40:52.975 27536-27536/com.example.devil2010.rapilityapp E/Rappyberry LOG: e : Entry, x: 9.0 y: 9.0`

 It seem I got right entry, but the data inside this entry is null

**Comment by dustedrob** [comment]
Were you able to fix this? I'm running into the same issue and I can't figure out why...
