### ISSUE TITLE
Help Required

### ISSUE THREAD

**Issue by naveedjamali** [PhilJay/MPAndroidChart#287]
![libshowingerrors](https://cloud.githubusercontent.com/assets/10383390/5603765/b002117a-93b6-11e4-9556-b00b8c58b68a.png)
@PhilJay 
This Library is showing error on following files.
message body is "The hierarchy of the type _ClassName is inconsistent";

BarChart.java
BarLineChartBase.java
CandleStickChart.java
Chart.java
HorizontalBarChart.java
LineChart.java
PieChart.java
PieRadarChartBase.java
RadarChart.java
ScatterChart.java

Please check it at yours, or if there is any error at my side please guide me.
Thank you.

**Comment by lsjwzh** [comment]
Same problem

**Comment by lsjwzh** [comment]
@naveedjamali  Have you  resolved it ?

**Comment by lsjwzh** [comment]
Got it !
I missed the `nineoldandroids-2.4.0-2.jar`
