### ISSUE TITLE
How to adjust the text size of no data?

### ISSUE THREAD

**Issue by JungYongWook** [PhilJay/MPAndroidChart#2877]
hello :)
I want to increase the size of the text when there is no data,

`mBar.setNoDataText();`

It only comes up with what text to write.

`Paint p = mBar.getPaint(Chart.PAINT_INFO);`
`p.setTextSize(20f);`

I tried the paint () line as above, but the text size did not get bigger.
Is there a way to apply it separately?
Does anyone know how to resize nodata text?

**Comment by nen155** [comment]
I have same problem. I want to resize but i can't. I have tried with setNoDataTextTypeface but no result. Somebody know how to resize?

**Comment by nen155** [comment]
I found the solution:
 mChart.getPaint(Chart.PAINT_INFO).setTextSize(Utils.convertDpToPixel(17f));
Use this code to change textSize.

**Comment by ArilesGit** [comment]
Thank you very much @nen155, it works great.
