### ISSUE TITLE
showing BarChart with zero number data

### ISSUE THREAD

**Issue by clementf2b** [PhilJay/MPAndroidChart#2882]
![photo_2017-03-04_17-09-30](https://cloud.githubusercontent.com/assets/9070390/23577560/619651b6-00fd-11e7-85bf-b4bd57c558e1.jpg)

I only set the fourth one be 1.0f and the other are 0.0f.
I think that when I insert a data with 0 number , it would show nothing. However, it show 0.0. Does anyone have the same problem and help me to solve this, please? Thank you.

**Comment by xujianlafeng** [comment]
How to solve this problem，thank you
