### ISSUE TITLE
Disable ylabel values

### ISSUE THREAD

**Issue by tensorfreitas** [PhilJay/MPAndroidChart#290]
It searched through the library but was unable to get a way to not diplaying the y values. Is it possible? 

Second question can someone told me the command to show a x value on a line chart when a point is clicked?

**Comment by zivkest** [comment]
this method does not seem to exist anymore, any other way?

**Comment by vanjavanjavanja** [comment]
any other way?

**Comment by sohel2178** [comment]
in Case of HorizontalBarChart
