### ISSUE TITLE
Animations Don't work

### ISSUE THREAD

**Issue by grndvl1** [PhilJay/MPAndroidChart#2903]
I copied your code for ListViewMultiChartActivity.  Copied every single class and put it in my project everything draws fine except the animations of the Graphs when they are first painted.  Yours animate and fill mine are drawn immediately with no animations.  Why?  Is there something that sets these globally that I am missing?

**Comment by atentis** [comment]
chart.animateXY(2000, 2000);

**Comment by grndvl1** [comment]
Found out it was a proguard issue needed to add this to our proguard file
`-keep class com.github.mikephil.charting.** { *; }`
