### ISSUE TITLE
Cannot remove decimals

### ISSUE THREAD

**Issue by beekay-dev** [PhilJay/MPAndroidChart#2939]
Hello, I am a user of MPAndroidChart. Do you know how to remove decimals from my bar graph? Is there a method that I can use(I am using v2 because I was having issues with v3)

**Comment by khalid-mahmood** [comment]
public class NumberAxisFormatter implements IAxisValueFormatter, IValueFormatter {

    private DecimalFormat mFormat;

    public NumberAxisFormatter() {
        mFormat = new DecimalFormat("###,###,###,###");
    }

    @Override
    public String getFormattedValue(float value, AxisBase axis) {
        return mFormat.format((int) value);
    }

    @Override
    public String getFormattedValue(float value, Entry entry, int dataSetIndex, ViewPortHandler viewPortHandler) {
        return mFormat.format((int) value);
    }
}
@beekay-dev you can try this in setFormatter() function

**Comment by beekay-dev** [comment]
@khalid-mahmood Thank you, it worked!
