### ISSUE TITLE
LargeValueFormatter issue with decimal

### ISSUE THREAD

**Issue by ste71m** [PhilJay/MPAndroidChart#295]
![device-2015-01-08-220019](https://cloud.githubusercontent.com/assets/5102690/5670599/c46f5644-9781-11e4-8f63-a538f204cef2.png)
if i set a LargeValueFormatter, 162.2 is shown as 1622 (in a multipledataset barchart) when enabling setDrawYValues(true)

**Comment by PhilJay** [comment]
Thank you for mentioning this.

Nevertheless I recommend to use `LargeValueFormatter` only for values with 5 digits (without separators) or more.
It is not designed for small numbers like 162 in your case.

**Comment by ste71m** [comment]
It seems that setting setDrawYValues(true) after setting the formatter fix the problem.
Thanks for suggestion anyway

**Comment by PhilJay** [comment]
If the provided `LargeValueFormatter` is not suitable for your issue, you can create your own formatter class by implementing the [ValueFormatter interface](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/com/github/mikephil/charting/utils/ValueFormatter.java).

And then set the formatter for the chart.

`chart.setValueFormatter(new YourFormatter());`

**Comment by ste71m** [comment]
After updating to version 2 can't find setValueFormatter

**Comment by PhilJay** [comment]
You can now set it for each `DataSet` separately or for the whole `ChartData` object.
