### ISSUE TITLE
is there anyway to upside down lineChart.getAxisRight()  value

### ISSUE THREAD

**Issue by Liveinadream** [PhilJay/MPAndroidChart#2955]
thses method can set the bottom value with 0 and top value with 100:

`   lineChart.getAxisRight().setAxisMaxValue(100);
        lineChart.getAxisRight().setAxisMinValue(0);`

I want to set the bottom value with 100 and the top value with 0,is there anyway to do it.

compile  version
 compile 'com.github.PhilJay:MPAndroidChart:v3.0.0-beta1'

**Comment by TheBogueRat** [comment]
You should be able to use: 

`yAxis.setInverted(true);`

**Comment by Liveinadream** [comment]
@TheBogueRat thanks
