### ISSUE TITLE
Failed to find: com.nineoldandroids:library:2.4.+

### ISSUE THREAD

**Issue by codezjx** [PhilJay/MPAndroidChart#297]
And gradle plugin show a warnning: Avoid using + in version numbers; can lead to unpredictable and unrepeatable builds.

**Comment by codezjx** [comment]
Finally I set "2.4.+" to "2.4.0"(It's the latest version of nineoldandroids), and rebuild, the error is gone.^^

**Comment by codezjx** [comment]
My question is: PhilJay, your Android Studio did't show the error above ?

**Comment by tajchert** [comment]
As you wrote in first comment it is not an error but warning.

**Comment by PhilJay** [comment]
I have not been using Android Studio so far, just switched today. Havent seen the warning yet.
