### ISSUE TITLE
Getting Issue for Cubic graph which is having one of the value 0 for 2.1.6 version 

### ISSUE THREAD

**Issue by pnaringe1** [PhilJay/MPAndroidChart#2985]
![screenshot_20170404-154702](https://cloud.githubusercontent.com/assets/26891645/24643040/dbf6292a-1928-11e7-9cab-2b332070139a.png)

Can  U please give the solution.

**Comment by pnaringe1** [comment]
Hello Phil,

I want to show curve without cutting on 0th value.How can I do that?

**Comment by PhilJay** [comment]
Make sure your axis is not set to start at zero

**Comment by pnaringe1** [comment]
No, I didint set to start at zero

**Comment by pnaringe1** [comment]
Hello Phil,
The y axis values are not align with horizontal line. what to do for that?

**Comment by pnaringe1** [comment]
lineChart.getXAxis().setSpaceBetweenLabels(1);
        lineChart.setBackgroundColor(Color.WHITE);
        lineChart.setDescription("");
        lineChart.getAxisLeft().setDrawGridLines(false);
        lineChart.setGridBackgroundColor(128);
        lineChart.setBorderColor(255);
        lineChart.getAxisRight().setDrawLabels(false);
        lineChart.getAxisLeft().setDrawLabels(true);
        lineChart.setDrawBorders(true);
        lineChart.setData(data);
        lineChart.getXAxis().setTextColor(labelColorAxis);
        lineChart.getAxisLeft().setTextColor(labelColorAxis);
        lineChart.getLegend().setEnabled(false);
        lineChart.setScaleEnabled(false);
        lineChart.getData().setHighlightEnabled(false);

        // line color
        dataset.setColor(dataSetColor);
        // line width
        dataset.setLineWidth(2);

        switch (type){
            // 7 Days
            case 0:
                dataset.setCircleColor(dataSetColor);
                dataset.setCircleColorHole(dataSetColor);
                dataset.setCircleSize(3f);
                // this shows values on graph
                dataset.setDrawValues(true);
                dataset.setValueTextSize(7f);
                break;
            // 30 Days
            case 1:
                dataset.setDrawCubic(true);
                dataset.setDrawFilled(false);
                dataset.setCircleSize(0);
                // this hides values on graph
                dataset.setDrawValues(false);
                dataset.setMode(HORIZONTAL_BEZIER);
//lineChart.setTouchEnabled(true);
                break;
        }


These are lines of code I used to set the properties for graph

**Comment by pnaringe1** [comment]
compile 'com.github.PhilJay:MPAndroidChart:v2.2.5'
I am using this version
