### ISSUE TITLE
BarChart not grouping correctly

### ISSUE THREAD

**Issue by deliehr** [PhilJay/MPAndroidChart#3010]
Hi!

I want to create a bar chart with a grouping feature.
Here are my data definitions:

        List<BarEntry> list1 = new ArrayList<BarEntry>();
        list1.add(new BarEntry(0f, 12f));
        list1.add(new BarEntry(1f, 2f));

        List<BarEntry> list2 = new ArrayList<BarEntry>();
        list2.add(new BarEntry(0f, 5f));
        list2.add(new BarEntry(1f, 1f));

        List<BarEntry> list3 = new ArrayList<BarEntry>();
        list3.add(new BarEntry(0f, 9f));
        list3.add(new BarEntry(1f, 2f));

So I have data at the integer points 0 and 1, am I'm right?
Via

        chart.setData(data);
        chart.groupBars(0, 0.1f, 0.01f);
        chart.invalidate(); // refresh

But, the three bars are not between the groups...
The result:
<img width="843" alt="2017-04-13 at 19 40" src="https://cloud.githubusercontent.com/assets/6537841/25016666/40b75924-2081-11e7-8605-3f5392d10430.png">

Can someone tell me why the framework is not grouping correctly?

The second questions: How are values grouped? Above I have three lists with each two values. Each value starts at x=0 or x=1. Are values grouped by values? Or by lists?
Greetings!

**Comment by RajkumarRepo** [comment]
String dayvals={"Sun","Mon","Tue","Wed","Thu","Fri","Sat"};
List<BarEntry> barentry=new ArrayList<BarEntry>();
barentry.add(new BarEntry(11000, 0));           //Parameter like value comes Description

List<BarEntry> barentry1=new ArrayList<BarEntry>();
barentry1.add(new BarEntry(10000, 0)); 

List<BarEntry> barentry2=new ArrayList<BarEntry>();
barentry2.add(new BarEntry(7000, 0)); 

BarDataSet barDataSet= new BarDataSet(barentry, "Bus");
 barDataSet.setBarSpacePercent(25);

BarDataSet barDataSet1 = new BarDataSet(barentry1, "Cycle");
 barDataSet1.setBarSpacePercent(25);

BarDataSet barDataSet2= new BarDataSet(barentry2, "Walk");
 barDataSet2.setBarSpacePercent(25);

BarData data= new BarData(dayvals);
data.addDataset(barDataSet);
data.addDataset(barDataSet1);
data.addDataset(barDataSet2);
                                        
barChart.setData(data);
barChart.setDescription("Travel");
barChart.invalidate();
