### ISSUE TITLE
Show a label when a value is selected

### ISSUE THREAD

**Issue by Firerazzer** [PhilJay/MPAndroidChart#3018]
I want to show a label with specific data when a value is selected like in the demo :
![screenshot_1492502996](https://cloud.githubusercontent.com/assets/19490379/25120679/62c3c4fc-241f-11e7-92b6-564163bbe261.png)

so I paste this code :
`

    @Override
    public void onValueSelected(Entry e, Highlight h) {

        if (e == null)
            return;

        RectF bounds = mOnValueSelectedRectF;
        mChart.getBarBounds((BarEntry) e, bounds);
        MPPointF position = mChart.getPosition(e, AxisDependency.LEFT);

        Log.i("bounds", bounds.toString());
        Log.i("position", position.toString());

        Log.i("x-index",
                "low: " + mChart.getLowestVisibleX() + ", high: "
                        + mChart.getHighestVisibleX());

        MPPointF.recycleInstance(position);
    }`

but it doesn't work, the log are displayed but nothing happen on the screen.
What I have forget or miss ?

**Comment by Firerazzer** [comment]
To display a marker with something inside when a value is selected use a MarkerView and not the valueSelected listener.

All the necessary doc for create yours is here : https://github.com/PhilJay/MPAndroidChart/wiki/IMarker-Interface

**Comment by VinayLucknow** [comment]
How to close MarkerView once it display. In my case MarkerView displaying continuous.
