### ISSUE TITLE
Replace graph dots circles into custom drawable

### ISSUE THREAD

**Issue by wass08** [PhilJay/MPAndroidChart#302]
Hi,

I wonder if it is possible to customize the dots in a line chart to replace the default circle and if yes, how to do that ?

The expected result would be like that :

![image](https://cloud.githubusercontent.com/assets/6551176/5737482/a0cfe06e-9be1-11e4-9cd6-d3d025c40d27.png)

Thank you !

**Comment by PhilJay** [comment]
That is not yet possible. You will have to implement it yourself.

Regards,
Phil
