### ISSUE TITLE
Value formatting problem

### ISSUE THREAD

**Issue by kozmabalazs** [PhilJay/MPAndroidChart#3024]
Hi guys. 

I'm using the old 2.2.5 version of the library. I would like to know if there is a way to show only round values on the bottom axis? Like 0, 1, 2 in this situation in the below picture.

Thanks!

![18012669_120332000241136143_464418501_o](https://cloud.githubusercontent.com/assets/22748551/25174270/7cea1b52-24ff-11e7-93b6-f151c48aca6e.jpg)

**Comment by Firerazzer** [comment]
Did "getXAxis().setGranularity(1)" exist in 2.2.5 ? I think it can resolve your problem.

**Comment by kozmabalazs** [comment]
Thank you for the suggestion! I had to do:
YAxis yAxisRight = mBarChart.getAxisRight();
yAxisRight.setGranularity(1f);

Problem solved.

**Comment by Firerazzer** [comment]
I've hade the same problem a week ago ! Close the issue if it's OK :)
