### ISSUE TITLE
No chart data available - Pie Chart

### ISSUE THREAD

**Issue by MGohil** [PhilJay/MPAndroidChart#3047]
Hi,

I am getting the message No chart data available, even though I am providing the data in it.
Please see the attached screenshots. Please some one help me where I am doing mistake.

Thanks,
MGohil
![code](https://cloud.githubusercontent.com/assets/16605284/25399768/20d892e4-2a0e-11e7-8392-cf54dfcfb68f.PNG)
![screenshot_1493142231](https://cloud.githubusercontent.com/assets/16605284/25399776/2a4c0a7c-2a0e-11e7-8ea9-21e5828e08e7.png)

**Comment by MGohil** [comment]
Solved the issue.

Here was my code above the posted screen shot.
var ignore = base.OnCreateView(inflater, container, savedInstanceState);
var v = this.BindingInflate(Resource.Layout.fragment_home, null);

var pieChart = (PieChart)v.FindViewById(Resource.Id.piechart);  ---> Didn't worked.
var pieChart = (PieChart)ignore.FindViewById(Resource.Id.piechart); ---> Worked like a charm!!

Thanks,
MGohil

**Comment by akshaymanagooli** [comment]
hi @MGohil i tried your solution, but it dint work for me. on first launch piechart is visible, but on second launch, not visible, please help
