### ISSUE TITLE
Line chart with logarithmic axis

### ISSUE THREAD

**Issue by m-Zarea** [PhilJay/MPAndroidChart#3065]
Hi, @myAlfred @aint @nielsz @dseider @mikemonteith @matiash 

I'm using your great chart view in my android app. It's so helpful and is very powerful. Thanks for your sharing. :)

 my app, I used it to show a line chart and I have to change X & Y axes to logarithmic. I can't find any example code about it at github to solve my problem.

Would you please help me to solve it?

I'm waiting for your guide.
Thanks so much
Zare

**Comment by m-Zarea** [comment]
Dear Programmers... 

please guide me to solve the problem...

I'm waiting...

**Comment by thierryH91200** [comment]
look at 
https://github.com/danielgindi/Charts/pull/2206

**Comment by m-Zarea** [comment]
Dear thierryH91200

I'm so sorry, I was so busy in last two weeks.
I checked the link you mentioned me in last comment. I think it's not suitable for me because it's just for OS developers. I develop my app in Android. 

Please help me to find the right way.
I'm waiting for your great answer.

Zare

**Comment by MGaetan89** [comment]
This was already reported in #2333.
Can you close your issue to focus the effort there?

**Comment by almic** [comment]
discussion moved to #2768 and #2801

Yeah, two issues, I know...
