### ISSUE TITLE
Making chart static (not responsive to touch)

### ISSUE THREAD

**Issue by jkwiecien** [PhilJay/MPAndroidChart#307]
I couln't make my pie chart unresponsive to touch. I don't want it to be clickable or able to rotate. It only messes up with my scroll view and pull to refresh. Is there a way to disable user interaction with chart?

**Comment by PhilJay** [comment]
You can call `setRotationEnabled(boolean enabled)` and `setTouchEnabled(boolean enabled)` to enable/disable rotation and touch.
