### ISSUE TITLE
Unexpected behavior when dragging chart content inside a ViewPager

### ISSUE THREAD

**Issue by brenoptsouza** [PhilJay/MPAndroidChart#3070]
When I try to scroll the content of a LineChart that is placed inside a ViewPager, the LineChart view won't consume the events properly and the ViewPager will start scrolling along with the chart contents

**Comment by brenoptsouza** [comment]
Nevermind, I dug deeper and found out that the problem was a parent view that wasn't implementing the `requestDisallowInterceptTouchEvent` call like expected.

**Comment by Shahar2k5** [comment]
@brenoptsouza can you explain?
I'm facing the same issue here.

**Comment by faith-hb** [comment]
I'm facing the same issue here.
