### ISSUE TITLE
how to draw MarkerView on two lines?

### ISSUE THREAD

**Issue by Dongwei0516** [PhilJay/MPAndroidChart#3071]
Hi! I have some questions with LineChart,  i know how to set the MarkerView and Hightlight, but how 
can i draw two MarkerView on two Lines when i touch the chart? like the picture below 
can you help me ? thanks!
<img width="520" alt="markerview" src="https://cloud.githubusercontent.com/assets/22168502/25646512/a79083e0-2feb-11e7-88b8-3f350e2e46b7.png">

**Comment by Dongwei0516** [comment]
`Highlight highlight1 = new Highlight(e.getX(),values2.get(x).getY(),1);
  Highlight highlight2 = new Highlight(e.getX(),values.get(x).getY(),0);
  ArrayList<Highlight> highlightList = new ArrayList<Highlight>();
  highlightList.add(highlight1);
  highlightList.add(highlight2);
  Highlight[] highlights = highlightList.toArray(new Highlight[0]);
  mChart.highlightValues(highlights);`

the problem has solved

**Comment by bartwell** [comment]
Hi @Dongwei0516 , could you please provide whole chart settings code? I am trying to use your code, but circles on the lines doesn't showing. How to fix it? What settings you are using?
