### ISSUE TITLE
How can I show text labels on X-axis bars in MP Android bubble chart v3.*

### ISSUE THREAD

**Issue by mubashar26** [PhilJay/MPAndroidChart#3093]
I'm using MP android bubble chart V3.0. I have to display labels of each bar on x-axis. it's working in v2.6 but not in v3.*
how to do this. does anyone know about this?
I need to implement using MP android v3.* not below.

**Comment by mubashar26** [comment]
I have to show in this way. like I have three bars. so I have to show on x-axis for each i.e label1, label2, label3 and so on.

**Comment by Sp4Rx** [comment]
Have you tried this:
 XAxis xAxis = mChart.getXAxis();
 xAxis.setValueFormatter(new IndexAxisValueFormatter(new String[]{"label1","label2",label3"}));

**Comment by moorthysubu** [comment]
Yes, I'm also facing this issue. Any solutions?

**Comment by itsrajgaur** [comment]
I am also facing the same issue.

**Comment by Jeffreyoboe1** [comment]
Same issue.  I'm thinking about using Groups to solve.

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
