### ISSUE TITLE
PieChart: How to get rid of bottom label

### ISSUE THREAD

**Issue by kotasunil79** [PhilJay/MPAndroidChart#3094]
Hi,
    I am trying to get rid of the bottom left-hand side label from the Pie Chart. I am obviously missing something simple here but I tried looking around to figure a way to do it.
Can anyone help me solve this,
![device-2017-05-08-101912](https://cloud.githubusercontent.com/assets/20445635/25816532/3605874c-33d9-11e7-95ed-316ec4f6f9a2.png)

Thanks,

**Comment by naderbal** [comment]
pieChart.setDrawEntryLabels(false);

**Comment by kotasunil79** [comment]
I have already set `pieChart.setDrawEntryLabels(false);` it is'nt helping

**Comment by naderbal** [comment]
`pieChart.getLegend().setEnabled(false);`

**Comment by kotasunil79** [comment]
`pieChart.getLegend().setEnabled(false);` worked. Thanks
