### ISSUE TITLE
MoveViewJob has Memory leak

### ISSUE THREAD

**Issue by xueyaolive** [PhilJay/MPAndroidChart#3099]
class: MoveViewJob
your code: 
               private static ObjectPool<MoveViewJob> pool = ObjectPool.create(2, new MoveViewJob((ViewPortHandler)null, 0.0F, 0.0F, (Transformer)null, (View)null));

I think the static poll has a context that will cause memory leaks .
It cannot be released from the outside,Maybe it should be made public ,Although I can solve it in the following ways, but this is not the way to solve it .

 code:  MoveViewJob.getInstance(null,0,0,null,null);
Please help me!Thanks.

**Comment by anthony3444** [comment]
The same problem saw with LeakCanary.
Thank you guys for your support!

**Comment by MGaetan89** [comment]
Can you close this issue as it was already reported in #2238?

**Comment by almic** [comment]
identical to 2238, closing

**Comment by snpmyn** [comment]
MoveViewJob has Memory leak.

**Comment by pengxinaglin** [comment]
Add the following code to the MoveViewJob class:

public static void recycleInstance(MoveViewJob instance) {
        instance.mViewPortHandler = null;
        instance.mTrans = null;
        instance.view = null;
        pool.recycle(instance);
 }
