### ISSUE TITLE
Customize x-labels text to build a time series chart 

### ISSUE THREAD

**Issue by gavabri** [PhilJay/MPAndroidChart#310]
I have a chart representing date and time on  x-values. I added those values in dataset  as milliseconds. It would be great to be able to  customize x-labels for example formatting the long value of DateTime in Millis to a string of date and time. Thank you for your beautiful library

**Comment by pavelkarasek** [comment]
I would love this feature. I want days on x axis but only hours of particular day. 
For example

 1/1/2015, 1, 2, 3, ..., 23
2/1/2015, 1, 2, 3, ..., 23

the date stands for 00:00 

could you give me some advice how to do that? Thank you
