### ISSUE TITLE
MPChart RTL issues

### ISSUE THREAD

**Issue by Faisal-Naseer** [PhilJay/MPAndroidChart#3109]
First of all thanks for a wonderful library. I am using MPCharts in one of my Multi-Lingual application but my charts are not displaying RTL.

**Comment by shubham1g5** [comment]
@Faisal-Naseer Probably too late though Graphs and Charts should not be mirrorred according to the RTL guidelines. So this seems expected. You can read more about what gets mirrorred and what not here - https://material.io/design/usability/bidirectionality.html#mirroring-layout

**Comment by almic** [comment]
Thanks @shubham1g5

**Comment by panovvitalik** [comment]
> First of all thanks for a wonderful library. I am using MPCharts in one of my Multi-Lingual application but my charts are not displaying RTL.

Is there a solution for today for supportin Rtl locale?
