### ISSUE TITLE
Native Crash

### ISSUE THREAD

**Issue by ymmmvp36** [PhilJay/MPAndroidChart#3146]
i have a activity.it contains a fragment.and the fragment has a viewpager. the viewpager shows a fragment which displays the charts such as bar,line,pie or radar.when i put the phone for several minutes，the app crashed.i found the log like this:
A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 3695 (hwuiTask1)
i don't know how to solve this.i need your help,please.thank you.

**Comment by pj210493** [comment]
@ymmmvp36 Can we convert this hexagon/pentagon shape into circle.

**Comment by almic** [comment]
@ymmmvp36 sorry but this issue tracker is not the place to ask for programming help. Questions like this belong on stackoverflow.
