### ISSUE TITLE
How to use this library.

### ISSUE THREAD

**Issue by naveedjamali** [PhilJay/MPAndroidChart#316]
This library is wonderful but is there any tutorial on the web for this lib. please give me any link about Tutorial or sample project. thank you.

**Comment by PhilJay** [comment]
This is the example project: https://play.google.com/store/apps/details?id=com.xxmassdeveloper.mpchartexample&hl=de

And this is the corresponding code: https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample

It can be found in this repository.
