### ISSUE TITLE
How to plot multiple dataset object with different number of points (x-values) in the same chart line

### ISSUE THREAD

**Issue by rrodriguez1975** [PhilJay/MPAndroidChart#318]
I have a line chart. Within it I want to plot multiple dataset objects, let's say, dataset 1 and dataset 2.
dataset 1 has a number of x-values different from dataset 2. For example:

Dataset object 1 Y-values: 0, 12,  23, 34, 50, 100, 130
                             X-values: 0, 10, 15,  20, 25,   30,   35

Dataset object 2 Y-values: 1,  5, 10, 15, 20,  30,  40,  70, 75, 80
                             X-values: 0,  1,  2,    3,   4,     5,    6,    7,    8,   9

In this case, how do you plot them in the same line chart? I am not be able to do it.

Please, could you help me?

I have posted it in stackoverflow:
http://stackoverflow.com/questions/28116357/mpandroidchart-how-to-represent-multiple-dataset-object-with-different-number-of

Also I have seen some people have same problem as me:
http://stackoverflow.com/questions/26873445/plot-multiple-charts-in-one-in-mpandroidchart

**Comment by PhilJay** [comment]
I responded on stackoverflow. Hope it helps.
