### ISSUE TITLE
Text Color for X-axis lables

### ISSUE THREAD

**Issue by rutvijkumarshah** [PhilJay/MPAndroidChart#319]
@PhilJay  Thanks for this awesome library. 

I could not find a way to change color of x-axis lables. I was able to change text color of y axis values using 
mChart.setValueTextColor(getResources().getColor(android.R.color.white));

But this changes text color of only y-axis values in Bar Chart.

**Comment by rutvijkumarshah** [comment]
Closing this issue. There is a way to set text color for XLables using following code :
  XLabels labels = mChart.getXLabels();
     labels.setTextColor(getResources().getColor(android.R.color.white));

**Comment by surfer190** [comment]
@rutvijkumarshah I'm not finding `.getXLabels()`

Is this on an older version?

**Comment by rutvijkumarshah** [comment]
@surfer190 , yeah its with old version, I filed the issue one year ago.

**Comment by Rohittt728** [comment]
@rutvijkumarshah It isn't working. then how to set color for x-axis Labels ?

**Comment by vishalsgithub** [comment]
Try it.

Chart.getXAxis().setTextColor(Color.Blue);

**Comment by AlexandrSushkov** [comment]
getXAxis()  - deprecated, and throws RuntimeException("PieChart has no XAxis"). What is the new way to change x-axis color?

**Comment by vishalsgithub** [comment]
if you want to change the text color of lables
try it..

mChart.setEntryLabelColor(Color.BLUE);

or if you want to change value color try it..

PieData data = new PieData(dataSet);
data.setValueTextColor(Color.RED);

i hope it works..

**Comment by AlexandrSushkov** [comment]
Thanks! It helped me, and saved a lot of time.

**Comment by goodlifechris** [comment]
legend will do

**Comment by goodlifechris** [comment]
pieChart.getLegend().setTextColor(Color.WHITE);

**Comment by MasonDarcy** [comment]
I have this issue now on a linechart, the text color of my x-labels changes to a dark purple but will not change to any other color.

**Comment by babbar01** [comment]
> 
> 
> I have this issue now on a linechart, the text color of my x-labels changes to a dark purple but will not change to any other color.

I know its a late reply but surely it will help others as it is common mistake
Use below line for that

ContextCompat.getColor(context, R.color.red_color)

The mistake is that you are providing the id of color ( by giving only R.color.some_color)  not the actual color

**Comment by anshul2502** [comment]
is it possible to give multiple colours to labels in pie chart? like this:
<img width="155" alt="frnWb" src="https://user-images.githubusercontent.com/8766047/118680706-95fe5400-b81c-11eb-9f4b-c437aa2e58c8.png">

**Comment by saldous** [comment]
> is it possible to give multiple colours to labels in pie chart? like this: <img alt="frnWb" width="155" src="https://user-images.githubusercontent.com/8766047/118680706-95fe5400-b81c-11eb-9f4b-c437aa2e58c8.png">

I would also love to be able to have each label with a different color, to match the color of the bar.
