### ISSUE TITLE
how to calculate zoom's scaleX and moveViewToX's xIndex ?

### ISSUE THREAD

**Issue by yanjf90** [PhilJay/MPAndroidChart#3197]
I used the follow function to zoom chart and move chart.
`mChart.zoom(scaleX，mChart.getScaleY(), mChart.getX(), mChart.getY());`
`mChart.moveViewToX(Integer.MAX_VALUE);`

the question is my xValues size is unfixed, maybe 1000 or 800...，I want to show the last 30 (month) or 7（week） datas. how the scaleX be calculated? and how xIndex?

**Comment by yanjf90** [comment]
I get it.
`scaleX = xVlaues.size() / 30.0f or xValues.size() / 7.0f;`  not  `scaleX = xVlaues.size() / 30 or xValues.size() / 7;`

**Comment by chuwe1** [comment]
thank u man, it works for me
