### ISSUE TITLE
ANR in DataSet.getEntryIndex

### ISSUE THREAD

**Issue by MGaetan89** [PhilJay/MPAndroidChart#3202]
I am getting multiple ANR reports for my applications regarding your library. Sadly I was not able to reproduce it.
Here is what I see in the logs. I am using v3.0.2 of your library. Don't hesitate to ask if you need more information.

> "main" prio=5 tid=1 Runnable
>   | group="main" sCount=0 dsCount=0 obj=0x74d1a2a0 self=0xb8b34e88
>   | sysTid=12387 nice=0 cgrp=default sched=0/0 handle=0xb6f37b34
>   | state=R schedstat=( 12213623221 1792568929 5417 ) utm=1152 stm=68 core=1 HZ=100
>   | stack=0xbe0f3000-0xbe0f5000 stackSize=8MB
>   | held mutexes= "mutator lock"(shared held)
>   at java.util.ArrayList.get (ArrayList.java:310)
>   **at com.github.mikephil.charting.data.DataSet.getEntryIndex (DataSet.java:303)**
>   **at com.github.mikephil.charting.data.DataSet.calcMinMaxY (DataSet.java:86)**
>   **at com.github.mikephil.charting.data.ChartData.calcMinMaxY (ChartData.java:120)**
>   **at com.github.mikephil.charting.charts.BarLineChartBase.autoScale (BarLineChartBase.java:347)**
>   **at com.github.mikephil.charting.charts.BarLineChartBase.onDraw (BarLineChartBase.java:198)**
>   at android.view.View.draw (View.java:16199)
>   at android.view.View.updateDisplayListIfDirty (View.java:15196)
>   at android.view.View.draw (View.java:15969)
>   at android.view.ViewGroup.drawChild (ViewGroup.java:3612)
>   at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3402)
>   at android.view.View.updateDisplayListIfDirty (View.java:15191)
>   at android.view.View.draw (View.java:15969)
>   at android.view.ViewGroup.drawChild (ViewGroup.java:3612)
>   at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3402)
>   at android.view.View.updateDisplayListIfDirty (View.java:15191)
>   at android.view.View.draw (View.java:15969)
>   at android.view.ViewGroup.drawChild (ViewGroup.java:3612)
>   at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3402)
>   at android.view.View.updateDisplayListIfDirty (View.java:15191)
>   at android.view.View.draw (View.java:15969)
>   at android.view.ViewGroup.drawChild (ViewGroup.java:3612)
>   at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3402)
>   at android.view.View.draw (View.java:16202)
>   at android.view.View.updateDisplayListIfDirty (View.java:15196)
>   at android.view.View.draw (View.java:15969)
>   at android.view.ViewGroup.drawChild (ViewGroup.java:3612)
>   at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3402)
>   at android.view.View.updateDisplayListIfDirty (View.java:15191)
>   at android.view.View.draw (View.java:15969)
>   at android.view.ViewGroup.drawChild (ViewGroup.java:3612)
>   at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3402)
>   at android.view.View.draw (View.java:16202)
>   at android.widget.ScrollView.draw (ScrollView.java:1715)
>   at android.view.View.updateDisplayListIfDirty (View.java:15196)
>   at android.view.View.draw (View.java:15969)
>   at android.view.ViewGroup.drawChild (ViewGroup.java:3612)
>   at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3402)
>   at android.view.View.draw (View.java:16202)
>   at android.view.View.updateDisplayListIfDirty (View.java:15196)
>   at android.view.View.draw (View.java:15969)
>   at android.view.ViewGroup.drawChild (ViewGroup.java:3612)
>   at android.support.design.widget.CoordinatorLayout.drawChild (CoordinatorLayout.java:1230)
>   at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3402)
>   at android.view.View.updateDisplayListIfDirty (View.java:15191)
>   at android.view.View.draw (View.java:15969)
>   at android.view.ViewGroup.drawChild (ViewGroup.java:3612)
>   at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3402)
>   at android.view.View.updateDisplayListIfDirty (View.java:15191)
>   at android.view.View.draw (View.java:15969)
>   at android.view.ViewGroup.drawChild (ViewGroup.java:3612)
>   at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3402)
>   at android.view.View.updateDisplayListIfDirty (View.java:15191)
>   at android.view.View.draw (View.java:15969)
>   at android.view.ViewGroup.drawChild (ViewGroup.java:3612)
>   at android.support.v4.widget.DrawerLayout.drawChild (DrawerLayout.java:1379)
>   at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3402)
>   at android.view.View.updateDisplayListIfDirty (View.java:15191)
>   at android.view.View.draw (View.java:15969)
>   at android.view.ViewGroup.drawChild (ViewGroup.java:3612)
>   at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3402)
>   at android.view.View.updateDisplayListIfDirty (View.java:15191)
>   at android.view.View.draw (View.java:15969)
>   at android.view.ViewGroup.drawChild (ViewGroup.java:3612)
>   at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3402)
>   at android.view.View.updateDisplayListIfDirty (View.java:15191)
>   at android.view.View.draw (View.java:15969)
>   at android.view.ViewGroup.drawChild (ViewGroup.java:3612)
>   at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3402)
>   at android.view.View.updateDisplayListIfDirty (View.java:15191)
>   at android.view.View.draw (View.java:15969)
>   at android.view.ViewGroup.drawChild (ViewGroup.java:3612)
>   at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3402)
>   at android.view.View.updateDisplayListIfDirty (View.java:15191)
>   at android.view.View.draw (View.java:15969)
>   at android.view.ViewGroup.drawChild (ViewGroup.java:3612)
>   at android.view.ViewGroup.dispatchDraw (ViewGroup.java:3402)
>   at android.view.View.draw (View.java:16202)
>   at com.android.internal.policy.PhoneWindow$DecorView.draw (PhoneWindow.java:2690)
>   at android.view.View.updateDisplayListIfDirty (View.java:15196)
>   at android.view.ThreadedRenderer.updateViewTreeDisplayList (ThreadedRenderer.java:281)
>   at android.view.ThreadedRenderer.updateRootDisplayList (ThreadedRenderer.java:287)
>   at android.view.ThreadedRenderer.draw (ThreadedRenderer.java:322)
>   at android.view.ViewRootImpl.draw (ViewRootImpl.java:2627)
>   at android.view.ViewRootImpl.performDraw (ViewRootImpl.java:2446)
>   at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2079)
>   at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1119)
>   at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:6060)
>   at android.view.Choreographer$CallbackRecord.run (Choreographer.java:858)
>   at android.view.Choreographer.doCallbacks (Choreographer.java:670)
>   at android.view.Choreographer.doFrame (Choreographer.java:606)
>   at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:844)
>   at android.os.Handler.handleCallback (Handler.java:746)
>   at android.os.Handler.dispatchMessage (Handler.java:95)
>   at android.os.Looper.loop (Looper.java:148)
>   at android.app.ActivityThread.main (ActivityThread.java:5459)
>   at java.lang.reflect.Method.invoke! (Native method)
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:728)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:618)

**Comment by jiangzenghe** [comment]
@MGaetan89 
Hello Muller, I have the same problem,please help me for a few infomations...I have no idea for this..thank very much.

**Comment by MGaetan89** [comment]
If I recall correctly, I have overiden `int LineDataSet#getEntryIndex(float, float, Rounding)` as follow:

```kotlin
class MyLineDataSet : LineDataSet(yVals: List<Entry>, label: String) : LineDataSet(yVals, label) {
	override fun getEntryIndex(xValue: Float, closestToY: Float, rounding: Rounding?): Int {
		if (mValues == null || mValues.isEmpty()) {
			return -1
		}

		var low = 0
		var high = mValues.size - 1
		var closest = high

		// Only change is here
		while (low < high && high - low > 1) {
			val m = (low + high) / 2

			val d1 = mValues[m].x - xValue
			val d2 = mValues[m + 1].x - xValue
			val ad1 = Math.abs(d1)
			val ad2 = Math.abs(d2)

			if (ad2 < ad1) {
				// [m + 1] is closer to xValue
				// Search in an higher place
				low = m + 1
			} else if (ad1 < ad2) {
				// [m] is closer to xValue
				// Search in a lower place
				high = m
			} else {
				// We have multiple sequential x-value with same distance
				if (d1 >= 0.0) {
					// Search in a lower place
					high = m
				} else if (d1 < 0.0) {
					// Search in an higher place
					low = m + 1
				}
			}

			closest = high
		}

		if (closest != -1) {
			val closestXValue = mValues[closest].x
			if (rounding == DataSet.Rounding.UP) {
				// If rounding up, and found x-value is lower than specified x, and we can go upper...
				if (closestXValue < xValue && closest < mValues.size - 1) {
					++closest
				}
			} else if (rounding == DataSet.Rounding.DOWN) {
				// If rounding down, and found x-value is upper than specified x, and we can go lower...
				if (closestXValue > xValue && closest > 0) {
					--closest
				}
			}

			// Search by closest to y-value
			if (!java.lang.Float.isNaN(closestToY)) {
				while (closest > 0 && mValues[closest - 1].x == closestXValue)
					closest -= 1

				var closestYValue = mValues[closest].y
				var closestYIndex = closest

				while (true) {
					closest += 1
					if (closest >= mValues.size)
						break

					val value = mValues[closest]

					if (value.x != closestXValue)
						break

					if (Math.abs(value.y - closestToY) < Math.abs(closestYValue - closestToY)) {
						closestYValue = closestToY
						closestYIndex = closest
					}
				}

				closest = closestYIndex
			}
		}

		return closest
	}
}
```

**Comment by Mayank7119** [comment]
Have you found any solution to this yet?
