### ISSUE TITLE
【BUG】java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by walkthehorizon** [PhilJay/MPAndroidChart#3213]
MP Example DataSet.Java
`    @Override
    public T getEntryForIndex(int index) {
        return mValues.get(index);
    }`
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0,trouble fixes it

**Comment by prometey123** [comment]
I have the same issue

**Comment by MGaetan89** [comment]
This is a duplicate of #2450

**Comment by prometey123** [comment]
I'm using v.3.0.2 "compile 'com.github.PhilJay:MPAndroidChart:v3.0.2'" but the bug is still present

**Comment by RJFares** [comment]
+1

**Comment by almic** [comment]
fixed now in d67ea481af1e8528c617dfd404d0c7827b0134b2
