### ISSUE TITLE
How to make LineChart discontinue ?

### ISSUE THREAD

**Issue by LJ-GH** [PhilJay/MPAndroidChart#3222]
Like this
![default](https://user-images.githubusercontent.com/20895106/27726043-663d54e8-5dab-11e7-8442-c4ee66546a6a.PNG)

**Comment by chengyixuan** [comment]
I have the same demand now. Have you solved it?

**Comment by LJ-GH** [comment]
use muti LineDataSet

**Comment by zjutcmos** [comment]
Can you help me? How do you do it? muti LineDataSet.   the data is always start 0(一月)

**Comment by zjutcmos** [comment]
Can you help me? How do you do it? muti LineDataSet. the data is always start 0(一月)  @chengyixuan  @LJ-GH
