### ISSUE TITLE
theming issue

### ISSUE THREAD

**Issue by dirkam** [PhilJay/MPAndroidChart#323]
I'm using this lib in one of my apps and it works great with Light Theme.
However, when I try to use Dark Theme it still uses the same colors. Is there a way to adjust the bg and text color according to the current theme that is used?

I found here that I can set the label colors and it works, but how can I change the color of the values on the chart and the description?
I also can't find a way to set the background of the chart. setBackgroundColor only sets the color of the surrounding of the chart but not the chart background itself (it's white no matter what I use).
Is there a way to set the color of the center of a Pie Chart?

Thanks

**Comment by patrickjason91** [comment]
Any answer regarding setting of the chart background @PhilJay  In my case also, whenever I set setBackground...(), it only sets the surrounding background, not the surface where the entries are plotted.

**Comment by l4km47** [comment]
> Any answer regarding setting of the chart background @PhilJay? i.e. The default background is white, I want it to be another color. In my case also, whenever I set setBackground...(), it only sets the surrounding background, not the surface where the entries are plotted. Same case as @dirkam

        chart.setDrawGridBackground(false);
