### ISSUE TITLE
Pie chart label overlapping when values are small

### ISSUE THREAD

**Issue by KeyurKba** [PhilJay/MPAndroidChart#3233]
First of all thank you Philipp Jahoda, for making such a great library, I had user your library many times in many projects. 

Recently I have added Pie chart in my application. and values of some portion is very small so labels are overlapping each other, for example as seen in image February and march is overlapping

Is there any solution to show labels outside of circle(Pie). so that they do not overlap each other.
</br>

![capture](https://user-images.githubusercontent.com/24403426/27832428-50138734-60ec-11e7-965f-9ef0a15ca373.PNG)

**Comment by vrendina** [comment]
I am having trouble with overlapping labels even when set outside. When there are two slices that are close to each other there is a lot of overlap. Anyway to prevent this?

```
 PieDataSet dataSet = new PieDataSet(entries, null);
 dataSet.setXValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);
 dataSet.setYValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);
```

<img width="322" alt="screen shot 2017-07-06 at 2 09 41 pm" src="https://user-images.githubusercontent.com/8770713/27926052-12afbbe6-6255-11e7-9acb-a663f3bea63e.png">

**Comment by sg552** [comment]
I also met this problem, any ideas?

**Comment by saeros** [comment]
I'm also having this issue with small values

![overlap](https://user-images.githubusercontent.com/562587/35335690-88fc6064-0116-11e8-8e49-22f45d9e854b.jpg)

**Comment by sg552** [comment]
My final solution is:  don't display the small values.  e.g. only display the values bigger than 5%.

**Comment by martaacarvalho** [comment]
@sg552 how did you do that?
Did you do something like:

if(pieEntry.getvalue<=5){ pieEntry.setLabel(""); }

??

**Comment by dxshindeo** [comment]
dang it, meeting the same problem...

**Comment by LucasXu01** [comment]
I also met this problem, but boss don't want to  hide the small values. how can i do it

**Comment by jwhijazi** [comment]
Kill your Boss :)
just kidding....

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.

**Comment by seanyc4** [comment]
What was the solution to this? Why was it closed?

**Comment by Quentinvk** [comment]
Any news on this issue?

**Comment by walterfenley** [comment]
Use this wrapper it will solve all your problems 
http://www.programmersought.com/article/9994929366/

**Comment by walterfenley** [comment]
> What was the solution to this? Why was it closed?

http://www.programmersought.com/article/9994929366/
