### ISSUE TITLE
Use double values instead of float for Entries

### ISSUE THREAD

**Issue by Alviere** [PhilJay/MPAndroidChart#325]
Hi there!
While using you library I encountered with this: Entry class takes float as value. That means if we have big int (50 million for example) highlighed values become incorrect with +- 10 precision. I think you should use double as values. Or BigDecimal. Charts often uses to represent financial data with big integer numbers, so values must be correct.

**Comment by PhilJay** [comment]
Yep, thats correct.
It's gonna be some work to refactor it all, but definitely worth it.

**Comment by blegoh** [comment]
why this issues was closed ? i have 135573875802.5 and i can't use float

**Comment by mars885** [comment]
@PhilJay Any progress made?

**Comment by Hub2018** [comment]
This problem still exists in 2019 with MPAndroidChart 3.1.0. In our case we have to move our projects to another charting library because of this limitation.

**Comment by wangrui112211** [comment]
> This problem still exists in 2019 with MPAndroidChart 3.1.0. In our case we have to move our projects to another charting library because of this limitation.

which one do you use?I got the same problem

**Comment by wangrui112211** [comment]
> why this issues was closed ? i have 135573875802.5 and i can't use float

I have the same problem,have you solve it?
