### ISSUE TITLE
More charts in one layout

### ISSUE THREAD

**Issue by masko82** [PhilJay/MPAndroidChart#326]
Hi Phil,
is it possible to add 2 or more charts in one layout?
Like a "gridview" of charts...

Thanks

**Comment by PhilJay** [comment]
Yes that is possible, have a loot at this example: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/ListViewMultiChartActivity.java
