### ISSUE TITLE
[BarChart] bars floating above the X-axis

### ISSUE THREAD

**Issue by OumaSyuu** [PhilJay/MPAndroidChart#3263]
Hi, I want to show datas in BarChart. And bars supposed to stand right above the X-axis line without spacing. But there is a gap between bar-bottom and the X-axis line.

**Comment by alexander-jones** [comment]
I am experiencing the same issue. It seems the offset from the x axis is dependent on how many data points  are supplied as part of the BarDataSets. In my app I'm using a CombinedChart and not a BarChart, so I cannot yet comment as to whether it happens generically to all charts containing BartSet(s). Here are a few examples:

![screenshot_2017-08-13-16-13-25](https://user-images.githubusercontent.com/1131110/29254096-bf13cf7a-8042-11e7-90e7-a8f89b13225d.png)
![screenshot_2017-08-13-16-13-32](https://user-images.githubusercontent.com/1131110/29254097-bf188218-8042-11e7-9762-2ea4874036ef.png)
![screenshot_2017-08-13-16-14-05](https://user-images.githubusercontent.com/1131110/29254098-bf1f181c-8042-11e7-8a1b-e4a0d240e64d.png)
![screenshot_2017-08-13-16-14-09](https://user-images.githubusercontent.com/1131110/29254099-bf1f7d02-8042-11e7-8124-487ad8dfb117.png)

If need be I can create a minimal sample that replicates the issue. If all contributes are busy I might take a crack at it after getting acquainted with the source and make a pull request.

**Comment by alexander-jones** [comment]
Also, sorry about the screenshot size, I didn't realize the resolution was so large!

**Comment by DTRAIN** [comment]
I'm having the same issue. Has anyone managed to resolve this?

**Comment by tmelko** [comment]
It appears when you have huge difference between bar values like: 76, 81, 1, 2...etc. It's usual behavior.
No workaround so far...

**Comment by elf-zwolf** [comment]
Did you try this?

```
chart.getAxisLeft().setAxisMinimum(0f);
```

**Comment by tmelko** [comment]
@elf-zwolf @alexander-jones 
Yeah, I did it few days ago. Forget to mention here.
Right way to fix this problem!! Resolved.
