### ISSUE TITLE
why XAxis can not show true data

### ISSUE THREAD

**Issue by youngxhui** [PhilJay/MPAndroidChart#3271]
hi , i use MyXAxisValueFormatter and return values, 

``` java 
public class MyXAxisValueFormatter implements IAxisValueFormatter {

    private List<String> mValues = new ArrayList<>();


    public MyXAxisValueFormatter(List<String> values) {
        this.mValues = values;
    }

    @Override
    public String getFormattedValue(float value, AxisBase axis) {
        return mValues.get((int) value);
    }

}
```

 value's data is four  but chart have five and some data is repeat.

![snipaste_20170718_205903](https://user-images.githubusercontent.com/16971804/28318060-f3c81222-6bfb-11e7-9399-966ceab66c07.png)
![snipaste_20170718_210016](https://user-images.githubusercontent.com/16971804/28318102-1f767238-6bfc-11e7-928e-b7b05faa5e4f.png)

How should i solve？
thanks 😄

**Comment by atentis** [comment]
I am having a similar issue... 

My xaxis date are supposed to be: 
7-13-17
7-14-17
7-17-17
7-18-17
7-19-19

This is what is showing on the graph:
![image](https://user-images.githubusercontent.com/8903400/28376190-1a02f290-6c6f-11e7-9209-c6c6c6d19227.png)

Any help would be appreciated,

**Comment by atentis** [comment]
This worked for me. 

xAxis1.setCenterAxisLabels(false);
xAxis1.setGranularity(1f);

https://stackoverflow.com/questions/43027652/mpandroidchart-xaxis-values-not-corresponding-to-data-values

**Comment by youngxhui** [comment]
@atentis  thanks。 This worked for me too。 👍
