### ISSUE TITLE
How to add inner padding in LineChart

### ISSUE THREAD

**Issue by gzw19931217** [PhilJay/MPAndroidChart#3274]
Hi PhilJay:
gratituding your lib help mine work, but I meet a confuse, I add x offset by "setVisibleXRange" method, make range size greater than data size, but in this way I can't scroll chart.
![tim 20170719155152](https://user-images.githubusercontent.com/15139302/28356645-6623a7ec-6c9b-11e7-9407-1a1c2ffe7365.jpg)
how can I set this format and can scroll it.

**Comment by rahulparihar09** [comment]
Did you find any solution?

**Comment by VinsonGuo** [comment]
yes, I solved it, just draw a invisible line after the last entry.

**Comment by almic** [comment]
You should set the visible X range to be smaller, check the [docs](https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport)
