### ISSUE TITLE
I don't need YAxis and XAxis - Top, how do I get rid of the left, Top, right margins of the diagram?

### ISSUE THREAD

**Issue by AmbitChen** [PhilJay/MPAndroidChart#3279]
I don't need YAxis and XAxis - Top, how do I get rid of the left, Top, right margins of the diagram?

**Comment by joaosardinha** [comment]
how did you do it?

**Comment by csbenz** [comment]
Would like to know too

**Comment by csbenz** [comment]
Worked with `chart.setViewPortOffsets(0F, 0F, 0F, 0F)`
