### ISSUE TITLE
Multiple Y scales in LineChart

### ISSUE THREAD

**Issue by Bishalsingh** [PhilJay/MPAndroidChart#329]
Hey. First of all, thanks a loads for such a wonderful Library for free. Does this Library Support Multiple Y scales in Line Chart??? I mean with different labels on both instead of single. Can we use the concept of overlay with some transparent background ??

**Comment by PhilJay** [comment]
Not supported on the latest release, but on my local commit it already works.
Going to be in the next update!

**Comment by Bishalsingh** [comment]
aww. Thanks. I will eagerly be waiting for the new release.

**Comment by Bishalsingh** [comment]
can you kindly say me when new update will be available?. I am towards the
ending of my project using your great library and this is the only thing
remaining in my project. Please do reply. Thanks

**Comment by PhilJay** [comment]
Not exactly sure. 2-3 weeks, probably even a little sooner than that. However, the dual y-axis festure is already working. Also in the example app.

**Comment by Bishalsingh** [comment]
Yeah, It's working like a charm. But using this beta jar, will it still support all the codes that it have supported before?. I mean you have commented that still pie chart and other charts are still to be done.

**Comment by Bishalsingh** [comment]
@PhilJay hey, My project currently have linechart(dual Y-Axis), Piechart, and BarChart. So, Using this beta version is there going to be any bug. Kindly reply soon. I am in a rush. Thanks
