### ISSUE TITLE
MarkerView offset

### ISSUE THREAD

**Issue by jfabrix101** [PhilJay/MPAndroidChart#330]
First of all compliment for your fantastic library

The latest built version (jar version 1.7.4) has different signature for methods getXOffset and getYOffset for class com.github.mikephil.charting.utils.MarkerView
(float instead of int as in the source code)

But the real problem is that are completaly ignored, the custom marker view is always displayed in the bottom right corner

Is the built version more updated than the source code ? What i should use ?
Thanks in advance

**Comment by warptrosse** [comment]
I had the same problem. Fast workaround override "draw" method
```
@Override
public void draw(Canvas canvas, float posx, float posy)
{
    // take offsets into consideration
    posx += getXOffset();
    posy += getYOffset();

    // translate to the correct position and draw
    canvas.translate(posx, posy);
    draw(canvas);
    canvas.translate(-posx, -posy);
}
```

**Comment by PhilJay** [comment]
Im not sure what the issue is here but I made some changes to the `MarkerView` for the next update. Maybe it will work then :-)
