### ISSUE TITLE
Real Time Combined Chart

### ISSUE THREAD

**Issue by Whem** [PhilJay/MPAndroidChart#3305]
I have a little problem with real time combined chart by MPAndroidChart. I had two different chart and it works in two single chart, but i would like to merge to one. The main problem is that there is nothing in the graph, when values incoming. I see ,that the references are okay.

Here is my code:
`private void IntialcombinedChart(){
    mChart = (CombinedChart) findViewById(R.id.chartFetalandToco);
    mChart.setDescription("");
    mChart.setNoDataText("No data yet");
    mChart.setDrawGridBackground(false);

    mChart.setTouchEnabled(true);
    mChart.setDragEnabled(true);
    mChart.setScaleEnabled(true);
    mChart.setDrawGridBackground(false);

    mChart.setVisibleXRangeMaximum((float)10);

    XAxis x1 = mChart.getXAxis();
    x1.setDrawGridLines(false);
    x1.setAxisMaxValue(1200);
    x1.setAvoidFirstLastClipping(true);

    YAxis y1 = mChart.getAxisLeft();
    y1.setAxisMaxValue(255);
    y1.setAxisMinValue(0);
    y1.setDrawGridLines(true);

    YAxis y12 = mChart.getAxisRight();
    y12.setEnabled(false);

    cData = new CombinedData();

    cData.setData(new LineData());
    cData.setData(new ScatterData());
    mChart.setData(cData);
    mChart.invalidate();
}

`public ScatterDataSet createFetalSet(){
    ScatterDataSet set = new ScatterDataSet(null,"Fetal");
    set.setScatterShapeSize(7.5f);
    set.setDrawValues(false);
    set.setValueTextSize(10f);
    set.setDrawValues(false);
    set.setColor(ColorTemplate.COLORFUL_COLORS[2]);
    set.setAxisDependency(YAxis.AxisDependency.LEFT);
    return  set;
}
 private LineDataSet createTocoSet(){
    LineDataSet set = new LineDataSet(null,"Toco");
    set.setDrawCircles(false);
    set.setDrawCubic(true);
    set.setDrawValues(false);
    set.setColor(ColorTemplate.COLORFUL_COLORS[3]);
    set.setAxisDependency(YAxis.AxisDependency.LEFT);
    return  set;

}`
 public void AddFetalEntry(float sinValue){
    CombinedData data = mChart.getData();
    if (data != null) {
        LineDataSet dataSetGraphA = (LineDataSet) data.getDataSetByIndex(0);
        ScatterDataSet dataSetGraphB = (ScatterDataSet) data.getDataSetByIndex(1);

        if (dataSetGraphA == null) {
            dataSetGraphA = createTocoSet();
            data.addDataSet(dataSetGraphA);
        }
        if (dataSetGraphB == null) {
            dataSetGraphB = createFetalSet();
            data.addDataSet(dataSetGraphB);
        }

        data.addXValue("");

        data.addEntry(new Entry(sinValue, dataSetGraphA.getEntryCount()), 0);

        data.addEntry(new Entry(sinValue, dataSetGraphB.getEntryCount()), 1);

        data.notifyDataChanged();

        // let the chart know it's data has changed
        mChart.notifyDataSetChanged();
        mChart.invalidate(); // refresh

        mChart.setVisibleXRangeMaximum(2000);

        //int valueCount = data.getXValCount();
        mChart.moveViewToX(data.getXValCount() - 2000);
    }
}`

I think I wrote a good code, but it does not work. I try so many way to solave this, but I cant. I will be happy when to same value could appear on graph.

I hope, you could help me.

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
