### ISSUE TITLE
HorizontalBarChar not correctly drawn with setAxisMinimum(0)

### ISSUE THREAD

**Issue by prouland** [PhilJay/MPAndroidChart#3307]
Hello,

I tried to display a little horizontal bar chart with MPAncroidChart.

I achieve to display this, which is very close of what I want to achieve:
![bar-chart-1](https://user-images.githubusercontent.com/1228173/28923080-03a5d072-785d-11e7-8fec-5b7d5ba39b20.png)

I just need to display the whole bars (from zero) to make it done. So I add this line after all options I wrote:
`        barChart.getAxisRight().setAxisMinimum(0);`

The result is below:
![bar-chart-2](https://user-images.githubusercontent.com/1228173/28923084-057d4664-785d-11e7-912e-d2bcf536f19f.png)

As you can see, the axis and the gris are redrawn properly. But not the bars :/
I tried to manually notify each BarData, BarDataSet or BarChart, or invalidate it, but not of those redraw the bar to match the new axis.

Did I miss something ?

**Comment by EvgeniyShilov** [comment]
Have the same issue with YAxis and LineChart
From documentation: "Customizations that affect the value range of the axis need to be applied before setting data for the chart."
But this advice does not help, cause i put
`chart.getAxisRight().setAxisMinimum(0);`
next to findViewById()

**Comment by prouland** [comment]
Yes thank you.

I found the same solution in the meantime :-)

Maybe drawing the chart might not consider the disabled axis.
