### ISSUE TITLE
Allow drawing LineChart with 0 offset (no padding)

### ISSUE THREAD

**Issue by OnlyInAmerica** [PhilJay/MPAndroidChart#331]
I'd love to have full-bleed graphs (without having to fork over a one-line change :))

![mpandroidchart-margins](http://i.imgur.com/C8Q0QEx.png)

While we can set `Chart#setOffsets(0, 0, 0, 0);` it seems that BarLineChartBase enforces a minimum offset of [11dp](https://github.com/PhilJay/MPAndroidChart/blob/2de56406b571d8b4f3f2189147b76764aefb0f08/MPChartLib/src/com/github/mikephil/charting/charts/BarLineChartBase.java#L366). Perhaps I'm missing something?

Anyway, all I'm trying to say is I Love your work. Much thanks. :+1:

**Comment by vbauer** [comment]
:+1:

**Comment by PhilJay** [comment]
The latest commit: https://github.com/PhilJay/MPAndroidChart/commit/74c4c166a5483fd18ec4bf25b9f103197a13dc9b allows this.

**Comment by AndreiD** [comment]
your_chart.setViewPortOffsets(15f, 15f, 15f, 15f); << put here 0f if you want 0 padding.
