### ISSUE TITLE
大神你好 请问我要是怎么处理默认显示最后的部分

### ISSUE THREAD

**Issue by caifuhao** [PhilJay/MPAndroidChart#3315]

**Comment by caifuhao** [comment]
大神你好 请问我要是怎么处理默认显示最后的部分

**Comment by fengbianyun** [comment]
Legend l = mchat.getLegend();
        l.setEnabled(false);//隐藏图列

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.

Closing old issue. If anyone still has this question please open a new one. (in english)
