### ISSUE TITLE
Can't display draw value on line graph without zoom. Can display the text is visible without zoom?

### ISSUE THREAD

**Issue by parthvora112** [PhilJay/MPAndroidChart#3316]
```
 LineDataSet set2 = new LineDataSet(entries1, "");
        set2.setAxisDependency(YAxis.AxisDependency.LEFT);
        set2.setColor(ContextCompat.getColor(getActivity(), R.color.line_chart));
        set2.setValueTextColor(Color.RED);
        set2.setDrawCircles(true);
        set2.setDrawValues(true);
        set2.setFillColor(Color.RED);
        set2.setHighLightColor(Color.RED);
        set2.setCircleColor(Color.RED);
        set2.setCircleRadius(2.0f);

        set2.setValueTextSize(10f);
        set2.setValueTextColor(Color.BLACK);

        set2.setDrawCircleHole(false);
        set2.setValueFormatter(new ValueFormatter());

```
Without zoom graph - 
![screenshot_4](https://user-images.githubusercontent.com/3677984/29076789-2018edfa-7c74-11e7-9b26-74d6e990a042.png)

Zoom graph -
![screenshot_3](https://user-images.githubusercontent.com/3677984/29076801-2e93a21c-7c74-11e7-9c0c-cee04f332d37.png)

I have set value on graph but can't display without zoom.
But I want without zoom.
Any one can help me

**Comment by hiral101** [comment]
yes i got the solution. just put  combinedChart.setMaxVisibleValueCount(Integer.MAX_VALUE); in your code and enjoy!!!

**Comment by parthvora112** [comment]
wow it is working fine thanks
