### ISSUE TITLE
is possible change XAxis background color?

### ISSUE THREAD

**Issue by susemi99** [PhilJay/MPAndroidChart#3318]
![screenshot 3](https://user-images.githubusercontent.com/1233318/29062710-ad75d698-7c5d-11e7-9be4-d5ea09687824.png)

like this?

**Comment by susemi99** [comment]
sorry, my mistake. it resolve just remove chart background color.

**Comment by gaj-programmer** [comment]
Its possible, I was also working on changing the X-Axis label's background colour, there is no direct API to do this, But i have done like this.

Step1: first extend the XAxisRenderer class and override drawLabels() method.
Step2: In drawLabels() method add this code, before drawLabel(c, label, x, pos, anchor, labelRotationAngleDegrees) method.

**if (i == 0) {
                    Paint rectPaint = new Paint();
                    rectPaint.setColor(context.getResources().getColor(R.color.vitaskin_skin_history_background_color));
                    rectPaint.setStyle(Paint.Style.FILL);
                    c.drawRect(0, (int) mViewPortHandler.contentBottom(), mViewPortHandler.getChartWidth(), mViewPortHandler.getChartHeight(), rectPaint);
               }**
               

> You will get the background color of XAxis labels.
