### ISSUE TITLE
Stacked BarChart

### ISSUE THREAD

**Issue by nicopasso** [PhilJay/MPAndroidChart#333]
Hi,
great library! Very useful but right now I' have some problems.

I'm trying to achieve this:
![grafico_costi_ios](https://cloud.githubusercontent.com/assets/1663205/5977618/b2ac5c8a-a899-11e4-940e-79322764333e.png)

The first bar has 3 sections (green, yellow, purple) stacked one above the other. Is it possible to stack the values of one chart like the first image? I didin't find a property in BarChart to do this.
I try to plot the bars with the same index but this is not what I want.

Thanks
Nico

**Comment by MGaetan89** [comment]
Have you look at this example?
https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/StackedBarActivity.java

**Comment by nicopasso** [comment]
Thanks! 
Now the values are correct but the colors aren't.

Here's the code:
````
float[] values = new float[3];
ArrayList<Integer> colors = new ArrayList<Integer>();
for (int i =0 - 1; i < 3; i++) {
      values[i] = 1000.0;
      colors.add(Color.parseColor(singleColor)); //singleColor is a different color for every step of the for
}
BarEntry entry = new BarEntry(values, 0);
yVals.add(entry);
BarDataSet barDataSet = new BarDataSet(yVals, "Values");
barDataSet.setColors(colors);
....
....
````

The chart has a value of 3000, which is correct, but the all stack is coloured with the last color added to the array.

**Comment by PhilJay** [comment]
In the code you posted, you are providing the same color (`singleColor`) for each part of the stacked-bar.
You need to provide different colors.
