### ISSUE TITLE
XValueText font color in Pie Chart not changing

### ISSUE THREAD

**Issue by smw7156** [PhilJay/MPAndroidChart#3333]
Hi, I am creating Pie Chart using MPAndroidCharts Library. Everything went well, just one problem i m facing regarding ValueTextColor

![chart_whole](https://user-images.githubusercontent.com/16005377/29207480-e6ce57e2-7ea3-11e7-8e0c-05a83e70e78a.png)

![chate_part](https://user-images.githubusercontent.com/16005377/29207487-ef4952f0-7ea3-11e7-83cf-e3fee5e4b5b5.png)

XValuesLabel are coming in White font Color, and YValueLabel in Black fontColor.
I want both of it in black color, but somehow setValueTextColor() is not making any impact in XValuesLabel

  ` Log.d("PIECHART dataset", "addDataSet started");
    ArrayList<PieEntry> yEntrys = new ArrayList<>();
    ArrayList<String> xEntrys = new ArrayList<>();

    for(int i = 0; i < yData.length; i++){
        if(yData[i]>0) {

            switch(i){
                case 0:
                    yEntrys.add(new PieEntry(yData[i], "banana"));
                    break;
                case 1:
                    yEntrys.add(new PieEntry(yData[i], "guava"));
                    break;
                case 2:
                    yEntrys.add(new PieEntry(yData[i], "apple"));
                    break;
                case 3:
                    yEntrys.add(new PieEntry(yData[i], "pineapple"));
                    break;
                case 4:
                    yEntrys.add(new PieEntry(yData[i], "mango"));
                    break;
                case 5:
                    yEntrys.add(new PieEntry(yData[i], "papaya"));
                    break;
                case 6:
                    yEntrys.add(new PieEntry(yData[i], "dates"));
                    break;
                default : ;
            }

        }
    }
    //create the data set

    pieDataSet = new PieDataSet(yEntrys, "");
    pieDataSet.setSliceSpace(2f);
    pieDataSet.setValueTextSize(15f);
    pieDataSet.setValueTextColor(Color.RED);/* this line not working */
    pieDataSet.setSelectionShift(10f);
    pieDataSet.setValueLinePart1OffsetPercentage(80.f);
    pieDataSet.setValueLinePart1Length(1f);
    pieDataSet.setValueLinePart2Length(0.9f);
    pieDataSet.setXValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);
    //pieDataSet.setYValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);
    
    //add colors to dataset
    ArrayList<Integer> colors = new ArrayList<>();
    colors.add(Color.rgb(156,254,230));
    colors.add(Color.rgb(159,185,235));
    colors.add(Color.rgb(143,231,161));
    colors.add(Color.rgb(160,239,136));
    colors.add(Color.rgb(200,246,139));
    colors.add(Color.rgb(176,219,233));
    colors.add(Color.rgb(183,176,253));
    
    pieDataSet.setColors(colors);

    ///// disabling chart legend
    pieChart.getLegend().setEnabled(false);

    Log.d("PIECHART dataset2", xEntrys.size()+" ");

    //create pie data object
    PieData pieData = new PieData(pieDataSet);
    pieData.setValueTextColor(Color.RED);/* only YValue color changes, Xvalues remains white*/
    pieData.setValueFormatter(new valueFormat());
    pieChart.setData(pieData);
    //pieDataSet.notifyDataSetChanged();
    //pieChart.invalidate();`

please help. Thanks

**Comment by mtotschnig** [comment]
You can change the XValueText color with:
        ((PieChartRenderer) chart.getRenderer()).getPaintEntryLabels().setColor(Color.GREEN);
