### ISSUE TITLE
add the unit  of x-coordinate and y-coordinate for BaseLineChart

### ISSUE THREAD

**Issue by xyczero** [PhilJay/MPAndroidChart#334]
Firstly,thank you for your library,it benefits me  a lot.

When I use it in practice,I find it not support that drawing the unit  of x-coordinate and y-coordinate for the chart which is inherited from BaseLineChart. Then I try to do it. 

The following picture which is drawed by a red circle is my result.

![screenshot](http://7u2jsw.com1.z0.glb.clouddn.com/githubMDChart_issue.png)

Can I pull request it to the master ? I want to contribute for MPAndroidChart.

**Comment by PhilJay** [comment]
Thank you for willing to contribute! I very much appreciate a feature like that! Unfortunately this feature has already been completed by myself and is just not published yet.

Best regards,
Phil

**Comment by whatsthebeef** [comment]
@PhilJay Is this featured published and if so how do you use it?

**Comment by hwjoy** [comment]
Practical feature. Why has not been published?

**Comment by 603530013** [comment]
[#1960](https://github.com/PhilJay/MPAndroidChart/issues/1960)
