### ISSUE TITLE
LineChart Fill issue

### ISSUE THREAD

**Issue by quinnovator** [PhilJay/MPAndroidChart#3340]
I have implemented the LineChart into my android application. When filling the chart, the fill often goes to the wrong side of the line. How can I change which side the fill is on? It occurs with both the standard and Cubic plotting modes. 

![image](https://user-images.githubusercontent.com/15806582/29242768-d43ccbf0-7f60-11e7-981f-ffebe103fa1f.png)

See the chart for automobile exports as an example.

**Comment by simopr** [comment]
how did you fill that chart? Show the code
