### ISSUE TITLE
打包签名后，显示柱状图，饼状图，折线图的动画怎么会失效呢？

### ISSUE THREAD

**Issue by Achenglove** [PhilJay/MPAndroidChart#3344]

**Comment by gb18030** [comment]
#图表库防混淆
-keep public class com.github.mikephil.charting.animation.* {
    public protected *;
}

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.

Closing old issue. If anyone still has this question please open a new one. (in english)
