### ISSUE TITLE
CombinedChart unable to drawIcons

### ISSUE THREAD

**Issue by jlo1** [PhilJay/MPAndroidChart#3346]
I'm able to use `drawIcons` and pass the drawable through fine when using `LineChart` and `ScatterChart`. But when I try to draw a line chart via the `CombinedChart`, the icons won't appear. Any way to work around this? Or fix this?

Thanks!

**Comment by jlo1** [comment]
nvm. issue on my end. Thanks!

**Comment by janvv** [comment]
Problem still there, any plans for that?
