### ISSUE TITLE
Possibility to set a fixed bar-width

### ISSUE THREAD

**Issue by mxylayout** [PhilJay/MPAndroidChart#335]
How to make the bar width fixed for barchart  whatever  how many bars in chart.
like this chart 
![image](https://cloud.githubusercontent.com/assets/10346229/6019185/b20bed26-abd8-11e4-8261-f491063812d7.png)
this is too width:
![image](https://cloud.githubusercontent.com/assets/10346229/6019237/4c6f25fe-abd9-11e4-88c1-e69ef97feb63.png)

Thanks in advance.

**Comment by ben04** [comment]
I'd also like to know that :+1:

**Comment by PhilJay** [comment]
A feature like that would cause bars to overlap once all space is used up.
Is that really a feature you want?

**Comment by mxylayout** [comment]
yes , as you might expect : to set a fixed bar-width whatever how many bars there.

**Comment by Manhazito** [comment]
I'de love to have that feature, too!

**Comment by vaiiibhav** [comment]
yes i also require that functionality

**Comment by maxbax** [comment]
Yes please, I also require it

**Comment by bita147** [comment]
How to set fixed width of bar chart??

**Comment by vaiiibhav** [comment]
take the count of number of bars you want to display , and multiply it by 100 and set that width of barchart , it works awesome

**Comment by bita147** [comment]
No width() method of chart!!

**Comment by bita147** [comment]
there is seminimumwidth() but it doesn't work

**Comment by vaiiibhav** [comment]
barChart.getLayoutParams().height=100*count;
where count is the number of bars to be displayed

**Comment by chrishunterkiller** [comment]
i also require it

**Comment by hijamoya** [comment]
```barDataSet.setBarSpacePercent(((float) (COUNT   - barData.getXValCount()) / (float) COUNT) * 100f);```
Where COUNT is the number of x labels which your ideal bar width shows on the chart

**Comment by vnd-ranga** [comment]
You can reduce the spacing between the bars that will automatically increase the width of bars.

BarDataSet set_a = new BarDataSet(vals, "Set A");
set_a.setBarSpacePercent(50f);

**Comment by PhilJay** [comment]
I just added a new feature that allows specifying the bar width with respect to the x-axis range. The new feature is currently on a separate branch and will be available as soon as v3.0.0 of this library is out.

**Comment by lschuetze** [comment]
@PhilJay What is the API for this change? I browsed the commits around 19 Jun but did not find anything related. We are currently at 3.0.0-beta1. All documented ways (documentation as of Stackoverflow and older issues) use non existent API.

**Comment by sarathraj-coder** [comment]
@PhilJay i have an issue with graph . when i set the data.setBarWidth(20f); i can see graphs are overlapped . how i can avoid this  overlapping and set it can be scrollabe in x-axis without zoom . and all x-labels should be visible 
![screenshot_20160821-190714](https://cloud.githubusercontent.com/assets/7710739/17837530/4e59252e-67d3-11e6-9d9a-57300d6ffe7e.png)

**Comment by JeffZane** [comment]
Yes please, I also require it

**Comment by fxjiao** [comment]
@JeffZane 
BarData.setBarWidth  works for me .  but..  actually..  I have never compared the v3.x.x with the previous ones

**Comment by tmac010sjh** [comment]
`BarData.setBarWidth()` set the **ratio** of barWidth to totalWidth.
so if you want to set barWidth like 10px ,  
you can calculate  the ratio dynamically according to the  bar count.

e.g.

```
int barWidth = 10px;

int count = 7; // bar count on each screen, not the total count

int totalWidth = screenWidth;// i used screen width dirctly

float ratio = barWidth * count / totalWidth;

BarData.setBarWidth(ratio); //finally set the ratio
```

**Comment by mrldroid** [comment]
> `BarData.setBarWidth()` set the **ratio** of barWidth to totalWidth.
> so if you want to set barWidth like 10px ,
> you can calculate the ratio dynamically according to the bar count.
> 
> e.g.
> 
> ```
> int barWidth = 10px;
> 
> int count = 7; // bar count on each screen, not the total count
> 
> int totalWidth = screenWidth;// i used screen width dirctly
> 
> float ratio = barWidth * count / totalWidth;
> 
> BarData.setBarWidth(ratio); //finally set the ratio
> ```

How about Group Bar?

**Comment by galaxi76** [comment]
> `BarData.setBarWidth()` set the **ratio** of barWidth to totalWidth.
> so if you want to set barWidth like 10px ,
> you can calculate the ratio dynamically according to the bar count.
> 
> e.g.
> 
> ```
> int barWidth = 10px;
> 
> int count = 7; // bar count on each screen, not the total count
> 
> int totalWidth = screenWidth;// i used screen width dirctly
> 
> float ratio = barWidth * count / totalWidth;
> 
> BarData.setBarWidth(ratio); //finally set the ratio
> ```

This works! The only problem now the bars are too spread out, making the spaces between the bars enormous.

**Comment by kalator** [comment]
Hi, what I have done was that I defined how much bars did I want in the plot, say 15. Then I would create "dummy empty bars" that would fill up to that number 15. When my bars overgrow 15, they would shrink, but it looks much better than those huge bars, when there is only a few of them. The only issue I have is that I cannot get rid of the BarEntry label showing the value of the bar for those dummy empty bars (see the zeros within the attached image). Does anybody have any idea how to get rid of them? Thank you in advance. 
![bars](https://user-images.githubusercontent.com/23026500/89529372-e86e0700-d7ec-11ea-89fb-e629c12642a7.png)

**Comment by samigehi** [comment]
I did the same and added remaining empty bars. it works!
