### ISSUE TITLE
柱状图柱子之间间距设置为0 ,相当于紧紧连接在一起，怎么设置？

### ISSUE THREAD

**Issue by dykdykdyk** [PhilJay/MPAndroidChart#3371]

**Comment by dykdykdyk** [comment]
a

**Comment by MashirosBaumkuchen** [comment]
![image](https://user-images.githubusercontent.com/12267364/29661119-a3849472-88f5-11e7-8d85-6cc1e01c4347.png)

just barChart.getBarData().setBarWidth(1f);
