### ISSUE TITLE
与Okhttp的io冲突

### ISSUE THREAD

**Issue by OkamiyGit** [PhilJay/MPAndroidChart#3378]
你好，我导入你的依赖库，之后在部分手机（华为H30-c00）中启动app奔溃了，报错“java.lang.NoClassDefFoundError: okio.Buffer”，感觉是和Okhttp的io冲突，求指点

**Comment by YifanWang1021** [comment]
He said that after he imported the lib, it was crashed on mobile of Huawei (H30-c00)  when the app launched. The exception was "java.lang.NoClassDefFoundError: okio.Buffer". He thought that there was a conflict between Okhttp and this lib.

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one. (in english)
