### ISSUE TITLE
Bar entry values are not displayed in HorizontalBarCharts

### ISSUE THREAD

**Issue by lucadln** [PhilJay/MPAndroidChart#3380]
A horizontal bar chart was creating using the following code:

        
        // Initialize bar chart
        HorizontalBarChart barChart = (HorizontalBarChart) findViewById(R.id.chart);

        // Create bars
        ArrayList<BarEntry> points = new ArrayList<>();
        points.add(new BarEntry(0f, 80));
        points.add(new BarEntry(1f, 50));
        points.add(new BarEntry(2f, 20));
        points.add(new BarEntry(3f, 60));
        points.add(new BarEntry(4f, 80));
        points.add(new BarEntry(5f, 100));
        points.add(new BarEntry(6f, 50));
        // Add bars to a bar set
        BarDataSet barSet = new BarDataSet(points, "Tenses");
        // Create a BarData object and assign it to the chart
        BarData barData = new BarData(barSet);
        // Display it as a percentage
        barData.setValueFormatter(new PercentFormatter());
        barChart.setData(barData);

        barSet.setDrawValues(true);

        barChart.invalidate();`

When running the application, the values corresponding to each bar are not displayed.

![demo_photo](https://user-images.githubusercontent.com/27018423/29748386-d2a71f38-8b1e-11e7-81a8-f11a827de263.png)

The expected result was to show values like in this picture:

![e1bpe](https://user-images.githubusercontent.com/27018423/29748508-e95485ac-8b20-11e7-8f32-4a3ec44632fd.jpeg)

This was tested using the MPAndroidChart:v3.0.2.

**Comment by lucadln** [comment]
Not sure how but after working a little bit longer on it I got it working:

`
        // Initialize bar chart
        HorizontalBarChart barChart = (HorizontalBarChart) findViewById(R.id.chart);

        obtainAllScores(scores);

        // Create bars
        ArrayList<BarEntry> yvalues = new ArrayList<>();
        yvalues.add(new BarEntry(0f, percentages[0]));
        yvalues.add(new BarEntry(1f, percentages[1]));
        yvalues.add(new BarEntry(2f, percentages[2]));
        yvalues.add(new BarEntry(3f, percentages[3]));
        yvalues.add(new BarEntry(4f, percentages[4]));
        yvalues.add(new BarEntry(5f, percentages[5]));
        yvalues.add(new BarEntry(6f, percentages[6]));

        // Create a data set
        BarDataSet dataSet = new BarDataSet(yvalues, "Tenses");
        dataSet.setDrawValues(true);

        // Create a data object from the dataSet
        BarData data = new BarData(dataSet);
        // Format data as percentage
        data.setValueFormatter(new PercentFormatter());

        // Make the chart use the acquired data
        barChart.setData(data);

        // Create the labels for the bars
        final ArrayList<String> xVals = new ArrayList<>();
        xVals.add("Present");
        xVals.add("Pres. Continuous");
        xVals.add("Simple Past");
        xVals.add("Past Perfect");
        xVals.add("Conditional");
        xVals.add("Cond. Perfect");
        xVals.add("Future");

        // Display labels for bars
        barChart.getXAxis().setValueFormatter(new IndexAxisValueFormatter(xVals));

        // Set the maximum value that can be taken by the bars
        barChart.getAxisLeft().setAxisMaximum(100);

        // Bars are sliding in from left to right
        barChart.animateXY(1000, 1000);
        // Display scores inside the bars
        barChart.setDrawValueAboveBar(false);

        // Hide grid lines
        barChart.getAxisLeft().setEnabled(false);
        barChart.getAxisRight().setEnabled(false);
        // Hide graph description
        barChart.getDescription().setEnabled(false);
        // Hide graph legend
        barChart.getLegend().setEnabled(false);

        // Design
        dataSet.setColors(ColorTemplate.VORDIPLOM_COLORS);
        data.setValueTextSize(13f);
        data.setValueTextColor(Color.DKGRAY);

        barChart.invalidate();
`

**Comment by lucadln** [comment]
Ok, one more update: if I zoom out horizontally the values are shown. 

This can also be seen in the pictures anove actually. In the first picture the bars are spanned starting from the left side of the screen. In the second picture the 0.0% makes the bars start a little to the right. 

Any solutions for this?

**Comment by lucadln** [comment]
Another issue similar to mine: https://github.com/PhilJay/MPAndroidChart/issues/3212

**Comment by lucadln** [comment]
Ok, I figured it out.

So the strangest part was that the labels were shown if one of the following conditions was met:
1. I zoomed out manually when using the application OR
2. One of the values in my chart was 0.

My chart contained labels with a maximum value of 100:
![noscores](https://user-images.githubusercontent.com/27018423/29993626-489b85ee-8fc5-11e7-8b8e-5bfff8c8611f.png)

...but I noticed that the bars were cropped (i.e. the minimum shown value was 50). When having one value with 0 or when zooming out then the whole graph would be displayed and hence also its labels:
![scores](https://user-images.githubusercontent.com/27018423/29993634-7f538a3c-8fc5-11e7-928f-7715b98a413a.png)

The solution which did it is just adding the axis minimum. In this way, no matter what the scores are, the bars were fully displayed. So the solution for me was just:
`barChart.getAxisLeft().setAxisMaximum(100);
        barChart.getAxisLeft().setAxisMinimum(0);`

And now the result is:
![result](https://user-images.githubusercontent.com/27018423/29993652-02ddc138-8fc6-11e7-923c-33e4f1ebc0f6.png)

I will close this issue now.

**Comment by Emad-Alhattami** [comment]
How delete precent?

**Comment by Emad-Alhattami** [comment]
I need gust number with out precent % ?

**Comment by 6vedant** [comment]
I am able to display the entry values, but its font size is very less. How to increase the font size?

**Comment by MarcellHarmaci** [comment]
@6vedant In Kotlin I used this, where dataSet was the `BarDataSet`
`dataSet.valueTextSize = 14f`
In Java it must be something like
`dataset.setValueTextSize(14.0f)`

**Comment by meassadkhan** [comment]
> I need gust number with out precent % ?

  valueFormatter = object : ValueFormatter() {
                override fun getFormattedValue(value: Float): String {
                    return String.format("%2.2f", -1 * value)
                }
            }
            I am making my value negative by multiplying with "-1"
            Here you can remove percent from your value by string remove function,
