### ISSUE TITLE
Data filtering broken on purpose, unhandled NPE crashes ensue

### ISSUE THREAD

**Issue by FranciscoEstevez** [PhilJay/MPAndroidChart#339]
BarLineCharBase.java Line 173

        if (mFilterData) {
            mData = getFilteredData();

            Log.i(LOG_TAG, "FilterTime: " + (System.currentTimeMillis() -
                    starttime) + " ms");
            starttime = System.currentTimeMillis();
        } else {
            mData = getData();
            // Log.i(LOG_TAG, "Filtering disabled.");
        }

getFilteredData() is commented out and returns a null.  Also, getData() is a redundant proxy to itself, with no caching of prefiltered data, which makes the whole block meaningless.

It's part of the example app, so while I understand it may be an unimplemented feature this is not the best way to handle it, a silent UnimplementedMethodException would be desirable.

**Comment by PhilJay** [comment]
Yep, good point.
-> next update :-)
