### ISSUE TITLE
Cubic Line Graph with different colors

### ISSUE THREAD

**Issue by santhosh285** [PhilJay/MPAndroidChart#3394]
Thanks for this awesome library.
By the way, can you please help me on a cubical graph(CUBIC_BEZIER) with different color according to the y value ?

Example like the below image:

![capture](https://user-images.githubusercontent.com/31067866/29916581-ce5e8baa-8e5c-11e7-9f24-2a914fa358d9.PNG)

**Comment by santhosh285** [comment]
I have achieved some what like the below image. Once again thanks for this awesome library. Great work. 
![device-2017-08-29-1254022](https://user-images.githubusercontent.com/31067866/30732382-f06d8b6c-9f8f-11e7-9d50-e5a3c1231b76.png)

**Comment by 5eeman** [comment]
@santhosh285 Hi, can you please post some example or solution?

**Comment by Prosquid1** [comment]
This can be achieved using a LinearGradient, you move along the x-axis only 
See [this link](https://github.com/PhilJay/MPAndroidChart/issues/3584#issuecomment-1263132765)
