### ISSUE TITLE
如何设置点击数据点显示图标，不是像例子里面会显示出所有数据点的图标

### ISSUE THREAD

**Issue by siliconvallley** [PhilJay/MPAndroidChart#3395]
如何设置点击数据点显示图标（icon），不是说的Markview，需求是点击数据点同时显示icon和MarkView
但是这样是显示出所有的图标（icon），我需要的是只显示我点击之后的数据点的icon
for (IDataSet set : mlinechart.getData().getDataSets()){
            //set.setDrawIcons(!set.isDrawIconsEnabled());
            set.setDrawIcons(false);
        }
        mlinechart.invalidate();

**Comment by siliconvallley** [comment]
![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)
![Image of Yaktocat](C:\Users\huidingc\Desktop\$1G[3ZR_SZ0)~A`FYHTE~_C.png)

**Comment by siliconvallley** [comment]
![GitHub Logo](C:\Users\huidingc\Desktop\$1G[3ZR_SZ0)~A`FYHTE~_C.png)
Format: ![Alt Text](url)

**Comment by siliconvallley** [comment]
![line](C:\Users\huidingc\Desktop\line.png)
Format: ![Alt Text](C:\Users\huidingc\Desktop\line.png)

**Comment by siliconvallley** [comment]
![line](https://user-images.githubusercontent.com/18340690/29964953-6037429c-8f3e-11e7-957a-f32d21e06073.png)

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.

Closing old issue. If anyone still has this question please open a new one. (in english)
