### ISSUE TITLE
Bar Chart with Various Bar Widths

### ISSUE THREAD

**Issue by tommyjackson** [PhilJay/MPAndroidChart#3398]
Hi, I'm trying to create a bar chart that has time on the x axis, and I want the bars to be created based on a certain time interval which can and will vary. For example, one bar will span the width of 0 to 8 seconds, the next from 8 to 10, and the next from 10 to 30. Is this possible using this library? Everything I have tried or seen online uses bars with the same width. Let me know, thanks!

**Comment by tommyjackson** [comment]
In case anyone else wanted to do this, I was able to get it done by using a LineChart. For each bar you want create a new DataSet having two entries, each with a different x value but both with the same y value. Then fill underneath to create the appearance of a bar. Works great.

**Comment by YuriyBereguliak** [comment]
Hello @tommyjackson , what about click listeners for those datasets, are they works right?
