### ISSUE TITLE
y轴出现多个0

### ISSUE THREAD

**Issue by kcjian** [PhilJay/MPAndroidChart#3410]
当数据很小时，y重复多个0，有时y显示为0011223这样，请问该怎么去掉这个问题

**Comment by kcjian** [comment]
![image](https://github.com/kcjian/kcjian.github.io/blob/master/css/images/IMG_0214.JPG)

**Comment by kcjian** [comment]
[https://github.com/kcjian/kcjian.github.io/blob/master/css/images/IMG_0214.JPG](url)

**Comment by q805699513** [comment]
数值太小了，其实是0点几，你自定义一下y轴显示的数值，保留小数点后几位

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.

Closing old issue. If anyone still has this question please open a new one. (in english)
