### ISSUE TITLE
X轴设置群组数据时，我X轴设置了7组数据，树状图数据有7组，但是X轴下面只显示6个，而且位置跟上面的数据位置不对齐，这是什么原因呢？

### ISSUE THREAD

**Issue by Achenglove** [PhilJay/MPAndroidChart#3413]
![image](https://user-images.githubusercontent.com/26593441/30269986-92a65722-971d-11e7-8cfe-57491bc79ab8.png)

**Comment by Sunxb** [comment]
刚开始看这个库 x轴的数据是怎么样设置的 ... 他的新版本的demo里面貌似没有涉及群组数据设置x轴  ~ 谢谢

**Comment by Achenglove** [comment]
@Sunxb 
![image](https://user-images.githubusercontent.com/26593441/31007740-1d8c4a6c-a534-11e7-9cec-dbf31fec424b.png)

**Comment by Sunxb** [comment]
@Achenglove 这不是设置的数据嘛 ?  我想问的是你的图中红色框里的09.05 09.11这种是怎么写上去的 .. 我看他demo里面最后面有一个groupBars会把之前设置的全覆盖掉了..

**Comment by Achenglove** [comment]
@Sunxb 
![image](https://user-images.githubusercontent.com/26593441/31011132-bdb9e610-a53f-11e7-96f6-f4168095cb3e.png)

**Comment by Achenglove** [comment]
@Sunxb 但是有个问题就是群组数据多的时候，X轴数据就对不上了

**Comment by Sunxb** [comment]
@Achenglove 这个数据设置我看到了 ... 就是这个value为啥是从-1开始 .. 然后好像默认是-1到5 .. 我也不太清楚  ...你说的这个数据对不上的问题我还没有碰到 .. 我刚开始看这个库.. 等过段时间碰到再跟你具体的交流 ~

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.

Closing old issue. If anyone still has this question please open a new one. (in english)
