### ISSUE TITLE
请问下怎样实现蜡烛图最少一个一个的滚动，而不会出现最左和最右的两个蜡烛图被遮挡部分的问题

### ISSUE THREAD

**Issue by q805699513** [PhilJay/MPAndroidChart#3419]
请问下怎样实现蜡烛图最少一个一个的滚动，而不会出现最左和最右的两个蜡烛图被遮挡部分的问题
I would like to ask how to realize the candle diagram at least one scroll, and not the most left and the right two candle diagram of the blocked part of the problem

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.

Closing old issue. If anyone still has this question please open a new one. (in english)
