### ISSUE TITLE
Horizontal Bar Chart draw error

### ISSUE THREAD

**Issue by NeoRaidenX** [PhilJay/MPAndroidChart#342]
Hi, first of all thank you for create a very useful and pretty library and share all your knowledge and support all android developers with this. I have a problem with the Horizontal Bar Chart it doesn't draw correctly the bars. Something that I saw it's that the second bar starts drawing after the first one finished. Maybe this helps you to find the error. 

This is the code I use to create the Bar Chart:

private void initBarChart() {
        mBarChart.setDrawYValues(true);
        mBarChart.setDrawValueAboveBar(true);
        mBarChart.setDescription("Descripcion");
        mBarChart.set3DEnabled(false);
        mBarChart.setPinchZoom(false);
        mBarChart.setDrawHorizontalGrid(true);
        mBarChart.setDrawVerticalGrid(false);
        mBarChart.setValueTextSize(10f);
        mBarChart.setDrawBorder(false);

        ArrayList<String> xVals = new ArrayList<>();
        ArrayList<BarEntry> yVals = new ArrayList<>();
        ArrayList<BarDataSet> dataSets = new ArrayList<>();

        for(int i = 0; i < 5; i++) {
            xVals.add("Compañia " + i);
            float val = (float) (Math.random() * 100);
            yVals.add(new BarEntry(val, i));
        }

        BarDataSet set = new BarDataSet(yVals, "DataSet");
        set.setBarSpacePercent(35f);
        dataSets.add(set);

        BarData data = new BarData(xVals, dataSets);
        mBarChart.setData(data);
    }

Maybe I'm doing something wrong. 

![10969125_10204865641653644_2080252119_o](https://cloud.githubusercontent.com/assets/3501629/6062760/c381c3f6-ad17-11e4-8ba1-81d3bb5f8e16.jpg)

**Comment by PhilJay** [comment]
Yep, the HorizontalBarChart still has a lot of issues.
I will work on fixing them in the next library-update.
