### ISSUE TITLE
怎么让这个控件在左侧显示文字类型，现在全都叠在一起了

### ISSUE THREAD

**Issue by wudaotiantian** [PhilJay/MPAndroidChart#3428]

**Comment by wudaotiantian** [comment]
https://camo.githubusercontent.com/2ec281e0ac3013076bff1c3ac00d8d6de372d7a4/68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d5043686172742f6d61737465722f73637265656e73686f74732f686f72697a6f6e74616c5f62617263686172742e706e67

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.

Closing old issue. If anyone still has this question please open a new one. (in english)
