### ISSUE TITLE
Pie Chart Text Position

### ISSUE THREAD

**Issue by xEnigma** [PhilJay/MPAndroidChart#344]
Hello there!

Is there a possibility to show the text values outside of the piechart, e.g. like here?
http://www.telerik.com/help/aspnet-ajax/media/htmlchart-piechart-simple-example.png

The problem is when the values get really small they are not readable anymore.
![screenshot_2015-02-09-21-02-18](https://cloud.githubusercontent.com/assets/9255325/6114560/4e4c1ca4-b09f-11e4-9e88-c7bee1969dad.png)

And I have another small problem. When I select one value in this piechart, the other one suddenly gets grey.
![screenshot_2015-02-09-21-02-58](https://cloud.githubusercontent.com/assets/9255325/6114615/9379f044-b09f-11e4-94ed-f38264e61dc4.png)

Normally the right one is blue, but when I touch the left value it gets transparent.

Thanks for your help!

**Comment by PhilJay** [comment]
Thats currently not possible, you will have to find a way to implement it yourself.

Best regards,
Phil

**Comment by chapliny** [comment]
hi  xEnigma , do you find a  way  to implement?

**Comment by cyph3rcod3r** [comment]
Use a custom render java class extend Mp Char't default renderer class, Override the method drawDataset copy the code from extended class inside the method. Draw the text according to your need! You cannot expect everything from PhilJay :p
