### ISSUE TITLE
setViewPortOffsets doesn't update the offsets right away

### ISSUE THREAD

**Issue by hruslowkirill** [PhilJay/MPAndroidChart#3441]
Hello, I stumbled upon a problem when aligning two graphs together. When new data arrives I need to set same offset two both graphs.

This is how I do it
```
        float offsetLeft = barChart.getViewPortHandler().offsetLeft();
        float offsetRight = barChart.getViewPortHandler().offsetRight();
        float offsetTop = barChart.getViewPortHandler().offsetTop();
        float offsetBottom = barChart.getViewPortHandler().offsetBottom();

        candleChart.setViewPortOffsets(offsetLeft, offsetTop, offsetRight, offsetBottom);
        candleChart.invalidate();
        candleChart.notifyDataSetChanged();
```
This code is executed after data is set to the graphs. 
But the graph is not redrawn. When I touch the candleChart then it redraws with proper offsets and stays that way.

Is it a bug in the library or am I doing something wrong?
as you can see invalidate doesn't really help.
Thank you.

**Comment by circassian8** [comment]
I am experiencing the same issue and tried the same things, no success...

**Comment by hruslowkirill** [comment]
Well if somebody is still interested in how to solve this, I found a dirty but working solution.
After you set the viewport you need to highlight a value.
```
 Handler handler = new Handler();
                handler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        if (this.graphData.size()>0)
                              candleChart.highlightValue(this.graphData.size() / 2, 0, true);
                    }
                }, 1); // 1ms delay
```
When Value is highlighted the offsets are displayed right. "Invalide" happens...
But it need to be done in 1 ms. God knows why. 

I know this is the worst solution ever, but it suits my needs, until the developer fixes the bug.

**Comment by waterdaan** [comment]
Cool

`Handler handler = new Handler(); 
                handler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        if (this.graphData.size()>0)
                              candleChart.invalidate();
                    }
                }, 1); // 1ms delay`

Also works for me

**Comment by RomanTourdyiev** [comment]
Nothing of the above solutions did work for me.
What worked for me is:

chart.post(new Runnable() {
            @Override
            public void run() {
                chart.highlightValue(entries.get(entries.size()-1).getX(), entries.get(entries.size()-1).getY(), 0, true);
            }
        });

**Comment by yh603797823** [comment]
what worked for me is:
chart.post(new Runnable() {
                    @Override
                    public void run() {
                        int mLabelHeight = chart.getXAxis().mLabelHeight;
                        barLineChartBase.setViewPortOffsets(0, 0, 0, mLabelHeight * 2);
                        **barLineChartBase.postInvalidate();**insteadof invalidate()
                    }
                });

**Comment by almic** [comment]
Please stop adding code to this issue, it is getting a little out of hand. Make absolutely sure you are doing things in the right order, because `chart.invalidate()` should always be called LAST, after you notify the data has changed!
