### ISSUE TITLE
"Locking" the x-axis in realtime plotting

### ISSUE THREAD

**Issue by AlewLoos** [PhilJay/MPAndroidChart#3457]
Hello there! First of all, thanks for AWESOME library. It really helps me out!

I am not sure if this is an issue or a noob question, but I dont know how to "lock" x-axis on a realtime plot. 

I'll be more clear with that example: Let's assume a real-time application, like temperature measurement. It takes ~ 10 samples for second and plots them to a LineChart. I've set the "mChart.setVisibleXRangeMaximum(100);". 

After ten seconds, it fills the screen and "starts pulling graph to the right" 

When it reaches to 101 points, there's a way to clean all the previous plotted points and start over de plotting from left to right?

Sorry if this is a dumb question! I really didnt find anything about wet.

Best regards,

Alexandre

**Comment by Jetz72** [comment]
As far as I'm aware, there's no automatic functionality for this. You could manually achieve it by moving the view manually when you add the first point that would go outside your range. I think mChart.moveViewToX will allow you to do that.

**Comment by AlewLoos** [comment]
Thanks, it worked! :)
