### ISSUE TITLE
Long Press call back and data of that view

### ISSUE THREAD

**Issue by sanketauti** [PhilJay/MPAndroidChart#3458]
Hi Phil,
        First of all thanks for this awesome library, My question is I don't know its an issue or not to get long press event callback and it's data for a particular bar in a bar graph, pie in a pie chart and other graphs also.
simply how to get the long press and data of any bar or pie or point.

Any clue how to accomplish this?

**Comment by sanketauti** [comment]
find the solution myself

**Comment by praveenb** [comment]
If any body interested on PieChart long press event.

you need to use `OnChartGestureListener` interface

then set Chart Gesture listener as below
`chart.setOnChartGestureListener(this);`

then in onChartLongPressed method, you may code like this below to get the highlighted Pie after long press event.
```
@Override
    public void onChartLongPressed(MotionEvent e) {
       Highlight h = chart.getHighlightByTouchPoint(e.getX(), e.getY());
        Log.i("VAL SELECTED",  "Value: " + e.getY() + ", index: " + h.getX() + ", DataSet index: " + h.getDataSetIndex());
        Highlight[] highlights= new Highlight[1];
        highlights[0] =h;
        chart.highlightValues(highlights);
        chart.invalidate();
    } 
```

Hope it helps somebody.
Thanks @PhilJay
