### ISSUE TITLE
PieChart color disappear.

### ISSUE THREAD

**Issue by Rao-Arsalan** [PhilJay/MPAndroidChart#3459]
When i touch on PieChart the pieChart color automatically disappear.
here is my code snippest.

 pieChart = (PieChart) v.findViewById(R.id.piechart);
        arrayList = new ArrayList<Entry>();
        arrayList.add(new Entry((float) totalExpense, 0));
        arrayList.add(new Entry((float) totalIncome, 1));
        pieDataSet = new PieDataSet(arrayList, "");
        ArrayList<String> labels = new ArrayList<String>();
        labels.add("Total Expense");
        labels.add("Total Income");
        data = new PieData(labels, pieDataSet); // initialize Piedata
        data.setValueTextSize(12.0f);
        pieChart.setData(data);
        ArrayList<Integer> colors = new ArrayList<>();
        colors.add(Color.rgb(188, 50, 50));// this color is red for TotalExpense
        colors.add(Color.rgb(74, 188, 50));// this color is green for TotalIncome
        pieDataSet.setColors(colors);
        data.setValueFormatter(new ValueFormatter() {
            @Override
            public String getFormattedValue(float value, Entry entry, int dataSetIndex, ViewPortHandler viewPortHandler) {
                return FormatterAmount.getAmountsWithInsertedCommas((double)value) ;
            }
        });
        pieChart.setDescription("");
        
--------------------------------
the problem is when i touch on Expense portion on pieChart the color of Income which is green is disappear.
how to fix it ? i'll try on stackoverflow and google but can't find desired solution.

**Comment by yusufnacir** [comment]
Can you try this ?
pieChart .setHighlighter(null);

**Comment by Rao-Arsalan** [comment]
i fixed it by using 
 pieChart.setHighlightPerTapEnabled(false);
