### ISSUE TITLE
A Suggestion regarding PieRadarChartTouchListener.java 

### ISSUE THREAD

**Issue by infinitec123** [PhilJay/MPAndroidChart#347]
Hi Phil,

Thanks for the awesome library. However one suggestion, if you may want to consider ...

I think In PieRadarChartTouchListener.java file 

if (distance > mChart.getRadius()) {
            // if no slice was touched, highlight nothing
            mChart.highlightValues(null);
            mLastHighlight = null;
}

is better off if 

if (distance > mChart.getRadius()) {
            // if no slice was touched, highlight nothing

          if (CHART_IS_ALREADY_HIGHLIGHTED){
            mChart.highlightTouch(null);
         } else {
            mChart.highlightValues(null);
         }
            mLastHighlight = null;
}

Because if a pie was in highlighted state, you are unhighlighting it. So I think it we could inform the listeners it would have helped.

Thank You.

**Comment by PhilJay** [comment]
Thank you for your suggestion, but are you using an older version of the library? This should already be possible!

Best regards,
Phil
