### ISSUE TITLE
Release apk - Proguard - No animations?

### ISSUE THREAD

**Issue by raulfdezhdez** [PhilJay/MPAndroidChart#348]
Hi!
First of all, thank you for your work. Excellent library.

I have one little problem when exporting a signed apk with proguard. When opening chart views, animations are not happening.
If I turn off proguard, the animations start to work again.

I am testing in two Android 5.0.1 phones (Nexus 6 and Samsung S5)

Any idea?

Thanks in advance.

**Comment by PhilJay** [comment]
Pffff. I honestly do not have the slightest idea why this is (obviously) not working.
Does anyone else know something?

**Comment by Bishalsingh** [comment]
The trick is the fact that the methods called by the PropertyValuesHolder are either set* or get*, so the ProGuard rules to keep such methods are:

void set*(***);
*** get*();
So, based on that, if your animated target is only one of a few classes, add this per animated target class:

-keep class my.package.MyClass {
    void set*(***);
    *** get*();
}
If all your targets extend some base class, you can add a single rule to save them all:

-keep class * extends my.package.MyBaseClass {
    void set*(***);
    *** get*();
}

**Comment by Bishalsingh** [comment]
Can I see your Logcat @raulfdezhdez ??
In mine case the problem was due to incompatibility issues and i fixed it as:
 ActionBarSherlock was failing to find a constructor "a(Activity,int)" using reflection.
 ProGuard doesn't (can't) know this and has removed the constructor, because it appears unused in the code. You therefore have to explicitly tell ProGuard to keep it:

-keepclassmembers class * extends com.actionbarsherlock.ActionBarSherlock {
    <init>(android.app.Activity, int);
}

**Comment by raulfdezhdez** [comment]
Mine is not generating any error log signing the apk or at runtime, and I am not using SherlockBar.
I have tried with the typical proguard rules, but no luck.
At the moment it is not a big problem and I am not in a hurry, so I will keep trying and if I find any clue o solution I will post it.
Thanks for the great library!

**Comment by MarcSalvat** [comment]
I had the same problem. I excluded the library from proguard adding this to proguard rules:

-dontwarn com.github.mikephil.**
-keep public class com.github.mikephil.** {
  public protected *;
}

I'm not sure if there's a better approach but this works

**Comment by romangromov** [comment]
@MarcSalvat this way MPAndroidChart become not obfuscated by proguard

**Comment by mesropd** [comment]
Here is the reason. Original ChartAnimator.java contains this code
```java
    mAnimatorY = ObjectAnimator.ofFloat(this, "phaseY", 0f, 1f);
    /**
     * This gets the y-phase that is used to animate the values.
     *
     * @return
     */
    public float getPhaseY() {
        return mPhaseY;
    }

    /**
     * This modifys the y-phase that is used to animate the values.
     *
     * @param phase
     */
    public void setPhaseY(float phase) {
        mPhaseY = phase;
    }
```

And this is a decompiled code, after proguard
```java
package com.github.mikephil.charting.a;

import android.animation.ObjectAnimator;
import android.animation.ValueAnimator.AnimatorUpdateListener;
import android.annotation.SuppressLint;
import android.os.Build.VERSION;

@SuppressLint({"NewApi"})
public class a
{
  protected float a = 1.0F;
  protected float b = 1.0F;
  private ValueAnimator.AnimatorUpdateListener c;
  private ObjectAnimator d;
  
  public a() {}
  
  public a(ValueAnimator.AnimatorUpdateListener paramAnimatorUpdateListener)
  {
    this.c = paramAnimatorUpdateListener;
  }
  
  public float a()
  {
    return this.a;
  }
  
  public void a(int paramInt)
  {
    if (Build.VERSION.SDK_INT < 11) {
      return;
    }
    this.d = ObjectAnimator.ofFloat(this, "phaseX", new float[] { 0.0F, 1.0F });
    this.d.setDuration(paramInt);
    this.d.addUpdateListener(this.c);
    this.d.start();
  }
  
  public float b()
  {
    return this.b;
  }
}
```

You see that here is missing property "phaseX", thats why animation doesn't work. So we need to add only this line in the pro-guard file 
```
-keep public class com.github.mikephil.charting.animation.* {
    public protected *;
}
```

**Comment by mesropd** [comment]
@PhilJay , you know where used hard coded class names or property names, that can be used via reflection, and need to update the Readme file for pro-guard use, to keep only that classes, no need to keep whole library

**Comment by BulatMukhutdinov** [comment]
The solution provided by @mesropd doesn't work anymore. Is the only option to keep the whole com.github.mikephil.charting?

**Comment by dlghrms95** [comment]
-dontwarn com.github.mikephil.**
-keep class com.github.mikephil.charting.animation.ChartAnimator{*;}

it works for me :)

**Comment by dlghrms95** [comment]
> The solution provided by @mesropd doesn't work anymore. Is the only option to keep the whole com.github.mikephil.charting?

-dontwarn com.github.mikephil.**
-keep class com.github.mikephil.charting.animation.ChartAnimator{*;}

it works for me :)

**Comment by dlghrms95** [comment]
> The solution provided by @mesropd doesn't work anymore. Is the only option to keep the whole com.github.mikephil.charting?

-dontwarn com.github.mikephil.**
-keep class com.github.mikephil.charting.animation.ChartAnimator{*;}

it works for me
try this :)

**Comment by Raziur306** [comment]
> > The solution provided by @mesropd doesn't work anymore. Is the only option to keep the whole com.github.mikephil.charting?
> 
> -dontwarn com.github.mikephil.** -keep class com.github.mikephil.charting.animation.ChartAnimator{*;}
> 
> it works for me try this :)

Worked for me 😁
