### ISSUE TITLE
LineChart显示不全

### ISSUE THREAD

**Issue by AiTheAnswer** [PhilJay/MPAndroidChart#3483]
![screenshot_2017-10-10-16-37-47 1](https://user-images.githubusercontent.com/21075364/31378025-98c2160c-addc-11e7-95a5-88005bbc096a.png)

**Comment by AiTheAnswer** [comment]
@Pitel

**Comment by AiTheAnswer** [comment]
@mikemonteith

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.

Closing old issue. If anyone still has this question please open a new one. (in english)
