### ISSUE TITLE
Chart Longpress Problem

### ISSUE THREAD

**Issue by triggetry** [PhilJay/MPAndroidChart#349]
I think this issue --> https://github.com/PhilJay/MPAndroidChart/issues/188 <-- should be **re-opened**, because the problem still exists, and there is only a workaround for this issue by setting an empty ``OnChartGestureListener`` to the chart.

Tested on a Samsung Galaxy Tab Pro 8.4, with version ``1.7.4`` and ``1.7.5``:
Reproducible:

1. Display data
2. Zoom, either with pinch or double tap
3. Scroll

This triggers the following debug text:
``"Longpress. Resetting zoom and drag, adjusting chart bounds to screen."``
and jumps back to full zoom out.

**Comment by PhilJay** [comment]
Totally annoying :-D
Now fixed and will be published in next release!
