### ISSUE TITLE
How to show the X-labels on the marker view in LineChart ??

### ISSUE THREAD

**Issue by qazwsx984** [PhilJay/MPAndroidChart#3490]
![test1](https://user-images.githubusercontent.com/32700852/31505590-d41ce66a-afa7-11e7-8027-b730a0752e09.jpg)
My markerview x-vaule gets.But is not my Formatter vaule. 
How to get X-lable?
My x-label vaule use numMap method to put.

**Comment by Mydesire** [comment]
![image](https://user-images.githubusercontent.com/12956945/32236929-89dd5ac0-be9e-11e7-8f0b-e3413626e616.png)
