### ISSUE TITLE
折线图中高亮线的高度怎么设置,点击高亮以后显示数据.

### ISSUE THREAD

**Issue by TunNanfengyan** [PhilJay/MPAndroidChart#3525]
![default](https://user-images.githubusercontent.com/28496556/32133295-9262cc0a-bc07-11e7-86d7-8c9e5e59fa4b.png)

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.

Closing old issue. If anyone still has this question please open a new one. (in english)
