### ISSUE TITLE
How to just offset the lines drawn?

### ISSUE THREAD

**Issue by wsgaowxh** [PhilJay/MPAndroidChart#3537]
Hi,When I use LineChart, I need to offset the drawn lines, but I did not find a way to offset lines only,Is there a way to achieve it?
Thanks

**Comment by Mydesire** [comment]
Can you provide more intentions I do not understand

**Comment by wsgaowxh** [comment]
@Mydesire I want to offset the green lines and red lines so that they are not near the edge of the screen
![screenshot_20171102-092350](https://user-images.githubusercontent.com/23549836/32305507-eab37abe-bf43-11e7-85b7-3c96b2e28856.png)

**Comment by Mydesire** [comment]
You can try to set this property of the setViewPortOffsets()

I don't know whether you want the effect

public void setViewPortOffsets(final float left, final float top,
                                   final float right, final float bottom) {

        mCustomViewPortEnabled = true;
        post(new Runnable() {

            @Override
            public void run() {

                mViewPortHandler.restrainViewPort(left, top, right, bottom);
                prepareOffsetMatrix();
                prepareValuePxMatrix();
            }
        });
    }

**Comment by wsgaowxh** [comment]
@Mydesire I tried this method, but it can not achieve the effect I want, but still very grateful to you
