### ISSUE TITLE
Bar inside listView title

### ISSUE THREAD

**Issue by thomaslc66** [PhilJay/MPAndroidChart#354]
Hi, 
i would like to know if there is a posibility to put a title for each row of the listview.

Not after de barChart but before.

![mpandroidcharttitle](https://cloud.githubusercontent.com/assets/9827392/6203803/e8f5990e-b533-11e4-86c9-444bfef827fb.PNG)

**Comment by PhilJay** [comment]
Not directly from the chart. However, it should not be that hard to adjust the layout of each `ListView` item and add an additional `TextView` for the title.

**Comment by thomaslc66** [comment]
Yeah, the problem is that the list is a new ArrayList<BarData> so i can't add someting else than barData.

**Comment by thomaslc66** [comment]
Ok i've done it. I Add a one more List to my Adapter and set it to the holder depending on the position. But it could be a good thing to implement this feature. A title in a graph can be usefull. Cheers

**Comment by nbau21** [comment]
Thomas,

Can you post a snippet of code for this workaround? I'm trying to implement titles in a list of charts in my project.

**Comment by thomaslc66** [comment]
Yeah sorry... For late answer. I ve done the same thing. Add a holder title in my viewholder. Then in my case i put a arraylist in parameter and I take index arraylist at position and set text for the title. If you need à snippet tell me...
