### ISSUE TITLE
How to disable animation when clicking on PieChartEntries

### ISSUE THREAD

**Issue by val66** [PhilJay/MPAndroidChart#3565]
Hello,

First thanks for the library, it really helps ! I read the documentation but i didn't find a way to disable animation when clicking on PieChartEntries, i mean the scale effect which made the slice bigger.

I know it is possible to setTouchEnabled to false, but i want to keep using OnChartValueSelectedListener. Do anyone know a workaround ?

Thanks

**Comment by val66** [comment]
I disabled highlight on my PieDataSet and PieData but even if i did disable animations the result was not really good because the select part became all white...
Actually the library can't disable that kind of animation and can't allow multi selection for PieChart so i paused my project for now :)

**Comment by ardagoc** [comment]
use  chart.isHighlightPerTapEnabled = false
