### ISSUE TITLE
Is it possible to have multiple y-axis background colors for a chart?

### ISSUE THREAD

**Issue by dowi** [PhilJay/MPAndroidChart#357]
please see here

http://stackoverflow.com/questions/28585267/is-it-possible-to-have-multiple-y-axis-background-colors-for-a-mpandroidchart-ch

thanks a lot for a great library

**Comment by PhilJay** [comment]
Unfortunately currently not possible.
Have a look here: http://stackoverflow.com/a/28638938/1590502

Best regards,
Phil
