### ISSUE TITLE
How Can I change color of entry recently added

### ISSUE THREAD

**Issue by PallaviTapkir** [PhilJay/MPAndroidChart#3590]
My application collecting multiple points in foreground and background as well and showing it on LineChart.  I want show foreground and background entries with different color. How can I achieve this? Any help will be appreciated.

**Comment by gcasar** [comment]
You can color each LineDataSet diferently. Do so with `dataSet.setColors( color )`. Be sure to resolve your color first, it needs to be a 32bit RGBA :)
