### ISSUE TITLE
STEPPED LineDataSet mode first data point fill interpolation bug

### ISSUE THREAD

**Issue by gcasar** [PhilJay/MPAndroidChart#3593]
When rendering a line graph with DataSet.Mode set to STEPPED, using a fill and stroke the fill won't match the stroke.

![screen shot 2017-11-20 at 17 28 00](https://user-images.githubusercontent.com/2477157/33029268-7039d416-ce18-11e7-8af1-077bc6d01d94.png)

Steps to reproduce:
```
dataSet.setFillColor(getResources().getColor(R.color.blue));
dataSet.setFillAlpha(125);
dataSet.setColors(getResources().getColor(R.color.blue));
dataSet.setLineWidth(1f);
```

**Comment by Jimdem** [comment]
+1

**Comment by kamilj** [comment]
+1

**Comment by tatocaster** [comment]
+1 Still exits. 

@PhilJay  any ideas when it will be resolved?

**Comment by hugobrock** [comment]
+1

**Comment by almic** [comment]
Should be fixed in the latest commit, until a new release is created you can just use the latest `-SNAPSHOT` version like this

```gradle
dependencies {
    implementation 'com.github.philjay:mpandroidchart:-SNAPSHOT'
}
```
