### ISSUE TITLE
remove gaps around chart

### ISSUE THREAD

**Issue by TeleginS** [PhilJay/MPAndroidChart#3594]
hi! i can not remove gaps. i have CUBIC_BEZIER chart
        ArrayList<Entry> yVals3 = new ArrayList<Entry>();

        for (int i = 0; i < 30; i++) {
            float mult = 30;
            float val = (float) (Math.random() * mult) + 500;
            yVals3.add(new Entry(i, val));
        }
        LineDataSet dataSet = new LineDataSet(yVals3, ""); // add entries to dataset
        dataSet.disableDashedLine();
        dataSet.disableDashedHighlightLine();
        dataSet.setColor(Color.GRAY);
        dataSet.setFillColor(Color.GRAY);
        dataSet.setDrawFilled(true);
        dataSet.setFillAlpha(255);
        dataSet.setValueTextColor(Color.BLACK);
        dataSet.setMode(LineDataSet.Mode.CUBIC_BEZIER);
        dataSet.setCircleRadius(0);

        LineData lineData = new LineData(dataSet);
        lineData.setValueTextSize(0);
        lineData.setDrawValues(false);

        Legend legend = recentActivityChart.getLegend();
        legend.setEnabled(false);

        YAxis leftAxis = recentActivityChart.getAxisLeft();
        leftAxis.setDrawLabels(false); // no axis labels
        leftAxis.setDrawAxisLine(false); // no axis line
        leftAxis.setDrawGridLines(false); // no grid lines
        leftAxis.disableAxisLineDashedLine();
        leftAxis.removeAllLimitLines();
        leftAxis.disableGridDashedLine();

        YAxis rightAxis = recentActivityChart.getAxisRight();
        rightAxis.setDrawLabels(false); // no axis labels
        rightAxis.setDrawAxisLine(false); // no axis line
        rightAxis.setDrawGridLines(false); // no grid lines
        rightAxis.disableAxisLineDashedLine();
        rightAxis.removeAllLimitLines();
        rightAxis.disableGridDashedLine();

        XAxis xAxis = recentActivityChart.getXAxis();
        xAxis.setDrawLabels(false); // no axis labels
        xAxis.setDrawAxisLine(false); // no axis line
        xAxis.setDrawGridLines(false); // no grid lines
        xAxis.disableAxisLineDashedLine();
        xAxis.removeAllLimitLines();
        xAxis.disableGridDashedLine();

        recentActivityChart.setBackgroundColor(Color.WHITE);
        Description description = new Description();
        description.setTextAlign(Paint.Align.LEFT);
        description.setText("Run");
        description.setPosition(0,0);
        recentActivityChart.setDescription(description);
        recentActivityChart.setData(lineData);
        recentActivityChart.invalidate();
        recentActivityChart.fitScreen();
   
![image](https://user-images.githubusercontent.com/1770370/33060732-fb57f3bc-cee4-11e7-8b29-73792a9c1163.png)

How i can remove it?

**Comment by gcasar** [comment]
The easiest way to achieve this is to call `setViewPortOffsets(0,0,0,0);` in addition to your code above.

You can remove quite a bit of your code by calling `setEnabled(false);` on each axis.

Another way is with `chart.setExtraOffsets(0,0,0,0);` but I'm having trouble getting the chart to recalculate its offsets (`setViewPortOffsets` does this for us).

**Comment by TeleginS** [comment]
Thanks @gcasar! Working well!

**Comment by ntaloventi** [comment]
hi @gcasar , if I implement `setViewPortOffsets(0,0,0,0)`
I am loosing my y right label, cannot remove bottom offset, attached pictures

<img width="539" alt="screen shot 2018-09-29 at 03 27 51" src="https://user-images.githubusercontent.com/1662174/46231884-b6412200-c397-11e8-8509-7414c6846156.png">

Need help remove bottom offset, ty

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.
