### ISSUE TITLE
When I upgraded Android studio3.0.1, I couldn't parse the dependency

### ISSUE THREAD

**Issue by wu781521512** [PhilJay/MPAndroidChart#3597]
Error:Unable to resolve dependency for ':mpcharttest@debug/compileClasspath': Could not resolve com.github.PhilJay:MPAndroidChart:v3.0.2.
<a href="openFile:E:/appSource/TestApp/mpcharttest/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:mpcharttest@debug/compileClasspath&#39;: Could not resolve com.github.PhilJay:MPAndroidChart:v3.0.2.">Show Details</a>

Error:Unable to resolve dependency for ':mpcharttest@debugAndroidTest/compileClasspath': Could not resolve com.github.PhilJay:MPAndroidChart:v3.0.2.
<a href="openFile:E:/appSource/TestApp/mpcharttest/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:mpcharttest@debugAndroidTest/compileClasspath&#39;: Could not resolve com.github.PhilJay:MPAndroidChart:v3.0.2.">Show Details</a>

Error:Unable to resolve dependency for ':mpcharttest@debugUnitTest/compileClasspath': Could not resolve com.github.PhilJay:MPAndroidChart:v3.0.2.
<a href="openFile:E:/appSource/TestApp/mpcharttest/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:mpcharttest@debugUnitTest/compileClasspath&#39;: Could not resolve com.github.PhilJay:MPAndroidChart:v3.0.2.">Show Details</a>

Error:Unable to resolve dependency for ':mpcharttest@release/compileClasspath': Could not resolve com.github.PhilJay:MPAndroidChart:v3.0.2.
<a href="openFile:E:/appSource/TestApp/mpcharttest/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:mpcharttest@release/compileClasspath&#39;: Could not resolve com.github.PhilJay:MPAndroidChart:v3.0.2.">Show Details</a>

Error:Unable to resolve dependency for ':mpcharttest@releaseUnitTest/compileClasspath': Could not resolve com.github.PhilJay:MPAndroidChart:v3.0.2.
<a href="openFile:E:/appSource/TestApp/mpcharttest/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:mpcharttest@releaseUnitTest/compileClasspath&#39;: Could not resolve com.github.PhilJay:MPAndroidChart:v3.0.2.">Show Details</a>

**Comment by nikitamarysoloman** [comment]
Hello iam facing the same issue please help me to fix this issue.
and also have error 
Error:android-apt plugin is incompatible with the Android Gradle plugin.  Please use 'annotationProcessor' configuration instead.
where as iam not able to find where "android-apt plugin" is used , i just commented out  "apply plugin: 'realm-android'" from mpchartexample buil.gradle  not sure is that the right solution

**Comment by nikitamarysoloman** [comment]
wu781521512 kindly help if u fixed this
