### ISSUE TITLE
Stacked Bar not supporting Negative Values. 

### ISSUE THREAD

**Issue by naveen1389** [PhilJay/MPAndroidChart#360]
![image](https://cloud.githubusercontent.com/assets/10599591/6263112/7a505366-b837-11e4-864e-b1982d3d061f.png)

If one of the value is negative , It will not draw both positive and negative values.

Example Code 

mChart.setStartAtZero(false);

ArrayList<BarEntry> yVals1 = new ArrayList<BarEntry>();

        for (int i = 0; i < mSeekBarX.getProgress()+1; i++) {
            float mult = (mSeekBarY.getProgress() + 1);
            float val1 = (float) (Math.random() * mult) + mult / 3;
            float val2 = (float) (Math.random() * mult) + mult / 3;
            float val3 = (float) (Math.random() * mult) + mult / 3;

            yVals1.add(new BarEntry(new float[] {
                     val1, val2, -val3  // One of the value negative
            }, i));
        }

**Comment by PhilJay** [comment]
Yep that is correct, negative values are not yet supported for stacked-barchart.

**Comment by qvouters** [comment]
Hi Philipp

Do you have any idea ,when this option will be implemented?

Thanks !

**Comment by PhilJay** [comment]
Now possible! https://github.com/PhilJay/MPAndroidChart/releases
