### ISSUE TITLE
How can i use setFitBars function via CombinedChart ?

### ISSUE THREAD

**Issue by Shineshyshi** [PhilJay/MPAndroidChart#3601]
Hi, there.
It's awesome library.
I can call `setFitBars()` from BarChart class.
but how can I call `setFitBars()`  via CombinedChart class??
I didn't see this function in CombinedChart class.

Sorry for my english.
Best,

**Comment by happyjosh** [comment]
Are you want to set the bar show fully？I set spaceMin(0.5f) & spaceMax(0.5f) for axis。

**Comment by Shineshyshi** [comment]
@happyjosh Yeah, I also done with this function. Thank you for your reply.
Can you suggest me how can I set the space between each bar? Thank again!
