### ISSUE TITLE
NPE in com.github.mikephil.charting.charts.PieChart.onDraw reports

### ISSUE THREAD

**Issue by tererecool** [PhilJay/MPAndroidChart#3605]
Hello, we are using this library and on Analytics there are some reports of the app crashing because of a NPE inside the lib:
Seen on Sony G3121 Xperia XA1
Android 7.0

NullPointerException (@android.graphics.Canvas:<init>:130) via (@com.github.mikephil.charting.e.m:a:136) FULL TRACE: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isMutable()' on a null object reference at android.graphics.Canvas.<init>(Canvas.java:130) at com.github.mikephil.charting.e.m.a(SourceFile:136) at com.github.mikephil.charting.charts.PieChart.onDraw(SourceFile:126) at android.view.View.draw(View.java:17368) at android.view.View.updateDisplayListIfDirty(View.java:16307) at android.view.View.draw(View.java:17118) at android.view.ViewGroup.drawChild(ViewGroup.java:3890) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676) at android.view.View.updateDisplayListIfDirty(View.java:16299) at android.view.View.draw(View.java:17118) at android.view.ViewGroup.drawChild(ViewGroup.java:3890) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676) at android.view.View.draw(View.java:17380) at android.view.View.updateDisplayListIfDirty(View.java:16307) at android.view.View.draw(View.java:17118) at android.view.ViewGroup.drawChild(ViewGroup.java:3890) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676) at android.view.View.draw(View.java:17380) at android.view.View.updateDisplayListIfDirty(View.java:16307) at android.view.View.draw(View.java:17118) at android.view.ViewGroup.drawChild(ViewGroup.java:3890) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676) at android.view.View.updateDisplayListIfDirty(View.java:16299) at android.view.View.draw(View.java:17118) at android.view.ViewGroup.drawChild(ViewGroup.java:3890) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676) at android.view.View.draw(View.java:17380) at android.support.v4.widget.NestedScrollView.draw(SourceFile:1815) at android.view.View.updateDisplayListIfDirty(View.java:16307) at android.view.View.draw(View.java:17118) at android.view.ViewGroup.drawChild(ViewGroup.java:3890) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676) at android.view.View.updateDisplayListIfDirty(View.java:16299) at android.view.View.draw(View.java:17118) at android.view.ViewGroup.drawChild(ViewGroup.java:3890) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676) at android.view.View.updateDisplayListIfDirty(View.java:16299) at android.view.View.draw(View.java:17118) at android.view.ViewGroup.drawChild(ViewGroup.java:3890) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676) at android.view.View.updateDisplayListIfDirty(View.java:16299) at android.view.View.draw(View.java:17118) at android.view.ViewGroup.drawChild(ViewGroup.java:3890) at android.support.v4.widget.DrawerLayout.drawChild(SourceFile:1366) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676) at android.view.View.draw(View.java:17380) at android.view.View.updateDisplayListIfDirty(View.java:16307) at android.view.View.draw(View.java:17118) at android.view.ViewGroup.drawChild(ViewGroup.java:3890) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676) at android.view.View.updateDisplayListIfDirty(View.java:16299) at android.view.View.draw(View.java:17118) at android.view.ViewGroup.drawChild(ViewGroup.java:3890) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676) at android.view.View.updateDisplayListIfDirty(View.java:16299) at android.view.View.draw(View.java:17118) at android.view.ViewGroup.drawChild(ViewGroup.java:3890) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676) at android.view.View.updateDisplayListIfDirty(View.java:16299) at android.view.View.draw(View.java:17118) at android.view.ViewGroup.drawChild(ViewGroup.java:3890) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676) at android.view.View.updateDisplayListIfDirty(View.java:16299) at android.view.View.draw(View.java:17118) at android.view.ViewGroup.drawChild(ViewGroup.java:3890) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676) at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:792) at android.view.View.draw(View.java:17380) at com.android.internal.policy.DecorView.draw(DecorView.java:778) at android.view.View.updateDisplayListIfDirty(View.java:16307) at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:661) at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:667) at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:775) at android.view.ViewRootImpl.draw(ViewRootImpl.java:3188) at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2981) at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2569) at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1462) at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6965) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907) at android.view.Choreographer.doCallbacks(Choreographer.java:709) at android.view.Choreographer.doFrame(Choreographer.java:644) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893) at android.os.Handler.handleCallback(Handler.java:836) at android.os.Handler.dispatchMessage(Handler.java:103) at android.os.Looper.loop(Looper.java:203) at android.app.ActivityThread.main(ActivityThread.java:6361) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by wouterdevos** [comment]
I'm also experiencing a number of these crashes. Is there any update on this?

**Comment by ablenesi** [comment]
We are experiencing the issue with the latest version of the library v 3.0.0
**Session information:**
- Date: 2018-10-04T15:05:00Z
- OS Version: 7.0
- Device: P9 Plus
- RAM Free: 20.8%
- Disk Free: 64.6%

**Logs:** [pie-chart-renderer-crash.txt](https://github.com/PhilJay/MPAndroidChart/files/2449499/pie-chart-renderer-crash.txt)

**Comment by almic** [comment]
Should be fixed in the latest commit, until a new release is created you can just use the latest `-SNAPSHOT` version like this

```gradle
dependencies {
    implementation 'com.github.philjay:mpandroidchart:-SNAPSHOT'
}
```
