### ISSUE TITLE
How have pie chart display label different from the  passed values for y axis?

### ISSUE THREAD

**Issue by digimatrix** [PhilJay/MPAndroidChart#361]
I want to display a piechart with y axis labels different from the values passed? For eg: Consider a pie chart with three X values. I would like to pass the values for Y as 88,6,6. But the y labels should display 112,1,1. Is this possible?

**Comment by nbau21** [comment]
Perhaps do a calculation to change the displayed values to what you want? Showing a different value than the passed Y value kind of ruins the point of having a chart.

**Comment by PhilJay** [comment]
You can check out the `ValueFormatter` interface.
With that you can basically return anything you want as a label for the values.

Also check out #162

**Comment by digimatrix** [comment]
Thanks a lot. It worked fine.
