### ISSUE TITLE
points inside circle/Ellipse

### ISSUE THREAD

**Issue by antoniohbmonteiro** [PhilJay/MPAndroidChart#3612]
Have any way to draw a circle and put points inside it?

like that:
![sem titulo](https://user-images.githubusercontent.com/21144063/33335380-12392a0a-d454-11e7-9b6a-fec094a59893.png)

**Comment by almic** [comment]
I'm really sorry no one answered your question, and I just got notified that you closed the issue. If it helps, you should be able to use a `CombinedChart` and use a Bubble/ Scatter chart combo.

Check out this example activity to see how you can do this: [`CombinedChartActivity`](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/main/java/com/xxmassdeveloper/mpchartexample/CombinedChartActivity.java)
