### ISSUE TITLE
3.x以后的版本  想要设置一个条形的数据组,怎样设置数据组对应的X轴的值

### ISSUE THREAD

**Issue by qishengtao** [PhilJay/MPAndroidChart#3613]
在2.x版本的时候  想要设置数据组  是这样的代码
ArrayList<IBarDataSet> dataSets = new ArrayList<IBarDataSet>();
		dataSets.add(set1);
		dataSets.add(set2);
		dataSets.add(set3);
BarData data = new BarData(xVals, dataSets);
mChart.setData(data);
//其中  xVals  就是对应的X轴的值的list     dataSets是对应的三个组

但是3.x以后BarData没有这个构造方法啦,请问用什么方法替换

**Comment by Weightang** [comment]
mChart.xAxis.setValueFormatter()

**Comment by realchen** [comment]
请问下 后来解决了吗？

**Comment by NotMyYida** [comment]
自己写一个实现 IAxisValueFormatter 的类，format方法返回的就是X轴上的值，假设类名为 CustomValueFormatter然后像二楼说的 mChart.setValueFormatter(customValueFormatter)，就行了

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.

Closing old issue. If anyone still has this question please open a new one. (in english)
