### ISSUE TITLE
Customise Icons of Legend

### ISSUE THREAD

**Issue by drd1988on** [PhilJay/MPAndroidChart#3619]
Hi,

could be possible add icons to graphs legend? 
I wants to display legend as dashed line instead of filled rectangles.

Regrds
Divya

**Comment by drd1988on** [comment]
Hi
Using setFormLineDashEffect ,it is possible.

        ```
set2.setFormLineWidth(1f);
        set2.setForm(Legend.LegendForm.LINE);
        set2.setFormLineDashEffect(new DashPathEffect(new float[]{10f, 5f}, 0f));
        set2.setFormSize(15.f);
```
Regards
Divya

**Comment by venusaim23** [comment]
> 

Hey @drd1988on is it possible to set one legend icon as dotted line and the other as solid line? The above solution works for all the icons in Legends
