### ISSUE TITLE
remove nineoldandroids support?

### ISSUE THREAD

**Issue by xanscale** [PhilJay/MPAndroidChart#362]
FACT1 = nineoldandroids is deprecated.

FACT2 = android 2.x are at 7.8 %

I propose to remove the animations on Android 2 and remove nineoldandroids

**Comment by PhilJay** [comment]
Good point. I have now 35 local commits waiting to be used in the next library update.
I will finish the update and also remove nineoldandroids lib asap.

**Comment by PhilJay** [comment]
Nineoldandroids is now removed from the library. Animations are now only possible for API level 11 and higher.
This will be online in the next release.
