### ISSUE TITLE
How to set a fixed x-axis zoom level?

### ISSUE THREAD

**Issue by mrZizik** [PhilJay/MPAndroidChart#363]
I found how to set zoom to barchart, but scale depends on how many xValues are in chart. How to make chart scaled similar in different cases?

**Comment by mrZizik** [comment]
@PhilJay Can you help me, please?

**Comment by PhilJay** [comment]
In the latest version, that is possible via

```java
// limit the number of visible entries
chart.setVisibleXRange(6);
chart.invalidate();
```

**Comment by mrZizik** [comment]
@PhilJay ty, but i made this via 
regChart.setScaleMinima((float) data.getXValCount() / 17f, 1f);
regChart.zoom(-10f,0f,0,0);
