### ISSUE TITLE
PieChart is redrawn when i move from one fragment to another

### ISSUE THREAD

**Issue by Quadriyanney** [PhilJay/MPAndroidChart#3637]
Hello, I'm trying to draw a pie chart for my data on different fragments using a tablayout with a viewPager buh anytime i switch to another tab and go back to the previous one, another chart is drawn on the already existing chart. How can I fix this?

**Comment by StuStirling** [comment]
This sounds like more of an implementation issue. Could you provide where you're populating your data set and reloading it etc?

**Comment by Quadriyanney** [comment]
Yeah, later figured out it was a mistake on my path. Thanks.

**Comment by AlexLutinNoir** [comment]
I had the same problem and my mistake was initializing the data of the chart inside the OnCreateView this caused the redraw of each chart inside the Fragment, my solution was to use a constructor instead, I would initialize my data in my constructor and inside the OnCreateView I would simply call the method to set data, of course all the variables are global inside my Fragment classes, If anyone faced this same problem and didn't find a solution, hope mine works for you.
