### ISSUE TITLE
Display of small values in Y-Axis

### ISSUE THREAD

**Issue by samfemboeck** [PhilJay/MPAndroidChart#3638]
I have set up a **LineChart** in order to show some price data for currencies.
For values that are within the 20 to 20+x range everything works fine. However, for values that are smaller than that it seems like the values are being rounded. It so happens that decimal values around the value 1, e.g. 0.4, 1.5, 0.8, actually display a straight line going through the y-value 1.

Is there any way to fix this?

**Comment by SergeyShustikov** [comment]
You need to convert your values to decimal values and display "as-is". After that when you need display some information about point(for ex. in MarkerView) just convert it back.
