### ISSUE TITLE
Set margin for BarEntries

### ISSUE THREAD

**Issue by mrZizik** [PhilJay/MPAndroidChart#364]
How to set margin_bottom for BarEntries on BarChart?

**Comment by PhilJay** [comment]
You can call 

`yAxis.setSpaceBottom(...);`

**Comment by mrZizik** [comment]
@PhilJay How i can get yAxis?

**Comment by PhilJay** [comment]
Check out the y-axis documentation: https://github.com/PhilJay/MPAndroidChart/wiki/d)-YAxis-(YLabels)

**Comment by mrZizik** [comment]
@PhilJay thanks. You saved me :-)
