### ISSUE TITLE
How to set a draw icons for line chart to my selected position ?

### ISSUE THREAD

**Issue by ismailtosun** [PhilJay/MPAndroidChart#3644]

**Comment by Sum41forever** [comment]
find the selected data in your dataset then use `setDrawIcon`s method
![71227165846](https://user-images.githubusercontent.com/18468976/34376652-ee61197c-eb27-11e7-81ea-cab4731ecf81.png)

```java
 List<ILineDataSet> sets = mChart.getData() .getDataSets();
 for (ILineDataSet iSet : sets) {
       LineDataSet set = (LineDataSet) iSet;
       set.setDrawIcons(!set.isDrawIconsEnabled());
 }
```

**Comment by sandeepyohans** [comment]
@ismailtosun You can add icon to your selected point using 3 parameters `Entry` constructor where third parameter is a `Drawable`:

public **Entry**(float x,  float y, android.graphics.drawable.Drawable icon)
      
**Parameters:**
x - the x value
y - the y value (the actual value of the entry)
icon - icon image

[Ref: MPAndroidChart v3.0.3 JavaDoc](https://jitpack.io/com/github/PhilJay/MPAndroidChart/v3.0.3/javadoc/com/github/mikephil/charting/data/Entry.html#Entry-float-float-android.graphics.drawable.Drawable-)

Example:
 ```
ArrayList<Entry> values = new ArrayList<Entry>();
values.add(new Entry (x, y, ContextCompat.getDrawable(getApplicationContext(),R.drawable.star)));
```

You can mark a single point with icon from entire `LineDataSet` by adding `Drawable` in `Entry` constructor.

**Comment by almic** [comment]
Closing old issue. If anyone still has this question please open a new one.

**Comment by mskahraman** [comment]
for(i in 0 until values.size){
                if(values[i].y.toInt() >= 8000){
                    values[i].icon = ContextCompat.getDrawable(this,R.drawable.oval_check)
                }
            }
