### ISSUE TITLE
Add space between xAxis and yAxis

### ISSUE THREAD

**Issue by thinhlam173** [PhilJay/MPAndroidChart#3651]
Hi,
I have overrided BarChart to render data. But padding between xAxis and yAxis (in top) too close. How can I add padding between them. Thanks.
![issue](https://user-images.githubusercontent.com/34502785/33927060-460639e8-e013-11e7-97b0-209eddf67c21.png)

**Comment by dotfeng** [comment]
axis.setXOffset(10);

**Comment by jaime1990** [comment]
> axis.setXOffset(10);

Hi， I used this function, but dose not work.  so what else way to resolve this problem ?  tks

**Comment by almic** [comment]
@jaime1990 please don't comment on old issues. If you've already scoured the documentation and can't find a solution, then please open a new issue. I will, however, recommend that you simply change the visible range by a half increment of your data. So, if you want to show data between 1 and 5, then set the range to 0.5 and 5.5, so the labels won't draw but get extra space.
