### ISSUE TITLE
Horizontal Stacked bar

### ISSUE THREAD

**Issue by goonerDroid** [PhilJay/MPAndroidChart#368]
Guys can you please help me out with a horizontal stacked bar?Appreciate your help

**Comment by PhilJay** [comment]
Horizontal stacked-barcharts are currently not supported by this library.

Regards,
Phil

**Comment by goonerDroid** [comment]
Cool but is there any resources you can help me out with!Thanks

**Comment by Im-PJ** [comment]
Even I'm trying to mix stacked and horizontal bar chart. values are showing but different colors are not being drawn. only the last color is visible. 
Is this supported now?
