### ISSUE TITLE
怎样自定义LineChart交点的样式，我想把交点改成图片显示？

### ISSUE THREAD

**Issue by YinHAHA** [PhilJay/MPAndroidChart#3689]

**Comment by Sum41forever** [comment]
是这种吗？
![71227165846](https://user-images.githubusercontent.com/18468976/34376558-491e4de0-eb27-11e7-9d48-64c1704f6a9b.png)

在数据集里面调用方法`setDrawIcons`，参考demo里的LineChartActivity1

```java
 List<ILineDataSet> sets = mChart.getData() .getDataSets();
 for (ILineDataSet iSet : sets) {
                    LineDataSet set = (LineDataSet) iSet;
                    set.setDrawIcons(!set.isDrawIconsEnabled());
 }
```

**Comment by YinHAHA** [comment]
是这个，谢谢，在库里面有点击交点图片显示高亮效果的方法吗？没有看到呢？

**Comment by chenzhanfeng** [comment]
可以是用maker ，因为maker 是一个控件，可以获取到点击事件。

**Comment by YinHAHA** [comment]
怎么获取marker的监听事件，然后在改变交点icon的状态呀？

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.

Closing old issue. If anyone still has this question please open a new one. (in english)
