### ISSUE TITLE
交点显示成Icon，点击图标显示高亮图标，怎么操作呀？

### ISSUE THREAD

**Issue by YinHAHA** [PhilJay/MPAndroidChart#3694]

**Comment by Sum41forever** [comment]
交点显示Icon的，是在数据集里设置图标，这个参考demo，demo里有说怎么使用。

高亮的方法，我认为可以参照maker的回掉。你可以看下它maker是怎么拿到数据集坐标的，你仿照maker 拿到数据集，在数据集中重新设置图标就行了。没有选中就设置图标为null 这样应该就能实现高亮显示图标，

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.

Closing old issue. If anyone still has this question please open a new one.
