### ISSUE TITLE
remove support v4

### ISSUE THREAD

**Issue by xanscale** [PhilJay/MPAndroidChart#372]
support v4 are only used in com.github.mikephil.charting.charts.Chart on row 201
using "android.support.v4.view.ViewCompat.postInvalidateOnAnimation" method

since we removed the animations from Android 2 I think we can also remove the v4

if we can not remove the v4, you can at least remove the jar included in librart jar?

**Comment by PhilJay** [comment]
Now removed.

Regards,
Phil

**Comment by xanscale** [comment]
I see no commit about this

congratulations for this project

**Comment by PhilJay** [comment]
Locally I removed it already, it will be published soon.
