### ISSUE TITLE
How can i set bar width for one value?

### ISSUE THREAD

**Issue by Shineshyshi** [PhilJay/MPAndroidChart#3723]
Hi, here is my implement.

   
  ```
 barData = new BarData(barDataSet);
 barData.setBarWidth(0.65f);
 
XAxis xAxis = combinedChart.getXAxis();
xAxis.setSpaceMin(0.5f);
xAxis.setSpaceMax(0.5f);
```
and result.
![screen shot 2561-01-10 at 17 49 13](https://user-images.githubusercontent.com/9112116/34769041-3c25918a-f62f-11e7-9b33-69ff21d50f66.png)

I need to set the bottom chart to the same width as above.
Thank you.

**Comment by xiaoxing0828** [comment]
BarData.setBarWidth(0.5f);

/**
     * Sets the width each bar should have on the x-axis (in values, not pixels).
     * Default 0.85f
     *
     * @param mBarWidth
     */
    public void setBarWidth(float mBarWidth) {
        this.mBarWidth = mBarWidth;
    }

**Comment by thezukkino** [comment]
The solution provided does not work. If I set manually the bar data width, the bar is always larger than expected (as Shineshyshi said).
I'd like to improve the question.
How to calculate the bar width if the bar number in viewport is defined (chart -> setVisibleXRangeMaximum method).

**Comment by almic** [comment]
@Shineshyshi this can be acheived by adding entries with value 0 to the last graph until it matches the same number entries for all other graphs.

**Comment by thezukkino** [comment]
The solution provided by @almic works fine but if you don't wanna change your data set, you can do the following:
```
//fixed bar width to prevent too large bars for number of samples lesser than viewport
xAxisMaximum = values[0].size() < MAX_BARS_IN_VIEWPORT ? MAX_BARS_IN_VIEWPORT : values[0].size();
//setup viewport
mChart.setVisibleXRangeMaximum(MAX_BARS_IN_VIEWPORT);
xAxis.setAxisMaximum(xAxisMaximum - 1 + EXTRA_OFFSET); //added extra offset
```
where:
- values[0] is my dataset.
- MAX_BARS_IN_VIEWPORT defines the max number of bars shown in viewport.

**Comment by YasirAmeen** [comment]
/*Shared Prefrences*/
        val interval = Utils.getDurationInterval(context)

        when (interval) {
            "daily" -> {
                b.barWidth = 0.45f
            }
            "weekly" -> {
                b.barWidth = 0.14f
            }
            "monthly" -> {
                b.barWidth = 0.50f
            }
            else -> {
                b.barWidth = 0.45f
            }
        }
        b.addDataSet(set1)

**Comment by YasirAmeen** [comment]
You will have to set a bar width size for each just like I am doing

`  /*Shared Prefrences*/
        val interval = Utils.getDurationInterval(context)

        when (interval) {
            "daily" -> {
                b.barWidth = 0.45f
            }
            "weekly" -> {
                b.barWidth = 0.14f
            }
            "monthly" -> {
                b.barWidth = 0.50f
            }
            else -> {
                b.barWidth = 0.45f
            }
        }
        b.addDataSet(set1)
`

**Comment by Changyun812** [comment]
barChart.setVisibleXRange(6F,6F)
