### ISSUE TITLE
zero data line can only  be drawn a half in LineChart

### ISSUE THREAD

**Issue by huazhouwang** [PhilJay/MPAndroidChart#3728]
In LineChart, if you add some zero line data, the zero data line can only be drawn a half.
The problem code here:
```java
// BarLineChartBase.onDraw(Canvas)
canvas.clipRect(mViewPortHandler.getContentRect());
```
clipped canvas clip a half zero data line.

**Comment by itchengguo** [comment]
how to solve it , i want to know too

**Comment by itchengguo** [comment]
Just comment this line of code and it will show up as normal.

**Comment by OhPeterPan** [comment]
how to solve it , i want to know too

**Comment by itchengguo** [comment]
![image](https://user-images.githubusercontent.com/13784099/173570173-83b756cb-4e26-4bb2-853f-42ae08c13aa8.png)
有这样一行代码 ,限制了canvas的绘制区域,后来注释掉这行代码 发现显示效果正常了
![image](https://user-images.githubusercontent.com/13784099/173570305-4311cc15-def7-4245-925d-47a3ae0ddf3c.png)


> how to solve it , i want to know too
