### ISSUE TITLE
problem to set time on x-axis in Candle stick graph

### ISSUE THREAD

**Issue by Neil1484** [PhilJay/MPAndroidChart#3731]
`cscCoinGraph.setBackgroundColor(Color.WHITE);
        cscCoinGraph.getDescription().setEnabled(false);
        cscCoinGraph.setDrawGridBackground(false);
        PriceGraph = new ArrayList<>();
        PriceGraph = dataBaseManager.getCandleGraphView("BTC");
        if (PriceGraph.size() != 0) {
            List<CandleEntry> ceList = new ArrayList<>();
            for (int i = 0; i < PriceGraph.size(); i++) {
                float high = Float.parseFloat(PriceGraph.get(i).getTCCurHigh());
                float low = Float.parseFloat(PriceGraph.get(i).getTCCURLOW());
                float close = Float.parseFloat(PriceGraph.get(i).getTCCURClose());
                float open = Float.parseFloat(PriceGraph.get(i).getTCVolume());
                long time = Long.parseLong(PriceGraph.get(i).getTCTime());
                ceList.add(new CandleEntry(time, high, low, open, close));
            }

            XAxis xAxis = cscCoinGraph.getXAxis();
            xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
            Typeface tf = Typeface.createFromAsset(this.getAssets(), "fonts/worksenslight.ttf");
            xAxis.setTypeface(tf);
            xAxis.setTextSize(12f);
            xAxis.setTextColor(Color.BLUE);
            xAxis.setDrawAxisLine(true);
            xAxis.setGranularityEnabled(true);
            xAxis.setDrawGridLines(true);
            xAxis.setTextColor(Color.rgb(0, 0, 0));
            xAxis.setCenterAxisLabels(false);
            xAxis.setGranularity(1f); // one hour
            xAxis.setDrawGridLines(false);
            xAxis.setLabelCount(5);
            xAxis.setValueFormatter(new IAxisValueFormatter() {
                private SimpleDateFormat mFormat = new SimpleDateFormat("HH:mm");

                @Override
                public String getFormattedValue(float value, AxisBase axis) {
                    Date s = new Date(new Float(value).longValue() * 1000L);
                    return mFormat.format(s);
                }
            });
            YAxis leftAxis = cscCoinGraph.getAxisLeft();
            leftAxis.setDrawGridLines(false);
            YAxis rightAxis = cscCoinGraph.getAxisRight();
            rightAxis.setEnabled(false);
            CandleDataSet cds = new CandleDataSet(ceList, "");
            cds.setShadowColor(getResources().getColor(R.color.black));
            cds.setShadowWidth(0.5f);
            cds.setIncreasingColor(getResources().getColor(R.color.green));
            cds.setDecreasingColor(getResources().getColor(R.color.red));
            cds.setIncreasingPaintStyle(Paint.Style.FILL_AND_STROKE);
            cds.setDecreasingPaintStyle(Paint.Style.FILL_AND_STROKE);
            cds.setNeutralColor(Color.BLUE);
            cds.setVisible(true);
            cds.setShadowColorSameAsCandle(false);
            cds.setShowCandleBar(true);
            cds.setDrawHighlightIndicators(true);
            CandleData cd = new CandleData(cds);
            cd.setDrawValues(false);
            cscCoinGraph.setData(cd);
            cscCoinGraph.invalidate();`

Above code after adding the a axis value as time  candle graph is not show. it show only single line. as show in image
![screenshot_1515993306](https://user-images.githubusercontent.com/18122372/34928103-50aa2c1e-f9e1-11e7-8c11-af3599c25f75.png)
Help me for solution

**Comment by coolxiao** [comment]
i have the same problem too

**Comment by wasabi-lee** [comment]
I also have this issue

**Comment by salunkhenilesh** [comment]
Hi Team,
     Provide the solution for it

**Comment by almic** [comment]
@Neil1484 this is not the place to ask for programming help. Questions like this belong on stackoverflow.
