### ISSUE TITLE
How To center align barChart xAxis title

### ISSUE THREAD

**Issue by jinujayakumar** [PhilJay/MPAndroidChart#3734]
I'm trying to create a bar chart it has a single data in item the label on xAxis is  not aligned center 
![device-2018-01-16-1133132](https://user-images.githubusercontent.com/10628436/34974188-bf812aae-fab1-11e7-9abb-7672086ddd65.png)
Here is my code for generating xAxis values 
`XAxis xAxis = chartBar.getXAxis();
        xAxis.setAvoidFirstLastClipping(true);
        xAxis.setDrawGridLines(false);
        xAxis.setDrawAxisLine(true);
        xAxis.setTextSize(8f);
        xAxis.setGranularity(1f);
        xAxis.setAxisMinimum(-0.5f);

        IndexAxisValueFormatter indexAxisValueFormatter = new IndexAxisValueFormatter(xLabels);
        xAxis.setCenterAxisLabels(false);
         @xAxis.setValueFormatter(indexAxisValueFormatter);
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);`

**Comment by Deaful** [comment]
So what's the solution? Thank you for your answer.
