### ISSUE TITLE
include PercentFormatter in library

### ISSUE THREAD

**Issue by marunjar** [PhilJay/MPAndroidChart#374]
hi, i just tried to migrate my project to 2.0.0 and i noticed that the percent chars in my pie charts are missing.
I copied the file from the examlpe for now but i think it would be nice if the PercentFormatter of the example would be also included in the library

**Comment by PhilJay** [comment]
Yep, I can do that.
However, the `PercentFormatter` actually only puts the "%" sign behind the value.

If you call `pieChart.setUsePercentValues(true)` all values in the chart (no matter how high) will be transformed in a way that the chart sum makes up 100%.
