### ISSUE TITLE
Draw line and bar in a same chart?

### ISSUE THREAD

**Issue by kobe82316** [PhilJay/MPAndroidChart#376]
Can i draw a line and a bar in a same chart?

ex: http://tinyurl.com/nc4x6mj

thx!!

**Comment by Bishalsingh** [comment]
@kobe82316  I think these are going to be updated in the next version, but i am not sure. if you want it right now you can see hellocharts library and implement the concept of overlay in this library too, by using framelayout one for bar and another for line.
refer this link : https://github.com/lecho/hellocharts-android
if you do have any queries feel free to hit me a mail. 
Plus: if it is not urgent i strongly urge you to wait for next version release. Thanks

**Comment by kobe82316** [comment]
@Bishalsingh OK! thank you very much! I will try!

**Comment by PhilJay** [comment]
If you only want a `CombinedChart`, and the other charts do not matter to you, you can already use the current pre-release.

A new release should be out within the next 14 days.

Best regards,
Phil

**Comment by kobe82316** [comment]
thank you very much!

**Comment by PhilJay** [comment]
The current example also shows bar-line chart combination: https://play.google.com/store/apps/details?id=com.xxmassdeveloper.mpchartexample
