### ISSUE TITLE
How to notify or redraw marker view once image is loaded from background thread - Android

### ISSUE THREAD

**Issue by neal786y** [PhilJay/MPAndroidChart#3762]
Hi Phil,

I am tring to load images at runtime in my markerview, but it doesnt reflect as required.
I am using Picasso library as you can see in below code.
Picasso.with(context)
                        .load(url)
                        .placeholder(R.mipmap.ic_launcher)
                        .into(imageView);
Let me know if I can notify someway through callback of picasso.

Thanks

**Comment by aloj22** [comment]
Any update on this? I'm having same problem using Glide, image is not shown for the first time

**Comment by almic** [comment]
@neal786y sorry but this issue tracker is not the place to ask for programming help. Questions like this belong on stackoverflow.
