### ISSUE TITLE
Multiline x labels

### ISSUE THREAD

**Issue by mrZizik** [PhilJay/MPAndroidChart#377]
I have chart with dates as xvals. I put days of month as xvals, but i want second line as month name. I tried to put 14th xVal as "15 \n January", but it doesn't work. Is there any way to do this? @PhilJay

**Comment by PhilJay** [comment]
That is currently not possible, however, I might consider such a feature in the future.

**Comment by akkishinde** [comment]
Can we write X labels or Bar values in Vertical Manner..!

**Comment by vishwanathb** [comment]
Hi PhilJay, can we highlight one xval, i.e. highlight today's date?

**Comment by fabriziogueli** [comment]
Hi,
I modified the library to allow multiline label on the xAxis using \n

https://github.com/fabriziogueli/MPAndroidChart/tree/axis_multiline_labels

It is working right now but need further testing and maybe some code styling / adjustment.

`XAxis xAxis = mChart.getXAxis();
   xAxis.setMultiLineLabel(true);`
