### ISSUE TITLE
How do you set up a Markview to display at initialization time?

### ISSUE THREAD

**Issue by VeryCure** [PhilJay/MPAndroidChart#3788]
If inscribe。
When I initializes the entry, I set the point of the default selection of linechart, and I want to display Markview, but I don't know how to set it. I hope to answer it, thank you?

**Comment by VeryCure** [comment]
I've solved it, by setting highlightValue, but to pay attention to a problem, the default highlighting must be set to the data first, after chart.setdata.

**Comment by yuzhongrong** [comment]
i want to get the detail code
