### ISSUE TITLE
setDrawYValues

### ISSUE THREAD

**Issue by mathieudebrito** [PhilJay/MPAndroidChart#379]
Hi, I just updated to 2.0 and I don't have the setDrawXValues and setDrawYValues methods anymore, what should I do ?

(context :I don't want to draw any legend, any value, anything except the chart.)

**Comment by PhilJay** [comment]
For x-values:

`chart.getXAxis().setEnabled(false)`

For y-values:

`dataSet.setDrawValues(false)`

**Comment by mathieudebrito** [comment]
Thx @PhilJay, dataSet.setDrawValues(false) works for me, 
but chart.getXAxis() is not known - I use a PieChart

**Comment by PhilJay** [comment]
For PieChart, call `setDrawSliceText(boolean enabled)`

**Comment by mathieudebrito** [comment]
Thank you very much, really appreciated !

**Comment by LeoYe168** [comment]
For PieChart,it work for me ..
For x-values:
setDrawSliceText(boolean enabled)
For y-values:
dataSet.setDrawValues(false)
