### ISSUE TITLE
Is it possible to draw the bar value vertically

### ISSUE THREAD

**Issue by gitvijay** [PhilJay/MPAndroidChart#3797]
![asas](https://user-images.githubusercontent.com/4252219/36094312-b269b652-1013-11e8-9ed7-84c8fa612720.png)
Hi,

I'm using Barchart. Within Bar i like to show the text value vertically.
Is it possible?
Thx in advance

**Comment by gitvijay** [comment]
Hi,

I followed this tutorial to achieved the desired output.
http://www.programfaqs.com/faq/mpandroidchart-barchart-vertical-values-inside-of-bars/
hope it helps for someone.
Bottom line is we have to play with the canvas.

**Comment by lalitjadav007** [comment]
Just override `XAxisRenderer` and `renderAxisLabels(c: Canvas)` method.

And set it to barChart `itemView.barChart.setXAxisRenderer(CustomBarChartRenderer(itemView.barChart.viewPortHandler, itemView.barChart.xAxis, itemView.barChart.rendererXAxis.transformer))`

        import android.graphics.Canvas
    import com.github.mikephil.charting.renderer.XAxisRenderer
    import com.github.mikephil.charting.utils.ViewPortHandler
    import com.github.mikephil.charting.components.XAxis
    import com.github.mikephil.charting.utils.MPPointF
    import com.github.mikephil.charting.utils.Transformer
    
    class CustomBarChartRenderer(viewPortHandler: ViewPortHandler, xAxis: XAxis, trans: Transformer) : XAxisRenderer(viewPortHandler, xAxis, trans) {
    
        override fun renderAxisLabels(c: Canvas) {
    
            if (!mXAxis.isEnabled || !mXAxis.isDrawLabelsEnabled)
                return
    
            val yoffset = mXAxis.yOffset
    
            mAxisLabelPaint.typeface = mXAxis.typeface
            mAxisLabelPaint.textSize = mXAxis.textSize
            mAxisLabelPaint.color = mXAxis.textColor
    
            val pointF = MPPointF.getInstance(0f, 0f)
            if (mXAxis.position == XAxis.XAxisPosition.TOP) {
                pointF.x = 0.5f
                pointF.y = 1.0f
                drawLabels(c, mViewPortHandler.contentTop() - yoffset, pointF)
    
            } else if (mXAxis.position == XAxis.XAxisPosition.TOP_INSIDE) {
                pointF.x = 0.5f
                pointF.y = 1.0f
                drawLabels(c, mViewPortHandler.contentBottom() - yoffset, pointF)
    
            } else if (mXAxis.position == XAxis.XAxisPosition.BOTTOM) {
                pointF.x = 0.5f
                pointF.y = 0.0f
                drawLabels(c, mViewPortHandler.contentBottom() + yoffset, pointF)
    
            } else if (mXAxis.position == XAxis.XAxisPosition.BOTTOM_INSIDE) {
                pointF.x = 0.5f
                pointF.y = 0.0f
                drawLabels(c, mViewPortHandler.contentBottom() - yoffset - mXAxis.mLabelRotatedHeight.toFloat(), pointF)
    
            } else { // BOTH SIDED
                pointF.x = 0.5f
                pointF.y = 1.0f
                drawLabels(c, mViewPortHandler.contentTop() - yoffset, pointF)
                pointF.x = 0.5f
                pointF.y = 0.0f
                drawLabels(c, mViewPortHandler.contentBottom() + yoffset, pointF)
            }
            MPPointF.recycleInstance(pointF)
        }
    }
