### ISSUE TITLE
Set text size based on style attribute

### ISSUE THREAD

**Issue by mtotschnig** [PhilJay/MPAndroidChart#380]
I would like to set the text-size of a chart (e.g. the center text of a pie chart) based on a style attribute. In my app, users can choose between different themes that differ with respect to text size, and this preference should also apply to the text used in the chart.
I am able to retrieve the value with the following code

      TypedValue typedValue = new TypedValue(); 
      getActivity().getTheme().resolveAttribute(android.R.attr.textAppearanceMedium, typedValue, true);
      int[] textSizeAttr = new int[] { android.R.attr.textSize };
      int indexOfAttrTextSize = 0;
      TypedArray a = getActivity().obtainStyledAttributes(typedValue.data, textSizeAttr);
      int textSize = a.getDimensionPixelSize(indexOfAttrTextSize, -1);
      a.recycle();

But this gives me a pixel size that can not be used in PieChart's setCenterTextsize method, since it expects a dp value that it transforms to pixels. Thus I suggest to provide a method that accepts the pixel value directly as in

    public void setCenterTextPixel(int pixel) {
      mCenterTextPaint.setTextSize(pixel);
    }

**Comment by PhilJay** [comment]
I have included such a method for you. It will be available in the next update.

`setCenterTextSizePixels(float sizePixels)`
