### ISSUE TITLE
Issues Faced During Beta Library:

### ISSUE THREAD

**Issue by Bishalsingh** [PhilJay/MPAndroidChart#381]
Hey @PhilJay Thanks for the beta version:
1.	This works like a charm on the dual Y-Axis Purpose. However I am facing a Problem:
a.	Enabling and disabling of data, lines of axis and grid is not as feasible as it was before.
Eg: Earlier versions: chart.setDrawVerticalGrid(false);	chart.setDrawHorizontalGrid(false); did the work but for now we have to go to every axis (Y dual) and then cancel it. By default Y should be single axis.
b.	By Default, the YAxis should be on Left and not on both in my view, because only on special        occasions people need it on both axis.
c.	Changes in the syntax with comparison to earlier version should be documented.
d.	Xaxis max and min value is included, Which is a nice thing now.
e.     How can we disable the YLabels in linechart.? if chart.getAxisLeft.Enabled(false) is done then, grid color horizontally is also disabled.
f.     What is the alternate to barchart.setUnit("units"); in new library?
g.    setUsePercentValues(true); in pie chart gives percantage value but '%' is not displayed after the     number
h.    setting minimum values for YAxis label doesnot work and is there any way to disable ylabels only with keeping grid values, axislines enabled?
![capture](https://cloud.githubusercontent.com/assets/7859556/6390963/270b024e-bdd9-11e4-8a8a-c833f36d913b.PNG)

**Comment by PhilJay** [comment]
a) Yep, I already thought of that. However I think most people would then not understand that there is the possibility of having 2 y-axes.
b) See a).
c) I will do that as soon as I have completed the update.
d) Thx!
e) I dont understand.
f) All formatting is now done via `ValueFormatter`
g) See f).
h) Setting minimum values above 0 should work. Below 0, you have to call `setStartAtZero(false)`

**Comment by Bishalsingh** [comment]
e. I mean that if i want to keep the grid lines enabled on left Y axis, but i donot want to have the Y-Labels enabled?? ho to achieve this. In short, how can we set the option setDrawYLabels(false)

**Comment by PhilJay** [comment]
Now I know what you mean. by `setEnabled(false)` the whole axis will become invisible.
What I did now is create a new method called `setDrawLabels(boolean enabled)` for the axes.

In that way, now there is the possibility to disable the axis labels only, while grid lines and so on are still drawn.

**Comment by Bishalsingh** [comment]
Ok thanks.
