### ISSUE TITLE
Funnel chart

### ISSUE THREAD

**Issue by Vivektilva** [PhilJay/MPAndroidChart#3811]
@Can you provide any code for funnel chart ??
![capture](https://user-images.githubusercontent.com/36498707/36297941-6b25e42c-131b-11e8-8224-af4df4a5c1c4.PNG)

@danielgindi @PhilJay @tonypatino-monoclesociety

**Comment by MGaetan89** [comment]
Can you close this issue as it was already reported in #3178?
