### ISSUE TITLE
XAxis value formatter value 

### ISSUE THREAD

**Issue by shaon2016** [PhilJay/MPAndroidChart#3813]
If I set some value in line chart it generates XAxis value comparing the value I provide. But when I try to set new values in the same line chart it holds the previous xAxis value and also holds the new xAxis value.
That's why IAxisValueFormatter listener provides previous axis value and new axis value both. Invalidate (refresh) didn't work in this situation.
 
Logcat shows the situation of IAxisValueFormatter:

DashboardActivity: 0.0
DashboardActivity: 1.0
DashboardActivity: 2.0
DashboardActivity: 3.0
DashboardActivity: 0.0
DashboardActivity: 1.0
DashboardActivity: 0.0
DashboardActivity: 1.0
DashboardActivity: 2.0
DashboardActivity: 3.0
DashboardActivity: 0.0
DashboardActivity: 1.0

Previous Code:

`IAxisValueFormatter formatter = (value, axis) -> {
            Lg.d(TAG, value + "");
                    return str.get((int) value);
        };
xAxis.setGranularity(1f);
xAxis.setValueFormatter(formatter);`

I solved this issue using this below code

`IAxisValueFormatter formatter = (value, axis) -> {Lg.d(TAG, value + ""); if(str.size()-1 < value) return "0";
            return str.get((int) value);
  };
         xAxis.setGranularity(1f); 
        xAxis.setValueFormatter(formatter);`

**Comment by almic** [comment]
This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.
