### ISSUE TITLE
Moving after zoom

### ISSUE THREAD

**Issue by ammaratef45** [PhilJay/MPAndroidChart#3817]
In linechart after zooming chart can be moved.
I have two questions here:
1- Can I disable that movement without disabling the zoom?
2- How can I stop page scrolling (if the chart was in scroll view or in pager adapter) while moving the chart, Just for better user experience.

**Comment by AnthonyJoshua1** [comment]
you can set like this 
lineChart.setScaleYEnabled(false); or X

**Comment by parthanjaria** [comment]
I am having a similar problem, but a slightly different way. when i set a particular zoom to the chart, and i scroll the barchart, and later i change the zoom and set the barchart to the last value, still it zooms to a totally different level.

**Comment by almic** [comment]
This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.
