### ISSUE TITLE
How to Send ILineDataSet to another Fragment using parcelable?

### ISSUE THREAD

**Issue by PallaviTapkir** [PhilJay/MPAndroidChart#3821]
I want to send ILineDataSet to another fragment. I am trying to pass using bundle, but not able to make ILineDataSet Parcelable. How can I achieve this?

**Comment by almic** [comment]
This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.
