### ISSUE TITLE
default need to show markview when draw finished

### ISSUE THREAD

**Issue by yuzhongrong** [PhilJay/MPAndroidChart#3823]
we need to show markview when chart init finished

**Comment by almic** [comment]
This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.

**Comment by AnJiuZhe** [comment]
it's supported now! call Chart.highlightValue(float x, int dataSetIndex) to set default markview after setData
