### ISSUE TITLE
Pie Chart display ' no chart data available'  in tab slider

### ISSUE THREAD

**Issue by anonymous1445** [PhilJay/MPAndroidChart#3826]
why this issue occured and how to solved it, it just happen in tab sliding.

**Comment by almic** [comment]
This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.
