### ISSUE TITLE
在使用LineChart绘图时x数据为负值时崩溃。

### ISSUE THREAD

**Issue by IrreplaceableChao** [PhilJay/MPAndroidChart#3827]
在使用LineChart绘图时x数据为负值时崩溃。
需要设置什么么，还是我哪里没有写明白

**Comment by IrreplaceableChao** [comment]
Crash when x data is negative when using LineChart drawing.What needs to be set up?

**Comment by almic** [comment]
This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.
