### ISSUE TITLE
Draw the linechart is  incoherence

### ISSUE THREAD

**Issue by yuzhongrong** [PhilJay/MPAndroidChart#3828]
![1111](https://user-images.githubusercontent.com/7382234/36836909-a954d776-1d75-11e8-8524-02e342d0004d.png)

**Comment by almic** [comment]
Sorry, this issue makes no sense. I cannot tell what problem you are having. In case it helps, here's a copy pasta.

This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.
