### ISSUE TITLE
FillColors method ?

### ISSUE THREAD

**Issue by mathieudebrito** [PhilJay/MPAndroidChart#383]
Hi, I would like to know how I can set multiple fill colors depending on the segment between 2 points?
Here is an example: 

![Multiple fill colorst](http://www.pantalithos.it/images/randonneur/2015/altimetria/Altimetria%20Openrunner.png)

**Comment by PhilJay** [comment]
This is currenlty not possible.
You will have to create the feature you described by yourself :-)

Best regards,
phil

**Comment by mathieudebrito** [comment]
ok thx for the quick answer :)

**Comment by SheepYang1993** [comment]
Just like this?
![image](https://user-images.githubusercontent.com/15150244/69506495-deabb880-0f69-11ea-9dd9-4343f22d5108.png)
