### ISSUE TITLE
How to achieve Drill Down Graph feature using MPAndroidChart in Android

### ISSUE THREAD

**Issue by KCRaju** [PhilJay/MPAndroidChart#3833]
Hi,

I am trying to implement  **Drill Down Graph** for BAR Graphs using **MPAndroidChart**. 

For that i implemented _implementation 'com.github.PhilJay:MPAndroidChart:v3.0.2'_ in my gradle. But using this Bars in graph are over lapping and not showing properly. please check below image for more details.

![device-2018-03-02-174939](https://user-images.githubusercontent.com/19387783/36899038-61a9d2c2-1e43-11e8-84dc-bddfab4009ea.png)

I fixed this issue by using _implementation 'com.github.PhilJay:MPAndroidChart:v2.2.4'_. Now graph is showing properly as shown below.
![device-2018-03-02-175548](https://user-images.githubusercontent.com/19387783/36899048-6c7ca1c0-1e43-11e8-9c13-fa0b53069b00.png)

But this is not latest version.

And
To achieve **Drill Down** feature i need to know the which bar is selected by position number.How to get this?

**Comment by almic** [comment]
This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.
