### ISSUE TITLE
how to show other charts in fragment using spinner

### ISSUE THREAD

**Issue by arusocse** [PhilJay/MPAndroidChart#3837]
Sir, how can i show other chart in one fragment using spinner. I want to show pie chart when I choose Today in the spinner. And Line Chart when I choose Weekly. Thank you.

**Comment by almic** [comment]
This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.
