### ISSUE TITLE
Unable to set another dynamic activity data on my pie chart

### ISSUE THREAD

**Issue by arpan9477** [PhilJay/MPAndroidChart#3838]
In my android app I want all data in my pie chart when I submit data. But I don't understand how how to do it. In my first activity have one spinner and a button when one number selected from spinner and click that button, that numbers edit text field and a button appear. When I click on that button that data goes to next page and print in a pie chart with that pie chart divided according what number data goes in next page. I already make pie chart with static data in another app but this one stuck.I do not understand piechart activity java.

**Comment by almic** [comment]
This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.
