### ISSUE TITLE
Swift version?

### ISSUE THREAD

**Issue by danielgindi** [PhilJay/MPAndroidChart#384]
Hey man!

I would be interested in writing a Swift version for this neat library (iOS),
And keeping it with sync of new features and bug fixes.

It's just a matter of - are you interested? Will you approve?
What about licensing? Is it permissive enough?

**Comment by PhilJay** [comment]
Yes of course, I'd like to see an iOS version of this Library. Feel free to create one :-)
Just let me know the link to the repo (maybe post it here).

Thank you!

**Comment by danielgindi** [comment]
So I have good news... I've done some major work in the past weeks, and there's a full result:

https://github.com/danielgindi/ios-charts/

**Comment by danielgindi** [comment]
Now if developers on MPAndroidChart will be more strict on atomic commits and clear descriptions - It will help keeping the iOS version in sync :-)

**Comment by PhilJay** [comment]
Thank you, it looks very promising! Awesome that you took the time!
I'm quite new to iOS and cloned your repo but I cant get it to run.

I opened ChartsDemo.xcodeproj and tried to run it on my iOS Simulator but I have like 324 errors :-D
It seems that the library (framework) is not linked correctly to the demo project.
Here is what I mean: (as you can see the linked Charts.framework is highlighted "red")
Do you have any idea of what is wrong?
![screen shot 2015-03-20 at 20 44 28](https://cloud.githubusercontent.com/assets/6759734/6759660/faddcc86-cf41-11e4-99b1-71907f00e58f.png)
![screen shot 2015-03-20 at 20 44 44](https://cloud.githubusercontent.com/assets/6759734/6759663/03ba63e6-cf42-11e4-9550-771d2f70795e.png)

**Comment by danielgindi** [comment]
Oh yes I do!
It will actually only compile against the current Beta version of Xcode, as
I wanted some new features of Swift that were only recently introduced.
The beta is public so you can download it easily :)

‏בתאריך יום שישי, 20 במרץ 2015, Philipp Jahoda <notifications@github.com>
כתב:

**Comment by PhilJay** [comment]
@danielgindi just passed our 1-year anniversary :-)

**Comment by danielgindi** [comment]
Yeah :-)

**Comment by YasaminZamaniPro** [comment]
Hi @danielgindi,
thanks a lot for your wonderful work here.
I just wanted to ask after digging the net for days, there is no proper documentation for the Swift Version, and as I refer to the Android Docs, I still can't manage to find my way around it. 
Any advice?

**Comment by YasaminZamaniPro** [comment]
and I constantly get these two errors in my console( but the graph still works) :
- nw_write_request_report [C41] Send failed with error "Broken pipe"
- nw_socket_handle_socket_event [C41.1:3] Socket SO_ERROR [54: Connection reset by peer]
