### ISSUE TITLE
First and last showing values on X and Y Axis

### ISSUE THREAD

**Issue by panzhiev** [PhilJay/MPAndroidChart#3842]
Good Day! First of all thank you for amazing library!

I have a chart with LineDataSet. I want that the first value of each Axis (X and Y) starts with min value in current set and ends with the max. How i do this??
```
private void setupChart(LineChart chart, LineData data, int color) {

        ((LineDataSet) data.getDataSetByIndex(0)).setCircleColorHole(color);

        chart.getDescription().setEnabled(false);
        chart.setDrawGridBackground(false);
        chart.setTouchEnabled(true);
        chart.setDragEnabled(true);
        chart.setScaleEnabled(false);
        chart.setPinchZoom(false);
        chart.setData(data);
        Legend l = chart.getLegend();
        l.setEnabled(false);

        chart.getAxisRight().setEnabled(false);

        YAxis yAxis = chart.getAxisLeft();
        yAxis.setEnabled(true);
        yAxis.setYOffset(-7f);
        yAxis.setAxisMinimum(data.getDataSetByIndex(0).getYMin() - data.getDataSetByIndex(0).getYMin() / 2000);
        yAxis.setAxisMaximum(data.getDataSetByIndex(0).getYMax());
        yAxis.enableGridDashedLine(10f, 10f, 0f);
        yAxis.setPosition(YAxis.YAxisLabelPosition.INSIDE_CHART);
        yAxis.setTextColor(getResources().getColor(R.color.colorTextDefault));

        XAxis xAxis = chart.getXAxis();
        xAxis.setEnabled(true);
        xAxis.setDrawGridLines(false);
        xAxis.setDrawAxisLine(true);
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setTextColor(getResources().getColor(R.color.colorTextDefault));
        xAxis.setAvoidFirstLastClipping(true);

        IAxisValueFormatter xAxisFormatter = new HourAxisValueFormatter(Long.parseLong(mPointList.get(0).getUnixTime()));
        xAxis.setValueFormatter(xAxisFormatter);
        chart.animateX(700);
    }
```
![screenshot_1520262306 1](https://user-images.githubusercontent.com/14140384/36983812-014e3188-209c-11e8-896e-d915a42bc6e5.png)

**Comment by xiaoshubin** [comment]
first you can use:
 yAxis.setSpaceBottom(0);
 yAxis.setSpaceTop(0);
and remove this code:
xAxis.setAvoidFirstLastClipping(true);

**Comment by almic** [comment]
This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.
