### ISSUE TITLE
open to new maintainers 

### ISSUE THREAD

**Issue by farfromrefug** [PhilJay/MPAndroidChart#3844]
@PhilJay I am not sure if you are still maintaining that lib?
I am willing to help in maintaining this project. 
Are you willing to add maintainers?
Or maybe we should create a github organisation where we could host MPandroidChart and Charts?
@danielgindi Would you agree to that?

MPandroidChart/Charts are in almost all my clients app. I am will to invest time into them.

**Comment by MGaetan89** [comment]
I would also be interested in supporting this lib.
For now, I forked the project to add a bunch of tests to the library. I will start to fix crashes and bugs in the coming weeks.

**Comment by farfromrefug** [comment]
@MGaetan89 same thing here. @PhilJay can you answer us?
Thanks

**Comment by RobertZagorski** [comment]
I am also interested in maintaining this project - especially in resolving the mess, that almost 1500 issues create 
Have time and will to fix issues and work on new featueres as well as improving the performance.
@PhilJay Would you consider giving me such rights to the project?

**Comment by almic** [comment]
Have no fear! @almic is here!
