### ISSUE TITLE
Change Circle color in linechart

### ISSUE THREAD

**Issue by Anusha5248** [PhilJay/MPAndroidChart#3845]
HI..
I have integrated MpAndroidChart in my application and I getting two issues. 
1. Color change issue--I need to change the circle color based pill status. If pill taken i need to display green circle or else pink. How can I change the color
2. Display allxaxis  values--
![line](https://user-images.githubusercontent.com/9796095/37050666-74bc381c-2142-11e8-94cb-5deb8eec07cf.png)
And How to display all xaxis values, Currently im displaying one week(28/2--06/03) data if I changed to 3months (04/02- 06/03) I need to display all xaxis values like(feb 04,05,06......mar 06). 
Please help me

**Comment by almic** [comment]
Currently, changing the circle colors based on the data is not possible. But, you would've figured that out if you read the documentation, and so...

This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.
