### ISSUE TITLE
Barchart - fully disable highlighting?

### ISSUE THREAD

**Issue by gfdarcy** [PhilJay/MPAndroidChart#3849]
I can't seem to fully disable highlighting. I want a zoomable bar graph, but it's highlighting the bars when I drag a zoomed in set of data.

**Comment by MGaetan89** [comment]
What have you tried?

**Comment by gfdarcy** [comment]
Sorry for the delay, I was away for Easter!

This is the code I'm using;

        // enable zooming
        mChart.setAutoScaleMinMaxEnabled(false);
        mChart.setScaleEnabled(false);
        mChart.setContextClickable(false);
        mChart.setClickable(false);
        mChart.setFocusable(false);
        mChart.setDoubleTapToZoomEnabled(true);
        mChart.setPinchZoom(false);
        mChart.setTouchEnabled(true);
        mChart.setDragEnabled(true);
        mChart.setScaleYEnabled(false);
        mChart.setScaleXEnabled(true);
        mChart.setHighlightPerTapEnabled(false);
        mChart.setHighlightFullBarEnabled(false);

**Comment by gfdarcy** [comment]
gibels, your post lead me to this;
        dataSet.setHighlightEnabled(false);

I'm still testing to see if it works, but so far so good.

**Comment by MGaetan89** [comment]
@gfdarcy Did @gibels-and-bits solution works for you? If so, can you close this issue?
