### ISSUE TITLE
Accept List instead of forcing ArrayList

### ISSUE THREAD

**Issue by Maragues** [PhilJay/MPAndroidChart#385]
Constructors of *DataSet* (*LineDataSet*, *BarDataSet*) force you to pass an *ArrayList*. Is there any particular reason? I can create a PR replacing *ArrayList* for *List*.

**Comment by PhilJay** [comment]
Well the reason is I like `ArrayList` nothing else :-D

**Comment by Maragues** [comment]
@PhilJay you should always prefer interfaces over specific implementations, unless there's a good reason. They offer flexibility and decouple the code from a given class. There's a lot of literature about it

http://www.javaworld.com/article/2073649/core-java/why-extends-is-evil.html
http://uet.vnu.edu.vn/~chauttm/e-books/java/Effective.Java.2nd.Edition.May.2008.3000th.Release.pdf, item 18

My vote is to reopen the issue, but it's your code

**Comment by PhilJay** [comment]
Allright, I'll do it as soon as there is the time. ´Currently it's not very high on my priority list tough :-)
