### ISSUE TITLE
savetopath() on server side

### ISSUE THREAD

**Issue by mfhawley** [PhilJay/MPAndroidChart#3850]
I got the **savetopath ()** function working on the user side where data is fed through the MPAndroidChart and a chart is shown to the user. The user can then has to click a button to convert the chart to a PNG which can be sent to the server.
However, I was looking for a way to feed the data through MPAndroidChart and save the chart to a PNG all on the server side before ever being shown to the user.

Could anyone help me on how I could make this work?

**Comment by almic** [comment]
This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.

> P.S.
> Upvoting your own issue is dishonest, especially if someone was sorting through issues based on upvotes. I added a downvote to balance it out :)
