### ISSUE TITLE
ScatterChart/CombinedChart - draw points in reverse order

### ISSUE THREAD

**Issue by jlo1** [PhilJay/MPAndroidChart#3851]
Are there plans to support a flag that will allow the chart to draw the datapoints in reverse order? Use case here is that we're drawing larger icons that can overlap each other, but we want the earlier data points to be drawn on top of the later data points.

**Comment by almic** [comment]
This is a very minor design change, so small I doubt a user would actually care which circles overlapped which. Right now I do not plan on adding a new flag and render check to support something so specific, and honestly not noticeable unless you actually showed someone the two options side-by-side.

Your best option is to add the entries in reverse order, this may be enough to trick the renderer into drawing them in the order you want. I haven't personally tested this, but from looking at the render and data set classes, it seems possible.
