### ISSUE TITLE
How to fix a Y label Width.

### ISSUE THREAD

**Issue by king1495** [PhilJay/MPAndroidChart#3852]
![image](https://user-images.githubusercontent.com/16570419/37196810-8c2b25a0-23bb-11e8-9f0c-70165ec3eff1.png)

I Plot a multi data in Listview.
I want to fix a Y-axis line at red-line(see figure).
but I can't find a option to fix y label width.

**Comment by almic** [comment]
Since this is such a minor design flaw, I doubt anyone except you cares. Don't get me wrong, this is triggering my OCD and I don't like the way it looks either. But right now I don't think this is a significant problem that deserves a new method, variables, and render checks to solve.

**Comment by Abu-Abdullah** [comment]
it can be done manually
```
final Paint paint = chart.getRendererLeftYAxis().getPaintAxisLabels();
float width = paint.measureText(" <text> ");
final YAxis yAxis = chart.getAxisLeft(); // Y-Axis Style
float dp = width / ((float) getResources().getDisplayMetrics().densityDpi / DisplayMetrics.DENSITY_DEFAULT);
yAxis.setMaxWidth(dp);
yAxis.setMinWidth(dp);
```
