### ISSUE TITLE
PieChart in RecyclerView is not drawn properly

### ISSUE THREAD

**Issue by salta-kozbagarova** [PhilJay/MPAndroidChart#3854]
I use piechart in cardview inside of recyclerview, overall i have 5 data to be used in piechart. Only first chart is drawn, but other data like center text, description is shown for every data.

**Comment by salta-kozbagarova** [comment]
```
package com.salikhanova.questionapp;

import android.content.Context;
import android.support.v7.widget.RecyclerView;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import com.github.mikephil.charting.charts.PieChart;
import com.github.mikephil.charting.components.Description;
import com.github.mikephil.charting.data.PieData;
import com.github.mikephil.charting.data.PieDataSet;
import com.github.mikephil.charting.data.PieEntry;
import com.salikhanova.questionapp.entity.Answer;
import com.salikhanova.questionapp.entity.Question;
import com.salikhanova.questionapp.entity.QuestionAnswer;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Created by User on 09.03.2018.
 */

public class StatisticsAdapter extends RecyclerView.Adapter<StatisticsAdapter.MyViewHolder> {

    private Context mContext;
    private List<QuestionAnswer> qaList;
    private List<Question> questions;
    List<PieEntry> entries;
    List<Integer> colors = new ArrayList<>();

    public class MyViewHolder extends RecyclerView.ViewHolder {
        public PieChart pieChart;
        public TextView question, answer1, answer2, answer3, answer4, answer5;
        public TextView[] answers;

        public MyViewHolder(View view) {
            super(view);
            pieChart = (PieChart) view.findViewById(R.id.chart);
            question = view.findViewById(R.id.question);
            answer1 = view.findViewById(R.id.answer1);
            answer2 = view.findViewById(R.id.answer2);
            answer3 = view.findViewById(R.id.answer3);
            answer4 = view.findViewById(R.id.answer4);
            answer5 = view.findViewById(R.id.answer5);
            answers = new TextView[]{answer1, answer2, answer3, answer4, answer5};
        }
    }

    public StatisticsAdapter(Context mContext, List<QuestionAnswer> qaList, List<Question> questions) {
        this.mContext = mContext;
        this.qaList = qaList;
        this.questions = questions;
        colors.add(mContext.getResources().getColor(R.color.pieColor1));
        colors.add(mContext.getResources().getColor(R.color.pieColor2));
        colors.add(mContext.getResources().getColor(R.color.pieColor3));
        colors.add(mContext.getResources().getColor(R.color.pieColor4));
        colors.add(mContext.getResources().getColor(R.color.pieColor5));
    }

    @Override
    public StatisticsAdapter.MyViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View itemView = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.statistics_item, parent, false);
        return new MyViewHolder(itemView);
    }

    @Override
    public void onBindViewHolder(final MyViewHolder holder, int position) {
        List<Integer> answers = new ArrayList<>();
        Question question = null;
        for(Question q : questions){
            if(q.getId() == (position+1)){
                question = q;
            }
        }
        entries = new ArrayList<>();
        for(QuestionAnswer qa : qaList){
            if(qa.getQuestionId() == (position+1)){
                answers.add(qa.getAnswerId());
            }
        }
        int occurrences;
        for(int i=1;i<5;i++){
            occurrences = Collections.frequency(answers, i);
            entries.add(new PieEntry(Float.valueOf(occurrences), "Ответ 1"));
        }
        holder.question.setText(question.getText());
        for(int i = 0; i < question.getAnswers().size(); i++){
            holder.answers[i].setText(question.getAnswers().get(i).getText());
        }
        PieDataSet pieDataSet = new PieDataSet(entries, question.getText());

        pieDataSet.setColors(colors);
        pieDataSet.setSliceSpace(2);
        pieDataSet.setValueTextSize(15);

        PieData pieData = new PieData(pieDataSet);
        holder.pieChart.setData(pieData);
        //pieChart.setUsePercentValues(true);
        holder.pieChart.setRotationEnabled(true);
        holder.pieChart.setCenterText("Всего: " + String.valueOf(answers.size()));
        holder.pieChart.setCenterTextSize(12);
        //pieChart.setBackgroundColor(getApplicationContext().getResources().getColor(R.color.colorPrimary));
        holder.pieChart.setDrawEntryLabels(false);
        Description description = new Description();
        description.setText("Description number " + (position+1));
        holder.pieChart.setDescription(description);
        holder.pieChart.notifyDataSetChanged();
        holder.pieChart.invalidate();
    }

    @Override
    public int getItemCount() {
        return questions.size();
    }
}

```

**Comment by salta-kozbagarova** [comment]
Everything works except color? Because all the data in its right place for every piechart, except the colors, there are no pies, i see description, legend, centertext, i even know that rotation works, because i can rotate the piechart, just can't see it as it is white, i mean no color.

**Comment by salta-kozbagarova** [comment]
Ohhhhh!!!! This is me! I have found my mistake)it's because of for(int i=1;i<5;i++){} lines, closing this issue

**Comment by hansraj123** [comment]
Please Watch this Video :https://youtu.be/AvSOh_RYxnY
This Is my Code ..

`package com.h8.h8wifiad.login.adapter;


import android.content.Context;
import android.graphics.Color;
import android.support.v7.widget.CardView;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;

import com.github.mikephil.charting.charts.PieChart;
import com.github.mikephil.charting.components.Legend;
import com.github.mikephil.charting.data.PieData;
import com.github.mikephil.charting.data.PieDataSet;
import com.github.mikephil.charting.data.PieEntry;
import com.github.mikephil.charting.formatter.PercentFormatter;
import com.github.mikephil.charting.utils.ColorTemplate;
import com.h8.h8wifiad.R;
import com.h8.h8wifiad.login.customfonts.CustomTextViewUbuntuRegular;
import com.h8.h8wifiad.login.dto.QuestionSummery_Dto;

import java.util.ArrayList;
import java.util.Random;


/**
 * Created by Jeffrey Liu on 3/21/16.
 */
public class SummaryList_Child_Adapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {

    LayoutInflater layoutInflater;
    Context mContext;
    ArrayList<QuestionSummery_Dto> alQuestionSummery;
    ArrayList<QuestionSummery_Dto> uniqueQuestionName;
    ArrayList<PieEntry> entries;
    PieDataSet dataSet;
    String subQuestionsName;
    PieData data;
    boolean isEnteryDataAdded = false;


    public SummaryList_Child_Adapter(ArrayList<QuestionSummery_Dto> uniqueQuestionName, ArrayList<QuestionSummery_Dto> alQuestionSummery, Context mContext) {
        this.alQuestionSummery = alQuestionSummery;
        this.mContext = mContext;
        this.uniqueQuestionName = uniqueQuestionName;
        entries = new ArrayList<PieEntry>();


    }

    private class CellViewHolder extends RecyclerView.ViewHolder {
        private PieChart summaryPieChart;
        CustomTextViewUbuntuRegular tvsubQuestion;
        CardView summary_child_mRoot;

        public CellViewHolder(View itemView) {
            super(itemView);
            summaryPieChart = (PieChart) itemView.findViewById(R.id.summaryPieChart);
            tvsubQuestion = (CustomTextViewUbuntuRegular) itemView.findViewById(R.id.tvsubQuestion);
            summary_child_mRoot=itemView.findViewById(R.id.summary_child_mRoot);

        }


    }

    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(final ViewGroup viewGroup, int viewType) {

        switch (viewType) {
            default: {
                View v1 = LayoutInflater.from(viewGroup.getContext()).inflate(R.layout.summary_child_raw, viewGroup, false);
                return new CellViewHolder(v1);
            }
        }
    }

    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder viewHolder, int position) {


        entries.clear();
        switch (viewHolder.getItemViewType()) {
            default: {
                CellViewHolder cellViewHolder = (CellViewHolder) viewHolder;
                try {
                    if (!uniqueQuestionName.get(position).getSubquestion().equalsIgnoreCase("") && !uniqueQuestionName.get(position).getSubquestion().equalsIgnoreCase(" ")) {
                        cellViewHolder.tvsubQuestion.setVisibility(View.VISIBLE);
                        cellViewHolder.tvsubQuestion.setText(uniqueQuestionName.get(position).getSubquestion());
                        subQuestionsName = uniqueQuestionName.get(position).getSubquestion();
                        LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(
                                LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT);

                        cellViewHolder.summary_child_mRoot.setLayoutParams(layoutParams);

                    } else {
                        cellViewHolder.tvsubQuestion.setVisibility(View.GONE);

                    }

                    for (QuestionSummery_Dto dto : alQuestionSummery) {
                        if (uniqueQuestionName.size() <= 1) {
                            entries.add(new PieEntry(Float.parseFloat(dto.getAnswerratio()), dto.getAnswer()));
                        } else {
                            try {
                                if (dto.getSubquestion().contains(subQuestionsName)) {

                                    entries.add(new PieEntry(Float.parseFloat(dto.getAnswerratio()), dto.getAnswer()));

                                }
                            } catch (ArrayIndexOutOfBoundsException e) {
                                e.printStackTrace();
                            }
                        }
                    }

                    cellViewHolder.summaryPieChart.setUsePercentValues(true);
                    cellViewHolder.summaryPieChart.getDescription().setEnabled(false);

                    cellViewHolder.summaryPieChart.setDragDecelerationFrictionCoef(0.95f);

//
//            holder.summaryPieChart.setExtraOffsets(20.f, 0.f, 20.f, 0.f);

                    cellViewHolder.summaryPieChart.setDrawHoleEnabled(true);
                    cellViewHolder.summaryPieChart.setHoleColor(Color.WHITE);

                    cellViewHolder.summaryPieChart.setTransparentCircleColor(Color.GRAY);
                    cellViewHolder.summaryPieChart.setTransparentCircleAlpha(110);

                    cellViewHolder.summaryPieChart.setHoleRadius(2f);
                    cellViewHolder.summaryPieChart.setTransparentCircleRadius(5f);
                    cellViewHolder.summaryPieChart.setDrawCenterText(true);
                    cellViewHolder.summaryPieChart.setRotationAngle(0);
                    cellViewHolder.summaryPieChart.setRotationEnabled(true);
                    cellViewHolder.summaryPieChart.setHighlightPerTapEnabled(true);

                    dataSet = new PieDataSet(entries, "Survey  Data");
                    dataSet.setDrawValues(false);
                    data = new PieData(dataSet);
                    dataSet.setSliceSpace(3f);
                    dataSet.setSelectionShift(5f);
                    dataSet.setColor(Color.BLACK);

                    showChart(cellViewHolder.summaryPieChart,data);


                } catch (Exception e) {
                    e.printStackTrace();
                }

                break;

            }


        }


//
    }

    private void showChart(PieChart chart, PieData data) {
        if (chart == null || data == null) {
            return;
        }
        ArrayList<Integer> colors = new ArrayList<Integer>();
//
        for (int c : ColorTemplate.MATERIAL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.JOYFUL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.COLORFUL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.MATERIAL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.COLORFUL_COLORS)
            colors.add(c);
//                    Random rnd = new Random();
//                    int color = Color.argb(255, rnd.nextInt(220), rnd.nextInt(250), rnd.nextInt(220));
//                view.setBackgroundColor(color);
//                    colors.add(colors);

        dataSet.setColors(colors);
        dataSet.setSelectionShift(0f);

        dataSet.setValueLinePart1OffsetPercentage(80.f);
        dataSet.setValueLinePart1Length(0.2f);
        dataSet.setValueLinePart2Length(0.4f);
        dataSet.setXValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);
        dataSet.setYValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);


        data.setValueFormatter(new PercentFormatter());
        data.setValueTextSize(9f);
        data.setValueTextColor(Color.BLACK);

        chart.setData(data);


        // undo all highlights
        chart.highlightValues(null);


//                        cellViewHolder.summaryPieChart.animateY(1400, Easing.EasingOption.EaseInOutQuad);

        Legend l = chart.getLegend();
        l.setVerticalAlignment(Legend.LegendVerticalAlignment.TOP);
        l.setHorizontalAlignment(Legend.LegendHorizontalAlignment.RIGHT);
        l.setOrientation(Legend.LegendOrientation.VERTICAL);
        l.setTextColor(Color.BLACK);
        l.setDrawInside(false);
        l.setEnabled(false);
        chart.notifyDataSetChanged();
        chart.invalidate();

    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public int getItemViewType(int position) {
        return position;
    }


    @Override
    public int getItemCount() {
        if (uniqueQuestionName == null)
            return 0;
        return uniqueQuestionName.size();
    }

}`
