### ISSUE TITLE
The x axis labels increase the click event

### ISSUE THREAD

**Issue by qinyang1018** [PhilJay/MPAndroidChart#3855]
![image](https://user-images.githubusercontent.com/15726024/37241100-b40c33d8-248e-11e8-8806-d158c0046dc3.png)

How the x axis labels to increase click event

Hope someone can help me to answer

**Comment by almic** [comment]
Currently this issue makes no sense, I can tell English isn't your language. Language barriers really make things difficult! However...

This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.
