### ISSUE TITLE
How to show the value of the X axis as a decimal

### ISSUE THREAD

**Issue by v515527946** [PhilJay/MPAndroidChart#3857]
Now I get a problem ,I want to get some points whose value of the X axis is not a int ,such as a float and so on . However ,the Entry only gives one method like entry(float y, int x). How can I solve the problem,Thanks!

**Comment by almic** [comment]
This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.

In this case, `AxisValueFormatter` does exactly what you want.
