### ISSUE TITLE
Resetting the axis after adding new data

### ISSUE THREAD

**Issue by paamand** [PhilJay/MPAndroidChart#3858]
I have a graph where the data can be scaled (showing values in different units).
When the values are scaled down, the YAxis keeps it's wide range, and the new 'maxY' is not taken into account when the Dataset/Data is notified and the Chart is invalidated.

The bug is due to the Data class not updating its minY/maxY members downwards. Only making them wider if needed. And those max/min values are propagated to the Dataset and Chart.

Working on a pull request, but please tell me if I overlooked some functionality.
Also, this is a bit related to the unsupported 'dynamic data' topics.

**Comment by almic** [comment]
After reviewing the code in `DataSet` class, I can confirm that calling `calcMinMax()` will indeed update the min and max values correctly. It is called inside `notifyDataSetChanged()`.

As it currently stands, the problem you describe is logically impossible if you notify the data sets and chart correctly.
