### ISSUE TITLE
I want to display piechart data from activity using recyclerview

### ISSUE THREAD

**Issue by sainadh9** [PhilJay/MPAndroidChart#3861]
P;lease help me how to create multiple pie charts the data should display in activity without model class

**Comment by almic** [comment]
> without model class

If you mean "without the example class" called `ListViewMultiChartActivity.java`, then I cannot help you.

You should really look at the example activities. I don't understand why so many people open an issue and expect an answer when the answer is literally in the example app. A RecylcerView is very similar to a ListView, you just have to learn how to use it. I didn't know what a RecyclerView even was at one point, but then I did some research and learned everything about it.

*Come on, people! At least TRY before opening an issue!*

**Comment by sainadh9** [comment]
Thanks for the response.i appreciate it.
