### ISSUE TITLE
class AxisRenderer has a wrong arithmetic in computeAxisValues method

### ISSUE THREAD

**Issue by xyz5359502** [PhilJay/MPAndroidChart#3862]
When I set barDataSet width with .4f，computeAxisValues will set a wrong series float number to mEntries.And then I'll get the wrong index in xaxis values array.
In my condition,I get mEntries with [0.0,0.8,1.6,3.2,4.0] after computeAxisValues.
Please fix it,thx!

**Comment by gfdarcy** [comment]
It's correct, but it's only showing x-axis gridlines for every second value. I've asked in another thread how to control which x-axis gridlines are drawn, but I'm awaiting a response.

**Comment by almic** [comment]
@xyz5359502 your description is quite difficult to read
@gfdarcy In that case, I'll answer both of those.

`setGranularity()` allows you to specify the steps that gridlines are drawn. You probably want to use a value of `1`.
