### ISSUE TITLE
Suggestion: use 9-patch for the "custom_marker_view.xml" file in the sample

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [PhilJay/MPAndroidChart#3863]
You don't have to use a layout for this. I'm talking about this file:

```
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="wrap_content"
    android:layout_height="40dp" android:background="@drawable/marker2">

    <TextView
        android:id="@+id/tvContent" android:layout_width="wrap_content" android:layout_height="wrap_content"
        android:layout_centerHorizontal="true" android:layout_marginLeft="5dp" android:layout_marginRight="5dp"
        android:layout_marginTop="7dp" android:ellipsize="end" android:singleLine="true" android:text=""
        android:textAppearance="?android:attr/textAppearanceSmall" android:textColor="@android:color/white"
        android:textSize="12dp"/>

</RelativeLayout>

```

You can convert the `marker2` file to be 9-patch, and instead of a `RelativeLayout` use just the `TextView`, with its background set to the new 9-patch file.

**Comment by almic** [comment]
I'm not familiar with 9-patch, but I know it's in the `drawable` space.

The current implementation is just fine, it also uses the better known layout files. Changing this will only further complicate the code and make it harder for others who want to mimic this effect.

**Comment by AndroidDeveloperLB** [comment]
It's not fine, because this type of content is best suited for 9-patch, as it covers a TextView around it. That's a very classic example of when to use 9-patch.

Using the current implementation, the triangle of the "marker2.file" will be distorted the larger the content is, and when it's small, it won't need so much empty space.

See:

![image](https://user-images.githubusercontent.com/5357526/39676964-076aa2ca-517c-11e8-8969-e1c82524e454.png)

![image](https://user-images.githubusercontent.com/5357526/39676970-263abe7e-517c-11e8-8ba6-fb72e4599cc3.png)

And it's not more complicated. It's actually simpler, having the padding within the image itself, keeping correct image content. One less view, meaning less code, and same number of files. And, the 9-patch file will take less space, because there is a lot of repeating content in it.

So, what you get:

1. Same files count, less code.
2. no distorted content
3. constant padding on the sides of the text.
4. For short text, no huge empty text
5. Less space for a simple image file.

**Comment by almic** [comment]
Just as a reminder, you are talking about the example app. I stand by my decision that this is a non-issue, and the current implementation is fine. However, this doesn't necessarily mean a pull request would be outright denied. However, this is such a small detail that it would only be noticeable with large text, as you demonstrated with the entire latin alphabet. Even then, it doesn't look *that* bad.

If you really want to, make a pull request and describe why it makes sense. From your reply, you already have a pretty strong argument in favor of 9-patch.

**Comment by AndroidDeveloperLB** [comment]
@almic Seeing that the TextView has `android:layout_marginLeft="5dp"` and `android:layout_marginRight="5dp"` shows that whoever created it, wanted that this would be the space on the sides. 
This fails because of the current implementation. 

You still haven't shown why it shouldn't have 9-patch. I think it's the most classical case of using it : container with a background image that has dynamic content within.

Looking at the current implementation, that's just not the way to do it.

**Comment by almic** [comment]
@AndroidDeveloperLB my argument was never against 9-patch, it was in disagreement that this should be changed at all. But like I said:

> If you really want to, make a pull request and describe why it makes sense. From your reply, you already have a pretty strong argument in favor of 9-patch.
