### ISSUE TITLE
Where is the jar file?

### ISSUE THREAD

**Issue by Angus2016** [PhilJay/MPAndroidChart#3864]
there is only source code?

**Comment by MGaetan89** [comment]
I don't think the project is available as a jar.
You should rather use it as a dependency in your project.

**Comment by youyiyang** [comment]
use New-->Import Module to use it.

**Comment by MGaetan89** [comment]
Found it here: https://jitpack.io/com/github/PhilJay/MPAndroidChart/v3.0.3/MPAndroidChart-v3.0.3.jar (see #2428 for the original answer).

**Comment by almic** [comment]
Use it as a gradle dependency, please.
