### ISSUE TITLE
How to add data dynamically To stacked chart.But I am getting single bar graph.Please solve my issue

### ISSUE THREAD

**Issue by sainadh9** [PhilJay/MPAndroidChart#3867]
for (int j = 0; j < s.length; j++) {
            Log.d("checklength", j + "");

            float value1 = converted[j];
            float value2 = notconverted[j];
            float value3 = notcontacted[j];
            Log.d("getvalue", value1 + " " + value2 + " " + value3);
            yVals.add(new BarEntry(j, new float[]{value1, value2, value3}));
            yVals.add(new BarEntry(4, new float[]{10.0f, 20.0f, 30.0f}));
            Log.d("checky", yVals.add(new BarEntry(j, new float[]{converted[j], notconverted[j], notcontacted[j]})) + "");
            BarDataSet set1 = new BarDataSet(yVals, "");
            ArrayList<IBarDataSet> dataSets = new ArrayList<IBarDataSet>();
            dataSets.add(set1);
            BarData data = new BarData(dataSets);
            data.notifyDataChanged();
            msc_managerDashboard_empStats.setData(data);

        }

        Log.d("yvalues", yVals + "");

        msc_managerDashboard_empStats.setFitBars(true);
        msc_managerDashboard_empStats.notifyDataSetChanged();
        msc_managerDashboard_empStats.invalidate();

**Comment by almic** [comment]
I'm not going to try to debug your code. Only you can do that.

Check the multiple stacked bar chart example activities in the example app. I'm sure the exact code you are looking for is in there.
