### ISSUE TITLE
negative number cause pie chart display incompletely , especially in two numbers, one of which is negative.

### ISSUE THREAD

**Issue by iamzj** [PhilJay/MPAndroidChart#3870]
![piechart bug](https://user-images.githubusercontent.com/21978982/37508640-ee67adf6-292e-11e8-86f2-5cd3bbfe6db1.png)

**Comment by youyiyang** [comment]
I tried your issue in my code that have 4 categories and the pie chart indeed had some problems. I think the pie chart categories' data need all positive numbers, so why not make your negative number positive firstly?

**Comment by almic** [comment]
Why are you using **NEGATIVE** numbers in a **PIE CHART**?

Just think about it for a second: *What does a Pie Chart show?*
Answer: *The parts of a whole*

You don't have negative values in Pie Charts, it makes no sense.
