### ISSUE TITLE
Value labels disappearing on zoom

### ISSUE THREAD

**Issue by c00lius** [PhilJay/MPAndroidChart#3871]
If you zoom in on a HorizontalBarChart, value labels will dissappear. This even happens in the demo app. The labels will reappear only if you scroll back to zero.

Zoomed out and working:
<img width="473" alt="screen shot 2018-03-17 at 11 41 44" src="https://user-images.githubusercontent.com/14002522/37554409-49e7a93e-29d8-11e8-8af6-7e7bfdd54619.png">

Zoomed in and slightly offset:

<img width="475" alt="screen shot 2018-03-17 at 11 41 38" src="https://user-images.githubusercontent.com/14002522/37554414-5d65f290-29d8-11e8-8048-d761ede6ea0a.png">

Zoomed in and scrolled to zero:
<img width="473" alt="screen shot 2018-03-17 at 11 41 44" src="https://user-images.githubusercontent.com/14002522/37554421-6e44a372-29d8-11e8-8304-73f7a488bc73.png">

**Comment by almic** [comment]
This was **intentionally** built-in, and if you think about it for a few seconds, it makes sense to hide the value labels when the data gets really close together.

**Comment by zahid--ali** [comment]
@almic  and @PhilJay  any update on this?
Can you purpose any custom solution?
