### ISSUE TITLE
HorizontalBarChart not draw start from zero

### ISSUE THREAD

**Issue by DaisyJin1** [PhilJay/MPAndroidChart#3873]
![horizonbarchart](https://user-images.githubusercontent.com/29156312/37633989-850da3a2-2c2f-11e8-89cf-421253c68ac0.jpg)
HorizontalBarChart not draw start from zero

**Comment by almic** [comment]
There is not enough detail here to know what could be causing this problem. Could you please **open a new issue** and better describe *what* you are doing and then I could help you.

**Comment by SJeagery** [comment]
“chart.getAxisLeft().setAxisMinimum(0)"，maybe work

**Comment by sattarsh** [comment]
How to MPandroidChart HorizontalBarChart not start zero

**Comment by Abdallah4021** [comment]
> setAxisMinimum
U need to set them Manually like this: 


val leftAxis = barChart.axisLeft
val rightAxis = barChart.axisRight
leftAxis.setAxisMinimum(0f)
rightAxis.setAxisMinimum(0f)
