### ISSUE TITLE
How to use LineData with BarChart

### ISSUE THREAD

**Issue by ubarua123** [PhilJay/MPAndroidChart#388]
In your documentation you have explained how to draw <code>Limit Lines</code> using 
<code>LineData</code> and they are supported in <b>BarChart</b>
But I can set only BarData in the  <b>BarChart</b>, so how do I use <code>LineData</code> in a barchart?
Also is there a way that I can specify the length of the line to extend to only a couple of bars?
Also <code>LineData ld = new LineData(...);</code> in this code, what are the expected parameters?

**Comment by PhilJay** [comment]
Which version of the library are you using?
