### ISSUE TITLE
MPAndroidChart inside Volley onResponse

### ISSUE THREAD

**Issue by crushman1** [PhilJay/MPAndroidChart#3887]
Hi, i have not been able to successfully run this library inside a volley onResponse method. I am trying to get json data and add it to the pieEntry. 
Has any one been successful with this?
I place the full question on stackoverflow in the hopes of a fix : https://stackoverflow.com/questions/49477368/mpandroidchart-inside-volley-onresponse

**Comment by MGaetan89** [comment]
It looks like you got your answer on StackOverflow.
Can you close this issue?

**Comment by crushman1** [comment]
Indeed.
