### ISSUE TITLE
XAxis Lables there is no padding between XAxisLine 

### ISSUE THREAD

**Issue by youssefshaaban** [PhilJay/MPAndroidChart#3888]
<img width="188" alt="capture" src="https://user-images.githubusercontent.com/13057499/37916531-58fef71a-311c-11e8-9f5c-fe48f1e60f1d.PNG">

my code to draw line chart 
` LineDataSet lineDataSet = new LineDataSet(entries, null);
        lineDataSet.setValueTextSize(10);
        lineDataSet.setDrawValues(false);
        lineDataSet.disableDashedLine();
        lineDataSet.setValueTextColor(Color.parseColor("#000000"));
        lineDataSet.setDrawFilled(true);
        lineDataSet.setDrawVerticalHighlightIndicator(true);
        lineDataSet.setLineWidth(3);
        lineDataSet.setDrawValues(true);
        int x[] = {Color.parseColor("#B0ADB4")};
        lineDataSet.setColors(x);
        lineDataSet.setCircleColor(Color.parseColor("#EF4A5B"));
        lineDataSet.setCircleColorHole(Color.parseColor("#ffffff"));
        //lineDataSet.setHighlightEnabled(true); // allow highlighting for DataSet
        //lineDataSet.setFillColor(Color.parseColor("#EB5060"));
        // set this to false to disable the drawing of highlight indicator (lines)
        //lineDataSet.setDrawHighlightIndicators(true);
        lineDataSet.setDrawCircleHole(true);
        lineDataSet.setDrawFilled(false);
        lineDataSet.disableDashedLine();
        lineDataSet.setValueTextSize(15f);
        lineDataSet.setAxisDependency(YAxis.AxisDependency.LEFT);
        lineDataSet.setCircleSize(5f);
        ArrayList<LineDataSet> lineDataSets = new ArrayList<>();
//        Entry e;
        lineDataSets.add(lineDataSet);
        ///////
        lineDataSets.add(lineDataSet);
        LineData lineData = new LineData(lables, lineDataSets);
        lineData.setValueTextSize(12);
        // lineChart Properties
        lineChart.setData(lineData);
        lineChart.getXAxis().setTextSize(15);
        lineChart.setDescription("Date");
        lineChart.setPadding(10, 0, 10, 10);
        lineChart.setGridBackgroundColor(Color.parseColor("#ffffff"));
        lineChart.setDrawGridBackground(false);
        lineChart.getLegend().setEnabled(false);
        lineChart.setDoubleTapToZoomEnabled(false);
        lineChart.setDrawBorders(false);
        lineChart.getAxisLeft().disableGridDashedLine();
        lineChart.getXAxis().setAxisLineColor(Color.parseColor("#ACACAE"));
        YAxis yAxis = lineChart.getAxisLeft();
        YAxis yAxis2 = lineChart.getAxisRight();
        //lineChart.getXAxis().setSpaceBetweenLabels(40);
        yAxis.disableGridDashedLine();
        yAxis2.disableGridDashedLine();
        yAxis2.setEnabled(false);
        yAxis.setAxisLineWidth(3);
        yAxis.mEntryCount = 10;
        //yAxis.setTypeface(); // set a different font
        yAxis.setTextSize(12f); // set the text size
        //yAxis.setAxisMinimum(0f); // start at zero
        //yAxis.setAxisMaximum(100f); // the axis maximum is 100
        yAxis.setTextColor(Color.BLACK);
        yAxis.setAxisLineColor(Color.parseColor("#ACACAE"));
        yAxis.enableGridDashedLine(10, 10000, 10);

        /////// XAxis ////////
        XAxis xAxis = lineChart.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setDrawGridLines(false);
        xAxis.setAxisLineColor(Color.TRANSPARENT);
        xAxis.setSpaceBetweenLabels(0);
        xAxis.setLabelRotationAngle(angle);
        xAxis.disableGridDashedLine();
        xAxis.removeAllLimitLines();
        xAxis.setGridColor(Color.parseColor("#000000"));
        xAxis.setAxisLineWidth(3);
`

**Comment by almic** [comment]
`setAxisMinimum()`
