### ISSUE TITLE
How can I set a line border (for a PieChart)?

### ISSUE THREAD

**Issue by sdeff** [PhilJay/MPAndroidChart#389]
I would like to have a white PieChart segment on white background. But I can't see it as long as I can't find a way to set a different colored line border.

As I couldn't find a suitable method I wonder if can somehow set a line border?

**Comment by PhilJay** [comment]
I am not sure what you mean. Can you be more specific?

**Comment by sdeff** [comment]
Thanks for your quick reply. I'm trying to set a line border like this:
![lineborder](https://cloud.githubusercontent.com/assets/2885756/6414699/ac11c2b4-be99-11e4-8899-524e942234f0.png)

**Comment by PhilJay** [comment]
Allright. Drawing a border line on the chart is not supported by default, you will have to implement that yourself.

As for the other things.

Simply add two slices, one colored grey with value 25, one colored white with value 75.
