### ISSUE TITLE
LineChart 如何设置数据距起点一段距离，不是从0开始

### ISSUE THREAD

**Issue by baohexin** [PhilJay/MPAndroidChart#3890]

**Comment by baohexin** [comment]
![20180327161012](https://user-images.githubusercontent.com/21255413/37954822-81bcb512-31d9-11e8-9a22-997c515ee66e.png)
类似于组合图中的折线图

**Comment by baohexin** [comment]
ok

**Comment by baohexin** [comment]
现在是可以设置，但是x轴数据会出现错乱，我是用组合图然后不显示柱状图解决的，但是这个单独LineChart还是没有解决，跪求大神指点。。。

**Comment by baohexin** [comment]
![20180403110159](https://user-images.githubusercontent.com/21255413/38227013-baabdb64-372e-11e8-97fb-040d3a39d996.png)

**Comment by almic** [comment]
Did you figure this out?

If not, look at `setAxisMinimum()`

**Comment by XuHX** [comment]
怎么实现啊

**Comment by yangzhenjie0** [comment]
您现在解决知道方法了吗

**Comment by XuHX** [comment]
不知道

**Comment by XuHX** [comment]
> 您现在解决知道方法了吗


lineChart.getXAxis().setAxisMinimum(-0.5f);
lineChart.getXAxis().setAxisMaximum(dataList.size()-0.5f);

**Comment by memoryjs** [comment]
> > 您现在解决知道方法了吗
> 
> lineChart.getXAxis().setAxisMinimum(-0.5f);
> lineChart.getXAxis().setAxisMaximum(dataList.size()-0.5f);

It works for me, but a little diffenrent, mine is 
lineChart.getXAxis().setAxisMinimum(-5f);
lineChart.getXAxis().setAxisMaximum(dataList.size()+0.5f);

**Comment by XuHX** [comment]
就是这样设置就可以了啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月6日(星期三) 下午3:54
收件人:&nbsp;"PhilJay/MPAndroidChart"<MPAndroidChart@noreply.github.com&gt;;
抄送:&nbsp;"谣言"<1211893391@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [PhilJay/MPAndroidChart] LineChart 如何设置数据距起点一段距离，不是从0开始 (#3890)



  
您现在解决知道方法了吗
  
lineChart.getXAxis().setAxisMinimum(-0.5f);
 lineChart.getXAxis().setAxisMaximum(dataList.size()-0.5f);
  
It works for me, but a little diffenrent, mine is
 lineChart.getXAxis().setAxisMinimum(-5f);
 lineChart.getXAxis().setAxisMaximum(dataList.size()+0.5f);
