### ISSUE TITLE
BarChart需要点击一下控件。数据才能加载出来。

### ISSUE THREAD

**Issue by a599219798** [PhilJay/MPAndroidChart#3891]
我的结构是Activity上面加载Fragment。Fragment上面加载Fragment1 和 Fragment2。Barchar放在Fragment2上面。现在BarChart需要点击才会显示显示出来。
操作视频：https://pan.baidu.com/s/1IOgRG2OdtEHusYA4Ac9zCA
以下是代码
@BindView(R.id.day_chart)
    BarChart dayChart;

    private DeviceList deviceList;

    private CommonAdapter selectorApater;
    private BottomSheetDialog sheetDialog;
    private HashSet<DeviceInfo> hashSet;

    @Override
    protected int getContentLayout() {
        return R.layout.fragment_report_gas;
    }

    @Override
    protected void initView() {

        hashSet = new HashSet<>();

        requestGasCollectReport();
        getDeviceList();

        initDayChartView();

        linearLayout.setOnClickListener(v -> {
            ArrayList<BarEntry> dayVals = new ArrayList<BarEntry>();
            for (int i = 0; i < 5; i++) {
                BarEntry barEntry = new BarEntry(i, i);
                dayVals.add(barEntry);
            }

            BarDataSet set;
            set = new BarDataSet(dayVals, "");
            set.setDrawIcons(false);
            set.setColor(getResources().getColor(R.color.chart_color));
            ArrayList<IBarDataSet> dataSets = new ArrayList<IBarDataSet>();
            dataSets.add(set);

            BarData data = new BarData(dataSets);
            data.setValueTextSize(10f);
            data.setBarWidth(0.9f);

            dayChart.setData(data);

//            showCustomDevicesSelector();
        });
    }

    private void initDayChartView() {
        dayChart.setOnChartValueSelectedListener(this);
        dayChart.setDrawBarShadow(false);
        dayChart.setDrawValueAboveBar(true);
        dayChart.getDescription().setEnabled(false);
        dayChart.setMaxVisibleValueCount(0);
        dayChart.setDragEnabled(false);
        dayChart.setScaleEnabled(false);
        dayChart.setDrawGridBackground(false);

        IAxisValueFormatter xAxisFormatter = new DateAxisValueFormatter(new ArrayList<>());
        XAxis xAxis = dayChart.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setDrawGridLines(false);
        xAxis.setGranularity(1f);
        xAxis.setLabelCount(4);
        xAxis.setValueFormatter(xAxisFormatter);

        YAxis leftAxis = dayChart.getAxisLeft();
        leftAxis.setDrawGridLines(false);
        leftAxis.setLabelCount(6, false);
        leftAxis.setSpaceTop(10f);
        leftAxis.setAxisMinimum(0f);

        YAxis rightAxis = dayChart.getAxisRight();
        rightAxis.setEnabled(false);

        Legend l = dayChart.getLegend();
        l.setEnabled(false);

//        XYMarkerView mv = new XYMarkerView(this.getContext(), xAxis.getValueFormatter());
//        mv.setChartView(dayChart);
//        dayChart.setMarker(mv);
    }

找到问题了。忘了写上  invalidate这个方法了。这个方法类似重绘

**Comment by CHANDRASHEKHAR-GS** [comment]
Thanku....
