### ISSUE TITLE
How to add padding to the data shown?

### ISSUE THREAD

**Issue by FrancoSabadini** [PhilJay/MPAndroidChart#3893]
I need to add a padding between the sides of the screen and the data being shown (but the zero line has to go all the way to the edge of the screen). How can I do this? (see attached pic)

<img width="385" alt="screen shot 2018-03-28 at 11 47 31 am" src="https://user-images.githubusercontent.com/5099645/37999163-1cc534ea-327e-11e8-8450-0d1d5954cf9d.png">

I was able to add padding on the right side by using `setVisibleXRangeMinimum()` but I can't figure out how to either center the data or also add padding on the left side.

**Comment by MGaetan89** [comment]
Have you tried one of the following methods?
https://github.com/PhilJay/MPAndroidChart/blob/6fbd49276168b6270a85cc8ddb2d655b0afaa1f2/MPChartLib/src/main/java/com/github/mikephil/charting/charts/Chart.java#L1071-L1141

In particular `setExtraLeftOffset(float)` and `setExtraRightOffset(float)`.

**Comment by FrancoSabadini** [comment]
yes I already tried that @MGaetan89, like I said in my description "the zero line has to go all the way to the edge of the screen" which the methods you mentioned don't allow.

**Comment by almic** [comment]
The library does allow for this, but the exact method signature escapes me right now. You're looking for an axis-specific method, something called `setAxisMinimum()`

You'll probably be setting the Y axis minimum to `0` to push the chart all the way down. You can do the same for the X axis, making the minimum **slightly** lower than the current lowest value, so as to not show the label for the next smaller value (if you need to worry about that).
