### ISSUE TITLE
getFormattedValue 返回数据异常？

### ISSUE THREAD

**Issue by diyhlgc** [PhilJay/MPAndroidChart#3894]
ok

**Comment by buketanwan** [comment]
怎么解决的，请问下这个方法的value是根据什么来的,谢谢

**Comment by diyhlgc** [comment]
你可以看一下源码，我看了一些 。但是不太懂只是大概。value值 根据传入的x轴最大值/你设置的分成几段（如果没有设置的话有默认值）=每段跨越的长度  根据这个传给你的value。最后我也没有解决，只是暂时放下，没办法。可以改源码。改源码的话 是可以的，但是还是有点小问题。所以就放弃了
