### ISSUE TITLE
PieChart: Use slice color as value line color

### ISSUE THREAD

**Issue by sembozdemir** [PhilJay/MPAndroidChart#3897]
![PieChart](https://i.snag.gy/zrOmTf.jpg)

I want to get this result but only one color can be set for value lines. It would be better to have an option to use slice color as value line color.

**Comment by sembozdemir** [comment]
I added this method. Look at my [PR](https://github.com/PhilJay/MPAndroidChart/pull/3898).

**Comment by luckerbai** [comment]
Is there any method just show one value line when clicked, not show all values lines? thank you.

**Comment by hxkdidi** [comment]
how can i get this code from your pr? @sembozdemir

**Comment by abdulBasitWaqas07** [comment]
Can you please share the full code? by using that code you are showing piechart like this? thanks in advance
