### ISSUE TITLE
Radar chart axis range

### ISSUE THREAD

**Issue by M1ntcraft3r** [PhilJay/MPAndroidChart#3899]
Is it not possible to use different ranges for the axis on the radial chart? 
I'd love to be able to use it as a sort of comparison.
Say I have 4 sets of data with 4 values each I'd like to compare. However, vale 1 has a range of 0-3, value 2 55-80 etc.
This is possible but the range will be the same for all axis, resulting in the small values almost looking meaningless...
Ta

**Comment by almic** [comment]
This limitation is rough, however adding a way for MPAndroidChart to do this automagically for you is out of scope.

The simplest, and best solution, is to manually scale up those smaller values, and use a value formatter to change them back to the original values, if you are using value labels...

However, a Radar chart is best suited to compare different values without necessarily seeing their actual value, which is excellently shown in the example `RadarChartActivity.java` in the example app.

I would also challenge you to think about the way such a chart would look. As a user, it could be overwhelming to see 4 data sets on a single radar chart, and be useless for the core purpose of charts: to give people a *simple* way to *simply* see data at a quick glance on a *simple* chart. Did I mention making your charts *simple*?

I could go on about good UI design, but I'll leave it for now.
