### ISSUE TITLE
NullPointerException：com.github.mikephil.charting.charts.PieChart.prepareContentRect(PieChart.java:322)

### ISSUE THREAD

**Issue by Tanlet** [PhilJay/MPAndroidChart#39]
When you don't use the method ‘setData’，so the expception appear.
So I can't see the graphical layout on the eclipse.
I solve it like:
PieChart.prepareContentRect() 
        float shift = 18f;
        if (mCurrentData!=null) {
            shift=((PieData) mCurrentData).getDataSet().getSelectionShift();
        }

**Comment by kumark86** [comment]
When try to draw piechart we got the following error. Please resolve the issue.


android.graphics.Canvas.<init>
in Canvas.java, line 136

Reason: java.lang.NullPointerException

1 android.graphics.Canvas.<init> 	Canvas.java, line 136
2 	com.github.mikephil.charting.renderer.PieChartRenderer.drawData 	PieChartRenderer.java, line 100
3 	com.github.mikephil.charting.charts.PieChart.onDraw 	PieChart.java, line 96
4 	android.view.View.draw 	View.java, line 14728
5 	android.view.View.getDisplayList 	View.java, line 13588
6 	android.view.View.getDisplayList 	View.java, line 13635
7 	android.view.View.draw 	View.java, line 14430
8 	android.view.ViewGroup.drawChild 	ViewGroup.java, line 3252
9 	android.view.ViewGroup.dispatchDraw 	ViewGroup.java, line 3070
10 	android.view.View.getDisplayList 	View.java, line 13580
11 	android.view.View.getDisplayList

**Comment by nesifazal** [comment]
I get the same error as top when i change the orientation or when i click the back button. :(
