### ISSUE TITLE
Removing entry Labels from PieChart

### ISSUE THREAD

**Issue by joosepjarve** [PhilJay/MPAndroidChart#3903]
![image](https://user-images.githubusercontent.com/17499637/38162530-435381b0-34eb-11e8-9f67-aa421bd51413.png)

How to remove these entries? I've tried pieChart.setDrawEntryLabels(false) and pieChart.setDrawSliceText(false) and neither of them work.

**Comment by almic** [comment]
Go back to the documentation and look again. You can definitely accomplish this, and its even inside an example activity for the example app.

**Comment by yurimachioni** [comment]
PieDataSet::setDrawValues(false)
