### ISSUE TITLE
How can I place the xAxis value at center of every group?( in multi-barchart )

### ISSUE THREAD

**Issue by Flying-Bullet** [PhilJay/MPAndroidChart#3908]
![1](https://user-images.githubusercontent.com/23204280/38193036-7d9e73b2-36a2-11e8-9432-04eae39c4e04.jpg)

**Comment by baohexin** [comment]
like this?@Flying-Bullet

![20180403110856](https://user-images.githubusercontent.com/21255413/38227189-a546b518-372f-11e8-883a-676e6e20a931.png)

**Comment by Flying-Bullet** [comment]
Yes，sorry for the upload picture, following is my result，there aren't anyway to solve this probelm still, please help me，Thanks

![12](https://user-images.githubusercontent.com/23204280/38478139-6b814ce4-3be9-11e8-9fc3-e6b3cc42b60a.jpg)

**Comment by Flying-Bullet** [comment]
Besides，I have already set the xAxis.setCenterAxisLabels(true);
![image](https://user-images.githubusercontent.com/23204280/38478208-d154872a-3be9-11e8-8485-18dd1e3944de.png)

**Comment by almic** [comment]
Perhaps `setCenterAxisLabels(true)` is causing this?

**Comment by RobertZagorski** [comment]
I guess, there's a bigger problem with `setCenterAxisEnabled`. Putting reference another issue:
#3810

**Comment by Flying-Bullet** [comment]
@almic @RobertZagorski 
    Thanks your help very much, And sorry for late response. I have solved this probelm by override the function **groupBars(float fromX, float groupSpace, float barSpace)**. After debuging, I find all points' xValue will be calculated by this function, the most important is **groupSpace + barSpace + barWidth * 2 = GranularityValue**
