### ISSUE TITLE
X-Axis labels do not load properly

### ISSUE THREAD

**Issue by srdivya** [PhilJay/MPAndroidChart#3911]
I used setValueFormatter to return labels.get((int) value)) in order for months to be displayed as x-axis values. But the values from the ArrayList labels are not getting loaded properly. On debugging I found that the float values being passed to setValueFormatter is the culprit. The values loaded for an array of size 12 are as seen in the attachment. I found a temporary workaround for now. Please fix this.
![whatsapp image 2018-04-02 at 5 10 10 pm](https://user-images.githubusercontent.com/22197058/38219751-1a415f8e-36a5-11e8-8802-a94fe442758f.jpeg)

**Comment by AlekseyLitvinov** [comment]
`xAxis.setGranularity(1f)`

**Comment by almic** [comment]
@AlekseyLitvinov solution is the way to go. Closing
