### ISSUE TITLE
How to change style of Axis and Legend Text?

### ISSUE THREAD

**Issue by laxmimerit** [PhilJay/MPAndroidChart#3912]
Hello,
I wanted to do some styling in Axis labels and legends such as Bold and Italic but I could not find any suitable method. Can anyone here suggest some?

**Comment by vidsag** [comment]
You can achieve it by using `chart.legend.typeface`

**Comment by laxmimerit** [comment]
Thanks. Of course my bad. I was looking something setBold, Italic kind of things. Anyway thanks for the answer.
