### ISSUE TITLE
How can I change the vertical position of y-axis values?

### ISSUE THREAD

**Issue by roncbird** [PhilJay/MPAndroidChart#3914]
I simply want to change the position of the y-axis values above the horizontal grid lines. I can move them into the graph with leftAxis.setPosition(YAxis.YAxisLabelPosition.INSIDE_CHART), but there doesn't seem to be any way to move their position vertically. 

Here is what I am trying to achieve:
![yaxis_label_position](https://user-images.githubusercontent.com/6894360/38252603-d6a2fad6-3711-11e8-8020-802f6baff42d.png)

Here is what it currently looks like:
![y_axis_label_position](https://user-images.githubusercontent.com/6894360/38252614-df6c39a2-3711-11e8-972b-f9bc26a426bc.png)

Is it possible to move the position of the y-axis labels vertically either up or down? Also, I'm trying to figure out how to show only certain y-values within the graph, for example "Average" and "You" which can be seen in the first screenshot. I also want to show a vertical grid-line up the circle seen in the screenshot. It would be greatly appreciated if someone could point me in the right direction in how to create this custom graph using MPAndroidChart library.

**Comment by OrkhanAlikhanov** [comment]
This is the exact question I have. **How can we shift the gird?**
Related issue #3091

**Comment by almic** [comment]
I know you can do this with Bar Charts, so I'm sure you can also do it with the Line chart.

try `setCenterAxisLabels()` on your axis objects

**Comment by sharmanirudh** [comment]
Use YOffset of YAxis to position the grid lines
`leftAxis.setYOffset(-7f);`

**Comment by aadi231** [comment]
<
<img width="372" alt="Screenshot 2023-12-12 at 1 16 38 PM" src="https://github.com/PhilJay/MPAndroidChart/assets/52204710/7805f3c6-dc30-4ce5-965b-c9f65bf738f7">

I want to draw a limit line upto a specific position in bar chart. As you guys can see in the attached image. dotted line from x-axis and y-axis to particular point on graph. Can you guys help me out with this. How i can do that. @roncbird i can see in you image king of same thing u had done. can you please help me out with this. 

@PhilJay you can help me out how i can do that. 

Thanks to all in advance. Waiting for the response from any one can help.
