### ISSUE TITLE
CandleStick chart "setBarSpace()" not working 

### ISSUE THREAD

**Issue by afinas-em** [PhilJay/MPAndroidChart#3915]
I am creating a CandleStick chart
from API: https://min-api.cryptocompare.com/data/histoday?fsym=BTC&tsym=USD&limit=10

When I creating the chart with the count of values as X-axis, There is no problem ( "ploat_point.add(new CandleEntry(i,high,low,open,close);" in for loop ).

But when I use "ploat_point.add(new CandleEntry(time,high,low,open,close);" in for loop, And parse X-axis values using my custom function.
i.e : xAxis.setValueFormatter();
This time it is showing the graph only when the paint style is set to "Paint.Style.FILL_AND_STROKE", But It does not increasing the bar size with "candleDataSet.setBarSize()" . It depending only the "candleDataSet.setShadowWidth()".

I need X-axis as time and bar size is more than shadow please help me.

**Comment by almic** [comment]
You have to notify both the dataset and the chart that it's data has changed, then invalidate the chart so it renders with updated data. Please check the documentation and example project. The solution is out there, please look for it before opening an issue.

**Comment by pratikdozee** [comment]
CandleStickChart  -> set1.setBarSpace(1f)  is not working properly. I'm getting only two bar sizes. One is default and another one is very thin no matter what value I set here.

I want to change width of Increasing Bar (or, decreasing bar). Is there any other method than setting bar space?
