### ISSUE TITLE
Line Chart Movable/Dragable when touch on a point on chart

### ISSUE THREAD

**Issue by nomizodiac** [PhilJay/MPAndroidChart#3916]
I want to implement a line chart exactly like shown in gif? Is there any callback where i can point where user has touch on linechart and then draw a marker on that point and then user can drag/move

![gcoj0](https://user-images.githubusercontent.com/3611309/38293666-d6287342-3801-11e8-8d0a-1366e97682cf.gif)

**Comment by almic** [comment]
This is ***way*** out of scope for this project. Cool idea, but definitely no.

If you want something like that, I would first recommend learning some basic algebra and do that yourself. Once you understand the math of that effect, it shouldn't be hard to track touch points inside a view and update the line function constants depending on the X and Y location of the touch.

**Comment by LivioGama** [comment]
@nomizodiac did you manage to do it, or did you find some library for it ?
