### ISSUE TITLE
Piechart in chart below line remove, plz solution

### ISSUE THREAD

**Issue by twinkleSiya** [PhilJay/MPAndroidChart#3917]
![screenshot_2018-04-05-16-32-29 1](https://user-images.githubusercontent.com/36469322/38362878-07de51ba-38f0-11e8-8117-ddb8b9bc5012.png)

see this screenshot and give me solution asap

**Comment by MGaetan89** [comment]
Have you tried `chart.getLegend().setEnabled(false)`?

**Comment by MGaetan89** [comment]
Can you close the issue of it solved your problem?

**Comment by MGaetan89** [comment]
@twinkleSiya or @almic, can you close this issue, as it is fixed?
