### ISSUE TITLE
how to remove background lines like grid in the chart?

### ISSUE THREAD

**Issue by badarshahzad** [PhilJay/MPAndroidChart#3918]
Hi 
  I want to remove the background grey lines (like grid in grey color) in the chart do you know how to remove these lines? I found in the docs for LineChart this method `lineChartDownFill.setDrawGridBackground(false);`  but its not working does would you like to tell what to do? 

Picture:
![photo](https://user-images.githubusercontent.com/19945367/38382320-091a35ac-3923-11e8-9463-89c464156a55.jpeg)

Thank you

**Comment by gibels-and-bits** [comment]
+1 setDrawGridBackground(false) does not work for me either

**Comment by badarshahzad** [comment]
I am closing this issue as I found this solution and I have answered the question here  :+1: https://stackoverflow.com/questions/31263097/mpandroidchart-hide-background-grid/49691717#49691717.

**Comment by shaon2016** [comment]
//Hide background grid view
     ```
        chart.getXAxis().setDrawGridLines(false);
        chart.getAxisLeft().setDrawGridLines(false);
        chart.getAxisRight().setDrawGridLines(false);
     ```
