### ISSUE TITLE
Why lineChart.setViewPortOffsets(0,0,0,0) disable the xaxis and yaxis

### ISSUE THREAD

**Issue by badarshahzad** [PhilJay/MPAndroidChart#3923]
Hi 
   Would you like to enlighten me about this when `lineChart.setViewPortOffsets(0,0,0,0)` disable the xaxis and yaxis values. 

when this line exist `lineChart.setViewPortOffsets(0,0,0,0)` the chart look like this
![bug](https://user-images.githubusercontent.com/19945367/38459261-05fe032c-3ac1-11e8-8348-e146125aa30f.png)

when I remove this line `lineChart.setViewPortOffsets(0,0,0,0)` the chart look like this
![solve](https://user-images.githubusercontent.com/19945367/38459270-13cd2df2-3ac1-11e8-9b98-34357cbbc044.png)

**Comment by almic** [comment]
*There is no question in your issue,* despite it being obvious you are looking for an answer to something.

I'll take a wild guess and say: **yes**. This is correct behavior.
