### ISSUE TITLE
LineData  draw values bug

### ISSUE THREAD

**Issue by happylin0x29a** [PhilJay/MPAndroidChart#3924]
![image](https://user-images.githubusercontent.com/30915794/38464185-bab94996-3b3b-11e8-941d-d915fe797b80.png)
If I don't set the drawing icon to false, there will be problems.

**Comment by MGaetan89** [comment]
What problems?

**Comment by happylin0x29a** [comment]
If I do not turn off the method of drawing icon，dataset doesn't have any data. The program reads dataset's data and will reports the array subscript's transboundary.

**Comment by almic** [comment]
> The program reads dataset's data and will reports the array subscript's transboundary.

Is that even a sentence?

Regardless, this *"bug"* makes no sense. The renderers use that method to determine if it should draw any values or icons. The code to draw value labels and icons are in the same function, but that function is only run when `shouldDrawValues()` returns `true`, that is, either value labels or icons have been enabled.
