### ISSUE TITLE
[Feature Request] Add breaks in chart

### ISSUE THREAD

**Issue by Namnodorel** [PhilJay/MPAndroidChart#3925]
I'd find a feature useful that allowed you to add breaks to a chart, or "skip" certain values on both the X and Y axis. This is very useful when some datapoints are extremely large or when there is, for example on a timeline, no entry for a long time.
I imagine it being something like this: http://www.pptalchemy.co.uk/images/chart3.jpg
but with limit lines instead of weird wiggles in the bar :D

**Comment by almic** [comment]
Something like what you describe, at least in that image, is currently possible (I believe) with two y axes.

However, something as generic as that would be difficult to hard code into the library. It would require at least two new options, a flag to enable this and a threshold parameter. However that alone wouldn't work if the data was too extreme, requiring multiple levels of breaks.

Drawing that on paper is easy, but putting something that objective in code will be a hassle and would probably just end up creating another feature that needs to be maintained yet rarely used.

I really like the idea, but this isn't practical to do automagically. You'll have to check out the dual y axes feature which already exists and manually determine a threshold.
