### ISSUE TITLE
How to set Max and Mean Label in plot 

### ISSUE THREAD

**Issue by laxmimerit** [PhilJay/MPAndroidChart#3927]
Hello
I want to show maximum and minimum data points in chart. How can I do this?

**Comment by ArilesGit** [comment]
Hi,
You could create different data sets for min and max data to give them different appearances (values and shapes).

**Comment by almic** [comment]
You can use `LimitLine` to draw lines on the graph, if you want that. Otherwise, do what ArilesGit said and use multiple data sets.

**Comment by almic** [comment]
You can use `LimitLine` to draw lines on the graph, if you want that. Otherwise, do what @ArilesGit said and use multiple data sets.
