### ISSUE TITLE
Simple BarChart

### ISSUE THREAD

**Issue by wlmirand** [PhilJay/MPAndroidChart#3931]
Dear Phil. First I'd like to thank you for this awesome library. My problem is the following:
I have a `Map<ReferenceDate, Float>` where it stores a value for each Month/Year... for example:

```java
map = new HashMap<>();
map.put(new ReferenceDate(2018,2), 100); //value for Feb 2018
map.put(new ReferenceDate(2018,3), 150); //value for Mar 2018
map.put(new ReferenceDate(2018,4), 200); //value for Apr 2018
```

I need to draw a Bar chart where each bar represents an entry for this map, so I've converted it into a List of BarEntries (which is what the lib expects):

```java
List<BarEntry> entries = new ArrayList<>();
int i = 0;
for (ReferenceDate refDate : map.keySet()) {
    entries.add(new BarEntry(i++, map.get(refDate)));
}
```

now I have a list of entries where X axis will display 0 .... N

Then I did 

```java
BarDataSet dataSet = new BarDataSet(entries, null);
dataSet.setColors(ColorTemplate.COLORFUL_COLORS);
BarData barData = new BarData(dataSet);
mChart.setData(barData);
mChart.invalidate();
```

The graph looks fine, colors are OK, but there's no Legend entries for each Month.... I mean... it should appear the indexes (0, 1, 2, ...).

I know I can make one BarDataSet for each month, but I think it's too big, since i want just to make one bar / legend label for each entry on my array.

On PieChart, I could achieve what I wanted usong only one PieDataSet.
Thanks and regards

**Comment by almic** [comment]
You can use the `AxisValueFormatter` to write custom labels for each bar. You can construct it by passing in your `map`, which just get's the key for that value and converts it into a string. That is the easiest way to do this, avoiding the legend completely.

The legend is automatically calculated based on the data sets in the chart. See the example `BarChartActivityMultiDataset.java` activity in the example project. To get what you wanted, you'll have to create a new data set for each, and call `data.addDataSet(set)` for each new set. You'll also be able to add the labels to the legend this way.
