### ISSUE TITLE
LineChart的x轴的数值不能为递减趋势的值？

### ISSUE THREAD

**Issue by kavieen** [PhilJay/MPAndroidChart#3933]
当我将x轴的值设置成递减趋势的值时，就无法显示曲线了，也没有什么的提示。。。

**Comment by NianyiYang** [comment]
Try to set yAxis Max&Min values abslutely

**Comment by almic** [comment]
I don't speak chinese, but hopefully you understand english.

You can extend `AxisValueFormatter` and simply add a negative sign in front of the labels.

Is that what you wanted?
