### ISSUE TITLE
    the line is seted  Small line       when set the setAxisMinimum 

### ISSUE THREAD

**Issue by yuzhongrong** [PhilJay/MPAndroidChart#3937]
if(entries.get(0).getY()==0.0){
                mChart.getAxisLeft().setStartAtZero(false);
                mChart.getAxisLeft().setAxisMinimum(0);
            }

**Comment by almic** [comment]
The second graph looks fine to me! Use that one!

I'm closing this for now, as I've done the same thing in my code...

`chart.getAxisLeft().setAxisMinimum(0f)`

...and it has worked for me, so I'm guessing this isn't a problem with the library.

**Comment by almic** [comment]
Also, remove the call to `setStartAtZero(false)`, this is deprecated and may be causing this issue!
