### ISSUE TITLE
Unable to draw closed graph

### ISSUE THREAD

**Issue by shree-vastava** [PhilJay/MPAndroidChart#3938]
I have a requirement where The value in my x-axis can decrease.
In that case, I am getting the error
`/UncaughtException: java.lang.NegativeArraySizeException: -6`

I want to achieve something like this

![plot](https://user-images.githubusercontent.com/20813696/38561036-a0fa47e8-3cf4-11e8-9f05-18cc2c3f8297.jpg)

Is it available in any of the versions yet?

**Comment by almic** [comment]
This is a really good feature suggestion, but this is **definitely out of scope for this project.**

Something like that would require, preferably, the ability to pass some crazy function into the chart and it spit out some craziness like that. A function with two possible X axis values is an *entirely new level of math* for sure. Normally, you'd pass a single function *twice* if you wanted that on, for example, your average graphing calculator. One positive and one negative version of the same function.

Therefore, the only solution is to draw **two** data sets, in which they both terminate at the furthest point. In this case it'll be the far right. This would be an algorithm you'll have to write yourself if you want to pass different x values for one line. However, it shouldn't be hard to do. You would just have to create a new data set every time the X values stack. Two sets for two X values, three for three, and so on...
