### ISSUE TITLE
Notifying when the bottom of the Y axis is reached

### ISSUE THREAD

**Issue by mars885** [PhilJay/MPAndroidChart#3939]
Hello everyone. First of all, I have the following layout:

- SwipeRefreshLayout
    - NestedScrollView
      - ConstraintLayout
        - CandleStickChart

As you can see, the layout is pretty complex. Nonetheless, what I'd like to do here is to allow a user to scroll down (using NestedScrollView) only whenever either of the following options are satisfied:

1. A chart is fully zoomed out (which I've successfully implemented).
2.  If the user zoomed in the chart and then scrolled to the bottom of the Y axis, then basically allow the scroll view to intercept the touch event and scroll down for more content.

I know how to implement all touch-related functionality. The piece of the puzzle I'm missing here is how can I get notified whenever a user scrolled to the bottom of the Y axis?

**Comment by almic** [comment]
`chart.getViewPortHandler().getTransY()` should return the current pan along the Y axis (not specific to left or right). I haven't tested the values for this but I'm sure it'll probably equal `0` if scrolled all the way down, assuming the minimum Y range is `0`.

You'll need to play with that, and just disable scrolling on the Y axis, inside your touch listener, until ACTION_UP or ACTION_CANCEL is called, at which point you can enable scrolling again after the chart is released.
