### ISSUE TITLE
2 Decimal number

### ISSUE THREAD

**Issue by kukuk1** [PhilJay/MPAndroidChart#394]
Hello, i have implemented the MPAndroidChart in my Project. When i disply value in the anotherbarBar Activity, an the value is higher than 8, it will display only one decimal number. If it's smaller than 8 it will display 2 decimal number behind the comma.

Can anybody help me?

**Comment by PhilJay** [comment]
Yes, it does that automatically. What do you want to display?

**Comment by kukuk1** [comment]
Thank you so much for your fast replay. I want to display always 2 decimal behind the comma

**Comment by PhilJay** [comment]
No, simply create a valueformatter like shown above and set it to your
axis or data object, that will do the job.
