### ISSUE TITLE
this is possible in this lib?

### ISSUE THREAD

**Issue by shivalekiran** [PhilJay/MPAndroidChart#3941]
![img_20180412_151646](https://user-images.githubusercontent.com/19802067/38669710-96e726ce-3e64-11e8-862f-30abc54760f8.jpg)

**Comment by shivalekiran** [comment]
i try using bubble chart but how to draw quadrant?

**Comment by ArilesGit** [comment]
Have you tried using limitLines ?

**Comment by shivalekiran** [comment]
Yeah limit lines work fine but i cant set Labels for Quadrants;

**Comment by almic** [comment]
You could also just add a TextView on top of the chart, just make sure it's xml `translationZ` is high, 5dp should work. You may be able to use limit lines with 0 width or a transparent color, and just set the label.
