### ISSUE TITLE
Display a selected value by pressing the chart

### ISSUE THREAD

**Issue by AllorNothinAbiq** [PhilJay/MPAndroidChart#3948]
Hi,

I used this chart creator to plot data, so far so good. I've seen that a horizontal and a vertical line appear when you thouch the screen. I wonder if I can display the X and Y value at the selected datapoint.

Thanks!!

**Comment by ArilesGit** [comment]
Hi,
Have a look at the [IMarker interface](https://github.com/PhilJay/MPAndroidChart/wiki/IMarker-Interface) in the wiki.

**Comment by AllorNothinAbiq** [comment]
I also found the Highlighting usefull, but thanks!!![Highlighting](https://github.com/PhilJay/MPAndroidChart/wiki/Highlighting)
