### ISSUE TITLE
Only alternate labels are shown in x axis when more entries comes

### ISSUE THREAD

**Issue by ruanbarroso** [PhilJay/MPAndroidChart#3950]
- Library Version: 3.0.3
- setGranularityEnabled(true)
- setGranularity(1f)
- setLabelCount(rows.size)
- When I use HorizontalBarChart and the number of entries is very large the odd labels of xAxis are not shown as you can see at the image (first chart displays correctly and second chart does not):

![image](https://user-images.githubusercontent.com/22946158/38835745-5fc99316-41a2-11e8-948f-937b17f1b98e.png)

**Comment by almic** [comment]
when doing `setLabelCount()`, you should also pass `true` as the last parameter to **force** that value.

Keep in mind that the max number of labels is 25 (hardcoded limit)

**Comment by Ezerous** [comment]
What is the purpose of having this hardcoded limit of labels?

**Comment by qingchen1016** [comment]
Thank you
