### ISSUE TITLE
lineDataSet.setMode(LineDataSet.Mode.CUBIC_BEZIER) draw error

### ISSUE THREAD

**Issue by surcreak** [PhilJay/MPAndroidChart#3951]
when 
lineDataSet.setDrawCircles(false);
lineDataSet.setMode(LineDataSet.Mode.CUBIC_BEZIER);
lineDataSet.setDrawFilled(true);
lineDataSet.setDrawValues(false);
![image](https://user-images.githubusercontent.com/5450685/38846776-c60702f6-4230-11e8-827a-5cfe5847481b.png)

set
//        lineDataSet.setDrawCircles(false);
        lineDataSet.setMode(LineDataSet.Mode.CUBIC_BEZIER);
//        lineDataSet.setDrawFilled(true);
//        lineDataSet.setDrawValues(false);
![image](https://user-images.githubusercontent.com/5450685/38846791-d72cf144-4230-11e8-9b3d-46e8edcaedcb.png)
@PhilJay Place help me！ Thank you。

**Comment by almic** [comment]
You could be adding the values in the wrong order, but I'm not sure if that affects it.

I use the `LineDataSet.Mode.HORIZONTAL_BEZIER` with a cubic intensity of 0.5f, and it looks fine for me.

Try using the `HORIZONTAL_BEZIER` or decrease your cubic intensity `setCubicIntensity()`
