### ISSUE TITLE
Chart with table 

### ISSUE THREAD

**Issue by sakaravinth** [PhilJay/MPAndroidChart#3952]
Hi All,
I want some more feature.When i click on  row of table selected row want to be highlighted on chart .
Is it already there or possible for it.
Thanks in advance
![scrrenshotchartwithdata](https://user-images.githubusercontent.com/8447192/38855085-237984e0-4240-11e8-99ca-8dbf5ed2decc.png)

**Comment by almic** [comment]
Use a listener on the table, and inside that listener, call `highlightValue(float x, int dataSetIndex)` on the `pieChart`

`x` should be mapped to the order of the entries you added, and `dataSetIndex` is probably `0`

**Comment by sakaravinth** [comment]
Thanks for update .Whether it will work for all charts.

**Comment by sakaravinth** [comment]
In pie chart highlight  is not appearing  .

**I have tried below code**
tableView.addDataClickListener(new TableDataClickListener<String[]>() {
                                            @Override
                                            public void onDataClicked(int rowIndex, String[] clickedData) {
                                                System.out.println("piechartRowCLick::"+clickedData.toString()+" ::rowIndex::"+rowIndex);
                                                pieChart.highlightValue(Float.parseFloat(clickedData[2].replace(",", "")),0,rowIndex);
//                                                pieChart.highlightValue(Float.parseFloat(clickedData[2].replace(",", "")),rowIndex);
//                                                pieChart.highlightValue(pieChart.getHighlighter().getHighlight(Float.parseFloat(clickedData[2].replace(",", "")), 0));
                                            }
                                        });

**Comment by sakaravinth** [comment]
In pie chart highlight is not appearing .

I have tried below code
tableView.addDataClickListener(new TableDataClickListener<String[]>() {
@Override
public void onDataClicked(int rowIndex, String[] clickedData) {
System.out.println("piechartRowCLick::"+clickedData.toString()+" ::rowIndex::"+rowIndex);
pieChart.highlightValue(Float.parseFloat(clickedData[2].replace(",", "")),0,rowIndex);
// pieChart.highlightValue(Float.parseFloat(clickedData[2].replace(",", "")),rowIndex);
// pieChart.highlightValue(pieChart.getHighlighter().getHighlight(Float.parseFloat(clickedData[2].replace(",", "")), 0));
}
});
