### ISSUE TITLE
Can I set a border line to a group rane in the x-axis?

### ISSUE THREAD

**Issue by JosueB** [PhilJay/MPAndroidChart#3954]
I was wondering if this would actually be possible in the x axis
![ydstg](https://user-images.githubusercontent.com/4667668/38909014-58dca6e2-4288-11e8-9307-9f3bc0f2aa24.png)

**Comment by almic** [comment]
Not currently possible within the library, however nothing it stopping you from throwing a drawable on top of the border.

That image looks more like a SeekBar, something you can do. You could just draw your own custom SeekBar below the graph (near the x axis), and make it move the graph based on the seek bar's value.

There may be other libraries to draw such seek bars, too.
