### ISSUE TITLE
Utils工具类drawImage方法有问题

### ISSUE THREAD

**Issue by liuchen8899** [PhilJay/MPAndroidChart#3956]
public static void drawImage(Canvas canvas,
                                 Drawable drawable,
                                 int x, int y,
                                 int width, int height) {

        MPPointF drawOffset = MPPointF.getInstance();
        drawOffset.x = x - (width / 2);
        drawOffset.y = y - (height / 2);

        drawable.copyBounds(mDrawableBoundsCache);
        drawable.setBounds(
                mDrawableBoundsCache.left,
                mDrawableBoundsCache.top,
                mDrawableBoundsCache.left + width,
                mDrawableBoundsCache.top + width);

        int saveId = canvas.save();
        // translate to the correct position and draw
        canvas.translate(drawOffset.x, drawOffset.y);
        drawable.draw(canvas);
        canvas.restoreToCount(saveId);
    }

  mDrawableBoundsCache.top + width应改为  mDrawableBoundsCache.top + height

**Comment by almic** [comment]
Create a pull request, and also describe ***what*** problem this fixes. All that does is force the image to be a square shape, which is probably intentional.
