### ISSUE TITLE
MpAndroidChart graph displays on alternative y axis lines

### ISSUE THREAD

**Issue by madhurihr1592** [PhilJay/MPAndroidChart#3958]
I have data for the year i.e data for each month. I am using Line Chart to display the data. I have made some customizations. Problem is it will display only alternative months Y axis line. I want to display all the y axis lines. Please refer screenshot. 1st image is what I am getting. I want it to be like the 2nd image. 
![screenshot_20180419-165935](https://user-images.githubusercontent.com/33710308/38929638-a0d4a7cc-432a-11e8-8b82-d1a28e972f6f.png)
![graph_year](https://user-images.githubusercontent.com/33710308/38929648-a63ba7e2-432a-11e8-855e-1d5aa5938a34.png)

**Comment by ArilesGit** [comment]
Hi !
Try this using : `chart.getXAxis().setLabelCount(someInt)`

And then, use a valueFormatter that returns only the months you want :

              `@Override
                public String getFormattedValue(float value, Entry entry, int dataSetIndex, ViewPortHandler viewPortHandler) {

                    //Get year from value
                    int year = ...;
                    return (year % 2 == 0) ? "" : yearAsString;

                }`

**Comment by madhurihr1592** [comment]
@ArilesGit Thanks this worked :)
