### ISSUE TITLE
ChartData.addDataSet() min/max error

### ISSUE THREAD

**Issue by jdecew** [PhilJay/MPAndroidChart#396]
If you create a `ChartData` with no datasets and then use `addDataSet(d)`, the `mYMin` will be at most 0, when it should be `d.getYMin()`.

Current source:
```
        if (mYMax < d.getYMax())
            mYMax = d.getYMax();
        if (mYMin > d.getYMin())
            mYMin = d.getYMin();
```
Could become:
```
        boolean first = mDataSets.size() == 1;
        if (mYMax < d.getYMax() || first)
            mYMax = d.getYMax();
        if (mYMin > d.getYMin() || first)
            mYMin = d.getYMin();
```

Not sure, but I'm guessing the `mLeftAxisMin` etc. variables may also need similar treatment.

**Comment by PhilJay** [comment]
I'm not sure if I am missing something, but I think the `addDataSet(...)` method covers that:

```java
public void addDataSet(T d) {
        if (mDataSets == null)
            mDataSets = new ArrayList<T>();
        mDataSets.add(d);

        mYValCount += d.getEntryCount();
        mYValueSum += d.getYValueSum();

        if (mYMax < d.getYMax())
            mYMax = d.getYMax();
        if (mYMin > d.getYMin())
            mYMin = d.getYMin();

        if (d.getAxisDependency() == AxisDependency.LEFT) {

            if (mLeftAxisMax < d.getYMax())
                mLeftAxisMax = d.getYMax();
            if (mLeftAxisMin > d.getYMin())
                mLeftAxisMin = d.getYMin();
        } else {
            if (mRightAxisMax < d.getYMax())
                mRightAxisMax = d.getYMax();
            if (mRightAxisMin > d.getYMin())
                mRightAxisMin = d.getYMin();
        }

        handleEmptyAxis(getFirstLeft(), getFirstRight());
    }

```

Or am I missing something?

**Comment by jdecew** [comment]
There's a special case when you are adding the first data.  In this case `mYMin` and `mYMax` are set (to 0) but don't indicate a real min or max, because there was no data.

As an example, if your DataSet's min/max is 100/150, then constructing the ChartData with that DataSet results in a min/max of 100/150.  However, if you construct the ChartData with just xValues, the min/max is initialized as 0/0, then calling `addDataSet` expands the range to 0/150, but it should ignore the 0/0 and set it to 100/150.
