### ISSUE TITLE
Show highlighted value on y-axis

### ISSUE THREAD

**Issue by cekoivisto** [PhilJay/MPAndroidChart#3961]
How would I be able to highlight a specific value and have that value's y-coordinate show up on the y-axis? So if my y-axis values were this:
100
110
120
130
And I highlighted a point whose y-value was 117.25, the y-axis would add that text in to become:
100
110
117.25
120
130
And if the new "117.25" text that it's adding overlaps any text on the y-axis it would remove the text underneath it. Is this possible?

**Comment by almic** [comment]
You can use limit lines.

Check out the [javadoc](https://jitpack.io/com/github/PhilJay/MPAndroidChart/v3.0.3/javadoc/) and implement the `OnChartValueSelectedListener`, and just remove and re-add a limit line whenever a value is selected.
