### ISSUE TITLE
show error。

### ISSUE THREAD

**Issue by shizhongyu** [PhilJay/MPAndroidChart#3963]
![_20180419122524](https://user-images.githubusercontent.com/13025541/38971238-d3cdcf6c-43cc-11e8-9c19-bef4c972de05.png)
![image](https://user-images.githubusercontent.com/13025541/38971252-e50fc744-43cc-11e8-8e39-c86c7082a977.png)
x is increase but show error.

**Comment by almic** [comment]
Those aren't errors, it's just logging the data. You can turn off logging with `chart.setLogEnabled(false)`.
