### ISSUE TITLE
PieChart start angle point

### ISSUE THREAD

**Issue by binaykumarrana** [PhilJay/MPAndroidChart#3966]
Hi, I am drawing a pie chart with 4 slices but the first slice wants to start from 12'O clock point. Right now it starts with 3'Oclock in a clockwise direction.  I can't find any method to set start point or any similar method.

Plz, help needs urgent.

Thanks
Binay

**Comment by almic** [comment]
`pieChart.setRotationAngle(angle)` is what you are looking for. The default is 270f, or 3 o'clock. To start at 12 o'clock, you should just have to set this to 0f. You can set it immediately after you create the chart.
