### ISSUE TITLE
Barchart overdraws Limit line

### ISSUE THREAD

**Issue by androideveloper** [PhilJay/MPAndroidChart#397]
Please see the problem in the attached screenshots.
Expected behavior: Limit line should be on barchart.

My code is
	LimitLine limitLine = new LimitLine((float) limit, String.format(context.getString(R.string.chart_limit),
		valueFormatter.getFormattedValue((float) limit)));
	limitLine.setLineWidth(3f);
	limitLine.setTextSize(10f);
	limitLine.setTextColor(context.getResources().getColor(R.color.gray));
	yAxisLeft.addLimitLine(limitLine);

![screenshot_2015-03-03-15-38-14](https://cloud.githubusercontent.com/assets/1249919/6461777/d02a998e-c1bc-11e4-8896-bf676e441a70.png)
![screenshot_2015-03-03-15-38-31](https://cloud.githubusercontent.com/assets/1249919/6461778/d02b9212-c1bc-11e4-8411-84c7b5de957f.png)

**Comment by PhilJay** [comment]
Yep, thats correct. 
A feature that allows the z-positioning of the limit-line is currently not available. You will have to modify the library (slightly) to achieve what you want.

**Comment by androideveloper** [comment]
But it was working correctly before update to library. Could you please fix it with next version? Because we are using .jar files, and this update broke our functionality(

**Comment by PhilJay** [comment]
Well if this is really an issue for you, I suggest you cut back to an older release of this library for now, and I will change the order of limit lines and bars in the next release!

Best regards,
Phil

**Comment by androideveloper** [comment]
Ok, great! We will be very grateful!
Awesome project! Thanks!

**Comment by androideveloper** [comment]
Thanks!
