### ISSUE TITLE
User Input

### ISSUE THREAD

**Issue by 10jumend** [PhilJay/MPAndroidChart#3972]
Hi, I'm currently making an app that tracks a user's blood pressure. Right now, I have a dataset with data programmed into the graph instead of a user actually inputting information. How would I store an integer and use it as a new data point in the graph?

**Comment by almic** [comment]
If you want to add new data points to an existing chart, like a line graph, check out the example `RealtimeLineChartActivity.java` in the example project.

You just have to grab the chart's data object:
`LineData data = chart.getData()`

Add an entry at the end:
`data.addEntry(new Entry(data.getEntryCount(), y))`

And alert the data and chart about the new entry

```js
    data.notifyDataChanged();
    chart.notifyDataSetChanged();

    // optionally move to the last entry
    chart.moveViewToX(data.getEntryCount());
