### ISSUE TITLE
set dynamically x axis value in List Item view(bar graph)

### ISSUE THREAD

**Issue by kkpareek1991** [PhilJay/MPAndroidChart#3978]
I am facing problem when set x axis value in listview with multiple item . I want to set dynamically month on x axis  in bar graph for mutiple Item. Please help.  I am not able to get how o set pass month array for mutiple Item in list view. Below code is used:

/*  IAxisValueFormatter formatter = new IAxisValueFormatter() {

            @Override
            public String getFormattedValue(float value, AxisBase axis) {
                return xAxisLabel.get((int) value);
            }

        };*/

This one giving null pointer  exception  (size issue ).

//below code for set bardata 
private BarData generateDataBar(List<GraphItem> result) {
        xAxisLabel  = new ArrayList<>();
        Log.d("GRAPH", "graph entry data size" +result.size());
        ArrayList<BarEntry> entries = new ArrayList<BarEntry>();
        for (int i = 0; i < result.size(); i++) {
            int value;
           try {
               value = (int) Double.parseDouble(result.get(i).getQuantity());
           }catch (Exception e){
               e.printStackTrace();
               value=0;
           }
            entries.add(new BarEntry(i, value));
            // set x axis value in array list and pass this array in set adapter constructor
            xAxisLabel.add(result.get(i).getMonth());
        }

        BarDataSet d = new BarDataSet(entries,  "(Quantity) " + result.get(0).getName());
        d.setColors(ColorTemplate.VORDIPLOM_COLORS);
        d.setHighLightAlpha(255);
        d.setBarShadowColor(Color.rgb(203, 203,203));

        ArrayList<IBarDataSet> sets= new ArrayList<>();
        sets.add(d);

        BarData cd = new BarData(sets);
        cd.setBarWidth(0.9f);
        return cd;
    }
// set data for adapter

                        ArrayList<String> shipToParty = removeShipToDuplicate(graphResult);
                        ArrayList<ChartItem> listRes = new ArrayList<ChartItem>();
                        Log.d("GRAPH", "ship to pary " + shipToParty.size());
                        for (int i = 0; i < shipToParty.size(); i++) {
                            List<GraphItem> customerResult = new ArrayList<>();
                            for (int j = 0; j < graphResult.size(); j++) {
                                if (shipToParty.get(i).equals(graphResult.get(j).getCustomer())) {
                                    customerResult.add(graphResult.get(j));
                                }
                            }
                            listRes.add(new BarChartItem(generateDataBar(customerResult), getActivity(), xAxisLabel));

                        

// set adapter value 

 ChartDataAdapter cda = new ChartDataAdapter(getActivity(), listRes);
        listView.setAdapter(cda);

**Comment by almic** [comment]
I glanced over your code and here's my suggestion.

You should be _implementing_ the interface into a _class_, not creating a new object.

Also, `getFormattedValue()` returns a `String`, and you get the x/y coordinate from `value`, so you can easily use that as an index for, say, an array of month strings.
