### ISSUE TITLE
how to change Line Chart Backgroud gridline color

### ISSUE THREAD

**Issue by ashishvirani** [PhilJay/MPAndroidChart#3980]
![untitled](https://user-images.githubusercontent.com/24842599/39292379-a3c96c18-4953-11e8-9f0b-5fcfcdb69b80.png)

**Please help how to change background gridline color in Line Chart.**

**Comment by almic** [comment]
Please see the Wiki section on this GitHub project (top of the page). It has styling options described there. `setGridBackgroundColor(int)` is what you need.
