### ISSUE TITLE
piechart valueLine and texts are out of the screen

### ISSUE THREAD

**Issue by fly7632785** [PhilJay/MPAndroidChart#3981]
I got a problem of the piechart, hope you guys give me some advice, thanks.
Please see the picture.
![52590ba8-3ab3-4b4c-a6bf-e396391a5d51](https://user-images.githubusercontent.com/10276266/39299463-543de5c0-497b-11e8-96d2-9f54a2b8b63e.png)

```
   dataSet.setValueLinePart1OffsetPercentage(70.f);
        dataSet.setValueLinePart1Length(0.8f);
        dataSet.setValueLinePart2Length(0.2f);
        dataSet.setValueLineColor(Color.BLACK);
        dataSet.setXValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);
        dataSet.setYValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);
```

When I enable the valueline, it seems not work good. The texts are out of the screen. The piechart is not scaled to let the valueline and texts show out.
I tried to set the padding or wrap_content, it's not working.
Thank you in advance.

**Comment by sembozdemir** [comment]
Give some extraTopOffset and extraBottomOffset for your pieChart

```
pieChart.setExtraTopOffset(offSet);
pieChart.setExtraBottomOffset(offSet);
```

**Comment by fly7632785** [comment]
@sembozdemir thank you every much, it works. Greate
