### ISSUE TITLE
Gradient background depend on positive/negative values

### ISSUE THREAD

**Issue by hannesa2** [PhilJay/MPAndroidChart#3985]
Does someone knows how to archive this ?
Gradient background depend on positive/negative values

<img width="164" alt="image" src="https://user-images.githubusercontent.com/3314607/39392045-7eb2a348-4aae-11e8-94f1-92c04cacbd2a.png">

**Comment by almic** [comment]
You could probably split the positive and negative values into two separate sets, and individually fill those with `lineDataSet.setFillDrawable(fadeDrawable)`. However, I bet the fills with overlap and spread into each other, but you may be able to avoid that with some cleverness in the drawables.

**Comment by tabish075** [comment]
@almic @hannesa2  
`int startColor = ContextCompat.getColor(this, android.R.color.black);
int endColor = ContextCompat.getColor(this, android.R.color.white);
set2.setGradientColor(startColor, endColor);` 

But i am getting a solid sky blue color instead of gradient using Horizontal bar chart  Any ideas?

**Comment by radian-rgc** [comment]
I was very disappointed
And I did not get the result ...
Please Help me

**Comment by Serpivskyi** [comment]
I done this)
class CustomLineChartRender(
    lineDataProvider: LineDataProvider,
    chartAnimator: ChartAnimator,
    port: ViewPortHandler
) : LineChartRenderer(lineDataProvider, chartAnimator, port) {
    override fun drawLinearFill(
        c: Canvas?,
        dataSet: ILineDataSet?,
        trans: Transformer?,
        bounds: XBounds?
    ) {
        val filled = mGenerateFilledPathBuffer

        val startingIndex = bounds!!.min
        val endingIndex = bounds!!.range + bounds!!.min
        val indexInterval = 1

        var currentStartIndex = 0
        var currentEndIndex = indexInterval
        var iterations = 0

        do {
            currentStartIndex = startingIndex + iterations * indexInterval
            currentEndIndex = currentStartIndex + indexInterval
            currentEndIndex = if (currentEndIndex > endingIndex) endingIndex else currentEndIndex
            if (currentStartIndex <= currentEndIndex) {
                generateFilledPath(dataSet!!, currentStartIndex, currentEndIndex, filled)
                trans!!.pathValueToPixel(filled)
                val drawable = dataSet.fillDrawable
                if (drawable != null) {
                    drawFilledPath(c, filled, drawable)
                } else {
                    val index = startingIndex + iterations
                    drawFilledPath(c, filled, dataSet.colors[index], dataSet.fillAlpha)
                }
            }
            iterations++
        } while (currentStartIndex <= currentEndIndex)

    }

    private fun generateFilledPath(
        dataSet: ILineDataSet,
        startIndex: Int,
        endIndex: Int,
        outputPath: Path
    ) {
        val fillMin = dataSet.fillFormatter.getFillLinePosition(dataSet, mChart)
        val phaseY = mAnimator.phaseY
        val isDrawSteppedEnabled = dataSet.mode == LineDataSet.Mode.STEPPED
        outputPath.reset()
        val entry = dataSet.getEntryForIndex(startIndex)
        outputPath.moveTo(entry.x, fillMin)
        outputPath.lineTo(entry.x, entry.y * phaseY)

        // create a new path
        var currentEntry: Entry? = null
        var previousEntry = entry
        for (x in startIndex + 1..endIndex) {
            currentEntry = dataSet.getEntryForIndex(x)
            if (isDrawSteppedEnabled) {
                outputPath.lineTo(currentEntry.x, previousEntry!!.y * phaseY)
            }
            outputPath.lineTo(currentEntry.x, currentEntry.y * phaseY)
            previousEntry = currentEntry
        }

        // close up
        if (currentEntry != null) {
            outputPath.lineTo(currentEntry.x, fillMin)
        }
        outputPath.close()
    }
}
