### ISSUE TITLE
Dashed Barchart

### ISSUE THREAD

**Issue by kheirus** [PhilJay/MPAndroidChart#3993]
I was wondering if I can draw bracharts that look like below dashed line barchart, with dashed line, and why not with gradient effect too?
![barchart](https://user-images.githubusercontent.com/8956608/39527327-6e57bc42-4e21-11e8-93ff-85ec5d420ee1.jpg)

**Comment by almic** [comment]
Currently, no. However this is definitely on the list of stuff to add. In the mean time, check out the other related issues for gradients in bar charts (quite a few exist) and there may be existing workarounds hiding in them. 👍
