### ISSUE TITLE
Data disappears after adding 

### ISSUE THREAD

**Issue by 10jumend** [PhilJay/MPAndroidChart#3994]
- [ ] I have read the [CONTRIBUTING](https://github.com/PhilJay/MPAndroidChart/blob/master/CONTRIBUTING.md) file before posting this issue.

**Describe the bug**

**Screenshots**

**Expected behavior**

**Device (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - Android Version [e.g. 7.0]
 - Libaray Version (e.g. 3.0.3)

**Additional context**

Add any other context about the problem here. If you have source code demonstrating this bug, create a [Gist](https://help.github.com/articles/creating-gists/) and link to it.

**Comment by abhilasha25** [comment]
Please share the solution
