### ISSUE TITLE
Data disappears after adding (MPAndroidChart)

### ISSUE THREAD

**Issue by 10jumend** [PhilJay/MPAndroidChart#3995]
After I add a new Entry to my chart, if I go to a different activity, the data point disappears when I return. How do I fix it so that the data set is saved and remembers the new data entered by the user?

**Comment by almic** [comment]
This is more of an instance state saving problem, something you'll have to learn how to do on your own. The library *cannot* do this for you, it has to be done at the activity level.

See the android developer page [Saving UI States](https://developer.android.com/topic/libraries/architecture/saving-states) to learn how you can accomplish this.
