### ISSUE TITLE
How to change YAxis values in line chart from float to integer? My YAxis data is in ArrayList<Entry> type.

### ISSUE THREAD

**Issue by vishalgupta1509** [PhilJay/MPAndroidChart#3996]
- [ ] I have read the [CONTRIBUTING](https://github.com/PhilJay/MPAndroidChart/blob/master/CONTRIBUTING.md) file before posting this issue.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vishalgupta1509** [comment]
LineDataSet set1 = new LineDataSet(yVals, "DataSet 1");

yVals takes List<Entry> type value which returns the float value. But i want data in integer format.
How to change the data in integer format?

**Comment by almic** [comment]
Just cast your integer to a float: `(float) 5`

And then set the chart granularity with `chart.setGranularity(1f)`

Also, please read the [wiki](https://github.com/PhilJay/MPAndroidChart/wiki), it describes exactly how to do this. I'm sure there's also some example activities in the example project that do this.
