### ISSUE TITLE
Pie chart display values bug

### ISSUE THREAD

**Issue by AndroFlo** [PhilJay/MPAndroidChart#400]
Hello Phil,

A rather annoying bug in the display level is one.
It's probably hard to reslove it ?

Thank you

![bug_pie_chart](https://cloud.githubusercontent.com/assets/5589240/6464129/5580031c-c1b8-11e4-90e4-a08cdef2d800.png)

**Comment by PhilJay** [comment]
Whats the bug?
Are you talking about the values being close together?

**Comment by AndroFlo** [comment]
Yes, the vallues

**Comment by PhilJay** [comment]
That's not really a bug. There is just no feature that handles very small values in the piechart.
