### ISSUE TITLE
Change in dataset

### ISSUE THREAD

**Issue by judemanutd** [PhilJay/MPAndroidChart#4003]
- [ x] I have read the [CONTRIBUTING](https://github.com/PhilJay/MPAndroidChart/blob/master/CONTRIBUTING.md) file before posting this issue.

**Describe the bug**

I am getting an entirely different value in the `IAxisValueFormatter` class that I am using. I have used the workaround as suggested in other issues related to large numbers.

I have a data set that looks like this.
```
[{"level":100,"time":1525354200},{"level":90,"time":1525350600},{"level":80,"time":1525347000},{"level":70,"time":1525343400},{"level":60,"time":1525339800},{"level":50,"time":1525336200},{"level":40,"time":1525332600}]
```

The snippet of code I have used is 

```
      if (tankLevels.size() > 0)
            tempTime = tankLevels.get(0).getTimestamp();

        for (int i = 0; i <= tankLevels.size() - 1; i++) {
            TankLevel tankLevel = tankLevels.get(i);
            long time = tempTime - tankLevel.getTimestamp();
            entries.add(new Entry(time, tankLevel.getLevel()));
        }
```
And then in the `IAxisValueFormatter`

```
xAxis.setValueFormatter(new IAxisValueFormatter() {

	private SimpleDateFormat mFormat = new SimpleDateFormat("HH:mm", Locale.getDefault());

	@Override
	public String getFormattedValue(float value, AxisBase axis) {
		long timestamp = tempTime + (long) value;
		long millis = TimeUnit.SECONDS.toMillis(timestamp);
		return mFormat.format(new Date(millis));
	}
});
```

**Expected behavior**

The problem is that in the `IAxisValueFormatter` the initial value I get is `0` which is fine but then next value is supposed to be `3600` ie `1525354200-1525350600` but the value I get is `3999.9998` which is not just losing precision but changing the data entirely. I am not sure what's going wrong here.

**Device (please complete the following information):**
 - Device: [Redmi Note 3]
 - Android Version [e.g. 6.0]
 - Libaray Version (e.g. 3.0.3)

**Comment by Jetz72** [comment]
What type is tempTime, and how does TankLevel store and retrieve timestamps?

**Comment by Jetz72** [comment]
Looks pretty similar to things I've done, and I don't see any reason this would cause a rounding issue unless I'm missing something or it's occurring outside what you've posted. 3600 shouldn't be any trouble for floating points. This isn't really a solution (and you may have done this already for all I know), but I'd try narrowing it down with log calls, printing out tempTime, time, the timestamp, Entry.getX(), value, the other timestamp, and millis, as they're computed and stored. Isolating where the problem is would be valuable information.

**Comment by judemanutd** [comment]
Where exactly should I be running `Entry.getX()` because I have logged the output of the entire List<Entry> objects after looping through it and verified the data which is correct. Will check again though, thanks for the suggestions.

On a side note, instead of inserting the actual value ie the timestamp into `entries.add(new Entry(time, tankLevel.getLevel()));` I did `entries.add(new Entry(i, tankLevel.getLevel()));` where `i` is the index in the loop. This way I could easily get the correct value  inside the `getFormattedValue` function from the global `tankLevels` list without losing any data but that leads to duplicate x axis entries and I can't really specify the granularity as these are random points spread over a certain time period that varies.

I am still in the process of figuring out the library but could you provide a little insight as to why the global list method doesn't work.

**Comment by almic** [comment]
Floats aren't perfect, that is something every java developer ever has dealt with. However you should be converting those floats back into integers when doing strictly integer math. This is some basic stuff, here.

I didn't get into the discussion between you and Jetz72, but judging by the simplicity of the issue I decided the solution is equally simple. Basically, use the index `i` for your X index. You can pass the original time stamps into your `AxisValueFormatter` when you initialize it, and use that to map your indexes 1:1 with the labels.

It looks like all your timestamps are in steps of `3600`, so this solution should not affect how the chart looks once you add the custom labels.
