### ISSUE TITLE
How to plot a point between two vertical line  in mpchart  ?? Please refer the below image i need a help

### ISSUE THREAD

**Issue by Deepak-Malha** [PhilJay/MPAndroidChart#4009]
(https://user-images.githubusercontent.com/33025665/39765664-05aa87f4-5300-11e8-95b6-234e399ae691.png)

**Comment by almic** [comment]
I guess you already figured it out, but just incase others stumble upon this issue, here's the short answer:

Set the granularity of the chart to `1f`, and then add `0.5f` to each x value. This way, the grid is drawn at every nth step, and every point is draw at (n + 0.5)th step, putting the points between the gridlines.
