### ISSUE TITLE
Support for Clusters

### ISSUE THREAD

**Issue by MohamadAtieh** [PhilJay/MPAndroidChart#401]
Please. That would be unbelievably useful.

**Comment by PhilJay** [comment]
Can you be a little bit more specific about what you want? :-)

**Comment by MohamadAtieh** [comment]
[This](http://www.scielo.org.za/img/revistas/sajs/v106n5-6/a11fig02m.gif) and [this](http://www.mathworks.com/products/demos/machine-learning/cluster_genes/Cluster_Genes_03.png)

**Comment by PhilJay** [comment]
Well the first link you posted is absolutely not supported :-)
The second image you showed I think can be covered using the `ScatterChart`.
