### ISSUE TITLE
How to plot a point between two vertical line  in mpchart for android  ?? Please refer the below image i need a help a

### ISSUE THREAD

**Issue by sathishcs59** [PhilJay/MPAndroidChart#4010]
@PhilJay ![image check](https://user-images.githubusercontent.com/19968166/39766226-6890ae06-5301-11e8-9f96-06dcc1cbd62e.png)

**Comment by almic** [comment]
See your previous issue, please. 

And, please NEVER open two issues for the sake of putting your name in the issue. It's pretty dumb :/

And another thing, [don't be stupid](https://github.com/PhilJay/MPAndroidChart/blob/master/.github/ISSUE_TEMPLATE/Support_help.md)
