### ISSUE TITLE
Line chart according to view

### ISSUE THREAD

**Issue by arpitjoshi08** [PhilJay/MPAndroidChart#4014]
![helpresource ashx](https://user-images.githubusercontent.com/17329682/39813897-de47c9be-53af-11e8-8792-acb1a1c2a0c4.png)

i want to show this type of line chart attached in image . line not an issue it can be show simply. i am getting two issues is that;
1) the x values and y  values will not start from 0 it will start index first according to image
2) how can i set x and y values currently i am using this code

```
     ArrayList<Entry> entries = new ArrayList<>();
        entries.add(new Entry(2015, 1));
        entries.add(new Entry(2016, 1));
        entries.add(new Entry(2017, 2));
        entries.add(new Entry(2018, 3));
        entries.add(new Entry(2018, 4));
```

```

LineDataSet lDataSet1 = new LineDataSet(entries, "DataSet1");
        lDataSet1.setColor(Color.RED);
        lDataSet1.setCircleColor(Color.RED);
        lines.add(lDataSet1);


        lineChart.setData(new LineData(lDataSet1));
```

on my graph its showing 2015 ... on x and  0 to 4 approx y axis and  1,1,2,3,4 showing line so at where i can set y axis values hardcode ? can anyone help me on this issue?

**Comment by almic** [comment]
You should always use the `ValueFormatter` or `AxisValueFormatter` interfaces for your data. That alone will make things easier to work with in case your data changes later.

You should also look at the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/The-Axis) for the axes, it describes solutions to your problems.
