### ISSUE TITLE
LineChart X-axis value Abnormal display

### ISSUE THREAD

**Issue by lxfwelldone** [PhilJay/MPAndroidChart#4017]
hello!
My English is not good, so long story short.

normally, The X-axis is displayed normally. X-axis such as 1,2,3...
[Entry, x: 1.0 y: 24.3, Entry, x: 2.0 y: 1234.05, Entry, x: 3.0 y: 0.0, Entry, x: 4.0 y: 276.05, Entry, x: 5.0 y: 0.0, Entry, x: 6.0 y: 0.0, Entry, x: 7.0 y: 0.0, Entry, x: 8.0 y: 0.0, Entry, x: 9.0 y: 0.0, Entry, x: 10.0 y: 0.0, Entry, x: 11.0 y: 0.0, Entry, x: 12.0 y: 0.0, Entry, x: 13.0 y: 0.0, Entry, x: 14.0 y: 0.0, Entry, x: 15.0 y: 0.0, Entry, x: 16.0 y: 0.0, Entry, x: 17.0 y: 0.0, Entry, x: 18.0 y: 0.0, Entry, x: 19.0 y: 0.0, Entry, x: 20.0 y: 0.0, Entry, x: 21.0 y: 0.0, Entry, x: 22.0 y: 0.0, Entry, x: 23.0 y: 0.0, Entry, x: 24.0 y: 0.0, Entry, x: 25.0 y: 0.0, Entry, x: 26.0 y: 0.0, Entry, x: 27.0 y: 0.0, Entry, x: 28.0 y: 123.7, Entry, x: 29.0 y: 0.0, Entry, x: 30.0 y: 0.0]

but this not!!!  like 1.8, 2.7, 3.6, 4.5, 5.4.....
It looks like a multiple of 0.9.
I can't understand why this is. 
[Entry, x: 1.0 y: 0.0, Entry, x: 2.0 y: 0.0, Entry, x: 3.0 y: 0.0, Entry, x: 4.0 y: 0.0, Entry, x: 5.0 y: 0.0, Entry, x: 6.0 y: 0.0, Entry, x: 7.0 y: 0.0, Entry, x: 8.0 y: 0.0, Entry, x: 9.0 y: 416.28, Entry, x: 10.0 y: 1805.29, Entry, x: 11.0 y: 751.16, Entry, x: 12.0 y: 424.05]

The same code is used, but the data source is different.

Main part of the code:

       	private LineChart lineChart; 
	private LineDataSet line; 
        private  ArrayList<Entry> pointValues; 

        lineChart= (LineChart) findViewById(R.id.lineChart);
        Description description =new Description();
        description.setText("");
        description.setTextColor(Color.RED);
        description.setTextSize(20);
        lineChart.setDescription(description);
        lineChart.setNoDataText("没有数据!");
        lineChart.setNoDataTextColor(Color.GRAY);
        lineChart.setDrawGridBackground(false);
        lineChart.setDrawBorders(false);

        XAxis xAxis = lineChart.getXAxis();
        xAxis.setEnabled(true);
        xAxis.setDrawAxisLine(true);//
        xAxis.setDrawGridLines(false);//
        xAxis.setDrawLabels(true);//
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);//
        xAxis.enableGridDashedLine(3f, 3f, 0f);
        xAxis.setAvoidFirstLastClipping(true);
        xAxis.setLabelRotationAngle(10f);
        
        YAxis rightAxis=lineChart.getAxisRight();
       rightAxis.setEnabled(false);
       YAxis leftAxis = lineChart.getAxisLeft();
       leftAxis.enableGridDashedLine(10f, 10f, 0f);

     
       pointValues = new ArrayList<Entry>(); //datasource
     ...
       Get the data from the server and refresh it.

        if (lineChart.getData() != null && lineChart.getData().getDataSetCount() > 0) {
            line = (LineDataSet) lineChart.getData().getDataSetByIndex(0);
            line.setValues(pointValues);
            lineChart.getData().notifyDataChanged();
            lineChart.notifyDataSetChanged();
        } else {
            line = new LineDataSet(pointValues, "销售额");
            line.setColor(getResources().getColor(R.color.color_active));
            line.setCircleColor(Color.BLACK);
            line.setLineWidth(1f);
            line.setCircleRadius(3f);
            line.enableDashedHighlightLine(10f, 5f, 0f);
            line.setHighlightLineWidth(2f);
            line.setHighlightEnabled(true);
            line.setHighLightColor(Color.RED);
            line.setValueTextSize(10f);
            line.setDrawFilled(false);

            final DecimalFormat mFormat = new DecimalFormat("0.00");
            line.setValueFormatter(new IValueFormatter() {
				@Override
				public String getFormattedValue(float value, Entry entry,
						int dataSetIndex, ViewPortHandler viewPortHandler) {
					return mFormat.format(value);
				}
            });

            float ratio = (float) pointValues.size()/(float) 6; 
            lineChart.zoom(ratio,1f,0,0);
            ArrayList<ILineDataSet> dataSets = new ArrayList<>();
            dataSets.add(line); // add the datasets
            LineData data = new LineData(dataSets);
            lineChart.setData(data);
            lineChart.invalidate();
        }

Need any other Settings?

Thank you very much !

**Comment by almic** [comment]
I guess you figured out whatever problem you had? But please, don't remove the original comment on issues next time. Someone in the future may have the same problem and come here. But alas...

This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/), it probably has what you're looking for.
