### ISSUE TITLE
I am Confused about Setting grid width in barchart

### ISSUE THREAD

**Issue by Bishalsingh** [PhilJay/MPAndroidChart#402]
Hello Phil,
               What is the alternate of chart.setGridWidth(some float value); 
               chart.setDrawLegend(true) ?
![screenshot_2015-03-04-10-18-39 1](https://cloud.githubusercontent.com/assets/7859556/6478334/de2f343a-c258-11e4-819a-bd172bfab839.png)
![screenshot_2015-03-04-10-18-51 1](https://cloud.githubusercontent.com/assets/7859556/6478335/de33d152-c258-11e4-94ea-565805e34624.png)
 
In Earlier versions of library, Settings labels of Y-Axis disabled gave some more space, but in this version of library, if we set y-Axis disabled, only the labels are invisible, but it do consumes space. 
What i want is , if we set Labels invisible, the space should be more so that people can see clear graph.

**Comment by Bishalsingh** [comment]
In second graph, using earlier graph, setting label disabled removes the space as well, but it is not happening in newer versions of library

**Comment by PhilJay** [comment]
It`s all in the documentation wiki.

**Comment by Bishalsingh** [comment]
disabling the labels doesnot reduce the gap and i can't find this in wiki bro.
