### ISSUE TITLE
Line chart space 

### ISSUE THREAD

**Issue by arpitjoshi08** [PhilJay/MPAndroidChart#4020]
![ashx](https://user-images.githubusercontent.com/17329682/39860035-78312b16-5459-11e8-9b85-b07aad70b071.png)
i need to add space in x axis i tried may thing but not getting proper answer. How can i set margin from left in x axis labels (Show in attached image arrow)

**Comment by RobertZagorski** [comment]
Sorry, this feature is not implemented yet, I think.
There already is such Issue/Request: #3874.

**Comment by almic** [comment]
This issue tracker is not for support or questions, especially not when the answer is easily found in the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport). Just read it, I can guarantee you will find a way to do this given the currently available options. If you have `tried may thing` then please tell us *what* you tried. But, please, go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there.

It's a shame that so many people do not read the documentation, and also insist on **blatantly ignoring** the warnings present in the mandatory issue templates. Especially [this one](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) which I'm sure you already saw.
