### ISSUE TITLE
Wrong highlight y value

### ISSUE THREAD

**Issue by oleonov** [PhilJay/MPAndroidChart#4021]
```
val values = candles!!.mapIndexed { index, candle -> CandleEntry(index.toFloat(),
                                    candle.highPrice.toFloat(),
                                    candle.lowPrice.toFloat(),
                                    candle.openPrice.toFloat(),
                                    candle.closePrice.toFloat()) }
//Setting values to candleChart
```
Highlighting
`candleChart.highlightValue(values.last().x, values.last().close,0, true)`
And on graph I see wrong horizontal line position, for example close 9347, but line on 9355.
I use last library version
How to resolve it?

**Comment by almic** [comment]
This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/blob/master/.github/ISSUE_TEMPLATE/Support_help.md).

**Comment by oleonov** [comment]
Yes,that's why I wrote here. It's a bug.
