### ISSUE TITLE
BarDataSet ValueTextSize should increase/decrease based on pinch-to-zoom level

### ISSUE THREAD

**Issue by sumitsahoo** [PhilJay/MPAndroidChart#4022]
In BarChart when pinch gesture happens then the value text size of the bar should also increase. Is there a way to achieve this ?

**Comment by almic** [comment]
Why should it? If it's already readable, it will remain readable. You can manually change the text size of the value labels if you don't think it's big enough, but automatically changing the text size while zooming is just going to slow down the renderer to add an unnecessary effect.
