### ISSUE TITLE
RecycleView  Inside Child  Horizontal Recycle View  Crash When Scroll Right to Left (Last position to Previews Position).

### ISSUE THREAD

**Issue by hansraj123** [PhilJay/MPAndroidChart#4025]
Please Watch this  Error Video .
[https://www.youtube.com/watch?v=AvSOh_RYxnY&feature=youtu.be](url)

This my main Recycle View  Adapter Code.

`package com.h8.h8wifiad.login.adapter;

import android.content.Context;
import android.support.v7.widget.DefaultItemAnimator;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.util.Log;
import android.util.SparseIntArray;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;

import com.h8.h8wifiad.R;
import com.h8.h8wifiad.login.constants.MultiScrolllist;
import com.h8.h8wifiad.login.customfonts.CustomTextViewUbuntuRegular;
import com.h8.h8wifiad.login.dto.HostpotWiseConsumption_DTO;
import com.h8.h8wifiad.login.dto.QuestionSummery_Dto;
import com.h8.h8wifiad.login.dto.SumaryPerformance_DTO;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;

import static android.content.ContentValues.TAG;

/**
 * Created by Jeffrey Liu on 3/21/16.
 */
public class SummaryList_Main_Adapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {

    Context mContext;
    ArrayList<QuestionSummery_Dto> alQuestionSummery;
    ArrayList<SumaryPerformance_DTO> alSummaryPerformance;
    QuestionSummery_Dto questionSummery_dto;
    JSONArray jsonArrayChild;
    String response_answer, response_answerratio, response_answercount, response_subquestion;
    private SparseIntArray listPosition = new SparseIntArray();
    ArrayList<QuestionSummery_Dto> uniqueQuestionName;

    public SummaryList_Main_Adapter(ArrayList<SumaryPerformance_DTO> alSummaryPerformance, Context mContext) {
        this.alSummaryPerformance = alSummaryPerformance;
        this.mContext = mContext;
        alQuestionSummery = new ArrayList<>();
    }

    private class CellViewHolder extends RecyclerView.ViewHolder {

        private CustomTextViewUbuntuRegular tvQuestionName, tvsubQuestion;
        private LinearLayout linearMyCampaignRoot;
        private RecyclerView chartRecycleView;

        public CellViewHolder(View convertView) {
            super(convertView);
            try {
                linearMyCampaignRoot = convertView.findViewById(R.id.linearMyCampaignRoot);
                tvQuestionName = (CustomTextViewUbuntuRegular) convertView.findViewById(R.id.tvQuestionName);

                chartRecycleView = convertView.findViewById(R.id.chartRecycleView);

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(final ViewGroup viewGroup, int viewType) {
        mContext = viewGroup.getContext();
        switch (viewType) {
            default: {
                View v1 = LayoutInflater.from(viewGroup.getContext()).inflate(R.layout.sumary_list_raw, viewGroup, false);
                return new CellViewHolder(v1);
            }
        }
    }

    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder viewHolder, final int position) {

        String summaryData = alSummaryPerformance.get(position).getQuestionSummery();

        switch (viewHolder.getItemViewType()) {
            default: {
                CellViewHolder cellViewHolder = (CellViewHolder) viewHolder;
                cellViewHolder.tvQuestionName.setText(alSummaryPerformance.get(position).getQuestion());
                alQuestionSummery.clear();
                try {
                    jsonArrayChild = new JSONArray(summaryData);
                    JSONObject jsonObjectQuetion = new JSONObject();

                    for (int i = 0; i < jsonArrayChild.length(); i++) {
                        jsonObjectQuetion = jsonArrayChild.getJSONObject(i);
                        response_answer = jsonObjectQuetion.getString("answer");
                        response_answerratio = jsonObjectQuetion.getString("answerratio");
                        response_answercount = jsonObjectQuetion.getString("answercount");
                        response_subquestion = jsonObjectQuetion.getString("subquestion");
                        questionSummery_dto = new QuestionSummery_Dto(response_answer, response_answerratio
                                , response_answercount, response_subquestion
                        );
                        alQuestionSummery.add(questionSummery_dto);

                    }

                    uniqueQuestionName = new ArrayList<>();
                    uniqueQuestionName.clear();
                    int j = 0;
                    boolean isCheked = false;
                    for (QuestionSummery_Dto ays : alQuestionSummery) {
                        if (!ays.getSubquestion().matches("")) {
                            if (uniqueQuestionName.size() <= 0) {
                                if (!uniqueQuestionName.contains(ays.getSubquestion())) {
                                    questionSummery_dto = new QuestionSummery_Dto(ays.getAnswer(), ays.getAnswerratio()
                                            , ays.getAnswercount(), ays.getSubquestion());
                                    uniqueQuestionName.add(questionSummery_dto);

                                }
                            } else {
                                if (!uniqueQuestionName.get(j).getSubquestion().equalsIgnoreCase(ays.getSubquestion())) {
                                    questionSummery_dto = new QuestionSummery_Dto(ays.getAnswer(), ays.getAnswerratio()
                                            , ays.getAnswercount(), ays.getSubquestion());
                                    uniqueQuestionName.add(questionSummery_dto);
                                    j++;
                                }
                            }
                        } else {
                            if (!isCheked) {
                                questionSummery_dto = new QuestionSummery_Dto(ays.getAnswer(), ays.getAnswerratio()
                                        , ays.getAnswercount(), ays.getSubquestion());
                                uniqueQuestionName.add(questionSummery_dto);
                                isCheked = true;
                            }

                        }

                    }

                    Log.d(TAG, "setDataHostpotPerformanceChartData: " + uniqueQuestionName);

                } catch (JSONException e) {
                    e.printStackTrace();
                }
                MultiScrolllist multiScrolllist = new MultiScrolllist(mContext, LinearLayoutManager.HORIZONTAL, true);
                multiScrolllist.setReverseLayout(false);
                cellViewHolder.chartRecycleView.setLayoutManager(multiScrolllist);
                cellViewHolder.chartRecycleView.setItemAnimator(new DefaultItemAnimator());
                cellViewHolder.chartRecycleView.setHasFixedSize(true);
                SummaryList_Child_Adapter adapter = new SummaryList_Child_Adapter(uniqueQuestionName, alQuestionSummery, mContext);
                cellViewHolder.chartRecycleView.setAdapter(adapter);
//                adapter.setHasStableIds(true);
                cellViewHolder.chartRecycleView.setItemViewCacheSize(10);
                int lastSeenFirstPosition = listPosition.get(position, 0);
                if (lastSeenFirstPosition >= 0) {
                    cellViewHolder.chartRecycleView.scrollToPosition(lastSeenFirstPosition);
                }
                break;
            }
        }
    }

    @Override
    public void onViewRecycled(RecyclerView.ViewHolder viewHolder) {
        final int position = viewHolder.getAdapterPosition();
        CellViewHolder cellViewHolder = (CellViewHolder) viewHolder;
        LinearLayoutManager layoutManager = ((LinearLayoutManager) cellViewHolder.chartRecycleView.getLayoutManager());
        int firstVisiblePosition = layoutManager.findFirstVisibleItemPosition();
        listPosition.put(position, firstVisiblePosition);

        super.onViewRecycled(viewHolder);
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public int getItemViewType(int position) {
        return position;
    }

    @Override
    public int getItemCount() {
        if (alSummaryPerformance == null)
            return 0;
        return alSummaryPerformance.size();
    }

}`

======================
this my Child Recycle View  Code 

`package com.h8.h8wifiad.login.adapter;

import android.content.Context;
import android.graphics.Color;
import android.support.v7.widget.CardView;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;

import com.github.mikephil.charting.charts.PieChart;
import com.github.mikephil.charting.components.Legend;
import com.github.mikephil.charting.data.PieData;
import com.github.mikephil.charting.data.PieDataSet;
import com.github.mikephil.charting.data.PieEntry;
import com.github.mikephil.charting.formatter.PercentFormatter;
import com.github.mikephil.charting.utils.ColorTemplate;
import com.h8.h8wifiad.R;
import com.h8.h8wifiad.login.customfonts.CustomTextViewUbuntuRegular;
import com.h8.h8wifiad.login.dto.QuestionSummery_Dto;

import java.util.ArrayList;
import java.util.Random;

/**
 * Created by Jeffrey Liu on 3/21/16.
 */
public class SummaryList_Child_Adapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {

    LayoutInflater layoutInflater;
    Context mContext;
    ArrayList<QuestionSummery_Dto> alQuestionSummery;
    ArrayList<QuestionSummery_Dto> uniqueQuestionName;
    ArrayList<PieEntry> entries;
    PieDataSet dataSet;
    String subQuestionsName;
    PieData data;
    boolean isEnteryDataAdded = false;

    public SummaryList_Child_Adapter(ArrayList<QuestionSummery_Dto> uniqueQuestionName, ArrayList<QuestionSummery_Dto> alQuestionSummery, Context mContext) {
        this.alQuestionSummery = alQuestionSummery;
        this.mContext = mContext;
        this.uniqueQuestionName = uniqueQuestionName;
        entries = new ArrayList<PieEntry>();

    }

    private class CellViewHolder extends RecyclerView.ViewHolder {
        private PieChart summaryPieChart;
        CustomTextViewUbuntuRegular tvsubQuestion;
        CardView summary_child_mRoot;

        public CellViewHolder(View itemView) {
            super(itemView);
            summaryPieChart = (PieChart) itemView.findViewById(R.id.summaryPieChart);
            tvsubQuestion = (CustomTextViewUbuntuRegular) itemView.findViewById(R.id.tvsubQuestion);
            summary_child_mRoot=itemView.findViewById(R.id.summary_child_mRoot);

        }

    }

    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(final ViewGroup viewGroup, int viewType) {

        switch (viewType) {
            default: {
                View v1 = LayoutInflater.from(viewGroup.getContext()).inflate(R.layout.summary_child_raw, viewGroup, false);
                return new CellViewHolder(v1);
            }
        }
    }

    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder viewHolder, int position) {

        entries.clear();
        switch (viewHolder.getItemViewType()) {
            default: {
                CellViewHolder cellViewHolder = (CellViewHolder) viewHolder;
                try {
                    if (!uniqueQuestionName.get(position).getSubquestion().equalsIgnoreCase("") && !uniqueQuestionName.get(position).getSubquestion().equalsIgnoreCase(" ")) {
                        cellViewHolder.tvsubQuestion.setVisibility(View.VISIBLE);
                        cellViewHolder.tvsubQuestion.setText(uniqueQuestionName.get(position).getSubquestion());
                        subQuestionsName = uniqueQuestionName.get(position).getSubquestion();
                        LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(
                                LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT);

                        cellViewHolder.summary_child_mRoot.setLayoutParams(layoutParams);

                    } else {
                        cellViewHolder.tvsubQuestion.setVisibility(View.GONE);

                    }

                    for (QuestionSummery_Dto dto : alQuestionSummery) {
                        if (uniqueQuestionName.size() <= 1) {
                            entries.add(new PieEntry(Float.parseFloat(dto.getAnswerratio()), dto.getAnswer()));
                        } else {
                            try {
                                if (dto.getSubquestion().contains(subQuestionsName)) {

                                    entries.add(new PieEntry(Float.parseFloat(dto.getAnswerratio()), dto.getAnswer()));

                                }
                            } catch (ArrayIndexOutOfBoundsException e) {
                                e.printStackTrace();
                            }
                        }
                    }

                    cellViewHolder.summaryPieChart.setUsePercentValues(true);
                    cellViewHolder.summaryPieChart.getDescription().setEnabled(false);

                    cellViewHolder.summaryPieChart.setDragDecelerationFrictionCoef(0.95f);

//
//            holder.summaryPieChart.setExtraOffsets(20.f, 0.f, 20.f, 0.f);

                    cellViewHolder.summaryPieChart.setDrawHoleEnabled(true);
                    cellViewHolder.summaryPieChart.setHoleColor(Color.WHITE);

                    cellViewHolder.summaryPieChart.setTransparentCircleColor(Color.GRAY);
                    cellViewHolder.summaryPieChart.setTransparentCircleAlpha(110);

                    cellViewHolder.summaryPieChart.setHoleRadius(2f);
                    cellViewHolder.summaryPieChart.setTransparentCircleRadius(5f);
                    cellViewHolder.summaryPieChart.setDrawCenterText(true);
                    cellViewHolder.summaryPieChart.setRotationAngle(0);
                    cellViewHolder.summaryPieChart.setRotationEnabled(true);
                    cellViewHolder.summaryPieChart.setHighlightPerTapEnabled(true);

                    dataSet = new PieDataSet(entries, "Survey  Data");
                    dataSet.setDrawValues(false);
                    data = new PieData(dataSet);
                    dataSet.setSliceSpace(3f);
                    dataSet.setSelectionShift(5f);
                    dataSet.setColor(Color.BLACK);

                    showChart(cellViewHolder.summaryPieChart,data);

                } catch (Exception e) {
                    e.printStackTrace();
                }

                break;

            }

        }

//
    }

    private void showChart(PieChart chart, PieData data) {
        if (chart == null || data == null) {
            return;
        }
        ArrayList<Integer> colors = new ArrayList<Integer>();
//
        for (int c : ColorTemplate.MATERIAL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.JOYFUL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.COLORFUL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.MATERIAL_COLORS)
            colors.add(c);

        for (int c : ColorTemplate.COLORFUL_COLORS)
            colors.add(c);
//                    Random rnd = new Random();
//                    int color = Color.argb(255, rnd.nextInt(220), rnd.nextInt(250), rnd.nextInt(220));
//                view.setBackgroundColor(color);
//                    colors.add(colors);

        dataSet.setColors(colors);
        dataSet.setSelectionShift(0f);

        dataSet.setValueLinePart1OffsetPercentage(80.f);
        dataSet.setValueLinePart1Length(0.2f);
        dataSet.setValueLinePart2Length(0.4f);
        dataSet.setXValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);
        dataSet.setYValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);

        data.setValueFormatter(new PercentFormatter());
        data.setValueTextSize(9f);
        data.setValueTextColor(Color.BLACK);

        chart.setData(data);

        // undo all highlights
        chart.highlightValues(null);

//                        cellViewHolder.summaryPieChart.animateY(1400, Easing.EasingOption.EaseInOutQuad);

        Legend l = chart.getLegend();
        l.setVerticalAlignment(Legend.LegendVerticalAlignment.TOP);
        l.setHorizontalAlignment(Legend.LegendHorizontalAlignment.RIGHT);
        l.setOrientation(Legend.LegendOrientation.VERTICAL);
        l.setTextColor(Color.BLACK);
        l.setDrawInside(false);
        l.setEnabled(false);
        chart.notifyDataSetChanged();
        chart.invalidate();

    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public int getItemViewType(int position) {
        return position;
    }

    @Override
    public int getItemCount() {
        if (uniqueQuestionName == null)
            return 0;
        return uniqueQuestionName.size();
    }

}`

**Comment by RobertZagorski** [comment]
Could you please share a crashlog, too?

**Comment by almic** [comment]
This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/), it probably has what you're looking for.
