### ISSUE TITLE
Interested to show data set values outside of graph top side.

### ISSUE THREAD

**Issue by KarthikKompelli** [PhilJay/MPAndroidChart#4027]
Please check this image, I interested to show chart like this. How can i do
I need this chart
![chart](https://user-images.githubusercontent.com/1123257/39941299-bca5ec5c-5579-11e8-8e4c-3388ebb69092.png)
![chart2](https://user-images.githubusercontent.com/1123257/39942031-f1c26030-557b-11e8-9c56-605dbeaefce0.png)

this my output, but need above chart result
![chart3](https://user-images.githubusercontent.com/1123257/39942032-f20760cc-557b-11e8-9e37-63e7df63f1d7.png)

# *STOP RIGHT THERE!*

Issues are ***NOT*** for getting help, only for reporting bugs and feature requests.

Search open and closed issues to see if your question already has an answer. However, **do not create a new issue.**

Instead, do the following:

1. Download the [Example App](https://play.google.com/store/apps/details?id=com.xxmassdeveloper.mpchartexample) and check out the [source code](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample). 90% of the time there is an example that does exactly what you are trying to do.

1. Look at the [Wiki](https://github.com/PhilJay/MPAndroidChart/wiki) for the official documentation for MPAndroidChart. You can also browse the [javadoc](https://jitpack.io/com/github/PhilJay/MPAndroidChart/v3.0.3/javadoc/) for a more detailed tutorial of the API.

1. Go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. The community will be much more helpful and willing to offer guidance.

### You have been warned!

From now on, any issues asking for help will get closed with a link to this file.

**Comment by almic** [comment]
You must be joking 🤣

> # *STOP RIGHT THERE!*
> 
> Issues are ***NOT*** for getting help, only for reporting bugs and feature requests.
> 
> Search open and closed issues to see if your question already has an answer. However, **do not create a new issue.**
> 
> Instead, do the following:
> 
> 1. Download the [Example App](https://play.google.com/store/apps/details?id=com.xxmassdeveloper.mpchartexample) and check out the [source code](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample). 90% of the time there is an example that does exactly what you are trying to do.
> 
> 1. Look at the [Wiki](https://github.com/PhilJay/MPAndroidChart/wiki) for the official documentation for MPAndroidChart. You can also browse the [javadoc](https://jitpack.io/com/github/PhilJay> /MPAndroidChart/v3.0.3/javadoc/) for a more detailed tutorial of the API.
> 
> 1. Go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. The community will be much more helpful and willing to offer guidance.
> 
> 
> ### You have been warned!
> 
> From now on, any issues asking for help will get closed with a link to this file.

Although this is a feature request for double x-axis, something the y-axis already has, I am closing it because you didn't understand the difference between "I need help!" and "Suggest a feature," likely because you assumed this was already a feature since you didn't attempt to look at the documentation or read that template you left sitting at the bottom of your issue comment.

Also, you added the same picture twice, the original edit and second edit, without removing the original image of the same problem.
