### ISSUE TITLE
Interested to show data set values outside of graph top side. line chart

### ISSUE THREAD

**Issue by KarthikKompelli** [PhilJay/MPAndroidChart#4029]
Please check this image, I interested to show chart like this. How can i do
I need this chart
![chart](https://user-images.githubusercontent.com/1123257/39941299-bca5ec5c-5579-11e8-8e4c-3388ebb69092.png)
![chart2](https://user-images.githubusercontent.com/1123257/39942031-f1c26030-557b-11e8-9c56-605dbeaefce0.png)

this my output, but need above chart result
![chart3](https://user-images.githubusercontent.com/1123257/39942032-f20760cc-557b-11e8-9e37-63e7df63f1d7.png)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by almic** [comment]
Why have you reposted this issue? #4027 ...
