### ISSUE TITLE
Graph drawing incorrectly when visibility changed

### ISSUE THREAD

**Issue by fiskurgit** [PhilJay/MPAndroidChart#403]
I have a graph with Visibility.GONE - when I change to VISIBLE and build the chart it draws incorrectly:

![screenshot_2015-03-04-10-21-06](https://cloud.githubusercontent.com/assets/5167046/6481852/ba6a226c-c258-11e4-97ed-33b795b45c19.png)

I suspect this may be related to my using `graph.setViewPortOffsets(0, 0, 0, 0);` but even when the view is always visible the first render always draw incorrectly:

![screenshot_2015-03-04-10-23-23](https://cloud.githubusercontent.com/assets/5167046/6481874/ed9106b0-c258-11e4-9c79-a1c14e500e6e.png)

all subsequent calls updating the graph draw as expected:

![screenshot_2015-03-04-10-21-20](https://cloud.githubusercontent.com/assets/5167046/6481885/06da4f3c-c259-11e4-8ab9-943164d0165d.png)

I've put in place a horrendous hack (in my Activity) to force a redraw the first time the view is displayed as invalidate doesn't work, this is obviously not ideal:

```
if(redraw){
            Timber.d("First graph viewing - redrawing");
            TimerTask task = new TimerTask() {

                public void run() {
                    runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            setData(elevations, false);
                        }
                    });


                }
            };

            Timer timer = new Timer();
            timer.schedule(task, 250);
        }
```

**Comment by PhilJay** [comment]
Thanks, I will look into it.

**Comment by PhilJay** [comment]
I have made some changes concerning your issue.

It should be possible now without that hack you developed.

Do it this way:

 - set chart visibility to "gone" in .xml
 - change visibility to "visible" in code
 - change offsets to 0,0,0,0
 - set data to the chart

Let me know if it works now.

**Comment by klevi** [comment]
I use the component as an item of a RecyclerView and the same issue happens here as well. For the following method call order the chart isn't drawn correctly for the first time. The issue is not related to setting view visibility.

```java
mChart.setViewPortOffsets(0, 0, 0, 0);
mChart.setData(data);
mChart.getLegend().setEnabled(false);
mChart.animateY(1500);
```

**Comment by davix10** [comment]
I have a similar problem. I have two charts and I can choose whether to display the first, second, or both together. when I view only the first or only the second is fine but if I choose to view them together, and then the first or the second I get a graph cut in half. why?

**Comment by davix10** [comment]
I solved using resetViewPortOffsets().
Thanks
