### ISSUE TITLE
Critical bug

### ISSUE THREAD

**Issue by oleonov** [PhilJay/MPAndroidChart#4030]
val values = candles!!.mapIndexed { index, candle -> CandleEntry(index.toFloat(),
                                    candle.highPrice.toFloat(),
                                    candle.lowPrice.toFloat(),
                                    candle.openPrice.toFloat(),
                                    candle.closePrice.toFloat()) }
//Setting values to candleChart

Highlighting
candleChart.highlightValue(values.last().x, values.last().close,0, true)
And on graph I see wrong horizontal line position, for example close 9347, but line on 9355.
I use last library version
It's critical bug.

**Comment by almic** [comment]
> It's a critical bug.

No, this is not. This is normal behavior. If your users know how to read a candlestick chart, they ought to know which is the open and close, and do not need the chart to hold their hand and show them which one it is.

You can use `ValueFormatter` to make it more obvious what the actual numbers are :+1:

**Comment by channae** [comment]
Can we override this behaviour and show actual values instead? I want to use this chart as a vertical range graph (non stock related). Could you point out which class does this calculation I can modify the logic
