### ISSUE TITLE
Horizontal Bar Chart Length out of bound

### ISSUE THREAD

**Issue by segunmicheal27** [PhilJay/MPAndroidChart#4031]
I get out of bound error if the supply entry value is equals to the length of BarEntry like this:

```java
int[] valuesRating = new int[]{ 30, 32, 34, 45, 65 }; // This is y values

for (int i = 1; i < valuesRating.length +1; i++) {
    yVals1.add(new BarEntry(i * spaceForBar, valuesRating[i]));
}
```

or 

```java
int[] valuesRating = new int[]{ 30, 32, 34, 45, 65 }; // This is y values

for (int i = 0; i <= valuesRating.length; i++) {
    yVals1.add(new BarEntry(i * spaceForBar, valuesRating[i]));
}
```

i get this error

`java.lang.ArrayIndexOutOfBoundsException: length=5; index=5`

how can i fix this error?

**Comment by almic** [comment]
This is a well known issue, having been reported a number of times already. If you had tried searching existing issues, I'm sure you would've found them. Closed for being a duplicate.
