### ISSUE TITLE
How to position marker?

### ISSUE THREAD

**Issue by ronakp** [PhilJay/MPAndroidChart#4035]
I am using `MarkerView` for marker on Line Chart.
```
public class MPChartLineMarker extends MarkerView
{
        private TextView markerText;
	private MPPointF mOffset;

	public MPChartLineMarker(Context context, int layoutResource)
	{
		super(context, layoutResource);
		markerText = (TextView) findViewById(R.id.marker_text);
	}

	@Override
	public void refreshContent(Entry e, Highlight highlight)
	{
		markerText.setText(String.valueOf(e.getY()));
		super.refreshContent(e, highlight);
	}
}
```
How can I position my Marker on chart? I want show it aligned top of my chart view as I track through line chart.

**Comment by almic** [comment]
This is not possible by default, but I'm sure you can implement this yourself if you look [here](https://github.com/PhilJay/MPAndroidChart/wiki/Highlighting). Shouldn't be hard at all, if you know what you're doing.
