### ISSUE TITLE
Need to set XAxis label count to 1

### ISSUE THREAD

**Issue by gathasite** [PhilJay/MPAndroidChart#4036]
Hi
Need to set label count to 1, tried setLabelCount(1, true) but its not working and setting it to default min count i.e. 2

Also need to set the entry count depending on the values, in my case its 1, but the entries have 7 values by default from 0 to 6 and throwing IndexOutOfBoundsException:: Index 1, Size 1 while setting the xAxisvalue formatter.
Tried setting mChart.setVisibleXRangeMaximum(1) but didnt work.

**Comment by almic** [comment]
Why did you close this?

**Comment by tahagit** [comment]
If you're using IAxisValueFormatter, just add this code inside that:

       IAxisValueFormatter formatter = new IAxisValueFormatter() {
                    @Override
                    public String getFormattedValue(float value, AxisBase axis) {
                        if (((int) value) < YOURLISTDATA.size()) {
                            return YOURLISTDATA.get((int) value);
                        } else {
                            return "0";
                        }

                    }
                };
