### ISSUE TITLE
LineChart 怎样设置x轴点距原点一段距离 How does LineChart set the distance from the origin point of the X axis

### ISSUE THREAD

**Issue by baohexin** [PhilJay/MPAndroidChart#4038]
LineChart 怎样设置x轴点距原点一段距离
How does LineChart set the distance from the origin point of the X axis

**Comment by zhenqinrui** [comment]
I also need to se the distance from the origin point of the X axis, I try the method it doesn't work

**Comment by almic** [comment]
This issue tracker is not for [support questions](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) or personal debugging. If you have questions, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. You could also read the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/) and look at the [example app](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample), it probably has what you're looking for.

**Comment by faith-hb** [comment]
I also need to se the distance from the origin point of the X axis, Ask for help

**Comment by faith-hb** [comment]
> LineChart 怎样设置x轴点距原点一段距离
> How does LineChart set the distance from the origin point of the X axis

试下这个：setDragOffsetX

**Comment by faith-hb** [comment]
> I also need to se the distance from the origin point of the X axis, I try the method it doesn't work

try setDragOffsetX
