### ISSUE TITLE
if only one value is non zero pie chart not coming up

### ISSUE THREAD

**Issue by harshmalhotra113** [PhilJay/MPAndroidChart#4040]
# *STOP RIGHT THERE!*

Issues are ***NOT*** for getting help, only for reporting bugs and feature requests.

Search open and closed issues to see if your question already has an answer. However, **do not create a new issue.**

Instead, do the following:

1. Download the [Example App](https://play.google.com/store/apps/details?id=com.xxmassdeveloper.mpchartexample) and check out the [source code](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample). 90% of the time there is an example that does exactly what you are trying to do.

1. Look at the [Wiki](https://github.com/PhilJay/MPAndroidChart/wiki) for the official documentation for MPAndroidChart. You can also browse the [javadoc](https://jitpack.io/com/github/PhilJay/MPAndroidChart/v3.0.3/javadoc/) for a more detailed tutorial of the API.

1. Go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. The community will be much more helpful and willing to offer guidance.

### You have been warned!

From now on, any issues asking for help will get closed with a link to this file.

**Comment by almic** [comment]
LMAO
