### ISSUE TITLE
How can I stop the translation(Kinetic Scolling)?如何停止惯性滑动

### ISSUE THREAD

**Issue by juicelover** [PhilJay/MPAndroidChart#4041]
I have a question.
After I dragged one chart, it can have an inertia slip time. At this point,how can I stop the translation?

Thanks

**Comment by juicelover** [comment]
I solved it.
mChartDateLine.setDragDecelerationFrictionCoef(0f);
The fun can stop the Kinetic Scolling.

图表的 抛掷/减速
setDragDecelerationEnabled(boolean enabled) : 如果设置为true，手指滑动抛掷图表后继续减速滚动。 默认值：true。
setDragDecelerationFrictionCoef(float coef) : 减速的摩擦系数在[0; 1]区间，数值越高表示速度会缓慢下降，例如，如果将其设置为0，将立即停止。 1是一个无效的值，会自动转换至0.9999。

Thanks for 天一方蓝,the following is his blogs.
https://blog.csdn.net/dt235201314/article/details/52222088

**Comment by almic** [comment]
Thanks for figuring it out yourself, instead of doing what most people do and just wait for someone to fix it for you. 👍
