### ISSUE TITLE
如何一个Y轴对应一条折线的数据--How does a Y axis correspond to a broken line

### ISSUE THREAD

**Issue by HuaZaiWuDi** [PhilJay/MPAndroidChart#4043]
# *STOP RIGHT THERE!*

Issues are ***NOT*** for getting help, only for reporting bugs and feature requests.

Search open and closed issues to see if your question already has an answer. However, **do not create a new issue.**

Instead, do the following:

1. Download the [Example App](https://play.google.com/store/apps/details?id=com.xxmassdeveloper.mpchartexample) and check out the [source code](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample). 90% of the time there is an example that does exactly what you are trying to do.

1. Look at the [Wiki](https://github.com/PhilJay/MPAndroidChart/wiki) for the official documentation for MPAndroidChart. You can also browse the [javadoc](https://jitpack.io/com/github/PhilJay/MPAndroidChart/v3.0.3/javadoc/) for a more detailed tutorial of the API.

1. Go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. The community will be much more helpful and willing to offer guidance.

### You have been warned!

From now on, any issues asking for help will get closed with a link to this file.

**Comment by almic** [comment]
I can tell you don't speak English, but that is no excuse to ignore the template completely. We live in 2018 with decent translation tools at our disposal. I don't ignore issues in other languages, I often try to translate them and answer them as best I can, but this issue simply doesn't help me understand what problem you are having.

You left [this template](https://github.com/PhilJay/MPAndroidChart/edit/master/.github/ISSUE_TEMPLATE/Support_help.md) in the body of the issue.

**Comment by baohexin** [comment]
lineDataSet.setAxisDependency(YAxis.AxisDependency.LEFT);数据对应左边Y轴
lineDataSet.setAxisDependency(YAxis.AxisDependency.RIGHT);数据对应右边Y轴
