### ISSUE TITLE
这个x轴的文字怎么换行啊，x轴的文字比较多。

### ISSUE THREAD

**Issue by itsgm** [PhilJay/MPAndroidChart#4050]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by almic** [comment]
sorry but this issue tracker is not the place to ask for programming help. Questions like this belong on stackoverflow.

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.

**Comment by Trammels** [comment]
需要修改源码

**Comment by zengx1998** [comment]
大佬 你解决了不
