### ISSUE TITLE
X axis doesn't display long text,Only last label has this problem(X轴文字过长不能显示全，最后一个数据有这个问题)

### ISSUE THREAD

**Issue by qidianli** [PhilJay/MPAndroidChart#4057]
``  
![qq 20180523170010](https://user-images.githubusercontent.com/19253019/40414442-c4a25ca8-5eaa-11e8-96db-610c8263f395.png)

 //初始化数据
        initData();
        //初始化MpChat
        initView();
        //初始化Y轴
        initY();
        //初始化X轴
        initX();
  

    private void initData() {
        //这里我模拟一些数据
        mValues1 = new ArrayList<Entry>();
        mValues1.add(new Entry(0, 66));
        mValues1.add(new Entry(1, 66));
        mValues1.add(new Entry(2, 66));
        mValues1.add(new Entry(3, 120));
        mValues1.add(new Entry(4, 30));
        mValues1.add(new Entry(5, 10));
        mValues1.add(new Entry(6, 110));
        mValues1.add(new Entry(7, 30));
        mValues1.add(new Entry(8, 160));
        mValues1.add(new Entry(9, 30));
        //实际的点
        mValuesX = new ArrayList<>();
        mValuesX.add("2017-01-01");
        mValuesX.add("2017-02-01");
        mValuesX.add("2017-03-01");
        mValuesX.add("2017-04-01");
        mValuesX.add("2017-05-01");
        mValuesX.add("2017-06-01");
        mValuesX.add("2017-07-01");
        mValuesX.add("2017-08-01");
        mValuesX.add("2017-09-01");
        mValuesX.add("2017-10-01");
    }

    //初始化View
    private void initView() {
        //基本控件
        //后台绘制
        mLineChar.setDrawGridBackground(false);
        //设置描述文本
        mLineChar.getDescription().setEnabled(false);
        mLineChar.setDragDecelerationFrictionCoef(0.9f);
        //设置推动
        mLineChar.setDragEnabled(true);
        //设置缩放
        mLineChar.setScaleEnabled(false);
        //如果禁用,扩展可以在x轴和y轴分别完成
        mLineChar.setPinchZoom(true);
        float ratio = (float) mValues1.size() / (float)5;
        //显示的时候是按照多大的比率缩放显示,1f表示不放大缩小
        mLineChar.zoom(ratio, 1f, 0, 0);
    }

    private void initY() {
        LimitLine ll1 = new LimitLine(150f, "参考上限");
        ll1.setLineWidth(1f);
        ll1.setLabelPosition(LimitLine.LimitLabelPosition.LEFT_TOP);
        ll1.setTextSize(10f);
        ll1.setTextColor(Color.BLACK);
        ll1.setLineColor(Color.RED);

        LimitLine ll2 = new LimitLine(30f, "参考下限");
        ll2.setLineWidth(1f);
        ll2.setLabelPosition(LimitLine.LimitLabelPosition.LEFT_BOTTOM);
        ll2.setTextSize(10f);
        ll2.setTextColor(Color.BLACK);
        ll2.setLineColor(Color.BLUE);

        YAxis leftAxis = mLineChar.getAxisLeft();
        //重置所有限制线,以避免重叠线
        leftAxis.removeAllLimitLines();
        //设置优秀线
        leftAxis.addLimitLine(ll1);
        //设置及格线
        leftAxis.addLimitLine(ll2);
        //y轴最大
        leftAxis.setAxisMaximum(200f);
        //y轴最小
        leftAxis.setAxisMinimum(0f);
        leftAxis.setDrawZeroLine(false);
        // 限制数据(而不是背后的线条勾勒出了上面)
        leftAxis.setDrawLimitLinesBehindData(true);
        mLineChar.getAxisRight().setEnabled(false);
        //设置数据
        setData(mValues1);
        //默认动画
        mLineChar.animateX(2500);
        // 得到这个文字
        Legend l = mLineChar.getLegend();
        l.setForm(Legend.LegendForm.NONE);
        l.setTextColor(Color.parseColor("#ffffff"));
    }

    private void initX() {
        //x轴
        XAxis xAxis = mLineChar.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM); //定制X轴是在图表上方还是下方。
        xAxis.setDrawGridLines(false);
        xAxis.setGranularity(1f);
        xAxis.setGranularityEnabled(true);
        xAxis.setTextSize(10);
        xAxis.setValueFormatter(new MyCustomXAxisValueFormatter(mValuesX));
    }

    //传递数据集
    private void setData(ArrayList<Entry> values) {
        if (mLineChar.getData() != null && mLineChar.getData().getDataSetCount() > 0) {
            set1 = (LineDataSet) mLineChar.getData().getDataSetByIndex(0);
            set1.setValues(values);
            mLineChar.getData().notifyDataChanged();
            mLineChar.notifyDataSetChanged();
        } else {
            // 创建一个数据集,并给它一个类型
            set1 = new LineDataSet(values, "数据比对");
            // 在这里设置线
            set1.setColor(getResources().getColor(R.color.orange));
            set1.setCircleColor(getResources().getColor(R.color.orange));
            set1.setLineWidth(1f);
            set1.setCircleRadius(3f);
            set1.setDrawCircleHole(true);
            set1.setValueTextSize(9f);
            set1.setDrawFilled(true);
            set1.setFormLineWidth(1f);
            set1.setFormLineDashEffect(new DashPathEffect(new float[]{10f, 5f}, 0f));
            set1.setFormSize(15.f);
            set1.setFillColor(getResources().getColor(R.color.back1));
            ArrayList<ILineDataSet> dataSets = new ArrayList<ILineDataSet>();
            //添加数据集
            dataSets.add(set1);
            //创建一个数据集的数据对象
            LineData data = new LineData(dataSets);
            //谁知数据
            mLineChar.setData(data);
        }
    }

> 
public class MyCustomXAxisValueFormatter implements IAxisValueFormatter {
    private List<String> labels;

    /**
     * @param labels 要显示的标签字符数组
     */
    public MyCustomXAxisValueFormatter(List<String> labels) {
        this.labels = labels;
    }

    @Override
    public String getFormattedValue(float value, AxisBase axis) {
        Log.e("hehe", "value:" + value + ";size:" + labels.size());
        return labels.get((int) value % labels.size());
    }
}
> ``

**Comment by ningjiaqi** [comment]
解决了没，同求

**Comment by OvenCroc** [comment]
大兄弟解决了没有啊 我也遇到一样的问题了 x轴的label超了

**Comment by chinachance** [comment]
同求

**Comment by Yuriko-wbh** [comment]
x轴的长度可以延长，没记错的话可以这么写
xAxis.setAxisMinimum(0f);
xAxis.setAxisMaximum(lineValues.length-0.5f);

**Comment by Jiansion** [comment]
设置图表的偏移位置，多出的位置就可以绘制文本了
mLineChar.setExtraOffsets(20f, 0f, 40f, 0f)
