### ISSUE TITLE
AxisLeft SetStartAtZero only works on Screen Rotation

### ISSUE THREAD

**Issue by gray419** [PhilJay/MPAndroidChart#406]
I am using a line chart on a fragment inside of a viewpager. When I launch the activity it defaults the chart to start the y-axis at 0 even though I have set the chart property to false.

```java
        LineData data = new LineData(xVal, dataSets);
        lineChart.setData(data);
        lineChart.getAxisRight().setEnabled(false);
        lineChart.getLegend().setEnabled(false);
        lineChart.getAxisLeft().setStartAtZero(false); //Set to not start at 0
        lineChart.getAxisLeft().setPosition(YAxis.YAxisLabelPosition.INSIDE_CHART);
        lineChart.getXAxis().setPosition(XAxis.XAxisPosition.BOTTOM_INSIDE);
        lineChart.getXAxis().setAvoidFirstLastClipping(true);
        lineChart.getXAxis().setTextSize(8f);
        lineChart.getAxisLeft().setTextSize(8f);
        lineChart.setTouchEnabled(false);
        lineChart.fitScreen();
        lineChart.setLogEnabled(true);
```
On Activity Start
![screen shot 2015-03-04 at 4 44 23 pm](https://cloud.githubusercontent.com/assets/3689237/6494222/1d55bd70-c28e-11e4-94bd-a408b801cc45.png)

On Rotate Landscape
![screen shot 2015-03-04 at 4 44 37 pm](https://cloud.githubusercontent.com/assets/3689237/6494221/1d55bf14-c28e-11e4-918a-55f08a703004.png)

On Rotate Vertical
![screen shot 2015-03-04 at 4 44 50 pm](https://cloud.githubusercontent.com/assets/3689237/6494220/1d55bc94-c28e-11e4-8ee9-6344f2b9e5a2.png)

```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.github.mikephil.charting.charts.LineChart
        android:id="@+id/lineChart"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</FrameLayout>
```

**Comment by PhilJay** [comment]
Have you tried setting this before calling `setData(...)`?

```java
chart.getAxisLeft().setStartAtZero(false);
chart.setData(...);
```

Does it work then?

**Comment by gray419** [comment]
Nice!, also it seems to be adding padding to the left when I put labels inside the chart like this:

```java
lineChart.getAxisLeft().setPosition(YAxis.YAxisLabelPosition.INSIDE_CHART);
```

**Comment by PhilJay** [comment]
Yep, sorry for that.

`chart.getAxisLeft().setPosition(YAxis.YAxisLabelPosition.INSIDE_CHART);`
currently doesnt work, its a known issue I will fix it in next release.
