### ISSUE TITLE
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.github.PhilJay:MPandroidChart:v3.0.3.	

### ISSUE THREAD

**Issue by uttampawar** [PhilJay/MPAndroidChart#4061]
Hi,
I'm working on Android project where I'm trying to add MPAndroidChart as follows,

At project level build.gradle file I've two repositories,
allprojects {
repositories {
  jcenter()
  maven { url 'https://maven.google.com' }
  maven { url "https://jitpack.io" }
  }
}
'Sync' at this point works okay. After that I added following line to the app/build.gradle file as,

dependencies {
...
...
...
implementation 'com.github.PhilJay:MPAndroidChart:v3.0.2'
}

With this change, I started getting 'Could not resolve' error. What am I missing? Any help is appreciated.

Build env:
Mac OS X High Sierra, 10.13
Android Studio version: 3.1.2

**Comment by almic** [comment]
make sure you are following the directions exactly on the README
