### ISSUE TITLE
When I refresh data frequently, APP will stop after a period of time.当我频繁的刷新图标中的曲线数据，app会停止运行

### ISSUE THREAD

**Issue by XYyelian** [PhilJay/MPAndroidChart#4068]
**Summary**
I create four entry and add one data each entry per second.What code I am used is just like 
                        set1 = (LineDataSet) fluLineChart.getData().getDataSetByIndex(0);
			set2 = (LineDataSet) fluLineChart.getData().getDataSetByIndex(1);
			set3 = (LineDataSet) fluLineChart.getData().getDataSetByIndex(2);
			set4 = (LineDataSet) fluLineChart.getData().getDataSetByIndex(3);
			set1.setValues(yVals1);
			set2.setValues(yVals2);
			set3.setValues(yVals3);
			set4.setValues(yVals4);
                        fluLineXAxis.setAxisMaximum(xMax);
			fluLineXAxis.setAxisMinimum(0f);
                        fluLineLeftAxis.setAxisMaximum(max);
		        fluLineLeftAxis.setAxisMinimum(0f);
                        fluLineChart.getData().notifyDataChanged();
		        fluLineChart.notifyDataSetChanged();
		        fluLineChart.invalidate();
xMax is a multiple of 6. like  the max X value is 15,then xMax is 18
max is a multiple of 1000. like the max Y value is 1862,then max is 2000

After about an hour,the app stops without any crash logs.So I donot know how to fix it.
我用上面的代码频繁的刷新图形数据，4条曲线每秒都会加1个数据。X轴的最大值是向上取整到6的倍数，Y轴的最大值是向上取整到1000的倍数，他们的最小值都是从0开始的。大概加了3000多个数据的时候（1个小时左右吧），app会停止运行。没有任何的错误日志，自定义了一个UncaughtExceptionHandler类也没有捕获到任何异常。

**Expected Behavior**

**Possible Solution**

**Device (please complete the following information):**
 - Device:  ??
 - Android Version   4.4.4
 - Library Version  3.0.3

**Additional Context**

**Comment by almic** [comment]
sorry but this issue tracker is not the place to ask for programming help. Questions like this belong on stackoverflow.
