### ISSUE TITLE
Space between bar and xAxis labels.

### ISSUE THREAD

**Issue by pankaj210891** [PhilJay/MPAndroidChart#4070]
Please help me xAxis labels and bar gap is increased if any of the bar value is 0.

Please look the below images.

**When any bar value is 0;**

![device-2018-05-30-124154](https://user-images.githubusercontent.com/22121472/40704725-966efbbe-6406-11e8-95d0-98928193c028.png)

**When all bar value is more than 0;**

![device-2018-05-30-124318](https://user-images.githubusercontent.com/22121472/40704747-a9492a8e-6406-11e8-8f88-3871b5c7b107.png)

I am sure you can notice the space in both situation, I want all labels to be assigned like in the second image irrespective of value.

**Comment by pankaj210891** [comment]
Hi There,

I am still waiting for the response, 6 days are already gone.
Please reply back need to resolve this issue ASAP.

**Comment by RobertZagorski** [comment]
If you could verify, whether newest master version fixes the problem that would be great.
Your problem was probably fixed in PR https://github.com/PhilJay/MPAndroidChart/pull/4013

**Comment by pankaj210891** [comment]
@RobertZagorski I am using the latest version of your library. The fix PR #4013 you shared is for label rotation, whereas I want to reduce the gap between the labels and the X-axis when any of the bar value is 0.

**Comment by RobertZagorski** [comment]
You are checking newest git master ref or newest version published to bintray repository?
Those are the different ones.

**Comment by pankaj210891** [comment]
Hi,

Can u please share the link for the latest master library.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by RobertZagorski** [comment]
You need to download the library from github, make it as a module in your project (remove gradle dependency to MPAndroidChart), compile, open and try to reproduce the crash.

**Comment by pankaj210891** [comment]
Hi There,

I am already using the library as a module.

I noticed that when any bar value is 0 then there is a space between the labels and X-axis.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by RobertZagorski** [comment]
So indeed this is a bug in the library.
Thanks for cooperating :)

**Comment by pankaj210891** [comment]
So what's now?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pankaj210891** [comment]
Any solution? or any suggestion.

**Comment by pankaj210891** [comment]
@RobertZagorski Any solution? or any suggestion.

**Comment by pankaj210891** [comment]
@RobertZagorski Finally I resolved the issue using xAxis.setYOffset. Thanks for the help, I am closing this issue.

**Comment by AndroidGecko** [comment]
had a similar issue, was able to resolve with 
```
chart.axisLeft.axisMinimum = 0f
chart.axisRight.axisMinimum = 0f
```

**Comment by faizanhaidarkhan** [comment]
@AndroidGecko Thanks, but its a little bit changed like
```
 chart.getAxisLeft().setAxisMinimum(0);
 chart.getAxisRight().setAxisMinimum(0);
```

**Comment by KhadijaHameed** [comment]
> had a similar issue, was able to resolve with
> 
> ```
> chart.axisLeft.axisMinimum = 0f
> chart.axisRight.axisMinimum = 0f
> ```

(Y)
