### ISSUE TITLE
why the getFormattedValue's value  is -1?

### ISSUE THREAD

**Issue by zhangshuliang** [PhilJay/MPAndroidChart#4075]
IAxisValueFormatter formatter = new IAxisValueFormatter() {

                            @Override
                            public String getFormattedValue(float value, AxisBase axis) {
                                String time = xValues.get((int) value);
                                String realTime = getTime(Long.parseLong(time));
                                return realTime;
                            }
                        };
I debug find the value is -1, why?

**Comment by MakawaMT** [comment]
Did u solve this issue? I have similar issues where value is always zero

**Comment by almic** [comment]
@zhangshuliang sorry but this issue tracker is not the place to ask for programming help. Questions like this belong on stackoverflow.

**Comment by josephcorbin91** [comment]
I am also seeing this issue it could be a potential bug.
