### ISSUE TITLE
How to show barChart even if data is = 0 ??

### ISSUE THREAD

**Issue by thomaslc66** [PhilJay/MPAndroidChart#409]
Hi, 
Since i update from version 1.7 to 2.1 i've to review things.

Before even if my data were equal to 0.0 the bar was there. Now i've only an empty chart. 
Now... when i add a number in the data bigger than 0 every bar of the Barchart are visible even if only one is set to (for exemple) 10 and the other are still to 0.0. Do you know why? Why can i have all my bar displayed even if all data are equals to 0?

And an other small question. If i don't want the right Axis the only solution is to set this as a new axis an setEnabled to false? or is there an other way?

Thanks

**Comment by thomaslc66** [comment]
For exemple here: https://github.com/PhilJay/MPAndroidChart/issues/354#issuecomment-75205716
you can find an exemple of my past graph view.

Now with update (no changes in my code) i have this:
![nodata](https://cloud.githubusercontent.com/assets/9827392/6508528/9fe44cea-c359-11e4-870d-138c413a5c49.PNG)

first graph i set one data to 20 and other bar are showed.
Second graph nothing upper than 0 and nothing is showed.

**Comment by PhilJay** [comment]
I dont understand.

Show me the code for your Niveau 1.0 and Niveau 1.2

**Comment by shahzebkhowaja** [comment]
I guess he is trying to say that, when we have only one entry on x-axis bar graph doesn't display all x-axis values in new updates, but in previous version we have x-axis display all over if we don't have entries.

I am also facing same issue on bar chart, and this seems working fine with line chart

**Comment by shahzebkhowaja** [comment]
My bad it's working now, in my case It's all related to setAxisMinValue setAxisMaxValue. I hope it's also same for him too

**Comment by thomaslc66** [comment]
I m not home now sorry. But shahzebkhowaja said it. Before when data entries were equals to zero all columns were visible. Now axisX only display 1... And none of my columns are visible. so i would like to know how Can i manage to display them all again??

**Comment by PhilJay** [comment]
Are your values smaller than 0?
If yes, set `startAtZero(...)` for your y-axis to false.

**Comment by thomaslc66** [comment]
No... all my columns values are equals to 0 at the begining. And I set my xAxis value to 1,2,3,4,5,6 
And only 1 appears like in the picture

**Comment by thomaslc66** [comment]
....

**Comment by thomaslc66** [comment]
Hi...

You didn't answer my question so i was quite disapointed. But i figured out some things.

My leftAxis is filled automaticaly i just say i want 7 Labal with the method setLabelCount(7)

if i let the leftAxis be filled out automaticaly i get empty barChart like this:
![capture](https://cloud.githubusercontent.com/assets/9827392/6847769/3204bfa4-d3c9-11e4-9b07-9ac60d8a94c0.PNG)

But if i use leftAxis.setAxisMaxValue(150f) (for exemple)

I get what i want:
![capture2](https://cloud.githubusercontent.com/assets/9827392/6847820/944135b2-d3c9-11e4-89e5-8a5e0f2837c1.PNG)

I hope you will understand now what i was asking. And maybe know you can help to do this, but without setting manualy a MaxValue for the leftAxis.

On your 1.7.4 Version it was doing it.

Thanks

**Comment by Snehankur** [comment]
Hi Phil,
I am facing the same issue. Could you please let me know what i need to do to fix the same. I using the version 2.0.8. Is there a newer version I need to use for my build. Please advise.

**Comment by PhilJay** [comment]
Yes, there is a newer version 2.0.9, but I recommend you wait until I release 2.1.0 next week.
