### ISSUE TITLE
当我给x设置一个较大的值的时候，x轴显示错误

### ISSUE THREAD

**Issue by wangxuchao** [PhilJay/MPAndroidChart#4092]
当我打算将时间戳转成时间显示在x轴上的时候，例如**1528250160**（06-06 09:56），**1528250220**（06-06 09:57）......会出现两个点同时显示在一个x轴上的情况

**Comment by wangxuchao** [comment]
最后发现并不是插件的问题，`public String getFormattedValue(float value, AxisBase axis)` 中的value为float类型，我进行计算 `(long) (value*1000l);`的时候最后3位数出现了其他的数据，临时处理方法`(long) ((int)value*1000l);`

**Comment by baiyh** [comment]
我也遇到这个问题，是long转float的时候精度，出现问题，导致x轴点出现问题，请问，你这个最后是怎么解决的

**Comment by wangxuchao** [comment]
以第一个点的时间为初始时间，其他的都是减去初始时间得到一个较小的int值，把这个值当作x轴坐标
0，1，2，3，4，5，6，7...
当格式化时间的时候再加上初始值应该就可以了
