### ISSUE TITLE
Failed to resolve:common

### ISSUE THREAD

**Issue by Nccssa** [PhilJay/MPAndroidChart#4094]
![11](https://user-images.githubusercontent.com/39074629/41146407-cb51fb20-6b35-11e8-8fc5-06760e6f4412.png)

try:
 maven { url "https://jitpack.io" }

pom.xml

Always such a mistake

**Comment by qinhaonan** [comment]
I had the same problem,

**Comment by MGaetan89** [comment]
Can you share your `build.gradle` file?

**Comment by RobertZagorski** [comment]
There's another site to programmers, where answers to such problems can be found. Here's sample link:
https://stackoverflow.com/questions/50565776/build-gradle-error-failed-to-resolve-common?noredirect=1&lq=1
or this one:
https://stackoverflow.com/questions/50760911/errorfailed-to-resolve-common-in-android-studio

This question is completely unrelated to the MPAndroidChart library

**Comment by Nccssa** [comment]
Works,

**Comment by Nccssa** [comment]
Works,  Change of position
this--->
build.gradle(Project Level)

allprojects {
    repositories {
        google()
        jcenter()
    }
}
