### ISSUE TITLE
Howto disable horizontal grid in barchart

### ISSUE THREAD

**Issue by ste71m** [PhilJay/MPAndroidChart#410]
How to disable grid or horizontal grid in barchart in version 2?

**Comment by PhilJay** [comment]
Check out the documentation concerning x-axis and y-axis: [Documentation-Wiki](https://github.com/PhilJay/MPAndroidChart/wiki)

Each axis is responsible for the grid lines in it's direction and allows to disable them separately.

**Comment by hishamcg** [comment]
YAxis yAxis = mChart.getAxisLeft(); 
yAxis.setDrawGridLines(false);

yAxis = mChart.getAxisRight();
yAxis.setDrawGridLines(false);

that should do it
