### ISSUE TITLE
setHoleColor在fragment 使用没有效果  一直是蓝色的 

### ISSUE THREAD

**Issue by zhangjilei106787** [PhilJay/MPAndroidChart#4104]
**Summary**

**Expected Behavior**

**Possible Solution**

**Device (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - Android Version [e.g. 7.0]
 - Library Version (e.g. 3.0.3)

**Additional Context**

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.
