### ISSUE TITLE
自定义的x轴，无法根据value获取到对应的内容，value是上次显示的文本值，并非是索引

### ISSUE THREAD

**Issue by faith-hb** [PhilJay/MPAndroidChart#4105]
自定义的x轴，无法根据value获取到对应的内容，value是上次显示的文本值，并非是索引

**Comment by zhanghuaAndroid** [comment]
您好，这个问题解决了吗？我也遇到了同样的问题，不知道怎么解决，期待您的回复...
Hello, has this problem been solved?I have encountered the same problem. I don't know how to solve it. I am looking forward to your reply.

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.
