### ISSUE TITLE
饼状图表显示的颜色和点击的颜色不一样 怎么回事,点击后会变色

### ISSUE THREAD

**Issue by zhangjilei106787** [PhilJay/MPAndroidChart#4107]
**Summary**

**Expected Behavior**

**Possible Solution**

**Device (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - Android Version [e.g. 7.0]
 - Library Version (e.g. 3.0.3)

**Additional Context**

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.
