### ISSUE TITLE
yAxis not visible properly, if chart set to ShowOnlyMinMax

### ISSUE THREAD

**Issue by shahzebkhowaja** [PhilJay/MPAndroidChart#411]
Hi Phil,
if I set ShowOnlyMinMax and setStartAtZero(false), the line graph's 3 point is not visible.
how can I fix this ?
![screenshot_2015-03-05-16-01-03](https://cloud.githubusercontent.com/assets/2663048/6514636/eee164fc-c351-11e4-9d03-f11987194efa.png)

**Comment by PhilJay** [comment]
Please show me your setup.

**Comment by shahzebkhowaja** [comment]
mv = new ChartMarkerView(mContext, R.layout.charts_marker_view);
        // Set MarkerView
        mLineChart.setMarkerView(mv);

        // disable the indicator from bar
        mLineChart.setHighlightIndicatorEnabled(false);

        // enable value highlighting
        mLineChart.setHighlightEnabled(true);

        // enable touch gestures
        mLineChart.setTouchEnabled(true);

        // enable scaling and dragging
        mLineChart.setDragEnabled(true);
        mLineChart.setScaleEnabled(true);
        mLineChart.setDrawGridBackground(false);

        // if disabled, scaling can be done on x- and y-axis separately
        mLineChart.setPinchZoom(true);

        // if more than 60 entries are displayed in the chart, no values will be drawn
        mLineChart.setMaxVisibleValueCount(15);

        // To set xAxis of Line Chart
        XAxis xAxis = mLineChart.getXAxis();
        xAxis.setTypeface(openSansRegular);
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setTextSize(12f);
        xAxis.setTextColor(mContext.getResources().getColor(R.color.dark_grey));
        xAxis.setDrawGridLines(false);
        xAxis.setDrawAxisLine(true);
        xAxis.setAxisLineColor(mContext.getResources().getColor(R.color.dark_grey));

        // To set Left yAxis of Line Chart
        YAxis leftAxis = mLineChart.getAxisLeft();
        leftAxis.setTypeface(openSansRegular);
        leftAxis.setTextColor(mContext.getResources().getColor(R.color.dark_grey));
        leftAxis.setTextSize(12f);
        leftAxis.setDrawGridLines(false);
        leftAxis.setDrawAxisLine(true);
        leftAxis.setAxisLineColor(mContext.getResources().getColor(R.color.dark_grey));
        leftAxis.setStartAtZero(false);
        leftAxis.setShowOnlyMinMax(true);

        // To set Right yAxis of Line Chart
        YAxis rightAxis = mLineChart.getAxisRight();
        rightAxis.setEnabled(false);

        mLineChart.animateX(ANIMATION_TIME);

        // to disable/enable double tap zoom
        mLineChart.setDoubleTapToZoomEnabled(false);





       // create a data set and give it a type
        LineDataSet set1 = new LineDataSet(yVals, "DataSet");

        set1.setColor(getResources().getColor(R.color.red));
        set1.setCircleColor(getResources().getColor(R.color.red));
        set1.setLineWidth(1f);
        set1.setCircleSize(4f);
        set1.setFillAlpha(65);
        set1.setFillColor(getResources().getColor(R.color.red));
        set1.setDrawValues(false);


        YAxis leftAxis = lineChart.getAxisLeft();
        leftAxis.setValueFormatter(new ValueFormatter());

        float mMaxVal = 0f;
        float mMinVal = 0f;
        if(yVals.size() > 1) {
            // set range of y values
            mMaxVal = Collections.max(yVals);
            mMinVal = Collections.min(yVals);
            leftAxis.setAxisMaxValue(mMaxVal);
            leftAxis.setAxisMinValue(mMinVal);
        }
        else {
            mMaxVal = Collections.max(yVals);
            leftAxis.setAxisMaxValue(mMaxVal);
            leftAxis.setAxisMinValue(mMinVal);
        }

        // set data
        lineChart.setData(data);
        // to enable/disable legend
        lineChart.getLegend().setEnabled(false);

**Comment by PhilJay** [comment]
Dont do that thing with Collections and calculating the values yourself. Let the chart do that by simply setting the top and bottom space for the axis to 0%:

```java
chart.getAxisLeft().setSpaceTop(0f);
chart.getAxisLeft().setSpaceBottom(0f);
```

This will cause the axis to be calculated without offset.
