### ISSUE TITLE
hello, i used PieChart has a problem

### ISSUE THREAD

**Issue by ChinaRedKing** [PhilJay/MPAndroidChart#4118]
i set this:
mPieChart.setUsePercentValues(true);

**Comment by yudapiandroid** [comment]
it is work? i used same setting~~ but it is not work~ 

![d891de95aeb59d90d3c820c82488d050](https://user-images.githubusercontent.com/21767081/41950066-f57e854c-79f6-11e8-9517-d3c1f712bff2.png)
