### ISSUE TITLE
is there any way to start drawing x-axis values with some padding

### ISSUE THREAD

**Issue by shahzebkhowaja** [PhilJay/MPAndroidChart#412]
Hi,
Is there any way to start drawing x-axis value little space from bottom(x-axis line) and left(y-axis line) for Line and BarChart ??

As red marks in screenshots to display space.
![screenshot_2015 03 05 16 01 03 - 2](https://cloud.githubusercontent.com/assets/2663048/6514993/ab1068d8-c354-11e4-9473-4130839969d5.png)

**Comment by PhilJay** [comment]
Well, simply add 1 more x-value on both sides than you need:

xvals.add("");

// loop and add the "real" values

xvals.add("");

**Comment by fantasymaker-cn** [comment]
@PhilJay Adding fake value will affect the labels on X-Axis. Is there any better work around? 
And how to treat with Y-axis spacing? This cannot simply be resolved by adding a value.
Is there any property like "set...Offset/Spacing"?

**Comment by 02gaurav** [comment]
@lixplor Let me know how you added space between bar chart and values on Y Axis?
