### ISSUE TITLE
Impossible to make a time series graph

### ISSUE THREAD

**Issue by mynavy** [PhilJay/MPAndroidChart#414]
Hello , 

First of all ==> This lib is absolutely perfect.

The problem:
I have some data that is based upon time, for example : 

For Y values : 3,5 
And X values : 12:30 - 12:45 
plot a line.

Is there any way I can plot this with a built in function, so for example:

TimeFunction ( 3 , 12:30 ( in milliseconds));
TimeFunction(5,12:45 ( in milliseconds));
TimeFunctionPlot; 

Thanks.

**Comment by PhilJay** [comment]
Currently, time-series are not supported.

Best regards,
Phil

**Comment by MikeFr** [comment]
Hi Phil,

Is it planned to be supported soon ?

Regards,
Mike
