### ISSUE TITLE
大神,请教一下，BarChart如何添加十字线呢

### ISSUE THREAD

**Issue by Zpsgithub** [PhilJay/MPAndroidChart#4148]
**Summary**

**Expected Behavior**

**Possible Solution**

**Device (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - Android Version [e.g. 7.0]
 - Library Version (e.g. 3.0.3)

**Additional Context**

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.
