### ISSUE TITLE
first and last xIndex on visible chart data

### ISSUE THREAD

**Issue by svasic** [PhilJay/MPAndroidChart#415]
Hi Phil!
Im trying to get the first and the last xIndex of the visible chart data. 
scenario: i zoom the chart to some point and want to to get the first and the last visible xIndex (or entry) of the data that is currently in visible rectangle. I can't find an elegant way to do that ... currently I am trying to achieve that with getEntryByTouchPoint(0,0) for first visible entry but it's not working as I would expect. What would be the best aproach to this issue?

Thanks for all the work and help!

**Comment by svasic** [comment]
If anyone else try to implement this ...
I implemented it in my extended LineChart class similar like Phil did it in 'drawValues' method in LineChart class, using positions from 'generateTransformedValuesLineScatter' method and checking them with isOffContentRight and isOffContentLeft methods. For finding starting point I am iterating the loop from the start and backwards for the end value.

Would be really nice if this would be implemented in next versions of the library. It isn't hard to implement and it's very useful for many use cases.

**Comment by ckoessler** [comment]
I am looking for that feature as well. @svasic , can you share your code?

Thank you!

**Comment by svasic** [comment]
Here is the code i used for getting the start value ... in my case xValues holds integers which represents time values
public int getVisibleStart() {
		RectF visibleRect = getContentRect();
		List<Entry> entries = getData().getDataSetByIndex(0).getYVals();
		float[] positions = getTransformer().generateTransformedValuesLineScatter((ArrayList<? extends Entry>) entries, getPhaseY());
		
		int start = -1;
		for (int j = 0; j < positions.length * getPhaseX(); j += 2) {
			if (isOffContentRight(positions[j])) break;
			if (isOffContentLeft(positions[j])) continue;
			
            Entry entry = entries.get(j/2);
            String xValue = getXValue(entry.getXIndex());
            try {
				start = Double.valueOf(xValue.trim()).intValue();
			} catch (NumberFormatException e) {
				Log.e(getTag(), "Could not parse int from xValue" + xValue);
			}
            return start;
        }
		return start;
	}

**Comment by ckoessler** [comment]
Thank you!

**Comment by svasic** [comment]
Don't know in which version you added it, but in last v2.0.8. this feature is supported by 'getLowestVisibleXIndex()' and 'getHighestVisibleXIndex()' methods.
Thank you!

**Comment by NexusHero** [comment]
Hi Folks,

the functions "getLowestVisibleXIndex()" and "getHighestVisibleIndex()" are not available in version 3.0.3?
Any Workarround here?

Thanks in advance

**Comment by fullmoon6661** [comment]
`chart.getLowestVisibleX()` and `chart.getHighestVisibleX()` should do it
