### ISSUE TITLE
更换数据maker怎么隐藏比较好

### ISSUE THREAD

**Issue by nanhou** [PhilJay/MPAndroidChart#4150]
更换数据maker怎么隐藏比较好

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.

**Comment by ohooblueblue** [comment]
LineChart.highlightValue(null);

**Comment by ohooblueblue** [comment]
> 更换数据maker怎么隐藏比较好

LineChart.highlightValue(null);
