### ISSUE TITLE
disable scaling on the Y axis?

### ISSUE THREAD

**Issue by svasic** [PhilJay/MPAndroidChart#416]
Is there any simple (implemented in library) solution to disable scaling (zooming) on the Y axis only, so that user can zoom only on the X axis? It seems like common requirement, but I can't find it in the documentation.

thanks

**Comment by PhilJay** [comment]
You are right, that is not yet possible. I will include such a feature in the next release, should be pretty easy to do :-)

**Comment by svasic** [comment]
That would be great! Thank you!

**Comment by shadowalker77** [comment]
Did you add this feature?

**Comment by ezamelczyk** [comment]
I don't think so.

**Comment by hak33m16** [comment]
Still not here yet? Would love to see this.

**Comment by CME64** [comment]
ugh I was looking for this feature, gotta find another plugin now or else I may have to implement it.

**Comment by sosite** [comment]
Here you go: `setScaleYEnabled(false)`

**Comment by PriyankaKikkuru5** [comment]
How to stop auto formatting y axis in barchart
