### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by eakteam** [PhilJay/MPAndroidChart#4167]
Will be any update with many bug fixes to this awesome library ? It is not updated since Nov 29, 2017. 
We are waiting for great improvements

**Comment by almic** [comment]
I'm working on version 3.1.0 right now, but I have no dates on when this will be released. For now, you can use the `-SNAPSHOT` version like this

```gradle
dependencies {
    implementation 'com.github.philjay:mpandroidchart:-SNAPSHOT'
}
```
