### ISSUE TITLE
Can I invert X Axis?

### ISSUE THREAD

**Issue by jack2684** [PhilJay/MPAndroidChart#418]
Hi,

I am trying to draw a history plot. It would be nicer if the data is plotted along with the timeline. (Data on the left represent those happens earlier, right means closer to present).

I notice there is a setinvert() function in yAsix. Is there a way to do it in xAsix? Thanks!

**Comment by jack2684** [comment]
Never mind. I figure out it is strongly related to the order you add X-axis points.

**Comment by NainalChauhan** [comment]
Hi,
I am adding entries in descending order for x axis but the map is not showing any points. It works fine when ascending values are given to x axis. Is there any thing else need to be done so that the x axis shows reverse order?

**Comment by abbasalill** [comment]
@NainalChauhan Hi if you got answer to start x axis from right end let me know what i did was change layout direction

**Comment by jcardama** [comment]
> 
> 
> @NainalChauhan Hi if you got answer to start x axis from right end let me know what i did was change layout direction

Could you let me know how?
