### ISSUE TITLE
How to use centerViewPort in the v2.0.7?

### ISSUE THREAD

**Issue by jack2684** [PhilJay/MPAndroidChart#419]
Hi,

I notice in the latest version, you can no longer use LineChart.centerViewPort (int, int). Instead it is in the ViewPortHandler. However in the demo code there is no example of how to use it.

Would you kindly give me some tips? Thanks!

**Comment by jack2684** [comment]
I try use it in this way：
vpHandler.centerViewPort(new float[]{2.5f, 0f}, mChart);
Since not working though

**Comment by PhilJay** [comment]
The new method is called `moveViewTo(...)`
