### ISSUE TITLE
If I click on the bar chart, how do I know which bar to click on?

### ISSUE THREAD

**Issue by wdmxzfG** [PhilJay/MPAndroidChart#4191]
Chinese
点击柱状图，怎么知道点击的是第几个？
在`public void onValueSelected(Entry e, Highlight h) {}`这个回调方法里，哪个参数能知道点击的是第一个还是几个？

English
If I click on the bar chart, how do I know which bar to click on?
which param is the position  when  I click the Bar in the method that `public void onValueSelected(Entry e, Highlight h) {}` ?

**Comment by ahmadalibaloch** [comment]
```
override fun onValueSelected(e: Entry?, h: Highlight?) {
                val entry = e as BarEntry
                val label = barLabels[entry.x.toInt()] // your bar labels array
                val barType = h?.stackIndex // if you are using stacked chart you can get which bar type was selected of the given stacked options
            }
```

**Comment by almic** [comment]
Use the `Entry e` object to check the x and y positions selected.
