### ISSUE TITLE
贝塞尔曲线格式的曲线，怎么实现曲线渐变呢？

### ISSUE THREAD

**Issue by izheer** [PhilJay/MPAndroidChart#4195]
**Summary**

**Expected Behavior**

**Possible Solution**

**Device (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - Android Version [e.g. 7.0]
 - Library Version (e.g. 3.0.3)

**Additional Context**

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.
