### ISSUE TITLE
Multiple bar chart datasets x axis

### ISSUE THREAD

**Issue by Mrkhagol** [PhilJay/MPAndroidChart#42]
Can you have two sets of values for x axis..where one is date..which I can represent just fine but other is like names associated with the dataset..is there a way to show that?

thanks

**Comment by ngarelimdex** [comment]
When do you think you will be supporting dual X axis ? is there an issue for this already?

**Comment by neaGaze** [comment]
@ngarelimdex there is an option of setting 
            xAxis.setPosition(XAxis.XAxisPosition.BOTH_SIDED);
which will add dual X axis in the graph

**Comment by ngarelimdex** [comment]
Thank you I ended up swapping my axis and rotating the chart. I'll see if I can use this option.

**Comment by grout-r** [comment]
Is there any changes regarding to this specific issue ? I'm stuck with the 2 differents X axis problem.

Here is what i try to achieve : 
![screen bar char v2](https://user-images.githubusercontent.com/10474368/33548801-bdacda10-d8e8-11e7-8b34-2bb25d066ea8.png)
