### ISSUE TITLE
It's possible to add labels to Bar values in Vertical just inside the bars ?

### ISSUE THREAD

**Issue by superay90** [PhilJay/MPAndroidChart#420]
I'm looking for do something like that ->
![example](https://cloud.githubusercontent.com/assets/9993149/6538034/ff193bfe-c45c-11e4-825a-237ad93d4f93.png)

It's possible ??

**Comment by PhilJay** [comment]
Unfortunately that is not possible by default. You will  have to implement that feature yourself. It should not be too hard tough.
