### ISSUE TITLE
setDrawSliceText(false) is not working

### ISSUE THREAD

**Issue by ashraf-patel** [PhilJay/MPAndroidChart#4201]
Hello, 
I am in love with the library. 
I am facing a minor issue.
`pieChart.setDrawSliceText(false);` is not working for me.

**Comment by almic** [comment]
Can you explain this more? Please open a new issue and use the [bug report](https://github.com/PhilJay/MPAndroidChart/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) template and describe what is happening.
