### ISSUE TITLE
请问当有多条曲线的时候且每条都有设置渐变背景色的时候，如何改变透明度使它们不会相互遮挡啊？

### ISSUE THREAD

**Issue by LiaoYuqiangzz** [PhilJay/MPAndroidChart#4202]
//设置渐变背景色
        dataSet1.setDrawFilled(true);
        dataSet2.setFillDrawable(getResources().getDrawable(R.drawable.chart_graint_blue));
        dataSet1.setDrawCircles(false);
        dataSet1.setHighlightLineWidth(1f);
        dataSet1.setHighlightEnabled(true);
        dataSet1.setHighLightColor(Color.parseColor("#aaaaaa"));
        dataSet1.enableDashedHighlightLine(10f,5f,0f);
        dataSet1.setFillAlpha(25);
        dataSet1.setMode(LineDataSet.Mode.HORIZONTAL_BEZIER);

        dataSet2.setDrawCircleHole(false);
        dataSet2.setDrawValues(false);
        dataSet2.setDrawCircles(false);
        dataSet2.setDrawFilled(true);
        dataSet2.setHighLightColor(Color.parseColor("#aaaaaa"));
        dataSet2.setFillAlpha(10);
        dataSet2.setHighlightLineWidth(1f);
        dataSet2.setHighlightEnabled(true);
        dataSet2.enableDashedHighlightLine(5f,5f,5f);
        dataSet2.setFillDrawable(getResources().getDrawable(R.drawable.chart_graint_gray));
        dataSet2.setMode(LineDataSet.Mode.HORIZONTAL_BEZIER);
        LineData lineData = new LineData(dataSet1,dataSet2);

两条曲线我都设置了setFillAlpha，但是实际运行效果，两条曲线还是会相互遮挡住彼此。。请问要如何做才能让它们重叠的部分也能展示出来啊？

**Comment by almic** [comment]
sorry but this issue tracker is strictly english only. We cannot help you with this.

**Comment by luyuan11233** [comment]
Baidu translation can help you...
