### ISSUE TITLE
minumum value barchart "bar not displayed";

### ISSUE THREAD

**Issue by Priya0325** [PhilJay/MPAndroidChart#4203]
**Summary**

**Expected Behavior**

**Possible Solution**

**Device (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - Android Version [e.g. 7.0]
 - Library Version (e.g. 3.0.3)

**Additional Context**

![mpchart](https://user-images.githubusercontent.com/40349500/44403377-ec59dd80-a571-11e8-9992-0bf1887fffd2.png)

- minumum value barchart "bar not displayed"
-Zero bar drawn on bar in line.

**Comment by almic** [comment]
I cannot tell what you are describing, the picture is not helping. Please follow the issue template and try again.
