### ISSUE TITLE
设置了纵坐标的原点0，但是原点位置不是左下角的角落，不是和横坐标0重合。

### ISSUE THREAD

**Issue by husuxing** [PhilJay/MPAndroidChart#4208]
**Summary**

**Expected Behavior**

**Possible Solution**

**Device (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - Android Version [e.g. 7.0]
 - Library Version (e.g. 3.0.3)

**Additional Context**

**Comment by afunnyrainman** [comment]
知道是为什么了吗？兄弟。

**Comment by almic** [comment]
@husuxing sorry but this issue tracker is strictly english only. We cannot help you with this.
