### ISSUE TITLE
Stacked bar chart

### ISSUE THREAD

**Issue by kanthi246** [PhilJay/MPAndroidChart#4210]
i don't know weather it's an issue or not....i'm just notifying this
I've created a stacked bar chart with multiple data sets and also i'm applying the colors for every data set...when i run the application it's showing "Stack" for each and every data value in the chart along with colors under the chart...

if its not an issue please notify me how to remove the "stack" under the chart

**Comment by almic** [comment]
I think that's the legend being rendered. It's hard to tell without a screenshot, so please add one!

**Comment by kanthi246** [comment]
(https://user-images.githubusercontent.com/34573093/47703576-bce8e080-dc46-11e8-961f-49e2dfce6e60.jpeg)

check this link for image..under the chart u can see the values as stack along with colors..i'm doing this stacked bar chart in a static way..if i do this in a dynamic way i think it will work fine but i don't know how to do that in a dynamic way because we should give the values as a stacked list to the arraylist..can you give me any example for dynamic stacked bar chart

**Comment by almic** [comment]
Here's the latest example for a stacked bar chart: [StackedBarActivity.java](https://github.com/PhilJay/MPAndroidChart/blob/9148f37f9eca975335bf64a9096808e659343610/MPChartExample/src/main/java/com/xxmassdeveloper/mpchartexample/StackedBarActivity.java)

I suggest you look at the `onProgressChanged()` method, and specifically at line `131`. If you aren't updating your data that way then it could be causing this. Just for the future, would you share the code you are using to change the data, as I could use it to find a way to make this less likely to happen.

**Comment by almic** [comment]
As for dynamic vs. static data, the only difference is whether you decide to inflate a new chart each time you want to display data, or if you change the data itself being displayed. There should be no difference either way, but it may be easier to outright inflate a new chart if your data changes.
