### ISSUE TITLE
MPAndroidChart crash when read realtime data from firebase

### ISSUE THREAD

**Issue by Fahri1690** [PhilJay/MPAndroidChart#4213]
package com.my.app.package;

import android.content.Intent;
import android.graphics.Color;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.v7.app.AlertDialog;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.TextView;

import com.my.app.package.R;
import com.github.mikephil.charting.charts.PieChart;
import com.github.mikephil.charting.data.PieData;
import com.github.mikephil.charting.data.PieDataSet;
import com.github.mikephil.charting.data.PieEntry;
import com.github.mikephil.charting.utils.ColorTemplate;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

import java.util.ArrayList;

public class MyClass extends AppCompatActivity {

    FirebaseDatabase database;
    DatabaseReference dbRef;

    FirebaseAuth mAuth;

    PieChart pieChart;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_pres_vote_email);

        database = FirebaseDatabase.getInstance();
        dbRef  = database.getReference("Ref");

        mAuth   = FirebaseAuth.getInstance();

        pieChart = (PieChart) findViewById(R.id.pieChart);

        pieChart.setUsePercentValues(true);
        pieChart.getDescription().setEnabled(false);
        pieChart.setExtraOffsets(10, 15, 10, 10);
        pieChart.setDrawHoleEnabled(false);

        final ArrayList<PieEntry> yValues = new ArrayList<>();

        dbRef.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                String myValueData = dataSnapshot.child("firebaseChild1").child("firebaseChild2").getValue().toString();
                //((TextView) findViewById(R.id.tvId1)).setText(myValueData);
                String myValueData2 = dataSnapshot.child("firebaseChild3").child("firebaseChild4").getValue().toString();
                //((TextView) findViewById(R.id.tvId2)).setText(myValueData2);

                yValues.add(new PieEntry(Float.parseFloat(myValueData), "LabelData"));
                yValues.add(new PieEntry(Float.parseFloat(myValueData2), "LabelData"));
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        });

        PieDataSet dataSet = new PieDataSet(yValues, " ");
        dataSet.setSliceSpace(3f);
        dataSet.setSelectionShift(5f);
        dataSet.setColors(ColorTemplate.JOYFUL_COLORS);

        PieData data = new PieData((dataSet));
        data.setValueTextSize(12f);
        data.setValueTextColor(Color.YELLOW);

        pieChart.setData(data);
    }

    public void LogOut(View view) {
        mAuth.signOut();
        startActivity(new Intent(getApplicationContext(), Login.class));
        finish();
    }

    @Override
    public void onBackPressed() {
        AlertDialog.Builder alertDialog = new AlertDialog.Builder(PresVoteEmail.this);
        alertDialog.setTitle("Alert Title");
        alertDialog.setMessage("Alert Message");
        alertDialog.show();
    }
}

-------------------------------------------------------------------------------------------------------------------
After i'm running, my app get crash with Log like at the screenshoot : 
can anybody help me? I really appreciate it. Thanks

Here's the crash : 

![4](https://user-images.githubusercontent.com/38343477/44913132-a4e40600-ad56-11e8-81df-c84c47bb09f9.jpg)

**Comment by jsmoctezuma** [comment]
te dejo mi ejemplo funciona pero no me coloca las etiquetas como debe de ser pero de algo te puede ayudar

import android.graphics.Color;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.github.mikephil.charting.charts.PieChart;
import com.github.mikephil.charting.components.Description;
import com.github.mikephil.charting.data.PieData;
import com.github.mikephil.charting.data.PieDataSet;
import com.github.mikephil.charting.data.PieEntry;
import com.github.mikephil.charting.formatter.PercentFormatter;
import com.github.mikephil.charting.utils.ColorTemplate;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

import java.util.ArrayList;

import static com.mikepenz.iconics.Iconics.TAG;

public class pmmec_frag extends Fragment {

    View VMMecView;
    PieChart pieChart;
    DatabaseReference vpDBReference;
    ArrayList<PieEntry> yvalues;
    int conta;
    String nomVoto;
    float numVoto;


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        VMMecView = inflater.inflate(R.layout.frag_pmmec, container, false);

        pieChart = VMMecView.findViewById(R.id.piechartpm);

        pieChart.setUsePercentValues(true);

        yvalues = new ArrayList<PieEntry>();

        //Instancia a la base de datos
        vpDBReference = FirebaseDatabase.getInstance().getReference().child("ModsMecanicos");
        vpDBReference.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                    yvalues.clear();
                    conta = 0;
                    for(DataSnapshot ds : dataSnapshot.getChildren()) {
                        nomVoto = String.valueOf(ds.child("titulo").getValue());
                        numVoto = Float.parseFloat(String.valueOf(ds.child("votos").getValue()));

                        yvalues.add(new PieEntry(0+numVoto, ""+nomVoto));

                        System.out.println("titulo = " + nomVoto);
                        System.out.println("votos = " + numVoto);
                        System.out.println("contador = " + conta);

                        conta += 1;
                    }
                PieDataSet dataSet = new PieDataSet(yvalues, " - Elementos Votados");
                PieData data = new PieData(dataSet);

                data.setValueFormatter(new PercentFormatter());
                pieChart.setData(data);
                dataSet.setColors(ColorTemplate.COLORFUL_COLORS);
                data.setValueTextSize(13f);
                data.setValueTextColor(Color.WHITE);
                Description description = new Description();
                description.setText("Resultados:");
                pieChart.setDescription(description);
                pieChart.animateX(3000);

                pieChart.setCenterText("MODs Mecanicos");
                pieChart.getCenterText();

                //pieChart.setDrawHoleEnabled(true);
                //pieChart.setTransparentCircleRadius(58f);
                //pieChart.setHoleRadius(58f);
            }

            @Override
            public void onCancelled(DatabaseError databaseError) {
                Log.d(TAG, "Error trying to get classified ad for update " +
                        ""+databaseError);
            }
        });
        return VMMecView;
    }
}
