### ISSUE TITLE
LineChart is not plotting correctly on some devices

### ISSUE THREAD

**Issue by pratikdozee** [PhilJay/MPAndroidChart#4215]
https://stackoverflow.com/questions/52033392/mpandroidchart-linechart-is-not-plotting-correctly

**Comment by pratikdozee** [comment]
I found that if I reduce the height of the graph, it is plotting with less noise.

**Comment by almic** [comment]
It really looks like the data being added is not right, some points are added many more times than they should be, causing the look of the same pattern being drawn many times and then sharply changing to another pattern.

I know you said your data is correct but could you please triple check that?

**Comment by barbeau** [comment]
Based on @pratikdozee answer on StackOverflow (https://stackoverflow.com/a/53430026/937715) it looks like the issue wasn't with MPAndoridChart, so this issue can be closed.
