### ISSUE TITLE
Set custom colors into Pie Chart

### ISSUE THREAD

**Issue by 1986stas** [PhilJay/MPAndroidChart#4218]
Hi Philipp! Thanks in advance for your library. Sorry to trouble you. I've got some difficulties. I cannot set my custom colors. Probably, I'm doing something wrong. Could you please help me? Below you can review my code:

        private List<ExpenseData> mExpenseData;
        private List<ExpenseItem> mExpenseColor;

        protected PieData generatePieData() {
        PieDataSet ds1; 
        mExpenseData = ExpenseLab.get(getActivity()).getExpenses(); //get all the expenses items from my db.I implemented without any impediments 
        mExpenseColor = ExpenseLab.get(getActivity()).getColor(); //get custom colors from my db

        ArrayList<PieEntry> entries = new ArrayList<>();

        for (int i = 0; i < mExpenseData.size(); i++){
            entries.add(new PieEntry(i));
        }
        List<Integer> color = new ArrayList<>();
        for(int j = 0; j < mExpenseColor.size(); j++){
            color.add(j);
        }
        ds1 = new PieDataSet(entries, "Some text");
        ds1.notifyDataSetChanged();
        ds1.setSliceSpace(2f);

        ds1.setColors(color); //here is I'm trying to set them, because all the items have their own colors
        ds1.setValueTextColor(Color.WHITE);
        ds1.setValueTextSize(12f);

        PieData d = new PieData(ds1);
        d.setValueTypeface(tf);
        return d;
}

Thanks,
Stas

**Comment by gnomeria** [comment]
Shouldn't this be put on the stackoverflow? 
Btw are you sure to put the color as an android color (packed ints) ? 
Try with something like : `Color.parseColor("#00ff00")` with hex string

**Comment by 1986stas** [comment]
Sure, I managed this issue. Really stupid question. This issue will be closed

**Comment by Kharlos** [comment]
i Have same issue but im working with kotlin


` val entries:ArrayList<PieEntry> = ArrayList()
        entries.add(PieEntry(2f, "Green"))
        entries.add(PieEntry(39f, "Yellow"))
        entries.add(PieEntry(59f, "Red"))

        val set:PieDataSet = PieDataSet(entries, "Election Results")
        var coloresmi: ArrayList<Int> = ArrayList();
        coloresmi.add(android.R.color.holo_green_dark)
        coloresmi.add(android.R.color.holo_blue_bright)
        coloresmi.add(android.R.color.holo_red_dark)

        //set.setColors(coloresmi)

        val data = PieData(set)
        chart.setDrawEntryLabels(false)
        chart.setData(data)
        chart.description.isEnabled = false
        chart.legend.orientation = Legend.LegendOrientation.VERTICAL
        chart.legend.horizontalAlignment = Legend.LegendHorizontalAlignment.RIGHT

        chart.invalidate() // refresh`
