### ISSUE TITLE
Is it possible to create grouped and stacked barchart together.

### ISSUE THREAD

**Issue by Nickx27** [PhilJay/MPAndroidChart#4220]
Hi @PhilJay , I just need a help to create a grouped chart for weekdays(Sunday, Monday,...). Each day contains 2 stacked entries Men, Women with multiple stack..Please find the attached image. @PhilJay 
![stack](https://user-images.githubusercontent.com/7982063/45072755-03fc9e80-b0fa-11e8-832c-22f6d3b6d678.jpg)

**Comment by almic** [comment]
This is possible, please see the example app and follow the documentation.
