### ISSUE TITLE
On touching or clicking the bar, its getting zoom

### ISSUE THREAD

**Issue by SanjeevaniRaje** [PhilJay/MPAndroidChart#4223]
**Summary**

**Expected Behavior**

**Possible Solution**

**Device (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - Android Version [e.g. 7.0]
 - Library Version (e.g. 3.0.3)

**Additional Context**

**Comment by almic** [comment]
Please follow the instructions in the templates. I cannot help you if you don't actually explain what is happening and what should happen.
