### ISSUE TITLE
Swap PieChart Value Label and Entry Label in places

### ISSUE THREAD

**Issue by danielmaman** [PhilJay/MPAndroidChart#4227]
Would be nice if there would be a possibility to swap Value Label and Entry Label in places
For example Value label in upper line and Entry Label in bottom line or vice versa

**Comment by almic** [comment]
Can you explain this more? Please open a new issue and use the [bug report](https://github.com/PhilJay/MPAndroidChart/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) or the [feature request](https://github.com/PhilJay/MPAndroidChart/blob/master/.github/ISSUE_TEMPLATE/Feature_request.md) templates depending on what you want.
