### ISSUE TITLE
setGradientColors this method can't find!!!

### ISSUE THREAD

**Issue by victorliuboom** [PhilJay/MPAndroidChart#4228]
![image](https://user-images.githubusercontent.com/13329831/45475568-5def0b00-b76f-11e8-9fe4-0a714ac9e8b5.png)
help me

**Comment by AlvinQiang** [comment]
You can try directly introducing the MPChartLib library. dont use gradle

**Comment by almic** [comment]
@victorliuboom sorry but this issue tracker is not the place to ask for programming help. Questions like this belong on stackoverflow.
