### ISSUE TITLE
resetAxisMaximum()  not work

### ISSUE THREAD

**Issue by taiwan1frog** [PhilJay/MPAndroidChart#4230]
**Summary**

**Expected Behavior**

**Possible Solution**

**Device (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - Android Version [e.g. 7.0]
 - Library Version (e.g. 3.0.3)

**Additional Context**

**Comment by almic** [comment]
Please follow the instructions in the templates. I cannot help if you don't give any information.
