### ISSUE TITLE
App not getting installed after gradle plugin update (3.1.4)

### ISSUE THREAD

**Issue by user0401** [PhilJay/MPAndroidChart#4231]
**Summary**

App containing MPAndroidChart:v3.0.3 dependency is not getting installed in Nvidia Sheild Android 5.1.1. 

The following dependency is added in the gradle.
implementation 'com.github.PhilJay:MPAndroidChart:v3.0.3'
When trying to install app, INSTALL_FAILED_DEXOPT error is displayed. App installs when the above dependency is removed. Also when D8 compiler is disabled the apk is getting installed.

The apk is getting installed in Android 6 and 7 devices.

**Device (please complete the following information):**
 - Device: Nvidia Shield Tablet K1
 - Android Version [5.1.1]
 - Library Version (3.0.3)

Attaching the logs for further reference.

--------- beginning of crash
09-13 10:23:20.200 5598-5600/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 5600 (Compiler driver)
09-13 10:23:20.289 629-1534/? W/ActivityManager: getRunningAppProcesses: caller 10088 does not hold REAL_GET_TASKS; limiting output
09-13 10:23:20.302 188-188/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'nvidia/sb_na_wf/shieldtablet:5.1.1/LMY48C/37154_590.0364:user/release-keys'
    Revision: '0'
    ABI: 'arm'
    pid: 5598, tid: 5600, name: Compiler driver  >>> /system/bin/dex2oat <<<
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
09-13 10:23:20.305 629-754/? W/NativeCrashListener: Couldn't find ProcessRecord for pid 5598
09-13 10:23:20.309 188-188/? I/DEBUG:     r0 b0e21f10  r1 b0e23eb8  r2 00000006  r3 00000000
09-13 10:23:20.309 188-188/? E/DEBUG: AM write failure (32 / Broken pipe)
09-13 10:23:20.309 188-188/? I/DEBUG:     r4 b0e24280  r5 b0e23098  r6 b0e23040  r7 00000000
        r8 b0e21ec8  r9 b0e21e18  sl b0e23220  fp b0e23e80
        ip b0e23098  sp b1135900  lr 00000015  pc b1d51b18  cpsr a0030030
    backtrace:
09-13 10:23:20.310 188-188/? I/DEBUG:     #00 pc 00008b18  /system/vendor/lib/libnvopt-artc.so (art::LoopEndCond::Start(art::PassDataHolder*) const+935)
        #01 pc 0012eb7b  /system/lib/libart-compiler.so (art::PassDriverMEOpts::ApplyPass(art::PassDataHolder*, art::Pass const*)+22)
        #02 pc 0012f061  /system/lib/libart-compiler.so
        #03 pc 0013087f  /system/lib/libart-compiler.so
        #04 pc 001311b5  /system/lib/libart-compiler.so (ArtQuickCompileMethod+48)
        #05 pc 00149b6d  /system/lib/libart-compiler.so (art::CompilerDriver::CompileMethod(art::DexFile::CodeItem const*, unsigned int, art::InvokeType, unsigned short, unsigned int, _jobject*, art::DexFile const&, art::DexToDexCompilationLevel, bool)+1044)
        #06 pc 0014a3a5  /system/lib/libart-compiler.so (art::CompilerDriver::CompileClass(art::ParallelCompilationManager const*, unsigned int)+1548)
        #07 pc 0013f6e5  /system/lib/libart-compiler.so
        #08 pc 002438f1  /system/lib/libart.so (art::ThreadPoolWorker::Run()+44)
        #09 pc 002441f1  /system/lib/libart.so (art::ThreadPoolWorker::Callback(void*)+60)
        #10 pc 000178df  /system/lib/libc.so (__pthread_start(void*)+30)
        #11 pc 00015823  /system/lib/libc.so (__start_thread+6)
09-13 10:23:20.393 188-188/? I/DEBUG: Tombstone written to: /data/tombstones/tombstone_07
09-13 10:23:20.393 629-650/? I/BootReceiver: Copying /data/tombstones/tombstone_07 to DropBox (SYSTEM_TOMBSTONE)
09-13 10:23:20.410 191-191/? E/installd: DexInv: --- END '/data/app/project-1/base.apk' --- status=0x000b, process failed
09-13 10:23:20.538 629-660/? W/PackageManager: Package couldn't be installed in /data/app/project-1
    com.android.server.pm.PackageManagerException: scanPackageLI
        at com.android.server.pm.PackageManagerService.scanPackageDirtyLI(PackageManagerService.java:5955)
        at com.android.server.pm.PackageManagerService.scanPackageLI(PackageManagerService.java:5267)
        at com.android.server.pm.PackageManagerService.installNewPackageLI(PackageManagerService.java:10519)
        at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:11049)
        at com.android.server.pm.PackageManagerService.access$2300(PackageManagerService.java:234)
        at com.android.server.pm.PackageManagerService$6.run(PackageManagerService.java:8649)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.android.server.ServiceThread.run(ServiceThread.java:46)

**Comment by almic** [comment]
make sure you are following the exact instructions for adding in the README for this project
