### ISSUE TITLE
MPandroid chart- Not able to select the pie of my piechat due to its very small value

### ISSUE THREAD

**Issue by HarshBinSem** [PhilJay/MPAndroidChart#4232]
Hey! Thanks for the wonderful library. 
I have a pie chart with 6 pies in it. values of one of the pie is really small like (1,50,0.67,2000,150). So for values like '1 and 0.67' i m not able to select the pie nor it is showing any color for small values.
and i want to use my piechart as a drilldown piechart but how should i select the pie with reall small values?
please help!

**Comment by almic** [comment]
thank you for pointing this out. A similar issue was reported and is currently being worked on.

some extra info: The solution will be to add a minimum slice angle option, which is currently not implemented but is being worked on!
