### ISSUE TITLE
Hiding particular drawentry labels in PiePolylineChart

### ISSUE THREAD

**Issue by son2017** [PhilJay/MPAndroidChart#4233]
hi @PhilJay ,
in PiePolyline chart i want hide all label, after spinning the chart in bottom side of chart the value should be display like below image it is i tried to search out all those thing and i find upto   mChart.setDrawEntryLabels(true); for hiding all label please but my requirment is something like that.
![demo](https://user-images.githubusercontent.com/25477633/45677553-17742480-bb52-11e8-81c7-d343b0696b0d.png)
kindly give me suggestion on that.

**Comment by fanggege** [comment]
hi Brother！
I also met the same question. Have you solved it?

**Comment by almic** [comment]
You should be able to use `getRotationAngle()` for this, and then use a TextView on top of the chart to show the values. I don't know how exactly you can do this, but that should be a good start.
