### ISSUE TITLE
Rounded corner bars

### ISSUE THREAD

**Issue by pawanpandey17** [PhilJay/MPAndroidChart#4234]
I have integrated bar chart sucessfully however the thing i required is the rounded corner bars instead of rectangles. Is there any way to do that.

**Comment by salauddinn** [comment]
I also required the rounded corner bar chart.

**Comment by almic** [comment]
thank you for pointing this out. A similar issue was reported and is currently being worked on.

**Comment by mathieudebrito** [comment]
@almic Could you add a link to the similar issue please ?
(+1, would also need this :))

**Comment by almic** [comment]
#4264

**Comment by mathieudebrito** [comment]
Thank  you :) I was not sure if you where talking about this one or this one : #803

**Comment by titiarimba** [comment]
i can't find this way on v3.0.3 :(
there's any way to get rounded bar chart?

**Comment by almic** [comment]
@titiarimba this is not added yet, please see the issue linked above
