### ISSUE TITLE
LineChart When there is only one piece of data, the x axis will display three lable

### ISSUE THREAD

**Issue by xsy2015** [PhilJay/MPAndroidChart#4238]
When there is only one piece of data, the x axis will display three label?
![screenshot_20180921-154348](https://user-images.githubusercontent.com/12710053/45867126-4b9b4f80-bdb5-11e8-9798-6e4743018c98.jpg)

**Comment by almic** [comment]
I'm not sure what you are asking about here. You can easily disable drawing values and disable highlight (selecting).
