### ISSUE TITLE
Why can't Override init() to set some attribute?

### ISSUE THREAD

**Issue by scsfwgy** [PhilJay/MPAndroidChart#4239]
* I have read all issues.

When I override init() to set some attribute like `setScaleYEnabled(false);`  `setDoubleTapToZoomEnabled(false);`
Its won't work!  I have debug this issues,`mScaleXEnabled=true` `mDoubleTapToZoomEnabled = true` after `setData(CombinedData data)`  .

ref:
#2733 
#2511
#2055

**Comment by almic** [comment]
This has to be done after the views are inflated. I've done exactly this in my own project and it is sort of finicky but that's just how Android works. For activities this is done inside `onCreate()`, for other things like fragments you do it inside `onViewCreated()`.
