### ISSUE TITLE
Class LineChart  method onDraw() invoke many time lead to method drawMarkers() is invoked to many time 

### ISSUE THREAD

**Issue by carl1990** [PhilJay/MPAndroidChart#424]
I am use LineChart,I want to know which markView is showing so I debug my program,and then I find this  issue.why?
another question : How Can I know which One index markView is showing and how  to control it is show?

**Comment by PhilJay** [comment]
What do you mean "is invoked too many times"?

You cannot get the currently highlighted values at this moment, there are only callbacks upon touching.

I will implement a method for that. In the future, you will be able to get the highlighted values by calling

`chart.getHighlighted()`

**Comment by carl1990** [comment]
I add a Log statement in the drawMarkers() method,when I touch the chart X axis the markView will show,and the log repeat print until the markView is dismiss.

`chart.getHighLighted()` is return Highligth? I also want to know this Highlight's index. thank you
