### ISSUE TITLE
Frequency plot

### ISSUE THREAD

**Issue by JeyanthInba** [PhilJay/MPAndroidChart#4242]
Hi,
I am trying to plot frequency spectrum,here my requirement is that,
X axis should be constant with given set of values
Y axis is varying one not constant.

I dont know how to add these values simultaeously.Please support m!
How to give X and Y values for plotting

**Comment by almic** [comment]
I wish I could help you out, as this is a pretty simple design question, but I really can't spend the time to help you. I'm working on updating the library to simplify it so it's easier to find what you need and customize charts. For now you just need to search through the [wiki](https://github.com/PhilJay/MPAndroidChart/wiki) and see if you can't find what you're looking for.

I can tell you this, however: `chart.invalidate()` will be your friend here.
