### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable com.github.mikephil.charting.data.Entry.getIcon()' on a null object reference

### ISSUE THREAD

**Issue by cybkw** [PhilJay/MPAndroidChart#4243]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable com.github.mikephil.charting.data.Entry.getIcon()' on a null object reference

**Comment by almic** [comment]
Should be fixed in the latest commit, until a new release is created you can just use the latest `-SNAPSHOT` version like this

```gradle
dependencies {
    implementation 'com.github.philjay:mpandroidchart:-SNAPSHOT'
}
```
