### ISSUE TITLE
How Can I Draw Cells Inside MPAndroidChart

### ISSUE THREAD

**Issue by Tufan21** [PhilJay/MPAndroidChart#4244]
How can I draw cells inside LineChart

I am able to display lines dynamically but didn't find how to draw inner cells.

I have followed these examples

https://github.com/PhilJay/MPAndroidChart/issues/3751
https://stackoverflow.com/questions/48401946/mpandroidchart-how-to-add-cells-inside-grids-like-graph-sheet
any suggestion will be appreciated 

![bbk3x](https://user-images.githubusercontent.com/8265931/46139541-716c9c80-c26c-11e8-8a03-8c0c1d37de62.jpg)

**Comment by almic** [comment]
I wish I could help you out, as this is a pretty simple design question, but I really can't spend the time to help you. I'm working on updating the library to simplify it so it's easier to find what you need and customize charts. For now you just need to search through the [wiki](https://github.com/PhilJay/MPAndroidChart/wiki) and see if you can't find what you're looking for.

**Comment by Shrikant-B** [comment]
@Tufan21 Are you able figure out any solution for this?
