### ISSUE TITLE
Getting Error "BarChart must not be null"

### ISSUE THREAD

**Issue by joshvapeter** [PhilJay/MPAndroidChart#4247]
Getting Below Error:
 java.lang.IllegalStateException: barChart must not be null

Code:

	 private var jsonStringArray = "[{\"dailyrate\":\"2018-09-01\",\"usercount\":33},{\"dailyrate\":\"2018-09-02\",\"usercount\":44},{\"dailyrate\":\"2018-09-03\",\"usercount\":23},{\"dailyrate\":\"2018-09-04\",\"usercount\":77}] "

		private fun fetchJSON() {
        println("String Value" + jsonStringArray)
        val entries = ArrayList<BarEntry>()
        val labels = ArrayList<String>()
        val arr = JSONArray(jsonStringArray)
        for (i in 0 until arr.length()) {
            entries.add(BarEntry(arr.getJSONObject(i).getInt("usercount").toFloat(), i))
            labels.add(arr.getJSONObject(i).getString("dailyrate"))
        }
        println("user count" + labels)
        val barDataSet = BarDataSet(entries, "Cells")
        val data = BarData(labels, barDataSet)
        barChart.data = data
        barChart.setDescription("User Count Rate")
       barDataSet.color = resources.getColor(R.color.colorAccent)
        barChart.animateY(5000)
    }

**Comment by MGaetan89** [comment]
How did you initialized `barChart`?

**Comment by joshvapeter** [comment]
In the kotlin activity file

**Comment by MGaetan89** [comment]
Can you show how you initialized it? Is it initialized before you call `fetchJSON()`?
