### ISSUE TITLE
Line Graph xAxis with unlimited Years, months and days.

### ISSUE THREAD

**Issue by Ceridoglu** [PhilJay/MPAndroidChart#4249]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ceridoglu** [comment]
Hello all i want to create a line graph include days. And every data will shown in a calculated days. 
Let's say we have Datas called X, Y and Z and every data will change next day(with calculation) how can i show them on the related date.  
Thanks.

**Comment by NavjeetSaini26** [comment]
Have you got any solution ?

**Comment by Ceridoglu** [comment]
Unfortunatelly i don’t get any solution.

**Comment by almic** [comment]
@Ceridoglu sorry but this issue tracker is not the place to ask for programming help. Questions like this belong on stackoverflow.
