### ISSUE TITLE
Implementing AutoZoom on Y-Axis in RealTime Graph 

### ISSUE THREAD

**Issue by Shivam101** [PhilJay/MPAndroidChart#425]
My application generates a real time graph wherein the value on the Y-Axis starts from a certain value(not necessarily 0) and goes up to another value and this keeps fluctuating (something like the graph of a human pulse).

The library already has pinch to zoom,XZoom and YZoom implemented for this, but I would like to have an auto-zoom feature i.e. the value along Y-Axis changes based on the range of the input on Y-Axis without any interference from the user. How can this be done ?

**Comment by PhilJay** [comment]
Take a look at this example: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/RealtimeLineChartActivity.java

Especially the "out-commented" stuff in the `addEntry()` method.
