### ISSUE TITLE
Show points value on combined chart line graph

### ISSUE THREAD

**Issue by NavjeetSaini26** [PhilJay/MPAndroidChart#4251]
How to show value of each points on line graph and line graph is showing additional straight line with points . how to hide this ?

**Comment by NavjeetSaini26** [comment]
[](url)
![graph](https://user-images.githubusercontent.com/38317173/46469745-eeaa8b00-c7f1-11e8-931e-fba7f3daf36c.PNG)

**Comment by almic** [comment]
I know you can do this, I'm going through issues pretty quick though so you need to check the example app yourself to see how this is done.
