### ISSUE TITLE
Change the default "No chart data available" before having data inputed

### ISSUE THREAD

**Issue by FrankXinqi** [PhilJay/MPAndroidChart#4252]
You don't literally copy+paste `char. setNoDataText("")` and expect the problem to fix itself. I've edited the answer by @PhilJay and deleted all the spam to clean this issue up.

And yes, the original answer was a typo, that's why I edited it.

_Originally posted by @almic in https://github.com/PhilJay/MPAndroidChart/issues/2039#issuecomment-388602367_

-----------
char. setNoDataText("") deoesn't work for me.
How could I change the "No chart data available" to something else.

**Comment by Androneilz** [comment]
Agreed. The setNoDataText("") method is not working still, despite numerous issues raised here claiming it does work or has been fixed.

I'm resorting to displaying my own loading view over the chart while it loads, but it would be nice if this simple method worked! Whatever I try, I always see the "No chart data available" text.

**Comment by almic** [comment]
If it doesn't work, then please link a gist with the code you have. I know you are doing something wrong here.

**Comment by smedic** [comment]
What could we do wrong here? 
Both of these don't work:
`PieChart resultsPieChart;
		resultsPieChart.setNoDataText("");
		resultsPieChart.setNoDataTextColor(Color.TRANSPARENT);`

**Comment by jesusignazio** [comment]
To all the people getting this problem, I finally solved it:

`LineChart chart = v.findViewById(R.id.chart);
        chart.setNoDataText("Loading...");
        chart.setNoDataTextColor(Color.TRANSPARENT);
        chart.invalidate();`

Then do all the stuff (get data, making entries, dataSet...etc)

If you set the method after the 'getData' loop, it will be shown the default 'No chart data available' text and by the moment the method is executed it will be never by shown because the chart data is already loaded. Remember the invalidate() too.

**Comment by AndresGarciaSobrado91** [comment]
> To all the people getting this problem, I finally solved it:
> 
> `LineChart chart = v.findViewById(R.id.chart); chart.setNoDataText("Loading..."); chart.setNoDataTextColor(Color.TRANSPARENT); chart.invalidate();`
> 
> Then do all the stuff (get data, making entries, dataSet...etc)
> 
> If you set the method after the 'getData' loop, it will be shown the default 'No chart data available' text and by the moment the method is executed it will be never be shown because the chart data is already loaded. Remember the invalidate() too.
> 
> @smedic @Androneilz

This is the key to solving it, thanks!
