### ISSUE TITLE
NullPointerException at drawMarkers:732

### ISSUE THREAD

**Issue by dimmells** [PhilJay/MPAndroidChart#4257]
If you click on point to display marker and then hide chart, you will have a NullPointerException in drawMarkers method at 732 line. As I understant, to fix that need write this
`            int entryIndex = set.getEntryIndex(e);
`
after this

            // make sure entry not null
            if (e == null || entryIndex > set.getEntryCount() * mAnimator.getPhaseX())
                continue;

Because when chart is not drawed but marker was drawed earlier, Entry object `e` is null.

**Comment by almic** [comment]
Could you please create a gist with the stacktrace and link it here?

**Comment by almic** [comment]
This should be fixed actually, please update to the latest version `3.1.0-alpha`
