### ISSUE TITLE
MPChartAndroid - Line chart with multiple dataset

### ISSUE THREAD

**Issue by aemssid** [PhilJay/MPAndroidChart#4258]
![c_users_pabar_appdata_local_packages_microsoft skypeapp_kzf8qxf38zg5c_localstate_1fc5e9ea-1b08-47fd-b37a-9ae5e838da2d](https://user-images.githubusercontent.com/17213261/46852744-9854d200-ce19-11e8-90cf-9ce497a27204.png)

Let's say we have DataSet1 and DataSet2. DataSet1 has a list of entries with timestamp as X-value and some Integer as Y-value. Dataset2 has only timestamp as X-value they do not have any Y-value. I want to plot DataSet2's entry on LineChart which was plotted on DataSet1's entries.

Required urgent help.

Thanks in advance

**Comment by almic** [comment]
I think you want vertical lines in specific places? You need to use the limit lines, check out the [wiki](https://github.com/PhilJay/MPAndroidChart/wiki).
