### ISSUE TITLE
Need label at top of the each bar in BarChart.

### ISSUE THREAD

**Issue by jayesh28589** [PhilJay/MPAndroidChart#4260]
Hello Phil, 

I need to show label on each bar in BarChart.

The chart is only horizontally srollable with fixed y axis, no zoom in/out functionality (I have already done tihs) , Please see the attached screenshot.
Now I want label on top of each bar, How can I do that ?

Thanks
![4](https://user-images.githubusercontent.com/4100414/46936210-457a5500-d07b-11e8-977f-4f22775655e4.png)

**Comment by almic** [comment]
@jayesh28589 thank you for pointing this out. A similar issue was reported and is currently being worked on.
