### ISSUE TITLE
I have more number of dishes in Graph where each one represents a different colour and at the bottom of page shows the respected dish name with respect to colour. so Here my issue is that i can able to see only limited number of dish names, so how to show all dishes at the bottom of page?

### ISSUE THREAD

**Issue by nishanthvasu** [PhilJay/MPAndroidChart#4265]
![screenshot_20181018-150216](https://user-images.githubusercontent.com/6093062/47145437-621ac500-d2e7-11e8-9f88-15a52a3d5404.jpeg)

**Comment by almic** [comment]
@nishanthvasu thank you for pointing this out. A similar issue was reported and is currently being worked on.
