### ISSUE TITLE
Line Graph Displayed Wrong

### ISSUE THREAD

**Issue by raymondbarrinuevo** [PhilJay/MPAndroidChart#4266]
**Summary**
The graph does not match with the target.

![image](https://user-images.githubusercontent.com/8297619/47199762-bb492e00-d3a5-11e8-800d-207ba51f6b70.png)

**Expected Behavior**
The data displayed should be reflected correctly by the graph.

**Device (please complete the following information):**
 - Device: Samsung Galaxy Tab A 2016 
 - Android Version 5.1.1
 - Library Version v3.0.3

**Additional Context**
As you can notice to the image I give correct value to LineDataSet.

![image](https://user-images.githubusercontent.com/8297619/47200282-14b25c80-d3a8-11e8-969b-faaa26a31fb2.png)

**Comment by almic** [comment]
You can try `HORIZONTAL_BEZIER` instead of `CUBIC_BEZIER`, other than that it looks like the line is being drawn correctly. I know it looks weird but that's just how it goes.
