### ISSUE TITLE
Potential bug

### ISSUE THREAD

**Issue by Xenios91** [PhilJay/MPAndroidChart#4267]
class: MPChartExample/src/com/xxmassdeveloper/mpchartexample/BubbleChartActivity.java
line :104
statement: switch (item.getItemId()) {

This switch statement doesnt appear to have a default value. This can lead to bugs.

**Comment by almic** [comment]
@Xenios91 you're right, in fact I don't think any of those menus have default statements. However, this won't cause any bugs, only that if the menu item is not defined in the switch, nothing happens. There is no reason to have a default case because the default would do nothing anyway.
