### ISSUE TITLE
Can we create radar chart in circle shape?

### ISSUE THREAD

**Issue by pj210493** [PhilJay/MPAndroidChart#4269]
# *STOP RIGHT THERE!*

Issues are ***NOT*** for getting help, only for reporting bugs and feature requests.

Search open and closed issues to see if your question already has an answer. However, **do not create a new issue.**

Instead, do the following:

1. Download the [Example App](https://play.google.com/store/apps/details?id=com.xxmassdeveloper.mpchartexample) and check out the [source code](https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample). 90% of the time there is an example that does exactly what you are trying to do.

1. Look at the [Wiki](https://github.com/PhilJay/MPAndroidChart/wiki) for the official documentation for MPAndroidChart. You can also browse the [javadoc](https://jitpack.io/com/github/PhilJay/MPAndroidChart/v3.0.3/javadoc/) for a more detailed tutorial of the API.

1. Go to [StackOverflow](https://stackoverflow.com/questions/tagged/mpandroidchart) and ask your questions there. The community will be much more helpful and willing to offer guidance.

### You have been warned!

From now on, any issues asking for help will get closed with a link to this file.

**Comment by pj210493** [comment]
https://github.com/thezukkino

**Comment by thezukkino** [comment]
As you can see in the comment, I've documented that the solution 
provided as answer of the question does not work.
The words below were an extra answer.

I think a warning is a little bit undue.


Il 24/10/2018 13:03, pj210493 ha scritto:

**Comment by almic** [comment]
Please follow the instructions in the templates.

And do not ping the developers.
