### ISSUE TITLE
Gesture Listener Not working on Fragments.

### ISSUE THREAD

**Issue by akkishinde** [PhilJay/MPAndroidChart#427]
Hi,

I am displaying my charts in fragments. I have implemented the OnChartGestureListener method.
But gestures are not working. for a test I generated the toast messages on gestures, but toasts are not generating.

**Comment by akkishinde** [comment]
Not even in Activity..!!! 

Actually I want to Save the chart on Long Pressed Gesture but none of the things working.
Save to Gallery is also getting failed.

**Comment by PhilJay** [comment]
Provide some code.
