### ISSUE TITLE
Library AAR/JAR update

### ISSUE THREAD

**Issue by eakteam** [PhilJay/MPAndroidChart#4275]
Will be there any release update after this : https://github.com/PhilJay/MPAndroidChart/commit/d67ea481af1e8528c617dfd404d0c7827b0134b2

Or we should download project as zip and implement as external library ?

**Comment by MGaetan89** [comment]
As this lib is published on JitPack, you can use any commit you want as the version.
So to answer your question, you can use the following dependency:
`com.github.PhilJay:MPAndroidChart:d67ea481af`

**Comment by eakteam** [comment]
@MGaetan89 , thanks for your help. It works

**Comment by almic** [comment]
Just to be clear, I plan on the next release being v3.1.0 which will implement at least everything currently in the [Version 3.1.0 Project](https://github.com/PhilJay/MPAndroidChart/projects/2).
