### ISSUE TITLE
Random color for every single bar on bar chart

### ISSUE THREAD

**Issue by ahmaadyunus** [PhilJay/MPAndroidChart#4278]
halooo,
I have problem with set color to bar chart with much data (50 - 100 data). I need to set all bar with different color for every single bar.  What should I do to fix this ? 
thanks
regard

**Comment by almic** [comment]
You can use `set.setColors()` with an `int[]` of colors. Check out this line of the example activity [`AnotherBarActivity`](https://github.com/PhilJay/MPAndroidChart/blob/5030b36c86cfa2d076bb6b86fa8fcb37ce58557f/MPChartExample/src/main/java/com/xxmassdeveloper/mpchartexample/AnotherBarActivity.java#L107)

**Comment by almic** [comment]
You can use as many or few colors as you want. For example, if you have 50 bars but only 3 colors, then those three colors will be repeated for all 50 bars.
