### ISSUE TITLE
group bar chart not show complete percentage

### ISSUE THREAD

**Issue by Deepakkast** [PhilJay/MPAndroidChart#4281]
i have group bar chart in my android project but when i get data from server my group bar chart show percentage like 55 on first bar and 44 on second bar how can i solve this problem because there is diffrance of 1 percent

**Comment by almic** [comment]
I think you need to look at your value formatter, which displays the numbers on your bars and is likely causing this rounding error.

Check this wiki page out for more info: [The ValueFormatter Interface](https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface)
And here is the actual class you'll use: [`IValueFormatter`](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/main/java/com/github/mikephil/charting/formatter/IValueFormatter.java)
