### ISSUE TITLE
How do I centralize the first bar and its label ? 

### ISSUE THREAD

**Issue by pikaboo** [PhilJay/MPAndroidChart#4284]
Look at the images below, the first bar and its label are always out of sync, the bar is more left and the label is more right

How can I fix this ? 

![image](https://user-images.githubusercontent.com/3405551/47965940-7388fe80-e055-11e8-8db3-16be06d3db14.png)

![image](https://user-images.githubusercontent.com/3405551/47965942-7be13980-e055-11e8-892a-65c6b3ba95b1.png)
![image](https://user-images.githubusercontent.com/3405551/47965946-87346500-e055-11e8-8e46-795052e6469f.png)

**Comment by almic** [comment]
This has to do with how you are adding the data to the chart. All the examples in the example app have properly centered labels, so please compare your code with that and do it correctly.
