### ISSUE TITLE
How to set a different radius for each piece in perchart

### ISSUE THREAD

**Issue by dongyiming** [PhilJay/MPAndroidChart#4287]
**Summary**

**Expected Behavior**

**Possible Solution**

**Device (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - Android Version [e.g. 7.0]
 - Library Version (e.g. 3.1.0-alpha)

**Additional Context**

**Comment by almic** [comment]
Please use the templates correctly, and also search the issues as this exact question has already been asked and I'm pretty confident it's in the project lists.

**Comment by almic** [comment]
If you didn't catch that, do *not* open another issue about this. Thanks
