### ISSUE TITLE
version 3.0.3

### ISSUE THREAD

**Issue by linjian99666** [PhilJay/MPAndroidChart#4288]
v3.0.3

 BarChart set Legend setYEntrySpace() doesn't work!

des:
       First,I  set xAxis.setLabelRotationAngle(-60);
       Then,I wanna to set legend.setYEntrySpace(20f); but I found that doesn't work ,so  I think it cound be the reason I set the angle,but  when I cancel set angle, it seems didn't work too,can you help me so solve this problem? thx very much.

**Comment by almic** [comment]
`Legend.setYEntrySpace()` is only to increase the line spacing for vertical legends, it has absolutely nothing to do with the axis labels.
