### ISSUE TITLE
Why my value xaxis keep repeat

### ISSUE THREAD

**Issue by Ryghas** [PhilJay/MPAndroidChart#4289]
![screenshot_1541563028](https://user-images.githubusercontent.com/19976921/48110146-fdff7700-e27c-11e8-98db-084d47945db6.png)
can anyone help me? my value label keep repeating when i get data from sqlite.

this my code

![screen shot 2018-11-07 at 11 07 48](https://user-images.githubusercontent.com/19976921/48110405-8a5e6980-e27e-11e8-8efc-f116298c331e.png)

**Comment by almic** [comment]
@Ryghas sorry but this issue tracker is not the place to ask for programming help. Questions like this belong on stackoverflow.

**Hint:** you need to actually use the `value` to determine which date to  😞

**Comment by almic** [comment]
Also there is never any reason to comment on your own post just to ask for help twice, we'll see it!
