### ISSUE TITLE
Line chart not drawn inside recyclerview

### ISSUE THREAD

**Issue by Javohir6949** [PhilJay/MPAndroidChart#4291]
I posted it in another issue.But noone answers me. I have recyclerview.Inside it linechart.Line chart is not drawn
        `yVals1.add(new Entry(1, 7500));
        yVals1.add(new Entry(2, 14500));
        yVals1.add(new Entry(3, 18500));
        yVals1.add(new Entry(4, 32500));
        yVals1.add(new Entry(5, 29000));
        yVals1.add(new Entry(6, 7500));
        yVals1.add(new Entry(7, 13500));

        yVals2.add(new Entry(1, 4500));
        yVals2.add(new Entry(2, 24500));
        yVals2.add(new Entry(3, 38500));
        yVals2.add(new Entry(4, 0));
        yVals2.add(new Entry(5, 0));
        yVals2.add(new Entry(6, 0));
        yVals2.add(new Entry(7, 0));

        viewHolder.mLineChart.setOnChartValueSelectedListener(this);
        viewHolder.mLineChart.setTouchEnabled(true);
        viewHolder.mLineChart.setDragDecelerationFrictionCoef(0.9f);
        viewHolder.mLineChart.setDragEnabled(true);
        viewHolder.mLineChart.getDescription().setEnabled(false);
        viewHolder.mLineChart.setScaleEnabled(true);
        viewHolder.mLineChart.setDrawGridBackground(false);
        viewHolder.mLineChart.setHighlightPerDragEnabled(false);
        viewHolder.mLineChart.setPinchZoom(true);
        viewHolder.mLineChart.setAutoScaleMinMaxEnabled(true);
        viewHolder.mLineChart.setBackgroundColor(mContext.getResources().getColor(R.color.white));
        viewHolder.mLineChart.animateX(500);

        viewHolder.mLineChart.setLayerType(View.LAYER_TYPE_NONE, null);
        viewHolder.mLineChart.getRenderer().getPaintRender().setShadowLayer(10, 0, 50, getColorWithAlpha(Color.GRAY,0.1f));

        viewHolder.mLineChart.notifyDataSetChanged();
        viewHolder.mLineChart.invalidate();
        XAxis xAxis = viewHolder.mLineChart.getXAxis();
        xAxis.setTextSize(11f);
        xAxis.setTextColor(mContext.getResources().getColor(R.color.inactive_tab_layout_text_color));
        xAxis.setDrawGridLines(false);
        xAxis.setDrawAxisLine(false);
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);

        YAxis leftAxis = viewHolder.mLineChart.getAxisLeft();
        leftAxis.setTextColor(ColorTemplate.getHoloBlue());
        leftAxis.setAxisMinimum(0f);
        leftAxis.setDrawGridLines(false);
        leftAxis.setGranularityEnabled(true);
        leftAxis.setEnabled(false);

        YAxis rightAxis = viewHolder.mLineChart.getAxisRight();
        rightAxis.setTextColor(Color.RED);
        rightAxis.setAxisMinimum(0);
        rightAxis.setDrawGridLines(false);
        rightAxis.setEnabled(false);
        rightAxis.setDrawZeroLine(false);
        rightAxis.setGranularityEnabled(false);

        Legend l = viewHolder.mLineChart.getLegend();
        l.setForm(Legend.LegendForm.LINE);
        l.setTextSize(11f);
        l.setTextColor(Color.WHITE);
        l.setVerticalAlignment(Legend.LegendVerticalAlignment.BOTTOM);
        l.setHorizontalAlignment(Legend.LegendHorizontalAlignment.LEFT);
        l.setOrientation(Legend.LegendOrientation.HORIZONTAL);
        l.setDrawInside(false);

        LineDataSet set1, set2;

        if (viewHolder.mLineChart.getData() != null && viewHolder.mLineChart.getData().getDataSetCount() > 0) {
            set1 = (LineDataSet) viewHolder.mLineChart.getData().getDataSetByIndex(0);
            set2 = (LineDataSet) viewHolder.mLineChart.getData().getDataSetByIndex(2);
            set1.setValues(yVals1);
            set2.setValues(yVals2);
            viewHolder.mLineChart.getData().notifyDataChanged();
            viewHolder.mLineChart.notifyDataSetChanged();
        } else {
            set1 = new LineDataSet(yVals1, "");

            set1.setAxisDependency(YAxis.AxisDependency.LEFT);
            set1.setColor(mContext.getResources().getColor(R.color.income_money_color));
            set1.setCircleColor(mContext.getResources().getColor(R.color.income_money_color));
            set1.setLineWidth(5f);
            set1.setCircleRadius(0f);
            set1.setFillAlpha(60);
            set1.setFillColor(mContext.getResources().getColor(R.color.income_money_color));
            set1.setHighLightColor(mContext.getResources().getColor(R.color.income_money_color));
            set1.setDrawCircleHole(false);

            set2 = new LineDataSet(yVals2, "");
            set2.setAxisDependency(YAxis.AxisDependency.RIGHT);
            set2.setColor(mContext.getResources().getColor(R.color.pastel_red));
            set2.setLineWidth(5f);
            set2.setCircleRadius(0f);
            set2.setFillAlpha(60);
            set2.setFillColor(mContext.getResources().getColor(R.color.pastel_red));
            set2.setDrawCircleHole(false);
            set2.setCircleColor(getColorWithAlpha(mContext.getResources().getColor(R.color.pastel_red),0.4f));
            set2.setHighLightColor(mContext.getResources().getColor(R.color.pastel_red));

            set1.setMode(LineDataSet.Mode.CUBIC_BEZIER);
            set2.setMode(LineDataSet.Mode.CUBIC_BEZIER);

            LineData data = new LineData(set1, set2);

            data.setValueTextColor(mContext.getResources().getColor(R.color.transparent));

            viewHolder.mLineChart.setData(data);
            viewHolder.mLineChart.getData().notifyDataChanged();
            viewHolder.mLineChart.notifyDataSetChanged();
        }`

**Comment by Javohir6949** [comment]
Please Can anyone help me?

**Comment by almic** [comment]
@Javohir6949 please look at the issue you already commented on, it has the solution.

If that doesn't fix your problem, then please open a new issue and follow the instructions in the templates. I cannot help you if you don't actually explain what is happening and what should happen.

Also, you barely waited 5 minutes before opening an issue, no one is that fast! Have some patience and try to figure it out yourself before spamming issue trackers.
