### ISSUE TITLE
I can't add additional label for the Xaxis

### ISSUE THREAD

**Issue by htduongdl96** [PhilJay/MPAndroidChart#4296]
I can't add additional label to the Xaxis, and if i add 0 data, the line point into 0, how can i make the line skip the data with 0 value?
![image](https://user-images.githubusercontent.com/37286834/48183696-2e6d1100-e362-11e8-992b-f92236b38c24.png)
I need to do this:
![image](https://user-images.githubusercontent.com/37286834/48183514-848d8480-e361-11e8-91fb-b1d4fe7c5c13.png)
Can anyone help me with this Issue?

**Comment by almic** [comment]
I guess you have a similar use case to another issue asking about allowing null values, thus causing the chart to skip rendering points between two other sections. This is currently being worked on.
