### ISSUE TITLE
LineChart graph is drawn with incomplete lines

### ISSUE THREAD

**Issue by benitovc** [PhilJay/MPAndroidChart#4298]
When I add points on my LineChart, they are drawn in a right way, but suddenly when I add the 7th and 8th points graph looks like:
![screenshot](https://user-images.githubusercontent.com/17068109/48315418-f8b76a80-e5a3-11e8-8f9b-6479ce99223c.png)

Points: [Entry, x: 30566.0 y: 656.85, Entry, x: 32913.0 y: 656.7, Entry, x: 32929.0 y: 656.5, Entry, x: 32952.0 y: 656.7, Entry, x: 32976.0 y: 657.25, Entry, x: 32979.0 y: 657.4, Entry, x: 32981.0 y: 657.5, Entry, x: 32989.0 y: 657.5]
Following is the code:
        mChart.setDrawGridBackground(false);
        Description description = new Description();
        description.setText("");
        mChart.setDescription(description);
        mChart.setNoDataText("");
        mChart.setTouchEnabled(false);
        mChart.setDragEnabled(false);
        mChart.setScaleEnabled(false);
        mChart.setPinchZoom(false);
        mChart.setDrawBorders(false);
        mChart.setAutoScaleMinMaxEnabled(true);
        mChart.setDrawMarkers(false);

        xAxis = mChart.getXAxis();
        xAxis.removeAllLimitLines();
        xAxis.setAxisLineColor(R.color.colorBlanco);
        xAxis.setDrawAxisLine(false);
        xAxis.enableAxisLineDashedLine(4f, 4f, 0f);
        xAxis.enableGridDashedLine(4f, 4f, 0f);
        xAxis.setAxisLineColor(ContextCompat.getColor(contexto, R.color.colorBlanco));
        xAxis.setGridColor(ContextCompat.getColor(contexto, R.color.colorAtenuadoC));
        xAxis.setTextColor(ContextCompat.getColor(contexto, R.color.colorAtenuadoB));
        xAxis.setPosition(XAxis.XAxisPosition.TOP);
        xAxis.setTextSize(14f);
        xAxis.setGridLineWidth(1f);
        xAxis.setValueFormatter(xLabelFormatter);
        xAxis.setYOffset(0);
        xAxis.setAvoidFirstLastClipping(true);

        YAxis leftAxis = mChart.getAxisLeft();
        leftAxis.setEnabled(false);

        rightAxis = mChart.getAxisRight();
        rightAxis.removeAllLimitLines();
        rightAxis.enableAxisLineDashedLine(0f, 4f, 0f);
        rightAxis.enableGridDashedLine(4f, 4f, 0f);
        rightAxis.setAxisLineColor(ContextCompat.getColor(contexto, R.color.colorBlanco));
        rightAxis.setGridColor(ContextCompat.getColor(contexto, R.color.colorAtenuadoC));
        rightAxis.setTextColor(ContextCompat.getColor(contexto, R.color.colorAtenuadoB));
        rightAxis.setZeroLineColor(ContextCompat.getColor(contexto, R.color.colorBlanco));
        rightAxis.setTextSize(16f);
        rightAxis.setDrawZeroLine(false);
        rightAxis.setDrawLimitLinesBehindData(false);
        rightAxis.setLabelCount(4, true);
        rightAxis.setGranularity(0.25f);
        rightAxis.setValueFormatter(yLabelFormatter);

        mChart.animateX(100);
        mChart.getLegend().setEnabled(false);

And set has the following settings:

        LineDataSet set = new LineDataSet(points, "");
        set.setCircleColor(color);
        set.setCircleRadius(0f);
        set.setColor(color);
        set.setLineWidth(1.1f);
        set.setValueTextSize(0f);
        set.setAxisDependency(YAxis.AxisDependency.RIGHT);
        set.setMode(LineDataSet.Mode.LINEAR);
        set.setDrawCircles(false);
        set.setDrawCircleHole(false);
        set.setDrawValues(false);

Any idea why graph is painted weird?

**Comment by almic** [comment]
"Any idea why graph is painted weird?" is not very specific at all. I assume you mean the line is drawn in that dashed way with the edges fading out. Are you sure that is all that you do to the line data set? I don't see any reason with the code you've shown that could cause the line to be drawn that way.

**Comment by benitovc** [comment]
Yes, the edges fading out are weird, I don´t have more code in for the graph.

**Comment by benitovc** [comment]
The following is the full class for the graph:

package com.bvcapps.marketdata;

import android.content.Context;
import android.graphics.Color;
import android.support.v4.content.ContextCompat;
import android.util.Log;

import com.github.mikephil.charting.charts.LineChart;
import com.github.mikephil.charting.components.AxisBase;
import com.github.mikephil.charting.components.Description;
import com.github.mikephil.charting.components.LimitLine;
import com.github.mikephil.charting.components.XAxis;
import com.github.mikephil.charting.components.YAxis;
import com.github.mikephil.charting.data.Entry;
import com.github.mikephil.charting.data.LineData;
import com.github.mikephil.charting.data.LineDataSet;
import com.github.mikephil.charting.formatter.IAxisValueFormatter;
import com.github.mikephil.charting.interfaces.datasets.ILineDataSet;

import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.TimeZone;

public class GraficoTrades {

    private static long GAP_END_GRAPH = 30; // treinta segundos cerca del tiempo final
    private static long ADITIONAL_GAP = 2 * 60; // dos minutos para mover el tiempo final
    private LineChart mChart;
    private int colorLine;
    private DateFormat formatUTC;
    private DateFormat formatTL;
    private DecimalFormat dfPrice;
    private DecimalFormat df;
    private IAxisValueFormatter yLabelFormatter;
    private IAxisValueFormatter xLabelFormatter;
    private ArrayList<Entry> priceValues;
    private long maxTime;
    private long firstTime;
    private long endTime;
    private long lastTime;
    private float lastPrice;
    private XAxis xAxis;
    private YAxis yAxis;
    LimitLine timeLimitLine;
    LimitLine priceLimitLine;

    public GraficoTrades(Context contexto, Object chart, String formatPrecio, int colorLine, int colorBarras) {
        mChart = (LineChart)chart;
        if (mChart == null) return;
        this.colorLine = colorLine;
        formatUTC = new SimpleDateFormat("yyyyMMdd-HH:mm:ss.SSS");
        formatUTC.setTimeZone(TimeZone.getTimeZone("UTC"));
        formatTL = new SimpleDateFormat("HHmmss");
        formatTL.setTimeZone(TimeZone.getDefault());
        firstTime = 0;
        maxTime = 24*60*60;
        dfPrice = new DecimalFormat(formatPrecio);
        yLabelFormatter = new IAxisValueFormatter() {
            @Override
            public String getFormattedValue(float value, AxisBase axis) {
                return dfPrice.format(value);
            }
        };
        xLabelFormatter = new IAxisValueFormatter() {
            @Override
            public String getFormattedValue(float value, AxisBase axis) {
                return formatTiempoHHMM(value);
            }
        };
        df = new DecimalFormat("00");

        priceValues = new ArrayList<Entry>();

        //mChart.setOnChartGestureListener(this);
        //mChart.setOnChartValueSelectedListener(this);
        mChart.setDrawGridBackground(false);
        Description description = new Description();
        description.setText("");
        mChart.setDescription(description);
        mChart.setNoDataText("");
        mChart.setTouchEnabled(false);
        mChart.setDragEnabled(false);
        mChart.setScaleEnabled(false);
        mChart.setPinchZoom(false);
        mChart.setDrawBorders(false);
        mChart.setAutoScaleMinMaxEnabled(true);
        mChart.setDrawMarkers(false);

        xAxis = mChart.getXAxis();
        xAxis.removeAllLimitLines();
        xAxis.setAxisLineColor(R.color.colorBlanco);
        xAxis.setDrawAxisLine(false);
        xAxis.enableAxisLineDashedLine(4f, 4f, 0f);
        xAxis.enableGridDashedLine(4f, 4f, 0f);
        xAxis.setAxisLineColor(ContextCompat.getColor(contexto, R.color.colorBlanco));
        xAxis.setGridColor(ContextCompat.getColor(contexto, R.color.colorAtenuadoC));
        xAxis.setTextColor(ContextCompat.getColor(contexto, R.color.colorAtenuadoB));
        xAxis.setPosition(XAxis.XAxisPosition.TOP);
        xAxis.setTextSize(14f);
        xAxis.setGridLineWidth(1f);
        xAxis.setValueFormatter(xLabelFormatter);
        xAxis.setYOffset(0);
        xAxis.setAvoidFirstLastClipping(true);
        xAxis.setLabelCount(5, true);
        xAxis.setGranularity(300);

        YAxis leftAxis = mChart.getAxisLeft();
        leftAxis.setEnabled(false);

        yAxis = mChart.getAxisRight();
        yAxis.removeAllLimitLines();
        yAxis.enableAxisLineDashedLine(0f, 4f, 0f);
        yAxis.enableGridDashedLine(4f, 4f, 0f);
        yAxis.setAxisLineColor(ContextCompat.getColor(contexto, R.color.colorBlanco));
        yAxis.setGridColor(ContextCompat.getColor(contexto, R.color.colorAtenuadoC));
        yAxis.setTextColor(ContextCompat.getColor(contexto, R.color.colorAtenuadoB));
        yAxis.setZeroLineColor(ContextCompat.getColor(contexto, R.color.colorBlanco));
        yAxis.setTextSize(16f);
        yAxis.setDrawZeroLine(false);
        yAxis.setDrawLimitLinesBehindData(false);
        yAxis.setLabelCount(4, true);
        yAxis.setGranularity(0.25f);
        yAxis.setValueFormatter(yLabelFormatter);

        mChart.animateX(100);
        mChart.getLegend().setEnabled(false);
    }

    public void clear() {
        if (mChart == null) return;
        mChart.clear();
    }

    public boolean addValorPrecio(String strTime, float value, boolean fromFullSanpshot) {
        if (mChart == null) return false;
        long time = getTiempo(strTime);
        //Log.wtf("textoGT", "addValorPrecio: tiempo=(" + tiempo + ")" + formatTiempo(tiempo) +
        //        ", " + valor + " horaMínima: (" + firstTime + ")" + formatTiempo(firstTime) +
        //        " endTime (" + endTime + ")" + formatTiempo(endTime));
        if (firstTime == 0 || time < firstTime) {
            firstTime = setFirstTime(time, ADITIONAL_GAP);
        }
        if (endTime - time < GAP_END_GRAPH) {
            // Solo si el el tiempo del último dato ya está muy cerca de la hora de fin, mover el fin
            setEndTime(time, ADITIONAL_GAP);
        }
        // Añade el nuevo valor
        priceValues.add(new Entry(time, value));
        if (lastTime < time) lastTime = time;
        lastPrice = value;
        return true;
    }

    public void notifyChange() {
        if (mChart == null) return;
        Log.wtf("textoGT", "notificarCambioGraficoTrades Precios: " + priceValues.size());
        LineDataSet set;
        LineData lineData = mChart.getData();
        if(lineData !=null && lineData.getDataSetCount() > 0) {
            set = (LineDataSet) lineData.getDataSetByIndex(0);
            set.setValues(priceValues);
            if (priceLimitLine.getLimit() != lastPrice) {
                yAxis.removeLimitLine(priceLimitLine);
                priceLimitLine.update(lastPrice, dfPrice.format(lastPrice));
                yAxis.addLimitLine(priceLimitLine);
            }
            mChart.getData().notifyDataChanged();
            mChart.notifyDataSetChanged();

            xAxis.removeLimitLine(timeLimitLine);
            timeLimitLine.update(lastTime, formatTiempo(lastTime));
            xAxis.addLimitLine(timeLimitLine);
            xAxis.setAxisMinimum(firstTime);
            xAxis.setAxisMaximum(endTime);
            mChart.invalidate();
        } else {
            ArrayList<ILineDataSet> dataSets = new ArrayList<ILineDataSet>();
            dataSets.add(prepareSet(priceValues, colorLine));
            priceLimitLine = prepareLimitLine(lastPrice, dfPrice.format(lastPrice), colorLine, Color.WHITE, 16f);
            yAxis.addLimitLine(priceLimitLine);
            LineData data = new LineData(dataSets);
            mChart.setData(data);

            timeLimitLine = prepareLimitLine(lastTime, formatTiempo(lastTime), colorLine, colorLine, 14f);
            xAxis.addLimitLine(timeLimitLine);
            xAxis.setAxisMinimum(firstTime);
            xAxis.setAxisMaximum(endTime);
            mChart.invalidate();
        }
    }

    private LineDataSet prepareSet(ArrayList<Entry> values, int color) {
        LineDataSet set = new LineDataSet(values, "");
        //set.setCircleColor(color);
        //set.setCircleRadius(0f);
        set.setColor(color);
        set.setLineWidth(1.1f);
        //set.setValueTextSize(0f);
        set.setAxisDependency(YAxis.AxisDependency.RIGHT);
        //set.setMode(LineDataSet.Mode.LINEAR);
        set.setDrawCircles(false);
        //set.setDrawCircleHole(false);
        set.setDrawValues(false);
        return set;
    }

    private LimitLine prepareLimitLine(float limit, String label, int colorLine, int textColor, float textSize) {
        LimitLine limitLine = new LimitLine(limit, label);
        limitLine.setLineColor(colorLine);
        limitLine.setTextColor(textColor);
        limitLine.setTextSize(textSize);
        limitLine.setLineWidth(1f);
        limitLine.setDrawLimitLineLabel (false);
        limitLine.enableDashedLine(4f, 4f, 0f);
        return limitLine;
    }

    public void setMaxTime(String strMaxTime) {
        if (mChart == null) return;
        this.maxTime = getTiempo(strMaxTime);
    }

    private long getHoraSegundos (String strTime) {
        long secs = (Integer.valueOf(strTime.substring(0,2)) * 60 + Integer.valueOf(strTime.substring(2,4))) * 60 + Integer.valueOf(strTime.substring(4));
        return secs;
    }

    private String formatTiempoHHMM(float value) {
        int minutes = (int)(value / 60f);
        int hours = (int)(minutes / 60f);
        minutes = minutes - hours * 60;
        return df.format(hours) + ":" + df.format(minutes);
    }

    private String formatTiempo(float value) {
        int minutes = (int)(value / 60f);
        int seconds = (int)value - minutes * 60;
        int hours = (int)(minutes / 60f);
        minutes = minutes - hours * 60;
        return df.format(hours) + ":" + df.format(minutes) + ":" + df.format(seconds);
    }

    private long getTiempo (String strTime) {
        try {
            return getHoraSegundos(formatTL.format(formatUTC.parse(strTime)));
        } catch (ParseException e) {
            e.printStackTrace();
        }
        return 0;
    }

    private long setFirstTime(long time, long aditionalGap) {
        // pone la hora mínima truncado a 5 minutos
        long t = (time - aditionalGap) / 300;
        return t * 300;
    }

    private void setEndTime(long time, long gap) {
        // pone la hora fin llevado al a 5 minutos siguientes
        endTime = (time + gap) / 300;
        endTime = (endTime + 1) * 300;
        if (endTime > maxTime) endTime = maxTime;
        Log.wtf("textoGT", "nuevo setEndTime: (" + endTime + ")" + formatTiempo(endTime));
    }

}

**Comment by almic** [comment]
Initially looking through I don't see anything that would cause this. I'm going to come back to this and try to recreate it to see what's going on. I can't give you a time estimate so for now just fiddle around with changing options until it looks right and see if you can figure it out.

**Comment by benitovc** [comment]
I found a related issue reported on stackoverflow:
[https://stackoverflow.com/questions/46118844/mpandroidchart-fading-lines-on-line-chart-step-when-last-two-entries-are-close](url)
The problem occurs in APIs under 18

**Comment by almic** [comment]
Well that's funny, at least it's a pretty simple fix. I wonder if there is a way to prevent this from happening without having to manually call `chart.setHardwareAccelerationEnabled(false);`

🤔

**Comment by chiragVDario** [comment]
can anyone help me to handle null or 0f entries in last entry
