### ISSUE TITLE
BarChart: How to draw gradient color for a bar?

### ISSUE THREAD

**Issue by jonescx** [PhilJay/MPAndroidChart#430]
Hi,
Is it possible to draw gradient color for a bar like the attached image? Thank you.

![68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d5043686172742f6d61737465722f73637265656e73686f74732f73696d706c6564657369676e5f6261726368617274332e706e67](https://cloud.githubusercontent.com/assets/6426584/6594546/464a4ae0-c81d-11e4-8cf9-93a382f0fa68.png)

**Comment by rajatdeshpande** [comment]
This looks like an interesting requirement, it would be amazing if we could
do this :)

On Wed, Mar 11, 2015 at 4:04 PM, Jones <notifications@github.com> wrote:

> Hi,
> I know how to set single color for each bar. Is it possible to draw
> gradient color for a bar like the attached image? Thank you.
>
> [image:
> 68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d5043686172742f6d61737465722f73637265656e73686f74732f73696d706c6564657369676e5f6261726368617274332e706e67]
> <https://cloud.githubusercontent.com/assets/6426584/6594546/464a4ae0-c81d-11e4-8cf9-93a382f0fa68.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PhilJay/MPAndroidChart/issues/430>.
>



-- 
Rajat Deshpande
Mechanical Engineering
IIT BOMBAY

**Comment by PhilJay** [comment]
Gradients are not yet possible, you will have to implement that yourself.

Best regards,
Phil

**Comment by comeback4u** [comment]
Hello PhilJay,
can I edit library for gradient support?

**Comment by Odaym** [comment]
Hey man, good job on the library, if you see the iOS counterpart library (exactly the same as this one, it's a port to iOS) they've posted a very similar issue [https://github.com/danielgindi/Charts/issues/1065](url) and the class offered in the questions works very well. Maybe something similar can happen here?
