### ISSUE TITLE
Pie Chart: Rounded corners / corner radius

### ISSUE THREAD

**Issue by JamieKalloe** [PhilJay/MPAndroidChart#4300]
Hi all,

I'm looking to round corners on a Pie Chart, preferably on a specific dataset if that's possible.

Some guidance and/or tips would be greatly appreciated!

Thank you!

**Comment by almic** [comment]
Do you mean something like this?
![screenshot_2018-11-12-10-05-04](https://user-images.githubusercontent.com/21991767/48363464-362efd00-e663-11e8-98bf-90659a6870b2.png)

**Comment by JamieKalloe** [comment]
@almic Yes this is exactly what I'm looking for, could you point me in the right direction on how to achieve this behaviour?

**Comment by almic** [comment]
@JamieKalloe I'm still have a lot of planned additions for this library, and I don't want to release alpha builds too frequently. For now you can use this in you dependencies until I create another pre-release build.

```groovy
implementation 'com.github.philjay:mpandroidchart:aea2ff3417'
```

**Comment by JamieKalloe** [comment]
@almic Thank you!

**Comment by AtifAbbAsi19** [comment]
after clicking curved part its not poping up why.?

**Comment by AtifAbbAsi19** [comment]
@almic any update regarding to highlighted slice.?
