### ISSUE TITLE
How to overide Talkback Accessibility to linechart

### ISSUE THREAD

**Issue by zicohasan** [PhilJay/MPAndroidChart#4301]
I have been worked for the chart with accessibility function for the blind user, like Talkback. But the swipe gesture in talkback would only run using two-finger gesture instead of one finger gesture. How to override this function so we can swipe using one finger like using without Talkback. And also, I found the double tap and fling is not working in if talkback is being enable. How we can make it work?

**Comment by almic** [comment]
Blind accessibility is, regrettably, not something I can help you with. I also can't recommend adding support for it to the library. Because of that I am closing this issue as `wontfix`.
