### ISSUE TITLE
features drawing lineswith xy start end

### ISSUE THREAD

**Issue by Pascal66** [PhilJay/MPAndroidChart#4305]
Hello, after many tries, it seems impossible to do that sort of diagram
I wish to draw it in background (it always change)  and plot some points inside in real time.
![Diagramm](http://uel.unisciel.fr/chimie/elementsp1/elementsp1_ch04/res/img1_ch4_ex1.png)

**Comment by almic** [comment]
All of this is possible to do, except for the black line coming off the second and third points, and the tick marks on the axes. If you have a suggestion then please make it as this chart has a lot of stuff going on and I don't know what exactly you have and what you don't have.

**Comment by Pascal66** [comment]
Thank @almic 
I'll try an old answer : [Multiple dataset](https://stackoverflow.com/questions/26873445/plot-multiple-charts-in-one-in-mpandroidchart)

**Comment by Pascal66** [comment]
Resolved for now. thank you
![first try](https://user-images.githubusercontent.com/3041616/48606119-02afe380-e97f-11e8-8474-7d0ea8a98683.png)

**Comment by almic** [comment]
@Pascal66 thanks for following up! Again, if you ever had any suggestions then please open an issue and use the template.
