### ISSUE TITLE
MPAndroidChart setData 2 Lines over BarGraph

### ISSUE THREAD

**Issue by maho424242** [PhilJay/MPAndroidChart#4307]
Hello,

I really need help about my Problem that is shown on the Picture.

I want to set my Bar-Data with two lines.

It's not possible to do it with **\n**.

I use MPAndroidChart Version v2.2.4.

I tried it with this code:

Bar1 = new BarEntry(20f,0,"2"+"\n"+"20");
Bar2 = new BarEntry(80f,1,"8"+"\n"+"80");
Bar3 = new BarEntry(60f,2,"6"+"\n"+"60");
Bar4 = new BarEntry(50f,3,"5"+"\n"+"50");
Bar5 = new BarEntry(70f,4,"7"+"\n"+"70");
Bar6 = new BarEntry(60f,5,"6"+"\n"+"60");

K1_barEntries = new ArrayList<>();

K1_barEntries.add(Bar1);
K1_barEntries.add(Bar2);
K1_barEntries.add(Bar3);
K1_barEntries.add(Bar4);
K1_barEntries.add(Bar5);
K1_barEntries.add(Bar6);

K1_barDataSet  = new BarDataSet(K1_barEntries,"");

K1_data = new BarData(labels, K1_barDataSet);
K1_barDataSet.setColors(ColorTemplate.COLORFUL_COLORS);

K1_barDataSet.setValueFormatter(new ValueFormatter() {
    @Override
    public String getFormattedValue(float value, Entry entry, int dataSetIndex, ViewPortHandler viewPortHandler) {
            return entry.getData().toString();
    }
});

![rgqyr](https://user-images.githubusercontent.com/45019175/48448044-09cbcb80-e79e-11e8-8903-3a96efa13a38.png)

I hope that someone can help me.
Thank you.

**Comment by almic** [comment]
This has been mentioned a few times already, and allowing the use of multiple lines in labels is something being worked on, but I can pretty much promise it won't be as simple as using the newline `\n` character in labels. I'm thinking more of allowing label formatters to return spannables or views, but I'm not sure yet.

I'm closing this issue to keep the tracker clean (as best as I can, I guess) but just know that this will be added in a future release!
