### ISSUE TITLE
Bug in clearing Realtime chart

### ISSUE THREAD

**Issue by PieterAelse** [PhilJay/MPAndroidChart#431]
Continuing my realtime data app using your latest Realtime chart changes (see previous 'issue' (https://github.com/PhilJay/MPAndroidChart/issues/314) ) I ran into some bug/issue when clearing the graph.

With my previous workaround my clear button would simply do `lineChart.clear()` and init the graph again with new lineData with 10 X values. Using the new way regarding your Realtime chart example this gave me some unwanted results. The graph doesn't seem to reset the viewport to fit the screen/X-width. I can scroll horizontally but that's not what I want for 10 X values after a clear. See image below.

![mpandroidchart_realtime_clear_bug](https://cloud.githubusercontent.com/assets/6347879/6594624/213a0e28-c7e3-11e4-9e01-2a4989af1db3.png)

I've tried using `lineChart.setVisibleXRange(10)` and/or `lineChart.fitScreen()` but this didn't seem to do the trick.

My workaround was calling `lineChart.fitScreen()` **after** adding the first entry, because doing it after Clear (with 10 X values but no entries yet) didn't seem to work. Example code:
```java
private void addNewEntryToChart(float value) {
     // Add entry stuff

       if (lineDataSet.getEntryCount() == 1) {
            lineGraph.fitScreen();
        }
}
```
This way I was able to get the expected result (see bottomright image), but I think something regarding the viewport should be reset using a clear.
The width of the graph, see bottomleft image, isn't always the same. The longer I let my realtime data  receive the shorter the viewport seems to be, with a minimum of 1.

The downside of this workaround is that until the first new entry is added (the first new realtime data is recieved) the graph is displayed like the image on the bottomleft..

**Comment by PhilJay** [comment]
Allright that looks like an issue. So after clear is called when the x-axis has previously been restrained, it does not fully zoom out?

**Comment by PhilJay** [comment]
In my local commit I have just created a method called `clearValues()`, which does not remove the x-values from the chart, but only the added DataSets (and entries). Would that also help you out?

**Comment by PieterAelse** [comment]
The x-axis gets restrained to (the latest) 10 values.
I'm not sure if **not** removing the x-values is the solution because I also want them to be reset from 0 - 32 (eg, see image) to 0-10.

**Comment by PhilJay** [comment]
The image "expected" shows values from 0-10. So you want them to be reset from 22-32 to 0-10?
Or do you want to only display values 0-10, but without restraining (so only 10 x-values are in the graph)?

**Comment by PieterAelse** [comment]
Basically the "expected" image is exactly what I'm pursuing:
1) No (y-)values data present in the chart anymore  (`chart.clear()` or `chart.clearValues()` )
2) 0-10 x-values displayed  (so viewport starts at 0)

Currently 2) is archieved by adding x-values 0-10 to chart after `clear()`. But when using `clearValues()` I think I need to remove x-values > 10. Otherwise I can scroll horizontally beyond x=10, when there is no data available yet.
