### ISSUE TITLE
App crash when build in release mode with dexguard

### ISSUE THREAD

**Issue by thphuoc** [PhilJay/MPAndroidChart#4312]
Hi,
I download the example and try to build in release mode with dexguard protector but it crash after that with Exception is: Cannot inflater PieChart in xml file (something like that)

Please help me check, thanks https://dexprotector.com/

**Comment by almic** [comment]
Did you figure out what caused this?

**Comment by thphuoc** [comment]
Hi,
We have fixed this issue. We just upgrade compileSdkVersion=28 instead of 27
I don't know what the root cause is but this way can fix the issue.
Thanks for your help.

*_______________________*
*| Tran Huu Phuoc                  |*
*|------------------------------------  |*
*| Phone: (+84)-1666459432  |*
*| Skype: tranhuuphuoc88      | *
*`-------------------------------------'*
