### ISSUE TITLE
LineChart XAxis to bottom

### ISSUE THREAD

**Issue by anhth169** [PhilJay/MPAndroidChart#432]
hi PhilJay, 
 I have 2 questions:
- i want to set XAxis to bottom LineChart
- if i have 20 values of XAxis but i just want to display 10 values, other values will be display when i swipe to left, can i do?
Sorry, my English is so bad.

**Comment by PhilJay** [comment]
Yes. 

Use `chart.getXAxis().setPosition(XAxisPosition.BOTTOM)` to set the x-axis position. 

You can use `chart.setVisibleXRange(10)` to show only 10 values maximum.

**Comment by malmberg2** [comment]
what if i want to show 100 values on the screen, but want the data to keep updating with new values. and still only show me the latest 100 values.

**Comment by illiaNaumov** [comment]
@malmberg2 did you solve it? I have the same issue: need to load data on left swiping

**Comment by AnkitTorenzo** [comment]
can anyone tell me that how to do the same in V2.2.4
