### ISSUE TITLE
Jitter when the line chart slides

### ISSUE THREAD

**Issue by RommiPlus** [PhilJay/MPAndroidChart#4322]
**Summary**
Dear author, when i use mpandroid chart, and i find a question. I have searched stackoverflow and github issues but no one have question as me. 

I set Y Axis lable fixed and force to that label as follows:

```
leftAxis.removeAllLimitLines();
leftAxis.resetAxisMaximum();
leftAxis.resetAxisMinimum();
leftAxis.setLabelCount(5, true);
```

Then I set Y axis auto scale with data change, and i set x axis visible max range 12 potint and can drag but can't  scale.

```
lcWeight.setAutoScaleMinMaxEnabled(true);
lcWeight.setVisibleXRangeMaximum(12);

lcWeight.setTouchEnabled(true);
lcWeight.setDragEnabled(true);
lcWeight.setScaleXEnabled(false);
lcWeight.setScaleYEnabled(false);
lcWeight.setPinchZoom(false);
```

Finally, set x axis min and max data, and i add data and sort for it.

```
xAxis.setAxisMinimum(minDate);
xAxis.setAxisMaximum(maxDate);
xAxis.setGranularity(1);
xAxis.setLabelCount(mPresenter.getLabelCount());

Collections.sort(fatDataList, new EntryXComparator());
LineDataSet set1 = new LineDataSet(mPresenter.getFatDataList(), "");
ArrayList<ILineDataSet> dataSets = new ArrayList<>();
dataSets.add(set1);
lineData = new LineData(dataSets);
```

When i scroll chart, when data changed, it sometimes Jitter  as follows:
http://v.youku.com/v_show/id_XMzkzODc1MjUxNg==.html?spm=a2h3j.8428770.3416059.1

**Expected Behavior**
I want to scroll the chart but not Jitter when slides. But i have no idea to how to solve this. So, how can i solve this problem ? hope your reply.

**Device (please complete the following information):**
 - Android Version: 8.1.0
 - Library Version: 3.1.0-alpha

**Comment by xuziqiaaa** [comment]
我也遇到了这个问题，都这么久了，应该都解决了吧，没解决可以参考一下。
我把BarLineChartBase类中的calculateOffsets()方法中的：
   // offsets for y-labels
            if (mAxisLeft.needsOffset()) {
                offsetLeft += mAxisLeft.getRequiredWidthSpace(mAxisRendererLeft
                        .getPaintAxisLabels());
            }
            
            if (mAxisRight.needsOffset()) {
                offsetRight += mAxisRight.getRequiredWidthSpace(mAxisRendererRight
                        .getPaintAxisLabels());
            }

改成了：

 // offsets for y-labels
            if (mAxisLeft.needsOffset()) {
                offsetLeft += mAxisLeft.getRequiredWidthSpace(mAxisRendererLeft
                        .getPaintAxisLabels());
            }
 
            if (mAxisRight.needsOffset()) {
                offsetRight += 120f;
            }

就好使了 = =，那个值是右间距

**Comment by Goopher** [comment]
@xuziqiaaa 's answer works a little bit, but not fully.

I have the same issue which seems to arise from changing lengths of the y labels. There's no smooth transition in that whatsoever, meaning that when the autoscale tries to change the y labels 30 times a second, this jitter appears.

No idea how to fix this tho.

**Comment by RommiPlus** [comment]
Finally，I solved this problem by custom y axis calculation. If you want to fix it, you can try this method.

**Comment by Goopher** [comment]
@RommiPlus, do you maybe have a small code snippet for inspiration?
