### ISSUE TITLE
BarChart: The space of removed right axis is not used

### ISSUE THREAD

**Issue by jonescx** [PhilJay/MPAndroidChart#433]
Hi,

The right axis part is removed but the space doesn't be used by the chart. 
How could I make the chart to extend to the right axis area that is highlight by a red rectangle? 
Thanks.

![default](https://cloud.githubusercontent.com/assets/6426584/6614613/1e23fed4-c8d7-11e4-84e6-1567332ad532.png)

Here is my bar chart setup code.
```java
        mChart.setDescription("");
        mChart.setDrawGridBackground(false);
        mChart.setDrawBarShadow(false);
        mChart.setPinchZoom(false);
        mChart.setDoubleTapToZoomEnabled(false);
        mChart.animateY(3000); // animate vertical 3000 milliseconds

        XAxis xAxis = mChart.getXAxis();
        xAxis.setDrawGridLines(false);
        xAxis.setDrawLabels(true);
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setTextColor(0xFFFFFFFF);

        YAxis leftAxis = mChart.getAxisLeft();
        leftAxis.setTextColor(0xFFFFFFFF);
        leftAxis.setGridColor(0xFFAAAAAA);
        leftAxis.setDrawAxisLine(false);

        YAxis rightAxis = mChart.getAxisRight();
        rightAxis.setDrawLabels(false);
        rightAxis.setDrawAxisLine(false);

**Comment by PhilJay** [comment]
Call `rightAxis.setEnabled(false)`

**Comment by jonescx** [comment]
Thank you very much for the quick reply.

**Comment by troy21688** [comment]
If I create a horizontal bar chart, are these axises inverted? In other words, do I have to set up YAxis xAxis = Chart.getAxisLeft() since a horizontal chart is inverted?
