### ISSUE TITLE
MarkerView offsets

### ISSUE THREAD

**Issue by svasic** [PhilJay/MPAndroidChart#435]
Hi Phil, 
This may or may not be a bug, but it certainly is not expected behaviour. Methods getXOffset() and getYOffset() are never called, instead member variables are used in code. On your wiki documentation you overrided those two methods and wrote a comment to show what should be expected behaviour. I'm using workaround and calling setOffset(getXOffset(), getYOffset()) in constructor of my extended MarkerView. 
Also you can update wiki documentation and change the type of those two methods from int to float.
It's not a big deal, just a small observation and a remark.

**Comment by PhilJay** [comment]
Are you using the latest version of the library? They are called in my code :-)

**Comment by svasic** [comment]
:) Yup, you're right ... we were not using the latest version.
