### ISSUE TITLE
How to hide the last value on the x-axis ?

### ISSUE THREAD

**Issue by gomeskingsley** [PhilJay/MPAndroidChart#436]
Hi Phil,

I have 5 x-axis values which are displayed on the graph. I want to hide the last value which is displayed on the graph. How can I achieve this behavior ? 
 
Here is my graph :
![graph](https://cloud.githubusercontent.com/assets/11442284/6634645/5091458e-c981-11e4-986e-1b3c5d26777a.png)

Is there any way I can hide the last value ,so that the graph would lilke : 
![edited_graph](https://cloud.githubusercontent.com/assets/11442284/6634663/9f8250a2-c981-11e4-983f-cdb9d0236c28.jpeg)

**Comment by PhilJay** [comment]
That's not possible by default. You will have to modify the library to achieve that.

Regards,
Phil
