### ISSUE TITLE
Fully disable zooming

### ISSUE THREAD

**Issue by RubyDerBoss** [PhilJay/MPAndroidChart#438]
Hi, great library!
I've ran into a problem: I have a bar chart, but I don't want it to be zoomable. 
I set both methods
```java 
chart.setDoubleTapToZoomEnabled(false);
chart.setPinchZoom(false);
```
But it is still zoomable with pinch.
Any thoughts on this?

Library Version 2.0.7
Android 5.0.2

**Comment by PhilJay** [comment]
Call `chart.setScaleEnabled(...)`. You can also find this in the documentation.

**Comment by shubhamjhandei** [comment]
Hi, 

I have disable zoom but it is also disabling  onChartGestureStart Callback for OnChartGestureListener and disabling draggable Highlighting feature. 

Is it desired behaviour?

**Comment by Jhandei** [comment]
Hi, 

Does disabling Zoom also disable Highlighting Per drag?

**Comment by minnanwang** [comment]
Disable all zooming:
chart.setScaleEnabled(false)

**Comment by RibinHaridas** [comment]
chart.setTouchEnabled(false);

**Comment by paragyogi** [comment]
Ribin this works for chart inner data. But on click my chart position changes

**Comment by AhmadullahSaikat** [comment]
mChart.setPinchZoom(false);
        mChart.setDoubleTapToZoomEnabled(false);

**Comment by Nasiralityagi** [comment]
mChart.setScaleEnabled(false);//disbale all zoom
mChart.getLegend().setEnabled(false);//hide chart highlight data
