### ISSUE TITLE
NegativeArraySizeException in 3.1.0-alpha

### ISSUE THREAD

**Issue by hannesa2** [PhilJay/MPAndroidChart#4380]
I run your recent version (e.g. 3.1.0-alpha) and  I still see this in PlayStore Pre-Launch report

> java.lang.NegativeArraySizeException: -702
> 	at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:178)
> 	at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:549)
> 	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:278)
> 	at android.view.View.draw(View.java:17235)

That means 3.1.0 has a huge rework https://github.com/PhilJay/MPAndroidChart/commit/d67ea481af1e8528c617dfd404d0c7827b0134b2 but the main issue was not solved

**Comment by hannesa2** [comment]
In the meantime I use my fork with several bug fixes, based on 3.0.x 
This fork doesn't crash 
`implementation 'com.github.hannesa2:MPAndroidChart:3.0.7'`

**Comment by ArcherEmiya05** [comment]
Where is the built in ValueFormatter class on this fork?

**Comment by hannesa2** [comment]
In the upstream the renamed it 
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/3314607/109860640-b0ce1d00-7c5e-11eb-9ea5-b1ae659844ce.png">
