### ISSUE TITLE
Fill LineChart sometimes not working

### ISSUE THREAD

**Issue by warmax** [PhilJay/MPAndroidChart#441]
With last version 2.0.8 sometimes the chart is not filled. When I revert back to 2.0.7 it works again.

set1.setDrawFilled(true);
set1.setFillColor(getResources().getColor(R.color.red_down));
mChart.setData(data)
mChart.invalidate();

regards

**Comment by PhilJay** [comment]
Could you describe the situation in more detail?
Which setup (which data) causes the chart not to be filled correctly?
Could you provide a screenshot of what it looks like?

**Comment by warmax** [comment]
Data is coming from a financial api so it's changing quite a bit.... some charts are just fine but others are not filled (I haven't been able to find a pattern). I attach a screenshot with v2.0.7 and v2.0.8 on the same chart:

![mp207](https://cloud.githubusercontent.com/assets/9325874/6699637/3f3c3498-cd04-11e4-922b-53807417531b.png)

![mp_208](https://cloud.githubusercontent.com/assets/9325874/6699640/442e3c80-cd04-11e4-837f-0a36c3ec00ba.png)

If you have any ideas of how can I help, please let me know.

**Comment by PhilJay** [comment]
Okay so the whole area is simply not filled. That is quite weird.
How many values are you plotting?

If the issue occurs, could you tell me if you can find the following warning message in your logcat: "Path too large to be rendered into a texture"

Thank you!

**Comment by warmax** [comment]
Yes I'm getting that error in logcat.

491 values -> not working
515 values -> not working
1545 values -> not working
128 values ->working 
261 values ->working
781 values -> working, strange??

**Comment by xu6148152** [comment]
may be you can debug the view which can not be working well using your data, and this way may solve this problem fast.

**Comment by PhilJay** [comment]
Alright. Does the issue occur instantly, or only when zooming in?

**Comment by PhilJay** [comment]
Could you try the latest commit and see if you are still having the issue?

**Comment by warmax** [comment]
Hi phil, just checked with last commit and it worked fine! 

Thanks

**Comment by PhilJay** [comment]
Good to know, I thought I might have fixed it!

**Comment by gray419** [comment]
I am still having this exact issue, it was working in 2.0.7, just updated my gradle build to 2.0.8 today and got the irregular fill behavior:

These are two diff charts with fill working and not working:
![screen shot 2015-03-20 at 2 35 40 pm](https://cloud.githubusercontent.com/assets/3689237/6758475/d8156674-cf0e-11e4-86a0-cdf85b36881a.png)
```java
LineDataSet priceData = new LineDataSet(yVal, "Price");
        priceData.setLineWidth(2f);
        priceData.setDrawFilled(true);
        priceData.setColor(getResources().getColor(R.color.positive_green_line));
        priceData.setFillColor(getResources().getColor(R.color.positive_green_fill));
        priceData.setDrawCircles(false);
        priceData.setDrawValues(false);

        ArrayList<LineDataSet> dataSets = new ArrayList<>();
        dataSets.add(priceData);

        LineData data = new LineData(xVal, dataSets);
        lineChart.getAxisLeft().setStartAtZero(false);
        lineChart.setData(data);
```
![screen shot 2015-03-20 at 2 35 57 pm](https://cloud.githubusercontent.com/assets/3689237/6758476/d81d52da-cf0e-11e4-9980-d03419b80b4a.png)
```java
LineDataSet sentimentData = new LineDataSet(yVal, "Sentiment");
        sentimentData.setLineWidth(0f);
        sentimentData.setDrawFilled(true);
        sentimentData.setFillColor(getResources().getColor(R.color.stock_up_green));
        sentimentData.setColor(getResources().getColor(R.color.stock_up_green));
        sentimentData.setDrawCircles(false);
        sentimentData.setDrawValues(false);

        ArrayList<LineDataSet> dataSets = new ArrayList<>();
        dataSets.add(sentimentData);

        LineData data = new LineData(xVal, dataSets);

        lineChart.getAxisLeft().setAxisMaxValue(100);
        lineChart.setData(data);
```

**Comment by PhilJay** [comment]
Have you tried the latest commit?
There is no release-version with this fix yet!

**Comment by MarcSalvat** [comment]
This bug is back in the main branch.

Had to change:
    c.drawPath(cubicPath, mRenderPaint);
to:
    mBitmapCanvas.drawPath(cubicPath, mRenderPaint);

regards

**Comment by gray419** [comment]
Just upgraded to 2.1.0 and am still experiencing this bug

**Comment by MGaetan89** [comment]
I am facing this issue too.
The chart is correctly filled when first drawn, but when I start to zoom, it is no longer filled and I only have the line.

As asked in a previous commit, I do have the following in my log:
```console
Path too large to be rendered into a texture
```

Any idea @PhilJay ?

**Comment by adammach** [comment]
I can see in logs (2.1.0): "Shape too large to be rendered into a texture"

**Comment by PhilJay** [comment]
Are you all using cubic lines?

**Comment by MGaetan89** [comment]
I'm not (I am using the default configuration).
But if I call `lineDataSet.setDrawCubic(true)`, then the chart is filled even when zoomed/dragged.

**Comment by adammach** [comment]
@PhilJay No I'm not using neither cubic nor circles.

**Comment by PhilJay** [comment]
Okay good then I can narrow down the issue to normal (straight) lines, I will have a look at it.

**Comment by ayltai** [comment]
If the chart dimension is large (200dp x 200dp) then all line charts (normal, straight lines) fail (instantly) to fill the area. If the chart dimension is small (40dp x 100dp) then some will fail and some will work. I got the same result every time.

**Comment by fiftycy** [comment]
@PhilJay Why this issue is closed? The problem still exist. Excellent work btw.

**Comment by tinsukE** [comment]
Can you guys check if this still happens with the latest commit from https://github.com/tinsukE/MPAndroidChart?

**Comment by adhieresthenes** [comment]
Hi bro Phil, im trying use libr of LineChart. eg: mChart = new LineChart(this);
After compiling then it works, but i've got a small of View linechart. The question is.. how can i change size of view chart ? Many Thanks
![screenshot_2016-03-24-19-18-07](https://cloud.githubusercontent.com/assets/8815474/14016873/910ca994-f1f5-11e5-9251-a5687689c5cb.png)
from my device?

**Comment by semirke** [comment]
Hi, 
  I believe it's caused for me because I used Float.NaN for missing values. 
  Can the fill work with NaNs?

Thanks
Semir

**Comment by semirke** [comment]
Hi, 
 I can defenitely verify that NaNs cause the missing area shading. As soon as every NaN is out of the screen (zoom/scroll) the shading returns. 

Bests, 
Semir

**Comment by noberasco** [comment]
I'll chime in with my own observations.

The issue is bigger than this.
If the portion of LineChart visible on screen starts with a NaN, than the whole chart won't be visible until you move/zoom it so that it starts with a valid number.

**Comment by noberasco** [comment]
Here is a quick fix for my chart-not-drawing issue:
#2878

**Comment by AravindhJahan** [comment]
i need a line chart became a curve like this
![img-20170417-wa0014 1](https://cloud.githubusercontent.com/assets/23451622/25081726/b034e042-2369-11e7-97cb-8224e9fa44e5.jpg)
