### ISSUE TITLE
minifyEnabled true = Animation does not work

### ISSUE THREAD

**Issue by CTNCardoso** [PhilJay/MPAndroidChart#443]
The animation does not work when enabled this option.

buildTypes {

        debug {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-project.txt'
        }
}

**Comment by MarcSalvat** [comment]
I wrote a workaround here: https://github.com/PhilJay/MPAndroidChart/issues/348#issuecomment-77280351

**Comment by CTNCardoso** [comment]
Thanks!
