### ISSUE TITLE
Pie Chart: set equal slice space from center to end of the arc

### ISSUE THREAD

**Issue by shahzebkhowaja** [PhilJay/MPAndroidChart#444]
Hi Phil,

How I can achieve equal slice space from center to end of the each arc on pie chart.
if you see the sample the arc is drawn properly but the slice spaces from center are not equal as end.

any possible solution ?

Thanks,

**Comment by spunja** [comment]
Has this enhancement been added??

**Comment by Parmenione** [comment]
Any news?

**Comment by MGaetan89** [comment]
The commit that added it is just above and is part of the latest version.

**Comment by Parmenione** [comment]
But with 2 elements in data set and draw hole disabled this does not work.

**Comment by MGaetan89** [comment]
If it does not already exists, open an issue for that, with maybe a screenshot to explain what you have/what you want.
