### ISSUE TITLE
Automatically PieChart Highlight in onCreate

### ISSUE THREAD

**Issue by Ponja94** [PhilJay/MPAndroidChart#4447]
I researched a lot here about how I leave a piece of PieChart selected when I call onCreate.

I would like to start the application and the 25% part in pieChart is already selected. But only when I click it is selected.

I also tried to read and apply the Hightlight documentation  [https://github.com/PhilJay/MPAndroidChart/wiki/Highlighting](url)

and every time I try to use **pieChart.highlightValue(float x, int dataSetIndex, boolean callListener)** the app does not open

![whatsapp image 2019-03-07 at 15 57 52](https://user-images.githubusercontent.com/47600437/53981817-28115a80-40f2-11e9-91c8-51bdc70e3854.jpeg)

**Comment by alierdogan7** [comment]
```
PieEntry entry = new PieEntry(value, label);        
pieChart.highlightValue(0, entry.getY(), dataSetIndex);
```

```highlightValue``` first parameter should always be 0, and the second is the Y value of that entry, and last one is dataSetIndex which will be 0 if you use only one dataset in your plot.
