### ISSUE TITLE
can I set Margin-Left to the first XAxis? the label is clipped

### ISSUE THREAD

**Issue by xu6148152** [PhilJay/MPAndroidChart#445]
thx

**Comment by PhilJay** [comment]
call `setAvoidFirstLastClipping(...)` on the axis

**Comment by xu6148152** [comment]
I call setAvoidFirstLastClipping, but it can not working.thank you

**Comment by codezjx** [comment]
Don't use setAvoidFirstLastClipping. Use  clipChildren & clipToPadding in your container layout. See:http://stackoverflow.com/questions/27847583/mpandroidchart-legend-labels-are-being-cut-off
