### ISSUE TITLE
draw different fill color when data upper upper limit, within limit and below lower limit

### ISSUE THREAD

**Issue by 2666fff** [PhilJay/MPAndroidChart#4473]
i had made some research about this issue in this git and stackoverflow didnt find out answers.

the question im facing is draw different fill color when data is above upper limit, inside two limits and below lower limit.

some thing like this 
![image](https://user-images.githubusercontent.com/7792682/55312974-4e2fdd80-5499-11e9-83aa-bbddf64753d6.png)
when data above upper limit fill color with yellow, inside limit fill with green, below lower limit fill with red.

is there anyway to acheive this? if not im requesting feature enhancement now

**Comment by 2666fff** [comment]
![image](https://user-images.githubusercontent.com/7792682/56076848-17968300-5e08-11e9-9f70-3df9e68557b6.png)
I had done this by my self but code is kind of messy, contact me if any one want this.

**Comment by s3hengwu** [comment]
I have the same problem, but I'm on the Y-axis. Ask for help.

**Comment by antondityativ** [comment]
the same problem

**Comment by branyt** [comment]
@2666fff  email 13646716305@163.com thank you
