### ISSUE TITLE
Line chart shows less data

### ISSUE THREAD

**Issue by yangtuhua** [PhilJay/MPAndroidChart#4478]
how can I do this like image pic2 as below, not like pic1, when there are less data in the chart

![image](https://user-images.githubusercontent.com/14036085/55450882-48eea200-5603-11e9-819c-9a97bb847bbd.png)

**Comment by yangtuhua** [comment]
if you have any solution, please give a hand, thanks a lot.

**Comment by zhaoyuehai** [comment]
Can I help you?  18511073583  Email:zhaoyuehai5282@163.com

**Comment by yangtuhua** [comment]
@zhaoyuehai Thanks for your kindness.
