### ISSUE TITLE
CombinedChart multiple BarDataSet

### ISSUE THREAD

**Issue by adelumban** [PhilJay/MPAndroidChart#449]
Hi @PhilJay 

I'm Trying to use combine chart with multiple bars and line graph 
I was expecting to get similar result with the image below, where the multiple bar in one month with line graph on it.

![multiplebar with linegraph](https://cloud.githubusercontent.com/assets/1313099/6726377/66d88f62-ce51-11e4-95f8-b05e7871de89.png)

But when I was able to render it shows me the image below

![device_multiplebar_line](https://cloud.githubusercontent.com/assets/1313099/6726491/f2936daa-ce52-11e4-8143-22f007730731.png)

Is there a way to do this correctly? thank you in advance and thank you for this wonderful library.

**Comment by PhilJay** [comment]
Yep, grouped bar-datasets are not yet supported for combined charts. I'm working on a solution.

**Comment by trungnguyen1791** [comment]
I have same problems. Can u get a solution for this ? @PhilJay

**Comment by irkasper** [comment]
i have same problem too
please help me 
can you say when this bug will be fixed?

**Comment by liuxuan30** [comment]
Any update? iOS portion has this request too.

**Comment by genielabs** [comment]
Any news or details about how to fix this? Thanks for this great library.

**Comment by joshfriend** [comment]
There is a fix in progress for the iOS charts version: danielgindi/ios-charts#269

@liuxuan30 made a commit to that branch yesterday and seems to be saying that it is mostly complete. I suspect that porting it to Java wouldn't be terribly difficult.

**Comment by liuxuan30** [comment]
@joshfriend It has been a while since I made the PR :-)  and being used in my project so far.

My work proposed one solution, and may not be the best, because it solved my problem but also introduced more complexity. I just want to start a discussion about it, because multiple bars support seems important to lots of people. 

Porting is absolutely not difficult, the idea is quite straightforward. Only what's the best way to do it matters.

**Comment by muhammad-naderi** [comment]
@PhilJay ...
Any update on this bug ?!

**Comment by Marconsou** [comment]
Any solution or workaround found? Any update?

**Comment by Aeonia** [comment]
Was this issue fixed?

**Comment by AndreasIgelCC** [comment]
Not working yet. In iOS Charts they are working for a solution (https://github.com/danielgindi/ios-charts/pull/269). What about MPAndroidChart? Does anyone have a solution yet?

**Comment by PhilJay** [comment]
I am on this issue, it's on top of my list.
However, it's quite complex and needs some design beforehand.

**Comment by liuxuan30** [comment]
@PhilJay how do you want to do it? Having reviewed my PR yet?

**Comment by aftabahmed1286** [comment]
@PhilJay Can you share some status on this?

**Comment by PhilJay** [comment]
The new v3.0.0 of the library which will be released within the next few weeks will include this feature, so I will close this issue now.

Best regards,
Phil

**Comment by jitsm555** [comment]
@PhilJay : I also don't know how to generate above screenshot like combine chart. Please help me its urgent.

**Comment by jitsm555** [comment]
@meshileya : Have you found any solution for combined graph? I also needed it.
