### ISSUE TITLE
Release POM file not well maintained (v3.1.0)

### ISSUE THREAD

**Issue by AlexanderEggers** [PhilJay/MPAndroidChart#4492]
I am using a license library to generate a json based on the distributed POM file. All looks well except the MPAndroidChart library. Only the library name is set and nothing else - no license, no owner. Is it possible that someone reviews the current POM creation to improve this in the future?

**Comment by pranavvij** [comment]
Any updates on the same. Even I am parsing through the pom file and don't file license meta data in the file itself and the project uses an abandoned library android-maven-gradle-plugin for maven .

**Comment by estrnod** [comment]
+1.  I have opened an issue on the license library that I use, to hopefully allow for manual entry of the info in case it can't be picked up from a dependency pom, but it'd be helpful if you could make it available at your end.  
https://github.com/jk1/Gradle-License-Report/issues/154 (and the linked one also)

**Comment by estrnod** [comment]
BTW, I do love your library :-)
