### ISSUE TITLE
BUG:PieChart .setTouchEnabled(false) don't work

### ISSUE THREAD

**Issue by Tanlet** [PhilJay/MPAndroidChart#45]
Solve:PieChart.class
    @Override
    public boolean onTouchEvent(MotionEvent event) {

```
    // use the piecharts own listener
    if (mTouchEnabled) {
        return mListener.onTouch(this, event);
    }
    return super.onTouchEvent(event);
}
```

**Comment by smejkal** [comment]
Currently it's not possible to use a context menu for a Pie Chart. onTouchEvent doesn't call the super method. You have provided a comment: "use the pie- and radarchart listener own listener". Why is this suppressed? If I copy the onTouchEvent function from the BarChartBase, then the context menu works.
