### ISSUE TITLE
Horizontal Bar Chart: setInverted-Method makes bars invisible

### ISSUE THREAD

**Issue by crimpphantom** [PhilJay/MPAndroidChart#450]
Tested with the MPAndroidChart Example-App:

I want to inverted the bars. For this a add following code in the onCreate-method of HorizontalBarCharActivity:
yl.setInverted(true);

The y-labels are inverted, but the bars disappear.
![error](https://cloud.githubusercontent.com/assets/11516859/6728261/fa399716-ce28-11e4-9df9-c8dfc3814326.png)

**Comment by PhilJay** [comment]
Looks like a bug, I'll check it out.

**Comment by PhilJay** [comment]
I have done some work on it and it should now display correctly.
The only thing not working correctly yet is the dragging / panning. It's also inverted at the time.

**Comment by PhilJay** [comment]
This should be fixed since the latest commit!

**Comment by crimpphantom** [comment]
Hi Phil,

i see now (Version 2.0.9) that the bars are inverted (from right to left) and i understand why, but is this useful? Imho for horizontal charts the y-Axis (in the example Jan-Dez) should be inverted, not the x-Axis! So the look in Version 2.0.8 was for me okay and the only error was the invisible bars...

Greetings,
Frank

**Comment by PhilJay** [comment]
I dont know, but it's the only thing that makes sense.
If you want to invert the x-axis values (Jan-Dec), simply add them in a different order.
