### ISSUE TITLE
timeline chart scrolling to the end of the chart

### ISSUE THREAD

**Issue by zipon** [PhilJay/MPAndroidChart#451]
Hi Phil

I have the same problem as described by issue "Viewport implementation #14". I have tried to change to the new way with moveViewToX(indexX), but if I have used setVisibleXRange(value) or setScaleMinima() I can't get to the last value. I saw that centerViewPort(xIndex, value) is no longer supported. I might have missed something trivial, but would appreciate your help. I'm using v2.0.8

**Comment by PhilJay** [comment]
Since the latest commit, this should work.

Also have a look at the documentation: https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport

**Comment by zipon** [comment]
Thanks mate.
