### ISSUE TITLE
Stacked BarChart with different colors for each individual bars block

### ISSUE THREAD

**Issue by haldunerbay** [PhilJay/MPAndroidChart#4511]
Hello,
I want to differentiate colors for each individuals bars' block.

For example, my first bar for Monday that I have 3 different activities and second bar for Tuesday that have 3 different activities from monday's activities. So, each activity has different color. 

Totally, I have 6 different activities which have different colors that done in Monday and Tuesday separately with different order.

I can draw a stacked barchart with same activities and each activities have different color.However, when activities change or order of activities change, color of block for bar doesn't change.

<img width="711" alt="Ekran Resmi 2019-04-27 13 20 47" src="https://user-images.githubusercontent.com/49325040/56848254-4d029c80-68ef-11e9-9f9f-0b66f3adc6cf.png">

According to this example, directors represent days and genres are activities.
Is it possible to draw with using BarChart in MPAndroidChart ?
@PhilJay

**Comment by zlrab** [comment]
barDataSet.addEntry(0,new float[]{100,200,300,400,500});
barDataSet.setColors(ColorTeample.JOYFUL_COLORS)

**Comment by kbeltrandev** [comment]
Hello, how did you solve it? Thank you

**Comment by DavidSilvain** [comment]
Hello,

Did you find a solution ?
I'm looking to do the same.
THANKS
