### ISSUE TITLE
mDrawBarShadow is true by default

### ISSUE THREAD

**Issue by Maragues** [PhilJay/MPAndroidChart#453]
By default, this draws a grey area behind every bar, which at least for me is unexpected. 

Plus, according to the javadoc *Enabling this will reduce performance by about 50%*, which means that by default there's a 50% performance penalty.

Is this working as intended or is it a bug?

**Comment by PhilJay** [comment]
I really would like to add you to the contributors list of this library :-) Unfortunately I could only merge your latest PR on CL.
Please get my latest commit, and make a PR that changes this to false.

It's actually really bad that this is set to true by default.

Best regards, 
Phil

**Comment by Maragues** [comment]
See PR https://github.com/PhilJay/MPAndroidChart/pull/454

My contribution has been really minor, but I'm glad to contribute to cool projects that I use
