### ISSUE TITLE
BarChart animated scroll problem in production

### ISSUE THREAD

**Issue by edwinkapkei** [PhilJay/MPAndroidChart#4549]
I have implemented bar chart on my android app and the chart scrolls when I run in debug mode but when I generate a release APK and run the app the chart does not scroll.

I have implemented the scroll with animation feature for bar charts with  a lot of data as indicated on the documentation(Link to source: https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport)

The code snippet for scrolling with animation:

`barchart.moveViewToAnimated(10, barchart.getData().getYMax(), YAxis.AxisDependency.RIGHT, 2500);`

The expectation would be the bar chart scrolls on both debug and production environment but somehow the chart does not scroll in production.

Any assistance on how to figure out the problem will be greatly appreciated.

**Comment by marinantonio** [comment]
Add this to your proguard-rules.pro
-keep class com.github.mikephil.charting.** { *; }

Source:
https://github.com/PhilJay/MPAndroidChart/wiki/Proguard

**Comment by edwinkapkei** [comment]
Why didn't I think of that 🤦
Thank you it worked.
