### ISSUE TITLE
LineChart lines get cut off at values of Y-Axis Minimum

### ISSUE THREAD

**Issue by DreamerLeon** [PhilJay/MPAndroidChart#4564]
Lines width is 2dp, lines bottom get cut off at Y-Axis values of minimum

**Comment by qiangzengli** [comment]
you dont set the minValue   ,it is OK

**Comment by qiangzengli** [comment]
leftAxis.setAxisMinimum(0f);      detele  this line

**Comment by DreamerLeon** [comment]
> leftAxis.setAxisMinimum(0f); detele this line

**Comment by DreamerLeon** [comment]
> leftAxis.setAxisMinimum(0f); detele this line

Thanks
