### ISSUE TITLE
Feature Request : Add `index` parameter at #ValueFormatter.getBarStackedLabel

### ISSUE THREAD

**Issue by koji-1009** [PhilJay/MPAndroidChart#4602]
**Is your feature request related to a problem? Please describe.**
Sometimes, I can't draw label correct. So, I want to get index parameter.

Case 1. [5, 5, 0]
[StackedValueFormatter](https://github.com/PhilJay/MPAndroidChart/blob/v3.1.0/MPChartLib/src/main/java/com/github/mikephil/charting/formatter/StackedValueFormatter.java) uses a following logic.

```java
// find out if we are on top of the stack
if (vals[vals.length - 1] == value) {

    // return the "sum" across all stack values
    return mFormat.format(entry.getY()) + mSuffix;
} else {
    return ""; // return empty
}
```

So, the painter paint the last value's position (in this case 0).
If the value is 0, the value's `y` is 0. Therefore, the `Stacked Label` is drawn above a non-zero bar. 
ref [BarChartRender](https://github.com/PhilJay/MPAndroidChart/blob/v3.1.0/MPChartLib/src/main/java/com/github/mikephil/charting/renderer/BarChartRenderer.java#L378)

Case 2. [0, 0, 0]

To avoid Case 1's error, I try following code.

```kotlin
override fun getBarStackedLabel(value: Float, entry: BarEntry?): String {
    if (entry == null || entry.yVals.isEmpty()) return ""

    val yVals = entry.yVals
    val position = yVals.indexOfLast { it > 0 }
    return if (value == yVals[position] ) {
        MyProjectValueFormatter.format(value)
    } else {
        ""
    }
}
```

In most cases there is no problem. But in the case of [0, 0, 0], I draw "0" 3 times. (I want to draw only one time...)
If I will get yVal's index, I can draw "correct" top position!

**Describe the solution you'd like**
Add `index` parameter at #ValueFormatter.getBarStackedLabel

**Describe alternatives you've considered**
Sorry, I couldn't find it...

Maybe this is related to the following issues.
#3542 #4082

**Comment by shubhampatel-slicepay** [comment]
@koji-1009 this has been really helpful a lot for me. However, for the safe-check please add ->

```
override fun getBarStackedLabel(value: Float, entry: BarEntry?): String {
       if (!mDrawWholeStack) {
            entry?.yVals?.let { yStackValues ->
                val position = yStackValues.indexOfLast { it > 0 }
                return if (position >= 0) {
                    if (value == yStackValues[position]) {
                        mFormat?.format(entry.y.toDouble())
                    } else {
                        ""
                    }
                } else {
                    mFormat?.format(0.0) _// Here's what for it's over-riding in 2nd case i.e. (0, 0, 0)_
                }
            } ?: return ""
        }
        return mFormat?.format(value.toDouble())
    }
```

**Comment by shubhampatel-slicepay** [comment]
@koji-1009 this has been really helpful a lot. However for safe case while using indexOfLast, please add this ->

```
override fun getBarStackedLabel(value: Float, entry: BarEntry?): String {
       if (!mDrawWholeStack) {
            entry?.yVals?.let { yStackValues ->
                val position = yStackValues.indexOfLast { it > 0 }
                return if (position >= 0) {
                    if (value == yStackValues[position]) {
                        mFormat?.format(entry.y.toDouble())
                    } else {
                        ""
                    }
                } else {
                    mFormat?.format(0.0) **// Here's what for it's over-riding in 2nd case i.e. (0, 0, 0)**
                }
            } ?: return ""
        }
        return mFormat?.format(value.toDouble())
    } 
```
