### ISSUE TITLE
MyXAxisValueFormatter cannot be converted to ValueFormatter

### ISSUE THREAD

**Issue by sandiumar** [PhilJay/MPAndroidChart#4605]
Hello, first I say thank you for make this libary because it's very useful

Back to Topic

I have a problem to custom Label on X axis line from 1-7 to "Jan - Aug", I have followed your documention about The AxisValueFormatter interface on your documentation like this

![bug1](https://user-images.githubusercontent.com/13393522/60771201-6e151400-a10e-11e9-932e-2619cff0d97a.PNG)
![bug2](https://user-images.githubusercontent.com/13393522/60771202-6eadaa80-a10e-11e9-8c86-5567a0da9e3f.PNG)

When I try to test it always show message = MyXAxisValueFormatter cannot be converted to ValueFormatter

Do you have any solutions ? Thank You

**Comment by sandiumar** [comment]
After i research carefully, it looks like the different of library version. So, I downgrade the library from v3.1.0 to v3.0.3

But, when I use extends method on ValueFormatter in  v3.1.0 it should be change the X Axis label name logically

**Comment by max696-gromsky** [comment]
> After i research carefully, it looks like the different of library version. So, I downgrade the library from v3.1.0 to v3.0.3
> 
> But, when I use extends method on ValueFormatter in v3.1.0 it should be change the X Axis label name logically

Thank you for solution, i have same problem. Downgrade helps me!

**Comment by andre719mv** [comment]
BTW it`s easy to migrate your formatter to extend ValueFormatter class. Look at DefaultValueFormatter class or my example: 
![Screen Shot 2019-10-22 at 11 27 36 PM](https://user-images.githubusercontent.com/22563994/67329687-de13a280-f523-11e9-8ebd-cf633d1f69df.png)
