### ISSUE TITLE
64 Bit support - x86_64

### ISSUE THREAD

**Issue by fredydoss** [PhilJay/MPAndroidChart#4608]
I use MPChart in my application for around 4 years now. 
I get a warning from google saying that my application does not support 64 bit. 

When I analyze the apk I find that the x86_64 folder is missing. I guess this is a missing .so file. 

![Screenshot 2019-07-11 at 15 12 34](https://user-images.githubusercontent.com/2931755/61053959-da359780-a3ee-11e9-9bf5-36b13b1fe3ac.png)

Google will not support the application after August 1 2019.

What would be the solution to fix this ?

**Comment by ismailtosun** [comment]
+1

**Comment by vvelmurugan** [comment]
@fredydoss  how are you sure that the warning is only because of this library? did you remove the library and check?

**Comment by fredydoss** [comment]
I think its not coming from this library. 
Thanks for the support
