### ISSUE TITLE
How can I set the first XAxis that can be away some distance from the left side of chart

### ISSUE THREAD

**Issue by xu6148152** [PhilJay/MPAndroidChart#461]
and last XAxis is away some distance from the right side of chart?

I want to choose place where I want to draw the first xaxis

Thank you very much

like this

![alt text](https://dl.dropboxusercontent.com/u/1599662/line.png)
or
![alt text](https://dl.dropboxusercontent.com/u/4904447/pnchart_legend_1.png)

**Comment by PhilJay** [comment]
Simply add an "" to the beginning and end of your x-values array and increase the xindex by one for each entry.

**Comment by xu6148152** [comment]
thank you very much
