### ISSUE TITLE
Overlapping Text - Horizontal Bar Chart

### ISSUE THREAD

**Issue by palaniramkumar** [PhilJay/MPAndroidChart#462]
How to resolve this overlapping text between x and y?

![image](https://cloud.githubusercontent.com/assets/591310/6768477/fb68b97a-d092-11e4-86ae-5a6ffa756cbe.png)

Code Snippet:

        hChart.setDrawBarShadow(false);

        hChart.setDrawValueAboveBar(true);
        hChart.setDescription("");
        // if more than 60 entries are displayed in the chart, no values will be
        // drawn
        hChart.setMaxVisibleValueCount(60);

        // scaling can now only be done on x- and y-axis separately
        hChart.setPinchZoom(false);
        hChart.setDrawGridBackground(false);

        XAxis xl = hChart.getXAxis();
        xl.setPosition(XAxis.XAxisPosition.TOP);
        xl.setDrawAxisLine(false);
        xl.setDrawGridLines(false);
        xl.setAdjustXLabels(true);

        

        YAxis yl = hChart.getAxisLeft();
        yl.setDrawAxisLine(false);
        yl.setDrawGridLines(false);
        yl.setDrawLabels(false);
        yl.setLabelCount(0);

        YAxis yr = hChart.getAxisRight();
        yr.setDrawAxisLine(false);
        yr.setDrawGridLines(false);
        yr.setDrawLabels(false);
        yr.setLabelCount(0);

        bill_expense_data();
        hChart.setScaleXEnabled(true);
        hChart.animateY(2500);

Thanks!

**Comment by PhilJay** [comment]
There is not really much to fix here. What you are asking is not supported yet.
You are gonna have to implement some kind of workaround.

Best regards,
Phil

**Comment by palaniramkumar** [comment]
Any suggestion to add space between the chart and the text ?
