### ISSUE TITLE
Selected point text on the Y axis, instead of on the point

### ISSUE THREAD

**Issue by mesropd** [PhilJay/MPAndroidChart#466]
I want to know is it possible to show selected point's text on the Y axis, with fixed X coordinate, if no, I can start to implement.
Like this.
![selection](https://cloud.githubusercontent.com/assets/8722637/6779791/09cb1b52-d179-11e4-9415-7913aa97ea1c.png)

**Comment by PhilJay** [comment]
Not yet possible! If you could provide a clean implementation of this I would very much appreciate it!

Best regards,
Phil

**Comment by mesropd** [comment]
I implemented it already, and also other 2 features, I will send pull request after testing and providing more clean implementation. Here is the list of changes that I did. I want to know if you interested in these features too.

1. Selected point text on the Y axis, instead of on the point. (this OK)
2. Dash grid lines for line charts.
3. Show grid lines for YAxis when isShowOnlyMinMaxEnabled is true, because there are cases, when we want to show only min/max, but also want to keep grid lines. (I searched for that functionality, but didn't find, is this duplicate or not?) I didn't want to use the existing fields for this feature  to not break existing functionality, I added this field, what you think about this, is this OK?
```
/** if true, the y-labels show all grid lines when mShowOnlyMinMax is true*/
protected boolean mShowGridLinesIfOnlyMinMax = false;

/**
* If enabled, the YLabels will show all grid lines of the chart even if
* isShowOnlyMinMaxEnabled is true.
*
* @param enabled
*/
public void setShowGridLinesIfOnlyMinMax(boolean enabled) {
    mShowGridLinesIfOnlyMinMax = enabled;
}

/**
* Returns true if showing grid lines is enabled when isShowOnlyMinMaxEnabled is true.
* Internaly this method used only when isShowOnlyMinMaxEnabled is true
*
* @return
*/
public boolean ismShowGridLinesIfOnlyMinMaxEnabled() {
    return mShowGridLinesIfOnlyMinMax;
}
```
![screenshot_2015-03-25-09-18-32](https://cloud.githubusercontent.com/assets/8722637/6818831/b0270828-d2d0-11e4-8bdf-402eb02542db.png)
