### ISSUE TITLE
Can I change the color on the way with LineChart?

### ISSUE THREAD

**Issue by kazetani** [PhilJay/MPAndroidChart#4666]
![image](https://user-images.githubusercontent.com/43020628/65208921-748e1780-dad1-11e9-964d-5779d3a49afe.png)

I want to change the color on the way with LineChart.
Please tell me how.

**Comment by JamieKalloe** [comment]
I think the best way would be to use distinct DataSet
Different datasets can have a color associated with them.

So you would have one dataset with an orange color and one with a blue color.
More info can be found here: https://github.com/PhilJay/MPAndroidChart/wiki/Setting-Colors

**Comment by kazetani** [comment]
Thanks!
Change DataSet color for each entry.
Kind regards.
