### ISSUE TITLE
BarChart.resetZoom() No effect

### ISSUE THREAD

**Issue by ooftf** [PhilJay/MPAndroidChart#4667]
I want use  BarChart.resetZoom() to reset the zoom,but the result still is Multiply,the code is 
chart.resetZoom();
chart.zoomToCenter(zoomX,1f);

**Comment by ooftf** [comment]
I have solve this problem
    chart.getViewPortHandler().getMatrixTouch().reset();
    chart.resetZoom();
   chart.zoom(zoomX, 1f, 0, 0);

**Comment by ajay-bsoft** [comment]
use `chart.fitScreen()`
