### ISSUE TITLE
PieChartRenderer drawCenterText lineHeight calculation should not depend on first line

### ISSUE THREAD

**Issue by mtotschnig** [PhilJay/MPAndroidChart#467]
If the center text of a PieChart is set to a multi line string and the first line only contains characters with a small text height, but the second line has character with full text height, the calculated line height is too small. The following screenshots illustrate the difference with the first line text being "aaaa" or "bbbb".

![aaaa](https://cloud.githubusercontent.com/assets/1485456/6781530/9eb09658-d16e-11e4-9503-ac2462885360.png)
![b](https://cloud.githubusercontent.com/assets/1485456/6781531/9eb3e5f6-d16e-11e4-96e9-e7447239741a.png)

**Comment by PhilJay** [comment]
Should be fixed now!
