### ISSUE TITLE
How do i achieve following style in line chart?

### ISSUE THREAD

**Issue by Arunkarthicknallasami** [PhilJay/MPAndroidChart#4677]
Hi,
 Does MP chart support line chart of this style?

https://user-images.githubusercontent.com/9251012/66468777-5b5f0200-eaa4-11e9-945a-f93906743598.png

It shows discrete and continuous line styles in same range. I want to plot a device's ON time and OFF time. Continous ON time will have straight connect lines and OFF time will have discrete lines

**Comment by PhilJay** [comment]
This can be achieved by using 2 different LineDataSets.
One with dashed line enabled: ------
One with dashed line disabled.

**Comment by Arunkarthicknallasami** [comment]
Thanks phil, I will seek support if i have any issues on it
