### ISSUE TITLE
Radar Chart size reduced every time new Data is set

### ISSUE THREAD

**Issue by twofingersapps** [PhilJay/MPAndroidChart#4689]
Hi guys,
first of all: Thanks for this awesome lib!

Currently I'm having an issue though, that drives me nuts, as I can't get rid of it.
I have a radar chart, that needs to overlap a background at a very specific size.
The data is updated every few seconds using basically the example code and only official API.
Anyway every time a new DataSet is set, the whole chart is rendered a little bit smaller.
After a few dozen updates the chart collapses into a point.

So in the beginning it looks like this:
<img width="389" alt="Bildschirmfoto 2019-10-18 um 11 16 01" src="https://user-images.githubusercontent.com/56719538/67082076-b2e22980-f198-11e9-9787-070e7ec7dc72.png">

After a while, like this:
<img width="376" alt="Bildschirmfoto 2019-10-18 um 11 17 56" src="https://user-images.githubusercontent.com/56719538/67082340-40257e00-f199-11e9-9e4f-f5fb23b354c1.png">

Any help is appreciated!
Regards,
Rafael

**Comment by hitori762** [comment]
Try to use yAxis.setLabelCount(int count, boolean force) with force = true

**Comment by twofingersapps** [comment]
Hi @hitori762,
thanks for your comment, works like a charm.
How did you come up with that? I don't see an immediate connection between the label count and the size of the chart.
Regards,
Rafael
