### ISSUE TITLE
Problem with axis

### ISSUE THREAD

**Issue by davix10** [PhilJay/MPAndroidChart#470]
Hi, I have a couple of problems with the axes. I would like to set the value of the x 0 to 2 in steps of 0.2 but I can not because then I go to insert variable values within the axis. I wish all my chart was visible without having to move it with a touch. Also I can not set the minimum value of the Y axis, continues to set only the maximum value using at least always and only 0. Can you help me?
Thanks.

**Comment by PhilJay** [comment]
The problem with the x axis:

 - simply add x-labels like "0", "0.2", ... and so on, then place your entries at index 0, 1, ...

The y-axis minimum value problem:
 - call `setStartAtZero(false)` on the axis, then set the minimum
