### ISSUE TITLE
setYRange missing from BarlineChartBase

### ISSUE THREAD

**Issue by enantiomer2000** [PhilJay/MPAndroidChart#471]
It seems like it was there at one point but now it is absent. How should I go about setting the y-axis so that it's max value is 100 even if all of the entries are under 50?

**Comment by PhilJay** [comment]
This can now be done via the `YAxis` object, have a look at the docs: https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-%28YLabels%29
