### ISSUE TITLE
Improvement suggestions - no data text color + handle zero sized data as no data

### ISSUE THREAD

**Issue by MichaelFlisar** [PhilJay/MPAndroidChart#473]
In the Chart.java class, the mInfoPaint should be configurable. At least for example like following:

setNoDataTextColor(customColor);

The second thing is, if the data is set by chart.setData(...) there should be a validation if it's not a zero size data set and if so, the no data available text should be drawn as well

Btw, your library is awesome and works like a charm. Thanks

**Comment by svasic** [comment]
You can get paint by calling chart.getPaint(Chart.PAINT_INFO)

**Comment by MichaelFlisar** [comment]
Thanks, that worked
