### ISSUE TITLE
Shader on LineChart

### ISSUE THREAD

**Issue by svasic** [PhilJay/MPAndroidChart#474]
I'm using 2.0.8 version of library. In previous version setting shader for mRenderPaint worked well, but now i can't achieve the same effect. 
I'm trying like this:

Paint paintRenderer = mChart.getPaint(Chart.PAINT_RENDER);
paintRenderer.setShader(new LinearGradient(0, 0, 0, 10, Color.BLACK, Color.WHITE, Shader.TileMode.MIRROR));
mChart.setPaint(paintRenderer, Chart.PAINT_RENDER);

Am I using it wrong or is this a bug?
ty

**Comment by PhilJay** [comment]
As of the latest commit I just pushed, you can use:

`chart.getRenderer().getPaintRender()` to get the paint used for renderng.
