### ISSUE TITLE
Fill between two LineDataSets

### ISSUE THREAD

**Issue by AlBirdie** [PhilJay/MPAndroidChart#477]
I'd like to fill the area between two given LineDataSets. I'm aware of the fact that you can have a custom FillFormatter that specifies where the fill appears, however, that custom formatter would have to be applied to the entire chart, which won't work for a lot of use cases.

For instance, imagine the following chart; http://finance.yahoo.com/echarts?s=AAPL+Interactive#%7B%22lineType%22%3A%22combo%22%2C%22indicators%22%3A%7B%22bollinger%22%3A%5B%7B%22id%22%3A%5B%22bollinger_upper%22%2C%22bollinger_lower%22%5D%2C%22name%22%3A%22bollinger%22%2C%22subLines%22%3A%5B%22upper%22%2C%22lower%22%5D%2C%22lineType%22%3A%7B%22upper%22%3A%22line%22%2C%22lower%22%3A%22line%22%7D%2C%22color%22%3A%7B%22bollinger_upper%22%3A%22%23ff00ff%22%2C%22bollinger_lower%22%3A%22%23ff00ff%22%7D%2C%22weight%22%3A%7B%22bollinger_upper%22%3A4%2C%22bollinger_lower%22%3A4%7D%2C%22params%22%3A%5B20%2C2%5D%7D%5D%7D%2C%22scale%22%3A%22linear%22%7D

In terms of MPAndroidChart that would be a CombinedChart showing a LineDataSet for the main chart (the Apple stock) with a regular fill, and another two LineDataSets that represent the Bollinger Bands indicator (marked in pink here). Lets assume we want the area between the two Bollinger Band curves filled as well, how would you do that? Is that even possible with the current version of MPAndroidCharts?

**Comment by PhilJay** [comment]
The `FillFormatter` might help here.
