### ISSUE TITLE
CombinedChart - How I can combine 2 lines graphics? 

### ISSUE THREAD

**Issue by Carlosmulero** [PhilJay/MPAndroidChart#480]
I'm trying CombinedChart, if I combine lines with bar graph works fine but if I try to combine two line graphs only last I get looks.
The YAxis if they are good.

**Comment by PhilJay** [comment]
So you only want 2 lines in your graph?
Then you do not have to use the `CombinedChart`. This chart is designed to combine different data types.

If you simply want 2 different lines, use the `LineChart` and add 2 `LineDataSets`.

Example: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/MultiLineChartActivity.java

**Comment by starjhlee** [comment]
I wanna 1 bar and 2 line.. help

**Comment by nazgul87** [comment]
Hi @PhilJay , do you have an example where you can combine two bar charts??

**Comment by nazgul87** [comment]
Based on your CombinedChart Example I saw you set the barwidth, barSpace and groupSpace. So, with this I could achieve the two bars creation.

**Comment by EvilCodes** [comment]
> So you only want 2 lines in your graph? Then you do not have to use the `CombinedChart`. This chart is designed to combine different data types.
> 
> If you simply want 2 different lines, use the `LineChart` and add 2 `LineDataSets`.
> 
> Example: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/MultiLineChartActivity.java
can you realize 1 bar two lines？

**Comment by EvilCodes** [comment]
@PhilJay

**Comment by johnnyzen** [comment]
@PhilJay long gone
