### ISSUE TITLE
Change legend text

### ISSUE THREAD

**Issue by hansandroid** [PhilJay/MPAndroidChart#4818]
Hello, I want to change the legend text with the selected coordinates on the chart. How can I change the legend text?

**Comment by Hart87** [comment]
After looking through the source, It takes a few steps. This is just a step in the direction, I'm not checking this in the example app

1 - create a MPPointD instance. You can create variables from the  and Y values you will derive. 
`MPPointD mMPPointD;`

2- make that MPPointD with getValuesByTouchPoint  ... this method is in the Transformer class and returns an MPPointD
`MPPointD = getValuesByTouchPoint();`

3 - concatenate the string values of MPPointD.x and MPPointD.y into a new variable or keep them separate

4- set the text of the legend with your new variable (through the use of some action not describe in this post) like so
```
Legend legend = mChart.getLegend();
    legend.setLabels(new String[]{"x", "y"});
```

Hope this helps 🤙🏼

**Comment by hansandroid** [comment]
Thank you, Hart87. It helped me with some edits. There is no such method in the version of MPA I use. So I used a different method. For example..
val entries: MutableList<LegendEntry> = ArrayList()

        for (i in arrayLabels.indices) {
            val entry = LegendEntry()
            entry.formColor = arrayColors[i]
            entry.label = arrayLabels[i]
            entries.add(entry)
        }

        legend.setCustom(entries)
