### ISSUE TITLE
Bug in stacked bar chart with one stack

### ISSUE THREAD

**Issue by aint** [PhilJay/MPAndroidChart#482]
The stacked bar chart with only one stack crashes on selecting value and a legend's labels aren't displayed.

![screen shot 2015-03-27 at 9 05 39 pm](https://cloud.githubusercontent.com/assets/3179252/6875131/755a425e-d4c5-11e4-8c45-97f7d8819f19.png)

```java
java.lang.ArrayIndexOutOfBoundsException: length=1; index=-1
            at com.xxmassdeveloper.mpchartexample.StackedBarActivity.onValueSelected(StackedBarActivity.java:258)
            at com.github.mikephil.charting.charts.Chart.highlightTouch(Chart.java:513)
            at com.github.mikephil.charting.listener.BarLineChartTouchListener.performHighlight(BarLineChartTouchListener.java:286)
            at com.github.mikephil.charting.listener.BarLineChartTouchListener.onSingleTapUp(BarLineChartTouchListener.java:475)
            at android.view.GestureDetector.onTouchEvent(GestureDetector.java:588)
            at com.github.mikephil.charting.listener.BarLineChartTouchListener.onTouch(BarLineChartTouchListener.java:84)
            at com.github.mikephil.charting.charts.BarLineChartBase.onTouchEvent(BarLineChartBase.java:521)
            at android.view.View.dispatchTouchEvent(View.java:7246)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2168)
...
```

It seems that if the stacked chart has only one stack it treats as a simple bar char. In this case the ```onValueSelected()``` method receives a _Highlight_ object with ```mStackIndex = -1``` by default and we get ```ArrayIndexOutOfBoundsException``` on ```entry.getVals()[h.getStackIndex()])```. For the same reason a ```mStackLabels``` array is ignored and the legend's labels aren't displayed.

You can easily reproduce it by going to the demo ```StackedBarActivity``` and comment out val2 and val3 vars.
```java
for (int i = 0; i < mSeekBarX.getProgress() + 1; i++) {
            float mult = (mSeekBarY.getProgress() + 1);
            float val1 = (float) (Math.random() * mult) + mult / 3;
//            float val2 = (float) (Math.random() * mult) + mult / 3;
//            float val3 = (float) (Math.random() * mult) + mult / 3;

            yVals1.add(new BarEntry(new float[] {
                    val1, //val2, val3
            }, i));
        }
```

**Comment by PhilJay** [comment]
Well if you only use one value, its not really a stack. So simply use the normal `BarEntry` contstructor for entries containing only one value.

**Comment by aint** [comment]
In our finance app (GnuCash) chart based on user data. Let's suppose that the user has income and expense transactions. In this case a stacked bar work as well. But what if user has only income transactions? In this situation we have broken legend and crashes on selecting.
![screen shot 2015-04-02 at 7 08 45 pm](https://cloud.githubusercontent.com/assets/3179252/6969211/5f540044-d975-11e4-86aa-db85b0e7b647.png)

Yes, I can check it in my code, but I suppose it should be handled by the charting library.
IMHO, if a chart has yVals array, its stacked. No matter what the array size is - zero, one or ten, it is a stacked chart, not simple bar.

**Comment by stevwin94** [comment]
Good evening, PhilJay. i wanna ask a question. i create the stacked bar using this code

 Vector<BarEntry> entries = new Vector<>();
        for (int i = 0; i < ready.size(); i++) {
            entries.add(new BarEntry(new float[]{5, 3}, i));
        }

and my question is :
how can i get that 2 value from 1 bar when i clicked it ?
for example, if i click 5, that it show 5, and also if i click 3, that show 3 in 1 bar.

please help me, i really confused about that. i hope that you understand about my question, sorry for bad english.
i'm junior developer android too, Thank you ;)

Best Regards, 

Steven

**Comment by s-ilnar** [comment]
how to make the entire bar column stand out? in stacked bar mode

entries.add(new BarEntry(i, new float[]{idleFuelVolume, fuelDrain, movementFuelVolume}, daysDatas.get(i).date));
