### ISSUE TITLE
Incorrect spacing between grid lines when using LineChart with dual y-axes.

### ISSUE THREAD

**Issue by cafrean** [PhilJay/MPAndroidChart#484]
![weirdgrid](https://cloud.githubusercontent.com/assets/8956472/6881370/cdeb7a68-d55c-11e4-893d-85aea91d7dfe.png)

It seems like there are two different grids that don't quite line up. This might not be an issue, but I'm not sure what could have caused this otherwise.

**Comment by PhilJay** [comment]
Actually, there is one grid that belongs to the left, and one grid that belongs to the right y-axis.
Simply disable one to make it look beautiful.
