### ISSUE TITLE
Displaying Plot labels without decimal point

### ISSUE THREAD

**Issue by kaarthickmlsg** [PhilJay/MPAndroidChart#4845]
Hi @PhilJay 
In the MPAndroidChart example, I am trying to do a custom implementation in the DynamicalAddingActivity. In the addEntry method I am implementing this:

`private void addEntry() {

        LineData data = chart.getData();

        if (data == null) {
            data = new LineData();
            chart.setData(data);
        }

        ILineDataSet set = data.getDataSetByIndex(0);
        if (set == null) {
            set = createSet("Set 1");
            data.addDataSet(set);
            data.addDataSet(createSet("Set 2"));
            data.addDataSet(createSet("Set 3"));
        }

        data.addEntry(new Entry(0,0), 0);
        data.addEntry(new Entry(1,110f), 0);
        data.addEntry(new Entry(2,140f), 0);
        data.addEntry(new Entry(3,158), 0);
        data.addEntry(new Entry(4,168), 0);
}
`

When I run the project, I see that in the Chart the values are shown as 140.0 , 158.0. Please see the screenshot. How can I remove the decimal point in the label to show values as 140, 158 etc?
I am already using a value formatter for formatting the x axis labels and it is working fine. 

![chart](https://user-images.githubusercontent.com/51783010/76607923-bf07c280-654f-11ea-90c8-05e0b1a2421f.png)

**Comment by kkuez** [comment]
Whats your solution here?
Im facing the same issue.

**Comment by Manish068** [comment]
```
dataSet.setValueFormatter(new ValueFormatter() {
            @Override
            public String getFormattedValue(float value) {
                int intValue = (int) value;
                return String.valueOf(intValue);
            }
        });
```


use this
