### ISSUE TITLE
The X value float is changing value by the time it gets to Value Formatter

### ISSUE THREAD

**Issue by therealccarter** [PhilJay/MPAndroidChart#4854]
**Summary**

I create a list of entries where the x is the date simply converted from y/m/d format, eg 2017-10-05, to 20171005. The entries class only takes floats so I just do Float.parseFloat(string), which in the debugger strangely comes out as 2.0171004E7. So, somehow the 5 became a 4. Then with the Value Formatter I would just take whatever x value and add the dashes back in for the x axis decoration. However, once it gets to the Value Formatter, the x value has deteriorated further, becoming 2.0175E7, or 20175000 as an int, which is now completely useless. 

**Edit** I learned that these values are above what a float can handle. So I took off two digits, making the example number 171005, which should safely be within the range of a float. It STILL warps these values by the time it hits the Value Formatter.  171005 becomes 2.1E7. 

**Edit2** To get the number even smaller, now I am calculating the days between the oldest possible date and the date of each event, and storing those as the x values. So it's numbers like 32, 238, etc with the highest being 984. Once it hits the value formatter, the value is 180000. How is this possible? It's completely destroying the data.

**Expected Behavior**

I expected the float value in my example to be  2.0171005E7 and stay that way once it hits the Value Formatter.

**Possible Solution**

**Device (please complete the following information):**
 - Device: [e.g. Google Pixel] ZTE Blade
 - Android Version [e.g. 7.0] 29
 - Library Version (e.g. 3.1.0-alpha) 3.1.0

**Comment by therealccarter** [comment]
https://github.com/PhilJay/MPAndroidChart/issues/2891

I've realized that this library just can't handle large numbers accurately. Using the workaround of a hashmap with incremented ints mapped to values, passed to the Value Formatter.

**Comment by mohamadjavadx** [comment]
> #2891
> 
> I've realized that this library, using floats, just can't handle large numbers accurately. Using the workaround of a hashmap with incremented ints mapped to values, passed to the Value Formatter.
@therealccarter 

can you provide example?
