### ISSUE TITLE
Distribute many Legend entries over multiple lines

### ISSUE THREAD

**Issue by Erlend2** [PhilJay/MPAndroidChart#4855]
Please correct me if I'm wrong but as far as I know, the legend entries are only listed in one row which limits the max amount of entries to about 5-6 on a smartphone (IF the labels are short).

I refer to the default LegendOrientation (horizontal).

The solution I'd like is for instance the option to write:

legend.singleLine=false;
OR
legend.multipleLines=true;
OR/AND
legend.setMaxLines=2;
legend.setMinLines=2;

And then the chart's legend would put entries to a second row if they overflow the width of the chart.

Since the original problem is actually about overlapping labels in a PieChart, the alternative solution would be to add settings to avoid the label overlap in PieCharts.

To clarify, not all overlap when spinning the wheel, but overlap between entries with similar and small values (e.g. 0-1% of the pie).

**Comment by MarzipanCop** [comment]
@Erlend2 : Did you find a solution for this?

In my case I have a horizontal bar chart and want to show a horizontal oriented legend. But like you mentioned, if you have to many items, than the items in the legend are overlapping.

**Comment by nift4** [comment]
pie.getLegend().setWordWrapEnabled(true);
fixed it for me
