### ISSUE TITLE
Pi chart cut off

### ISSUE THREAD

**Issue by angelsfan1** [PhilJay/MPAndroidChart#486]
When I change the orientation of the device, part of the pie chart gets cuts off. It appears to be due to legend as it is always cutoff on the side corresponding to the legend. It appears as though a large box is being made for the legend which doesn't update appropriately causing the chart to be covered. If I'm doing something wrong or if there is a way to adjust the size of this apparent box then I would love to know how. Thanks for your help and thanks for such a great tool!

**Comment by PhilJay** [comment]
What do you mean by "cutoff"? Can you provide a screenshot?

Are you still facing these issues with the latest commit I just made?

**Comment by angelsfan1** [comment]
![screenshot_2015-04-10-12-36-32](https://cloud.githubusercontent.com/assets/9101636/7095350/7023e542-df7e-11e4-9f35-7c7432b1fdf0.png)

It only happens when I rotate the device from landscape to portrait. When I select the option in portrait mode again it goes back to normal. This is with 2.0.9

**Comment by PhilJay** [comment]
Are you using 

```xml 
android:configChanges="keyboardHidden|orientation|screenSize" 
```

for the `Activity` the `PieChart` is in?

**Comment by angelsfan1** [comment]
Yes

**Comment by PhilJay** [comment]
Allright, that should be fixed in the latest commit already. If you do not want to check out that commit, the fix will be included in the next release.

**Comment by angelsfan1** [comment]
Thanks for your help and awesome work!
