### ISSUE TITLE
Missing Files  com.github.mikephil.charting.utils.Fill;

### ISSUE THREAD

**Issue by gorillabull** [PhilJay/MPAndroidChart#4865]
I added the module to my project as described in the Gradle Setup section. 

I added a BarChart to my project by copying files from the sample project provided. 

Everything works fine except I cannot find the following file in my project: com.github.mikephil.charting.utils.Fill;

For some reason it did not get imported to my project however it exists in the example project?

**Comment by gorillabull** [comment]
I used a method that is now deprecated in the example project instead called setGradientColors 
I dont know why Fill is not available yet

**Comment by muigukenneth** [comment]
@gorillabull I think he has done new changes to the library 2 months ago on this Fill. But not published them to Gradle. Unfortunately i have to import the library manually to use fill.

**Comment by varunchandran333** [comment]
Same here
