### ISSUE TITLE
BarChart setStartAtZero(false) not working

### ISSUE THREAD

**Issue by svasic** [PhilJay/MPAndroidChart#489]
followed by #475 
I tried it and it does not fix our issue. For better understanding here is some more details:
In BarChart I have 6 categories (XAxis values). Data for BarChart is like this: [0, 100], [1, 0], [2, 0], [3, 0], [4, 0], [5, 0]
Because i dont want to have empty stack on 1,2,3,4,5 categories, I use setStartAtZero(false) in combination with yAxis.setAxisMinValue(X); where X should be the minimum bottom offset I want to see on every stack.
This is the output I would like to achieve
![image](https://cloud.githubusercontent.com/assets/9920953/6865144/35177270-d46b-11e4-9f8a-6dacab3d2b7b.png)

Instead, I get:
![image](https://cloud.githubusercontent.com/assets/9920953/6865174/6e4ba12e-d46b-11e4-9948-9c2af00604d4.png)

There are two issues here:
- first is that i dont see bottom rectangle that should appear when setting setStartAtZero(false)
- second is that if I call setAxisMinValue(X), then I don't see zero value labels  (Y values) above 1,2,3,4,5 (X values) - obviously because they are filtered out, based on axis min value which is used for different purposes. There should be method for setting minOffsetFromAxis which doesn't have impact on the data filtration.

I hope it's clear now, what our use case is, and hopefully this can be fixed. As i said, i'm using ugly workaround, which will certainly give me headaches in the future if i don't remove it asap.

thanks for any help

**Comment by PhilJay** [comment]
For me, this works: (startatzero disabled)
![screenshot_2015-04-02-13-02-36](https://cloud.githubusercontent.com/assets/6759734/6962900/813a43e4-d939-11e4-8384-36c7147da2bd.png)

(startatzero enabled)
![screenshot_2015-04-02-13-02-46](https://cloud.githubusercontent.com/assets/6759734/6962901/815c8170-d939-11e4-8b25-901c3aa56109.png)


Concerning the "bottom rectangle":

This cannot work, even if startAtZero(...) is set to false. The simple reason therefore is that all bars start at zero. The reason therefore is that I also want to be able to plot values < 0 and values > 0 in the same plot. If i then let bars start at infinity it would display bars incorrectly.
