### ISSUE TITLE
ScatterDataSet is picking wrong color?

### ISSUE THREAD

**Issue by xizzhu** [PhilJay/MPAndroidChart#490]
I'm using a ScatterDataSet and a BarDataSet from the CombinedData. When I'm trying to add color to them, it seems ScatterDataSet is picking the color from a wrong index (BarDataSet works as expected)?
I have:
```
ArrayList<Integer> colors = new ArrayList<>();
colors.add(color1); // used by the 1st entry
colors.add(color2); // never used
colors.add(color3); // used by the 2nd entry
colors.add(color4); // never used
colors.add(color5); // used by the 3rd entry
colors.add(color6); // never used
...
scatterDataSet.setColors(colors);
```

Then I checked a bit of the source code:
In ScatterChartRenderer.drawDataSet(), it's picking the color with:
```
mRenderPaint.setColor(dataSet.getColor(i));
```

Compared to BarChartRenderer.drawDataSet(), it's picking the color with:
```
mRenderPaint.setColor(dataSet.getColor(j / 4));
```

Is this a bug, or I'm doing something wrong?

**Comment by PhilJay** [comment]
Yep, looks like an issue. I will correct it now.

**Comment by PhilJay** [comment]
Fixed.

**Comment by xizzhu** [comment]
Wow, that's really fast. Thanks!
