### ISSUE TITLE
Documentation website down

### ISSUE THREAD

**Issue by lienbacher** [PhilJay/MPAndroidChart#4904]
I'm trying to access the documentation, but the linked website https://weeklycoding.com/mpandroidchart/ seems to be down. Theres an error message: "Error establishing a database connection"

**Comment by MahmoudMabrok** [comment]
occurs with me also

**Comment by MahmoudMabrok** [comment]
@lienbacher  you can see Example App, till website being solved

**Comment by lienbacher** [comment]
I'd like to read the API documentation. The example app is insufficient I'm afraid.

**Comment by MahmoudMabrok** [comment]
- u can wait
- try & error with example app 
- use another lib (if its urgent for you)

**Comment by developer-dmp** [comment]
Saw this as well - was going to reach out somehow.  Not a show stopper, but wanted to put it on the radar if it wasn't already there.

**Comment by PhilJay** [comment]
Thanks for letting me know! Should be up now again - hosting provider did some maintenance I was unaware of - sorry for that! :-)

**Comment by lienbacher** [comment]
No worries, thank for the fast fix!
