### ISSUE TITLE
NegativeArraySizeException

### ISSUE THREAD

**Issue by pandeeswaran** [PhilJay/MPAndroidChart#4905]
**Summary**
   Hope need to this issue fixed soon.  Track and trace functionality have been implemented in the MPAndroidChart. 
1. Previously we have been implemented the Library for trace functionality based on X axis and Y axis values.
2. We have frequently getting "NegativeArraySizeException" and app was crashed.
3. Finally we had used sort functions (Collections.sort(ArrayList, new EntryXComparator())), its resolved while got crashed the app.
4. Sort method does not supported for our requirements. 

**Expected Behavior**

1. Given positive x and y values are worked as expected.
2. Trace point come from max value to min value its won't worked as expected because we are using "Sort" functionality.

Without adding Sort functionality, is it possible to resolve this issue

Entry, x: 2.4622053E-4 y (sum): -2.5103273E-4 Entry, x: 1.4264166E-4 y (sum): 1.06562635E-4 Entry, x: 1.0069651E-4 y (sum): 2.2954303E-4 Entry, x: 3.3205854E-6 y (sum): 6.520928E-5 Entry, x: 2.1512537E-4 y (sum): -1.926993E-4 Entry, x: 1.4847405E-4 y (sum): -1.5883509E-4 Entry, x: 2.8459038E-4 y (sum): 1.1068245E-4 Entry, x: 1.3150444E-4 y (sum): 1.4332784E-4 Entry, x: 7.719888E-5 y (sum): 1.6962597E-4 Entry, x: 1.3707434E-4 y (sum): 1.7498349E-4 Entry, x: 2.5035875E-4 y (sum): 3.8239497E-4 Entry, x: 1.0254524E-4 y (sum): 1.468406E-4 Entry, x: 1.5425305E-4 y (sum): 4.278698E-5 Entry, x: 1.2035284E-4 y (sum): 3.2309844E-4 Entry, x: 8.58292E-5 y (sum): 4.6827746E-4 Entry, x: 8.473067E-5 y (sum): 4.3495893E-4 Entry, x: 3.0464705E-4 y (sum): -2.1406553E-4 Entry, x: 2.2885398E-4 y (sum): -1.1195301E-4 Entry, x: 1.5392534E-4 y (sum): 4.011409E-5 Entry, x: 2.240534E-4 y (sum): 1.1159029E-5 Entry, x: 2.7432045E-4 y (sum): -1.8261799E-5 Entry, x: 4.9744867E-5 y (sum): -1.1376083E-4 

Thanks.

**Comment by sandeep549** [comment]
Hi @pandeeswaran 
I'm new user, and want to contribute and help you here.
I don't see 'NegativeArraySizeException' such exception in this library code.

Could you please share:
1. Steps to reproduce the issue.
2. Stack trace for crash.

**Comment by pandeeswaran** [comment]
Thanks @sandeep549. Issue found and fixed myself

**Comment by nandha2907** [comment]
@pandeeswaran Could you please give solution on this issue

**Comment by obaid-jatoi** [comment]
@pandeeswaran what was the issue? if you find the solution please write it here it will help others !

**Comment by pandeeswaran** [comment]
Hi @obaid-jatoi 

Basically my requirement was totally different, mpchart didn't help to met my requirement because this library plot the value by Using Sort algorithm. 

Mentioned issue fixed by Collections.sort(), without using this functions frequently get negative array size expection whenever try to plot the value from max to min ( higher value to lower value) 

Suggestions: if you want to plot this kind of values mean choose "Android plot" Library. No need to sort the values, given order it will plot very smoothly.


Note: Mpchart great Library, easy to use but didn't to work for my requirement. ( Imagine trace badminton players foot steps, eg. Move front foot and back foot ( higher to lower value) plot the point given order of values ( 1, 4, 2, 5, 6, 7) without sorting this get crashed due to this exception)

Exact values were gave in my first post. See the reference of x and y axis. 

I am not against this library because 3 more projects I have been used Mpchart.

Thanks

**Comment by oneAcorn** [comment]
You might want to take a look at this library [XFree-MPAndroidChart](https://github.com/oneAcorn/XFree-MPAndroidChart) which is based on MPAndroidChart and allows unsorted data
