### ISSUE TITLE
Question - Horizontal Single StackedBar Chart

### ISSUE THREAD

**Issue by TurKurT656** [PhilJay/MPAndroidChart#491]
Hi and TnQ for this great lib.
Is there a way to use Horizontal Single StackedBar Chart? See:
![2015-03-30_19-49-16](https://cloud.githubusercontent.com/assets/7152030/6899463/e8a47cd2-d715-11e4-9dce-73a6f69f4c4d.jpg)

**Comment by PhilJay** [comment]
Should be possible in some way, you will have to try I guess :-)
