### ISSUE TITLE
Draw LimitLine behind the data?

### ISSUE THREAD

**Issue by xizzhu** [PhilJay/MPAndroidChart#493]
I'm using the `LimitLine` to draw a line for the average value in Y-axis. However, the line is drawn on top of the data, as the drawing order hard-coded in `BarLineChartBase.onDraw()`.

So, am I supposed to use it this way? If so, can you provide some interface to tweak the drawing order?

**Comment by PhilJay** [comment]
<code>setDrawLimitLinesBehindData(boolean enabled)</code>: Allows to control the z-order between the `LimitLines` and the actual data. If this is set to true, the `LimitLines` are drawn behind the actual data, otherwise on top. Default: false

**Comment by xizzhu** [comment]
Cool, thanks a lot!
