### ISSUE TITLE
LimitLine enableDashedLine not working

### ISSUE THREAD

**Issue by aint** [PhilJay/MPAndroidChart#494]
Code from [example](https://github.com/PhilJay/MPAndroidChart/blob/c42b88082d80ce4b02d37501eb0e2a0b1be0bf7b/MPChartExample/src/com/xxmassdeveloper/mpchartexample/LineChartActivity1.java#L332) :
```java
        LimitLine ll1 = new LimitLine(130f, "Upper Limit");
        ll1.setLineWidth(4f);
        ll1.enableDashedLine(10f, 10f, 0f); // <--
        ll1.setLabelPosition(LimitLabelPosition.POS_RIGHT);
        ll1.setTextSize(10f);

        LimitLine ll2 = new LimitLine(-30f, "Lower Limit");
        ll2.setLineWidth(4f);
        ll2.enableDashedLine(10f, 10f, 0f);  // <--
        ll2.setLabelPosition(LimitLabelPosition.POS_RIGHT);
        ll2.setTextSize(10f);
```

![screenshot_2015-03-31-18-01-55](https://cloud.githubusercontent.com/assets/3179252/6921911/573aea40-d7d0-11e4-8f71-00b01cf88ada.png)

**Comment by mesropd** [comment]
Disable hardware acceleration
setHardwareAccelerationEnabled(false)

**Comment by aint** [comment]
Thanks for quick response, but doesn't work.

**Comment by mesropd** [comment]
Very strange, it works well on my 3 devices, on which device you run it and which android version?

**Comment by aint** [comment]
Yes, it's very strange. My device Motorola XT881, Android 4.1.2.
Also I have tested on various emulators:
* API 14 - not work
* API 15 - not work
* API 16 - not work
* API 17 - not work
* API 18 - work
* API 19 - work
* API 20 - work

![screen shot 2015-03-31 at 8 06 05 pm](https://cloud.githubusercontent.com/assets/3179252/6944152/0825e51a-d89b-11e4-9fbc-9d90b88e51f7.png)

**Comment by PhilJay** [comment]
Are you using the latest version of the library? This works for me.

**Comment by neotel** [comment]
I have the same problem on Galaxy S4. Any idea?

**Comment by aint** [comment]
I checked out last commit just now and reproduce this bug if __API <= 17__. Tested on the standard Android emulators, GenyMotion x86 emulators and on my own device. 
The most strange thing is that ```LineDataSet```'s ```enableDashedLine()``` works like a charm.

![screen shot 2015-04-02 at 6 48 36 pm](https://cloud.githubusercontent.com/assets/3179252/6967823/a7aa6d48-d96a-11e4-9592-2ca791f587d1.png)

**Comment by PhilJay** [comment]
Finally found the bug, please try the latest commit :-)
