### ISSUE TITLE
how to Change color of a specific bar in barchart

### ISSUE THREAD

**Issue by sundravel** [PhilJay/MPAndroidChart#4951]
This is my bar entries

val barEntries: ArrayList<BarEntry> = ArrayList()
        barEntries.add(BarEntry(0f, getSortedData?.iHour6am?.toFloat() ?: 0f))
        barEntries.add(BarEntry(1f, getSortedData?.iHour7am?.toFloat() ?: 0f))
        barEntries.add(BarEntry(2f, getSortedData?.iHour8am?.toFloat() ?: 0f))
        barEntries.add(BarEntry(3f, getSortedData?.iHour9am?.toString()?.toInt()?.toFloat() ?: 0f))
        barEntries.add(BarEntry(4f, getSortedData?.iHour10am?..toFloat() ?: 0f))
        barEntries.add(BarEntry(5f, getSortedData?.iHour11am?..toFloat() ?: 0f))
        barEntries.add(BarEntry(6f, getSortedData?.iHour12pm?.toFloat() ?: 0f))

val barDataSet = BarDataSet(barEntries, "DATA SET 1")

this is how i set my bar color barDataSet.color = Color.parseColor("#41bdf0")

but i want to change last bar graph color to  #e9bb01  and rest all bar color should be #41bdf0, How can i achieve this

**Comment by varunchandran333** [comment]
Why this closed?
Any answer for this??

**Comment by sundravel** [comment]
> Why this closed?
> Any answer for this??

Yes had got the solution, please refer this link
https://stackoverflow.com/questions/29879943/mpandroidchart-is-there-a-way-to-set-different-colors-for-different-bars
