### ISSUE TITLE
Linechart flickers when adding new data dynamically (v3.1.0)

### ISSUE THREAD

**Issue by smokinghot** [PhilJay/MPAndroidChart#4955]
We're using v3.1.0 in our project.
The behavior is adding new data while scrolling horizontally 
The line chart flickers severely when notify new data comparing to iOS.

Below is part of our code. Looking forward to your reply

        var lineDataSet: LineDataSet
        val values: MutableList<Entry> = ArrayList()
        if (mLineChart.data != null && mLineChart.data.dataSetCount > 0) {
            updateXAxis()
            lineDataSet = mLineChart.data.getDataSetByIndex(0) as LineDataSet;
            lineDataSet.values = it
            mLineChart.axisLeft.setLabelCount(viewModel.config.mYAxisLabelCount, false)
            updateLeftYAxis()
            mLineChart.data.notifyDataChanged();
            mLineChart.notifyDataSetChanged()
        }

**Comment by smokinghot** [comment]
This is the screenshot.FYR
[https://github.com/smokinghot/curvechart/blob/master/chart.mp4](url)

**Comment by EvanZch** [comment]
> 这是截图 [。FYR https://github.com/smokinghot/curvechart/blob/master/chart.mp4](https://github.com/smokinghot/curvechart/blob/master/chart.mp4)

How to solve the problem？

**Comment by EvanZch** [comment]
> 这是截图 [。FYR https://github.com/smokinghot/curvechart/blob/master/chart.mp4](https://github.com/smokinghot/curvechart/blob/master/chart.mp4)

Has the problem been dealt with？
