### ISSUE TITLE
Piechart X text color and percentage symbol 

### ISSUE THREAD

**Issue by ivangag** [PhilJay/MPAndroidChart#496]
Hi, 
I upgraded to the latest version and i'm facing with the following issues about **PieChart** graph:

* text color of value is black instead of white as before. Is it possible to set the color of text value?
* value now is simply a text with the raw value without % symbol as before. Is it possible to enable/restore that behavior?

Thanks

**Comment by PhilJay** [comment]
```java
pieData.setValueTextColor(Color.WHITE);
pieChart.setUsePercentValues(true);

```

Then set a `PercentFormatter` to show the % sign.
https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/com/github/mikephil/charting/utils/PercentFormatter.java

**Comment by ivangag** [comment]
Thanks it works a charm!
