### ISSUE TITLE
Cannot color onValueSelected Point in LineChart

### ISSUE THREAD

**Issue by aladinsane** [PhilJay/MPAndroidChart#502]
Hi,
I have a LineChart with two lines.. there is a way to color only the selected point?

**Comment by PhilJay** [comment]
What do you mean by "color"?

**Comment by aladinsane** [comment]
Fill only the selected circle with a specific color :)

**Comment by PhilJay** [comment]
Well upon highlighting the value you could define a new set of colors for your DataSet and exchange the color of the highlighted index to your desire.
