### ISSUE TITLE
Is there any method to set chart color with color string, like "#F44141"?

### ISSUE THREAD

**Issue by yuyang551003** [PhilJay/MPAndroidChart#504]
Hi,

My app will get all of the data from API response and then generate charts. For the colors, my app app should also use the color string specified by the response. Is there any method to set chart color with color string, like

setColors(new String[] { "#F44141", "#34DA76", "#5FC61B", "#FFC600" }, Context);

Thanks!

**Comment by yuyang551003** [comment]
It is easy to convert color string to int using:
int color = Color.parseColor("#2222FF");

But according to the MPAndroidChart Wiki, the existing setColor methods only support colors with resource id, right? That means we must define the colors in resource files in a "static" way before using them in charts.

setColors(int [] colors, Context c): Sets the colors that should be used fore this DataSet.Internally, the colors are resolved using getResources().getColor(...).
setColors(int [] colors): Sets the colors that should be used fore this DataSet.  Make sure that the colors are already prepared (by calling getResources().getColor(...)) before adding them to the DataSet.
setColors(ArrayList<Integer> colors): Sets the colors that should be used fore this DataSet.  Make sure that the colors are already prepared (by calling getResources().getColor(...)) before adding them to the DataSet.
setColor(int color): Sets the one and ONLY color that should be used for this DataSet. Internally, this recreates the colors array and adds the specified color.

**Comment by PhilJay** [comment]
No, the color just needs to be "resolved", meaning you cannot simply provide the resource id alone.

Anything like

 - `Color.rgb(...)`
 - `Color.BLACK`
 - `getResources().getColor(R.color.green)`

will work.

For transforming hex e.g. to RGB, simply use this:

```java
public static Color hex2Rgb(String colorStr) {
    return new Color(
            Integer.valueOf( colorStr.substring( 1, 3 ), 16 ),
            Integer.valueOf( colorStr.substring( 3, 5 ), 16 ),
            Integer.valueOf( colorStr.substring( 5, 7 ), 16 ) );
}
```

**Comment by shahrukhbaig786** [comment]
I want to set Mutiple Color in my PieDataSet object ?.Not working 
on  dataSet.setColor(int color );--Error can't convert Integer<ArrayList >to int  

 1 )PieDataSet dataSet = new PieDataSet(yValue, "Market Share");


 ArrayList<Integer> colors = new ArrayList<Integer>();
        for (int i : ColorTemplate.VORDIPLOM_COLORS)
            colors.add(i);

        for (int i : ColorTemplate.JOYFUL_COLORS)
            colors.add(i);
        for (int i : ColorTemplate.COLORFUL_COLORS)
            colors.add(i);
        for (int i : ColorTemplate.LIBERTY_COLORS)
            colors.add(i);
        for (int i : ColorTemplate.PASTEL_COLORS)
            colors.add(i);
 2)   dataSet.setColor(Color.GRAY); ------ERRROR IS HERE
