### ISSUE TITLE
How can i set grid with a specific interval in a real time recording?

### ISSUE THREAD

**Issue by davix10** [PhilJay/MPAndroidChart#506]
Hi,
I have the following problem. I am recording real time data from my bluetooth device and i would like to show them on the chart.
My dataset has a sample frequency of 32 samples per second.
I would like to show the signal with a 0.5 seconds grid, 3 seconds real time window.
It means that i need to see 96 samples on the chart and a grid every 16 samples.

Furthermore, this is a moving window, hence i would replace the coordinates.

If you know C#, i need something like the function

chart.Series[0].Points.Clear();
for (int ii=0; ii<96; ii++)
{
      chart.Series[0].Points.AddXY((double)(ii/32),signal[ii]);
}

Thank you so much for your help.

davix10

**Comment by PhilJay** [comment]
For setting the window size, check the documentation: https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport

It is currently not possible to set a specific grid interval on the x-axis.

**Comment by marcio-granzotto-ckl** [comment]
@PhilJay and on the y-axis?
