### ISSUE TITLE
Color customization for the CandleEntry

### ISSUE THREAD

**Issue by mesropd** [PhilJay/MPAndroidChart#507]
I looked at the codes and didn't found coloring options for the `CandleEntry` class, like this
![candlechart](https://cloud.githubusercontent.com/assets/8722637/6980956/22d7ac06-da0b-11e4-93ce-d5aa26bedce7.png)
Are there any plans to implement it soon? if no, I can implement it

**Comment by PhilJay** [comment]
I must have somehow missed that that is not yet possible :-)
Anyway I added a feature in the latest commit that allows to separately set the color of the line behind the candle-body.

Have a look at the `CandleDataSet` documentation: https://github.com/PhilJay/MPAndroidChart/wiki/DataSet-classes-in-detail

**Comment by mesropd** [comment]
I implemented it already, will send a pull request soon :)
