### ISSUE TITLE
CandleStick displaying data issue

### ISSUE THREAD

**Issue by ArcherEmiya05** [PhilJay/MPAndroidChart#5102]
I am having trouble to make my CandleStick graph work, what I want is similar to this
![image](https://user-images.githubusercontent.com/38008900/109725515-39f83c00-7bec-11eb-809c-f14da216bfa3.png)

But there are problems:

1. X-Axis only takes float value
2. Color label of Y and X axis is all black
3. Need X-Axis values as date (MM-dd-yyyy)
4. Display information and additional data which is **Volume**

**Comment by ArcherEmiya05** [comment]
Solved

**Comment by vickypathak123** [comment]
How to solve ?

**Comment by BalachandarMarimuthu** [comment]
How to solve this issue?
