### ISSUE TITLE
BarChart with only one entry

### ISSUE THREAD

**Issue by roccadev** [PhilJay/MPAndroidChart#511]
BarChart with only one BarDataSet which contains only one BarEntry, doesn't draw the bar of that single entry. The other elements are drawn (axis etc.).
Just to be clear, here is a screenshot: the 2 lines are the left and right axes;
![screenshot 04_apr_2015 10_57_21](https://cloud.githubusercontent.com/assets/11795213/6992094/2184c258-daba-11e4-8e4e-311d95db8bdb.jpg)

Debug shows that all the objects are correct: barData contains the list of BarDataSet, whose first and only element contains a list of BarEntry with a single entry, which has the correct label and value. The chart data is not really empty, otherwise the noDataText would be shown.
If another entry is added, the 2 bars are correctly shown as intended.
In any other case the chart works well.
This is how I edited the barChart, may it be relevant:

    barChart.setDrawValueAboveBar(true);
    barChart.setTouchEnabled(false);
    barChart.setDescription("");
    barChart.setDrawBarShadow(false);
    barChart.setDrawGridBackground(false);

    barData.setValueTextSize(11f);
    barData.setValueTextColor(mColor);

    XAxis xAxis1 = barChart.getXAxis();
    xAxis1.setEnabled(false);

    YAxis yAxisL = barChart.getAxisLeft();
    yAxisL.setStartAtZero(false);
    yAxisL.setDrawGridLines(false);
    yAxisL.setDrawTopYLabelEntry(false);
    yAxisL.setDrawAxisLine(true);
    yAxisL.setTextColor(mColor2);
    yAxisL.setAxisLineColor(mColor3);

    YAxis yAxisR = barChart.getAxisRight();
    yAxisR.setStartAtZero(false);
    yAxisR.setDrawTopYLabelEntry(false);
    yAxisR.setDrawGridLines(false);
    yAxisR.setDrawAxisLine(true);
    yAxisR.setTextColor(mColor2);
    yAxisR.setAxisLineColor(mColor3);

**Comment by PhilJay** [comment]
Did you call `chart.setData(...)`?

**Comment by roccadev** [comment]
Of course. I just double-checked that it's called.

**Comment by PhilJay** [comment]
You were right, there was a little bug. I just fixed it, pelase try again with the latest commit.

**Comment by roccadev** [comment]
It's working now, thank you. 
On a side note, when animating the chart with a single entry, it seems the animation starts with a delay and runs a bit faster than other "normal" charts with more entries, whose animation always starts with no lag. The code generating such charts is always the same. It's just a detail, not even opening a new issue, just a feedback to let you know, just in case you want to look into it.

**Comment by proverbface** [comment]
I'm experiencing a similar issue with a BarChart with one BarDataSet. The x axis labels are rendered but the bars are not.

`BarData barData = new BarData();
        barData.setValueTextColor(Color.BLACK);
        barData.setValueTextSize(9f);
        barData.setDrawValues(true);
        barData.setBarWidth(0.9f);

        for (WidgetSeries widgetSeries : series) {
            int blackColor = ContextCompat.getColor(itemView.getContext(), R.color.dark_gray);
            int lineColor = !TextUtils.isEmpty(widgetSeries.getColor()) ? Color.parseColor(widgetSeries.getColor()) : ContextCompat.getColor(itemView.getContext(), R.color.brand_blue);

            BarDataSet barDataSet = new BarDataSet(widgetSeries.getData(), widgetSeries.getName());
            barDataSet.setValueTextColor(blackColor);
            barDataSet.setHighLightColor(blackColor);
            barDataSet.setValueFormatter(new IntValueFormatter());
            barDataSet.setDrawValues(true);
            barDataSet.setColor(lineColor);
            barData.addDataSet(barDataSet);
        }

        barChartView.setData(barData);`

The line widgetSeries.getData() contains a list of BarEntry. The JSON representation is:
`[{"mNegativeSum":0.0,"mPositiveSum":0.0,"x":1.5318036E12,"y":50.0},{"mNegativeSum":0.0,"mPositiveSum":0.0,"x":1.53180714E12,"y":7.0}]`

I'm running on MPAndroidChart v.3.0.3 and please bear with me that I already spent 6 hours reading the docs and trying different things.
