### ISSUE TITLE
android elevation for graph for API 21

### ISSUE THREAD

**Issue by xanscale** [PhilJay/MPAndroidChart#512]
http://stackoverflow.com/questions/27497987/android-elevation-is-not-showing-a-shadow-under-a-customview

this is the method to support material elevation API

i suggest to implement if it is possible :)

**Comment by mpost** [comment]
No change of the graph library is required to enable elevation.

**Comment by xanscale** [comment]
Just insert elevation param in xml?

**Comment by mpost** [comment]
and provide a background or OutlineProvider that shapes the shadow.

**Comment by xanscale** [comment]
Why not add this in library by default?

**Comment by xanscale** [comment]
any news from author?

**Comment by xanscale** [comment]
@PhilJay so i need to write a OutlineProvider for each graph inside the library?
why can't be inside lib?

**Comment by PhilJay** [comment]
Nope, just set your elevation, you don't have to do anything else.

**Comment by xanscale** [comment]
@PhilJay lib 2.1.0 android 5.1
layout:
<?xml version="1.0" encoding="utf-8"?>
<com.github.mikephil.charting.charts.PieChart xmlns:android="http://schemas.android.com/apk/res/android"
	android:layout_width="match_parent"
	android:layout_height="match_parent"
	android:elevation="8dp" />

no elevation result

**Comment by PhilJay** [comment]
Add some margin

**Comment by xanscale** [comment]
@PhilJay sorry for delay i didn't see reply. same with this code

http://pastebin.com/wp1EzUiS

**Comment by cmatulessy** [comment]
### Note: I know this is an old thread, but I leave this one here for people who are also struggling with it.

So for my markerview this elevation wont work. Reason for it is because under the hood everything will be drawn on a canvas. So what we did was basically creating a shadow in our MarkerView XML Layout:
![image](https://user-images.githubusercontent.com/8668043/163211648-4cf879db-71b9-4123-8e00-80988ec6b379.png)

Code:

```
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape android:shape="oval">
            <gradient
                android:startColor="#FF808080"
                android:endColor="#00000000"
                android:gradientRadius="11dp"
                android:type="radial" />
        </shape>
    </item>

    <item android:top="1dp" android:left="1dp" android:right="1dp" android:bottom="6dp">
        <shape android:shape="oval">
            <solid android:color="@android:color/holo_blue_bright" />
            <stroke
                android:width="3dp"
                android:color="@color/white" />
            <size
                android:width="20dp"
                android:height="20dp" />
        </shape>
    </item>
</layer-list>
```

As you can see the top, left, right, bottom is there to manipulate the shadow.
