### ISSUE TITLE
Axis Title

### ISSUE THREAD

**Issue by t-moe** [PhilJay/MPAndroidChart#513]
It would be nice if we could add axis title. 
Imagine you plot the temperature over the time. 
y-axis-title: °C
x-axis-title: time

**Comment by klassm** [comment]
+1 here

**Comment by klassm** [comment]
Now both issues are closed?
Am 22.06.2015 2:48 vorm. schrieb "Philipp Jahoda" <notifications@github.com

**Comment by darktechsupport** [comment]
@PhilJay Was this closed because it's a 'will-never-implement'?
If not, could we reopen it and add the 'enhancement' label?

**Comment by almic** [comment]
This will not be implemented. Use a text view!

**Comment by alkla** [comment]
+1, I do think many people need this functionality. Text views are a rather inconvenient workaround.

**Comment by nightfixed** [comment]
> +1, I do think many people need this functionality. Text views are a rather inconvenient workaround.

The problem arise when you have a chart legend.
I am currently facing this issue: must add a title to the X-Axis, and under this title, the legend. I don't know where/how to draw the X-Axis title :(

**Comment by bndrylyr** [comment]
This is a fundamental requirement for a plotting tool.
