### ISSUE TITLE
Gradle is unable to download the artifact.

### ISSUE THREAD

**Issue by 123abceng** [PhilJay/MPAndroidChart#5136]
**Since today the Gradle is unable to download the artifact.**

`Unable to resolve dependency for ':app@DODebugAndroidTest/compileClasspath': Could not download MPAndroidChart-v3.1.0.aar (com.github.PhilJay:MPAndroidChart:v3.1.0)
Show Details
Affected Modules: app

Unable to resolve dependency for ':app@DODebugUnitTest/compileClasspath': Could not download MPAndroidChart-v3.1.0.aar (com.github.PhilJay:MPAndroidChart:v3.1.0)
Show Details
Affected Modules: app

Unable to resolve dependency for ':app@DODebug/compileClasspath': Could not download MPAndroidChart-v3.1.0.aar (com.github.PhilJay:MPAndroidChart:v3.1.0)
Show Details
Affected Modules: app`

I've checked all the dependencies.

**Comment by rajohns08** [comment]
jitpack.io is currently down:

![Screen Shot 2021-05-04 at 8 35 02 PM](https://user-images.githubusercontent.com/2711642/117088649-b0163d80-ad18-11eb-8500-ff589d36de59.png)


I'd humbly recommend this dependency move away from jitpack if it still has active maintainers.

**Comment by 123abceng** [comment]
Thank you, @rajohns08. Today the issue has been disappeared.
