### ISSUE TITLE
Add project to jcenter

### ISSUE THREAD

**Issue by galex** [PhilJay/MPAndroidChart#514]
Hello,

Is it planned to deploy the library into jcenter (bintray)? 

Regards,
Alex

**Comment by PhilJay** [comment]
Did you know you can already get it via jitpack?  https://github.com/PhilJay/MPAndroidChart#usage

**Comment by jaredsburrows** [comment]
+1 @galex

**Comment by jaredsburrows** [comment]
@PhilJay Why use jitpack? That means we all have to specify another repository. It would be nice to keep it down to `jcenter` and/or `mavenCentral`.
