### ISSUE TITLE
Multiple data lines in graph (Different Y axis scale) . Graph scaling failing

### ISSUE THREAD

**Issue by vijeshp** [PhilJay/MPAndroidChart#5154]
I have 4 data lines in graph.  line 1 & 3 belongs to same type and 2 & 4 different type. I want to use full space of graph and scale this data lines. Currently I am using the Axis dependency feature to achieve this .  Line 1,3 will be using YAxisDependency.Left  &    2 , 4  will be using YAxisDependency.Right. 

Above logic works for most. But failing some scenarios. The details are below

Line Data 1
Y max = 4.02
Y min = -2.82
No of data 868
Axis dependency : Left

Line Data 2
Y max = 178.7
Y min = -94.5
No of data 868
Axis dependency : Right

Line Data 3
Y max = 3.97
Y min = -2.88
No of data 767
Axis dependency : Left

Line Data 4
Y max = 126.8
Y min = -148.6
No of data 767
Axis dependency : Right

Combining above signals , I am setting below Min & Max for Y axis

mLeftAxisMax = 4.02
mLeftAxisMin = -2.88
mRightAxisMax = 178.7
mRightAxisMin = -148.6

The problem is that graph line is going out of the boundary and its not scaling fully.  Please Check this

**Comment by vijeshp** [comment]
Got the fix

**Comment by vickypathak123** [comment]
Great
