### ISSUE TITLE
Different color for negative values on barchart

### ISSUE THREAD

**Issue by mikeng13** [PhilJay/MPAndroidChart#517]
Hi! Thanks for this awesome chart lib.

I am working with the barchart and trying to set green column color for positive Y values and red column color for negative Y values? How can I achieve this? I tried looking in the wiki but I wasn't able to find what I was looking for.

Mike

**Comment by longmang** [comment]
This worked for me http://stackoverflow.com/questions/29888850/mpandroidchart-set-different-color-to-bar-in-a-bar-chart-based-on-y-axis-values

**Comment by PhilJay** [comment]
This is now possible. `dataSet.setValueColors(...)`

Example here: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/BarChartPositiveNegative.java

**Comment by zgulser** [comment]
Hi,

what about fill colors? I couldn't find a way to do that. Is there any?

**Comment by JCarlosR** [comment]
Thanks for the example. 

Btw, I see it was moved to a new location: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/main/java/com/xxmassdeveloper/mpchartexample/BarChartPositiveNegative.java#L110
