### ISSUE TITLE
Pie Chart Colors becoming transparent upon selection of one slice

### ISSUE THREAD

**Issue by lordian-g** [PhilJay/MPAndroidChart#519]
![screenshot_2015-04-06-17-39-59](https://cloud.githubusercontent.com/assets/7241631/7002942/216486f6-dc85-11e4-95f5-c7b70d3b1fd6.png)
![screenshot_2015-04-06-17-40-01](https://cloud.githubusercontent.com/assets/7241631/7002946/2933b096-dc85-11e4-96d4-596a8bd065c1.png)

Sometimes, clicking on a slice of a pie chart seems to be making its adjacent slices transparent.  After several tries, I still have not been able to pinpoint when this happens.  

I set the colors with:
ArrayList<Integer> colors = new ArrayList<Integer>();
// for loop
colors.add(Color.parseColor("#00ff00"));

pieDataSet.setColors(colors);

See images for reference.

**Comment by PhilJay** [comment]
Which version of the library are you using?

**Comment by lordian-g** [comment]
2.0.8
In my build.gradle:
compile files('libs/mpandroidchartlibrary-2-0-8.jar')

**Comment by PhilJay** [comment]
That's weird indeed. I dont think its related to the colors tough, I will look into it.
Which device did you test it on? Android version?

**Comment by lordian-g** [comment]
Tested it on Two Devices:
Device 1
Android Version : 4.4.4
Unit Model : XiaoMi Mi3

Device 2
Android Version : 4.4.2
Unit Model : Samsung GT-N7100

**Comment by PhilJay** [comment]
Does the issue also occur when you use colors like Color.BLACK, Color.RED, ...?

**Comment by lordian-g** [comment]
I'm using hex for my colors.  For the red - #9a002d, For the black - #1c2027.  But I have encountered this when I'm using different colors as well.

**Comment by xanscale** [comment]
same code:
on android 2.3 there is that problem
on android 5.1 all it's ok

**Comment by PhilJay** [comment]
This should be fixed since the latest commit.

**Comment by lordian-g** [comment]
this is in 2.0.9? Thanks!

**Comment by PhilJay** [comment]
Nope, it's in the latest commit that is not contained in any release yet.
It will be in v2.1.0

**Comment by ssaurel** [comment]
Hello,

Problem is always there with last release 2.1.0 for me.

Sylvan
