### ISSUE TITLE
LineChartRenderer drawCircles bug

### ISSUE THREAD

**Issue by lichong19880911** [PhilJay/MPAndroidChart#521]
int circleColor = dataSet.getCircleColor(j / 2);
   instead of
   int circleColor = dataSet.getCircleColor(j / 2+minx);

**Comment by PhilJay** [comment]
And why do you think this is a bug?
Whats your problem with it?

**Comment by PhilJay** [comment]
Now I see your point. Tough I think you meant:

Use this
`dataSet.getCircleColor(j / 2+minx);`

instead of this
`dataSet.getCircleColor(j / 2);`

and not the other way around.
