### ISSUE TITLE
Gradient on line chart based on line limiter (on y-axis)

### ISSUE THREAD

**Issue by konarsarnava** [PhilJay/MPAndroidChart#5215]
Hi @PhilJay, how can we implement line chart with multi-color gradient on the line. It should be based on limits on y-axis. For e.g - if value is b/w 30-45 line should be of red color, if b/w 46-80 it should be blue color. Also the color change will have gradient.

How to implement this? (example image below)

<img width="433" alt="Screenshot 2021-11-16 at 7 27 16 PM" src="https://user-images.githubusercontent.com/93985524/141999575-1f44521f-9597-41ed-a509-8cf5b793da7f.png">

**Comment by EvanZch** [comment]
How to achieve?
