### ISSUE TITLE
Left or right scroll ended

### ISSUE THREAD

**Issue by omiu** [PhilJay/MPAndroidChart#522]
Hello!

There is a way to know if, on scrolling, i am on the left or right scroll end?

Thx

**Comment by PhilJay** [comment]
The chart provides a `getLowestVisibleXIndex()` and `getHighestVisibleXIndex()` methods.
With them you can determine where you are at!

**Comment by omiu** [comment]
Dude,

Thx a lot

**Comment by omiu** [comment]
i cant find these methods :) there are in a newer version or what?
