### ISSUE TITLE
Problem with import 

### ISSUE THREAD

**Issue by Bollardinho** [PhilJay/MPAndroidChart#5220]
Hi, 
I cant import com.github.mikephil.charting.charts.LineChart;
I dont understand why, there is no problem with imports for example import com.github.mikephil.charting.data.LineData;

but any charts import doesn't work. What should I do?

**Comment by tirumala007** [comment]
same problem for me. any help?

**Comment by Bollardinho** [comment]
Yes, I repaired it with implementation of private LineChart ...
