### ISSUE TITLE
Unable to implement the library after jcenter is shutdown

### ISSUE THREAD

**Issue by sbmvirdi** [PhilJay/MPAndroidChart#5245]
I have updated the gradle version to 7.0.4 as the jcenter is deprecated so when building the project build is failing
When i replaced jcenter() to mavenCentral() it is not able to find it.

**To Reproduce**
1. Remove the jcenter from project level repositories 
2. upgrade to gradle 7.0.4 atleast
3. Build the project

**Expected behavior**
The repository should be visible when replacing jcenter() with mavenCentral() 

**Desktop:**
 - OS: MacOS
 - Version: 12.1

**Smartphone :**
 - Device: Samsung M31s
 - OS: Android
 - Version 11

**Additional context**
AI tried running the project with gradle 8.0 in my github action but it is also failing

**Comment by stepanov-standy** [comment]
+1 the same problem :(

**Comment by sbmvirdi** [comment]
I think they need to put this library in mavenCentral as jcenter is completely shutdown. Its happening to many libraries some of them which are there in mavenCentral they are running fine.

**Comment by stepanov-standy** [comment]
> I think they need to put this library in mavenCentral as jcenter is completely shutdown. Its happening to many libraries some of them which are there in mavenCentral they are running fine.

I have fixed the problem by adding

repositories {
    maven { url 'https://jitpack.io' }
}

and using the latest 3.1.0 version.

**Comment by sbmvirdi** [comment]
![Screenshot 2022-01-20 at 3 32 54 PM](https://user-images.githubusercontent.com/20088165/150317089-6afd126e-5f2f-4712-b5d6-57f32cee623c.png)
I have already added 
repositories {
maven { url 'https://jitpack.io' }
}

still getting the error while running it on device i,e when creating the debug apk. i am currently using gradle 7.0.2

**Comment by sbmvirdi** [comment]
@stepanov-standy I fixed it by adding 
maven { url 'https://jitpack.io' } within addProjects{} previously i was just adding in buildscripts{}
