### ISSUE TITLE
Saving chart state on orientation change

### ISSUE THREAD

**Issue by paulblessing** [PhilJay/MPAndroidChart#526]
Is there a recommended approach for saving the chart state (zoom level, selected entry, etc.) upon orientation change? The sample app seems to just redraw the charts from scratch for any orientation change.

**Comment by PhilJay** [comment]
So far no approach in that direction :-)
But you are welcome to PR :-)

**Comment by PhilJay** [comment]
Also, check those attributes for the activity in the android manifest: `android:configChanges="keyboardHidden|orientation|screenSize"`
