### ISSUE TITLE
[Solved] How can i draw the bar from a non zero position at y-axis?

### ISSUE THREAD

**Issue by migueljr13** [PhilJay/MPAndroidChart#5261]
Good afternoon everyone!!
How can i draw the bar from a non zero position at y-axis, such as image below? 

<img width="605" alt="print_2022-02-17_app" src="https://user-images.githubusercontent.com/7277422/154556297-4d535ba6-35e2-4c8c-bf6c-e13194a472cf.png">

Thanks for the contribution.

**Comment by khiemdnt** [comment]
hello!. 
How did you solve that problem?

**Comment by migueljr13** [comment]
hello! Yes. I achieved, @khiemdnt. 

Thanks.

**Comment by adapana** [comment]
@migueljr13 can you share how did you make it work?
I am facing the same issue.
