### ISSUE TITLE
Documentation link not opening

### ISSUE THREAD

**Issue by gleb-it** [PhilJay/MPAndroidChart#5263]
I'm trying to open documentation link from Read.me (https://weeklycoding.com/mpandroidchart/) but getting timeout error. I tried to open link from different browsers and vpn also, but still can't open it. Could you help me?

**Comment by MGaetan89** [comment]
Until the link works again, the documentation can still be accessed from the [wiki](https://github.com/PhilJay/MPAndroidChart/wiki) (open the navigation on the right to access it)

**Comment by gleb-it** [comment]
Thank you very much!
