### ISSUE TITLE
Cubic LineChart with 3 values or less

### ISSUE THREAD

**Issue by svasic** [PhilJay/MPAndroidChart#528]
I'm facing a bug in v2.0.9 version of library. LineCharts with 3 or less values are not drawn properly. If I draw y values, they are visible on proper places, but line itself with fill is not visible.

**Comment by romangromov** [comment]
Hi @PhilJay, same issue here for me

**Comment by PhilJay** [comment]
Allright, what does "not properly" mean? Please post a screenshot or something :-)

**Comment by svasic** [comment]
This is what i get ... as seen from the picture, values (Y labels) are drawn on proper places but chart is not there. Actually there is some strange line on bottom of the chart, but that is not what it should look like. Highlights are also shown on proper place like labels. 

![image](https://cloud.githubusercontent.com/assets/9920953/7061433/30adf7aa-de92-11e4-8c9c-1bb8ab3c28c8.png)

**Comment by svasic** [comment]
and if I add a fourth value to the data, the whole chart is drawn like it should be. actually I just realized that the last Y label is not drawn ... so one more thing to fix. sry :)
![image](https://cloud.githubusercontent.com/assets/9920953/7061536/96fa20aa-de93-11e4-9d95-d66ac3824f55.png)

**Comment by PhilJay** [comment]
Unfortunately I cannot reproduce the issue. Form me all draws perfectly. 

Please post your chart setup and your Android version. Are you sure you are using v2.0.9 of the library?

**Comment by svasic** [comment]
Yes, I use v2.0.9 and a lot of setup methods. I'll try to disable some of them to be sure that they do not interfere with each other. I'll be back :)

**Comment by svasic** [comment]
I think i found it ... problem appears when i use setDrawCubic(true) on LineDataSet ... i could not use it if the data has 3 or less values, but probably the best solution would be to fix it in the library.
Can you reproduce this bug now?

**Comment by PhilJay** [comment]
@romangromov do you also use cubic lines?

**Comment by romangromov** [comment]
@PhilJay yes, I'm using code below and line chart is not drawing (only points and axis are visible, but not chart line)

```
public class MainActivity extends ActionBarActivity {

    private LineChart mChart;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mChart = (LineChart) findViewById(R.id.chart);

        setData(3, 10);

        mChart.animateX(2500);
    }

    private void setData(int count, float range) {

        ArrayList<String> xVals = new ArrayList<String>();
        for (int i = 0; i < count; i++) {
            xVals.add((i) + "");
        }

        ArrayList<Entry> yVals = new ArrayList<Entry>();

        for (int i = 0; i < count; i++) {

            float mult = (range + 1);
            float val = (float) (Math.random() * mult) + 3;// + (float)
            // ((mult *
            // 0.1) / 10);
            yVals.add(new Entry(val, i));
        }

        // create a dataset and give it a type
        LineDataSet set1 = new LineDataSet(yVals, "DataSet 1");
        set1.setDrawCubic(true);

        ArrayList<LineDataSet> dataSets = new ArrayList<LineDataSet>();
        dataSets.add(set1); // add the datasets

        // create a data object with the datasets
        LineData data = new LineData(xVals, dataSets);

        // set data
        mChart.setData(data);
    }

}
```

**Comment by PhilJay** [comment]
Yes, I will look into the issue. If it's a problem for now, simply disable cubic and it should draw fine!

Best regards,
Phil

**Comment by PhilJay** [comment]
Please try the latest commit and see if it works now!

**Comment by svasic** [comment]
It works for me! 
Thank you @PhilJay
