### ISSUE TITLE
How to custom this chart? Pls help

### ISSUE THREAD

**Issue by sontranit1996** [PhilJay/MPAndroidChart#5287]
I want to create a chart like this? Pls give me key word or give me a link if you have any question.
Many thanks
![future](https://user-images.githubusercontent.com/65209512/161942642-998ecc25-74b4-44c8-99bc-5cdea93ac6e4.PNG)

**Comment by gs666** [comment]
It seems like a common chart has a mirror on bottom.If you don't change library code,you can just use another chart below origin chart,just has different color and direction...

**Comment by sontranit1996** [comment]
Thank you, I have done this chart with BarChart and Negative value
