### ISSUE TITLE
LineChart with axis range specified: buggy while filled

### ISSUE THREAD

**Issue by fredydoss** [PhilJay/MPAndroidChart#530]
![screen shot 2015-04-08 at 15 42 39](https://cloud.githubusercontent.com/assets/2931755/7046449/210fe894-de06-11e4-8fb5-7d437b5d6b42.png)

Condition:
SetAxisMaxValue 35 and SetAxisMinValue -15 with setStartAtZero(false)

The chart doesn't not fill from the 0 ( y axis value ) of the leftAxis but instead it gets filled from the Y zero.

But it works perfectly well when I have entries with both positive and negative values.

![screen shot 2015-04-08 at 15 41 05](https://cloud.githubusercontent.com/assets/2931755/7046436/0b1e9cf6-de06-11e4-8835-15144ecc3b13.png)
![screen shot 2015-04-08 at 15 41 12](https://cloud.githubusercontent.com/assets/2931755/7046446/18340d0e-de06-11e4-9f08-f6af1c3878e7.png)

Problem occurs only when I have all entries as positive or all entries as negative.

**Comment by PhilJay** [comment]
This is actually expected behaviour.

Check out the `FillFormatter` interface.

This interface allows you to define where the filling line should end.
Just create your own  `FillFormatter` class that implements that interface ant set it to the `LineChart`.

```java
lineChart.setFillFormatter(new MyFillFormatter());
```

**Comment by fredydoss** [comment]
Awesome !!!
