### ISSUE TITLE
How to hide or remove the top label of the radarChat

### ISSUE THREAD

**Issue by WestMyna** [PhilJay/MPAndroidChart#5307]
I have been implementing radar chart
I have tried to call   RadarDataSet(entries1, "") 
but the top square is still there
I want the way to end

**Comment by gs666** [comment]
the top square is the "Legend"。

you can use below code to hide it。

`chart.getLegend().setEnabled(false);`

**Comment by WestMyna** [comment]
> the top square is the "Legend"。
> 
> you can use below code to hide it。
> 
> `chart.getLegend().setEnabled(false);`

thank you very much

**Comment by WestMyna** [comment]
I'm glad this problem has been solved
