### ISSUE TITLE
A question about the X-axis

### ISSUE THREAD

**Issue by OhPeterPan** [PhilJay/MPAndroidChart#5311]
Now I have two LineDataSet of different sizes that replace each other, but after the replacement, the x-axis always takes the ticks of the first LineDataSet as the total; the effect I want is that every time a new LineDataSet is replaced, it is replaced by the inside data to redraw the x-axis, what should I do? If anyone knows, thanks in advance

**Comment by gs666** [comment]
maybe you can try `x.resetAxisMaximum()` before you redraw x-axis

**Comment by OhPeterPan** [comment]
> maybe you can try `x.resetAxisMaximum()` before you redraw x-axis

Still no, but thank you

**Comment by cmy82** [comment]
If you're only showing one dataset at a time, have two different charts and show/hide them as needed.

**Comment by OhPeterPan** [comment]
> If you're only showing one dataset at a time, have two different charts and show/hide them as needed.
