### ISSUE TITLE
Animation issue (since 2.0.9?)

### ISSUE THREAD

**Issue by xizzhu** [PhilJay/MPAndroidChart#532]
With the demo app (version 2.0.9), if you open "BarChart inside ListView" or "Multiple charts inside ListView", you'll notice the bar chart is first rendered in full height, then start animation. I didn't remember see this earlier.

**Comment by PhilJay** [comment]
Yes, there are issues. I have just discovered some myself and I am working on resolving them.
If it's a big problem just revert back to 2.0.8 until 2.1.0 is out.

Best regards,
Phil

**Comment by PhilJay** [comment]
I did some fixes regarding that, should be fine now.
