### ISSUE TITLE
getVisibleRange()?

### ISSUE THREAD

**Issue by AlBirdie** [PhilJay/MPAndroidChart#534]
Is there a way to get the visible range (start x, end x) from any given chart?

I've been looking for areas where I can implement such a method, but given that zooming and panning a chart works by modifying the Matrix, I'm having a hard time finding a solution to this.

This range is a pre-requisite for things like percentage based y axes and chart annotations regarding the last visible x value.

**Comment by PhilJay** [comment]
Those methods already exist, check the `misc` documentation: https://github.com/PhilJay/MPAndroidChart/wiki/Miscellaneous

They are called `getLowestVisibleXIndex()` and `getHighestVisibleXIndex()`.

**Comment by AlBirdie** [comment]
Excellent! Thanks a lot Phil!
