### ISSUE TITLE
PieChart: label text cluttered 

### ISSUE THREAD

**Issue by honglu-intel** [PhilJay/MPAndroidChart#535]
Thanks for the great work.

I run into a problem of the pie chart, when some of the slices are small (say <5%), their label could be overlap and clutter together. 

Is there a way to turn off the label only for small slices? I still what to show the lable and value for bigger slices though.

thanks a lot.

**Comment by PhilJay** [comment]
Are you talking about the y-values (the percent values)?

If so, yes you can, simply create a custom `ValueFormatter`, example:

```java
public class MyValueFormatter implements ValueFormatter {

    private DecimalFormat mFormat;
    
    public MyValueFormatter() {
        mFormat = new DecimalFormat("###,###,###,##0.0");
    }
    
    @Override
    public String getFormattedValue(float value) {

        if(value < 5) return "";
        else return mFormat.format(value) + " &";
    }
}
```

Dont't forget to call `pieChart.setUsePercentValues(true)`

**Comment by honglu-intel** [comment]
Thanks a lot for the quick reply!!

One other detail, when I use data.setDrawValues(false), and only draw x labels. 
The text of x labels are slight off the center, toward the top of the slice in the piechart.
If I only display the y-value, same thing.
It seems the bottom of the label's textView is placed on the center of the slice.
I try the demo app from play store, some thing.

**Comment by PhilJay** [comment]
Please give it another try, I fixed something.

**Comment by honglu-intel** [comment]
It looks better, especially for larger slice. Thanks!

**Comment by danielgindi** [comment]
@PhilJay I think we should generate new screenshots for the Pie chart ;-)

**Comment by sakshi5724** [comment]
@PhilJay 
how i set a slice either if the value for two slices is 0. it should not be overlap
plz help me
