### ISSUE TITLE
jitpack.io is down

### ISSUE THREAD

**Issue by rtsisyk** [PhilJay/MPAndroidChart#5366]
```
* What went wrong:
9 actionable tasks: 9 executed
Execution failed for task ':mergeGoogleBetaNativeLibs'.
> Could not resolve all files for configuration ':googleBetaRuntimeClasspath'.
   > Could not resolve com.github.devnullorthrow:MPAndroidChart:3.2.0-alpha.
     Required by:
         project :
      > Could not resolve com.github.devnullorthrow:MPAndroidChart:3.2.0-alpha.
         > Could not get resource 'https://www.jitpack.io/com/github/devnullorthrow/MPAndroidChart/3.2.0-alpha/MPAndroidChart-3.2.0-alpha.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/devnullorthrow/MPAndroidChart/3.2.0-alpha/MPAndroidChart-3.2.0-alpha.pom'. Received status code 521 from server: 
```

Please relocate to another hosting...

<img width="1114" alt="screenshot" src="https://user-images.githubusercontent.com/1799054/209139809-0414e05f-5369-476f-8039-c2358d133b0d.png">

**Comment by asmodeoux** [comment]
same here, please ping me when it starts working 🙏🏻

**Comment by MoeHamoud** [comment]
same, any updates?

**Comment by asmodeoux** [comment]
Someone might try to use this instruction to make our own working fork of it on Maven: https://gist.github.com/cleberjamaral/6c9b0a615e51e26c94ffe407a641f531

**Comment by asmodeoux** [comment]
Or this one, this one even looks easier: https://vegeta2102.medium.com/how-to-publish-android-library-to-github-package-as-a-maven-repository-4709de7608ab

If someone can do this we could finally switch to a better repo once and forever

**Comment by Jbwzx** [comment]
Seems like its back online on jitpack @asmodeoux

**Comment by Rolf-Smit** [comment]
@PhilJay see my comment here: https://github.com/PhilJay/MPAndroidChart/issues/5139#issuecomment-1363870274

I think it is about time to move to a more reputable repository such as Maven Central to avoid issues like this in the future. Or consider publishing the library to both repositories.

**Comment by hannesa2** [comment]
@rtsisyk gitpack.io is back again. Please close this issue to reduce noise
