### ISSUE TITLE
HorizontalBarChart value formatted overflow

### ISSUE THREAD

**Issue by gavabri** [PhilJay/MPAndroidChart#537]
I have an horizontal barchart which dataset contains values of type long. I use a ValueFormatter to  build a string such:

#total-hours:#minutes:#seconds

I set chart to draw values above bars and in some cases value overflows on the right. 
If i set to not draw values above bars it overflows on the left.
Any suggestion?

Thanks for you library
![mp](https://cloud.githubusercontent.com/assets/10604466/7083344/cf1710a6-df60-11e4-841e-1525bd1f6ee1.jpg)

**Comment by PhilJay** [comment]
Yes, you can simply increase the top-space on the axis: https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-(YLabels)

```java
chart.getAxisLeft().setSpaceTop(25f);
```
