### ISSUE TITLE
LineChart.moveViewToX() resets Y-Axis

### ISSUE THREAD

**Issue by Jantleing** [PhilJay/MPAndroidChart#539]
When "setDragEnabled(true)" and "setScaleEnabled(true)", zooming into the graph and dragging it vertically so that Y-Axis begins at other value than "0", then calling "LineChart.moveViewToX()" resets Y-Axis to "0". Expected behaviour would be to not change Y-Axis at all.

**Comment by danielgindi** [comment]
I think this was fixed a week ago. Please try again.
