### ISSUE TITLE
Horizontal scrolling 

### ISSUE THREAD

**Issue by HamzaGhazouani** [PhilJay/MPAndroidChart#54]
Hello PhilJay, thank you for your library is too great.
I would like to know if your library allows horizontal scrolling ? 
I changed the layout but it's not worked :  

![capture d ecran 2014-08-22 a 12 10 15](https://cloud.githubusercontent.com/assets/2019146/4009510/65637f04-29e5-11e4-8e4f-91c49958a4c7.png)

Thank you

**Comment by asrin475** [comment]
Hi PhilJay, Thanks for you wonderful library.
the chart disappears when it within the scroll layout. do you have any solution?
Thanks!.
