### ISSUE TITLE
how to set double xAxis

### ISSUE THREAD

**Issue by whiterye** [PhilJay/MPAndroidChart#540]
now i want to set double xaxis but i do not know how to set

**Comment by PhilJay** [comment]
Documentation: https://github.com/PhilJay/MPAndroidChart/wiki/XAxis-%28XLabels%29

If you want the x-axis to appear on both sides, call:

`chart.getXAxis().setPosition(XAxisPosition.BOTH_SIDED);`

**Comment by whiterye** [comment]
Thanks, I know this method.
But in fact ,I want two x-axises to appear on one side.
