### ISSUE TITLE
LineChart.moveViewToX(0) messes up graph.

### ISSUE THREAD

**Issue by Jantleing** [PhilJay/MPAndroidChart#541]
This is a different issue with moveViewToX() than the one filed before!

Calling `LineChart.moveViewToX(0)` before or directly after adding the **first** Entry messes up the Graph. Nothing is displayed (no Data, no X-Axis), even after adding more Entries. Also after zooming vertically Y-Axis and Gridlines disappear.

```java
    public void addSingleData(float temp) {

        // calling moveViewToX() before adding element:
        // if (mData.getXValCount() == 0)  mChart.moveViewToX(0);  // this breaks Chart
        // if (mData.getXValCount() == 0)  mChart.moveViewToX(5);  // moving to any other X seems to work OK
        // if (mData.getXValCount() > 0)  mChart.moveViewToX(0);   // moving to X=0 with more than 0 entries seems to work OK

        mData.addXValue(mData.getXValCount() + "");
        mDataSet.addEntry(new Entry(temp, mDataSet.getEntryCount()));
        mChart.notifyDataSetChanged();

        // calling moveViewToX() after adding element
        // if (mData.getXValCount() == 1)  mChart.moveViewToX(0);  // this breaks Chart
        // if (mData.getXValCount() == 1)  mChart.moveViewToX(5);  // seems to work OK
        // if (mData.getXValCount() > 1)  mChart.moveViewToX(0);  // seems to work OK

        mChart.invalidate();
    }
```

Graph and Data have basically been setup like this:

```java
    private LineChart mChart;
    private LineData mData;
    private LineDataSet mDataSet;

    private void setupChart(){

        mDataSet = new LineDataSet(null, "Sensor  1");

        mData = new LineData();
        mData.addDataSet(mDataSet);

        mChart = (LineChart) findViewById(R.id.chart1)
        mChart.setData(mData);
    }
```
Of course there has been more code like formatting for Graph and LineData, but commenting it out didn't solve or change the issue.

One more thing I noticed (maybe another different issue?): 
Zooming vertically messes up Y-Axis when there is exactly 1 Entry in DataSet even without calling `moveViewToX(0)` before

**Comment by PhilJay** [comment]
Which version are you using?

**Comment by Jantleing** [comment]
It is latest Master Sources which I use. I experienced the issue also in version 2.0.9 as library, which was the reason to download and use latest sources.

**Comment by PhilJay** [comment]
Unfortunately I cannot reproduce your issue. I have tried in the example app with the `DynamicalDataAddingActivity` and there it works fine: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/DynamicalAddingActivity.java

Try with in-commenting this: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/DynamicalAddingActivity.java#L74-78

**Comment by Jantleing** [comment]
Thanks for testing!  
I tried your example app and it worked fine, so I looked for differences..
In my app I added entries directly to LineDataSet instead of passing it to LineData.
After replacing line 69
https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/DynamicalAddingActivity.java#L69
```java
data.addEntry(new Entry((float) (Math.random() * 10) + 50f, set.getEntryCount()), randomDataSetIndex);
```
by 
```java 
set.addEntry(new Entry((float) (Math.random() * 10) + 50f, set.getEntryCount()));
``` 
you should be able to reproduce the issue with calling `mChart.moveViewToX(0)`  after  `mChart.notifyDataSetChanged();`

**Comment by danielgindi** [comment]
https://github.com/PhilJay/MPAndroidChart/issues/539

**Comment by danielgindi** [comment]
You should try with the latest version
