### ISSUE TITLE
Tap on chart moves chart view to the left

### ISSUE THREAD

**Issue by gavabri** [PhilJay/MPAndroidChart#546]
I have horizontal barchart set as follow:

mChart.setDoubleTapToZoomEnabled(false);
mChart.setScaleEnabled(false);
mChart.setHighlightEnabled(false);
mChart.getLegend().setEnabled(false);

The charts shows correctly but if i tap on the chart area (pic 1) both on the bar or on the white area,
the chart view moves to the left (pic 2).
I have 3 charts in a viewpager but the problem occurs in the first page only

Don't know if it is related but If i set animation
mChart.animateY(2500);
the view chart shows already moved to the left (pic 2)

![1](https://cloud.githubusercontent.com/assets/10604466/7107208/59be7fe2-e15e-11e4-8614-822b36c79643.png)
![2](https://cloud.githubusercontent.com/assets/10604466/7107209/5c24942e-e15e-11e4-94af-96c482757408.png)

**Comment by PhilJay** [comment]
Please post your full chart setup.

**Comment by gavabri** [comment]
Here is the complete chart setup

	public void setupChart()
	{
		mChart.setOnChartValueSelectedListener(this);
		mChart.setDrawBarShadow(false);

		mChart.setDrawValueAboveBar(true);
		mChart.setViewPortOffsets(0f, 0f, 100f, 0f);

		mChart.setDescription("");

		mChart.setMaxVisibleValueCount(60);

		mChart.setPinchZoom(false);
		mChart.setDrawGridBackground(false);

		mChart.setDoubleTapToZoomEnabled(false);

		mChart.setScaleEnabled(false);

		mChart.setHighlightEnabled(false);

		XAxis xl = mChart.getXAxis();		
		xl.setPosition(XAxisPosition.BOTTOM);
		xl.setDrawAxisLine(false);
		xl.setDrawGridLines(false);
		xl.setGridLineWidth(0.3f);

		YAxis yl = mChart.getAxisLeft();
		yl.setDrawLabels(false);
		yl.setDrawAxisLine(false);
		yl.setDrawGridLines(false);
		yl.setGridLineWidth(0.3f);	
		yl.setSpaceTop(35f);

		YAxis yr = mChart.getAxisRight();
		yr.setDrawLabels(false);
		yr.setDrawAxisLine(true);
		yr.setDrawGridLines(false);		

		setData();
		//mChart.animateY(2500);

		Legend l = mChart.getLegend();
		l.setPosition(LegendPosition.BELOW_CHART_LEFT);
		l.setFormSize(8f);
		l.setXEntrySpace(4f);

		mChart.invalidate();
	}

**Comment by PhilJay** [comment]
By calling this `mChart.setViewPortOffsets(0f, 0f, 100f, 0f)` you are removing all offsets. THis is the reason why your data overdraws the axis.
