### ISSUE TITLE
LineChart circles truncated for Max/Min Y values

### ISSUE THREAD

**Issue by Maragues** [PhilJay/MPAndroidChart#548]
I'm using a LineChart with some of the Y values placed at the Max/Min edge , but the circles drawn are truncated

![device-2015-04-13-122342](https://cloud.githubusercontent.com/assets/655970/7113864/45b8c65e-e1d8-11e4-99e0-b0855291e329.png)

I've tried setting a padding, but the chart doesn't use it, and I don't see which piece of the code I'd need to touch.

**Comment by PhilJay** [comment]
Have a look at the documentation: https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-(YLabels)

Specifically, these four methods:

 - <code>setAxisMaxValue(float max)</code>: Set a custom maximum value for this axis. If set, this value will not be calculated automatically depending on the provided data. 
 - <code>setAxisMinValue(float min)</code>: Set a custom minimum value for this axis. If set, this value will not be calculated automatically depending on the provided data. 
 - <code>setSpaceTop(float percent)</code>: Sets the top spacing (in percent of the total axis-range) of the highest value in the chart in comparison to the highest value on the axis. 
 - <code>setSpaceBottom(float percent)</code>: Sets the bottom spacing (in percent of the total axis-range) of the lowest value in the chart in comparison to the lowest value on the axis. 

Also, be aware of `setStartAtZero(...)`
