### ISSUE TITLE
Candlestick chart indicators?

### ISSUE THREAD

**Issue by rchockxm** [PhilJay/MPAndroidChart#549]
Hi, Phil,

Do you have any plans on Candlestick chart in the future?
I was wondering, is there any plan to add indicators feature?

We are a forex trader and happy to uses MPAndroidChart library for our project.

Regards,
Rchockxm

**Comment by PhilJay** [comment]
What do you mean by inidcators exactly?

**Comment by mesropd** [comment]
I have a project with rich support of candlestick charts, I planned to add many features to it, so if you clarify which indicators you need, maybe I will implement it

**Comment by rchockxm** [comment]
Hi, Phil,

Thank you for your prompt reply.

I found some Javascript library for this feature.

https://github.com/amih/Candlestick.js/tree/master
http://www.highcharts.com/plugin-registry/single/24/Indicators

Indicators: BB, MACD, SMA, EMA, RSI, ATR

https://www.quantconnect.com/forum/discussion/416/indicator-examples-bb-macd-sma-ema-rsi-atr/p1

Regards,
Rchockxm

**Comment by rchockxm** [comment]
Hi, Mesrop,

I am happy to hear that you are doing well.

I need an indicator with BB, MACD, SMA, EMA, RSI, ATR.

https://www.quantconnect.com/forum/discussion/416/indicator-examples-bb-macd-sma-ema-rsi-atr/p1

Regards,
Rchockxm

**Comment by mesropd** [comment]
Hi, of course we need indicators, but will implement during next month, if you also don't need it soon, could wait )

**Comment by rchockxm** [comment]
Hi, Mesrop,

Thank you for your prompt reply.
I will be waiting for you.

Regards,
Rchockxm

**Comment by AlBirdie** [comment]
Implementing indicators for finance data is actually quite straightforward and shouldn't be included in MPAndroidCharts as indicators don't require any specific chart drawing. All you need to do is calculate your indicator data points and just draw the charts with them. In case of the MACD, just create a combinedchart, and add a BarDataSet for the histogram, plus two LineDataSets for the MACD line and the trigger line.
That's already fully supported by MPAndroidCharts. Finance data calculations isn't anything that should ever be part of a generic charting library.

**Comment by mesropd** [comment]
Yes it's right, indicators are separate data sets that we can combine, but I think that it will be good to have functions to generate those data sets.

**Comment by AlBirdie** [comment]
I don't quite understand what you mean with that. Generating indicator data sets isn't any different from generating data sets for any other chart, why would you need a function for that?
Mind that I'm not a contributer to this library, I'm just giving my opinion about having such functionality in a generic chart library.
