### ISSUE TITLE
how to invalidate charts in listview?

### ISSUE THREAD

**Issue by nbau21** [PhilJay/MPAndroidChart#550]
I have a bunch of charts set in a listview, and I'm trying to have them all refresh on a button click from the activity. Is there a way to have all these charts refresh together?

My code is similar to the one in the example code for multiple charts in a list.

**Comment by PhilJay** [comment]
Thats basic listview stuff and has nothing to do with the lib. Just call notifyDataSetChanged() on your adapter.
