### ISSUE TITLE
Unable to remove grey background from charts

### ISSUE THREAD

**Issue by rajatdeshpande** [PhilJay/MPAndroidChart#552]
Hi I am using

v2.0.9 

BarChart summaryChart;
summaryChart.setBackgroundColor(Color.WHITE); 

Does not change the background to white. I have also tried 

<com.github.mikephil.charting.charts.LineChart
                android:id="@+id/new_chart"
                android:layout_width="match_parent"
                android:layout_height="200dp"
                android:background="@android:color/transparent"/>

this also does not change the background to transparent.

Please help.

Regards,

Rajat

**Comment by PhilJay** [comment]
Did you also call

`chart.setDrawGridBackground(false)`

It's in the documentation: https://github.com/PhilJay/MPAndroidChart/wiki/Getting-Started

**Comment by rajatdeshpande** [comment]
Hi,

Yes I did. Is that a problem?

Thanks,

Rajat

On Wed, Apr 15, 2015 at 1:33 PM, Philipp Jahoda <notifications@github.com>
wrote:

> Did you also call
>
> chart.setDrawGridBackground(false)
>
> It's in the documentation:
> https://github.com/PhilJay/MPAndroidChart/wiki/Getting-Started
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PhilJay/MPAndroidChart/issues/552#issuecomment-93252029>
> .
>



-- 
Rajat Deshpande
Mechanical Engineering
IIT BOMBAY

**Comment by rajatdeshpande** [comment]
Edit - I didn't call setDrawGridBackground(false)

I called setDrawGridLines(false)

On Wed, Apr 15, 2015 at 2:32 PM, Rajat Deshpande <rajatdeshpande@gmail.com>
wrote:

> Hi,
>
> Yes I did. Is that a problem?
>
> Thanks,
>
> Rajat
>
> On Wed, Apr 15, 2015 at 1:33 PM, Philipp Jahoda <notifications@github.com>
> wrote:
>
>> Did you also call
>>
>> chart.setDrawGridBackground(false)
>>
>> It's in the documentation:
>> https://github.com/PhilJay/MPAndroidChart/wiki/Getting-Started
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/PhilJay/MPAndroidChart/issues/552#issuecomment-93252029>
>> .
>>
>
>
>
> --
> Rajat Deshpande
> Mechanical Engineering
> IIT BOMBAY
>



-- 
Rajat Deshpande
Mechanical Engineering
IIT BOMBAY

**Comment by rajatdeshpande** [comment]
Solved, Thanks! didn't spot this is in the documentation

Solved this by calling setDrawGridBackground(false)
