### ISSUE TITLE
LineDataSet: shader vs. paint color

### ISSUE THREAD

**Issue by svasic** [PhilJay/MPAndroidChart#557]
Hi @PhilJay !

I'm facing a problem when drawing linechart with 2 datasets and with different fill colors. Because I want to have gradient fill, I'm setting shader on mRenderPaint which works fine. Problem appears when I want to have different color for 2nd dataset which works fine when not using Shader. 
Based on Shader documentation, this is not posible, because paint will always use color which is set on shader. 

From Shader documentation: "... A subclass of Shader is installed in a Paint calling paint.setShader(shader). After that any object (other than a bitmap) that is drawn with that paint will get its color(s) from the shader."

So, I am wondering if there is any posibility to improve library in a way that we can use different shaders for each dataset? 
Sory for my bad english ... I hope this makes sense to you.

As always, thanks for your effort!
Best regards

**Comment by PhilJay** [comment]
Currently there is no option to set a shader for a specific dataset. But I will consider adding that in the future.

**Comment by svasic** [comment]
Thank you! :+1:

**Comment by PhilJay** [comment]
http://www.polyglotprogramminginc.com/adding-gradients-to-android-graphs-with-mpandroidchart-and-decoview/

**Comment by PhilJay** [comment]
<code>setFillDrawable(Drawable d)</code>: Sets a `Drawable` that should cover the fill-area. This also allows to use gradients.
