### ISSUE TITLE
HorizontalBarChart: xAxis values Above 

### ISSUE THREAD

**Issue by yuliya-tarasenko** [PhilJay/MPAndroidChart#558]
Is it possible to display xAxis values above the corresponding HorizontalBarChart rows?

**Comment by PhilJay** [comment]
I'm not exactly sure what you mean? Could you provide an example?

**Comment by yuliya-tarasenko** [comment]
Something like: http://ozuxgylhmuxgg3y.cmle.ru/wp-content/uploads/2014/12/Screen-Shot-2014-12-08-at-5.53.13-PM.png
In case labels are too long.

**Comment by PhilJay** [comment]
Sorry but I somehow can't access the file :-)

**Comment by yuguseva** [comment]
![screen-shot-2014-12-08-at-5 53 13-pm](https://cloud.githubusercontent.com/assets/10737751/7161206/966a30e6-e396-11e4-8486-95e3ffdac2ea.png)

**Comment by PhilJay** [comment]
Thanks, and unfortunately that is not possible yet. You will have to code that yourself somehow.

**Comment by yuguseva** [comment]
Ok, thank you.
