### ISSUE TITLE
How to remove text from piechart slice

### ISSUE THREAD

**Issue by narendrakothamire** [PhilJay/MPAndroidChart#559]
I dont want text on slice of piechart but besides it with an arrow pointing to that slice like this this image
![pie2](https://cloud.githubusercontent.com/assets/11056951/7174537/71d209ac-e427-11e4-8d37-122f5f5c250b.jpg)

**Comment by PhilJay** [comment]
Currently not supported.

**Comment by dheerajsinghrathore** [comment]
> Currently not supported.

![screenshot_20190104-130158_2](https://user-images.githubusercontent.com/24730424/50677828-00cedc00-1022-11e9-99f8-1fb7b272efb9.png)


How to remove text from label ? not from Description
