### ISSUE TITLE
Wrong plot when setAxisMaxValue and setAxisMinValue are set

### ISSUE THREAD

**Issue by mesropd** [PhilJay/MPAndroidChart#560]
I add values greater than 1, and set min/max values for the YAxis
```java
        YAxis rightAxis = chart.getAxisRight();
        rightAxis.setTextColor(Color.parseColor("#737888"));
        rightAxis.setTextSize(12);
        rightAxis.setStartAtZero(false);
        rightAxis.enableGridDashedLine(4.0f, 4.0f, 0);
        rightAxis.setGridLineWidth(1.0f);
        rightAxis.setAxisMaxValue(0.2f);
        rightAxis.setAxisMinValue(0.1f);
```
Here is the screenshot. Is this is a bug or I did something incorrect? I use latest code from master without modification.
![screenshot_2015-04-16-10-23-00](https://cloud.githubusercontent.com/assets/8722637/7175401/5323bbd8-e425-11e4-99af-a3f1de9b2050.png)

**Comment by PhilJay** [comment]
Are you using a custom format for the displayed entry value?

**Comment by mesropd** [comment]
No I don't use, but probably this is a bug, because it goes if I added this code, same for left axis, though it is disabled
```java
chart.getAxisLeft().setEnabled(false);
chart.getAxisLeft().setStartAtZero(false);
chart.getAxisLeft().setAxisMinValue(0.1f);
chart.getAxisLeft().setAxisMaxValue(0.2f);
```
Also I noticed this issue, the app has entries, that differ from each other by 0.0001 or closer that, here is the plot for this code
```java
YAxis rightAxis = chart.getAxisRight();
rightAxis.setStartAtZero(false);
chart.getAxisLeft().setEnabled(false);
```
You see that it is almost a straight line, but the entries differ from each other about 0.0001
![screenshot_2015-04-16-13-15-43](https://cloud.githubusercontent.com/assets/8722637/7177876/32f13fe6-e43b-11e4-9405-a59a7a314afe.png)


But if I change to this I get this plot
```java
YAxis rightAxis = chart.getAxisRight();
rightAxis.setStartAtZero(false);
chart.getAxisLeft().setEnabled(false);
chart.getAxisLeft().setStartAtZero(false); //This line was added, though left axis is disabled
```
![screenshot_2015-04-16-13-13-48](https://cloud.githubusercontent.com/assets/8722637/7177893/6b5dd1c8-e43b-11e4-9d09-93aacf113a64.png)

**Comment by PhilJay** [comment]
Now I see. You did not set the axis-dependency for your dataset. Set it to `AxisDependency.RIGHT`

**Comment by mesropd** [comment]
Thanks :)
