### ISSUE TITLE
How to change chart's description color and position?

### ISSUE THREAD

**Issue by borwoj** [PhilJay/MPAndroidChart#563]
`barChart.setDescription("desc");`

Is there any way to change the description color from the default black?

Also, is there a way to reposition the description in a similar way as with the `XAxis` class? - `xAxis.setPosition(XAxis.XAxisPosition.BOTTOM)`. Currently it's in the bottom right corner by default.

**Comment by PhilJay** [comment]
Yes, you need to get the description `Paint` and then can change the color:

```java
Paint p = chart.getPaint(Chart.PAINT_DESCRIPTION);
p.setColor(...);
```

Concerning the position, there is currently no option to change that.

**Comment by PhilJay** [comment]
Update: I just added some methods that should allow that:

 - setDescriptionPosition(...)
 - setDescriptionColor(...)

**Comment by blasian** [comment]
@PhilJay Do you know if setDescriptionPosition: been added to the iOS version as well? I can't seem to find it :/

**Comment by ashishrg** [comment]
how to change color of text of second argument passed in BarDataSet? If I define a BarDataSet like this and want to change color of the text that displays description from default black to White then how would I achieve it?

BarDataSet barDataSet2 = new BarDataSet(valueSet2, "Incorrect");
barDataSet2.setValueTextSize(12f);

In above code snippet, I want to change color of text "Incorrect" from black to whit. How would I do that?

**Comment by NainalChauhan** [comment]
I want to set description label at top position without giving x and y pixels. Can I achieve this?

**Comment by monoharmayumrohitsharma** [comment]
how can we change the position of yvalue below xvalue

**Comment by hackerAnurags** [comment]
use this lines you can change position and also change color to description.
 barChart.getDescription().setTextColor(Color.RED);
 barChart.getDescription().setPosition(200,100);
