### ISSUE TITLE
Add XY coordinate

### ISSUE THREAD

**Issue by davix10** [PhilJay/MPAndroidChart#564]
Hi,
I am using your library for creating a chart.
I need to set each point in order to get the final curve, but points are not equidistant.

I tried to use your library to solve my problem, but when i have to draw a step i found the following problem:

![screenshot_2015-04-17-10-13-09](https://cloud.githubusercontent.com/assets/6436570/7198299/2fccf6ba-e4eb-11e4-92d6-f3bafbbef3b9.png)

Instead, i need to draw something like the following pic (drawn using matlab). The best would be the blue line, but it can be used also the red one.

![untitled](https://cloud.githubusercontent.com/assets/6436570/7198308/50aa4f4a-e4eb-11e4-9e4c-a35ff81db741.png)

I wonder if there is a way to add also X coordinate. If you have some experience with c#, i would need something like 

chart.Series[0].Points.AddXY (double x, double y);

Thank you very much for your help.

Best regards

davix10

**Comment by PhilJay** [comment]
Just set two entries to the same x-coordinate?

new Entry(50f, 1);
new Entry(60f, 1);

will result in a step from 50 to 60.

**Comment by davix10** [comment]
I am sorry, I am new with android.
I don't get where I should set that entry.
I read 

addXValue(string xVal) void

hence i did not try that before. Btw, now I just tried it and it does not accept the command

data.addEntry(new Entry(50f, 1));

Thank you

**Comment by PhilJay** [comment]
I don't understand what exactly your problem is?

**Comment by jamesporter** [comment]
I think @davix10  wants to be able to set both x and y coordinates for a series of points: i.e. entries should be properly 2 dimensional.

As I understand it this isn't possible at the moment: each chart has a single set of x labels for a set of x coordinates which must be equidistant. You can have many sets of y coordinates (different lines etc) but they must all share x-coordinates (while you can have some missing you can't have two coordinates within a series for the same x coordinate).

While this is sufficient for most purposes it would appear unable to do what you want @davix10

**Comment by davix10** [comment]
This is exactly what @jamesporter said.
I have to draw something like a square signal, where steps can have different time lengths.
Moreover, when I pass from a plateau to the other, it must move vertically, it means that on the same x value i must have two y coordinates.
In matlab I would set it as follows:

t=[0 5 5 7 7 11];
y=[0 0 4 4 3 3];
plot(t,y);

This way I would get a curve with y=0 for 5 seconds, y=4 for 2 seconds and y=3 for 4 seconds.

Thank you

davix10
