### ISSUE TITLE
Chart does not appear inside a ScrollView.

### ISSUE THREAD

**Issue by Adrian-David** [PhilJay/MPAndroidChart#566]
I'm trying to use your library to generate a chart inside a ScrollView, but it never appear.

The only way I get it work is inside a LinearLayout and with fixed height:

-ScrollView (width: match_parent, height: match_parent)
    --LinearLayout (width: match_parent, height: wrap_content)
        ---BarChart (width: match_parent, height: 300dp ie)

There is another way?

**Comment by PhilJay** [comment]
Post your full xml and chart setup.

**Comment by MikeSpitz** [comment]
For anyone else who finds this thread, this is a defect/undocumented behaviour. If you don't see a chart then put it inside a linear layout, as above, and it will work.

PhilJay, for you to recreate simply copy paste your RadarChart example code and change the relevant xml to have a ScrollView as the layouts parent.

**Comment by 127001david** [comment]
When I use LineChart in a ScrollView(like vertical ) I found when I move a little distance on y-axis direction the move event will be thrown to the ScrollView,When i set touchListener on LineChart it called MotionEvent.ACTION_CANCEL.I guess if it is the way you solve the scroll conflict problem but I feel the user experience is not very good.I thank the move distance can be custom or much more longer than now will be better.I think if it can be solve in GestureDetector but failed, it will be nice if you can help me,thanks! : )

**Comment by abrahaj** [comment]
Had the same issue with a BarChart within a RelativeLayout (wrap_content).
Apparently the RelativeLayout should have a height defined.
