### ISSUE TITLE
Slide on chart to move the highlighted value

### ISSUE THREAD

**Issue by MGaetan89** [PhilJay/MPAndroidChart#567]
Would it be possible to enable a slide gesture to be able to move the highlighted values? Unless the chart is zoomed, of course.

**Comment by PhilJay** [comment]
This is already in development: #106

**Comment by PhilJay** [comment]
Now available `chart.setHighlightPerDragEnabled(boolean enabled)`

**Comment by MGaetan89** [comment]
Great! Thank you for this new feature!
