### ISSUE TITLE
Problem aligning values with the xAxis

### ISSUE THREAD

**Issue by OskarPersson** [PhilJay/MPAndroidChart#568]
In my application I have a database with integers given at different times of the day. Now, I want visualize this in a BarChart but I don't know how I should use the indexes and xAxis correctly. I want the values (integers) to be on the yAxis and the time on the xAxis.

Currently I create each entry like this
```
//for each set of stats
ArrayList<BarEntry> barRatingEntries = new ArrayList<>();
for (HashMap<String, String> entry : stats) {
    if (!xVals.contains(entry.get("time"))) {
        xVals.add(entry.get("time"));
    }
    barRatingEntries.add(new BarEntry(Float.valueOf(entry.get("rating")), xVals.indexOf(entry.get("time"))));
}
barDataSet = new BarDataSet(barRatingEntries, question.get("text"));
barDataSets.add(barDataSet);

...

BarData data = new BarData(xVals, barDataSets);
barChart.setData(data);
```

The problem is that values doesn't get placed at the correct time in the chart when I have multiple datasets. I think that the reason might be that all datasets doesn't have a value for each entry in xVals, but I don't know how to solve that.

**Comment by skr-sharma** [comment]
hello developer,,

here i attached the screenshot in which i implement your library, i want to set space in x-axis value (i.e <20 )  from  y-Axis line (i.e 0.0$) i tried   xAxis.setSpaceBetweenLabels(space); but it took space between the x-axis labels string within not from y-axis,
please let me know how to achieve this.. i am looking forward to your response ,
![img_20150419_030856](https://cloud.githubusercontent.com/assets/12004449/7217341/9d2aea66-e642-11e4-91a4-a395b9caf6b8.jpg)

thanks in advance.
