### ISSUE TITLE
I can't move the line chart directly,how can I solve it?

### ISSUE THREAD

**Issue by xubuhang** [PhilJay/MPAndroidChart#569]
Hello! I have a question to ask you. If your chart can move around (x, Y axis at the same time changes), in the case of amplification?
![20150420130055](https://cloud.githubusercontent.com/assets/4189632/7224012/c5a71f4c-e75e-11e4-852a-0c757354d3b3.png)

**Comment by PhilJay** [comment]
I'm not sure what you mean, but check out the documentation concerning interaction with the chart: https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart

Maybe calling `setPinchZoom(false)` solves your problem.

**Comment by xubuhang** [comment]
thank you!
