### ISSUE TITLE
When the screen rotation，view can't invalidate?

### ISSUE THREAD

**Issue by cwangkkb** [PhilJay/MPAndroidChart#570]
<activity android:name="com.kkb.activity.uchart.UNewStudentActivity"
                  android:configChanges="screenSize|orientation|keyboardHidden"
                />
 ArrayList<LineDataSet> sets = (ArrayList<LineDataSet>) line_chart.getData()
                .getDataSets();

        for (LineDataSet set : sets) {
            set.setDrawFilled(true);
            set.setFillColor(getResources().getColor(R.color.line_chart_fill));
        }
line_chart.invalidate();

@Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE) {
            ll_header_normal.setVisibility(View.GONE);
            top_header.setVisibility(View.GONE);
            header.setVisibility(View.GONE);
            new_student_list.setVisibility(View.GONE);
        } else if (newConfig.orientation == Configuration.ORIENTATION_PORTRAIT) {
            ll_header_normal.setVisibility(View.VISIBLE);
            top_header.setVisibility(View.VISIBLE);
            header.setVisibility(View.VISIBLE);
            new_student_list.setVisibility(View.VISIBLE);
        }
    }

There is screenSize ：
the view can't invalidate so when  draw filled only draw portrait width;
THere is no screenSize:
the view can invalidate, draw filled can draw fullscreen width,but beginning with Android 3.2 (API level 13) ,no screenSize, can't call the onConfigurationChanged methon,

Can you understand what I mean?
I hope to help，thanks

**Comment by cwangkkb** [comment]
![Uploading 2.png . . .]()
![Uploading device-2015-04-20-160630.png . . .]()

**Comment by PhilJay** [comment]
Your images are not uploading as it seems, can you retry

**Comment by cwangkkb** [comment]
![2](https://cloud.githubusercontent.com/assets/7898476/7226406/17093bba-e77b-11e4-8c21-6da3010c043f.png)

**Comment by cwangkkb** [comment]
![device-2015-04-20-160630](https://cloud.githubusercontent.com/assets/7898476/7226412/20c7ddaa-e77b-11e4-9a8c-848b38c9e591.png)

**Comment by cwangkkb** [comment]
and the horizontal line i also can't change it color .

**Comment by PhilJay** [comment]
Okay, the issue here is that you are using one of those (or all of those attributes: `android:configChanges="keyboardHidden|orientation|screenSize"`

This bug is already fixed in the latest commit to the master branch, but not fixed in release v2.0.9.
It will be included in the next release version 2.1.0

**Comment by MiaShopgal** [comment]
I set android:configChanges="orientation|screenSize" in the AndroidManifest.
The version of PhilJay:MPAndroidChart is v3.1.0-alpha ( I need IAxisValueFormatter )
I can't keep the chart when onConfigurationChanged been triggered
The chart will show No chart data available. 
Could @PhilJay kindly take a look at this?
