### ISSUE TITLE
not showing message " No chart data available "

### ISSUE THREAD

**Issue by pmvegar** [PhilJay/MPAndroidChart#572]
In my line chart only shows " No chart data available " when the application starts, but then when for example I do not have data for the button 7 days shows me axis and I dont wants this, i want the message " No chart data available " , help me!
![screenshot_2015-04-20-11-33-39](https://cloud.githubusercontent.com/assets/12030979/7227577/029857fc-e752-11e4-8270-cd8eaa4815b7.png)

**Comment by PhilJay** [comment]
I suppose the reason is that somewhere in the data that is set for the chart there are entries. And that's why it doesnt display the message.

**Comment by pmvegar** [comment]
ok thanks you
