### ISSUE TITLE
Limit Number of Line Graph Circles Drawn

### ISSUE THREAD

**Issue by pyraego** [PhilJay/MPAndroidChart#573]
Is there an easy way to limit the number of circles drawn? I have 12 X-Axis points (The 12 months in a year). It seems to be plotting a point for each month. Is there a way to only plot every other point so a total of 6? I am using your standard code from your examples with my own data. Thanks.
![device-2015-04-20-115724](https://cloud.githubusercontent.com/assets/1516560/7234379/b67ef0f8-e754-11e4-92a9-b5f21fd522a7.png)

**Comment by PhilJay** [comment]
Not right now.

However it should not be too difficult to modify the library to support something like this!
