### ISSUE TITLE
Question: Stroking a line

### ISSUE THREAD

**Issue by SjoerdvGestel** [PhilJay/MPAndroidChart#575]
Hi, i've been searching for this some time now...
Is it possible to stroke a line in a graph.

I've got 3 datasets, two of wich are filled and one is not.. the one that's not filled i would love to give it a white stroke of 2-3 px top and bottom so it stands out a little more on the other data sets... is this possible or do i have to make 2 data sets, one wider and white below and one smaller with the other color above it.

thanks!

**Comment by PhilJay** [comment]
Unfortunately there is no way to add a stroke per default. You will have to use a custom solution like the one you proposed.

**Comment by SjoerdvGestel** [comment]
Ah that's just good to know, ill talk with the designer to see if i can change his mind ;) Thanks for the fast response!
