### ISSUE TITLE
Is MPChart support annotations?

### ISSUE THREAD

**Issue by vikky001** [PhilJay/MPAndroidChart#578]
I check this library, Its good. Could you please tell me if its support annotations as well. 
Like in aChart library we had annotations to show values on graph.

Please have a look on attach image for better understanding 
![screenshot_2015-04-22-18-04-31](https://cloud.githubusercontent.com/assets/7021891/7274479/bf2014a4-e91a-11e4-9d7b-b8987ba2a2d8.png)

**Comment by PhilJay** [comment]
Check out this: https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface
Maybe it's what you are looking for.
