### ISSUE TITLE
HorizontalBarChart: xAxis values.

### ISSUE THREAD

**Issue by NeoRaidenX** [PhilJay/MPAndroidChart#579]
Is it possible to modify how the xAxis values are shown? I get the values from server and sometimes the string size is too large and appears like this: 

![img_20150422_130354](https://cloud.githubusercontent.com/assets/3501629/7281791/6b071814-e8f1-11e4-877d-f2efb12b596f.JPG)

Even if I put the text above the bars is not the best solution:

![img_20150422_130330](https://cloud.githubusercontent.com/assets/3501629/7281795/72eb81d2-e8f1-11e4-8c8f-6e8ecf15750c.JPG)

Is it possible to modify the text's view to be from this:
____
____|
____|  TooLargeText Example Foo Bar xAxisValue
____|  

to this?:
_____
_____|  TooLargeText 
_____|  Example Foo 
_____|  Bar xAxisValue

Also another question. Is only Integers available for the barValues?

Thank you. 

Regards.

**Comment by PhilJay** [comment]
The bar values can have any number of digits you want.
Concerning the x-axis values, I suggest you find a way to make them shorter.

**Comment by ivanove** [comment]
Hi dude 

How to do to display bar's value like integer ?
