### ISSUE TITLE
Updating a pie Chart

### ISSUE THREAD

**Issue by bhallacharanjit** [PhilJay/MPAndroidChart#582]
Hi 
I am working with the Pie chart and I need to refresh the chart to new values. But I am not able to do that as the invalidate function that is being called is not refreshing the data. 
Please let me know the solution to this

**Comment by PhilJay** [comment]
That's weird. You will need to show me some code in order for me to be able to help you.
The invalidate function is derived from the `View` class.

**Comment by bhallacharanjit** [comment]
Hey, Sorry I was travelling that is why couldnot respond. And I found it out that was my mistake. I was not providing the instance with the updated value. 
Thanks for the response :D
