### ISSUE TITLE
build Error: causing ' org.gradle.process.internal.ExecException'

### ISSUE THREAD

**Issue by demo-Ashif** [PhilJay/MPAndroidChart#583]
Getting this error after adding MPChartLib as library project. Please give me solution

Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_25\bin\java.exe'' finished with non-zero exit value 2

**Comment by PhilJay** [comment]
Does not seem like an issue related to the library, check your project setup.

**Comment by renatosugimoto** [comment]
I've got the same error.
Even if it's a setup problem you could offer some help showing how to setup the project to support your lib.

**Comment by PhilJay** [comment]
This is not some kind of gradle support platform.
All information that is needed to use this project as a gradle dependency is provided in the readme. With that information, the majority of users get it to work. The ones that don't will have to invest some of their own time and figure it out.

**Comment by renatosugimoto** [comment]
Ok, sorry for bothering you.

**Comment by tevjef** [comment]
Project structure > JDK Location > Change it to a 1.7 version of the jdk.

**Comment by almic** [comment]
@mulukalaabhisek this issue is closed and is unrelated to the library, please refrain from commenting on issues like this, especially just to ask for programming help.
