### ISSUE TITLE
Custom Axis value formatter - more complex styling

### ISSUE THREAD

**Issue by miszmaniac** [PhilJay/MPAndroidChart#584]
Hi,

Would it be possible to get access to access textView containing axis value... for example I'd like to make custom background for last value on axis.

I guess it could be available in valueFormatter, or maybe from some getter method on axis:
```
textView getValueViewForIndex(int index) 
```

**Comment by PhilJay** [comment]
There are no textviews that display the labels. They are just Strings directly rendered to the canvas.
