### ISSUE TITLE
I want to clear the previously drawn chart

### ISSUE THREAD

**Issue by narendrakothamire** [PhilJay/MPAndroidChart#585]
I want to clear the previously drawn chart, and update with new values but calling chart.clear() does nothing.

**Comment by PhilJay** [comment]
Are you using the latest version?
Provide your code.

**Comment by narendrakothamire** [comment]
Yes I m using latest version

I have following method when i call this method again i can see previous chart and then chart animates to display new values


public void initPieChart(){

        pieChart.clearValues();
        pieChart.clear();
        pieChart.animateY(1000);
        pieChart.setDescription("");

        pieChart.getLegend().setEnabled(false);
        pieChart.setDrawSliceText(false);

        ArrayList<String> xVals = new ArrayList<String>();
        ArrayList<Entry> yVals1 = new ArrayList<Entry>();
        ArrayList<Integer> colors = new ArrayList<Integer>();

        colors = getPieChartColors(colors);

        pieChartXAxisTextArrayList.clear();
        for (int i = 0; i < accountVolumeList.size(); i++) {
            yVals1.add(new Entry((Float.parseFloat(accountVolumeList.get(i).getPercentage())), i));
            
            xVals.add(accountVolumeList.get(i).getAccountNo());
            pieChartXAxisTextArrayList.add(new PieChartXAxisText(colors.get(i),accountVolumeList.get(i).getAccountNo()));

        }
        pieChartXAxisTextAdapter.notifyDataSetChanged();

        PieDataSet dataSet = new PieDataSet(yVals1, "");
        dataSet.setSliceSpace(0);
        dataSet.setSelectionShift(5f);


       

        dataSet.setColors(colors);

        PieData data = new PieData(xVals, dataSet);
        data.setValueFormatter(new PercentFormatter());
        data.setValueTextSize(11f);

        data.setValueTextColor(Color.BLACK);
        pieChart.setData(data);

        pieChart.highlightValues(null);
        pieChart.invalidate();
    }

infact i have seen that even if i call it once it chart shows and then it animates 

Thanks

**Comment by anismarzouk** [comment]
https://github.com/PhilJay/MPAndroidChart/issues/496

**Comment by KishanMevada** [comment]
Actually, you do not need to clear chart. you need to clear the LIST you pass in, while setting up chart, it worked in my case.
