### ISSUE TITLE
Ask, can BarChart style looks set to do this? Thanks

### ISSUE THREAD

**Issue by 120660021** [PhilJay/MPAndroidChart#587]
Rounded top
![qq 20150423233223](https://cloud.githubusercontent.com/assets/8433054/7300820/34d562ca-ea11-11e4-9e65-4a23e05f9ef9.png)

**Comment by PhilJay** [comment]
Yes, but you will have to customize the library to do that, should not be too hard though :-)

**Comment by 120660021** [comment]
Under the guidance of thinking can it? THX
