### ISSUE TITLE
how to different bar color for different grouped Bar Data like given Image ?

### ISSUE THREAD

**Issue by demo-Ashif** [PhilJay/MPAndroidChart#589]
![capture](https://cloud.githubusercontent.com/assets/6146842/7330529/d913e388-eb11-11e4-91f0-df553cda438f.PNG)

**Comment by PhilJay** [comment]
Here is the documentation: https://github.com/PhilJay/MPAndroidChart/wiki/Setting-Colors

In short: Just create your different `BarDataSets`, and then add the colors you want

Its also in the example project.
