### ISSUE TITLE
use of Barchart in with viewpager fragments

### ISSUE THREAD

**Issue by dasbiswajit** [PhilJay/MPAndroidChart#59]
I am almost new to android. I am using your library at master branch. Your project looks very interesting for me.
I have some dummy values in array-
String[] valArray = new String[] { "23.5", "20.3", "23.5", "44" };
(where min-0 and max value=100 lets say)
I want to show a bar chart on a fragment page like below with same color bars with value on it and animation on draw up to height.
![screenshot_2014-08-24-23-55-07](https://cloud.githubusercontent.com/assets/3852746/4024201/b86bf64e-2bbc-11e4-9422-9f0f83947ec9.png)

My main **activity** class is having a ViewPager. ViewPager is holding no of screens. here is the activity code-

```
       public class MainActivity extends FragmentActivity {
        ViewPager viewPager;
         PagerAdapter adapter;
         public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
          setContentView(R.layout.viewpager_main);
    initialisePaging();
            }
           private void initialisePaging() {

    //Loading screens
    List<Fragment> screens = new Vector<Fragment>();
    screens.add(Fragment.instantiate(this,Basic1.class.getName()));


    adapter =new ViewPagerAdapter(this.getSupportFragmentManager(),screens,);

    // Binds the Adapter to the ViewPager
    viewPager.setAdapter(adapter);
          }
          }
```

my **adapter** class -

```
    public class ViewPagerAdapter extends FragmentPagerAdapter {

     private List<Fragment> screens;

    public ViewPagerAdapter(FragmentManager fm, List<Fragment> fragments ) {
    super(fm);
            this.screens = fragments;
  }
@Override
public Fragment getItem(int arg0) {
    // TODO Auto-generated method stub
    return this.screens.get(arg0);
}

@Override
public int getCount() {
    // TODO Auto-generated method stub
    return this.screens.size();
}
 }
```

Here is the **fragment class** where I want to draw the Barchart programmecally not from layout.-

```
     public class Basic1 extends Fragment {
Context mContext;

@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container,
        Bundle savedInstanceState) {
    // TODO Auto-generated method stub
    if (container == null) {
        return null;
    }
           mContext = container.getContext();  
           String[] valArray = new String[] { "23.5", "20.3", "23.5", "44" };              
    View viewObj=inflater.inflate(R.layout.viewpager_item,
            container, false);
         return viewObj;
       }}
```

**Here I want to draw the Animated BarChart.
a. I want to use the dataset from valArray in the class to draw the bars with animation.
b. When I swipe to another screen. It will disappire so that every this bargraph animation loads when this screens loads
c. Please let me know if I have to extend or implements in Basic1 Fragment**

If you can help me I would be really appreciated. Since I am new to this. I am not able to understand properly and your example app in playstore. 
Regards
Biswajit

**Comment by iad24** [comment]
@PhilJay hi jay. great library btw. Just wondering if its a possible that user can scroll first the barchart. Then if theres nothing to scroll anymore, viewpager gets scrolled.
