### ISSUE TITLE
HorizontalBar chart setViewPortOffsets(0f, 0f, 0f, 0f) not working.

### ISSUE THREAD

**Issue by Agreema** [PhilJay/MPAndroidChart#594]
Hi,
I am trying to create horizontal bar chart with setViewPortOffsets(0f, 0f, 0f, 0f). Please see my code below:

HorizontalBarChart barchart = new HorizontalBarChart(activity);
			barchart.setLayoutParams(new LinearLayout.LayoutParams(0, 110,weight));
			ArrayList<BarEntry> entries = new ArrayList<BarEntry>();
			entries.add(new BarEntry(Float.valueOf(title), 0));
			BarDataSet dataset = new BarDataSet(entries, "");
			dataset.setColor(Color.parseColor("#E0E0E0"));
			ArrayList<String> labels = new ArrayList<String>();
			labels.add(title); 
			BarData bardata = new BarData(labels, dataset);
			barchart.setData(bardata);			
			barchart.setViewPortOffsets(0f, 0f, 0f, 0f);
			barchart.setPadding(0, 0, 0, 0);
			barchart.setDescription("");
			barchart.setPressed(true);
			Legend legend = barchart.getLegend();
			legend.setEnabled(false);
			YAxis topAxis = barchart.getAxisLeft();
			topAxis.setDrawLabels(false);
			YAxis bottomAxis = barchart.getAxisRight();
			bottomAxis.setDrawLabels(false);
			XAxis rightAxis = barchart.getXAxis();
			rightAxis.setDrawLabels(false);
			bottomAxis.setDrawLabels(false);
			barchart.setTouchEnabled(false);

But it feels like its not setting the offsets to 0 at once, when i click the chart then only it shows my changes(removes offset). I think its not invalidating the view on barchart.setViewPortOffsets(0f, 0f, 0f, 0f);
I also tried calling
barchart.invalidate(), but it also didn't work. Can you please help me,I am stuck, I need to remove the offsets/padding from my chart.Please help.

Before clicking it looks like 

![capture](https://cloud.githubusercontent.com/assets/12134357/7345030/e065594e-ecee-11e4-968c-1a979d9a1752.PNG)

After clicking it looks like this

![capture1](https://cloud.githubusercontent.com/assets/12134357/7345031/e066b316-ecee-11e4-906e-76f670da9566.PNG)

**Comment by PhilJay** [comment]
That's exatly how it's supposed to look.

Now set the barspace to zero and the top space (space between largest bar and top of chart-view) and it should all be gone.

**Comment by Agreema** [comment]
I also want my chart to look like second image, but currently i am getting it like first image and i have to click on it to get the chart like second image.

I want to get a bar chart that look like second image and i want it on first load not by clicking on it. 
I hope i am clear.
