### ISSUE TITLE
piechart - how to remove x labels?

### ISSUE THREAD

**Issue by dowi** [PhilJay/MPAndroidChart#595]
Hi and thanks!

in the new library (2.0.9)

how do i remove the labels from within the pie chart itself? (and leave it in the legend)

thanks!

**Comment by AndroFlo** [comment]
Hello, 
Try with : 
pieChart.setDrawSliceText(false);

**Comment by PhilJay** [comment]
Documentation: https://github.com/PhilJay/MPAndroidChart/wiki/Specific-chart-settings

**Comment by dowi** [comment]
thanks! it works

**Comment by anilthummar** [comment]
Thanks it works perfect...

**Comment by hakamibrahim** [comment]
Hei @AndroFlo _pieChart.setDrawSliceText(false);_ not work in my kotlin code. can you help me to fix it?

**Comment by AndroFlo** [comment]
Hi @hakamibrahim , sorry but i haven't used this library for 3 years, good luck
