### ISSUE TITLE
how to remove the number readings for individual points ?

### ISSUE THREAD

**Issue by demo-Ashif** [PhilJay/MPAndroidChart#599]
![device-2015-04-29-001213](https://cloud.githubusercontent.com/assets/6146842/7376918/ef760d18-ee04-11e4-8fec-3e0bee1f99d2.png)

**Comment by PhilJay** [comment]
Have a look at the documentation: https://github.com/PhilJay/MPAndroidChart/wiki

dataSet.setDrawValues(false)

**Comment by demo-Ashif** [comment]
Thanks a Lot Phil. I didn't notice it in wiki . sorry for that
