### ISSUE TITLE
How to achieve stacked area line (or OHLC) chart?

### ISSUE THREAD

**Issue by goshki** [PhilJay/MPAndroidChart#600]
Hi,

I've seen in the issue #472 that it's possible to achieve stacked area and OHLC charts. I've tested the demo app and checked the source code  but I cannot find any reference to it. I've seen that it's possible to activate fill on the line chart but it always fills to 0 on y-axis. Any ideas on what should I look at?

**Comment by PhilJay** [comment]
Check out the [FillFormatter](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/com/github/mikephil/charting/utils/FillFormatter.java). It allows you to customize where the filling line should end.
