### ISSUE TITLE
BarChart setMaxVisibleValueCount invalid.

### ISSUE THREAD

**Issue by TinuxBin** [PhilJay/MPAndroidChart#601]
I want to show four Y values in BarChart, actually, I set 30 Y values. I set following:
mChart.setMaxVisibleValueCount(4);
but, it doesn't work.

**Comment by PhilJay** [comment]
This sets the number of labels that are plotted. If set to 100, and more than 100 values are in the chart, no more value labels will be displayed.

I think you should look into this: https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport

**Comment by TinuxBin** [comment]
Thanks,I fix this problem. I use the method:setScaleMinima(5f, 1f) to meet my needs. I misunderstood the usefulness of  method setMaxVisibleValueCount.
