### ISSUE TITLE
Is it possible to restrict X-axis or Y-axis zoom ?

### ISSUE THREAD

**Issue by demo-Ashif** [PhilJay/MPAndroidChart#602]
There is option to disable or enable zooming, dragging etc. There is also OnGestureListener in the library. I need to know that how can I restrict X-axis or Y-axis zoom scale. Suppose I want to restrict zoom scale that how much zoom user will be enable to do in X-axis and Y-axis. Consider me as a novice developer

**Comment by PhilJay** [comment]
Currently it's not possible to restrict the maximum zoom level.
