### ISSUE TITLE
PieChart display x values and x values percent in same time

### ISSUE THREAD

**Issue by AndroFlo** [PhilJay/MPAndroidChart#603]
Hello Phil,

Actually in PieChart we can display XVals and Yvals, but think you add the possibilitie to display the x values et the x values in percent ?

Thank you

**Comment by PhilJay** [comment]
Yes, check out the [ValueFormatter](https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface) (or the predefined [PercentFormatter](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/com/github/mikephil/charting/utils/PercentFormatter.java) for formatting the y-values (and adding %).

For the x-values, just add % to the `String`.

It's also in the piechart of the example project.

**Comment by AndroFlo** [comment]
I think you have not understood me, i would like in same time display the x values in normal value and in percent like this : (the % are added with paint)

![screenshot_2015-04-29-16-14-10](https://cloud.githubusercontent.com/assets/5589240/7392931/43b4710e-ee8b-11e4-95ab-3cc979d604fd.png)

**Comment by PhilJay** [comment]
Ok, then let the original value (yvalue, e.g. "523") be as it is.
And for the x-labels string array, calculate the percentages.

**Comment by AndroFlo** [comment]
That's not possible beacause x-labels match to 'android...'

**Comment by prathibhaprabs** [comment]
@AndroFlo Is the issue solved. I'm trying for something similar. @PhilJay Could you please look at this once. Thanks.

**Comment by prathibhaprabs** [comment]
I've tried like this

class MaterialInValueFormatter implements IValueFormatter {
    private DecimalFormat percentageFormat;
    private DecimalFormat valueFormat;
    private ArrayList<String> unit = new ArrayList<>();

    MaterialInValueFormatter() {
        percentageFormat = new DecimalFormat("###,###,##0.0");
        valueFormat = new DecimalFormat("###,###,###");
    }

    MaterialInValueFormatter(ArrayList<String> unit) {
        this.unit.addAll(unit);
    }

    @Override
    public String getFormattedValue(float value, Entry entry, int dataSetIndex, ViewPortHandler viewPortHandler) {
        if (unit.size()>0) {
            return percentageFormat.format(value) + " %";
//            return percentageFormat.format(value) + " %" + "\n" + value + " " + unit.get(dataSetIndex); //here I'm trying to add the unit to the value. it is either 'gm' or 'kg'. the array list 'unit' has the respective unit of the value
        }
        else  
            return valueFormat.format(value) +"";
    }
}


I'm trying to get a result as:

25 kg
36%

**Comment by viko58** [comment]
I've tried this, I hope it will help 

class dataGraph implements IValueFormatter {
        private DecimalFormat percentageFormat;
        dataGraph() {  
           percentageFormat = new DecimalFormat("###,###,##0.0");
        }
        @Override
        public String getFormattedValue(float value, Entry entry, int dataSetIndex, ViewPortHandler viewPortHandler) {
            return percentageFormat.format(value) + " %";
        }
    }

ArrayList<PieEntry> entries = new ArrayList<PieEntry>(); 
entries.add(new PieEntry(valueFloat, String.valueOf(valueFloat).concat(" units")));

PieData data = new PieData(dataset);
data.setValueFormatter(new dataGraph());
