### ISSUE TITLE
LineChart animation glitch?

### ISSUE THREAD

**Issue by andyroid42** [PhilJay/MPAndroidChart#604]
Hello,

I experience some glitch in an animation-enabled line-chart, in particular once the line-chart is shown it displays the graphics based on provided data just for a sec or less without animating its appearance and then starts animation as expected. This causes some short blink effect that I would like to avoid somehow. Please tell me how to do this? Thank you!

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_line_chart, container, false);
        LineChart chart = (LineChart) view.findViewById(R.id.chart);
        setChartStyling(chart);
        chart.setData(data goes here);
        chart.animateY(3000);
        //chart.invalidate();

        return view;
    }

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:background="@layout/background"
    android:orientation="vertical"
    tools:ignore="Overdraw">

    <com.github.mikephil.charting.charts.LineChart
        android:id="@+id/chart"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
</RelativeLayout>

**Comment by PhilJay** [comment]
Pull the latest version, this should be fixed already.

**Comment by andyroid42** [comment]
Thank you for your response, PhilJay!

I pulled now the latest version and it works! Thank you!

PS: Before cloning from git the following lines in my Gradle build system involving MPAndroidChart v2.0.9 did not work for some reason:

repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.github.PhilJay:MPAndroidChart:v2.0.9'
}

**Comment by PhilJay** [comment]
Okay, what happened? Error message?

**Comment by andyroid42** [comment]
No, there were no any errors, the project compiled nice with the library MPAndroidChart v2.0.9 and was working fine, however the described glitch in a line-chart still was there. Now once I have cloned directly from the git repository, the glitch has gone. Just not sure why that 'dependencies' thing did't work. Now I have all files right in the project, therefore I just removed this 'dependencies' declaration for now.

**Comment by PhilJay** [comment]
That is because you just pulled the latest commit on the master branch that is not yet in any release version.

**Comment by andyroid42** [comment]
Ah, I see. Well, as soon as these new updates will go into the next release version I will switch back to 'dependencies' in my Gradle build file. Thank you!

**Comment by 3mph4515** [comment]
Have faced with the same issue but with PieChart class. Before starting animation it displays filled piechart for a moment.  
Library version : 3.0.0-beta1
