### ISSUE TITLE
PieChart rotation and setTouchEnabled relations

### ISSUE THREAD

**Issue by mikereman** [PhilJay/MPAndroidChart#61]
Hi Philipp,

I noticed you fixed the bug related to the setTouchEnabled(false) method not having any effect on the PieChart. 
This is really awesome but is it possible to handle some logic to only disable the rotation and still have touch enabled?

Many thanks!

**Comment by anbarasu-seven** [comment]
how can i rotate ChartView by 45" before launching(ie. before calling invalidate method)

**Comment by anilthummar** [comment]
How to Disable click event of  **mChart****.setCenterText("");**

**Comment by anilthummar** [comment]
Hii PhilJay,

we can select multiple slice on touch view like clock wise  touch running and slice selected with ascending and descending order ?.
Please help me.

i am using MPChart Library in android.

**Comment by HaizonCruz** [comment]
If we are drawing a hole in the pie chart, can we enable click in such a way that it works only if click on the slices of the chart. In my case I am clicking in the hole area and still getting the response that I should get when I click on the slices.

Thank you
