### ISSUE TITLE
Bars not displaying for BarChart

### ISSUE THREAD

**Issue by ndoctor13** [PhilJay/MPAndroidChart#610]
I am trying to create a bar chart with four data points but for some reason the bars are not displaying. Can you tell me what might be the issue? Below is what I see. When I click on the X value, a dark grey box shows. The image below shows that as well
![device-2015-04-30-221359](https://cloud.githubusercontent.com/assets/9276671/7426246/43cd5db2-ef86-11e4-8e04-db96cda52ebb.png)

**Comment by nbau21** [comment]
Check if you're populating the BarEntry array or BarDataSet array properly.

**Comment by PhilJay** [comment]
Are the values below 0?
If so, call leftAxis.setStartAtZero(false) & rightAxis.setStartAtZero(false)

**Comment by ndoctor13** [comment]
Below is my code. I don't have any zero values. I have hard coded the Y Values for that purpose but they still don't show. I have one value that is 10 so the grey bar shown in the image above is representing that but all X values are representing the same Y value i.e. 10 when I click on individual X axis.

Note: This same code works properly for PieChart but I want to represent the data in bar chart format

 for (RunObject item : result) {
  
                            String date2 = item.getDate();
                            SimpleDateFormat df = new SimpleDateFormat("MM/dd/yyyy   HH:mm:ss");
                            try {
                               date1 = df.parse(date2);
                            } catch (ParseException e) {
                                e.printStackTrace();
                            }
                            calendar.setTime(date1);
                            int week = calendar.get(Calendar.WEEK_OF_YEAR);
                            if(week==currentWeek)
                            {
                                totalDistance1 = totalDistance1 + item.getDistance();
                            } else if (week == (currentWeek-1))
                            {
                                totalDistance2 = totalDistance2 + item.getDistance();
                            } else if (week == (currentWeek - 2))
                            {
                                totalDistance3 = totalDistance3 + item.getDistance();
                            }
                        }
                        setData((float)(10), currentWeek);
                        setData((float)(5), currentWeek-1);
                        setData((float)(8), currentWeek-2);
                        setData((float)(9), currentWeek-3);

public void setData(float d, int c){

    BarEntry dis = new BarEntry(d, c);
    distance.add(dis);

    BarDataSet dataSet = new BarDataSet(distance, "Weekly");
    
    ArrayList<String> labels = new ArrayList<String> ();

    labels.add(Integer.toString(currentWeek));
    labels.add(Integer.toString(currentWeek-1));
    labels.add(Integer.toString(currentWeek-2));
    labels.add(Integer.toString(currentWeek-3));

    dataSet.setColors(ColorTemplate.COLORFUL_COLORS);

    BarData data = new BarData(labels, dataSet);


    data.setValueTextSize(16f);
    data.setValueTextColor(Color.WHITE);
    data.setValueTypeface(tf);
    chart.setData(data);

    chart.invalidate();

}

**Comment by PhilJay** [comment]
Please look at the example project. The issue is that you are not setting the data correctly. Wich each call of `setData(...)` you are only setting one entry for the chart, and of course overwriting all others.

Put all the entries you want to display in one dataSet and add that to the chart.

**Comment by ndoctor13** [comment]
I did exactly what you said and followed the example but it still didn't resolve it for me. See my changes below. I would really appreciate it if you could let me know what else I need to do. I really like this library and want to use it. The code works for PieChart but does not for BarChart

public void setData(){
        distance5 = new ArrayList<BarEntry>();

        distance5.add(new BarEntry((float)(totalDistance1), currentWeek));
        distance5.add(new BarEntry((float)(totalDistance2), currentWeek-1));
        distance5.add(new BarEntry((float)(totalDistance3), currentWeek-2));
        distance5.add(new BarEntry((float)(totalDistance4), currentWeek-3));

        BarDataSet dataSet = new BarDataSet(distance5, "Weekly");

        dataSet.setBarSpacePercent(35f);

        //ArrayList<BarDataSet> dataSets = new ArrayList<BarDataSet>();
       // dataSets.add(dataSet);

        ArrayList<String> labels = new ArrayList<String> ();

        labels.add(Integer.toString(currentWeek));
        labels.add(Integer.toString(currentWeek-1));
        labels.add(Integer.toString(currentWeek-2));
        labels.add(Integer.toString(currentWeek-3));


        dataSet.setColors(ColorTemplate.COLORFUL_COLORS);

        BarData data = new BarData(labels, dataSet);
        chart.setDrawGridBackground(false);

        chart.setData(data);
        //chart.animateX(3000);
       chart.setDescription("Weekly Total Distance");
       chart.invalidate();

    }
