### ISSUE TITLE
Draw label over bar

### ISSUE THREAD

**Issue by Snehankur** [PhilJay/MPAndroidChart#620]
Hi Phil, 

Is it possible to draw label over bars in Barchart like the on below. 

![label over bar](https://cloud.githubusercontent.com/assets/11004059/7479718/1746af74-f381-11e4-844a-5fae3be24b2b.png)

**Comment by PhilJay** [comment]
Try this:

```java
XAxis x = chart.getXAxis();
x.setPosition(XAxisPosition.BOTTOM_INSIDE);
```
