### ISSUE TITLE
finger drawing

### ISSUE THREAD

**Issue by fguf** [PhilJay/MPAndroidChart#624]
Hi!
I am trying to use the finger drawing feature to edit line chart by draging entries but i didn't found working examples.
Is this feature still available ? 

thanks!

**Comment by PhilJay** [comment]
Finger drawing is currently not possible.

**Comment by loteresa2** [comment]
I would like a follow up on this. Will this feature be available soon?

**Comment by PalakDarjiHs** [comment]
I am looking for the same feature. Is it included?
