### ISSUE TITLE
mChart.getYChartMax() when drawing custom lines

### ISSUE THREAD

**Issue by tehras** [PhilJay/MPAndroidChart#626]
Hi,
I'm trying to write some custom renderers because i need to do some custom highlights, so I'm trying to get the max Y axis and draw something slightly under it, however when i do                        

 ```
           float[] originalPts = new float[]{
                    xIndex, mChart.getYChartMax(), xIndex, y
            };
            Transformer transformer = mChart.getTransformer(set.getAxisDependency());
            transformer.pointValuesToPixel(originalPts);
```

That mChart.getYChartMax() in pixels gives me some value that doesn't seem to actually be the top? 
Am i missing something? No matter how many pixels i add / subtract, the line still goes all the way to the top.

**Comment by PhilJay** [comment]
`getYChartMax()` returns the maximum value the `YAxis` can display.
If you just want the highest value that is displayed in the chart, call `getYMax()` on your data object.
