### ISSUE TITLE
Draw the custom line by touch

### ISSUE THREAD

**Issue by GeekerSlz** [PhilJay/MPAndroidChart#627]
Hi Phil,
I use your lib to build my chart,it's awesome on show the data.But I want to draw some custom line by touch.I tried this:
         `Transformer t = new Transformer(mChart.getViewPortHandler());`
        `PointD pd = t.getValuesByTouchPoint(me.getX(), me.getY());`
        `ToastUtils.showToast(this,pd.toString());`
it got x,y of a touch point in chart.
I drawn it via canvas.drawLine(...) in onDraw().
However,it doesn't scale follow the chart.

**Comment by danielgindi** [comment]
This doesn't look like a drawing code, but showing a Toast. 
Anyway, the Chart is drawing itself - you cannot add custom drawing code to it. You may want to add a transparent View over it and draw whatever you want.

**Comment by GeekerSlz** [comment]
Right,it just got x,y of a touch point  in chart.
I drawn it via canvas.drawLine(...) in onDraw().
However,it doesn't scale follow the chart.
