### ISSUE TITLE
how to add the shadow of different colors to CandleStickChart

### ISSUE THREAD

**Issue by wangningdy** [PhilJay/MPAndroidChart#628]
hi phil，
Thank you for MPAndroidChart！！
I got a problem , how to add the shadow of different colors to CandleStickChart
I mean increase is green shadow line ，decreas is red shadow line。
My English is poor， please help me。

**Comment by PhilJay** [comment]
Well for the shadow that is not possible, but you can set it for the body: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/CandleStickChartActivity.java
