### ISSUE TITLE
LinearChart. Y-values

### ISSUE THREAD

**Issue by yuguseva** [PhilJay/MPAndroidChart#630]
Is it possible to set max displayed y-value of LinearChart to some value which is not in LineDataSet? Because I have max y-value equals to 1 and the chart displays decimal value. I don't like to dislay decimal values. Maybe there is an ability to show only specified values?

**Comment by PhilJay** [comment]
- [YAxis](https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-(YLabels))
 - [ValueFormatter](https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface)
