### ISSUE TITLE
Difference in x-axis values between chart types

### ISSUE THREAD

**Issue by cafrean** [PhilJay/MPAndroidChart#631]
![shift](https://cloud.githubusercontent.com/assets/8956472/7544213/682596f2-f5cb-11e4-9dff-5800ad0f90b8.png)

When presenting the exact same data using BarChart and LineChart there seems to be quite a big difference in how values on the x-axis (the dates, in the picture above) are presented. I know that they're two completely different chart-types, but since everything else is quite similar I thought I'd share it.

Is this an issue, or intentional? Any workarounds?

**Comment by PhilJay** [comment]
It's intentional.

The thing is that the center of the first bar in the barchart is always at x-index 0. This kind of "shifts" the barchart to the left in comparison to the linechart.
