### ISSUE TITLE
How can i change the Chart orientation?

### ISSUE THREAD

**Issue by brunotrisso** [PhilJay/MPAndroidChart#632]
I need to change de chart orientation to landscape without need to change all the Activity orientation like "getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);".

How can i do this? I cant invert the axis values because the Y axis only accepts float values.

**Comment by PhilJay** [comment]
Just rotate the `View` in xml (rotation in degrees):

```xml
 <com.github.mikephil.charting.charts.LineChart
        android:id="@+id/chart"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:rotation="90" />
```

**Comment by felislynx-silae** [comment]
@PhilJay I've stumbled on this issue by myself and to be honest rotation=90 is not working properly. View is not rendering correctly (it's cutting chart).

**Comment by cagriyalcinn** [comment]
Any solution ?

**Comment by AndroPlus** [comment]
still no solution for this issue ?

**Comment by AndroPlus** [comment]
@PhilJay on applying rotation=90, it is not expanding full view, it shows like portraint. The chart is not expanding..

![screenshot-1517663793883](https://user-images.githubusercontent.com/8198941/35767460-a7f0470c-0912-11e8-8beb-632b02ac6242.jpg)

**Comment by cagriyalcinn** [comment]
@AndroPlus thanks for advice. So what about the LineChart ?

**Comment by AndroPlus** [comment]
@cagriyalcinn I didn't tried that.. Thanks

**Comment by HarryMMR** [comment]
@AndroPlus But if we go for HorizontalBarChart, how do we convert to line instead of bar?

**Comment by think-twice-code-once** [comment]
is this something what you want? if it's right I'll show my code.
![screenshot_20180727-165543](https://user-images.githubusercontent.com/25735122/43314857-6ce8413e-91be-11e8-8b5e-f26e8ce68b1e.png)

**Comment by Amritvirk** [comment]
Labels are not coming by using this code? can anyone help

**Comment by Amritvirk** [comment]
i get it done!
