### ISSUE TITLE
How to set the Visibility of YAxis(Left or Right) to GONE/INVISIBILITY?

### ISSUE THREAD

**Issue by deviltsw** [PhilJay/MPAndroidChart#633]
I don't need the YAxis,thank you.

**Comment by SilverFoxA** [comment]
Have you tried this? 
`charttype.getAxisRight().setEnabled(false);` or `charttype.getAxisLeft().setEnabled(false);`

**Comment by deviltsw** [comment]
@SilverFoxA ,thx for your reply.You save my time.
