### ISSUE TITLE
highlightValue(index, dataset) does nothing

### ISSUE THREAD

**Issue by capitancook** [PhilJay/MPAndroidChart#635]
I tried to programmatically highlight an interval of bars in a barchart  but it doesn't work.
The code fragment is the following:
```java
for (int i = 3; i <= 5; i++) {
   mChart1.highlightValue(i, 0);
   mChart2.highlightValue(i, 0);
}

```
I don't get errors but the bar 3, 4 and 5 are not highlighted :(

**Comment by PhilJay** [comment]
This method is for highlighting a single value, what you are doing (with your loop) is overwriting every previous statement.

There is a specific call for highlighting multiple values: https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart

**Comment by capitancook** [comment]
Thanks a lot.
