### ISSUE TITLE
Legend Not Centered  Properly

### ISSUE THREAD

**Issue by jemshit** [PhilJay/MPAndroidChart#637]
As you see in image below legend is not centered , it is a bit on right side. 
i have used: `legend.setPosition(Legend.LegendPosition.BELOW_CHART_CENTER);` but it doesnot work correctly, any solution?

![screenshot_2015-05-12-18-21-48](https://cloud.githubusercontent.com/assets/1948828/7591307/cd3fee4a-f8d5-11e4-8c3e-f686a62bcb2d.png)

**Comment by jemshit** [comment]
It happens on my other screen too. I realized that when fragment(which has chart) is created, it can not  put legend on center below. 
![screenshot_2015-05-18-10-44-10](https://cloud.githubusercontent.com/assets/1948828/7676367/64516704-fd4b-11e4-9c09-6e2606f5eb80.png)

But when fragment is resumed(just go out of tab and come back) legend relocates itself and comes to center correctly.

![screenshot_2015-05-18-10-44-20](https://cloud.githubusercontent.com/assets/1948828/7676371/684fa7ee-fd4b-11e4-8339-c6c0cb66ffb5.png)

Probably when there is no data and data is added later, it can't locate legend properly.

**Comment by jemshit** [comment]
If i set data of chart inside `asynchTask (onPostExecute)` which is called in `onCreate` it can not set center it properly. If i directly set its data from `onCreate` it centers properly. Solve this please.

**Comment by PhilJay** [comment]
Hmmm that  is weird, but I guess than you have to avoid the asynctask :-)
