### ISSUE TITLE
Skip xAxis Labels, Different Intervals

### ISSUE THREAD

**Issue by ReversiPro** [PhilJay/MPAndroidChart#638]
I would like to create a graph that shows how a certain value develops over time.

The values, however, are not periodically, but in unpredictable intervals.

Is it possible to display every hour in the x-axis (6:00, 7:00, 8:00 ...), but only add values for lets say 6:00 and 8:00, so it will skip 7:00?

**Comment by PhilJay** [comment]
Yes, that is possiblie :-)

**Comment by ReversiPro** [comment]
I'm sorry if I'm wasting your time, but I don't get it.

How is it done? With the setLabelsToSkip() method?

Could you maybe drop some hints or even instructions for me? Thank you very much!
