### ISSUE TITLE
How to add AnimatorListener to the Charts

### ISSUE THREAD

**Issue by su1216** [PhilJay/MPAndroidChart#639]
How can we know whether the chart finish the animation or cancel the animation?

**Comment by michel-t-86** [comment]
Why was this question closed without an answer? I am trying to add a AnimationListener to the pie chart but to no avail.

**Comment by michel-t-86** [comment]
@su1216 did you find a solution to this?

**Comment by su1216** [comment]
@michel-t-86 Sorry, no.
