### ISSUE TITLE
DataSet.getEntryForXIndex does not work for all cases

### ISSUE THREAD

**Issue by Maragues** [PhilJay/MPAndroidChart#641]
**Whats wrong**
getEntryForXIndex does a binary search assuming that mYVals is ordered from smallest to biggest xIndex. Nor the documentation nor any parameter check enforce this order.

**Consequences**
If mHighLightIndicatorEnabled is true and mYVals is not in ascend order, the MarkerView is always placed on top of either the first or the last Entry because it doesn't find a matching xIndex. Specifically, the problem lies here

```java
/*
* this code assumes that if the xIndex we are looking for is bigger 
* than the item we are comparing against, the next item to look at 
* is in the subsequent part of the list
*/
if (x > mYVals.get(m).getXIndex())
    low = m + 1;
else
   high = m - 1;
```

**Potential solutions**
Just some quick thoughts, sure someone else can come up with something better.

1) Assume O(n) performance. Not good for large collections

```java
public BarEntry getEntryForXIndex(int x) {
    for(int i=0;i<mYVals.size();i++){
      if(mYVals.get(i) != null && mYVals.get(i).getXIndex() == x)
        return mYVals.get(i);
    }

    return null;
  }
```

2) Automatically order yVals in DataSet constructor

3) Force yVals to be ordered

4) Combination of 2) and 3)

5) Change the ```if (x > mYVals.get(m).getXIndex())``` part to a better lookup, which will probably have performance consequences

6) Something better?

**Comment by PhilJay** [comment]
Thank you for your input, we are just working on fixing this issue since it affects other parts of the library as well. The issue concerning highlighting should already be fixed.
