### ISSUE TITLE
LimitLine class not identified

### ISSUE THREAD

**Issue by miteshpithadiya** [PhilJay/MPAndroidChart#646]
Is LimitLine class removed from the newer versions?? The class is not available in 2.1.0, 2.0.9, etc.

**Comment by PhilJay** [comment]
The `LimitLine` is still available.

**Comment by miteshpithadiya** [comment]
PFB the error:
![limitline error](https://cloud.githubusercontent.com/assets/7931013/7655860/371d9de2-fb44-11e4-9934-3339a039112a.png)

PFB the build.gradle line for importing the library.
![error](https://cloud.githubusercontent.com/assets/7931013/7655887/671caaa6-fb44-11e4-8be6-6e9fe32dbd5d.png)

Please let me know if I am missing something.

**Comment by PhilJay** [comment]
You are missing something.

`LimitLines` are now handled by the `Axis`, and no longer by the `ChartData` object.

You can read that in the [documentation](https://github.com/PhilJay/MPAndroidChart/wiki/The-Axis) or check the [example](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/LineChartActivity1.java).

**Comment by miteshpithadiya** [comment]
Got the issue, it is working now, Thanks for the quick response and support... Appreciate your awesome work.. Thanks again.
