### ISSUE TITLE
CandleStick

### ISSUE THREAD

**Issue by rajadva** [PhilJay/MPAndroidChart#648]
One or more of the DataSet Entry arrays are longer than the x-values array of this ChartData object.

Am new to android and am getting the above as an error in my logcat while i am trying to implement the candlestick chart.
Can You please help me.

[["7:00 AM",0.1234,0.14542,0.154,0.14542,0.485],["8:00 AM",0.1125167,0.19,0.1973,0.1829,0.2017],["9:00 AM",0.20161,0.1952,0.2064,0.1888,0.2112],["10:00 AM",0.199915,0.194,0.2038,0.1881,0.2077],["11:00 AM",0.19737667,0.1923,0.2015,0.1872,0.2056],["12:00 PM",0.20012667,0.1928,0.2055,0.1854,0.2108],["1:00 PM",0.18912333,0.1747,0.197,0.1602,0.2049],["2:00 PM",0.17367667,0.1647,0.1859,0.1558,0.1982],["3:00 PM",0.16614333,0.1601,0.1711,0.154,0.176],["4:00 PM",0.18704167,0.1739,0.1961,0.1608,0.2052],["5:00 PM",0.19353167,0.188,0.1993,0.1825,0.205],["6:00 PM",0.4785,0.1837,0.1937,0.1772,0.1972],["7:00 PM",0.4564,0.1832,0.1976,0.1778,0.2065],["8:00 PM",0.19489333,0.1899,0.2,0.185,0.2052],["9:00 PM",0.4884,0.1823,0.1949,0.1757,0.2009],["10:00 PM",0.7845,0.1772,0.1986,0.1646,0.2073],["11:00 PM",0.18352667,0.1765,0.1916,0.1694,0.1996],["12:00 AM",0.18597667,0.145,0.1932,0.1698,0.2005],["1:00 AM",0.18476333,0.1723,0.1953,0.1598,0.2059],["2:00 AM",0.18983167,0.1852,0.1961,0.1806,0.2024],["3:00 AM",0.1905,0.1858,0.1955,0.1811,0.2005],["4:00 AM",0.19230833,0.1841,0.1975,0.1759,0.2027],["5:00 AM",0.18996,0.1838,0.1941,0.1776,0.1983],["6:00 AM",0.18275167,0.1774,0.186,0.172,0.1893]],"metadata":[{"colIndex":0,"colType":"String","colName":"Hourly"},{"colIndex":1,"colType":"Numeric","colName":"Median"},{"colIndex":2,"colType":"Numeric","colName":"Lower Quartile"},{"colIndex":3,"colType":"Numeric","colName":"Upper Quartile"},{"colIndex":4,"colType":"Numeric","colName":"Minimum Value"},{"colIndex":5,"colType":"Numeric","colName":"Maximum Value"}]}

**Comment by PhilJay** [comment]
The error message you are getting pretty much says it all.

The x-values array you are providing for your data needs to be at least as long as the highest x-index that you want to display in the chart.
