### ISSUE TITLE
中文翻译地址

### ISSUE THREAD

**Issue by tuteng** [PhilJay/MPAndroidChart#649]
https://github.com/tuteng/MPAndroidChart

**Comment by wangningdy** [comment]
嗨  你好，看了你的博客，写的很好。最近也一直在关注MPAndroidChart ，突然在 Issue中看到中文翻译还是挺激动的。最近也打算也一篇博客来分享一下MPAndroidChart ，不知道可否告诉我你的邮箱？我希望能有些技术上的交流，相互学习一下！！
谢谢
