### ISSUE TITLE
How could I make it come true?

### ISSUE THREAD

**Issue by xubuhang** [PhilJay/MPAndroidChart#653]
How could I make it come true?
![e61190ef76c6a7ef417864c7f9faaf51f2de66f1](https://cloud.githubusercontent.com/assets/4189632/7675576/a42db456-fd6c-11e4-8b81-28115d9f9dbc.jpg)
![518091733](https://cloud.githubusercontent.com/assets/4189632/7675600/d894e9f8-fd6c-11e4-81cc-fa2ccf262752.png)

**Comment by PhilJay** [comment]
Image1: Use 2 different datasets
Image2: Use 1 DataSet and the `FillFormatter`

**Comment by xubuhang** [comment]
Thanks a million
