### ISSUE TITLE
BarChart chart area size

### ISSUE THREAD

**Issue by bugadani** [PhilJay/MPAndroidChart#658]
Hi!

I have two nearly identical barcharts. The charts are placed side by side, they are the exact same size and are configured by the same function. The only difference is in their data - one charts shows the best and the other shows the average value of a time series.
The issue I'm having is that the chart area of the charts are not equally sized and the arrangement looks weird.
![error](https://cloud.githubusercontent.com/assets/977627/7701388/e39c65e6-fe26-11e4-8140-bf44e6221c41.png)

**Comment by danielgindi** [comment]
This is an interesting one... Are you sure nothing was done to the legend maybe? An offset?

@PhilJay could that be the equivalent of the "jumps" we had on the x-axis grid lines up until a month ago?

**Comment by PhilJay** [comment]
Are they nested in a `LinearLayout` using the `weight` attribute?

**Comment by bugadani** [comment]
They are. But if I don't change anything but use the same data for both views, it's completely fine.

No offset is set for anything, both charts have been configured exactly the same (one function does the configuration).

**Comment by PhilJay** [comment]
Use a horizontal linearlayout, and give each chart a weight of 1. Tell me what happens.

**Comment by bugadani** [comment]
Unfortunately I'm not able to do this this week. I'll get back to you then. Thanks for the help.

**Comment by bugadani** [comment]
![screenshot_2015-05-28-16-38-51](https://cloud.githubusercontent.com/assets/977627/7861350/e0f1e3f4-054f-11e5-894e-3a9edd0d8116.png)

The charts are the same size, initialized by the same code, only difference is that they have different data.

layout.xml:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="horizontal">

        <com.github.mikephil.charting.charts.BarChart
            android:id="@+id/bestTimesBarChart"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1">

        </com.github.mikephil.charting.charts.BarChart>

        <com.github.mikephil.charting.charts.BarChart
            android:id="@+id/averageTimesBarChart"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1">

        </com.github.mikephil.charting.charts.BarChart>
</LinearLayout>

Java code:

        BarChart     bestBarChart    = createBarChart((BarChart) v.findViewById(R.id.bestTimesBarChart));
        BarChart     averageBarChart = createBarChart((BarChart) v.findViewById(R.id.averageTimesBarChart));

        bestBarChart.setData(generateBestTimesBarData(trainingDataArrayList));
        averageBarChart.setData(generateAverageTimesBarData(trainingDataArrayList));

private BarChart createBarChart(BarChart chart) {
        chart.setDescription("");

        chart.enableScroll();
        chart.setDoubleTapToZoomEnabled(false);
        chart.setHighlightIndicatorEnabled(false);
        chart.setDrawGridBackground(true);
        chart.setDrawBarShadow(false);
        chart.setPinchZoom(false);
        chart.setScaleYEnabled(false);
        chart.setScaleXEnabled(false);
        chart.setDrawValueAboveBar(false);

        Legend legend = chart.getLegend();
        legend.setPosition(Legend.LegendPosition.BELOW_CHART_LEFT);
        legend.setTextSize(15);
        legend.setFormSize(15);
        legend.setTextColor(Color.WHITE);
        legend.setTypeface(mTF);

        YAxis leftAxis = chart.getAxisLeft();
        leftAxis.setPosition(YAxis.YAxisLabelPosition.OUTSIDE_CHART);
        leftAxis.setTextSize(15);
        leftAxis.setTextColor(Color.WHITE);
        leftAxis.setTypeface(mTF);
        //leftAxis.setLabelCount(4);
        leftAxis.setValueFormatter(mTimeFormatter);

        chart.getAxisRight().setEnabled(false);
        chart.getXAxis().setEnabled(false);

        return chart;
    }

**Comment by bugadani** [comment]
This problem is still present in 2.1.1. After some tinkering with my code it looks like the space above the labels depends on the label text length. The longer the text, the bigger the gap is, even though the text has plenty of space.
