### ISSUE TITLE
Dragging one LineChartItem drags all LineChartItems in ListViewMultiChartActivity

### ISSUE THREAD

**Issue by kefs** [PhilJay/MPAndroidChart#659]
Modify the example app: give the ability to drag to all `LineChartItem`s within the `getView()`:

```
holder.chart.setDragEnabled(true); //enable drag
holder.chart.setVisibleXRange(2); //added so we can drag something
```
Run the example app, run Multiple chart inside ListView

If you drag one of your line charts, any line chart off screen shows up dragged to the same position. It also happens to the touch points.. if you touch somewhere in a line chart within the listview and it shows the crosshairs (red in the example app), the crosshairs will be drawn in the same spot on newly drawn rows in the `ListView`.

**Comment by PhilJay** [comment]
Yes, that is common `ListView` behaviour as the `ListView` recycles it's children.

If you unhiglight in every call of `getView(...)` and reset all scaling and dragging, this will no longer occur.

**Comment by kefs** [comment]
Instead of resetting the drag position to 0, I'd like to save and restore it, but I'm not sure which method to use to `get` the xAxis value current at position one. I realize I can set this with `.moveViewToX(x)`, but I can't find where to get that value.. I'm assuming I would have to get the updated value from the `OnChartGestureListener`'s `onTranslate`, but the internal `dX` value doesn't seem to be what I'm looking for, neither are `chart.getXChartMin`, `.getCenter`, or anything else i've tried.  What method should I be using here? I couldn't find anything in [the wiki](https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport) about x position retrieval. Thanks.
