### ISSUE TITLE
How refresh the chart after calling setVisibleXRange?

### ISSUE THREAD

**Issue by brunotrisso** [PhilJay/MPAndroidChart#660]
I have a button to rotate and the invalidate is not working:

if (chart.getRotation() == 90.0f)
   chart.setVisibleXRange(20f);
else
   chart.setVisibleXRange(10f);

chart.invalidate();

**Comment by PhilJay** [comment]
What do you mean by "is not working"?

**Comment by brunotrisso** [comment]
When i call the invalidate it does not change the visible x range. 
I have a button to rotate and change the amount of visible x points dynamically...

**Comment by PhilJay** [comment]
Do you have more than 10 values in the chart?

**Comment by brunotrisso** [comment]
Yes. I solved by calling fitScreen after setVisibleXRange.
