### ISSUE TITLE
legend can't wrap

### ISSUE THREAD

**Issue by KokerWang** [PhilJay/MPAndroidChart#661]
When the column and line chart line too much legend on the display is not full, if you can wrap? Thanks!

**Comment by danielgindi** [comment]
I'm actually working on word-wrapping the legend for my needs, and will be soon available in both ios and android versions.

**Comment by danielgindi** [comment]
https://github.com/PhilJay/MPAndroidChart/pull/702

**Comment by vincent-paing** [comment]
It's broken with constraintlayout
