### ISSUE TITLE
How could I make it come true?

### ISSUE THREAD

**Issue by xubuhang** [PhilJay/MPAndroidChart#662]
![qq 2015059](https://cloud.githubusercontent.com/assets/4189632/7724121/34f4fdf4-ff21-11e4-91b7-da1213938f16.png)
![qq 20150520182719](https://cloud.githubusercontent.com/assets/4189632/7724122/35228864-ff21-11e4-9a7d-f423b72d9f72.png)

**Comment by PhilJay** [comment]
I honestly don't know. Study the examples.
