### ISSUE TITLE
YAxis: how to set integer of them?

### ISSUE THREAD

**Issue by wsk900906** [PhilJay/MPAndroidChart#664]
I don't want to show the x.xx in the YAxis.
if I use setValueFormatter it will just delete the .xx part:
such as: the YAxis shows: 1 1.3 1.6 1.9 2.2 2.5 total 6 numbers 
I just want to show 1, 2 total 2 numbers at the left side.
How to do it?

**Comment by PhilJay** [comment]
- Use `ValueFormatter` to cut off decimals
 - Use `setAxisMaxValue(...)` and `setAxisMinValue(...)` to adjust your axis range
 - Use `setLabelCount(...)` and set as many labels as you need

**Comment by wsk900906** [comment]
thank you, but the problem is that my data range is from 1 to 100000, is
there a way not hard code the label count to show just integer values? and
when i use setAxisMaxValue(new  Defaultvalueformatter(0)). it doesnt work.
why?
2015年5月21日 12:31 AM于 "Philipp Jahoda" <notifications@github.com>写道：
