### ISSUE TITLE
How to make the chart real-time display?

### ISSUE THREAD

**Issue by wangningdy** [PhilJay/MPAndroidChart#666]
Hi Philip
Thank you for MPAndroidChart!
How to make the chart real-time display?
I mean data is constantly updated, Such as X axis is a total of 1-5， now it is 3，The chart shows the data of 1-3，After 3 is empty！ 
I don't know whether MPAndroidChart support that？
I don‘t know if or whether you can understand 。My English is too poor！
No matter how to thank you！！
![aaaa](https://cloud.githubusercontent.com/assets/7581053/7741313/e9a2de72-ffaf-11e4-9eb1-538e3294ab0d.png)

**Comment by PhilJay** [comment]
- [realtime data documentation](https://github.com/PhilJay/MPAndroidChart/wiki/Dynamic-&-Realtime-Data)
 - [realtime data example](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/RealtimeLineChartActivity.java)

**Comment by mitesh-shah** [comment]
@wangningdy : Use handler and call setData function each time with different values. and then write mChart.invalidate();
It worked for me.

**Comment by yuliangC** [comment]
@wangningdy  Hi wangningdy  ，I am in trouble with the same question like yours,did you solve your question? Can you tell me how did you do for this question? if you are Chinese,please answer me for 中文，thanks! Best wishes!
