### ISSUE TITLE
Value will be disappeared automatically

### ISSUE THREAD

**Issue by sachil** [PhilJay/MPAndroidChart#668]
I had a problem.When I use the LineChart and call the method setDrawValues(true),the value will be shown in the chart,but the value will be disappeared automatically after a period of time.And now I call the method isDrawValuesEnabled(),it always return true,here is my code:

	private static final int VISIBLE_NUM = 5;

	private void initChart() {
		mChart = (LineChart) findViewById(R.id.realtime_chart);
		mChart.setDrawGridBackground(false);
		mChart.setDescription("");
		mChart.setNoDataTextDescription("You need to provide data for the chart.");
		mChart.setHighlightEnabled(true);
		mChart.setTouchEnabled(true);
		mChart.setDragEnabled(true);
		mChart.setScaleEnabled(true);
		mChart.setPinchZoom(true);

		XAxis xl = mChart.getXAxis();
		xl.setTextColor(Color.BLACK);
		xl.setDrawGridLines(false);
		xl.setAvoidFirstLastClipping(true);
		xl.setSpaceBetweenLabels(5);
		xl.setEnabled(true);
		xl.setPosition(XAxis.XAxisPosition.BOTTOM);

		YAxis leftAxis = mChart.getAxisLeft();
		leftAxis.setAxisMaxValue(50f);
		leftAxis.setAxisMinValue(40f);
		leftAxis.setStartAtZero(false);
		leftAxis.enableGridDashedLine(10f, 10f, 0f);
		mChart.getAxisRight().setEnabled(false);
		LineData data = new LineData();
		data.setValueTextColor(Color.BLACK);

		mChart.setData(data);
	}

	private void refreshData(float value) {
		LineData data = mChart.getData();
		if (data != null) {
			LineDataSet set = data.getDataSetByIndex(0);

			if (set == null) {

				set = new LineDataSet(null, "DataSet");
				//set.enableDashedLine(10f, 5f, 0f);
				set.setColor(Color.BLUE);
				set.setCircleColor(Color.GREEN);
				set.setLineWidth(1f);
				set.setCircleSize(3f);
				set.setDrawCircleHole(false);
				set.setValueTextSize(9f);
				set.setFillAlpha(65);
				set.setFillColor(Color.BLACK);
				set.setDrawValues(true);
				data.addDataSet(set);
			}

			if(set.getEntryCount() == VISIBLE_NUM) {
				data.removeXValue(0);
				set.removeEntry(0);
				for (Entry entry : set.getYVals()) {
					entry.setXIndex(entry.getXIndex() - 1);
				}
			}

			data.addXValue(new SimpleDateFormat("HH:mm:ss").format(new Date(
					System.currentTimeMillis())));

			set.addEntry(new Entry(value, set.getEntryCount()));

			mChart.notifyDataSetChanged();

			//mChart.setVisibleXRange(VISIBLE_NUM - 1);
			//mChart.moveViewToX(data.getXValCount() - VISIBLE_NUM);
			mChart.invalidate();
		}

**Comment by PhilJay** [comment]
Call `setMaxVisibleValueCount(10000)`

**Comment by sachil** [comment]
It works ok,thanks a lot.
