### ISSUE TITLE
vertical lables

### ISSUE THREAD

**Issue by RaffiOhanian** [PhilJay/MPAndroidChart#669]
Hey guys , 

How can i show the labels in the x axis vertically (rotated) so they fit in the screen ?

**Comment by PhilJay** [comment]
That is not supported yet, you will have to do it yourself

**Comment by hfahmy** [comment]
@PhilJay Can you provide some direction as how to get x-axis labels to render vertically? Which class(es) to subclass, which methods to override maybe? Any help would be appreciated!

This library has everything I'm looking for! (except vertical x-axis labels that is ;)

**Comment by opswhisperer** [comment]
This is a basic feature of any chart, especially for bar charts. Any idea when this might be supported? Or some guidance on how to "do it yourself" ?
