### ISSUE TITLE
Typo in wiki (Getting Started)

### ISSUE THREAD

**Issue by filipedelimabrito** [PhilJay/MPAndroidChart#672]
Hi PhilJay and MPAndroidChart’s contributors! 

In the second paragraph (here: https://github.com/PhilJay/MPAndroidChart/wiki/Getting-Started), did you mean “And then <b>retrieve</b> it from your Activity, Fragment or whatever:” instead of “And then <b>retreive</b> it from your Activity, Fragment or whatever:”?

It is a small error (I know), but I want only to contribute.

**Comment by PhilJay** [comment]
Thanks! It's changed.
