### ISSUE TITLE
Using setLabelCount

### ISSUE THREAD

**Issue by GunaseelanArumaikkannu** [PhilJay/MPAndroidChart#673]
While I use the following code 

barChart.getAxisLeft().setAxisMaxValue(100);
barChart.getAxisLeft().setAxisMinValue(0);
barChart.getAxisLeft().setLabelCount(5);

I am getting 0,20,40,60,80,100, But I need 0,25,50,75,100, For more detail I have added post in following SO link
http://stackoverflow.com/questions/29943447/using-setlabelcount-in-mpandroidchart

**Comment by PhilJay** [comment]
What you want is currently not really supported. It's not possible to set the values of the y-axis exactly to your needs.

What you could try (and this is a very hacky solution) is modify the `public float[] mEntries` property of the `YAxis` and set the labels you want. But I am not sure myself if this will work :-D

**Comment by carrchr** [comment]
FYI future people. PhilJay added `setLabelCount(int count, boolean force)` [here](https://github.com/PhilJay/MPAndroidChart/commit/d07ceda265830d585cda65d1132ebba283f2941c)  
See [YAxis (Y Labels) wiki](https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-(YLabels))

**Comment by GunaseelanArumaikkannu** [comment]
Thank you so much

On Thu, Oct 1, 2015 at 12:34 AM, Chris Carr <notifications@github.com>
wrote:

> FYI future people. PhilJay added setLabelCount(int count, boolean force)
> here
> <https://github.com/PhilJay/MPAndroidChart/commit/d07ceda265830d585cda65d1132ebba283f2941c>
>
> See YAxis (Y Labels) wiki
> <https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-(YLabels)>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PhilJay/MPAndroidChart/issues/673#issuecomment-144508462>
> .
>



-- 
Thanks & Regards
Gunaseelan A
9965470689
