### ISSUE TITLE
Peaks

### ISSUE THREAD

**Issue by Pitel** [PhilJay/MPAndroidChart#674]
This is more a question... I'm looking for some charting library, and this look really good. But I have one thing... I want to have a bar chart, but I want peaks of the bars above some value to have different color.

![Example](https://i.stack.imgur.com/4i8bc.png)

Is this possible with this library?

**Comment by PhilJay** [comment]
Unfortunately this is currently not possible. However it should not be too hard to modify the library to achieve this if you want.

**Comment by Pitel** [comment]
Well, I solved it with stacked bar chart. So, thanks for your great library. :)
