### ISSUE TITLE
Something wrong with getting x-index which is still visible on the chart

### ISSUE THREAD

**Issue by sachil** [PhilJay/MPAndroidChart#678]
Dear Philipp,I have a trouble when using MPAndroidChart.I want to get the min value and the max value on the x-axis,so I call getLowestVisibleXIndex() and getHighestVisibleXIndex() to get them,but sometimes the returned values are wrong.My x-axis is startting with 0,and when I scoll the chart to the start,I get a negative value to call getLowestVisibleXIndex().Please give me some suggestions,thanks.

**Comment by PhilJay** [comment]
Are you using the barchart?

**Comment by sachil** [comment]
Yes,I'm using barchart.

**Comment by kirvenjt** [comment]
I'm having the same issue on a line chart. Once I scroll all the way to one edge the high or low value continues to decrease or increase if I keep swiping. It seems to be registering the inertia of the scroll. If I fling to one edge the value will keep changing for a bit after the gesture is over. 
I will see if I can figure out what's going on in more detail soon.

**Comment by siliosffreitas** [comment]
Then kirvenjt, do you have a solution? I'm have the same problem.

**Comment by kirvenjt** [comment]
@siliosffreitas, I don't remember if I got this figured out or not. I think I may have hacked around it, but I'll have to check when I get a chance. You can look at my project https://github.com/teebeck/jot and probably figure out what I did faster than I can

**Comment by hiperioncn** [comment]
Any update about linechart
