### ISSUE TITLE
new Entry value

### ISSUE THREAD

**Issue by RaffiOhanian** [PhilJay/MPAndroidChart#680]
Hey guys , 

should the value for entry only be a float? cant i have an int value for my entry ?

**Comment by PhilJay** [comment]
sure you can `new Entry(1, xindex)`

**Comment by RaffiOhanian** [comment]
well sure I can , but its converting 1 to 1.00 converting everything to float. i dont need .00 how do i get rid of that?

**Comment by mitesh-shah** [comment]
Do change in MyValueFormatter class, according to your need.
