### ISSUE TITLE
HorizontalBarChart Y axis values has cut off in large values

### ISSUE THREAD

**Issue by OmarHassan25** [PhilJay/MPAndroidChart#681]
Hello,

I am using Horizontal Bar Chart, when using large values in Y axis values, these values have a cutoff and are partially drawn outside the screen. 
![horizontalbarchart](https://cloud.githubusercontent.com/assets/11418971/7794115/947be204-02cf-11e5-942f-d914221d7d3d.png)

The same thing happens in Line chart, when clicking marker view to see its values, the right most marker view is partially drawn outside the device screen.
![linebarchart](https://cloud.githubusercontent.com/assets/11418971/7794119/9e0cd6b6-02cf-11e5-98e9-36620940e43f.png)

**Comment by PhilJay** [comment]
Read the [documentation of the YAxis](https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-(YLabels)).

Focus on the following methods:

 - `setStartAtZero(...)`
 - `setAxisMaxValue(...)` & `setAxisMinValue(...)`
 - `setSpaceTop(...)`
 - `setSpaceBottom(...)`

And this: https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport

**Comment by OmarHassan25** [comment]
This does not solve the problem, Please help
