### ISSUE TITLE
Reset dragging issue

### ISSUE THREAD

**Issue by Brian0122** [PhilJay/MPAndroidChart#684]
Hi Phil, 
I'm drawing multi data set bar chart, and met a reset scale and dragging issue.
I think it's like the closed issue #431. 
When first load the data and scroll to see more items, then filter data with less data shown.
The dragging is still remaining to previous dataset, so I have to scroll back o see the filtered data.
I have try fitScreen but it's no luck.
Is it possible to reset scale/dragging and display from first position as chart initialization?
Thank you!

**Comment by PhilJay** [comment]
Maybe you can find something here: https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport

**Comment by krupalagile** [comment]
Nothing found working. moveViewTo... methods aren't working. can you please provide an example for that?

**Comment by KirilKovachev** [comment]
Did you find solution on this ? To me the issue occurs when dragging - then IAxisValueFormatter is initiated. If dataset gets reloaded while  IAxisValueFormatter is still running, the scale and dragging is not reset even though chart.fitScren() is called in the end of dataset reload
