### ISSUE TITLE
ScatterChart.invalidate() after moveViewToX() causes rendering issues

### ISSUE THREAD

**Issue by Faltenreich** [PhilJay/MPAndroidChart#686]
Hello Philipp Jahoda,

first of all thank you for your great work and your effort that you put in this excellent library. It is much appreciated!

Sadly I currently have a problem with the moveViewToX()-method of the BarLineChartBase - maybe connected with #541 . It seems that sometimes the chart gets not rendered correctly after calling moveViewToX() and then invalidate().
OnActivityCreated I initialize my ScatterChart with some data and then move the view to some point via the moveViewToX()-method. Next I implemented an automatic scroll through a Handler that is moving the view via the same method X times a second until a target destination has been reached. Both actions stripped down look like this:

```
chart.moveViewToX(INTEGER);
chart.invalidate();
```

After these steps the chart (more or less reproducible) has been moved to a wrong position: at the startup not a bit and after the automatic scroll action a few indices too little. Interestingly it jumps to the correct position when I tap on the chart. Seems to me like the chart has the expected viewport but gets not rendered correctly / invalidate() is not working correctly.
Am I missing something for moving the viewport correctly or is this a bug?

(Maybe connected, maybe a separate issue:)
Additionally moving the chart programmatically via moveViewToX() (or respectively moveViewTo()) has no effect when the chart is currently scrolling (caused by a Scroll- or Fling-event). Is there a way to interrupt currently running scrolling actions to move the chart programmatically?

Thank you in advance.

Best regards from Germany,
A namesake

**Comment by kendix** [comment]
I can confirm that this is an issue. I am currently trying to find a workaround and I will edit/respond if I find a fix.

**Comment by PhilJay** [comment]
Are you still experiencing this issue with newer versions of the library?
I did some fixes in that direction.
