### ISSUE TITLE
Line Chart

### ISSUE THREAD

**Issue by rajadva** [PhilJay/MPAndroidChart#687]
Hi ,
     I dont want to show the values in line chart by default.Can you please help me how to remove the values which is shown in the line chart?

Thanks,
Yuvaraj.D

**Comment by rajadva** [comment]
hi i didn't get solution but you closed it without giving solution?

**Comment by sideris** [comment]
Hello @rajadva . My guess is that he closed the issue, because it's mostly a programming knowledge question, rather than an issue. I would suggest you to read the docs, go to stackoverflow, try things out yourself.

**Comment by rajadva** [comment]
Hi Sideris, yes ur right. I got it thanks:)
