### ISSUE TITLE
Line Chart

### ISSUE THREAD

**Issue by rajadva** [PhilJay/MPAndroidChart#688]
Hi ,
I dont want to show the values in line chart by default.Can you please help me how to remove the values which is shown in the line chart?

Thanks,
Yuvaraj.D

**Comment by PhilJay** [comment]
Don't create duplicate issues. I do not have the time to answer questions from authors who don't even want to invest half a minute to understandably describe their problem.

If you don`t want to show values, don't add them until you want to show them.
