### ISSUE TITLE
Can we customise design of donut based on our custom design needs?

### ISSUE THREAD

**Issue by syeduzairshah** [PhilJay/MPAndroidChart#691]
I want to customise donut design based on client custom needs, can I create something similar using MPAndroid PieChart ?

![img1](https://cloud.githubusercontent.com/assets/4517172/7811043/9b365966-03c0-11e5-8105-4556ef5ccef0.jpg)
![img3](https://cloud.githubusercontent.com/assets/4517172/7811044/9b3a886a-03c0-11e5-8194-a0ec9e9a1d9c.png)

**Comment by danielgindi** [comment]
For whatever is in the middle, you could draw behind the chart or over it.
For the icons, there's a PR pending, but not allowing labels simultaneously I think. @PhilJay do you want to accept the icons PR to a separate branch so I can work on it and improve before merging?

**Comment by PhilJay** [comment]
I just merged the PR with some modifications into the experimental branch.
You can check it out there. I didn't really like that the integration of the images was tied to the x-axis. It like it more to have a `PieEntry` with a separate constructor that allows to add bitmaps.

**Comment by danielgindi** [comment]
Yes that's what I thought... I'll look into it

**Comment by rohitgarg29** [comment]
Hi I would like to ask if these changes ever merged into the main library as i also have the similar kind of need right now?
