### ISSUE TITLE
Auto zooming or auto set range

### ISSUE THREAD

**Issue by elnatand** [PhilJay/MPAndroidChart#692]
I want to show only third of the line chart on the screen. 

I did it with mChart.setVisibleXRange().

The Y values are very small, hence I did manual zoom by setting range to the chart with the functions:

mChart.getAxisLeft().setAxisMaxValue(maxValue);
mChart.getAxisLeft().setAxisMinValue(minValue);

I’m interested on zooming only on the visible part of the chart so I took max\min value only on the visible part of the chart.

It caused some problem: when I scrolled left to the rest part of the chart, some points where not shown because their Y value was over the min/max value that I set.

This is the time to mention that I want zoom or fixed range only on the visible part of the chart.

Is there auto zooming or auto range function according to the Y values of the given points of the visible part?

**Comment by PhilJay** [comment]
What about `setVisibleYRange(...)`? https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport

**Comment by Ornolfr** [comment]
@PhilJay this is no what we ask about. We want to be able to zoom to specific range of Y values, like: `zoomY(yMin, yMax)`.
