### ISSUE TITLE
PieChart not rendered correctly on Round Android Wear

### ISSUE THREAD

**Issue by Lekic** [PhilJay/MPAndroidChart#696]
There is no way to make the pie chart fill the whole watch face. Unlike the legend, when you have no description on the chart, the space below the chart is still reserved.

You need to implement a way that just the chart without any supporting text/legends can be rendered and consume the whole round face for an effective representation.

**Comment by PhilJay** [comment]
So you disabled the legend?
`chart.getLengend().setEnabled(false)`

Maybe you can try setting custom offsets to 0:
https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport

Check out the `setViewPortOffsets(...)` method.

**Comment by Lekic** [comment]
I have disabled the legend, but the chart does not render correctly due to the space left below for the description that is set to empty.

All viewport modifications you linked are not applicable to Pie Charts.

**Comment by PhilJay** [comment]
Ow yea haha :-D
It has gotten so complex I dont even know my own library anymore. Could you post a screenshot of the problem?

**Comment by Lekic** [comment]
I can imagine, you have a lot of features. :)
Sure thing, I've attached two shots below. Note: the chart is the only thing in the activity is set to match_parent for both width and height.

![img_20150601_055644](https://cloud.githubusercontent.com/assets/4584883/7903548/3f347924-0823-11e5-9363-e52c75bec665.jpg)
![android wear screenshot](https://cloud.githubusercontent.com/assets/4584883/7903549/3f60103e-0823-11e5-83a5-876d49c23b1b.jpg)

**Comment by PhilJay** [comment]
Hmmm, have you tried centering the chart into the parent layout via xml?

**Comment by Lekic** [comment]
It is centred. The mNoDataText is perfectly centred, but when there is data and the graph is rendered it it raised for some reason... :/
