### ISSUE TITLE
Line break for labels

### ISSUE THREAD

**Issue by Faltenreich** [PhilJay/MPAndroidChart#697]
Hello Philipp,

is it possible to add a line break to a chart label or respectively a multi-line label, for example to show hours in one line and days in the next (like in the screenshot below at the yellow highlighted label)? 

![unbenannt](https://cloud.githubusercontent.com/assets/7239950/7833627/724240a8-0468-11e5-8c19-5c7cbe7a920f.PNG)

I tried adding "\n" and "< br>" to the string but it either gets ignored or simply gets displayed. Seems like you don't work with a normal TextView or WebView here.

Thank you very much in advance and have a nice day!

A namesake

**Comment by Grch** [comment]
Hello, had same issue, but adding "\n" to the label helped me. But these multiline labels are centered on the X axis: one at the top, another at the bottom, whereas I'm using setPosition(XLabels.XLabelPosition.BOTTOM). Can I stay here with my problem? may be someone could help me too :+1:
