### ISSUE TITLE
Enable bar on start

### ISSUE THREAD

**Issue by mbcampolino** [PhilJay/MPAndroidChart#699]
hi thanks for your library..

how do I start a horizontal bar as selected?

**Comment by PhilJay** [comment]
Be more clear.

**Comment by mbcampolino** [comment]
for example I have 4 bars, I want to start a selected according to a posted position (in image position 1...). Sorry for my bad English. I am Brazilian.
![Image of Yaktocat](http://codecampos.com.br/coisas/image.png)

**Comment by PhilJay** [comment]
Keyword "highlighting": https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart

**Comment by mbcampolino** [comment]
thanks
