### ISSUE TITLE
Line Chart won't draw on Fragment create

### ISSUE THREAD

**Issue by JasonCromer** [PhilJay/MPAndroidChart#700]
When starting my application and swiping to the Fragment that has the chart layout, the chart shows that I have no data via me setting:
 myChart.setNoDataTextDescription("You need to provide data for the chart.");

However, this worked with the Bar Graph, so I am confused as to why the graph is not being animated/created when swiping to the fragment. I will post my code below:

public class FragmentB extends Fragment implements View.OnClickListener {

    protected View view;
    protected LineChart myChart;
    protected Button refreshButton;
    protected float[] dataArray = new float[10];
    protected float myDataFloat;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        view = inflater.inflate(R.layout.fragment_b, container, false);

        myChart = (LineChart) view.findViewById(R.id.chart1);
        refreshButton = (Button) view.findViewById(R.id.getDataButton);
        refreshButton.setOnClickListener(this);

        float[] userData = GetUserData();
        setUserData(userData);
        setupChart();
        myChart.invalidate();

        return view;
    }

    private float[] GetUserData() {
        ParseUser currentUser = ParseUser.getCurrentUser();
        final String currentUserString = currentUser.getString("username");

        ParseQuery<ParseObject> query = ParseQuery.getQuery("DeadLift");
        query.whereEqualTo("Username", currentUserString);
        query.whereExists("DeadLiftData");
        query.orderByAscending("createdAt");
        query.findInBackground(new FindCallback<ParseObject>() {
            @Override
            public void done(List<ParseObject> list, ParseException e) {
                if (list == null) {
                    Toast.makeText(getActivity(), "Data retrieval failed. Please try at another time.", Toast.LENGTH_LONG).show();
                } else {
                    int i = 0;
                    for (ParseObject dataObject : list) {
                        final String eachPR = dataObject.getString("DeadLiftData");
                        myDataFloat = Float.valueOf(eachPR);
                        dataArray[i] = myDataFloat;
                        i++;
                    }
                }
            }
        });

        return dataArray;
    }

    private void setUserData(float[] dataValues) {

        //Create an array to add datasets to
        ArrayList<LineDataSet> dataSets = new ArrayList<>();

        // Create a value set, 1
        ArrayList<Entry> valueSet1 = new ArrayList<>();

        //Loop through each value in array and assign to a new bar
        for(int i = 0; i < dataValues.length; i++) {
            if(dataValues[i] > 10.0) {
                Entry thisEntry = new Entry(dataValues[i], i);
                valueSet1.add(thisEntry);
            }
        }

        LineDataSet set1 = new LineDataSet(valueSet1, "DataSet 1");
        set1.setAxisDependency(YAxis.AxisDependency.LEFT);
        set1.setLineWidth(1.75f);
        set1.setCircleSize(3f);
        set1.setColor(Color.WHITE);
        set1.setCircleColor(Color.BLUE);
        set1.setHighLightColor(Color.WHITE);
        set1.setDrawValues(true);
        set1.setValueTextSize(8f);
        set1.setValueTextColor(Color.WHITE);

        dataSets.add(set1);

        ArrayList<String> xVals = new ArrayList<>();
        for(int i = 0; i < mMonths.length; i++) {
            xVals.add(mMonths[i]);
        }

        LineData data = new LineData(xVals, dataSets);
        
        myChart.setData(data);
    }

    private void setupChart() {

        // no description text
        myChart.setDescription("");
        myChart.setNoDataTextDescription("You need to provide data for the chart.");

        // enable/disable grid background
        myChart.setDrawGridBackground(false);

        //enable touch gestures
        myChart.setTouchEnabled(true);

        //disable scaling and dragging
        myChart.setDragEnabled(false);
        myChart.setScaleEnabled(false);
        myChart.setPinchZoom(false);

        //get the legend (only possible after setting data)
        Legend chartLegend = myChart.getLegend();
        chartLegend.setEnabled(false);

        myChart.getAxisLeft().setEnabled(true);
        myChart.getAxisRight().setEnabled(false);
        myChart.getXAxis().setEnabled(true);
        myChart.getXAxis().setTextColor(Color.WHITE);
        myChart.getAxisLeft().setTextColor(Color.WHITE);

        myChart.animateXY(1500, 1000);
    }

    private String[] mMonths = new String[] {
            "JAN", "FEB", "MAR", "APR", "MAY",
            "JUN", "JUL", "AUG", "SEP", "OCT",
            "NOV", "DEC"
    };

    public void onClick(View v){
        final float[] newUserData = GetUserData();
        setUserData(newUserData);
        setupChart();
    }

}

**Comment by PhilJay** [comment]
Honestly I dont know. I just know it works in the example. Maybe you can study it and see if you are doing anything differently.
