### ISSUE TITLE
add button to Markerview doesn't work

### ISSUE THREAD

**Issue by cleverboat** [PhilJay/MPAndroidChart#701]
I want to add a button to markerview so that I could click on the button when markerview show up.
But it doesn't trigger 'OnClickListener'. 
//---------------------MyMarkerView.java---------------------------
    private TextView tvContent;
    private TextView xlabelTextView;
    private Button  btnmarkerButton;
    
    public MyMarkerView(Context context, int layoutResource) {
        super(context, layoutResource);
        
        
        tvContent = (TextView) findViewById(R.id.tvContent);
        xlabelTextView=(TextView)findViewById(R.id.xlabel);
        
        btnmarkerButton=(Button)findViewById(R.id.btn_marker);
        btnmarkerButton.setOnClickListener(new OnClickListener() {
			
			@Override
			public void onClick(View v) {
				// TODO Auto-generated method stub
				
			}
		}); 
    }

**Comment by pranaypatel512** [comment]
hi cleverboat,
try something like this:-
new View.OnClickListener(){
//your stuff
}

**Comment by cleverboat** [comment]
@pranaypatel512 I  have tried,but it still doesn't work.

**Comment by cleverboat** [comment]
![qq 20150611144832](https://cloud.githubusercontent.com/assets/12637389/8101400/65f4c32e-1049-11e5-9ffa-e40e79f98d95.jpg)

**Comment by RadwaHassan** [comment]
Why is this issue closed? Is there a solution?

**Comment by juliusspencer** [comment]
Good question @RadwaHassan Perhaps the answer is in another issue. Let me know if you came to a conclusion on it.

**Comment by juliusspencer** [comment]
Looking at this comment I suspect this in the enhancement category.
[https://github.com/PhilJay/MPAndroidChart/issues/144](https://github.com/PhilJay/MPAndroidChart/issues/144)

**Comment by juliusspencer** [comment]
I made a solution of sorts:
http://stackoverflow.com/questions/37959156/mpandroidchart-button-click-in-markerview/37984995#37984995
