### ISSUE TITLE
Importing project Error

### ISSUE THREAD

**Issue by alburaawi** [PhilJay/MPAndroidChart#706]
I'm trying to import the library via ```build.gradle``` and for some reason it's giving me an error. 
```javas
Error:(42, 13) Failed to resolve: com.github.PhilJay:MPAndroidChart:v2.1.0
Show in File
Show in Project Structure dialog
```

I tried ```compile 'com.github.PhilJay:MPAndroidChart:v2.1.0'```

Any ideas of how to solve it! Thanks.

**Comment by Faltenreich** [comment]
Did you miss to add the maven repository?

```
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.PhilJay:MPAndroidChart:v2.1.0'
}
```

**Comment by alburaawi** [comment]
Thanks mate, i forgot to add that and it works now.
