### ISSUE TITLE
Piechart hide titles?

### ISSUE THREAD

**Issue by faizandedia** [PhilJay/MPAndroidChart#709]
how to disable pie chart xValues? only want to show the values for that.

PieData data = new PieData(xVals, dataSet);
data.setDrawValues(true);
I can disable the value , but there is not method to disable the xVal?

**Comment by PhilJay** [comment]
This has been asked a thousand times, and it's int he documentation: https://github.com/PhilJay/MPAndroidChart/wiki/Specific-chart-settings

`pieChart.setDrawSliceText(false)`

**Comment by faizandedia** [comment]
Thank you..!!!
