### ISSUE TITLE
Bug that changes filled lines to regular lines when scrolling in v2.1.0

### ISSUE THREAD

**Issue by SjoerdvGestel** [PhilJay/MPAndroidChart#711]
Hi, just tried out v2.1.0, sadly it didn't fix my previous issue.
I noteced a new issue with scrolling to the graph with the same setup:
when scrolling trough it, it will make filled lines switch to regular lines for a short while. 

I will try to get some more details or a visual examle of what i experiance.

**Comment by SjoerdvGestel** [comment]
video of the glitch: https://vid.me/delete/22yirr1i4kxwk0s8kw0okocws

It currently only happends on the phone i use as a daly driver, Genymotion does not encouter the same  glitch

**Comment by AlBirdie** [comment]
Same issue here. Occasionally, the fill is getting removed from a line chart.

**Comment by MGaetan89** [comment]
Same for me when zooming, or sometimes without doing anything (on a tablet when the chart takes the whole screen).

**Comment by joshfriend** [comment]
Check logcat for warnings while rendering the graph. I get this when I zoom in too far on a section of a chart and the fill disappears:

```
W/OpenGLRenderer﹕ Path too large to be rendered into a texture
```

People on StackOverflow [recommend disabling hardware acceleration](http://stackoverflow.com/a/10002630/1255482), though I haven't had much luck with that. I just stick to limiting the zoom.

**Comment by danielgindi** [comment]
Well, the path is too large. Android's renderer does not know how to cut a path to the visible part and render only that. It tries to allocate a bitmap for the whole thing. If there won't be a systematic solution, we'll need to come up with a way to cut the path ourselves, which is complex when there's curved paths.

**Comment by AlBirdie** [comment]
Won't the path be drawn for the start and end x values only? 
If not, what has changed from 2.0 to 2.1 that the path is too large now?

**Comment by danielgindi** [comment]
Before, there were bugs drawing the last point etc. Sometimes curves turned into lines etc. We changed things a little to fix that...
