### ISSUE TITLE
yAxis not visible properly, if chart rightAxis.setEnabled(true) =  and  leftAxis.setEnabled(false);

### ISSUE THREAD

**Issue by ordele** [PhilJay/MPAndroidChart#712]
Hi Phile,
yaxis not visble properly,what did i do wrong?
here are my changes:
  YAxis leftAxis = mChart.getAxisLeft();
        leftAxis.setEnabled(false);
        leftAxis.setLabelCount(7);
        leftAxis.setDrawGridLines(false);
        leftAxis.setDrawAxisLine(false);
        leftAxis.setStartAtZero(false);

        YAxis rightAxis = mChart.getAxisRight();
        rightAxis.setEnabled(true);

 
![device-2015-06-02-113708](https://cloud.githubusercontent.com/assets/12711000/7932022/e4920116-091d-11e5-8c57-e933538df961.png)

**Comment by PhilJay** [comment]
Are you plotting your data against the right axis?

`dataSet.setAxisDependency(AxisDependency.RIGHT)`
