### ISSUE TITLE
Showing Star in barchart 

### ISSUE THREAD

**Issue by Nyan274** [PhilJay/MPAndroidChart#717]
How do i add a star in the barchart like this? Assume this is single bardataset

![68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d5043686172742f6d61737465722f73637265656e73686f74732f73696d706c6564657369676e5f6261726368617274332e706e67](https://cloud.githubusercontent.com/assets/1953619/7989661/9a5aac36-0b1d-11e5-8758-9185f491fefd.png)

**Comment by PhilJay** [comment]
You will have to rewrite the library to your needs to achieve this.
