### ISSUE TITLE
what is mParties ?

### ISSUE THREAD

**Issue by smemamian** [PhilJay/MPAndroidChart#719]
Hi

In the below class, what is mParties?

https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/PieChartActivity.java#L34

I get this message : 

Cannot resolve symbol 'mParties '

**Comment by PhilJay** [comment]
It's a protected variable inherited from the baseclass.
