### ISSUE TITLE
Multiple Y-Axes

### ISSUE THREAD

**Issue by oli107** [PhilJay/MPAndroidChart#72]
This is a great library, really appreciate all the work you are putting into it and all the recent updates. Have you considered supporting multiple Y-Axes? 

Thanks

Oli

**Comment by PhilJay** [comment]
Since the latest pre-release, this is possible.

Best regards,
Phil

**Comment by mirowane** [comment]
I only found support for 2 y-axes. Can anybody please explain how to implement 3 and more y-axes?

**Comment by unchiujar** [comment]
@mirowane Did you find a way to implement 3 or more axes ?

**Comment by zkdzegede** [comment]
+1 for 3 or more axes

**Comment by rolyanos** [comment]
Hello, can anybody provide the solution to this issue?

**Comment by vojto** [comment]
Hi,

Also needing this. I understand that the easiest way now is to normalize all data to use same range of values.

**Comment by bdeshong** [comment]
+1 for this, too.  Trying to graph three distinct values with different units across a single timespan.

**Comment by AppDevMichael** [comment]
+1, this would be awesome.

**Comment by almic** [comment]
Um, [this exists](https://github.com/PhilJay/MPAndroidChart/wiki/YAxis)?
