### ISSUE TITLE
mXVals to long

### ISSUE THREAD

**Issue by vincent-leonardo** [PhilJay/MPAndroidChart#721]
Thanks for the awesome library, it's not easy to find a library that has beautiful & yet smooth and responsive UI for large dataset.

I've read through several open & closed issues regarding Time-based support. I, myself had tried to create this functionality by extending and modifying certain classes (CustomXAxisRenderer, CustomAxisFormatter). So far, I've managed to create a graph with time-based x-axis with equally-distributed time. My approach is simply generating xAxis values with fixed interval and automatically modify the *XIndex* for each entry to its index in the new xAxis.

It's almost ready to be used but I hit a wall when testing for large dataset support, when the timespan get too large (more than 1 years) with interval of 1 minute, which results in 525600~ values on XAxis. As the structure originally used for **XAxis**'s *mValues* is ***List\<String\>*** it quickly hits the memory cap. I tried generate equal as well as larger amount of data in ***long[ ]*** and it has no problem.

I can create an extended class of **XAxis** with ***long[ ]*** as value and pass on to the chart's axis renderer but it seems that the **ChartData** class requires ***List\<String\>*** as its *xVals* as well. 

So, I was wondering would it be feasible to change the **ChartData**'s *xVals* to ***long[ ]*** instead since a lot of other components are based on **ChartData**?

**Comment by PhilJay** [comment]
I see your problem but unfortunately this requires huge changes that are currently not suitable. There are hundreds (if not thousands) of people using this library, and I cannot make changes like that just for the sake of one person, since this would most likely interfere with the implementation of other users.
