### ISSUE TITLE
BarChart moveViewToX() issue

### ISSUE THREAD

**Issue by stairs** [PhilJay/MPAndroidChart#722]
Many thanks for a great library!

I have a few questions on moving bar chart to a certain x position. What I'm doing is the following:
```java
mBarChart.zoom(scaleX, 1, 0, 0);
mBarChart.moveViewToX(xPos);
mBarChart.invalidate();
```
This results in chart being moved on just a few positions. It seems to me that the actual number that should be passed to the method is not x, but rather x * numberOfDataSets. However the result in this case is also not precise. Could you please advice on how to use this method correctly?

Another question is about performing the same set of actions just after the view has been actively scrolled. If I try to perform this piece of code just after scrolling the chart, the resulted zoom and x position are not correct. Is there any build in way to stop propagating scrolling events in order to make zooming and moving chart actions work fine?

Thanks in advance!

PS I'm using 2.1.0 version of the lib

**Comment by PhilJay** [comment]
Yes, that method is actually "not that clear" for the barchart in case there are multiple datasets.

You will have to consider the following factors:
 - each bar exactly uses a space of 1 (the width of the bar + barspace)
 - the groupspace, which is set for the `BarData` object and separates "groups" of bars

**Comment by stairs** [comment]
Many thanks for a quick answer! Now it works fine!
However, I probably haven't explained the second question good enough. I'll create a new issue for that. Thanks again!
