### ISSUE TITLE
incompatible types: View cannot be converted to PieChart

### ISSUE THREAD

**Issue by Rensodiaz** [PhilJay/MPAndroidChart#725]
I just start a simple project to use the library but I'm getting this error: incompatible types: View cannot be converted to PieChart. I'm using android studio 1.2.2 and this is where I'm getting it.

private PieChart mChart;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_pie_chart);

        mChart = (PieChart) findViewById(R.id.chart1); ---->Here is the problem, really weird because I'm following you example code. 
    }
is there anything I'm missing here, and thanks in advance.

**Comment by PhilJay** [comment]
I have no idea, this is more a general android question than something related to the library. Maybe you did not reference the dependency correctly.
