### ISSUE TITLE
Negative Value didn't show on Horizontal bar chart

### ISSUE THREAD

**Issue by bishinew** [PhilJay/MPAndroidChart#727]
Negative Value didn't show on Horizontal bar chart for       

 leftAxis.setStartAtZero(false);

Any suggestion?

**Comment by PhilJay** [comment]
Post a screenshot.

Also, call `rightAxis.setStartAtZero(false)`

**Comment by bishinew** [comment]
Thank you very much for reply.

**Comment by suvDev** [comment]
@PhilJay The bar is overlapping the negative values, please have a look https://stackoverflow.com/questions/59541099/set-the-negative-values-to-the-left-of-the-bars-in-horizontal-bar-chart
