### ISSUE TITLE
Piechart crash

### ISSUE THREAD

**Issue by kumark86** [PhilJay/MPAndroidChart#729]
When try to draw piechart, we got the following error. Please resolve the issue.

android.graphics.Canvas.
in Canvas.java, line 136

Reason: java.lang.NullPointerException

1 android.graphics.Canvas. Canvas.java, line 136
2 com.github.mikephil.charting.renderer.PieChartRenderer.drawData PieChartRenderer.java, line 100
3 com.github.mikephil.charting.charts.PieChart.onDraw PieChart.java, line 96
4 android.view.View.draw View.java, line 14728
5 android.view.View.getDisplayList View.java, line 13588
6 android.view.View.getDisplayList View.java, line 13635
7 android.view.View.draw View.java, line 14430
8 android.view.ViewGroup.drawChild ViewGroup.java, line 3252
9 android.view.ViewGroup.dispatchDraw ViewGroup.java, line 3070
10 android.view.View.getDisplayList View.java, line 13580
11 android.view.View.getDisplayList

**Comment by PhilJay** [comment]
Are you using the latest version 2.1.0?
