### ISSUE TITLE
Ability to Wrap and show X Labels

### ISSUE THREAD

**Issue by Praveen2106** [PhilJay/MPAndroidChart#73]
Hi Phil,
Thanks for your library. Previously I was using achartengine, which allows wrap X Labels manually by adding new line character (\n), which was really useful when you need to show a Time Stamp as X labels. But here, the new line character doesn't work, it shows the entire String in a single line. Is there any other way to wrap the contents of X labels?

**Comment by thomasfeduk** [comment]
Hey @PhilJay, we are testing the ability to wrap the text displayed on the pie slices of pie charts and I see that you said the newline functionality was added, but its still ignoring "\n" in our test cases. Is there something we are overlooking?

Sample:
ArrayList<String> xVals= new ArrayList<String>();
names.add("Make new \n line here");
PieData data = new PieData(xVals, set1);
