### ISSUE TITLE
Problem with zooming when the chart is being scrolled

### ISSUE THREAD

**Issue by stairs** [PhilJay/MPAndroidChart#730]
Hello Phillip,
I'd be very thankful if you could give me an advice on how to deal with the following case.

When user scrolls back to the beginning of chart I load additional data, reload the chart and try to zoom in order to make only a certain amount of entries to be visible on the screen. Here is the code:
            mBarChart.setData(chartData);
            int xvalcount = mBarChart.getXValCount();
            final float scaleX = xvalcount / 7f;
            mBarChart.zoom(scaleX / mBarChart.getScaleX(), 1, 0, 0);
            mBarChart.animateY(1000);

If the chart is not scrolling at the moment the logic works just fine. However, otherwise zooming is not applied correctly (visually it seems like the scale is left the same).

Thanks for your time!

**Comment by PhilJay** [comment]
Are you working with the listeners and calling the zoom method upon translating?

**Comment by stairs** [comment]
Yes, I tried to do it this way. However the default touch listener passes only ACTION_MOVE motion events which doesn't suit me as I need to perform the code only once (on ACTION_UP lets say). So for now I just load the data on demand (special button) and the described behavior reproduces each time if the chart is being scrolled at the moment.

I can send you a sample project and video if you like.

**Comment by PhilJay** [comment]
Yes a video would be great

**Comment by stairs** [comment]
I've emailed you a link to the video. Many thanks for being ready to help.

**Comment by stairs** [comment]
I'm sorry to bother you again, but do you have any thoughts on the source of the problem?
