### ISSUE TITLE
Vertical Bar Chart with x Label in Angle Position

### ISSUE THREAD

**Issue by bishinew** [PhilJay/MPAndroidChart#731]
In some cases,  x Label is long and takes much space. We also need to show each label. So we would like to display the label in an angle. Is there any way to do this?

**Comment by PhilJay** [comment]
There is no way to rotate the labels. With `xAxis.setLabelsToSkip(0)` you can force draw all labels, but then they might overlap.

**Comment by bishinew** [comment]
Please add this feature to make your product stand out. We also use the AChartEngine which has this feature. Thanks.

**Comment by hfahmy** [comment]
+1

**Comment by hardikamal** [comment]
+1

**Comment by RobotFish** [comment]
+1

**Comment by opswhisperer** [comment]
+100
