### ISSUE TITLE
piechart display after click on piechart area !!!

### ISSUE THREAD

**Issue by pranaypatel512** [PhilJay/MPAndroidChart#732]
i have filled all required data into dataset of graph(with x-axis values and y-axis values).
but on first time rendering chart it will not display.after click or touch on chart area it will display.

**Comment by PhilJay** [comment]
provide code

**Comment by pranaypatel512** [comment]
![screenshot_1_empty](https://cloud.githubusercontent.com/assets/10808436/8078845/1f68926c-0f7e-11e5-88ac-59e33aa65881.png)
![screenshot_2 _withchartpng](https://cloud.githubusercontent.com/assets/10808436/8078844/1f682516-0f7e-11e5-9ba2-8d3cf2d81106.png)

**Comment by pranaypatel512** [comment]
/**
	 * initialize pie chart
	 */
	private void initPieChart() {

		Log.e(TAG, "Init Pie Chart");
		mPieChartPortfolio.setDescription("");
		mPieChartPortfolio.setNoDataText("No chart data avaiable");
		mPieChartPortfolio
				.setNoDataTextDescription("You need to provide data for the chart.");
		mPieChartPortfolio.setHighlightEnabled(true);
		mPieChartPortfolio.setTouchEnabled(true);

		mPieChartPortfolio.setDrawHoleEnabled(true);
		mPieChartPortfolio.setHoleColorTransparent(true);
		mPieChartPortfolio.setTransparentCircleRadius(Color.WHITE);

		mPieChartPortfolio.setHoleRadius(0f);
		mPieChartPortfolio.setTransparentCircleRadius(0f);

		mPieChartPortfolio.setRotationAngle(360 - 135f);
		mPieChartPortfolio.setRotationEnabled(false);
		mPieChartPortfolio.setHorizontalScrollBarEnabled(true);
		Log.i("asset_length", arrAssetName.length + "");
		setChartData(arrAssetName.length, 100);

		Legend legend = mPieChartPortfolio.getLegend();
		legend.setEnabled(false);

	}

	private void setChartData(int count, int range) {

		Log.e(TAG, "Set Data");
		// temporary data
		arrValue = new float[] { perGold, perSilver, perPlatinum, perPalladium };
		// y value
		ArrayList<Entry> yValues = new ArrayList<Entry>();
		for (int i = 0; i < count; i++) {
			yValues.add(new Entry((float) (arrValue[i]), i));

		}

		// x value
		xValues = new ArrayList<String>();
		for (int i = 0; i < count; i++) {
			String str = arrValue[i] + "";
			if (str.toString().equals("0.0")) {
				arrAssetName[i] = "";
			}
			xValues.add(arrAssetName[i]);
		}

		PieDataSet dataSet = new PieDataSet(yValues, "Assets");
		dataSet.setSliceSpace(0f);
		dataSet.setSelectionShift(5f);

		// set colors
		ArrayList<Integer> colors = new ArrayList<Integer>();

		for (int c : ColorTemplate.createColors(new int[] { COLOR_GOLD,
				COLOR_SILVER, COLOR_PLATINUM, COLOR_PALLADIUM }))
			colors.add(c);

		colors.add(ColorTemplate.getHoloBlue());
		dataSet.setColors(colors);

		mPieDataPortfolio = new PieData(xValues, dataSet);
		mPieDataPortfolio.setValueFormatter(new PercentFormatter());
		mPieDataPortfolio.setValueTextSize(12f);
		mPieDataPortfolio.setValueTextColor(contextAct.getResources().getColor(
				R.color.white));
		mPieChartPortfolio.setData(mPieDataPortfolio);

		mPieChartPortfolio.setHighlightEnabled(true);
		Log.i("pie chart set===>", "pie chart set===>");
	}

**Comment by PhilJay** [comment]
call `invalidate()` after all setup

**Comment by pranaypatel512** [comment]
HI PhilJay,
after called invalidate() its worked.

**Comment by harshitha93** [comment]
I need to show data on click of particular portion on the pie chart..like a label..how to do it ?

**Comment by anilthummar** [comment]
Hii

Override onNothingSelected() and onValueSelected method.

public void onNothingSelected() {
        Log.i("PieChart", "nothing selected");
        try {
            dataSet.getColors().set(intSelectedPos, Color.rgb(3, 3, 3));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
____________________________________________________
public void onValueSelected(Entry e, Highlight h) {

        if (e == null)
            return;
        intSelectedPos = (int) h.getX();
        if (intSelectedPos >= 0) {
            for (int i = 0; i < dataSet.getColors().size(); i++) {
                dataSet.getColors().set(i, Color.rgb(3, 3, 3));
            }
            if (intSelectedPos == (int) h.getX()) {
                dataSet.getColors().set(intSelectedPos, Color.rgb(1, 229, 68));
            }
        }

        
        Log.i("VAL SELECTED", "Value: " + e.getY() + ", index: " + h.getX() + ", DataSet index: " + h.getDataSetIndex());

    }

**Comment by thohagungnarso** [comment]
> call `invalidate()` after all setup

Perfect !

**Comment by shridharBanavasi** [comment]
If dataset is changing,call notifyDataSetChanged() will help before calling invalidsate()
