### ISSUE TITLE
hi,how can i set all line of grid background to dotted line?

### ISSUE THREAD

**Issue by wonghoman** [PhilJay/MPAndroidChart#733]
![issue](https://cloud.githubusercontent.com/assets/6296547/8077623/e348e82a-0f89-11e5-8488-01728b993bd8.png)
as you see, i have set the horizontal line to dotted line except for the bottom line. 
1: how can i set all line of grid background to dotted line? 
2: how to hide the lable in red circle part?
3: how to set the spacing of the left and right axes have the same length, which makes two dotted lines in horizontal direction coincide?(e.g. like this "30- - - - - -100","60- - - - - -200" in my upload picture)

**Comment by PhilJay** [comment]
1. you can do that via `XAxis` and `YAxis`
2. that is the label you provided for your dataset, provide "" and it will be gone
3. you cannot, since the axes have different scaling. what you can do is hide the line on one of the axes

**Comment by wonghoman** [comment]
1: 
XAxis xAxis = mChart.getXAxis();
xAxis.enableGridDashedLine(10f, 10f, 0f);
// xAxis.setTypeface(tf);
xAxis.setTextSize(12f);
xAxis.setTextColor(Color.BLACK);
xAxis.setDrawGridLines(true);
xAxis.setDrawAxisLine(true);
xAxis.setSpaceBetweenLabels(1);
xAxis.setPosition(XAxisPosition.BOTTOM);

i use this code, but it can't show me the dotted line of  vertical direction, why?

2: i provide "" and "AAA""BBB" was gone, but the color bar which left of "AAA""BBB" still showing, what should i do?
