### ISSUE TITLE
Problem in setting Visible range

### ISSUE THREAD

**Issue by badhriappadoodle** [PhilJay/MPAndroidChart#734]
setVisibleXRangeMaximum(float maxXRange) and
setVisibleXRangeMinimum(float minXRange) functions not detected as shown in https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport
Only setVisibleXRange() is working.
With setVisibleXRange(), the zoomout doesn't work.

**Comment by badhriappadoodle** [comment]
Fixed with chart.zoom(scaleX / chart.getScaleX(), 1, 0, 0); function....cheers

**Comment by pranaypatel512** [comment]
hi badhriappadoodle,
i think you passed scaleY as 1(sec args).You should try something else,because scaleY=1=no Zoom.
please show attachment for more.
thanks
![git_post](https://cloud.githubusercontent.com/assets/10808436/8082765/4493c07e-0f9d-11e5-8761-995298d12fcd.png)

**Comment by badhriappadoodle** [comment]
Hey pranaypatel512,
Yes, I basically want the Yaxis scale to be fixed and the Xaxis alone to be zoomed.
Cheers.

**Comment by pranaypatel512** [comment]
hi badhriappadoodle,
got it :+1:

**Comment by PhilJay** [comment]
I no longer understand where the problem is to be honest

**Comment by dcale** [comment]
the problem is:
1. that you cannot zoom out once you've set setVisibleXRange(),
2. that your documentation is outdated (setVisibleXRangeMinimum and setVisibleXRangeMaximum does not exist)

please reopen
