### ISSUE TITLE
hi, something about dotted line

### ISSUE THREAD

**Issue by wonghoman** [PhilJay/MPAndroidChart#735]
thank you for your answer!
![issue](https://cloud.githubusercontent.com/assets/6296547/8077623/e348e82a-0f89-11e5-8488-01728b993bd8.png)
1: 
XAxis xAxis = mChart.getXAxis();
xAxis.enableGridDashedLine(10f, 10f, 0f);
// xAxis.setTypeface(tf);
xAxis.setTextSize(12f);
xAxis.setTextColor(Color.BLACK);
xAxis.setDrawGridLines(true);
xAxis.setDrawAxisLine(true);
xAxis.setSpaceBetweenLabels(1);
xAxis.setPosition(XAxisPosition.BOTTOM);

i use this code, but it can't show me the dotted line of vertical direction, why?

2: i provide "" and "AAA""BBB" was gone, but the color bar which left of "AAA""BBB" still showing, what should i do?

**Comment by PhilJay** [comment]
`chart.getLegend().setEnabled(false)`
`yAxis.enableGridDashedLine(10f,10f,0f)`
