### ISSUE TITLE
Use MPAndroidChart with ViewFlipper makes rendering incorrect.

### ISSUE THREAD

**Issue by minamic** [PhilJay/MPAndroidChart#738]
I make 3 charts, and use viewflipper to switch between them. But when i do this. Chart rendering result got weired randomly:
sometimes lost one yAxisLines or incorrect yAxisLines, stickbar's body space not correct, min value of Y is incorrect.
btw, I searched all issues/wiki to set fixed Y range, but i didn't see a mothed 'setYRange' for CandleStickChart.

Appreciate for your work for this library.

**Comment by PhilJay** [comment]
provide screenshots

**Comment by minamic** [comment]
I use candlestickchart from MPAndroid with a little modification(just 3 lines to draw a circle at min and max value).
//----------------CandleStickChartRenderer.java---------------
//Line:151, in method: 
protected void drawDataSet(Canvas c, CandleDataSet dataSet){
//...
            } else { // equal values
                
                mRenderPaint.setColor(Color.BLACK);
                mRenderPaint.setStyle(Paint.Style.STROKE);
                c.drawLine(leftBody, open, rightBody, close, mRenderPaint);
            }
            //custom modify here: draw circle for min max.
            mRenderPaint.setColor(Color.WHITE);
            c.drawCircle(0.5f * (leftBody + rightBody), open, 0.5f * (rightBody - leftBody), mRenderPaint);
            c.drawCircle(0.5f * (leftBody + rightBody), close, 0.5f * (rightBody - leftBody), mRenderPaint);
        }
    }
//----------------------end of method---------------------------
And screenshots.
![image](https://cloud.githubusercontent.com/assets/3139536/8101414/9a1373b2-1049-11e5-86c7-c847edce5b06.png)
loose/incorrect yAxis lines.
![image](https://cloud.githubusercontent.com/assets/3139536/8101405/7fdd3cee-1049-11e5-8fbe-432785b33556.png)
for comparation.

![image](https://cloud.githubusercontent.com/assets/3139536/8101430/b376c53e-1049-11e5-85a8-90c7264c56bb.png)


![image](https://cloud.githubusercontent.com/assets/3139536/8101450/d89a4e1c-1049-11e5-84be-10fc29bf483b.png)
bodyspace not correct for some values.
Y value range is clipped, which i set minYvalue=30, maxYvalue=180 with YStartAtZero(false).

Thanks for your patient.

**Comment by bugadani** [comment]
This issue stands when the charts are in a viewpager, as well, with both BarCharts and LineCharts.
