### ISSUE TITLE
Customize CandleStick

### ISSUE THREAD

**Issue by MGaetan89** [PhilJay/MPAndroidChart#741]
Would it be possible to add the two following customization options to `CandleDataSet`?

- Allow decreasing candles to be filled (like it is currently the case for increasing candles)
- Set the vertical bar color (or at least allow the bar to be the same color as its candle)

**Comment by PhilJay** [comment]
Yes, that is possible:

```java
        dataSet.setDecreasingColor(Color.RED);
        dataSet.setDecreasingPaintStyle(Paint.Style.STROKE);
        dataSet.setIncreasingColor(Color.rgb(122, 242, 84));
        dataSet.setIncreasingPaintStyle(Paint.Style.FILL);
```

**Comment by MGaetan89** [comment]
Thanks for the quick answer!

Is there something for the vertical bar too (the blue one behind each candle).

**Comment by MGaetan89** [comment]
Found it. I have to use `dataSet.setShadowColor(int)` (in case someone else is looking for this).
