### ISSUE TITLE
Invaliding cart not working

### ISSUE THREAD

**Issue by prgwar** [PhilJay/MPAndroidChart#742]
i am following the example provided to change the values when seek bar is changed but invaliding is not working

     seekBar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener() {
                     @Override
               public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {
                setdata(progress, 12);
                barChart.invalidate();

               }

            @Override
            public void onStartTrackingTouch(SeekBar seekBar) {

            }

            @Override
            public void onStopTrackingTouch(SeekBar seekBar) {

            }
        });

**Comment by prgwar** [comment]
can i know where i am making mistake

**Comment by PhilJay** [comment]
given the information you provided me with, I have no idea - you probably forgot to set the listener to the seekbar or something
