### ISSUE TITLE
Pie chart crash on scrolling

### ISSUE THREAD

**Issue by murthyanitaa** [PhilJay/MPAndroidChart#747]
06-11 21:11:49.034: E/AndroidRuntime(4083): java.lang.NullPointerException
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at com.github.mikephil.charting.renderer.PieChartRenderer.drawHole(PieChartRenderer.java:268)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at com.github.mikephil.charting.renderer.PieChartRenderer.drawExtras(PieChartRenderer.java:240)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:101)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.draw(View.java:14614)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13510)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13552)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3092)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13448)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13552)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3092)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13448)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13552)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3092)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13448)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13552)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3092)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13448)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13552)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3092)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13448)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13552)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3092)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13448)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13552)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3092)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13448)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13552)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3092)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13448)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13552)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.draw(View.java:14331)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3118)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2955)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.draw(View.java:14617)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.widget.FrameLayout.draw(FrameLayout.java:472)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.widget.ScrollView.draw(ScrollView.java:1631)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13510)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13552)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.draw(View.java:14331)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3118)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2955)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13505)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13552)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3092)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13448)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13552)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3092)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13448)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.View.getDisplayList(View.java:13552)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1622)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1487)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2580)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2430)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2005)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1076)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5905)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:807)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.Choreographer.doCallbacks(Choreographer.java:601)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.Choreographer.doFrame(Choreographer.java:562)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:791)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.os.Handler.handleCallback(Handler.java:733)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.os.Looper.loop(Looper.java:157)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at android.app.ActivityThread.main(ActivityThread.java:5633)
06-11 21:11:49.034: E/AndroidRuntime(4083): 	at java.lang.reflect.Method.invokeNativ

**Comment by murthyanitaa** [comment]
Saw just now this issue has already been addressed. I just changed the height of the pie chart from WRAP_CONTENT to 150dp. Now it seems to work!

**Comment by ajrulez** [comment]
I have the same issue with mpandroidchartlibrary-2-1-0.jar. Haven't tried any other/older version. I was using match_parent for Height and Width and got the same crash. Setting Height and Width to a fixed value (I used 300 dp for both) worked. Is a fix coming for this? I pretty much copy-pasted the code from Samples:

<com.github.mikephil.charting.charts.PieChart
        android:id="@+id/chart1"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/seekBar1" />

not sure why it crashed for me, but worked in the sample.
