### ISSUE TITLE
Horizontal Bar chart requirement

### ISSUE THREAD

**Issue by murthyanitaa** [PhilJay/MPAndroidChart#748]
![sample](https://cloud.githubusercontent.com/assets/6929302/8116326/220ee42c-109f-11e5-919a-5be729d80278.png)

Can you please help on how to achieve the above? 

I have managed to achieve the following screenshot:
![sample_1](https://cloud.githubusercontent.com/assets/6929302/8116378/6d727b54-109f-11e5-8429-2228033c7ed1.png)

Can you please help me get the labels inside the bar (at the bottom) in multiple sizes?
Also, is it possible to achieve a line around each bar (like the grey line seen in the first screenshot?

Thanks in advance for your help! Really cool library

**Comment by PhilJay** [comment]
Having two (or more) labels inside each bar will require customization, so I don't think that the scenario you are trying to achieve is possible by default.

What you will have to do is modify the library to your needs. Things such as setting different text sizes are already supported.

**Comment by murthyanitaa** [comment]
Understood! Thanks for the help. But can you please point me in the right direction as to where to change the code to customize? 
For instance, I need to add a grey border next to each bar (as shown in the first image above). Where do I need to look to customize? 
Also, I need to change the labels inside the bar chart, at the beginning of the chart (not at the end as displayed).

thanks again for your help!

**Comment by PhilJay** [comment]
Well most of your customizations will happen in the `HorizontalBarChartRenderer` class.

For the grey border I'd simply draw another rectangle over the actual bar with paint-style STROKE instead of FILL.

For the labels, check the `drawValues(...)` method inside the renderer.

**Comment by murthyanitaa** [comment]
Hi Phil, Thanks a lot for your help! I have managed to implement according to my requirements by customizing the library. Just a quick question...is there a way to set max limit to horizontal bar chart? For eg: all my chart values are set to percentage. If my values are 25%, 12%, 10%, 34%, then how can I set max limit as 100 to the y axis?

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-%28YLabels%29

**Comment by murthyanitaa** [comment]
Awesome! Thanks a lot!
