### ISSUE TITLE
MPAndroidChart not fade transitioning with rest of layout

### ISSUE THREAD

**Issue by clay-to-n** [PhilJay/MPAndroidChart#749]
I'm using Android 5 transition animations.  Using a shared element transition and also a fade transition (which I think is the default when makeSceneTransitionAnimation with shared elements).

For some reason, on the transition in, MPAndroidChart gets loaded before everything else, and on the transition out, after everything else.  It's not fading at all like the rest of my layout elements.

I've never run into something like this before, and the Android GraphView library elements transition fine.

Any ideas what could be causing this?

**Comment by PhilJay** [comment]
Interesting, I will look into it.

Could you provide me with the animations you are using?

**Comment by clay-to-n** [comment]
Here's a simple example of the glitch: https://github.com/clay-to-n/MPAndroidChart-transition-glitch

I'm not using my own xml animations - I'm just using a shared element transition, and it uses a fade-out animation by default for the other elements unless you specify otherwise.
