### ISSUE TITLE
Add Candlestick variations

### ISSUE THREAD

**Issue by MGaetan89** [PhilJay/MPAndroidChart#750]
In my application, I display 3 kinds of candlesticks:
- The default (as implemented in your library)
- High/Low
- [Heikin-Ashi](http://www.investopedia.com/articles/technical/04/092204.asp)

The Hight/Low version doesn't show the shadow line. I use this to display them:
```java
new CandleEntry(i, high, low, open > close ? high : low, open > close ? low : high)
```

All of them are displayed as standard candlesticks. I was wondering if you are interested in integrating the two new variations in your library? As I have implemented it in my application, I can send a PR with the appropriate changes.

I though about adding the corresponding logic in `CandleEntry`. What do you think?

**Comment by PhilJay** [comment]
The way I see it this does not require any additional implementation, since the Heikin-Ashi simply modifies the values, but other than that works like a normal candle-stick chart. All you have to do is provide the modified values in the constructor.
