### ISSUE TITLE
How to extend XAxisRenderer

### ISSUE THREAD

**Issue by davidbin** [PhilJay/MPAndroidChart#752]
Hi, I'm trying to extend XAxisRenderer class, but I'm not sure how to force the chart to use the extended class.
The reason why I want to do it because I want to  override the renderAxisLabels method  to add a custom label below each XLabel for xAxis.

@Override
    public void renderAxisLabels(Canvas c) {
       .............
      drawLabels(c, mViewPortHandler.contentBottom() + mXAxis.mLabelHeight + yoffset * 1.5f);
      ..............
   }

Thanks for your help.

**Comment by PhilJay** [comment]
In the latest commit I provided a method called `setXAxisRenderer(...)` this is where you can set your custom renderer. 

You need to provide `chart.getViewPortHandler()` for the constructor of the renderer.

Don't forget to `invalidate()` the chart upon setting a new renderer.
