### ISSUE TITLE
IllegalArgument Exception occurs in chart.saveToPath().

### ISSUE THREAD

**Issue by ins112** [PhilJay/MPAndroidChart#753]
Hi, I'm studying your library to adjust my app. I test saveToPath() method, but it makes "java.lang.IllegalArgumentException: width and height must be > 0".

As I see vars of 'chart' by debugger, I think the problem lies on position vals are 0, such as  mLeft = 0 and mRight = 0.. but I can't understand why and how to handle it.

Library version is 2.1.0.

Here's my codes.

MainActivity.java

        setContentView(R.layout.activity_main);

        Random rand = new Random(System.currentTimeMillis());
        LineChart chart =(LineChart)findViewById(R.id.chart);  

        ArrayList<Entry> set1 = new ArrayList<>();  
        ArrayList<Entry> set2 = new ArrayList<>();
        ArrayList<Entry> set3 = new ArrayList<>();
        double[] i = new double[32];
        ArrayList<String> xVals = new ArrayList<>();  

        for (int j  = 0; j<32; j++){
            i[j] = Math.PI*2/32*j;

            set1.add(new Entry((float)Math.sin(i[j]), j));
            set2.add(new Entry((float)Math.cos(i[j]), j));
            set3.add(new Entry(rand.nextFloat()*2-1, j));
            xVals.add(j+".");

        } 

        LineDataSet setComp1 = new LineDataSet(set1, "SIG1"); 
        LineDataSet setComp2 = new LineDataSet(set2, "SIG2");
        LineDataSet setComp3 = new LineDataSet(set3, "SIG3");
        setComp1.setColor(Color.RED);
        setComp1.setDrawCircles(false);
        setComp1.setDrawValues(false); 
        setComp2.setColor(Color.BLUE);
        setComp2.setDrawCircles(false);
        setComp2.setDrawValues(false);
        setComp3.setColor(Color.GREEN);
        setComp3.setDrawCircles(false);
        setComp3.setDrawValues(false);

        ArrayList<LineDataSet> list = new ArrayList<>(); 
        list.add(setComp1);
        list.add(setComp2);
        list.add(setComp3);
        LineData ld = new LineData(xVals, list); 

        chart.getAxisLeft().setStartAtZero(false); 
        chart.getAxisRight().setStartAtZero(false);
        chart.setDescription(""); 
        chart.setData(ld); 

        chart.invalidate();
        chart.saveToPath("graph", Environment.getExternalStorageDirectory().toString());

activity_main.xml

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools" android:layout_width="match_parent"
        android:layout_height="match_parent" android:paddingLeft="@dimen/activity_horizontal_margin"
        android:paddingRight="@dimen/activity_horizontal_margin"
        android:paddingTop="@dimen/activity_vertical_margin"
        android:paddingBottom="@dimen/activity_vertical_margin" tools:context=".MainActivity">

        <com.github.mikephil.charting.charts.LineChart
            android:id="@+id/chart"
            android:layout_width="match_parent"
            android:layout_height="250dp" />

    </RelativeLayout>

**Comment by PhilJay** [comment]
Honestly I think that you cannot save the chart directly after first drawing it. I think the drawing routine is not finished yet and therefore causes the exception upon save.

You need to somehow delay the saving at  least a little bit.

**Comment by ins112** [comment]
Thank you for your advice! I add OnGlobalLayoutListener to chart and now it works.

**Comment by manu-alar** [comment]
@ins112 can you share the code pls?
