### ISSUE TITLE
with YAxisLabelPosition.INSIDE_CHART the setYOffset have no effect

### ISSUE THREAD

**Issue by maxbax** [PhilJay/MPAndroidChart#754]
Hi, I need to show a linear chart with the visible labels on Yaxis. I want to show labels top the axis line and not over so a I try to set the Yoffset (I see that the Xoffset property is ok), but it has no effect.
Could you suggest me something to resolve it?
Thanks 
Max

**Comment by maxbax** [comment]
I don't know if it's right, but in this moment I resolved replacing in YAxisRenderer the line:
float yoffset = Utils.calcTextHeight(mAxisLabelPaint, "A") / 2.5f;
with 
float yoffset = Utils.calcTextHeight(mAxisLabelPaint, "A") / 2.5f + mYAxis.getYOffset();
Could be the solution?

**Comment by PhilJay** [comment]
Yep, that is indeed correct, I just pushed the fix, thank you!
