### ISSUE TITLE
set all line of grid background are dashed line

### ISSUE THREAD

**Issue by wonghoman** [PhilJay/MPAndroidChart#755]
![qq 20150611110434](https://cloud.githubusercontent.com/assets/6296547/8099010/d3195c3c-1029-11e5-97d5-f41c4edba571.png)

my case like "A" at picture, how can i set it like "B" at picture? (all line of grid background are dashed line)

rightAxis.enableGridDashedLine(...)
leftAxis.enableGridDashedLine(...)
xAxis.enableGridDashedLine(...)

i had use this code, but it can't show me the dashed line of vertical direction, is there something forget to add?

**Comment by iChon** [comment]
How do you resolve this problem? I have same
