### ISSUE TITLE
How to make LineChart completely fill its space?

### ISSUE THREAD

**Issue by grahampople** [PhilJay/MPAndroidChart#760]
Thanks for writing this great library.  I'm trying to use it to create a tiny LineChart I can embed inside a table cell, with no labels, axes or gridlines - just the data line itself.  I've got this mostly working, the only issue left is, I want the data line to completely fill its space, but I can't get rid of some whitespace border from the edges.  I've tried fitScreen, setAxisMin/MaxValue and setBorderWidth, but no joy.  This is a bigger version:

![chart_borders](https://cloud.githubusercontent.com/assets/795437/8143723/ab64ba76-11e4-11e5-8fcf-44a20430ab24.png)

Any ideas?

**Comment by MGaetan89** [comment]
Maybe you can try with `YAxis.setSpaceTop(0f)` and `YAxis.setSpaceBottom(0f)`. But I'm not sure if it will work since you are not using axes.

For the horizontal spaces, I have no idea.

**Comment by grahampople** [comment]
Thanks for the suggestion, I gave it a try but no difference.  I have those disabled anyway:

mChart.getAxisLeft().setEnabled(false)
mChart.getAxisRight().setEnabled(false)

**Comment by grahampople** [comment]
In BarLineChartBase.java calculateOffsets, there is a line:

            float min = Utils.convertDpToPixel(10f);

I'm guessing that's probably the culprit.  On a tiny chart (I display this in around 70x30dp), that border space dominates the chart.

**Comment by PhilJay** [comment]
Try `chart.setViewPortOffsets(0,0,0,0)`

**Comment by grahampople** [comment]
Thanks, that works perfectly.

**Comment by markljones** [comment]
Is there a way to do this for only the left and right side? I don't want to disrupt the ability to display the axis labels below the graph.
