### ISSUE TITLE
DoubleTapToZoom zooms both axis even one is disabled to zoom

### ISSUE THREAD

**Issue by fmt-Println-MKO** [PhilJay/MPAndroidChart#762]
I would expect if i disable zoom for one axis, with  *setScaleYEnabled(false)* and double tap zoom is enabled *setDoubleTapToZoomEnabled(true)* that if you double tap, only the axis which is allowed to zoomed, is zoomed. Currently with double tap both axis are zoomed but you cant get back the that is disabled.

**Comment by PhilJay** [comment]
#740
