### ISSUE TITLE
LineChart description label soft background (feature suggestion?)

### ISSUE THREAD

**Issue by sideris** [PhilJay/MPAndroidChart#763]
Hello!

Thanks for the great library. I was working with LineChart and I added a description label on the chart. I noticed --given the number of lines (and with that colours) that exist in my chart-- that it was getting a tad difficult to read the label.

I was wondering if (in the spirit of general UI good principles of text readability) , we could add a background behind the label (e.g. black with alpha 0.7 and white text color). 

I would love to hear your feedback behind this idea.

Cheers

**Comment by PhilJay** [comment]
Thank you for the suggestion, but I am currently busy with other thinks and not going to implement something like this in near future!

Best regards,
Phil

**Comment by psyren89** [comment]
+1 to this. Labels on a pie chart are unreadable when the slices are dark enough.

**Comment by Savrov** [comment]
+1 good feature
