### ISSUE TITLE
How work with integers no float

### ISSUE THREAD

**Issue by golontico** [PhilJay/MPAndroidChart#764]
Ty for the lib it´s great!!!
I need how to set max like 100  and not average of the all in bars!
This like the video where BarChart inside ListView not use float just set the max and fill each bar with data.
thanks

**Comment by PhilJay** [comment]
You can set the maximum via `YAxis`. Concerning the integers, use the `ValueFormatter` to remove decimals.

**Comment by golontico** [comment]
thanks!
