### ISSUE TITLE
Graph viewport not changed after call to movieViewToX

### ISSUE THREAD

**Issue by gopi1410** [PhilJay/MPAndroidChart#765]
In my code I do a call to 
```java
    mChart.moveViewToX(data.getXValCount() - 11);
    mChart.invalidate();
```

I keep on adding data dynamically to the chart the above code is executed after each data addition.
Sometimes the chart does not change the viewport and after the next data, it changes.

I looked in the issue and I noted that if I call `invalidate()` once again after a second or so of adding the data then the chart moves. Upon further examining the issue, the found that the issue was due to not refreshing the chart upon completion of the `post()` job. In the *ViewPortHandler.java* class, if I change the `refresh(save, view, false);` to `refresh(save, view, true);`, then my chart renders as desired. Is there any reason why you aren't refreshing after changing the viewport?

**Comment by gopi1410** [comment]
P.S. I am drawing a line chart, with multiple fill colours (i.e. one fill colour for dataset values above a specified limit and another fill colour for values below the limit) by using multiple datasets. IMO it would be an interesting demo to be added in your demo app. Let if know if I should send a pull request for the same :)

**Comment by PhilJay** [comment]
Are you doing anything different than this: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/DynamicalAddingActivity.java ?

Because there it is working.

**Comment by gopi1410** [comment]
Yes its almost the same thing except that I am making the datasets with colour filled (so maybe slower rendering than the demo). Also in the demo (DynamicalAddingActivity.java), sometimes the viewport doesn't move to the next value on addition. I am testing it on samsung galaxy tab S, haven't checked on other devices.
I also wanted to know why isn't the view getting refreshed in the moveViewToX function. As far I could understand in the code, it's being executed in the View.post queue (the MoveViewJob class). So, if the next call to chart.invalidate() is called earlier than the callback of View.post job, then the chart will not be updated.

**Comment by PhilJay** [comment]
Hmmmm that's weird.
Is your chart in a regular activity? Or inside some fragment or custom view?

**Comment by gopi1410** [comment]
Yes, in a regular activity. Also when the viewport is not moving upon a particular data, if I touch/tap the screen before adding the next data, the viewport moves to the correct position, I guess this is because of invalidate being called on touch.

**Comment by PhilJay** [comment]
Yes, that could be an issue, I will look into it

**Comment by PhilJay** [comment]
Please have another go at it now, I just pushed the fix.

**Comment by gopi1410** [comment]
Great. Verified. Working smoothly.

**Comment by joshfriend** [comment]
:+1: fixed for me as well!

**Comment by ductranit** [comment]
@PhilJay This fix doesn't work for me.
 It only works on first time after I populate graph data. I call `chart.moveViewToX(data.size() - 1)` and the view port move to end (which is correct).
When I scroll to left, and call `chart.moveViewToX(data.size() - 1)` again, nothing happens (the graph data doesn't change)

**Comment by Firerazzer** [comment]
And what if the chart is inside some fragment or custom view ?

**Comment by i-schuetz** [comment]
It also stops working for me sometimes... I'm using the chart in a fragment.

**Comment by coolrukshan** [comment]
mChartTemp.moveViewTo(mChartTemp.getData().getEntryCount() - 11,32f, YAxis.AxisDependency.LEFT); 

This works fine for me

**Comment by Freshman111** [comment]
I found the reason why movieViewToX doesn't work is that computeScroll always call mChart.getViewPortHandler().refresh(); after movieViewToX().I changed the code by Override computeScroll method and movieViewToX worked again.

**Comment by NicolasKun** [comment]
> I found the reason why movieViewToX doesn't work is that computeScroll always call mChart.getViewPortHandler().refresh(); after movieViewToX().I changed the code by Override computeScroll method and movieViewToX worked again.

same problem :D
so i make isDragDecelerationEnabled = false 
this way temporary worked for me

**Comment by KostyaBakay** [comment]
I have the same issue when BarChart is an item of a ViewPager. In this case, moveViewToX() works only for the first item. Is any available solution for this problem?

**Comment by AlephC** [comment]
In my case, I'm trying to improve my code, I mean making it more robust.

**Comment by KostyaBakay** [comment]
> In my case, I'm trying to improve my code, I mean making it more robust.
Okay, so is it a known issue for the chart as an element of ViewPager?

**Comment by cychancw** [comment]
I faced similar problem in 3.1.0.
