### ISSUE TITLE
Issue with drawing a bar graph

### ISSUE THREAD

**Issue by mitesh-shah** [PhilJay/MPAndroidChart#766]
Hi,

I have 3 issues, please check the marking in the image attached.
1) Start the Y axis value from 10 not from 0. and it should be 10 not 10.00
2) Replace the top value of a bar with a dash line.
3) Move the dashed line to a bit right so that it will be exactly same as bar's width.

I am unable to find the code for this logic in your library. Please help me to sort this out.

Thank you, your small help will be much appreciated.
![paint](https://cloud.githubusercontent.com/assets/4998078/8158057/46f85e46-1377-11e5-96a8-8c253f88b9fd.jpg)

**Comment by PhilJay** [comment]
1) [Documentation of the YAxis](https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-%28YLabels%29)
2) [Formatting Values](https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface)
3) `enableGridDashedLine(....)` has three parameters, the third one defines the phase / offset which will allow to move the starting point of the "dash"

**Comment by mitesh-shah** [comment]
Hi,
Thank you for the reply.

I still have 2 problems which i am unable to find.
1) Y axis value should not start from zero.
--> I know the answer could be = leftAxis.setStartAtZero(false); but by using this bar doesn't even start. It just shows empty chart.

2) I am unable to find the code of bar values (Which are set above each bar). I have a arraylist of 10 values and i just want to display that on bars without any calculations. It need to write it in BarChartActivity.

3) I am working on a app which measures the sound frequency and display ups&downs on the bar, so i need to display continuous ups&downs to each bar is it possible? because in your code all bars animate simultaneously, but i want to animate each single bar based on values in every milliseconds.
