### ISSUE TITLE
clicking on a piece of pie chart makes one of the other pieces invisible

### ISSUE THREAD

**Issue by BlackGoblin** [PhilJay/MPAndroidChart#767]
Hi and thank you for your outstanding component that you've built.
I am having a hard time trying to make the pieces of pie chart not clickable.. because when a user clicks on one of the pieces one of the other pieces becomes invisible.. how could I make them unclickable.

**Comment by PhilJay** [comment]
Which version are you using?

**Comment by BlackGoblin** [comment]
I believe I am using version 2-0-9

**Comment by wakim** [comment]
@PhilJay there is any hint to resolve this problem? I'm using version 2.1.3 and it's happening to me.

My chart configurations are:

```java

PieChart chart = ...;

chart.setHoleColorTransparent(true);
chart.setRotationEnabled(allowInteraction);

chart.setDrawSliceText(false);
chart.setUsePercentValues(true);
chart.setTransparentCircleRadius(1f);

chart.setHoleRadius(60f);
```

And there are no relevant configurations to `PieDataSet` and to `PieData`.
