### ISSUE TITLE
Lines on LineChart disappearing unexpectedly

### ISSUE THREAD

**Issue by joshfriend** [PhilJay/MPAndroidChart#768]
In the screenshot below, the green line segment starts at 2015-03-02 (xindex=260), and ends at 2015-04-22 (xindex=311). The chart's `setVisibleXRangeMinimum` is 14 (2 weeks):

![example](http://i.imgur.com/8A91zqV.png)

If I scroll the X axis beyond April 21st to the right, the green line disappears

The vanishing point for the line is always when the vertical gridline immediately to the left of the endpoint of the line segment ("21 apr" in the screenshot) disappears offscreen to the right. Even when both the start and endpoints of the line are both shown on the visible chart area, the line segment connecting them disappears when the gridline moves offscreen.

So far, I've circumvented this by interpolating a data point for each X axis index between the start and end points of the segment, but that gets annoying.

I've noticed that similar behavior can be duplicated on the line chart example in the sample app by zooming in on one of the data points far enough.

Any ideas what might be going on?

**Comment by PhilJay** [comment]
Thank you for your input, this is related to  #718

I am working on it!

**Comment by joshfriend** [comment]
The fix for #718 pushed in 9a9c9ab does not change the behavior I've reported here.
