### ISSUE TITLE
Wrong values bars o X Axis in BarChart

### ISSUE THREAD

**Issue by diegoaraujolima** [PhilJay/MPAndroidChart#769]
Pardon my english (i'm brazillian). When i use horizontal bar chart with 2 or more datasets, the bars are in wrong places on X axis. My example is: Axis X = 12 months of year and axis Y = value sales. two datasets for each year to comparate the periods. When i use only one dataset, its work. My version is 2.1.0.

**Comment by PhilJay** [comment]
Can you post a screenshot?

**Comment by diegoaraujolima** [comment]
![1dataset](https://cloud.githubusercontent.com/assets/12902441/8172003/e9306a58-1392-11e5-94b4-fc81e791e4c7.png)
![2datasets](https://cloud.githubusercontent.com/assets/12902441/8172004/e9356d8c-1392-11e5-89b1-bb7ccad65221.png)
![pre_activity_1datasets](https://cloud.githubusercontent.com/assets/12902441/8172005/e93af0ea-1392-11e5-8496-7bbfe4a14021.png)
![pre_activity_2dataset](https://cloud.githubusercontent.com/assets/12902441/8172006/e9415ca0-1392-11e5-86f6-fd5b981d626b.png)


The pre-datasets images its to show how work the month selected.

**Comment by PhilJay** [comment]
Okay, could you provide the code where you setup the chart?

**Comment by diegoaraujolima** [comment]
Here is the setup chart  code:

GraficoFechamentoMesResposta sFechamentoMesResposta = new Gson().fromJson(fDadosGrafico, GraficoFechamentoMesResposta.class);
            if (sFechamentoMesResposta.getFechamentoMes() != null) {
                fchtGraficoBarras.setVisibility(View.VISIBLE);
                fchtGraficoBarras.setDrawBarShadow(false);
                //fchtGraficoBarras.setDrawValueAboveBar(false);
                fchtGraficoBarras.setDescription("");
                fchtGraficoBarras.setDrawGridBackground(false);
                fchtGraficoBarras.animateXY(3000, 3000);
                //fchtGraficoBarras.setPinchZoom(true);
                fchtGraficoBarras.setMarkerView(
                        new GraficosFechamentoMesMarkerView(getBaseContext(),
                                R.layout.activity_graficos_fechamento_mes_markview));

                XAxis sEixoX = fchtGraficoBarras.getXAxis();
                sEixoX.setLabelsToSkip(0);
                //sEixoX.setAdjustXLabels(false);
                sEixoX.setDrawLabels(true);
                sEixoX.setTextSize(5);

                List<String> sValoresX = Enumerados.ListarMeses(Enumerados.enumTipoMeses.Abreviado);
                ArrayList<BarEntry> sValoresY;
                BarDataSet sDataSet;
                BarEntry sBarEntry;
                int sContAgrupamento = 0;
                ArrayList<BarDataSet> sListaDataSet = new ArrayList<>();
                for(GraficoFechamentoMesResposta.FechamentoMesItem itemAgrupador : sFechamentoMesResposta.getFechamentoMes()){
                    sValoresY = new ArrayList<>();
                    for (GraficoFechamentoMesResposta.FechamentoMesItemValor itemMes : itemAgrupador.getMeses()){
                        sBarEntry = new BarEntry((float) itemMes.getValor(), itemMes.getMes() - 1, itemMes);
                        sValoresY.add(sBarEntry);
                    }
                    sDataSet = new BarDataSet(sValoresY,
                            (itemAgrupador.getCodigo().equals("0")) ? String.valueOf(itemAgrupador.getAno()) :
                                    itemAgrupador.getDescricao() + " - " + itemAgrupador.getAno());
                    //sDataSet.setBarSpacePercent(35f);
                    sDataSet.setColor(Grafico.PegarCorBasica(sContAgrupamento));
                    sDataSet.setDrawValues(false);

                    sListaDataSet.add(sDataSet);
                    sContAgrupamento++;
                }
                BarData sDadosBanco = new BarData((ArrayList)sValoresX, sListaDataSet);
                fchtGraficoBarras.setData(sDadosBanco);

**Comment by PhilJay** [comment]
Unfortunately I am not able to reproduce the issue, for me it works :-)

What could be the issue is that you are overwriting each dataset upon creation.
Are you using the latest version of the lib?

**Comment by diegoaraujolima** [comment]
Yes, i'm using e last version, 2.1.0. The problem can not be this, because i'm create a new instance for each iteration. Besides, whe the error ocurs, the 12 moths not be showed, only 9. See the screenshot.

**Comment by diegoaraujolima** [comment]
are is resolved?
