### ISSUE TITLE
Legend Wiki is outdated or 2 legend functionalities got lost in the newest version

### ISSUE THREAD

**Issue by Pexeed** [PhilJay/MPAndroidChart#770]
Hi,
I was trying to break the line of a legend, and the wiki says there are 2 methods that shoud help me do it.
But they are only on the wiki, the Legend class from the MPAndroidChart 2.1.0, doesn`t have these 2 methods.

setWordWrapEnabled(boolean enabled): If enabled, the content of the legend will not clip outside the setMaxSizePercent(float maxSize): Sets the maximum relative size out of the whole chart view in percent. Default: 0.95f (95%)

https://github.com/PhilJay/MPAndroidChart/wiki/Legend

**Comment by PhilJay** [comment]
Actually, the release is outdated, the wiki is not.
The methods you mentioned are not in a release version yet, thus, you cannot find them if you use a release version.
