### ISSUE TITLE
Bar chart with multiple data sets, but not grouped

### ISSUE THREAD

**Issue by cpfeiffer** [PhilJay/MPAndroidChart#774]
I would like to have multiple data sets in a bar chart, but I don't want them to be grouped.

My use case is displaying different kinds of activities from an activity tracker (sports activities and different sleep phases).
By definition these data sets do not overlap, so this is also related to #293, because the entries obviously all have different x values.
Alternatively I could also use just a single data set with all activities, but I couldn't figure out how to give them different colors, then.

I had a look at BarData.isGrouped(), but overriding this and returning false had not the desired effect.
If you could give me some pointers where to look, I'd try implementing this.

Thanks a lot for implementing and supporting this wonderful library!

**Comment by PhilJay** [comment]
Check out [how to set colors](https://github.com/PhilJay/MPAndroidChart/wiki/Setting-Colors), this will help you use just one `DataSet` and the colors you want.

**Comment by cpfeiffer** [comment]
Thanks for the pointer. This does indeed work. There's a drawback though: the legend. I would've expected it to show just a single item, because I have just a single data set. In reality it shows one item for every data entry, though.

I could set my own labels and colors via Legend.setLabels() and Legend.setColors(), however they are always overwritten by LegendRenderer.computeLegend().

What I've done now is to create a subclass of BarChart, setting a subclass of LegendRenderer which overrides computeLegend() such that it never calculates colors and labels.

Is that intended usage of the library or should that work somehow different? E.g. I could add a method setEnableLegendComputation() to avoid the subclassing.

**Comment by PhilJay** [comment]
No, that is not the intended use. These methods will be deprecated in the next release.

On the latest commit on the master branch, there is already a method called `setCustom(...)` which allows to set custom labels and colors for the legend.
This method however is not in any release yet (it will be in the next). So you will have to either clone the repo or wait until the next release (which will be soon).

**Comment by cpfeiffer** [comment]
Alright, I'll keep my version until the next release is out. Thanks again!
