### ISSUE TITLE
Max bubble size

### ISSUE THREAD

**Issue by fguf** [PhilJay/MPAndroidChart#775]
Hi,
thank you for the fix #773.

I have an other request, I would like to draw bubbles with a size higher than 1 x unit. (size fixed to 1 in BubbleChartRenderer: sizeBuffer[2] = 1f;).
So in my project i added a property maxBubbleSize in the BubbleDataSet class initialized to 1, and i changed sizeBuffer[2] = 1f to sizeBuffer[2] = dataSet.getBubbleMaxSize() in the drawHighlighted and drawDataSet methods. 
 I know it could run to overlay issue if not used the good way, but i need to draw some big bubbles in my project.

What do you think about this? Can you add this functionality to the lib?

Thanks.

**Comment by PhilJay** [comment]
If you need it, im just fine with you modifying the library to your needs. However, this is not how a BubbleChart is supposed to be and expected to look like.
So I will not add this. Thank you anyway!

**Comment by fguf** [comment]
I understand your point of view but i think i am not the only one who need this. For example the Javascript library highChart allow the bubble overlay (http://www.highcharts.com/demo/bubble).

Again, thank you for your amazing job!
