### ISSUE TITLE
Cannot find the setVisibleXRangeMaximum() or the setVisibleXRangeMinimum() Methods

### ISSUE THREAD

**Issue by srinivaskalyani** [PhilJay/MPAndroidChart#776]
Hi,

This is a fantastic library, saved me a lot of effort, so kudos to the developer(s). However, I am unable to call the aforementioned methods from a BarChart object. Am I doing something wrong here?

**Comment by PhilJay** [comment]
This is not in a release yet, you have to wait until it is released.

The methods can only be found in the latest commit of the master branch.

**Comment by srinivaskalyani** [comment]
Thanks a lot.
