### ISSUE TITLE
HighLigh in multiple dataSet chart

### ISSUE THREAD

**Issue by fguf** [PhilJay/MPAndroidChart#777]
Hi phil,
I think i found an issue in the highlighting process when the chart contains more than one dataSet.

In the getHighlightByTouchPoint method (BarLineChartBase class), we get the SelInfo List containing all the DataSets having an Entry close to the touched x value. Then, we get the touched dataSetIndex by calling Utils.getClosestDataSetIndex. 
The problem is that the SelInfo list given to this method contains all the dataSets, even if the mHihlightEnabled is set to false.
So, in some cases, the getHighlightByTouchPoint will return the index of a not Hightlightable dataSet, and it's a problem if an otherDataset with an Entry close to the touched point is hightlightable.

To fix this issue, i suggest to remove the not hightlightable datasets from the SelInfo List before calling the getClosestDataSetIndex method.

I hope i am clear enougth.

Thanks

**Comment by PhilJay** [comment]
Thanks!
