### ISSUE TITLE
Make chart data and/or datatsets serializable and/or parcelable

### ISSUE THREAD

**Issue by Pitel** [PhilJay/MPAndroidChart#778]
This will allow easy passing of data. Eg, when your chart has live updated data, and you rotate screen, and your activity is recreated, you will be able to easily do:
```java
@Override
public void onSaveInstanceState(final Bundle outState) {
	outState.putSerializable("chart", barChart.getData());
	//outState.putParcelable("chart", barChart.getData());
}
```
and then restore data in `onCreate`.

Parcelable will be preferred. It's difficult to implement, but should be faster to pass those data.

**Comment by sideris** [comment]
Yeah, but in a screen with live updated data would you need to destroy the activity everytime the screen is rotated?

To do that add `android:configChanges="orientation|screenSize">` in your activity tag in `AndroidManifest.xml`

**Comment by PhilJay** [comment]
You are welcome to make a PR for this, unfortunately I currently do not have the time to do this.

**Comment by jkwiecien** [comment]
Made a pull request for that https://github.com/PhilJay/MPAndroidChart/pull/2797

**Comment by stijnbrouwers** [comment]
Can this be reopened and the related PR #2797 checked? It seems to implement exactly what I need...
