### ISSUE TITLE
API for setting max and min zoom in chart

### ISSUE THREAD

**Issue by gopi1410** [PhilJay/MPAndroidChart#779]
Wouldn't it be better if you have APIs for setting min and max zoom, and a separate for max x values showing in the current viewport. Currently we have `setVisibleXRangeMaximum()` which limits the zoom cannot be zoomed out lesser than that value. But suppose if I want to show 10 values on my X axis (I'm speaking in context of line chart), and want that the user should be able to scale out and see a maximum of 30 values at a time. How would I achieve this using the current APIs?

**Comment by PhilJay** [comment]
You set the maximum visible range to 30, and use the zoom methods to zoom to 10 values.
