### ISSUE TITLE
Horizontal bar

### ISSUE THREAD

**Issue by VizantiecNET** [PhilJay/MPAndroidChart#78]
Thanks for your great chart library!

Can make the bars not only vertical but horizontal?

**Comment by simonwzb** [comment]
+1

**Comment by PhilJay** [comment]
Horizontal BarChart will be available in the next release.

**Comment by andregsilv** [comment]
This is really great!

**Comment by caxex** [comment]
great

**Comment by dvaldman** [comment]
Hello, at first, I would like to thank you for your awesome work ! 

I would like to ask if it is possible to set different colores for specific bars in one chart. 

Thank you in advance.
