### ISSUE TITLE
Change Bar values

### ISSUE THREAD

**Issue by mitesh-shah** [PhilJay/MPAndroidChart#780]
Hi,

First of all thank you for creating such wonderful library and answering to my last issue.

I have few more basic issue. Please help me on it soon. Please refer my screen shot
1) Y axis value should not start from zero.
--> I know the answer could be: leftAxis.setStartAtZero(false); but by using this bar doesn't even start. It just shows empty chart.

2) I am unable to find the code of bar values (Which are set above each bar). I have a arraylist of 10 values and i just want to display that on bars without any calculations. It need to write it in BarChartActivity.

3) I am working on a app which measures the sound frequency and display ups&downs on the bar, so i need to display continuous ups&downs to each bar is it possible? because in your code all bars animate simultaneously, but i want to animate each single bar based on values in every milliseconds.

![screenshot_2015-06-18-05-13-41](https://cloud.githubusercontent.com/assets/4998078/8230484/4a6e8406-15de-11e5-9a6d-a1bc467186fc.png)

**Comment by PhilJay** [comment]
Provide code
