### ISSUE TITLE
MarkerView out of the chart

### ISSUE THREAD

**Issue by fredydoss** [PhilJay/MPAndroidChart#781]
The markerView is going out the ChartView.
![screen shot 2015-06-18 at 14 19 55](https://cloud.githubusercontent.com/assets/2931755/8230959/352a7190-15c5-11e5-81b9-384469462d7b.png)

**Comment by PhilJay** [comment]
Well you can do the following to prevent that:
 - make your x-values array larger and by that give the chart more space on the left and right
 - implement some logic in the markerview that will shift it to the left/right depending on the selected x-index
