### ISSUE TITLE
get the point nearest in the center in LineChart

### ISSUE THREAD

**Issue by maxbax** [PhilJay/MPAndroidChart#783]
Hi, in this moment I'm using getLowestVisibleXIndex and getHighestVisibleXIndex to get the min and max visible xindex. This to select a point in the visible window. I'm showing only two or three x values and I want to identify the middle value, the point nearest in the center : how can I find it?
Thanks

**Comment by PhilJay** [comment]
(low + high) / 2 :-D

**Comment by maxbax** [comment]
It isn't the right solutions if you have only two or three xindex visible.
I solved it adding a new method. I put here if can help someone else:

public int getCenterVisibleXIndex() {
		float[] pts_left = new float[] { mViewPortHandler.contentLeft(),
				mViewPortHandler.contentBottom() };
		getTransformer(AxisDependency.LEFT).pixelsToValue(pts_left);
		float[] pts_right = new float[] { mViewPortHandler.contentRight(),
				mViewPortHandler.contentBottom() };
		getTransformer(AxisDependency.LEFT).pixelsToValue(pts_right);
		int pt_middle = Math.round(pts_left[0] + (pts_right[0] - pts_left[0]) / 2);
		if (pt_middle <= 0)
			pt_middle = 0;
		if (pt_middle >= mData.getXValCount())
			pt_middle = mData.getXValCount() - 1;
		return pt_middle;
	}

Max
