### ISSUE TITLE
Date on Xaxis

### ISSUE THREAD

**Issue by joshisunil-1983** [PhilJay/MPAndroidChart#784]
hi, i am using MPandroid chart in my app. i want to plot chart using values on y axis and date on x axis.  I don't find any datetime axis in mp android chart. is there any way to plot x axis using date. i want to set the interval also for datetime axis. like months,days,year according to my data.

guide.

**Comment by PhilJay** [comment]
Just name your x-axis labels according to the dates (days, months, years) you need.

**Comment by joshisunil-1983** [comment]
Can i pass date to x axis dataset. after after that i ll format the axis labels to accordingly.
