### ISSUE TITLE
The marker view could not display completely when moved to the rightmost.

### ISSUE THREAD

**Issue by mengfanpp** [PhilJay/MPAndroidChart#787]
The marker view could not display completely when moved to the rightmost. Please check the attached image.  Thanks

![line](https://cloud.githubusercontent.com/assets/1270807/8265475/642278a8-172d-11e5-9bf8-31b433e203fa.png)

**Comment by PhilJay** [comment]
What you can do:
- increase your x-axis range, making more space for the marker
- increase the charts left and right offset
- write some kind of logic in your marker that prevents this from happening
