### ISSUE TITLE
I don't need zoom, just need move to left or right to see more data,

### ISSUE THREAD

**Issue by mengfanpp** [PhilJay/MPAndroidChart#788]
I don't need zoom, just need move to left or right to see more data, like LineChart and Barchart, just need move, how to implement it? 

Also, is barchart support 3D?

Thanks,

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport

`moveViewToX(...)`

**Comment by mengfanpp** [comment]
Not moveViewToX(...). 
Because there are many data, I want to slide to view more data, but I need to double click the chart first, and then I can slide the chart, I don't want to double click it, I want to slide it directly. 

Thanks.
