### ISSUE TITLE
Date on X axis.

### ISSUE THREAD

**Issue by joshisunil-1983** [PhilJay/MPAndroidChart#789]
hi, i am using MPandroid chart in my app. i want to plot chart using values on y axis and date on x axis. I don't find any datetime axis in mp android chart. is there any way to plot x axis using date.  i have values against date. i want to show the dates in (ddMMM-yy) format on x axis and the values on y axis. anyone can pass me the sample link for the same.

sample for data:
Date(X axis)                          Value(Y axis)
01/01/2001                          966.78
01/02/2001                          666.78
01/03/2001                          966.78
01/04/2001                          966.78
01/05/2001                          966.78
01/06/2001                          966.78
01/07/2001                          966.78

guide.

**Comment by PhilJay** [comment]
Set this "01/01/2001"  and so on as an x-axis label, place your values to the correct x-indices

**Comment by silviul** [comment]
I have literally done this today. It's quite easy. Labels on the X Axis can be whatever strings. I converted a list of dates to my preferred format and set them as the X values like so: ```LineData lineData = new LineData(xValues);```. You then have to set values to corresponding indices, like @PhilJay said before.

**Comment by PhilJay** [comment]
@silviul Did you do that for Shazam? Or something else?

**Comment by silviul** [comment]
I'm just playing with the library. Not for Shazam.

**Comment by JiaminZhu** [comment]
I'm hoping for the exact function.  Not only what I want date as string, but I hope the date label can be dynamically according to zoom gestures.  For example, if I'm showing one year of data, I want the label as months but if I zoomed in and is only showing one month of data,  then the label could be days.  Is it possible to achieve this with overriding some methods?

**Comment by PhilJay** [comment]
Now possible:

https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/BarChartActivity.java

Example formatter: 

https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/custom/DayAxisValueFormatter.java

**Comment by Griffins** [comment]
That seems to working only for the barchart or am getting something wrong??

**Comment by JiaminZhu** [comment]
@Griffins The api just updated thoroughly and the documentation is out of date, as said [here](https://github.com/PhilJay/MPAndroidChart/releases/tag/v3.0.0-beta),  This confuses me for the whole morning.

But I kind of like the new way, treating X and Left and Right Axis all the same.  Just hope the new documentation will be out soon. @PhilJay

**Comment by oscarcuenca** [comment]
Hi.
I have a list in Array of 480 date and time each day (timestamp). I would like to fix this in X axi, How can do it automatically (not typing one by one) I get in ansyncronic process it, if "labels" are fixed OnCreate, means it is filled before I get data later on ansyncronic task... Any code exemple to help me...

**Comment by manmohan556** [comment]
How to give two space between two bars in stacked bar.And total count on top of bar .I am using
 .PhilJay:MPAndroidChart:v3.0.0-beta1'.Please help me

**Comment by Yasir-Ghunaim** [comment]
I had this exact issue. "DayAxisValueFormatter.java" helped me to come up with a similar implementation that uses timestamps instead. Final result looks like below screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/4573867/17865486/75214e42-68ab-11e6-8602-c94e1e65a7f1.png)

 
To use this method, make sure to do the following:

**xAxis:** 
- Populate with timestamps that increments from a reference timestamp.  
For example, rather than using this structure:
**x1** = 1471890054, **x2** = 1471890055, **x3** = 1471890056, etc. I store first timestamp (1471890054) in a global variable and define x axis as follow: **x1** = 0, **x2** = 1, **x3** = 2, etc. 
Later whenever I retrieve x values in my code, I add back the reference timestamp to x values. This method seems a bit faster than storing long timestamps. 

**xAxisValueFormatter**
- Apply this formatter: [HourAxisValueFormatter.java.txt](https://github.com/PhilJay/MPAndroidChart/files/430803/HourAxisValueFormatter.java.txt) to show hours and minutes (HH:mm) on x axis.

**MarkerView**
- Use [MyMarkerView.java.txt](https://github.com/PhilJay/MPAndroidChart/files/430802/MyMarkerView.java.txt) to show the whole date.

**Comment by gmkdev** [comment]
hi yasir can you gave me some example?

**Comment by LeslieJG** [comment]
Can you give an XML example of your MyMarkerView layout? I would like to know how you got the nice triangle at the bottom?

**Comment by Yasir-Ghunaim** [comment]
@gmkdev
Please refer to my last comment. I revised the whole comment and provided more explanations. 

@LeslieJG
I added more details about MyMarkerView layout in my last comment. See last two sentences. Best of luck.

**Comment by hammadtariqsahi** [comment]
@Yasir-Ghunaim  I am doing exactly same but i want to ask why x -axis values do not start from zero. means why your first value is away from origin ? can we force it to start from origin for first value ?

**Comment by sunilMyUniverse** [comment]
Hi phil,
I want to set dates to xAxis ,How can achieve this?

**Comment by sunilMyUniverse** [comment]
Hi phil,
I want to set dates to xAxis ,How can I achieve this?

**Comment by ashwinipawar1710** [comment]
i want to set dates to xaxis on the bar,how can i achieve this?

**Comment by LasseOnTheHub** [comment]
@ashwinipawar1710 
You can format the SimpleDateFormat as you wish in @Yasir-Ghunaim  ' s HourAxisValueFormatter like this where i show the date before the time.

`public HourAxisValueFormatter(long referenceTimestamp) {
        this.referenceTimestamp = referenceTimestamp;
        this.mDataFormat = new SimpleDateFormat("dd-HH:mm", Locale.ENGLISH);
        this.mDate = new Date();
    }`

![image](https://cloud.githubusercontent.com/assets/2629761/21903635/ea9d43e0-d900-11e6-8816-a6f30b45c9cc.png)
Dont mind the broken marker and generally poor design.

**Comment by janmarlon** [comment]
![barchart](https://cloud.githubusercontent.com/assets/25011726/21965229/973f7e96-db96-11e6-933d-8ea1740b7790.JPG)

@PhilJay look at may captured codes. I am new with mpandroidchart library, I am currently developing an application with bar graphs. I want to set my xVal as dates. but it seems BarData is not accepting a string parameter. hope you response ASAP. Thank you and God bless

**Comment by janmarlon** [comment]
@PhilJay  Is setting data in bar chart is different from linechart? I watched some tutorials and tried their codes, but it did not work with my project. I'm having an error with the parameter in BarData. when I removed the "labels" as parameter in BarData and left the "set" parameter, it properly works. and i tried it also with LineChart, LineData accepts 2 parameters. only in BarChart I am having a trouble. Please help me. Thanks!

**Comment by janmarlon** [comment]
@PhilJay please do notice me. ty

**Comment by garimawadhera** [comment]
http://stackoverflow.com/questions/41716677/getting-error-in-implementing-dayaxisvalueformatter-using-mpandroidchart
Please resolve this

**Comment by Malikkhoja** [comment]
@Yasir-Ghunaim  As per the reference given by you for the time support on X-Axis. I musing your solution exactly for Multiline chart. But the data on my XAxis is repetitive and not in the correct order. I am not sure why this is happenning. I have already asked the question with the details of the data that i m using to plot the graph. 
Please look at the issue :  #2775

It would be great if u can help me with the solution. Thanks

**Comment by ashish411** [comment]
@Yasir-Ghunaim in your demonstration when you converted dates to Timestamps how do you pass them in the Entry method which requires float value ?

**Comment by DivyaBansal** [comment]
@Yasir-Ghunaim Thank you for the wonderful solution. But the methods in the  MarkerView class in Phil's code has changed. How do I incorporate these changes in your code?

**Comment by Yasir-Ghunaim** [comment]
@DivyaBansal Could you point out which methods were changed as I am not keeping up with latest updates? 

Alternatively, refer to this version that I initially used:
> compile 'com.github.PhilJay:MPAndroidChart:v3.0.0-beta1'

and compare MarkerView methods in this version against latest version.

**Comment by ewertonluizmenezesrocha** [comment]
@Yasir-Ghunaim  
How do I create a label for when I touch 
the screen on one of the scales the values ​​of the x and y axis appear? As the one that appears a value 50% and the date in LineChart?

![75214e42-68ab-11e6-8602-c94e1e65a7f1](https://cloud.githubusercontent.com/assets/24612453/24882547/cf1d3f4c-1e17-11e7-9ec3-e4a966c8cd77.png)

**Comment by hiteshsahu** [comment]
**Marker arrow was not consistent so I did it in alternate approach** 

Example with Android Toast

<img width="214" alt="device-2017-05-19-153743" src="https://cloud.githubusercontent.com/assets/4076925/26243359/377b24a0-3ca9-11e7-80e9-2d0e85286433.png">

**Steps**

1.  Let  your parent activity containing chart implements `OnChartValueSelectedListener`

`public class APrioriResultActivity extends AppCompatActivity implements OnChartValueSelectedListener`

2.  Then assign your activity class to bar chart as `OnChartValueSelectedListener`

` barChart.setOnChartValueSelectedListener(this);`

3. and then implement `onValueSelected ` method to paint data  on screen in whichever way you like ie- Toast, Snack bar, dialog, TextView etc

   ```
   Toast mCurrentToast;

    @Override
    public void onValueSelected(Entry e, Highlight h) {

        if (mCurrentToast != null) {
            mCurrentToast.cancel();
        }

        mCurrentToast = Toast.makeText(this, "Support for" +
                        setEntries.get(Math.round(e.getX())) + " is " + e.getY(),
                Toast.LENGTH_LONG);
        mCurrentToast.show();
    }

     @Override
      public void onNothingSelected() {
 
      }
```

**Comment by abhishek-bharadwaj** [comment]
If anyone using `compile 'com.github.PhilJay:MPAndroidChart:v3.0.2'` I made couple of changes in @Yasir-Ghunaim 's solution AxisValueFormatter is not there anymore so use this

`HourAxisValueFormatter axisFormatter = new HourAxisValueFormatter(minTimeStamp);
        chart.getXAxis().setValueFormatter(axisFormatter);`

`package com.healthifyme.basic.diy_reports;

import com.github.mikephil.charting.components.AxisBase;
import com.github.mikephil.charting.formatter.IAxisValueFormatter;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

/**
 * Created by Abhishek on 08/06/17.
 */
public class HourAxisValueFormatter implements IAxisValueFormatter {

    private long referenceTimestamp; // minimum timestamp in your data set
    private DateFormat mDataFormat;
    private Date mDate;

    public HourAxisValueFormatter(long referenceTimestamp) {
        this.referenceTimestamp = referenceTimestamp;
        this.mDataFormat = new SimpleDateFormat("HH:mm", Locale.ENGLISH);
        this.mDate = new Date();
    }

    /**
     * Called when a value from an axis is to be formatted
     * before being drawn. For performance reasons, avoid excessive calculations
     * and memory allocations inside this method.
     */

    @Override
    public String getFormattedValue(float value, AxisBase axis) {
        // convertedTimestamp = originalTimestamp - referenceTimestamp
        long convertedTimestamp = (long) value;

        // Retrieve original timestamp
        long originalTimestamp = referenceTimestamp + convertedTimestamp;

        // Convert timestamp to hour:minute
        return getHour(originalTimestamp);
    }

    private String getHour(long timestamp) {
        try {
            mDate.setTime(timestamp * 1000);
            return mDataFormat.format(mDate);
        } catch (Exception ex) {
            return "xx";
        }
    }
}`

**Comment by adriamt** [comment]
I have an implementation like this, but the problem is that the labels are not equally spaced. For example I want labels like '11:00' , '11:30' , '12:00', '12:30' ,etc and I'm getting 10:59 , 11:31, 12:04, 12:29, etc.
Any clue how to achieve this @Yasir-Ghunaim ?
Here is a capture of what I'm talking.
![screenshot_20170704-172319_2](https://user-images.githubusercontent.com/11394100/27852764-b154b012-6160-11e7-8fc0-99545e8a81f6.png)

**Comment by Yasir-Ghunaim** [comment]
@adriamt I noticed this problem earlier but didn't know how to fix it. Based on several experiments, existing algorithm places labels at multiples of 100s, 1000s, 5000s which doesn't look nicely with seconds and minutes. I think one way would be to explore AxisBase and ComponentBase classes and see whether you can manipulate their algorithm so that labels are positioned at every an hour or at every multiple of 3600 (i.e. at 3600, 7200, etc). 

Once you achieve that, you might want to provide an offset to this labeling mechanism so that if your reference timestamp doesn't start at the exact beginning of an hour, you could simply shift the multiples of 3600 to match your data set structure.

**Comment by sonczyponcze** [comment]
Workaround for putting dates [String] on XAxis, maintaining proportional spacing:
- pass your x values to Entry object as (long) TimeInMilis
.....
Entry(calendar.getTimeinMilis(), y)
.......
- override getFormattedValue to build your Date from "value" and format it to whatever string you like
.......
public class DateAxisValueFormatter implements IAxisValueFormatter
{
    private String[] mValues;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy.MM.dd");

    public DateAxisValueFormatter(String[] values) {
        this.mValues = values; }

    //@Override
    public String getFormattedValue(float value, AxisBase axis) {
        return sdf.format(new Date((long)value)); }
}
......
- there is no need of passing any String[] to the value formatter
........
xAxis.setValueFormatter(new DateAxisValueFormatter(null));
..........
voile!!!

**Comment by crazypigs** [comment]
How would you go about putting on the x axis the day and inbetween days the time in hh:mm ??

**Comment by gxlinda** [comment]
Is it possible to write date on X axis in two lines? For example like this:
2017
12.10

**Comment by CG-Vivek** [comment]
@gxlinda 
save the date string using "  \n " between 2017 and 12.10

toFormatter.dateFormat = "hh:mm a \n dd/MM/yy"

**Comment by singlakaran** [comment]
is it possible to show the only month in xAxis?
and set (highlighter) label when a user clicks nearby points.

**Comment by CG-Vivek** [comment]
yes it is possible, you can provide xAxis data Array to be displayed.

**Comment by khalidelq** [comment]
<img width="677" alt="screen shot 2018-10-11 at 18 35 15" src="https://user-images.githubusercontent.com/20515647/46822841-78270380-cd84-11e8-8da5-71c64473ed08.png">
Can you help me, i have a probleme with date truncate, for exemple (06/09)
and that is my code:
public class CombinedChartAdria extends CombinedChart  {

    private CombinedChart mChart;
    private ArrayList<Entry> entriesLine;
    private ArrayList<BarEntry> entriesBar;
    private List<ChartModel> chartModels;
    private int positifColor, negatifColor;
    private int mRadius;

    public CombinedChartAdria(Context context) {
        super(context);
    }


    public CombinedChartAdria(Context context, AttributeSet attrs) {
        super(context, attrs);
        mRadius = attrs.getAttributeIntValue("http://schemas.android.com/apk/res-auto", "rounded", 0);
    }
    public void initChart(final List<ChartModel> chartModels) {
        this.chartModels = chartModels;
        entriesLine = new ArrayList<>();

        mChart = findViewById(R.id.chart);
        mChart.setHighlightFullBarEnabled(false);

        // draw bars behind lines

        YAxis rightAxis = mChart.getAxisRight();
        rightAxis.setPosition(YAxis.YAxisLabelPosition.OUTSIDE_CHART);
        rightAxis.setDrawLabels(false); // no axis labels
        rightAxis.setDrawAxisLine(false); // no axis line
        rightAxis.setDrawGridLines(false); // no grid lines
        rightAxis.setTypeface(Utils.getTypeFaceRegular(this.getContext()));
        rightAxis.setDrawZeroLine(true); // draw a zero line
        rightAxis.setGridLineWidth(0.5f);


        YAxis leftAxis = mChart.getAxisLeft();
        leftAxis.setDrawLabels(true); // no axis labels
        leftAxis.setDrawAxisLine(false); // no axis line
        leftAxis.setDrawGridLines(false); // no grid lines
        leftAxis.setTextSize(6f);
        leftAxis.setTextColor(getResources().getColor(R.color.txtMainColor));
        leftAxis.setTypeface(Utils.getTypeFaceRegular(this.getContext()));
        leftAxis.setDrawZeroLine(true); // draw a zero line
        leftAxis.setGridLineWidth(1f);


        XAxis xAxis = mChart.getXAxis();
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setDrawLabels(true); // no axis labels
        xAxis.setDrawAxisLine(false); // no axis line
        xAxis.setDrawGridLines(false); // no grid lines
        xAxis.setTextSize(6f);
        xAxis.setTextColor(getResources().getColor(R.color.txtMainColor));
        xAxis.setTypeface(Utils.getTypeFaceRegular(this.getContext()));
        xAxis.setGranularity(1f);
        xAxis.setLabelRotationAngle(-90);
        xAxis.setCenterAxisLabels(false);
        xAxis.setAxisMinimum(0);
        xAxis.setGranularityEnabled(false);
        xAxis.setValueFormatter(new IAxisValueFormatter() {
            @Override
            public String getFormattedValue(float value, AxisBase axis) {
                return  chartModels.get((int) value).getLabel();
            }

        });

        xAxis.setLabelCount(chartModels.size());
        CombinedData data = new CombinedData();
        data.setData(generateLineData());
        data.setData(generateBarData());
        xAxis.setAxisMinimum(data.getXMin() - 0.5f);
        xAxis.setAxisMaximum(data.getXMax() + 0.5f);
        //mChart.setViewPortOffsets(-10f, 0f, 0f, -10f);
        this.animateXY(1000, 1000);

        Paint paint = this.getRenderer().getPaintRender();
        int height = 200;
        LinearGradient linGrad = new LinearGradient(0, 0, 0, height,
                getResources().getColor(R.color.colorRedGradient),
                getResources().getColor(R.color.colorGradient2),
                Shader.TileMode.CLAMP);
        paint.setShader(linGrad);
        this.setData(data);
        this.invalidate();
    }
    private LineData generateLineData() {
        entriesLine = new ArrayList<>();
        positifColor = getResources().getColor(R.color.colorBgDark);
        negatifColor = getResources().getColor(R.color.graphBodyColor);
        for (ChartModel chartModel : chartModels)
            entriesLine.add(chartModel.getBarEntry());
        final ArrayList<Integer> listColor = new ArrayList<>();
        for (Entry entry : entriesLine) {
            listColor.add(entry.getY() < 0 ? negatifColor : positifColor);
        }
        LineDataSet dataset = new LineDataSet(entriesLine, "label");
        dataset.setDrawValues(false);
        dataset.setDrawFilled(false);
        dataset.setMode(LineDataSet.Mode.LINEAR); // Line type
        dataset.setColors(listColor);
        dataset.setCircleColor(positifColor);
        dataset.setCircleRadius(1.5f);
        dataset.setCircleColorHole(positifColor);
        //dataset.setDrawCircles(false);
        LineData data = new LineData(dataset);
        return data;
    }

    private BarData generateBarData() {
        entriesBar = new ArrayList<>();
        positifColor = getResources().getColor(R.color.colorGradient2);
        negatifColor = getResources().getColor(R.color.graphBodyColor);
        for (ChartModel chartModel : chartModels) {
            entriesBar.add(chartModel.getBarEntry());
        }
        final ArrayList<Integer> listColor = new ArrayList<>();
        for (BarEntry barEntry : entriesBar) {
            listColor.add(barEntry.getY() < 0 ? negatifColor : positifColor);
        }
        BarDataSet dataset = new BarDataSet(entriesBar, "label");
        dataset.setDrawValues(false);
        dataset.setColors(positifColor);

        BarData data = new BarData(dataset);
        data.setBarWidth(0.4f);
        this.setDescription(null);
        this.getLegend().setEnabled(false);
        this.setTouchEnabled(false);
        this.setScaleEnabled(false);
        this.animateXY(1000, 1000);

        Paint paint = this.getRenderer().getPaintRender();
        int height = 200;
        LinearGradient linGrad = new LinearGradient(0, 0, 0, height,
                getResources().getColor(R.color.colorRedGradient),
                getResources().getColor(R.color.colorGradient2),
                Shader.TileMode.CLAMP);
        paint.setShader(linGrad);
        this.invalidate();
        return data;
    }
}

**Comment by krishnamurthy12** [comment]
I am trying to draw dynamic line graph , where i will get temperature value from sensor , I need to draw time vs temperature graph . I have stuck in formatting x axis . 

This method giving me the solution upto some extent 
while inserting value i am using 

```
 Calendar c = Calendar.getInstance();
            SimpleDateFormat dateformat = new SimpleDateFormat("HHmm");
            String hoursMins= dateformat.format(c.getTime());

 setData(hoursmins,temperatureValue);
```

```
 xAxis.setValueFormatter(new IAxisValueFormatter() {

             private DecimalFormat mFormat= new DecimalFormat("#0.00");

            @Override
            public String getFormattedValue(float value, AxisBase axis) {
                value= (float) value/100;  //This is to splitup hours and minutes as it is combined 4 digit integer
                return mFormat.format(value);
}
```

But the issue i am facing here is , as i am using DecimalFormat , the X-axis is taking values from 0.1 to 0.9
But i wil get time only up to 0.60 (which means 60 minutes) from 0.60 to 0.90 nothing will be plotted and that wont look good as gap between the hours. I have tried many solutions but none of those gave me the solution i wanted. 
Anyone please help me out to solve this.

**Comment by DonGorias229** [comment]
it is possible to have 24 points on the abscissa?

**Comment by CG-Vivek** [comment]
Hi Arias
yes you can have multiple points on the abscissa.

**Comment by DonGorias229** [comment]
@CG-Vivek Ok thank you very much for your answer, I explain what I want to do but I do not know how to take to do that. I want to display the graphs by setting the hours of the day, but also in the last 7 days of the week and also the last 30 days

**Comment by DonGorias229** [comment]
@CG-Vivek basically the user of my graph will have the choice to see the evolution of graph during the day, but also of the week, and also the month always with the same data

**Comment by CG-Vivek** [comment]
@DonGorias229 yes you can do this using MPCharts, i don't find any complexity 
what you want from me?

**Comment by DonGorias229** [comment]
@CG-Vivek yes exactly I can do for a day but I do not know how to do it for the last 7 days and the last 30 days, can you help me?
find attached a catch for that of the day 
![WhatsApp Image 2019-04-22 at 08 50 14](https://user-images.githubusercontent.com/37826074/56487616-0c181b80-64dc-11e9-9d84-f81545ac7f1a.jpeg)

**Comment by CG-Vivek** [comment]
@DonGorias229 sure can help you, if it's about iOS development.

**Comment by DonGorias229** [comment]
I think that the formatting logic will be the same in Android as in iOS, explain me how to do in iOS that can help me in something

**Comment by CG-Vivek** [comment]
@DonGorias229 
If you have control over data and can filter day/week/month data
in iOS i just provide formatted data to xAixs
**LineChartView.xAxis.valueFormatter = IndexAxisValueFormatter(values:xaxisData)**

**Comment by DonGorias229** [comment]
@CG-Vivek Okay thank you so much

**Comment by CG-Vivek** [comment]
![1 Day](https://user-images.githubusercontent.com/35721393/56488442-fd416100-64fb-11e9-9b5e-39f416ea158e.png)
![7 day](https://user-images.githubusercontent.com/35721393/56488439-fca8ca80-64fb-11e9-8a07-11238dbc3b73.png)
![1 month](https://user-images.githubusercontent.com/35721393/56488440-fca8ca80-64fb-11e9-94f7-4c7977e16d99.png)

**Comment by CG-Vivek** [comment]
above are 1Day, 1 Week, 1 Month

**Comment by DonGorias229** [comment]
@CG-Vivek That's exactly what I want to do

**Comment by DonGorias229** [comment]
@CG-Vivek Is it possible for you to make available the part of the code that handles this part?

**Comment by CG-Vivek** [comment]
sorry, won't be able to share code snapshot.
you can identify chart for 1day, 1week, 1month and accordingly create an array of xaxisData with particular date formatter
for eg: 1Day (date formatter) : "hh:mm"
1week(date formatter): "dd/mm/yyy hh:mm"
1month(date formatter): "dd/mmm/yyyy"

**Comment by DonGorias229** [comment]
@CG-Vivek Thank you very much for the help

**Comment by miz33ar** [comment]
> **Note:** below solution was implemented using the following version:
> 
> > compile 'com.github.PhilJay:MPAndroidChart:v3.0.0-beta1'
> 
> This workaround is based on the implementation of "DayAxisValueFormatter.java" suggested previously by @PhilJay. Final result looks like this:
> 
> ![screenshot](https://cloud.githubusercontent.com/assets/4573867/17865486/75214e42-68ab-11e6-8602-c94e1e65a7f1.png)
> 
> # Steps:
> ## 1. Expressing x values in timestamps:
> Say, for example, we have this data set:
> 
> x	y
> 2016-01-01 15:00:00 GMT	25
> 2016-01-01 22:00:00 GMT	58
> 2016-01-02 08:00:00 GMT	36
> 2016-01-02 14:00:00 GMT	12
> 2016-01-02 19:00:00 GMT	29
> We would like to populate a MPAndroidChart LineChart instance with above date set but we can only do so using a float type in the form: Entry(float x, float y). One easy way to handle this obstacle is to convert all dates to timestamps to get this result:
> 
> x	y
> 1451660400	25
> 1451685600	58
> 1451721600	36
> 1451743200	12
> 1451761200	29
> Now, it seems like we should be good to go but one final adjustment is still required. When I tried these huge x values, my chart became really slow especially when zooming in and out.
> 
> ## 2. Converting timestamps to small numbers:
> As a solution to this, we can further manipulate these x values by using this conversion:
> 
> ### `Xnew = Xold - reference_timestamp`
> * Xnew: timestamp after conversion
> * Xold: original timestamp
> * reference_timestamp: first timestamp in our sorted data set in ascending order.
> 
> First timestamp in a sorted data set should be the minimum timestamp which can be perfectly used as a zero reference. In that case, if we apply this equation to our sorted data set such as:
> 
> #### `reference_timestamp = 1451660400`
> we get this new data set:
> 
> x	y
> 0	25
> 25200	58
> 61200	36
> 82800	12
> 100800	29
> > We can even reduce these numbers by converting from seconds timestamps to minutes timestamps if that is really needed.
> 
> Make sure to keep reference_timestamp stored in a global variable so that you can retrieve your original timestamp when needed.
> 
> ## 3. Applying ValueFormatter to show x labels of hours and minutes:
> At this moment, your chart should be working smoothly but your x axis will show labels that has no meaning to your user. Let's add some meaning to our x axis by using this value formatter which provides a nice label to our dataset in hours and minutes (HH:mm):
> [HourAxisValueFormatter.java](https://github.com/PhilJay/MPAndroidChart/files/455552/HourAxisValueFormatter.java.txt)
> 
> You can apply it in this way:
> 
> ```
> AxisValueFormatter xAxisFormatter = new HourAxisValueFormatter(referenceTimestamp);
> XAxis xAxis = mChart.getXAxis();
> xAxis.setValueFormatter(xAxisFormatter);
> ```
> ## 4. Set a MarkerView to show a popup containing the full date and time when a value is highlighted:
> More details about MarkerView can be found here [wiki](https://github.com/PhilJay/MPAndroidChart/wiki/MarkerView).
> 
> Use [MyMarkerView.java](https://github.com/PhilJay/MPAndroidChart/files/455567/MyMarkerView.java.txt) to show full date and time when a value is pressed. Implementation is easy just call setMakerView() like this:
> 
> ```
> MyMarkerView myMarkerView= new MyMarkerView(getApplicationContext(), R.layout.my_marker_view_layout, referenceTimestamp);
> mChart.setMarkerView(myMarkerView);
> ```
> **R.layout.my_marker_view_layout** is found here: [custom_marker_view.xml](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/res/layout/custom_marker_view.xml)
> and **@drawable/marker2** is found here: [marker2.png](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/res/drawable-nodpi/marker2.png)

how do i converts date to timestamps??

**Comment by DonGorias229** [comment]
@miz33ar Hi, thank you very much for your approach, please you can give us access to the complete source code of this part?

**Comment by miz33ar** [comment]
@DonGorias229  here is my code ` protected void onCreate(Bundle savedInstanceState) {
     super.onCreate(savedInstanceState);
     setContentView(R.layout.activity_main);
     temperature = new ArrayList<>();
     temps = new ArrayList<>();
     humidité = new ArrayList<>();
     entries = new ArrayList<Entry>();
     final LineChart chart = findViewById(R.id.chart);
     PerformNetworkRequestD request = new PerformNetworkRequestD(Api.url, new PerformNetworkRequestD.AsyncResponse() {
         @Override
         public void processFinish(JSONArray output) {
             if (output != null) {
                 for (int i = 0; i < output.length(); i++) {
                     try {
                         int t = output.getJSONObject(i).getInt("nbTemp");
                         String d = output.getJSONObject(i).getString("le_temps");
                         int h = output.getJSONObject(i).getInt("humidite");
                         temperature.add(t);
                         humidité.add(h);
                        
                         Date date = formatter.parse(d);

                         temps.add(date);


                     } catch (JSONException e) {
                         e.printStackTrace();
                     } catch (ParseException e) {
                         e.printStackTrace();
                     }
                 }
                 //write your code here
                    for(int i=0;i<temperature.size();i++){

                        entries.add(new Entry(temps.get(i),temperature.get(i)));

                    }
                    LineDataSet dataSet = new LineDataSet(entries, "temperature");
                    LineData lineData = new LineData(dataSet);
                    chart.setData(lineData);
                    chart.invalidate();`

**Comment by DonGorias229** [comment]
@miz33ar thank you very much, may I have your email address?

**Comment by miz33ar** [comment]
> @miz33ar Hi, thank you very much for your approach, please you can give us access to the complete source code of this part?



> @miz33ar Hi, thank you very much for your approach, please you can give us access to the complete source code of this part?

i added my code can you pls check -- above

**Comment by DonGorias229** [comment]
@miz33ar Yes, I did, but I have a particular concern that I would like to discuss with you privately

**Comment by miz33ar** [comment]
Can you show me how put my list of dates on x axis pls ?? and what you want to discuss im all yours .

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Don Arias <notifications@github.com>
Envoyé : Monday, April 29, 2019 3:24:01 PM
À : PhilJay/MPAndroidChart
Cc : miz33ar; Mention
Objet : Re: [PhilJay/MPAndroidChart] Date on X axis. (#789)


@miz33ar<https://github.com/miz33ar> Yes, I did, but I have a particular concern that I would like to discuss with you privately

**Comment by miz33ar** [comment]
> @miz33ar thank you very much, may I have your email address?

zaeriaanas@outlook.fr

**Comment by DonGorias229** [comment]
> > @ miz33ar merci beaucoup, puis-je avoir votre adresse e-mail?
> 
> [zaeriaanas@outlook.fr](mailto:zaeriaanas@outlook.fr)

thank you very much, I would leave a message by mail

**Comment by miz33ar** [comment]
> > > @ miz33ar merci beaucoup, puis-je avoir votre adresse e-mail?
> > 
> > 
> > [zaeriaanas@outlook.fr](mailto:zaeriaanas@outlook.fr)
> 
> thank you very much, I would leave a message by mail

Hi,im still waiting for your message ,i realy need your help @DonGorias229 ..

**Comment by RumsPatel** [comment]
> 
> 
> Now possible:
> 
> https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/BarChartActivity.java
> 
> Example formatter:
> 
> https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/custom/DayAxisValueFormatter.java

both link broken.

**Comment by sidcgithub** [comment]
### The following are tips to format date for candlestick graphs
**1) Use IAxisValueFormatter**
`IAxisValueFormatter theFormatYouWant= new TheFormatYouWant();`

**2)  Create a formatter by implementing IAxisValueFormatter**
```
public class TheFormatYouWant implements IAxisValueFormatter {
    @Override
    public String getFormattedValue(float value, AxisBase axis) {


        Date date = new Date((long)value);
        //Specify the format you'd like
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd", Locale.ENGLISH);
        return sdf.format(date);

    }
}
```
**3) Set Format to XAxis**
After
`yValsCandleStick.add(timestamp, float1,   float2,   foat3,  float4);`

Set the format for the timestamps
```

 XAxis xAxis = candleStickChart.getXAxis();
 xAxis.setValueFormatter(TheFormatYouWant);
```
The above works with the following dependencies
```
    implementation 'com.github.PhilJay:MPAndroidChart-Realm:v3.0.3@aar'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.0.3'
```

**Comment by JonesiL** [comment]
Hey!

I got a similar problem to this. I have data in Firestore database and I am trying to show it a line chart. I want HH:mm on m y xAxis and temperature values on yAxis. I have the 3.1.0 version and I am trying to work with HourAxisValueFormatter. I have converted the x values from date objects and then I turned them according @Yasir-Ghunaim instructions, but I only get the first time "08:00" to my xAxis and I can't figure out how to get them all. I have the <xnew values in a Long type arraylist.

I also tried this in fdew other ways and managed to get xAxis correctly but then I could not get my entries correctly -> could not put my values to the correct x-indexes.

Can someone help me?

**Comment by Proxcentaur** [comment]
@JonesiL could u tell me how to convert the x values from the date object?

**Comment by KonstantinDementiev** [comment]
Maybe this is useful to someone.
To round timestamps on the x-axis do the following in ValueFormatter:
`long dateInMillis = (long) Math.round ((value * 60000) / 300000) * 300000;`
value -  Unix time in milliseconds.
This will round the marks up to 5 minutes and remove the uneven marks:
before: 5.01, 6.01, 6.58... after: 5.00, 6.00, 7.00...

**Comment by trav3711** [comment]
I'm so confused by this. I have a DB containing SQLite timestamps and integer values. All I want to do is create one bar for each timestamp/value entry. Therefore I just want one bar per entry, and I don't know why I have to mess around with all of this Value Formatter stuff.

**Comment by JerryThl** [comment]
My problem happened on Candlestick chart whereby the bar will disappear when using IndexAxisValueFormatter method.

The simplest way is to divide the timestamp by 10k or 100k, ONLY THEN pass into IndexAxisValueFormatter
Within IndexAxisValueFormatter, multiply the received timestamp by 10k or 100k depending which amount you divide previously.

Problem Solved.
