### ISSUE TITLE
How add a custom view in Pie chart center?

### ISSUE THREAD

**Issue by liuxun349** [PhilJay/MPAndroidChart#79]
i wanna add a custom view in pie chart center.ex: add a button in pie chart center.when i click the button,i can change some date.

How do it? Thx.

**Comment by sagarAndroidDev** [comment]
Dear mikereman&liuxun349, the relative layout's child view of button(or any other view/layout included) has to be placed below the pie chart view literally in the code in order to render it over the pie chart center.
Hope it helps!
-S.S
