### ISSUE TITLE
MPAndroidChart mMonths not support Utf-8

### ISSUE THREAD

**Issue by nemati456** [PhilJay/MPAndroidChart#791]
hi
 in ِdemobase when i change mMonth  for example Sep to "قمری"

in app shows me ***** and not show "قمری"

what should i do sry for my Poor English

**Comment by PhilJay** [comment]
it's a demo

**Comment by nemati456** [comment]
i konow but i want copy some code to my project and i think m Month noth support utf-8 what should i do thanks for your answering

**Comment by danielgindi** [comment]
You should set a font that supports Arabic characters. The font the Phil set in the demo is a special font, not the default font, and it includes only Latin characters

**Comment by nemati456** [comment]
default  font is in library or..?

**Comment by danielgindi** [comment]
Can't you just look at the code and find out?..
>
>
