### ISSUE TITLE
YAxis values out of layout!

### ISSUE THREAD

**Issue by arash-jahani** [PhilJay/MPAndroidChart#792]
hi everybody!

YAxis values in myChart out Of box,but why?how solving?

![device-2015-06-23-102622](https://cloud.githubusercontent.com/assets/2876900/8299872/8927eb8e-1993-11e5-909d-2a9d7c15e0ba.png)

Thanks.

**Comment by danielgindi** [comment]
Is this Persian?

**Comment by danielgindi** [comment]
Does your language have characters significantly wider than the others?

**Comment by arash-jahani** [comment]
yes this is persian, no it does not.

**Comment by danielgindi** [comment]
How many characters are being cut?

**Comment by arash-jahani** [comment]
just first character

**Comment by danielgindi** [comment]
It looks to me like it measures the "longest labels" for the wrong label.
It counts the characters, but if you have a very narrow characters, or a
character the modifies another character for punctuations or something
similar, it may deduce the wrong longest label. We may need to change
behaviour to actually measure all the labels...
