### ISSUE TITLE
Get data from sqlite

### ISSUE THREAD

**Issue by danzhu10** [PhilJay/MPAndroidChart#796]
hey phil, i'm using your library, its very good. i'm having problem to fetch my database and display it to Barchart, it just show 1 row with 3 barchart.
this is my code:

       try{
            Cursor cursor = dbHelper.fetchChartStatistic("1");      
            cursor.moveToFirst();
            int count = cursor.getCount();
            String[] soal_salah = new String[count];
            String[] total_nilai = new String[count];       
            if(cursor!=null){
                do{
            for(int x=0; x<count; x++) {
                total_nilai[x] = cursor.getString(4);
                soal_salah[x] = cursor.getString(2);
            }
            }while(cursor.moveToNext());
            }
            ArrayList<BarEntry> yVals1 = new ArrayList<BarEntry>();
            for (int i = 0; i < total_nilai.length; i++) {
                yVals1.add(new BarEntry((float) Float.parseFloat(soal_salah[i]),i));
            }

            ArrayList<String> xVals = new ArrayList<String>();
            for (int i = 0; i < total_nilai.length; i++)
                xVals.add(total_nilai[i%total_nilai.length]);

            BarDataSet set1 = new BarDataSet(yVals1, "Data Set");
            set1.setColors(ColorTemplate.VORDIPLOM_COLORS);
            set1.setDrawValues(false);
            BarData data = new BarData(xVals, set1);
            mChart.setData(data); 
        }catch(Exception c){
            c.printStackTrace();
            }
        }
the barchart show this

![barchart](https://cloud.githubusercontent.com/assets/10788806/8323745/ae0dbb56-1a72-11e5-99f8-9f9dbdf506f8.PNG)

**Comment by PhilJay** [comment]
I honestly have no idea sinc I cannot know what kind of data is in your cursor and what chart you would expect. If it's not displaying as you expect, I suppose it might be related to `soal_salah[i]`

**Comment by danzhu10** [comment]
this is my data

![capture](https://cloud.githubusercontent.com/assets/10788806/8325360/2ea49d42-1a83-11e5-943a-d44c3e1e97a5.PNG)
.
i want to display column of soal_salah in xVals, and column of total_nilai in yVals, but i get just 1 row from both column

**Comment by PhilJay** [comment]
IN the code above, you are displaying `soal_salah` as the y-value

**Comment by krupal22** [comment]
I Don't Know How To Dislay Data From Data Base. Can You Help ME?
