### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by MGaetan89** [PhilJay/MPAndroidChart#799]
There were quite some changes/fixes since the last version (2.1.0): https://github.com/PhilJay/MPAndroidChart/compare/v2.1.0...master

Is a new version planned any time soon?

**Comment by PhilJay** [comment]
Im currently working on negative bar-stacks & the related highlighting issues. I guess after that is finished there is gonna be a new release (since I'm very busy right now, it's gonna be in approximately 2 weeks)

**Comment by MGaetan89** [comment]
Ok, thanks for your answer :smile:

**Comment by danielgindi** [comment]
@PhilJay highlights are fixed in the PR. I think we are ready... :-)

**Comment by PhilJay** [comment]
Yep, I'll probably look over the other code this weekend and then do the release, thanks for the PR :-)

**Comment by MGaetan89** [comment]
Any news on this yet?
