### ISSUE TITLE
Support single Entry for LineChart

### ISSUE THREAD

**Issue by 120660021** [PhilJay/MPAndroidChart#80]
Hello, I was in China android developer, your library is especially strong, very much, which encountered some problems, hope to get your help。
  I used LineChart time, I modified your demo in LineChartActivity classes, 117 lines setData (45, 100); modified setData (1, 100) ;, is only one data, line graph interface is empty, there is no way to make him appear ， My mail is 120660021@qq.com，I hope to hear from you，Thank you！

**Comment by ITDeveloper123** [comment]
Hello, I am an Indian developer. Recently tried out this library. It is wonderful but I am facing an issue. Could you please help. I have a xaxis with custom labels and putting entries into it using 
Xvalues are = [17th March, 18th March, 19th March,20th March,21st March,22nd March,23rd March];

but it is displaying only 23rd march across xaxis and with 55.0f value if I am giving only one entry as

ArrayList<Entry> yVals = new ArrayList<Entry>();
        yVals.add(new Entry(5.0f, 55.0f));
 
I searched a lot. But couldn't be able to solve it. If I am giving 

  yVals.add(new Entry(1.0f, 10.0f));
  yVals.add(new Entry(5.0f, 55.0f));

it is working fine displaying all labels.
