### ISSUE TITLE
Line connecting two points disappears when one of them is off-screen

### ISSUE THREAD

**Issue by goshki** [PhilJay/MPAndroidChart#801]
On the attached screenshots, you can see that the white line connecting to white points disappears when the chart is zoomed in a little bit and the left point gets off-screen.

It's worth mentioning that there are a 100 or so NULL entries between these two points (it's a chart that shows 356 days and not every day has a value).

<img src="https://cloud.githubusercontent.com/assets/146900/8326739/6840d680-1a63-11e5-9e99-4a0efc5f166e.jpeg" height="192" alt="Chart zoomed out, all lines visible"> <img src="https://cloud.githubusercontent.com/assets/146900/8326738/683a3ece-1a63-11e5-9f4f-6d7f500839e9.jpeg" height="192" alt="Chart zoomed in, white line disappeared">

**Comment by olivierg13** [comment]
I got the same behaviour and would be interested in a fix :)

**Comment by StoyanD** [comment]
so what you do is override the BarLineScatterCandleDataProvider interface to tell the renderer to graph for points off the ViewPortHandeler. You can do this by extending the LineChart. What you are doing in the background is drawing for more points than can be seen, so be careful to not dump a huge amount of points into a dataset.

```java
public class ProgressLineChartView extends LineChart {
    public ProgressLineChartView(Context context) {
        super(context);
    }

    public ProgressLineChartView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public ProgressLineChartView(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
    }

    @Override
    public int getLowestVisibleXIndex() {
        return 0;
    }

    @Override
    public int getHighestVisibleXIndex() {
        return (this.mData).getXValCount() - 1;
    }
}
```

**Comment by StoyanD** [comment]
![screenshot_2015-07-06-16-51-05](https://cloud.githubusercontent.com/assets/746098/8602205/dfae9f86-2625-11e5-9bad-1620def20a33.png)

**Comment by StoyanD** [comment]
![screen shot 2015-07-09 at 10 32 34 am](https://cloud.githubusercontent.com/assets/746098/8602215/edcd8d5c-2625-11e5-89a6-0126c3aaf1f6.png)

**Comment by PhilJay** [comment]
The fix in general is good and will exactly result in the behavior you want. But please keep in mind that this will (can) have a negative impact on performance since values that are outside of the view (when the chart is zoomed in) are still rendered using this approach even though they are not visible.

However this should not be an issue for up to ~300-500 values in the linechart, depending on your device.
