### ISSUE TITLE
OutOfMemory in the new version 2.1.0

### ISSUE THREAD

**Issue by ciceromsjr** [PhilJay/MPAndroidChart#802]
In the new version of this library, I have an OutOfMemory error when I rotate my device.
The device's model is Galaxy S4 and I am using LineChart to show statistics data.
If I rotate it about twice I have a crash error.

I did not have this error in preview version (2.0.9).

The error log follow below:

java.lang.OutOfMemoryError: Failed to allocate a 4688652 byte allocation with 3116164 free bytes and 2MB until OOM
1	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
2	at android.graphics.Bitmap.nativeCreate(Native Method)
3	at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
4	at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
5	at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
6	at com.github.mikephil.charting.charts.Chart.onSizeChanged(Chart.java:1457)
7	at android.view.View.sizeChange(View.java:16819)
8	at android.view.View.setFrame(View.java:16792)
9	at android.view.View.layout(View.java:16707)
10	at android.view.ViewGroup.layout(ViewGroup.java:5328)
11	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
12	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
13	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
14	at android.view.View.layout(View.java:16711)
15	at android.view.ViewGroup.layout(ViewGroup.java:5328)
16	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
17	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
18	at android.view.View.layout(View.java:16711)
19	at android.view.ViewGroup.layout(ViewGroup.java:5328)
20	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
21	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
22	at android.view.View.layout(View.java:16711)
23	at android.view.ViewGroup.layout(ViewGroup.java:5328)
24	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
25	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
26	at android.view.View.layout(View.java:16711)
27	at android.view.ViewGroup.layout(ViewGroup.java:5328)
28	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
29	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
30	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
31	at android.view.View.layout(View.java:16711)
32	at android.view.ViewGroup.layout(ViewGroup.java:5328)
33	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
34	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
35	at android.widget.ScrollView.onLayout(ScrollView.java:2288)
36	at android.view.View.layout(View.java:16711)
37	at android.view.ViewGroup.layout(ViewGroup.java:5328)
38	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
39	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
40	at android.view.View.layout(View.java:16711)
41	at android.view.ViewGroup.layout(ViewGroup.java:5328)
42	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
43	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
44	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
45	at android.view.View.layout(View.java:16711)
46	at android.view.ViewGroup.layout(ViewGroup.java:5328)
47	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
48	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
49	at android.view.View.layout(View.java:16711)
50	at android.view.ViewGroup.layout(ViewGroup.java:5328)
51	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1594)
52	at android.view.View.layout(View.java:16711)
53	at android.view.ViewGroup.layout(ViewGroup.java:5328)
54	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
55	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
56	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
57	at android.view.View.layout(View.java:16711)
58	at android.view.ViewGroup.layout(ViewGroup.java:5328)
59	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
60	at android.view.View.layout(View.java:16711)
61	at android.view.ViewGroup.layout(ViewGroup.java:5328)
62	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
63	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
64	at android.view.View.layout(View.java:16711)
65	at android.view.ViewGroup.layout(ViewGroup.java:5328)
66	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
67	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
68	at android.view.View.layout(View.java:16711)
69	at android.view.ViewGroup.layout(ViewGroup.java:5328)
70	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
71	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
72	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
73	at android.view.View.layout(View.java:16711)
74	at android.view.ViewGroup.layout(ViewGroup.java:5328)
75	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:890)
76	at android.view.View.layout(View.java:16711)
77	at android.view.ViewGroup.layout(ViewGroup.java:5328)
78	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
79	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
80	at android.view.View.layout(View.java:16711)
81	at android.view.ViewGroup.layout(ViewGroup.java:5328)
82	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
83	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
84	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
85	at android.view.View.layout(View.java:16711)
86	at android.view.ViewGroup.layout(ViewGroup.java:5328)
87	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
88	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
89	at android.view.View.layout(View.java:16711)
90	at android.view.ViewGroup.layout(ViewGroup.java:5328)
91	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
92	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
93	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
94	at android.view.View.layout(View.java:16711)
95	at android.view.ViewGroup.layout(ViewGroup.java:5328)
96	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
97	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
98	at android.view.View.layout(View.java:16711)
99	at android.view.ViewGroup.layout(ViewGroup.java:5328)
100	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2319)
101	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2032)
102	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
103	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
104	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
105	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
106	at android.view.Choreographer.doFrame(Choreographer.java:560)
107	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
108	at android.os.Handler.handleCallback(Handler.java:739)
109	at android.os.Handler.dispatchMessage(Handler.java:95)
110	at android.os.Looper.loop(Looper.java:145)
111	at android.app.ActivityThread.main(ActivityThread.java:5942)
112	at java.lang.reflect.Method.invoke(Native Method)
113	at java.lang.reflect.Method.invoke(Method.java:372)
114	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
115	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by ciceromsjr** [comment]
It is ocurring in both versions

**Comment by jaredsburrows** [comment]
@ciceromsjr Which versions? Why did you close this?
