### ISSUE TITLE
Rounded bar chart with customize background

### ISSUE THREAD

**Issue by sbron** [PhilJay/MPAndroidChart#803]
I would like add rounded corners on bar chart and add a customized background. In Android, I know I can create rounded corner for rectangle on a drawable but this library doesn't support "barchart.setBackground(R.drawable.my_custom_back);"
It is possible to add this function? Or, may be, is there an another solution?

**Comment by PhilJay** [comment]
http://stackoverflow.com/questions/11947603/setbackground-vs-setbackgrounddrawable-android

**Comment by sbron** [comment]
Sorry, it's my fault. I would like create rouded BAR!

**Comment by alliecurry** [comment]
@sbron Here's what I did accomplish what you're looking for...

1. Make custom render Class that extends BarChartRenderer
2. Override method drawDataSet
3. Change occurrences of "drawRect" to "drawRoundedRect"
4. Set the renderer to your bar chart...  
```` barChart.setRenderer(new MyRenderer(barChart, barChart.getAnimator(), barChart.getViewPortHandler()));````

You can also add any other customizations for drawing the bars in that method. Good luck!

**Comment by marcochin** [comment]
@alliecurry Ty it works! There so much to account for though. 

Like If you round the rect, it rounds all 4 corners. If I want to round just the top 2 corners, a solution might be to draw a regular square rect on bottom half and have it overlap the rounded rect.

Then you have to account for the highlight color which is a completely separate bar that is overlayed on top the regular bar. That also needs to be rounded. The highlight color has some transparency to it so if you draw a square rect on bottom of the rounded highlight bar, the bottom part will be visibly darker than the top half. 

I'll just stick with the square bar, imo it looks a lot more cleaner anyways.

**Comment by mjurkus** [comment]
@alliecurry I'm using method you described. But for some reason I get only top corners rounded.
Is there a reason for that?

```KOTLIN
 fun drawRoundRect(canvas: Canvas, left: Float, top: Float, right: Float, bottom: Float) {
    val rad = (right - left) / 2
    canvas.drawRoundRect(left, top, right, bottom, rad, rad, mRenderPaint)
}
```

**Comment by iRuth** [comment]
@alliecurry, thanks for the tip. I got it to work [here](https://github.com/WW-Digital/MPAndroidChart/commit/f940a527418aa0b695cd4f7fdf8b07922317cb17).

**Comment by sridharsaminathan** [comment]
i need to add round corner to radar chat in Xamarin. pls help

**Comment by AdityaAnand1** [comment]
Is there a 2018 in-library solution for this?

**Comment by idofle** [comment]
There is a simple solution using custom shapes:

`
import { BarChart, Bar, XAxis, YAxis, Rectangle } from 'recharts';

export default class SingleBarChart extends React.Component
{
    RoundedRectangle( props )
    {
        return <Rectangle {...props} radius = { 60 } >
        </Rectangle>;
    }

    render()
    {
        const { value } = this.props;

        const data = [
            {name : 'score', value}
         ];

        return <BarChart width = { 350 } height = { 200 } data = { data }  >
            <Bar dataKey = "value" fill = "#8884d8"  shape = { this.RoundedRectangle()} />
      </BarChart>;
    }
}

You just need to define your own shape and pass it to the `Bar` component. In the case of 4 corners rounded rectangle, we can use Rechart's Rectangle.

**Comment by AdityaAnand1** [comment]
^

* Wrong language
* Wrong library

...

**Comment by titiarimba** [comment]
@AdityaAnand1 have you solve this issues and make a success to build a rounded bar charts?

**Comment by Dansanchez** [comment]
> @alliecurry I'm using method you described. But for some reason I get only top corners rounded.
> Is there a reason for that?
> 
> ```kotlin
>  fun drawRoundRect(canvas: Canvas, left: Float, top: Float, right: Float, bottom: Float) {
>     val rad = (right - left) / 2
>     canvas.drawRoundRect(left, top, right, bottom, rad, rad, mRenderPaint)
> }
> ```

I am also getting only top corners to be round and I need also bottom corners to be round. Any one has accomplished having all 4 corners round in the barchart?

**Comment by tabish075** [comment]
Hey everyone I've implemented this with stackedHorizontal BarChart but only highlights are rounded can someone help me with this

Here what it looks like:
![screenshot_20181226-143155](https://user-images.githubusercontent.com/32475249/50441644-85807280-091d-11e9-9bf1-9ff1da339e8f.png)


And this is how i want it:
![chart](https://user-images.githubusercontent.com/32475249/50441255-b2338a80-091b-11e9-96b8-ded38c7615d7.PNG)

**Comment by Hashan1599** [comment]
> Hey everyone I'm trying to achieve this:
> ![chart](https://user-images.githubusercontent.com/32475249/50441255-b2338a80-091b-11e9-96b8-ded38c7615d7.PNG)
> 
> And this is what i've done so far:
> ![screenshot_20181226-153130](https://user-images.githubusercontent.com/32475249/50443082-83b9ad80-0923-11e9-9096-3965ad4e9d05.png)
> 
> Now i need to overlap first value bar to the next one and so on how can i do this please help

i'm running with same issue. have you got a solution

**Comment by Hashan1599** [comment]
@tabish075 i'm also running on same issue. have you got a solution

**Comment by tabish075** [comment]
@Hashan1599 Not with this library.. no

**Comment by Hashan1599** [comment]
@tabish075 how can i get rid of this issue. what library should i want to tryout

**Comment by tabish075** [comment]
I'll make a gist and share soon !

**Comment by ionalexandru1401** [comment]
> @sbron Here's what I did to accomplish what you're looking for...
> 
> 1. Make custom render Class that extends BarChartRenderer
> 2. Override method drawDataSet (easiest approach is to copy over drawDataSet  method code from BarChartRenderer.java)
> 3. Change occurrences of "drawRect" to "drawRoundedRect"
> 4. Set the renderer to your bar chart...
>    `barChart.setRenderer(new MyRenderer(barChart, barChart.getAnimator(), barChart.getViewPortHandler()));`
> 
> You can also add any other customizations for drawing the bars in that method. Good luck!

Hello!
Sorry, but how would you guys proceed if we have the Bars inside a CombinedChart ? I am not able to find a solution to this...

**Comment by timtsj** [comment]
@tabish075 @Hashan1599 hi, have you solved this issue? if yes, can you share please

**Comment by Priyanshi-Z** [comment]
@anmol-max any update on it? I am also trying to achieve the same

**Comment by gs666** [comment]
welcome to view this post
https://juejin.cn/post/7100863388850503693

**Comment by aneebarshad** [comment]
Rectangle box with rounded corner that worked for me.
```
  private void drawRectWithRoundedCorner(Canvas canvas, float x, float y) {
        float left = x - 50;
        float top = y - 50;
        RectF myRectum = new RectF(left, top, left + 100, top + 100);
        canvas.drawRoundRect(myRectum,15,15, dayPaint); // rectangle with radius
    }
```
