### ISSUE TITLE
Import and run example project?

### ISSUE THREAD

**Issue by baggednismo** [PhilJay/MPAndroidChart#804]
I have tried just about everything I can think of here in eclipse and without a .project file in the example I dont think it is going to work. Could you please explain to me how to Import and run your example project as an android project in eclipse? I have the source downloaded as well the git repository cloned with EGit but unable to run them.

**Comment by danielgindi** [comment]
Why bot just move to Android Studio? Eclipse is not designed for Android.

**Comment by baggednismo** [comment]
Well I guess I could but I have a feeling its not going to solve the problem. If I'm not mistaken Android Studio is eclipse for the most part. I use eclipse for PHP and standard Java development already so if I can limit the IDE's that would be prefered.

**Comment by danielgindi** [comment]
Well actually no. Android Studio is not eclipse even in a small percentage.
It's an Android IDE. There are so many aspects of Android that eclipse is
not aware of. And it was generally just hell to work with eclipse to build
for Android and that's the reason Google closed a deal with JetBrains to
create Android Studio.

With Android Studio it will just compile it. Try and you'll see.

**Comment by baggednismo** [comment]
I wasn't aware. It may have been a few years since I last used it but from what I remember they looked almost identical. I will give it a shot, eclipse has been throwing random errors at me lately. Spent more time fixing ghost problems that just appear out of nowhere than developing...

**Comment by baggednismo** [comment]
Well after installing Android Studio and getting my own projects moved over I once again tried the example project and still running into problems. ended up creating settings.gradle to include MPChartLib but im affraid the include is incorrect as im now getting "cannot evaluate module". seems im not meant to open this example...
