### ISSUE TITLE
LineChart not showing in fragment!

### ISSUE THREAD

**Issue by kimnamcham** [PhilJay/MPAndroidChart#805]
In htc one v - android ver 4.0.4, i add linechart in fragment, line chart not showing and yaxis, xaxis has been inverted. In other device with android ver higher, everything it's ok. I just tested the mpchartandroid example in this device, it run normaly. 
Here is xml code:
<?xml version="1.0" encoding="utf-8"?>
< LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    android:orientation="vertical">
    < include layout="@layout/layout_header_bao_cao"></ include>
    < com.github.mikephil.charting.charts.LineChart
        android:id="@+id/lineChartBieuDo"
        android:layout_width="match_parent"
        android:layout_height="match_parent"></ com.github.mikephil.charting.charts.LineChart>
</ LinearLayout>
![screenshot_2015-06-25-11-03-10](https://cloud.githubusercontent.com/assets/6441065/8346686/a3c231a0-1b2a-11e5-82c4-91762f98a7a2.png)

Line chart in lg g2, android ver 4.4.2, it's okay.

![screenshot_2015-06-25-11-08-22](https://cloud.githubusercontent.com/assets/6441065/8346698/cdbc52a6-1b2a-11e5-9f6a-8f29a6f7dd44.png)

**Comment by danielgindi** [comment]
LOL

**Comment by kimnamcham** [comment]
@danielgindi : why did you laugh?

**Comment by kimnamcham** [comment]
Almost all chart don't show, only piechart work,

**Comment by danielgindi** [comment]
Because it's funny to see the "magic" of Android every time with a
different aspect.

In other words: If something would not draw- I'd accept it as software vs.
hardware issues. But the axis drawing inverted? Without any more
information I can only deduce that your ROM is faulty, implementing the
native matrix functions in a wrong way, or having the Zero matrix
initialized to an inverted matrix or something similar.

Every vendor is doing whatever he likes. And sometimes it's not even the
vendor's fault- it could be the user installing some custom ROM.

**Comment by kimnamcham** [comment]
Seems to be like you did'nt reading my problems careful. I tested the example mpchart and it's running normaly. I think custom rom is not main problem.

**Comment by danielgindi** [comment]
Well you're claiming that the SAME code, works on one Android but behaves
abnormally on another. Did I not understand you?

**Comment by kimnamcham** [comment]
Because you said the problems is custom rom. And i don't agree with your thinking.

**Comment by danielgindi** [comment]
Well nobody is forcing you to agree, I just offered my understanding of it.
If something works on one device and not on the other, it means in most
cases that there's a critical difference. In my experience it's a result of
custom roms. I've had trouble with Asus roms for example, modifying the way
long-press works, and HTC roms modifying the way that Gyroscope sensor data
is translated in the API. They could easily modify something else, and the
user could easily install a completely custom ROM.

You should test on more devices.

**Comment by kimnamcham** [comment]
Thanks for your advice :). I haved tested on 6 device (smartphone and tablet), only in htc device has problem. So you can explain why chart not showing? Thanks. 
Here is my code when add data to chart:

private void loadDataChart() {
        lineChart.setDrawGridBackground(false);
        lineChart.setDescription("");
        lineChart.setNoDataTextDescription("");

        lineChart.setHighlightEnabled(true);
        lineChart.setTouchEnabled(true);
        lineChart.setDragEnabled(true);
        lineChart.setScaleEnabled(true);

        MyMarkerView myMarkerView = new MyMarkerView(getActivity().getApplicationContext(), R.layout.custom_marker_view);
        lineChart.setMarkerView(myMarkerView);

        lineChart.setHighlightIndicatorEnabled(false);

        YAxis leftAxis = lineChart.getAxisLeft();
        leftAxis.removeAllLimitLines();
        leftAxis.setAxisMaxValue(300f); // gia tri tung do max
        leftAxis.setAxisMinValue(0); // gia tri tung do min
        leftAxis.setStartAtZero(true);
        leftAxis.enableGridDashedLine(10f, 10f, 0f);
        leftAxis.setTextSize(20f);

        leftAxis.setDrawLimitLinesBehindData(true);
        lineChart.getAxisRight().setEnabled(false);
        lineChart.getXAxis().setPosition(XAxis.XAxisPosition.BOTTOM);
        lineChart.getXAxis().setTextSize(20f);

        Legend legend = lineChart.getLegend();
        legend.setForm(Legend.LegendForm.LINE);
        legend.setTextSize(20f);

        setData();
    }

    private void setData() {
        ArrayList<String> xVals = new ArrayList<String>();
        xVals.add("Tháng 1");
        xVals.add("Tháng 2");
        xVals.add("Tháng 3");
        xVals.add("Tháng 4");

        ArrayList<Entry> yVals = new ArrayList<Entry>();
        yVals.add(new Entry(150f, 0));
        yVals.add(new Entry(200f, 1));
        yVals.add(new Entry(50f, 2));

        LineDataSet set1 = new LineDataSet(yVals, "Chi nhánh 1");
        set1.enableDashedLine(10f, 10f, 10f);
        set1.setColor(Color.BLUE);
        set1.setCircleColor(Color.BLACK);
        set1.setLineWidth(1f);
        set1.setCircleSize(3f);
        set1.setDrawCircleHole(false);
        set1.setValueTextSize(20f);
        set1.setFillAlpha(65);
        set1.setFillColor(Color.BLUE);
        set1.setDrawFilled(true);

        ArrayList<LineDataSet> dataSets = new ArrayList<LineDataSet>();
        dataSets.add(set1);

        LineData lineData = new LineData(xVals, dataSets);
        lineChart.setData(lineData);
        lineChart.invalidate();
    }

**Comment by danielgindi** [comment]
If so, then the problem is clearly in your HTC. I found myself writing a
lot of code to specifically handle HTC roms.
Anyway, I would try to initialize a Matrix on HTC and on another device,
and compare their values.
Because a transformation matrix controls where we draw our axis labels, and
convert our chart points to pixels etc. - it is reasonable to think that
something is wrong with the matrix mechanism. (It's basically the stuff in
ViewPort/Transformer)

**Comment by kimnamcham** [comment]
Waiting for your response soon, thanks again :)

**Comment by vinoth12594** [comment]
Same problem
