### ISSUE TITLE
update bar chart in fragment

### ISSUE THREAD

**Issue by meddd** [PhilJay/MPAndroidChart#808]
I have main activity with 3 fragments. in all of them a have chart.
In main activity I have pickerDate, and when i chose date, I send them (as bundle) to fragments.
Problem is, that i cant refresh chart in fragment, when new data is selected.
but I can see chart, when fragment is loading at first time, I can see updated chart when change orientation orwhen I Pressed screen (method onChartLongPressed). is it something wrong with my code, or it is bug?

import java.util.Random;
        import android.graphics.Typeface;
        import android.os.Bundle;
        import android.support.v4.app.Fragment;

        import android.util.Log;
        import android.view.LayoutInflater;
        import android.view.MotionEvent;
        import android.view.View;
        import android.view.ViewGroup;

import android.widget.Toast;

import com.github.mikephil.charting.charts.BarChart;
        import com.github.mikephil.charting.components.Legend;
        import com.github.mikephil.charting.components.XAxis;
        import com.github.mikephil.charting.components.YAxis;
        import com.github.mikephil.charting.listener.OnChartGestureListener;

import com.github.mikephil.charting.data.BarData;
import com.github.mikephil.charting.data.BarDataSet;
import com.github.mikephil.charting.data.BarEntry;
import com.github.mikephil.charting.data.ChartData;
import com.github.mikephil.charting.data.Entry;
import com.github.mikephil.charting.data.LineData;
import com.github.mikephil.charting.data.LineDataSet;
import com.github.mikephil.charting.data.PieData;
import com.github.mikephil.charting.data.PieDataSet;
import com.github.mikephil.charting.data.ScatterData;
import com.github.mikephil.charting.data.ScatterDataSet;
import com.github.mikephil.charting.utils.ColorTemplate;
import com.github.mikephil.charting.utils.FileUtils;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import android.app.Activity;
import android.os.Handler;

public class BarChartFrag extends Fragment implements OnChartGestureListener {

    public  BarChartFrag () {    }

    private Bundle bundle;
    private static final String TAG = "DemoActivity";
    private BarChart mChart;
    private Typeface tf;
    private static Locale mLocale = Locale.getDefault();
    String mStartDate;
    String mEndDate;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
           bundle=savedInstanceState;

    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.fragment_graph, container, false);

        mChart = (BarChart) v.findViewById(R.id.gragh_layout);
        Log.i(TAG, "onCreateView ");
        mChart.setDescription("");
        mChart.setOnChartGestureListener(this);
        MyMarkerView mv = new MyMarkerView(getActivity(), R.layout.custom_marker_view);
        mChart.setMarkerView(mv);
        mChart.setHighlightEnabled(false);
        mChart.setDrawGridBackground(false);
        mChart.setDrawBarShadow(false);

        return v;
    }
    private void initGraph(){
        SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd HH:mm",mLocale);
        Bundle args = getArguments();
        if(args==null){
            Calendar calstart = Calendar.getInstance();
            calstart.add(Calendar.MONTH, -1);//odjecie miasiaca
            Calendar calend = Calendar.getInstance();
            mStartDate=date_format.format(calstart.getTime());
            mEndDate=date_format.format(calend.getTime());
        }
        else
        {
            if (!args.containsKey("mStartYear") && !args.containsKey("mEndYear")) {
                Toast.makeText(getActivity(), "arguments is null ", Toast.LENGTH_LONG).show();
                Calendar calstart = Calendar.getInstance();
                calstart.add(Calendar.MONTH, -1);//odjecie miasiaca
                Calendar calend = Calendar.getInstance();
                mStartDate=date_format.format(calstart.getTime());
                mEndDate=date_format.format(calend.getTime());
            }
//startdate
            else if(args.containsKey("mStartYear") && args.containsKey("mEndYear")) {
                Calendar calstart = Calendar.getInstance();
                calstart.set(Calendar.YEAR, Integer.parseInt(args.getString("mStartYear")));
                calstart.set(Calendar.MONTH, Integer.parseInt(args.getString("mStartMonth")));
                calstart.set(Calendar.DAY_OF_MONTH, Integer.parseInt(args.getString("mStartDay")));
                calstart.set(Calendar.HOUR_OF_DAY, 00);
                calstart.set(Calendar.MINUTE, 00);
                Date startDate = calstart.getTime();
                mStartDate = date_format.format(startDate);

                Calendar calend = Calendar.getInstance();
                calend.set(Calendar.YEAR, Integer.parseInt(args.getString("mEndYear")));
                calend.set(Calendar.MONTH, Integer.parseInt(args.getString("mEndMonth")));
                calend.set(Calendar.DAY_OF_MONTH, Integer.parseInt(args.getString("mEndDay")));
                calend.set(Calendar.HOUR_OF_DAY, 23);
                calend.set(Calendar.MINUTE, 59);
                Date endDate = calend.getTime();
                mEndDate = date_format.format(endDate);
            }
            if(args.containsKey("mEndYear")) {
                Log.i(TAG, "mStartYear " + mStartDate + mEndDate);
            }

        }

        // create a new chart object

        Typeface tf = Typeface.createFromAsset(getActivity().getAssets(), "OpenSans-Light.ttf");

        //mChart.setData(generateBarData(1, 20000, 12));
        Random rand = new Random();
        int value = rand.nextInt(6);
        //mChart.clear();
        mChart.setData(generateBarData(1, 20, value));
        Log.i(TAG, "generateBarData " + value);

        Legend l = mChart.getLegend();
        l.setTypeface(tf);

        YAxis leftAxis = mChart.getAxisLeft();
        leftAxis.setTypeface(tf);

        mChart.getAxisRight().setEnabled(false);

        XAxis xAxis = mChart.getXAxis();
        xAxis.setEnabled(false);

        mChart.notifyDataSetChanged();
        mChart.invalidate();

    }

    @Override
    public void onResume() {
        super.onResume();

        //initGraph();
        updateChart();
        //mTimerHandler.postDelayed(updateTimerThread, 10);
        Log.i(TAG, "onResume");
    }

    public void updateChart(){
        this.getActivity().runOnUiThread(new Runnable() {
           @Override
            public void run() {
                initGraph();
                Log.i(TAG, "updateChart"+mEndDate);
            }
        });
    }

    @Override
    public void onChartLongPressed(MotionEvent me) {
        initGraph(); Log.i("LongPress", "Chart longpressed.");
    }

    @Override
    public void onChartDoubleTapped(MotionEvent me) {
        initGraph();Log.i("DoubleTap", "Chart double-tapped.");
    }

    @Override
    public void onChartSingleTapped(MotionEvent me) {
        initGraph();Log.i("SingleTap", "Chart single-tapped.");
    }

    @Override
    public void onChartFling(MotionEvent me1, MotionEvent me2, float velocityX, float velocityY) {
        Log.i("Fling", "Chart flinged. VeloX: " + velocityX + ", VeloY: " + velocityY);
    }

    @Override
    public void onChartScale(MotionEvent me, float scaleX, float scaleY) {
        Log.i("Scale / Zoom", "ScaleX: " + scaleX + ", ScaleY: " + scaleY);
    }

    @Override
    public void onChartTranslate(MotionEvent me, float dX, float dY) {
        Log.i("Translate / Move", "dX: " + dX + ", dY: " + dY);
    }

    protected BarData generateBarData(int dataSets, float range, int count) {

        ArrayList<BarDataSet> sets = new ArrayList<BarDataSet>();

        for(int i = 0; i < dataSets; i++) {

            ArrayList<BarEntry> entries = new ArrayList<BarEntry>();

            for(int j = 0; j < count; j++) {
                entries.add(new BarEntry((float) (Math.random() * range) + range / 4, j));
            }

            BarDataSet ds = new BarDataSet(entries, getLabel(i));
            ds.setColors(ColorTemplate.VORDIPLOM_COLORS);
            sets.add(ds);
        }

        BarData d = new BarData(ChartData.generateXVals(0, count), sets);
        d.setValueTypeface(tf);
        return d;
    }
    private String[] mLabels = new String[] { "Company A", "Company B", "Company C", "Company D", "Company E", "Company F" };

    private String getLabel(int i) {
        return mLabels[i];
    }

}

**Comment by PhilJay** [comment]
I have no idea, your explaination is far from clear...

**Comment by meddd** [comment]
In method onresume there is updatechart which should recreate chart when new data from main activity will be recived. But this does not happen. Event if i put initgraph() in onresume te efect is the same and the chart is not recreate. 
But using this code when i change orientation of screen or pressed screen (i put initGraph() in onChartLongPressed ) the new chart is recreated. So initGrafh() is good but i dont know why new chart is not created when onresume() start to work when new data arrived.

**Comment by TR4Android** [comment]
@meddd OnResume() only gets called when the fragment has been paused and is resumed again. This is why it works when changing the orientation: this pauses the fragment and resumes it again in the new orientation. It does not get called automatically when new data is received.
The Android Developers page has a section on [Communication of Fragments](http://developer.android.com/training/basics/fragments/communicating.html#Deliver). Please refer to this to correctly update your fragment.
