### ISSUE TITLE
Line cart - Markers are shown when clicking anywhere along the y-Axis point on that x coordinate

### ISSUE THREAD

**Issue by udayan9803** [PhilJay/MPAndroidChart#809]
Thanks for the wonderful library, been enjoying working with it. 
I am trying to draw a time series using the LineChart. The chart looks awesome with the various formatting option that come alone, a BIG thanks for that. 

I have a question, on the chat when selecting an Entry by clicking on the circles, looks like currently alone the entire Y-XAIS points on the screen i can select that circle(data point). 
Is it possible to restrict the selection on specific x and y point where the circle is drawn.

thanks...

**Comment by udayan9803** [comment]
Any help will be appreciated.

**Comment by PhilJay** [comment]
One approach could be that you use a separate `DataSet` that has circles enabled and that is only displayed if something is selected.

**Comment by udayan9803** [comment]
Hi Phil, not sure if I am following you, Can you please kindly explain it little bit.
thank you in advance.
