### ISSUE TITLE
Change background lineChart

### ISSUE THREAD

**Issue by fatemeh2sh** [PhilJay/MPAndroidChart#81]
Hi
how do i change background of this photo
![graph](https://cloud.githubusercontent.com/assets/8721987/4237887/3809dce4-39d3-11e4-8138-ca9a316bd55c.jpg)

 Can i help me?

Regards fatemeh

**Comment by saiidabs** [comment]
@PhilJay  in your new version of chart libary, your colored line chart cant all the other stuff u could do in previous versions, how do i work around this?
