### ISSUE TITLE
while ploting with dual y axis chart points mess in left of the chart.

### ISSUE THREAD

**Issue by joshisunil-1983** [PhilJay/MPAndroidChart#811]
i am plotting with line data chart. after adding  y axis on right plotted data points not spread.
https://www.dropbox.com/s/wubkrxlel6vv3cf/WP_20150626_004.jpg?dl=0
https://www.dropbox.com/s/d843gir3g4i19b3/WP_20150626_003.jpg?dl=0

**Comment by joshisunil-1983** [comment]
@PhilJay Owner please help on the topic.

**Comment by PhilJay** [comment]
**The data points are exactly where they should be.** The only thing that has changed is the range of values that is displayed on each axis.
--> this range is now significationly lower because only one set of data is represented by each axis, before, one axis had to scale large enough to display both datasets.

I suggest you read the [documentation of the YAxis](https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-%28YLabels%29) and simply increase the range of values that should be displayed on the axis.

**Comment by joshisunil-1983** [comment]
@PhilJay  as you can see in my code given below that i am providing custom range for the each axis. This range provided on the behalf of actual data. so whenever chart data get changed i am providing the new range according to data. but chart data point not spreading over the x axis. why all of them appearing only in left of the chart. even scale also not start from the given min value. in above given image i am providing the min value 1240 and the max value 1440 to right axis and i want the interval of the data should be 40 but axis value not starting from the given value.can see in 2nd image
    mChart = (LineChart) findViewById(R.id.Chart);
    mChart.setGridBackgroundColor(Color.parseColor("#F4F4F4"));
    mChart.setDrawGridBackground(false);
    mChart.setTouchEnabled(true);
    mChart.setHighlightEnabled(false);
    mChart.setDragEnabled(false);
    mChart.setScaleEnabled(true);
    mChart.setPinchZoom(true);
    mChart.setDescription("");
    mChart.getAxisLeft().setAxisMaxValue(YMaxValue);
    mChart.getAxisLeft().setAxisMinValue(YMinValue);
    mChart.getAxisLeft().setStartAtZero(false);
    mChart.getAxisRight().setEnabled(false);
    if(General.InnerClass.Y2AxisValues.size()>0)
    {
     mChart.getAxisRight().setEnabled(true);
     mChart.getAxisRight().setSpaceBottom(12.25f);
     mChart.getAxisRight().setAxisMaxValue(Y2MaxValue);
     mChart.getAxisRight().setAxisMinValue(Y2MinValue);
     mChart.getAxisRight().setStartAtZero(false);
     mChart.getXAxis().setAvoidFirstLastClipping(true);
    }
    mChart.setData(data);
    progbar.setVisibility(View.GONE);
    mChart.invalidate();
