### ISSUE TITLE
Bar Graph hangs while updating it simultenously

### ISSUE THREAD

**Issue by mitesh-shah** [PhilJay/MPAndroidChart#812]
Hello PhilJay,

Thank you for a creating such a good library.

I am calculating the sound frequency using FFT algorithm and passing the values to graph so that graph will update continuously. But graph hangs and whole UI blocks.
It updates at first time then it hangs, it goes in setData function every time but UI doesn't update.

I am providing the code below, for now i am passing static values to arraylist not the actual FFT values. and shuffling that arraylist. Please check what i am missing. :( :(

       ArrayList<Integer> testListNew = new ArrayList<Integer>();
       Handler handlerNew = new Handler();
       Runnable r;

        testListNew.add(21);
        testListNew.add(28);
        testListNew.add(30);
        testListNew.add(35);
        testListNew.add(42);
        testListNew.add(47);
        testListNew.add(53);
        testListNew.add(58);
        testListNew.add(60);
        testListNew.add(63);

       private void setData(int count, float range) {

             Collections.shuffle(testListNew);

             Log.v("", "Shuffled Value: " + testListNew.get(0));

             ArrayList<String> xVals = new ArrayList<String>();
                for (int i = 0; i < count; i++) {
                     xVals.add(mMonths[i % 10]);
                }

              ArrayList<BarEntry> yVals1 = new ArrayList<BarEntry>();

               for (int i = 0; i < count; i++) {
                      //float mult = (range + 1);
                     //float val = (float) (Math.random() * mult);
                      yVals1.add(new BarEntry(testListNew.get(i), i));
              }

             BarDataSet set1 = new BarDataSet(yVals1, "DataSet");
             set1.setBarSpacePercent(35f);

             ArrayList<BarDataSet> dataSets = new ArrayList<BarDataSet>();
             dataSets.add(set1);

            BarData data = new BarData(xVals, dataSets);
            //data.setValueFormatter(new MyValueFormatter());
            data.setValueTextSize(10f);
            data.setValueTypeface(mTf);
            mChart.setData(data);
    }

    private double ComputeFrequency(int arrayIndex, int value) {

         r = new Runnable() {
             public void run() {

                setData(10, 10);
                mChart.invalidate();
            
                handlerNew.postDelayed(this, 100);
            }
        };

        handlerNew.post(r);
    }

The Log for shuffled values are changing continuously but UI (Graph) is not updating. The ComputeFrequency function runs at every milisecond based on AudioProcessing.

I thought the problem is we are creating BarData object at every milisecond this might hangs the UI, is there any way by updating it without creating object like we do for Adapters (BaseAdapter). I have also used mChart.notifyDataSetChanged(); but it's not working.

Please help. Your little help will be much appreciated.
Thank you so much.! If you want more details, please do let me know.

**Comment by PhilJay** [comment]
You are not calling `invalidate()` to refresh the chart-view.
