### ISSUE TITLE
Customized X axsis labels

### ISSUE THREAD

**Issue by Shahroz16** [PhilJay/MPAndroidChart#813]
Hi PhilJay, thanks for an amazing library, before bothering you I tried searching for a similar issue in the list of open and closed issues but could't find any. Anyways I wanted to ask is there any way I can customized the labels in x axis ?.
![chart](https://cloud.githubusercontent.com/assets/4658866/8391767/e9d8ac96-1ce7-11e5-8689-36c275a0f19b.jpg)

Also how can I get this dotted line in the middle ? 
Any kind of help would be greatly appreciated.

**Comment by TR4Android** [comment]
@Shahroz16 To address your two issues:
* You can change the labels on the `XAxis` by changing the `ArrayList<String> xVals` passed to the `...Data()` constructor. To get the exact same result as your image you could try using the `setLabelsToSkip(int count)` method outlined in the [`XAxis`](https://github.com/PhilJay/MPAndroidChart/wiki/XAxis-%28XLabels%29) wiki. As images are not supported by the `XAxis` directly your best shot is to work around that by using unicode characters for example (&#x2600; `&#x2600;` and &#9790; `&#9790;`), although I have never tried it myself. You might also need to set a custom `Typeface` that supports those characters.
* To achieve the dotted vertical line you can use a `LimitLine`. More on that subject can be found in the [`The Axis`](https://github.com/PhilJay/MPAndroidChart/wiki/The-Axis) wiki in the **Limit Lines** section.

**Comment by Shahroz16** [comment]
@TR4Android Thanks alot, will give these very useful looking suggestions a try. :+1:
