### ISSUE TITLE
Change Highlight indicator on Line charts

### ISSUE THREAD

**Issue by knseir** [PhilJay/MPAndroidChart#814]
Hi Phil, 
I've looked in the documentation, and couldn't find anything to change the highlight indicator on line charts.
I'm looking at changing the color, width, and removing the horizontal line.
I've only found a way to change the width so far (chart.setHighlightLineWidth() )
Thank you

**Comment by fountaingeyser** [comment]
@knseir Have you already tried `setHighLightColor(int color)` of the [`BarLineScatterCandleDataSet`](https://github.com/PhilJay/MPAndroidChart/blob/f32cfd04d223665eab9db9fdfc36328cec8a2ac9/MPChartLib/src/com/github/mikephil/charting/data/BarLineScatterCandleDataSet.java) to change the color?
Your implementation might look something like this to change the color of your highlight indicator:
```Java
LineDataSet set = new LineDataSet(mYVals, label);
...
set.setHighLightColor(ctx.getResources().getColor(R.color.color_highlight_indicator));
```
Not sure what you meant with 
> removing the horizontal line 

though. Did you mean you only want to remove the horizontal line but want the vertical line to be shown?

**Comment by knseir** [comment]
'Did you mean you only want to remove the horizontal line but want the vertical line to be shown?'
Yes, that's it. The intersection of the highlight indicator and the line chart is marked by a vertical and a horizontal line. I need to show only the vertical line.

Also, if possible, replace that line by a custom drawable

**Comment by fountaingeyser** [comment]
@knseir Sorry, but I'm not aware of a possibility to do something like that. Maybe @PhilJay or @danielgindi can help you there.

**Comment by knseir** [comment]
@fountaingeyser Thanks for answering. I'll look into making some changes to the library then

**Comment by sankar07** [comment]
Hi, while drawing the vertical highlight line in a line chart, i need the line upto the point in the graph.
How can we implement that

**Comment by muhammadWaqasCheetayPk** [comment]
> @knseir Have you already tried `setHighLightColor(int color)` of the [`BarLineScatterCandleDataSet`](https://github.com/PhilJay/MPAndroidChart/blob/f32cfd04d223665eab9db9fdfc36328cec8a2ac9/MPChartLib/src/com/github/mikephil/charting/data/BarLineScatterCandleDataSet.java) to change the color?
> Your implementation might look something like this to change the color of your highlight indicator:
> 
> 
> LineDataSet set = new LineDataSet(mYVals, label);
> ...
> set.setHighLightColor(ctx.getResources().getColor(R.color.color_highlight_indicator));
> Not sure what you meant with
> 
> > removing the horizontal line
> 
> though. Did you mean you only want to remove the horizontal line but want the vertical line to be shown?

Set property **drawHorizontalHighlightIndicatorEnabled = false** on the set you want to remove horizontal line

**Comment by enricomoko** [comment]
> Hi, while drawing the vertical highlight line in a line chart, i need to show only the line upto the point in the graph.
> How can we implement that

UP!!! there's a way to extends the Highlighter and draw only from the bottom to the value and not above?

**Comment by juleimisf** [comment]
> Hi, while drawing the vertical highlight line in a line chart, i need to show only the line upto the point in the graph. How can we implement that

is there a way?

**Comment by spencerhowell** [comment]
> > Hi, while drawing the vertical highlight line in a line chart, i need to show only the line upto the point in the graph. How can we implement that
> 
> is there a way? @PhilJay

@juleimisf The way to implement this is to override the `drawHighlightLines()` method in a custom `LineChartRenderer` subclass. There you can change the drawing function to end at the provided `y` value.

Hope this helps!
