### ISSUE TITLE
Realtime  Data Example does nothing

### ISSUE THREAD

**Issue by Binero** [PhilJay/MPAndroidChart#816]
I figured I would try out the example before using this library. I am mostly interested in the real-time capabilities.

This example doesn't seem to be working though on my stock-5.1 Android Nexus device though. It says "No chart data available. You need to provide data for the chart.". The "Clear Values" button adds a legend but still no data. The "Add Entry" button seems to do nothing at all.

![screenshot_2015-06-29-01-22-30](https://cloud.githubusercontent.com/assets/6867251/8398791/5cd73166-1dfd-11e5-83aa-b4e8ba83a98a.png)

Furthermore, as a side-question, would this library be suitable for real-time data much like a heartbeat monitor you'd see in a hospital?

**Comment by PhilJay** [comment]
Add a dataset, then add entries, the behaviour is expected.

**Comment by Binero** [comment]
There is no add dataset button...

**Comment by Binero** [comment]
@PhilJay Can you also please answer my last side-question?
