### ISSUE TITLE
android studio cannot resolve XLabels and YLabels

### ISSUE THREAD

**Issue by Fakher-Hakim** [PhilJay/MPAndroidChart#822]
i changed my gradle file like this:
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.PhilJay:MPAndroidChart:v2.1.0'
}

but the problem is that the android studio cannot resolve XLabels and YLabels but it can resovle other classes from this lib such as LineData or Entry

**Comment by fountaingeyser** [comment]
@Fakher-Hakim XLabels was replaced with [`XAxis`](https://github.com/PhilJay/MPAndroidChart/blob/f32cfd04d223665eab9db9fdfc36328cec8a2ac9/MPChartLib/src/com/github/mikephil/charting/components/XAxis.java) in version 2.0.0 as far as I know. For more information have a look at the [XAxis (XLabels)](https://github.com/PhilJay/MPAndroidChart/wiki/XAxis-%28XLabels%29) section of the wiki.

**Comment by Fakher-Hakim** [comment]
@fountaingeyser  yes you have right thanks :)
i am working on a project now, the problem is that there's a lot of mthodes that cannot be resolved such as "setDrawYValues", ""setDrawXValues ...

**Comment by PhilJay** [comment]
There have been a lot of changes in the API.
Use the wiki it should help you resolve them.
