### ISSUE TITLE
Pie Chart: Section becomes grey upon selecting other section

### ISSUE THREAD

**Issue by Jakob-Ruf** [PhilJay/MPAndroidChart#824]
When selecting a section of a pie chart consisting of just 2 sections, one section becomes grey upon selecting the other one. This does not happen when selecting the other section.

[selected](http://i.imgur.com/5v6H0fJ.png)
[not selected](http://i.imgur.com/BmYdG5B.png)

**Comment by PhilJay** [comment]
Which version are you using?

**Comment by Jakob-Ruf** [comment]
I added "com.github.PhilJay:MPAndroidChart:v2.1.0" to the gradle file so it should be the latest version

**Comment by PhilJay** [comment]
Which device is it and which android version?
Currently unfortunately I am unable to reproduce the issue after some time of testing

**Comment by NamTranDev** [comment]
PieChart can handle with bitmap from url not color
