### ISSUE TITLE
How to hide chart Lables ? How to add axis titles ?

### ISSUE THREAD

**Issue by Seanmir** [PhilJay/MPAndroidChart#828]
Hello,
I tried to hide chart value labels but I can't figure it out, Here is the current charts that I Have:

![donut](https://cloud.githubusercontent.com/assets/10271758/8521084/b0ab3948-23e0-11e5-8782-7591a6ed62a6.png)

![screenshot_2015-07-06-13-04-24](https://cloud.githubusercontent.com/assets/10271758/8521088/b3f13c60-23e0-11e5-9838-bcc756a087e1.jpeg)

Is it possible to hide these labels ?
And another issue, is it possible to add axis Titles ? like the one that I have for Bar Chart (I used separate Text view for that Calories title)

And also currently the pie chart have animations and interactions, How can I disable that ?

Thank a lot.

**Comment by PhilJay** [comment]
`dataSet.setDrawValues(false)`

It's all in the documentation.
Concerning the axis-title: I have no idea where that comes from, this library does not even support axis-titles.

**Comment by knseir** [comment]
Hi Philipp,
dataSet.setDrawValues(false) on a pieChartDataSet just makes it so that it hides the values.
What if I need it to show the values but hide what's in xValues ? (currently shows "option A 30" & "option B 70", need only "30" and "70"
also, would like to make the font bigger
Thank you

**Comment by hotzambo** [comment]
I think to hide description values is to add blank string like this.
ArrayList<String> xVals = new ArrayList<String>();
        for (int i = 0; i < entryPercorso.size() + 1; i++)
            xVals.add("");

        PieData dataPercorso = new PieData(xVals, dataset);

**Comment by ashokcs** [comment]
This will hide Legends also..  Any other way to hide only xvalues alone?

**Comment by coolscott** [comment]
eg. mChart.getXAxis().setDrawLabels(false);

**Comment by ashokcs** [comment]
@coolscott It doesn't work. there is no method called getXAxis() is available.

**Comment by coolscott** [comment]
sorry. yes~ it's PieData. try isDrawSliceTextEnabled() instead.

**Comment by ashokcs** [comment]
You meant mPieChart.setDrawSliceTextEnabled(false) right? Yes, it works. Your swift help made my day. Thanks a lot @coolscott

**Comment by coolscott** [comment]
bingo. it's my pleasure.

**Comment by anuragphadke19** [comment]
I know this is an old thread, but I can't locate mPieChart.setDrawSliceTextEnabled(false) method anymore. It seems to be have been removed. Is there an alternate way to hide just the labels on the chart but not the legend?

**Comment by anuragphadke19** [comment]
Found the answer almost immediately looking at the code. Just for completion sake, the method to use now is : mPieChart.setDrawEntryLabels(false)

**Comment by jackengine** [comment]
@coolscott `isDrawSliceTextEnabled` method is not resolved with latest.
