### ISSUE TITLE
Bar Chart width settings it can be fixed

### ISSUE THREAD

**Issue by 120660021** [PhilJay/MPAndroidChart#83]
I demo in BarChartActivity class 111line mSeekBarX.setProgress (12); modified mSeekBarX.setProgress (1);，When only one bar Chart, when the width of the bar graph is too large, there is a fixed attribute can set its width it? Thanks

**Comment by vaiiibhav** [comment]
barChart.getLayoutParams().height=100*count;
where count is the number of bars to be displayed

**Comment by milon87** [comment]
It is not about spacing between bars. I need to fix the bar width. suppose I have only one bar to show then it covers whole area.

**Comment by CyberMew** [comment]
`dataSet.setBarWidth(barWidth);` should work.

**Comment by AndrewWay** [comment]
setBarWidth and setBarSpace don't appear to be methods for BarDataSet anymore.
