### ISSUE TITLE
How to avoid showing text description when no data loaded in BarLineChartBase?

### ISSUE THREAD

**Issue by jacktan1991** [PhilJay/MPAndroidChart#830]
I use BarLineChartBase to display data received from back-end. Before loading the data, the BarLineChartBase's onDraw method will return doing nothing.
```java

    @Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);

        if (mDataNotSet)
            return;

        long starttime = System.currentTimeMillis();
        calcModulus();
        ...
```

and then text description will be shown, how to avoid that? Instead of showing text description, I want show **blank grid background**.

**Comment by danielgindi** [comment]
`chart.setNoDataTextDescription("");
