### ISSUE TITLE
Present some of the data on combined chart

### ISSUE THREAD

**Issue by EfiMIsh** [PhilJay/MPAndroidChart#831]
Hi,

I want to present only the first hour data on a chart with seven hours. How to do that without the graph being scaled with only the data that is present?

Thanks in advance,
Efi

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport

**Comment by EfiMIsh** [comment]
Actually, this was not the answer. It took a long time to find how to create partial graphs, which I am sure many users need.
