### ISSUE TITLE
Add a custom font at the chart

### ISSUE THREAD

**Issue by neaGaze** [PhilJay/MPAndroidChart#832]
Could you please suggest me on how to add custom signs like '%' at the top of the individual bar item in BarChart? Right now the only supported data type is float array in the BarEntry. And the float value is shown at top of the bar. Is there any way to show a String rather than float so that custom texts could be added?

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface
