### ISSUE TITLE
HorizontalBarChart Y axis values has cut off in large values

### ISSUE THREAD

**Issue by OmarHassan25** [PhilJay/MPAndroidChart#833]
I have posted this issue before but the developer reply does not help me,
https://github.com/PhilJay/MPAndroidChart/issues/681

I am using Horizontal Bar Chart, when using large values in Y axis values, these values have a cutoff and are partially drawn outside the screen. 
horizontalbarchart
![947be204-02cf-11e5-942f-d914221d7d3d](https://cloud.githubusercontent.com/assets/11418971/8547266/6a62a46c-24c6-11e5-92f2-3dbef96bfd1e.png)

The same thing happens in Line chart, when clicking marker view to see its values, the right most marker view is partially drawn outside the device screen.
linebarchart
![9e0cd6b6-02cf-11e5-98e9-36620940e43f](https://cloud.githubusercontent.com/assets/11418971/8547269/738f0260-24c6-11e5-99d1-4672ca8aad53.png)

**Comment by PhilJay** [comment]
Set bigger offsets or change the y-axis range - it's all in the documentation.

**Comment by usmanfarhat** [comment]
I am having the same issue as in the first screen shot. I am using HorizontalBarChart. I am using the following code:
                    BarData data = new BarData(labels, dataset);
                    data.setValueFormatter(new MyValueFormatter());

                    chart.setData(data);
                    XAxis xAxis = chart.getXAxis();
                    xAxis.setPosition(XAxis.XAxisPosition.BOTTOM); //bottom is good
                    xAxis.setDrawGridLines(false);
                    xAxis.setDrawAxisLine(false);

                    YAxis yAxis = chart.getAxisLeft(); // upper part
                    yAxis.setEnabled(false);

                    yAxis = chart.getAxisRight(); // lower part
                    yAxis.setEnabled(false);

                    chart.setDrawGridBackground(false);

                    chart.setDescription("");
                    chart.getLegend().setEnabled(false);
                    chart.setTouchEnabled(false);

                    chart.animateY(5000);
                    chart.invalidate();

the class MyValueFormatter returns this-
 mFormat.format(value) + " votes";

Here, in the maximum value, e.g "7 votes", I get "7 vote".
I even tried to set a limited layout_width and left blank space to my right and then used android:clipChildren="false" but still the text animates and cuts just on the border of the HorizontalBarChart.

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/YAxis-(YLabels)

**Comment by usmanfarhat** [comment]
thanks for replying but I'm afraid I'm still confused.
first of all, in horizontal bar chart, the x axis shows the bars and their values as seen by the following code. the said position has effect on the position of the text values.

    xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);

but you're referring to a page of y axis. Yet I've gone through the guides for both axes and for the generic axis but failed to find a solution. Please guide me.. I've made a whole app dependent on this module but now I'm stuck.

maybe I'm missing a very minor thing but I've spent hours on this issue with no fruitful result.

**Comment by Spoonrad** [comment]
I haven't found a way to solve this issue either. My value gets cut off at the right end of my bar charts when the value is close to the maximum, and setting offsets does not solve the issue.

**Comment by usmanfarhat** [comment]
I've given up this module and made my own layout using progress bars.

**Comment by Spoonrad** [comment]
I fixed this using:
`setViewPortOffsets(float left, float top, float right, float bottom)`
https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport

:)

**Comment by CyberMew** [comment]
My dataset value text are also being truncated, since I have my own custom value formatter which added more characters to the default one. I'm on 3.0, is there no way to shrink the bars to fit the text?

**Comment by vichare-ketan89** [comment]
Try this:
mChart.setExtraRightOffset(30f);

**Comment by WTDIndia** [comment]
![chart](https://user-images.githubusercontent.com/6008499/48050655-79532100-e1c8-11e8-902e-a58bf42b4e2f.png)


My code is here ....right sid ecut the chart

 for(int i=0;i<list.get(position).areaLocation.size() ;i++)

        {
           // Log.d("==Area == size :: ",list.get(position).areaLocation.size()+"");

            List<Entry> entryL = new ArrayList<>();

            for(int j=0;j<list.get(position).areaLocation.get(i).listLine.size();j++)

            {

                Line data =list.get(position).areaLocation.get(i).listLine.get(j);

                entryL.add(new Entry(Float.parseFloat(data.x),Float.parseFloat(data.y)));
            }
            Collections.sort(entryL, new EntryXComparator());

            LineDataSet dataset = new LineDataSet(entryL, null);
            dataset.setAxisDependency(YAxis.AxisDependency.LEFT);
            dataset.setColor(context.getResources().getColor(R.color.line1));
            dataset.setFillColor(context.getResources().getColor(R.color.linebg));
            dataset.setDrawFilled(true);
            dataset.setCubicIntensity(2f);
            dataset.setLineWidth(2f);
            dataset.setCircleRadius(4f);
            dataset.setCircleColor(context.getResources().getColor(R.color.linebg));
            dataset.setDrawCircleHole(false);
            dataset.setDrawCircles(true);
            dataset.setMode(LineDataSet.Mode.HORIZONTAL_BEZIER);

            iLinedata.add(dataset);

        }
        LineData linedata = new LineData(iLinedata);
        holder.mChart.setExtraBottomOffset(0f);
         holder.mChart.setExtraRightOffset(0f);
        holder.mChart.setData(linedata);

        holder.mChart.invalidate(); //refreshing the line chart


        XAxis xAxis = holder.mChart.getXAxis();
        xAxis.setGranularity(1f);
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setYOffset(0f);
        xAxis.setDrawGridLines(false);

//============
not working any solutions. Plz help me

**Comment by almic** [comment]
@WTDIndia please do NOT POST CODE on old issues and expect someone to come along and fix everything for you. This issue has been resolved, as Philip originally said that adding extra offset to the chart fixes this. Again, do not do this kind of stuff on issue trackers, no one likes it.

**Comment by mostafaimran** [comment]
`override fun getOffsetForDrawingAtPoint(posX: Float, posY: Float): MPPointF {
        if (posX > chartView.width - width) {
            offset.x = (-width).toFloat()
        } else {
            offset.x = (-(width / 2)).toFloat()
        }

        offset.y = -(height / 2).toFloat()

        return offset
    }`

You need to set chart view to `MarkerView.chartView` before calculation.
