### ISSUE TITLE
Various wiki documentation errors

### ISSUE THREAD

**Issue by joshfriend** [PhilJay/MPAndroidChart#835]
I found a few issues with the documentation on the wiki:

* `setTouchEnabled` is [duplicated on the same page twice](https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart)
* `setVisibleYRange` is mentioned [here](https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport) but [does not actually exist](https://github.com/PhilJay/MPAndroidChart/search?utf8=%E2%9C%93&q=setVisibleYRange)
* `BarLineChartBase.setVisibleYRangeMaximum` is not documented.

Also, would it be easy (and beneficial) to post the generated javadoc to the GitHub pages site for this repo? ([example](http://prolificinteractive.github.io/material-calendarview/))

**Comment by PhilJay** [comment]
Thanks man, JavaDoc is a good idea!
