### ISSUE TITLE
When adding OnTouchListener to LineChart can't zoom

### ISSUE THREAD

**Issue by ratll** [PhilJay/MPAndroidChart#836]
When I add OnTouchListener to my LineChart I lost ability to zoom. Is it issue or I'am doing something wrong.

**Comment by joshfriend** [comment]
[Zoom is handled by the chart touch listener](https://github.com/PhilJay/MPAndroidChart/blob/be95c277e908a959e117bdb15c7c3366202861ab/MPChartLib/src/com/github/mikephil/charting/listener/BarLineChartTouchListener.java#L66-L213). You probably have overridden this, or are always returning `true` from your listener which indicates the event should not be passed along.

**Comment by ratll** [comment]
Tried return true and false and neither aproach worked.

**Comment by danielgindi** [comment]
You have probably replaced the Touch Listener of the chart by your own. This means that the code handling zoom and panning is no longer there.
You can keep a reference to the original listener, and pass the events to it after you are done with them.

**Comment by PhilJay** [comment]
Daniel said it all :-)
