### ISSUE TITLE
setHighlightEnabled on particular DataSet

### ISSUE THREAD

**Issue by jkwiecien** [PhilJay/MPAndroidChart#837]
Can we have possibility to ```setHighlightEnabled``` on particular DataSet instead the whole chart?

**Comment by joshfriend** [comment]
Check out 4ec22d79. It's not in a tagged version yet, but you can still [use Jitpack to get `master`](https://jitpack.io/#philjay/mpandroidchart/master).

**Comment by PhilJay** [comment]
Already possible, just not released yet.

**Comment by jkwiecien** [comment]
I cannot sync gradle when using ```compile 'com.github.philjay:mpandroidchart:master'````
