### ISSUE TITLE
Performance of initbuffers

### ISSUE THREAD

**Issue by Troels51** [PhilJay/MPAndroidChart#838]
I wanted to test the library for an application with real-time data, so i downloaded the source code and changed the real-time example to write a lot more entries to the chart with a very small delay.

In the beginning the app could handle the increased load, but after some time it got more and more sluggish. I narrowed the performance problem down to a lot of allocations in the renderers initbuffers method, which is called each each time the data set changes.

The initbuffers method allocates new buffers using the size of the dataset.

The old buffers should be reused to avoid the extra allocations. Perhaps you could double the size everytime the size limit is reached to amortize the cost.

An example of how it could be implemented in LineChartRenderer is below, it reduced the amount of allocations by a lot, but i'm not familiar enough with the code base to say that it doesn't break something else

```java
    @Override
    public void initBuffers() {
        LineData lineData = mChart.getLineData();
        if(mLineBuffers == null ||
            mLineBuffers.length != lineData.getDataSetCount())
        {
            mLineBuffers = new LineBuffer[lineData.getDataSetCount()];
            mCircleBuffers = new CircleBuffer[lineData.getDataSetCount()];
            for (int i = 0; i < mLineBuffers.length; i++) {
                LineDataSet set = lineData.getDataSetByIndex(i);
                if (mLineBuffers[i] == null) {
                    mLineBuffers[i] = new LineBuffer(set.getEntryCount() * 4 - 4);
                    mCircleBuffers[i] = new CircleBuffer(set.getEntryCount() * 2);
                }
            }
        }
        else {
            for (int i = 0; i < mLineBuffers.length; i++)
            {
                LineDataSet set = lineData.getDataSetByIndex(i);
                if (set.getEntryCount() * 4 > mLineBuffers[i].size()) {
                    mLineBuffers[i] = new LineBuffer(mLineBuffers[i].size() * 2);
                    mCircleBuffers[i] = new CircleBuffer(mCircleBuffers[i].size() * 2);
                }
            }
        }
    }
```

**Comment by danielgindi** [comment]
@PhilJay I think we could move the calculations code back to the renderers, and keep a small buffer to prevent allocations. i.e. a buffer for Rect, a buffer for Point etc.

**Comment by danielgindi** [comment]
This was actually done already for line charts, and will be done to the other ones when we have spare time...
