### ISSUE TITLE
double clicking line chart doubles y axis

### ISSUE THREAD

**Issue by chitgoks** [PhilJay/MPAndroidChart#839]
im not sure why it acts this way. i have a simple linechart

when i double click it, the y axis gets double for every double click

also, while limitline is a start, do you have plans to make like a limitbounds? rendering limitlines every 0.01 distance is expensive

**Comment by joshfriend** [comment]
Double tap is supposed to zoom in Android. This gesture works in maps/chrome/basically anywhere pinch to zoom also works.

**Comment by chitgoks** [comment]
ah i see. then ill just disable double click to disable zoom
