### ISSUE TITLE
The animation lags every time on startup

### ISSUE THREAD

**Issue by SilverFoxA** [PhilJay/MPAndroidChart#842]
Whenever the activity with the graph starts the default animation lags after going to a point and again starts working.
i.e. it comes to a point, stuck for a sec and again goes up.

**Comment by PhilJay** [comment]
That has simply to do with the huge load that is on the CPU / GPU when a new Activity is started, especially when that activity has a lot of stuff to do at startup. Workarounds could be to reduce the load, and do only the stuff that is necessary, or delay the data setting / animation of the chart.
