### ISSUE TITLE
How to disable the two lines when slip? Thanks.

### ISSUE THREAD

**Issue by mengfanpp** [PhilJay/MPAndroidChart#845]
See this picture: http://a3.qpic.cn/psb?/V13pUGJK3iqhUY/NVUwWizxaqDn0JD6jsblkBqniUZA3RzV.WW.lp0NDi0!/m/dBoBAAAAAAAAnull&bo=xQEgAQAAAAADB8c!&rf=photolist&t=5

**Comment by PhilJay** [comment]
#814
