### ISSUE TITLE
MPAndroidChart BarChart Crash

### ISSUE THREAD

**Issue by jinseok7586** [PhilJay/MPAndroidChart#846]
I am trying to implement the BarChart from MPAndroidChart. When I call the setData() method from the barchart, I get the following error:

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

The crash is occuring at the following place: com.github.mikephil.charting.components.YAxis.getLongestLabel(YAxis.java:333)

I literally copied the sample code. What is going on?

**Comment by PhilJay** [comment]
Somewhere in your code you provided a `String` for the library that is null. Thats why your app is crashing.
