### ISSUE TITLE
LineChartRenderer.drawLinear(...)

### ISSUE THREAD

**Issue by robertschmid** [PhilJay/MPAndroidChart#847]
Back in v1 this method (then in LineChart) used a Path and Canvas.drawPath() instead of the current use of the buffer and drawLines.  Around line 327 in LineChartRenderer.drawLinear.

This had the effect that I could add a CornerPathEffect to the Paint used for rendering and smooth out thick lines.  Now, when using a thick line, it is jagged.  I simply overrode the renderer and the method to use the old code but would it be possible to get this approach back in the main project?

**Comment by PhilJay** [comment]
drawLines is much better on performance, therefore it will stay
