### ISSUE TITLE
XValueFormatter (level of detail)

### ISSUE THREAD

**Issue by cpfeiffer** [PhilJay/MPAndroidChart#848]
MPAndroidChart nicely manages to selectively display only certain x values+labels when there are too many.

In this case it would be nice if one could display different x labels depending on the number of x-labels skipped.

Imagine a time scale on the x axis with values for every minute. The label for every entry would typically be the timestamp (hour:minute). Now depending on how many entries you display (a day, a week, a month), it doesn't make sense to display hour:minute. For a week, you would rather display the day, or maybe day:hour. For a month maybe just the day.

The whole thing not only depends on the number of entries provided though, but on the entries actually displayed in the viewport. I.e. when you zoom deep into a month, you may want to get the actual hour:minute labels again.

It would be nice if MPAndroidChart would provide an XValueFormatter interface that would be provided with enough information so that it can calculate the "level of detail" to calculate an appropriate label.

**Comment by PhilJay** [comment]
Okay. "provided with enough information" --> what do you have in mind that could be useful?
