### ISSUE TITLE
getPixelsForValues return wrong value after add view dynamical

### ISSUE THREAD

**Issue by codezjx** [PhilJay/MPAndroidChart#850]
```java
mChartContainer.addView(chartView, LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.MATCH_PARENT);
int posY = (int) chart.getPixelsForValues(0, XX, chart.getAxisLeft().getAxisDependency()).y;
```

After add chartView dynamical, and call getPixelsForValues() immediately, method return a wrong value! Same situation in getValuesByTouchPoint() method.

**Comment by PhilJay** [comment]
Yep, that's because the chartview has not been measured yet and does not know it's size. So it cannot calculate correct mapping values.
