### ISSUE TITLE
BUG: Unable to re-set CombinedChart data

### ISSUE THREAD

**Issue by 0xBEEF** [PhilJay/MPAndroidChart#851]
When you call setData on a combinedChart that already have a dataSet, and the new dataset doesn't contain all of the dataset types of the previous dataset, the CombinedChartRenderer tries to work with it's old configuration(the old dataset types) and thus a nullpointer is thrown.
Version is v2.1.0

Stacktrace:
.charting.data.BarData.getDataSetCount()' on a null object reference
.BarChartRenderer.initBuffers(BarChartRenderer.java:54)
.CombinedChartRenderer.initBuffers(CombinedChartRenderer.java:79)
.BarLineChartBase.notifyDataSetChanged(BarLineChartBase.java:294)
.Chart.setData(Chart.java:280)
.CombinedChart.setData(CombinedChart.java:117)

Steps to reproduce this stacktrace:
1: add combinedData which includes LineData and BarData
2: display chart
3: add new combinedData which only include LineData

**Comment by hfahmy** [comment]
This bug still persists. Steps to reproduce:

                CombinedData data1 = new CombinedData();
                data1.setData(asLineData(snip.getName(), snip.getPayload().second));
                chart.setData(data1);

                CombinedData data2 = new CombinedData();
                data2.setData(asBarData(snip.getName(), snip.getPayload().second));
                chart.setData(data2);`
