### ISSUE TITLE
Multiple colorin singleline chart 

### ISSUE THREAD

**Issue by assaddia** [PhilJay/MPAndroidChart#852]
i am trying to add multiple color in singel line chart to show the level of confidence of data represent by different color i tried this code
    int c=prin(RF);
           if(c==2)
           set.setCircleColor(Color.BLACK);
           if(c==1)
        	   set.setCircleColor(Color.RED);
            data.addEntry(new Entry((int) (c), set.getEntryCount()), 0);

initially  graph shows red for c==1 when the velue of c changed to 2 then whole result changed to black (including previous resultwhich was red before) is to possiblein mpandroid chart to assigne different color todiff values in single line chart

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Setting-Colors
