### ISSUE TITLE
[Issue]Cannot resolve method 'addLimitLine'

### ISSUE THREAD

**Issue by AndyFoolish** [PhilJay/MPAndroidChart#853]
I have just started to learn how to use MPAndroidChart, 
I just created a BarChart, and it worked well. But when I added two lines, 

LimitLine line = new LimitLine(10f);
data.addLimitLine(line);

Android Studio showed me an issue. Just like this:
"Cannot resolve method 'addLimitLine(com.github.mikephil.charting.components.LimitLine)'".

Can anyone help me?

**Comment by PhilJay** [comment]
`LimitLines` are now handled via the `Axis`.
https://github.com/PhilJay/MPAndroidChart/wiki/The-Axis
