### ISSUE TITLE
ART runtime issue

### ISSUE THREAD

**Issue by shawncalda** [PhilJay/MPAndroidChart#854]
graphs stuck in single line when using ART runtime, might cause future issues if ever google decides to use ART instead of Dalvik

**Comment by MGaetan89** [comment]
Which is the case since Android 5.0.

**Comment by shawncalda** [comment]
yea, im on android kitkat but yesterday i switched to ART instead of Dalvik then experienced this issue, i switched back to Dalvik and now it's displaying fine

**Comment by PhilJay** [comment]
What odes "graph stuck in single line" mean?

**Comment by shawncalda** [comment]
oh sorry i meant all of the y-axis labels are in a single line and no graph was drawn (line graph used in this case).

sorry i cant take a screenshot since i converted it back to dalvik already
