### ISSUE TITLE
How did i set line width in HorizontalBarChart 

### ISSUE THREAD

**Issue by yaming116** [PhilJay/MPAndroidChart#855]
thx

**Comment by PhilJay** [comment]
Which line?

**Comment by yaming116** [comment]
![barchar](https://camo.githubusercontent.com/2ec281e0ac3013076bff1c3ac00d8d6de372d7a4/68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d5043686172742f6d61737465722f73637265656e73686f74732f686f72697a6f6e74616c5f62617263686172742e706e67)

When I have a lot of the time, each is very small, so I wanted to give each setting a minimum height

**Comment by yaming116** [comment]
who can help me? thx

**Comment by PhilJay** [comment]
I still don't know which line you mean. The grid?

**Comment by yaming116** [comment]
#335

**Comment by PhilJay** [comment]
So you mean the width of the "bars"?
That width cannot be modified it only depends on the x-axis scale.
