### ISSUE TITLE
Remove HorizontalBarChart background grid

### ISSUE THREAD

**Issue by bkawakami** [PhilJay/MPAndroidChart#856]
Hey guys!

I want remove the grid in background of my Horizontal BarChart. But seems like impossible :(

I tried:

chart.getAxisLeft().setDrawAxisLine(false);
chart.getAxisLeft().setDrawGridLines(false);
chart.setDrawGridBackground(false);
chart.setDrawingCacheEnabled(false);

And nothing work...

Someone know how remove this grid?

**Comment by PhilJay** [comment]
disable the right axis

**Comment by bkawakami** [comment]
well, still have a horizontal grid. I want my background without any grids or labels...

chart.getAxisRight().disableGridDashedLine();
chart.getAxisRight().setDrawTopYLabelEntry(false);
chart.getAxisRight().setDrawGridLines(false);
chart.getAxisRight().setDrawAxisLine(false);

chart.getAxisLeft().disableGridDashedLine();
chart.getAxisLeft().setDrawTopYLabelEntry(false);
chart.getAxisLeft().setDrawGridLines(false);
chart.getAxisLeft().setDrawAxisLine(false);

I really don't understand what is wrong :/

**Comment by bkawakami** [comment]
Well...

I add the XAxis and works! For documentation if someone one day need this:

chart.getXAxis().setDrawGridLines(false);
chart.getXAxis().setDrawAxisLine(false);
chart.getXAxis().disableGridDashedLine();

**Comment by josemigallas** [comment]
Thanks a lot!
