### ISSUE TITLE
"fill-line" on candle graph possibility

### ISSUE THREAD

**Issue by ordele** [PhilJay/MPAndroidChart#858]
hi,
do you have something like a horizontal guide line across the candle graph ,which be able to point on the current rate?
  
![candle after](https://cloud.githubusercontent.com/assets/12711000/8651897/464d7472-2984-11e5-90b6-c38e5c3b20cf.png)
![device-2015-07-13-171026](https://cloud.githubusercontent.com/assets/12711000/8651899/4a96685e-2984-11e5-8691-bd31b5722577.png)

**Comment by PhilJay** [comment]
Check the `LimitLine` class
