### ISSUE TITLE
remove the XAxis slightly up and YAxis slightly left  

### ISSUE THREAD

**Issue by ordele** [PhilJay/MPAndroidChart#859]
hi,
for some reason i cant add the attribute "android:layout_margin_Bottom" and "android:layout_margin_Left" in my .XML (on the candle graph component) , there is any way to change Axis (X and Y) location beside 
xAxis.setPosition (BOTTOM/TOP/etc...) and yAxis.setPosition....?

**Comment by PhilJay** [comment]
No, there is no other way
