### ISSUE TITLE
Rotate the chart in a fixed portrait activity

### ISSUE THREAD

**Issue by koyabr** [PhilJay/MPAndroidChart#864]
I have an activity which is set as <code>android:screenOrientation="portrait"</code>, in order to prevent rotation. The activity contains a toolbar and a fragment, nothing else. 

Now I'd like to draw a chart rotated 90 degrees, with X axis on the left and Y axis on the top, so I wrote the fragment xml as below:

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:rotation="90">

    <com.github.mikephil.charting.charts.LineChart
        android:id="@+id/chart"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</FrameLayout>

```

However I see only part of the chart is displayed, like this:

![untitled picture](https://cloud.githubusercontent.com/assets/3038766/8691035/d4274dc4-2aef-11e5-9528-d82c85084682.png)

How can I fix this? Thanks for any help.

**Comment by joshisunil-1983** [comment]
is there any specific need to rotate a chart . otherwise you can move the axis by using setpostion.
    mChart.getXAxis().setPosition(XAxis.XAxisPosition.BOTTOM);
    mChart.getXAxis().setPosition(XAxis.XAxisPosition.TOP);

**Comment by PhilJay** [comment]
Your charts height is greater than the width -> then you rotate -> then obviously the chart is too wide -> you need the height of the chart to be equal or smaller than the width

**Comment by DhayaKDS** [comment]
this is also not working suggest a better way to rotate
