### ISSUE TITLE
while plotting with dual y axis chart points mess in left of the chart.

### ISSUE THREAD

**Issue by joshisunil-1983** [PhilJay/MPAndroidChart#866]
i am plotting with line data chart. after adding y axis on right plotted data points not spread.
https://www.dropbox.com/s/wubkrxlel6vv3cf/WP_20150626_004.jpg?dl=0
https://www.dropbox.com/s/d843gir3g4i19b3/WP_20150626_003.jpg?dl=0

@PhilJay as you can see in my code given below that i am providing custom range for the each axis. This range provided on the behalf of actual data. so whenever chart data get changed i am providing the new range according to data. but chart data point not spreading over the x axis. why all of them appearing only in left of the chart. even scale also not start from the given min value. in above given image i am providing the min value 1240 and the max value 1440 to right axis and i want the interval of the data should be 40 but axis value not starting from the given value.can see in 1st image

    mChart = (LineChart) findViewById(R.id.Chart);
    mChart.setGridBackgroundColor(Color.parseColor("#F4F4F4"));
    mChart.setDrawGridBackground(false);
    mChart.setTouchEnabled(true);
    mChart.setHighlightEnabled(false);
    mChart.setDragEnabled(false);
    mChart.setScaleEnabled(true);
    mChart.setPinchZoom(true);
    mChart.setDescription("");
    mChart.getAxisLeft().setAxisMaxValue(YMaxValue);
    mChart.getAxisLeft().setAxisMinValue(YMinValue);
    mChart.getAxisLeft().setStartAtZero(false);
    mChart.getAxisRight().setEnabled(false);
    if(General.InnerClass.Y2AxisValues.size()>0)
    {
     mChart.getAxisRight().setEnabled(true);
     mChart.getAxisRight().setAxisMaxValue(Y2MaxValue);
     mChart.getAxisRight().setAxisMinValue(Y2MinValue);
     mChart.getAxisRight().setStartAtZero(false);
     mChart.getXAxis().setAvoidFirstLastClipping(true);
    }
    mChart.setData(data);
    progbar.setVisibility(View.GONE);
    mChart.invalidate();

**Comment by PhilJay** [comment]
you disabled the right axis so it cannot work

**Comment by joshisunil-1983** [comment]
it is on condition basis so when user want it ll become enable and visible to user

**Comment by PhilJay** [comment]
Okay, then I would check the x-indices you are using and make sure they are correct

**Comment by joshisunil-1983** [comment]
thnx @PhilJay  
let me check with the indices but why y axis on right not starting from just top of the x axis.
