### ISSUE TITLE
Adding Entries or DataSets dynamically (real time graph)

### ISSUE THREAD

**Issue by Praveen2106** [PhilJay/MPAndroidChart#87]
Hi Phil,
Is it possible to draw a real time graph (e.g. ECG) using your library ? I've tried to call invalidate after setting the value. But it doesn't draw anything. Please let me know if there is any extra implementation need for such chart.

**Comment by afzal1994** [comment]
barChart.setVisibility(View.GONE);
        barChart.setData(data);
        barChart.setVisibility(View.VISIBLE);
This will also work if we have to update the data by spinner selection or by any other means.This will work in all Dynamic Data

**Comment by senthilmnhr87** [comment]
Hi PhiilJay,

I'm trying to plot 12 lead ecg graph. Is it possible to plot using this library and also background grid should be a graph. 

If its possible can you share a code snippet.

Thanks,
Senthil
