### ISSUE TITLE
Does MPAndroidChart support 3D bar chart or this effect?

### ISSUE THREAD

**Issue by mengfanpp** [PhilJay/MPAndroidChart#870]
Does MPAndroidChart support 3D bar chart or this effect?

Thanks!

![1](https://cloud.githubusercontent.com/assets/1270807/8722040/35bc7b32-2bf3-11e5-8a43-9f8a63963fdd.png)

**Comment by PhilJay** [comment]
Stacked bars are supported, 3D bars are not.
