### ISSUE TITLE
LineChart shadow problem

### ISSUE THREAD

**Issue by guorongqiang** [PhilJay/MPAndroidChart#875]
1. shadow gradient can do it? If you can set the attributes?
2. If the value is a negative number, then the shaded how to draw a minimum value to a negative shadow, rather than painting 0 to a negative shadow it?

**Comment by PhilJay** [comment]
Shadows are not possible by default

**Comment by guorongqiang** [comment]
![image](https://cloud.githubusercontent.com/assets/8790809/8792546/49af4010-2f9b-11e5-84b8-2e22916a25bf.png)
This negative effect can display it?

**Comment by guorongqiang** [comment]
![image](https://cloud.githubusercontent.com/assets/8790809/8792596/f4ead1a6-2f9b-11e5-841c-2a5b50d78bb3.png)

Now the effect!
