### ISSUE TITLE
Select value on chart by default

### ISSUE THREAD

**Issue by sidsverma** [PhilJay/MPAndroidChart#876]
I want one bar of the bar chart to be selected by default(when the view is created). After this, the user can select any bar on the chart(and I react on it with onValueSelected()).
But, I want this default bar to be again selected in the case of onNothingSelected().

Is this possible? I have been looking for many resources for doing something like this but unable to find any.

Thanks.

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart
