### ISSUE TITLE
Showing "No chart data available" although non-empty data has been set.

### ISSUE THREAD

**Issue by dominikschubert** [PhilJay/MPAndroidChart#88]
The Charts semi-randomly show "No chart data available" instead of the chart data. If they are touch-enabled, they do render correctly after the first touch though.

**Comment by pmvegar** [comment]
In my line chart only shows " No chart data available " when the application starts, but then when for example I do not have data for the button 7 days shows me axis and I dont wants this, i want the message " No chart data available " 
![screenshot_2015-04-20-11-33-39](https://cloud.githubusercontent.com/assets/12030979/7227533/ad431684-e751-11e4-8cb4-ccbac4482c2f.png)

**Comment by crescent7272** [comment]
I have same problem. Even I have some data, pie chart started to not showing and printing "No chart data available" text.` lineChart.invalidate()` does not work for me. Is there another solution? Thanks.

**Comment by crescent7272** [comment]
Sorry solved the problem. There were really no data. thanks

**Comment by hellbreaks** [comment]
@crescent7272 could you tell me how you solved the problem, im in the same situation, and don't know how to fix it?

**Comment by crescent7272** [comment]
@hellbreaks actually it was not a real problem because there were really no data in my case. As I remember I had changed some place in my code but after I forgat that, so as a result my data set was empty.  When my data set is not empty there is no problem.

**Comment by suryasinghvijay** [comment]
solved the problem thanks @PhilJay and @dominikschubert

**Comment by ItsRajesh4uguys** [comment]
Hello, 

`  holder.chart.setNoDataText("No data available"); `
Above line is not showing any text when my  does not have any data.

**Comment by debupal99** [comment]
Same problem here, without click event the chart is not showing any data, although there is data, plz help me.

**Comment by waqarshaukat** [comment]
pieChart.invalidate();    saved my day,Thanks man

**Comment by HomoLupus** [comment]
Maybe you did not bind the chart with a view
chart = (LineChart) findViewById(R.id.chart);

**Comment by milk717** [comment]
I am implementing a native module using MPandroidchart in React Native and I am having the same problem. `lineChart.invalidate()` not work for me. If anyone has experienced the same problem, please let me know the solution
