### ISSUE TITLE
v2.1.1 jar file is wrong and too big

### ISSUE THREAD

**Issue by Maragues** [PhilJay/MPAndroidChart#882]
I was having conflicts after upgrading to v2.1.1. The error log listed issues with MPAndroidChart BuildConfig files, so I checked the .jar to see what could be wrong. The error message was similar to "parse exception buildconfig does not match path"

There were two obvious problems with the .jar file:

1. It includes the whole MPChartLib module, including the .iml files and the build/ directory, which was causing my problems.
2. It's 1.5MB vs the 600KB of the previous version. Plus, If I generate it in my fork, the .jar file is only 284KB and everyhing seems to work fine. I use *./gradlew clean assembleDefault* and just copy the generated .jar at *MPChartLib/build/intermediates/bundles/release/classes.jar*

**Comment by PhilJay** [comment]
Thank you for noticing this, I just uploaded a new jar, please try again!
