### ISSUE TITLE
Labels Orientation problem

### ISSUE THREAD

**Issue by nivasboy19** [PhilJay/MPAndroidChart#883]
When I use the smartphone in Portrait layout, dont show all of the columns of Labels.
Show only Tree Labels: Janeiro, Fevereiro e Março.
![screenshot_2015-07-21-13-38-00](https://cloud.githubusercontent.com/assets/13438227/8807256/9fc8181c-2fb1-11e5-9345-3143fedcdacb.png)

But I have six Labels: Janeiro, Fevereiro, Março, Abril, Maio e Junho.
And If I use the Landscape Layout, show all columns.
![screenshot_2015-07-21-13-38-16](https://cloud.githubusercontent.com/assets/13438227/8807257/9fd46a0e-2fb1-11e5-9194-7064f99bcc43.png)

Have a option to set, to show all columns?

My code is:
		ArrayList<BarEntry> entries = new ArrayList<BarEntry>();
		entries.add(new BarEntry(60, 0));
		entries.add(new BarEntry(50, 1));
		entries.add(new BarEntry(40, 2));
		entries.add(new BarEntry(30, 3));
		entries.add(new BarEntry(20, 4));
		entries.add(new BarEntry(10, 5));	
		
		ArrayList<String> labels = new ArrayList<String>();
		labels.add("Janeiro"); 
		labels.add("Fevereiro"); 
		labels.add("Março"); 
		labels.add("Abril"); 
		labels.add("Maio");
		labels.add("Junho");
		
	
		
		BarDataSet dataset = new BarDataSet(entries, "Empresa 01");
		dataset.setColor(Color.BLUE);
		
		ArrayList<BarEntry> entries2 = new ArrayList<BarEntry>();
		entries2.add(new BarEntry(10, 0));
		entries2.add(new BarEntry(20, 1));		
		entries2.add(new BarEntry(30, 2));
		entries2.add(new BarEntry(40, 3));
		entries2.add(new BarEntry(50, 4));				
		entries2.add(new BarEntry(60, 5));
				
		BarDataSet dataset2 = new BarDataSet(entries2, "Empresa 02");		
		dataset.setColor(Color.GREEN);

		ArrayList<BarDataSet> dataSets = new ArrayList<BarDataSet>();
		dataSets.add(dataset);
		dataSets.add(dataset2);
	
		BarData data = new BarData(labels, dataSets);
		
		BarChart chart = (BarChart) findViewById(R.id.chart);		
		chart.setData(data);
		chart.setDescription("Testes Graficos");

**Comment by PhilJay** [comment]
Try: `xAxis.setLabelsToSkip(0)``
This will force all labels to be drawn.

https://github.com/PhilJay/MPAndroidChart/wiki/XAxis-%28XLabels%29

**Comment by nivasboy19** [comment]
It is work.
Thank you..
