### ISSUE TITLE
overlaping values which near 0%

### ISSUE THREAD

**Issue by pranaypatel512** [PhilJay/MPAndroidChart#885]
![overlap_issue](https://cloud.githubusercontent.com/assets/10808436/8822620/60df5614-3084-11e5-8798-fee2bbe0e952.png)

when i added multiple values in xValues in pieChart. I got result like this.Please help to solve overlaping problem

**Comment by PhilJay** [comment]
There is not really much I can do about this. YOu will have to implement a solution yourself or avoid drawing values that are too small
