### ISSUE TITLE
When click on pie chart slice , the next slice change the color to white

### ISSUE THREAD

**Issue by Motazlubbad** [PhilJay/MPAndroidChart#886]
the problem is when click on pie chart slice , the next slice change the color to white.

like the pic.

http://im63.gulfup.com/ZiHnCH.jpg

code :

    mChart = (PieChart) layout.findViewById(R.id.pieChart);
        mChart.setDrawHoleEnabled(true);
        mChart.setHoleColorTransparent(true);
        mChart.setTransparentCircleColor(Color.WHITE);
        mChart.setHoleRadius(58f);
        mChart.setTransparentCircleRadius(61f);
        mChart.setDrawCenterText(true);
        mChart.setRotationAngle(0);
        mChart.setRotationEnabled(true);

**Comment by PhilJay** [comment]
Which library version are you using?
Which device did that issue occur on?
Which Android version does the device have?

**Comment by Motazlubbad** [comment]
I found the problem ,, I starting the y values from 1 , and the x values from 0

**Comment by PhilJay** [comment]
I don't understand. Can you show some code?

**Comment by PhilJay** [comment]
#824

**Comment by Motazlubbad** [comment]
Sorry for the delay 

the code with problem

    int index = 0;
        for (TopSales tmp : topSales) {
  index++;

            if (index == 10) break;
            TopSales dailySale = tmp;
   
                labels.add(tmp.Name);
                chartTitles.add(new ChartTitle(index, color[index], tmp.Name));
            
          
        }


after

    int index = 0;
        for (TopSales tmp : topSales) {
          
                labels.add(tmp.Name);
                chartTitles.add(new ChartTitle(index, color[index], tmp.Name));
            
            index++;

        }

**Comment by mocc99** [comment]
yeah,i get the same problem.

**Comment by mocc99** [comment]
Yeah! I get the same problem.when value=1,the PieChart of this value turn white. you can all values multiply by 2. All  the value become double,but Proportion the same
