### ISSUE TITLE
Custom XAxisRendererBarChart

### ISSUE THREAD

**Issue by fobios** [PhilJay/MPAndroidChart#887]
Hi PhilJay! I'm drawing barChart with your amazing lib and I need to set X-labels align left. If I ovveride and set my custom XAxisRenderer like 
public CustomXAxisRenderer(ViewPortHandler viewPortHandler, XAxis xAxis, Transformer trans) {
		super(viewPortHandler, xAxis, trans);
		mAxisLabelPaint.setColor(Color.RED);
		mAxisLabelPaint.setTextAlign(Align.LEFT);
	}

chart.setXAxisRenderer(new CustomXAxisRenderer(chart.getViewPortHandler(), xAxis, chart.getTransformer(null)));

it doesnt work. I guess I need to override XAxisRendererBarChart and set it to chart.

**Comment by fobios** [comment]
As I tried - it doesnt help. So is there any way to display labels exact under gridline, not under middle of bar ?

**Comment by PhilJay** [comment]
There sure is a way, you will just have to look deeper into the code and see why it is not working.
By default, left aligned x-axis labels are not possible.
