### ISSUE TITLE
"The DataSet class" wiki documentation error

### ISSUE THREAD

**Issue by HitOdessit** [PhilJay/MPAndroidChart#888]
On the wiki page: https://github.com/PhilJay/MPAndroidChart/wiki/The-DataSet-class
I found minor error - page currently says:
`public class DataSet extends LineDataSet { ...`
but actually it should be vise versa, e.g.:
`public class LineDataSet extends DataSet { ...`

PS: In fact, `LineDataSet` class is not extending `DataSet` class directly, but I think it's fine for simplicity reasons.

**Comment by PhilJay** [comment]
thx!
