### ISSUE TITLE
How to style the "no data set" text?

### ISSUE THREAD

**Issue by romangromov** [PhilJay/MPAndroidChart#89]
Hi Phil,

is there any way to customize look & feel of `No chart data available` text in the same way ? 

``` Java
.setTextColor(...);
.setTypeface(...);
.setTextSize(...);
```

Right now it is available in orange color only.
Thanks in advance!

**Comment by abeemukthees** [comment]
thank you :)

**Comment by marcochin** [comment]
Ty, kinda surprised there no direct way to modify it...

**Comment by yurisnm** [comment]
Do not forget do validate right after editing Paint.
