### ISSUE TITLE
Multi dataSet bar bug

### ISSUE THREAD

**Issue by AndroFlo** [PhilJay/MPAndroidChart#890]
Hello,

I have a barChart with two dataSets.
This is the array source: 

[{"name":"android","values":[{"name":1,"value":0},{"name":2,"value":0},{"name":3,"value":0},{"name":4,"value":0},{"name":5,"value":0},{"name":6,"value":50},{"name":7,"value":0},{"name":8,"value":0},{"name":9,"value":0},{"name":10,"value":0},{"name":11,"value":50}]},{"name":"ios","values":[{"name":1,"value":0},{"name":2,"value":0},{"name":3,"value":0},{"name":4,"value":0},{"name":5,"value":0},{"name":6,"value":0},{"name":7,"value":0},{"name":8,"value":0},{"name":9,"value":0},{"name":10,"value":0},{"name":11,"value":100}]}]

This is the good representation of the chart (web) :+1: 
![ss 2015-07-23 at 05 43 02](https://cloud.githubusercontent.com/assets/5589240/8854856/6b3c9ac0-3162-11e5-95d8-d3db62a44790.png)

And the bad with mapChart:
![screenshot_2015-07-23-17-43-34](https://cloud.githubusercontent.com/assets/5589240/8854863/757f325e-3162-11e5-9470-3134d990e7e7.png)

```Java
 ArrayList<BarEntry> yVals;
        ArrayList<String> xVals = new ArrayList<>();
        ArrayList<BarDataSet> dataSets = new ArrayList<>();

        for (int i = 0; i < listUserRententionObjects.size(); i++) {

            yVals = new ArrayList<>();
            xVals = new ArrayList<>();

            UserRetentionObject userRetentionObject = listUserRententionObjects.get(i);

            for (BarObject barObject : userRetentionObject.listBarObjects) {

                yVals.add(new BarEntry(barObject.value, i));
                xVals.add(barObject.name);
            }

            //String tempValue = xVals.get(xVals.size() - 1) + "+ ";//+getString(R.string.opens);

           // xVals.remove(xVals.size() - 1);
            //xVals.add(tempValue);

            BarDataSet barDataSet = new BarDataSet(yVals, listUserRententionObjects.get(i).os);
            barDataSet.setColor(getResources().getColor(ColorUtils.VORDIPLOM_EXTENDED[i]));

            dataSets.add(barDataSet);
        }

        BarData data = new BarData(xVals, dataSets);
        barChart.setData(data);
        data.setDrawValues(false);
```
Is it a bug or by code is wrong ?

Thank you

**Comment by PhilJay** [comment]
I think this is your issue: 
` yVals.add(new BarEntry(barObject.value, i));`

I needs to be incremented in each run through your `foreach` loop.

**Comment by AndroFlo** [comment]
Oh so stupid...

Thank you
