### ISSUE TITLE
setViewPortOffsets not working on load

### ISSUE THREAD

**Issue by FiCode** [PhilJay/MPAndroidChart#892]
If I set a custom offset, the chart loads with no offset.  After tapping on the chart, it will show the custom offset.  Once tapped & manually loaded, the offset will remain upon subsequent chart loads.

[Here is a video](https://drive.google.com/file/d/0B_7AQyfVuZ0rR0dFQkY5M2t1OWc/view?usp=sharing)

The last three lines of my definition are as follows, and I have tried sequencing them in different orders as well:

```java
chart_Reps.fitScreen ();
chart_Reps.setViewPortOffsets ( 50f, 0f, 25f, 50f );
chart_Reps.invalidate ();
```

This issue was previously mentioned, although I believe you may have misunderstood the issue based on the closing comment & the user's response after the issue was closed:

[HorizontalBar chart setViewPortOffsets(0f, 0f, 0f, 0f) not working. #594](https://github.com/PhilJay/MPAndroidChart/issues/594)

**Comment by PhilJay** [comment]
In the video it looks like you already set a custom offset and upon touching the custom offset is reset to default.

If you cannot show me more code there is not much more I can do.
Have you tried calling `invalidate()` on the chart after setting the offsets?

**Comment by hruslowkirill** [comment]
So did you fix the issue? I'm also struggling with it.
Custom offset is visible only after tapping on chart. Niether invalidate nor notifyDataSetChanged work.
Is it a bug of the library?

**Comment by Schabaani** [comment]
Did you solve it? I have same problem... Why my chart does not have **invalidate()**

**Comment by hruslowkirill** [comment]
Here you go
https://github.com/PhilJay/MPAndroidChart/issues/3441


2017-10-08 12:17 GMT+06:00 Amir Shabani <notifications@github.com>:
