### ISSUE TITLE
Gradient coloured area in the piechart 

### ISSUE THREAD

**Issue by knseir** [PhilJay/MPAndroidChart#893]
Hi, 

Is it possible to give a slice of a pie chart a gradient colour ? Example below

<img width="395" alt="screen shot 2015-07-23 at 9 33 31 pm" src="https://cloud.githubusercontent.com/assets/10488165/8865809/c093eb8e-3182-11e5-90cc-cd53f3ed192c.png">

Thank you

**Comment by PhilJay** [comment]
No, gradients are not supported by default
