### ISSUE TITLE
x-Label cut-off at bottom edge when Legand.setEnabled(false)

### ISSUE THREAD

**Issue by vkarthikeyan** [PhilJay/MPAndroidChart#894]
@PhilJay I have used the below code to hide the legand in Bar Chart (Column Chart).
      barChart.getLegend().setEnabled(false);       
      
By that way, the x-axis labels' bottom edge cut-off. For example, the letter y,g,q are cut-off at bottom.

I have  managed by doing like below.
Enabled the legand . barChart.getLegend().setEnabled(true).

//set the barDataset with the Legend string "." (dot).
BarDataSet barDataSet = new BarDataSet(barEntries, ".");

Then,
 barChart.getLegend().setPosition(Legend.LegendPosition.BELOW_CHART_CENTER);
 barChart.getLegend().setFormSize(0f);
 barChart.getLegend().setTextSize(1f);

**Comment by PhilJay** [comment]
Library version?

**Comment by vkarthikeyan** [comment]
@PhilJay Library version 2-1-0.
