### ISSUE TITLE
LineChart shadow problem

### ISSUE THREAD

**Issue by guorongqiang** [PhilJay/MPAndroidChart#895]
The desired effect
![a](https://cloud.githubusercontent.com/assets/8790809/8888077/da183f52-32d0-11e5-8130-e53bc3302968.png)
 Now the effect!
![b](https://cloud.githubusercontent.com/assets/8790809/8888080/e4259030-32d0-11e5-9158-aa0e0f952cce.png)
What should I do?

**Comment by PhilJay** [comment]
Use one `DataSet` to represent the red line in the first picture, and set it to filled.
Use a second `DataSet` to represent the blue line.
