### ISSUE TITLE
How to clear / reset chart zoom?

### ISSUE THREAD

**Issue by romangromov** [PhilJay/MPAndroidChart#90]
Hi Phil,

Probably I missed something, but
is there any way to clear chart `Zoom factor`?

Use case:
1. display chart with `mChart.setData(...)`
2. user zoom in with `pinch zoom gesture`
3. now, when displaying another one data with  `mChart.setData(...)`, user expects that new Chart will be displayed with default `zoom scale factor`

Looks like no way to achieve this behavior right now without re-initialization `mChart`.
Thanks in advance!

**Comment by anuinsonix** [comment]
I have tried FitScreen() but its doing nothing in my case instead of restoring the graph to initial zoom state.Please help

**Comment by RuchiteshPM** [comment]
I have a button which executes the lineChart.fitScreen() after clicking on it. But when I scroll and click on button immediately nothing happens. How can I provide more priority to fitScreen() method over scrolling effect ??

**Comment by rmirabelle** [comment]
Same as others - `fitScreen()` does not always work - sometimes working and sometimes not - even after calling `invalidate()`. Also tried `resetZoom()`

**Comment by ajay-bsoft** [comment]
`fitScreen()` for Barchart work to me 
```
chart.fitScreen()
chart.invalidate()
```
