### ISSUE TITLE
Memory Leak in Chart.java

### ISSUE THREAD

**Issue by VishalAdhau** [PhilJay/MPAndroidChart#900]
There is mDrawBitmap in Chart.java, in function onSizeChanged() it creates bitmap and assigned it to mDrawBitmap.
if (mDrawBitmap != null)
                mDrawBitmap.recycle();
mDrawBitmap = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_4444);

mDrawBitmap is not used anywhere in codebase, it allocates the huge memory depending on resolution causes OOM. 

Steps to reproduce it from MPChartSample
Add default condition in switch of getItem() in SimpleChartDemo.java like
default:
                f = PieChartFrag.newInstance();

Add return count 50 from getCount().
@Override
public int getCount() {
            return 50;
}

**Comment by PhilJay** [comment]
This is not a memory leak, it's simply a `Bitmap` that uses a lot of memory.
However, it's no longer needed and therefore I removed it.
