### ISSUE TITLE
how to rotated x-axis labels

### ISSUE THREAD

**Issue by wang9090980** [PhilJay/MPAndroidChart#901]
Hi:
   rotated x-axis labels  
![issue](https://cloud.githubusercontent.com/assets/6111077/8950738/12316be6-35f8-11e5-8588-7a0a203111b9.png)

**Comment by PhilJay** [comment]
currently not possible

**Comment by wang9090980** [comment]
Hi phiJay:
        you   are so handsome!
can I use ttf TypeFace resolve this problem?
