### ISSUE TITLE
How to set pie chart hole color with a thin slices?

### ISSUE THREAD

**Issue by donsaad** [PhilJay/MPAndroidChart#902]
Hi, I'm trying to make a pie chart like this
![pie hole](https://cloud.githubusercontent.com/assets/5939798/8954932/8c35afbc-35f1-11e5-9e75-a778bc7a1487.PNG)

but how do I get a small thin slice with a hole color that doesn't fill to the slices like this

![pie hole mine](https://cloud.githubusercontent.com/assets/5939798/8954971/d57fa452-35f1-11e5-9987-9df92ff0b476.PNG)

**Comment by PhilJay** [comment]
```java
pieChart.setTransparentCircleColor(Color.WHITE);
pieChart.setTransparentCircleAlpha(255); // fully opaque
```

**Comment by donsaad** [comment]
Thanks for answering but I use `pieChart.setHoleRadius(80f);` to get a thin slice which in turn makes the inner circle go bigger when I fill it with color `pieChart.setHoleColor(Color.CYAN);`

while `pieChart.setTransparentCircleAlpha(255);` cannot be resolved as a method! so what do i miss?
thanks again
