### ISSUE TITLE
wrong percent with large values entry  in piechart

### ISSUE THREAD

**Issue by kimnamcham** [PhilJay/MPAndroidChart#903]
When value of each entry too large, percent is wrong 
![large_number](https://cloud.githubusercontent.com/assets/6441065/8961094/721a87e6-363d-11e5-871f-f7368cd9641f.png)
result:
![screenshot_2015-07-29-21-58-28](https://cloud.githubusercontent.com/assets/6441065/8961109/90f00c18-363d-11e5-9718-ec3ebc62be7c.png)

**Comment by PhilJay** [comment]
Add some more digits to the `ValueFormatter` you are using.

**Comment by lukas1** [comment]
@PhilJay I don't understand what you mean by your answer. ValueFormatter if I understand it correctly is only changing labels of values displayed on chart. It does not affect the value itself (or it at least shouldn't, that would be very strange behaviour). The screenshot posted by OP shows, that the chart itself draws values incorrectly. It draws the values based on float values stored in PieEntry objects, if I understand it correctly, but it is obvious, that for some reason (a bug?) the chart acts as if only chart item had a nonzero value. I'm having the same problem, and I just don't see how ValueFormatter is involved. First of all I haven't even used ValueFormatter at all, but even when I try to use it (although expecting it to fail) it didn't change anything.
