### ISSUE TITLE
How to group by for xVals LineData in LineChart

### ISSUE THREAD

**Issue by droiddevgirl** [PhilJay/MPAndroidChart#905]
Hi i'm using MPAndroidChart for LineChart, i have weekly data but i want to display and group by monthly, how can i do that? I want to display it like this : 
<img width="356" alt="screen shot 2015-07-30 at 3 02 40 pm" src="https://cloud.githubusercontent.com/assets/1728863/8978429/67000c7a-36cc-11e5-823c-2cb153910545.png">

**Comment by PhilJay** [comment]
Just add an empty value "" to the x-values array 

"" "" "Jan" "" "" "" "" "Feb" "" "" 

Like this :-)
