### ISSUE TITLE
The "no data" message in LineChart never disappears if entries are added directly to DataSet's

### ISSUE THREAD

**Issue by EkaterinaT** [PhilJay/MPAndroidChart#907]
If we add new entries directly to DataSet like this:
  chart.getLineData().getDataSetByIndex(0).addEntry(entry);
and not by using 
  chart.getLineData().addEntry(entry);
than the new points are shown correctly in the chart but the "no data" message never disappears

**Comment by PhilJay** [comment]
in that case, call `notifyDataSetChanged()` on the chart after adding
