### ISSUE TITLE
how to draw a area between two Y axis values in a LineChart

### ISSUE THREAD

**Issue by wang9090980** [PhilJay/MPAndroidChart#911]
Hi :

how to draw a area between two Y axis values in a LineChart?

**Comment by PhilJay** [comment]
Check out the `FillFormatter` and `lineDataSet.setDrawFilled(true)`

**Comment by wang9090980** [comment]
thank you very much!

**Comment by shiguiyou** [comment]
@PhilJay  Hi,how to draw a area between parallel y axis？
