### ISSUE TITLE
"No chart data available"

### ISSUE THREAD

**Issue by kellyhosokawa** [PhilJay/MPAndroidChart#912]
I get the "No chart data available" error message even when my bar chart has data. I used invalidate().
![image](https://cloud.githubusercontent.com/assets/9992282/9021333/d63e8ed8-37f1-11e5-8758-803363f7f883.png)
![image](https://cloud.githubusercontent.com/assets/9992282/9021336/0fa45392-37f2-11e5-8319-da7b80bea84e.png)

**Comment by PhilJay** [comment]
Hmm I will have to look deeper into this. Which version of the lib are you using?

As a temproary workaround, simply call `setNoDataText("")` on the chart to get rid of the text.

**Comment by kellyhosokawa** [comment]
I'm using version 2.1.2.  Even when I call setNoDataText(""), it still shows up :/

![image](https://cloud.githubusercontent.com/assets/9992282/9022924/5b83aefc-383d-11e5-9be4-b970618d903f.png)
![image](https://cloud.githubusercontent.com/assets/9992282/9022934/8f65b102-383d-11e5-894f-924e96b7faa8.png)

**Comment by kellyhosokawa** [comment]
Also, if I call chart.setNoDataText("Test"), i get the same screen as shown above (no "Test" text; just "No chart data available.").

**Comment by PhilJay** [comment]
do you have overlapping layouts or activities? show your xml

**Comment by kellyhosokawa** [comment]
That was the problem! Thank you for all of your help!

**Comment by gawex** [comment]
> That was the problem! Thank you for all of your help!

Hi, kellyhosokawa

How you solve your error? I have same problem. Thx

**Comment by FannyDelaroque** [comment]
> > That was the problem! Thank you for all of your help!
> 
> Hi, kellyhosokawa
> 
> How you solve your error? I have same problem. Thx

Hello, did you find a solution?
