### ISSUE TITLE
ValueFormatter use SpannableStringBuilder

### ISSUE THREAD

**Issue by woutergoossens** [PhilJay/MPAndroidChart#917]
Hi,

I need to use 2 different fonts to show a value on the Y-Axis. 

In my project I use the SpannableStringBuilder to do this, but for the graph I use a subclass of the ValueFormatter I am not able to return the SpannableStringBuilder but only a String (in getFormattedValue). 

How can I make this work?

Thanks,

Wouter

**Comment by PhilJay** [comment]
I am afraid it will not be that easy since the valueformatter interface is tightly intergrated into the library. You will have to find a solution yourself to use spannablestringbuilder or go with string.
