### ISSUE TITLE
Can't set position of XAxis

### ISSUE THREAD

**Issue by Bavilo** [PhilJay/MPAndroidChart#918]
For some reason no property is working on the XAxis. I can not change the color, position, etc.

Here is how I get the XAxis:

XAxis xAxis = mChart.getXAxis();
xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
xAxis.setTextColor(Color.GREEN);
xAxis.setEnabled(true);

and this is the output:
![screenshot_20150802-201436](https://cloud.githubusercontent.com/assets/335020/9027362/2b938f48-3953-11e5-85e9-9eee77cab0c8.png)

As you can see, the Y Axis works fine...I can set the color, position etc.

What am I doing wrong regarding the X Axis?

**Comment by PhilJay** [comment]
I suppose somewhere in your code you are calling `xAxis.setEnabled(false)` since the axis is not showing.

**Comment by Bavilo** [comment]
xAxis.setEnabled is no where in my code...

http://pastebin.com/uVmWqDN4

 I don't know what the left labels are...I have not enabled this anywhere...
The xAxis just will not show...no matter what I do.
