### ISSUE TITLE
HorizontalBarChart wrong width 

### ISSUE THREAD

**Issue by Stefan2505** [PhilJay/MPAndroidChart#921]
Hi got an error when using horizontal bar chart. I use the following code to create one horizontal bar.
The red bar should fill the entire width.

    private void setProgress(HorizontalBarChart chart) {

        ArrayList<BarEntry> yVals1 = new ArrayList<>();
        ArrayList<String> xVals = new ArrayList<>();

        xVals.add(0, "Progress");
        yVals1.add(new BarEntry(1f, 0));

        BarDataSet set1 = new BarDataSet(yVals1, "ProgressBar");
        set1.setColors(new int[]{R.color.mainRed, R.color.mainOrange, R.color.mainBlue}, getActivity());

        ArrayList<BarDataSet> dataSets = new ArrayList<>();
        dataSets.add(set1);

        BarData data = new BarData(xVals, dataSets);

        data.setValueTextSize(12f);

        chart.setData(data);

        chart.setDescription(null);
        chart.animateY(1000);
        chart.getLegend().setEnabled(false);
        chart.setTouchEnabled(false);
        chart.setDrawGridBackground(false);

        chart.getAxisLeft().setEnabled(false);
        chart.getXAxis().setEnabled(false);

        YAxis yAxis = chart.getAxisRight();
        yAxis.setDrawGridLines(false);
        yAxis.setAxisMaxValue(1.0f);
        yAxis.setShowOnlyMinMax(true);
        yAxis.setTextSize(12f);

        chart.setDrawValueAboveBar(false);
        chart.setExtraRightOffset(15f);
        chart.setExtraLeftOffset(15f);
    }

<img width="767" alt="bug" src="https://cloud.githubusercontent.com/assets/11771173/9042176/3ebd6124-3a0d-11e5-883d-ba8d8c417a79.png">

**Comment by supsabhi** [comment]
yah same problem i am also facing and even for me background line is not visible in between only.
![screentosen](https://cloud.githubusercontent.com/assets/5425322/9201620/068e797a-405f-11e5-9ff5-ba89ede21744.png)

**Comment by troy21688** [comment]
How do you change the bar width?
