### ISSUE TITLE
hide labels on pie chart?

### ISSUE THREAD

**Issue by kavithagee** [PhilJay/MPAndroidChart#923]
Hi Phil,
Is there a way I can hide labels being displayed on the slices in a pie chart? I know I can hide the values but couldn't find how to hide labels.
Thanks!

**Comment by kavithagee** [comment]
Found it pieChart.setDrawSliceText(false).

**Comment by ivanove** [comment]
Hi dude,

I need to hide the values on the slices, how I can do that ? cause I need only the center value of pie chart

**Comment by ivanove** [comment]
I found it :) 

        PieData data = new PieData(dataSet);
        data.setDrawValues(false);// hide the values
