### ISSUE TITLE
PieChart and highlightValues(Highlight[] highs)

### ISSUE THREAD

**Issue by grishko188a** [PhilJay/MPAndroidChart#924]
Hi! First - thanks a lot for greate library!
But i found some bug.
To reproduce:
1) Do "onClick" programmatically using one of methods -  highlightValues(Highlight[] highs), highlightValue(int xIndex, int dataSetIndex) or void highlightTouch(Highlight high) (here everythings seems ok)
2) Next try to click manually on highlighted sector - and here you will find an issue - the click wouldn't work correct(sector not recognized as highlighted)

I found a solution:

    @Override
    public void highlightValues(Highlight[] highs) {
        // set the indices to highlight
        mIndicesToHightlight = highs;
        if (highs == null || highs.length == 0) {
            mChartTouchListener.setLastHighlighted(null);
        } else {
            mChartTouchListener.setLastHighlighted(highs[0]); <--- you forget to notify your touch listener
        }
        // redraw the chart
        invalidate();
    } 
And this why when you click on highlighted sector he not recognized - Your ChartTouchListener have know idea about programmatically highlited sectors.

I hope it will be useful =)

**Comment by tuliofmoura** [comment]
@grishko188a I had the same problem. Thanks for the answer.

@PhilJay Thanks for the library, it is awesome!
