### ISSUE TITLE
Dragging in LineChart is unresponsive when contained in ScrollView

### ISSUE THREAD

**Issue by ruthvik947** [PhilJay/MPAndroidChart#925]
I have a LineChart contained within a ScrollView. When the chart is long enough for it to be necessary for a user to scroll to see it in its entirety, the drag features become unresponsive. Drag gestures only register when I hold my finger down for a short period of time in the chart bounds and then drag. 

I have tried using the [requestDisallowInterceptTouchEvent](https://developer.android.com/intl/zh-TW/reference/android/view/ViewGroup.html#requestDisallowInterceptTouchEvent(boolean)/ "Title") method that should prevent the chart's parents from intercepting the touch events (but this doesn't solve anything). I've also tried directly passing MotionEvents registered by the ScrollView straight to the chart/translating drag gestures to translateY calls but this doesn't do what I thought it would.

Note: Zooming continues to work perfectly.

Also, this is not an issue when the graph fits in the original window or when it's placed in any view that is not a ScrollView. I have considered getting rid of the ScrollView but it's a pretty necessary feature in my project.

Any ideas on why this could be happening would be appreciated! And thank you for this great library!

**Comment by TeunKooijman** [comment]
For anyone who is also running in to this issue, I have found the following solution. Although Android is fiercely against placing scroll-able views within scroll-able views, sometimes you just find yourself in a situation where there is no other way.

You can extend the LineChart class, override the `onTouchEvent(MotionEvent event)` from the `BarLineChartBase` class, request the parent to no longer intercept touch events and consume the event.

The following code shows this solution in practice:

```
public class CustomLineChart extends LineChart
{
    public CustomLineChart(Context context)
    {   super(context);}

    public CustomLineChart(Context context, AttributeSet attrs)
    {   super(context, attrs);}

    public CustomLineChart(Context context, AttributeSet attrs, int defStyle)
    {   super(context, attrs, defStyle);}


    @Override
    public boolean onTouchEvent(MotionEvent event)
    {
        getParent().requestDisallowInterceptTouchEvent(true);
        super.onTouchEvent(event);
        return true;
    }
}
```

Hope this helps.
