### ISSUE TITLE
set PieChart hole color with selected slice color?

### ISSUE THREAD

**Issue by donsaad** [PhilJay/MPAndroidChart#928]
First thanks for such a great lib. 
So the PieChart takes only one dataSet and I want to set the hole color according to the selected slice color which i cant get, so is there any other way?
this is my listener
```java
mPieChart.setOnChartValueSelectedListener(new OnChartValueSelectedListener() { 
            @Override
            public void onValueSelected(Entry e, int dataSetIndex, Highlight h) {
                // TODO set hole color with the same as selected slice color

            }

            @Override
            public void onNothingSelected() {

            }
        });

**Comment by PhilJay** [comment]
It is possible to get the selected color, because the xIndex of the selected entry correspons to the index of the color in the colors array you set for the chart.

`int selectedColor = colorsArray.get(e.getXIndex())`

**Comment by Rahman-94** [comment]
e.getXIndex doesn't exist !
