### ISSUE TITLE
PieChart legend entries not displayed if too many

### ISSUE THREAD

**Issue by vk3057** [PhilJay/MPAndroidChart#93]
First of all its the best library of many I have tried.

I wanted to display values in legend> 5 (Inside Pie Chart). Currently all legend entries are displayed in one line and they do not wrap automatically to next line if there are many entries.

I have tried following legend positions: 
1. Below Center (Values gets skipped no wrapping done)
2. Right  (Values gets skipped no wrapping done)
3. Left (Values gets skipped no wrapping done)

Example of Legend Values Wrapping

 [] Party A            [] Party B           [] Party C       [] Party D     [] Party E   (Screen Size reached)
 [] Party F  and so on

Can you please let me know how can I achieve this in existing code.

**Comment by duduzeta** [comment]
Hey Phil,

I'm wraping the legend, but when there are more than one line of legend, the chart gets smaller and smaller. Is there a way to fix the chart size?

**Comment by sakaravinth** [comment]
If we  reusing colors for pie chart legends not coming . Is there any solution to get legends with same color.

**Comment by TusharSri** [comment]
Hi Phil,

I am setting some text inside pie chart, 
Problem is if text increases then it moves outside the pie slice.
Can we make ellipses true if text increases a particular length.

**Comment by anilthummar** [comment]
Hiii i want to set Text like below image in android.
I am used MPchart library, Please help me.

![capture](https://user-images.githubusercontent.com/7361686/38040769-d976942c-32cd-11e8-998a-1e2007ef92b0.PNG)

**Comment by subhasmiththapa** [comment]
I am using v 'com.github.PhilJay:MPAndroidChart:v2.2.4' and I am still facing the issue mentioned above of legends not being shown if too many. I tried checking the Chart.java class but couldn't find that function drawLegend(). Any help?
