### ISSUE TITLE
Request Progress bar

### ISSUE THREAD

**Issue by anaszakariyah** [PhilJay/MPAndroidChart#935]
Is it possible to get on more chart for progress bar?
The idea is using only two values which consist of target value and an actual value. It usually counted using percent in the bar and perhaps the label can tell the actual number too (ex. 30/50 <-- actual number/target number).

Ps: Great library. Thank you for this wonderful library :+1:

**Comment by PhilJay** [comment]
This might be what you are looking for: https://github.com/PhilJay/ValueBar
