### ISSUE TITLE
Allow highlight lines to be dashed

### ISSUE THREAD

**Issue by joshfriend** [PhilJay/MPAndroidChart#938]
iOS Charts has had this since "Initial Commit" danielgindi/ios-charts@19165ddacb2bbac9db0a541fd92f86b294147c11. I had planned on using that, but found it wasn't an option in Android. I might get around to adding this myself in the near future, but thought I should put it out there that the feature is missing.

**Comment by sirolei** [comment]
Trying to add the feature myself too but don't kown how to start...

**Comment by joshfriend** [comment]
@sirolei I was just going to try to copy the implementation from ios-charts. Since it's in Swift, it looks a lot more like Java than Objective C, so that should help somewhat. Plus, line graphs already support dashed lines, so I'd imagine the implementation would also be similar to that.

**Comment by sirolei** [comment]
@joshfriend I just found that we can get the HightLightPaint which is just the paint to draw the highlight lines. U can find the getter  function getPaintHighlight() in the DataRender class.

**Comment by sirolei** [comment]
I just got a way to make it. U can make a your own customized MyLineChartRender class by inheriting from the LineChartRender. Then U override the method drawHighLightLines. But I don't think this is the best way !.  Anyway here is how i make the highlight lines to be dashed ：

    MyLineChartRender render = new MyLineChartRender(chart, chart.getAnimator(), chart.getViewPortHandler());
        render.setmDashHighLightLinesEnabled(true);
        chart.setRenderer(render);
        chart.getRenderer().getPaintHighlight().setPathEffect(new DashPathEffect(new float[]{10f, 5f}, 0));

And MyLineChartRender code is below:

    public class MyLineChartRender extends LineChartRenderer {
    public MyLineChartRender(LineDataProvider chart, ChartAnimator animator, ViewPortHandler viewPortHandler) {
        super(chart, animator, viewPortHandler);
    }

    private boolean mDashHighLightLinesEnabled = false;

    @Override
    protected void drawHighlightLines(Canvas c, float[] pts, boolean horizontal, boolean vertical) {
        if (mDashHighLightLinesEnabled){
            Path path = new Path();
            if (vertical){
                path.moveTo(pts[0], pts[1]);
                path.lineTo(pts[2], pts[3]);
                c.drawPath(path, mHighlightPaint);
                Log.e("siro", "draw horizontal highline");
            }

            if (horizontal){
                path.moveTo(pts[4], pts[5]);
                path.lineTo(pts[6], pts[7]);
                c.drawPath(path, mHighlightPaint);
                Log.e("siro", "draw vertical highline ps is " + pts[4] +", " + pts[5] + ", " + pts[6] + ", " + pts[7] );
            }
        }else {
            super.drawHighlightLines(c, pts, horizontal, vertical);

        }
    }

    public boolean ismDashHighLightLinesEnabled() {
        return mDashHighLightLinesEnabled;
    }

    public void setmDashHighLightLinesEnabled(boolean mDashHighLightLinesEnabled) {
        this.mDashHighLightLinesEnabled = mDashHighLightLinesEnabled;
    }
}

**Comment by joshfriend** [comment]
@PhilJay has this feature been added? I glanced at the recent commits but didn't see anything related to this issue.

**Comment by PhilJay** [comment]
Yes, I am going to push in 5 min :-)

**Comment by joshfriend** [comment]
Oh, Great! Sorry, I didn't mean to rush you...
