### ISSUE TITLE
Hi PhilJay,can this library support this effect

### ISSUE THREAD

**Issue by wusuowei1991** [PhilJay/MPAndroidChart#939]
![w5t49s my 9e63e7 bgzw](https://cloud.githubusercontent.com/assets/12437849/9215324/6cd715a8-40db-11e5-94fd-3332f523333d.jpg)

**Comment by hardikamal** [comment]
@wusuowei1991 any solution found to this???

**Comment by PhilJay** [comment]
currently not supported
