### ISSUE TITLE
Making Entry class Parcelable

### ISSUE THREAD

**Issue by hfahmy** [PhilJay/MPAndroidChart#941]
Would it be possible to make the Entry class that hold the data Parcelable? This would greatly help in managing data in the android activity lifecycle.

I'm using your library in one of my major projects, and currently have to use a workaround to store the data since Entry class is not Parcelable, and oh boy, it looks horrible :(

**Comment by hfahmy** [comment]
Btw, here is a great library that instantly does parceling for you by "adding" code to your classes. Check it out.

https://github.com/mg6maciej/hrisey

**Comment by frakc** [comment]
Also in android studio 1.3 parceble generation is added from box. just generate missing methods and statments 2 times
