### ISSUE TITLE
MarkerView doesn't shown in HorizontalBarChart

### ISSUE THREAD

**Issue by HitOdessit** [PhilJay/MPAndroidChart#944]
I'm facing an issue with custom `MarkerView` - markers simply won't shown when using `HorizontalBarChart`. 
My implementation of custom `MarkerView` is correct, because if I simply change `HorizontalBarChart` to `BarChart` instance, everything works as expected. Once I return `HorizontalBarChart` back, no markers are displayed.

According to this question: http://stackoverflow.com/questions/30319466/markerview-in-mpandroidchart same issue valid for `PieChart` also.

I'm using v2.1.3 of MPAndroidChart library

**Comment by Im-PJ** [comment]
Same issue here...
@HitOdessit Did you find out any solution?

**Comment by HitOdessit** [comment]
@Im-PJ Unfortunately, no. I think it's just not implemented for that case.

**Comment by PhilJay** [comment]
Now supported.

**Comment by PhilJay** [comment]
75be29ef038f960b686430ab8a75dff89575c6ac
