### ISSUE TITLE
Too many callbacks triggered when interacting with map

### ISSUE THREAD

**Issue by xizzhu** [PhilJay/MPAndroidChart#949]
When I add a OnChartGestureListener to the chart, and it looks like there're too many callbacks triggered. Is it possible to reduce the number of callbacks triggered, or provide some kind of "onChartScaleFinished" or "onChartTranslateFinished" callbacks? Thanks.

**Comment by PhilJay** [comment]
The `OnChartGestureListener` now provides a method called `onChartGestureEnd(MotionEvent me, ChartTouchListener.ChartGesture lastPerformedGesture)`. This method allows to react on gesture-end and provides the last performed gesture as a enum.
