### ISSUE TITLE
Plot bands

### ISSUE THREAD

**Issue by tijee** [PhilJay/MPAndroidChart#950]
Hi, is there a way to draw plot bands with MPAndroidChart? Something like that: 
![plot_bands_and_plot_lines](https://cloud.githubusercontent.com/assets/1949486/9247911/6669b554-41b7-11e5-8751-0c72b8f60dc3.png)

Thanks

**Comment by PhilJay** [comment]
Currently not supported

**Comment by pradeep-orbi** [comment]
Is this supported now ?

**Comment by pradeep-orbi** [comment]
> Currently not supported

@PhilJay Is this supported now ?
