### ISSUE TITLE
Updating version from 2.1.0 to 2.1.3 caused some problems

### ISSUE THREAD

**Issue by Damore** [PhilJay/MPAndroidChart#956]
Hello,

I need to get the 2.1.3 version because one of the bugs corrected are the subtitles below a Linechart graph. However, after the update my graph is not having the same behavior as when it was with 2.1.0

Below is the image with 2.1.0 

![graph_2_1_0](https://cloud.githubusercontent.com/assets/4624254/9276411/2cfed24a-427a-11e5-8971-dacbca04e0e6.jpeg)

And with the 2.1.3

![graph_2_1_3](https://cloud.githubusercontent.com/assets/4624254/9276443/630048e2-427a-11e5-91b0-5fdce35fc0ae.jpg)

Here is the XML
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:tools="http://schemas.android.com/tools"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:id="@+id/graph">
      
      
      <LinearLayout
        android:id="@+id/loading"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:layout_margin="5dip"
        android:gravity="center"
        android:orientation="vertical">
        

        <ProgressBar
            android:layout_width="32dip"
            android:layout_height="32dip"
            android:layout_marginRight="5dip" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/label_carregando" />
    </LinearLayout>
                
    <ScrollView
    android:layout_width="match_parent"
    android:layout_height="wrap_content" >

    <com.github.mikephil.charting.charts.LineChart
        android:id="@+id/charts"
            android:layout_width="match_parent"
            android:layout_height="450dp"
 /> 
        </ScrollView>
 
</LinearLayout>
```

**Comment by danielgindi** [comment]
This looks like a layout problem, not a chart problem. Your view turns out a lot smaller, and the text is overlaid by another piece of text. So you need to investigate your layout

**Comment by Damore** [comment]
But if it is a layout problem, why on the version 2.1.0 the graph works fine and on the 2.1.3 (with the same layout) the graph shrinks?

**Comment by davidbin** [comment]
+1 , I have the same issue also after updating from 2.1.0 to 2.1.3

**Comment by danielgindi** [comment]
@PhilJay do you recall any changes in onMeasure or the likes?

**Comment by PhilJay** [comment]
Yes I made some changes but they should only give the chart default width and height of 50 or something when wrap_content is used as a parameter for height or width.

**Comment by Damore** [comment]
@PhilJay When you say default width, you mean the value of "wrap_content"? So, to workaround this problem, I should use:
width = wrap_content
height = 50

**Comment by PhilJay** [comment]
try getting your chart out of the scrollview

**Comment by Damore** [comment]
@PhilJay I removed the scrollview and here is the result:

![graph_2_1_3](https://cloud.githubusercontent.com/assets/4624254/9440338/b9a9fed2-4a44-11e5-9de4-185ea59c2e29.jpeg)

**Comment by Damore** [comment]
Any clues? @PhilJay @danielgindi

**Comment by Damore** [comment]
@PhilJay @danielgindi Do you guys have any feedback? It has being a while since our last talk.

**Comment by PhilJay** [comment]
You obviously have some kind of issue with your layout.

For the chart to display like in your screenshot, it needs the height property `wrap_content`. If `match_parent` or a static height are set, this cannot occur.

**Comment by Damore** [comment]
@PhilJay I changed the height to "match_parent". But the error was the same. Also, I removed the ScrollView and the error persisted If you want to, I can put the project on the github and you can see the error happening. Sorry for making this issue a real boring one, but I just want to update the version of your project, because I think it is an awesome work! You guys did the best and I want to keep using it!

**Comment by PhilJay** [comment]
Okay, could you try your layout like this (just copy paste it):

```xml
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="vertical"
                android:id="@+id/graph">
    <LinearLayout
        android:id="@+id/loading"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:layout_margin="5dip"
        android:gravity="center"
        android:orientation="vertical">
        <ProgressBar
            android:layout_width="32dip"
            android:layout_height="32dip"
            android:layout_marginRight="5dip" />
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/label_carregando" />
    </LinearLayout>
    <com.github.mikephil.charting.charts.LineChart
        android:id="@+id/charts"
            android:layout_width="match_parent"
            android:layout_height="450dp" />
</LinearLayout>

```

**Comment by Damore** [comment]
Thanks for your quick reply @PhilJay. Here is the xml that you said to me copy and paste (just changed the name of the ids that I use on my code)

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/graph_cliente"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">


    <LinearLayout
        android:id="@+id/loading_get_relatorio_cliente"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:layout_margin="5dip"
        android:orientation="vertical">

        <ProgressBar
            android:layout_width="32dip"
            android:layout_height="32dip"

            android:layout_marginRight="5dip" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/label_carregando" />
    </LinearLayout>

    <com.github.mikephil.charting.charts.LineChart
        android:id="@+id/charts"
        android:layout_width="match_parent"
        android:layout_height="450dp" />
</LinearLayout>
```

And here is the image:
![Uploading Screenshot_2015-09-04.png…]()

**Comment by Damore** [comment]
@PhilJay It has been a while that you don't reply. Did you find anything that could explain this error?
