### ISSUE TITLE
how to update bar chart with new values

### ISSUE THREAD

**Issue by janardhan1212** [PhilJay/MPAndroidChart#960]
please provide a sample code to update values in bar chart

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Dynamic-&-Realtime-Data

**Comment by robgarai** [comment]
Hi, My pie chart use SharedPrefferences for showing the  
     mChart.setDescription(String.format("Goal %.2f km", Goal ));
value .
I am setting this Goal value in different activity, so I am storing this Goal value inside SharedPrefferences. But when I am returning from settings activity into dashboard where PieChart is displayed then the PieChart always shows old version of Goal value. It is never changed. But after restarting the app the goal instatly shows correct value. It seems to me that
      mChart.notifyDataSetChanged();
     mChart.invalidate(); 
refresh methods won't works. 

Please, how to properly refresh my dashboard activity for refreshing the piechart data?

**Comment by manzoorsk** [comment]
how to refresh pie chart values (json data) please help
