### ISSUE TITLE
Legend ordering after removing/re-adding dataset

### ISSUE THREAD

**Issue by zqillini4** [PhilJay/MPAndroidChart#961]
I have the following code to add or remove data sets from my line chart using the onCheckedChanged listener:
        set1Checkbox.setOnCheckedChangeListener(new OnCheckedChangeListener() {
        	@Override
        	public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
        		if (buttonView.isChecked()) {
        			allDataSets.add(set1Trend);
        			mChart.notifyDataSetChanged();
        			mChart.invalidate();
        		}
        		else {
        			allDataSets.remove(set1Trend);
        			mChart.notifyDataSetChanged();
        			mChart.invalidate();
        		}
        	}
        });

It is working great, however when I re-add set1, it puts at the end of the legend.  I was wondering if there was any way to retain its position within the legend after the data refresh?  See attached images for clarification:

![graph_before_removal_and_re-add](https://cloud.githubusercontent.com/assets/13842729/9320186/8d60aee8-451c-11e5-9140-31a00ae6082f.JPG)

![graph_after_set1_removal](https://cloud.githubusercontent.com/assets/13842729/9320192/952da9dc-451c-11e5-9186-69ae8f2ba8a7.JPG)

![graph_after_set1_re-added](https://cloud.githubusercontent.com/assets/13842729/9320196/997439fc-451c-11e5-923f-c048e573bb77.JPG)

**Comment by frakc** [comment]
try to remove all sets and then set all of selected
