### ISSUE TITLE
Hiding everything except line chart (labels, numbers, borders, etc.)

### ISSUE THREAD

**Issue by umuplus** [PhilJay/MPAndroidChart#965]
Is it possible to hide everything except the line chart itself to achieve something like that:

![line-chart](https://cloud.githubusercontent.com/assets/681115/9378204/447fd8f8-4728-11e5-8e03-204552154975.png)

There are some methods to limit visible X and Y values and labels but I couldn't go further.

**Comment by thmp** [comment]
Calling all of these, you are left with only the line chart

         // Draw chart
        LineChart chart = (LineChart) findViewById(...); // fill in your chart

        // Prepare data
        ArrayList<Entry> values = new ArrayList<>();
        values.add(...)

        LineDataSet dataSet = new LineDataSet(values, "Label");

        dataSet.setDrawValues(false);
        dataSet.setLineWidth(2f);
        dataSet.setDrawCubic(true);

        dataSet.setDrawCircles(false);

        ArrayList<LineDataSet> dataSets = new ArrayList<>();
        dataSets.add(dataSet);

        ArrayList<String> xValues = new ArrayList<>();
        xValues.add(...);

        LineData data = new LineData(xValues, dataSets);

        chart.setData(data);

        // style chart
        chart.setBackgroundColor(getResources().getColor(...)); // use your bg color
        chart.setDescription(" ");
        chart.setDrawGridBackground(false);
        chart.setDrawBorders(false);

        chart.setAutoScaleMinMaxEnabled(true);

        // remove axis
        YAxis leftAxis = chart.getAxisLeft();
        leftAxis.setEnabled(false);
        YAxis rightAxis = chart.getAxisRight();
        rightAxis.setEnabled(false);

        XAxis xAxis = chart.getXAxis();
        xAxis.setEnabled(false);

        // hide legend
        Legend legend = chart.getLegend();
        legend.setEnabled(false);

        chart.invalidate();

**Comment by Winghin2517** [comment]
With the latest build, to get this effect, you would have to use these settings:

`        mChart.getAxisLeft().setDrawLabels(false);
        mChart.getAxisRight().setDrawLabels(false);
        mChart.getXAxis().setDrawLabels(false);
      // https://stackoverflow.com/questions/31263097/mpandroidchart-hide-background-grid
        mChart.getAxisLeft().setDrawGridLines(false);
        mChart.getXAxis().setDrawGridLines(false);
        mChart.getAxisRight().setDrawGridLines(false);
        
        XAxis xAxis = mChart.getXAxis();
        xAxis.setEnabled(false);

        YAxis yAxis = mChart.getAxisLeft();
        yAxis.setEnabled(false);

        YAxis yAxis2 = mChart.getAxisRight();
        yAxis2.setEnabled(false);

        mChart.setDrawBorders(false);
        mChart.setDrawGridBackground(false);

        mChart.getLegend().setEnabled(false);
        // no description text
        mChart.getDescription().setEnabled(false);

        // enable touch gestures
        mChart.setTouchEnabled(true);

        // enable scaling and dragging
        mChart.setDragEnabled(false);
        mChart.setScaleEnabled(false);
        // mChart.setScaleXEnabled(true);
        // mChart.setScaleYEnabled(true);

        // if disabled, scaling can be done on x- and y-axis separately
        mChart.setPinchZoom(false);
        mChart.setAutoScaleMinMaxEnabled(true);
        // hide legend
        Legend legend = mChart.getLegend();
        legend.setEnabled(false);`

**Comment by nicconicco** [comment]
You save my weekend! thanks!

**Comment by forceporquillo** [comment]
It works like charm! Thanks!

**Comment by Amrjyniat** [comment]
how to hide the axis (Y,X) when clicking on the chart?
