### ISSUE TITLE
How to to draw entry at the horizontal center of line chart view

### ISSUE THREAD

**Issue by tonypham1693** [PhilJay/MPAndroidChart#967]
HI PhilJay! I get a problem like this: let's assume that I have only one xVal label on bottom and I wanna show it and all of its values at the horizontal center of line chart view so how can I do that?
Thanks a lot!

**Comment by gajicm93** [comment]
Add total od 3 xValues to the chart, where the real value would be the middle one, while the other two would be "dummy" values, which you would make invisible by making their xVal string = "", and making their Y values 0, or the same as the real value, and make the line to be the same color as background so it becomes almost invisible.. Or completely disable the line if possible, or set trasnparent color or something..

**Comment by tonypham1693** [comment]
yeah! it works, thanks a lot!
