### ISSUE TITLE
Stacked BarChart with small value

### ISSUE THREAD

**Issue by AngelOfMors** [PhilJay/MPAndroidChart#968]
If the data set values are found to be zero or small, the output value overrides the lower value of the other data.
![screenshot_2015-08-20-16-48-46](https://cloud.githubusercontent.com/assets/13793037/9381713/a9225bcc-475b-11e5-9c73-c14bd990051c.png)

**Comment by PhilJay** [comment]
Yes, that is correct. Unfortunately there is no default mechanism to avoid this, you will have to modify the library to e.g. prevent some values from being drawn.
