### ISSUE TITLE
CombinedChart - Reduce y-axis of individual data sets

### ISSUE THREAD

**Issue by gray419** [PhilJay/MPAndroidChart#969]
Using a combined chart to display candles and bar charts pictured below.

My question is how can I reduce the scale of the y-axis on the BarChart data so that the overlap isn't as large as it currently is.

Thanks for the help!

<img width="1026" alt="screen shot 2015-08-20 at 10 33 05 am" src="https://cloud.githubusercontent.com/assets/3689237/9385932/08270dd2-4727-11e5-9310-fc4134182386.png">

**Comment by gray419** [comment]
Finally figured a way to do this.

Using Combined Chart set bar data to an AxisDependency, Left in this case;
```java
        BarDataSet volumeSet = new BarDataSet(yVolumeVals, "Volume Data");
        volumeSet.setDrawValues(false);
        volumeSet.setAxisDependency(YAxis.AxisDependency.LEFT);
```

Then after getting all the data, calculate largest Y value and set Left Axis Max value to N times that for desired height. In this case 3x

```java
        CombinedData combinedData = new CombinedData(xVals);
        combinedData.setData(priceData);
        combinedData.setData(volumeData);
        candleChart.getAxisLeft().setAxisMaxValue(volumeData.getYMax() * 3);
        candleChart.setData(combinedData);
        candleChart.invalidate();
``` 

Thanks again @PhilJay for the awesome library!

**Comment by minggo** [comment]
> My question is how can I reduce the scale of the y-axis on the BarChart data so that the overlap isn't as large as it currently is.

Did you mean BarChat and CandleChart overlap?

**Comment by minggo** [comment]
@gray419
@PhilJay 
 Can BarChart and CandleChart depend on different axis? And they have different unit. If can, then could you tell me how to? Thanks.

**Comment by Saloed123** [comment]
@minggo 
yes, you can set bardataset and candledataset on another axis
```
 public static void setBarDataSet(BarDataSet dataSet) {
        dataSet.setColor(android.support.design.R.color.design_fab_shadow_end_color);
        dataSet.setDrawValues(false);
        dataSet.setAxisDependency(YAxis.AxisDependency.LEFT);
        dataSet.setHighlightEnabled(false);
    }
    //----------------------------------------------------------------------------------------------

    public static void setCandleDataSet(CandleDataSet dataSet) {
        dataSet.setAxisDependency(YAxis.AxisDependency.RIGHT);
        dataSet.setShadowColorSameAsCandle(true);
        dataSet.setBarSpace(0.1f);
        dataSet.setDrawValues(false);

        dataSet.setIncreasingColor(Color.GREEN);
        dataSet.setIncreasingPaintStyle(Paint.Style.FILL);

        dataSet.setDecreasingColor(Color.RED);
        dataSet.setDecreasingPaintStyle(Paint.Style.FILL);

        dataSet.setNeutralColor(Color.BLACK);
    }
```
