### ISSUE TITLE
Line Chart X Axis Top space (Inset for graph padding)

### ISSUE THREAD

**Issue by bhavin-chauhan** [PhilJay/MPAndroidChart#971]
First of all Thank you very much for great library. I have setup this library in one sample project. I am facing some issue,I need your help. 
I have write these lines code in my sample app.
// X Axis
XAxis xAxis = lineChart.getXAxis();
xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
xAxis.setDrawGridLines(false);
xAxis.setTypeface(proximaNovaSemibold);
xAxis.setAxisLineColor(Color.TRANSPARENT);
xAxis.setSpaceBetweenLabels(0);

// Y Axis
YAxis yRightAxis = lineChart.getAxisRight();
yRightAxis .setDrawGridLines(false);
yRightAxis .setDrawAxisLine(false);
yRightAxis .setDrawLabels(false);

YAxis yLeftAxis = lineChart.getAxisLeft();
yLeftAxis.setPosition(YAxis.YAxisLabelPosition.OUTSIDE_CHART);
yLeftAxis.setGridColor(getActivity().getResources().getColor(R.color.graph_line_chart_grid_line_color));
yLeftAxis.setAxisLineColor(Color.TRANSPARENT);
yLeftAxis.setGridLineWidth(1.5f);

// LineDataSet 

LineDataSet set1 = new LineDataSet(yVals, "Test");
set1.setColor(getActivity().getResources().getColor(R.color.graph_line_chart_progress_color));
set1.setCircleColor(getActivity().getResources().getColor(R.color.graph_line_chart_progress_color));
set1.setLineWidth(4f);
set1.setCircleSize(5f);
set1.setDrawCircleHole(true);
set1.setCircleColorHole(getActivity().getResources().getColor(R.color.graph_line_chart_circle_color));
set1.setValueTextSize(9f);
set1.setValueTypeface(proximaNovaSemibold);
set1.setColor(getActivity().getResources().getColor(R.color.graph_line_chart_progress_color));

Facing problems,
1) Last " yLeftAxis " line couldn't draw.
2) when value is "0" LineDataSet line size is became thin (reduce size than assign size)
  
![capture](https://cloud.githubusercontent.com/assets/6767645/9404008/628d871e-4809-11e5-9369-5e04c5666805.PNG)

Here Y axis 24 line is not visible. and X aixs J F M set is thinner than others. 
Give me any suggestions.
Thanks!!

**Comment by bhavin-chauhan** [comment]
@Philipp Jahoda  I have tried to set offset in graph, x Axis, Right y Axis, Left y Axis.
But it couldn't help me. Let me know is there any property which will set padding or inset in side graph. Thanks!!!!

**Comment by PhilJay** [comment]
Looks like you have two datasets with the same color (yellow) overlapping.

**Comment by bhavin-chauhan** [comment]
@PhilJay I have only one dataset. and this is not overlapping. When line is plotting on "0" value  it became thinner.  I have set it with  "set1.setLineWidth(4f);" you can check when there are values greater than "0" then plotting became "4F" but on "0" it will reduce the size.Is there any property which will take extra bottom space for  first value ("0") I want extra space(May be Inset). Please let me suggest any solution. 
Thanks.
