### ISSUE TITLE
Is it possible to set custom shapes as LineChart data points?

### ISSUE THREAD

**Issue by gajicm93** [PhilJay/MPAndroidChart#972]
I'm required by design to set a custom shape as a data point in Line Chart? Is it possible, and if not, it should be implemented.

**Comment by sathishkumars92** [comment]
Hi I need this same answer ,anyone make it soon whether its possible or not

**Comment by gajicm93** [comment]
Just to share my solution, if anybody needs this ASAP. I did this by modifying the library itself, but the solution is actually extremely simple as long as you're not bothered by including the library sources into your project.

Data points are drawn in the protected void drawCircles(Canvas c) method, in the LineChartRenderer class, and X and Y coordinates for drawing are calculated for you, so just replace the c.drawCircle commands at the end of the method by drawing anything else you want, while using the same X and Y coordinates, and you're done.

**Comment by PhilJay** [comment]
Not yet possible, but I am considering to add this.

**Comment by sathishkumars92** [comment]
When will the next version will be released ??

**Comment by revg75** [comment]
Yes this would be great. I am also in need of custom graphics to be used as a data points. I require it to allow me to display a different custom graphic for each data point depending on certain factors. I have done like gajicm93 suggests, but would be nice to have it built right in there :)

**Comment by davidhowe** [comment]
Agreed, also a feature that I desperately needed

**Comment by dhruvpatidar359** [comment]
is this resolved or not ?
