### ISSUE TITLE
MPAndroidchart set mark decoration on chart

### ISSUE THREAD

**Issue by neruja** [PhilJay/MPAndroidChart#973]
How can i set an icon on the graph, connected to a data point, The icon should follow the data entry point. I tried using a customized marker, but i can only add one type of MarkerView.

I want to set different icon markers on the graph, to specify different events happening.

Is there a way to specify or set different markers for highlighting? Or is it not a good way to set more permanent "decoration" icons on the chart.

**Comment by PhilJay** [comment]
What you can do is create just one marker-view, and then, depending on which entry is selected display a different icon in it.
