### ISSUE TITLE
Min/max values for YAxis

### ISSUE THREAD

**Issue by doom369** [PhilJay/MPAndroidChart#975]
Hello,

is there a way to force YAxis to start from min value of graph data without overriding it? For instance I have values in range 100-200. And I would like to see label starting from 100 ending with 200 and with intermediate labels.

**Comment by gajicm93** [comment]
chart.getAxisLeft().setAxisMaxValue(200f);
			chart.getAxisLeft().setAxisMinValue(100f);

**Comment by doom369** [comment]
Well, I mean without manual code for finding min and max. Via some property like setShowOnlyMinMax. Something like 

```
setStartWithMin(true);
setEndWithMax(true);
```

I tried 

```
        setSpaceBottom(0);
        setSpaceTop(0);
```
But it  still doesn't work as expected.

**Comment by vonox7** [comment]
For future reference:

    startAtZero(true)

must be called too. Working example:

    chart.getAxisRight().setAxisMinValue(chartDataSet.getYMin())
    chart.getAxisRight().setAxisMaxValue(chartDataSet.getYMax())
    chart.getAxisRight().setStartAtZero(false)

**Comment by Moiragod** [comment]
I think you need to calculate the Label Count for y-axis. As the default value of label count is 6, if you set the max y-axis is 200, then chart will only show 180 in the top of y-axis.
