### ISSUE TITLE
Display months on the bottom of the chart

### ISSUE THREAD

**Issue by darkovski88** [PhilJay/MPAndroidChart#978]
Hello,
I want to display the monthnames on the bottom of the chart. I saw the images that this is possible but can anyone tell me how can i do that?

here is the code i have:

<code>
mChart.setDescription("");
        mChart.setNoDataTextDescription("You need to provide data for the chart.");

        mChart.setDragDecelerationFrictionCoef(0.9f);

        mChart.setDrawGridBackground(false);
        mChart.setHighlightPerDragEnabled(false);
        mChart.setBackgroundColor(Color.WHITE);

        // add data
        Log.d(TAG, " bills size " + bills.getBills().size() + " totals size " + billTotals.size());
        setData(bills.getBills().size());
        // get the legend (only possible after setting data)
        Legend l = mChart.getLegend();
        l.setForm(Legend.LegendForm.CIRCLE);
        l.setTextSize(11f);
//        l.setExtra(ColorTemplate.VORDIPLOM_COLORS, new String[]{"may", "jun", "jul", "aug", "sep"});
        l.setTextColor(Color.BLACK);

        List<String> dateVals = new ArrayList<>();
        for (BillTotal bill : billTotals) {
            Log.d(TAG, "date " + bill.getDate());
            //HERE ARE THE DATE VALUES - LONGS FOR THE MONTH 
            dateVals.add(bill.getDate() + "");
        }

        Typeface gotham = Typeface.createFromAsset(
                getActivity().getAssets(),
                "fonts/gotham_bold.ttf");

        XAxis xAxis = mChart.getXAxis();
//        xAxis.setTypeface(tf);
        xAxis.setTextSize(13f);
        xAxis.setValues(dateVals);
        xAxis.setTypeface(gotham);
        xAxis.setTextColor(getResources().getColor(R.color.toolbar_text_blue));
        xAxis.enableGridDashedLine(10f, 10f, 0f);
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setDrawGridLines(true);
        xAxis.setDrawAxisLine(false);

        YAxis leftAxis = mChart.getAxisLeft();
        leftAxis.setAxisMaxValue(55f);
        leftAxis.setAxisMinValue(0f);
        leftAxis.setTypeface(gotham);
        leftAxis.enableGridDashedLine(10f, 10f, 0f);
        leftAxis.setTextSize(13f);
        leftAxis.setValueFormatter(new MyValueFormatter());
        leftAxis.setTextColor(getResources().getColor(R.color.toolbar_text_blue));
        leftAxis.setDrawGridLines(true);

        YAxis rightAxis = mChart.getAxisRight();
        rightAxis.setTextColor(Color.WHITE);
        rightAxis.setStartAtZero(false);
        rightAxis.setDrawGridLines(false);
        rightAxis.setAxisMaxValue(50);
        rightAxis.setAxisMinValue(0f);
</code>

**Comment by gajicm93** [comment]
chart.getXAxis().setPosition(XAxis.XAxisPosition.BOTTOM);

**Comment by darkovski88** [comment]
@gajicm93 and how can I set the values? Any idea?

**Comment by gajicm93** [comment]
@darkovski88 How are months represented in your data model?

This is how you add a string value to the X axis:
lineData.addXValue(formatter.format(date));

Now all you have to decide is how are you going to get "month name string" from your data model. For example, this is how you get month name string from the Date class:

Date date = new Date();
System.out.println(new SimpleDateFormat("MMM").format(date));
