### ISSUE TITLE
Specific colors for specific xVals on Pie Chart

### ISSUE THREAD

**Issue by vanshg** [PhilJay/MPAndroidChart#980]
I am unable to figure out how to do this. I don't want the colors to be randomly assigned. I only have 1 data set, with 3 values in it. I want each value to have a specific color each time. How can it be done?

**Comment by azizimusa** [comment]
+1 for same question

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/wiki/Setting-Colors
