### ISSUE TITLE
StackedBarChart setDrawValuesForWholeStack

### ISSUE THREAD

**Issue by aint** [PhilJay/MPAndroidChart#985]
Hi There!
I have been updated from 2.1.0 to 2.1.3 and noticeв that the ```setDrawValuesForWholeStack()``` method not available now. Is it removed or renamed? 
Thanks in advantage!

**Comment by andr0man** [comment]
same problem here..

**Comment by Im-PJ** [comment]
same here...How to sum up the stacked values now.
@aint did you find any solution?

**Comment by aint** [comment]
Unfortunately not.

**Comment by PhilJay** [comment]
You can use the `ValueFormatter` to do that. It's not as easy but overall allows much more flexibility.
I just created a default formatter specifically for stacked values.

https://github.com/PhilJay/MPAndroidChart/wiki/The-ValueFormatter-interface
