### ISSUE TITLE
Float is not enough for financial data and shows wrong values because it overflows.

### ISSUE THREAD

**Issue by marcosmbbrito** [PhilJay/MPAndroidChart#986]
Hi there, 

Today the financial tester found a bug.
 If the entry Val number has more than 9 algarisms,  like this number 17002232005410, the y val will be 17002232020992 because of the float limitation. 

I did some investigation and found that even double doesn't solve the issue...

                String num="123456789012345678901234567890.23838";
		BigDecimal bign=new BigDecimal(num);
		Double d=Double.parseDouble(num);

BigDecimal shows all the number,  Double doesn't.

Many thanks and continue with this very nice lib, the best! 
I will pay you some drinks soon, you deserve it!

**Comment by xizzhu** [comment]
You can store any object to an `Entry` and use it later:
```java
Entry entry = new Entry(floatValue, xIndex, object);
MyObject myObject = entry.getData();
```

**Comment by marcosmbbrito** [comment]
If I store a BigDecimal in the Entry, how can a make a BarChart with this data:

"dados": [{
		"xvals": "Declarado(CONTRIBUINTE)",
		"total": 17002232005410
	},
	{
		"xvals": "Apurado(DCI) ",
		"total": 5641862609
	}]

Because my barchart is looking like this:
![screenshot_2015-08-27-10-55-33](https://cloud.githubusercontent.com/assets/8974462/9519944/62bf85a2-4caa-11e5-8ee3-a0e0d22ad92c.png)

Thanks in advance

**Comment by xizzhu** [comment]
You can do something like this:
```java
BigDecimal total = "17002232005410";
Entry entry = new Entry(total.floatValue(), xIndex, total);

BarChart barChart = ...
barChart.setMarkerView(new CustomMarkerView(...));
```

Then your `CustomMarkerView`:
```java
public class CustomMarkerView extends MarkerView {
    ...

    @Override
    public void refreshContent(Entry e, Highlight highlight) {
        BigDecimal total = (BigDecimal) e.getData();
        ...
    }
}
```

**Comment by marcosmbbrito** [comment]
Thank you it worked!
 Now I will do some "if case" if the number is Big, to otimize memory in the other cases and hide de label

![screenshot_2015-08-27-11-54-13](https://cloud.githubusercontent.com/assets/8974462/9521076/a231c516-4cb3-11e5-87f4-69be7b3c2b9b.png)

**Comment by PhilJay** [comment]
(y) good solution!

**Comment by hamidchi** [comment]
excuse me i'm using the Pie Chart but I have a same problem
when i set the value to 627050000 the chart shows 627049986
and for 477470000 the chart shows 477470016
i didn't understand your solution for bar chart . can u help me ?
 I also read about ValueFormatter but just confused.
 Thanks in advance

**Comment by almic** [comment]
@hamidchi basically the value was stored inside the entry object, but that doesn't help the x-value. If you are getting this with the x index, then the only real solution is to reduce the number you are working with. Indexes really shouldn't be huge for any reason, because you should be changing them to a proper label. All you can do is figure out how to reduce the size of the number without loosing accuracy.
In the future I would like to add support for using larger numbers without worrying about loss of accuracy, but I can't give you an exact time when that will happen.
