### ISSUE TITLE
Set chart data through adapters

### ISSUE THREAD

**Issue by bogdanzurac** [PhilJay/MPAndroidChart#988]
Hey there guys. We've just recently implemented your library in one of our projects and we're extremely excited about what you've done with it, good job!

The only thing we've found missing is the ability to set the chart data through the years old Android Adapter pattern we're all using for our ListViews, instead of creating separate Entries and DataSets. The reasoning behind this is that you are effectively duplicating the data you already store inside POJOs or cursors inside other adapters in your app. So, for example, if you get your data from a REST API, you're probably going to have an Adapter with an ArrayList of objects. If you store the data inside a ContentProvider, you would probably have a CursorAdapter containing a Cursor with all the data. Do you see where I'm going here? And for every use case like these, the developer would have to pretty much parse the ArrayList of objects, or the Cursor, then copy the data inside an ArrayList of Entries. Depending on the data size, it might even be a performance hit.

What I suggest is not necessarily switching the library to an Adapter-only pattern, but at least providing support for it for the developers that wish to use such a thing.

This would be implemented by providing Adapter interfaces specific to each type of chart. For example, LineChartAdapter, BarChartAdapter, PieChartAdapter, etc. Each adapter would expose the necessary methods that the chart actually requires, for example getSetsCount(), getLineDataValue(int xIndex), getSlicesCount(), etc. By using the Adapter pattern, the chart could also register a DataSetObserver which could call a redraw if notifyDataSetChanged() is called on the adapter subclass, like it already works for regular ListViews.

The main 2 improvements which would arrive with this implementation would be:
1) Removing the possibility of a performance hit for large data sets, due to copying values into a new ArrayList.
2) Much more ease of use from a developer's point of view, considering the Adapter pattern is the most widely used pattern in Android. This is probably the most important part.

Let me know what you guys think of this. Cheers.

**Comment by evgkarasev** [comment]
Agree, that would be extremely useful!

**Comment by PhilJay** [comment]
As a matter of fact, I am already working on something like that (at least similar). It's not the adapter pattern, but I am planning on allowing to feed data to the chart via interfaces.

So what is then possible is that you implement the interface in your model class and will be able to feed the data for the chart directly from your model, without duplicating any data.

**Comment by bogdanzurac** [comment]
@PhilJay Cool. But bear in mind that not all implementations use models. In case of the CursorAdapter, how would the system that you are describing work? That's why I was thinking about using the interface pattern on the Adapter, not on individual models.

Is there by any chance a commit on another branch with this system, where we can take a look at how it works? I'd be interested in checking it out, if it's committed already.

**Comment by djghoshal** [comment]
@PhilJay Hi Phil, so basically you are saying that if I have a same json object to insert as data for multiple charts, will be implementing the interface you are working on!!! Now let me help you with something, there's an app in Play Store called "Spending Tracker" which uses same data for all the charts. Please have a look into the app and share your thoughts. I need some suggestions on charts badly

**Comment by bogdanzurac** [comment]
Has this been implemented? Is there any docs with details on the usage or whatnot?

**Comment by PhilJay** [comment]
Yes!
https://github.com/PhilJay/MPAndroidChart/wiki/Custom-DataSets

**Comment by bogdanzurac** [comment]
I guess it gets the job done in cases where you already have a list of items as POJOs and you could extend them from the base DataSet. However, in case of CursorAdapters, this solves nothing. Furthermore, even in the case I mentioned above, if you data model already extends some other model you have, you're stuck. I don't really think this current approach is flexible enough compared to what I explained in the first post. Is there any reasoning as to why you've taken this route instead?

**Comment by farfromrefug** [comment]
@PhilJay stumble upon this as i have that exact issue.
I have multiple data sets which depend on the same actual data (JSONArray).
It is a huge performance hit to have to create ArrayList and entries for all data of all datasets where a simple adapter would suffice.

Would you be willing to think again about this?
