### ISSUE TITLE
Half Pie chart request

### ISSUE THREAD

**Issue by RonEskinder** [PhilJay/MPAndroidChart#989]
Is there any way to achieve this chart with this library? i have looked in the documentation and didn't find anything, but maybe i am missing something.

Example: 
![k8gkk](https://cloud.githubusercontent.com/assets/2273945/9562871/8fd4bf62-4e35-11e5-99b2-4f548aff3e23.jpg)

**Comment by mseroczynski** [comment]
+1, I would be interested in that too.

**Comment by svangsgaard** [comment]
+1, this would be nice. Although, maybe if it can be done so that you can specify the "gap" in degrees? In the above picure the gapSize, if you will, will be 180.
THAT would be awesome!

**Comment by PhilJay** [comment]
Now available: `pieChart.setMaxAngle(180f)`

````java
    /**
     * Sets the max angle that is used for calculating the pie-circle. 360f means
     * it's a full PieChart, 180f results in a half-pie-chart. Default: 360f
     *
     * @param maxangle min 90, max 360
     */
    public void setMaxAngle(float maxangle);
````

**Comment by sid0893** [comment]
i have imported the project using gradle, but i am not seeing this setMaxAngle function anywhere. How can I use it?

**Comment by PhilJay** [comment]
The feature is already in the latest master commit, but not released yet. That's why you cannot get it via gradle.

**Comment by sid0893** [comment]
so how shall i import it so i can use this feature? or are you planning a
new release soon, then i could continue through gradle..?

thanks!

**Comment by bhunnu** [comment]
how can i add an arrow sign for indication of value in below half pie chart ?
/home/intel/Pictures/HalfPie.jpg

**Comment by srinudkonda** [comment]
Hi, I tried half pie chart but with setMacAngle = 180f. now it shows half but with 90 degree rotation angle of above screenshot, is there anything i am missing here.

**Comment by odaga** [comment]
> Hi, I tried half pie chart but with setMacAngle = 180f. now it shows half but with 90 degree rotation angle of above screenshot, is there anything i am missing here.
I had the same issue. I fixed it by adding 90 degrees counter-clockwise rotation to the view. This can be done by calling pieChart.rotation = -90F.
