### ISSUE TITLE
notifyDataSetChanged does not update when I change the entry value.

### ISSUE THREAD

**Issue by alexmilano** [PhilJay/MPAndroidChart#990]
Hi!

I tried to update an BarEntry entry with entry.setVal(value);
Then, I call notifyDataSetChanged, but the getYValueSum() is still the same! I see that the sum value is the original, so when I update only an entry, the sum is not really sum the all updated entries.

**Comment by PhilJay** [comment]
Did you call notifyDataSetChanged on the data object, or on the chart?
