### ISSUE TITLE
how can i show the specified values on xAxis   (Candlestickchart)

### ISSUE THREAD

**Issue by uuttxtgyf** [PhilJay/MPAndroidChart#991]
for example ,there are "Date Strings" from "20150101" to "20150304" (20150101 20150102 ...20150201 20150202 ......20150304), i only want to show  "20150101","20150201" and "20150301"  on the xAxis,how can i do this

**Comment by droiddevgirl** [comment]
You just add empty string "" in List<String> for detail you can see my issue on https://github.com/PhilJay/MPAndroidChart/issues/905 it's work for me but in your case doesn't need grouping just show selected date, hope it's help

**Comment by uuttxtgyf** [comment]
@droiddevgirl  thank you very much

**Comment by uuttxtgyf** [comment]
@PhilJay  thank you very much
