### ISSUE TITLE
Feature request: align left and right scale zero line

### ISSUE THREAD

**Issue by beegee-tokyo** [PhilJay/MPAndroidChart#992]
See: http://stackoverflow.com/questions/32092147/mpandroid-multi-line-chart-align-0-line-of-left-and-right-scale</br>

I have a multi line chart with 3 datasets. dataset 1 & 2 use the left side scale, the 3rd one uses the right side scale. Values of first 2 datasets are between -300W and +2500W, the values of the 3rd dataset are between 0 and 7000lux.</br>

How can I align the 0 position of the left and right scale?</br>

That is what I get right now: </br>
![screenshot_2015-08-19-17-39-41](https://cloud.githubusercontent.com/assets/512690/9571042/0911184a-4fca-11e5-94ce-37b51601ee09.png)</br>
The 0 line of the green plot is at -500 of the others. The data changes dynamically, so I cannot set a fixed offset for the green plot.

Anybody knows how to do this? I didn't find anything in the MPAndroid documentation.

**Comment by Scrounger** [comment]
Hi @PhilJay,
i came across the same problem. Tried to solve this trough setOffset, set min/max for the right Axise, but without succes.
Is this generally impossible?
Please tell me the trick or great woulb be to have such a feature implemented.

regards
Scrounger

**Comment by beegee-tokyo** [comment]
No solution for my me yet. I just gave up with on the right side scale.

**Comment by PhilJay** [comment]
The `setAxisDependency(...)` method provided by the `DataSet` class lets you choose which axis your data should be plotted against.

Here is an example where one dataset is plotted against the left and the other dataset is plotted against the right axis: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/LineChartActivity2.java

**Comment by Scrounger** [comment]
@PhilJay
Thynks for the answer. But thats not my question. As @beegee-tokyo described in his first post, we looking foward to have the zero value on the left and the right axis at same level / value (one common horizontal zero line).
