### ISSUE TITLE
Feature request: for supporting SpannableString 

### ISSUE THREAD

**Issue by ShrutiD** [PhilJay/MPAndroidChart#993]
I am working on a PieChart, and i needed to pass a SpannableString for, 
`objPieChart.setCenterText(String);` which is not available. Is it possible to support  such strings too?
Thanks!

**Comment by eastwoodwang** [comment]
i have the same request for display the different color and font size in PieChart center text, Need you guide about it, thanks.

**Comment by eastwoodwang** [comment]
thanks for enhance the codes and i had changed the source codes and
generate the class to replace them in the jar.

2015-10-11 22:49 GMT+08:00 Philipp Jahoda <notifications@github.com>:
