### ISSUE TITLE
MPAndroidChart Line Chart size issue

### ISSUE THREAD

**Issue by imkharlo** [PhilJay/MPAndroidChart#994]
![screenshot_2015-09-01-00-13-02 1](https://cloud.githubusercontent.com/assets/14058323/9583905/5bdeade6-5040-11e5-9a35-ab3bd51b830e.png)

I'm trying to create a line chart, but after the customization of the chart that I got from youtube it just became like this, the chart is very small. Please help me ASAP THANK YOU VERY MUCH

**Comment by droiddevgirl** [comment]
You can try to set height manual (ex: 200dp) and do not use wrap_content

**Comment by imkharlo** [comment]
But I'm using match_parent

**Comment by danielius59** [comment]
I am having the same problem while doing this on Fragment. The layout has match_parent`s.

**Comment by danielius59** [comment]
http://stackoverflow.com/a/32362569/2579075
