### ISSUE TITLE
Disable vertical line on XAxis

### ISSUE THREAD

**Issue by droiddevgirl** [PhilJay/MPAndroidChart#998]
Hi PhilJay, i was submit issue https://github.com/PhilJay/MPAndroidChart/issues/905 and it's working, but now i want to ask how can i disable the vertical line that contain empty string "", because for now my graph looks like this, the vertical line looks too much :  
![screen shot 2015-09-03 at 10 09 02 am](https://cloud.githubusercontent.com/assets/1728863/9649830/79f80076-5224-11e5-901b-d1bfa31de981.png)

**Comment by PhilJay** [comment]
`xAxis.setDrawAxisLine(false)`

**Comment by droiddevgirl** [comment]
hi philjay, actually i've found the answer, i'm try to create custom XAxisRenderer and i override renderAxisLine function and checking if label from mAxis is NOT empty then draw line, anyway thanks for your reply :smile:
