### ISSUE TITLE
No equal spacing between labels.

### ISSUE THREAD

**Issue by despDev** [PhilJay/MPAndroidChart#999]
I have tried to solve this for hours. I can't make labels to have an equal spacing.
![ask_pic_1](https://cloud.githubusercontent.com/assets/9020678/9650351/6ab3c6d2-520a-11e5-9642-db07ead4e21d.jpg)
When setAvoidFirstLastClipping(false) I get this:
![ask_pic_2](https://cloud.githubusercontent.com/assets/9020678/9650363/7fce5e06-520a-11e5-8547-e2fd751c1537.jpg)
It seems like spacing now is equal and as you can see only label 1 has shifted, others two didn't move a bit. I also played with getXAxis().setSpaceBetweenLabels(10); The best outcome was.
![ask_pic_3](https://cloud.githubusercontent.com/assets/9020678/9650365/86f31ad2-520a-11e5-98fe-5e8221b93869.jpg)
Moreover the position of second and third label is different every time and depends on entries quantity.

**Comment by PhilJay** [comment]
Your labels are pretty long. And you cant have both equal spacing between all labels and still expect no label to exceed the bounds of the drawing area. The reason for that is that depending on the zoom level, a specific amount of labels is "skipped".
